VRCapstoneGames: Oculus.Platform.Samples.VrBoardGame.MatchmakingManager Class Reference
Oculus.Platform.Samples.VrBoardGame.MatchmakingManager Class Reference
Public Member Functions
void MatchButtonPressed ()
void EndMatch (int localScore, int remoteScore)
void SendLocalMove (GamePiece.Piece piece, int boardX, int boardY)
Member Function Documentation
EndMatch()
void Oculus.Platform.Samples.VrBoardGame.MatchmakingManager.EndMatch (int localScore, int remoteScore)
Referenced by Oculus.Platform.Samples.VrBoardGame.GameController.PracticeButtonPressed(), and Oculus.Platform.Samples.VrBoardGame.GameController.RemoteMatchEnded().
MatchButtonPressed()
void Oculus.Platform.Samples.VrBoardGame.MatchmakingManager.MatchButtonPressed ()
SendLocalMove()
void Oculus.Platform.Samples.VrBoardGame.MatchmakingManager.SendLocalMove (GamePiece::Piece piece, int boardX, int boardY)
Referenced by Oculus.Platform.Samples.VrBoardGame.GameController.TryPlacePiece().
The documentation for this class was generated from the following file:
C:/Users/Lykos/Desktop/Projects/Capstone/VRGames/Assets/ThirdParty/Oculus/Platform/Samples/VrBoardGame/Scripts/MatchmakingManager.cs