VRCapstoneGames: Oculus.Interaction.HandPosing.SnapSurfaces.BoxSurface Class Reference
Oculus.Interaction.HandPosing.SnapSurfaces.BoxSurface Class Reference
This SnapSurface defines a Rectangle around which the grip point is valid. Since the grip point might be offset from the fingers, a valid range for each opposite side of the rectangle can be set so the grabbing fingers are constrained to the object bounds.
Public Member Functions
Pose MirrorPose (in Pose pose)
Method for mirroring a Pose around the surface. Different surfaces will prefer mirroring along different axis.
ISnapSurface CreateMirroredSurface (GameObject gameObject)
Creates a new ISnapSurface under the selected gameobject that is a mirror version of the current.
ISnapSurface CreateDuplicatedSurface (GameObject gameObject)
Creates a new ISnapSurface under the selected gameobject with the same data as this one.
float CalculateBestPoseAtSurface (in Pose targetPose, in Pose reference, out Pose bestPose, in PoseMeasureParameters scoringModifier)
Finds the Pose at the surface that is the closest to the given pose.
bool CalculateBestPoseAtSurface (Ray targetRay, in Pose recordedPose, out Pose bestPose)
Finds the Pose at the surface that is the closest to the given ray.
void InjectAllBoxSurface (BoxSurfaceData data, Transform relativeTo, Transform gripPoint)
void InjectData (BoxSurfaceData data)
void InjectRelativeTo (Transform relativeTo)
void InjectGripPoint (Transform gripPoint)
Protected Member Functions
virtual void Start ()
Vector3 NearestPointInSurface (Vector3 targetPosition)
Pose MinimalRotationPoseAtSurface (in Pose userPose, in Pose snapPose)
Pose MinimalTranslationPoseAtSurface (in Pose userPose, in Pose snapPose)
Quaternion RotateUp (Quaternion baseRot, float angle)
Protected Attributes
BoxSurfaceData _data = new BoxSurfaceData()
Properties
BoxSurfaceData Data [get, set]
Getter for the data-only version of this surface. Used so it can be stored when created at Play-Mode.
Transform RelativeTo [get, set]
Transform to which the surface refers to.
Transform GripPoint [get, set]
Valid point at which the hand can snap, typically the SnapPoint position itself.
float WidthOffset [get, set]
The lateral displacement of the grip point in the main side.
Vector4 SnapOffset [get, set]
The range at which the sides are constrained. X,Y for the back and forward sides range. Z,W for the left and right sides range.
Vector3 Size [get, set]
The size of the rectangle. Y is ignored.
Quaternion Rotation [get, set]
The rotation of the rectangle from the Grip point.
Vector3 Direction [get]
The forward direction of the rectangle (based on its rotation)
Detailed Description
This SnapSurface defines a Rectangle around which the grip point is valid. Since the grip point might be offset from the fingers, a valid range for each opposite side of the rectangle can be set so the grabbing fingers are constrained to the object bounds.
Member Function Documentation
CalculateBestPoseAtSurface() [1/2]
float Oculus.Interaction.HandPosing.SnapSurfaces.BoxSurface.CalculateBestPoseAtSurface (in Pose targetPose, in Pose reference, out Pose bestPose, in PoseMeasureParameters scoringModifier)
Finds the Pose at the surface that is the closest to the given pose.
Parameters
targetPose The pose to find the nearest to.
reference The reference snap point to use for measuring at the surface.
bestPose The best found pose at the surface.<
Returns
The score indicating how good the found pose was, -1 for invalid result.
Implements Oculus.Interaction.HandPosing.SnapSurfaces.ISnapSurface.
CalculateBestPoseAtSurface() [2/2]
bool Oculus.Interaction.HandPosing.SnapSurfaces.BoxSurface.CalculateBestPoseAtSurface (Ray targetRay, in Pose reference, out Pose bestPose)
Finds the Pose at the surface that is the closest to the given ray.
Parameters
targetRay Ray searching for the nearest snap pose
reference The reference snap point to use for measuring at the surface.
bestPose The best found pose at the surface.
Returns
True if the pose was found
Implements Oculus.Interaction.HandPosing.SnapSurfaces.ISnapSurface.
CreateDuplicatedSurface()
ISnapSurface Oculus.Interaction.HandPosing.SnapSurfaces.BoxSurface.CreateDuplicatedSurface (GameObject gameObject)
Creates a new ISnapSurface under the selected gameobject with the same data as this one.
Parameters
gameObject The gameobject in which to place the new ISnapSurface.
Returns
A clone of this ISnapSurface.
Implements Oculus.Interaction.HandPosing.SnapSurfaces.ISnapSurface.
CreateMirroredSurface()
ISnapSurface Oculus.Interaction.HandPosing.SnapSurfaces.BoxSurface.CreateMirroredSurface (GameObject gameObject)
Creates a new ISnapSurface under the selected gameobject that is a mirror version of the current.
Parameters
gameObject The gameobject in which to place the new ISnapSurface.
Returns
A mirror of this ISnapSurface.
Implements Oculus.Interaction.HandPosing.SnapSurfaces.ISnapSurface.
InjectAllBoxSurface()
void Oculus.Interaction.HandPosing.SnapSurfaces.BoxSurface.InjectAllBoxSurface (BoxSurfaceData data, Transform relativeTo, Transform gripPoint)
InjectData()
void Oculus.Interaction.HandPosing.SnapSurfaces.BoxSurface.InjectData (BoxSurfaceData data)
Referenced by Oculus.Interaction.HandPosing.SnapSurfaces.BoxSurface.InjectAllBoxSurface().
InjectGripPoint()
void Oculus.Interaction.HandPosing.SnapSurfaces.BoxSurface.InjectGripPoint (Transform gripPoint)
Referenced by Oculus.Interaction.HandPosing.SnapSurfaces.BoxSurface.InjectAllBoxSurface().
InjectRelativeTo()
void Oculus.Interaction.HandPosing.SnapSurfaces.BoxSurface.InjectRelativeTo (Transform relativeTo)
Referenced by Oculus.Interaction.HandPosing.SnapSurfaces.BoxSurface.InjectAllBoxSurface().
MinimalRotationPoseAtSurface()
Pose Oculus.Interaction.HandPosing.SnapSurfaces.BoxSurface.MinimalRotationPoseAtSurface (in Pose userPose, in Pose snapPose) protected
Referenced by Oculus.Interaction.HandPosing.SnapSurfaces.BoxSurface.CalculateBestPoseAtSurface().
MinimalTranslationPoseAtSurface()
Pose Oculus.Interaction.HandPosing.SnapSurfaces.BoxSurface.MinimalTranslationPoseAtSurface (in Pose userPose, in Pose snapPose) protected
Referenced by Oculus.Interaction.HandPosing.SnapSurfaces.BoxSurface.CalculateBestPoseAtSurface(), and Oculus.Interaction.HandPosing.SnapSurfaces.BoxSurface.CalculateBestPoseAtSurface().
MirrorPose()
Pose Oculus.Interaction.HandPosing.SnapSurfaces.BoxSurface.MirrorPose (in Pose gripPose)
Method for mirroring a Pose around the surface. Different surfaces will prefer mirroring along different axis.
Parameters
gripPose The Pose to be mirrored.
Returns
A new pose mirrored at this surface.
Implements Oculus.Interaction.HandPosing.SnapSurfaces.ISnapSurface.
NearestPointInSurface()
Vector3 Oculus.Interaction.HandPosing.SnapSurfaces.BoxSurface.NearestPointInSurface (Vector3 targetPosition) protected
Referenced by Oculus.Interaction.HandPosing.SnapSurfaces.BoxSurface.CalculateBestPoseAtSurface().
RotateUp()
Quaternion Oculus.Interaction.HandPosing.SnapSurfaces.BoxSurface.RotateUp (Quaternion baseRot, float angle) protected
Referenced by Oculus.Interaction.HandPosing.SnapSurfaces.BoxSurface.MinimalTranslationPoseAtSurface().
Start()
virtual void Oculus.Interaction.HandPosing.SnapSurfaces.BoxSurface.Start () protected virtual
Member Data Documentation
_data
BoxSurfaceData Oculus.Interaction.HandPosing.SnapSurfaces.BoxSurface._data = new BoxSurfaceData() protected
Referenced by Oculus.Interaction.HandPosing.SnapSurfaces.BoxSurface.CreateDuplicatedSurface(), Oculus.Interaction.HandPosing.SnapSurfaces.BoxSurface.CreateMirroredSurface(), Oculus.Interaction.HandPosing.SnapSurfaces.BoxSurface.InjectData(), and Oculus.Interaction.HandPosing.SnapSurfaces.BoxSurface.Start().
Property Documentation
Data
BoxSurfaceData Oculus.Interaction.HandPosing.SnapSurfaces.BoxSurface.Data get set
Getter for the data-only version of this surface. Used so it can be stored when created at Play-Mode.
Direction
Vector3 Oculus.Interaction.HandPosing.SnapSurfaces.BoxSurface.Direction get
The forward direction of the rectangle (based on its rotation)
Referenced by Oculus.Interaction.HandPosing.SnapSurfaces.BoxSurface.MirrorPose().
GripPoint
Transform Oculus.Interaction.HandPosing.SnapSurfaces.BoxSurface.GripPoint get set
Valid point at which the hand can snap, typically the SnapPoint position itself.
RelativeTo
Transform Oculus.Interaction.HandPosing.SnapSurfaces.BoxSurface.RelativeTo get set
Transform to which the surface refers to.
Referenced by Oculus.Interaction.HandPosing.SnapSurfaces.BoxSurface.MirrorPose().
Rotation
Quaternion Oculus.Interaction.HandPosing.SnapSurfaces.BoxSurface.Rotation get set
The rotation of the rectangle from the Grip point.
Referenced by Oculus.Interaction.HandPosing.SnapSurfaces.BoxSurface.CalculateBestPoseAtSurface(), Oculus.Interaction.HandPosing.SnapSurfaces.BoxSurface.MinimalRotationPoseAtSurface(), Oculus.Interaction.HandPosing.SnapSurfaces.BoxSurface.MirrorPose(), and Oculus.Interaction.HandPosing.SnapSurfaces.BoxSurface.RotateUp().
Size
Vector3 Oculus.Interaction.HandPosing.SnapSurfaces.BoxSurface.Size get set
The size of the rectangle. Y is ignored.
SnapOffset
Vector4 Oculus.Interaction.HandPosing.SnapSurfaces.BoxSurface.SnapOffset get set
The range at which the sides are constrained. X,Y for the back and forward sides range. Z,W for the left and right sides range.
Referenced by Oculus.Interaction.HandPosing.SnapSurfaces.BoxSurface.MinimalRotationPoseAtSurface().
WidthOffset
float Oculus.Interaction.HandPosing.SnapSurfaces.BoxSurface.WidthOffset get set
The lateral displacement of the grip point in the main side.
The documentation for this class was generated from the following file:
C:/Users/Lykos/Desktop/Projects/Capstone/VRGames/Assets/ThirdParty/Oculus/Interaction/Runtime/Scripts/HandPosing/SnapSurfaces/BoxSurface.cs