VRCapstoneGames: Oculus.Interaction.HandPosing.SnapSurfaces.CylinderSurfaceData Class Reference
Oculus.Interaction.HandPosing.SnapSurfaces.CylinderSurfaceData Class Reference
Public Member Functions
object Clone ()
CylinderSurfaceData Mirror ()
Public Attributes
Vector3 startPoint = new Vector3(0f, 0.1f, 0f)
Vector3 endPoint = new Vector3(0f, -0.1f, 0f)
float angle = 120f
Member Function Documentation
Clone()
object Oculus.Interaction.HandPosing.SnapSurfaces.CylinderSurfaceData.Clone ()
Referenced by Oculus.Interaction.HandPosing.SnapSurfaces.CylinderSurfaceData.Mirror().
Mirror()
CylinderSurfaceData Oculus.Interaction.HandPosing.SnapSurfaces.CylinderSurfaceData.Mirror ()
Referenced by Oculus.Interaction.HandPosing.SnapSurfaces.CylinderSurface.CreateMirroredSurface().
Member Data Documentation
angle
float Oculus.Interaction.HandPosing.SnapSurfaces.CylinderSurfaceData.angle = 120f
Referenced by Oculus.Interaction.HandPosing.SnapSurfaces.CylinderSurfaceData.Clone().
endPoint
Vector3 Oculus.Interaction.HandPosing.SnapSurfaces.CylinderSurfaceData.endPoint = new Vector3(0f, -0.1f, 0f)
Referenced by Oculus.Interaction.HandPosing.SnapSurfaces.CylinderSurfaceData.Clone().
startPoint
Vector3 Oculus.Interaction.HandPosing.SnapSurfaces.CylinderSurfaceData.startPoint = new Vector3(0f, 0.1f, 0f)
Referenced by Oculus.Interaction.HandPosing.SnapSurfaces.CylinderSurfaceData.Clone().
The documentation for this class was generated from the following file:
C:/Users/Lykos/Desktop/Projects/Capstone/VRGames/Assets/ThirdParty/Oculus/Interaction/Runtime/Scripts/HandPosing/SnapSurfaces/CylinderSurface.cs