VRCapstoneGames: UnityEngine.ProBuilder.BezierShape Class Reference
UnityEngine.ProBuilder.BezierShape Class Reference sealed
Public Member Functions
void Init ()
Initialize the points list with a default set.
void Refresh ()
Rebuild the ProBuilderMesh with the extruded spline.
Public Attributes
List< BezierPoint > points = new List<BezierPoint>()
bool closeLoop = false
float radius = .5f
int rows = 8
int columns = 16
bool smooth = true
Properties
bool isEditing [get, set]
ProBuilderMesh mesh [get, set]
Member Function Documentation
Init()
void UnityEngine.ProBuilder.BezierShape.Init ()
Initialize the points list with a default set.
Referenced by UnityEditor.ProBuilder.BezierShapeEditor.OnInspectorGUI(), and UnityEditor.ProBuilder.Actions.NewBezierShape.PerformActionImplementation().
Refresh()
void UnityEngine.ProBuilder.BezierShape.Refresh ()
Rebuild the ProBuilderMesh with the extruded spline.
Member Data Documentation
closeLoop
bool UnityEngine.ProBuilder.BezierShape.closeLoop = false
Referenced by UnityEngine.ProBuilder.BezierShape.Refresh().
columns
int UnityEngine.ProBuilder.BezierShape.columns = 16
Referenced by UnityEngine.ProBuilder.BezierShape.Refresh().
points
List<BezierPoint> UnityEngine.ProBuilder.BezierShape.points = new List<BezierPoint>()
Referenced by UnityEngine.ProBuilder.BezierShape.Init(), and UnityEngine.ProBuilder.BezierShape.Refresh().
radius
float UnityEngine.ProBuilder.BezierShape.radius = .5f
Referenced by UnityEngine.ProBuilder.BezierShape.Refresh().
rows
int UnityEngine.ProBuilder.BezierShape.rows = 8
Referenced by UnityEngine.ProBuilder.BezierShape.Refresh().
smooth
bool UnityEngine.ProBuilder.BezierShape.smooth = true
Referenced by UnityEngine.ProBuilder.BezierShape.Refresh().
Property Documentation
isEditing
bool UnityEngine.ProBuilder.BezierShape.isEditing get set
mesh
ProBuilderMesh UnityEngine.ProBuilder.BezierShape.mesh get set
Referenced by UnityEngine.ProBuilder.BezierShape.Refresh().
The documentation for this class was generated from the following file:
C:/Users/Lykos/Desktop/Projects/Capstone/VRGames/Library/PackageCache/com.unity.probuilder@5.0.6/Runtime/Core/BezierShape.cs