VRGames: Oculus.Interaction.PoseDetection.Editor.FeatureListPropertyDrawer Class Reference
Oculus.Interaction.PoseDetection.Editor.FeatureListPropertyDrawer Class Reference abstract
Public Member Functions
override float GetPropertyHeight (SerializedProperty property, GUIContent label)
override bool CanCacheInspectorGUI (SerializedProperty property)
override void OnGUI (Rect drawerPos, SerializedProperty property, GUIContent label)
Protected Member Functions
virtual FeatureStateActiveMode[] GetAllowedModes (FeatureConfig model)
Enum FlagsToEnum (uint flags)
uint EnumToFlags (Enum flags)
string FeatureToString (int featureIdx)
FeatureStateDescription[] GetStatesForFeature (int featureIdx)
Model.FeatureConfigList CreateModel (SerializedProperty property)
Properties
float ControlLineHeight [get]
float BottomMargin [get]
Member Function Documentation
CanCacheInspectorGUI()
override bool Oculus.Interaction.PoseDetection.Editor.FeatureListPropertyDrawer.CanCacheInspectorGUI (SerializedProperty property)
CreateModel()
Model.FeatureConfigList Oculus.Interaction.PoseDetection.Editor.FeatureListPropertyDrawer.CreateModel (SerializedProperty property) abstract protected
Referenced by Oculus.Interaction.PoseDetection.Editor.FeatureListPropertyDrawer.GetPropertyHeight(), and Oculus.Interaction.PoseDetection.Editor.FeatureListPropertyDrawer.OnGUI().
EnumToFlags()
uint Oculus.Interaction.PoseDetection.Editor.FeatureListPropertyDrawer.EnumToFlags (Enum flags) abstract protected
FeatureToString()
string Oculus.Interaction.PoseDetection.Editor.FeatureListPropertyDrawer.FeatureToString (int featureIdx) abstract protected
FlagsToEnum()
Enum Oculus.Interaction.PoseDetection.Editor.FeatureListPropertyDrawer.FlagsToEnum (uint flags) abstract protected
GetAllowedModes()
virtual FeatureStateActiveMode[] Oculus.Interaction.PoseDetection.Editor.FeatureListPropertyDrawer.GetAllowedModes (FeatureConfig model) protected virtual
GetPropertyHeight()
override float Oculus.Interaction.PoseDetection.Editor.FeatureListPropertyDrawer.GetPropertyHeight (SerializedProperty property, GUIContent label)
GetStatesForFeature()
FeatureStateDescription[] Oculus.Interaction.PoseDetection.Editor.FeatureListPropertyDrawer.GetStatesForFeature (int featureIdx) abstract protected
Referenced by Oculus.Interaction.PoseDetection.Editor.FeatureListPropertyDrawer.GetAllowedModes().
OnGUI()
override void Oculus.Interaction.PoseDetection.Editor.FeatureListPropertyDrawer.OnGUI (Rect drawerPos, SerializedProperty property, GUIContent label)
Property Documentation
BottomMargin
float Oculus.Interaction.PoseDetection.Editor.FeatureListPropertyDrawer.BottomMargin get
Referenced by Oculus.Interaction.PoseDetection.Editor.FeatureListPropertyDrawer.GetPropertyHeight().
ControlLineHeight
float Oculus.Interaction.PoseDetection.Editor.FeatureListPropertyDrawer.ControlLineHeight get
Referenced by Oculus.Interaction.PoseDetection.Editor.FeatureListPropertyDrawer.GetPropertyHeight().
The documentation for this class was generated from the following file:
C:/Users/Lykos/Desktop/Projects/Capstone/VRGames/Assets/ThirdParty/Oculus/Interaction/Editor/PoseDetection/FeatureListPropertyDrawer.cs