VRCapstoneGames: Oculus.Interaction.Interactable< TInteractor, TInteractable > Class Template Reference
Oculus.Interaction.Interactable< TInteractor, TInteractable > Class Template Reference abstract
Interactable provides a base template for any kind of interactable object. An Interactable can have Hover and HandleSelected Interactor(s) acting on it. Concrete Interactables can define whether they have a One-to-One or One-to-Many relationship with their associated concrete Interactors.
Public Member Functions
void AddInteractor (TInteractor interactor)
void RemoveInteractor (TInteractor interactor)
void AddSelectingInteractor (TInteractor interactor)
void RemoveSelectingInteractor (TInteractor interactor)
bool CanBeSelectedBy (TInteractor interactor)
bool HasInteractor (TInteractor interactor)
bool HasSelectingInteractor (TInteractor interactor)
void Enable ()
void Disable ()
void RemoveInteractorById (int id)
Protected Member Functions
virtual void InteractorAdded (TInteractor interactor)
virtual void InteractorRemoved (TInteractor interactor)
virtual void SelectingInteractorAdded (TInteractor interactor)
virtual void SelectingInteractorRemoved (TInteractor interactor)
virtual void OnEnable ()
virtual void OnDisable ()
virtual void SetRegistry (IInteractableRegistry< TInteractor, TInteractable > registry)
Properties
int MaxInteractors [get, set]
int MaxSelectingInteractors [get, set]
MAction< TInteractor > WhenInteractorAdded [get]
MAction< TInteractor > WhenInteractorRemoved [get]
MAction< TInteractor > WhenSelectingInteractorAdded [get]
MAction< TInteractor > WhenSelectingInteractorRemoved [get]
InteractableState State [get]
static IInteractableRegistry< TInteractor, TInteractable > Registry [get]
int InteractorsCount [get]
int SelectingInteractorsCount [get]
IEnumerable< TInteractor > Interactors [get]
IEnumerable< TInteractor > SelectingInteractors [get]
Properties inherited from Oculus.Interaction.IInteractable< TInteractor >
Properties inherited from Oculus.Interaction.IInteractableView< out TInteractor >
Properties inherited from Oculus.Interaction.IComponent
GameObject gameObject [get]
Properties inherited from Oculus.Interaction.IInteractableView< TInteractor >
InteractableState State [get]
int MaxInteractors [get]
int MaxSelectingInteractors [get]
int InteractorsCount [get]
int SelectingInteractorsCount [get]
IEnumerable< TInteractor > Interactors [get]
IEnumerable< TInteractor > SelectingInteractors [get]
MAction< TInteractor > WhenInteractorAdded [get]
MAction< TInteractor > WhenInteractorRemoved [get]
MAction< TInteractor > WhenSelectingInteractorAdded [get]
MAction< TInteractor > WhenSelectingInteractorRemoved [get]
Events
Action WhenInteractorsCountUpdated = delegate { }
Action WhenSelectingInteractorsCountUpdated = delegate { }
Action< InteractableStateChangeArgs > WhenStateChanged = delegate { }
Events inherited from Oculus.Interaction.IInteractableView< out TInteractor >
Action< InteractableStateChangeArgs > WhenStateChanged
Action WhenInteractorsCountUpdated
Action WhenSelectingInteractorsCountUpdated
Events inherited from Oculus.Interaction.IInteractableView< TInteractor >
Action< InteractableStateChangeArgs > WhenStateChanged
Action WhenInteractorsCountUpdated
Action WhenSelectingInteractorsCountUpdated
Detailed Description
Interactable provides a base template for any kind of interactable object. An Interactable can have Hover and HandleSelected Interactor(s) acting on it. Concrete Interactables can define whether they have a One-to-One or One-to-Many relationship with their associated concrete Interactors.
Type Constraints
TInteractor : class
TInteractor : IInteractor<TInteractable>
TInteractable : Interactable
TInteractable : TInteractor
TInteractable : TInteractable
Member Function Documentation
AddInteractor()
void Oculus.Interaction.Interactable< TInteractor, TInteractable >.AddInteractor (TInteractor interactor)
Implements Oculus.Interaction.IInteractable< TInteractor >.
AddSelectingInteractor()
void Oculus.Interaction.Interactable< TInteractor, TInteractable >.AddSelectingInteractor (TInteractor interactor)
Implements Oculus.Interaction.IInteractable< TInteractor >.
CanBeSelectedBy()
bool Oculus.Interaction.Interactable< TInteractor, TInteractable >.CanBeSelectedBy (TInteractor interactor)
Implements Oculus.Interaction.IInteractable< TInteractor >.
Disable()
void Oculus.Interaction.Interactable< TInteractor, TInteractable >.Disable ()
Implements Oculus.Interaction.IInteractable< TInteractor >.
Referenced by Oculus.Interaction.Interactable< TInteractor, TInteractable >.OnDisable().
Enable()
void Oculus.Interaction.Interactable< TInteractor, TInteractable >.Enable ()
Implements Oculus.Interaction.IInteractable< TInteractor >.
Referenced by Oculus.Interaction.Interactable< TInteractor, TInteractable >.OnEnable().
HasInteractor()
bool Oculus.Interaction.Interactable< TInteractor, TInteractable >.HasInteractor (TInteractor interactor)
Implements Oculus.Interaction.IInteractable< TInteractor >.
HasSelectingInteractor()
bool Oculus.Interaction.Interactable< TInteractor, TInteractable >.HasSelectingInteractor (TInteractor interactor)
Implements Oculus.Interaction.IInteractable< TInteractor >.
InteractorAdded()
virtual void Oculus.Interaction.Interactable< TInteractor, TInteractable >.InteractorAdded (TInteractor interactor) protected virtual
Referenced by Oculus.Interaction.Interactable< TInteractor, TInteractable >.AddInteractor().
InteractorRemoved()
virtual void Oculus.Interaction.Interactable< TInteractor, TInteractable >.InteractorRemoved (TInteractor interactor) protected virtual
Referenced by Oculus.Interaction.Interactable< TInteractor, TInteractable >.RemoveInteractor().
OnDisable()
virtual void Oculus.Interaction.Interactable< TInteractor, TInteractable >.OnDisable () protected virtual
Reimplemented in Oculus.Interaction.GrabInteractable, Oculus.Interaction.HandPosing.HandGrabInteractable, Oculus.Interaction.PokeInteractable, and Oculus.Interaction.RayInteractable.
OnEnable()
virtual void Oculus.Interaction.Interactable< TInteractor, TInteractable >.OnEnable () protected virtual
Reimplemented in Oculus.Interaction.GrabInteractable, Oculus.Interaction.HandPosing.HandGrabInteractable, Oculus.Interaction.PokeInteractable, and Oculus.Interaction.RayInteractable.
RemoveInteractor()
void Oculus.Interaction.Interactable< TInteractor, TInteractable >.RemoveInteractor (TInteractor interactor)
Implements Oculus.Interaction.IInteractable< TInteractor >.
Referenced by Oculus.Interaction.Interactable< TInteractor, TInteractable >.Disable(), and Oculus.Interaction.Interactable< TInteractor, TInteractable >.RemoveInteractorById().
RemoveInteractorById()
void Oculus.Interaction.Interactable< TInteractor, TInteractable >.RemoveInteractorById (int id)
Implements Oculus.Interaction.IInteractable< TInteractor >.
RemoveSelectingInteractor()
void Oculus.Interaction.Interactable< TInteractor, TInteractable >.RemoveSelectingInteractor (TInteractor interactor)
Implements Oculus.Interaction.IInteractable< TInteractor >.
Referenced by Oculus.Interaction.Interactable< TInteractor, TInteractable >.Disable(), and Oculus.Interaction.Interactable< TInteractor, TInteractable >.RemoveInteractorById().
SelectingInteractorAdded()
virtual void Oculus.Interaction.Interactable< TInteractor, TInteractable >.SelectingInteractorAdded (TInteractor interactor) protected virtual
Referenced by Oculus.Interaction.Interactable< TInteractor, TInteractable >.AddSelectingInteractor().
SelectingInteractorRemoved()
virtual void Oculus.Interaction.Interactable< TInteractor, TInteractable >.SelectingInteractorRemoved (TInteractor interactor) protected virtual
Referenced by Oculus.Interaction.Interactable< TInteractor, TInteractable >.RemoveSelectingInteractor().
SetRegistry()
virtual void Oculus.Interaction.Interactable< TInteractor, TInteractable >.SetRegistry (IInteractableRegistry< TInteractor, TInteractable< TInteractor, TInteractable > > registry) protected virtual
Property Documentation
Interactors
IEnumerable<TInteractor> Oculus.Interaction.Interactable< TInteractor, TInteractable >.Interactors get
Implements Oculus.Interaction.IInteractableView< out TInteractor >.
InteractorsCount
int Oculus.Interaction.Interactable< TInteractor, TInteractable >.InteractorsCount get
Implements Oculus.Interaction.IInteractableView< out TInteractor >.
Referenced by Oculus.Interaction.Interactable< TInteractor, TInteractable >.CanBeSelectedBy().
MaxInteractors
int Oculus.Interaction.Interactable< TInteractor, TInteractable >.MaxInteractors get set
Implements Oculus.Interaction.IInteractable< TInteractor >.
Referenced by Oculus.Interaction.Interactable< TInteractor, TInteractable >.CanBeSelectedBy().
MaxSelectingInteractors
int Oculus.Interaction.Interactable< TInteractor, TInteractable >.MaxSelectingInteractors get set
Implements Oculus.Interaction.IInteractable< TInteractor >.
Referenced by Oculus.Interaction.Interactable< TInteractor, TInteractable >.CanBeSelectedBy().
Registry
IInteractableRegistry<TInteractor, TInteractable> Oculus.Interaction.Interactable< TInteractor, TInteractable >.Registry static get
Referenced by Oculus.Interaction.HandPosing.HandGrabInteractor.ComputeBestSnapAddress(), Oculus.Interaction.GrabInteractor.ComputeCandidate(), and Oculus.Interaction.RayInteractor.ComputeCandidate().
SelectingInteractors
IEnumerable<TInteractor> Oculus.Interaction.Interactable< TInteractor, TInteractable >.SelectingInteractors get
Implements Oculus.Interaction.IInteractableView< out TInteractor >.
SelectingInteractorsCount
int Oculus.Interaction.Interactable< TInteractor, TInteractable >.SelectingInteractorsCount get
Implements Oculus.Interaction.IInteractableView< out TInteractor >.
Referenced by Oculus.Interaction.Interactable< TInteractor, TInteractable >.CanBeSelectedBy().
State
InteractableState Oculus.Interaction.Interactable< TInteractor, TInteractable >.State get
Implements Oculus.Interaction.IInteractableView< out TInteractor >.
Referenced by Oculus.Interaction.Interactable< TInteractor, TInteractable >.CanBeSelectedBy(), Oculus.Interaction.Interactable< TInteractor, TInteractable >.Disable(), Oculus.Interaction.Interactable< TInteractor, TInteractable >.Enable(), and Oculus.Interaction.Interactable< TInteractor, TInteractable >.RemoveInteractorById().
WhenInteractorAdded
MAction<TInteractor> Oculus.Interaction.Interactable< TInteractor, TInteractable >.WhenInteractorAdded get
Implements Oculus.Interaction.IInteractableView< out TInteractor >.
WhenInteractorRemoved
MAction<TInteractor> Oculus.Interaction.Interactable< TInteractor, TInteractable >.WhenInteractorRemoved get
Implements Oculus.Interaction.IInteractableView< out TInteractor >.
WhenSelectingInteractorAdded
MAction<TInteractor> Oculus.Interaction.Interactable< TInteractor, TInteractable >.WhenSelectingInteractorAdded get
Implements Oculus.Interaction.IInteractableView< out TInteractor >.
WhenSelectingInteractorRemoved
MAction<TInteractor> Oculus.Interaction.Interactable< TInteractor, TInteractable >.WhenSelectingInteractorRemoved get
Implements Oculus.Interaction.IInteractableView< out TInteractor >.
Event Documentation
WhenInteractorsCountUpdated
Action Oculus.Interaction.Interactable< TInteractor, TInteractable >.WhenInteractorsCountUpdated = delegate { }
Referenced by Oculus.Interaction.Interactable< TInteractor, TInteractable >.AddInteractor(), and Oculus.Interaction.Interactable< TInteractor, TInteractable >.RemoveInteractor().
WhenSelectingInteractorsCountUpdated
Action Oculus.Interaction.Interactable< TInteractor, TInteractable >.WhenSelectingInteractorsCountUpdated = delegate { }
Referenced by Oculus.Interaction.Interactable< TInteractor, TInteractable >.AddSelectingInteractor(), and Oculus.Interaction.Interactable< TInteractor, TInteractable >.RemoveSelectingInteractor().
WhenStateChanged
Action<InteractableStateChangeArgs> Oculus.Interaction.Interactable< TInteractor, TInteractable >.WhenStateChanged = delegate { }
The documentation for this class was generated from the following file:
C:/Users/Lykos/Desktop/Projects/Capstone/VRGames/Assets/ThirdParty/Oculus/Interaction/Runtime/Scripts/Interaction/Core/Interactable.cs