VRCapstoneGames: Unity.XR.CoreUtils.Tests.PerformanceTestBase Class Reference
Unity.XR.CoreUtils.Tests.PerformanceTestBase Class Reference abstract
Protected Member Functions
void Update ()
string GetReport ()
void SetupData ()
void RunTestFrame ()
Protected Attributes
int m_CallCount = 1000
int m_FrameCount = 10
long m_ElapsedTicks
string m_Report
readonly Stopwatch m_Timer = new Stopwatch()
string m_TestClassLabel
string m_MethodLabel
int m_FrameCounter
Member Function Documentation
GetReport()
string Unity.XR.CoreUtils.Tests.PerformanceTestBase.GetReport () abstract protected
Referenced by Unity.XR.CoreUtils.Tests.PerformanceTestBase.Update().
RunTestFrame()
void Unity.XR.CoreUtils.Tests.PerformanceTestBase.RunTestFrame () abstract protected
Referenced by Unity.XR.CoreUtils.Tests.PerformanceComparisonTest.Awake(), Unity.XR.CoreUtils.Tests.PerformanceTest.Awake(), and Unity.XR.CoreUtils.Tests.PerformanceTestBase.Update().
SetupData()
void Unity.XR.CoreUtils.Tests.PerformanceTestBase.SetupData () abstract protected
Referenced by Unity.XR.CoreUtils.Tests.PerformanceComparisonTest.Awake(), and Unity.XR.CoreUtils.Tests.PerformanceTest.Awake().
Update()
void Unity.XR.CoreUtils.Tests.PerformanceTestBase.Update () protected
Member Data Documentation
m_CallCount
int Unity.XR.CoreUtils.Tests.PerformanceTestBase.m_CallCount = 1000 protected
Referenced by Unity.XR.CoreUtils.Tests.PerformanceComparisonTest.GetReport(), Unity.XR.CoreUtils.Tests.PerformanceTest.GetReport(), Unity.XR.CoreUtils.Tests.ConvexHullPerformanceTest.SetupData(), Unity.XR.CoreUtils.Tests.CustomApproximatePerformanceTest.SetupData(), and Unity.XR.CoreUtils.Tests.PointInPolygonPerformanceTest.SetupData().
m_ElapsedTicks
long Unity.XR.CoreUtils.Tests.PerformanceTestBase.m_ElapsedTicks protected
Referenced by Unity.XR.CoreUtils.Tests.PerformanceComparisonTest.Awake(), Unity.XR.CoreUtils.Tests.PerformanceTest.Awake(), Unity.XR.CoreUtils.Tests.PerformanceComparisonTest.GetReport(), Unity.XR.CoreUtils.Tests.ConvexHullPerformanceTest.RunTestFrame(), Unity.XR.CoreUtils.Tests.CustomApproximatePerformanceTest.RunTestFrame(), and Unity.XR.CoreUtils.Tests.PointInPolygonPerformanceTest.RunTestFrame().
m_FrameCount
int Unity.XR.CoreUtils.Tests.PerformanceTestBase.m_FrameCount = 10 protected
Referenced by Unity.XR.CoreUtils.Tests.PerformanceTestBase.Update().
m_FrameCounter
int Unity.XR.CoreUtils.Tests.PerformanceTestBase.m_FrameCounter protected
Referenced by Unity.XR.CoreUtils.Tests.PerformanceComparisonTest.GetReport(), Unity.XR.CoreUtils.Tests.PerformanceTest.GetReport(), and Unity.XR.CoreUtils.Tests.PerformanceTestBase.Update().
m_MethodLabel
string Unity.XR.CoreUtils.Tests.PerformanceTestBase.m_MethodLabel protected
Referenced by Unity.XR.CoreUtils.Tests.ConvexHullPerformanceTest.SetupData(), Unity.XR.CoreUtils.Tests.CustomApproximatePerformanceTest.SetupData(), and Unity.XR.CoreUtils.Tests.PointInPolygonPerformanceTest.SetupData().
m_Report
string Unity.XR.CoreUtils.Tests.PerformanceTestBase.m_Report protected
Referenced by Unity.XR.CoreUtils.Tests.PerformanceComparisonTest.GetReport(), and Unity.XR.CoreUtils.Tests.PerformanceTest.GetReport().
m_TestClassLabel
string Unity.XR.CoreUtils.Tests.PerformanceTestBase.m_TestClassLabel protected
Referenced by Unity.XR.CoreUtils.Tests.PerformanceComparisonTest.Awake(), and Unity.XR.CoreUtils.Tests.PerformanceTest.Awake().
m_Timer
readonly Stopwatch Unity.XR.CoreUtils.Tests.PerformanceTestBase.m_Timer = new Stopwatch() protected
Referenced by Unity.XR.CoreUtils.Tests.PerformanceComparisonTest.Awake(), Unity.XR.CoreUtils.Tests.PerformanceTest.Awake(), Unity.XR.CoreUtils.Tests.ConvexHullPerformanceTest.RunTestFrame(), Unity.XR.CoreUtils.Tests.CustomApproximatePerformanceTest.RunTestFrame(), and Unity.XR.CoreUtils.Tests.PointInPolygonPerformanceTest.RunTestFrame().
The documentation for this class was generated from the following file:
C:/Users/Lykos/Desktop/Projects/Capstone/VRGames/Library/PackageCache/com.unity.xr.core-utils@2.0.0/Tests/Runtime/Scripts/PerformanceTestBase.cs