VRCapstoneGames: Oculus.Interaction.MaterialPropertyBlockEditor Class Reference
Oculus.Interaction.MaterialPropertyBlockEditor Class Reference
Public Member Functions
void UpdateMaterialPropertyBlock ()
Protected Member Functions
virtual void Awake ()
virtual void Update ()
Properties
List< Renderer > Renderers [get, set]
List< MaterialPropertyVector > VectorProperties [get, set]
List< MaterialPropertyColor > ColorProperties [get, set]
List< MaterialPropertyFloat > FloatProperties [get, set]
MaterialPropertyBlock MaterialPropertyBlock [get]
Member Function Documentation
Awake()
virtual void Oculus.Interaction.MaterialPropertyBlockEditor.Awake () protected virtual
Update()
virtual void Oculus.Interaction.MaterialPropertyBlockEditor.Update () protected virtual
UpdateMaterialPropertyBlock()
void Oculus.Interaction.MaterialPropertyBlockEditor.UpdateMaterialPropertyBlock ()
Referenced by Oculus.Interaction.MaterialPropertyBlockEditor.Awake(), Oculus.Interaction.DotGridProperties.Update(), and Oculus.Interaction.MaterialPropertyBlockEditor.Update().
Property Documentation
ColorProperties
List<MaterialPropertyColor> Oculus.Interaction.MaterialPropertyBlockEditor.ColorProperties get set
FloatProperties
List<MaterialPropertyFloat> Oculus.Interaction.MaterialPropertyBlockEditor.FloatProperties get set
MaterialPropertyBlock
MaterialPropertyBlock Oculus.Interaction.MaterialPropertyBlockEditor.MaterialPropertyBlock get
Referenced by Oculus.Interaction.DotGridProperties.Update(), and Oculus.Interaction.MaterialPropertyBlockEditor.UpdateMaterialPropertyBlock().
Renderers
List<Renderer> Oculus.Interaction.MaterialPropertyBlockEditor.Renderers get set
VectorProperties
List<MaterialPropertyVector> Oculus.Interaction.MaterialPropertyBlockEditor.VectorProperties get set
The documentation for this class was generated from the following file:
C:/Users/Lykos/Desktop/Projects/Capstone/VRGames/Assets/ThirdParty/Oculus/Interaction/Runtime/Scripts/MaterialProperties/MaterialPropertyBlockEditor.cs