VRCapstoneGames: UnityEngine.ProBuilder.Csg.Plane Class Reference
UnityEngine.ProBuilder.Csg.Plane Class Reference sealed
Represents a plane in 3d space.
Public Member Functions
Plane ()
Plane (Vector3 a, Vector3 b, Vector3 c)
override string ToString ()
bool Valid ()
void Flip ()
void SplitPolygon (Polygon polygon, List< Polygon > coplanarFront, List< Polygon > coplanarBack, List< Polygon > front, List< Polygon > back)
Public Attributes
Vector3 normal
float w
Detailed Description
Represents a plane in 3d space.
Does not include position.
Constructor & Destructor Documentation
Plane() [1/2]
UnityEngine.ProBuilder.Csg.Plane.Plane ()
Plane() [2/2]
UnityEngine.ProBuilder.Csg.Plane.Plane (Vector3 a, Vector3 b, Vector3 c)
Member Function Documentation
Flip()
void UnityEngine.ProBuilder.Csg.Plane.Flip ()
Referenced by UnityEngine.ProBuilder.Csg.Polygon.Flip(), and UnityEngine.ProBuilder.Csg.Node.Invert().
SplitPolygon()
void UnityEngine.ProBuilder.Csg.Plane.SplitPolygon (Polygon polygon, List< Polygon > coplanarFront, List< Polygon > coplanarBack, List< Polygon > front, List< Polygon > back)
Referenced by UnityEngine.ProBuilder.Csg.Node.Build(), and UnityEngine.ProBuilder.Csg.Node.ClipPolygons().
ToString()
override string UnityEngine.ProBuilder.Csg.Plane.ToString ()
Valid()
bool UnityEngine.ProBuilder.Csg.Plane.Valid ()
Referenced by UnityEngine.ProBuilder.Csg.Node.Build(), and UnityEngine.ProBuilder.Csg.Node.ClipPolygons().
Member Data Documentation
normal
Vector3 UnityEngine.ProBuilder.Csg.Plane.normal
Referenced by UnityEngine.ProBuilder.Csg.Plane.Flip(), UnityEngine.ProBuilder.Csg.Plane.Plane(), UnityEngine.ProBuilder.Csg.Plane.Plane(), and UnityEngine.ProBuilder.Csg.Plane.SplitPolygon().
w
float UnityEngine.ProBuilder.Csg.Plane.w
Referenced by UnityEngine.ProBuilder.Csg.Plane.Flip(), UnityEngine.ProBuilder.Csg.Plane.Plane(), UnityEngine.ProBuilder.Csg.Plane.Plane(), and UnityEngine.ProBuilder.Csg.Plane.SplitPolygon().
The documentation for this class was generated from the following file:
C:/Users/Lykos/Desktop/Projects/Capstone/VRGames/Library/PackageCache/com.unity.probuilder@5.0.6/External/CSG/Classes/Plane.cs