VRGames: UnityEngine.ProBuilder.ProBuilderMesh Class Reference
UnityEngine.ProBuilder.ProBuilderMesh Class Reference sealed
Represents the ProBuilder MeshFilter component, which is responsible for storing all the data necessary for editing and compiling UnityEngine.Mesh objects.
Classes
struct NonVersionedEditScope
Public Member Functions
bool HasArrays (MeshArrays channels)
Tests whether the mesh contains the requested arrays.
Vertex[] GetVertices (IList< int > indexes=null)
Creates a new array of vertices with values from a ProBuilderMesh component.
void SetVertices (IList< Vertex > vertices, bool applyMesh=false)
Sets the vertex element arrays on this mesh.
Vector3[] GetNormals ()
Gets the normals array for this mesh.
Color[] GetColors ()
Returns the Color values from the mesh.
Vector4[] GetTangents ()
Returns the tangents applied to the mesh. If they haven't been initialized yet, it creates and caches them.
void GetUVs (int channel, List< Vector4 > uvs)
Copies values from the specified UV channel to the list of texture UVs.
void SetUVs (int channel, List< Vector4 > uvs)
Sets the mesh UVs per channel. Channels 0 and 1 are cast to Vector2, but channels 2 and 3 remain Vector4.
void Clear ()
Resets (empties) all the attribute arrays on this object and clears any selected elements. The attribute arrays include faces, positions, texture UVs, tangents, shared vertices, shared textures, and vertex colors.
void RebuildWithPositionsAndFaces (IEnumerable< Vector3 > vertices, IEnumerable< Face > faces)
Clears all mesh attributes and reinitializes the mesh with new positions and face collections.
void ToMesh (MeshTopology preferredTopology=MeshTopology.Triangles)
Rebuilds the mesh positions and submeshes.
void CopyFrom (ProBuilderMesh other)
Copies the mesh data from another mesh to this one.
void Refresh (RefreshMask mask=RefreshMask.All)
Recalculates mesh attributes: normals, collisions, UVs, tangents, and colors.
void RefreshUV (IEnumerable< Face > facesToRefresh)
Rebuilds the UV arrays on the specified faces.
void SetFaceColor (Face face, Color color)
Applies a vertex color to the specified Face.
void SetMaterial (IEnumerable< Face > faces, Material material)
Sets a specific material on a collection of faces.
List< int > GetCoincidentVertices (IEnumerable< int > vertices)
Returns a list of vertices that are coincident to any of the specified vertices.
void GetCoincidentVertices (IEnumerable< Face > faces, List< int > coincident)
Populates a list of vertices that are coincident to any of the specified vertices.
void GetCoincidentVertices (IEnumerable< Edge > edges, List< int > coincident)
Populates a list of vertices that are coincident to any of the specified vertices.
void GetCoincidentVertices (IEnumerable< int > vertices, List< int > coincident)
Populates a list of vertices that are coincident to any of the specified vertices.
void GetCoincidentVertices (int vertex, List< int > coincident)
Populates a list with all the vertices that are coincident to the specified vertex.
void SetVerticesCoincident (IEnumerable< int > vertices)
Marks the specified vertices as coincident on this mesh.
Face[] GetSelectedFaces ()
Returns a copy of the array of selected faces.
void SetSelectedFaces (IEnumerable< Face > selected)
Sets the face selection for this mesh. Also sets the vertex and edge selection to match.
void SetSelectedEdges (IEnumerable< Edge > edges)
Sets the edge selection for this mesh. Also sets the vertex selection to match and clears the selected faces.
void SetSelectedVertices (IEnumerable< int > vertices)
Sets the selected vertices array. Clears the selected faces and selected edges arrays.
void ClearSelection ()
Clears the arrays of selected faces, edges, and vertices. You don't need to call this when setting an individual array, as the setter methods handle updating the associated caches.
Static Public Member Functions
static ProBuilderMesh Create ()
Creates a new GameObject with a ProBuilderMesh, UnityEngine.MeshFilter, and UnityEngine.MeshRenderer component but leaves the position and face information empty.
static ProBuilderMesh Create (IEnumerable< Vector3 > positions, IEnumerable< Face > faces)
Creates a new GameObject with a ProBuilderMesh, UnityEngine.MeshFilter, and UnityEngine.MeshRenderer component. Then it initializes the ProBuilderMesh with the specified sets of positions and faces.
static ProBuilderMesh Create (IList< Vertex > vertices, IList< Face > faces, IList< SharedVertex > sharedVertices=null, IList< SharedVertex > sharedTextures=null, IList< Material > materials=null)
Creates a new GameObject with a ProBuilderMesh, UnityEngine.MeshFilter, and UnityEngine.MeshRenderer component. Then it initializes the ProBuilderMesh with the specified sets of positions and faces, and if specified, coincident vertices, texture coordinates, and materials.
Static Public Attributes
const uint maxVertexCount = ushort.MaxValue
The maximum number of vertices that a ProBuilderMesh can accomodate.
Properties
bool userCollisions [get, set]
If false, ProBuilder will automatically create and scale colliders.
UnwrapParameters unwrapParameters [get, set]
UV2 generation parameters.
bool preserveMeshAssetOnDestroy [get, set]
Gets or sets whether to destroy the mesh asset if this ProBuilderMesh is deleted.
IList< Face > faces [get, set]
Gets or sets the faces that ProBuilder uses to compile a mesh.
IList< SharedVertex > sharedVertices [get, set]
Gets or sets the sharedVertices for this ProBuilderMesh object.
IList< Vector3 > positions [get, set]
Gets or sets the vertex positions that compose this mesh.
IList< Vector3 > normals [get]
Gets the normals for this mesh.
IList< Color > colors [get, set]
Gets or sets a collecton of the vertex colors for this mesh. When setting, the value must match the length of the positions.
IList< Vector4 > tangents [get, set]
Gets or sets the array of tangents that the user explicitly set for this mesh.
IList< Vector2 > textures [get, set]
Gets or sets the UV0 channel.
int faceCount [get]
Gets the number of faces that this mesh has.
int vertexCount [get]
Gets the number of vertices in the positions array.
int edgeCount [get]
Gets the number of edges that compose this mesh.
int indexCount [get]
Gets the number of vertex indices that compose this mesh.
int triangleCount [get]
Gets the number of triangles that compose this mesh.
MeshSyncState meshSyncState [get]
Gets a flag that indicates whether the UnityEngine.Mesh is in sync with the ProBuilderMesh.
bool selectable [get, set]
Gets or sets whether elements can be selected. Used by UnityEditor.ProBuilder.ProBuilderEditor.
int selectedFaceCount [get]
Gets the number of faces that are currently selected on this object.
int selectedVertexCount [get]
Gets the number of selected vertex indices.
int selectedEdgeCount [get]
Gets the number of selected edges.
ReadOnlyCollection< int > selectedFaceIndexes [get]
Gets a collection of the currently selected faces by their index in the ProBuilderMesh.faces array.
ReadOnlyCollection< int > selectedVertices [get]
Gets a collection of the currently selected vertices by their index in the ProBuilderMesh.positions array.
ReadOnlyCollection< Edge > selectedEdges [get]
Gets a collection of the currently selected edges.
Events
static Action< ProBuilderMesh > meshWillBeDestroyed
Invoked when this ProBuilderMesh is deleted.
static Action< ProBuilderMesh > elementSelectionChanged
Invoked when the element selection changes on any ProBuilderMesh.
Detailed Description
Represents the ProBuilder MeshFilter component, which is responsible for storing all the data necessary for editing and compiling UnityEngine.Mesh objects.
Member Function Documentation
Clear()
void UnityEngine.ProBuilder.ProBuilderMesh.Clear ()
Resets (empties) all the attribute arrays on this object and clears any selected elements. The attribute arrays include faces, positions, texture UVs, tangents, shared vertices, shared textures, and vertex colors.
Referenced by UnityEngine.ProBuilder.SceneSelection.Clear(), UnityEngine.ProBuilder.ProBuilderMesh.CopyFrom(), UnityEngine.ProBuilder.MeshOperations.MeshImporter.Import(), UnityEngine.ProBuilder.Shapes.Cube.RebuildMesh(), UnityEngine.ProBuilder.Shapes.Sprite.RebuildMesh(), UnityEngine.ProBuilder.ProBuilderMesh.RebuildWithPositionsAndFaces(), UnityEngine.ProBuilder.BezierShape.Refresh(), and UnityEngine.ProBuilder.ProBuilderMesh.SetVertices().
ClearSelection()
void UnityEngine.ProBuilder.ProBuilderMesh.ClearSelection ()
Clears the arrays of selected faces, edges, and vertices. You don't need to call this when setting an individual array, as the setter methods handle updating the associated caches.
Referenced by UnityEngine.ProBuilder.ProBuilderMesh.Clear(), and UnityEngine.ProBuilder.ProBuilderMesh.SetSelectedEdges().
CopyFrom()
void UnityEngine.ProBuilder.ProBuilderMesh.CopyFrom (ProBuilderMesh other)
Copies the mesh data from another mesh to this one.
Parameters
other The mesh to copy from.
Create() [1/3]
static ProBuilderMesh UnityEngine.ProBuilder.ProBuilderMesh.Create () static
Creates a new GameObject with a ProBuilderMesh, UnityEngine.MeshFilter, and UnityEngine.MeshRenderer component but leaves the position and face information empty.
Returns
A reference to the new ProBuilderMesh component.
Create() [2/3]
static ProBuilderMesh UnityEngine.ProBuilder.ProBuilderMesh.Create (IEnumerable< Vector3 > positions, IEnumerable< Face > faces) static
Creates a new GameObject with a ProBuilderMesh, UnityEngine.MeshFilter, and UnityEngine.MeshRenderer component. Then it initializes the ProBuilderMesh with the specified sets of positions and faces.
Parameters
positions Vertex positions array.
faces Faces array.
Returns
A reference to the new ProBuilderMesh component.
Create() [3/3]
static ProBuilderMesh UnityEngine.ProBuilder.ProBuilderMesh.Create (IList< Vertex > vertices, IList< Face > faces, IList< SharedVertex > sharedVertices = null, IList< SharedVertex > sharedTextures = null, IList< Material > materials = null) static
Creates a new GameObject with a ProBuilderMesh, UnityEngine.MeshFilter, and UnityEngine.MeshRenderer component. Then it initializes the ProBuilderMesh with the specified sets of positions and faces, and if specified, coincident vertices, texture coordinates, and materials.
Parameters
vertices Array of vertex positions to use.
faces Array of faces to use.
sharedVertices Optional SharedVertex array to define the coincident vertices.
sharedTextures Optional SharedVertex array to define the coincident texture coordinates (UV0).
materials Optional array of materials to be assigned to the UnityEngine.MeshRenderer.
Returns
A reference to the new ProBuilderMesh component.
GetCoincidentVertices() [1/5]
void UnityEngine.ProBuilder.ProBuilderMesh.GetCoincidentVertices (IEnumerable< Edge > edges, List< int > coincident)
Populates a list of vertices that are coincident to any of the specified vertices.
Parameters
edges A collection of edges to gather vertices from.
coincident The list to clear and populate with any vertices that are coincident.
Exceptions
ArgumentNullException The vertices and coincident parameters may not be null.
GetCoincidentVertices() [2/5]
void UnityEngine.ProBuilder.ProBuilderMesh.GetCoincidentVertices (IEnumerable< Face > faces, List< int > coincident)
Populates a list of vertices that are coincident to any of the specified vertices.
Parameters
faces A collection of faces to gather vertices from.
coincident The list to clear and populate with any vertices that are coincident.
Exceptions
ArgumentNullException The vertices and coincident parameters may not be null.
GetCoincidentVertices() [3/5]
List< int > UnityEngine.ProBuilder.ProBuilderMesh.GetCoincidentVertices (IEnumerable< int > vertices)
Returns a list of vertices that are coincident to any of the specified vertices.
Parameters
vertices A collection of indices relative to the mesh positions.
Returns
A list of all vertices that share a position with any of the specified vertices.
Exceptions
ArgumentNullException The vertices parameter may not be null.
Referenced by UnityEngine.ProBuilder.ProBuilderMesh.GetCoincidentVertices(), UnityEditor.ProBuilder.ElementGroup.GetElementGroups(), UnityEditor.ProBuilder.Actions.WeldVertices.PerformActionImplementation(), UnityEditor.ProBuilder.VertexColorPalette.SetFaceColors(), and UnityEngine.ProBuilder.ProBuilderMesh.SetVerticesCoincident().
GetCoincidentVertices() [4/5]
void UnityEngine.ProBuilder.ProBuilderMesh.GetCoincidentVertices (IEnumerable< int > vertices, List< int > coincident)
Populates a list of vertices that are coincident to any of the specified vertices.
Parameters
vertices A collection of indices relative to the mesh positions.
coincident The list to clear and populate with any vertices that are coincident.
Exceptions
ArgumentNullException The vertices and coincident parameters may not be null.
GetCoincidentVertices() [5/5]
void UnityEngine.ProBuilder.ProBuilderMesh.GetCoincidentVertices (int vertex, List< int > coincident)
Populates a list with all the vertices that are coincident to the specified vertex.
Parameters
vertex An index relative to a positions array.
coincident The list to clear and populate with any vertices that are coincident.
Exceptions
ArgumentNullException The coincident list may not be null.
ArgumentOutOfRangeException The SharedVertex[] does not contain an entry for the requested vertex.
GetColors()
Color[] UnityEngine.ProBuilder.ProBuilderMesh.GetColors ()
Returns the Color values from the mesh.
Returns
An array of colors for this mesh. If the mesh does not contain colors, it returns a new array filled with the default value (UnityEngine.Color.white).
Referenced by UnityEditor.ProBuilder.VertexColorPalette.SetFaceColors().
GetNormals()
Vector3[] UnityEngine.ProBuilder.ProBuilderMesh.GetNormals ()
Gets the normals array for this mesh.
Returns
An array of normals for this mesh.
Referenced by UnityEngine.ProBuilder.ProBuilderMesh.GetVertices().
GetSelectedFaces()
Face[] UnityEngine.ProBuilder.ProBuilderMesh.GetSelectedFaces ()
Returns a copy of the array of selected faces.
Returns
Array of currently selected faces.
Referenced by UnityEditor.ProBuilder.Actions.ConformFaceNormals.PerformActionImplementation(), UnityEditor.ProBuilder.Actions.ExtrudeFaces.PerformActionImplementation(), UnityEditor.ProBuilder.Actions.FlipFaceNormals.PerformActionImplementation(), and UnityEditor.ProBuilder.Actions.GrowSelection.PerformActionImplementation().
GetTangents()
Vector4[] UnityEngine.ProBuilder.ProBuilderMesh.GetTangents ()
Returns the tangents applied to the mesh. If they haven't been initialized yet, it creates and caches them.
Returns
The tangents applied to UnityEngine.MeshFilter.sharedMesh or null if the tangents array length doesn't match the vertex count.
Referenced by UnityEngine.ProBuilder.ProBuilderMesh.GetVertices().
GetUVs()
void UnityEngine.ProBuilder.ProBuilderMesh.GetUVs (int channel, List< Vector4 > uvs)
Copies values from the specified UV channel to the list of texture UVs.
Parameters
channel The index of the UV channel to fetch values from. The valid range is {0, 1, 2, 3}.
uvs The list of texture UVs to clear and populate with the copied UVs.
Referenced by UnityEngine.ProBuilder.ProBuilderMesh.GetVertices(), and UnityEditor.ProBuilder.TextureTool.MeshAndTextures.MeshAndTextures().
GetVertices()
Vertex[] UnityEngine.ProBuilder.ProBuilderMesh.GetVertices (IList< int > indexes = null)
Creates a new array of vertices with values from a ProBuilderMesh component.
Parameters
indexes An optional list of indices used to designate the subset of vertices values to retrieve from the mesh in the array.
Returns
An array of vertices matching either the specified list in the indexes parameter. If the indexes parameter contains no list, this returns all mesh vertices.
Referenced by UnityEngine.ProBuilder.FaceRebuildData.Apply(), and UnityEditor.ProBuilder.Model.Model().
HasArrays()
bool UnityEngine.ProBuilder.ProBuilderMesh.HasArrays (MeshArrays channels)
Tests whether the mesh contains the requested arrays.
Parameters
channels A flag containing the array types that a ProBuilder mesh stores.
Returns
True if all arrays in the flag are present, false if not.
Referenced by UnityEngine.ProBuilder.ProBuilderMesh.GetColors(), UnityEngine.ProBuilder.ProBuilderMesh.GetNormals(), UnityEngine.ProBuilder.ProBuilderMesh.GetTangents(), UnityEngine.ProBuilder.ProBuilderMesh.RefreshUV(), and UnityEngine.ProBuilder.ProBuilderMesh.SetFaceColor().
RebuildWithPositionsAndFaces()
void UnityEngine.ProBuilder.ProBuilderMesh.RebuildWithPositionsAndFaces (IEnumerable< Vector3 > vertices, IEnumerable< Face > faces)
Clears all mesh attributes and reinitializes the mesh with new positions and face collections.
Parameters
vertices New vertex positions array to use.
faces New faces array to use.
Referenced by UnityEngine.ProBuilder.Shapes.Cone.RebuildMesh(), UnityEngine.ProBuilder.Shapes.Cylinder.RebuildMesh(), UnityEngine.ProBuilder.Shapes.Prism.RebuildMesh(), UnityEngine.ProBuilder.Shapes.Sphere.RebuildMesh(), UnityEngine.ProBuilder.Shapes.Sprite.RebuildMesh(), and UnityEngine.ProBuilder.Shapes.Torus.RebuildMesh().
Refresh()
void UnityEngine.ProBuilder.ProBuilderMesh.Refresh (RefreshMask mask = RefreshMask::All)
Recalculates mesh attributes: normals, collisions, UVs, tangents, and colors.
Parameters
mask Optional. Specify a RefreshMask to indicate which components to update. Use this when you want to wait until later to rebuild some components in order to save processing power, since UVs and collisions are expensive to rebuild and can usually be deferred until the task finishes.
Referenced by UnityEditor.ProBuilder.MaterialEditor.ClickShortcutCheck(), UnityEditor.ProBuilder.UVEditor.Menu_BoxProject(), UnityEditor.ProBuilder.UVEditor.Menu_SewUVs(), UnityEditor.ProBuilder.UVEditor.Menu_SphericalProject(), UnityEditor.ProBuilder.UVEditor.Menu_SplitUVs(), UnityEditor.ProBuilder.Actions.MirrorObjects.Mirror(), UnityEditor.ProBuilder.Model.Model(), UnityEditor.ProBuilder.EntityEditor.OnInspectorGUI(), UnityEditor.ProBuilder.Actions.BevelEdges.PerformActionImplementation(), UnityEditor.ProBuilder.Actions.ConformFaceNormals.PerformActionImplementation(), UnityEditor.ProBuilder.Actions.DeleteFaces.PerformActionImplementation(), UnityEditor.ProBuilder.Actions.ExtrudeEdges.PerformActionImplementation(), UnityEditor.ProBuilder.Actions.ExtrudeFaces.PerformActionImplementation(), UnityEditor.ProBuilder.Actions.FillHole.PerformActionImplementation(), UnityEditor.ProBuilder.Actions.FlipFaceEdge.PerformActionImplementation(), UnityEditor.ProBuilder.Actions.FlipFaceNormals.PerformActionImplementation(), UnityEditor.ProBuilder.Actions.InsertEdgeLoop.PerformActionImplementation(), UnityEditor.ProBuilder.Actions.MergeFaces.PerformActionImplementation(), UnityEditor.ProBuilder.Actions.SubdivideEdges.PerformActionImplementation(), UnityEditor.ProBuilder.Actions.SubdivideFaces.PerformActionImplementation(), UnityEditor.ProBuilder.Actions.TriangulateFaces.PerformActionImplementation(), UnityEditor.ProBuilder.Actions.WeldVertices.PerformActionImplementation(), UnityEditor.ProBuilder.Actions.ConformObjectNormals.PerformActionImplementation(), UnityEditor.ProBuilder.Actions.FlipObjectNormals.PerformActionImplementation(), UnityEditor.ProBuilder.Actions.SubdivideObject.PerformActionImplementation(), UnityEditor.ProBuilder.Actions.SoftDeleteEdgesAction.PerformActionImplementation(), UnityEngine.ProBuilder.Shapes.Arch.RebuildMesh(), UnityEngine.ProBuilder.Shapes.Torus.RebuildMesh(), UnityEngine.ProBuilder.ProBuilderMesh.RebuildWithPositionsAndFaces(), UnityEngine.ProBuilder.BezierShape.Refresh(), UnityEditor.ProBuilder.VertexColorPalette.SetFaceColors(), and UnityEditor.ProBuilder.UVEditor.SetIsManual().
RefreshUV()
void UnityEngine.ProBuilder.ProBuilderMesh.RefreshUV (IEnumerable< Face > facesToRefresh)
Rebuilds the UV arrays on the specified faces.
This usually applies only to faces set to use Auto UVs. However, if ProBuilder can't detect any valid UV arrays, it resets the faces from Manual to Auto before rebuilding them.
Parameters
facesToRefresh The set of faces to process.
See also
Refresh
Referenced by UnityEngine.ProBuilder.Shapes.Cone.RebuildMesh(), and UnityEngine.ProBuilder.ProBuilderMesh.Refresh().
SetFaceColor()
void UnityEngine.ProBuilder.ProBuilderMesh.SetFaceColor (Face face, Color color)
Applies a vertex color to the specified Face.
Parameters
face The target face to apply the colors to.
color The color to apply to this face's referenced vertices.
Referenced by UnityEditor.ProBuilder.VertexColorPalette.SetFaceColors().
SetMaterial()
void UnityEngine.ProBuilder.ProBuilderMesh.SetMaterial (IEnumerable< Face > faces, Material material)
Sets a specific material on a collection of faces.
To apply the changes to the UnityEngine.Mesh, call ToMesh and Refresh.
Parameters
faces The faces to apply the material to.
material The material to apply.
SetSelectedEdges()
void UnityEngine.ProBuilder.ProBuilderMesh.SetSelectedEdges (IEnumerable< Edge > edges)
Sets the edge selection for this mesh. Also sets the vertex selection to match and clears the selected faces.
Parameters
edges A set of edges to select.
Referenced by UnityEditor.ProBuilder.Actions.ExtrudeEdges.PerformActionImplementation(), UnityEditor.ProBuilder.Actions.InsertEdgeLoop.PerformActionImplementation(), UnityEditor.ProBuilder.Actions.SubdivideEdges.PerformActionImplementation(), UnityEditor.ProBuilder.Actions.GrowSelection.PerformActionImplementation(), UnityEditor.ProBuilder.Actions.SelectEdgeLoop.PerformActionImplementation(), UnityEditor.ProBuilder.Actions.SelectHole.PerformActionImplementation(), and UnityEditor.ProBuilder.Actions.ShrinkSelection.PerformActionImplementation().
SetSelectedFaces()
void UnityEngine.ProBuilder.ProBuilderMesh.SetSelectedFaces (IEnumerable< Face > selected)
Sets the face selection for this mesh. Also sets the vertex and edge selection to match.
Parameters
selected A set of faces to select.
Referenced by UnityEditor.ProBuilder.Actions.SelectFaceRing.MenuRingAndLoopFaces(), UnityEditor.ProBuilder.Actions.BevelEdges.PerformActionImplementation(), UnityEditor.ProBuilder.Actions.ExtrudeFaces.PerformActionImplementation(), UnityEditor.ProBuilder.Actions.FillHole.PerformActionImplementation(), UnityEditor.ProBuilder.Actions.MergeFaces.PerformActionImplementation(), UnityEditor.ProBuilder.Actions.SubdivideFaces.PerformActionImplementation(), UnityEditor.ProBuilder.Actions.TriangulateFaces.PerformActionImplementation(), UnityEditor.ProBuilder.Actions.GrowSelection.PerformActionImplementation(), UnityEditor.ProBuilder.Actions.SelectFaceLoop.PerformActionImplementation(), UnityEditor.ProBuilder.Actions.SelectFaceRing.PerformActionImplementation(), UnityEditor.ProBuilder.Actions.SelectSmoothingGroup.PerformActionImplementation(), UnityEditor.ProBuilder.Actions.SelectVertexColor.PerformActionImplementation(), UnityEditor.ProBuilder.Actions.ShrinkSelection.PerformActionImplementation(), and UnityEngine.ProBuilder.ProBuilderMesh.SetSelectedFaces().
SetSelectedVertices()
void UnityEngine.ProBuilder.ProBuilderMesh.SetSelectedVertices (IEnumerable< int > vertices)
Sets the selected vertices array. Clears the selected faces and selected edges arrays.
Parameters
vertices The new vertices to select.
Referenced by UnityEditor.ProBuilder.Actions.WeldVertices.PerformActionImplementation(), UnityEditor.ProBuilder.Actions.SubdivideObject.PerformActionImplementation(), and UnityEditor.ProBuilder.Actions.ShrinkSelection.PerformActionImplementation().
SetUVs()
void UnityEngine.ProBuilder.ProBuilderMesh.SetUVs (int channel, List< Vector4 > uvs)
Sets the mesh UVs per channel. Channels 0 and 1 are cast to Vector2, but channels 2 and 3 remain Vector4.
Does not apply to mesh (use Refresh to reflect changes after application).
Parameters
channel The index of the UV channel to copy values to. The valid range is {0, 1, 2, 3}.
uvs The list of new UV values.
Referenced by UnityEngine.ProBuilder.ProBuilderMesh.CopyFrom().
SetVertices()
void UnityEngine.ProBuilder.ProBuilderMesh.SetVertices (IList< Vertex > vertices, bool applyMesh = false)
Sets the vertex element arrays on this mesh.
Parameters
vertices The new vertex array.
applyMesh Optionally indicate whether to apply elements to the UnityEngine.MeshFilter.sharedMesh. Note that you should only use this when the mesh is in its original state, not optimized (that is, when it won't affect triangles which can be optimized).
Referenced by UnityEngine.ProBuilder.FaceRebuildData.Apply(), and UnityEngine.ProBuilder.MeshOperations.MeshImporter.Import().
SetVerticesCoincident()
void UnityEngine.ProBuilder.ProBuilderMesh.SetVerticesCoincident (IEnumerable< int > vertices)
Marks the specified vertices as coincident on this mesh.
Note that it is up to the caller to ensure that the specified vertices are indeed sharing a position.
Parameters
vertices The list of vertices to be marked as coincident.
ToMesh()
void UnityEngine.ProBuilder.ProBuilderMesh.ToMesh (MeshTopology preferredTopology = MeshTopology::Triangles)
Rebuilds the mesh positions and submeshes.
If the vertex count matches the new positions array, the existing attributes are kept (except for UV2s, which are always cleared). Otherwise, the mesh is cleared.
Parameters
preferredTopology You can specify MeshTopology.Quads if you don't want to use the default MeshTopology.Triangles.
Referenced by UnityEditor.ProBuilder.MaterialEditor.ClickShortcutCheck(), UnityEditor.ProBuilder.UVEditor.Menu_SewUVs(), UnityEditor.ProBuilder.UVEditor.Menu_SplitUVs(), UnityEditor.ProBuilder.Actions.MirrorObjects.Mirror(), UnityEditor.ProBuilder.Model.Model(), UnityEditor.ProBuilder.EntityEditor.OnInspectorGUI(), UnityEditor.ProBuilder.Actions.BevelEdges.PerformActionImplementation(), UnityEditor.ProBuilder.Actions.ConformFaceNormals.PerformActionImplementation(), UnityEditor.ProBuilder.Actions.DeleteFaces.PerformActionImplementation(), UnityEditor.ProBuilder.Actions.ExtrudeEdges.PerformActionImplementation(), UnityEditor.ProBuilder.Actions.ExtrudeFaces.PerformActionImplementation(), UnityEditor.ProBuilder.Actions.FillHole.PerformActionImplementation(), UnityEditor.ProBuilder.Actions.FlipFaceEdge.PerformActionImplementation(), UnityEditor.ProBuilder.Actions.FlipFaceNormals.PerformActionImplementation(), UnityEditor.ProBuilder.Actions.InsertEdgeLoop.PerformActionImplementation(), UnityEditor.ProBuilder.Actions.MergeFaces.PerformActionImplementation(), UnityEditor.ProBuilder.Actions.SubdivideEdges.PerformActionImplementation(), UnityEditor.ProBuilder.Actions.SubdivideFaces.PerformActionImplementation(), UnityEditor.ProBuilder.Actions.TriangulateFaces.PerformActionImplementation(), UnityEditor.ProBuilder.Actions.WeldVertices.PerformActionImplementation(), UnityEditor.ProBuilder.Actions.ConformObjectNormals.PerformActionImplementation(), UnityEditor.ProBuilder.Actions.FlipObjectNormals.PerformActionImplementation(), UnityEditor.ProBuilder.Actions.SubdivideObject.PerformActionImplementation(), UnityEditor.ProBuilder.Actions.SoftDeleteEdgesAction.PerformActionImplementation(), UnityEngine.ProBuilder.ProBuilderMesh.RebuildWithPositionsAndFaces(), UnityEngine.ProBuilder.BezierShape.Refresh(), UnityEditor.ProBuilder.VertexColorPalette.SetFaceColors(), and UnityEditor.ProBuilder.UVEditor.SetIsManual().
Member Data Documentation
maxVertexCount
const uint UnityEngine.ProBuilder.ProBuilderMesh.maxVertexCount = ushort.MaxValue static
The maximum number of vertices that a ProBuilderMesh can accomodate.
Property Documentation
colors
IList<Color> UnityEngine.ProBuilder.ProBuilderMesh.colors get set
Gets or sets a collecton of the vertex colors for this mesh. When setting, the value must match the length of the positions.
Returns
A collection of colors for this mesh.
Referenced by UnityEngine.ProBuilder.ProBuilderMesh.CopyFrom(), UnityEngine.ProBuilder.ProBuilderMesh.GetColors(), and UnityEngine.ProBuilder.ProBuilderMesh.GetVertices().
edgeCount
int UnityEngine.ProBuilder.ProBuilderMesh.edgeCount get
Gets the number of edges that compose this mesh.
Returns
The number of edges in this mesh.
faceCount
int UnityEngine.ProBuilder.ProBuilderMesh.faceCount get
Gets the number of faces that this mesh has.
Returns
The number of faces on this mesh.
faces
IList<Face> UnityEngine.ProBuilder.ProBuilderMesh.faces get set
Gets or sets the faces that ProBuilder uses to compile a mesh.
Meshes are composed of vertices and faces. Faces primarily contain triangles and material information.
Returns
A collection of the Face objects that make up this mesh.
Referenced by UnityEngine.ProBuilder.ProBuilderMesh.Create(), UnityEngine.ProBuilder.ProBuilderMesh.Create(), UnityEngine.ProBuilder.ProBuilderMesh.GetCoincidentVertices(), UnityEngine.ProBuilder.ProBuilderMesh.GetCoincidentVertices(), UnityEditor.ProBuilder.Actions.ConformObjectNormals.PerformActionImplementation(), UnityEngine.ProBuilder.ProBuilderMesh.RebuildWithPositionsAndFaces(), UnityEngine.ProBuilder.ProBuilderMesh.SetMaterial(), and UnityEditor.ProBuilder.TextureMoveTool.TranslateTextureSelection.TranslateTextureSelection().
indexCount
int UnityEngine.ProBuilder.ProBuilderMesh.indexCount get
Gets the number of vertex indices that compose this mesh.
Returns
The number of vertices in this mesh.
meshSyncState
MeshSyncState UnityEngine.ProBuilder.ProBuilderMesh.meshSyncState get
Gets a flag that indicates whether the UnityEngine.Mesh is in sync with the ProBuilderMesh.
Returns
A flag that describes the state of the synchronicity between the UnityEngine.MeshFilter.sharedMesh and ProBuilderMesh components.
normals
IList<Vector3> UnityEngine.ProBuilder.ProBuilderMesh.normals get
Gets the normals for this mesh.
Refresh Normals.CalculateNormals
Returns
A collection of normals for this mesh.
Referenced by UnityEngine.ProBuilder.ProBuilderMesh.GetNormals(), and UnityEngine.ProBuilder.ProBuilderMesh.GetVertices().
positions
IList<Vector3> UnityEngine.ProBuilder.ProBuilderMesh.positions get set
Gets or sets the vertex positions that compose this mesh.
Referenced by UnityEngine.ProBuilder.ProBuilderMesh.CopyFrom(), UnityEngine.ProBuilder.ProBuilderMesh.Create(), ProBuilder.Examples.Handles.Draw(), UnityEngine.ProBuilder.ProBuilderMesh.GetVertices(), and UnityEditor.ProBuilder.PositionTool.MeshAndPositions.MeshAndPositions().
preserveMeshAssetOnDestroy
bool UnityEngine.ProBuilder.ProBuilderMesh.preserveMeshAssetOnDestroy get set
Gets or sets whether to destroy the mesh asset if this ProBuilderMesh is deleted.
In the Editor, when you delete a ProBuilderMesh you usually also want to destroy the mesh asset. However, there are situations you'd want to keep the mesh around, like when stripping ProBuilder scripts.
Returns
True to keep the mesh asset; false to destroy it.
selectable
bool UnityEngine.ProBuilder.ProBuilderMesh.selectable get set
Gets or sets whether elements can be selected. Used by UnityEditor.ProBuilder.ProBuilderEditor.
Returns
False if mesh elements are not selectable.
Referenced by UnityEngine.ProBuilder.ProBuilderMesh.CopyFrom().
selectedEdgeCount
int UnityEngine.ProBuilder.ProBuilderMesh.selectedEdgeCount get
Gets the number of selected edges.
Returns
Number of selected edges.
Referenced by UnityEditor.ProBuilder.Actions.ExtrudeEdges.PerformActionImplementation(), UnityEditor.ProBuilder.Actions.SelectEdgeLoop.PerformActionImplementation(), and UnityEditor.ProBuilder.Actions.SoftDeleteEdgesAction.PerformActionImplementation().
selectedEdges
ReadOnlyCollection<Edge> UnityEngine.ProBuilder.ProBuilderMesh.selectedEdges get
Gets a collection of the currently selected edges.
Returns
Collection of Edge objects representing the currently selected edges.
Referenced by UnityEditor.ProBuilder.Actions.BevelEdges.PerformActionImplementation(), UnityEditor.ProBuilder.Actions.ExtrudeEdges.PerformActionImplementation(), UnityEditor.ProBuilder.Actions.InsertEdgeLoop.PerformActionImplementation(), UnityEditor.ProBuilder.Actions.SubdivideEdges.PerformActionImplementation(), UnityEditor.ProBuilder.Actions.SelectEdgeLoop.PerformActionImplementation(), UnityEditor.ProBuilder.Actions.ShrinkSelection.PerformActionImplementation(), and UnityEditor.ProBuilder.Actions.SoftDeleteEdgesAction.PerformActionImplementation().
selectedFaceCount
int UnityEngine.ProBuilder.ProBuilderMesh.selectedFaceCount get
Gets the number of faces that are currently selected on this object.
Returns
Number of selected faces.
Referenced by UnityEditor.ProBuilder.Actions.DeleteFaces.PerformActionImplementation(), UnityEditor.ProBuilder.Actions.ExtrudeFaces.PerformActionImplementation(), UnityEditor.ProBuilder.Actions.FlipFaceNormals.PerformActionImplementation(), and UnityEditor.ProBuilder.Actions.MergeFaces.PerformActionImplementation().
selectedFaceIndexes
ReadOnlyCollection<int> UnityEngine.ProBuilder.ProBuilderMesh.selectedFaceIndexes get
Gets a collection of the currently selected faces by their index in the ProBuilderMesh.faces array.
Returns
Array of indices representing the currently selected faces.
Referenced by UnityEditor.ProBuilder.TextureMoveTool.TranslateTextureSelection.TranslateTextureSelection().
selectedVertexCount
int UnityEngine.ProBuilder.ProBuilderMesh.selectedVertexCount get
Gets the number of selected vertex indices.
Returns
Number of selected vertices.
Referenced by UnityEditor.ProBuilder.Actions.GrowSelection.PerformActionImplementation().
selectedVertices
ReadOnlyCollection<int> UnityEngine.ProBuilder.ProBuilderMesh.selectedVertices get
Gets a collection of the currently selected vertices by their index in the ProBuilderMesh.positions array.
Returns
Array of indices representing the currently selected vertices.
Referenced by UnityEditor.ProBuilder.Actions.WeldVertices.PerformActionImplementation().
sharedVertices
IList<SharedVertex> UnityEngine.ProBuilder.ProBuilderMesh.sharedVertices get set
Gets or sets the sharedVertices for this ProBuilderMesh object.
ProBuilder makes the assumption that no Face references a vertex used by another. However, ProBuilder needs to be able to associate vertices in the Editor for many operations. These vertices are usually called coincident, or "shared" vertices. ProBuilder manages these associations with the sharedIndexes array.
Each array contains a list of triangles that points to vertices considered to be coincident. When ProBuilder compiles a UnityEngine.Mesh from the ProBuilderMesh, it condenses these vertices to a single vertex where possible.
Returns
The shared (or common) index array for this mesh.
Referenced by UnityEngine.ProBuilder.ProBuilderMesh.CopyFrom(), and UnityEngine.ProBuilder.ProBuilderMesh.Create().
tangents
IList<Vector4> UnityEngine.ProBuilder.ProBuilderMesh.tangents get set
Gets or sets the array of tangents that the user explicitly set for this mesh.
Returns
A collection of tangents for this mesh or null if the user hasn't set any tangents yet.
To get the generated tangents that are applied to the mesh through Refresh(), use GetTangents().
See also
GetTangents
Referenced by UnityEngine.ProBuilder.ProBuilderMesh.CopyFrom(), UnityEngine.ProBuilder.ProBuilderMesh.GetTangents(), and UnityEngine.ProBuilder.ProBuilderMesh.GetVertices().
textures
IList<Vector2> UnityEngine.ProBuilder.ProBuilderMesh.textures get set
Gets or sets the UV0 channel.
Returns
The list of texture UVs for this mesh or null if there are none.
See also
GetUVs
Referenced by UnityEditor.ProBuilder.TextureMoveTool.DoToolGUI().
triangleCount
int UnityEngine.ProBuilder.ProBuilderMesh.triangleCount get
Gets the number of triangles that compose this mesh.
Returns
The number of triangles in this mesh.
unwrapParameters
UnwrapParameters UnityEngine.ProBuilder.ProBuilderMesh.unwrapParameters get set
UV2 generation parameters.
Referenced by UnityEngine.ProBuilder.ProBuilderMesh.CopyFrom().
userCollisions
bool UnityEngine.ProBuilder.ProBuilderMesh.userCollisions get set
If false, ProBuilder will automatically create and scale colliders.
Referenced by UnityEngine.ProBuilder.ProBuilderMesh.CopyFrom(), and UnityEditor.ProBuilder.EntityEditor.OnInspectorGUI().
vertexCount
int UnityEngine.ProBuilder.ProBuilderMesh.vertexCount get
Gets the number of vertices in the positions array.
Returns
The number of vertex positions for this mesh.
Referenced by UnityEngine.ProBuilder.ProBuilderMesh.GetColors(), UnityEngine.ProBuilder.ProBuilderMesh.GetUVs(), UnityEngine.ProBuilder.ProBuilderMesh.GetVertices(), UnityEngine.ProBuilder.ProBuilderMesh.HasArrays(), UnityEditor.ProBuilder.Actions.WeldVertices.PerformActionImplementation(), UnityEditor.ProBuilder.Actions.SelectVertexColor.PerformActionImplementation(), UnityEngine.ProBuilder.ProBuilderMesh.RefreshUV(), UnityEngine.ProBuilder.ProBuilderMesh.SetFaceColor(), and UnityEngine.ProBuilder.ProBuilderMesh.ToMesh().
Event Documentation
elementSelectionChanged
Action<ProBuilderMesh> UnityEngine.ProBuilder.ProBuilderMesh.elementSelectionChanged static
Invoked when the element selection changes on any ProBuilderMesh.
See also
SetSelectedFaces, SetSelectedVertices, SetSelectedEdges
Referenced by UnityEngine.ProBuilder.ProBuilderMesh.SetSelectedEdges(), and UnityEngine.ProBuilder.ProBuilderMesh.SetSelectedVertices().
meshWillBeDestroyed
Action<ProBuilderMesh> UnityEngine.ProBuilder.ProBuilderMesh.meshWillBeDestroyed static
Invoked when this ProBuilderMesh is deleted.
In the Editor, when a ProBuilderMesh is destroyed it also destroys the UnityEngine.MeshFilter.sharedMesh that it finds with the parent GameObject. To override the default behavior, subscribe to onDestroyObject. When onDestroyObject has a subscriber, ProBuilder invokes it instead of cleaning up unused meshes by itself.
See also
preserveMeshAssetOnDestroy, OnDestroy
The documentation for this class was generated from the following files:
C:/Users/Lykos/Desktop/Projects/Capstone/VRGames/Library/PackageCache/com.unity.probuilder@5.0.6/Runtime/Core/ProBuilderMesh.cs
C:/Users/Lykos/Desktop/Projects/Capstone/VRGames/Library/PackageCache/com.unity.probuilder@5.0.6/Runtime/Core/ProBuilderMeshFunction.cs
C:/Users/Lykos/Desktop/Projects/Capstone/VRGames/Library/PackageCache/com.unity.probuilder@5.0.6/Runtime/Core/ProBuilderMeshSelection.cs