VRGames: UnityEditor.ProBuilder.ShapeState Class Reference
UnityEditor.ProBuilder.ShapeState Class Reference abstract
Public Member Functions
ShapeState DoState (Event evt)
Static Public Member Functions
static ShapeState StartStateMachine ()
static ShapeState ResetState ()
Public Attributes
ShapeState m_nextState = null
Static Public Attributes
static ShapeState s_defaultState
static DrawShapeTool tool
Protected Member Functions
virtual void InitState ()
virtual void EndState ()
virtual ShapeState NextState ()
Member Function Documentation
DoState()
ShapeState UnityEditor.ProBuilder.ShapeState.DoState (Event evt) abstract
Referenced by UnityEditor.ProBuilder.DrawShapeTool.OnToolGUI().
EndState()
virtual void UnityEditor.ProBuilder.ShapeState.EndState () protected virtual
Referenced by UnityEditor.ProBuilder.ShapeState.NextState().
InitState()
virtual void UnityEditor.ProBuilder.ShapeState.InitState () protected virtual
Referenced by UnityEditor.ProBuilder.ShapeState.NextState().
NextState()
virtual ShapeState UnityEditor.ProBuilder.ShapeState.NextState () protected virtual
ResetState()
static ShapeState UnityEditor.ProBuilder.ShapeState.ResetState () static
Referenced by UnityEditor.ProBuilder.ShapeState.NextState().
StartStateMachine()
static ShapeState UnityEditor.ProBuilder.ShapeState.StartStateMachine () static
Member Data Documentation
m_nextState
ShapeState UnityEditor.ProBuilder.ShapeState.m_nextState = null
Referenced by UnityEditor.ProBuilder.ShapeState.NextState().
s_defaultState
ShapeState UnityEditor.ProBuilder.ShapeState.s_defaultState static
Referenced by UnityEditor.ProBuilder.ShapeState.ResetState(), and UnityEditor.ProBuilder.ShapeState.StartStateMachine().
tool
DrawShapeTool UnityEditor.ProBuilder.ShapeState.tool static
Referenced by UnityEditor.ProBuilder.ShapeState.ResetState(), and UnityEditor.ProBuilder.ShapeState.StartStateMachine().
The documentation for this class was generated from the following file:
C:/Users/Lykos/Desktop/Projects/Capstone/VRGames/Library/PackageCache/com.unity.probuilder@5.0.6/Editor/StateMachines/ShapeState.cs