VRCapstoneGames: Oculus.Interaction.Surfaces.PointablePlane Class Reference
Oculus.Interaction.Surfaces.PointablePlane Class Reference
Public Types
enum NormalFacing { Backward , Forward }
Public Member Functions
Vector2 GetSurfaceDistanceBetween (Vector3 worldPoint0, Vector3 worldPoint1)
Find the distance between two world space surface points in the surface's frame of reference.
bool IsPointAboveSurface (Vector3 point)
Check if a point is on the normal-side of the collider (is raycast hit possible from this origin point)
bool ClosestSurfacePoint (in Vector3 point, out SurfaceHit hit, float maxDistance)
Find nearest point to surface.
bool Raycast (in Ray ray, out SurfaceHit hit, float maxDistance)
Raycast to the surface with an optional maximum distance value.
Plane GetPlane ()
void InjectAllPointablePlane (NormalFacing facing, bool doubleSided)
void InjectNormalFacing (NormalFacing facing)
void InjectDoubleSided (bool doubleSided)
Properties
NormalFacing Facing [get, set]
bool DoubleSided [get, set]
Vector3 Normal [get]
Member Enumeration Documentation
NormalFacing
enum Oculus.Interaction.Surfaces.PointablePlane.NormalFacing
Enumerator
Backward
Normal faces along the transform's negative Z axis.
Forward
Normal faces along the transform's positive Z axis.
Member Function Documentation
ClosestSurfacePoint()
bool Oculus.Interaction.Surfaces.PointablePlane.ClosestSurfacePoint (in Vector3 point, out SurfaceHit hit, float maxDistance)
Find nearest point to surface.
Parameters
ray Point to check
hit The returned hit data
maxDistance If greater than zero, maximum distance of check
Returns
true if nearest point was found
Implements Oculus.Interaction.Surfaces.IPointableSurface.
Referenced by Oculus.Interaction.Editor.PointablePlaneEditor.Draw().
GetPlane()
Plane Oculus.Interaction.Surfaces.PointablePlane.GetPlane ()
Referenced by Oculus.Interaction.Surfaces.PointablePlane.ClosestSurfacePoint(), Oculus.Interaction.Surfaces.PointablePlane.IsPointAboveSurface(), and Oculus.Interaction.Surfaces.PointablePlane.Raycast().
GetSurfaceDistanceBetween()
Vector2 Oculus.Interaction.Surfaces.PointablePlane.GetSurfaceDistanceBetween (Vector3 worldPoint0, Vector3 worldPoint1)
Find the distance between two world space surface points in the surface's frame of reference.
Parameters
worldPoint0 World point on surface
worldPoint1 World point on surface
Returns
Vector2(Horizontal delta, Vertical delta)
Implements Oculus.Interaction.Surfaces.IPointableSurface.
InjectAllPointablePlane()
void Oculus.Interaction.Surfaces.PointablePlane.InjectAllPointablePlane (NormalFacing facing, bool doubleSided)
InjectDoubleSided()
void Oculus.Interaction.Surfaces.PointablePlane.InjectDoubleSided (bool doubleSided)
Referenced by Oculus.Interaction.Surfaces.PointablePlane.InjectAllPointablePlane().
InjectNormalFacing()
void Oculus.Interaction.Surfaces.PointablePlane.InjectNormalFacing (NormalFacing facing)
Referenced by Oculus.Interaction.Surfaces.PointablePlane.InjectAllPointablePlane().
IsPointAboveSurface()
bool Oculus.Interaction.Surfaces.PointablePlane.IsPointAboveSurface (Vector3 point)
Check if a point is on the normal-side of the collider (is raycast hit possible from this origin point)
Parameters
point The point to check
Returns
True when above the surface
Implements Oculus.Interaction.Surfaces.IPointableSurface.
Referenced by Oculus.Interaction.Surfaces.PointablePlane.ClosestSurfacePoint(), and Oculus.Interaction.Surfaces.PointablePlane.Raycast().
Raycast()
bool Oculus.Interaction.Surfaces.PointablePlane.Raycast (in Ray ray, out SurfaceHit hit, float maxDistance)
Raycast to the surface with an optional maximum distance value.
Parameters
ray The ray to cast
hit The returned hit data
maxDistance If greater than zero, maximum distance of raycast
Returns
true if surface was hit
Implements Oculus.Interaction.Surfaces.IPointableSurface.
Property Documentation
DoubleSided
bool Oculus.Interaction.Surfaces.PointablePlane.DoubleSided get set
Facing
NormalFacing Oculus.Interaction.Surfaces.PointablePlane.Facing get set
Normal
Vector3 Oculus.Interaction.Surfaces.PointablePlane.Normal get
Referenced by Oculus.Interaction.Editor.PointablePlaneEditor.Draw(), and Oculus.Interaction.Surfaces.PointablePlane.GetPlane().
The documentation for this class was generated from the following file:
C:/Users/Lykos/Desktop/Projects/Capstone/VRGames/Assets/ThirdParty/Oculus/Interaction/Runtime/Scripts/Interaction/Surfaces/PointablePlane.cs