VRCapstoneGames: Oculus.Interaction.UnityCanvas.CanvasRenderTexture Class Reference
Oculus.Interaction.UnityCanvas.CanvasRenderTexture Class Reference
Classes
class Properties
Public Types
enum DriveMode { Auto , Manual }
Public Member Functions
bool UseEditorEmulation ()
Vector2Int CalcAutoResolution ()
Vector2Int GetBaseResolutionToUse ()
Vector2Int GetScaledResolutionToUse ()
float PixelsToUnits (float pixels)
float UnitsToPixels (float units)
void InjectAllCanvasRenderTexture (int pixelsPerUnit, int renderScale, LayerMask renderingLayers, RenderingMode renderingMode, bool doUnderlayAntiAliasing, float alphaCutoutThreshold, bool useAlphaToMask)
void InjectPixelsPerUnit (int pixelsPerUnit)
void InjectRenderScale (int renderScale)
void InjectRenderingMode (RenderingMode renderingMode)
void InjectRenderingLayers (LayerMask renderingLayers)
void InjectDoUnderlayAntiAliasing (bool doUnderlayAntiAliasing)
void InjectUseAlphaToMask (bool useAlphaToMask)
void InjectAlphaCutoutThreshold (float alphaCutoutThreshold)
void InjectOptionalDefaultUIMaterial (Material defaultUIMaterial)
void InjectOptionalGenerateMipMaps (bool generateMipMaps)
Public Member Functions inherited from UnityEngine.EventSystems.UIBehaviour
virtual bool IsActive ()
Returns true if the GameObject and the Component are active.
bool IsDestroyed ()
Returns true if the native representation of the behaviour has been destroyed.
Public Attributes
Action< Texture > OnUpdateRenderTexture = delegate { }
Static Public Attributes
const int DEFAULT_UI_LAYERMASK = 1 << 5
Protected Member Functions
override void OnRectTransformDimensionsChange ()
This callback is called when the dimensions of an associated RectTransform change. It is always called before Awake, OnEnable, or Start. The call is also made to all child RectTransforms, regardless of whether their dimensions change (which depends on how they are anchored).
override void Start ()
override void OnEnable ()
override void OnDisable ()
void UpdateCamera ()
void UpdateRenderTexture ()
GameObject CreateChildObject (string name)
Protected Member Functions inherited from UnityEngine.EventSystems.UIBehaviour
virtual void Awake ()
virtual void OnDestroy ()
virtual void OnBeforeTransformParentChanged ()
virtual void OnTransformParentChanged ()
virtual void OnDidApplyAnimationProperties ()
virtual void OnCanvasGroupChanged ()
virtual void OnCanvasHierarchyChanged ()
Called when the state of the parent Canvas is changed.
Protected Attributes
bool _enableSuperSampling = true
bool _started = false
Properties
RenderingMode RenderingMode [get]
LayerMask RenderingLayers [get]
bool UseAlphaToMask [get]
bool DoUnderlayAntiAliasing [get]
bool EnableSuperSampling [get]
float AlphaCutoutThreshold [get]
int RenderScale [get, set]
Material DefaultUIMaterial [get]
Camera OverlayCamera [get]
Texture Texture [get]
bool ShouldUseOVROverlay [get]
Member Enumeration Documentation
DriveMode
enum Oculus.Interaction.UnityCanvas.CanvasRenderTexture.DriveMode
Enumerator
Auto
Manual
Member Function Documentation
CalcAutoResolution()
Vector2Int Oculus.Interaction.UnityCanvas.CanvasRenderTexture.CalcAutoResolution ()
Referenced by Oculus.Interaction.UnityCanvas.CanvasRenderTexture.GetBaseResolutionToUse().
CreateChildObject()
GameObject Oculus.Interaction.UnityCanvas.CanvasRenderTexture.CreateChildObject (string name) protected
Referenced by Oculus.Interaction.UnityCanvas.CanvasRenderTexture.UpdateCamera().
GetBaseResolutionToUse()
Vector2Int Oculus.Interaction.UnityCanvas.CanvasRenderTexture.GetBaseResolutionToUse ()
Referenced by Oculus.Interaction.UnityCanvas.CanvasRect.GenerateMesh(), Oculus.Interaction.UnityCanvas.CanvasRenderTexture.GetScaledResolutionToUse(), Oculus.Interaction.UnityCanvas.CanvasCylinder.UpdateOverlayPositionAndScale(), and Oculus.Interaction.UnityCanvas.CanvasRect.UpdateOverlayPositionAndScale().
GetScaledResolutionToUse()
Vector2Int Oculus.Interaction.UnityCanvas.CanvasRenderTexture.GetScaledResolutionToUse ()
Referenced by Oculus.Interaction.UnityCanvas.CanvasRenderTexture.UpdateRenderTexture().
InjectAllCanvasRenderTexture()
void Oculus.Interaction.UnityCanvas.CanvasRenderTexture.InjectAllCanvasRenderTexture (int pixelsPerUnit, int renderScale, LayerMask renderingLayers, RenderingMode renderingMode, bool doUnderlayAntiAliasing, float alphaCutoutThreshold, bool useAlphaToMask)
InjectAlphaCutoutThreshold()
void Oculus.Interaction.UnityCanvas.CanvasRenderTexture.InjectAlphaCutoutThreshold (float alphaCutoutThreshold)
Referenced by Oculus.Interaction.UnityCanvas.CanvasRenderTexture.InjectAllCanvasRenderTexture().
InjectDoUnderlayAntiAliasing()
void Oculus.Interaction.UnityCanvas.CanvasRenderTexture.InjectDoUnderlayAntiAliasing (bool doUnderlayAntiAliasing)
Referenced by Oculus.Interaction.UnityCanvas.CanvasRenderTexture.InjectAllCanvasRenderTexture().
InjectOptionalDefaultUIMaterial()
void Oculus.Interaction.UnityCanvas.CanvasRenderTexture.InjectOptionalDefaultUIMaterial (Material defaultUIMaterial)
InjectOptionalGenerateMipMaps()
void Oculus.Interaction.UnityCanvas.CanvasRenderTexture.InjectOptionalGenerateMipMaps (bool generateMipMaps)
InjectPixelsPerUnit()
void Oculus.Interaction.UnityCanvas.CanvasRenderTexture.InjectPixelsPerUnit (int pixelsPerUnit)
Referenced by Oculus.Interaction.UnityCanvas.CanvasRenderTexture.InjectAllCanvasRenderTexture().
InjectRenderingLayers()
void Oculus.Interaction.UnityCanvas.CanvasRenderTexture.InjectRenderingLayers (LayerMask renderingLayers)
Referenced by Oculus.Interaction.UnityCanvas.CanvasRenderTexture.InjectAllCanvasRenderTexture().
InjectRenderingMode()
void Oculus.Interaction.UnityCanvas.CanvasRenderTexture.InjectRenderingMode (RenderingMode renderingMode)
Referenced by Oculus.Interaction.UnityCanvas.CanvasRenderTexture.InjectAllCanvasRenderTexture().
InjectRenderScale()
void Oculus.Interaction.UnityCanvas.CanvasRenderTexture.InjectRenderScale (int renderScale)
Referenced by Oculus.Interaction.UnityCanvas.CanvasRenderTexture.InjectAllCanvasRenderTexture().
InjectUseAlphaToMask()
void Oculus.Interaction.UnityCanvas.CanvasRenderTexture.InjectUseAlphaToMask (bool useAlphaToMask)
Referenced by Oculus.Interaction.UnityCanvas.CanvasRenderTexture.InjectAllCanvasRenderTexture().
OnDisable()
override void Oculus.Interaction.UnityCanvas.CanvasRenderTexture.OnDisable () protected virtual
Reimplemented from UnityEngine.EventSystems.UIBehaviour.
OnEnable()
override void Oculus.Interaction.UnityCanvas.CanvasRenderTexture.OnEnable () protected virtual
Reimplemented from UnityEngine.EventSystems.UIBehaviour.
OnRectTransformDimensionsChange()
override void Oculus.Interaction.UnityCanvas.CanvasRenderTexture.OnRectTransformDimensionsChange () protected virtual
This callback is called when the dimensions of an associated RectTransform change. It is always called before Awake, OnEnable, or Start. The call is also made to all child RectTransforms, regardless of whether their dimensions change (which depends on how they are anchored).
Reimplemented from UnityEngine.EventSystems.UIBehaviour.
PixelsToUnits()
float Oculus.Interaction.UnityCanvas.CanvasRenderTexture.PixelsToUnits (float pixels)
Referenced by Oculus.Interaction.UnityCanvas.CanvasRect.GenerateMesh(), Oculus.Interaction.UnityCanvas.CanvasCylinder.UpdateOverlayPositionAndScale(), and Oculus.Interaction.UnityCanvas.CanvasRect.UpdateOverlayPositionAndScale().
Start()
override void Oculus.Interaction.UnityCanvas.CanvasRenderTexture.Start () protected virtual
Reimplemented from UnityEngine.EventSystems.UIBehaviour.
UnitsToPixels()
float Oculus.Interaction.UnityCanvas.CanvasRenderTexture.UnitsToPixels (float units)
Referenced by Oculus.Interaction.UnityCanvas.CanvasRenderTexture.CalcAutoResolution().
UpdateCamera()
void Oculus.Interaction.UnityCanvas.CanvasRenderTexture.UpdateCamera () protected
Referenced by Oculus.Interaction.UnityCanvas.CanvasRenderTexture.OnEnable(), and Oculus.Interaction.UnityCanvas.CanvasRenderTexture.OnRectTransformDimensionsChange().
UpdateRenderTexture()
void Oculus.Interaction.UnityCanvas.CanvasRenderTexture.UpdateRenderTexture () protected
Referenced by Oculus.Interaction.UnityCanvas.CanvasRenderTexture.UpdateCamera().
UseEditorEmulation()
bool Oculus.Interaction.UnityCanvas.CanvasRenderTexture.UseEditorEmulation ()
Referenced by Oculus.Interaction.UnityCanvas.CanvasRenderTextureMesh.CreateMaterial(), and Oculus.Interaction.UnityCanvas.CanvasRenderTextureMesh.HandleUpdateRenderTexture().
Member Data Documentation
_enableSuperSampling
bool Oculus.Interaction.UnityCanvas.CanvasRenderTexture._enableSuperSampling = true protected
_started
bool Oculus.Interaction.UnityCanvas.CanvasRenderTexture._started = false protected
Referenced by Oculus.Interaction.UnityCanvas.CanvasRenderTexture.OnDisable(), Oculus.Interaction.UnityCanvas.CanvasRenderTexture.OnEnable(), Oculus.Interaction.UnityCanvas.CanvasRenderTexture.OnRectTransformDimensionsChange(), and Oculus.Interaction.UnityCanvas.CanvasRenderTexture.Start().
DEFAULT_UI_LAYERMASK
const int Oculus.Interaction.UnityCanvas.CanvasRenderTexture.DEFAULT_UI_LAYERMASK = 1 << 5 static
Referenced by Oculus.Interaction.UnityCanvas.Editor.CanvasRenderTextureEditor.AutoFixAssignUIToMask().
OnUpdateRenderTexture
Action<Texture> Oculus.Interaction.UnityCanvas.CanvasRenderTexture.OnUpdateRenderTexture = delegate { }
Referenced by Oculus.Interaction.UnityCanvas.CanvasRenderTexture.UpdateRenderTexture().
Property Documentation
AlphaCutoutThreshold
float Oculus.Interaction.UnityCanvas.CanvasRenderTexture.AlphaCutoutThreshold get
Referenced by Oculus.Interaction.UnityCanvas.CanvasRenderTextureMesh.HandleUpdateRenderTexture().
DefaultUIMaterial
Material Oculus.Interaction.UnityCanvas.CanvasRenderTexture.DefaultUIMaterial get
DoUnderlayAntiAliasing
bool Oculus.Interaction.UnityCanvas.CanvasRenderTexture.DoUnderlayAntiAliasing get
Referenced by Oculus.Interaction.UnityCanvas.CanvasRenderTextureMesh.CreateMaterial().
EnableSuperSampling
bool Oculus.Interaction.UnityCanvas.CanvasRenderTexture.EnableSuperSampling get
Referenced by Oculus.Interaction.UnityCanvas.CanvasRenderTextureMesh.UpdateOverlay().
OverlayCamera
Camera Oculus.Interaction.UnityCanvas.CanvasRenderTexture.OverlayCamera get
RenderingLayers
LayerMask Oculus.Interaction.UnityCanvas.CanvasRenderTexture.RenderingLayers get
RenderingMode
RenderingMode Oculus.Interaction.UnityCanvas.CanvasRenderTexture.RenderingMode get
Referenced by Oculus.Interaction.UnityCanvas.CanvasRenderTextureMesh.CreateMaterial(), and Oculus.Interaction.UnityCanvas.CanvasRenderTextureMesh.HandleUpdateRenderTexture().
RenderScale
int Oculus.Interaction.UnityCanvas.CanvasRenderTexture.RenderScale get set
ShouldUseOVROverlay
bool Oculus.Interaction.UnityCanvas.CanvasRenderTexture.ShouldUseOVROverlay get
Referenced by Oculus.Interaction.UnityCanvas.CanvasRenderTextureMesh.UpdateOverlay(), and Oculus.Interaction.UnityCanvas.CanvasRenderTexture.UpdateRenderTexture().
Texture
Texture Oculus.Interaction.UnityCanvas.CanvasRenderTexture.Texture get
Referenced by Oculus.Interaction.UnityCanvas.CanvasRenderTextureMesh.HandleUpdateRenderTexture(), and Oculus.Interaction.UnityCanvas.CanvasRenderTextureMesh.OnEnable().
UseAlphaToMask
bool Oculus.Interaction.UnityCanvas.CanvasRenderTexture.UseAlphaToMask get
Referenced by Oculus.Interaction.UnityCanvas.CanvasRenderTextureMesh.CreateMaterial(), and Oculus.Interaction.UnityCanvas.CanvasRenderTextureMesh.HandleUpdateRenderTexture().
The documentation for this class was generated from the following file:
C:/Users/Lykos/Desktop/Projects/Capstone/VRGames/Assets/ThirdParty/Oculus/Interaction/Runtime/Scripts/Unity/UnityCanvas/CanvasRenderTexture.cs