VRCapstoneGames: UnityEngine.InputSystem.Processors.NormalizeProcessor Class Reference
UnityEngine.InputSystem.Processors.NormalizeProcessor Class Reference
Normalizes input values in the range min and max to unsigned normalized form [0..1] if zero is placed at (or below) min or to signed normalized form [-1..1] if zero is placed in-between min and max.
Public Member Functions
override float Process (float value, InputControl control)
Normalize value with respect to min and max.
override string ToString ()
Public Member Functions inherited from UnityEngine.InputSystem.InputProcessor< float >
object ProcessAsObject (object value, InputControl control)
Process an input value, given as an object, and return the processed value as an object.
override object ProcessAsObject (object value, InputControl control)
unsafe void Process (void *buffer, int bufferSize, InputControl control)
TValue Process (TValue value, InputControl control)
Process the given value and return the result.
override unsafe void Process (void *buffer, int bufferSize, InputControl control)
Static Public Member Functions
static float Normalize (float value, float min, float max, float zero)
Normalize value with respect to min and max .
Public Attributes
float min
Input value (inclusive) that corresponds to 0 or -1 (depending on zero), the lower bound.
float max
Input value (inclusive) that corresponds to 1, the upper bound.
float zero
Input value that corresponds to 0. If this is placed at or below min, the resulting normalization returns a [0..1] value. If this is placed in-between min and max, the resulting normalization returns a [-1..1] value.
Detailed Description
Normalizes input values in the range min and max to unsigned normalized form [0..1] if zero is placed at (or below) min or to signed normalized form [-1..1] if zero is placed in-between min and max.
This processor is registered (see InputSystem.RegisterProcessor<T>) under the name "normalize".
Note that this processor does not clamp the incoming value to min and max. To achieve this, either add a ClampProcessor or use AxisDeadzoneProcessor which combines clamping and normalizing.
// Bind to right trigger on gamepad such that the value values below 0.3 and above 0.7 get normalized // to values between [0..1]. new InputAction(binding: "&lt;Gamepad&gt;/rightTrigger", processors: "normalize(min=0.3,max=0.7)");
See also
NormalizeVector2Processor, NormalizeVector3Processor
Member Function Documentation
Normalize()
static float UnityEngine.InputSystem.Processors.NormalizeProcessor.Normalize (float value, float min, float max, float zero) static
Normalize value with respect to min and max .
Parameters
value Input value.
min Lower bound. See min.
max Upper bound. See max.
zero Zero point. See zero.
Returns
Normalized value.
This method performs the same function as Process.
// Normalize 2 against a [1..5] range. Returns 0.25.
NormalizeProcessor.Normalize(2, 1, 5, 1)
Referenced by UnityEngine.InputSystem.Composites.AxisComposite.EvaluateMagnitude(), UnityEngine.InputSystem.Controls.AxisControl.EvaluateMagnitude(), UnityEngine.InputSystem.Controls.AxisControl.Preprocess(), and UnityEngine.InputSystem.Processors.NormalizeProcessor.Process().
Process()
override float UnityEngine.InputSystem.Processors.NormalizeProcessor.Process (float value, InputControl control)
Normalize value with respect to min and max.
Parameters
value Input value.
control Ignored.
Returns
Normalized value.
ToString()
override string UnityEngine.InputSystem.Processors.NormalizeProcessor.ToString ()
Member Data Documentation
max
float UnityEngine.InputSystem.Processors.NormalizeProcessor.max
Input value (inclusive) that corresponds to 1, the upper bound.
If the input value goes beyond max, the result is undefined.
Referenced by UnityEngine.InputSystem.Processors.NormalizeProcessor.Normalize(), and UnityEngine.InputSystem.Processors.NormalizeProcessor.Process().
min
float UnityEngine.InputSystem.Processors.NormalizeProcessor.min
Input value (inclusive) that corresponds to 0 or -1 (depending on zero), the lower bound.
If the input value drops below min, the result is undefined.
Referenced by UnityEngine.InputSystem.Processors.NormalizeProcessor.Normalize(), and UnityEngine.InputSystem.Processors.NormalizeProcessor.Process().
zero
float UnityEngine.InputSystem.Processors.NormalizeProcessor.zero
Input value that corresponds to 0. If this is placed at or below min, the resulting normalization returns a [0..1] value. If this is placed in-between min and max, the resulting normalization returns a [-1..1] value.
Referenced by UnityEngine.InputSystem.Processors.NormalizeProcessor.Normalize(), and UnityEngine.InputSystem.Processors.NormalizeProcessor.Process().
The documentation for this class was generated from the following file:
C:/Users/Lykos/Desktop/Projects/Capstone/VRGames/Library/PackageCache/com.unity.inputsystem@1.3.0/InputSystem/Controls/Processors/NormalizeProcessor.cs