VRGames: Oculus.Interaction.Input.SyntheticHand Class Reference
Oculus.Interaction.Input.SyntheticHand Class Reference
Alters hand data piped into this modifier to lock and unlock joints (wrist position and rotation, finger joint rotations) When switching between locked and unlocked states, additionally smooths out transitions by easing between source hand data and target hand data.
Public Types
enum WristLockMode { Position = 1 << 0 , Rotation = 1 << 1 , Full = (1 << 2) - 1 }
Public Member Functions
void OverrideAllJoints (in Quaternion[] jointRotations, float overrideFactor)
Stores the rotation data for all joints in the hand, to be applied during the ApplyHand event.
void OverrideFingerRotations (HandFinger finger, Quaternion[] rotations, float overrideFactor)
Stores the rotation data for all joints for the given finger, to be applied during the ApplyHand event.
void OverrideJointRotation (HandJointId jointId, Quaternion rotation, float overrideFactor)
void LockFingerAtCurrent (in HandFinger finger)
Immediately locks an individual finger (all its internal joints) at the last known value.
void LockJoint (in HandJointId jointId, Quaternion rotation, float overrideFactor=1f)
void SetFingerFreedom (in HandFinger finger, in JointFreedom freedomLevel, bool skipAnimation=false)
To use in conjunction with OverrideAllJoints, it sets the freedom state for a provided finger. Opposite to LockFingerAtCurrent, this method uses the data provided in OverrideAllJoints instead of the last known state.
void SetJointFreedom (in HandJointId jointId, in JointFreedom freedomLevel, bool skipAnimation=false)
JointFreedom GetJointFreedom (in HandJointId jointId)
void FreeAllJoints ()
Short-hand method for setting the freedom level of all fingers in a hand to Free. Similar to calling SetFingerFreedom for each single finger in the hand with a value of FingerFreedom.Free for the freedomLevel.
void LockWristPose (Pose wristPose, float overrideFactor=1f, WristLockMode lockMode=WristLockMode.Full, bool worldPose=false, bool skipAnimation=false)
Stores the desired pose to set the wrist of the hand to. This is not necessarily the final pose of the hand, as it allows lerping between the tracked and provided one during the ApplyHand phase.
void LockWristPosition (Vector3 position, float overrideFactor=1f, bool skipAnimation=false)
void LockWristRotation (Quaternion rotation, float overrideFactor=1f, bool skipAnimation=false)
void FreeWrist (WristLockMode lockMode=WristLockMode.Full)
Unlocks the hand (locked at the OverrideWristPose method) starting a timer for the smooth release animation.
void InjectAllSyntheticHandModifier (UpdateModeFlags updateMode, IDataSource updateAfter, DataModifier< HandDataAsset > modifyDataFromSource, bool applyModifier, Component[] aspects, ProgressCurve wristPositionLockCurve, ProgressCurve wristPositionUnlockCurve, ProgressCurve wristRotationLockCurve, ProgressCurve wristRotationUnlockCurve, ProgressCurve jointLockCurve, ProgressCurve jointUnlockCurve, float spreadAllowance)
void InjectWristPositionLockCurve (ProgressCurve wristPositionLockCurve)
void InjectWristPositionUnlockCurve (ProgressCurve wristPositionUnlockCurve)
void InjectWristRotationLockCurve (ProgressCurve wristRotationLockCurve)
void InjectWristRotationUnlockCurve (ProgressCurve wristRotationUnlockCurve)
void InjectJointLockCurve (ProgressCurve jointLockCurve)
void InjectJointUnlockCurve (ProgressCurve jointUnlockCurve)
void InjectSpreadAllowance (float spreadAllowance)
Public Member Functions inherited from Oculus.Interaction.Input.Hand
override void MarkInputDataRequiresUpdate ()
bool GetFingerIsPinching (HandFinger finger)
bool GetIndexFingerIsPinching ()
bool GetPointerPose (out Pose pose)
Attempts to calculate the pose that can be used as a root for raycasting, in world space Returns false if there is no valid tracking data.
bool GetJointPose (HandJointId handJointId, out Pose pose)
Attempts to calculate the pose of the requested hand joint, in world space. Returns false if the skeleton is not yet initialized, or there is no valid tracking data.
bool GetJointPoseLocal (HandJointId handJointId, out Pose pose)
Attempts to calculate the pose of the requested hand joint, in local space. Returns false if the skeleton is not yet initialized, or there is no valid tracking data.
bool GetJointPosesLocal (out ReadOnlyHandJointPoses localJointPoses)
Returns an array containing the local pose of each joint. The poses do not have the root pose applied, nor the hand scale. It is in the same coordinate system as the hand skeleton.
bool GetJointPoseFromWrist (HandJointId handJointId, out Pose pose)
Attempts to calculate the pose of the requested hand joint relative to the wrist. Returns false if the skeleton is not yet initialized, or there is no valid tracking data.
bool GetJointPosesFromWrist (out ReadOnlyHandJointPoses jointPosesFromWrist)
Returns an array containing the pose of each joint relative to the wrist. The poses do not have the root pose applied, nor the hand scale. It is in the same coordinate system as the hand skeleton.
bool GetPalmPoseLocal (out Pose pose)
Obtains palm pose in local space.
bool GetFingerIsHighConfidence (HandFinger finger)
float GetFingerPinchStrength (HandFinger finger)
bool GetRootPose (out Pose pose)
Gets the root pose of the wrist, in world space. Will return true if a pose was available; false otherwise. Confidence level of the pose is exposed via IsHighConfidence.
bool GetCenterEyePose (out Pose pose)
Gets the pose of the center eye (HMD), in world space. Will return true if a pose was available; false otherwise.
bool GetHandAspect< TComponent > (out TComponent foundComponent)
An Aspect provides additional functionality on top of what the HandState provides. The underlying hand is responsible for finding the most appropriate component. It is usually, but not necessarily, located within the same GameObject as the underlying hand. For example, this method can be used to source the SkinnedMeshRenderer representing the hand, if one exists.
Returns
true if an aspect of the requested type was found, false otherwise
void InjectAllHand (UpdateModeFlags updateMode, IDataSource updateAfter, DataModifier< HandDataAsset > modifyDataFromSource, bool applyModifier, Component[] aspects)
void InjectAspects (Component[] aspects)
Public Member Functions inherited from Oculus.Interaction.Input.DataModifier< HandDataAsset >
void ResetSources (IDataSource< TData > modifyDataFromSource, IDataSource updateAfter, UpdateModeFlags updateMode)
void InjectAllDataModifier (UpdateModeFlags updateMode, IDataSource updateAfter, IDataSource< TData > modifyDataFromSource, bool applyModifier)
void InjectModifyDataFromSource (IDataSource< TData > modifyDataFromSource)
void InjectApplyModifier (bool applyModifier)
Public Attributes
System.Action UpdateRequired = delegate { }
Protected Member Functions
override void Start ()
override void Apply (HandDataAsset data)
Protected Member Functions inherited from Oculus.Interaction.Input.Hand
override void Apply (HandDataAsset data)
Protected Member Functions inherited from Oculus.Interaction.Input.DataModifier< HandDataAsset >
override void UpdateData ()
void Apply (TData data)
override void Start ()
Additional Inherited Members
Protected Attributes inherited from Oculus.Interaction.Input.DataModifier< HandDataAsset >
MonoBehaviour _iModifyDataFromSourceMono
Properties inherited from Oculus.Interaction.Input.Hand
IReadOnlyList< Component > Aspects [get]
Handedness Handedness [get]
ITrackingToWorldTransformer TrackingToWorldTransformer [get]
HandSkeleton HandSkeleton [get]
IDataSource< HmdDataAsset > HmdData [get]
bool IsConnected [get]
bool IsHighConfidence [get]
The hand is connected and tracked, and the root pose's tracking data is marked as high confidence. If this is true, then it implies that IsConnected and IsRootPoseValid are also true, so they don't need to be checked in addition to this.
bool IsDominantHand [get]
float Scale [get]
bool IsPointerPoseValid [get]
Will return true if a pointer pose is available, that can be retrieved via GetPointerPose
bool IsTrackedDataValid [get]
True if the hand is currently tracked, thus tracking poses are available for the hand root and finger joints. This property does not indicate pointing pose validity, which has its own property: IsPointerPoseValid.
bool IsCenterEyePoseValid [get]
Will return true if an HMD Center Eye pose available, that can be retrieved via GetCenterEyePose
Transform TrackingToWorldSpace [get]
The transform that was applied to all tracking space poses to convert them to world space.
Properties inherited from Oculus.Interaction.Input.DataModifier< HandDataAsset >
override TData DataAsset [get]
virtual IDataSource< TData > ModifyDataFromSource [get]
override int CurrentDataVersion [get]
Properties inherited from Oculus.Interaction.Input.IHand
int CurrentDataVersion [get]
Incremented every time the source tracking or state data changes.
Events inherited from Oculus.Interaction.Input.Hand
Action WhenHandUpdated = delegate { }
Events inherited from Oculus.Interaction.Input.IHand
Action WhenHandUpdated
Detailed Description
Alters hand data piped into this modifier to lock and unlock joints (wrist position and rotation, finger joint rotations) When switching between locked and unlocked states, additionally smooths out transitions by easing between source hand data and target hand data.
Member Enumeration Documentation
WristLockMode
enum Oculus.Interaction.Input.SyntheticHand.WristLockMode
Enumerator
Position
Rotation
Full
Member Function Documentation
Apply()
override void Oculus.Interaction.Input.SyntheticHand.Apply (HandDataAsset data) protected
FreeAllJoints()
void Oculus.Interaction.Input.SyntheticHand.FreeAllJoints ()
Short-hand method for setting the freedom level of all fingers in a hand to Free. Similar to calling SetFingerFreedom for each single finger in the hand with a value of FingerFreedom.Free for the freedomLevel.
FreeWrist()
void Oculus.Interaction.Input.SyntheticHand.FreeWrist (WristLockMode lockMode = WristLockMode::Full)
Unlocks the hand (locked at the OverrideWristPose method) starting a timer for the smooth release animation.
GetJointFreedom()
JointFreedom Oculus.Interaction.Input.SyntheticHand.GetJointFreedom (in HandJointId jointId)
InjectAllSyntheticHandModifier()
void Oculus.Interaction.Input.SyntheticHand.InjectAllSyntheticHandModifier (UpdateModeFlags updateMode, IDataSource updateAfter, DataModifier< HandDataAsset > modifyDataFromSource, bool applyModifier, Component[] aspects, ProgressCurve wristPositionLockCurve, ProgressCurve wristPositionUnlockCurve, ProgressCurve wristRotationLockCurve, ProgressCurve wristRotationUnlockCurve, ProgressCurve jointLockCurve, ProgressCurve jointUnlockCurve, float spreadAllowance)
InjectJointLockCurve()
void Oculus.Interaction.Input.SyntheticHand.InjectJointLockCurve (ProgressCurve jointLockCurve)
Referenced by Oculus.Interaction.Input.SyntheticHand.InjectAllSyntheticHandModifier().
InjectJointUnlockCurve()
void Oculus.Interaction.Input.SyntheticHand.InjectJointUnlockCurve (ProgressCurve jointUnlockCurve)
Referenced by Oculus.Interaction.Input.SyntheticHand.InjectAllSyntheticHandModifier().
InjectSpreadAllowance()
void Oculus.Interaction.Input.SyntheticHand.InjectSpreadAllowance (float spreadAllowance)
Referenced by Oculus.Interaction.Input.SyntheticHand.InjectAllSyntheticHandModifier().
InjectWristPositionLockCurve()
void Oculus.Interaction.Input.SyntheticHand.InjectWristPositionLockCurve (ProgressCurve wristPositionLockCurve)
Referenced by Oculus.Interaction.Input.SyntheticHand.InjectAllSyntheticHandModifier().
InjectWristPositionUnlockCurve()
void Oculus.Interaction.Input.SyntheticHand.InjectWristPositionUnlockCurve (ProgressCurve wristPositionUnlockCurve)
Referenced by Oculus.Interaction.Input.SyntheticHand.InjectAllSyntheticHandModifier().
InjectWristRotationLockCurve()
void Oculus.Interaction.Input.SyntheticHand.InjectWristRotationLockCurve (ProgressCurve wristRotationLockCurve)
Referenced by Oculus.Interaction.Input.SyntheticHand.InjectAllSyntheticHandModifier().
InjectWristRotationUnlockCurve()
void Oculus.Interaction.Input.SyntheticHand.InjectWristRotationUnlockCurve (ProgressCurve wristRotationUnlockCurve)
Referenced by Oculus.Interaction.Input.SyntheticHand.InjectAllSyntheticHandModifier().
LockFingerAtCurrent()
void Oculus.Interaction.Input.SyntheticHand.LockFingerAtCurrent (in HandFinger finger)
Immediately locks an individual finger (all its internal joints) at the last known value.
Parameters
finger The finger for which to lock joints.
LockJoint()
void Oculus.Interaction.Input.SyntheticHand.LockJoint (in HandJointId jointId, Quaternion rotation, float overrideFactor = 1f)
LockWristPose()
void Oculus.Interaction.Input.SyntheticHand.LockWristPose (Pose wristPose, float overrideFactor = 1f, WristLockMode lockMode = WristLockMode::Full, bool worldPose = false, bool skipAnimation = false)
Stores the desired pose to set the wrist of the hand to. This is not necessarily the final pose of the hand, as it allows lerping between the tracked and provided one during the ApplyHand phase.
To ensure the hand is locked at the desired pose, pass a value of 1 in the overrideFactor
Parameters
wristPose The final pose desired for the wrist
lockMode Either lock the position, rotation or both (default)
overrideFactor How much to lerp between the tracked and the provided pose
skipAnimation Whether to skip the animation curve for this override.
LockWristPosition()
void Oculus.Interaction.Input.SyntheticHand.LockWristPosition (Vector3 position, float overrideFactor = 1f, bool skipAnimation = false)
Referenced by Oculus.Interaction.Input.SyntheticHand.LockWristPose().
LockWristRotation()
void Oculus.Interaction.Input.SyntheticHand.LockWristRotation (Quaternion rotation, float overrideFactor = 1f, bool skipAnimation = false)
Referenced by Oculus.Interaction.Input.SyntheticHand.LockWristPose().
OverrideAllJoints()
void Oculus.Interaction.Input.SyntheticHand.OverrideAllJoints (in Quaternion[] jointRotations, float overrideFactor)
Stores the rotation data for all joints in the hand, to be applied during the ApplyHand event.
Parameters
jointRotations The joint rotations following the FingersMetadata.HAND_JOINT_IDS format.
overrideFactor How much to lerp the fingers from the tracked (raw) state to the provided one.
OverrideFingerRotations()
void Oculus.Interaction.Input.SyntheticHand.OverrideFingerRotations (HandFinger finger, Quaternion[] rotations, float overrideFactor)
Stores the rotation data for all joints for the given finger, to be applied during the ApplyHand event.
Parameters
finger The finger for which to lock joints.
rotations The joint rotations for each joint on the finger
overrideFactor How much to lerp the fingers from the tracked (raw) state to the provided one.
OverrideJointRotation()
void Oculus.Interaction.Input.SyntheticHand.OverrideJointRotation (HandJointId jointId, Quaternion rotation, float overrideFactor)
SetFingerFreedom()
void Oculus.Interaction.Input.SyntheticHand.SetFingerFreedom (in HandFinger finger, in JointFreedom freedomLevel, bool skipAnimation = false)
To use in conjunction with OverrideAllJoints, it sets the freedom state for a provided finger. Opposite to LockFingerAtCurrent, this method uses the data provided in OverrideAllJoints instead of the last known state.
Parameters
freedomLevel The freedom level for the finger
Referenced by Oculus.Interaction.Input.SyntheticHand.LockFingerAtCurrent().
SetJointFreedom()
void Oculus.Interaction.Input.SyntheticHand.SetJointFreedom (in HandJointId jointId, in JointFreedom freedomLevel, bool skipAnimation = false)
Start()
override void Oculus.Interaction.Input.SyntheticHand.Start () protected
Member Data Documentation
UpdateRequired
System.Action Oculus.Interaction.Input.SyntheticHand.UpdateRequired = delegate { }
Referenced by Oculus.Interaction.Input.SyntheticHand.Apply().
The documentation for this class was generated from the following file:
C:/Users/Lykos/Desktop/Projects/Capstone/VRGames/Assets/ThirdParty/Oculus/Interaction/Runtime/Scripts/Input/Hands/DataModifiers/SyntheticHand.cs