VRCapstoneGames: OVRNativeBuffer Class Reference
OVRNativeBuffer Class Reference
Encapsulates an 8-byte-aligned of unmanaged memory.
Public Member Functions
OVRNativeBuffer (int numBytes)
Creates a buffer of the specified size.
void Reset (int numBytes)
Reallocates the buffer with the specified new size.
int GetCapacity ()
The current number of bytes in the buffer.
IntPtr GetPointer (int byteOffset=0)
A pointer to the unmanaged memory in the buffer, starting at the given offset in bytes.
void Dispose ()
Releases all resource used by the OVRNativeBuffer object.
Detailed Description
Encapsulates an 8-byte-aligned of unmanaged memory.
Constructor & Destructor Documentation
OVRNativeBuffer()
OVRNativeBuffer.OVRNativeBuffer (int numBytes)
Creates a buffer of the specified size.
Member Function Documentation
Dispose()
void OVRNativeBuffer.Dispose ()
Releases all resource used by the OVRNativeBuffer object.
Call Dispose when you are finished using the OVRNativeBuffer. The Dispose method leaves the OVRNativeBuffer in an unusable state. After calling Dispose, you must release all references to the OVRNativeBuffer so the garbage collector can reclaim the memory that the OVRNativeBuffer was occupying.
Referenced by Dispose().
GetCapacity()
int OVRNativeBuffer.GetCapacity ()
The current number of bytes in the buffer.
Referenced by OVRBoundary.GetGeometry().
GetPointer()
IntPtr OVRNativeBuffer.GetPointer (int byteOffset = 0)
A pointer to the unmanaged memory in the buffer, starting at the given offset in bytes.
Referenced by OVRBoundary.GetGeometry().
Reset()
void OVRNativeBuffer.Reset (int numBytes)
Reallocates the buffer with the specified new size.
Referenced by OVRBoundary.GetGeometry().
The documentation for this class was generated from the following file:
C:/Users/Lykos/Desktop/Projects/Capstone/VRGames/Assets/ThirdParty/Oculus/VR/Scripts/OVRCommon.cs