VRGames: UnityEngine.XR.Management.Tests.Standalone.StandaloneLoader Class Reference
UnityEngine.XR.Management.Tests.Standalone.StandaloneLoader Class Reference
Public Member Functions
override bool Initialize ()
Initialize the loader. This should initialize all subsystems to support the desired runtime setup this loader represents.
override bool Start ()
Ask loader to start all initialized subsystems.
override bool Stop ()
Ask loader to stop all initialized subsystems.
override bool Deinitialize ()
Ask loader to deinitialize all initialized subsystems.
Public Member Functions inherited from UnityEngine.XR.Management.XRLoaderHelper
override T GetLoadedSubsystem< T > ()
Gets the loaded subsystem of the specified type. Implementation dependent as only implemetnations know what they have loaded and how best to get it..
override bool Deinitialize ()
Override of XRLoader.Deinitialize to provide for clearing the instance map.true.
Public Member Functions inherited from UnityEngine.XR.Management.XRLoader
T GetLoadedSubsystem< T > ()
Gets the loaded subsystem of the specified type. Implementation dependent as only implemetnations know what they have loaded and how best to get it..
virtual List< GraphicsDeviceType > GetSupportedGraphicsDeviceTypes (bool buildingPlayer)
Gets the loader's supported graphics device types. If the list is empty, it is assumed that it supports all graphics device types.
Properties
StandaloneSubsystem standaloneSubsystem [get]
bool started [get, protected set]
bool stopped [get, protected set]
bool deInitialized [get, protected set]
Additional Inherited Members
Protected Member Functions inherited from UnityEngine.XR.Management.XRLoaderHelper
void StartSubsystem< T > ()
Start a subsystem instance of a given type. Subsystem assumed to already be loaded from a previous call to CreateSubsystem.
void StopSubsystem< T > ()
Stop a subsystem instance of a given type. Subsystem assumed to already be loaded from a previous call to CreateSubsystem.
void DestroySubsystem< T > ()
Destroy a subsystem instance of a given type. Subsystem assumed to already be loaded from a previous call to CreateSubsystem.
void CreateSubsystem< TDescriptor, TSubsystem > (List< TDescriptor > descriptors, string id)
Creates a subsystem given a list of descriptors and a specific subsystem id.
void CreateIntegratedSubsystem< TDescriptor, TSubsystem > (List< TDescriptor > descriptors, string id)
Creates a native, integrated subsystem given a list of descriptors and a specific subsystem id. DEPRECATED: Please use the geenric CreateSubsystem method. This method is soley retained for backwards compatibility and will be removed in a future release.
void CreateStandaloneSubsystem< TDescriptor, TSubsystem > (List< TDescriptor > descriptors, string id)
Creates a managed, standalone subsystem given a list of descriptors and a specific subsystem id. DEPRECATED: Please use the geenric CreateSubsystem method. This method is soley retained for backwards compatibility and will be removed in a future release.
Protected Attributes inherited from UnityEngine.XR.Management.XRLoaderHelper
Dictionary< Type, ISubsystem > m_SubsystemInstanceMap = new Dictionary<Type, ISubsystem>()
Map of loaded susbsystems. Used so we don't always have to fo to XRSubsystemManger and do a manual search to find the instance we loaded.
Member Function Documentation
Deinitialize()
override bool UnityEngine.XR.Management.Tests.Standalone.StandaloneLoader.Deinitialize () virtual
Ask loader to deinitialize all initialized subsystems.
Returns
Whether or not deinitialization succeeded.
Reimplemented from UnityEngine.XR.Management.XRLoader.
Referenced by UnityEditor.XR.Management.Tests.EditorTests.StandaloneLoaderLifecycleTest().
Initialize()
override bool UnityEngine.XR.Management.Tests.Standalone.StandaloneLoader.Initialize () virtual
Initialize the loader. This should initialize all subsystems to support the desired runtime setup this loader represents.
This is the only method on XRLoader that Management uses to determine the active loader to use. If this method returns true, Management locks this loader as the XRManagerSettings.activeLoader and and stops fall through processing on the XRManagerSettings.loaders list of current loaders.
If this method returns false, XRManagerSettings continues to process the next loader in the XRManagerSettings.loaders list, or fails completely when the list is exhausted.
Returns
Whether or not initialization succeeded.
Reimplemented from UnityEngine.XR.Management.XRLoader.
Referenced by UnityEditor.XR.Management.Tests.EditorTests.StandaloneLoaderCreateTest(), and UnityEditor.XR.Management.Tests.EditorTests.StandaloneLoaderLifecycleTest().
Start()
override bool UnityEngine.XR.Management.Tests.Standalone.StandaloneLoader.Start () virtual
Ask loader to start all initialized subsystems.
Returns
Whether or not all subsystems were successfully started.
Reimplemented from UnityEngine.XR.Management.XRLoader.
Referenced by UnityEditor.XR.Management.Tests.EditorTests.StandaloneLoaderLifecycleTest().
Stop()
override bool UnityEngine.XR.Management.Tests.Standalone.StandaloneLoader.Stop () virtual
Ask loader to stop all initialized subsystems.
Returns
Whether or not all subsystems were successfully stopped.
Reimplemented from UnityEngine.XR.Management.XRLoader.
Referenced by UnityEditor.XR.Management.Tests.EditorTests.StandaloneLoaderLifecycleTest().
Property Documentation
deInitialized
bool UnityEngine.XR.Management.Tests.Standalone.StandaloneLoader.deInitialized get protected set
Referenced by UnityEngine.XR.Management.Tests.Standalone.StandaloneLoader.Initialize(), and UnityEditor.XR.Management.Tests.EditorTests.StandaloneLoaderLifecycleTest().
standaloneSubsystem
StandaloneSubsystem UnityEngine.XR.Management.Tests.Standalone.StandaloneLoader.standaloneSubsystem get
Referenced by UnityEngine.XR.Management.Tests.Standalone.StandaloneLoader.Deinitialize(), UnityEngine.XR.Management.Tests.Standalone.StandaloneLoader.Initialize(), UnityEngine.XR.Management.Tests.Standalone.StandaloneLoader.Start(), and UnityEngine.XR.Management.Tests.Standalone.StandaloneLoader.Stop().
started
bool UnityEngine.XR.Management.Tests.Standalone.StandaloneLoader.started get protected set
Referenced by UnityEngine.XR.Management.Tests.Standalone.StandaloneLoader.Initialize(), and UnityEditor.XR.Management.Tests.EditorTests.StandaloneLoaderLifecycleTest().
stopped
bool UnityEngine.XR.Management.Tests.Standalone.StandaloneLoader.stopped get protected set
Referenced by UnityEngine.XR.Management.Tests.Standalone.StandaloneLoader.Initialize(), and UnityEditor.XR.Management.Tests.EditorTests.StandaloneLoaderLifecycleTest().
The documentation for this class was generated from the following file:
C:/Users/Lykos/Desktop/Projects/Capstone/VRGames/Library/PackageCache/com.unity.xr.management@4.2.1/Tests/StandaloneSubsystem/StandaloneLoader.cs