VRCapstoneGames: Oculus.Interaction.HandPokeLimiterVisual Class Reference
Oculus.Interaction.HandPokeLimiterVisual Class Reference
HandPokeInteractorVisual forwards the finger state of an associated HandPokeInteractor to a HandGrabModifier to lock and unlock finger joints in the modifier's target hand data.
Public Member Functions
void InjectAllHandPokeLimiterVisual (IHand hand, PokeInteractor pokeInteractor, SyntheticHand syntheticHand)
void InjectHand (IHand hand)
void InjectPokeInteractor (PokeInteractor pokeInteractor)
void InjectSyntheticHand (SyntheticHand syntheticHand)
Protected Member Functions
virtual void Awake ()
virtual void Start ()
virtual void OnEnable ()
virtual void OnDisable ()
virtual void LateUpdate ()
Protected Attributes
bool _started = false
Detailed Description
HandPokeInteractorVisual forwards the finger state of an associated HandPokeInteractor to a HandGrabModifier to lock and unlock finger joints in the modifier's target hand data.
Member Function Documentation
Awake()
virtual void Oculus.Interaction.HandPokeLimiterVisual.Awake () protected virtual
InjectAllHandPokeLimiterVisual()
void Oculus.Interaction.HandPokeLimiterVisual.InjectAllHandPokeLimiterVisual (IHand hand, PokeInteractor pokeInteractor, SyntheticHand syntheticHand)
InjectHand()
void Oculus.Interaction.HandPokeLimiterVisual.InjectHand (IHand hand)
Referenced by Oculus.Interaction.HandPokeLimiterVisual.InjectAllHandPokeLimiterVisual().
InjectPokeInteractor()
void Oculus.Interaction.HandPokeLimiterVisual.InjectPokeInteractor (PokeInteractor pokeInteractor)
Referenced by Oculus.Interaction.HandPokeLimiterVisual.InjectAllHandPokeLimiterVisual().
InjectSyntheticHand()
void Oculus.Interaction.HandPokeLimiterVisual.InjectSyntheticHand (SyntheticHand syntheticHand)
Referenced by Oculus.Interaction.HandPokeLimiterVisual.InjectAllHandPokeLimiterVisual().
LateUpdate()
virtual void Oculus.Interaction.HandPokeLimiterVisual.LateUpdate () protected virtual
OnDisable()
virtual void Oculus.Interaction.HandPokeLimiterVisual.OnDisable () protected virtual
OnEnable()
virtual void Oculus.Interaction.HandPokeLimiterVisual.OnEnable () protected virtual
Start()
virtual void Oculus.Interaction.HandPokeLimiterVisual.Start () protected virtual
Member Data Documentation
_started
bool Oculus.Interaction.HandPokeLimiterVisual._started = false protected
Referenced by Oculus.Interaction.HandPokeLimiterVisual.OnDisable(), Oculus.Interaction.HandPokeLimiterVisual.OnEnable(), and Oculus.Interaction.HandPokeLimiterVisual.Start().
The documentation for this class was generated from the following file:
C:/Users/Lykos/Desktop/Projects/Capstone/VRGames/Assets/ThirdParty/Oculus/Interaction/Runtime/Scripts/Interaction/Models/Poke/Visuals/HandPokeLimiterVisual.cs