VRGames: Oculus.Interaction.UnityCanvas.CanvasRenderTextureMesh Class Reference
Oculus.Interaction.UnityCanvas.CanvasRenderTextureMesh Class Reference abstract
Public Member Functions
Vector3 ImposterToCanvasTransformPoint (Vector3 worldPosition)
Transform a position in world space relative to the imposter to an associated position relative to the original canvas in world space.
void InjectAllCanvasRenderTextureMesh (CanvasRenderTexture canvasRenderTexture)
void InjectCanvasRenderTexture (CanvasRenderTexture canvasRenderTexture)
void InjectOptionalMeshCollider (MeshCollider meshCollider)
Protected Member Functions
Vector3 MeshInverseTransform (Vector3 localPosition)
void GenerateMesh (out List< Vector3 > verts, out List< int > tris, out List< Vector2 > uvs)
void UpdateOverlayPositionAndScale ()
virtual void Start ()
virtual void OnEnable ()
virtual void OnDisable ()
virtual void HandleUpdateRenderTexture (Texture texture)
virtual void UpdateImposter ()
void CreateMaterial ()
void UpdateOverlay ()
GameObject CreateChildObject (string name)
Protected Attributes
CanvasRenderTexture _canvasRenderTexture
MeshCollider _meshCollider = null
Vector3 _runtimeOffset = new Vector3(0, 0, 0)
OVROverlay _overlay
bool _started = false
Properties
OVROverlay.OverlayShape OverlayShape [get]
Member Function Documentation
CreateChildObject()
GameObject Oculus.Interaction.UnityCanvas.CanvasRenderTextureMesh.CreateChildObject (string name) protected
Referenced by Oculus.Interaction.UnityCanvas.CanvasRenderTextureMesh.UpdateOverlay().
CreateMaterial()
void Oculus.Interaction.UnityCanvas.CanvasRenderTextureMesh.CreateMaterial () protected
Referenced by Oculus.Interaction.UnityCanvas.CanvasRenderTextureMesh.OnEnable().
GenerateMesh()
void Oculus.Interaction.UnityCanvas.CanvasRenderTextureMesh.GenerateMesh (out List< Vector3 > verts, out List< int > tris, out List< Vector2 > uvs) abstract protected
Referenced by Oculus.Interaction.UnityCanvas.CanvasRenderTextureMesh.UpdateImposter().
HandleUpdateRenderTexture()
virtual void Oculus.Interaction.UnityCanvas.CanvasRenderTextureMesh.HandleUpdateRenderTexture (Texture texture) protected virtual
Referenced by Oculus.Interaction.UnityCanvas.CanvasRenderTextureMesh.OnDisable(), and Oculus.Interaction.UnityCanvas.CanvasRenderTextureMesh.OnEnable().
ImposterToCanvasTransformPoint()
Vector3 Oculus.Interaction.UnityCanvas.CanvasRenderTextureMesh.ImposterToCanvasTransformPoint (Vector3 worldPosition)
Transform a position in world space relative to the imposter to an associated position relative to the original canvas in world space.
InjectAllCanvasRenderTextureMesh()
void Oculus.Interaction.UnityCanvas.CanvasRenderTextureMesh.InjectAllCanvasRenderTextureMesh (CanvasRenderTexture canvasRenderTexture)
Referenced by Oculus.Interaction.UnityCanvas.CanvasCylinder.InjectAllCanvasCylinder(), and Oculus.Interaction.UnityCanvas.CanvasRect.InjectAllCanvasRect().
InjectCanvasRenderTexture()
void Oculus.Interaction.UnityCanvas.CanvasRenderTextureMesh.InjectCanvasRenderTexture (CanvasRenderTexture canvasRenderTexture)
Referenced by Oculus.Interaction.UnityCanvas.CanvasRenderTextureMesh.InjectAllCanvasRenderTextureMesh().
InjectOptionalMeshCollider()
void Oculus.Interaction.UnityCanvas.CanvasRenderTextureMesh.InjectOptionalMeshCollider (MeshCollider meshCollider)
MeshInverseTransform()
Vector3 Oculus.Interaction.UnityCanvas.CanvasRenderTextureMesh.MeshInverseTransform (Vector3 localPosition) abstract protected
Referenced by Oculus.Interaction.UnityCanvas.CanvasRenderTextureMesh.ImposterToCanvasTransformPoint().
OnDisable()
virtual void Oculus.Interaction.UnityCanvas.CanvasRenderTextureMesh.OnDisable () protected virtual
OnEnable()
virtual void Oculus.Interaction.UnityCanvas.CanvasRenderTextureMesh.OnEnable () protected virtual
Start()
virtual void Oculus.Interaction.UnityCanvas.CanvasRenderTextureMesh.Start () protected virtual
Reimplemented in Oculus.Interaction.UnityCanvas.CanvasCylinder.
UpdateImposter()
virtual void Oculus.Interaction.UnityCanvas.CanvasRenderTextureMesh.UpdateImposter () protected virtual
Reimplemented in Oculus.Interaction.UnityCanvas.CanvasCylinder.
Referenced by Oculus.Interaction.UnityCanvas.CanvasRenderTextureMesh.HandleUpdateRenderTexture(), and Oculus.Interaction.UnityCanvas.CanvasRenderTextureMesh.OnEnable().
UpdateOverlay()
void Oculus.Interaction.UnityCanvas.CanvasRenderTextureMesh.UpdateOverlay () protected
Referenced by Oculus.Interaction.UnityCanvas.CanvasRenderTextureMesh.HandleUpdateRenderTexture().
UpdateOverlayPositionAndScale()
void Oculus.Interaction.UnityCanvas.CanvasRenderTextureMesh.UpdateOverlayPositionAndScale () abstract protected
Referenced by Oculus.Interaction.UnityCanvas.CanvasRenderTextureMesh.UpdateOverlay().
Member Data Documentation
_canvasRenderTexture
CanvasRenderTexture Oculus.Interaction.UnityCanvas.CanvasRenderTextureMesh._canvasRenderTexture protected
Referenced by Oculus.Interaction.UnityCanvas.CanvasRenderTextureMesh.CreateMaterial(), Oculus.Interaction.UnityCanvas.CanvasRect.GenerateMesh(), Oculus.Interaction.UnityCanvas.CanvasRenderTextureMesh.HandleUpdateRenderTexture(), Oculus.Interaction.UnityCanvas.CanvasRenderTextureMesh.ImposterToCanvasTransformPoint(), Oculus.Interaction.UnityCanvas.CanvasRenderTextureMesh.InjectCanvasRenderTexture(), Oculus.Interaction.UnityCanvas.CanvasRenderTextureMesh.OnEnable(), Oculus.Interaction.UnityCanvas.CanvasRenderTextureMesh.Start(), Oculus.Interaction.UnityCanvas.CanvasRenderTextureMesh.UpdateOverlay(), Oculus.Interaction.UnityCanvas.CanvasCylinder.UpdateOverlayPositionAndScale(), and Oculus.Interaction.UnityCanvas.CanvasRect.UpdateOverlayPositionAndScale().
_meshCollider
MeshCollider Oculus.Interaction.UnityCanvas.CanvasRenderTextureMesh._meshCollider = null protected
Referenced by Oculus.Interaction.UnityCanvas.CanvasRenderTextureMesh.InjectOptionalMeshCollider(), and Oculus.Interaction.UnityCanvas.CanvasRenderTextureMesh.UpdateImposter().
_overlay
OVROverlay Oculus.Interaction.UnityCanvas.CanvasRenderTextureMesh._overlay protected
Referenced by Oculus.Interaction.UnityCanvas.CanvasRenderTextureMesh.UpdateOverlay(), Oculus.Interaction.UnityCanvas.CanvasCylinder.UpdateOverlayPositionAndScale(), and Oculus.Interaction.UnityCanvas.CanvasRect.UpdateOverlayPositionAndScale().
_runtimeOffset
Vector3 Oculus.Interaction.UnityCanvas.CanvasRenderTextureMesh._runtimeOffset = new Vector3(0, 0, 0) protected
Referenced by Oculus.Interaction.UnityCanvas.CanvasCylinder.UpdateOverlayPositionAndScale(), and Oculus.Interaction.UnityCanvas.CanvasRect.UpdateOverlayPositionAndScale().
_started
bool Oculus.Interaction.UnityCanvas.CanvasRenderTextureMesh._started = false protected
Referenced by Oculus.Interaction.UnityCanvas.CanvasRenderTextureMesh.OnDisable(), Oculus.Interaction.UnityCanvas.CanvasRenderTextureMesh.OnEnable(), Oculus.Interaction.UnityCanvas.CanvasCylinder.Start(), and Oculus.Interaction.UnityCanvas.CanvasRenderTextureMesh.Start().
Property Documentation
OverlayShape
OVROverlay.OverlayShape Oculus.Interaction.UnityCanvas.CanvasRenderTextureMesh.OverlayShape get abstract protected
Referenced by Oculus.Interaction.UnityCanvas.CanvasRenderTextureMesh.UpdateOverlay().
The documentation for this class was generated from the following file:
C:/Users/Lykos/Desktop/Projects/Capstone/VRGames/Assets/ThirdParty/Oculus/Interaction/Runtime/Scripts/Unity/UnityCanvas/CanvasRenderTextureMesh.cs