VRCapstoneGames: UnityEngine.ProBuilder.KdTree.KdTree< TKey, TValue > Class Template Reference
UnityEngine.ProBuilder.KdTree.KdTree< TKey, TValue > Class Template Reference
Public Member Functions
KdTree (int dimensions, ITypeMath< TKey > typeMath)
KdTree (int dimensions, ITypeMath< TKey > typeMath, AddDuplicateBehavior addDuplicateBehavior)
bool Add (TKey[] point, TValue value)
void RemoveAt (TKey[] point)
KdTreeNode< TKey, TValue >[] GetNearestNeighbours (TKey[] point, int count)
KdTreeNode< TKey, TValue >[] RadialSearch (TKey[] center, TKey radius, int count)
bool TryFindValueAt (TKey[] point, out TValue value)
TValue FindValueAt (TKey[] point)
bool TryFindValue (TValue value, out TKey[] point)
TKey[] FindValue (TValue value)
override string ToString ()
void Balance ()
void Clear ()
void SaveToFile (string filename)
IEnumerator< KdTreeNode< TKey, TValue > > GetEnumerator ()
Static Public Member Functions
static KdTree< TKey, TValue > LoadFromFile (string filename)
Properties
AddDuplicateBehavior AddDuplicateBehavior [get]
int Count [get]
Properties inherited from UnityEngine.ProBuilder.KdTree.IKdTree< TKey, TValue >
Constructor & Destructor Documentation
KdTree() [1/2]
UnityEngine.ProBuilder.KdTree.KdTree< TKey, TValue >.KdTree (int dimensions, ITypeMath< TKey > typeMath)
KdTree() [2/2]
UnityEngine.ProBuilder.KdTree.KdTree< TKey, TValue >.KdTree (int dimensions, ITypeMath< TKey > typeMath, AddDuplicateBehavior addDuplicateBehavior)
Member Function Documentation
Add()
bool UnityEngine.ProBuilder.KdTree.KdTree< TKey, TValue >.Add (TKey[] point, TValue value)
Implements UnityEngine.ProBuilder.KdTree.IKdTree< TKey, TValue >.
Balance()
void UnityEngine.ProBuilder.KdTree.KdTree< TKey, TValue >.Balance ()
Clear()
void UnityEngine.ProBuilder.KdTree.KdTree< TKey, TValue >.Clear ()
Implements UnityEngine.ProBuilder.KdTree.IKdTree< TKey, TValue >.
Referenced by UnityEngine.ProBuilder.KdTree.KdTree< TKey, TValue >.Balance().
FindValue()
TKey[] UnityEngine.ProBuilder.KdTree.KdTree< TKey, TValue >.FindValue (TValue value)
Implements UnityEngine.ProBuilder.KdTree.IKdTree< TKey, TValue >.
FindValueAt()
TValue UnityEngine.ProBuilder.KdTree.KdTree< TKey, TValue >.FindValueAt (TKey[] point)
Implements UnityEngine.ProBuilder.KdTree.IKdTree< TKey, TValue >.
GetEnumerator()
IEnumerator< KdTreeNode< TKey, TValue > > UnityEngine.ProBuilder.KdTree.KdTree< TKey, TValue >.GetEnumerator ()
GetNearestNeighbours()
KdTreeNode< TKey, TValue >[] UnityEngine.ProBuilder.KdTree.KdTree< TKey, TValue >.GetNearestNeighbours (TKey[] point, int count)
Implements UnityEngine.ProBuilder.KdTree.IKdTree< TKey, TValue >.
LoadFromFile()
static KdTree< TKey, TValue > UnityEngine.ProBuilder.KdTree.KdTree< TKey, TValue >.LoadFromFile (string filename) static
RadialSearch()
KdTreeNode< TKey, TValue >[] UnityEngine.ProBuilder.KdTree.KdTree< TKey, TValue >.RadialSearch (TKey[] center, TKey radius, int count)
Implements UnityEngine.ProBuilder.KdTree.IKdTree< TKey, TValue >.
RemoveAt()
void UnityEngine.ProBuilder.KdTree.KdTree< TKey, TValue >.RemoveAt (TKey[] point)
Implements UnityEngine.ProBuilder.KdTree.IKdTree< TKey, TValue >.
SaveToFile()
void UnityEngine.ProBuilder.KdTree.KdTree< TKey, TValue >.SaveToFile (string filename)
ToString()
override string UnityEngine.ProBuilder.KdTree.KdTree< TKey, TValue >.ToString ()
TryFindValue()
bool UnityEngine.ProBuilder.KdTree.KdTree< TKey, TValue >.TryFindValue (TValue value, out TKey[] point)
Implements UnityEngine.ProBuilder.KdTree.IKdTree< TKey, TValue >.
Referenced by UnityEngine.ProBuilder.KdTree.KdTree< TKey, TValue >.FindValue().
TryFindValueAt()
bool UnityEngine.ProBuilder.KdTree.KdTree< TKey, TValue >.TryFindValueAt (TKey[] point, out TValue value)
Implements UnityEngine.ProBuilder.KdTree.IKdTree< TKey, TValue >.
Referenced by UnityEngine.ProBuilder.KdTree.KdTree< TKey, TValue >.FindValueAt().
Property Documentation
AddDuplicateBehavior
AddDuplicateBehavior UnityEngine.ProBuilder.KdTree.KdTree< TKey, TValue >.AddDuplicateBehavior get
Count
int UnityEngine.ProBuilder.KdTree.KdTree< TKey, TValue >.Count get
Implements UnityEngine.ProBuilder.KdTree.IKdTree< TKey, TValue >.
Referenced by UnityEngine.ProBuilder.KdTree.KdTree< TKey, TValue >.Add(), UnityEngine.ProBuilder.KdTree.KdTree< TKey, TValue >.GetNearestNeighbours(), UnityEngine.ProBuilder.KdTree.KdTree< TKey, TValue >.KdTree(), and UnityEngine.ProBuilder.KdTree.KdTree< TKey, TValue >.RemoveAt().
The documentation for this class was generated from the following file:
C:/Users/Lykos/Desktop/Projects/Capstone/VRGames/Library/PackageCache/com.unity.probuilder@5.0.6/External/KdTree/KdTreeLib/KdTree.cs