VRGames: win::ComPtr< T > Class Template Reference
win::ComPtr< T > Class Template Reference
#include <ComPtr.h>
Public Member Functions
ComPtr (void)
~ComPtr (void)
ComPtr (T *ptr)
ComPtr (const ComPtr &ptr)
bool operator! () const
operator T* () const
T * operator-> () const
T & operator* ()
ComPtrRef< T > operator& ()
const ComPtr & operator= (T *ptr)
const ComPtr & operator= (const ComPtr &ptr)
void Free (void)
T ** ReleaseAndGetAddressOf ()
template<typename U >
HRESULT As (ComPtrRef< U > p) const throw ()
bool operator== (std::nullptr_t) const
template<typename U >
bool operator== (U *other)
template<typename U >
bool operator== (ComPtr< U > &other)
bool operator!= (std::nullptr_t) const
template<typename U >
bool operator!= (U *other)
template<typename U >
bool operator!= (ComPtr< U > &other)
Constructor & Destructor Documentation
ComPtr() [1/3]
template<typename T > win::ComPtr< T >::ComPtr (void)
~ComPtr()
template<typename T > win::ComPtr< T >::~ComPtr (void)
ComPtr() [2/3]
template<typename T > win::ComPtr< T >::ComPtr (T * ptr)
ComPtr() [3/3]
template<typename T > win::ComPtr< T >::ComPtr (const ComPtr< T > & ptr)
Member Function Documentation
As()
template<typename T > template<typename U > HRESULT win::ComPtr< T >::As (ComPtrRef< U > p) const throw ()
Free()
template<typename T > void win::ComPtr< T >::Free (void)
Referenced by win::ComPtr< T >::operator=(), win::ComPtr< T >::operator=(), win::ComPtr< T >::ReleaseAndGetAddressOf(), and win::ComPtr< T >::~ComPtr().
operator T*()
template<typename T > win::ComPtr< T >::operator T* () const
operator!()
template<typename T > bool win::ComPtr< T >::operator! () const
operator!=() [1/3]
template<typename T > template<typename U > bool win::ComPtr< T >::operator!= (ComPtr< U > & other)
operator!=() [2/3]
template<typename T > bool win::ComPtr< T >::operator!= (std::nullptr_t) const
operator!=() [3/3]
template<typename T > template<typename U > bool win::ComPtr< T >::operator!= (U * other)
operator&()
template<typename T > ComPtrRef< T > win::ComPtr< T >::operator& ()
operator*()
template<typename T > T & win::ComPtr< T >::operator* ()
operator->()
template<typename T > T * win::ComPtr< T >::operator-> () const
operator=() [1/2]
template<typename T > const ComPtr & win::ComPtr< T >::operator= (const ComPtr< T > & ptr)
operator=() [2/2]
template<typename T > const ComPtr & win::ComPtr< T >::operator= (T * ptr)
operator==() [1/3]
template<typename T > template<typename U > bool win::ComPtr< T >::operator== (ComPtr< U > & other)
operator==() [2/3]
template<typename T > bool win::ComPtr< T >::operator== (std::nullptr_t) const
operator==() [3/3]
template<typename T > template<typename U > bool win::ComPtr< T >::operator== (U * other)
ReleaseAndGetAddressOf()
template<typename T > T ** win::ComPtr< T >::ReleaseAndGetAddressOf ()
Referenced by win::ComPtrRef< T >::operator T**(), and win::ComPtrRef< T >::operator void **().
The documentation for this class was generated from the following file:
C:/Users/Lykos/Desktop/Projects/Capstone/VRGames/Library/PackageCache/com.unity.ide.visualstudio@2.0.16/Editor/COMIntegration/COMIntegration~/ComPtr.h