VRCapstoneGames: OvrAvatarComponent Class Reference
OvrAvatarComponent Class Reference
Public Member Functions
void SetOvrAvatarOwner (OvrAvatar ovrAvatarOwner)
void UpdateAvatar (IntPtr nativeComponent)
void UpdateAvatarMaterial (Material mat, ovrAvatarMaterialState matState)
Static Public Member Functions
static Texture2D GetLoadedTexture (UInt64 assetId)
Public Attributes
List< OvrAvatarRenderComponent > RenderParts = new List<OvrAvatarRenderComponent>()
Static Public Attributes
static readonly string[] LayerKeywords = new[] { "LAYERS_0", "LAYERS_1", "LAYERS_2", "LAYERS_3", "LAYERS_4", "LAYERS_5", "LAYERS_6", "LAYERS_7", "LAYERS_8", }
static readonly string[] LayerSampleModeParameters = new[] { "_LayerSampleMode0", "_LayerSampleMode1", "_LayerSampleMode2", "_LayerSampleMode3", "_LayerSampleMode4", "_LayerSampleMode5", "_LayerSampleMode6", "_LayerSampleMode7", }
static readonly string[] LayerBlendModeParameters = new[] { "_LayerBlendMode0", "_LayerBlendMode1", "_LayerBlendMode2", "_LayerBlendMode3", "_LayerBlendMode4", "_LayerBlendMode5", "_LayerBlendMode6", "_LayerBlendMode7", }
static readonly string[] LayerMaskTypeParameters = new[] { "_LayerMaskType0", "_LayerMaskType1", "_LayerMaskType2", "_LayerMaskType3", "_LayerMaskType4", "_LayerMaskType5", "_LayerMaskType6", "_LayerMaskType7", }
static readonly string[] LayerColorParameters = new[] { "_LayerColor0", "_LayerColor1", "_LayerColor2", "_LayerColor3", "_LayerColor4", "_LayerColor5", "_LayerColor6", "_LayerColor7", }
static readonly string[] LayerSurfaceParameters = new[] { "_LayerSurface0", "_LayerSurface1", "_LayerSurface2", "_LayerSurface3", "_LayerSurface4", "_LayerSurface5", "_LayerSurface6", "_LayerSurface7", }
static readonly string[] LayerSampleParametersParameters = new[] { "_LayerSampleParameters0", "_LayerSampleParameters1", "_LayerSampleParameters2", "_LayerSampleParameters3", "_LayerSampleParameters4", "_LayerSampleParameters5", "_LayerSampleParameters6", "_LayerSampleParameters7", }
static readonly string[] LayerMaskParametersParameters = new[] { "_LayerMaskParameters0", "_LayerMaskParameters1", "_LayerMaskParameters2", "_LayerMaskParameters3", "_LayerMaskParameters4", "_LayerMaskParameters5", "_LayerMaskParameters6", "_LayerMaskParameters7", }
static readonly string[] LayerMaskAxisParameters = new[] { "_LayerMaskAxis0", "_LayerMaskAxis1", "_LayerMaskAxis2", "_LayerMaskAxis3", "_LayerMaskAxis4", "_LayerMaskAxis5", "_LayerMaskAxis6", "_LayerMaskAxis7", }
Protected Member Functions
void UpdateActive (OvrAvatar avatar, ovrAvatarVisibilityFlags mask)
Protected Attributes
OvrAvatar owner = null
ovrAvatarComponent nativeAvatarComponent = new ovrAvatarComponent()
Member Function Documentation
GetLoadedTexture()
static Texture2D OvrAvatarComponent.GetLoadedTexture (UInt64 assetId) static
Referenced by UpdateAvatarMaterial().
SetOvrAvatarOwner()
void OvrAvatarComponent.SetOvrAvatarOwner (OvrAvatar ovrAvatarOwner)
UpdateActive()
void OvrAvatarComponent.UpdateActive (OvrAvatar avatar, ovrAvatarVisibilityFlags mask) protected
UpdateAvatar()
void OvrAvatarComponent.UpdateAvatar (IntPtr nativeComponent)
UpdateAvatarMaterial()
void OvrAvatarComponent.UpdateAvatarMaterial (Material mat, ovrAvatarMaterialState matState)
Referenced by OvrAvatarSkinnedMeshRenderComponent.UpdateSkinnedMeshRender().
Member Data Documentation
LayerBlendModeParameters
readonly string [] OvrAvatarComponent.LayerBlendModeParameters = new[] { "_LayerBlendMode0", "_LayerBlendMode1", "_LayerBlendMode2", "_LayerBlendMode3", "_LayerBlendMode4", "_LayerBlendMode5", "_LayerBlendMode6", "_LayerBlendMode7", } static
Referenced by UpdateAvatarMaterial().
LayerColorParameters
readonly string [] OvrAvatarComponent.LayerColorParameters = new[] { "_LayerColor0", "_LayerColor1", "_LayerColor2", "_LayerColor3", "_LayerColor4", "_LayerColor5", "_LayerColor6", "_LayerColor7", } static
Referenced by UpdateAvatarMaterial().
LayerKeywords
readonly string [] OvrAvatarComponent.LayerKeywords = new[] { "LAYERS_0", "LAYERS_1", "LAYERS_2", "LAYERS_3", "LAYERS_4", "LAYERS_5", "LAYERS_6", "LAYERS_7", "LAYERS_8", } static
Referenced by UpdateAvatarMaterial().
LayerMaskAxisParameters
readonly string [] OvrAvatarComponent.LayerMaskAxisParameters = new[] { "_LayerMaskAxis0", "_LayerMaskAxis1", "_LayerMaskAxis2", "_LayerMaskAxis3", "_LayerMaskAxis4", "_LayerMaskAxis5", "_LayerMaskAxis6", "_LayerMaskAxis7", } static
Referenced by UpdateAvatarMaterial().
LayerMaskParametersParameters
readonly string [] OvrAvatarComponent.LayerMaskParametersParameters = new[] { "_LayerMaskParameters0", "_LayerMaskParameters1", "_LayerMaskParameters2", "_LayerMaskParameters3", "_LayerMaskParameters4", "_LayerMaskParameters5", "_LayerMaskParameters6", "_LayerMaskParameters7", } static
Referenced by UpdateAvatarMaterial().
LayerMaskTypeParameters
readonly string [] OvrAvatarComponent.LayerMaskTypeParameters = new[] { "_LayerMaskType0", "_LayerMaskType1", "_LayerMaskType2", "_LayerMaskType3", "_LayerMaskType4", "_LayerMaskType5", "_LayerMaskType6", "_LayerMaskType7", } static
Referenced by UpdateAvatarMaterial().
LayerSampleModeParameters
readonly string [] OvrAvatarComponent.LayerSampleModeParameters = new[] { "_LayerSampleMode0", "_LayerSampleMode1", "_LayerSampleMode2", "_LayerSampleMode3", "_LayerSampleMode4", "_LayerSampleMode5", "_LayerSampleMode6", "_LayerSampleMode7", } static
Referenced by UpdateAvatarMaterial().
LayerSampleParametersParameters
readonly string [] OvrAvatarComponent.LayerSampleParametersParameters = new[] { "_LayerSampleParameters0", "_LayerSampleParameters1", "_LayerSampleParameters2", "_LayerSampleParameters3", "_LayerSampleParameters4", "_LayerSampleParameters5", "_LayerSampleParameters6", "_LayerSampleParameters7", } static
Referenced by UpdateAvatarMaterial().
LayerSurfaceParameters
readonly string [] OvrAvatarComponent.LayerSurfaceParameters = new[] { "_LayerSurface0", "_LayerSurface1", "_LayerSurface2", "_LayerSurface3", "_LayerSurface4", "_LayerSurface5", "_LayerSurface6", "_LayerSurface7", } static
Referenced by UpdateAvatarMaterial().
nativeAvatarComponent
ovrAvatarComponent OvrAvatarComponent.nativeAvatarComponent = new ovrAvatarComponent() protected
Referenced by OvrAvatarBody.GetNativeAvatarComponent(), and UpdateAvatar().
owner
OvrAvatar OvrAvatarComponent.owner = null protected
Referenced by OvrAvatarBody.GetNativeAvatarComponent(), SetOvrAvatarOwner(), and UpdateAvatar().
RenderParts
List<OvrAvatarRenderComponent> OvrAvatarComponent.RenderParts = new List<OvrAvatarRenderComponent>()
Referenced by OvrAvatar.GetHandTransform(), and UpdateAvatar().
The documentation for this class was generated from the following file:
C:/Users/Lykos/Desktop/Projects/Capstone/VRGames/Assets/ThirdParty/Oculus/Avatar/Scripts/OvrAvatarComponent.cs