VRGames: UnityEngine.XR.Interaction.Toolkit.XRBaseInteractor Class Reference
UnityEngine.XR.Interaction.Toolkit.XRBaseInteractor Class Reference abstract
Abstract base class from which all interactor behaviours derive. This class hooks into the interaction system (via XRInteractionManager) and provides base virtual methods for handling hover and selection.
Public Member Functions
virtual Transform GetAttachTransform (IXRInteractable interactable)
Gets the Transform that is used as the attachment point for a given Interactable.
Parameters
interactable The specific Interactable as context to get the attachment point for.
Returns
Returns the attachment point Transform.
See also
IXRInteractable.GetAttachTransform
This should typically return the Transform of a child GameObject or the transform itself.
Pose GetAttachPoseOnSelect (IXRSelectInteractable interactable)
Gets the world position and rotation of the Attach Transform captured during the moment of selection.
Parameters
interactable The specific Interactable as context to get the attachment point for.
Returns
Returns the world pose of the attachment point during the moment of selection, and otherwise the identity Pose if it was not selected during the current selection stack.
See also
GetLocalAttachPoseOnSelect, IXRInteractor.GetAttachTransform, IXRSelectInteractable.GetAttachPoseOnSelect
Pose GetLocalAttachPoseOnSelect (IXRSelectInteractable interactable)
Gets the local position and rotation of the Attach Transform captured during the moment of selection.
Parameters
interactable The specific Interactable as context to get the attachment point for.
Returns
Returns the local pose of the attachment point during the moment of selection, and otherwise the identity Pose if it was not selected during the current selection stack.
See also
GetAttachPoseOnSelect, IXRInteractor.GetAttachTransform, IXRSelectInteractable.GetLocalAttachPoseOnSelect
virtual void GetValidTargets (List< IXRInteractable > targets)
Retrieve the list of Interactables that this Interactor could possibly interact with this frame. This list is sorted by priority (with highest priority first).
Parameters
targets The results list to populate with Interactables that are valid for selection or hover.
When implementing this method, Unity expects you to clear targets before adding to it.
virtual bool CanHover (IXRHoverInteractable interactable)
Determines if the Interactable is valid for hover this frame.
virtual bool CanSelect (IXRSelectInteractable interactable)
Determines if the Interactable is valid for selection this frame.
bool IsHovering (IXRHoverInteractable interactable)
Determines whether this Interactor is currently hovering the Interactable.
Parameters
interactable Interactable to check.
Returns
Returns true if this Interactor is currently hovering the Interactable. Otherwise, returns .
In other words, returns whether interactablesHovered contains interactable .
bool IsSelecting (IXRSelectInteractable interactable)
Determines whether this Interactor is currently selecting the Interactable.
Parameters
interactable Interactable to check.
Returns
Returns true if this Interactor is currently selecting the Interactable. Otherwise, returns .
In other words, returns whether interactablesSelected contains interactable .
virtual void PreprocessInteractor (XRInteractionUpdateOrder.UpdatePhase updatePhase)
The XRInteractionManager calls this method to update the Interactor before interaction events occur. Interactors should use this method to do tasks like determine their valid targets.
Parameters
updatePhase The update phase this is called during.
Please see the XRInteractionManager and XRInteractionUpdateOrder.UpdatePhase documentation for more details on update order.
virtual void ProcessInteractor (XRInteractionUpdateOrder.UpdatePhase updatePhase)
The XRInteractionManager calls this method to update the Interactor after interaction events occur.
Parameters
updatePhase The update phase this is called during.
Please see the XRInteractionManager and XRInteractionUpdateOrder.UpdatePhase documentation for more details on update order.
virtual void StartManualInteraction (IXRSelectInteractable interactable)
Manually initiate selection of an Interactable.
virtual void EndManualInteraction ()
Ends the manually initiated selection of an Interactable.
void GetHoverTargets (List< XRBaseInteractable > targets)
Retrieves a copy of the list of target Interactables that are currently being hovered over.
virtual void GetValidTargets (List< XRBaseInteractable > targets)
Retrieve the list of Interactables that this Interactor could possibly interact with this frame. This list is sorted by priority (with highest priority first).
virtual bool CanHover (XRBaseInteractable interactable)
Determines if the Interactable is valid for hover this frame.
virtual bool CanSelect (XRBaseInteractable interactable)
Determines if the Interactable is valid for selection this frame.
virtual void StartManualInteraction (XRBaseInteractable interactable)
Manually initiate selection of an Interactable.
Protected Member Functions
virtual void Reset ()
See MonoBehaviour.
virtual void Awake ()
See MonoBehaviour.
virtual void OnEnable ()
See MonoBehaviour.
virtual void OnDisable ()
See MonoBehaviour.
virtual void Start ()
See MonoBehaviour.
virtual void OnDestroy ()
See MonoBehaviour.
bool IsHovering (IXRInteractable interactable)
Determines whether this Interactor is currently hovering the Interactable.
bool IsSelecting (IXRInteractable interactable)
Determines whether this Interactor is currently selecting the Interactable.
void CaptureAttachPose (IXRSelectInteractable interactable)
Capture the current Attach Transform pose. This method is automatically called by Unity to capture the pose during the moment of selection.
virtual void OnRegistered (InteractorRegisteredEventArgs args)
The XRInteractionManager calls this method when this Interactor is registered with it.
virtual void OnUnregistered (InteractorUnregisteredEventArgs args)
The XRInteractionManager calls this method when this Interactor is unregistered from it.
virtual void OnHoverEntering (HoverEnterEventArgs args)
The XRInteractionManager calls this method right before the Interactor first initiates hovering over an Interactable in a first pass.
virtual void OnHoverEntered (HoverEnterEventArgs args)
The XRInteractionManager calls this method when the Interactor first initiates hovering over an Interactable in a second pass.
virtual void OnHoverExiting (HoverExitEventArgs args)
The XRInteractionManager calls this method right before the Interactor ends hovering over an Interactable in a first pass.
virtual void OnHoverExited (HoverExitEventArgs args)
The XRInteractionManager calls this method when the Interactor ends hovering over an Interactable in a second pass.
virtual void OnSelectEntering (SelectEnterEventArgs args)
The XRInteractionManager calls this method right before the Interactor first initiates selection of an Interactable in a first pass.
virtual void OnSelectEntered (SelectEnterEventArgs args)
The XRInteractionManager calls this method when the Interactor first initiates selection of an Interactable in a second pass.
virtual void OnSelectExiting (SelectExitEventArgs args)
The XRInteractionManager calls this method right before the Interactor ends selection of an Interactable in a first pass.
virtual void OnSelectExited (SelectExitEventArgs args)
The XRInteractionManager calls this method when the Interactor ends selection of an Interactable in a second pass.
virtual void OnHoverEntering (XRBaseInteractable interactable)
(Deprecated) The XRInteractionManager calls this method right before the Interactor first initiates hovering over an Interactable in a first pass.
virtual void OnHoverEntered (XRBaseInteractable interactable)
(Deprecated) The XRInteractionManager calls this method when the Interactor first initiates hovering over an Interactable in a second pass.
virtual void OnHoverExiting (XRBaseInteractable interactable)
(Deprecated) The XRInteractionManager calls this method right before the Interactor ends hovering over an Interactable in a first pass.
virtual void OnHoverExited (XRBaseInteractable interactable)
(Deprecated) The XRInteractionManager calls this method when the Interactor ends hovering over an Interactable in a second pass.
virtual void OnSelectEntering (XRBaseInteractable interactable)
(Deprecated) The XRInteractionManager calls this method right before the Interactor first initiates selection of an Interactable in a first pass.
virtual void OnSelectEntered (XRBaseInteractable interactable)
(Deprecated) The XRInteractionManager calls this method when the Interactor first initiates selection of an Interactable in a second pass.
virtual void OnSelectExiting (XRBaseInteractable interactable)
(Deprecated) The XRInteractionManager calls this method right before the Interactor ends selection of an Interactable in a first pass.
virtual void OnSelectExited (XRBaseInteractable interactable)
(Deprecated) The XRInteractionManager calls this method when the Interactor ends selection of an Interactable in a second pass.
Properties
XRInteractionManager interactionManager [get, set]
The XRInteractionManager that this Interactor will communicate with (will find one if null).
InteractionLayerMask interactionLayers [get, set]
Allows interaction with Interactables whose Interaction Layer Mask overlaps with any Layer in this Interaction Layer Mask.
Transform attachTransform [get, set]
The Transform that is used as the attach point for Interactables.
bool keepSelectedTargetValid [get, set]
Whether to keep selecting an Interactable after initially selecting it even when it is no longer a valid target.Return true to make the XRInteractionManager retain the selection even if the Interactable is not contained within the list of valid targets. Return false to make the Interaction Manager clear the selection if it isn't within the list of valid targets.
A common use for disabling this is for Ray Interactors used for teleportation to make the teleportation Interactable no longer selected when not currently pointing at it.
XRBaseInteractable startingSelectedInteractable [get, set]
The Interactable that this Interactor automatically selects at startup (optional, may be null).
HoverEnterEvent hoverEntered [get, set]
The event that is called when this Interactor begins hovering over an Interactable.The HoverEnterEventArgs passed to each listener is only valid while the event is invoked, do not hold a reference to it.
HoverExitEvent hoverExited [get, set]
The event that is called when this Interactor ends hovering over an Interactable.The HoverExitEventArgs passed to each listener is only valid while the event is invoked, do not hold a reference to it.
SelectEnterEvent selectEntered [get, set]
The event that is called when this Interactor begins selecting an Interactable.The SelectEnterEventArgs passed to each listener is only valid while the event is invoked, do not hold a reference to it.
SelectExitEvent selectExited [get, set]
The event that is called when this Interactor ends selecting an Interactable.The SelectEnterEventArgs passed to each listener is only valid while the event is invoked, do not hold a reference to it.
bool allowHover [get, set]
Defines whether this interactor allows hover events.
bool allowSelect [get, set]
Defines whether this interactor allows select events.
bool isPerformingManualInteraction [get]
Defines whether this interactor is performing a manual interaction or not.
List< IXRHoverInteractable > interactablesHovered = new List<IXRHoverInteractable>() [get]
(Read Only) The list of Interactables that are currently being hovered over (may by empty).You should treat this as a read only view of the list and should not modify it. It is exposed as a List<T> rather than an IReadOnlyList<T> to avoid GC Allocations when enumerating the list.
bool hasHover [get]
(Read Only) Indicates whether this Interactor is currently hovering an Interactable.In other words, returns whether interactablesHovered contains any Interactables.
interactablesHovered.Count > 0
List< IXRSelectInteractable > interactablesSelected = new List<IXRSelectInteractable>() [get]
(Read Only) The list of Interactables that are currently being selected (may by empty).This should be treated as a read only view of the list and should not be modified by external callers. It is exposed as a List<T> rather than an IReadOnlyList<T> to avoid GC Allocations when enumerating the list.
IXRSelectInteractable firstInteractableSelected [get]
(Read Only) The first Interactable selected since not having any selection. This Interactor may not currently be selecting the Interactable, which would be the case when it was released while multiple Interactables were selected.
See also
IXRSelectInteractable.firstInteractorSelecting
bool hasSelection [get]
(Read Only) Indicates whether this Interactor is currently selecting an Interactable.In other words, returns whether interactablesSelected contains any Interactables.
interactablesSelected.Count > 0
virtual bool isHoverActive [get]
(Read Only) Indicates whether this Interactor is in a state where it could hover.
virtual bool isSelectActive [get]
(Read Only) Indicates whether this Interactor is in a state where it could select.
virtual XRBaseInteractable.? MovementType selectedInteractableMovementTypeOverride [get]
(Read Only) Overriding movement type of the selected Interactable's movement. By default, this does not override the movement type.
LayerMask interactionLayerMask [get, set]
(Deprecated) Allows interaction with Interactables whose Interaction Layer Mask overlaps with any Layer in this Interaction Layer Mask.
bool enableInteractions [get, set]
(Deprecated) Defines whether interactions are enabled or not.
XRInteractorEvent onHoverEntered [get, set]
(Deprecated) Gets or sets the event that Unity calls when this Interactor begins hovering over an Interactable.
XRInteractorEvent onHoverExited [get, set]
(Deprecated) Gets or sets the event that Unity calls when this Interactor ends hovering over an Interactable.
XRInteractorEvent onSelectEntered [get, set]
(Deprecated) Gets or sets the event that Unity calls when this Interactor begins selecting an Interactable.
XRInteractorEvent onSelectExited [get, set]
(Deprecated) Gets or sets the event that Unity calls when this Interactor ends selecting an Interactable.
XRInteractorEvent onHoverEnter [get]
(Deprecated) Gets or sets the event that Unity calls when this Interactor begins hovering over an Interactable.
XRInteractorEvent onHoverExit [get]
(Deprecated) Gets or sets the event that Unity calls when this Interactor ends hovering over an Interactable.
XRInteractorEvent onSelectEnter [get]
(Deprecated) Gets or sets the event that Unity calls when this Interactor begins selecting an Interactable.
XRInteractorEvent onSelectExit [get]
(Deprecated) Gets or sets the event that Unity calls when this Interactor ends selecting an Interactable.
XRBaseInteractable selectTarget [get, protected set]
Selected Interactable for this Interactor (may be null).
List< XRBaseInteractable > hoverTargets = new List<XRBaseInteractable>() [get]
Target Interactables that are currently being hovered over (may by empty).
virtual bool requireSelectExclusive [get]
(Deprecated) (Read Only) Indicates whether this Interactor requires that an Interactable is not currently selected to begin selecting it.
Properties inherited from UnityEngine.XR.Interaction.Toolkit.IXRHoverInteractor
Properties inherited from UnityEngine.XR.Interaction.Toolkit.IXRInteractor
Transform transform [get]
(Read Only) The Transform associated with the Interactor.
Properties inherited from UnityEngine.XR.Interaction.Toolkit.IXRSelectInteractor
Events
Action< InteractorRegisteredEventArgs > registered
Action< InteractorUnregisteredEventArgs > unregistered
Events inherited from UnityEngine.XR.Interaction.Toolkit.IXRInteractor
Action< InteractorRegisteredEventArgs > registered
Calls the methods in its invocation list when this Interactor is registered with an Interaction Manager.
Action< InteractorUnregisteredEventArgs > unregistered
Calls the methods in its invocation list when this Interactor is unregistered from an Interaction Manager.
Detailed Description
Abstract base class from which all interactor behaviours derive. This class hooks into the interaction system (via XRInteractionManager) and provides base virtual methods for handling hover and selection.
Member Function Documentation
Awake()
virtual void UnityEngine.XR.Interaction.Toolkit.XRBaseInteractor.Awake () protected virtual
See MonoBehaviour.
Reimplemented in UnityEngine.XR.Interaction.Toolkit.XRBaseControllerInteractor, UnityEngine.XR.Interaction.Toolkit.XRDirectInteractor, UnityEngine.XR.Interaction.Toolkit.XRRayInteractor, and UnityEngine.XR.Interaction.Toolkit.XRSocketInteractor.
CanHover() [1/2]
virtual bool UnityEngine.XR.Interaction.Toolkit.XRBaseInteractor.CanHover (IXRHoverInteractable interactable) virtual
Determines if the Interactable is valid for hover this frame.
Parameters
interactable Interactable to check.
Returns
Returns true if the Interactable can be hovered over this frame.
See also
IXRHoverInteractable.IsHoverableBy
Implements UnityEngine.XR.Interaction.Toolkit.IXRHoverInteractor.
Reimplemented in UnityEngine.XR.Interaction.Toolkit.XRDirectInteractor, UnityEngine.XR.Interaction.Toolkit.XRRayInteractor, and UnityEngine.XR.Interaction.Toolkit.XRSocketInteractor.
CanHover() [2/2]
virtual bool UnityEngine.XR.Interaction.Toolkit.XRBaseInteractor.CanHover (XRBaseInteractable interactable) virtual
Determines if the Interactable is valid for hover this frame.
Parameters
interactable Interactable to check.
Returns
Returns true if the interactable can be hovered over this frame.
See also
XRBaseInteractable.IsHoverableBy(XRBaseInteractor)
CanHover(XRBaseInteractable) has been deprecated. Use CanHover(IXRHoverInteractable) instead.
Reimplemented in UnityEngine.XR.Interaction.Toolkit.XRDirectInteractor, UnityEngine.XR.Interaction.Toolkit.XRRayInteractor, and UnityEngine.XR.Interaction.Toolkit.XRSocketInteractor.
CanSelect() [1/2]
virtual bool UnityEngine.XR.Interaction.Toolkit.XRBaseInteractor.CanSelect (IXRSelectInteractable interactable) virtual
Determines if the Interactable is valid for selection this frame.
Parameters
interactable Interactable to check.
Returns
Returns true if the Interactable can be selected this frame.
See also
IXRSelectInteractable.IsSelectableBy
Implements UnityEngine.XR.Interaction.Toolkit.IXRSelectInteractor.
Reimplemented in UnityEngine.XR.Interaction.Toolkit.XRDirectInteractor, UnityEngine.XR.Interaction.Toolkit.XRRayInteractor, and UnityEngine.XR.Interaction.Toolkit.XRSocketInteractor.
CanSelect() [2/2]
virtual bool UnityEngine.XR.Interaction.Toolkit.XRBaseInteractor.CanSelect (XRBaseInteractable interactable) virtual
Determines if the Interactable is valid for selection this frame.
Parameters
interactable Interactable to check.
Returns
Returns true if the Interactable can be selected this frame.
See also
XRBaseInteractable.IsSelectableBy(XRBaseInteractor)
CanSelect(XRBaseInteractable) has been deprecated. Use CanSelect(IXRSelectInteractable) instead.
Reimplemented in UnityEngine.XR.Interaction.Toolkit.XRDirectInteractor, UnityEngine.XR.Interaction.Toolkit.XRRayInteractor, and UnityEngine.XR.Interaction.Toolkit.XRSocketInteractor.
CaptureAttachPose()
void UnityEngine.XR.Interaction.Toolkit.XRBaseInteractor.CaptureAttachPose (IXRSelectInteractable interactable) protected
Capture the current Attach Transform pose. This method is automatically called by Unity to capture the pose during the moment of selection.
Parameters
interactable The specific Interactable as context to get the attachment point for.
Unity automatically calls this method during OnSelectEntering(SelectEnterEventArgs) and should not typically need to be called by a user.
See also
GetAttachPoseOnSelect, GetLocalAttachPoseOnSelect, XRBaseInteractable.CaptureAttachPose
Referenced by UnityEngine.XR.Interaction.Toolkit.XRBaseInteractor.OnSelectEntering().
EndManualInteraction()
virtual void UnityEngine.XR.Interaction.Toolkit.XRBaseInteractor.EndManualInteraction () virtual
Ends the manually initiated selection of an Interactable.
See also
StartManualInteraction(IXRSelectInteractable)
GetAttachPoseOnSelect()
Pose UnityEngine.XR.Interaction.Toolkit.XRBaseInteractor.GetAttachPoseOnSelect (IXRSelectInteractable interactable)
Gets the world position and rotation of the Attach Transform captured during the moment of selection.
Parameters
interactable The specific Interactable as context to get the attachment point for.
Returns
Returns the world pose of the attachment point during the moment of selection, and otherwise the identity Pose if it was not selected during the current selection stack.
See also
GetLocalAttachPoseOnSelect, IXRInteractor.GetAttachTransform, IXRSelectInteractable.GetAttachPoseOnSelect
Implements UnityEngine.XR.Interaction.Toolkit.IXRSelectInteractor.
GetAttachTransform()
virtual Transform UnityEngine.XR.Interaction.Toolkit.XRBaseInteractor.GetAttachTransform (IXRInteractable interactable) virtual
Gets the Transform that is used as the attachment point for a given Interactable.
Parameters
interactable The specific Interactable as context to get the attachment point for.
Returns
Returns the attachment point Transform.
See also
IXRInteractable.GetAttachTransform
This should typically return the Transform of a child GameObject or the transform itself.
Implements UnityEngine.XR.Interaction.Toolkit.IXRInteractor.
Referenced by UnityEngine.XR.Interaction.Toolkit.XRBaseInteractor.CaptureAttachPose().
GetHoverTargets()
void UnityEngine.XR.Interaction.Toolkit.XRBaseInteractor.GetHoverTargets (List< XRBaseInteractable > targets)
Retrieves a copy of the list of target Interactables that are currently being hovered over.
Parameters
targets The results list to store hover targets into.
Clears targets before adding to it.
GetHoverTargets has been deprecated. Use interactablesHovered instead.
GetLocalAttachPoseOnSelect()
Pose UnityEngine.XR.Interaction.Toolkit.XRBaseInteractor.GetLocalAttachPoseOnSelect (IXRSelectInteractable interactable)
Gets the local position and rotation of the Attach Transform captured during the moment of selection.
Parameters
interactable The specific Interactable as context to get the attachment point for.
Returns
Returns the local pose of the attachment point during the moment of selection, and otherwise the identity Pose if it was not selected during the current selection stack.
See also
GetAttachPoseOnSelect, IXRInteractor.GetAttachTransform, IXRSelectInteractable.GetLocalAttachPoseOnSelect
Implements UnityEngine.XR.Interaction.Toolkit.IXRSelectInteractor.
GetValidTargets() [1/2]
virtual void UnityEngine.XR.Interaction.Toolkit.XRBaseInteractor.GetValidTargets (List< IXRInteractable > targets) virtual
Retrieve the list of Interactables that this Interactor could possibly interact with this frame. This list is sorted by priority (with highest priority first).
Parameters
targets The results list to populate with Interactables that are valid for selection or hover.
When implementing this method, Unity expects you to clear targets before adding to it.
Implements UnityEngine.XR.Interaction.Toolkit.IXRInteractor.
Reimplemented in UnityEngine.XR.Interaction.Toolkit.XRDirectInteractor, UnityEngine.XR.Interaction.Toolkit.XRRayInteractor, UnityEngine.XR.Interaction.Toolkit.XRSocketInteractor, and UnityEngine.XR.Interaction.Toolkit.Tests.MockInteractor.
Referenced by UnityEngine.XR.Interaction.Toolkit.Tests.InteractorTests.ContactInteractorCullsValidTargetsUponRegistering(), UnityEngine.XR.Interaction.Toolkit.Tests.InteractorTests.ContactInteractorCullsValidTargetsWhenInteractableUnregistered(), UnityEngine.XR.Interaction.Toolkit.Tests.InteractorTests.ContactInteractorIgnoresDisabledCollidersWhenSortingValidTargets(), UnityEngine.XR.Interaction.Toolkit.Tests.InteractorTests.ContactInteractorTargetStaysValidWhenTouchingAnyCollider(), UnityEngine.XR.Interaction.Toolkit.Tests.InteractorTests.ContactInteractorUpdatesValidTargetsForPreviouslyUnassociatedCollidersUponRegistering(), and UnityEngine.XR.Interaction.Toolkit.Tests.InteractorTests.ContactInteractorUpdatesValidTargetsForPreviouslyUnassociatedCollidersWhenInteractableRegistered().
GetValidTargets() [2/2]
virtual void UnityEngine.XR.Interaction.Toolkit.XRBaseInteractor.GetValidTargets (List< XRBaseInteractable > targets) virtual
Retrieve the list of Interactables that this Interactor could possibly interact with this frame. This list is sorted by priority (with highest priority first).
Parameters
targets The results list to populate with Interactables that are valid for selection or hover.
GetValidTargets(List<XRBaseInteractable>) has been deprecated. Use GetValidTargets(List<IXRInteractable>) instead. XRInteractionManager.GetValidTargets(IXRInteractor, List<IXRInteractable>) will stitch the results together with GetValidTargets(List<IXRInteractable>), but by default this method now does nothing.
IsHovering() [1/2]
bool UnityEngine.XR.Interaction.Toolkit.XRBaseInteractor.IsHovering (IXRHoverInteractable interactable)
Determines whether this Interactor is currently hovering the Interactable.
Parameters
interactable Interactable to check.
Returns
Returns true if this Interactor is currently hovering the Interactable. Otherwise, returns .
In other words, returns whether interactablesHovered contains interactable .
Implements UnityEngine.XR.Interaction.Toolkit.IXRHoverInteractor.
Referenced by UnityEngine.XR.Interaction.Toolkit.XRRayInteractor.TryGetHitInfo().
IsHovering() [2/2]
bool UnityEngine.XR.Interaction.Toolkit.XRBaseInteractor.IsHovering (IXRInteractable interactable) protected
Determines whether this Interactor is currently hovering the Interactable.
Parameters
interactable Interactable to check.
Returns
Returns true if this Interactor is currently hovering the Interactable. Otherwise, returns .
In other words, returns whether interactablesHovered contains interactable .
See also
interactablesHovered, IXRHoverInteractor.IsHovering
IsSelecting() [1/2]
bool UnityEngine.XR.Interaction.Toolkit.XRBaseInteractor.IsSelecting (IXRInteractable interactable) protected
Determines whether this Interactor is currently selecting the Interactable.
Parameters
interactable Interactable to check.
Returns
Returns true if this Interactor is currently selecting the Interactable. Otherwise, returns .
In other words, returns whether interactablesSelected contains interactable .
See also
interactablesSelected, IXRSelectInteractor.IsSelecting
IsSelecting() [2/2]
bool UnityEngine.XR.Interaction.Toolkit.XRBaseInteractor.IsSelecting (IXRSelectInteractable interactable)
Determines whether this Interactor is currently selecting the Interactable.
Parameters
interactable Interactable to check.
Returns
Returns true if this Interactor is currently selecting the Interactable. Otherwise, returns .
In other words, returns whether interactablesSelected contains interactable .
Implements UnityEngine.XR.Interaction.Toolkit.IXRSelectInteractor.
Referenced by UnityEngine.XR.Interaction.Toolkit.XRDirectInteractor.CanHover(), UnityEngine.XR.Interaction.Toolkit.XRRayInteractor.CanHover(), UnityEngine.XR.Interaction.Toolkit.XRDirectInteractor.CanSelect(), UnityEngine.XR.Interaction.Toolkit.XRRayInteractor.CanSelect(), UnityEngine.XR.Interaction.Toolkit.XRSocketInteractor.CanSelect(), and UnityEngine.XR.Interaction.Toolkit.XRSocketInteractor.DrawHoveredInteractables().
OnDestroy()
virtual void UnityEngine.XR.Interaction.Toolkit.XRBaseInteractor.OnDestroy () protected virtual
See MonoBehaviour.
OnDisable()
virtual void UnityEngine.XR.Interaction.Toolkit.XRBaseInteractor.OnDisable () protected virtual
See MonoBehaviour.
Reimplemented in UnityEngine.XR.Interaction.Toolkit.XRRayInteractor.
OnEnable()
virtual void UnityEngine.XR.Interaction.Toolkit.XRBaseInteractor.OnEnable () protected virtual
See MonoBehaviour.
Reimplemented in UnityEngine.XR.Interaction.Toolkit.XRRayInteractor.
OnHoverEntered() [1/2]
virtual void UnityEngine.XR.Interaction.Toolkit.XRBaseInteractor.OnHoverEntered (HoverEnterEventArgs args) protected virtual
The XRInteractionManager calls this method when the Interactor first initiates hovering over an Interactable in a second pass.
Parameters
args Event data containing the Interactable that is being hovered over.
args is only valid during this method call, do not hold a reference to it.
See also
OnHoverExited(HoverExitEventArgs)
Implements UnityEngine.XR.Interaction.Toolkit.IXRHoverInteractor.
OnHoverEntered() [2/2]
virtual void UnityEngine.XR.Interaction.Toolkit.XRBaseInteractor.OnHoverEntered (XRBaseInteractable interactable) protected virtual
(Deprecated) The XRInteractionManager calls this method when the Interactor first initiates hovering over an Interactable in a second pass.
Parameters
interactable Interactable that is being hovered over.
See also
OnHoverExited(XRBaseInteractable)
OnHoverEntered(XRBaseInteractable) has been deprecated. Use OnHoverEntered(HoverEnterEventArgs) instead.
OnHoverEntering() [1/2]
virtual void UnityEngine.XR.Interaction.Toolkit.XRBaseInteractor.OnHoverEntering (HoverEnterEventArgs args) protected virtual
The XRInteractionManager calls this method right before the Interactor first initiates hovering over an Interactable in a first pass.
Parameters
args Event data containing the Interactable that is being hovered over.
args is only valid during this method call, do not hold a reference to it.
See also
OnHoverEntered(HoverEnterEventArgs)
Implements UnityEngine.XR.Interaction.Toolkit.IXRHoverInteractor.
Reimplemented in UnityEngine.XR.Interaction.Toolkit.XRBaseControllerInteractor, and UnityEngine.XR.Interaction.Toolkit.XRSocketInteractor.
OnHoverEntering() [2/2]
virtual void UnityEngine.XR.Interaction.Toolkit.XRBaseInteractor.OnHoverEntering (XRBaseInteractable interactable) protected virtual
(Deprecated) The XRInteractionManager calls this method right before the Interactor first initiates hovering over an Interactable in a first pass.
Parameters
interactable Interactable that is being hovered over.
See also
OnHoverEntered(XRBaseInteractable)
OnHoverEntering(XRBaseInteractable) has been deprecated. Use OnHoverEntering(HoverEnterEventArgs) instead.
OnHoverExited() [1/2]
virtual void UnityEngine.XR.Interaction.Toolkit.XRBaseInteractor.OnHoverExited (HoverExitEventArgs args) protected virtual
The XRInteractionManager calls this method when the Interactor ends hovering over an Interactable in a second pass.
Parameters
args Event data containing the Interactable that is no longer hovered over.
args is only valid during this method call, do not hold a reference to it.
See also
OnHoverEntered(HoverEnterEventArgs)
Implements UnityEngine.XR.Interaction.Toolkit.IXRHoverInteractor.
OnHoverExited() [2/2]
virtual void UnityEngine.XR.Interaction.Toolkit.XRBaseInteractor.OnHoverExited (XRBaseInteractable interactable) protected virtual
(Deprecated) The XRInteractionManager calls this method when the Interactor ends hovering over an Interactable in a second pass.
Parameters
interactable Interactable that is no longer hovered over.
See also
OnHoverEntered(XRBaseInteractable)
OnHoverExited(XRBaseInteractable) has been deprecated. Use OnHoverExited(HoverExitEventArgs) instead.
OnHoverExiting() [1/2]
virtual void UnityEngine.XR.Interaction.Toolkit.XRBaseInteractor.OnHoverExiting (HoverExitEventArgs args) protected virtual
The XRInteractionManager calls this method right before the Interactor ends hovering over an Interactable in a first pass.
Parameters
args Event data containing the Interactable that is no longer hovered over.
args is only valid during this method call, do not hold a reference to it.
See also
OnHoverExited(HoverExitEventArgs)
Implements UnityEngine.XR.Interaction.Toolkit.IXRHoverInteractor.
Reimplemented in UnityEngine.XR.Interaction.Toolkit.XRBaseControllerInteractor, and UnityEngine.XR.Interaction.Toolkit.XRSocketInteractor.
OnHoverExiting() [2/2]
virtual void UnityEngine.XR.Interaction.Toolkit.XRBaseInteractor.OnHoverExiting (XRBaseInteractable interactable) protected virtual
(Deprecated) The XRInteractionManager calls this method right before the Interactor ends hovering over an Interactable in a first pass.
Parameters
interactable Interactable that is no longer hovered over.
See also
OnHoverExited(XRBaseInteractable)
OnHoverExiting(XRBaseInteractable) has been deprecated. Use OnHoverExiting(HoverExitEventArgs) instead.
OnRegistered()
virtual void UnityEngine.XR.Interaction.Toolkit.XRBaseInteractor.OnRegistered (InteractorRegisteredEventArgs args) protected virtual
The XRInteractionManager calls this method when this Interactor is registered with it.
Parameters
args Event data containing the Interaction Manager that registered this Interactor.
args is only valid during this method call, do not hold a reference to it.
See also
XRInteractionManager.RegisterInteractor(IXRInteractor)
Implements UnityEngine.XR.Interaction.Toolkit.IXRInteractor.
Reimplemented in UnityEngine.XR.Interaction.Toolkit.XRDirectInteractor, and UnityEngine.XR.Interaction.Toolkit.XRSocketInteractor.
OnSelectEntered() [1/2]
virtual void UnityEngine.XR.Interaction.Toolkit.XRBaseInteractor.OnSelectEntered (SelectEnterEventArgs args) protected virtual
The XRInteractionManager calls this method when the Interactor first initiates selection of an Interactable in a second pass.
Parameters
args Event data containing the Interactable that is being selected.
args is only valid during this method call, do not hold a reference to it.
See also
OnSelectExited(SelectExitEventArgs)
Implements UnityEngine.XR.Interaction.Toolkit.IXRSelectInteractor.
OnSelectEntered() [2/2]
virtual void UnityEngine.XR.Interaction.Toolkit.XRBaseInteractor.OnSelectEntered (XRBaseInteractable interactable) protected virtual
(Deprecated) The XRInteractionManager calls this method when the Interactor first initiates selection of an Interactable in a second pass.
Parameters
interactable Interactable that is being selected.
See also
OnSelectExited(XRBaseInteractable)
OnSelectEntered(XRBaseInteractable) has been deprecated. Use OnSelectEntered(SelectEnterEventArgs) instead.
OnSelectEntering() [1/2]
virtual void UnityEngine.XR.Interaction.Toolkit.XRBaseInteractor.OnSelectEntering (SelectEnterEventArgs args) protected virtual
The XRInteractionManager calls this method right before the Interactor first initiates selection of an Interactable in a first pass.
Parameters
args Event data containing the Interactable that is being selected.
args is only valid during this method call, do not hold a reference to it.
See also
OnSelectEntered(SelectEnterEventArgs)
Implements UnityEngine.XR.Interaction.Toolkit.IXRSelectInteractor.
Reimplemented in UnityEngine.XR.Interaction.Toolkit.XRBaseControllerInteractor, and UnityEngine.XR.Interaction.Toolkit.XRRayInteractor.
OnSelectEntering() [2/2]
virtual void UnityEngine.XR.Interaction.Toolkit.XRBaseInteractor.OnSelectEntering (XRBaseInteractable interactable) protected virtual
(Deprecated) The XRInteractionManager calls this method right before the Interactor first initiates selection of an Interactable in a first pass.
Parameters
interactable Interactable that is being selected.
See also
OnSelectEntered(XRBaseInteractable)
OnSelectEntering(XRBaseInteractable) has been deprecated. Use OnSelectEntering(SelectEnterEventArgs) instead.
OnSelectExited() [1/2]
virtual void UnityEngine.XR.Interaction.Toolkit.XRBaseInteractor.OnSelectExited (SelectExitEventArgs args) protected virtual
The XRInteractionManager calls this method when the Interactor ends selection of an Interactable in a second pass.
Parameters
args Event data containing the Interactable that is no longer selected.
args is only valid during this method call, do not hold a reference to it.
See also
OnSelectEntered(SelectEnterEventArgs)
Implements UnityEngine.XR.Interaction.Toolkit.IXRSelectInteractor.
OnSelectExited() [2/2]
virtual void UnityEngine.XR.Interaction.Toolkit.XRBaseInteractor.OnSelectExited (XRBaseInteractable interactable) protected virtual
(Deprecated) The XRInteractionManager calls this method when the Interactor ends selection of an Interactable in a second pass.
Parameters
interactable Interactable that is no longer selected.
See also
OnSelectEntered(XRBaseInteractable)
OnSelectExited(XRBaseInteractable) has been deprecated. Use OnSelectExited(SelectExitEventArgs) instead.
OnSelectExiting() [1/2]
virtual void UnityEngine.XR.Interaction.Toolkit.XRBaseInteractor.OnSelectExiting (SelectExitEventArgs args) protected virtual
The XRInteractionManager calls this method right before the Interactor ends selection of an Interactable in a first pass.
Parameters
args Event data containing the Interactable that is no longer selected.
args is only valid during this method call, do not hold a reference to it.
See also
OnSelectExited(SelectExitEventArgs)
Implements UnityEngine.XR.Interaction.Toolkit.IXRSelectInteractor.
Reimplemented in UnityEngine.XR.Interaction.Toolkit.XRBaseControllerInteractor, UnityEngine.XR.Interaction.Toolkit.XRRayInteractor, and UnityEngine.XR.Interaction.Toolkit.XRSocketInteractor.
OnSelectExiting() [2/2]
virtual void UnityEngine.XR.Interaction.Toolkit.XRBaseInteractor.OnSelectExiting (XRBaseInteractable interactable) protected virtual
(Deprecated) The XRInteractionManager calls this method right before the Interactor ends selection of an Interactable in a first pass.
Parameters
interactable Interactable that is no longer selected.
See also
OnSelectExited(XRBaseInteractable)
OnSelectExiting(XRBaseInteractable) has been deprecated. Use OnSelectExiting(SelectExitEventArgs) instead.
OnUnregistered()
virtual void UnityEngine.XR.Interaction.Toolkit.XRBaseInteractor.OnUnregistered (InteractorUnregisteredEventArgs args) protected virtual
The XRInteractionManager calls this method when this Interactor is unregistered from it.
Parameters
args Event data containing the Interaction Manager that unregistered this Interactor.
args is only valid during this method call, do not hold a reference to it.
See also
XRInteractionManager.UnregisterInteractor(IXRInteractor)
Implements UnityEngine.XR.Interaction.Toolkit.IXRInteractor.
Reimplemented in UnityEngine.XR.Interaction.Toolkit.XRDirectInteractor, and UnityEngine.XR.Interaction.Toolkit.XRSocketInteractor.
PreprocessInteractor()
virtual void UnityEngine.XR.Interaction.Toolkit.XRBaseInteractor.PreprocessInteractor (XRInteractionUpdateOrder::UpdatePhase updatePhase) virtual
The XRInteractionManager calls this method to update the Interactor before interaction events occur. Interactors should use this method to do tasks like determine their valid targets.
Parameters
updatePhase The update phase this is called during.
Please see the XRInteractionManager and XRInteractionUpdateOrder.UpdatePhase documentation for more details on update order.
Implements UnityEngine.XR.Interaction.Toolkit.IXRInteractor.
Reimplemented in UnityEngine.XR.Interaction.Toolkit.XRBaseControllerInteractor, and UnityEngine.XR.Interaction.Toolkit.XRRayInteractor.
ProcessInteractor()
virtual void UnityEngine.XR.Interaction.Toolkit.XRBaseInteractor.ProcessInteractor (XRInteractionUpdateOrder::UpdatePhase updatePhase) virtual
The XRInteractionManager calls this method to update the Interactor after interaction events occur.
Parameters
updatePhase The update phase this is called during.
Please see the XRInteractionManager and XRInteractionUpdateOrder.UpdatePhase documentation for more details on update order.
Implements UnityEngine.XR.Interaction.Toolkit.IXRInteractor.
Reimplemented in UnityEngine.XR.Interaction.Toolkit.XRBaseControllerInteractor, UnityEngine.XR.Interaction.Toolkit.XRDirectInteractor, UnityEngine.XR.Interaction.Toolkit.XRRayInteractor, and UnityEngine.XR.Interaction.Toolkit.XRSocketInteractor.
Reset()
virtual void UnityEngine.XR.Interaction.Toolkit.XRBaseInteractor.Reset () protected virtual
See MonoBehaviour.
Start()
virtual void UnityEngine.XR.Interaction.Toolkit.XRBaseInteractor.Start () protected virtual
See MonoBehaviour.
Reimplemented in UnityEngine.XR.Interaction.Toolkit.XRDirectInteractor, and UnityEngine.XR.Interaction.Toolkit.XRSocketInteractor.
StartManualInteraction() [1/2]
virtual void UnityEngine.XR.Interaction.Toolkit.XRBaseInteractor.StartManualInteraction (IXRSelectInteractable interactable) virtual
Manually initiate selection of an Interactable.
Parameters
interactable Interactable that is being selected.
See also
EndManualInteraction
StartManualInteraction() [2/2]
virtual void UnityEngine.XR.Interaction.Toolkit.XRBaseInteractor.StartManualInteraction (XRBaseInteractable interactable) virtual
Manually initiate selection of an Interactable.
Parameters
interactable Interactable that is being selected.
See also
EndManualInteraction
StartManualInteraction(XRBaseInteractable) has been deprecated. Use StartManualInteraction(IXRSelectInteractable) instead.
Property Documentation
allowHover
bool UnityEngine.XR.Interaction.Toolkit.XRBaseInteractor.allowHover get set
Defines whether this interactor allows hover events.
A hover exit event will still occur if this value is disabled while hovering.
allowSelect
bool UnityEngine.XR.Interaction.Toolkit.XRBaseInteractor.allowSelect get set
Defines whether this interactor allows select events.
A select exit event will still occur if this value is disabled while selecting.
attachTransform
Transform UnityEngine.XR.Interaction.Toolkit.XRBaseInteractor.attachTransform get set
The Transform that is used as the attach point for Interactables.
Automatically instantiated and set in Awake if null. Setting this will not automatically destroy the previous object.
Referenced by UnityEngine.XR.Interaction.Toolkit.XRRayInteractor.ProcessInteractor().
enableInteractions
bool UnityEngine.XR.Interaction.Toolkit.XRBaseInteractor.enableInteractions get set
(Deprecated) Defines whether interactions are enabled or not.
enableInteractions = value; is a convenience property for:
allowHover = value;
allowSelect = value;
enableInteractions has been deprecated. Use allowHover and allowSelect instead.
firstInteractableSelected
IXRSelectInteractable UnityEngine.XR.Interaction.Toolkit.XRBaseInteractor.firstInteractableSelected get
(Read Only) The first Interactable selected since not having any selection. This Interactor may not currently be selecting the Interactable, which would be the case when it was released while multiple Interactables were selected.
See also
IXRSelectInteractable.firstInteractorSelecting
Implements UnityEngine.XR.Interaction.Toolkit.IXRSelectInteractor.
Referenced by UnityEngine.XR.Interaction.Toolkit.XRBaseInteractor.OnSelectEntering(), and UnityEngine.XR.Interaction.Toolkit.XRBaseInteractor.OnSelectExited().
hasHover
bool UnityEngine.XR.Interaction.Toolkit.XRBaseInteractor.hasHover get
(Read Only) Indicates whether this Interactor is currently hovering an Interactable.In other words, returns whether interactablesHovered contains any Interactables.
interactablesHovered.Count > 0
Implements UnityEngine.XR.Interaction.Toolkit.IXRHoverInteractor.
Referenced by UnityEngine.XR.Interaction.Toolkit.XRBaseControllerInteractor.GetActivateTargets(), and UnityEngine.XR.Interaction.Toolkit.XRSocketInteractor.ProcessInteractor().
hasSelection
bool UnityEngine.XR.Interaction.Toolkit.XRBaseInteractor.hasSelection get
(Read Only) Indicates whether this Interactor is currently selecting an Interactable.In other words, returns whether interactablesSelected contains any Interactables.
interactablesSelected.Count > 0
Implements UnityEngine.XR.Interaction.Toolkit.IXRSelectInteractor.
Referenced by UnityEngine.XR.Interaction.Toolkit.XRDirectInteractor.CanHover(), UnityEngine.XR.Interaction.Toolkit.XRRayInteractor.CanHover(), UnityEngine.XR.Interaction.Toolkit.XRDirectInteractor.CanSelect(), UnityEngine.XR.Interaction.Toolkit.XRRayInteractor.CanSelect(), UnityEngine.XR.Interaction.Toolkit.XRSocketInteractor.CanSelect(), UnityEngine.XR.Interaction.Toolkit.XRSocketInteractor.DrawHoveredInteractables(), UnityEngine.XR.Interaction.Toolkit.XRBaseControllerInteractor.GetActivateTargets(), UnityEngine.XR.Interaction.Toolkit.XRRayInteractor.OnSelectExiting(), and UnityEngine.XR.Interaction.Toolkit.XRRayInteractor.ProcessInteractor().
hoverEntered
HoverEnterEvent UnityEngine.XR.Interaction.Toolkit.XRBaseInteractor.hoverEntered get set
The event that is called when this Interactor begins hovering over an Interactable.The HoverEnterEventArgs passed to each listener is only valid while the event is invoked, do not hold a reference to it.
Implements UnityEngine.XR.Interaction.Toolkit.IXRHoverInteractor.
hoverExited
HoverExitEvent UnityEngine.XR.Interaction.Toolkit.XRBaseInteractor.hoverExited get set
The event that is called when this Interactor ends hovering over an Interactable.The HoverExitEventArgs passed to each listener is only valid while the event is invoked, do not hold a reference to it.
Implements UnityEngine.XR.Interaction.Toolkit.IXRHoverInteractor.
hoverTargets
List<XRBaseInteractable> UnityEngine.XR.Interaction.Toolkit.XRBaseInteractor.hoverTargets = new List<XRBaseInteractable>() get protected
Target Interactables that are currently being hovered over (may by empty).
See also
XRBaseInteractable.hoveringInteractors
hoverTargets has been deprecated. Use interactablesHovered instead.
Referenced by UnityEngine.XR.Interaction.Toolkit.XRBaseInteractor.GetHoverTargets(), UnityEngine.XR.Interaction.Toolkit.XRBaseInteractor.OnHoverEntering(), and UnityEngine.XR.Interaction.Toolkit.XRBaseInteractor.OnHoverExiting().
interactablesHovered
List<IXRHoverInteractable> UnityEngine.XR.Interaction.Toolkit.XRBaseInteractor.interactablesHovered = new List<IXRHoverInteractable>() get
(Read Only) The list of Interactables that are currently being hovered over (may by empty).You should treat this as a read only view of the list and should not modify it. It is exposed as a List<T> rather than an IReadOnlyList<T> to avoid GC Allocations when enumerating the list.
Implements UnityEngine.XR.Interaction.Toolkit.IXRHoverInteractor.
Referenced by UnityEngine.XR.Interaction.Toolkit.XRSocketInteractor.DrawHoveredInteractables(), UnityEngine.XR.Interaction.Toolkit.XRBaseControllerInteractor.GetActivateTargets(), UnityEngine.XR.Interaction.Toolkit.XRBaseInteractor.IsHovering(), UnityEngine.XR.Interaction.Toolkit.XRBaseInteractor.OnHoverEntering(), and UnityEngine.XR.Interaction.Toolkit.XRBaseInteractor.OnHoverExiting().
interactablesSelected
List<IXRSelectInteractable> UnityEngine.XR.Interaction.Toolkit.XRBaseInteractor.interactablesSelected = new List<IXRSelectInteractable>() get
(Read Only) The list of Interactables that are currently being selected (may by empty).This should be treated as a read only view of the list and should not be modified by external callers. It is exposed as a List<T> rather than an IReadOnlyList<T> to avoid GC Allocations when enumerating the list.
Implements UnityEngine.XR.Interaction.Toolkit.IXRSelectInteractor.
Referenced by UnityEngine.XR.Interaction.Toolkit.XRBaseControllerInteractor.GetActivateTargets(), UnityEngine.XR.Interaction.Toolkit.XRBaseInteractor.IsSelecting(), UnityEngine.XR.Interaction.Toolkit.XRBaseInteractor.OnSelectEntering(), UnityEngine.XR.Interaction.Toolkit.XRRayInteractor.OnSelectEntering(), UnityEngine.XR.Interaction.Toolkit.XRBaseInteractor.OnSelectExited(), and UnityEngine.XR.Interaction.Toolkit.XRBaseInteractor.OnSelectExiting().
interactionLayerMask
LayerMask UnityEngine.XR.Interaction.Toolkit.XRBaseInteractor.interactionLayerMask get set
(Deprecated) Allows interaction with Interactables whose Interaction Layer Mask overlaps with any Layer in this Interaction Layer Mask.
See also
XRBaseInteractable.interactionLayerMask
interactionLayerMask has been deprecated. Use interactionLayers instead.
interactionLayers
InteractionLayerMask UnityEngine.XR.Interaction.Toolkit.XRBaseInteractor.interactionLayers get set
Allows interaction with Interactables whose Interaction Layer Mask overlaps with any Layer in this Interaction Layer Mask.
See also
IXRInteractable.interactionLayers, CanHover(IXRHoverInteractable), CanSelect(IXRSelectInteractable)
(Read Only) Allows interaction with Interactables whose Interaction Layer Mask overlaps with any Layer in this Interaction Layer Mask.
See also
IXRInteractable.interactionLayers
Implements UnityEngine.XR.Interaction.Toolkit.IXRInteractor.
interactionManager
XRInteractionManager UnityEngine.XR.Interaction.Toolkit.XRBaseInteractor.interactionManager get set
The XRInteractionManager that this Interactor will communicate with (will find one if null).
Referenced by UnityEngine.XR.Interaction.Toolkit.XRDirectInteractor.Awake(), UnityEngine.XR.Interaction.Toolkit.XRSocketInteractor.Awake(), UnityEngine.XR.Interaction.Toolkit.XRBaseInteractor.EndManualInteraction(), UnityEngine.XR.Interaction.Toolkit.XRRayInteractor.GetValidTargets(), UnityEngine.XR.Interaction.Toolkit.XRBaseInteractor.StartManualInteraction(), and UnityEngine.XR.Interaction.Toolkit.XRRayInteractor.TryGetHitInfo().
isHoverActive
virtual bool UnityEngine.XR.Interaction.Toolkit.XRBaseInteractor.isHoverActive get
(Read Only) Indicates whether this Interactor is in a state where it could hover.
Implements UnityEngine.XR.Interaction.Toolkit.IXRHoverInteractor.
isPerformingManualInteraction
bool UnityEngine.XR.Interaction.Toolkit.XRBaseInteractor.isPerformingManualInteraction get
Defines whether this interactor is performing a manual interaction or not.
See also
StartManualInteraction(IXRSelectInteractable), EndManualInteraction
isSelectActive
virtual bool UnityEngine.XR.Interaction.Toolkit.XRBaseInteractor.isSelectActive get
(Read Only) Indicates whether this Interactor is in a state where it could select.
Implements UnityEngine.XR.Interaction.Toolkit.IXRSelectInteractor.
keepSelectedTargetValid
bool UnityEngine.XR.Interaction.Toolkit.XRBaseInteractor.keepSelectedTargetValid get set
Whether to keep selecting an Interactable after initially selecting it even when it is no longer a valid target.Return true to make the XRInteractionManager retain the selection even if the Interactable is not contained within the list of valid targets. Return false to make the Interaction Manager clear the selection if it isn't within the list of valid targets.
A common use for disabling this is for Ray Interactors used for teleportation to make the teleportation Interactable no longer selected when not currently pointing at it.
Implements UnityEngine.XR.Interaction.Toolkit.IXRSelectInteractor.
onHoverEnter
XRInteractorEvent UnityEngine.XR.Interaction.Toolkit.XRBaseInteractor.onHoverEnter get
(Deprecated) Gets or sets the event that Unity calls when this Interactor begins hovering over an Interactable.
onHoverEnter has been deprecated. Use onHoverEntered instead.
onHoverEntered
XRInteractorEvent UnityEngine.XR.Interaction.Toolkit.XRBaseInteractor.onHoverEntered get set
(Deprecated) Gets or sets the event that Unity calls when this Interactor begins hovering over an Interactable.
onHoverEntered has been deprecated. Use hoverEntered with updated signature instead.
onHoverExit
XRInteractorEvent UnityEngine.XR.Interaction.Toolkit.XRBaseInteractor.onHoverExit get
(Deprecated) Gets or sets the event that Unity calls when this Interactor ends hovering over an Interactable.
onHoverExit has been deprecated. Use onHoverExited instead.
onHoverExited
XRInteractorEvent UnityEngine.XR.Interaction.Toolkit.XRBaseInteractor.onHoverExited get set
(Deprecated) Gets or sets the event that Unity calls when this Interactor ends hovering over an Interactable.
onHoverExited has been deprecated. Use hoverExited with updated signature instead.
onSelectEnter
XRInteractorEvent UnityEngine.XR.Interaction.Toolkit.XRBaseInteractor.onSelectEnter get
(Deprecated) Gets or sets the event that Unity calls when this Interactor begins selecting an Interactable.
onSelectEnter has been deprecated. Use onSelectEntered instead.
onSelectEntered
XRInteractorEvent UnityEngine.XR.Interaction.Toolkit.XRBaseInteractor.onSelectEntered get set
(Deprecated) Gets or sets the event that Unity calls when this Interactor begins selecting an Interactable.
onSelectEntered has been deprecated. Use selectEntered with updated signature instead.
onSelectExit
XRInteractorEvent UnityEngine.XR.Interaction.Toolkit.XRBaseInteractor.onSelectExit get
(Deprecated) Gets or sets the event that Unity calls when this Interactor ends selecting an Interactable.
onSelectExit> has been deprecated. Use onSelectExited instead.
onSelectExited
XRInteractorEvent UnityEngine.XR.Interaction.Toolkit.XRBaseInteractor.onSelectExited get set
(Deprecated) Gets or sets the event that Unity calls when this Interactor ends selecting an Interactable.
onSelectExited has been deprecated. Use selectExited with updated signature instead.
requireSelectExclusive
virtual bool UnityEngine.XR.Interaction.Toolkit.XRBaseInteractor.requireSelectExclusive get
(Deprecated) (Read Only) Indicates whether this Interactor requires that an Interactable is not currently selected to begin selecting it.
When true, the Interaction Manager will only begin a selection when the Interactable is not currently selected.
requireSelectExclusive has been deprecated. Put logic in CanSelect(IXRSelectInteractable) instead.
Referenced by UnityEngine.XR.Interaction.Toolkit.XRInteractionManager.ResolveExistingSelect().
selectedInteractableMovementTypeOverride
virtual XRBaseInteractable.? MovementType UnityEngine.XR.Interaction.Toolkit.XRBaseInteractor.selectedInteractableMovementTypeOverride get
(Read Only) Overriding movement type of the selected Interactable's movement. By default, this does not override the movement type.
You can use this to change the effective movement type of an Interactable for different Interactors. An example would be having an Interactable use XRBaseInteractable.MovementType.VelocityTracking so it does not move through geometry with a Collider when interacting with it using a Ray or Direct Interactor, but have a Socket Interactor override the movement type to be XRBaseInteractable.MovementType.Instantaneous for reduced movement latency.
See also
XRGrabInteractable.movementType
selectEntered
SelectEnterEvent UnityEngine.XR.Interaction.Toolkit.XRBaseInteractor.selectEntered get set
The event that is called when this Interactor begins selecting an Interactable.The SelectEnterEventArgs passed to each listener is only valid while the event is invoked, do not hold a reference to it.
Implements UnityEngine.XR.Interaction.Toolkit.IXRSelectInteractor.
Referenced by UnityEngine.XR.Interaction.Toolkit.XRInteractorReticleVisual.Awake(), and UnityEngine.XR.Interaction.Toolkit.XRInteractorReticleVisual.OnDestroy().
selectExited
SelectExitEvent UnityEngine.XR.Interaction.Toolkit.XRBaseInteractor.selectExited get set
The event that is called when this Interactor ends selecting an Interactable.The SelectEnterEventArgs passed to each listener is only valid while the event is invoked, do not hold a reference to it.
Implements UnityEngine.XR.Interaction.Toolkit.IXRSelectInteractor.
selectTarget
XRBaseInteractable UnityEngine.XR.Interaction.Toolkit.XRBaseInteractor.selectTarget get protected set
Selected Interactable for this Interactor (may be null).
See also
XRBaseInteractable.selectingInteractor
selectTarget has been deprecated. Use interactablesSelected, XRSelectInteractorExtensions.GetOldestInteractableSelected(IXRSelectInteractor), hasSelection, or XRBaseInteractor.IsSelecting(IXRSelectInteractable) instead.
startingSelectedInteractable
XRBaseInteractable UnityEngine.XR.Interaction.Toolkit.XRBaseInteractor.startingSelectedInteractable get set
The Interactable that this Interactor automatically selects at startup (optional, may be null).
Referenced by UnityEngine.XR.Interaction.Toolkit.XRBaseControllerInteractor.Awake().
Event Documentation
registered
Action<InteractorRegisteredEventArgs> UnityEngine.XR.Interaction.Toolkit.XRBaseInteractor.registered
Referenced by UnityEngine.XR.Interaction.Toolkit.XRBaseInteractor.OnRegistered().
unregistered
Action<InteractorUnregisteredEventArgs> UnityEngine.XR.Interaction.Toolkit.XRBaseInteractor.unregistered
Referenced by UnityEngine.XR.Interaction.Toolkit.XRBaseInteractor.OnUnregistered().
The documentation for this class was generated from the following files:
C:/Users/Lykos/Desktop/Projects/Capstone/VRGames/Library/PackageCache/com.unity.xr.interaction.toolkit@2.0.2/Runtime/Interaction/Interactors/XRBaseInteractor.cs
C:/Users/Lykos/Desktop/Projects/Capstone/VRGames/Library/PackageCache/com.unity.xr.interaction.toolkit@2.0.2/Runtime/Interaction/Interactors/XRBaseInteractor.deprecated.cs