VRCapstoneGames: UnityEngine.InputSystem.LowLevel.InputStateHistory< TValue > Class Template Reference
UnityEngine.InputSystem.LowLevel.InputStateHistory< TValue > Class Template Reference
Record a history of state changes applied to one or more controls.
Classes
struct Record
struct RecordHeader
Public Member Functions
InputStateHistory (int maxStateSizeInBytes)
InputStateHistory (string path)
InputStateHistory (InputControl control)
InputStateHistory (IEnumerable< InputControl > controls)
void Clear ()
unsafe Record AddRecord (Record record)
void StartRecording ()
void StopRecording ()
unsafe Record RecordStateChange (InputControl control, InputEventPtr eventPtr)
unsafe Record RecordStateChange (InputControl control, void *statePtr, double time)
IEnumerator< Record > GetEnumerator ()
void Dispose ()
InputStateHistory (int? maxStateSizeInBytes=null)
InputStateHistory (InputControl< TValue > control)
InputStateHistory (string path)
unsafe Record AddRecord (Record record)
unsafe Record RecordStateChange (InputControl< TValue > control, TValue value, double time=-1)
new IEnumerator< Record > GetEnumerator ()
Protected Member Functions
void Destroy ()
unsafe TValue ReadValue< TValue > (RecordHeader *data)
unsafe object ReadValueAsObject (RecordHeader *data)
Properties
int Count [get]
Total number of state records currently captured in the history.
uint version [get]
Current version stamp. Every time a record is stored in the history, this is incremented by one.
int historyDepth [get, set]
Maximum number of records that can be recorded in the history.
int extraMemoryPerRecord [get, set]
InputUpdateType updateMask [get, set]
ReadOnlyArray< InputControl > controls [get]
unsafe Record this[int index] [get, set]
Action< Record > onRecordAdded [get, set]
Func< InputControl, double, InputEventPtr, bool > onShouldRecordStateChange [get, set]
new unsafe Record this[int index] [get, set]
Detailed Description
Record a history of state changes applied to one or more controls.
Records value changes of a given control over time.
This class makes it easy to track input values over time. It will automatically retain input state up to a given maximum history depth (historyDepth). When the history is full, it will start overwriting the oldest entry each time a new history record is received.
The class listens to changes on the given controls by adding change monitors (IInputStateChangeMonitor) to each control.
// Track all stick controls in the system.
var history = new InputStateHistory<Vector2>("*&zwj;/<Stick>");
foreach (var control in history.controls)
    Debug.Log("Capturing input on " + control);
// Start capturing.
history.StartRecording();
// Perform a couple artificial value changes.
Gamepad.current.leftStick.QueueValueChange(new Vector2(0.123f, 0.234f));
Gamepad.current.leftStick.QueueValueChange(new Vector2(0.234f, 0.345f));
Gamepad.current.leftStick.QueueValueChange(new Vector2(0.345f, 0.456f));
InputSystem.Update();
// Every value change will be visible in the history.
foreach (var record in history)
    Debug.Log($"{record.control} changed value to {record.ReadValue()}");
// Histories allocate unmanaged memory and must be disposed of in order to not leak.
history.Dispose();
Template Parameters
TValue
Type Constraints
TValue : struct
Constructor & Destructor Documentation
InputStateHistory() [1/7]
UnityEngine.InputSystem.LowLevel.InputStateHistory< TValue >.InputStateHistory (int maxStateSizeInBytes)
InputStateHistory() [2/7]
UnityEngine.InputSystem.LowLevel.InputStateHistory< TValue >.InputStateHistory (string path)
InputStateHistory() [3/7]
UnityEngine.InputSystem.LowLevel.InputStateHistory< TValue >.InputStateHistory (InputControl control)
InputStateHistory() [4/7]
UnityEngine.InputSystem.LowLevel.InputStateHistory< TValue >.InputStateHistory (IEnumerable< InputControl > controls)
InputStateHistory() [5/7]
UnityEngine.InputSystem.LowLevel.InputStateHistory< TValue >.InputStateHistory (int? maxStateSizeInBytes = null)
InputStateHistory() [6/7]
UnityEngine.InputSystem.LowLevel.InputStateHistory< TValue >.InputStateHistory (InputControl< TValue > control)
InputStateHistory() [7/7]
UnityEngine.InputSystem.LowLevel.InputStateHistory< TValue >.InputStateHistory (string path)
Member Function Documentation
AddRecord() [1/2]
unsafe Record UnityEngine.InputSystem.LowLevel.InputStateHistory< TValue >.AddRecord (Record record)
AddRecord() [2/2]
unsafe Record UnityEngine.InputSystem.LowLevel.InputStateHistory< TValue >.AddRecord (Record record)
Clear()
void UnityEngine.InputSystem.LowLevel.InputStateHistory< TValue >.Clear ()
Destroy()
void UnityEngine.InputSystem.LowLevel.InputStateHistory< TValue >.Destroy () protected
Referenced by UnityEngine.InputSystem.LowLevel.InputStateHistory< TValue >.Dispose().
Dispose()
void UnityEngine.InputSystem.LowLevel.InputStateHistory< TValue >.Dispose ()
GetEnumerator() [1/2]
IEnumerator< Record > UnityEngine.InputSystem.LowLevel.InputStateHistory< TValue >.GetEnumerator ()
GetEnumerator() [2/2]
new IEnumerator< Record > UnityEngine.InputSystem.LowLevel.InputStateHistory< TValue >.GetEnumerator ()
ReadValue< TValue >()
unsafe TValue UnityEngine.InputSystem.LowLevel.InputStateHistory< TValue >.ReadValue< TValue > (RecordHeader * data) protected
Type Constraints
TValue : struct
ReadValueAsObject()
unsafe object UnityEngine.InputSystem.LowLevel.InputStateHistory< TValue >.ReadValueAsObject (RecordHeader * data) protected
RecordStateChange() [1/3]
unsafe Record UnityEngine.InputSystem.LowLevel.InputStateHistory< TValue >.RecordStateChange (InputControl control, InputEventPtr eventPtr)
Referenced by UnityEngine.InputSystem.LowLevel.InputStateHistory< TValue >.RecordStateChange(), and UnityEngine.InputSystem.LowLevel.InputStateHistory< TValue >.RecordStateChange().
RecordStateChange() [2/3]
unsafe Record UnityEngine.InputSystem.LowLevel.InputStateHistory< TValue >.RecordStateChange (InputControl control, void * statePtr, double time)
RecordStateChange() [3/3]
unsafe Record UnityEngine.InputSystem.LowLevel.InputStateHistory< TValue >.RecordStateChange (InputControl< TValue > control, TValue value, double time = -1)
StartRecording()
void UnityEngine.InputSystem.LowLevel.InputStateHistory< TValue >.StartRecording ()
StopRecording()
void UnityEngine.InputSystem.LowLevel.InputStateHistory< TValue >.StopRecording ()
Referenced by UnityEngine.InputSystem.LowLevel.InputStateHistory< TValue >.Dispose().
Property Documentation
controls
ReadOnlyArray<InputControl> UnityEngine.InputSystem.LowLevel.InputStateHistory< TValue >.controls get
Referenced by UnityEngine.InputSystem.LowLevel.InputStateHistory< TValue >.InputStateHistory(), UnityEngine.InputSystem.LowLevel.InputStateHistory< TValue >.InputStateHistory(), UnityEngine.InputSystem.LowLevel.InputStateHistory< TValue >.ReadValue< TValue >(), UnityEngine.InputSystem.LowLevel.InputStateHistory< TValue >.ReadValueAsObject(), UnityEngine.InputSystem.LowLevel.InputStateHistory< TValue >.StartRecording(), and UnityEngine.InputSystem.LowLevel.InputStateHistory< TValue >.StopRecording().
Count
int UnityEngine.InputSystem.LowLevel.InputStateHistory< TValue >.Count get
Total number of state records currently captured in the history.
Number of records in the collection.
This will always be at most historyDepth.
See also
historyDepth, RecordStateChange(InputControl,InputEventPtr)
extraMemoryPerRecord
int UnityEngine.InputSystem.LowLevel.InputStateHistory< TValue >.extraMemoryPerRecord get set
historyDepth
int UnityEngine.InputSystem.LowLevel.InputStateHistory< TValue >.historyDepth get set
Maximum number of records that can be recorded in the history.
Upper limit on number of records.
Exceptions
ArgumentException value is negative.
A fixed size memory block of unmanaged memory will be allocated to store history records. This property determines TODO
onRecordAdded
Action<Record> UnityEngine.InputSystem.LowLevel.InputStateHistory< TValue >.onRecordAdded get set
Referenced by UnityEngine.InputSystem.LowLevel.InputStateHistory< TValue >.RecordStateChange().
onShouldRecordStateChange
Func<InputControl, double, InputEventPtr, bool> UnityEngine.InputSystem.LowLevel.InputStateHistory< TValue >.onShouldRecordStateChange get set
this[int index] [1/2]
unsafe Record UnityEngine.InputSystem.LowLevel.InputStateHistory< TValue >.this[int index] get set
this[int index] [2/2]
new unsafe Record UnityEngine.InputSystem.LowLevel.InputStateHistory< TValue >.this[int index] get set
updateMask
InputUpdateType UnityEngine.InputSystem.LowLevel.InputStateHistory< TValue >.updateMask get set
version
uint UnityEngine.InputSystem.LowLevel.InputStateHistory< TValue >.version get
Current version stamp. Every time a record is stored in the history, this is incremented by one.
Version stamp that indicates the number of mutations.
See also
RecordStateChange(InputControl,InputEventPtr)
The documentation for this class was generated from the following file:
C:/Users/Lykos/Desktop/Projects/Capstone/VRGames/Library/PackageCache/com.unity.inputsystem@1.3.0/InputSystem/State/InputStateHistory.cs