VRCapstoneGames: Oculus.Interaction.GrabStrengthIndicator Class Reference
Oculus.Interaction.GrabStrengthIndicator Class Reference
Public Member Functions
void InjectAllGrabStrengthIndicator (IHandGrabInteractor handGrab, IInteractor interactor, MaterialPropertyBlockEditor handMaterialPropertyBlockEditor)
void InjectHandGrab (IHandGrabInteractor handGrab)
void InjectInteractor (IInteractor interactor)
void InjectHandMaterialPropertyBlockEditor (MaterialPropertyBlockEditor handMaterialPropertyBlockEditor)
Protected Member Functions
virtual void Start ()
virtual void OnEnable ()
virtual void OnDisable ()
Protected Attributes
bool _started = false
Properties
float GlowLerpSpeed [get, set]
float GlowColorLerpSpeed [get, set]
Color FingerGlowColorWithInteractable [get, set]
Color FingerGlowColorWithNoInteractable [get, set]
Member Function Documentation
InjectAllGrabStrengthIndicator()
void Oculus.Interaction.GrabStrengthIndicator.InjectAllGrabStrengthIndicator (IHandGrabInteractor handGrab, IInteractor interactor, MaterialPropertyBlockEditor handMaterialPropertyBlockEditor)
InjectHandGrab()
void Oculus.Interaction.GrabStrengthIndicator.InjectHandGrab (IHandGrabInteractor handGrab)
Referenced by Oculus.Interaction.GrabStrengthIndicator.InjectAllGrabStrengthIndicator().
InjectHandMaterialPropertyBlockEditor()
void Oculus.Interaction.GrabStrengthIndicator.InjectHandMaterialPropertyBlockEditor (MaterialPropertyBlockEditor handMaterialPropertyBlockEditor)
Referenced by Oculus.Interaction.GrabStrengthIndicator.InjectAllGrabStrengthIndicator().
InjectInteractor()
void Oculus.Interaction.GrabStrengthIndicator.InjectInteractor (IInteractor interactor)
Referenced by Oculus.Interaction.GrabStrengthIndicator.InjectAllGrabStrengthIndicator().
OnDisable()
virtual void Oculus.Interaction.GrabStrengthIndicator.OnDisable () protected virtual
OnEnable()
virtual void Oculus.Interaction.GrabStrengthIndicator.OnEnable () protected virtual
Start()
virtual void Oculus.Interaction.GrabStrengthIndicator.Start () protected virtual
Member Data Documentation
_started
bool Oculus.Interaction.GrabStrengthIndicator._started = false protected
Referenced by Oculus.Interaction.GrabStrengthIndicator.OnDisable(), Oculus.Interaction.GrabStrengthIndicator.OnEnable(), and Oculus.Interaction.GrabStrengthIndicator.Start().
Property Documentation
FingerGlowColorWithInteractable
Color Oculus.Interaction.GrabStrengthIndicator.FingerGlowColorWithInteractable get set
FingerGlowColorWithNoInteractable
Color Oculus.Interaction.GrabStrengthIndicator.FingerGlowColorWithNoInteractable get set
GlowColorLerpSpeed
float Oculus.Interaction.GrabStrengthIndicator.GlowColorLerpSpeed get set
GlowLerpSpeed
float Oculus.Interaction.GrabStrengthIndicator.GlowLerpSpeed get set
The documentation for this class was generated from the following file:
C:/Users/Lykos/Desktop/Projects/Capstone/VRGames/Assets/ThirdParty/Oculus/Interaction/Runtime/Scripts/Grab/Visuals/GrabStrengthIndicator.cs