VRCapstoneGames: UnityEngine.InputSystem.InputTestFixture Class Reference
UnityEngine.InputSystem.InputTestFixture Class Reference
A test fixture for writing tests that use the input system. Can be derived from or simply instantiated from another test fixture.
Classes
class ActionConstraint
Public Member Functions
virtual void Setup ()
Put InputSystem into a known state where it only has a basic set of layouts and does not have any input devices.
virtual void TearDown ()
Restore the state of the input system it had when the test was started.
unsafe void SetKeyboardLayout (string name, Keyboard keyboard=null)
Set Keyboard.keyboardLayout of the given keyboard.
unsafe void SetKeyInfo (Key key, string displayName, int scanCode=0)
Set the InputControl.displayName of key on the current Keyboard to be displayName .
ActionConstraint Started (InputAction action, InputControl control=null, double? time=null, object value=null)
ActionConstraint Started< TValue > (InputAction action, InputControl< TValue > control, TValue value, double? time=null)
ActionConstraint Performed (InputAction action, InputControl control=null, double? time=null, double? duration=null, object value=null)
ActionConstraint Performed< TValue > (InputAction action, InputControl< TValue > control, TValue value, double? time=null, double? duration=null)
ActionConstraint Canceled (InputAction action, InputControl control=null, double? time=null, double? duration=null, object value=null)
ActionConstraint Canceled< TValue > (InputAction action, InputControl< TValue > control, TValue value, double? time=null, double? duration=null)
ActionConstraint Started< TInteraction > (InputAction action, InputControl control=null, object value=null, double? time=null)
ActionConstraint Performed< TInteraction > (InputAction action, InputControl control=null, object value=null, double? time=null, double? duration=null)
ActionConstraint Canceled< TInteraction > (InputAction action, InputControl control=null, object value=null, double? time=null, double? duration=null)
void Press (ButtonControl button, double time=-1, double timeOffset=0, bool queueEventOnly=false)
void Release (ButtonControl button, double time=-1, double timeOffset=0, bool queueEventOnly=false)
void PressAndRelease (ButtonControl button, double time=-1, double timeOffset=0, bool queueEventOnly=false)
void Click (ButtonControl button, double time=-1, double timeOffset=0, bool queueEventOnly=false)
void Set< TValue > (InputDevice device, string path, TValue state, double time=-1, double timeOffset=0, bool queueEventOnly=false)
Set the control with the given path on device to the given state by sending a state event with the value to the device.
void Set< TValue > (InputControl< TValue > control, TValue state, double time=-1, double timeOffset=0, bool queueEventOnly=false)
Set the control to the given value by sending a state event with the value to the control's device.
void Move (InputControl< Vector2 > positionControl, Vector2 position, Vector2? delta=null, double time=-1, double timeOffset=0, bool queueEventOnly=false)
void BeginTouch (int touchId, Vector2 position, bool queueEventOnly=false, Touchscreen screen=null, double time=-1, double timeOffset=0)
void BeginTouch (int touchId, Vector2 position, float pressure, bool queueEventOnly=false, Touchscreen screen=null, double time=-1, double timeOffset=0)
void MoveTouch (int touchId, Vector2 position, Vector2 delta=default, bool queueEventOnly=false, Touchscreen screen=null, double time=-1, double timeOffset=0)
void MoveTouch (int touchId, Vector2 position, float pressure, Vector2 delta=default, bool queueEventOnly=false, Touchscreen screen=null, double time=-1, double timeOffset=0)
void EndTouch (int touchId, Vector2 position, Vector2 delta=default, bool queueEventOnly=false, Touchscreen screen=null, double time=-1, double timeOffset=0)
void EndTouch (int touchId, Vector2 position, float pressure, Vector2 delta=default, bool queueEventOnly=false, Touchscreen screen=null, double time=-1, double timeOffset=0)
void CancelTouch (int touchId, Vector2 position, Vector2 delta=default, bool queueEventOnly=false, Touchscreen screen=null, double time=-1, double timeOffset=0)
void CancelTouch (int touchId, Vector2 position, float pressure, Vector2 delta=default, bool queueEventOnly=false, Touchscreen screen=null, double time=-1, double timeOffset=0)
void SetTouch (int touchId, TouchPhase phase, Vector2 position, Vector2 delta=default, bool queueEventOnly=true, Touchscreen screen=null, double time=-1, double timeOffset=0)
void SetTouch (int touchId, TouchPhase phase, Vector2 position, float pressure, Vector2 delta=default, bool queueEventOnly=true, Touchscreen screen=null, double time=-1, double timeOffset=0)
void Trigger< TValue > (InputAction action, InputControl< TValue > control, TValue value)
void Trigger (InputAction action)
Perform the input action without having to know what it is bound to.
Static Public Member Functions
static void AssertButtonPress< TState > (InputDevice device, TState state, params ButtonControl[] buttons)
static void AssertStickValues (StickControl stick, Vector2 stickValue, float up, float down, float left, float right)
Properties
double currentTime [get, set]
Get or set the current time used by the input system.
Detailed Description
A test fixture for writing tests that use the input system. Can be derived from or simply instantiated from another test fixture.
The fixture will put the input system into a known state where it has only the built-in set of basic layouts and no devices. The state of the system before starting a test is recorded and restored when the test finishes.
public class MyInputTests : InputTestFixture
{
    public override void Setup()
    {
        base.Setup();
        InputSystem.RegisterLayout<MyDevice>();
    }
    [Test]
    public void CanCreateMyDevice()
    {
        InputSystem.AddDevice<MyDevice>();
        Assert.That(InputSystem.devices, Has.Exactly(1).TypeOf<MyDevice>());
    }
}
The test fixture will also sever the tie of the input system to the Unity runtime. This means that while the test fixture is active, the input system will not receive input and device discovery or removal notifications from platform code. This ensures that while the test is running, input that may be generated on the machine running the test will not infer with it.
Member Function Documentation
AssertButtonPress< TState >()
static void UnityEngine.InputSystem.InputTestFixture.AssertButtonPress< TState > (InputDevice device, TState state, params ButtonControl[] buttons) static
Type Constraints
TState : struct
TState : IInputStateTypeInfo
AssertStickValues()
static void UnityEngine.InputSystem.InputTestFixture.AssertStickValues (StickControl stick, Vector2 stickValue, float up, float down, float left, float right) static
BeginTouch() [1/2]
void UnityEngine.InputSystem.InputTestFixture.BeginTouch (int touchId, Vector2 position, bool queueEventOnly = false, Touchscreen screen = null, double time = -1, double timeOffset = 0)
BeginTouch() [2/2]
void UnityEngine.InputSystem.InputTestFixture.BeginTouch (int touchId, Vector2 position, float pressure, bool queueEventOnly = false, Touchscreen screen = null, double time = -1, double timeOffset = 0)
Canceled()
ActionConstraint UnityEngine.InputSystem.InputTestFixture.Canceled (InputAction action, InputControl control = null, double? time = null, double? duration = null, object value = null)
Canceled< TInteraction >()
ActionConstraint UnityEngine.InputSystem.InputTestFixture.Canceled< TInteraction > (InputAction action, InputControl control = null, object value = null, double? time = null, double? duration = null)
Type Constraints
TInteraction : IInputInteraction
Canceled< TValue >()
ActionConstraint UnityEngine.InputSystem.InputTestFixture.Canceled< TValue > (InputAction action, InputControl< TValue > control, TValue value, double? time = null, double? duration = null)
Type Constraints
TValue : struct
CancelTouch() [1/2]
void UnityEngine.InputSystem.InputTestFixture.CancelTouch (int touchId, Vector2 position, float pressure, Vector2 delta = default, bool queueEventOnly = false, Touchscreen screen = null, double time = -1, double timeOffset = 0)
CancelTouch() [2/2]
void UnityEngine.InputSystem.InputTestFixture.CancelTouch (int touchId, Vector2 position, Vector2 delta = default, bool queueEventOnly = false, Touchscreen screen = null, double time = -1, double timeOffset = 0)
Click()
void UnityEngine.InputSystem.InputTestFixture.Click (ButtonControl button, double time = -1, double timeOffset = 0, bool queueEventOnly = false)
EndTouch() [1/2]
void UnityEngine.InputSystem.InputTestFixture.EndTouch (int touchId, Vector2 position, float pressure, Vector2 delta = default, bool queueEventOnly = false, Touchscreen screen = null, double time = -1, double timeOffset = 0)
EndTouch() [2/2]
void UnityEngine.InputSystem.InputTestFixture.EndTouch (int touchId, Vector2 position, Vector2 delta = default, bool queueEventOnly = false, Touchscreen screen = null, double time = -1, double timeOffset = 0)
Move()
void UnityEngine.InputSystem.InputTestFixture.Move (InputControl< Vector2 > positionControl, Vector2 position, Vector2? delta = null, double time = -1, double timeOffset = 0, bool queueEventOnly = false)
MoveTouch() [1/2]
void UnityEngine.InputSystem.InputTestFixture.MoveTouch (int touchId, Vector2 position, float pressure, Vector2 delta = default, bool queueEventOnly = false, Touchscreen screen = null, double time = -1, double timeOffset = 0)
MoveTouch() [2/2]
void UnityEngine.InputSystem.InputTestFixture.MoveTouch (int touchId, Vector2 position, Vector2 delta = default, bool queueEventOnly = false, Touchscreen screen = null, double time = -1, double timeOffset = 0)
Performed()
ActionConstraint UnityEngine.InputSystem.InputTestFixture.Performed (InputAction action, InputControl control = null, double? time = null, double? duration = null, object value = null)
Performed< TInteraction >()
ActionConstraint UnityEngine.InputSystem.InputTestFixture.Performed< TInteraction > (InputAction action, InputControl control = null, object value = null, double? time = null, double? duration = null)
Type Constraints
TInteraction : IInputInteraction
Performed< TValue >()
ActionConstraint UnityEngine.InputSystem.InputTestFixture.Performed< TValue > (InputAction action, InputControl< TValue > control, TValue value, double? time = null, double? duration = null)
Type Constraints
TValue : struct
Press()
void UnityEngine.InputSystem.InputTestFixture.Press (ButtonControl button, double time = -1, double timeOffset = 0, bool queueEventOnly = false)
Referenced by UnityEngine.InputSystem.InputTestFixture.PressAndRelease().
PressAndRelease()
void UnityEngine.InputSystem.InputTestFixture.PressAndRelease (ButtonControl button, double time = -1, double timeOffset = 0, bool queueEventOnly = false)
Referenced by UnityEngine.InputSystem.InputTestFixture.Click().
Release()
void UnityEngine.InputSystem.InputTestFixture.Release (ButtonControl button, double time = -1, double timeOffset = 0, bool queueEventOnly = false)
Referenced by UnityEngine.InputSystem.InputTestFixture.PressAndRelease().
Set< TValue >() [1/2]
void UnityEngine.InputSystem.InputTestFixture.Set< TValue > (InputControl< TValue > control, TValue state, double time = -1, double timeOffset = 0, bool queueEventOnly = false)
Set the control to the given value by sending a state event with the value to the control's device.
Parameters
control An input control on a device that has been added to the system.
state New value for the input control.
time Timestamp to use for the state event. If -1 (default), current time is used (see InputTestFixture.currentTime).
timeOffset Offset to apply to the current time. This is an alternative to time . By default, no offset is applied.
queueEventOnly If true, no InputSystem.Update will be performed after queueing the event. This will only put the state event on the event queue and not do anything else. The default is to call InputSystem.Update after queuing the event. Note that not issuing an update means the state of the device will not change yet. This may affect subsequent Set/Press/Release/etc calls as they will not yet see the state change.
Note that this parameter will be ignored if the test is a [UnityTest]. Multi-frame playmode tests will automatically process input as part of the Unity player loop.
Template Parameters
TValue Value type of the given control.
var gamepad = InputSystem.AddDevice<Gamepad>();
Set(gamepad.leftButton, 1);
Type Constraints
TValue : struct
Set< TValue >() [2/2]
void UnityEngine.InputSystem.InputTestFixture.Set< TValue > (InputDevice device, string path, TValue state, double time = -1, double timeOffset = 0, bool queueEventOnly = false)
Set the control with the given path on device to the given state by sending a state event with the value to the device.
Parameters
device Device on which to find a control.
path Path of the control on the device.
state New state for the control.
time Timestamp to use for the state event. If -1 (default), current time is used (see InputTestFixture.currentTime).
timeOffset Offset to apply to the current time. This is an alternative to time . By default, no offset is applied.
queueEventOnly If true, no InputSystem.Update will be performed after queueing the event. This will only put the state event on the event queue and not do anything else. The default is to call InputSystem.Update after queuing the event. Note that not issuing an update means the state of the device will not change yet. This may affect subsequent Set/Press/Release/etc calls as they will not yet see the state change.
Note that this parameter will be ignored if the test is a [UnityTest]. Multi-frame playmode tests will automatically process input as part of the Unity player loop.
Template Parameters
TValue Value type of the control.
var device = InputSystem.AddDevice("TestDevice");
Set<ButtonControl>(device, "button", 1);
Set<AxisControl>(device, "{Primary2DMotion}/x", 123.456f);
Type Constraints
TValue : struct
SetKeyboardLayout()
unsafe void UnityEngine.InputSystem.InputTestFixture.SetKeyboardLayout (string name, Keyboard keyboard = null)
Set Keyboard.keyboardLayout of the given keyboard.
Parameters
name Name of the keyboard layout to switch to.
keyboard Keyboard to switch layout on. If null, Keyboard.current is used.
Exceptions
ArgumentException keyboard and Keyboard.current are both null.
Also queues and immediately processes an DeviceConfigurationEvent for the keyboard.
SetKeyInfo()
unsafe void UnityEngine.InputSystem.InputTestFixture.SetKeyInfo (Key key, string displayName, int scanCode = 0)
Set the InputControl.displayName of key on the current Keyboard to be displayName .
Parameters
key Key to set the display name for.
displayName Display name for the key.
scanCode Optional KeyControl.scanCode to report for the key.
Automatically adds a Keyboard if none has been added yet.
SetTouch() [1/2]
void UnityEngine.InputSystem.InputTestFixture.SetTouch (int touchId, TouchPhase phase, Vector2 position, float pressure, Vector2 delta = default, bool queueEventOnly = true, Touchscreen screen = null, double time = -1, double timeOffset = 0)
SetTouch() [2/2]
void UnityEngine.InputSystem.InputTestFixture.SetTouch (int touchId, TouchPhase phase, Vector2 position, Vector2 delta = default, bool queueEventOnly = true, Touchscreen screen = null, double time = -1, double timeOffset = 0)
Referenced by UnityEngine.InputSystem.InputTestFixture.BeginTouch(), UnityEngine.InputSystem.InputTestFixture.BeginTouch(), UnityEngine.InputSystem.InputTestFixture.CancelTouch(), UnityEngine.InputSystem.InputTestFixture.CancelTouch(), UnityEngine.InputSystem.InputTestFixture.EndTouch(), UnityEngine.InputSystem.InputTestFixture.EndTouch(), UnityEngine.InputSystem.InputTestFixture.MoveTouch(), UnityEngine.InputSystem.InputTestFixture.MoveTouch(), and UnityEngine.InputSystem.InputTestFixture.SetTouch().
Setup()
virtual void UnityEngine.InputSystem.InputTestFixture.Setup () virtual
Put InputSystem into a known state where it only has a basic set of layouts and does not have any input devices.
If you derive your own test fixture directly from InputTestFixture, this method will automatically be called. If you embed InputTestFixture into your fixture, you have to explicitly call this method yourself.
See also
TearDown
Started()
ActionConstraint UnityEngine.InputSystem.InputTestFixture.Started (InputAction action, InputControl control = null, double? time = null, object value = null)
Started< TInteraction >()
ActionConstraint UnityEngine.InputSystem.InputTestFixture.Started< TInteraction > (InputAction action, InputControl control = null, object value = null, double? time = null)
Type Constraints
TInteraction : IInputInteraction
Started< TValue >()
ActionConstraint UnityEngine.InputSystem.InputTestFixture.Started< TValue > (InputAction action, InputControl< TValue > control, TValue value, double? time = null)
Type Constraints
TValue : struct
TearDown()
virtual void UnityEngine.InputSystem.InputTestFixture.TearDown () virtual
Restore the state of the input system it had when the test was started.
See also
Setup
Trigger()
void UnityEngine.InputSystem.InputTestFixture.Trigger (InputAction action)
Perform the input action without having to know what it is bound to.
Parameters
action An input action that is currently enabled and has controls it is bound to.
Blindly triggering an action requires making a few assumptions. Actions are not built to be able to trigger without any input. This means that this method has to generate input on a control that the action is bound to.
Note that this method has no understanding of the interactions that may be present on the action and thus does not know how they may affect the triggering of the action.
Trigger< TValue >()
void UnityEngine.InputSystem.InputTestFixture.Trigger< TValue > (InputAction action, InputControl< TValue > control, TValue value)
Type Constraints
TValue : struct
Property Documentation
currentTime
double UnityEngine.InputSystem.InputTestFixture.currentTime get set
Get or set the current time used by the input system.
Current time used by the input system.
The documentation for this class was generated from the following file:
C:/Users/Lykos/Desktop/Projects/Capstone/VRGames/Library/PackageCache/com.unity.inputsystem@1.3.0/Tests/TestFixture/InputTestFixture.cs