VRCapstoneGames: Firesplash.UnityAssets.SocketIO.SocketIOInstance Class Reference
Firesplash.UnityAssets.SocketIO.SocketIOInstance Class Reference
This is the class you will use to setup your events. It's the equivalent to JS socket.io's object returned from var con = io(...). You get an instance of this class by adding the SocketIOCommunicator to a GameObject and using it's "Instance" field.
Public Types
enum SIOStatus { DISCONNECTED , CONNECTED , ERROR , RECONNECTING }
DISCONNECTED means a disconnect happened upon request or a connection has never been attempted. CONNECTED is obvious ERROR means that connection should be established but it is not (check log output) RECONNECTING means that connection was established but got disconnected and the system is still trying to reconnect.
Public Member Functions
delegate void SocketIOEvent (string data)
This is the callback type for Socket.IO events.
virtual bool IsConnected ()
virtual void Connect ()
virtual void Close ()
virtual void On (string EventName, SocketIOEvent Callback)
virtual void Off (string EventName, SocketIOEvent Callback)
virtual void Off (string EventName)
virtual void Emit (string EventName, string Data, bool DataIsPlainText)
Emits a Socket.IO Event with payload.
virtual void Emit (string EventName, string Data)
Emits a Socket.IO Event with payload If you are using JSON.NET, everything is fine. If not, consider using it (and set the HAS_JSON_NET flag) OR use the third parameter to specify the data type manually.
virtual void Emit (string EventName)
Emits a Socket.IO Event without payload.
Protected Member Functions
void PrepareDestruction ()
Protected Attributes
string InstanceName
Properties
SIOStatus Status = SIOStatus.DISCONNECTED [get, set]
virtual string SocketID [get, set]
Detailed Description
This is the class you will use to setup your events. It's the equivalent to JS socket.io's object returned from var con = io(...). You get an instance of this class by adding the SocketIOCommunicator to a GameObject and using it's "Instance" field.
Member Enumeration Documentation
SIOStatus
enum Firesplash.UnityAssets.SocketIO.SocketIOInstance.SIOStatus
DISCONNECTED means a disconnect happened upon request or a connection has never been attempted. CONNECTED is obvious ERROR means that connection should be established but it is not (check log output) RECONNECTING means that connection was established but got disconnected and the system is still trying to reconnect.
Enumerator
DISCONNECTED
CONNECTED
ERROR
RECONNECTING
Member Function Documentation
Close()
virtual void Firesplash.UnityAssets.SocketIO.SocketIOInstance.Close () virtual
Referenced by Firesplash.UnityAssets.SocketIO.SocketIOInstance.PrepareDestruction().
Connect()
virtual void Firesplash.UnityAssets.SocketIO.SocketIOInstance.Connect () virtual
Emit() [1/3]
virtual void Firesplash.UnityAssets.SocketIO.SocketIOInstance.Emit (string EventName) virtual
Emits a Socket.IO Event without payload.
Parameters
EventName The name of the event
Emit() [2/3]
virtual void Firesplash.UnityAssets.SocketIO.SocketIOInstance.Emit (string EventName, string Data) virtual
Emits a Socket.IO Event with payload If you are using JSON.NET, everything is fine. If not, consider using it (and set the HAS_JSON_NET flag) OR use the third parameter to specify the data type manually.
Parameters
EventName The name of the event
Data The payload (can for example be a serialized object)
Emit() [3/3]
virtual void Firesplash.UnityAssets.SocketIO.SocketIOInstance.Emit (string EventName, string Data, bool DataIsPlainText) virtual
Emits a Socket.IO Event with payload.
Parameters
EventName The name of the event
Data The payload (can for example be a serialized object)
DataIsPlainText Use this parameter to explicitely state if the data is stringified JSON or a plain text string. Default: false = JSON object
Referenced by Network.NetworkManager.SendGameEndedSignal(), Network.NetworkManager.SendPositionalData(), Network.NetworkManager.SendRepTrackingData(), and Network.NetworkManager.UpdateBalloonProgression().
IsConnected()
virtual bool Firesplash.UnityAssets.SocketIO.SocketIOInstance.IsConnected () virtual
Referenced by Firesplash.UnityAssets.SocketIO.SocketIOInstance.PrepareDestruction().
Off() [1/2]
virtual void Firesplash.UnityAssets.SocketIO.SocketIOInstance.Off (string EventName) virtual
Off() [2/2]
virtual void Firesplash.UnityAssets.SocketIO.SocketIOInstance.Off (string EventName, SocketIOEvent Callback) virtual
On()
virtual void Firesplash.UnityAssets.SocketIO.SocketIOInstance.On (string EventName, SocketIOEvent Callback) virtual
PrepareDestruction()
void Firesplash.UnityAssets.SocketIO.SocketIOInstance.PrepareDestruction () protected
SocketIOEvent()
delegate void Firesplash.UnityAssets.SocketIO.SocketIOInstance.SocketIOEvent (string data)
This is the callback type for Socket.IO events.
Parameters
data The data payload of the transmitted event. Plain text or stringified JSON object.
Member Data Documentation
InstanceName
string Firesplash.UnityAssets.SocketIO.SocketIOInstance.InstanceName protected
Property Documentation
SocketID
virtual string Firesplash.UnityAssets.SocketIO.SocketIOInstance.SocketID get set
Status
SIOStatus Firesplash.UnityAssets.SocketIO.SocketIOInstance.Status = SIOStatus.DISCONNECTED get set
Referenced by Firesplash.UnityAssets.SocketIO.SocketIOInstance.IsConnected().
The documentation for this class was generated from the following file:
C:/Users/Lykos/Desktop/Projects/Capstone/VRGames/Assets/ThirdParty/Firesplash Entertainment/Socket.IO/S.IO-Library/SocketIOInstance.cs