VRCapstoneGames: Oculus.Interaction.Grabbable Class Reference
Oculus.Interaction.Grabbable Class Reference
Public Member Functions
void AddGrabPoint (int id, Pose pose)
void UpdateGrabPoint (int id, Pose pose)
void RemoveGrabPoint (int id, Pose pose)
void ResetGrabPoint (int id, Pose grabSourcePose)
void InjectOptionalOneGrabTransformer (ITransformer transformer)
void InjectOptionalTwoGrabTransformer (ITransformer transformer)
Protected Member Functions
virtual void Awake ()
virtual void Start ()
Protected Attributes
List< Pose > _grabPoints
List< int > _grabPointIds
bool _started = false
Properties
bool TransferHandOnSecondGrab [get, set]
bool AddNewGrabsToFront [get, set]
int MaxGrabPoints [get, set]
List< Pose > GrabPoints [get]
int GrabPointsCount [get]
Transform Transform [get]
Properties inherited from Oculus.Interaction.IGrabbable
Events
Action< GrabbableArgs > WhenGrabbableUpdated = delegate { }
Events inherited from Oculus.Interaction.IGrabbable
Action< GrabbableArgs > WhenGrabbableUpdated
Member Function Documentation
AddGrabPoint()
void Oculus.Interaction.Grabbable.AddGrabPoint (int id, Pose pose)
Referenced by Oculus.Interaction.GrabInteractor.InteractableSelected(), and Oculus.Interaction.HandPosing.HandGrabInteractor.InteractableSelected().
Awake()
virtual void Oculus.Interaction.Grabbable.Awake () protected virtual
InjectOptionalOneGrabTransformer()
void Oculus.Interaction.Grabbable.InjectOptionalOneGrabTransformer (ITransformer transformer)
InjectOptionalTwoGrabTransformer()
void Oculus.Interaction.Grabbable.InjectOptionalTwoGrabTransformer (ITransformer transformer)
RemoveGrabPoint()
void Oculus.Interaction.Grabbable.RemoveGrabPoint (int id, Pose pose)
Referenced by Oculus.Interaction.Grabbable.AddGrabPoint(), Oculus.Interaction.GrabInteractor.InteractableUnselected(), and Oculus.Interaction.HandPosing.HandGrabInteractor.InteractableUnselected().
ResetGrabPoint()
void Oculus.Interaction.Grabbable.ResetGrabPoint (int id, Pose grabSourcePose)
Start()
virtual void Oculus.Interaction.Grabbable.Start () protected virtual
UpdateGrabPoint()
void Oculus.Interaction.Grabbable.UpdateGrabPoint (int id, Pose pose)
Referenced by Oculus.Interaction.GrabInteractor.DoSelectUpdate(), and Oculus.Interaction.HandPosing.HandGrabInteractor.DoSelectUpdate().
Member Data Documentation
_grabPointIds
List<int> Oculus.Interaction.Grabbable._grabPointIds protected
Referenced by Oculus.Interaction.Grabbable.AddGrabPoint(), Oculus.Interaction.Grabbable.RemoveGrabPoint(), Oculus.Interaction.Grabbable.ResetGrabPoint(), Oculus.Interaction.Grabbable.Start(), and Oculus.Interaction.Grabbable.UpdateGrabPoint().
_grabPoints
List<Pose> Oculus.Interaction.Grabbable._grabPoints protected
Referenced by Oculus.Interaction.Grabbable.AddGrabPoint(), Oculus.Interaction.Grabbable.RemoveGrabPoint(), Oculus.Interaction.Grabbable.ResetGrabPoint(), Oculus.Interaction.Grabbable.Start(), and Oculus.Interaction.Grabbable.UpdateGrabPoint().
_started
bool Oculus.Interaction.Grabbable._started = false protected
Referenced by Oculus.Interaction.Grabbable.Start().
Property Documentation
AddNewGrabsToFront
bool Oculus.Interaction.Grabbable.AddNewGrabsToFront get set
GrabPoints
List<Pose> Oculus.Interaction.Grabbable.GrabPoints get
Implements Oculus.Interaction.IGrabbable.
GrabPointsCount
int Oculus.Interaction.Grabbable.GrabPointsCount get
MaxGrabPoints
int Oculus.Interaction.Grabbable.MaxGrabPoints get set
TransferHandOnSecondGrab
bool Oculus.Interaction.Grabbable.TransferHandOnSecondGrab get set
Transform
Transform Oculus.Interaction.Grabbable.Transform get
Implements Oculus.Interaction.IGrabbable.
Event Documentation
WhenGrabbableUpdated
Action<GrabbableArgs> Oculus.Interaction.Grabbable.WhenGrabbableUpdated = delegate { }
Referenced by Oculus.Interaction.Grabbable.AddGrabPoint(), Oculus.Interaction.Grabbable.RemoveGrabPoint(), and Oculus.Interaction.Grabbable.UpdateGrabPoint().
The documentation for this class was generated from the following file:
C:/Users/Lykos/Desktop/Projects/Capstone/VRGames/Assets/ThirdParty/Oculus/Interaction/Runtime/Scripts/Interaction/Grabbable/Grabbable.cs