VRCapstoneGames: Facebook.WitAi.Lib.WitResponseNode Class Reference
Facebook.WitAi.Lib.WitResponseNode Class Reference
Public Member Functions
virtual void Add (string aKey, WitResponseNode aItem)
virtual void Add (WitResponseNode aItem)
virtual WitResponseNode Remove (string aKey)
virtual WitResponseNode Remove (int aIndex)
virtual WitResponseNode Remove (WitResponseNode aNode)
override string ToString ()
virtual string ToString (string aPrefix)
override bool Equals (object obj)
override int GetHashCode ()
virtual void Serialize (System.IO.BinaryWriter aWriter)
void SaveToStream (System.IO.Stream aData)
void SaveToCompressedStream (System.IO.Stream aData)
void SaveToCompressedFile (string aFileName)
string SaveToCompressedBase64 ()
void SaveToFile (string aFileName)
string SaveToBase64 ()
Static Public Member Functions
static implicit operator WitResponseNode (string s)
static implicit operator string (WitResponseNode d)
static bool operator== (WitResponseNode a, object b)
static bool operator!= (WitResponseNode a, object b)
static WitResponseNode Parse (string aJSON)
static WitResponseNode Deserialize (System.IO.BinaryReader aReader)
static WitResponseNode LoadFromCompressedFile (string aFileName)
static WitResponseNode LoadFromCompressedStream (System.IO.Stream aData)
static WitResponseNode LoadFromCompressedBase64 (string aBase64)
static WitResponseNode LoadFromStream (System.IO.Stream aData)
static WitResponseNode LoadFromFile (string aFileName)
static WitResponseNode LoadFromBase64 (string aBase64)
Properties
virtual WitResponseNode this[int aIndex] [get, set]
virtual WitResponseNode this[string aKey] [get, set]
virtual string Value [get, set]
virtual int Count [get]
virtual IEnumerable< WitResponseNode > Childs [get]
IEnumerable< WitResponseNode > DeepChilds [get]
virtual int AsInt [get, set]
virtual float AsFloat [get, set]
virtual double AsDouble [get, set]
virtual bool AsBool [get, set]
virtual WitResponseArray AsArray [get]
virtual string[] AsStringArray [get]
virtual WitResponseClass AsObject [get]
Member Function Documentation
Add() [1/2]
virtual void Facebook.WitAi.Lib.WitResponseNode.Add (string aKey, WitResponseNode aItem) virtual
Reimplemented in Facebook.WitAi.Lib.WitResponseArray, and Facebook.WitAi.Lib.WitResponseClass.
Referenced by Facebook.WitAi.Data.Entities.WitDynamicEntity.GetEntityPair(), Facebook.WitAi.Data.Entities.WitSimpleDynamicEntity.GetEntityPair(), and Facebook.WitAi.Lib.WitResponseNode.Parse().
Add() [2/2]
virtual void Facebook.WitAi.Lib.WitResponseNode.Add (WitResponseNode aItem) virtual
Deserialize()
static WitResponseNode Facebook.WitAi.Lib.WitResponseNode.Deserialize (System::IO::BinaryReader aReader) static
Referenced by Facebook.WitAi.Lib.WitResponseNode.Deserialize(), and Facebook.WitAi.Lib.WitResponseNode.LoadFromStream().
Equals()
override bool Facebook.WitAi.Lib.WitResponseNode.Equals (object obj)
GetHashCode()
override int Facebook.WitAi.Lib.WitResponseNode.GetHashCode ()
LoadFromBase64()
static WitResponseNode Facebook.WitAi.Lib.WitResponseNode.LoadFromBase64 (string aBase64) static
LoadFromCompressedBase64()
static WitResponseNode Facebook.WitAi.Lib.WitResponseNode.LoadFromCompressedBase64 (string aBase64) static
LoadFromCompressedFile()
static WitResponseNode Facebook.WitAi.Lib.WitResponseNode.LoadFromCompressedFile (string aFileName) static
LoadFromCompressedStream()
static WitResponseNode Facebook.WitAi.Lib.WitResponseNode.LoadFromCompressedStream (System::IO::Stream aData) static
LoadFromFile()
static WitResponseNode Facebook.WitAi.Lib.WitResponseNode.LoadFromFile (string aFileName) static
LoadFromStream()
static WitResponseNode Facebook.WitAi.Lib.WitResponseNode.LoadFromStream (System::IO::Stream aData) static
Referenced by Facebook.WitAi.Lib.WitResponseNode.LoadFromBase64(), and Facebook.WitAi.Lib.WitResponseNode.LoadFromFile().
operator string()
static implicit Facebook.WitAi.Lib.WitResponseNode.operator string (WitResponseNode d) static
operator WitResponseNode()
static implicit Facebook.WitAi.Lib.WitResponseNode.operator WitResponseNode (string s) static
operator!=()
static bool Facebook.WitAi.Lib.WitResponseNode.operator!= (WitResponseNode a, object b) static
operator==()
static bool Facebook.WitAi.Lib.WitResponseNode.operator== (WitResponseNode a, object b) static
Parse()
static WitResponseNode Facebook.WitAi.Lib.WitResponseNode.Parse (string aJSON) static
Referenced by Facebook.WitAi.Windows.WitUnderstandingViewer.OnEnable(), Oculus.Voice.Bindings.Android.VoiceSDKListenerBinding.onResponse(), and Facebook.WitAi.Lib.WitResponseNode.Parse().
Remove() [1/3]
virtual WitResponseNode Facebook.WitAi.Lib.WitResponseNode.Remove (int aIndex) virtual
Reimplemented in Facebook.WitAi.Lib.WitResponseArray, and Facebook.WitAi.Lib.WitResponseClass.
Remove() [2/3]
virtual WitResponseNode Facebook.WitAi.Lib.WitResponseNode.Remove (string aKey) virtual
Reimplemented in Facebook.WitAi.Lib.WitResponseClass.
Referenced by Facebook.WitAi.Lib.WitResponseArray.Remove().
Remove() [3/3]
virtual WitResponseNode Facebook.WitAi.Lib.WitResponseNode.Remove (WitResponseNode aNode) virtual
Reimplemented in Facebook.WitAi.Lib.WitResponseArray, and Facebook.WitAi.Lib.WitResponseClass.
SaveToBase64()
string Facebook.WitAi.Lib.WitResponseNode.SaveToBase64 ()
SaveToCompressedBase64()
string Facebook.WitAi.Lib.WitResponseNode.SaveToCompressedBase64 ()
SaveToCompressedFile()
void Facebook.WitAi.Lib.WitResponseNode.SaveToCompressedFile (string aFileName)
SaveToCompressedStream()
void Facebook.WitAi.Lib.WitResponseNode.SaveToCompressedStream (System::IO::Stream aData)
SaveToFile()
void Facebook.WitAi.Lib.WitResponseNode.SaveToFile (string aFileName)
SaveToStream()
void Facebook.WitAi.Lib.WitResponseNode.SaveToStream (System::IO::Stream aData)
Referenced by Facebook.WitAi.Lib.WitResponseNode.SaveToBase64(), and Facebook.WitAi.Lib.WitResponseNode.SaveToFile().
Serialize()
virtual void Facebook.WitAi.Lib.WitResponseNode.Serialize (System::IO::BinaryWriter aWriter) virtual
Reimplemented in Facebook.WitAi.Lib.WitResponseArray, Facebook.WitAi.Lib.WitResponseClass, and Facebook.WitAi.Lib.WitResponseData.
Referenced by Facebook.WitAi.Lib.WitResponseNode.SaveToStream().
ToString() [1/2]
override string Facebook.WitAi.Lib.WitResponseNode.ToString ()
ToString() [2/2]
virtual string Facebook.WitAi.Lib.WitResponseNode.ToString (string aPrefix) virtual
Reimplemented in Facebook.WitAi.Lib.WitResponseArray, Facebook.WitAi.Lib.WitResponseClass, and Facebook.WitAi.Lib.WitResponseData.
Property Documentation
AsArray
virtual WitResponseArray Facebook.WitAi.Lib.WitResponseNode.AsArray get
AsBool
virtual bool Facebook.WitAi.Lib.WitResponseNode.AsBool get set
Referenced by Facebook.WitAi.Lib.WitResponseData.Serialize(), and Facebook.WitAi.Lib.WitResponseData.WitResponseData().
AsDouble
virtual double Facebook.WitAi.Lib.WitResponseNode.AsDouble get set
Referenced by Facebook.WitAi.Lib.WitResponseData.Serialize(), and Facebook.WitAi.Lib.WitResponseData.WitResponseData().
AsFloat
virtual float Facebook.WitAi.Lib.WitResponseNode.AsFloat get set
Referenced by Facebook.WitAi.ObjectNodeReference.GetFloatValue(), Facebook.WitAi.Lib.WitResponseData.Serialize(), and Facebook.WitAi.Lib.WitResponseData.WitResponseData().
AsInt
virtual int Facebook.WitAi.Lib.WitResponseNode.AsInt get set
Referenced by Facebook.WitAi.ArrayNodeReference.GetFloatValue(), Facebook.WitAi.ArrayNodeReference.GetIntValue(), Facebook.WitAi.ObjectNodeReference.GetIntValue(), Facebook.WitAi.Lib.WitResponseData.Serialize(), and Facebook.WitAi.Lib.WitResponseData.WitResponseData().
AsObject
virtual WitResponseClass Facebook.WitAi.Lib.WitResponseNode.AsObject get
AsStringArray
virtual string [] Facebook.WitAi.Lib.WitResponseNode.AsStringArray get
Childs
virtual IEnumerable<WitResponseNode> Facebook.WitAi.Lib.WitResponseNode.Childs get
Count
virtual int Facebook.WitAi.Lib.WitResponseNode.Count get
DeepChilds
IEnumerable<WitResponseNode> Facebook.WitAi.Lib.WitResponseNode.DeepChilds get
this[int aIndex]
virtual WitResponseNode Facebook.WitAi.Lib.WitResponseNode.this[int aIndex] get set
this[string aKey]
virtual WitResponseNode Facebook.WitAi.Lib.WitResponseNode.this[string aKey] get set
Value
virtual string Facebook.WitAi.Lib.WitResponseNode.Value get set
Referenced by Facebook.WitAi.Lib.WitResponseNode.Deserialize(), Facebook.WitAi.ArrayNodeReference.GetStringValue(), Facebook.WitAi.ObjectNodeReference.GetStringValue(), Facebook.WitAi.CallbackHandlers.WitUtteranceMatcher.OnHandleResponse(), and Facebook.WitAi.Lib.WitResponseNode.operator string().
The documentation for this class was generated from the following file:
C:/Users/Lykos/Desktop/Projects/Capstone/VRGames/Assets/ThirdParty/Oculus/Voice/Lib/Wit.ai/Scripts/Runtime/Lib/WitResponse.cs