VRCapstoneGames: Oculus.Interaction.InteractorDriverGroup Class Reference
Oculus.Interaction.InteractorDriverGroup Class Reference
InteractorDriverGroup coordinates between a set of InteractorDrivers to determine which InteractorDriver(s) should be enabled at a time.
Public Types
enum InteractorDriverGroupStrategy { PRIORITY = 0 , FIRST = 1 , MULTIPLE = 2 }
InteractorGroupStrategy defines how an InteractorDriverGroup coordinates hovering between InteractorDrivers when no InteractorDriver is yet selected. Upon selection, all other drivers are disabled.
Public Member Functions
void UpdateInteraction ()
void UpdateHover ()
void UpdateSelection (bool selectionCanBeEmpty)
void Enable ()
void Disable ()
virtual void AddInteractorDriver (IInteractorDriver interactorDriver)
virtual void RemoveInteractorDriver (IInteractorDriver interactorDriver)
void InjectAllInteractorDriverGroup (List< IInteractorDriver > interactorDrivers)
void InjectInteractorDrivers (List< IInteractorDriver > interactorDrivers)
void InjectOptionalInteractorDriverGroupStrategy (InteractorDriverGroupStrategy interactorDriverGroupStrategy)
void InjectOptionalInteractorComparer (IInteractorComparer comparer)
Protected Member Functions
virtual void Awake ()
virtual void Start ()
virtual void Update ()
Protected Attributes
List< IInteractorDriver > InteractorDrivers
IInteractorComparer InteractorComparer = null
Properties
bool IsRootInteractorDriver = true [get, set]
bool IsSelectingInteractable [get]
bool IsSelecting [get]
bool HasCandidate [get]
IInteractor CandidateInteractor [get]
bool ShouldSelect [get]
bool IsHovering [get]
Properties inherited from Oculus.Interaction.IInteractorDriver
Detailed Description
InteractorDriverGroup coordinates between a set of InteractorDrivers to determine which InteractorDriver(s) should be enabled at a time.
By default, InteractorDrivers are prioritized in list order (first = highest priority). InteractorDrivers can also be prioritized with an optional IInteractorComparer
Member Enumeration Documentation
InteractorDriverGroupStrategy
enum Oculus.Interaction.InteractorDriverGroup.InteractorDriverGroupStrategy
InteractorGroupStrategy defines how an InteractorDriverGroup coordinates hovering between InteractorDrivers when no InteractorDriver is yet selected. Upon selection, all other drivers are disabled.
Enumerator
PRIORITY
Until selecting, reevaluate drivers in priority order.
FIRST
Until hovering, reevaluate drivers in priority order.
MULTIPLE
Until selecting, allow multiple hovered drivers.
Member Function Documentation
AddInteractorDriver()
virtual void Oculus.Interaction.InteractorDriverGroup.AddInteractorDriver (IInteractorDriver interactorDriver) virtual
Awake()
virtual void Oculus.Interaction.InteractorDriverGroup.Awake () protected virtual
Disable()
void Oculus.Interaction.InteractorDriverGroup.Disable ()
Implements Oculus.Interaction.IInteractorDriver.
Enable()
void Oculus.Interaction.InteractorDriverGroup.Enable ()
Implements Oculus.Interaction.IInteractorDriver.
InjectAllInteractorDriverGroup()
void Oculus.Interaction.InteractorDriverGroup.InjectAllInteractorDriverGroup (List< IInteractorDriver > interactorDrivers)
InjectInteractorDrivers()
void Oculus.Interaction.InteractorDriverGroup.InjectInteractorDrivers (List< IInteractorDriver > interactorDrivers)
Referenced by Oculus.Interaction.InteractorDriverGroup.InjectAllInteractorDriverGroup().
InjectOptionalInteractorComparer()
void Oculus.Interaction.InteractorDriverGroup.InjectOptionalInteractorComparer (IInteractorComparer comparer)
InjectOptionalInteractorDriverGroupStrategy()
void Oculus.Interaction.InteractorDriverGroup.InjectOptionalInteractorDriverGroupStrategy (InteractorDriverGroupStrategy interactorDriverGroupStrategy)
RemoveInteractorDriver()
virtual void Oculus.Interaction.InteractorDriverGroup.RemoveInteractorDriver (IInteractorDriver interactorDriver) virtual
Start()
virtual void Oculus.Interaction.InteractorDriverGroup.Start () protected virtual
Update()
virtual void Oculus.Interaction.InteractorDriverGroup.Update () protected virtual
UpdateHover()
void Oculus.Interaction.InteractorDriverGroup.UpdateHover ()
Implements Oculus.Interaction.IInteractorDriver.
Referenced by Oculus.Interaction.InteractorDriverGroup.Update(), and Oculus.Interaction.InteractorDriverGroup.UpdateSelection().
UpdateInteraction()
void Oculus.Interaction.InteractorDriverGroup.UpdateInteraction ()
Implements Oculus.Interaction.IInteractorDriver.
Referenced by Oculus.Interaction.InteractorDriverGroup.Update(), and Oculus.Interaction.InteractorDriverGroup.UpdateSelection().
UpdateSelection()
void Oculus.Interaction.InteractorDriverGroup.UpdateSelection (bool selectionCanBeEmpty)
Implements Oculus.Interaction.IInteractorDriver.
Referenced by Oculus.Interaction.InteractorDriverGroup.Update().
Member Data Documentation
InteractorComparer
IInteractorComparer Oculus.Interaction.InteractorDriverGroup.InteractorComparer = null protected
InteractorDrivers
List<IInteractorDriver> Oculus.Interaction.InteractorDriverGroup.InteractorDrivers protected
Referenced by Oculus.Interaction.InteractorDriverGroup.AddInteractorDriver(), Oculus.Interaction.InteractorDriverGroup.Awake(), Oculus.Interaction.InteractorDriverGroup.Disable(), Oculus.Interaction.InteractorDriverGroup.Enable(), Oculus.Interaction.InteractorDriverGroup.InjectInteractorDrivers(), Oculus.Interaction.InteractorDriverGroup.RemoveInteractorDriver(), Oculus.Interaction.InteractorDriverGroup.Start(), Oculus.Interaction.InteractorDriverGroup.UpdateHover(), Oculus.Interaction.InteractorDriverGroup.UpdateInteraction(), and Oculus.Interaction.InteractorDriverGroup.UpdateSelection().
Property Documentation
CandidateInteractor
IInteractor Oculus.Interaction.InteractorDriverGroup.CandidateInteractor get
Implements Oculus.Interaction.IInteractorDriver.
HasCandidate
bool Oculus.Interaction.InteractorDriverGroup.HasCandidate get
Implements Oculus.Interaction.IInteractorDriver.
IsHovering
bool Oculus.Interaction.InteractorDriverGroup.IsHovering get
Implements Oculus.Interaction.IInteractorDriver.
IsRootInteractorDriver
bool Oculus.Interaction.InteractorDriverGroup.IsRootInteractorDriver = true get set
Implements Oculus.Interaction.IInteractorDriver.
Referenced by Oculus.Interaction.InteractorDriverGroup.Update().
IsSelecting
bool Oculus.Interaction.InteractorDriverGroup.IsSelecting get
Implements Oculus.Interaction.IInteractorDriver.
IsSelectingInteractable
bool Oculus.Interaction.InteractorDriverGroup.IsSelectingInteractable get
Implements Oculus.Interaction.IInteractorDriver.
ShouldSelect
bool Oculus.Interaction.InteractorDriverGroup.ShouldSelect get
Implements Oculus.Interaction.IInteractorDriver.
The documentation for this class was generated from the following file:
C:/Users/Lykos/Desktop/Projects/Capstone/VRGames/Assets/ThirdParty/Oculus/Interaction/Runtime/Scripts/Interaction/Core/InteractorDriverGroup.cs