VRCapstoneGames: Oculus.Interaction.PoseDetection.ColliderContainsHandJointActiveState Class Reference
Oculus.Interaction.PoseDetection.ColliderContainsHandJointActiveState Class Reference
Test if hand joint is inside generic collider and updates its active state based on that test. We could trigger-based testing, but if the hand disappears during one frame, we will not get a trigger exit event (which means we require manual testing in Update anyway to accomodate that edge case).
Public Member Functions
void InjectAllColliderContainsHandJointActiveState (IHand hand, Collider[] entryColliders, Collider[] exitColliders, HandJointId jointToTest)
void InjectHand (IHand hand)
void InjectEntryColliders (Collider[] entryColliders)
void InjectExitColliders (Collider[] exitColliders)
void InjectJointToTest (HandJointId jointToTest)
Protected Member Functions
virtual void Awake ()
virtual void Start ()
virtual void Update ()
Properties
bool Active [get]
Properties inherited from Oculus.Interaction.IActiveState
Detailed Description
Test if hand joint is inside generic collider and updates its active state based on that test. We could trigger-based testing, but if the hand disappears during one frame, we will not get a trigger exit event (which means we require manual testing in Update anyway to accomodate that edge case).
Member Function Documentation
Awake()
virtual void Oculus.Interaction.PoseDetection.ColliderContainsHandJointActiveState.Awake () protected virtual
InjectAllColliderContainsHandJointActiveState()
void Oculus.Interaction.PoseDetection.ColliderContainsHandJointActiveState.InjectAllColliderContainsHandJointActiveState (IHand hand, Collider[] entryColliders, Collider[] exitColliders, HandJointId jointToTest)
InjectEntryColliders()
void Oculus.Interaction.PoseDetection.ColliderContainsHandJointActiveState.InjectEntryColliders (Collider[] entryColliders)
Referenced by Oculus.Interaction.PoseDetection.ColliderContainsHandJointActiveState.InjectAllColliderContainsHandJointActiveState().
InjectExitColliders()
void Oculus.Interaction.PoseDetection.ColliderContainsHandJointActiveState.InjectExitColliders (Collider[] exitColliders)
Referenced by Oculus.Interaction.PoseDetection.ColliderContainsHandJointActiveState.InjectAllColliderContainsHandJointActiveState().
InjectHand()
void Oculus.Interaction.PoseDetection.ColliderContainsHandJointActiveState.InjectHand (IHand hand)
Referenced by Oculus.Interaction.PoseDetection.ColliderContainsHandJointActiveState.InjectAllColliderContainsHandJointActiveState().
InjectJointToTest()
void Oculus.Interaction.PoseDetection.ColliderContainsHandJointActiveState.InjectJointToTest (HandJointId jointToTest)
Referenced by Oculus.Interaction.PoseDetection.ColliderContainsHandJointActiveState.InjectAllColliderContainsHandJointActiveState().
Start()
virtual void Oculus.Interaction.PoseDetection.ColliderContainsHandJointActiveState.Start () protected virtual
Update()
virtual void Oculus.Interaction.PoseDetection.ColliderContainsHandJointActiveState.Update () protected virtual
Property Documentation
Active
bool Oculus.Interaction.PoseDetection.ColliderContainsHandJointActiveState.Active get
Implements Oculus.Interaction.IActiveState.
Referenced by Oculus.Interaction.PoseDetection.ColliderContainsHandJointActiveState.Awake(), and Oculus.Interaction.PoseDetection.ColliderContainsHandJointActiveState.Update().
The documentation for this class was generated from the following file:
C:/Users/Lykos/Desktop/Projects/Capstone/VRGames/Assets/ThirdParty/Oculus/Interaction/Runtime/Scripts/PoseDetection/ColliderContainsHandJointActiveState.cs