VRCapstoneGames: UnityEngine.XR.Interaction.Toolkit.ContinuousMoveProviderBase Class Reference
UnityEngine.XR.Interaction.Toolkit.ContinuousMoveProviderBase Class Reference abstract
Locomotion provider that allows the user to smoothly move their rig continuously over time.
Public Types
enum GravityApplicationMode { AttemptingMove , Immediately }
Defines when gravity begins to take effect.
Protected Member Functions
void Update ()
See MonoBehaviour.
Vector2 ReadInput ()
Reads the current value of the move input.
virtual Vector3 ComputeDesiredMove (Vector2 input)
Determines how much to slide the rig due to input vector.
virtual void MoveRig (Vector3 translationInWorldSpace)
Creates a locomotion event to move the rig by translationInWorldSpace , and optionally applies gravity.
Protected Member Functions inherited from UnityEngine.XR.Interaction.Toolkit.LocomotionProvider
virtual void Awake ()
See MonoBehaviour.
bool CanBeginLocomotion ()
Checks if locomotion can begin.
bool BeginLocomotion ()
Invokes begin locomotion events.
bool EndLocomotion ()
Invokes end locomotion events.
Properties
float moveSpeed [get, set]
The speed, in units per second, to move forward.
bool enableStrafe [get, set]
Controls whether to enable strafing (sideways movement).
bool useGravity [get, set]
Controls whether gravity affects this provider when a CharacterController is used.
GravityApplicationMode gravityApplicationMode [get, set]
Controls when gravity begins to take effect.
Transform forwardSource [get, set]
The source Transform that defines the forward direction.
Properties inherited from UnityEngine.XR.Interaction.Toolkit.LocomotionProvider
LocomotionSystem system [get, set]
The LocomotionSystem that this LocomotionProvider communicates with for exclusive access to an XR Origin. If one is not provided, the behavior will attempt to locate one during its Awake call.
Additional Inherited Members
Events inherited from UnityEngine.XR.Interaction.Toolkit.LocomotionProvider
Action< LocomotionSystem > beginLocomotion
Unity calls the beginLocomotion action when a LocomotionProvider successfully begins a locomotion event.
Action< LocomotionSystem > endLocomotion
Unity calls the endLocomotion action when a LocomotionProvider successfully ends a locomotion event.
Action< LocomotionSystem > startLocomotion
(Deprecated) The startLocomotion action will be called when a LocomotionProvider successfully begins a locomotion event.
Detailed Description
Locomotion provider that allows the user to smoothly move their rig continuously over time.
See also
LocomotionProvider
Member Enumeration Documentation
GravityApplicationMode
enum UnityEngine.XR.Interaction.Toolkit.ContinuousMoveProviderBase.GravityApplicationMode
Defines when gravity begins to take effect.
See also
gravityApplicationMode
Enumerator
AttemptingMove
Only begin to apply gravity and apply locomotion when a move input occurs. When using gravity, continues applying each frame, even if input is stopped, until touching ground.
Use this style when you don't want gravity to apply when the player physically walks away and off a ground surface. Gravity will only begin to move the player back down to the ground when they try to use input to move.
Immediately
Apply gravity and apply locomotion every frame, even without move input.
Use this style when you want gravity to apply when the player physically walks away and off a ground surface, even when there is no input to move.
Member Function Documentation
ComputeDesiredMove()
virtual Vector3 UnityEngine.XR.Interaction.Toolkit.ContinuousMoveProviderBase.ComputeDesiredMove (Vector2 input) protected virtual
Determines how much to slide the rig due to input vector.
Parameters
input Input vector, such as from a thumbstick.
Returns
Returns the translation amount in world space to move the rig.
Referenced by UnityEngine.XR.Interaction.Toolkit.ContinuousMoveProviderBase.Update().
MoveRig()
virtual void UnityEngine.XR.Interaction.Toolkit.ContinuousMoveProviderBase.MoveRig (Vector3 translationInWorldSpace) protected virtual
Creates a locomotion event to move the rig by translationInWorldSpace , and optionally applies gravity.
Parameters
translationInWorldSpace The translation amount in world space to move the rig (pre-gravity).
Referenced by UnityEngine.XR.Interaction.Toolkit.ContinuousMoveProviderBase.Update().
ReadInput()
Vector2 UnityEngine.XR.Interaction.Toolkit.ContinuousMoveProviderBase.ReadInput () abstract protected
Reads the current value of the move input.
Returns
Returns the input vector, such as from a thumbstick.
Referenced by UnityEngine.XR.Interaction.Toolkit.ContinuousMoveProviderBase.Update().
Update()
void UnityEngine.XR.Interaction.Toolkit.ContinuousMoveProviderBase.Update () protected
See MonoBehaviour.
Property Documentation
enableStrafe
bool UnityEngine.XR.Interaction.Toolkit.ContinuousMoveProviderBase.enableStrafe get set
Controls whether to enable strafing (sideways movement).
forwardSource
Transform UnityEngine.XR.Interaction.Toolkit.ContinuousMoveProviderBase.forwardSource get set
The source Transform that defines the forward direction.
gravityApplicationMode
GravityApplicationMode UnityEngine.XR.Interaction.Toolkit.ContinuousMoveProviderBase.gravityApplicationMode get set
Controls when gravity begins to take effect.
See also
GravityApplicationMode
moveSpeed
float UnityEngine.XR.Interaction.Toolkit.ContinuousMoveProviderBase.moveSpeed get set
The speed, in units per second, to move forward.
useGravity
bool UnityEngine.XR.Interaction.Toolkit.ContinuousMoveProviderBase.useGravity get set
Controls whether gravity affects this provider when a CharacterController is used.
The documentation for this class was generated from the following file:
C:/Users/Lykos/Desktop/Projects/Capstone/VRGames/Library/PackageCache/com.unity.xr.interaction.toolkit@2.0.2/Runtime/Locomotion/Continuous/ContinuousMoveProviderBase.cs