VRCapstoneGames: CreateSceneUtility Class Reference
CreateSceneUtility Class Reference
Static Public Member Functions
static void CreateScene (string sceneName, Action delegateToExecute)
Member Function Documentation
CreateScene()
static void CreateSceneUtility.CreateScene (string sceneName, Action delegateToExecute) static
Referenced by CanvasSizeCorrectInAwakeAndStart.Setup(), NoActiveCameraInSceneDoesNotCrashEditor.Setup(), RectTransformValidAfterEnable.Setup(), and SceneWithNestedLayoutElementsLoad.Setup().
The documentation for this class was generated from the following file:
C:/Users/Lykos/Desktop/Projects/Capstone/VRGames/Library/PackageCache/com.unity.ugui@1.0.0/Tests/Runtime/Canvas/CreateSceneUtility.cs