VRCapstoneGames: Oculus.Interaction.HandPosing.SnapSurfaces.ColliderSurface Class Reference
Oculus.Interaction.HandPosing.SnapSurfaces.ColliderSurface Class Reference
Public Member Functions
float CalculateBestPoseAtSurface (in Pose targetPose, in Pose snapPose, out Pose bestPose, in PoseMeasureParameters scoringModifier)
Finds the Pose at the surface that is the closest to the given pose.
bool CalculateBestPoseAtSurface (Ray targetRay, in Pose recordedPose, out Pose bestPose)
Finds the Pose at the surface that is the closest to the given ray.
Pose MirrorPose (in Pose gripPose)
Method for mirroring a Pose around the surface. Different surfaces will prefer mirroring along different axis.
ISnapSurface CreateMirroredSurface (GameObject gameObject)
Creates a new ISnapSurface under the selected gameobject that is a mirror version of the current.
ISnapSurface CreateDuplicatedSurface (GameObject gameObject)
Creates a new ISnapSurface under the selected gameobject with the same data as this one.
void InjectCollider (Collider collider)
void InjectAllColliderSurface (Collider collider)
Protected Member Functions
virtual void Start ()
Member Function Documentation
CalculateBestPoseAtSurface() [1/2]
float Oculus.Interaction.HandPosing.SnapSurfaces.ColliderSurface.CalculateBestPoseAtSurface (in Pose targetPose, in Pose reference, out Pose bestPose, in PoseMeasureParameters scoringModifier)
Finds the Pose at the surface that is the closest to the given pose.
Parameters
targetPose The pose to find the nearest to.
reference The reference snap point to use for measuring at the surface.
bestPose The best found pose at the surface.<
Returns
The score indicating how good the found pose was, -1 for invalid result.
Implements Oculus.Interaction.HandPosing.SnapSurfaces.ISnapSurface.
CalculateBestPoseAtSurface() [2/2]
bool Oculus.Interaction.HandPosing.SnapSurfaces.ColliderSurface.CalculateBestPoseAtSurface (Ray targetRay, in Pose reference, out Pose bestPose)
Finds the Pose at the surface that is the closest to the given ray.
Parameters
targetRay Ray searching for the nearest snap pose
reference The reference snap point to use for measuring at the surface.
bestPose The best found pose at the surface.
Returns
True if the pose was found
Implements Oculus.Interaction.HandPosing.SnapSurfaces.ISnapSurface.
CreateDuplicatedSurface()
ISnapSurface Oculus.Interaction.HandPosing.SnapSurfaces.ColliderSurface.CreateDuplicatedSurface (GameObject gameObject)
Creates a new ISnapSurface under the selected gameobject with the same data as this one.
Parameters
gameObject The gameobject in which to place the new ISnapSurface.
Returns
A clone of this ISnapSurface.
Implements Oculus.Interaction.HandPosing.SnapSurfaces.ISnapSurface.
Referenced by Oculus.Interaction.HandPosing.SnapSurfaces.ColliderSurface.CreateMirroredSurface().
CreateMirroredSurface()
ISnapSurface Oculus.Interaction.HandPosing.SnapSurfaces.ColliderSurface.CreateMirroredSurface (GameObject gameObject)
Creates a new ISnapSurface under the selected gameobject that is a mirror version of the current.
Parameters
gameObject The gameobject in which to place the new ISnapSurface.
Returns
A mirror of this ISnapSurface.
Implements Oculus.Interaction.HandPosing.SnapSurfaces.ISnapSurface.
InjectAllColliderSurface()
void Oculus.Interaction.HandPosing.SnapSurfaces.ColliderSurface.InjectAllColliderSurface (Collider collider)
Referenced by Oculus.Interaction.HandPosing.SnapSurfaces.ColliderSurface.CreateDuplicatedSurface().
InjectCollider()
void Oculus.Interaction.HandPosing.SnapSurfaces.ColliderSurface.InjectCollider (Collider collider)
Referenced by Oculus.Interaction.HandPosing.SnapSurfaces.ColliderSurface.InjectAllColliderSurface().
MirrorPose()
Pose Oculus.Interaction.HandPosing.SnapSurfaces.ColliderSurface.MirrorPose (in Pose gripPose)
Method for mirroring a Pose around the surface. Different surfaces will prefer mirroring along different axis.
Parameters
gripPose The Pose to be mirrored.
Returns
A new pose mirrored at this surface.
Implements Oculus.Interaction.HandPosing.SnapSurfaces.ISnapSurface.
Start()
virtual void Oculus.Interaction.HandPosing.SnapSurfaces.ColliderSurface.Start () protected virtual
The documentation for this class was generated from the following file:
C:/Users/Lykos/Desktop/Projects/Capstone/VRGames/Assets/ThirdParty/Oculus/Interaction/Runtime/Scripts/HandPosing/SnapSurfaces/ColliderSurface.cs