VRGames: Oculus.Interaction.ProgressCurve Class Reference
Oculus.Interaction.ProgressCurve Class Reference
ProgressCurve provides a helper for creating curves for easing. In some respects it works like an AnimationCurve except that ProgressCurve always takes in a normalized AnimationCurve and a second parameter defines the length of the animation.
Public Member Functions
ProgressCurve ()
ProgressCurve (AnimationCurve animationCurve, float animationLength)
ProgressCurve (ProgressCurve other)
void Start ()
float Progress ()
float ProgressIn (float time)
float ProgressTime ()
void End ()
Properties
float AnimationLength [get]
Detailed Description
ProgressCurve provides a helper for creating curves for easing. In some respects it works like an AnimationCurve except that ProgressCurve always takes in a normalized AnimationCurve and a second parameter defines the length of the animation.
A few helper methods are provided to track progress through the animation.
Constructor & Destructor Documentation
ProgressCurve() [1/3]
Oculus.Interaction.ProgressCurve.ProgressCurve ()
ProgressCurve() [2/3]
Oculus.Interaction.ProgressCurve.ProgressCurve (AnimationCurve animationCurve, float animationLength)
ProgressCurve() [3/3]
Oculus.Interaction.ProgressCurve.ProgressCurve (ProgressCurve other)
Member Function Documentation
End()
void Oculus.Interaction.ProgressCurve.End ()
Progress()
float Oculus.Interaction.ProgressCurve.Progress ()
Referenced by Oculus.Interaction.PokeInteractor.DoSelectUpdate(), and Oculus.Interaction.Tween.Tick().
ProgressIn()
float Oculus.Interaction.ProgressCurve.ProgressIn (float time)
ProgressTime()
float Oculus.Interaction.ProgressCurve.ProgressTime ()
Referenced by Oculus.Interaction.ProgressCurve.Progress(), Oculus.Interaction.ProgressCurve.ProgressIn(), and Oculus.Interaction.Tween.Tick().
Start()
void Oculus.Interaction.ProgressCurve.Start ()
Referenced by Oculus.Interaction.PokeInteractor.DoSelectUpdate().
Property Documentation
AnimationLength
float Oculus.Interaction.ProgressCurve.AnimationLength get
Referenced by Oculus.Interaction.Tween.Tick().
The documentation for this class was generated from the following file:
C:/Users/Lykos/Desktop/Projects/Capstone/VRGames/Assets/ThirdParty/Oculus/Interaction/Runtime/Scripts/Utils/ProgressCurve.cs