VRCapstoneGames: Oculus.Platform.Samples.VrBoardGame.GameBoard Class Reference
Oculus.Platform.Samples.VrBoardGame.GameBoard Class Reference
Public Member Functions
void Reset ()
bool IsFull ()
bool CanPlayerMoveToPostion (int x, int y)
bool CanPlayerPowerUpPosition (int x, int y)
void AddPiece (int player, GameObject prefab, int x, int y)
GamePiece AddProposedPiece (GameObject prefab, BoardPosition pos)
void AddPowerPiece (int player, GameObject prefab, int x, int y)
GamePiece AddProposedPowerPiece (GameObject prefab, BoardPosition pos)
int GetPlayerScore (int player)
Static Public Attributes
const int LENGTH_X = 3
const int LENGTH_Y = 3
const int MAX_PLAYERS = 2
Member Function Documentation
AddPiece()
void Oculus.Platform.Samples.VrBoardGame.GameBoard.AddPiece (int player, GameObject prefab, int x, int y)
Referenced by Oculus.Platform.Samples.VrBoardGame.GameController.MakeRemoteMove(), and Oculus.Platform.Samples.VrBoardGame.GameController.TryPlacePiece().
AddPowerPiece()
void Oculus.Platform.Samples.VrBoardGame.GameBoard.AddPowerPiece (int player, GameObject prefab, int x, int y)
Referenced by Oculus.Platform.Samples.VrBoardGame.GameController.MakeRemoteMove(), and Oculus.Platform.Samples.VrBoardGame.GameController.TryPlacePiece().
AddProposedPiece()
GamePiece Oculus.Platform.Samples.VrBoardGame.GameBoard.AddProposedPiece (GameObject prefab, BoardPosition pos)
Referenced by Oculus.Platform.Samples.VrBoardGame.GameController.StartedLookingAtPosition().
AddProposedPowerPiece()
GamePiece Oculus.Platform.Samples.VrBoardGame.GameBoard.AddProposedPowerPiece (GameObject prefab, BoardPosition pos)
Referenced by Oculus.Platform.Samples.VrBoardGame.GameController.StartedLookingAtPosition().
CanPlayerMoveToPostion()
bool Oculus.Platform.Samples.VrBoardGame.GameBoard.CanPlayerMoveToPostion (int x, int y)
Referenced by Oculus.Platform.Samples.VrBoardGame.GameController.StartedLookingAtPosition().
CanPlayerPowerUpPosition()
bool Oculus.Platform.Samples.VrBoardGame.GameBoard.CanPlayerPowerUpPosition (int x, int y)
Referenced by Oculus.Platform.Samples.VrBoardGame.GameController.StartedLookingAtPosition().
GetPlayerScore()
int Oculus.Platform.Samples.VrBoardGame.GameBoard.GetPlayerScore (int player)
Referenced by Oculus.Platform.Samples.VrBoardGame.GameController.PracticeButtonPressed(), and Oculus.Platform.Samples.VrBoardGame.GameController.RemoteMatchEnded().
IsFull()
bool Oculus.Platform.Samples.VrBoardGame.GameBoard.IsFull ()
Reset()
void Oculus.Platform.Samples.VrBoardGame.GameBoard.Reset ()
Referenced by Oculus.Platform.Samples.VrBoardGame.GameController.PracticeButtonPressed(), and Oculus.Platform.Samples.VrBoardGame.GameController.StartOnlineMatch().
Member Data Documentation
LENGTH_X
const int Oculus.Platform.Samples.VrBoardGame.GameBoard.LENGTH_X = 3 static
Referenced by Oculus.Platform.Samples.VrBoardGame.GameBoard.IsFull(), and Oculus.Platform.Samples.VrBoardGame.GameBoard.Reset().
LENGTH_Y
const int Oculus.Platform.Samples.VrBoardGame.GameBoard.LENGTH_Y = 3 static
Referenced by Oculus.Platform.Samples.VrBoardGame.GameBoard.AddPiece(), Oculus.Platform.Samples.VrBoardGame.GameBoard.AddPowerPiece(), Oculus.Platform.Samples.VrBoardGame.GameBoard.IsFull(), and Oculus.Platform.Samples.VrBoardGame.GameBoard.Reset().
MAX_PLAYERS
const int Oculus.Platform.Samples.VrBoardGame.GameBoard.MAX_PLAYERS = 2 static
The documentation for this class was generated from the following file:
C:/Users/Lykos/Desktop/Projects/Capstone/VRGames/Assets/ThirdParty/Oculus/Platform/Samples/VrBoardGame/Scripts/GameBoard.cs