VRGames: Oculus.Interaction.HandPosing.SnapSurfaces.SphereSurface Class Reference
Oculus.Interaction.HandPosing.SnapSurfaces.SphereSurface Class Reference
Specifies an entire sphere around an object in which the grip point is valid.
Public Member Functions
Pose MirrorPose (in Pose pose)
Method for mirroring a Pose around the surface. Different surfaces will prefer mirroring along different axis.
bool CalculateBestPoseAtSurface (Ray targetRay, in Pose recordedPose, out Pose bestPose)
Finds the Pose at the surface that is the closest to the given ray.
float CalculateBestPoseAtSurface (in Pose targetPose, in Pose reference, out Pose bestPose, in PoseMeasureParameters scoringModifier)
Finds the Pose at the surface that is the closest to the given pose.
ISnapSurface CreateMirroredSurface (GameObject gameObject)
Creates a new ISnapSurface under the selected gameobject that is a mirror version of the current.
ISnapSurface CreateDuplicatedSurface (GameObject gameObject)
Creates a new ISnapSurface under the selected gameobject with the same data as this one.
void InjectAllSphereSurface (SphereSurfaceData data, Transform relativeTo, Transform gripPoint)
void InjectData (SphereSurfaceData data)
void InjectRelativeTo (Transform relativeTo)
void InjectGripPoint (Transform gripPoint)
Protected Member Functions
virtual void Start ()
Vector3 NearestPointInSurface (Vector3 targetPosition)
Pose MinimalRotationPoseAtSurface (in Pose userPose, in Pose snapPose)
Pose MinimalTranslationPoseAtSurface (in Pose userPose, in Pose snapPose)
Quaternion RotationAtPoint (Vector3 surfacePoint, Quaternion baseRot, Quaternion desiredRotation)
Protected Attributes
SphereSurfaceData _data = new SphereSurfaceData()
Properties
SphereSurfaceData Data [get, set]
Getter for the data-only version of this surface. Used so it can be stored when created at Play-Mode.
Transform RelativeTo [get, set]
Transform to which the surface refers to.
Transform GripPoint [get, set]
Valid point at which the hand can snap, typically the SnapPoint position itself.
Vector3 Centre [get, set]
The center of the sphere in world coordinates.
float Radius [get]
The radius of the sphere, this is automatically calculated as the distance between the center and the original grip pose.
Vector3 Direction [get]
The direction of the sphere, measured from the center to the original grip position.
Quaternion Rotation [get]
The rotation of the sphere from the recorded grip position.
Detailed Description
Specifies an entire sphere around an object in which the grip point is valid.
One of the main advantages of spheres is that the rotation of the hand pose does not really matters, as it will always fit the surface correctly.
Member Function Documentation
CalculateBestPoseAtSurface() [1/2]
float Oculus.Interaction.HandPosing.SnapSurfaces.SphereSurface.CalculateBestPoseAtSurface (in Pose targetPose, in Pose reference, out Pose bestPose, in PoseMeasureParameters scoringModifier)
Finds the Pose at the surface that is the closest to the given pose.
Parameters
targetPose The pose to find the nearest to.
reference The reference snap point to use for measuring at the surface.
bestPose The best found pose at the surface.<
Returns
The score indicating how good the found pose was, -1 for invalid result.
Implements Oculus.Interaction.HandPosing.SnapSurfaces.ISnapSurface.
CalculateBestPoseAtSurface() [2/2]
bool Oculus.Interaction.HandPosing.SnapSurfaces.SphereSurface.CalculateBestPoseAtSurface (Ray targetRay, in Pose reference, out Pose bestPose)
Finds the Pose at the surface that is the closest to the given ray.
Parameters
targetRay Ray searching for the nearest snap pose
reference The reference snap point to use for measuring at the surface.
bestPose The best found pose at the surface.
Returns
True if the pose was found
Implements Oculus.Interaction.HandPosing.SnapSurfaces.ISnapSurface.
CreateDuplicatedSurface()
ISnapSurface Oculus.Interaction.HandPosing.SnapSurfaces.SphereSurface.CreateDuplicatedSurface (GameObject gameObject)
Creates a new ISnapSurface under the selected gameobject with the same data as this one.
Parameters
gameObject The gameobject in which to place the new ISnapSurface.
Returns
A clone of this ISnapSurface.
Implements Oculus.Interaction.HandPosing.SnapSurfaces.ISnapSurface.
CreateMirroredSurface()
ISnapSurface Oculus.Interaction.HandPosing.SnapSurfaces.SphereSurface.CreateMirroredSurface (GameObject gameObject)
Creates a new ISnapSurface under the selected gameobject that is a mirror version of the current.
Parameters
gameObject The gameobject in which to place the new ISnapSurface.
Returns
A mirror of this ISnapSurface.
Implements Oculus.Interaction.HandPosing.SnapSurfaces.ISnapSurface.
InjectAllSphereSurface()
void Oculus.Interaction.HandPosing.SnapSurfaces.SphereSurface.InjectAllSphereSurface (SphereSurfaceData data, Transform relativeTo, Transform gripPoint)
InjectData()
void Oculus.Interaction.HandPosing.SnapSurfaces.SphereSurface.InjectData (SphereSurfaceData data)
Referenced by Oculus.Interaction.HandPosing.SnapSurfaces.SphereSurface.InjectAllSphereSurface().
InjectGripPoint()
void Oculus.Interaction.HandPosing.SnapSurfaces.SphereSurface.InjectGripPoint (Transform gripPoint)
Referenced by Oculus.Interaction.HandPosing.SnapSurfaces.SphereSurface.InjectAllSphereSurface().
InjectRelativeTo()
void Oculus.Interaction.HandPosing.SnapSurfaces.SphereSurface.InjectRelativeTo (Transform relativeTo)
Referenced by Oculus.Interaction.HandPosing.SnapSurfaces.SphereSurface.InjectAllSphereSurface().
MinimalRotationPoseAtSurface()
Pose Oculus.Interaction.HandPosing.SnapSurfaces.SphereSurface.MinimalRotationPoseAtSurface (in Pose userPose, in Pose snapPose) protected
Referenced by Oculus.Interaction.HandPosing.SnapSurfaces.SphereSurface.CalculateBestPoseAtSurface().
MinimalTranslationPoseAtSurface()
Pose Oculus.Interaction.HandPosing.SnapSurfaces.SphereSurface.MinimalTranslationPoseAtSurface (in Pose userPose, in Pose snapPose) protected
Referenced by Oculus.Interaction.HandPosing.SnapSurfaces.SphereSurface.CalculateBestPoseAtSurface(), and Oculus.Interaction.HandPosing.SnapSurfaces.SphereSurface.CalculateBestPoseAtSurface().
MirrorPose()
Pose Oculus.Interaction.HandPosing.SnapSurfaces.SphereSurface.MirrorPose (in Pose gripPose)
Method for mirroring a Pose around the surface. Different surfaces will prefer mirroring along different axis.
Parameters
gripPose The Pose to be mirrored.
Returns
A new pose mirrored at this surface.
Implements Oculus.Interaction.HandPosing.SnapSurfaces.ISnapSurface.
NearestPointInSurface()
Vector3 Oculus.Interaction.HandPosing.SnapSurfaces.SphereSurface.NearestPointInSurface (Vector3 targetPosition) protected
Referenced by Oculus.Interaction.HandPosing.SnapSurfaces.SphereSurface.CalculateBestPoseAtSurface(), Oculus.Interaction.HandPosing.SnapSurfaces.SphereSurface.MinimalRotationPoseAtSurface(), and Oculus.Interaction.HandPosing.SnapSurfaces.SphereSurface.MinimalTranslationPoseAtSurface().
RotationAtPoint()
Quaternion Oculus.Interaction.HandPosing.SnapSurfaces.SphereSurface.RotationAtPoint (Vector3 surfacePoint, Quaternion baseRot, Quaternion desiredRotation) protected
Referenced by Oculus.Interaction.HandPosing.SnapSurfaces.SphereSurface.MinimalRotationPoseAtSurface(), and Oculus.Interaction.HandPosing.SnapSurfaces.SphereSurface.MinimalTranslationPoseAtSurface().
Start()
virtual void Oculus.Interaction.HandPosing.SnapSurfaces.SphereSurface.Start () protected virtual
Member Data Documentation
_data
SphereSurfaceData Oculus.Interaction.HandPosing.SnapSurfaces.SphereSurface._data = new SphereSurfaceData() protected
Referenced by Oculus.Interaction.HandPosing.SnapSurfaces.SphereSurface.CreateDuplicatedSurface(), Oculus.Interaction.HandPosing.SnapSurfaces.SphereSurface.CreateMirroredSurface(), Oculus.Interaction.HandPosing.SnapSurfaces.SphereSurface.InjectData(), and Oculus.Interaction.HandPosing.SnapSurfaces.SphereSurface.Start().
Property Documentation
Centre
Vector3 Oculus.Interaction.HandPosing.SnapSurfaces.SphereSurface.Centre get set
The center of the sphere in world coordinates.
Referenced by Oculus.Interaction.HandPosing.SnapSurfaces.SphereSurface.CalculateBestPoseAtSurface(), Oculus.Interaction.HandPosing.SnapSurfaces.SphereSurface.MinimalRotationPoseAtSurface(), Oculus.Interaction.HandPosing.SnapSurfaces.SphereSurface.NearestPointInSurface(), and Oculus.Interaction.HandPosing.SnapSurfaces.SphereSurface.RotationAtPoint().
Data
SphereSurfaceData Oculus.Interaction.HandPosing.SnapSurfaces.SphereSurface.Data get set
Getter for the data-only version of this surface. Used so it can be stored when created at Play-Mode.
Direction
Vector3 Oculus.Interaction.HandPosing.SnapSurfaces.SphereSurface.Direction get
The direction of the sphere, measured from the center to the original grip position.
Referenced by Oculus.Interaction.HandPosing.SnapSurfaces.SphereSurface.MinimalRotationPoseAtSurface(), Oculus.Interaction.HandPosing.SnapSurfaces.SphereSurface.MirrorPose(), and Oculus.Interaction.HandPosing.SnapSurfaces.SphereSurface.RotationAtPoint().
GripPoint
Transform Oculus.Interaction.HandPosing.SnapSurfaces.SphereSurface.GripPoint get set
Valid point at which the hand can snap, typically the SnapPoint position itself.
Radius
float Oculus.Interaction.HandPosing.SnapSurfaces.SphereSurface.Radius get
The radius of the sphere, this is automatically calculated as the distance between the center and the original grip pose.
Referenced by Oculus.Interaction.HandPosing.SnapSurfaces.SphereSurface.CalculateBestPoseAtSurface(), Oculus.Interaction.HandPosing.SnapSurfaces.SphereSurface.MinimalRotationPoseAtSurface(), and Oculus.Interaction.HandPosing.SnapSurfaces.SphereSurface.NearestPointInSurface().
RelativeTo
Transform Oculus.Interaction.HandPosing.SnapSurfaces.SphereSurface.RelativeTo get set
Transform to which the surface refers to.
Referenced by Oculus.Interaction.HandPosing.SnapSurfaces.SphereSurface.MirrorPose().
Rotation
Quaternion Oculus.Interaction.HandPosing.SnapSurfaces.SphereSurface.Rotation get
The rotation of the sphere from the recorded grip position.
The documentation for this class was generated from the following file:
C:/Users/Lykos/Desktop/Projects/Capstone/VRGames/Assets/ThirdParty/Oculus/Interaction/Runtime/Scripts/HandPosing/SnapSurfaces/SphereSurface.cs