VRCapstoneGames: UnityEngine.XR.Interaction.Toolkit.Inputs.Simulation.XRDeviceSimulator Class Reference
UnityEngine.XR.Interaction.Toolkit.Inputs.Simulation.XRDeviceSimulator Class Reference
A component which handles mouse and keyboard input from the user and uses it to drive simulated XR controllers and an XR head mounted display (HMD).
Public Types
enum Space { Local , Parent , Screen }
The coordinate space in which to operate.
enum TransformationMode { Translate , Rotate }
The transformation mode in which to operate.
enum Axis2DTargets { None = 0 , Position = 1 << 0 , Primary2DAxis = 1 << 1 , Secondary2DAxis = 1 << 2 }
The target device control(s) to update from input.
Protected Member Functions
virtual void Awake ()
See MonoBehaviour.
virtual void OnEnable ()
See MonoBehaviour.
virtual void OnDisable ()
See MonoBehaviour.
virtual void Update ()
See MonoBehaviour.
virtual void ProcessPoseInput ()
Process input from the user and update the state of manipulated device(s) related to position and rotation.
virtual void ProcessControlInput ()
Process input from the user and update the state of manipulated controller device(s) related to input controls.
virtual void ProcessAxis2DControlInput ()
Process input from the user and update the state of manipulated controller device(s) related to 2D Axis input controls.
virtual void ProcessButtonControlInput (ref XRSimulatedControllerState controllerState)
Process input from the user and update the state of manipulated controller device(s) related to button input controls.
virtual void AddDevices ()
Add simulated XR devices to the Input System.
virtual void RemoveDevices ()
Remove simulated XR devices from the Input System.
Vector3 GetResetScale ()
Gets a Vector3 that can be multiplied component-wise with another Vector3 to reset components of the Vector3, based on axis constraint inputs.
Properties
InputActionReference keyboardXTranslateAction [get, set]
The Input System Action used to translate in the x-axis (left/right) while held. Must be a InputActionType.Value AxisControl.
InputActionReference keyboardYTranslateAction [get, set]
The Input System Action used to translate in the y-axis (up/down) while held. Must be a InputActionType.Value AxisControl.
InputActionReference keyboardZTranslateAction [get, set]
The Input System Action used to translate in the z-axis (forward/back) while held. Must be a InputActionType.Value AxisControl.
InputActionReference manipulateLeftAction [get, set]
The Input System Action used to enable manipulation of the left-hand controller while held. Must be a ButtonControl.
InputActionReference manipulateRightAction [get, set]
The Input System Action used to enable manipulation of the right-hand controller while held. Must be a ButtonControl.
InputActionReference toggleManipulateLeftAction [get, set]
The Input System Action used to toggle enable manipulation of the left-hand controller when pressed. Must be a ButtonControl.
InputActionReference toggleManipulateRightAction [get, set]
The Input System Action used to toggle enable manipulation of the right-hand controller when pressed. Must be a ButtonControl.
InputActionReference manipulateHeadAction [get, set]
The Input System Action used to enable manipulation of the HMD while held. Must be a ButtonControl.
InputActionReference mouseDeltaAction [get, set]
The Input System Action used to translate or rotate by a scaled amount along or about the x- and y-axes. Must be a InputActionType.Value Vector2Control.
InputActionReference mouseScrollAction [get, set]
The Input System Action used to translate or rotate by a scaled amount along or about the z-axis. Must be a InputActionType.Value Vector2Control.
InputActionReference rotateModeOverrideAction [get, set]
The Input System Action used to cause the manipulated device(s) to rotate when moving the mouse when held. Must be a ButtonControl.
InputActionReference toggleMouseTransformationModeAction [get, set]
The Input System Action used to toggle between translating or rotating the manipulated device(s) when moving the mouse when pressed. Must be a ButtonControl.
InputActionReference negateModeAction [get, set]
The Input System Action used to cause the manipulated device(s) to rotate when moving the mouse while held when it would normally translate, and vice-versa. Must be a ButtonControl.
InputActionReference xConstraintAction [get, set]
The Input System Action used to constrain the translation or rotation to the x-axis when moving the mouse or resetting. May be combined with another axis constraint to constrain to a plane. Must be a ButtonControl.
InputActionReference yConstraintAction [get, set]
The Input System Action used to constrain the translation or rotation to the y-axis when moving the mouse or resetting. May be combined with another axis constraint to constrain to a plane. Must be a ButtonControl.
InputActionReference zConstraintAction [get, set]
The Input System Action used to constrain the translation or rotation to the z-axis when moving the mouse or resetting. May be combined with another axis constraint to constrain to a plane. Must be a ButtonControl.
InputActionReference resetAction [get, set]
The Input System Action used to cause the manipulated device(s) to reset position or rotation (depending on the effective manipulation mode). Must be a ButtonControl.
InputActionReference toggleCursorLockAction [get, set]
The Input System Action used to toggle the cursor lock mode for the game window when pressed. Must be a ButtonControl.
InputActionReference toggleDevicePositionTargetAction [get, set]
The Input System Action used to toggle enable translation from keyboard inputs when pressed. Must be a ButtonControl.
InputActionReference togglePrimary2DAxisTargetAction [get, set]
The Input System action used to toggle enable manipulation of the Axis2DTargets.Primary2DAxis of the controllers when pressed. Must be a ButtonControl.
InputActionReference toggleSecondary2DAxisTargetAction [get, set]
The Input System action used to toggle enable manipulation of the Axis2DTargets.Secondary2DAxis of the controllers when pressed. Must be a ButtonControl.
InputActionReference axis2DAction [get, set]
The Input System Action used to control the value of one or more 2D Axis controls on the manipulated controller device(s). Must be a InputActionType.Value Vector2Control.
InputActionReference restingHandAxis2DAction [get, set]
The Input System Action used to control one or more 2D Axis controls on the opposite hand of the exclusively manipulated controller device. Must be a InputActionType.Value Vector2Control.
InputActionReference gripAction [get, set]
The Input System Action used to control the Grip control of the manipulated controller device(s). Must be a ButtonControl.
InputActionReference triggerAction [get, set]
The Input System Action used to control the Trigger control of the manipulated controller device(s). Must be a ButtonControl.
InputActionReference primaryButtonAction [get, set]
The Input System Action used to control the PrimaryButton control of the manipulated controller device(s). Must be a ButtonControl.
InputActionReference secondaryButtonAction [get, set]
The Input System Action used to control the SecondaryButton control of the manipulated controller device(s). Must be a ButtonControl.
InputActionReference menuAction [get, set]
The Input System Action used to control the Menu control of the manipulated controller device(s). Must be a ButtonControl.
InputActionReference primary2DAxisClickAction [get, set]
The Input System Action used to control the Primary2DAxisClick control of the manipulated controller device(s). Must be a ButtonControl.
InputActionReference secondary2DAxisClickAction [get, set]
The Input System Action used to control the Secondary2DAxisClick control of the manipulated controller device(s). Must be a ButtonControl.
InputActionReference primary2DAxisTouchAction [get, set]
The Input System Action used to control the Primary2DAxisTouch control of the manipulated controller device(s). Must be a ButtonControl.
InputActionReference secondary2DAxisTouchAction [get, set]
The Input System Action used to control the Secondary2DAxisTouch control of the manipulated controller device(s). Must be a ButtonControl.
InputActionReference primaryTouchAction [get, set]
The Input System Action used to control the PrimaryTouch control of the manipulated controller device(s). Must be a ButtonControl.
InputActionReference secondaryTouchAction [get, set]
The Input System Action used to control the SecondaryTouch control of the manipulated controller device(s). Must be a ButtonControl.
Transform cameraTransform [get, set]
The Transform that contains the Camera. This is usually the "Head" of XR Origins. Automatically set to Camera.main if unset.
Space keyboardTranslateSpace [get, set]
The coordinate space in which keyboard translation should operate.
Space mouseTranslateSpace [get, set]
The coordinate space in which mouse translation should operate.
float keyboardXTranslateSpeed [get, set]
Speed of translation in the x-axis (left/right) when triggered by keyboard input.
float keyboardYTranslateSpeed [get, set]
Speed of translation in the y-axis (up/down) when triggered by keyboard input.
float keyboardZTranslateSpeed [get, set]
Speed of translation in the z-axis (forward/back) when triggered by keyboard input.
float mouseXTranslateSensitivity [get, set]
Sensitivity of translation in the x-axis (left/right) when triggered by mouse input.
float mouseYTranslateSensitivity [get, set]
Sensitivity of translation in the y-axis (up/down) when triggered by mouse input.
float mouseScrollTranslateSensitivity [get, set]
Sensitivity of translation in the z-axis (forward/back) when triggered by mouse scroll input.
float mouseXRotateSensitivity [get, set]
Sensitivity of rotation along the x-axis (pitch) when triggered by mouse input.
float mouseYRotateSensitivity [get, set]
Sensitivity of rotation along the y-axis (yaw) when triggered by mouse input.
float mouseScrollRotateSensitivity [get, set]
Sensitivity of rotation along the z-axis (roll) when triggered by mouse scroll input.
bool mouseYRotateInvert [get, set]
A boolean value of whether to invert the y-axis of mouse input when rotating by mouse input. A false value (default) means typical FPS style where moving the mouse up/down pitches up/down. A true value means flight control style where moving the mouse up/down pitches down/up.
CursorLockMode desiredCursorLockMode [get, set]
The desired cursor lock mode to toggle to from CursorLockMode.None (either CursorLockMode.Locked or CursorLockMode.Confined).
TransformationMode mouseTransformationMode = TransformationMode.Translate [get, set]
The transformation mode in which the mouse should operate.
Axis2DTargets axis2DTargets = Axis2DTargets.Primary2DAxis [get, set]
One or more 2D Axis controls that keyboard input should apply to (or none).
Detailed Description
A component which handles mouse and keyboard input from the user and uses it to drive simulated XR controllers and an XR head mounted display (HMD).
This class does not directly manipulate the camera or controllers which are part of the XR Origin, but rather drives them indirectly through simulated input devices.
Use the Package Manager window to install the XR Device Simulator sample into your project to get sample mouse and keyboard bindings for Input System actions that this component expects. The sample also includes a prefab of a GameObject with this component attached that has references to those sample actions already set. To make use of this simulator, add the prefab to your scene (the prefab makes use of InputActionManager to ensure the Input System actions are enabled).
Note that the XR Origin must read the position and rotation of the HMD and controllers by using Input System actions (such as by using ActionBasedController and TrackedPoseDriver) for this simulator to work as expected. Attempting to use XR input subsystem device methods (such as by using XRController and SpatialTracking.TrackedPoseDriver) will not work as expected since this simulator depends on the Input System to drive the simulated devices.
See also
XRSimulatedController, XRSimulatedHMD, SimulatedInputLayoutLoader
Member Enumeration Documentation
Axis2DTargets
enum UnityEngine.XR.Interaction.Toolkit.Inputs.Simulation.XRDeviceSimulator.Axis2DTargets
The target device control(s) to update from input.
FlagsAttribute to support updating multiple controls from input (e.g. to drive the primary and secondary 2D axis on a controller from the same input).
See also
axis2DTargets
Enumerator
None
Do not update device state from input.
Position
Update device position from input.
Primary2DAxis
Update the primary touchpad or joystick on a controller device from input.
Secondary2DAxis
Update the secondary touchpad or joystick on a controller device from input.
Space
enum UnityEngine.XR.Interaction.Toolkit.Inputs.Simulation.XRDeviceSimulator.Space
The coordinate space in which to operate.
See also
keyboardTranslateSpace, mouseTranslateSpace
Enumerator
Local
Applies translations of a controller or HMD relative to its own coordinate space, considering its own rotations. Will translate a controller relative to itself, independent of the camera.
Parent
Applies translations of a controller or HMD relative to its parent. If the object does not have a parent, meaning it is a root object, the parent coordinate space is the same as the world coordinate space. This is the same as Local but without considering its own rotations.
Screen
Applies translations of a controller or HMD relative to the screen. Will translate a controller relative to the camera, independent of the controller's orientation.
TransformationMode
enum UnityEngine.XR.Interaction.Toolkit.Inputs.Simulation.XRDeviceSimulator.TransformationMode
The transformation mode in which to operate.
See also
mouseTransformationMode
Enumerator
Translate
Applies translations from input.
Rotate
Applies rotations from input.
Member Function Documentation
AddDevices()
virtual void UnityEngine.XR.Interaction.Toolkit.Inputs.Simulation.XRDeviceSimulator.AddDevices () protected virtual
Add simulated XR devices to the Input System.
Referenced by UnityEngine.XR.Interaction.Toolkit.Inputs.Simulation.XRDeviceSimulator.OnEnable().
Awake()
virtual void UnityEngine.XR.Interaction.Toolkit.Inputs.Simulation.XRDeviceSimulator.Awake () protected virtual
See MonoBehaviour.
GetResetScale()
Vector3 UnityEngine.XR.Interaction.Toolkit.Inputs.Simulation.XRDeviceSimulator.GetResetScale () protected
Gets a Vector3 that can be multiplied component-wise with another Vector3 to reset components of the Vector3, based on axis constraint inputs.
Returns
See also
resetAction, xConstraintAction, yConstraintAction, zConstraintAction
Referenced by UnityEngine.XR.Interaction.Toolkit.Inputs.Simulation.XRDeviceSimulator.ProcessPoseInput().
OnDisable()
virtual void UnityEngine.XR.Interaction.Toolkit.Inputs.Simulation.XRDeviceSimulator.OnDisable () protected virtual
See MonoBehaviour.
OnEnable()
virtual void UnityEngine.XR.Interaction.Toolkit.Inputs.Simulation.XRDeviceSimulator.OnEnable () protected virtual
See MonoBehaviour.
ProcessAxis2DControlInput()
virtual void UnityEngine.XR.Interaction.Toolkit.Inputs.Simulation.XRDeviceSimulator.ProcessAxis2DControlInput () protected virtual
Process input from the user and update the state of manipulated controller device(s) related to 2D Axis input controls.
Referenced by UnityEngine.XR.Interaction.Toolkit.Inputs.Simulation.XRDeviceSimulator.ProcessControlInput().
ProcessButtonControlInput()
virtual void UnityEngine.XR.Interaction.Toolkit.Inputs.Simulation.XRDeviceSimulator.ProcessButtonControlInput (ref XRSimulatedControllerState controllerState) protected virtual
Process input from the user and update the state of manipulated controller device(s) related to button input controls.
Parameters
controllerState The controller state that will be processed.
Referenced by UnityEngine.XR.Interaction.Toolkit.Inputs.Simulation.XRDeviceSimulator.ProcessControlInput().
ProcessControlInput()
virtual void UnityEngine.XR.Interaction.Toolkit.Inputs.Simulation.XRDeviceSimulator.ProcessControlInput () protected virtual
Process input from the user and update the state of manipulated controller device(s) related to input controls.
Referenced by UnityEngine.XR.Interaction.Toolkit.Inputs.Simulation.XRDeviceSimulator.Update().
ProcessPoseInput()
virtual void UnityEngine.XR.Interaction.Toolkit.Inputs.Simulation.XRDeviceSimulator.ProcessPoseInput () protected virtual
Process input from the user and update the state of manipulated device(s) related to position and rotation.
Referenced by UnityEngine.XR.Interaction.Toolkit.Inputs.Simulation.XRDeviceSimulator.Update().
RemoveDevices()
virtual void UnityEngine.XR.Interaction.Toolkit.Inputs.Simulation.XRDeviceSimulator.RemoveDevices () protected virtual
Remove simulated XR devices from the Input System.
Referenced by UnityEngine.XR.Interaction.Toolkit.Inputs.Simulation.XRDeviceSimulator.OnDisable().
Update()
virtual void UnityEngine.XR.Interaction.Toolkit.Inputs.Simulation.XRDeviceSimulator.Update () protected virtual
See MonoBehaviour.
Property Documentation
axis2DAction
InputActionReference UnityEngine.XR.Interaction.Toolkit.Inputs.Simulation.XRDeviceSimulator.axis2DAction get set
The Input System Action used to control the value of one or more 2D Axis controls on the manipulated controller device(s). Must be a InputActionType.Value Vector2Control.
togglePrimary2DAxisTargetAction and toggleSecondary2DAxisTargetAction toggle enables the ability to manipulate 2D Axis controls on the simulated controllers, and this axis2DAction actually controls the value of them while those controller devices are being manipulated.
Typically bound to WASD on a keyboard, and controls the primary and/or secondary 2D Axis controls on them.
axis2DTargets
Axis2DTargets UnityEngine.XR.Interaction.Toolkit.Inputs.Simulation.XRDeviceSimulator.axis2DTargets = Axis2DTargets.Primary2DAxis get set
One or more 2D Axis controls that keyboard input should apply to (or none).
Used to control a combination of the position (Axis2DTargets.Position), primary 2D axis (Axis2DTargets.Primary2DAxis), or secondary 2D axis (Axis2DTargets.Secondary2DAxis) of manipulated device(s).
See also
keyboardXTranslateAction, keyboardYTranslateAction, keyboardZTranslateAction, axis2DAction, restingHandAxis2DAction
Referenced by UnityEngine.XR.Interaction.Toolkit.Inputs.Simulation.XRDeviceSimulator.ProcessAxis2DControlInput(), and UnityEngine.XR.Interaction.Toolkit.Inputs.Simulation.XRDeviceSimulator.ProcessPoseInput().
cameraTransform
Transform UnityEngine.XR.Interaction.Toolkit.Inputs.Simulation.XRDeviceSimulator.cameraTransform get set
The Transform that contains the Camera. This is usually the "Head" of XR Origins. Automatically set to Camera.main if unset.
desiredCursorLockMode
CursorLockMode UnityEngine.XR.Interaction.Toolkit.Inputs.Simulation.XRDeviceSimulator.desiredCursorLockMode get set
The desired cursor lock mode to toggle to from CursorLockMode.None (either CursorLockMode.Locked or CursorLockMode.Confined).
See also
toggleCursorLockAction
gripAction
InputActionReference UnityEngine.XR.Interaction.Toolkit.Inputs.Simulation.XRDeviceSimulator.gripAction get set
The Input System Action used to control the Grip control of the manipulated controller device(s). Must be a ButtonControl.
keyboardTranslateSpace
Space UnityEngine.XR.Interaction.Toolkit.Inputs.Simulation.XRDeviceSimulator.keyboardTranslateSpace get set
The coordinate space in which keyboard translation should operate.
See also
Space, mouseTranslateSpace, keyboardXTranslateAction, keyboardYTranslateAction, keyboardZTranslateAction
keyboardXTranslateAction
InputActionReference UnityEngine.XR.Interaction.Toolkit.Inputs.Simulation.XRDeviceSimulator.keyboardXTranslateAction get set
The Input System Action used to translate in the x-axis (left/right) while held. Must be a InputActionType.Value AxisControl.
keyboardXTranslateSpeed
float UnityEngine.XR.Interaction.Toolkit.Inputs.Simulation.XRDeviceSimulator.keyboardXTranslateSpeed get set
Speed of translation in the x-axis (left/right) when triggered by keyboard input.
See also
keyboardXTranslateAction, keyboardYTranslateSpeed, keyboardZTranslateSpeed
keyboardYTranslateAction
InputActionReference UnityEngine.XR.Interaction.Toolkit.Inputs.Simulation.XRDeviceSimulator.keyboardYTranslateAction get set
The Input System Action used to translate in the y-axis (up/down) while held. Must be a InputActionType.Value AxisControl.
keyboardYTranslateSpeed
float UnityEngine.XR.Interaction.Toolkit.Inputs.Simulation.XRDeviceSimulator.keyboardYTranslateSpeed get set
Speed of translation in the y-axis (up/down) when triggered by keyboard input.
See also
keyboardYTranslateAction, keyboardXTranslateSpeed, keyboardZTranslateSpeed
keyboardZTranslateAction
InputActionReference UnityEngine.XR.Interaction.Toolkit.Inputs.Simulation.XRDeviceSimulator.keyboardZTranslateAction get set
The Input System Action used to translate in the z-axis (forward/back) while held. Must be a InputActionType.Value AxisControl.
keyboardZTranslateSpeed
float UnityEngine.XR.Interaction.Toolkit.Inputs.Simulation.XRDeviceSimulator.keyboardZTranslateSpeed get set
Speed of translation in the z-axis (forward/back) when triggered by keyboard input.
See also
keyboardZTranslateAction, keyboardXTranslateSpeed, keyboardYTranslateSpeed
manipulateHeadAction
InputActionReference UnityEngine.XR.Interaction.Toolkit.Inputs.Simulation.XRDeviceSimulator.manipulateHeadAction get set
The Input System Action used to enable manipulation of the HMD while held. Must be a ButtonControl.
manipulateLeftAction
InputActionReference UnityEngine.XR.Interaction.Toolkit.Inputs.Simulation.XRDeviceSimulator.manipulateLeftAction get set
The Input System Action used to enable manipulation of the left-hand controller while held. Must be a ButtonControl.
Note that if controls on the left-hand controller are actuated when this action is released, those controls will continue to remain actuated. This is to allow for multi-hand interactions without needing to have dedicated bindings for manipulating each controller separately and concurrently.
See also
manipulateRightAction, toggleManipulateLeftAction
manipulateRightAction
InputActionReference UnityEngine.XR.Interaction.Toolkit.Inputs.Simulation.XRDeviceSimulator.manipulateRightAction get set
The Input System Action used to enable manipulation of the right-hand controller while held. Must be a ButtonControl.
Note that if controls on the right-hand controller are actuated when this action is released, those controls will continue to remain actuated. This is to allow for multi-hand interactions without needing to have dedicated bindings for manipulating each controller separately and concurrently.
See also
manipulateLeftAction
menuAction
InputActionReference UnityEngine.XR.Interaction.Toolkit.Inputs.Simulation.XRDeviceSimulator.menuAction get set
The Input System Action used to control the Menu control of the manipulated controller device(s). Must be a ButtonControl.
mouseDeltaAction
InputActionReference UnityEngine.XR.Interaction.Toolkit.Inputs.Simulation.XRDeviceSimulator.mouseDeltaAction get set
The Input System Action used to translate or rotate by a scaled amount along or about the x- and y-axes. Must be a InputActionType.Value Vector2Control.
Typically bound to the screen-space motion delta of the mouse in pixels.
See also
mouseScrollAction
mouseScrollAction
InputActionReference UnityEngine.XR.Interaction.Toolkit.Inputs.Simulation.XRDeviceSimulator.mouseScrollAction get set
The Input System Action used to translate or rotate by a scaled amount along or about the z-axis. Must be a InputActionType.Value Vector2Control.
Typically bound to the horizontal and vertical scroll wheels, though only the vertical is used.
See also
mouseDeltaAction
mouseScrollRotateSensitivity
float UnityEngine.XR.Interaction.Toolkit.Inputs.Simulation.XRDeviceSimulator.mouseScrollRotateSensitivity get set
Sensitivity of rotation along the z-axis (roll) when triggered by mouse scroll input.
See also
mouseScrollAction, mouseXRotateSensitivity, mouseYRotateSensitivity
mouseScrollTranslateSensitivity
float UnityEngine.XR.Interaction.Toolkit.Inputs.Simulation.XRDeviceSimulator.mouseScrollTranslateSensitivity get set
Sensitivity of translation in the z-axis (forward/back) when triggered by mouse scroll input.
See also
mouseScrollAction, mouseXTranslateSensitivity, mouseYTranslateSensitivity
mouseTransformationMode
TransformationMode UnityEngine.XR.Interaction.Toolkit.Inputs.Simulation.XRDeviceSimulator.mouseTransformationMode = TransformationMode.Translate get set
The transformation mode in which the mouse should operate.
Referenced by UnityEngine.XR.Interaction.Toolkit.Inputs.Simulation.XRDeviceSimulator.ProcessPoseInput().
mouseTranslateSpace
Space UnityEngine.XR.Interaction.Toolkit.Inputs.Simulation.XRDeviceSimulator.mouseTranslateSpace get set
The coordinate space in which mouse translation should operate.
See also
Space, keyboardTranslateSpace
mouseXRotateSensitivity
float UnityEngine.XR.Interaction.Toolkit.Inputs.Simulation.XRDeviceSimulator.mouseXRotateSensitivity get set
Sensitivity of rotation along the x-axis (pitch) when triggered by mouse input.
See also
mouseDeltaAction, mouseYRotateSensitivity, mouseScrollRotateSensitivity
mouseXTranslateSensitivity
float UnityEngine.XR.Interaction.Toolkit.Inputs.Simulation.XRDeviceSimulator.mouseXTranslateSensitivity get set
Sensitivity of translation in the x-axis (left/right) when triggered by mouse input.
See also
mouseDeltaAction, mouseYTranslateSensitivity, mouseScrollTranslateSensitivity
mouseYRotateInvert
bool UnityEngine.XR.Interaction.Toolkit.Inputs.Simulation.XRDeviceSimulator.mouseYRotateInvert get set
A boolean value of whether to invert the y-axis of mouse input when rotating by mouse input. A false value (default) means typical FPS style where moving the mouse up/down pitches up/down. A true value means flight control style where moving the mouse up/down pitches down/up.
mouseYRotateSensitivity
float UnityEngine.XR.Interaction.Toolkit.Inputs.Simulation.XRDeviceSimulator.mouseYRotateSensitivity get set
Sensitivity of rotation along the y-axis (yaw) when triggered by mouse input.
See also
mouseDeltaAction, mouseXRotateSensitivity, mouseScrollRotateSensitivity
mouseYTranslateSensitivity
float UnityEngine.XR.Interaction.Toolkit.Inputs.Simulation.XRDeviceSimulator.mouseYTranslateSensitivity get set
Sensitivity of translation in the y-axis (up/down) when triggered by mouse input.
See also
mouseDeltaAction, mouseXTranslateSensitivity, mouseScrollTranslateSensitivity
negateModeAction
InputActionReference UnityEngine.XR.Interaction.Toolkit.Inputs.Simulation.XRDeviceSimulator.negateModeAction get set
The Input System Action used to cause the manipulated device(s) to rotate when moving the mouse while held when it would normally translate, and vice-versa. Must be a ButtonControl.
Can be used to temporarily change the mouse transformation mode to the other mode while held for making quick adjustments.
See also
toggleMouseTransformationModeAction
primary2DAxisClickAction
InputActionReference UnityEngine.XR.Interaction.Toolkit.Inputs.Simulation.XRDeviceSimulator.primary2DAxisClickAction get set
The Input System Action used to control the Primary2DAxisClick control of the manipulated controller device(s). Must be a ButtonControl.
primary2DAxisTouchAction
InputActionReference UnityEngine.XR.Interaction.Toolkit.Inputs.Simulation.XRDeviceSimulator.primary2DAxisTouchAction get set
The Input System Action used to control the Primary2DAxisTouch control of the manipulated controller device(s). Must be a ButtonControl.
primaryButtonAction
InputActionReference UnityEngine.XR.Interaction.Toolkit.Inputs.Simulation.XRDeviceSimulator.primaryButtonAction get set
The Input System Action used to control the PrimaryButton control of the manipulated controller device(s). Must be a ButtonControl.
primaryTouchAction
InputActionReference UnityEngine.XR.Interaction.Toolkit.Inputs.Simulation.XRDeviceSimulator.primaryTouchAction get set
The Input System Action used to control the PrimaryTouch control of the manipulated controller device(s). Must be a ButtonControl.
resetAction
InputActionReference UnityEngine.XR.Interaction.Toolkit.Inputs.Simulation.XRDeviceSimulator.resetAction get set
The Input System Action used to cause the manipulated device(s) to reset position or rotation (depending on the effective manipulation mode). Must be a ButtonControl.
Resets position to Vector3.zero and rotation to Quaternion.identity. May be combined with axis constraints (xConstraintAction, yConstraintAction, and zConstraintAction).
restingHandAxis2DAction
InputActionReference UnityEngine.XR.Interaction.Toolkit.Inputs.Simulation.XRDeviceSimulator.restingHandAxis2DAction get set
The Input System Action used to control one or more 2D Axis controls on the opposite hand of the exclusively manipulated controller device. Must be a InputActionType.Value Vector2Control.
Typically bound to Q and E on a keyboard for the horizontal component, and controls the opposite hand's 2D Axis controls when manipulating one (and only one) controller. Can be used to quickly and simultaneously control the 2D Axis on the other hand's controller. In a typical setup of continuous movement bound on the left-hand controller stick, and turning bound on the right-hand controller stick, while exclusively manipulating the left-hand controller to move, this action can be used to trigger turning.
See also
axis2DAction
rotateModeOverrideAction
InputActionReference UnityEngine.XR.Interaction.Toolkit.Inputs.Simulation.XRDeviceSimulator.rotateModeOverrideAction get set
The Input System Action used to cause the manipulated device(s) to rotate when moving the mouse when held. Must be a ButtonControl.
Forces rotation mode when held, no matter what the current mouse transformation mode is.
See also
negateModeAction
secondary2DAxisClickAction
InputActionReference UnityEngine.XR.Interaction.Toolkit.Inputs.Simulation.XRDeviceSimulator.secondary2DAxisClickAction get set
The Input System Action used to control the Secondary2DAxisClick control of the manipulated controller device(s). Must be a ButtonControl.
secondary2DAxisTouchAction
InputActionReference UnityEngine.XR.Interaction.Toolkit.Inputs.Simulation.XRDeviceSimulator.secondary2DAxisTouchAction get set
The Input System Action used to control the Secondary2DAxisTouch control of the manipulated controller device(s). Must be a ButtonControl.
secondaryButtonAction
InputActionReference UnityEngine.XR.Interaction.Toolkit.Inputs.Simulation.XRDeviceSimulator.secondaryButtonAction get set
The Input System Action used to control the SecondaryButton control of the manipulated controller device(s). Must be a ButtonControl.
secondaryTouchAction
InputActionReference UnityEngine.XR.Interaction.Toolkit.Inputs.Simulation.XRDeviceSimulator.secondaryTouchAction get set
The Input System Action used to control the SecondaryTouch control of the manipulated controller device(s). Must be a ButtonControl.
toggleCursorLockAction
InputActionReference UnityEngine.XR.Interaction.Toolkit.Inputs.Simulation.XRDeviceSimulator.toggleCursorLockAction get set
The Input System Action used to toggle the cursor lock mode for the game window when pressed. Must be a ButtonControl.
See also
Cursor.lockState, desiredCursorLockMode
toggleDevicePositionTargetAction
InputActionReference UnityEngine.XR.Interaction.Toolkit.Inputs.Simulation.XRDeviceSimulator.toggleDevicePositionTargetAction get set
The Input System Action used to toggle enable translation from keyboard inputs when pressed. Must be a ButtonControl.
See also
keyboardXTranslateAction, keyboardYTranslateAction, keyboardZTranslateAction
toggleManipulateLeftAction
InputActionReference UnityEngine.XR.Interaction.Toolkit.Inputs.Simulation.XRDeviceSimulator.toggleManipulateLeftAction get set
The Input System Action used to toggle enable manipulation of the left-hand controller when pressed. Must be a ButtonControl.
See also
manipulateLeftAction, toggleManipulateRightAction
toggleManipulateRightAction
InputActionReference UnityEngine.XR.Interaction.Toolkit.Inputs.Simulation.XRDeviceSimulator.toggleManipulateRightAction get set
The Input System Action used to toggle enable manipulation of the right-hand controller when pressed. Must be a ButtonControl.
See also
manipulateRightAction, toggleManipulateLeftAction
toggleMouseTransformationModeAction
InputActionReference UnityEngine.XR.Interaction.Toolkit.Inputs.Simulation.XRDeviceSimulator.toggleMouseTransformationModeAction get set
The Input System Action used to toggle between translating or rotating the manipulated device(s) when moving the mouse when pressed. Must be a ButtonControl.
togglePrimary2DAxisTargetAction
InputActionReference UnityEngine.XR.Interaction.Toolkit.Inputs.Simulation.XRDeviceSimulator.togglePrimary2DAxisTargetAction get set
The Input System action used to toggle enable manipulation of the Axis2DTargets.Primary2DAxis of the controllers when pressed. Must be a ButtonControl.
See also
toggleSecondary2DAxisTargetAction, toggleDevicePositionTargetAction, axis2DAction
toggleSecondary2DAxisTargetAction
InputActionReference UnityEngine.XR.Interaction.Toolkit.Inputs.Simulation.XRDeviceSimulator.toggleSecondary2DAxisTargetAction get set
The Input System action used to toggle enable manipulation of the Axis2DTargets.Secondary2DAxis of the controllers when pressed. Must be a ButtonControl.
See also
togglePrimary2DAxisTargetAction, toggleDevicePositionTargetAction, axis2DAction
triggerAction
InputActionReference UnityEngine.XR.Interaction.Toolkit.Inputs.Simulation.XRDeviceSimulator.triggerAction get set
The Input System Action used to control the Trigger control of the manipulated controller device(s). Must be a ButtonControl.
xConstraintAction
InputActionReference UnityEngine.XR.Interaction.Toolkit.Inputs.Simulation.XRDeviceSimulator.xConstraintAction get set
The Input System Action used to constrain the translation or rotation to the x-axis when moving the mouse or resetting. May be combined with another axis constraint to constrain to a plane. Must be a ButtonControl.
See also
yConstraintAction, zConstraintAction
yConstraintAction
InputActionReference UnityEngine.XR.Interaction.Toolkit.Inputs.Simulation.XRDeviceSimulator.yConstraintAction get set
The Input System Action used to constrain the translation or rotation to the y-axis when moving the mouse or resetting. May be combined with another axis constraint to constrain to a plane. Must be a ButtonControl.
See also
xConstraintAction, zConstraintAction
zConstraintAction
InputActionReference UnityEngine.XR.Interaction.Toolkit.Inputs.Simulation.XRDeviceSimulator.zConstraintAction get set
The Input System Action used to constrain the translation or rotation to the z-axis when moving the mouse or resetting. May be combined with another axis constraint to constrain to a plane. Must be a ButtonControl.
See also
xConstraintAction, yConstraintAction
The documentation for this class was generated from the following file:
C:/Users/Lykos/Desktop/Projects/Capstone/VRGames/Library/PackageCache/com.unity.xr.interaction.toolkit@2.0.2/Runtime/Inputs/Simulation/XRDeviceSimulator.cs