VRGames: UnityEditor.XR.Management.XRGeneralSettingsPerBuildTarget Class Reference
UnityEditor.XR.Management.XRGeneralSettingsPerBuildTarget Class Reference
Container class that holds general settings for each build target group installed in Unity.
Public Member Functions
bool HasSettingsForBuildTarget (BuildTargetGroup buildTargetGroup)
Query this settings store to see if there are settings for a specific BuildTargetGroup.
void CreateDefaultSettingsForBuildTarget (BuildTargetGroup buildTargetGroup)
Create default settings for a given build target.
void SetSettingsForBuildTarget (BuildTargetGroup targetGroup, XRGeneralSettings settings)
Set specific settings for a given build target.
XRGeneralSettings SettingsForBuildTarget (BuildTargetGroup targetGroup)
Get specific settings for a given build target.
bool HasManagerSettingsForBuildTarget (BuildTargetGroup targetGroup)
Check if current settings instance has an instance of XRManagerSettings.
void CreateDefaultManagerSettingsForBuildTarget (BuildTargetGroup targetGroup)
Create a new default instance of XRManagerSettings for a build target. Requires that the there exists a settings instance for the build target. If there isn't, then one is created.
XRManagerSettings ManagerSettingsForBuildTarget (BuildTargetGroup targetGroup)
Return the current instance of XRManagerSettings for a build target.
void OnBeforeSerialize ()
Serialization override.
void OnAfterDeserialize ()
Serialization override.
Static Public Member Functions
static XRGeneralSettings XRGeneralSettingsForBuildTarget (BuildTargetGroup targetGroup)
Given a build target, get the general settings container assigned to it.
Detailed Description
Container class that holds general settings for each build target group installed in Unity.
Member Function Documentation
CreateDefaultManagerSettingsForBuildTarget()
void UnityEditor.XR.Management.XRGeneralSettingsPerBuildTarget.CreateDefaultManagerSettingsForBuildTarget (BuildTargetGroup targetGroup)
Create a new default instance of XRManagerSettings for a build target. Requires that the there exists a settings instance for the build target. If there isn't, then one is created.
This will overwrite any current settings for that build target.
Parameters
targetGroup An enum specifying which platform group this build is for.
CreateDefaultSettingsForBuildTarget()
void UnityEditor.XR.Management.XRGeneralSettingsPerBuildTarget.CreateDefaultSettingsForBuildTarget (BuildTargetGroup buildTargetGroup)
Create default settings for a given build target.
This will overwrite any current settings for that build target.
Parameters
buildTargetGroup Build target to create default settings for.
Referenced by UnityEditor.XR.Management.XRGeneralSettingsPerBuildTarget.CreateDefaultManagerSettingsForBuildTarget().
HasManagerSettingsForBuildTarget()
bool UnityEditor.XR.Management.XRGeneralSettingsPerBuildTarget.HasManagerSettingsForBuildTarget (BuildTargetGroup targetGroup)
Check if current settings instance has an instance of XRManagerSettings.
Parameters
targetGroup An enum specifying which platform group this build is for.
Returns
True if it exists, false otherwise.
HasSettingsForBuildTarget()
bool UnityEditor.XR.Management.XRGeneralSettingsPerBuildTarget.HasSettingsForBuildTarget (BuildTargetGroup buildTargetGroup)
Query this settings store to see if there are settings for a specific BuildTargetGroup.
Parameters
buildTargetGroup Build target to check
Returns
True if there are settings, otherwise false.
Referenced by UnityEditor.XR.Management.XRGeneralSettingsPerBuildTarget.CreateDefaultManagerSettingsForBuildTarget().
ManagerSettingsForBuildTarget()
XRManagerSettings UnityEditor.XR.Management.XRGeneralSettingsPerBuildTarget.ManagerSettingsForBuildTarget (BuildTargetGroup targetGroup)
Return the current instance of XRManagerSettings for a build target.
Parameters
targetGroup An enum specifying which platform group this build is for.
Returns
OnAfterDeserialize()
void UnityEditor.XR.Management.XRGeneralSettingsPerBuildTarget.OnAfterDeserialize ()
Serialization override.
OnBeforeSerialize()
void UnityEditor.XR.Management.XRGeneralSettingsPerBuildTarget.OnBeforeSerialize ()
Serialization override.
SetSettingsForBuildTarget()
void UnityEditor.XR.Management.XRGeneralSettingsPerBuildTarget.SetSettingsForBuildTarget (BuildTargetGroup targetGroup, XRGeneralSettings settings)
Set specific settings for a given build target.
Parameters
targetGroup An enum specifying which platform group this build is for.
settings An instance of XRGeneralSettings to assign for the given key.
Referenced by UnityEditor.XR.Management.XRGeneralSettingsPerBuildTarget.CreateDefaultSettingsForBuildTarget(), UnityEditor.XR.Management.Tests.PackageManagementTests.SetUp(), and Unity.XR.TestTooling.ManagementTestSetup.SetupTest().
SettingsForBuildTarget()
XRGeneralSettings UnityEditor.XR.Management.XRGeneralSettingsPerBuildTarget.SettingsForBuildTarget (BuildTargetGroup targetGroup)
Get specific settings for a given build target.
Parameters
targetGroup An enum specifying which platform group this build is for.
Returns
The instance of XRGeneralSettings assigned to the key, or null if not.
Referenced by UnityEditor.XR.Management.XRGeneralSettingsPerBuildTarget.CreateDefaultManagerSettingsForBuildTarget(), UnityEditor.XR.Management.XRGeneralSettingsPerBuildTarget.HasManagerSettingsForBuildTarget(), UnityEditor.XR.Management.XRGeneralSettingsPerBuildTarget.HasSettingsForBuildTarget(), UnityEditor.XR.Management.XRGeneralSettingsPerBuildTarget.ManagerSettingsForBuildTarget(), UnityEditor.XR.Management.XRGeneralBuildProcessor.OnPreprocessBuild(), UnityEditor.XR.Management.Tests.XRGeneralSettingsTests.UpdateGeneralSettings_ToPerBuildTargetSettings(), and UnityEditor.XR.Management.XRGeneralSettingsPerBuildTarget.XRGeneralSettingsForBuildTarget().
XRGeneralSettingsForBuildTarget()
static XRGeneralSettings UnityEditor.XR.Management.XRGeneralSettingsPerBuildTarget.XRGeneralSettingsForBuildTarget (BuildTargetGroup targetGroup) static
Given a build target, get the general settings container assigned to it.
Parameters
targetGroup An enum specifying which platform group this build is for.
Returns
The instance of XRGeneralSettings assigned to the key, or null if not.
Referenced by UnityEditor.XR.Management.Metadata.XRPackageMetadataStore.IsLoaderAssigned().
The documentation for this class was generated from the following file:
C:/Users/Lykos/Desktop/Projects/Capstone/VRGames/Library/PackageCache/com.unity.xr.management@4.2.1/Editor/XRGeneralSettingsPerBuildTarget.cs