VRCapstoneGames: TMPro.TMP_UpdateManager Class Reference
TMPro.TMP_UpdateManager Class Reference
Static Public Member Functions
static void RegisterTextElementForLayoutRebuild (TMP_Text element)
Function to register elements which require a layout rebuild.
static void RegisterTextElementForGraphicRebuild (TMP_Text element)
Function to register elements which require a layout rebuild.
static void RegisterTextElementForCullingUpdate (TMP_Text element)
static void UnRegisterTextElementForRebuild (TMP_Text element)
Function to unregister elements which no longer require a rebuild.
Member Function Documentation
RegisterTextElementForCullingUpdate()
static void TMPro.TMP_UpdateManager.RegisterTextElementForCullingUpdate (TMP_Text element) static
Referenced by TMPro.TextMeshProUGUI.Cull().
RegisterTextElementForGraphicRebuild()
static void TMPro.TMP_UpdateManager.RegisterTextElementForGraphicRebuild (TMP_Text element) static
Function to register elements which require a layout rebuild.
Parameters
element
Referenced by TMPro.TextMeshPro.SetVerticesDirty().
RegisterTextElementForLayoutRebuild()
static void TMPro.TMP_UpdateManager.RegisterTextElementForLayoutRebuild (TMP_Text element) static
Function to register elements which require a layout rebuild.
Parameters
element
UnRegisterTextElementForRebuild()
static void TMPro.TMP_UpdateManager.UnRegisterTextElementForRebuild (TMP_Text element) static
Function to unregister elements which no longer require a rebuild.
Parameters
element
Referenced by TMPro.TextMeshPro.OnDestroy(), and TMPro.TextMeshPro.OnDisable().
The documentation for this class was generated from the following file:
C:/Users/Lykos/Desktop/Projects/Capstone/VRGames/Library/PackageCache/com.unity.textmeshpro@3.0.6/Scripts/Runtime/TMP_UpdateManager.cs