VRGames: UnityEditor.XR.Interaction.Toolkit.XRControllerRecordingEditor Class Reference
UnityEditor.XR.Interaction.Toolkit.XRControllerRecordingEditor Class Reference
Custom editor for an XRControllerRecording.
Classes
class Contents
Contents of GUI elements used by this editor.
Protected Member Functions
virtual void OnEnable ()
This function is called when the object becomes enabled and active.
override void DrawInspector ()
virtual void DrawBeforeProperties ()
This method is automatically called by DrawInspector to draw the section of the custom inspector before DrawProperties. By default, this draws the read-only Script property.
virtual void DrawProperties ()
This method is automatically called by DrawInspector to draw the property fields. Override this method to customize the properties shown in the Inspector. This is typically the method overridden when a derived behavior adds additional serialized properties that should be displayed in the Inspector.
virtual void DrawRecordingFrames ()
Draw the frames stored in the recording.
virtual void DrawRecordingFrame (XRControllerState frame)
Draw the frame stored in the recording.
Protected Member Functions inherited from UnityEditor.XR.Interaction.Toolkit.BaseInteractionEditor
void DrawInspector ()
This method is automatically called by OnInspectorGUI to draw the custom inspector. Override this method to customize the inspector as a whole.
virtual void InitializeKnownSerializedPropertyNames ()
This method is automatically called by OnInspectorGUI to initialize knownSerializedPropertyNames if necessary. This is used together with DrawDerivedProperties to draw all unknown serialized fields from derived classes.
virtual List< string > GetDerivedSerializedPropertyNames ()
Returns a list containing the SerializeField names of all SerializedProperty fields defined in the Editor (including derived types).
virtual void DrawDerivedProperties ()
This method is automatically called by DrawInspector to draw the property fields of derived classes that are not explicitly defined in the Editor.
virtual void DrawScript ()
Draw the standard read-only Script property.
Static Protected Attributes
const string k_ValueFormat = "0.#"
String format used to display the interaction values.
Additional Inherited Members
Public Member Functions inherited from UnityEditor.XR.Interaction.Toolkit.BaseInteractionEditor
override void OnInspectorGUI ()
Properties inherited from UnityEditor.XR.Interaction.Toolkit.BaseInteractionEditor
string[] knownSerializedPropertyNames [get, set]
The SerializeField names of all SerializedProperty fields defined in the Editor (including derived types).
Detailed Description
Custom editor for an XRControllerRecording.
Member Function Documentation
DrawBeforeProperties()
virtual void UnityEditor.XR.Interaction.Toolkit.XRControllerRecordingEditor.DrawBeforeProperties () protected virtual
This method is automatically called by DrawInspector to draw the section of the custom inspector before DrawProperties. By default, this draws the read-only Script property.
Referenced by UnityEditor.XR.Interaction.Toolkit.XRControllerRecordingEditor.DrawInspector().
DrawInspector()
override void UnityEditor.XR.Interaction.Toolkit.XRControllerRecordingEditor.DrawInspector () protected
See also
DrawBeforeProperties, DrawProperties, BaseInteractionEditor.DrawDerivedProperties
DrawProperties()
virtual void UnityEditor.XR.Interaction.Toolkit.XRControllerRecordingEditor.DrawProperties () protected virtual
This method is automatically called by DrawInspector to draw the property fields. Override this method to customize the properties shown in the Inspector. This is typically the method overridden when a derived behavior adds additional serialized properties that should be displayed in the Inspector.
Referenced by UnityEditor.XR.Interaction.Toolkit.XRControllerRecordingEditor.DrawInspector().
DrawRecordingFrame()
virtual void UnityEditor.XR.Interaction.Toolkit.XRControllerRecordingEditor.DrawRecordingFrame (XRControllerState frame) protected virtual
Draw the frame stored in the recording.
Parameters
frame The controller frame to draw.
Referenced by UnityEditor.XR.Interaction.Toolkit.XRControllerRecordingEditor.DrawRecordingFrames().
DrawRecordingFrames()
virtual void UnityEditor.XR.Interaction.Toolkit.XRControllerRecordingEditor.DrawRecordingFrames () protected virtual
Draw the frames stored in the recording.
Referenced by UnityEditor.XR.Interaction.Toolkit.XRControllerRecordingEditor.DrawProperties().
OnEnable()
virtual void UnityEditor.XR.Interaction.Toolkit.XRControllerRecordingEditor.OnEnable () protected virtual
This function is called when the object becomes enabled and active.
See also
MonoBehaviour
Member Data Documentation
k_ValueFormat
const string UnityEditor.XR.Interaction.Toolkit.XRControllerRecordingEditor.k_ValueFormat = "0.#" static protected
String format used to display the interaction values.
Referenced by UnityEditor.XR.Interaction.Toolkit.XRControllerRecordingEditor.DrawRecordingFrame().
The documentation for this class was generated from the following file:
C:/Users/Lykos/Desktop/Projects/Capstone/VRGames/Library/PackageCache/com.unity.xr.interaction.toolkit@2.0.2/Editor/Interaction/Controllers/XRControllerRecordingEditor.cs