VRCapstoneGames: UnityEditor.Timeline.TrackEditor Class Reference
UnityEditor.Timeline.TrackEditor Class Reference
Use this class to customize track types in the TimelineEditor.
Public Member Functions
virtual TrackDrawOptions GetTrackOptions (TrackAsset track, UnityEngine.Object binding)
Implement this method to override the default options for drawing a track.
string GetErrorText (TrackAsset track, UnityEngine.Object boundObject, TrackBindingErrors detectErrors)
Gets the error text for the specified track.
Color GetTrackColor (TrackAsset track)
Gets the color information of a track.
System.Type GetBindingType (TrackAsset track)
Gets the binding type for a track.
virtual void OnCreate (TrackAsset track, TrackAsset copiedFrom)
Callback for when a track is created.
virtual void OnTrackChanged (TrackAsset track)
Callback for when a track is changed.
virtual bool IsBindingAssignableFrom (UnityEngine.Object candidate, TrackAsset track)
Override this method to validate if a binding for track can be determined from candidate .
virtual UnityEngine.Object GetBindingFrom (UnityEngine.Object candidate, TrackAsset track)
Override this method to determine which object to bind to track . A binding object should be determined from candidate .
Static Public Attributes
static readonly float DefaultTrackHeight = 30.0f
The default height of a track.
static readonly float MinimumTrackHeight = 10.0f
The minimum unscaled height of a track.
static readonly float MaximumTrackHeight = 256.0f
The maximum height of a track.
Detailed Description
Use this class to customize track types in the TimelineEditor.
Member Function Documentation
GetBindingFrom()
virtual UnityEngine.Object UnityEditor.Timeline.TrackEditor.GetBindingFrom (UnityEngine::Object candidate, TrackAsset track) virtual
Override this method to determine which object to bind to track . A binding object should be determined from candidate .
By default, the TrackBindingType attribute from track will be used to determine the binding.
Parameters
candidate The source object from which a track binding should be determined.
track The track to bind an object to.
Returns
The object to bind to track .
See also
UnityEngine.Timeline.TrackBindingTypeAttribute, UnityEngine.Timeline.TrackAsset
GetBindingType()
System.Type UnityEditor.Timeline.TrackEditor.GetBindingType (TrackAsset track)
Gets the binding type for a track.
Parameters
track The track to retrieve the binding type from.
Returns
Returns the binding type for the specified track. Returns null if the track does not have binding.
Referenced by UnityEditor.Timeline.TrackEditor.GetBindingFrom(), UnityEditor.Timeline.TrackEditor.GetErrorText(), and UnityEditor.Timeline.TrackEditor.IsBindingAssignableFrom().
GetErrorText()
string UnityEditor.Timeline.TrackEditor.GetErrorText (TrackAsset track, UnityEngine::Object boundObject, TrackBindingErrors detectErrors)
Gets the error text for the specified track.
Parameters
track The track to retrieve options for.
boundObject The binding for the track.
detectErrors The errors to check for.
Returns
An error to be displayed on the track, or string.Empty if there is no error.
Referenced by UnityEditor.Timeline.TrackEditor.GetTrackOptions().
GetTrackColor()
Color UnityEditor.Timeline.TrackEditor.GetTrackColor (TrackAsset track)
Gets the color information of a track.
Parameters
track
Returns
Returns the color for the specified track.
Referenced by UnityEditor.Timeline.TrackEditor.GetTrackOptions().
GetTrackOptions()
virtual TrackDrawOptions UnityEditor.Timeline.TrackEditor.GetTrackOptions (TrackAsset track, UnityEngine::Object binding) virtual
Implement this method to override the default options for drawing a track.
Parameters
track The track from which track options are retrieved.
binding The binding for the track.
Returns
The options for drawing the track.
IsBindingAssignableFrom()
virtual bool UnityEditor.Timeline.TrackEditor.IsBindingAssignableFrom (UnityEngine::Object candidate, TrackAsset track) virtual
Override this method to validate if a binding for track can be determined from candidate .
The default implementation of this method will return true if
candidate is not null or,
candidate is not part of a Prefab Asset or,
candidate is a Component that can be bound to track
Parameters
candidate
track TBD
Returns
True if a binding can be determined from candidate .
See also
UnityEngine.Timeline.TrackBindingTypeAttribute, UnityEngine.Timeline.TrackAsset
OnCreate()
virtual void UnityEditor.Timeline.TrackEditor.OnCreate (TrackAsset track, TrackAsset copiedFrom) virtual
Callback for when a track is created.
Parameters
track The track that is created.
copiedFrom The source that the track is copied from. This can be set to null if the track is not a copy.
Reimplemented in UnityEditor.Timeline.ActivationTrackEditor.
OnTrackChanged()
virtual void UnityEditor.Timeline.TrackEditor.OnTrackChanged (TrackAsset track) virtual
Callback for when a track is changed.
Parameters
track The track that is changed.
Member Data Documentation
DefaultTrackHeight
readonly float UnityEditor.Timeline.TrackEditor.DefaultTrackHeight = 30.0f static
The default height of a track.
Referenced by UnityEditor.Timeline.TimelineGroupGUI.GetHeight(), UnityEditor.Timeline.TimelineTreeView.GetSizeOfRow(), and UnityEditor.Timeline.TrackEditor.GetTrackOptions().
MaximumTrackHeight
readonly float UnityEditor.Timeline.TrackEditor.MaximumTrackHeight = 256.0f static
The maximum height of a track.
MinimumTrackHeight
readonly float UnityEditor.Timeline.TrackEditor.MinimumTrackHeight = 10.0f static
The minimum unscaled height of a track.
The documentation for this class was generated from the following file:
C:/Users/Lykos/Desktop/Projects/Capstone/VRGames/Library/PackageCache/com.unity.timeline@1.6.4/Editor/CustomEditors/TrackEditor.cs