VRCapstoneGames: Oculus.Interaction.RayInteractable Class Reference
Oculus.Interaction.RayInteractable Class Reference
Public Member Functions
bool Raycast (Ray ray, out SurfaceHit hit, in float maxDistance, in bool useSurface)
void InjectAllRayInteractable (Collider collider)
void InjectCollider (Collider collider)
void InjectOptionalSurface (IPointableSurface surface)
Public Member Functions inherited from Oculus.Interaction.Interactable< RayInteractor, RayInteractable >
void AddInteractor (TInteractor interactor)
void RemoveInteractor (TInteractor interactor)
void AddSelectingInteractor (TInteractor interactor)
void RemoveSelectingInteractor (TInteractor interactor)
bool CanBeSelectedBy (TInteractor interactor)
bool HasInteractor (TInteractor interactor)
bool HasSelectingInteractor (TInteractor interactor)
void Enable ()
void Disable ()
void RemoveInteractorById (int id)
Protected Member Functions
virtual void Awake ()
virtual void Start ()
override void OnEnable ()
override void OnDisable ()
virtual void OnDestroy ()
Protected Member Functions inherited from Oculus.Interaction.Interactable< RayInteractor, RayInteractable >
virtual void InteractorAdded (TInteractor interactor)
virtual void InteractorRemoved (TInteractor interactor)
virtual void SelectingInteractorAdded (TInteractor interactor)
virtual void SelectingInteractorRemoved (TInteractor interactor)
virtual void SetRegistry (IInteractableRegistry< TInteractor, TInteractable > registry)
Protected Attributes
bool _started = false
Properties
Collider Collider [get]
Properties inherited from Oculus.Interaction.Interactable< RayInteractor, RayInteractable >
int MaxInteractors [get, set]
int MaxSelectingInteractors [get, set]
MAction< TInteractor > WhenInteractorAdded [get]
MAction< TInteractor > WhenInteractorRemoved [get]
MAction< TInteractor > WhenSelectingInteractorAdded [get]
MAction< TInteractor > WhenSelectingInteractorRemoved [get]
InteractableState State [get]
static IInteractableRegistry< TInteractor, TInteractable > Registry [get]
int InteractorsCount [get]
int SelectingInteractorsCount [get]
IEnumerable< TInteractor > Interactors [get]
IEnumerable< TInteractor > SelectingInteractors [get]
Events
Action< PointerArgs > OnPointerEvent = delegate { }
Events inherited from Oculus.Interaction.Interactable< RayInteractor, RayInteractable >
Action WhenInteractorsCountUpdated
Action WhenSelectingInteractorsCountUpdated
Action< InteractableStateChangeArgs > WhenStateChanged
Events inherited from Oculus.Interaction.IPointable
Action< PointerArgs > OnPointerEvent
Member Function Documentation
Awake()
virtual void Oculus.Interaction.RayInteractable.Awake () protected virtual
InjectAllRayInteractable()
void Oculus.Interaction.RayInteractable.InjectAllRayInteractable (Collider collider)
InjectCollider()
void Oculus.Interaction.RayInteractable.InjectCollider (Collider collider)
Referenced by Oculus.Interaction.RayInteractable.InjectAllRayInteractable().
InjectOptionalSurface()
void Oculus.Interaction.RayInteractable.InjectOptionalSurface (IPointableSurface surface)
OnDestroy()
virtual void Oculus.Interaction.RayInteractable.OnDestroy () protected virtual
OnDisable()
override void Oculus.Interaction.RayInteractable.OnDisable () protected virtual
Reimplemented from Oculus.Interaction.Interactable< RayInteractor, RayInteractable >.
OnEnable()
override void Oculus.Interaction.RayInteractable.OnEnable () protected virtual
Reimplemented from Oculus.Interaction.Interactable< RayInteractor, RayInteractable >.
Raycast()
bool Oculus.Interaction.RayInteractable.Raycast (Ray ray, out SurfaceHit hit, in float maxDistance, in bool useSurface)
Referenced by Oculus.Interaction.RayInteractor.ComputeCandidate(), and Oculus.Interaction.RayInteractor.DoSelectUpdate().
Start()
virtual void Oculus.Interaction.RayInteractable.Start () protected virtual
Member Data Documentation
_started
bool Oculus.Interaction.RayInteractable._started = false protected
Referenced by Oculus.Interaction.RayInteractable.OnDisable(), Oculus.Interaction.RayInteractable.OnEnable(), and Oculus.Interaction.RayInteractable.Start().
Property Documentation
Collider
Collider Oculus.Interaction.RayInteractable.Collider get
Referenced by Oculus.Interaction.RayInteractable.Raycast().
Event Documentation
OnPointerEvent
Action<PointerArgs> Oculus.Interaction.RayInteractable.OnPointerEvent = delegate { }
The documentation for this class was generated from the following file:
C:/Users/Lykos/Desktop/Projects/Capstone/VRGames/Assets/ThirdParty/Oculus/Interaction/Runtime/Scripts/Interaction/Models/Ray/RayInteractable.cs