VRCapstoneGames: Oculus.Interaction.HandPosing.Visuals.HandGhost Class Reference
Oculus.Interaction.HandPosing.Visuals.HandGhost Class Reference
A static (non-user controlled) representation of a hand. This script is used to be able to manually visualize hand grab poses.
Public Member Functions
void SetPose (HandGrabPoint handGrabPoint)
Relay to the Puppet to set the ghost hand to the desired static pose.
void SetGripPose (Pose gripPose, Transform relativeTo)
Moves the underlying puppet so the grip point aligns with the given parameters.
void InjectHandPuppet (HandPuppet puppet)
void InjectGripPoint (Transform gripPoint)
void InjectOptionalHandGrabPoint (HandGrabPoint handGrabPoint)
void InjectAllHandGhost (HandPuppet puppet, Transform gripPoint)
Protected Member Functions
virtual void Reset ()
virtual void OnValidate ()
virtual void Start ()
Detailed Description
A static (non-user controlled) representation of a hand. This script is used to be able to manually visualize hand grab poses.
Member Function Documentation
InjectAllHandGhost()
void Oculus.Interaction.HandPosing.Visuals.HandGhost.InjectAllHandGhost (HandPuppet puppet, Transform gripPoint)
InjectGripPoint()
void Oculus.Interaction.HandPosing.Visuals.HandGhost.InjectGripPoint (Transform gripPoint)
Referenced by Oculus.Interaction.HandPosing.Visuals.HandGhost.InjectAllHandGhost().
InjectHandPuppet()
void Oculus.Interaction.HandPosing.Visuals.HandGhost.InjectHandPuppet (HandPuppet puppet)
Referenced by Oculus.Interaction.HandPosing.Visuals.HandGhost.InjectAllHandGhost().
InjectOptionalHandGrabPoint()
void Oculus.Interaction.HandPosing.Visuals.HandGhost.InjectOptionalHandGrabPoint (HandGrabPoint handGrabPoint)
OnValidate()
virtual void Oculus.Interaction.HandPosing.Visuals.HandGhost.OnValidate () protected virtual
Reset()
virtual void Oculus.Interaction.HandPosing.Visuals.HandGhost.Reset () protected virtual
SetGripPose()
void Oculus.Interaction.HandPosing.Visuals.HandGhost.SetGripPose (Pose gripPose, Transform relativeTo)
Moves the underlying puppet so the grip point aligns with the given parameters.
Parameters
gripPose The relative grip pose to align the hand to
relativeTo The object to use as anchor
Referenced by Oculus.Interaction.HandPosing.Visuals.HandGhost.SetPose().
SetPose()
void Oculus.Interaction.HandPosing.Visuals.HandGhost.SetPose (HandGrabPoint handGrabPoint)
Relay to the Puppet to set the ghost hand to the desired static pose.
Parameters
handGrabPoint The point to read the HandPose from
Referenced by Oculus.Interaction.HandPosing.Visuals.HandGhost.OnValidate().
Start()
virtual void Oculus.Interaction.HandPosing.Visuals.HandGhost.Start () protected virtual
The documentation for this class was generated from the following file:
C:/Users/Lykos/Desktop/Projects/Capstone/VRGames/Assets/ThirdParty/Oculus/Interaction/Runtime/Scripts/HandPosing/Visuals/HandGhost.cs