VRCapstoneGames: TimelineProjectSettings Class Reference
TimelineProjectSettings Class Reference
Store the settings for Timeline that will be stored with the Unity Project.
Public Member Functions
void Save ()
Save the timeline project settings file in the project directory.
Public Attributes
float assetDefaultFramerate = (float)TimelineAsset.EditorSettings.kDefaultFrameRate
Define the default framerate when a Timeline asset is created.
Properties
double defaultFrameRate [get, set]
Defines the default frame rate when a Timeline asset is created from the project window.
Detailed Description
Store the settings for Timeline that will be stored with the Unity Project.
Member Function Documentation
Save()
void TimelineProjectSettings.Save ()
Save the timeline project settings file in the project directory.
Referenced by TimelineProjectSettingsProvider.OnActivate(), TimelineProjectSettingsProvider.OnGUI(), and Save().
Member Data Documentation
assetDefaultFramerate
float TimelineProjectSettings.assetDefaultFramerate = (float)TimelineAsset.EditorSettings.kDefaultFrameRate
Define the default framerate when a Timeline asset is created.
Property Documentation
defaultFrameRate
double TimelineProjectSettings.defaultFrameRate get set
Defines the default frame rate when a Timeline asset is created from the project window.
The documentation for this class was generated from the following file:
C:/Users/Lykos/Desktop/Projects/Capstone/VRGames/Library/PackageCache/com.unity.timeline@1.6.4/Editor/inspectors/TimelineProjectSettings.cs