VRGames: Oculus.Interaction.CenterEyeOffset Class Reference
Oculus.Interaction.CenterEyeOffset Class Reference
Public Member Functions
void GetOffset (ref Pose pose)
void GetWorldPose (ref Pose pose)
void InjectHand (IHand hand)
void InjectOffset (Vector3 offset)
void InjectRotation (Quaternion rotation)
void InjectAllCenterEyeOffset (IHand hand, Vector3 offset, Quaternion rotation)
Protected Member Functions
virtual void Awake ()
virtual void Start ()
virtual void OnEnable ()
virtual void OnDisable ()
Protected Attributes
bool _started = false
Properties
IHand Hand [get]
Member Function Documentation
Awake()
virtual void Oculus.Interaction.CenterEyeOffset.Awake () protected virtual
GetOffset()
void Oculus.Interaction.CenterEyeOffset.GetOffset (ref Pose pose)
GetWorldPose()
void Oculus.Interaction.CenterEyeOffset.GetWorldPose (ref Pose pose)
InjectAllCenterEyeOffset()
void Oculus.Interaction.CenterEyeOffset.InjectAllCenterEyeOffset (IHand hand, Vector3 offset, Quaternion rotation)
InjectHand()
void Oculus.Interaction.CenterEyeOffset.InjectHand (IHand hand)
Referenced by Oculus.Interaction.CenterEyeOffset.InjectAllCenterEyeOffset().
InjectOffset()
void Oculus.Interaction.CenterEyeOffset.InjectOffset (Vector3 offset)
Referenced by Oculus.Interaction.CenterEyeOffset.InjectAllCenterEyeOffset().
InjectRotation()
void Oculus.Interaction.CenterEyeOffset.InjectRotation (Quaternion rotation)
Referenced by Oculus.Interaction.CenterEyeOffset.InjectAllCenterEyeOffset().
OnDisable()
virtual void Oculus.Interaction.CenterEyeOffset.OnDisable () protected virtual
OnEnable()
virtual void Oculus.Interaction.CenterEyeOffset.OnEnable () protected virtual
Start()
virtual void Oculus.Interaction.CenterEyeOffset.Start () protected virtual
Member Data Documentation
_started
bool Oculus.Interaction.CenterEyeOffset._started = false protected
Referenced by Oculus.Interaction.CenterEyeOffset.OnDisable(), Oculus.Interaction.CenterEyeOffset.OnEnable(), and Oculus.Interaction.CenterEyeOffset.Start().
Property Documentation
Hand
IHand Oculus.Interaction.CenterEyeOffset.Hand get
The documentation for this class was generated from the following file:
C:/Users/Lykos/Desktop/Projects/Capstone/VRGames/Assets/ThirdParty/Oculus/Interaction/Runtime/Scripts/Selection/Hands/CenterEyeOffset.cs