VRCapstoneGames: Oculus.Interaction.PoseDetection.TransformRecognizerActiveState Class Reference
Oculus.Interaction.PoseDetection.TransformRecognizerActiveState Class Reference
Public Member Functions
void GetFeatureVectorAndWristPos (TransformFeature feature, bool isHandVector, ref Vector3? featureVec, ref Vector3? wristPos)
void InjectAllTransformRecognizerActiveState (IHand hand, TransformFeatureConfigList transformFeatureList, TransformConfig transformConfig)
void InjectHand (IHand hand)
void InjectTransformFeatureList (TransformFeatureConfigList transformFeatureList)
void InjectTransformConfig (TransformConfig transformConfig)
Protected Member Functions
virtual void Awake ()
virtual void Start ()
virtual void OnEnable ()
virtual void OnDisable ()
Protected Attributes
bool _started = false
Properties
IHand Hand [get]
IReadOnlyList< TransformFeatureConfig > FeatureConfigs [get]
TransformConfig TransformConfig [get]
bool Active [get]
Properties inherited from Oculus.Interaction.IActiveState
Member Function Documentation
Awake()
virtual void Oculus.Interaction.PoseDetection.TransformRecognizerActiveState.Awake () protected virtual
GetFeatureVectorAndWristPos()
void Oculus.Interaction.PoseDetection.TransformRecognizerActiveState.GetFeatureVectorAndWristPos (TransformFeature feature, bool isHandVector, ref Vector3? featureVec, ref Vector3? wristPos)
Referenced by Oculus.Interaction.PoseDetection.Debug.TransformFeatureVectorDebugParentVisual.GetTransformFeatureVectorAndWristPos().
InjectAllTransformRecognizerActiveState()
void Oculus.Interaction.PoseDetection.TransformRecognizerActiveState.InjectAllTransformRecognizerActiveState (IHand hand, TransformFeatureConfigList transformFeatureList, TransformConfig transformConfig)
InjectHand()
void Oculus.Interaction.PoseDetection.TransformRecognizerActiveState.InjectHand (IHand hand)
Referenced by Oculus.Interaction.PoseDetection.TransformRecognizerActiveState.InjectAllTransformRecognizerActiveState().
InjectTransformConfig()
void Oculus.Interaction.PoseDetection.TransformRecognizerActiveState.InjectTransformConfig (TransformConfig transformConfig)
Referenced by Oculus.Interaction.PoseDetection.TransformRecognizerActiveState.InjectAllTransformRecognizerActiveState().
InjectTransformFeatureList()
void Oculus.Interaction.PoseDetection.TransformRecognizerActiveState.InjectTransformFeatureList (TransformFeatureConfigList transformFeatureList)
Referenced by Oculus.Interaction.PoseDetection.TransformRecognizerActiveState.InjectAllTransformRecognizerActiveState().
OnDisable()
virtual void Oculus.Interaction.PoseDetection.TransformRecognizerActiveState.OnDisable () protected virtual
OnEnable()
virtual void Oculus.Interaction.PoseDetection.TransformRecognizerActiveState.OnEnable () protected virtual
Start()
virtual void Oculus.Interaction.PoseDetection.TransformRecognizerActiveState.Start () protected virtual
Member Data Documentation
_started
bool Oculus.Interaction.PoseDetection.TransformRecognizerActiveState._started = false protected
Referenced by Oculus.Interaction.PoseDetection.TransformRecognizerActiveState.OnDisable(), Oculus.Interaction.PoseDetection.TransformRecognizerActiveState.OnEnable(), and Oculus.Interaction.PoseDetection.TransformRecognizerActiveState.Start().
Property Documentation
Active
bool Oculus.Interaction.PoseDetection.TransformRecognizerActiveState.Active get
Implements Oculus.Interaction.IActiveState.
FeatureConfigs
IReadOnlyList<TransformFeatureConfig> Oculus.Interaction.PoseDetection.TransformRecognizerActiveState.FeatureConfigs get
Referenced by Oculus.Interaction.PoseDetection.Debug.TransformFeatureVectorDebugParentVisual.Start().
Hand
IHand Oculus.Interaction.PoseDetection.TransformRecognizerActiveState.Hand get
TransformConfig
TransformConfig Oculus.Interaction.PoseDetection.TransformRecognizerActiveState.TransformConfig get
Referenced by Oculus.Interaction.PoseDetection.Debug.TransformFeatureDebugVisual.Update().
The documentation for this class was generated from the following file:
C:/Users/Lykos/Desktop/Projects/Capstone/VRGames/Assets/ThirdParty/Oculus/Interaction/Runtime/Scripts/PoseDetection/TransformRecognizerActiveState.cs