VRCapstoneGames: OVRLipSyncContext Class Reference
OVRLipSyncContext Class Reference
OVRLipSyncContext interfaces into the Oculus phoneme recognizer. This component should be added into the scene once for each Audio Source.
Public Member Functions
void PreprocessAudioSamples (float[] data, int channels)
Preprocess F32 PCM audio buffer.
void PostprocessAudioSamples (float[] data, int channels)
Postprocess F32 PCM audio buffer.
void ProcessAudioSamplesRaw (float[] data, int channels)
Pass F32 PCM audio buffer to the lip sync module.
void ProcessAudioSamplesRaw (short[] data, int channels)
Pass S16 PCM audio buffer to the lip sync module.
void ProcessAudioSamples (float[] data, int channels)
Process F32 audio sample and pass it to the lip sync module for computation.
Public Member Functions inherited from OVRLipSyncContextBase
OVRLipSync.Frame GetCurrentPhonemeFrame ()
Gets the current phoneme frame (lock and copy current frame to caller frame)
void SetVisemeBlend (int viseme, int amount)
Sets a given viseme id blend weight to a given amount.
void SetLaughterBlend (int amount)
Sets a given viseme id blend weight to a given amount.
OVRLipSync.Result ResetContext ()
Resets the context.
Public Attributes
bool enableKeyboardInput = false
bool enableTouchInput = false
bool audioLoopback = false
KeyCode loopbackKey = KeyCode.L
bool showVisemes = false
KeyCode debugVisemesKey = KeyCode.D
bool skipAudioSource = false
float gain = 1.0f
KeyCode debugLaughterKey = KeyCode.H
bool showLaughter = false
float laughterScore = 0.0f
Public Attributes inherited from OVRLipSyncContextBase
AudioSource audioSource = null
OVRLipSync.ContextProviders provider = OVRLipSync.ContextProviders.Enhanced
bool enableAcceleration = true
Additional Inherited Members
Properties inherited from OVRLipSyncContextBase
int Smoothing [get, set]
uint Context [get]
OVRLipSync.Frame Frame [get]
Detailed Description
OVRLipSyncContext interfaces into the Oculus phoneme recognizer. This component should be added into the scene once for each Audio Source.
Member Function Documentation
PostprocessAudioSamples()
void OVRLipSyncContext.PostprocessAudioSamples (float[] data, int channels)
Postprocess F32 PCM audio buffer.
Parameters
data Data.
channels Channels.
Referenced by ProcessAudioSamples().
PreprocessAudioSamples()
void OVRLipSyncContext.PreprocessAudioSamples (float[] data, int channels)
Preprocess F32 PCM audio buffer.
Parameters
data Data.
channels Channels.
Referenced by ProcessAudioSamples().
ProcessAudioSamples()
void OVRLipSyncContext.ProcessAudioSamples (float[] data, int channels)
Process F32 audio sample and pass it to the lip sync module for computation.
Parameters
data Data.
channels Channels.
ProcessAudioSamplesRaw() [1/2]
void OVRLipSyncContext.ProcessAudioSamplesRaw (float[] data, int channels)
Pass F32 PCM audio buffer to the lip sync module.
Parameters
data Data.
channels Channels.
Referenced by ProcessAudioSamples(), OvrAvatar.UpdateVoiceData(), and OvrAvatar.UpdateVoiceData().
ProcessAudioSamplesRaw() [2/2]
void OVRLipSyncContext.ProcessAudioSamplesRaw (short[] data, int channels)
Pass S16 PCM audio buffer to the lip sync module.
Parameters
data Data.
channels Channels.
Member Data Documentation
audioLoopback
bool OVRLipSyncContext.audioLoopback = false
Referenced by PostprocessAudioSamples().
debugLaughterKey
KeyCode OVRLipSyncContext.debugLaughterKey = KeyCode.H
debugVisemesKey
KeyCode OVRLipSyncContext.debugVisemesKey = KeyCode.D
enableKeyboardInput
bool OVRLipSyncContext.enableKeyboardInput = false
enableTouchInput
bool OVRLipSyncContext.enableTouchInput = false
gain
float OVRLipSyncContext.gain = 1.0f
Referenced by PreprocessAudioSamples().
laughterScore
float OVRLipSyncContext.laughterScore = 0.0f
loopbackKey
KeyCode OVRLipSyncContext.loopbackKey = KeyCode.L
showLaughter
bool OVRLipSyncContext.showLaughter = false
showVisemes
bool OVRLipSyncContext.showVisemes = false
skipAudioSource
bool OVRLipSyncContext.skipAudioSource = false
The documentation for this class was generated from the following file:
C:/Users/Lykos/Desktop/Projects/Capstone/VRGames/Assets/ThirdParty/Oculus/LipSync/Scripts/OVRLipSyncContext.cs