VRCapstoneGames: Oculus.Platform.Samples.VrVoiceChat.RoomManager Class Reference
Oculus.Platform.Samples.VrVoiceChat.RoomManager Class Reference
Classes
struct Invite
Public Member Functions
RoomManager ()
bool CheckForLaunchInvite ()
void CreateRoomAndLaunchInviteMenu ()
void UpdateActiveInvitesList ()
void JoinExistingRoom (ulong roomID)
void LeaveCurrentRoom ()
Properties
ulong RemoteUserID [get]
String RemoteOculusID [get]
bool ShouldPollInviteList [get]
Constructor & Destructor Documentation
RoomManager()
Oculus.Platform.Samples.VrVoiceChat.RoomManager.RoomManager ()
Member Function Documentation
CheckForLaunchInvite()
bool Oculus.Platform.Samples.VrVoiceChat.RoomManager.CheckForLaunchInvite ()
CreateRoomAndLaunchInviteMenu()
void Oculus.Platform.Samples.VrVoiceChat.RoomManager.CreateRoomAndLaunchInviteMenu ()
Referenced by Oculus.Platform.Samples.VrVoiceChat.PlatformManager.CallFriendOnClick().
JoinExistingRoom()
void Oculus.Platform.Samples.VrVoiceChat.RoomManager.JoinExistingRoom (ulong roomID)
Referenced by Oculus.Platform.Samples.VrVoiceChat.PlatformManager.AnswerCallOnClick(), and Oculus.Platform.Samples.VrVoiceChat.RoomManager.CheckForLaunchInvite().
LeaveCurrentRoom()
void Oculus.Platform.Samples.VrVoiceChat.RoomManager.LeaveCurrentRoom ()
Referenced by Oculus.Platform.Samples.VrVoiceChat.PlatformManager.HangupOnClick(), and Oculus.Platform.Samples.VrVoiceChat.PlatformManager.TransitionToState().
UpdateActiveInvitesList()
void Oculus.Platform.Samples.VrVoiceChat.RoomManager.UpdateActiveInvitesList ()
Property Documentation
RemoteOculusID
String Oculus.Platform.Samples.VrVoiceChat.RoomManager.RemoteOculusID get
RemoteUserID
ulong Oculus.Platform.Samples.VrVoiceChat.RoomManager.RemoteUserID get
Referenced by Oculus.Platform.Samples.VrVoiceChat.PlatformManager.TransitionToState().
ShouldPollInviteList
bool Oculus.Platform.Samples.VrVoiceChat.RoomManager.ShouldPollInviteList get
The documentation for this class was generated from the following file:
C:/Users/Lykos/Desktop/Projects/Capstone/VRGames/Assets/ThirdParty/Oculus/Platform/Samples/VrVoiceChat/Scripts/RoomManager.cs