VRCapstoneGames: Oculus.Interaction.Editor.EditorConstants Class Reference
Oculus.Interaction.Editor.EditorConstants Class Reference
Static Public Attributes
static readonly Color PRIMARY_COLOR = new Color(0f, 1f, 1f, 0.5f)
static readonly Color PRIMARY_COLOR_DISABLED = new Color(0f, 1f, 1f, 0.1f)
static readonly Color SECONDARY_COLOR = new Color(0.5f, 0.3f, 1f, 0.5f)
static readonly Color SECONDARY_COLOR_DISABLED = new Color(0.5f, 0.3f, 1f, 0.1f)
static readonly float LINE_THICKNESS = 2f
static readonly float ROW_HEIGHT = 20f
Member Data Documentation
LINE_THICKNESS
readonly float Oculus.Interaction.Editor.EditorConstants.LINE_THICKNESS = 2f static
Referenced by Oculus.Interaction.Editor.CircleProximityFieldEditor.OnSceneGUI(), and Oculus.Interaction.Editor.PokeInteractableEditor.OnSceneGUI().
PRIMARY_COLOR
readonly Color Oculus.Interaction.Editor.EditorConstants.PRIMARY_COLOR = new Color(0f, 1f, 1f, 0.5f) static
Referenced by Oculus.Interaction.Editor.BoxProximityFieldEditor.OnSceneGUI(), Oculus.Interaction.Editor.CircleProximityFieldEditor.OnSceneGUI(), Oculus.Interaction.Editor.CylinderProximityFieldEditor.OnSceneGUI(), and Oculus.Interaction.Editor.PokeInteractableEditor.OnSceneGUI().
PRIMARY_COLOR_DISABLED
readonly Color Oculus.Interaction.Editor.EditorConstants.PRIMARY_COLOR_DISABLED = new Color(0f, 1f, 1f, 0.1f) static
ROW_HEIGHT
readonly float Oculus.Interaction.Editor.EditorConstants.ROW_HEIGHT = 20f static
Referenced by Oculus.Interaction.GrabAPI.GrabbingRuleEditor.OnGUI(), and Oculus.Interaction.HandPosing.Editor.HandPoseEditor.OnGUI().
SECONDARY_COLOR
readonly Color Oculus.Interaction.Editor.EditorConstants.SECONDARY_COLOR = new Color(0.5f, 0.3f, 1f, 0.5f) static
SECONDARY_COLOR_DISABLED
readonly Color Oculus.Interaction.Editor.EditorConstants.SECONDARY_COLOR_DISABLED = new Color(0.5f, 0.3f, 1f, 0.1f) static
The documentation for this class was generated from the following file:
C:/Users/Lykos/Desktop/Projects/Capstone/VRGames/Assets/ThirdParty/Oculus/Interaction/Editor/Utils/EditorConstants.cs