VRCapstoneGames: Oculus.Interaction.Input.DataSource< TData > Class Template Reference
Oculus.Interaction.Input.DataSource< TData > Class Template Reference abstract
Public Member Functions
TData GetData ()
virtual void MarkInputDataRequiresUpdate ()
Marks the DataAsset stored as outdated, which means it will be re-processed JIT during the next call to GetData.
void InjectAllDataSource (UpdateModeFlags updateMode, IDataSource updateAfter)
void InjectUpdateMode (UpdateModeFlags updateMode)
void InjectUpdateAfter (IDataSource updateAfter)
Protected Member Functions
virtual void Start ()
virtual void OnEnable ()
virtual void OnDisable ()
virtual void Update ()
virtual void FixedUpdate ()
virtual void LateUpdate ()
void ResetUpdateAfter (IDataSource updateAfter, UpdateModeFlags updateMode)
bool RequiresUpdate ()
void UpdateData ()
Protected Attributes
bool _started = false
Properties
bool Started [get]
UpdateModeFlags UpdateMode [get]
bool UpdateModeAfterPrevious [get]
virtual int CurrentDataVersion [get]
TData DataAsset [get]
Returns the current DataAsset, without performing any updates.
Properties inherited from Oculus.Interaction.Input.IDataSource< TData >
Events
Action InputDataAvailable = delegate { }
Events inherited from Oculus.Interaction.Input.IDataSource< TData >
Action InputDataAvailable
Member Function Documentation
FixedUpdate()
virtual void Oculus.Interaction.Input.DataSource< TData >.FixedUpdate () protected virtual
GetData()
TData Oculus.Interaction.Input.DataSource< TData >.GetData ()
Implements Oculus.Interaction.Input.IDataSource< TData >.
InjectAllDataSource()
void Oculus.Interaction.Input.DataSource< TData >.InjectAllDataSource (UpdateModeFlags updateMode, IDataSource< TData > updateAfter)
InjectUpdateAfter()
void Oculus.Interaction.Input.DataSource< TData >.InjectUpdateAfter (IDataSource< TData > updateAfter)
Referenced by Oculus.Interaction.Input.DataSource< TData >.InjectAllDataSource().
InjectUpdateMode()
void Oculus.Interaction.Input.DataSource< TData >.InjectUpdateMode (UpdateModeFlags updateMode)
Referenced by Oculus.Interaction.Input.DataSource< TData >.InjectAllDataSource().
LateUpdate()
virtual void Oculus.Interaction.Input.DataSource< TData >.LateUpdate () protected virtual
MarkInputDataRequiresUpdate()
virtual void Oculus.Interaction.Input.DataSource< TData >.MarkInputDataRequiresUpdate () virtual
Marks the DataAsset stored as outdated, which means it will be re-processed JIT during the next call to GetData.
Implements Oculus.Interaction.Input.IDataSource< TData >.
Referenced by Oculus.Interaction.Input.DataSource< TData >.FixedUpdate(), Oculus.Interaction.Input.DataSource< TData >.LateUpdate(), Oculus.Interaction.Input.DataSource< TData >.OnDisable(), Oculus.Interaction.Input.DataSource< TData >.OnEnable(), and Oculus.Interaction.Input.DataSource< TData >.Update().
OnDisable()
virtual void Oculus.Interaction.Input.DataSource< TData >.OnDisable () protected virtual
Referenced by Oculus.Interaction.Input.DataSource< TData >.ResetUpdateAfter().
OnEnable()
virtual void Oculus.Interaction.Input.DataSource< TData >.OnEnable () protected virtual
Referenced by Oculus.Interaction.Input.DataSource< TData >.ResetUpdateAfter().
RequiresUpdate()
bool Oculus.Interaction.Input.DataSource< TData >.RequiresUpdate () protected
Referenced by Oculus.Interaction.Input.DataSource< TData >.GetData().
ResetUpdateAfter()
void Oculus.Interaction.Input.DataSource< TData >.ResetUpdateAfter (IDataSource< TData > updateAfter, UpdateModeFlags updateMode) protected
Start()
virtual void Oculus.Interaction.Input.DataSource< TData >.Start () protected virtual
Reimplemented in Oculus.Interaction.Input.DataModifier< TData >, Oculus.Interaction.Input.FromOVRControllerDataSource, Oculus.Interaction.Input.FromOVRControllerHandDataSource, Oculus.Interaction.Input.FromOVRHandDataSource, and Oculus.Interaction.Input.FromOVRHmdDataSource.
Update()
virtual void Oculus.Interaction.Input.DataSource< TData >.Update () protected virtual
UpdateData()
void Oculus.Interaction.Input.DataSource< TData >.UpdateData () abstract protected
Referenced by Oculus.Interaction.Input.DataSource< TData >.GetData().
Member Data Documentation
_started
bool Oculus.Interaction.Input.DataSource< TData >._started = false protected
Referenced by Oculus.Interaction.Input.DataSource< TData >.OnDisable(), Oculus.Interaction.Input.DataSource< TData >.OnEnable(), and Oculus.Interaction.Input.DataSource< TData >.Start().
Property Documentation
CurrentDataVersion
virtual int Oculus.Interaction.Input.DataSource< TData >.CurrentDataVersion get
Implements Oculus.Interaction.Input.IDataSource< TData >.
DataAsset
TData Oculus.Interaction.Input.DataSource< TData >.DataAsset get abstract protected
Returns the current DataAsset, without performing any updates.
Returns
Null if no call to GetData has been made since this data source was initialized.
Referenced by Oculus.Interaction.Input.DataSource< TData >.GetData().
Started
bool Oculus.Interaction.Input.DataSource< TData >.Started get
Referenced by Oculus.Interaction.Input.DataSource< TData >.OnEnable(), and Oculus.Interaction.Input.DataSource< TData >.Start().
UpdateMode
UpdateModeFlags Oculus.Interaction.Input.DataSource< TData >.UpdateMode get
UpdateModeAfterPrevious
bool Oculus.Interaction.Input.DataSource< TData >.UpdateModeAfterPrevious get protected
Referenced by Oculus.Interaction.Input.DataSource< TData >.OnEnable().
Event Documentation
InputDataAvailable
Action Oculus.Interaction.Input.DataSource< TData >.InputDataAvailable = delegate { }
Referenced by Oculus.Interaction.Input.DataSource< TData >.MarkInputDataRequiresUpdate().
The documentation for this class was generated from the following file:
C:/Users/Lykos/Desktop/Projects/Capstone/VRGames/Assets/ThirdParty/Oculus/Interaction/Runtime/Scripts/Input/DataSource.cs