VRCapstoneGames: OVRRaycaster Class Reference
OVRRaycaster Class Reference
Extension of GraphicRaycaster to support ray casting with world space rays instead of just screen-space pointer positions.
Public Member Functions
override void Raycast (PointerEventData eventData, List< RaycastResult > resultAppendList)
Performs a raycast using eventData.worldSpaceRay.
void RaycastPointer (PointerEventData eventData, List< RaycastResult > resultAppendList)
Performs a raycast using the pointer object attached to this OVRRaycaster.
Vector2 GetScreenPosition (RaycastResult raycastResult)
Get screen position of worldPosition contained in this RaycastResult.
bool IsFocussed ()
Is this the currently focussed Raycaster according to the InputModule.
void OnPointerEnter (PointerEventData e)
Use this callback to detect pointer enter events.
Public Member Functions inherited from UnityEngine.UI.GraphicRaycaster
override void Raycast (PointerEventData eventData, List< RaycastResult > resultAppendList)
Perform the raycast against the list of graphics associated with the Canvas.
Public Member Functions inherited from UnityEngine.EventSystems.BaseRaycaster
void Raycast (PointerEventData eventData, List< RaycastResult > resultAppendList)
Raycast against the scene.
override string ToString ()
Public Member Functions inherited from UnityEngine.EventSystems.UIBehaviour
virtual bool IsActive ()
Returns true if the GameObject and the Component are active.
bool IsDestroyed ()
Returns true if the native representation of the behaviour has been destroyed.
Public Attributes
GameObject pointer
int sortOrder = 0
Protected Member Functions
OVRRaycaster ()
override void Start ()
Protected Member Functions inherited from UnityEngine.UI.GraphicRaycaster
GraphicRaycaster ()
Protected Member Functions inherited from UnityEngine.EventSystems.BaseRaycaster
override void OnEnable ()
override void OnDisable ()
override void OnCanvasHierarchyChanged ()
Called when the state of the parent Canvas is changed.
override void OnTransformParentChanged ()
Protected Member Functions inherited from UnityEngine.EventSystems.UIBehaviour
virtual void Awake ()
virtual void OnDestroy ()
virtual void OnRectTransformDimensionsChange ()
This callback is called when the dimensions of an associated RectTransform change. It is always called before Awake, OnEnable, or Start. The call is also made to all child RectTransforms, regardless of whether their dimensions change (which depends on how they are anchored).
virtual void OnBeforeTransformParentChanged ()
virtual void OnDidApplyAnimationProperties ()
virtual void OnCanvasGroupChanged ()
Properties
override Camera eventCamera [get]
override int sortOrderPriority [get]
Properties inherited from UnityEngine.UI.GraphicRaycaster
override int sortOrderPriority [get]
Priority of the raycaster based upon sort order.
override int renderOrderPriority [get]
Priority of the raycaster based upon render order.
bool ignoreReversedGraphics [get, set]
Whether Graphics facing away from the raycaster are checked for raycasts.
BlockingObjects blockingObjects [get, set]
The type of objects that are checked to determine if they block graphic raycasts.
LayerMask blockingMask [get, set]
The type of objects specified through LayerMask that are checked to determine if they block graphic raycasts.
override Camera eventCamera [get]
The camera that will generate rays for this raycaster.
Properties inherited from UnityEngine.EventSystems.BaseRaycaster
Camera eventCamera [get]
The camera that will generate rays for this raycaster.
virtual int priority [get]
virtual int sortOrderPriority [get]
Priority of the raycaster based upon sort order.
virtual int renderOrderPriority [get]
Priority of the raycaster based upon render order.
BaseRaycaster rootRaycaster [get]
Raycaster on root canvas.
Additional Inherited Members
Public Types inherited from UnityEngine.UI.GraphicRaycaster
enum BlockingObjects { None = 0 , TwoD = 1 , ThreeD = 2 , All = 3 }
Type of raycasters to check against to check for canvas blocking elements.
Protected Attributes inherited from UnityEngine.UI.GraphicRaycaster
LayerMask m_BlockingMask = kNoEventMaskSet
Static Protected Attributes inherited from UnityEngine.UI.GraphicRaycaster
const int kNoEventMaskSet = -1
Detailed Description
Extension of GraphicRaycaster to support ray casting with world space rays instead of just screen-space pointer positions.
Constructor & Destructor Documentation
OVRRaycaster()
OVRRaycaster.OVRRaycaster () protected
Member Function Documentation
GetScreenPosition()
Vector2 OVRRaycaster.GetScreenPosition (RaycastResult raycastResult)
Get screen position of worldPosition contained in this RaycastResult.
Parameters
worldPosition
Returns
Referenced by UnityEngine.EventSystems.OVRInputModule.GetCanvasPointerData(), and UnityEngine.EventSystems.OVRInputModule.GetGazePointerData().
IsFocussed()
bool OVRRaycaster.IsFocussed ()
Is this the currently focussed Raycaster according to the InputModule.
Returns
OnPointerEnter()
void OVRRaycaster.OnPointerEnter (PointerEventData eventData)
Use this callback to detect pointer enter events.
Implements UnityEngine.EventSystems.IPointerEnterHandler.
Raycast()
override void OVRRaycaster.Raycast (PointerEventData eventData, List< RaycastResult > resultAppendList)
Performs a raycast using eventData.worldSpaceRay.
Parameters
eventData
resultAppendList
RaycastPointer()
void OVRRaycaster.RaycastPointer (PointerEventData eventData, List< RaycastResult > resultAppendList)
Performs a raycast using the pointer object attached to this OVRRaycaster.
Parameters
eventData
resultAppendList
Referenced by UnityEngine.EventSystems.OVRInputModule.GetCanvasPointerData().
Start()
override void OVRRaycaster.Start () protected virtual
Reimplemented from UnityEngine.EventSystems.UIBehaviour.
Member Data Documentation
pointer
GameObject OVRRaycaster.pointer
Referenced by RaycastPointer().
sortOrder
int OVRRaycaster.sortOrder = 0
Property Documentation
eventCamera
override Camera OVRRaycaster.eventCamera get
Referenced by GetScreenPosition(), and RaycastPointer().
sortOrderPriority
override int OVRRaycaster.sortOrderPriority get
The documentation for this class was generated from the following file:
C:/Users/Lykos/Desktop/Projects/Capstone/VRGames/Assets/ThirdParty/Oculus/VR/Scripts/Util/OVRRaycaster.cs