VRCapstoneGames: Facebook.WitAi.Windows.WitPropertyDrawer Class Reference
Facebook.WitAi.Windows.WitPropertyDrawer Class Reference abstract
Public Member Functions
override float GetPropertyHeight (SerializedProperty property, GUIContent label)
override void OnGUI (Rect position, SerializedProperty property, GUIContent label)
Static Public Attributes
const string LocalizedTitleKey = "title"
const string LocalizedMissingKey = "missing"
Protected Member Functions
virtual void OnGUIPreFields (Rect position, SerializedProperty property, GUIContent label)
virtual void LayoutField (int index, SerializedProperty property, FieldInfo subfield, WitPropertyEditType editType)
virtual void LayoutPropertyField (FieldInfo subfield, SerializedProperty subfieldProperty, GUIContent labelContent, bool canEdit)
virtual void OnGUIPostFields (Rect position, SerializedProperty property, GUIContent label)
virtual string GetLocalizedText (SerializedProperty property, string key)
virtual bool ShouldLayoutField (SerializedProperty property, FieldInfo subfield)
virtual string GetDefaultFieldValue (SerializedProperty property, FieldInfo subfield)
virtual string GetFieldStringValue (SerializedProperty property, string fieldName)
virtual string GetFieldStringValue (SerializedProperty subfieldProperty)
virtual void SetFieldStringValue (SerializedProperty subfieldProperty, string newFieldValue)
Properties
virtual bool FoldoutEnabled [get]
virtual WitPropertyEditType EditType [get]
Member Function Documentation
GetDefaultFieldValue()
virtual string Facebook.WitAi.Windows.WitPropertyDrawer.GetDefaultFieldValue (SerializedProperty property, FieldInfo subfield) protected virtual
Reimplemented in Facebook.WitAi.Windows.WitEndpointConfigDrawer.
Referenced by Facebook.WitAi.Windows.WitPropertyDrawer.LayoutField().
GetFieldStringValue() [1/2]
virtual string Facebook.WitAi.Windows.WitPropertyDrawer.GetFieldStringValue (SerializedProperty property, string fieldName) protected virtual
Referenced by Facebook.WitAi.Windows.WitPropertyDrawer.GetFieldStringValue(), Facebook.WitAi.Windows.WitEntityPropertyDrawer.GetLocalizedText(), Facebook.WitAi.Windows.WitIntentPropertyDrawer.GetLocalizedText(), Facebook.WitAi.Windows.WitTraitPropertyDrawer.GetLocalizedText(), and Oculus.Voice.Windows.VoiceApplicationDetailProvider.ShouldLayoutField().
GetFieldStringValue() [2/2]
virtual string Facebook.WitAi.Windows.WitPropertyDrawer.GetFieldStringValue (SerializedProperty subfieldProperty) protected virtual
GetLocalizedText()
virtual string Facebook.WitAi.Windows.WitPropertyDrawer.GetLocalizedText (SerializedProperty property, string key) protected virtual
Reimplemented in Facebook.WitAi.Windows.WitEndpointConfigDrawer, Facebook.WitAi.Windows.WitApplicationPropertyDrawer, Facebook.WitAi.Windows.WitEntityPropertyDrawer, Facebook.WitAi.Windows.WitIntentPropertyDrawer, and Facebook.WitAi.Windows.WitTraitPropertyDrawer.
Referenced by Facebook.WitAi.Windows.WitPropertyDrawer.LayoutField(), and Facebook.WitAi.Windows.WitPropertyDrawer.OnGUI().
GetPropertyHeight()
override float Facebook.WitAi.Windows.WitPropertyDrawer.GetPropertyHeight (SerializedProperty property, GUIContent label)
LayoutField()
virtual void Facebook.WitAi.Windows.WitPropertyDrawer.LayoutField (int index, SerializedProperty property, FieldInfo subfield, WitPropertyEditType editType) protected virtual
Referenced by Facebook.WitAi.Windows.WitPropertyDrawer.OnGUI().
LayoutPropertyField()
virtual void Facebook.WitAi.Windows.WitPropertyDrawer.LayoutPropertyField (FieldInfo subfield, SerializedProperty subfieldProperty, GUIContent labelContent, bool canEdit) protected virtual
Reimplemented in Facebook.WitAi.Windows.WitIntentPropertyDrawer.
Referenced by Facebook.WitAi.Windows.WitPropertyDrawer.LayoutField().
OnGUI()
override void Facebook.WitAi.Windows.WitPropertyDrawer.OnGUI (Rect position, SerializedProperty property, GUIContent label)
OnGUIPostFields()
virtual void Facebook.WitAi.Windows.WitPropertyDrawer.OnGUIPostFields (Rect position, SerializedProperty property, GUIContent label) protected virtual
Referenced by Facebook.WitAi.Windows.WitPropertyDrawer.OnGUI().
OnGUIPreFields()
virtual void Facebook.WitAi.Windows.WitPropertyDrawer.OnGUIPreFields (Rect position, SerializedProperty property, GUIContent label) protected virtual
Referenced by Facebook.WitAi.Windows.WitPropertyDrawer.OnGUI().
SetFieldStringValue()
virtual void Facebook.WitAi.Windows.WitPropertyDrawer.SetFieldStringValue (SerializedProperty subfieldProperty, string newFieldValue) protected virtual
Referenced by Facebook.WitAi.Windows.WitPropertyDrawer.LayoutField().
ShouldLayoutField()
virtual bool Facebook.WitAi.Windows.WitPropertyDrawer.ShouldLayoutField (SerializedProperty property, FieldInfo subfield) protected virtual
Reimplemented in Facebook.WitAi.Windows.WitEndpointConfigDrawer, Facebook.WitAi.Windows.WitApplicationPropertyDrawer, Facebook.WitAi.Windows.WitEntityPropertyDrawer, Facebook.WitAi.Windows.WitIntentPropertyDrawer, Facebook.WitAi.Windows.WitTraitPropertyDrawer, and Oculus.Voice.Windows.VoiceApplicationDetailProvider.
Referenced by Facebook.WitAi.Windows.WitPropertyDrawer.OnGUI().
Member Data Documentation
LocalizedMissingKey
const string Facebook.WitAi.Windows.WitPropertyDrawer.LocalizedMissingKey = "missing" static
Referenced by Facebook.WitAi.Windows.WitApplicationPropertyDrawer.GetLocalizedText(), and Facebook.WitAi.Windows.WitPropertyDrawer.OnGUI().
LocalizedTitleKey
const string Facebook.WitAi.Windows.WitPropertyDrawer.LocalizedTitleKey = "title" static
Referenced by Facebook.WitAi.Windows.WitEndpointConfigDrawer.GetLocalizedText(), Facebook.WitAi.Windows.WitApplicationPropertyDrawer.GetLocalizedText(), Facebook.WitAi.Windows.WitEntityPropertyDrawer.GetLocalizedText(), Facebook.WitAi.Windows.WitIntentPropertyDrawer.GetLocalizedText(), Facebook.WitAi.Windows.WitTraitPropertyDrawer.GetLocalizedText(), and Facebook.WitAi.Windows.WitPropertyDrawer.OnGUI().
Property Documentation
EditType
virtual WitPropertyEditType Facebook.WitAi.Windows.WitPropertyDrawer.EditType get protected
Referenced by Facebook.WitAi.Windows.WitPropertyDrawer.OnGUI().
FoldoutEnabled
virtual bool Facebook.WitAi.Windows.WitPropertyDrawer.FoldoutEnabled get protected
Referenced by Facebook.WitAi.Windows.WitPropertyDrawer.OnGUI().
The documentation for this class was generated from the following file:
C:/Users/Lykos/Desktop/Projects/Capstone/VRGames/Assets/ThirdParty/Oculus/Voice/Lib/Wit.ai/Scripts/Editor/Windows/PropertyDrawers/WitPropertyDrawer.cs