VRGames: UnityEditor.ProBuilder.ProBuilderEditor Class Reference
UnityEditor.ProBuilder.ProBuilderEditor Class Reference sealed
Manages the ProBuilder toolbar and tool mode.
Public Member Functions
void AddItemsToMenu (GenericMenu menu)
Builds the context menu for the ProBuilder toolbar. This menu allows the user to toggle between text and button mode, and to change whether the toolbar is floating or dockable.
Static Public Member Functions
static void ResetToLastSelectMode ()
Changes the SelectMode to the last used mesh element mode.
static void Refresh (bool vertexCountChanged=true)
Rebuilds the mesh wireframe and selection caches.
Properties
static SelectMode selectMode [get, set]
Gets and sets the current SelectMode value.
static ProBuilderEditor instance [get]
Gets the active ProBuilderEditor window, or null if no instance is open. The ProBuilderEditor window appears in the Unity Editor as both the Edit Mode toolbar and the ProBuilder toolbar working together.
Events
static Action< IEnumerable< ProBuilderMesh > > selectionUpdated
Raised any time the ProBuilder editor refreshes the selection. This is called every frame when interacting with mesh elements, and after any mesh operation.
static Action< SelectMode > selectModeChanged
Raised when the EditLevel changes.
static Action< IEnumerable< ProBuilderMesh > > afterMeshModification
Raised when vertex modifications are complete.
static Action< IEnumerable< ProBuilderMesh > > beforeMeshModification
Raised immediately prior to beginning vertex modifications, when the ProBuilderMesh is in un-altered state. This is after ProBuilderMesh.ToMesh and ProBuilderMesh.Refresh have been called, but before EditorMeshUtility.Optimize.
Detailed Description
Manages the ProBuilder toolbar and tool mode.
Member Function Documentation
AddItemsToMenu()
void UnityEditor.ProBuilder.ProBuilderEditor.AddItemsToMenu (GenericMenu menu)
Builds the context menu for the ProBuilder toolbar. This menu allows the user to toggle between text and button mode, and to change whether the toolbar is floating or dockable.
Parameters
menu The context menu
Refresh()
static void UnityEditor.ProBuilder.ProBuilderEditor.Refresh (bool vertexCountChanged = true) static
Rebuilds the mesh wireframe and selection caches.
Parameters
vertexCountChanged True if the number of vertices changed, which is the default value.
Referenced by UnityEditor.ProBuilder.PositionTool.Apply(), UnityEditor.ProBuilder.Actions.ProBuilderize.DoProBuilderize(), UnityEditor.ProBuilder.ProBuilderShapeEditor.DrawShapeGUI(), UnityEditor.ProBuilder.ProBuilderShapeEditor.DrawShapeParametersGUI(), UnityEditor.ProBuilder.Actions.ExportAsset.ExportWithFileDialog(), UnityEditor.ProBuilder.VertexManipulationTool.FinishEdit(), UnityEditor.ProBuilder.Actions.SelectFaceRing.MenuRingAndLoopFaces(), UnityEditor.ProBuilder.Actions.BevelEdges.PerformActionImplementation(), UnityEditor.ProBuilder.Actions.BridgeEdges.PerformActionImplementation(), UnityEditor.ProBuilder.Actions.CollapseVertices.PerformActionImplementation(), UnityEditor.ProBuilder.Actions.ConformFaceNormals.PerformActionImplementation(), UnityEditor.ProBuilder.Actions.ConnectEdges.PerformActionImplementation(), UnityEditor.ProBuilder.Actions.ConnectVertices.PerformActionImplementation(), UnityEditor.ProBuilder.Actions.DeleteFaces.PerformActionImplementation(), UnityEditor.ProBuilder.Actions.ExtrudeEdges.PerformActionImplementation(), UnityEditor.ProBuilder.Actions.ExtrudeFaces.PerformActionImplementation(), UnityEditor.ProBuilder.Actions.FillHole.PerformActionImplementation(), UnityEditor.ProBuilder.Actions.FlipFaceEdge.PerformActionImplementation(), UnityEditor.ProBuilder.Actions.InsertEdgeLoop.PerformActionImplementation(), UnityEditor.ProBuilder.Actions.MergeFaces.PerformActionImplementation(), UnityEditor.ProBuilder.Actions.OffsetElements.PerformActionImplementation(), UnityEditor.ProBuilder.Actions.SetPivotToSelection.PerformActionImplementation(), UnityEditor.ProBuilder.Actions.SplitVertices.PerformActionImplementation(), UnityEditor.ProBuilder.Actions.SubdivideEdges.PerformActionImplementation(), UnityEditor.ProBuilder.Actions.SubdivideFaces.PerformActionImplementation(), UnityEditor.ProBuilder.Actions.TriangulateFaces.PerformActionImplementation(), UnityEditor.ProBuilder.Actions.WeldVertices.PerformActionImplementation(), UnityEditor.ProBuilder.Actions.CenterPivot.PerformActionImplementation(), UnityEditor.ProBuilder.Actions.ConformObjectNormals.PerformActionImplementation(), UnityEditor.ProBuilder.Actions.FreezeTransform.PerformActionImplementation(), UnityEditor.ProBuilder.Actions.MergeObjects.PerformActionImplementation(), UnityEditor.ProBuilder.Actions.MirrorObjects.PerformActionImplementation(), UnityEditor.ProBuilder.Actions.SubdivideObject.PerformActionImplementation(), UnityEditor.ProBuilder.Actions.TriangulateObject.PerformActionImplementation(), UnityEditor.ProBuilder.Actions.GrowSelection.PerformActionImplementation(), UnityEditor.ProBuilder.Actions.SelectEdgeLoop.PerformActionImplementation(), UnityEditor.ProBuilder.Actions.SelectEdgeRing.PerformActionImplementation(), UnityEditor.ProBuilder.Actions.SelectFaceLoop.PerformActionImplementation(), UnityEditor.ProBuilder.Actions.SelectFaceRing.PerformActionImplementation(), UnityEditor.ProBuilder.Actions.SelectHole.PerformActionImplementation(), UnityEditor.ProBuilder.Actions.SelectMaterial.PerformActionImplementation(), UnityEditor.ProBuilder.Actions.SelectSmoothingGroup.PerformActionImplementation(), UnityEditor.ProBuilder.Actions.SelectVertexColor.PerformActionImplementation(), UnityEditor.ProBuilder.Actions.ShrinkSelection.PerformActionImplementation(), ProBuilder.ExampleActions.CreateShadowObject.PerformActionImplementation(), ProBuilder.ExampleActions.MakeFacesDoubleSided.PerformActionImplementation(), UnityEditor.ProBuilder.Actions.SoftDeleteEdgesAction.PerformActionImplementation(), UnityEditor.ProBuilder.PolyShapeTool.RebuildPolyShapeMesh(), and UnityEditor.ProBuilder.ProBuilderEditor.ResetToLastSelectMode().
ResetToLastSelectMode()
static void UnityEditor.ProBuilder.ProBuilderEditor.ResetToLastSelectMode () static
Changes the SelectMode to the last used mesh element mode.
Property Documentation
instance
ProBuilderEditor UnityEditor.ProBuilder.ProBuilderEditor.instance static get
Gets the active ProBuilderEditor window, or null if no instance is open. The ProBuilderEditor window appears in the Unity Editor as both the Edit Mode toolbar and the ProBuilder toolbar working together.
Referenced by UnityEditor.ProBuilder.PolyShapeEditor.OnInspectorGUI(), UnityEditor.ProBuilder.ProBuilderEditor.Refresh(), and UnityEditor.ProBuilder.VertexColorPalette.SetFaceColors().
selectMode
SelectMode UnityEditor.ProBuilder.ProBuilderEditor.selectMode static get set
Gets and sets the current SelectMode value.
Referenced by UnityEditor.ProBuilder.TextureMoveTool.DoToolGUI(), UnityEditor.ProBuilder.ElementGroup.GetElementGroups(), UnityEditor.ProBuilder.TextureTool.OnToolDisengaged(), UnityEditor.ProBuilder.VertexManipulationTool.OnToolGUI(), UnityEditor.ProBuilder.Actions.Extrude.PerformActionImplementation(), UnityEditor.ProBuilder.Actions.FillHole.PerformActionImplementation(), UnityEditor.ProBuilder.Actions.OffsetElements.PerformActionImplementation(), UnityEditor.ProBuilder.Actions.SmartConnect.PerformActionImplementation(), UnityEditor.ProBuilder.Actions.SmartSubdivide.PerformActionImplementation(), UnityEditor.ProBuilder.Actions.GrowSelection.PerformActionImplementation(), UnityEditor.ProBuilder.Actions.SelectLoop.PerformActionImplementation(), UnityEditor.ProBuilder.Actions.SelectRing.PerformActionImplementation(), UnityEditor.ProBuilder.Actions.ShrinkSelection.PerformActionImplementation(), and UnityEditor.ProBuilder.VertexColorPalette.SetFaceColors().
Event Documentation
afterMeshModification
Action<IEnumerable<ProBuilderMesh> > UnityEditor.ProBuilder.ProBuilderEditor.afterMeshModification static
Raised when vertex modifications are complete.
beforeMeshModification
Action<IEnumerable<ProBuilderMesh> > UnityEditor.ProBuilder.ProBuilderEditor.beforeMeshModification static
Raised immediately prior to beginning vertex modifications, when the ProBuilderMesh is in un-altered state. This is after ProBuilderMesh.ToMesh and ProBuilderMesh.Refresh have been called, but before EditorMeshUtility.Optimize.
selectionUpdated
Action<IEnumerable<ProBuilderMesh> > UnityEditor.ProBuilder.ProBuilderEditor.selectionUpdated static
Raised any time the ProBuilder editor refreshes the selection. This is called every frame when interacting with mesh elements, and after any mesh operation.
selectModeChanged
Action<SelectMode> UnityEditor.ProBuilder.ProBuilderEditor.selectModeChanged static
Raised when the EditLevel changes.
The documentation for this class was generated from the following file:
C:/Users/Lykos/Desktop/Projects/Capstone/VRGames/Library/PackageCache/com.unity.probuilder@5.0.6/Editor/EditorCore/ProBuilderEditor.cs