VRCapstoneGames: UnityEngine.XR.Interaction.Toolkit.SnapTurnProviderBase Class Reference
UnityEngine.XR.Interaction.Toolkit.SnapTurnProviderBase Class Reference abstract
A locomotion provider that allows the user to rotate their rig using a 2D axis input.
Protected Member Functions
void Update ()
See MonoBehaviour.
Vector2 ReadInput ()
Reads the current value of the snap turn input.
virtual float GetTurnAmount (Vector2 input)
Determines the turn amount in degrees for the given input vector.
void StartTurn (float amount)
Begins turning locomotion.
Protected Member Functions inherited from UnityEngine.XR.Interaction.Toolkit.LocomotionProvider
virtual void Awake ()
See MonoBehaviour.
bool CanBeginLocomotion ()
Checks if locomotion can begin.
bool BeginLocomotion ()
Invokes begin locomotion events.
bool EndLocomotion ()
Invokes end locomotion events.
Properties
float turnAmount [get, set]
The number of degrees clockwise Unity rotates the rig when snap turning clockwise.
float debounceTime [get, set]
The amount of time that Unity waits before starting another snap turn.
bool enableTurnLeftRight [get, set]
Controls whether to enable left and right snap turns.
bool enableTurnAround [get, set]
Controls whether to enable 180° snap turns.
Properties inherited from UnityEngine.XR.Interaction.Toolkit.LocomotionProvider
LocomotionSystem system [get, set]
The LocomotionSystem that this LocomotionProvider communicates with for exclusive access to an XR Origin. If one is not provided, the behavior will attempt to locate one during its Awake call.
Additional Inherited Members
Events inherited from UnityEngine.XR.Interaction.Toolkit.LocomotionProvider
Action< LocomotionSystem > beginLocomotion
Unity calls the beginLocomotion action when a LocomotionProvider successfully begins a locomotion event.
Action< LocomotionSystem > endLocomotion
Unity calls the endLocomotion action when a LocomotionProvider successfully ends a locomotion event.
Action< LocomotionSystem > startLocomotion
(Deprecated) The startLocomotion action will be called when a LocomotionProvider successfully begins a locomotion event.
Detailed Description
A locomotion provider that allows the user to rotate their rig using a 2D axis input.
Member Function Documentation
GetTurnAmount()
virtual float UnityEngine.XR.Interaction.Toolkit.SnapTurnProviderBase.GetTurnAmount (Vector2 input) protected virtual
Determines the turn amount in degrees for the given input vector.
Parameters
input Input vector, such as from a thumbstick.
Returns
Returns the turn amount in degrees for the given input vector.
Referenced by UnityEngine.XR.Interaction.Toolkit.SnapTurnProviderBase.Update().
ReadInput()
Vector2 UnityEngine.XR.Interaction.Toolkit.SnapTurnProviderBase.ReadInput () abstract protected
Reads the current value of the snap turn input.
Returns
Returns the input vector, such as from a thumbstick.
Referenced by UnityEngine.XR.Interaction.Toolkit.SnapTurnProviderBase.Update().
StartTurn()
void UnityEngine.XR.Interaction.Toolkit.SnapTurnProviderBase.StartTurn (float amount) protected
Begins turning locomotion.
Parameters
amount Amount to turn.
Referenced by UnityEngine.XR.Interaction.Toolkit.SnapTurnProviderBase.Update().
Update()
void UnityEngine.XR.Interaction.Toolkit.SnapTurnProviderBase.Update () protected
See MonoBehaviour.
Property Documentation
debounceTime
float UnityEngine.XR.Interaction.Toolkit.SnapTurnProviderBase.debounceTime get set
The amount of time that Unity waits before starting another snap turn.
enableTurnAround
bool UnityEngine.XR.Interaction.Toolkit.SnapTurnProviderBase.enableTurnAround get set
Controls whether to enable 180° snap turns.
See also
enableTurnLeftRight
enableTurnLeftRight
bool UnityEngine.XR.Interaction.Toolkit.SnapTurnProviderBase.enableTurnLeftRight get set
Controls whether to enable left and right snap turns.
See also
enableTurnAround
turnAmount
float UnityEngine.XR.Interaction.Toolkit.SnapTurnProviderBase.turnAmount get set
The number of degrees clockwise Unity rotates the rig when snap turning clockwise.
Referenced by UnityEngine.XR.Interaction.Toolkit.Tests.LocomotionTests.SnapTurn().
The documentation for this class was generated from the following file:
C:/Users/Lykos/Desktop/Projects/Capstone/VRGames/Library/PackageCache/com.unity.xr.interaction.toolkit@2.0.2/Runtime/Locomotion/SnapTurn/SnapTurnProviderBase.cs