VRCapstoneGames: OVRManifestPreprocessor Class Reference
OVRManifestPreprocessor Class Reference
Static Public Member Functions
static void GenerateManifestForSubmission ()
static void UpdateAndroidManifest ()
static void RemoveAndroidManifest ()
static void PatchAndroidManifest (string sourceFile, string destinationFile=null, bool skipExistingAttributes=true, bool enableSecurity=false)
Member Function Documentation
GenerateManifestForSubmission()
static void OVRManifestPreprocessor.GenerateManifestForSubmission () static
PatchAndroidManifest()
static void OVRManifestPreprocessor.PatchAndroidManifest (string sourceFile, string destinationFile = null, bool skipExistingAttributes = true, bool enableSecurity = false) static
Referenced by GenerateManifestForSubmission(), OVRGradleGeneration.PatchAndroidManifest(), and UpdateAndroidManifest().
RemoveAndroidManifest()
static void OVRManifestPreprocessor.RemoveAndroidManifest () static
UpdateAndroidManifest()
static void OVRManifestPreprocessor.UpdateAndroidManifest () static
The documentation for this class was generated from the following file:
C:/Users/Lykos/Desktop/Projects/Capstone/VRGames/Assets/ThirdParty/Oculus/VR/Editor/OVRManifestPreprocessor.cs