VRGames: Oculus.Voice.AppVoiceExperience Class Reference
Oculus.Voice.AppVoiceExperience Class Reference
Public Member Functions
override void Activate ()
Activate the microphone and send data for NLU processing.
override void Activate (WitRequestOptions options)
Activate the microphone and send data for NLU processing with custom request options.
override void ActivateImmediately ()
override void ActivateImmediately (WitRequestOptions options)
override void Deactivate ()
Stop listening and submit the collected microphone data for processing.
override void DeactivateAndAbortRequest ()
Stop listening and abort any requests that may be active without waiting for a response.
override void Activate (string text)
Send text data for NLU processing.
override void Activate (string text, WitRequestOptions requestOptions)
Send text data for NLU processing with custom request options.
Public Member Functions inherited from Facebook.WitAi.VoiceService
void Activate ()
Start listening for sound or speech from the user and start sending data to Wit.ai once sound or speech has been detected.
void Activate (WitRequestOptions requestOptions)
Activate the microphone and send data for NLU processing. Includes optional additional request parameters like dynamic entities and maximum results.
void ActivateImmediately ()
Activate the microphone and send data for NLU processing immediately without waiting for sound/speech from the user to begin.
void ActivateImmediately (WitRequestOptions requestOptions)
Activate the microphone and send data for NLU processing immediately without waiting for sound/speech from the user to begin. Includes optional additional request parameters like dynamic entities and maximum results.
void Deactivate ()
Stop listening and submit any remaining buffered microphone data for processing.
void DeactivateAndAbortRequest ()
Stop listening and abort any requests that may be active without waiting for a response.
void Activate (string text)
Send text data for NLU processing. Results will return the same way a voice based activation would.
void Activate (string text, WitRequestOptions requestOptions)
Send text data for NLU processing with custom request options.
Properties
WitRuntimeConfiguration RuntimeConfiguration [get, set]
override bool Active [get]
Returns true if this voice service is currently active and listening with the mic.
override bool IsRequestActive [get]
override ITranscriptionProvider TranscriptionProvider [get, set]
override bool MicActive [get]
override bool ShouldSendMicData [get]
bool HasPlatformIntegrations [get]
Properties inherited from Facebook.WitAi.VoiceService
bool Active [get]
Returns true if this voice service is currently active and listening with the mic.
bool IsRequestActive [get]
Returns true if the service is actively communicating with Wit.ai during an Activation. The mic may or may not still be active while this is true.
ITranscriptionProvider TranscriptionProvider [get, set]
Gets/Sets a custom transcription provider. This can be used to replace any built in asr with an on device model or other provided source.
bool MicActive [get]
Returns true if this voice service is currently reading data from the microphone.
VoiceEvents VoiceEvents [get, set]
bool ShouldSendMicData [get]
Returns true if the audio input should be read in an activation.
Properties inherited from Facebook.WitAi.IVoiceService
Properties inherited from Facebook.WitAi.IWitRuntimeConfigProvider
Additional Inherited Members
Public Attributes inherited from Facebook.WitAi.VoiceService
VoiceEvents events = new VoiceEvents()
Member Function Documentation
Activate() [1/4]
override void Oculus.Voice.AppVoiceExperience.Activate ()
Activate the microphone and send data for NLU processing.
Implements Facebook.WitAi.IVoiceService.
Referenced by Oculus.Voice.Demo.BuiltInDemo.WitActivation.ActivateWit(), and Oculus.Voice.Demo.UIShapesDemo.InteractionHandler.ToggleActivation().
Activate() [2/4]
override void Oculus.Voice.AppVoiceExperience.Activate (string transcription)
Send text data for NLU processing.
Parameters
text
Implements Facebook.WitAi.IVoiceService.
Activate() [3/4]
override void Oculus.Voice.AppVoiceExperience.Activate (string text, WitRequestOptions requestOptions)
Send text data for NLU processing with custom request options.
Parameters
text
requestOptions
Implements Facebook.WitAi.IVoiceService.
Activate() [4/4]
override void Oculus.Voice.AppVoiceExperience.Activate (WitRequestOptions requestOptions)
Activate the microphone and send data for NLU processing with custom request options.
Parameters
requestOptions
Implements Facebook.WitAi.IVoiceService.
ActivateImmediately() [1/2]
override void Oculus.Voice.AppVoiceExperience.ActivateImmediately ()
Implements Facebook.WitAi.IVoiceService.
ActivateImmediately() [2/2]
override void Oculus.Voice.AppVoiceExperience.ActivateImmediately (WitRequestOptions options)
Implements Facebook.WitAi.IVoiceService.
Deactivate()
override void Oculus.Voice.AppVoiceExperience.Deactivate ()
Stop listening and submit the collected microphone data for processing.
Implements Facebook.WitAi.IVoiceService.
Referenced by Oculus.Voice.Demo.UIShapesDemo.InteractionHandler.ToggleActivation().
DeactivateAndAbortRequest()
override void Oculus.Voice.AppVoiceExperience.DeactivateAndAbortRequest ()
Stop listening and abort any requests that may be active without waiting for a response.
Implements Facebook.WitAi.IVoiceService.
Property Documentation
Active
override bool Oculus.Voice.AppVoiceExperience.Active get
Returns true if this voice service is currently active and listening with the mic.
Implements Facebook.WitAi.IVoiceService.
Referenced by Oculus.Voice.Demo.UIShapesDemo.InteractionHandler.ToggleActivation().
HasPlatformIntegrations
bool Oculus.Voice.AppVoiceExperience.HasPlatformIntegrations get
IsRequestActive
override bool Oculus.Voice.AppVoiceExperience.IsRequestActive get
Implements Facebook.WitAi.IVoiceService.
MicActive
override bool Oculus.Voice.AppVoiceExperience.MicActive get
Implements Facebook.WitAi.IVoiceService.
RuntimeConfiguration
WitRuntimeConfiguration Oculus.Voice.AppVoiceExperience.RuntimeConfiguration get set
Implements Facebook.WitAi.IWitRuntimeConfigProvider.
ShouldSendMicData
override bool Oculus.Voice.AppVoiceExperience.ShouldSendMicData get protected
TranscriptionProvider
override ITranscriptionProvider Oculus.Voice.AppVoiceExperience.TranscriptionProvider get set
Implements Facebook.WitAi.IVoiceService.
The documentation for this class was generated from the following file:
C:/Users/Lykos/Desktop/Projects/Capstone/VRGames/Assets/ThirdParty/Oculus/Voice/Scripts/Runtime/Service/AppVoiceExperience.cs