VRCapstoneGames: Oculus.Interaction.PoseDetection.FingerShapes Class Reference
Oculus.Interaction.PoseDetection.FingerShapes Class Reference
Public Member Functions
virtual float GetValue (HandFinger finger, FingerFeature feature, IHand hand)
float GetCurlValue (HandFinger finger, IHand hand)
float GetFlexionValue (HandFinger finger, IHand hand)
float GetAbductionValue (HandFinger finger, IHand hand)
float GetOppositionValue (HandFinger finger, IHand hand)
virtual IReadOnlyList< HandJointId > GetJointsAffected (HandFinger finger, FingerFeature feature)
Protected Member Functions
float ComputeAngleSum (HandJointId[] joints, IHand hand)
Member Function Documentation
ComputeAngleSum()
float Oculus.Interaction.PoseDetection.FingerShapes.ComputeAngleSum (HandJointId[] joints, IHand hand) protected
Referenced by Oculus.Interaction.PoseDetection.FingerShapes.GetCurlValue(), and Oculus.Interaction.PoseDetection.FingerShapes.GetFlexionValue().
GetAbductionValue()
float Oculus.Interaction.PoseDetection.FingerShapes.GetAbductionValue (HandFinger finger, IHand hand)
Referenced by Oculus.Interaction.PoseDetection.FingerShapes.GetValue().
GetCurlValue()
float Oculus.Interaction.PoseDetection.FingerShapes.GetCurlValue (HandFinger finger, IHand hand)
Referenced by Oculus.Interaction.PoseDetection.FingerShapes.GetValue().
GetFlexionValue()
float Oculus.Interaction.PoseDetection.FingerShapes.GetFlexionValue (HandFinger finger, IHand hand)
Referenced by Oculus.Interaction.PoseDetection.FingerShapes.GetValue().
GetJointsAffected()
virtual IReadOnlyList< HandJointId > Oculus.Interaction.PoseDetection.FingerShapes.GetJointsAffected (HandFinger finger, FingerFeature feature) virtual
GetOppositionValue()
float Oculus.Interaction.PoseDetection.FingerShapes.GetOppositionValue (HandFinger finger, IHand hand)
Referenced by Oculus.Interaction.PoseDetection.FingerShapes.GetValue().
GetValue()
virtual float Oculus.Interaction.PoseDetection.FingerShapes.GetValue (HandFinger finger, FingerFeature feature, IHand hand) virtual
Referenced by Oculus.Interaction.PoseDetection.FingerFeatureStateProvider.GetFeatureValue().
The documentation for this class was generated from the following file:
C:/Users/Lykos/Desktop/Projects/Capstone/VRGames/Assets/ThirdParty/Oculus/Interaction/Runtime/Scripts/PoseDetection/FingerShapes.cs