VRCapstoneGames: UnityEngine.ProBuilder.KdTree.Math.TypeMath< T > Class Template Reference
UnityEngine.ProBuilder.KdTree.Math.TypeMath< T > Class Template Reference abstract
Public Member Functions
int Compare (T a, T b)
bool AreEqual (T a, T b)
virtual bool AreEqual (T[] a, T[] b)
T Min (T a, T b)
T Max (T a, T b)
T Add (T a, T b)
T Subtract (T a, T b)
T Multiply (T a, T b)
T DistanceSquaredBetweenPoints (T[] a, T[] b)
Properties
T MinValue [get]
T MaxValue [get]
T Zero [get]
T NegativeInfinity [get]
T PositiveInfinity [get]
Properties inherited from UnityEngine.ProBuilder.KdTree.ITypeMath< T >
Member Function Documentation
Add()
T UnityEngine.ProBuilder.KdTree.Math.TypeMath< T >.Add (T a, T b) abstract
Implements UnityEngine.ProBuilder.KdTree.ITypeMath< T >.
AreEqual() [1/2]
bool UnityEngine.ProBuilder.KdTree.Math.TypeMath< T >.AreEqual (T a, T b) abstract
Implements UnityEngine.ProBuilder.KdTree.ITypeMath< T >.
Referenced by UnityEngine.ProBuilder.KdTree.Math.TypeMath< T >.AreEqual().
AreEqual() [2/2]
virtual bool UnityEngine.ProBuilder.KdTree.Math.TypeMath< T >.AreEqual (T[] a, T[] b) virtual
Implements UnityEngine.ProBuilder.KdTree.ITypeMath< T >.
Compare()
int UnityEngine.ProBuilder.KdTree.Math.TypeMath< T >.Compare (T a, T b) abstract
Implements UnityEngine.ProBuilder.KdTree.ITypeMath< T >.
Referenced by UnityEngine.ProBuilder.KdTree.Math.TypeMath< T >.Max(), and UnityEngine.ProBuilder.KdTree.Math.TypeMath< T >.Min().
DistanceSquaredBetweenPoints()
T UnityEngine.ProBuilder.KdTree.Math.TypeMath< T >.DistanceSquaredBetweenPoints (T[] a, T[] b) abstract
Implements UnityEngine.ProBuilder.KdTree.ITypeMath< T >.
Max()
T UnityEngine.ProBuilder.KdTree.Math.TypeMath< T >.Max (T a, T b)
Implements UnityEngine.ProBuilder.KdTree.ITypeMath< T >.
Min()
T UnityEngine.ProBuilder.KdTree.Math.TypeMath< T >.Min (T a, T b)
Implements UnityEngine.ProBuilder.KdTree.ITypeMath< T >.
Multiply()
T UnityEngine.ProBuilder.KdTree.Math.TypeMath< T >.Multiply (T a, T b) abstract
Implements UnityEngine.ProBuilder.KdTree.ITypeMath< T >.
Subtract()
T UnityEngine.ProBuilder.KdTree.Math.TypeMath< T >.Subtract (T a, T b) abstract
Implements UnityEngine.ProBuilder.KdTree.ITypeMath< T >.
Property Documentation
MaxValue
T UnityEngine.ProBuilder.KdTree.Math.TypeMath< T >.MaxValue get abstract
Implements UnityEngine.ProBuilder.KdTree.ITypeMath< T >.
MinValue
T UnityEngine.ProBuilder.KdTree.Math.TypeMath< T >.MinValue get abstract
Implements UnityEngine.ProBuilder.KdTree.ITypeMath< T >.
NegativeInfinity
T UnityEngine.ProBuilder.KdTree.Math.TypeMath< T >.NegativeInfinity get abstract
Implements UnityEngine.ProBuilder.KdTree.ITypeMath< T >.
PositiveInfinity
T UnityEngine.ProBuilder.KdTree.Math.TypeMath< T >.PositiveInfinity get abstract
Implements UnityEngine.ProBuilder.KdTree.ITypeMath< T >.
Zero
T UnityEngine.ProBuilder.KdTree.Math.TypeMath< T >.Zero get abstract
Implements UnityEngine.ProBuilder.KdTree.ITypeMath< T >.
The documentation for this class was generated from the following file:
C:/Users/Lykos/Desktop/Projects/Capstone/VRGames/Library/PackageCache/com.unity.probuilder@5.0.6/External/KdTree/KdTreeLib/Math/TypeMath.cs