VRCapstoneGames: Oculus.Interaction.HandVisual Class Reference
Oculus.Interaction.HandVisual Class Reference
Public Member Functions
void UpdateSkeleton ()
Transform GetTransformByHandJointId (HandJointId handJointId)
void InjectAllHandSkeletonVisual (IHand hand, SkinnedMeshRenderer skinnedMeshRenderer)
void InjectHand (IHand hand)
void InjectSkinnedMeshRenderer (SkinnedMeshRenderer skinnedMeshRenderer)
void InjectOptionalUpdateRootPose (bool updateRootPose)
void InjectOptionalUpdateRootScale (bool updateRootScale)
void InjectOptionalRoot (Transform root)
void InjectOptionalMaterialPropertyBlockEditor (MaterialPropertyBlockEditor editor)
Public Attributes
IHand Hand
Protected Member Functions
virtual void Awake ()
virtual void Start ()
virtual void OnEnable ()
virtual void OnDisable ()
Properties
bool IsVisible [get]
List< Transform > Joints [get]
bool ForceOffVisibility [get, set]
Events
Action WhenHandVisualUpdated = delegate { }
Member Function Documentation
Awake()
virtual void Oculus.Interaction.HandVisual.Awake () protected virtual
GetTransformByHandJointId()
Transform Oculus.Interaction.HandVisual.GetTransformByHandJointId (HandJointId handJointId)
InjectAllHandSkeletonVisual()
void Oculus.Interaction.HandVisual.InjectAllHandSkeletonVisual (IHand hand, SkinnedMeshRenderer skinnedMeshRenderer)
InjectHand()
void Oculus.Interaction.HandVisual.InjectHand (IHand hand)
Referenced by Oculus.Interaction.HandVisual.InjectAllHandSkeletonVisual().
InjectOptionalMaterialPropertyBlockEditor()
void Oculus.Interaction.HandVisual.InjectOptionalMaterialPropertyBlockEditor (MaterialPropertyBlockEditor editor)
InjectOptionalRoot()
void Oculus.Interaction.HandVisual.InjectOptionalRoot (Transform root)
InjectOptionalUpdateRootPose()
void Oculus.Interaction.HandVisual.InjectOptionalUpdateRootPose (bool updateRootPose)
InjectOptionalUpdateRootScale()
void Oculus.Interaction.HandVisual.InjectOptionalUpdateRootScale (bool updateRootScale)
InjectSkinnedMeshRenderer()
void Oculus.Interaction.HandVisual.InjectSkinnedMeshRenderer (SkinnedMeshRenderer skinnedMeshRenderer)
Referenced by Oculus.Interaction.HandVisual.InjectAllHandSkeletonVisual().
OnDisable()
virtual void Oculus.Interaction.HandVisual.OnDisable () protected virtual
OnEnable()
virtual void Oculus.Interaction.HandVisual.OnEnable () protected virtual
Start()
virtual void Oculus.Interaction.HandVisual.Start () protected virtual
UpdateSkeleton()
void Oculus.Interaction.HandVisual.UpdateSkeleton ()
Referenced by Oculus.Interaction.HandVisual.OnDisable(), and Oculus.Interaction.HandVisual.OnEnable().
Member Data Documentation
Hand
IHand Oculus.Interaction.HandVisual.Hand
Property Documentation
ForceOffVisibility
bool Oculus.Interaction.HandVisual.ForceOffVisibility get set
Referenced by Oculus.Interaction.HandVisual.UpdateSkeleton().
IsVisible
bool Oculus.Interaction.HandVisual.IsVisible get
Referenced by Oculus.Interaction.Input.HandPhysicsCapsules.FixedUpdate(), and Oculus.Interaction.HandVisual.UpdateSkeleton().
Joints
List<Transform> Oculus.Interaction.HandVisual.Joints get
Referenced by Oculus.Interaction.Hands.Editor.HandVisualEditor.OnInspectorGUI(), and Oculus.Interaction.Input.HandPhysicsCapsules.Start().
Event Documentation
WhenHandVisualUpdated
Action Oculus.Interaction.HandVisual.WhenHandVisualUpdated = delegate { }
Referenced by Oculus.Interaction.HandVisual.UpdateSkeleton().
The documentation for this class was generated from the following file:
C:/Users/Lykos/Desktop/Projects/Capstone/VRGames/Assets/ThirdParty/Oculus/Interaction/Runtime/Scripts/Interaction/Visuals/HandVisual.cs