VRCapstoneGames: UnityEngine.UI.ContentSizeFitter Class Reference
UnityEngine.UI.ContentSizeFitter Class Reference
Resizes a RectTransform to fit the size of its content.
Public Types
enum FitMode { Unconstrained , MinSize , PreferredSize }
The size fit modes avaliable to use.
Public Member Functions
virtual void SetLayoutHorizontal ()
Calculate and apply the horizontal component of the size to the RectTransform.
virtual void SetLayoutVertical ()
Calculate and apply the vertical component of the size to the RectTransform.
Public Member Functions inherited from UnityEngine.EventSystems.UIBehaviour
virtual bool IsActive ()
Returns true if the GameObject and the Component are active.
bool IsDestroyed ()
Returns true if the native representation of the behaviour has been destroyed.
Protected Member Functions
ContentSizeFitter ()
override void OnEnable ()
override void OnDisable ()
override void OnRectTransformDimensionsChange ()
This callback is called when the dimensions of an associated RectTransform change. It is always called before Awake, OnEnable, or Start. The call is also made to all child RectTransforms, regardless of whether their dimensions change (which depends on how they are anchored).
void SetDirty ()
Protected Member Functions inherited from UnityEngine.EventSystems.UIBehaviour
virtual void Awake ()
virtual void Start ()
virtual void OnDestroy ()
virtual void OnBeforeTransformParentChanged ()
virtual void OnTransformParentChanged ()
virtual void OnDidApplyAnimationProperties ()
virtual void OnCanvasGroupChanged ()
virtual void OnCanvasHierarchyChanged ()
Called when the state of the parent Canvas is changed.
Protected Attributes
FitMode m_HorizontalFit = FitMode.Unconstrained
FitMode m_VerticalFit = FitMode.Unconstrained
Properties
FitMode horizontalFit [get, set]
The fit mode to use to determine the width.
FitMode verticalFit [get, set]
The fit mode to use to determine the height.
Detailed Description
Resizes a RectTransform to fit the size of its content.
The ContentSizeFitter can be used on GameObjects that have one or more ILayoutElement components, such as Text, Image, HorizontalLayoutGroup, VerticalLayoutGroup, and GridLayoutGroup.
Member Enumeration Documentation
FitMode
enum UnityEngine.UI.ContentSizeFitter.FitMode
The size fit modes avaliable to use.
Enumerator
Unconstrained
Don't perform any resizing.
MinSize
Resize to the minimum size of the content.
PreferredSize
Resize to the preferred size of the content.
Constructor & Destructor Documentation
ContentSizeFitter()
UnityEngine.UI.ContentSizeFitter.ContentSizeFitter () protected
Member Function Documentation
OnDisable()
override void UnityEngine.UI.ContentSizeFitter.OnDisable () protected virtual
Reimplemented from UnityEngine.EventSystems.UIBehaviour.
OnEnable()
override void UnityEngine.UI.ContentSizeFitter.OnEnable () protected virtual
Reimplemented from UnityEngine.EventSystems.UIBehaviour.
OnRectTransformDimensionsChange()
override void UnityEngine.UI.ContentSizeFitter.OnRectTransformDimensionsChange () protected virtual
This callback is called when the dimensions of an associated RectTransform change. It is always called before Awake, OnEnable, or Start. The call is also made to all child RectTransforms, regardless of whether their dimensions change (which depends on how they are anchored).
Reimplemented from UnityEngine.EventSystems.UIBehaviour.
SetDirty()
void UnityEngine.UI.ContentSizeFitter.SetDirty () protected
Referenced by UnityEngine.UI.ContentSizeFitter.OnEnable(), and UnityEngine.UI.ContentSizeFitter.OnRectTransformDimensionsChange().
SetLayoutHorizontal()
virtual void UnityEngine.UI.ContentSizeFitter.SetLayoutHorizontal () virtual
Calculate and apply the horizontal component of the size to the RectTransform.
Referenced by LayoutTests.ContentSizeFitterTests.TestFitModeMinSize(), LayoutTests.ContentSizeFitterTests.TestFitModePreferredSize(), and LayoutTests.ContentSizeFitterTests.TestFitModeUnconstrained().
SetLayoutVertical()
virtual void UnityEngine.UI.ContentSizeFitter.SetLayoutVertical () virtual
Calculate and apply the vertical component of the size to the RectTransform.
Referenced by LayoutTests.ContentSizeFitterTests.TestFitModeMinSize(), LayoutTests.ContentSizeFitterTests.TestFitModePreferredSize(), and LayoutTests.ContentSizeFitterTests.TestFitModeUnconstrained().
Member Data Documentation
m_HorizontalFit
FitMode UnityEngine.UI.ContentSizeFitter.m_HorizontalFit = FitMode.Unconstrained protected
m_VerticalFit
FitMode UnityEngine.UI.ContentSizeFitter.m_VerticalFit = FitMode.Unconstrained protected
Property Documentation
horizontalFit
FitMode UnityEngine.UI.ContentSizeFitter.horizontalFit get set
The fit mode to use to determine the width.
verticalFit
FitMode UnityEngine.UI.ContentSizeFitter.verticalFit get set
The fit mode to use to determine the height.
The documentation for this class was generated from the following file:
C:/Users/Lykos/Desktop/Projects/Capstone/VRGames/Library/PackageCache/com.unity.ugui@1.0.0/Runtime/UI/Core/Layout/ContentSizeFitter.cs