VRCapstoneGames: UnityEditor.Timeline.FrameSelectedAction Class Reference
UnityEditor.Timeline.FrameSelectedAction Class Reference
Public Member Functions
override ActionValidity Validate (ActionContext context)
override bool Execute (ActionContext actionContext)
Public Member Functions inherited from UnityEditor.Timeline.Actions.TimelineAction
bool Execute (ActionContext context)
Execute the action.
ActionValidity Validate (ActionContext context)
Defines the validity of an Action based on the context.
Static Public Member Functions
static void FrameRange (float startTime, float endTime)
static bool ShouldHandleInlineCurve (IClipCurveEditorOwner curveEditorOwner)
static void FrameInlineCurves (IClipCurveEditorOwner curveEditorOwner, bool selectionOnly)
Member Function Documentation
Execute()
override bool UnityEditor.Timeline.FrameSelectedAction.Execute (ActionContext actionContext)
FrameInlineCurves()
static void UnityEditor.Timeline.FrameSelectedAction.FrameInlineCurves (IClipCurveEditorOwner curveEditorOwner, bool selectionOnly) static
Referenced by UnityEditor.Timeline.FrameAllAction.Execute(), and UnityEditor.Timeline.FrameSelectedAction.Execute().
FrameRange()
static void UnityEditor.Timeline.FrameSelectedAction.FrameRange (float startTime, float endTime) static
Referenced by UnityEditor.Timeline.FrameAllAction.Execute(), UnityEditor.Timeline.FrameSelectedAction.Execute(), and UnityEditor.Timeline.FrameSelectedAction.FrameInlineCurves().
ShouldHandleInlineCurve()
static bool UnityEditor.Timeline.FrameSelectedAction.ShouldHandleInlineCurve (IClipCurveEditorOwner curveEditorOwner) static
Referenced by UnityEditor.Timeline.FrameAllAction.Execute(), and UnityEditor.Timeline.FrameSelectedAction.Execute().
Validate()
override ActionValidity UnityEditor.Timeline.FrameSelectedAction.Validate (ActionContext context)
The documentation for this class was generated from the following file:
C:/Users/Lykos/Desktop/Projects/Capstone/VRGames/Library/PackageCache/com.unity.timeline@1.6.4/Editor/Actions/TimelineActions.cs