VRCapstoneGames: P2PManager Class Reference
P2PManager Class Reference
Public Member Functions
P2PManager ()
void ConnectTo (ulong userID)
void Disconnect (ulong userID)
void SendAvatarUpdate (ulong userID, Transform rootTransform, UInt32 sequence, byte[] avatarPacket)
void GetRemotePackets ()
void processAvatarPacket (RemotePlayer remote, ref byte[] packet, ref int offset)
Constructor & Destructor Documentation
P2PManager()
P2PManager.P2PManager ()
Member Function Documentation
ConnectTo()
void P2PManager.ConnectTo (ulong userID)
Disconnect()
void P2PManager.Disconnect (ulong userID)
Referenced by SocialPlatformManager.OnApplicationQuit().
GetRemotePackets()
void P2PManager.GetRemotePackets ()
Referenced by SocialPlatformManager.Update().
processAvatarPacket()
void P2PManager.processAvatarPacket (RemotePlayer remote, ref byte[] packet, ref int offset)
Referenced by GetRemotePackets().
SendAvatarUpdate()
void P2PManager.SendAvatarUpdate (ulong userID, Transform rootTransform, UInt32 sequence, byte[] avatarPacket)
Referenced by SocialPlatformManager.OnLocalAvatarPacketRecorded().
The documentation for this class was generated from the following file:
C:/Users/Lykos/Desktop/Projects/Capstone/VRGames/Assets/ThirdParty/Oculus/Avatar/Samples/SocialStarter/Assets/Scripts/P2PManager.cs