VRCapstoneGames: Oculus.Interaction.MultiAction< T > Class Template Reference
Oculus.Interaction.MultiAction< T > Class Template Reference
Classes that implement an interface that has MActions can use MultiAction as their MAction implementation to allow for multiple types of delegates to subscribe to the generic type.
Public Member Functions
void Invoke (T t)
Protected Attributes
HashSet< Action< T > > actions = new HashSet<Action<T>>()
Properties
Action< T > Action
Additional Inherited Members
Events inherited from Oculus.Interaction.MAction< T >
Action< T > Action
Detailed Description
Classes that implement an interface that has MActions can use MultiAction as their MAction implementation to allow for multiple types of delegates to subscribe to the generic type.
Member Function Documentation
Invoke()
void Oculus.Interaction.MultiAction< T >.Invoke (T t)
Referenced by Oculus.Interaction.Interactor< TInteractor, TInteractable >.InteractableSelected(), Oculus.Interaction.Interactor< TInteractor, TInteractable >.InteractableSet(), Oculus.Interaction.Interactor< TInteractor, TInteractable >.InteractableUnselected(), Oculus.Interaction.Interactor< TInteractor, TInteractable >.InteractableUnset(), Oculus.Interaction.Interactable< TInteractor, TInteractable >.InteractorAdded(), Oculus.Interaction.Interactable< TInteractor, TInteractable >.InteractorRemoved(), Oculus.Interaction.Interactable< TInteractor, TInteractable >.SelectingInteractorAdded(), and Oculus.Interaction.Interactable< TInteractor, TInteractable >.SelectingInteractorRemoved().
Member Data Documentation
actions
HashSet<Action<T> > Oculus.Interaction.MultiAction< T >.actions = new HashSet<Action<T>>() protected
Referenced by Oculus.Interaction.MultiAction< T >.Invoke().
Property Documentation
Action
Action<T> Oculus.Interaction.MultiAction< T >.Action add remove
The documentation for this class was generated from the following file:
C:/Users/Lykos/Desktop/Projects/Capstone/VRGames/Assets/ThirdParty/Oculus/Interaction/Runtime/Scripts/Interaction/Core/MultiAction.cs