VRGames: Facebook.WitAi.Tests.ConnectionTest Class Reference
Facebook.WitAi.Tests.ConnectionTest Class Reference abstract
Public Member Functions
void Execute (Wit wit)
void OnResponse (WitResponseNode response)
virtual void OnError (string code, string message)
void Reset ()
virtual void OnRequestCompleted ()
virtual void OnRequestCreated (WitRequest request)
void TestPassed ()
void TestFailed (string reason)
Public Attributes
string endpoint = WitRequest.WIT_ENDPOINT_SPEECH
bool isSlowTest = false
Protected Member Functions
void OnExecute (Wit wit)
virtual void OnReset ()
virtual void OnRawResponse (string response)
Protected Attributes
string name
Properties
bool IsSlowTest [get]
virtual string Name [get, set]
virtual bool Success = false [get, protected set]
virtual bool TestComplete = false [get, protected set]
virtual string TestResult = "" [get, protected set]
string TestEndpoint [get, set]
Member Function Documentation
Execute()
void Facebook.WitAi.Tests.ConnectionTest.Execute (Wit wit)
OnError()
virtual void Facebook.WitAi.Tests.ConnectionTest.OnError (string code, string message) virtual
Reimplemented in Facebook.WitAi.Tests.TestErrorCode.
OnExecute()
void Facebook.WitAi.Tests.ConnectionTest.OnExecute (Wit wit) abstract protected
Referenced by Facebook.WitAi.Tests.ConnectionTest.Execute().
OnRawResponse()
virtual void Facebook.WitAi.Tests.ConnectionTest.OnRawResponse (string response) protected virtual
Referenced by Facebook.WitAi.Tests.ConnectionTest.OnRequestCreated().
OnRequestCompleted()
virtual void Facebook.WitAi.Tests.ConnectionTest.OnRequestCompleted () virtual
OnRequestCreated()
virtual void Facebook.WitAi.Tests.ConnectionTest.OnRequestCreated (WitRequest request) virtual
OnReset()
virtual void Facebook.WitAi.Tests.ConnectionTest.OnReset () protected virtual
Referenced by Facebook.WitAi.Tests.ConnectionTest.Reset().
OnResponse()
void Facebook.WitAi.Tests.ConnectionTest.OnResponse (WitResponseNode response) abstract
Reset()
void Facebook.WitAi.Tests.ConnectionTest.Reset ()
TestFailed()
void Facebook.WitAi.Tests.ConnectionTest.TestFailed (string reason)
Referenced by Facebook.WitAi.Tests.ConnectionTest.OnError(), Facebook.WitAi.Tests.TestErrorCode.OnError(), Facebook.WitAi.Tests.Message1024BoundaryTest.OnResponse(), and Facebook.WitAi.Tests.TestErrorCode.OnResponse().
TestPassed()
void Facebook.WitAi.Tests.ConnectionTest.TestPassed ()
Referenced by Facebook.WitAi.Tests.TestErrorCode.OnError(), and Facebook.WitAi.Tests.Message1024BoundaryTest.OnResponse().
Member Data Documentation
endpoint
string Facebook.WitAi.Tests.ConnectionTest.endpoint = WitRequest.WIT_ENDPOINT_SPEECH
Referenced by Facebook.WitAi.Tests.ConnectionTest.OnRequestCreated().
isSlowTest
bool Facebook.WitAi.Tests.ConnectionTest.isSlowTest = false
name
string Facebook.WitAi.Tests.ConnectionTest.name protected
Property Documentation
IsSlowTest
bool Facebook.WitAi.Tests.ConnectionTest.IsSlowTest get
Name
virtual string Facebook.WitAi.Tests.ConnectionTest.Name get set
Success
virtual bool Facebook.WitAi.Tests.ConnectionTest.Success = false get protected set
Referenced by Facebook.WitAi.Tests.ConnectionTest.Reset(), Facebook.WitAi.Tests.End2EndTests.TestConnection(), Facebook.WitAi.Tests.ConnectionTest.TestFailed(), and Facebook.WitAi.Tests.ConnectionTest.TestPassed().
TestComplete
virtual bool Facebook.WitAi.Tests.ConnectionTest.TestComplete = false get protected set
Referenced by Facebook.WitAi.Tests.ConnectionTest.OnRequestCompleted(), and Facebook.WitAi.Tests.ConnectionTest.Reset().
TestEndpoint
string Facebook.WitAi.Tests.ConnectionTest.TestEndpoint get set abstract
TestResult
virtual string Facebook.WitAi.Tests.ConnectionTest.TestResult = "" get protected set
Referenced by Facebook.WitAi.Tests.ConnectionTest.TestFailed().
The documentation for this class was generated from the following file:
C:/Users/Lykos/Desktop/Projects/Capstone/VRGames/Assets/ThirdParty/Oculus/Voice/Lib/Wit.ai/Tests/Runtime/End2EndTests/ConnectionTest.cs