VRGames: UnityEngine.ProBuilder.Poly2Tri.DelaunayTriangle Class Reference
UnityEngine.ProBuilder.Poly2Tri.DelaunayTriangle Class Reference
Public Member Functions
DelaunayTriangle (TriangulationPoint p1, TriangulationPoint p2, TriangulationPoint p3)
int IndexOf (TriangulationPoint p)
int IndexCWFrom (TriangulationPoint p)
int IndexCCWFrom (TriangulationPoint p)
bool Contains (TriangulationPoint p)
void MarkNeighbor (DelaunayTriangle t)
Exhaustive search to update neighbor pointers.
TriangulationPoint OppositePoint (DelaunayTriangle t, TriangulationPoint p)
DelaunayTriangle NeighborCWFrom (TriangulationPoint point)
DelaunayTriangle NeighborCCWFrom (TriangulationPoint point)
DelaunayTriangle NeighborAcrossFrom (TriangulationPoint point)
TriangulationPoint PointCCWFrom (TriangulationPoint point)
TriangulationPoint PointCWFrom (TriangulationPoint point)
void Legalize (TriangulationPoint oPoint, TriangulationPoint nPoint)
Legalize triangle by rotating clockwise around oPoint.
override string ToString ()
void MarkNeighborEdges ()
Finalize edge marking.
void MarkEdge (DelaunayTriangle triangle)
void MarkEdge (List< DelaunayTriangle > tList)
void MarkConstrainedEdge (int index)
void MarkConstrainedEdge (DTSweepConstraint edge)
void MarkConstrainedEdge (TriangulationPoint p, TriangulationPoint q)
Mark edge as constrained.
double Area ()
TriangulationPoint Centroid ()
int EdgeIndex (TriangulationPoint p1, TriangulationPoint p2)
Get the index of the neighbor that shares this edge (or -1 if it isn't shared)
bool GetConstrainedEdgeCCW (TriangulationPoint p)
bool GetConstrainedEdgeCW (TriangulationPoint p)
bool GetConstrainedEdgeAcross (TriangulationPoint p)
void SetConstrainedEdgeCCW (TriangulationPoint p, bool ce)
void SetConstrainedEdgeCW (TriangulationPoint p, bool ce)
void SetConstrainedEdgeAcross (TriangulationPoint p, bool ce)
bool GetDelaunayEdgeCCW (TriangulationPoint p)
bool GetDelaunayEdgeCW (TriangulationPoint p)
bool GetDelaunayEdgeAcross (TriangulationPoint p)
void SetDelaunayEdgeCCW (TriangulationPoint p, bool ce)
void SetDelaunayEdgeCW (TriangulationPoint p, bool ce)
void SetDelaunayEdgeAcross (TriangulationPoint p, bool ce)
Public Attributes
FixedArray3< TriangulationPoint > Points
FixedArray3< DelaunayTriangle > Neighbors
FixedBitArray3 EdgeIsConstrained
FixedBitArray3 EdgeIsDelaunay
Properties
bool IsInterior [get, set]
Constructor & Destructor Documentation
DelaunayTriangle()
UnityEngine.ProBuilder.Poly2Tri.DelaunayTriangle.DelaunayTriangle (TriangulationPoint p1, TriangulationPoint p2, TriangulationPoint p3)
Member Function Documentation
Area()
double UnityEngine.ProBuilder.Poly2Tri.DelaunayTriangle.Area ()
Centroid()
TriangulationPoint UnityEngine.ProBuilder.Poly2Tri.DelaunayTriangle.Centroid ()
Contains()
bool UnityEngine.ProBuilder.Poly2Tri.DelaunayTriangle.Contains (TriangulationPoint p)
Referenced by UnityEngine.ProBuilder.Poly2Tri.DelaunayTriangle.MarkNeighbor().
EdgeIndex()
int UnityEngine.ProBuilder.Poly2Tri.DelaunayTriangle.EdgeIndex (TriangulationPoint p1, TriangulationPoint p2)
Get the index of the neighbor that shares this edge (or -1 if it isn't shared)
Returns
index of the shared edge or -1 if edge isn't shared
Referenced by UnityEngine.ProBuilder.Poly2Tri.DelaunayTriangle.MarkConstrainedEdge().
GetConstrainedEdgeAcross()
bool UnityEngine.ProBuilder.Poly2Tri.DelaunayTriangle.GetConstrainedEdgeAcross (TriangulationPoint p)
GetConstrainedEdgeCCW()
bool UnityEngine.ProBuilder.Poly2Tri.DelaunayTriangle.GetConstrainedEdgeCCW (TriangulationPoint p)
GetConstrainedEdgeCW()
bool UnityEngine.ProBuilder.Poly2Tri.DelaunayTriangle.GetConstrainedEdgeCW (TriangulationPoint p)
GetDelaunayEdgeAcross()
bool UnityEngine.ProBuilder.Poly2Tri.DelaunayTriangle.GetDelaunayEdgeAcross (TriangulationPoint p)
GetDelaunayEdgeCCW()
bool UnityEngine.ProBuilder.Poly2Tri.DelaunayTriangle.GetDelaunayEdgeCCW (TriangulationPoint p)
GetDelaunayEdgeCW()
bool UnityEngine.ProBuilder.Poly2Tri.DelaunayTriangle.GetDelaunayEdgeCW (TriangulationPoint p)
IndexCCWFrom()
int UnityEngine.ProBuilder.Poly2Tri.DelaunayTriangle.IndexCCWFrom (TriangulationPoint p)
Referenced by UnityEngine.ProBuilder.Poly2Tri.DelaunayTriangle.Legalize().
IndexCWFrom()
int UnityEngine.ProBuilder.Poly2Tri.DelaunayTriangle.IndexCWFrom (TriangulationPoint p)
IndexOf()
int UnityEngine.ProBuilder.Poly2Tri.DelaunayTriangle.IndexOf (TriangulationPoint p)
Referenced by UnityEngine.ProBuilder.Poly2Tri.DelaunayTriangle.GetConstrainedEdgeAcross(), UnityEngine.ProBuilder.Poly2Tri.DelaunayTriangle.GetConstrainedEdgeCCW(), UnityEngine.ProBuilder.Poly2Tri.DelaunayTriangle.GetConstrainedEdgeCW(), UnityEngine.ProBuilder.Poly2Tri.DelaunayTriangle.GetDelaunayEdgeAcross(), UnityEngine.ProBuilder.Poly2Tri.DelaunayTriangle.GetDelaunayEdgeCCW(), UnityEngine.ProBuilder.Poly2Tri.DelaunayTriangle.GetDelaunayEdgeCW(), UnityEngine.ProBuilder.Poly2Tri.DelaunayTriangle.IndexCCWFrom(), UnityEngine.ProBuilder.Poly2Tri.DelaunayTriangle.IndexCWFrom(), UnityEngine.ProBuilder.Poly2Tri.DelaunayTriangle.PointCCWFrom(), UnityEngine.ProBuilder.Poly2Tri.DelaunayTriangle.PointCWFrom(), UnityEngine.ProBuilder.Poly2Tri.DelaunayTriangle.SetConstrainedEdgeAcross(), UnityEngine.ProBuilder.Poly2Tri.DelaunayTriangle.SetConstrainedEdgeCCW(), UnityEngine.ProBuilder.Poly2Tri.DelaunayTriangle.SetConstrainedEdgeCW(), UnityEngine.ProBuilder.Poly2Tri.DelaunayTriangle.SetDelaunayEdgeAcross(), UnityEngine.ProBuilder.Poly2Tri.DelaunayTriangle.SetDelaunayEdgeCCW(), and UnityEngine.ProBuilder.Poly2Tri.DelaunayTriangle.SetDelaunayEdgeCW().
Legalize()
void UnityEngine.ProBuilder.Poly2Tri.DelaunayTriangle.Legalize (TriangulationPoint oPoint, TriangulationPoint nPoint)
Legalize triangle by rotating clockwise around oPoint.
Parameters
oPoint The origin point to rotate around
nPoint ???
MarkConstrainedEdge() [1/3]
void UnityEngine.ProBuilder.Poly2Tri.DelaunayTriangle.MarkConstrainedEdge (DTSweepConstraint edge)
MarkConstrainedEdge() [2/3]
void UnityEngine.ProBuilder.Poly2Tri.DelaunayTriangle.MarkConstrainedEdge (int index)
Referenced by UnityEngine.ProBuilder.Poly2Tri.DelaunayTriangle.MarkConstrainedEdge(), UnityEngine.ProBuilder.Poly2Tri.DelaunayTriangle.MarkEdge(), and UnityEngine.ProBuilder.Poly2Tri.DelaunayTriangle.MarkEdge().
MarkConstrainedEdge() [3/3]
void UnityEngine.ProBuilder.Poly2Tri.DelaunayTriangle.MarkConstrainedEdge (TriangulationPoint p, TriangulationPoint q)
Mark edge as constrained.
MarkEdge() [1/2]
void UnityEngine.ProBuilder.Poly2Tri.DelaunayTriangle.MarkEdge (DelaunayTriangle triangle)
MarkEdge() [2/2]
void UnityEngine.ProBuilder.Poly2Tri.DelaunayTriangle.MarkEdge (List< DelaunayTriangle > tList)
MarkNeighbor()
void UnityEngine.ProBuilder.Poly2Tri.DelaunayTriangle.MarkNeighbor (DelaunayTriangle t)
Exhaustive search to update neighbor pointers.
MarkNeighborEdges()
void UnityEngine.ProBuilder.Poly2Tri.DelaunayTriangle.MarkNeighborEdges ()
Finalize edge marking.
NeighborAcrossFrom()
DelaunayTriangle UnityEngine.ProBuilder.Poly2Tri.DelaunayTriangle.NeighborAcrossFrom (TriangulationPoint point)
NeighborCCWFrom()
DelaunayTriangle UnityEngine.ProBuilder.Poly2Tri.DelaunayTriangle.NeighborCCWFrom (TriangulationPoint point)
NeighborCWFrom()
DelaunayTriangle UnityEngine.ProBuilder.Poly2Tri.DelaunayTriangle.NeighborCWFrom (TriangulationPoint point)
OppositePoint()
TriangulationPoint UnityEngine.ProBuilder.Poly2Tri.DelaunayTriangle.OppositePoint (DelaunayTriangle t, TriangulationPoint p)
Parameters
t Opposite triangle
p The point in t that isn't shared between the triangles
PointCCWFrom()
TriangulationPoint UnityEngine.ProBuilder.Poly2Tri.DelaunayTriangle.PointCCWFrom (TriangulationPoint point)
PointCWFrom()
TriangulationPoint UnityEngine.ProBuilder.Poly2Tri.DelaunayTriangle.PointCWFrom (TriangulationPoint point)
Referenced by UnityEngine.ProBuilder.Poly2Tri.DTSweepContext.MapTriangleToNodes(), and UnityEngine.ProBuilder.Poly2Tri.DelaunayTriangle.OppositePoint().
SetConstrainedEdgeAcross()
void UnityEngine.ProBuilder.Poly2Tri.DelaunayTriangle.SetConstrainedEdgeAcross (TriangulationPoint p, bool ce)
SetConstrainedEdgeCCW()
void UnityEngine.ProBuilder.Poly2Tri.DelaunayTriangle.SetConstrainedEdgeCCW (TriangulationPoint p, bool ce)
SetConstrainedEdgeCW()
void UnityEngine.ProBuilder.Poly2Tri.DelaunayTriangle.SetConstrainedEdgeCW (TriangulationPoint p, bool ce)
SetDelaunayEdgeAcross()
void UnityEngine.ProBuilder.Poly2Tri.DelaunayTriangle.SetDelaunayEdgeAcross (TriangulationPoint p, bool ce)
SetDelaunayEdgeCCW()
void UnityEngine.ProBuilder.Poly2Tri.DelaunayTriangle.SetDelaunayEdgeCCW (TriangulationPoint p, bool ce)
SetDelaunayEdgeCW()
void UnityEngine.ProBuilder.Poly2Tri.DelaunayTriangle.SetDelaunayEdgeCW (TriangulationPoint p, bool ce)
ToString()
override string UnityEngine.ProBuilder.Poly2Tri.DelaunayTriangle.ToString ()
Member Data Documentation
EdgeIsConstrained
FixedBitArray3 UnityEngine.ProBuilder.Poly2Tri.DelaunayTriangle.EdgeIsConstrained
Referenced by UnityEngine.ProBuilder.Poly2Tri.DelaunayTriangle.GetConstrainedEdgeAcross(), UnityEngine.ProBuilder.Poly2Tri.DelaunayTriangle.GetConstrainedEdgeCCW(), UnityEngine.ProBuilder.Poly2Tri.DelaunayTriangle.GetConstrainedEdgeCW(), UnityEngine.ProBuilder.Poly2Tri.DelaunayTriangle.MarkConstrainedEdge(), UnityEngine.ProBuilder.Poly2Tri.DelaunayTriangle.MarkConstrainedEdge(), UnityEngine.ProBuilder.Poly2Tri.DelaunayTriangle.MarkEdge(), UnityEngine.ProBuilder.Poly2Tri.DelaunayTriangle.MarkEdge(), UnityEngine.ProBuilder.Poly2Tri.DelaunayTriangle.MarkNeighborEdges(), UnityEngine.ProBuilder.Poly2Tri.DelaunayTriangle.SetConstrainedEdgeAcross(), UnityEngine.ProBuilder.Poly2Tri.DelaunayTriangle.SetConstrainedEdgeCCW(), and UnityEngine.ProBuilder.Poly2Tri.DelaunayTriangle.SetConstrainedEdgeCW().
EdgeIsDelaunay
FixedBitArray3 UnityEngine.ProBuilder.Poly2Tri.DelaunayTriangle.EdgeIsDelaunay
Referenced by UnityEngine.ProBuilder.Poly2Tri.DelaunayTriangle.GetDelaunayEdgeAcross(), UnityEngine.ProBuilder.Poly2Tri.DelaunayTriangle.GetDelaunayEdgeCCW(), UnityEngine.ProBuilder.Poly2Tri.DelaunayTriangle.GetDelaunayEdgeCW(), UnityEngine.ProBuilder.Poly2Tri.DelaunayTriangle.SetDelaunayEdgeAcross(), UnityEngine.ProBuilder.Poly2Tri.DelaunayTriangle.SetDelaunayEdgeCCW(), and UnityEngine.ProBuilder.Poly2Tri.DelaunayTriangle.SetDelaunayEdgeCW().
Neighbors
FixedArray3<DelaunayTriangle > UnityEngine.ProBuilder.Poly2Tri.DelaunayTriangle.Neighbors
Referenced by UnityEngine.ProBuilder.Poly2Tri.DTSweepContext.MapTriangleToNodes(), UnityEngine.ProBuilder.Poly2Tri.DelaunayTriangle.MarkNeighbor(), UnityEngine.ProBuilder.Poly2Tri.DelaunayTriangle.MarkNeighborEdges(), UnityEngine.ProBuilder.Poly2Tri.DelaunayTriangle.NeighborAcrossFrom(), UnityEngine.ProBuilder.Poly2Tri.DelaunayTriangle.NeighborCCWFrom(), and UnityEngine.ProBuilder.Poly2Tri.DelaunayTriangle.NeighborCWFrom().
Points
FixedArray3<TriangulationPoint> UnityEngine.ProBuilder.Poly2Tri.DelaunayTriangle.Points
Referenced by UnityEngine.ProBuilder.Poly2Tri.DelaunayTriangle.Area(), UnityEngine.ProBuilder.Poly2Tri.DelaunayTriangle.Centroid(), UnityEngine.ProBuilder.Poly2Tri.DelaunayTriangle.Contains(), UnityEngine.ProBuilder.Poly2Tri.DTSweepContext.CreateAdvancingFront(), UnityEngine.ProBuilder.Poly2Tri.DelaunayTriangle.DelaunayTriangle(), UnityEngine.ProBuilder.Poly2Tri.DelaunayTriangle.EdgeIndex(), UnityEngine.ProBuilder.Poly2Tri.DelaunayTriangle.IndexOf(), UnityEngine.ProBuilder.Poly2Tri.DelaunayTriangle.Legalize(), UnityEngine.ProBuilder.Poly2Tri.DTSweepContext.MapTriangleToNodes(), UnityEngine.ProBuilder.Poly2Tri.DelaunayTriangle.MarkEdge(), UnityEngine.ProBuilder.Poly2Tri.DelaunayTriangle.MarkEdge(), UnityEngine.ProBuilder.Poly2Tri.DelaunayTriangle.MarkNeighbor(), UnityEngine.ProBuilder.Poly2Tri.DelaunayTriangle.MarkNeighborEdges(), UnityEngine.ProBuilder.Poly2Tri.DelaunayTriangle.NeighborAcrossFrom(), UnityEngine.ProBuilder.Poly2Tri.DelaunayTriangle.NeighborCCWFrom(), UnityEngine.ProBuilder.Poly2Tri.DelaunayTriangle.NeighborCWFrom(), UnityEngine.ProBuilder.Poly2Tri.DelaunayTriangle.PointCCWFrom(), UnityEngine.ProBuilder.Poly2Tri.DelaunayTriangle.PointCWFrom(), and UnityEngine.ProBuilder.Poly2Tri.DelaunayTriangle.ToString().
Property Documentation
IsInterior
bool UnityEngine.ProBuilder.Poly2Tri.DelaunayTriangle.IsInterior get set
The documentation for this class was generated from the following file:
C:/Users/Lykos/Desktop/Projects/Capstone/VRGames/Library/PackageCache/com.unity.probuilder@5.0.6/External/Poly2Tri/Triangulation/Delaunay/DelaunayTriangle.cs