VRCapstoneGames: UnityEditor.ProBuilder.TooltipEditor Class Reference
UnityEditor.ProBuilder.TooltipEditor Class Reference sealed
Tooltip window implementation.
Public Member Functions
void ShowInternal (Rect rect, TooltipContent content)
Static Public Member Functions
static TooltipEditor instance ()
static void Hide ()
static bool IsFocused ()
static void Show (Rect rect, TooltipContent content)
Public Attributes
TooltipContent content = null
Detailed Description
Tooltip window implementation.
Member Function Documentation
Hide()
static void UnityEditor.ProBuilder.TooltipEditor.Hide () static
Referenced by UnityEditor.ProBuilder.EditorToolbar.OnGUI().
instance()
static TooltipEditor UnityEditor.ProBuilder.TooltipEditor.instance () static
Referenced by UnityEditor.ProBuilder.TooltipEditor.Show().
IsFocused()
static bool UnityEditor.ProBuilder.TooltipEditor.IsFocused () static
Referenced by UnityEditor.ProBuilder.EditorToolbar.OnGUI().
Show()
static void UnityEditor.ProBuilder.TooltipEditor.Show (Rect rect, TooltipContent content) static
ShowInternal()
void UnityEditor.ProBuilder.TooltipEditor.ShowInternal (Rect rect, TooltipContent content)
Member Data Documentation
content
TooltipContent UnityEditor.ProBuilder.TooltipEditor.content = null
Referenced by UnityEditor.ProBuilder.TooltipEditor.Show(), and UnityEditor.ProBuilder.TooltipEditor.ShowInternal().
The documentation for this class was generated from the following file:
C:/Users/Lykos/Desktop/Projects/Capstone/VRGames/Library/PackageCache/com.unity.probuilder@5.0.6/Editor/EditorCore/TooltipEditor.cs