VRCapstoneGames: Oculus.Interaction.HandPosing.SnapSurfaces.BoxSurfaceData Class Reference
Oculus.Interaction.HandPosing.SnapSurfaces.BoxSurfaceData Class Reference
Public Member Functions
object Clone ()
BoxSurfaceData Mirror ()
Public Attributes
float widthOffset = 0.5f
Vector4 snapOffset
Vector3 size = new Vector3(0.1f, 0f, 0.1f)
Vector3 eulerAngles
Member Function Documentation
Clone()
object Oculus.Interaction.HandPosing.SnapSurfaces.BoxSurfaceData.Clone ()
Referenced by Oculus.Interaction.HandPosing.SnapSurfaces.BoxSurfaceData.Mirror().
Mirror()
BoxSurfaceData Oculus.Interaction.HandPosing.SnapSurfaces.BoxSurfaceData.Mirror ()
Referenced by Oculus.Interaction.HandPosing.SnapSurfaces.BoxSurface.CreateMirroredSurface().
Member Data Documentation
eulerAngles
Vector3 Oculus.Interaction.HandPosing.SnapSurfaces.BoxSurfaceData.eulerAngles
Referenced by Oculus.Interaction.HandPosing.SnapSurfaces.BoxSurfaceData.Clone().
size
Vector3 Oculus.Interaction.HandPosing.SnapSurfaces.BoxSurfaceData.size = new Vector3(0.1f, 0f, 0.1f)
Referenced by Oculus.Interaction.HandPosing.SnapSurfaces.BoxSurfaceData.Clone().
snapOffset
Vector4 Oculus.Interaction.HandPosing.SnapSurfaces.BoxSurfaceData.snapOffset
Referenced by Oculus.Interaction.HandPosing.SnapSurfaces.BoxSurfaceData.Clone(), and Oculus.Interaction.HandPosing.SnapSurfaces.BoxSurfaceData.Mirror().
widthOffset
float Oculus.Interaction.HandPosing.SnapSurfaces.BoxSurfaceData.widthOffset = 0.5f
Referenced by Oculus.Interaction.HandPosing.SnapSurfaces.BoxSurfaceData.Clone().
The documentation for this class was generated from the following file:
C:/Users/Lykos/Desktop/Projects/Capstone/VRGames/Assets/ThirdParty/Oculus/Interaction/Runtime/Scripts/HandPosing/SnapSurfaces/BoxSurface.cs