VRCapstoneGames: UnityEngine.XR.Interaction.Toolkit.ContinuousTurnProviderBase Class Reference
UnityEngine.XR.Interaction.Toolkit.ContinuousTurnProviderBase Class Reference abstract
Locomotion provider that allows the user to smoothly rotate their rig continuously over time.
Protected Member Functions
void Update ()
See MonoBehaviour.
Vector2 ReadInput ()
Reads the current value of the turn input.
virtual float GetTurnAmount (Vector2 input)
Determines the turn amount in degrees for the given input vector.
void TurnRig (float turnAmount)
Rotates the rig by turnAmount degrees.
Protected Member Functions inherited from UnityEngine.XR.Interaction.Toolkit.LocomotionProvider
virtual void Awake ()
See MonoBehaviour.
bool CanBeginLocomotion ()
Checks if locomotion can begin.
bool BeginLocomotion ()
Invokes begin locomotion events.
bool EndLocomotion ()
Invokes end locomotion events.
Properties
float turnSpeed [get, set]
The number of degrees/second clockwise to rotate when turning clockwise.
Properties inherited from UnityEngine.XR.Interaction.Toolkit.LocomotionProvider
LocomotionSystem system [get, set]
The LocomotionSystem that this LocomotionProvider communicates with for exclusive access to an XR Origin. If one is not provided, the behavior will attempt to locate one during its Awake call.
Additional Inherited Members
Events inherited from UnityEngine.XR.Interaction.Toolkit.LocomotionProvider
Action< LocomotionSystem > beginLocomotion
Unity calls the beginLocomotion action when a LocomotionProvider successfully begins a locomotion event.
Action< LocomotionSystem > endLocomotion
Unity calls the endLocomotion action when a LocomotionProvider successfully ends a locomotion event.
Action< LocomotionSystem > startLocomotion
(Deprecated) The startLocomotion action will be called when a LocomotionProvider successfully begins a locomotion event.
Detailed Description
Locomotion provider that allows the user to smoothly rotate their rig continuously over time.
See also
LocomotionProvider, SnapTurnProviderBase
Member Function Documentation
GetTurnAmount()
virtual float UnityEngine.XR.Interaction.Toolkit.ContinuousTurnProviderBase.GetTurnAmount (Vector2 input) protected virtual
Determines the turn amount in degrees for the given input vector.
Parameters
input Input vector, such as from a thumbstick.
Returns
Returns the turn amount in degrees for the given input vector.
Referenced by UnityEngine.XR.Interaction.Toolkit.ContinuousTurnProviderBase.Update().
ReadInput()
Vector2 UnityEngine.XR.Interaction.Toolkit.ContinuousTurnProviderBase.ReadInput () abstract protected
Reads the current value of the turn input.
Returns
Returns the input vector, such as from a thumbstick.
Referenced by UnityEngine.XR.Interaction.Toolkit.ContinuousTurnProviderBase.Update().
TurnRig()
void UnityEngine.XR.Interaction.Toolkit.ContinuousTurnProviderBase.TurnRig (float turnAmount) protected
Rotates the rig by turnAmount degrees.
Parameters
turnAmount The amount of rotation in degrees.
Referenced by UnityEngine.XR.Interaction.Toolkit.ContinuousTurnProviderBase.Update().
Update()
void UnityEngine.XR.Interaction.Toolkit.ContinuousTurnProviderBase.Update () protected
See MonoBehaviour.
Property Documentation
turnSpeed
float UnityEngine.XR.Interaction.Toolkit.ContinuousTurnProviderBase.turnSpeed get set
The number of degrees/second clockwise to rotate when turning clockwise.
The documentation for this class was generated from the following file:
C:/Users/Lykos/Desktop/Projects/Capstone/VRGames/Library/PackageCache/com.unity.xr.interaction.toolkit@2.0.2/Runtime/Locomotion/Continuous/ContinuousTurnProviderBase.cs