VRCapstoneGames: UnityEngine.XR.Interaction.Toolkit.XRBaseControllerInteractor Class Reference
UnityEngine.XR.Interaction.Toolkit.XRBaseControllerInteractor Class Reference abstract
Abstract base class from which all interactors that are controller-driven derive. This class hooks into the interaction system (via XRInteractionManager) and provides base virtual methods for handling hover and selection. Additionally, this class provides functionality for checking the controller's selection status and hiding the controller on selection.
Public Types
enum InputTriggerType { State , StateChange , Toggle , Sticky }
This defines the type of input that triggers an interaction.
Public Member Functions
override void PreprocessInteractor (XRInteractionUpdateOrder.UpdatePhase updatePhase)
The XRInteractionManager calls this method to update the Interactor before interaction events occur. Interactors should use this method to do tasks like determine their valid targets.
Parameters
updatePhase The update phase this is called during.
Please see the XRInteractionManager and XRInteractionUpdateOrder.UpdatePhase documentation for more details on update order.
override void ProcessInteractor (XRInteractionUpdateOrder.UpdatePhase updatePhase)
The XRInteractionManager calls this method to update the Interactor after interaction events occur.
Parameters
updatePhase The update phase this is called during.
Please see the XRInteractionManager and XRInteractionUpdateOrder.UpdatePhase documentation for more details on update order.
virtual void GetActivateTargets (List< IXRActivateInteractable > targets)
Retrieve the list of Interactables that this Interactor could possibly activate or deactivate this frame.
Parameters
targets The results list to populate with Interactables that are valid for activate or deactivate.
When implementing this method, Unity expects you to clear targets before adding to it.
bool SendHapticImpulse (float amplitude, float duration)
Play a haptic impulse on the controller if one is available.
Public Member Functions inherited from UnityEngine.XR.Interaction.Toolkit.XRBaseInteractor
virtual Transform GetAttachTransform (IXRInteractable interactable)
Gets the Transform that is used as the attachment point for a given Interactable.
Parameters
interactable The specific Interactable as context to get the attachment point for.
Returns
Returns the attachment point Transform.
See also
IXRInteractable.GetAttachTransform
This should typically return the Transform of a child GameObject or the transform itself.
Pose GetAttachPoseOnSelect (IXRSelectInteractable interactable)
Gets the world position and rotation of the Attach Transform captured during the moment of selection.
Parameters
interactable The specific Interactable as context to get the attachment point for.
Returns
Returns the world pose of the attachment point during the moment of selection, and otherwise the identity Pose if it was not selected during the current selection stack.
See also
GetLocalAttachPoseOnSelect, IXRInteractor.GetAttachTransform, IXRSelectInteractable.GetAttachPoseOnSelect
Pose GetLocalAttachPoseOnSelect (IXRSelectInteractable interactable)
Gets the local position and rotation of the Attach Transform captured during the moment of selection.
Parameters
interactable The specific Interactable as context to get the attachment point for.
Returns
Returns the local pose of the attachment point during the moment of selection, and otherwise the identity Pose if it was not selected during the current selection stack.
See also
GetAttachPoseOnSelect, IXRInteractor.GetAttachTransform, IXRSelectInteractable.GetLocalAttachPoseOnSelect
virtual void GetValidTargets (List< IXRInteractable > targets)
Retrieve the list of Interactables that this Interactor could possibly interact with this frame. This list is sorted by priority (with highest priority first).
Parameters
targets The results list to populate with Interactables that are valid for selection or hover.
When implementing this method, Unity expects you to clear targets before adding to it.
virtual bool CanHover (IXRHoverInteractable interactable)
Determines if the Interactable is valid for hover this frame.
virtual bool CanSelect (IXRSelectInteractable interactable)
Determines if the Interactable is valid for selection this frame.
bool IsHovering (IXRHoverInteractable interactable)
Determines whether this Interactor is currently hovering the Interactable.
Parameters
interactable Interactable to check.
Returns
Returns true if this Interactor is currently hovering the Interactable. Otherwise, returns .
In other words, returns whether interactablesHovered contains interactable .
bool IsSelecting (IXRSelectInteractable interactable)
Determines whether this Interactor is currently selecting the Interactable.
Parameters
interactable Interactable to check.
Returns
Returns true if this Interactor is currently selecting the Interactable. Otherwise, returns .
In other words, returns whether interactablesSelected contains interactable .
virtual void StartManualInteraction (IXRSelectInteractable interactable)
Manually initiate selection of an Interactable.
virtual void EndManualInteraction ()
Ends the manually initiated selection of an Interactable.
void GetHoverTargets (List< XRBaseInteractable > targets)
Retrieves a copy of the list of target Interactables that are currently being hovered over.
virtual void GetValidTargets (List< XRBaseInteractable > targets)
Retrieve the list of Interactables that this Interactor could possibly interact with this frame. This list is sorted by priority (with highest priority first).
virtual bool CanHover (XRBaseInteractable interactable)
Determines if the Interactable is valid for hover this frame.
virtual bool CanSelect (XRBaseInteractable interactable)
Determines if the Interactable is valid for selection this frame.
virtual void StartManualInteraction (XRBaseInteractable interactable)
Manually initiate selection of an Interactable.
Protected Member Functions
override void Awake ()
See MonoBehaviour.
override void OnSelectEntering (SelectEnterEventArgs args)
The XRInteractionManager calls this method right before the Interactor first initiates selection of an Interactable in a first pass.
Parameters
args Event data containing the Interactable that is being selected.
args is only valid during this method call, do not hold a reference to it.
override void OnSelectExiting (SelectExitEventArgs args)
The XRInteractionManager calls this method right before the Interactor ends selection of an Interactable in a first pass.
Parameters
args Event data containing the Interactable that is no longer selected.
args is only valid during this method call, do not hold a reference to it.
override void OnHoverEntering (HoverEnterEventArgs args)
The XRInteractionManager calls this method right before the Interactor first initiates hovering over an Interactable in a first pass.
Parameters
args Event data containing the Interactable that is being hovered over.
args is only valid during this method call, do not hold a reference to it.
override void OnHoverExiting (HoverExitEventArgs args)
The XRInteractionManager calls this method right before the Interactor ends hovering over an Interactable in a first pass.
Parameters
args Event data containing the Interactable that is no longer hovered over.
args is only valid during this method call, do not hold a reference to it.
virtual void PlayAudio (AudioClip audioClip)
Play an AudioClip.
Protected Member Functions inherited from UnityEngine.XR.Interaction.Toolkit.XRBaseInteractor
virtual void Reset ()
See MonoBehaviour.
virtual void OnEnable ()
See MonoBehaviour.
virtual void OnDisable ()
See MonoBehaviour.
virtual void Start ()
See MonoBehaviour.
virtual void OnDestroy ()
See MonoBehaviour.
bool IsHovering (IXRInteractable interactable)
Determines whether this Interactor is currently hovering the Interactable.
bool IsSelecting (IXRInteractable interactable)
Determines whether this Interactor is currently selecting the Interactable.
void CaptureAttachPose (IXRSelectInteractable interactable)
Capture the current Attach Transform pose. This method is automatically called by Unity to capture the pose during the moment of selection.
virtual void OnRegistered (InteractorRegisteredEventArgs args)
The XRInteractionManager calls this method when this Interactor is registered with it.
virtual void OnUnregistered (InteractorUnregisteredEventArgs args)
The XRInteractionManager calls this method when this Interactor is unregistered from it.
virtual void OnHoverEntered (HoverEnterEventArgs args)
The XRInteractionManager calls this method when the Interactor first initiates hovering over an Interactable in a second pass.
virtual void OnHoverExited (HoverExitEventArgs args)
The XRInteractionManager calls this method when the Interactor ends hovering over an Interactable in a second pass.
virtual void OnSelectEntered (SelectEnterEventArgs args)
The XRInteractionManager calls this method when the Interactor first initiates selection of an Interactable in a second pass.
virtual void OnSelectExited (SelectExitEventArgs args)
The XRInteractionManager calls this method when the Interactor ends selection of an Interactable in a second pass.
virtual void OnHoverEntering (XRBaseInteractable interactable)
(Deprecated) The XRInteractionManager calls this method right before the Interactor first initiates hovering over an Interactable in a first pass.
virtual void OnHoverEntered (XRBaseInteractable interactable)
(Deprecated) The XRInteractionManager calls this method when the Interactor first initiates hovering over an Interactable in a second pass.
virtual void OnHoverExiting (XRBaseInteractable interactable)
(Deprecated) The XRInteractionManager calls this method right before the Interactor ends hovering over an Interactable in a first pass.
virtual void OnHoverExited (XRBaseInteractable interactable)
(Deprecated) The XRInteractionManager calls this method when the Interactor ends hovering over an Interactable in a second pass.
virtual void OnSelectEntering (XRBaseInteractable interactable)
(Deprecated) The XRInteractionManager calls this method right before the Interactor first initiates selection of an Interactable in a first pass.
virtual void OnSelectEntered (XRBaseInteractable interactable)
(Deprecated) The XRInteractionManager calls this method when the Interactor first initiates selection of an Interactable in a second pass.
virtual void OnSelectExiting (XRBaseInteractable interactable)
(Deprecated) The XRInteractionManager calls this method right before the Interactor ends selection of an Interactable in a first pass.
virtual void OnSelectExited (XRBaseInteractable interactable)
(Deprecated) The XRInteractionManager calls this method when the Interactor ends selection of an Interactable in a second pass.
Properties
InputTriggerType selectActionTrigger [get, set]
Choose how Unity interprets the select input action from the controller. Controls between different input styles for determining if this Interactor can select, such as whether the button is currently pressed or just toggles the active state.
bool hideControllerOnSelect [get, set]
Controls whether this Interactor should hide the controller model on selection.
bool allowHoveredActivate [get, set]
Controls whether to send activate and deactivate events to interactables that this interactor is hovered over but not selected when there is no current selection. By default, the interactor will only send activate and deactivate events to interactables that it's selected.
bool playAudioClipOnSelectEntered [get, set]
Controls whether Unity plays an AudioClip on Select Entered.
AudioClip audioClipForOnSelectEntered [get, set]
The AudioClip Unity plays on Select Entered.
bool playAudioClipOnSelectExited [get, set]
Controls whether Unity plays an AudioClip on Select Exited.
AudioClip audioClipForOnSelectExited [get, set]
The AudioClip Unity plays on Select Exited.
bool playAudioClipOnSelectCanceled [get, set]
Controls whether Unity plays an AudioClip on Select Canceled.
AudioClip audioClipForOnSelectCanceled [get, set]
The AudioClip Unity plays on Select Canceled.
bool playAudioClipOnHoverEntered [get, set]
Controls whether Unity plays an AudioClip on Hover Entered.
AudioClip audioClipForOnHoverEntered [get, set]
The AudioClip Unity plays on Hover Entered.
bool playAudioClipOnHoverExited [get, set]
Controls whether Unity plays an AudioClip on Hover Exited.
AudioClip audioClipForOnHoverExited [get, set]
The AudioClip Unity plays on Hover Exited.
bool playAudioClipOnHoverCanceled [get, set]
Controls whether Unity plays an AudioClip on Hover Canceled.
AudioClip audioClipForOnHoverCanceled [get, set]
The AudioClip Unity plays on Hover Canceled.
bool playHapticsOnSelectEntered [get, set]
Controls whether Unity plays haptics on Select Entered.
float hapticSelectEnterIntensity [get, set]
The Haptics intensity Unity plays on Select Entered.
float hapticSelectEnterDuration [get, set]
The Haptics duration (in seconds) Unity plays on Select Entered.
bool playHapticsOnSelectExited [get, set]
Controls whether Unity plays haptics on Select Exited.
float hapticSelectExitIntensity [get, set]
The Haptics intensity Unity plays on Select Exited.
float hapticSelectExitDuration [get, set]
The Haptics duration (in seconds) Unity plays on Select Exited.
bool playHapticsOnSelectCanceled [get, set]
Controls whether Unity plays haptics on Select Canceled.
float hapticSelectCancelIntensity [get, set]
The Haptics intensity Unity plays on Select Canceled.
float hapticSelectCancelDuration [get, set]
The Haptics duration (in seconds) Unity plays on Select Canceled.
bool playHapticsOnHoverEntered [get, set]
Controls whether Unity plays haptics on Hover Entered.
float hapticHoverEnterIntensity [get, set]
The Haptics intensity Unity plays on Hover Entered.
float hapticHoverEnterDuration [get, set]
The Haptics duration (in seconds) Unity plays on Hover Entered.
bool playHapticsOnHoverExited [get, set]
Controls whether Unity plays haptics on Hover Exited.
float hapticHoverExitIntensity [get, set]
The Haptics intensity Unity plays on Hover Exited.
float hapticHoverExitDuration [get, set]
The Haptics duration (in seconds) Unity plays on Hover Exited.
bool playHapticsOnHoverCanceled [get, set]
Controls whether Unity plays haptics on Hover Canceled.
float hapticHoverCancelIntensity [get, set]
The Haptics intensity Unity plays on Hover Canceled.
float hapticHoverCancelDuration [get, set]
The Haptics duration (in seconds) Unity plays on Hover Canceled.
bool allowActivate [get, set]
Defines whether this interactor allows sending activate and deactivate events.
XRBaseController xrController [get, set]
The controller instance that is queried for input.
override bool isSelectActive [get]
(Read Only) Indicates whether this Interactor is in a state where it could select.
bool isUISelectActive [get]
(Read Only) Whether or not Unity considers the UI Press controller input pressed.
virtual bool shouldActivate [get]
(Read Only) Indicates whether this interactor is in a state where it should send the activate event this frame.
virtual bool shouldDeactivate [get]
(Read Only) Indicates whether this interactor is in a state where it should send the deactivate event this frame.
bool playAudioClipOnSelectEnter [get]
(Deprecated) Controls whether Unity plays an AudioClip on Select Entered.
AudioClip audioClipForOnSelectEnter [get]
(Deprecated) The AudioClip Unity plays on Select Entered.
AudioClip AudioClipForOnSelectEnter [get, set]
(Deprecated) The AudioClip Unity plays on Select Entered.
bool playAudioClipOnSelectExit [get]
(Deprecated) Controls whether Unity plays an AudioClip on Select Exited.
AudioClip audioClipForOnSelectExit [get]
(Deprecated) The AudioClip Unity plays on Select Exited.
AudioClip AudioClipForOnSelectExit [get, set]
(Deprecated) The AudioClip Unity plays on Select Exited.
bool playAudioClipOnHoverEnter [get]
(Deprecated) Controls whether Unity plays an AudioClip on Hover Entered.
AudioClip audioClipForOnHoverEnter [get]
(Deprecated) The AudioClip Unity plays on Hover Entered.
AudioClip AudioClipForOnHoverEnter [get, set]
(Deprecated) The AudioClip Unity plays on Hover Entered.
bool playAudioClipOnHoverExit [get]
(Deprecated) Controls whether Unity plays an AudioClip on Hover Exited.
AudioClip audioClipForOnHoverExit [get]
(Deprecated) The AudioClip Unity plays on Hover Exited.
AudioClip AudioClipForOnHoverExit [get, set]
(Deprecated) The AudioClip Unity plays on Hover Exited.
bool playHapticsOnSelectEnter [get]
(Deprecated) Controls whether Unity plays haptics on Select Entered.
bool playHapticsOnSelectExit [get]
(Deprecated) Controls whether Unity plays haptics on Select Exited.
bool playHapticsOnHoverEnter [get]
(Deprecated) Controls whether Unity plays haptics on Hover Entered.
virtual List< XRBaseInteractable > validTargets = new List<XRBaseInteractable>() [get]
(Deprecated) (Read Only) A list of Interactables that this Interactor could possibly interact with this frame.
Properties inherited from UnityEngine.XR.Interaction.Toolkit.XRBaseInteractor
XRInteractionManager interactionManager [get, set]
The XRInteractionManager that this Interactor will communicate with (will find one if null).
InteractionLayerMask interactionLayers [get, set]
Allows interaction with Interactables whose Interaction Layer Mask overlaps with any Layer in this Interaction Layer Mask.
Transform attachTransform [get, set]
The Transform that is used as the attach point for Interactables.
bool keepSelectedTargetValid [get, set]
Whether to keep selecting an Interactable after initially selecting it even when it is no longer a valid target.Return true to make the XRInteractionManager retain the selection even if the Interactable is not contained within the list of valid targets. Return false to make the Interaction Manager clear the selection if it isn't within the list of valid targets.
A common use for disabling this is for Ray Interactors used for teleportation to make the teleportation Interactable no longer selected when not currently pointing at it.
XRBaseInteractable startingSelectedInteractable [get, set]
The Interactable that this Interactor automatically selects at startup (optional, may be null).
HoverEnterEvent hoverEntered [get, set]
The event that is called when this Interactor begins hovering over an Interactable.The HoverEnterEventArgs passed to each listener is only valid while the event is invoked, do not hold a reference to it.
HoverExitEvent hoverExited [get, set]
The event that is called when this Interactor ends hovering over an Interactable.The HoverExitEventArgs passed to each listener is only valid while the event is invoked, do not hold a reference to it.
SelectEnterEvent selectEntered [get, set]
The event that is called when this Interactor begins selecting an Interactable.The SelectEnterEventArgs passed to each listener is only valid while the event is invoked, do not hold a reference to it.
SelectExitEvent selectExited [get, set]
The event that is called when this Interactor ends selecting an Interactable.The SelectEnterEventArgs passed to each listener is only valid while the event is invoked, do not hold a reference to it.
bool allowHover [get, set]
Defines whether this interactor allows hover events.
bool allowSelect [get, set]
Defines whether this interactor allows select events.
bool isPerformingManualInteraction [get]
Defines whether this interactor is performing a manual interaction or not.
List< IXRHoverInteractable > interactablesHovered = new List<IXRHoverInteractable>() [get]
(Read Only) The list of Interactables that are currently being hovered over (may by empty).You should treat this as a read only view of the list and should not modify it. It is exposed as a List<T> rather than an IReadOnlyList<T> to avoid GC Allocations when enumerating the list.
bool hasHover [get]
(Read Only) Indicates whether this Interactor is currently hovering an Interactable.In other words, returns whether interactablesHovered contains any Interactables.
interactablesHovered.Count > 0
List< IXRSelectInteractable > interactablesSelected = new List<IXRSelectInteractable>() [get]
(Read Only) The list of Interactables that are currently being selected (may by empty).This should be treated as a read only view of the list and should not be modified by external callers. It is exposed as a List<T> rather than an IReadOnlyList<T> to avoid GC Allocations when enumerating the list.
IXRSelectInteractable firstInteractableSelected [get]
(Read Only) The first Interactable selected since not having any selection. This Interactor may not currently be selecting the Interactable, which would be the case when it was released while multiple Interactables were selected.
See also
IXRSelectInteractable.firstInteractorSelecting
bool hasSelection [get]
(Read Only) Indicates whether this Interactor is currently selecting an Interactable.In other words, returns whether interactablesSelected contains any Interactables.
interactablesSelected.Count > 0
virtual bool isHoverActive [get]
(Read Only) Indicates whether this Interactor is in a state where it could hover.
virtual bool isSelectActive [get]
(Read Only) Indicates whether this Interactor is in a state where it could select.
virtual XRBaseInteractable.? MovementType selectedInteractableMovementTypeOverride [get]
(Read Only) Overriding movement type of the selected Interactable's movement. By default, this does not override the movement type.
LayerMask interactionLayerMask [get, set]
(Deprecated) Allows interaction with Interactables whose Interaction Layer Mask overlaps with any Layer in this Interaction Layer Mask.
bool enableInteractions [get, set]
(Deprecated) Defines whether interactions are enabled or not.
XRInteractorEvent onHoverEntered [get, set]
(Deprecated) Gets or sets the event that Unity calls when this Interactor begins hovering over an Interactable.
XRInteractorEvent onHoverExited [get, set]
(Deprecated) Gets or sets the event that Unity calls when this Interactor ends hovering over an Interactable.
XRInteractorEvent onSelectEntered [get, set]
(Deprecated) Gets or sets the event that Unity calls when this Interactor begins selecting an Interactable.
XRInteractorEvent onSelectExited [get, set]
(Deprecated) Gets or sets the event that Unity calls when this Interactor ends selecting an Interactable.
XRInteractorEvent onHoverEnter [get]
(Deprecated) Gets or sets the event that Unity calls when this Interactor begins hovering over an Interactable.
XRInteractorEvent onHoverExit [get]
(Deprecated) Gets or sets the event that Unity calls when this Interactor ends hovering over an Interactable.
XRInteractorEvent onSelectEnter [get]
(Deprecated) Gets or sets the event that Unity calls when this Interactor begins selecting an Interactable.
XRInteractorEvent onSelectExit [get]
(Deprecated) Gets or sets the event that Unity calls when this Interactor ends selecting an Interactable.
XRBaseInteractable selectTarget [get, protected set]
Selected Interactable for this Interactor (may be null).
List< XRBaseInteractable > hoverTargets = new List<XRBaseInteractable>() [get]
Target Interactables that are currently being hovered over (may by empty).
virtual bool requireSelectExclusive [get]
(Deprecated) (Read Only) Indicates whether this Interactor requires that an Interactable is not currently selected to begin selecting it.
Properties inherited from UnityEngine.XR.Interaction.Toolkit.IXRHoverInteractor
Properties inherited from UnityEngine.XR.Interaction.Toolkit.IXRInteractor
Transform transform [get]
(Read Only) The Transform associated with the Interactor.
Properties inherited from UnityEngine.XR.Interaction.Toolkit.IXRSelectInteractor
Properties inherited from UnityEngine.XR.Interaction.Toolkit.IXRActivateInteractor
Additional Inherited Members
Events inherited from UnityEngine.XR.Interaction.Toolkit.XRBaseInteractor
Action< InteractorRegisteredEventArgs > registered
Action< InteractorUnregisteredEventArgs > unregistered
Events inherited from UnityEngine.XR.Interaction.Toolkit.IXRInteractor
Action< InteractorRegisteredEventArgs > registered
Calls the methods in its invocation list when this Interactor is registered with an Interaction Manager.
Action< InteractorUnregisteredEventArgs > unregistered
Calls the methods in its invocation list when this Interactor is unregistered from an Interaction Manager.
Detailed Description
Abstract base class from which all interactors that are controller-driven derive. This class hooks into the interaction system (via XRInteractionManager) and provides base virtual methods for handling hover and selection. Additionally, this class provides functionality for checking the controller's selection status and hiding the controller on selection.
Member Enumeration Documentation
InputTriggerType
enum UnityEngine.XR.Interaction.Toolkit.XRBaseControllerInteractor.InputTriggerType
This defines the type of input that triggers an interaction.
See also
selectActionTrigger
Enumerator
State
Unity will consider the input active while the button is pressed. A user can hold the button before the interaction is possible and still trigger the interaction when it is possible.
See also
InteractionState.active
StateChange
Unity will consider the input active only on the frame the button is pressed, and if successful remain engaged until the input is released. A user must press the button while the interaction is possible to trigger the interaction. They will not trigger the interaction if they started pressing the button before the interaction was possible.
See also
InteractionState.activatedThisFrame
Toggle
The interaction starts on the frame the input is pressed and remains engaged until the second time the input is pressed.
Sticky
The interaction starts on the frame the input is pressed and remains engaged until the second time the input is released.
Member Function Documentation
Awake()
override void UnityEngine.XR.Interaction.Toolkit.XRBaseControllerInteractor.Awake () protected virtual
See MonoBehaviour.
Reimplemented from UnityEngine.XR.Interaction.Toolkit.XRBaseInteractor.
Reimplemented in UnityEngine.XR.Interaction.Toolkit.XRDirectInteractor, and UnityEngine.XR.Interaction.Toolkit.XRRayInteractor.
GetActivateTargets()
virtual void UnityEngine.XR.Interaction.Toolkit.XRBaseControllerInteractor.GetActivateTargets (List< IXRActivateInteractable > targets) virtual
Retrieve the list of Interactables that this Interactor could possibly activate or deactivate this frame.
Parameters
targets The results list to populate with Interactables that are valid for activate or deactivate.
When implementing this method, Unity expects you to clear targets before adding to it.
Implements UnityEngine.XR.Interaction.Toolkit.IXRActivateInteractor.
Referenced by UnityEngine.XR.Interaction.Toolkit.XRBaseControllerInteractor.ProcessInteractor().
OnHoverEntering()
override void UnityEngine.XR.Interaction.Toolkit.XRBaseControllerInteractor.OnHoverEntering (HoverEnterEventArgs args) protected virtual
The XRInteractionManager calls this method right before the Interactor first initiates hovering over an Interactable in a first pass.
Parameters
args Event data containing the Interactable that is being hovered over.
args is only valid during this method call, do not hold a reference to it.
Reimplemented from UnityEngine.XR.Interaction.Toolkit.XRBaseInteractor.
OnHoverExiting()
override void UnityEngine.XR.Interaction.Toolkit.XRBaseControllerInteractor.OnHoverExiting (HoverExitEventArgs args) protected virtual
The XRInteractionManager calls this method right before the Interactor ends hovering over an Interactable in a first pass.
Parameters
args Event data containing the Interactable that is no longer hovered over.
args is only valid during this method call, do not hold a reference to it.
Reimplemented from UnityEngine.XR.Interaction.Toolkit.XRBaseInteractor.
OnSelectEntering()
override void UnityEngine.XR.Interaction.Toolkit.XRBaseControllerInteractor.OnSelectEntering (SelectEnterEventArgs args) protected virtual
The XRInteractionManager calls this method right before the Interactor first initiates selection of an Interactable in a first pass.
Parameters
args Event data containing the Interactable that is being selected.
args is only valid during this method call, do not hold a reference to it.
Reimplemented from UnityEngine.XR.Interaction.Toolkit.XRBaseInteractor.
Reimplemented in UnityEngine.XR.Interaction.Toolkit.XRRayInteractor.
OnSelectExiting()
override void UnityEngine.XR.Interaction.Toolkit.XRBaseControllerInteractor.OnSelectExiting (SelectExitEventArgs args) protected virtual
The XRInteractionManager calls this method right before the Interactor ends selection of an Interactable in a first pass.
Parameters
args Event data containing the Interactable that is no longer selected.
args is only valid during this method call, do not hold a reference to it.
Reimplemented from UnityEngine.XR.Interaction.Toolkit.XRBaseInteractor.
Reimplemented in UnityEngine.XR.Interaction.Toolkit.XRRayInteractor.
PlayAudio()
virtual void UnityEngine.XR.Interaction.Toolkit.XRBaseControllerInteractor.PlayAudio (AudioClip audioClip) protected virtual
Play an AudioClip.
Parameters
audioClip The clip to play.
Referenced by UnityEngine.XR.Interaction.Toolkit.XRBaseControllerInteractor.OnHoverEntering(), UnityEngine.XR.Interaction.Toolkit.XRBaseControllerInteractor.OnHoverExiting(), UnityEngine.XR.Interaction.Toolkit.XRBaseControllerInteractor.OnSelectEntering(), and UnityEngine.XR.Interaction.Toolkit.XRBaseControllerInteractor.OnSelectExiting().
PreprocessInteractor()
override void UnityEngine.XR.Interaction.Toolkit.XRBaseControllerInteractor.PreprocessInteractor (XRInteractionUpdateOrder::UpdatePhase updatePhase) virtual
The XRInteractionManager calls this method to update the Interactor before interaction events occur. Interactors should use this method to do tasks like determine their valid targets.
Parameters
updatePhase The update phase this is called during.
Please see the XRInteractionManager and XRInteractionUpdateOrder.UpdatePhase documentation for more details on update order.
Reimplemented from UnityEngine.XR.Interaction.Toolkit.XRBaseInteractor.
Reimplemented in UnityEngine.XR.Interaction.Toolkit.XRRayInteractor.
ProcessInteractor()
override void UnityEngine.XR.Interaction.Toolkit.XRBaseControllerInteractor.ProcessInteractor (XRInteractionUpdateOrder::UpdatePhase updatePhase) virtual
The XRInteractionManager calls this method to update the Interactor after interaction events occur.
Parameters
updatePhase The update phase this is called during.
Please see the XRInteractionManager and XRInteractionUpdateOrder.UpdatePhase documentation for more details on update order.
Reimplemented from UnityEngine.XR.Interaction.Toolkit.XRBaseInteractor.
Reimplemented in UnityEngine.XR.Interaction.Toolkit.XRDirectInteractor, and UnityEngine.XR.Interaction.Toolkit.XRRayInteractor.
SendHapticImpulse()
bool UnityEngine.XR.Interaction.Toolkit.XRBaseControllerInteractor.SendHapticImpulse (float amplitude, float duration)
Play a haptic impulse on the controller if one is available.
Parameters
amplitude Amplitude (from 0.0 to 1.0) to play impulse at.
duration Duration (in seconds) to play haptic impulse.
Returns
Returns true if successful. Otherwise, returns false.
See also
XRBaseController.SendHapticImpulse
Referenced by UnityEngine.XR.Interaction.Toolkit.XRBaseControllerInteractor.OnHoverEntering(), UnityEngine.XR.Interaction.Toolkit.XRBaseControllerInteractor.OnHoverExiting(), UnityEngine.XR.Interaction.Toolkit.XRBaseControllerInteractor.OnSelectEntering(), and UnityEngine.XR.Interaction.Toolkit.XRBaseControllerInteractor.OnSelectExiting().
Property Documentation
allowActivate
bool UnityEngine.XR.Interaction.Toolkit.XRBaseControllerInteractor.allowActivate get set
Defines whether this interactor allows sending activate and deactivate events.
See also
allowHoveredActivate, shouldActivate, shouldDeactivate
allowHoveredActivate
bool UnityEngine.XR.Interaction.Toolkit.XRBaseControllerInteractor.allowHoveredActivate get set
Controls whether to send activate and deactivate events to interactables that this interactor is hovered over but not selected when there is no current selection. By default, the interactor will only send activate and deactivate events to interactables that it's selected.
See also
allowActivate, GetActivateTargets
audioClipForOnHoverCanceled
AudioClip UnityEngine.XR.Interaction.Toolkit.XRBaseControllerInteractor.audioClipForOnHoverCanceled get set
The AudioClip Unity plays on Hover Canceled.
See also
playAudioClipOnHoverCanceled
audioClipForOnHoverEnter
AudioClip UnityEngine.XR.Interaction.Toolkit.XRBaseControllerInteractor.audioClipForOnHoverEnter get
(Deprecated) The AudioClip Unity plays on Hover Entered.
See also
playAudioClipOnHoverEntered
audioClipForOnHoverEnter has been deprecated. Use audioClipForOnHoverEntered instead.
AudioClipForOnHoverEnter
AudioClip UnityEngine.XR.Interaction.Toolkit.XRBaseControllerInteractor.AudioClipForOnHoverEnter get set
(Deprecated) The AudioClip Unity plays on Hover Entered.
See also
playAudioClipOnHoverEntered
AudioClipForOnHoverEnter has been deprecated. Use audioClipForOnHoverEntered instead.
audioClipForOnHoverEntered
AudioClip UnityEngine.XR.Interaction.Toolkit.XRBaseControllerInteractor.audioClipForOnHoverEntered get set
The AudioClip Unity plays on Hover Entered.
See also
playAudioClipOnHoverEntered
audioClipForOnHoverExit
AudioClip UnityEngine.XR.Interaction.Toolkit.XRBaseControllerInteractor.audioClipForOnHoverExit get
(Deprecated) The AudioClip Unity plays on Hover Exited.
See also
playAudioClipOnHoverExited
audioClipForOnHoverExit has been deprecated. Use audioClipForOnHoverExited instead.
AudioClipForOnHoverExit
AudioClip UnityEngine.XR.Interaction.Toolkit.XRBaseControllerInteractor.AudioClipForOnHoverExit get set
(Deprecated) The AudioClip Unity plays on Hover Exited.
See also
playAudioClipOnHoverExited
AudioClipForOnHoverExit has been deprecated. Use audioClipForOnHoverExited instead.
audioClipForOnHoverExited
AudioClip UnityEngine.XR.Interaction.Toolkit.XRBaseControllerInteractor.audioClipForOnHoverExited get set
The AudioClip Unity plays on Hover Exited.
See also
playAudioClipOnHoverExited
audioClipForOnSelectCanceled
AudioClip UnityEngine.XR.Interaction.Toolkit.XRBaseControllerInteractor.audioClipForOnSelectCanceled get set
The AudioClip Unity plays on Select Canceled.
See also
playAudioClipOnSelectCanceled
audioClipForOnSelectEnter
AudioClip UnityEngine.XR.Interaction.Toolkit.XRBaseControllerInteractor.audioClipForOnSelectEnter get
(Deprecated) The AudioClip Unity plays on Select Entered.
See also
playAudioClipOnSelectEntered
audioClipForOnSelectEnter has been deprecated. Use audioClipForOnSelectEntered instead.
AudioClipForOnSelectEnter
AudioClip UnityEngine.XR.Interaction.Toolkit.XRBaseControllerInteractor.AudioClipForOnSelectEnter get set
(Deprecated) The AudioClip Unity plays on Select Entered.
See also
playAudioClipOnSelectEntered
AudioClipForOnSelectEnter has been deprecated. Use audioClipForOnSelectEntered instead.
audioClipForOnSelectEntered
AudioClip UnityEngine.XR.Interaction.Toolkit.XRBaseControllerInteractor.audioClipForOnSelectEntered get set
The AudioClip Unity plays on Select Entered.
See also
playAudioClipOnSelectEntered
audioClipForOnSelectExit
AudioClip UnityEngine.XR.Interaction.Toolkit.XRBaseControllerInteractor.audioClipForOnSelectExit get
(Deprecated) The AudioClip Unity plays on Select Exited.
See also
playAudioClipOnSelectExited
audioClipForOnSelectExit has been deprecated. Use audioClipForOnSelectExited instead.
AudioClipForOnSelectExit
AudioClip UnityEngine.XR.Interaction.Toolkit.XRBaseControllerInteractor.AudioClipForOnSelectExit get set
(Deprecated) The AudioClip Unity plays on Select Exited.
See also
playAudioClipOnSelectExited
AudioClipForOnSelectExit has been deprecated. Use audioClipForOnSelectExited instead.
audioClipForOnSelectExited
AudioClip UnityEngine.XR.Interaction.Toolkit.XRBaseControllerInteractor.audioClipForOnSelectExited get set
The AudioClip Unity plays on Select Exited.
See also
playAudioClipOnSelectExited
hapticHoverCancelDuration
float UnityEngine.XR.Interaction.Toolkit.XRBaseControllerInteractor.hapticHoverCancelDuration get set
The Haptics duration (in seconds) Unity plays on Hover Canceled.
See also
hapticHoverCancelIntensity, playHapticsOnHoverCanceled
hapticHoverCancelIntensity
float UnityEngine.XR.Interaction.Toolkit.XRBaseControllerInteractor.hapticHoverCancelIntensity get set
The Haptics intensity Unity plays on Hover Canceled.
See also
hapticHoverCancelDuration, playHapticsOnHoverCanceled
hapticHoverEnterDuration
float UnityEngine.XR.Interaction.Toolkit.XRBaseControllerInteractor.hapticHoverEnterDuration get set
The Haptics duration (in seconds) Unity plays on Hover Entered.
See also
hapticHoverEnterIntensity, playHapticsOnHoverEntered
hapticHoverEnterIntensity
float UnityEngine.XR.Interaction.Toolkit.XRBaseControllerInteractor.hapticHoverEnterIntensity get set
The Haptics intensity Unity plays on Hover Entered.
See also
hapticHoverEnterDuration, playHapticsOnHoverEntered
hapticHoverExitDuration
float UnityEngine.XR.Interaction.Toolkit.XRBaseControllerInteractor.hapticHoverExitDuration get set
The Haptics duration (in seconds) Unity plays on Hover Exited.
See also
hapticHoverExitIntensity, playHapticsOnHoverExited
hapticHoverExitIntensity
float UnityEngine.XR.Interaction.Toolkit.XRBaseControllerInteractor.hapticHoverExitIntensity get set
The Haptics intensity Unity plays on Hover Exited.
See also
hapticHoverExitDuration, playHapticsOnHoverExited
hapticSelectCancelDuration
float UnityEngine.XR.Interaction.Toolkit.XRBaseControllerInteractor.hapticSelectCancelDuration get set
The Haptics duration (in seconds) Unity plays on Select Canceled.
See also
hapticSelectCancelIntensity, playHapticsOnSelectCanceled
hapticSelectCancelIntensity
float UnityEngine.XR.Interaction.Toolkit.XRBaseControllerInteractor.hapticSelectCancelIntensity get set
The Haptics intensity Unity plays on Select Canceled.
See also
hapticSelectCancelDuration, playHapticsOnSelectCanceled
hapticSelectEnterDuration
float UnityEngine.XR.Interaction.Toolkit.XRBaseControllerInteractor.hapticSelectEnterDuration get set
The Haptics duration (in seconds) Unity plays on Select Entered.
See also
hapticSelectEnterIntensity, playHapticsOnSelectEntered
hapticSelectEnterIntensity
float UnityEngine.XR.Interaction.Toolkit.XRBaseControllerInteractor.hapticSelectEnterIntensity get set
The Haptics intensity Unity plays on Select Entered.
See also
hapticSelectEnterDuration, playHapticsOnSelectEntered
hapticSelectExitDuration
float UnityEngine.XR.Interaction.Toolkit.XRBaseControllerInteractor.hapticSelectExitDuration get set
The Haptics duration (in seconds) Unity plays on Select Exited.
See also
hapticSelectExitIntensity, playHapticsOnSelectExited
hapticSelectExitIntensity
float UnityEngine.XR.Interaction.Toolkit.XRBaseControllerInteractor.hapticSelectExitIntensity get set
The Haptics intensity Unity plays on Select Exited.
See also
hapticSelectExitDuration, playHapticsOnSelectExited
hideControllerOnSelect
bool UnityEngine.XR.Interaction.Toolkit.XRBaseControllerInteractor.hideControllerOnSelect get set
Controls whether this Interactor should hide the controller model on selection.
See also
XRBaseController.hideControllerModel
isSelectActive
override bool UnityEngine.XR.Interaction.Toolkit.XRBaseControllerInteractor.isSelectActive get
(Read Only) Indicates whether this Interactor is in a state where it could select.
Implements UnityEngine.XR.Interaction.Toolkit.IXRSelectInteractor.
isUISelectActive
bool UnityEngine.XR.Interaction.Toolkit.XRBaseControllerInteractor.isUISelectActive get protected
(Read Only) Whether or not Unity considers the UI Press controller input pressed.
Returns
Returns true if active. Otherwise, returns false.
Referenced by UnityEngine.XR.Interaction.Toolkit.XRRayInteractor.UpdateUIModel().
playAudioClipOnHoverCanceled
bool UnityEngine.XR.Interaction.Toolkit.XRBaseControllerInteractor.playAudioClipOnHoverCanceled get set
Controls whether Unity plays an AudioClip on Hover Canceled.
See also
audioClipForOnHoverCanceled
playAudioClipOnHoverEnter
bool UnityEngine.XR.Interaction.Toolkit.XRBaseControllerInteractor.playAudioClipOnHoverEnter get
(Deprecated) Controls whether Unity plays an AudioClip on Hover Entered.
See also
audioClipForOnHoverEntered
playAudioClipOnHoverEnter has been deprecated. Use playAudioClipOnHoverEntered instead.
playAudioClipOnHoverEntered
bool UnityEngine.XR.Interaction.Toolkit.XRBaseControllerInteractor.playAudioClipOnHoverEntered get set
Controls whether Unity plays an AudioClip on Hover Entered.
See also
audioClipForOnHoverEntered
playAudioClipOnHoverExit
bool UnityEngine.XR.Interaction.Toolkit.XRBaseControllerInteractor.playAudioClipOnHoverExit get
(Deprecated) Controls whether Unity plays an AudioClip on Hover Exited.
See also
audioClipForOnHoverExited
playAudioClipOnHoverExit has been deprecated. Use playAudioClipOnHoverExited instead.
playAudioClipOnHoverExited
bool UnityEngine.XR.Interaction.Toolkit.XRBaseControllerInteractor.playAudioClipOnHoverExited get set
Controls whether Unity plays an AudioClip on Hover Exited.
See also
audioClipForOnHoverExited
playAudioClipOnSelectCanceled
bool UnityEngine.XR.Interaction.Toolkit.XRBaseControllerInteractor.playAudioClipOnSelectCanceled get set
Controls whether Unity plays an AudioClip on Select Canceled.
See also
audioClipForOnSelectCanceled
playAudioClipOnSelectEnter
bool UnityEngine.XR.Interaction.Toolkit.XRBaseControllerInteractor.playAudioClipOnSelectEnter get
(Deprecated) Controls whether Unity plays an AudioClip on Select Entered.
See also
audioClipForOnSelectEntered
playAudioClipOnSelectEnter has been deprecated. Use playAudioClipOnSelectEntered instead.
playAudioClipOnSelectEntered
bool UnityEngine.XR.Interaction.Toolkit.XRBaseControllerInteractor.playAudioClipOnSelectEntered get set
Controls whether Unity plays an AudioClip on Select Entered.
See also
audioClipForOnSelectEntered
playAudioClipOnSelectExit
bool UnityEngine.XR.Interaction.Toolkit.XRBaseControllerInteractor.playAudioClipOnSelectExit get
(Deprecated) Controls whether Unity plays an AudioClip on Select Exited.
See also
audioClipForOnSelectExited
playAudioClipOnSelectExit has been deprecated. Use playAudioClipOnSelectExited instead.
playAudioClipOnSelectExited
bool UnityEngine.XR.Interaction.Toolkit.XRBaseControllerInteractor.playAudioClipOnSelectExited get set
Controls whether Unity plays an AudioClip on Select Exited.
See also
audioClipForOnSelectExited
playHapticsOnHoverCanceled
bool UnityEngine.XR.Interaction.Toolkit.XRBaseControllerInteractor.playHapticsOnHoverCanceled get set
Controls whether Unity plays haptics on Hover Canceled.
See also
hapticHoverCancelIntensity, hapticHoverCancelDuration
playHapticsOnHoverEnter
bool UnityEngine.XR.Interaction.Toolkit.XRBaseControllerInteractor.playHapticsOnHoverEnter get
(Deprecated) Controls whether Unity plays haptics on Hover Entered.
See also
hapticHoverEnterIntensity, hapticHoverEnterDuration
playHapticsOnHoverEnter has been deprecated. Use playHapticsOnHoverEntered instead.
playHapticsOnHoverEntered
bool UnityEngine.XR.Interaction.Toolkit.XRBaseControllerInteractor.playHapticsOnHoverEntered get set
Controls whether Unity plays haptics on Hover Entered.
See also
hapticHoverEnterIntensity, hapticHoverEnterDuration
playHapticsOnHoverExited
bool UnityEngine.XR.Interaction.Toolkit.XRBaseControllerInteractor.playHapticsOnHoverExited get set
Controls whether Unity plays haptics on Hover Exited.
See also
hapticHoverExitIntensity, hapticHoverExitDuration
playHapticsOnSelectCanceled
bool UnityEngine.XR.Interaction.Toolkit.XRBaseControllerInteractor.playHapticsOnSelectCanceled get set
Controls whether Unity plays haptics on Select Canceled.
See also
hapticSelectCancelIntensity, hapticSelectCancelDuration
playHapticsOnSelectEnter
bool UnityEngine.XR.Interaction.Toolkit.XRBaseControllerInteractor.playHapticsOnSelectEnter get
(Deprecated) Controls whether Unity plays haptics on Select Entered.
See also
hapticSelectEnterIntensity, hapticSelectEnterDuration
playHapticsOnSelectEnter has been deprecated. Use playHapticsOnSelectEntered instead.
playHapticsOnSelectEntered
bool UnityEngine.XR.Interaction.Toolkit.XRBaseControllerInteractor.playHapticsOnSelectEntered get set
Controls whether Unity plays haptics on Select Entered.
See also
hapticSelectEnterIntensity, hapticSelectEnterDuration
playHapticsOnSelectExit
bool UnityEngine.XR.Interaction.Toolkit.XRBaseControllerInteractor.playHapticsOnSelectExit get
(Deprecated) Controls whether Unity plays haptics on Select Exited.
See also
hapticSelectExitIntensity, hapticSelectExitDuration
playHapticsOnSelectExit has been deprecated. Use playHapticsOnSelectExited instead.
playHapticsOnSelectExited
bool UnityEngine.XR.Interaction.Toolkit.XRBaseControllerInteractor.playHapticsOnSelectExited get set
Controls whether Unity plays haptics on Select Exited.
See also
hapticSelectExitIntensity, hapticSelectExitDuration
selectActionTrigger
InputTriggerType UnityEngine.XR.Interaction.Toolkit.XRBaseControllerInteractor.selectActionTrigger get set
Choose how Unity interprets the select input action from the controller. Controls between different input styles for determining if this Interactor can select, such as whether the button is currently pressed or just toggles the active state.
See also
InputTriggerType, isSelectActive
shouldActivate
virtual bool UnityEngine.XR.Interaction.Toolkit.XRBaseControllerInteractor.shouldActivate get
(Read Only) Indicates whether this interactor is in a state where it should send the activate event this frame.
Implements UnityEngine.XR.Interaction.Toolkit.IXRActivateInteractor.
Referenced by UnityEngine.XR.Interaction.Toolkit.XRBaseControllerInteractor.ProcessInteractor().
shouldDeactivate
virtual bool UnityEngine.XR.Interaction.Toolkit.XRBaseControllerInteractor.shouldDeactivate get
(Read Only) Indicates whether this interactor is in a state where it should send the deactivate event this frame.
Implements UnityEngine.XR.Interaction.Toolkit.IXRActivateInteractor.
Referenced by UnityEngine.XR.Interaction.Toolkit.XRBaseControllerInteractor.ProcessInteractor().
validTargets
virtual List<XRBaseInteractable> UnityEngine.XR.Interaction.Toolkit.XRBaseControllerInteractor.validTargets = new List<XRBaseInteractable>() get protected
(Deprecated) (Read Only) A list of Interactables that this Interactor could possibly interact with this frame.
xrController
XRBaseController UnityEngine.XR.Interaction.Toolkit.XRBaseControllerInteractor.xrController get set
The controller instance that is queried for input.
Referenced by UnityEngine.XR.Interaction.Toolkit.XRRayInteractor.ProcessInteractor().
The documentation for this class was generated from the following files:
C:/Users/Lykos/Desktop/Projects/Capstone/VRGames/Library/PackageCache/com.unity.xr.interaction.toolkit@2.0.2/Runtime/Interaction/Interactors/XRBaseControllerInteractor.cs
C:/Users/Lykos/Desktop/Projects/Capstone/VRGames/Library/PackageCache/com.unity.xr.interaction.toolkit@2.0.2/Runtime/Interaction/Interactors/XRBaseControllerInteractor.deprecated.cs