VRCapstoneGames: OVRADBTool Class Reference
OVRADBTool Class Reference
Public Member Functions
OVRADBTool (string androidSdkRoot)
delegate void WaitingProcessToExitCallback ()
int StartServer (WaitingProcessToExitCallback waitingProcessToExitCallback)
int KillServer (WaitingProcessToExitCallback waitingProcessToExitCallback)
int ForwardPort (int port, WaitingProcessToExitCallback waitingProcessToExitCallback)
int ReleasePort (int port, WaitingProcessToExitCallback waitingProcessToExitCallback)
List< string > GetDevices ()
int RunCommand (string[] arguments, WaitingProcessToExitCallback waitingProcessToExitCallback, out string outputString, out string errorString)
Process RunCommandAsync (string[] arguments, DataReceivedEventHandler outputDataRecievedHandler)
Static Public Member Functions
static bool IsAndroidSdkRootValid (string androidSdkRoot)
Public Attributes
bool isReady
string androidSdkRoot
string androidPlatformToolsPath
string adbPath
Constructor & Destructor Documentation
OVRADBTool()
OVRADBTool.OVRADBTool (string androidSdkRoot)
Referenced by IsAndroidSdkRootValid().
Member Function Documentation
ForwardPort()
int OVRADBTool.ForwardPort (int port, WaitingProcessToExitCallback waitingProcessToExitCallback)
GetDevices()
List< string > OVRADBTool.GetDevices ()
Referenced by OVRGradleGeneration.OnPostprocessBuild().
IsAndroidSdkRootValid()
static bool OVRADBTool.IsAndroidSdkRootValid (string androidSdkRoot) static
KillServer()
int OVRADBTool.KillServer (WaitingProcessToExitCallback waitingProcessToExitCallback)
ReleasePort()
int OVRADBTool.ReleasePort (int port, WaitingProcessToExitCallback waitingProcessToExitCallback)
RunCommand()
int OVRADBTool.RunCommand (string[] arguments, WaitingProcessToExitCallback waitingProcessToExitCallback, out string outputString, out string errorString)
Referenced by ForwardPort(), GetDevices(), KillServer(), ReleasePort(), and StartServer().
RunCommandAsync()
Process OVRADBTool.RunCommandAsync (string[] arguments, DataReceivedEventHandler outputDataRecievedHandler)
Referenced by OVRGradleGeneration.OnPostprocessBuild().
StartServer()
int OVRADBTool.StartServer (WaitingProcessToExitCallback waitingProcessToExitCallback)
WaitingProcessToExitCallback()
delegate void OVRADBTool.WaitingProcessToExitCallback ()
Member Data Documentation
adbPath
string OVRADBTool.adbPath
Referenced by OVRADBTool(), RunCommand(), and RunCommandAsync().
androidPlatformToolsPath
string OVRADBTool.androidPlatformToolsPath
Referenced by OVRADBTool().
androidSdkRoot
string OVRADBTool.androidSdkRoot
Referenced by IsAndroidSdkRootValid(), OVRADBTool(), RunCommand(), and RunCommandAsync().
isReady
bool OVRADBTool.isReady
Referenced by IsAndroidSdkRootValid(), OVRGradleGeneration.OnPostprocessBuild(), OVRADBTool(), RunCommand(), and RunCommandAsync().
The documentation for this class was generated from the following file:
C:/Users/Lykos/Desktop/Projects/Capstone/VRGames/Assets/ThirdParty/Oculus/VR/Editor/OVRADBTool.cs