VRCapstoneGames: UnityEngine.InputSystem.InputBindingComposite< TValue > Class Template Reference
UnityEngine.InputSystem.InputBindingComposite< TValue > Class Template Reference abstract
A binding that synthesizes a value from from several component bindings.
Public Member Functions
unsafe void ReadValue (ref InputBindingCompositeContext context, void *buffer, int bufferSize)
Read a value from the composite without having to know the value type (unlike InputBindingComposite<TValue>.ReadValue(ref InputBindingCompositeContext) and without allocating GC heap memory (unlike ReadValueAsObject).
object ReadValueAsObject (ref InputBindingCompositeContext context)
Read the value of the composite as a boxed object. This allows reading the value without having to know the value type and without having to deal with raw byte buffers.
virtual float EvaluateMagnitude (ref InputBindingCompositeContext context)
Determine the current level of actuation of the composite.
TValue ReadValue (ref InputBindingCompositeContext context)
Read a value for the composite given the supplied context.
override unsafe void ReadValue (ref InputBindingCompositeContext context, void *buffer, int bufferSize)
override unsafe object ReadValueAsObject (ref InputBindingCompositeContext context)
Static Public Member Functions
static string GetExpectedControlLayoutName (string composite, string part)
Return the name of the control layout that is expected for the given part (e.g. "Up") on the given composite (e.g. "Dpad").
Protected Member Functions
virtual void FinishSetup (ref InputBindingCompositeContext context)
Called after binding resolution for an InputActionMap is complete.
Properties
Type valueType [get]
The type of value returned by the composite.
int valueSizeInBytes [get]
Size of a value read by ReadValue.
override Type valueType [get]
The type of value returned by the composite, i.e. typeof(TValue).
override int valueSizeInBytes [get]
The size of values returned by the composite, i.e. sizeof(TValue).
Detailed Description
A binding that synthesizes a value from from several component bindings.
A binding composite arranges several bindings such that they form a "virtual control".
TODO: clarify whether this can have state or not
This is the base class for composite bindings. See InputBindingComposite<TValue> for more details about composites and for how to define custom composites.
See also
InputSystem.RegisterBindingComposite<T>
Template Parameters
TValue Type of value returned by the composite. This must be a "blittable" type, that is, a type whose values can simply be copied around.
Composite bindings are a special type of InputBinding. Whereas normally an input binding simply references a set of controls and returns whatever input values are generated by those controls, a composite binding sources input from several controls and derives a new value from that.
A good example for that is a classic WASD keyboard binding:
var moveAction = new InputAction(name: "move");
moveAction.AddCompositeBinding("Vector2")
    .With("Up", "<Keyboard>/w")
    .With("Down", "<Keyboard>/s")
    .With("Left", "<Keyboard>/a")
    .With("Right", "<Keyboard>/d")
Here, each direction is represented by a separate binding. "Up" is bound to "W", "Down" is bound to "S", and so on. Each direction individually returns a 0 or 1 depending on whether it is pressed or not.
However, as a composite, the binding to the "move" action returns a combined Vector2 that is computed from the state of each of the directional controls. This is what composites do. They take inputs from their "parts" to derive an input for the binding as a whole.
Note that the properties and methods defined in InputBindingComposite and this class will generally be called internally by the input system and are not generally meant to be called directly from user land.
The set of composites available in the system is extensible. While some composites are such as Composites.Vector2Composite and Composites.ButtonWithOneModifier are available out of the box, new composites can be implemented by anyone and simply be registered with InputSystem.RegisterBindingComposite<T>.
See the "Custom Composite" sample (can be installed from package manager UI) for a detailed example of how to create a custom composite.
See also
InputSystem.RegisterBindingComposite<T>
Type Constraints
TValue : struct
Member Function Documentation
EvaluateMagnitude()
virtual float UnityEngine.InputSystem.InputBindingComposite< TValue >.EvaluateMagnitude (ref InputBindingCompositeContext context) virtual
Determine the current level of actuation of the composite.
Parameters
context Callback context for the binding composite. Use this to access the values supplied by part bindings.
Returns
This method by default returns -1, meaning that the composite does not support magnitudes. You can override the method to add support for magnitudes.
See InputControl.EvaluateMagnitude() for details of how magnitudes work.
See also
InputControl.EvaluateMagnitude()
Reimplemented in UnityEngine.InputSystem.Composites.AxisComposite, UnityEngine.InputSystem.Composites.ButtonWithOneModifier, UnityEngine.InputSystem.Composites.ButtonWithTwoModifiers, UnityEngine.InputSystem.Composites.OneModifierComposite, UnityEngine.InputSystem.Composites.TwoModifiersComposite, and UnityEngine.InputSystem.Composites.Vector2Composite.
FinishSetup()
virtual void UnityEngine.InputSystem.InputBindingComposite< TValue >.FinishSetup (ref InputBindingCompositeContext context) protected virtual
Called after binding resolution for an InputActionMap is complete.
Some composites do not have predetermine value types. Two examples of this are Composites.OneModifierComposite and Composites.TwoModifiersComposite, which both have a "binding" part that can be bound to arbitrary controls. This means that the value type of these bindings can only be determined at runtime.
Overriding this method allows accessing the actual controls bound to each part at runtime.
[InputControl] public int binding;
protected override void FinishSetup(ref InputBindingContext context)
{
    // Get all controls bound to the 'binding' part.
    var controls = context.controls
        .Where(x => x.part == binding)
        .Select(x => x.control);
}
Reimplemented in UnityEngine.InputSystem.Composites.OneModifierComposite, and UnityEngine.InputSystem.Composites.TwoModifiersComposite.
GetExpectedControlLayoutName()
static string UnityEngine.InputSystem.InputBindingComposite< TValue >.GetExpectedControlLayoutName (string composite, string part) static
Return the name of the control layout that is expected for the given part (e.g. "Up") on the given composite (e.g. "Dpad").
Parameters
composite Registration name of the composite.
part Name of the part.
Returns
The layout name (such as "Button") expected for the given part on the composite or null if there is no composite with the given name or no part on the composite with the given name.
Expected control layouts can be set on composite parts by setting the InputControlAttribute.layout property on them.
InputBindingComposite.GetExpectedControlLayoutName("Dpad", "Up") // Returns "Button"
// This is how Dpad communicates that:
[InputControl(layout = "Button")] public int up;
Referenced by UnityEngine.InputSystem.InputActionRebindingExtensions.RebindingOperation.WithTargetBinding().
ReadValue() [1/3]
TValue UnityEngine.InputSystem.InputBindingComposite< TValue >.ReadValue (ref InputBindingCompositeContext context) abstract
Read a value for the composite given the supplied context.
Parameters
context Callback context for the binding composite. Use this to access the values supplied by part bindings.
Returns
The current value of the composite according to the state made accessible through context .
This is the main method to implement in custom composites.
public class CustomComposite : InputBindingComposite<float>
{
    [InputControl(layout = "Button")]
    public int button;
    public float scaleFactor = 1;
    public override float ReadValue(ref InputBindingComposite context)
    {
        return context.ReadValue<float>(button) * scaleFactor;
    }
}
The other method to consider overriding is InputBindingComposite.EvaluateMagnitude.
See also
InputAction.ReadValue<TValue>, InputAction.CallbackContext.ReadValue<TValue>
ReadValue() [2/3]
unsafe void UnityEngine.InputSystem.InputBindingComposite< TValue >.ReadValue (ref InputBindingCompositeContext context, void * buffer, int bufferSize) abstract
Read a value from the composite without having to know the value type (unlike InputBindingComposite<TValue>.ReadValue(ref InputBindingCompositeContext) and without allocating GC heap memory (unlike ReadValueAsObject).
Parameters
context Callback context for the binding composite. Use this to access the values supplied by part bindings.
buffer Buffer that receives the value read for the composite.
bufferSize Size of the buffer allocated at buffer .
Exceptions
ArgumentException bufferSize is smaller than valueSizeInBytes.
ArgumentNullException buffer is null.
This API will be used if someone calls InputAction.CallbackContext.ReadValue(void*,int) with the action leading to the composite.
By deriving from InputBindingComposite<TValue>, this will automatically be implemented for you.
See also
InputAction.CallbackContext.ReadValue
Referenced by UnityEngine.InputSystem.InputBindingComposite< TValue >.ReadValue(), and UnityEngine.InputSystem.InputBindingComposite< TValue >.ReadValueAsObject().
ReadValue() [3/3]
override unsafe void UnityEngine.InputSystem.InputBindingComposite< TValue >.ReadValue (ref InputBindingCompositeContext context, void * buffer, int bufferSize)
ReadValueAsObject() [1/2]
object UnityEngine.InputSystem.InputBindingComposite< TValue >.ReadValueAsObject (ref InputBindingCompositeContext context) abstract
Read the value of the composite as a boxed object. This allows reading the value without having to know the value type and without having to deal with raw byte buffers.
Parameters
context Callback context for the binding composite. Use this to access the values supplied by part bindings.
Returns
The current value of the composite according to the state passed in through context .
This API will be used if someone calls InputAction.CallbackContext.ReadValueAsObject with the action leading to the composite.
By deriving from InputBindingComposite<TValue>, this will automatically be implemented for you.
ReadValueAsObject() [2/2]
override unsafe object UnityEngine.InputSystem.InputBindingComposite< TValue >.ReadValueAsObject (ref InputBindingCompositeContext context)
Property Documentation
valueSizeInBytes [1/2]
int UnityEngine.InputSystem.InputBindingComposite< TValue >.valueSizeInBytes get abstract
Size of a value read by ReadValue.
Size of values stored in memory buffers by ReadValue.
This is usually implicitly defined by the size of values derived from the type argument to InputBindingComposite<TValue>. E.g. if the type argument is Vector2, this property will be 8.
See also
InputControl.valueSizeInBytes, InputAction.CallbackContext.valueSizeInBytes
valueSizeInBytes [2/2]
override int UnityEngine.InputSystem.InputBindingComposite< TValue >.valueSizeInBytes get
The size of values returned by the composite, i.e. sizeof(TValue).
Returns sizeof(TValue).
valueType [1/2]
Type UnityEngine.InputSystem.InputBindingComposite< TValue >.valueType get abstract
The type of value returned by the composite.
Type of value returned by the composite.
Just like each InputControl has a specific type of value it will return, each composite has a specific type of value it will return. This is usually implicitly defined by the type parameter of InputBindingComposite<TValue>.
See also
InputControl.valueType, InputAction.CallbackContext.valueType
valueType [2/2]
override Type UnityEngine.InputSystem.InputBindingComposite< TValue >.valueType get
The type of value returned by the composite, i.e. typeof(TValue).
Returns typeof(TValue).
The documentation for this class was generated from the following file:
C:/Users/Lykos/Desktop/Projects/Capstone/VRGames/Library/PackageCache/com.unity.inputsystem@1.3.0/InputSystem/Actions/InputBindingComposite.cs