VRCapstoneGames: Oculus.Platform.OculusPlatformSettingsEditor Class Reference
Oculus.Platform.OculusPlatformSettingsEditor Class Reference
Public Types
enum PluginPlatform { Android32 , Android64 }
Public Member Functions
override void OnInspectorGUI ()
Static Public Member Functions
static void Edit ()
static void EnforcePluginPlatformSettings ()
static void EnforcePluginPlatformSettings (PluginPlatform platform)
static bool IsArm64PluginPlatformEnabled ()
static void EnablePluginPlatform (PluginPlatform platform)
static void DisablePluginPlatform (PluginPlatform platform)
Member Enumeration Documentation
PluginPlatform
enum Oculus.Platform.OculusPlatformSettingsEditor.PluginPlatform
Enumerator
Android32
Android64
Member Function Documentation
DisablePluginPlatform()
static void Oculus.Platform.OculusPlatformSettingsEditor.DisablePluginPlatform (PluginPlatform platform) static
Referenced by Oculus.Platform.OculusPlatformSettingsEditor.OnInspectorGUI().
Edit()
static void Oculus.Platform.OculusPlatformSettingsEditor.Edit () static
EnablePluginPlatform()
static void Oculus.Platform.OculusPlatformSettingsEditor.EnablePluginPlatform (PluginPlatform platform) static
Referenced by Oculus.Platform.OculusPlatformSettingsEditor.OnInspectorGUI().
EnforcePluginPlatformSettings() [1/2]
static void Oculus.Platform.OculusPlatformSettingsEditor.EnforcePluginPlatformSettings () static
Referenced by Oculus.Platform.OculusPlatformSettingsEditor.EnablePluginPlatform(), and Oculus.Platform.OculusPlatformSettingsEditor.EnforcePluginPlatformSettings().
EnforcePluginPlatformSettings() [2/2]
static void Oculus.Platform.OculusPlatformSettingsEditor.EnforcePluginPlatformSettings (PluginPlatform platform) static
IsArm64PluginPlatformEnabled()
static bool Oculus.Platform.OculusPlatformSettingsEditor.IsArm64PluginPlatformEnabled () static
Referenced by Oculus.Platform.OculusPlatformSettingsEditor.OnInspectorGUI().
OnInspectorGUI()
override void Oculus.Platform.OculusPlatformSettingsEditor.OnInspectorGUI ()
The documentation for this class was generated from the following file:
C:/Users/Lykos/Desktop/Projects/Capstone/VRGames/Assets/ThirdParty/Oculus/Platform/Editor/OculusPlatformSettingsEditor.cs