VRGames: UnityEditor.ProBuilder.MenuAction Class Reference
UnityEditor.ProBuilder.MenuAction Class Reference abstract
Base class for any action that appears on the ProBuilder toolbar.
Inherited by ProBuilder.ExampleActions.CreateShadowObject, ProBuilder.ExampleActions.MakeFacesDoubleSided, UnityEditor.ProBuilder.Actions.BevelEdges, UnityEditor.ProBuilder.Actions.BridgeEdges, UnityEditor.ProBuilder.Actions.CenterPivot, UnityEditor.ProBuilder.Actions.CollapseVertices, UnityEditor.ProBuilder.Actions.ConformFaceNormals, UnityEditor.ProBuilder.Actions.ConformObjectNormals, UnityEditor.ProBuilder.Actions.ConnectEdges, UnityEditor.ProBuilder.Actions.ConnectVertices, UnityEditor.ProBuilder.Actions.DeleteFaces, UnityEditor.ProBuilder.Actions.DetachFaces, UnityEditor.ProBuilder.Actions.DuplicateFaces, UnityEditor.ProBuilder.Actions.Export, UnityEditor.ProBuilder.Actions.ExportAsset, UnityEditor.ProBuilder.Actions.ExportObj, UnityEditor.ProBuilder.Actions.ExportPly, UnityEditor.ProBuilder.Actions.ExportStlAscii, UnityEditor.ProBuilder.Actions.ExportStlBinary, UnityEditor.ProBuilder.Actions.Extrude, UnityEditor.ProBuilder.Actions.ExtrudeEdges, UnityEditor.ProBuilder.Actions.ExtrudeFaces, UnityEditor.ProBuilder.Actions.FillHole, UnityEditor.ProBuilder.Actions.FlipFaceEdge, UnityEditor.ProBuilder.Actions.FlipFaceNormals, UnityEditor.ProBuilder.Actions.FlipObjectNormals, UnityEditor.ProBuilder.Actions.FreezeTransform, UnityEditor.ProBuilder.Actions.GenerateUV2, UnityEditor.ProBuilder.Actions.GrowSelection, UnityEditor.ProBuilder.Actions.InsertEdgeLoop, UnityEditor.ProBuilder.Actions.MergeFaces, UnityEditor.ProBuilder.Actions.MergeObjects, UnityEditor.ProBuilder.Actions.MirrorObjects, UnityEditor.ProBuilder.Actions.NewBezierShape, UnityEditor.ProBuilder.Actions.OffsetElements, UnityEditor.ProBuilder.Actions.OpenLightmapUVEditor, UnityEditor.ProBuilder.Actions.OpenMaterialEditor, UnityEditor.ProBuilder.Actions.OpenSmoothingEditor, UnityEditor.ProBuilder.Actions.OpenUVEditor, UnityEditor.ProBuilder.Actions.OpenVertexColorEditor, UnityEditor.ProBuilder.Actions.OpenVertexPositionEditor, UnityEditor.ProBuilder.Actions.ProBuilderize, UnityEditor.ProBuilder.Actions.SelectEdgeLoop, UnityEditor.ProBuilder.Actions.SelectEdgeRing, UnityEditor.ProBuilder.Actions.SelectFaceLoop, UnityEditor.ProBuilder.Actions.SelectFaceRing, UnityEditor.ProBuilder.Actions.SelectHole, UnityEditor.ProBuilder.Actions.SelectLoop, UnityEditor.ProBuilder.Actions.SelectMaterial, UnityEditor.ProBuilder.Actions.SelectRing, UnityEditor.ProBuilder.Actions.SelectSmoothingGroup, UnityEditor.ProBuilder.Actions.SelectVertexColor, UnityEditor.ProBuilder.Actions.SetCollider, UnityEditor.ProBuilder.Actions.SetPivotToSelection, UnityEditor.ProBuilder.Actions.SetTrigger, UnityEditor.ProBuilder.Actions.ShrinkSelection, UnityEditor.ProBuilder.Actions.SmartConnect, UnityEditor.ProBuilder.Actions.SmartSubdivide, UnityEditor.ProBuilder.Actions.SoftDeleteEdgesAction, UnityEditor.ProBuilder.Actions.SplitVertices, UnityEditor.ProBuilder.Actions.SubdivideEdges, UnityEditor.ProBuilder.Actions.SubdivideFaces, UnityEditor.ProBuilder.Actions.SubdivideObject, UnityEditor.ProBuilder.Actions.ToggleDragRectMode, UnityEditor.ProBuilder.Actions.ToggleDragSelectionMode, UnityEditor.ProBuilder.Actions.ToggleHandleOrientation, UnityEditor.ProBuilder.Actions.ToggleSelectBackFaces, UnityEditor.ProBuilder.Actions.ToggleXRay, UnityEditor.ProBuilder.Actions.TriangulateFaces, UnityEditor.ProBuilder.Actions.TriangulateObject, UnityEditor.ProBuilder.Actions.WeldVertices, and UnityEditor.ProBuilder.MenuToolToggle.
Public Types
enum MenuActionState { Hidden = 0x0 , Visible = 0x1 , Enabled = 0x2 , VisibleAndEnabled = 0x3 }
Determines whether the menu item is visible, and if visible, whether it is enabled.
Public Member Functions
ActionResult PerformAction ()
Performs the action for this menu item. Use PerformActionImplementation to implement the action. Calling this method triggers the onPerformAction event.
ActionResult DoAction ()
Performs whatever action this menu item is supposed to do.
Static Public Attributes
static Action< MenuAction > onPerformAction
Invoked when the user selects an action to perform from the toolbar.
Protected Member Functions
MenuAction ()
Creates a new button on the ProBuilder toolbar in the Editor.
ActionResult PerformActionImplementation ()
Performs the action for this menu item. Use this method to implement the action and then use PerformAction to call it.
virtual void DoAlternateAction ()
Performs the action for this menu item when in Text mode.
virtual void OnSettingsGUI ()
Implement the extra settings GUI for your action in this method.
virtual void OnSettingsEnable ()
Called when the settings window is opened.
virtual void OnSettingsDisable ()
Called when the settings window is closed.
bool DoAltButton (params GUILayoutOption[] options)
Draws the menu item for this action in Text mode.
Properties
virtual Texture2D disabledIcon [get]
Gets the icon to use when the action button on the toolbar is disabled. By default, this function looks for an image named ${icon}_disabled. Override this function if your disabled icon does not follow that naming convention or location.
ToolbarGroup group [get]
Gets the category assigned to this action.
virtual int toolbarPriority [get]
Gets the value to optionally influence where this menu item appears in the toolbar. The default value is -1 (no preference).
Texture2D icon [get]
Gets the icon to display on the toolbar for this action.
TooltipContent tooltip [get]
Gets the contents of the tooltip to display for this menu action.
virtual string menuTitle [get]
Gets the override title for this action to display on the toolbar button.
virtual bool hasFileMenuEntry [get]
Gets whether this class should have an entry built into the hardware menu. This is not implemented for custom actions.
MenuActionState menuActionState [get]
Gets a flag that indicates both the visibility and enabled state of an action to determine whether the current mode and selection is valid for it.
virtual SelectMode validSelectModes [get]
Gets the SelectMode states where this action applies. This drives the hidden property unless you override it.
virtual bool enabled [get]
Gets whether or not the action is valid given the current selection.
virtual bool hidden [get]
Gets whether this action is visible in the ProBuilder toolbar.
virtual MenuActionState optionsMenuState [get]
Gets a flag that indicates whether the action implements extra options. If it does, it must also implement OnSettingsGUI so that an options indicator appears for this action button.
bool iconMode [get, set]
Gets or sets whether the Toolbar display mode is set to Icon mode (true) or Text mode (false).
Detailed Description
Base class for any action that appears on the ProBuilder toolbar.
Member Enumeration Documentation
MenuActionState
enum UnityEditor.ProBuilder.MenuAction.MenuActionState
Determines whether the menu item is visible, and if visible, whether it is enabled.
Enumerator
Hidden
The button is not visible in the toolbar.
Visible
The button is visible in the toolbar.
Enabled
The button (and by proxy, the action it performs) are valid given the current selection.
VisibleAndEnabled
Button and action are both visible in the toolbar and valid given the current selection.
Constructor & Destructor Documentation
MenuAction()
UnityEditor.ProBuilder.MenuAction.MenuAction () protected
Creates a new button on the ProBuilder toolbar in the Editor.
Member Function Documentation
DoAction()
ActionResult UnityEditor.ProBuilder.MenuAction.DoAction ()
Performs whatever action this menu item is supposed to do.
Returns
A new ActionResult with a summary of the state of the action's success.
DoAltButton()
bool UnityEditor.ProBuilder.MenuAction.DoAltButton (params GUILayoutOption[] options) protected
Draws the menu item for this action in Text mode.
Parameters
options Optional array of layout options for this menu item.
Returns
True if successful; false otherwise.
DoAlternateAction()
virtual void UnityEditor.ProBuilder.MenuAction.DoAlternateAction () protected virtual
Performs the action for this menu item when in Text mode.
Reimplemented in UnityEditor.ProBuilder.Actions.OffsetElements, and UnityEditor.ProBuilder.Actions.GenerateUV2.
OnSettingsDisable()
virtual void UnityEditor.ProBuilder.MenuAction.OnSettingsDisable () protected virtual
Called when the settings window is closed.
Referenced by UnityEditor.ProBuilder.MenuAction.DoAlternateAction().
OnSettingsEnable()
virtual void UnityEditor.ProBuilder.MenuAction.OnSettingsEnable () protected virtual
Called when the settings window is opened.
Reimplemented in ProBuilder.ExampleActions.CreateShadowObject.
Referenced by UnityEditor.ProBuilder.MenuAction.DoAlternateAction().
OnSettingsGUI()
virtual void UnityEditor.ProBuilder.MenuAction.OnSettingsGUI () protected virtual
Implement the extra settings GUI for your action in this method.
Reimplemented in UnityEditor.ProBuilder.Actions.Export, UnityEditor.ProBuilder.Actions.BevelEdges, UnityEditor.ProBuilder.Actions.CollapseVertices, UnityEditor.ProBuilder.Actions.DetachFaces, UnityEditor.ProBuilder.Actions.DuplicateFaces, UnityEditor.ProBuilder.Actions.ExtrudeEdges, UnityEditor.ProBuilder.Actions.ExtrudeFaces, UnityEditor.ProBuilder.Actions.FillHole, UnityEditor.ProBuilder.Actions.SubdivideEdges, UnityEditor.ProBuilder.Actions.WeldVertices, UnityEditor.ProBuilder.Actions.MirrorObjects, UnityEditor.ProBuilder.Actions.ProBuilderize, UnityEditor.ProBuilder.Actions.GrowSelection, UnityEditor.ProBuilder.Actions.SelectEdgeLoop, UnityEditor.ProBuilder.Actions.SelectEdgeRing, UnityEditor.ProBuilder.Actions.SelectMaterial, UnityEditor.ProBuilder.Actions.SelectVertexColor, and ProBuilder.ExampleActions.CreateShadowObject.
Referenced by UnityEditor.ProBuilder.MenuAction.DoAlternateAction().
PerformAction()
ActionResult UnityEditor.ProBuilder.MenuAction.PerformAction ()
Performs the action for this menu item. Use PerformActionImplementation to implement the action. Calling this method triggers the onPerformAction event.
Any new action classes that derive from this base class must also use the PerformAction method to register the new action in the Undo call stack.
Returns
A new ActionResult with a summary of the state of the action's success.
Referenced by ProBuilder.ExampleActions.CreateShadowObject.OnSettingsEnable(), UnityEditor.ProBuilder.Actions.Export.OnSettingsGUI(), UnityEditor.ProBuilder.Actions.BevelEdges.OnSettingsGUI(), UnityEditor.ProBuilder.Actions.CollapseVertices.OnSettingsGUI(), UnityEditor.ProBuilder.Actions.DetachFaces.OnSettingsGUI(), UnityEditor.ProBuilder.Actions.DuplicateFaces.OnSettingsGUI(), UnityEditor.ProBuilder.Actions.ExtrudeEdges.OnSettingsGUI(), UnityEditor.ProBuilder.Actions.ExtrudeFaces.OnSettingsGUI(), UnityEditor.ProBuilder.Actions.FillHole.OnSettingsGUI(), UnityEditor.ProBuilder.Actions.SubdivideEdges.OnSettingsGUI(), UnityEditor.ProBuilder.Actions.WeldVertices.OnSettingsGUI(), UnityEditor.ProBuilder.Actions.MirrorObjects.OnSettingsGUI(), UnityEditor.ProBuilder.Actions.ProBuilderize.OnSettingsGUI(), UnityEditor.ProBuilder.Actions.GrowSelection.OnSettingsGUI(), UnityEditor.ProBuilder.Actions.SelectEdgeLoop.OnSettingsGUI(), UnityEditor.ProBuilder.Actions.SelectEdgeRing.OnSettingsGUI(), UnityEditor.ProBuilder.Actions.SelectMaterial.OnSettingsGUI(), UnityEditor.ProBuilder.Actions.SelectVertexColor.OnSettingsGUI(), ProBuilder.ExampleActions.CreateShadowObject.OnSettingsGUI(), UnityEditor.ProBuilder.Actions.Extrude.PerformActionImplementation(), UnityEditor.ProBuilder.Actions.SmartConnect.PerformActionImplementation(), UnityEditor.ProBuilder.Actions.SmartSubdivide.PerformActionImplementation(), UnityEditor.ProBuilder.Actions.SelectLoop.PerformActionImplementation(), and UnityEditor.ProBuilder.Actions.SelectRing.PerformActionImplementation().
PerformActionImplementation()
ActionResult UnityEditor.ProBuilder.MenuAction.PerformActionImplementation () abstract protected
Performs the action for this menu item. Use this method to implement the action and then use PerformAction to call it.
Returns
A new ActionResult with a summary of the state of the action's success.
Referenced by UnityEditor.ProBuilder.MenuAction.PerformAction().
Member Data Documentation
onPerformAction
Action<MenuAction> UnityEditor.ProBuilder.MenuAction.onPerformAction static
Invoked when the user selects an action to perform from the toolbar.
Referenced by UnityEditor.ProBuilder.MenuAction.PerformAction().
Property Documentation
disabledIcon
virtual Texture2D UnityEditor.ProBuilder.MenuAction.disabledIcon get protected
Gets the icon to use when the action button on the toolbar is disabled. By default, this function looks for an image named ${icon}_disabled. Override this function if your disabled icon does not follow that naming convention or location.
enabled
virtual bool UnityEditor.ProBuilder.MenuAction.enabled get
Gets whether or not the action is valid given the current selection.
True if this action is valid with the current selection and mode.
See also
hidden
group
ToolbarGroup UnityEditor.ProBuilder.MenuAction.group get abstract
Gets the category assigned to this action.
hasFileMenuEntry
virtual bool UnityEditor.ProBuilder.MenuAction.hasFileMenuEntry get protected
Gets whether this class should have an entry built into the hardware menu. This is not implemented for custom actions.
hidden
virtual bool UnityEditor.ProBuilder.MenuAction.hidden get
Gets whether this action is visible in the ProBuilder toolbar.
True if this action appears in the toolbar with the current mode and settings; false otherwise.
This returns false by default.
See also
enabled
icon
Texture2D UnityEditor.ProBuilder.MenuAction.icon get abstract
Gets the icon to display on the toolbar for this action.
This property is not used when the Toolbar display mode is set to text.
iconMode
bool UnityEditor.ProBuilder.MenuAction.iconMode get set protected
Gets or sets whether the Toolbar display mode is set to Icon mode (true) or Text mode (false).
Referenced by UnityEditor.ProBuilder.MenuAction.MenuAction(), and UnityEditor.ProBuilder.MenuToolToggle.MenuToolToggle().
menuActionState
MenuActionState UnityEditor.ProBuilder.MenuAction.menuActionState get
Gets a flag that indicates both the visibility and enabled state of an action to determine whether the current mode and selection is valid for it.
Returns
.
menuTitle
virtual string UnityEditor.ProBuilder.MenuAction.menuTitle get
Gets the override title for this action to display on the toolbar button.
If you don't implement this property, toolbar button displays the tooltip title.
optionsMenuState
virtual MenuActionState UnityEditor.ProBuilder.MenuAction.optionsMenuState get protected
Gets a flag that indicates whether the action implements extra options. If it does, it must also implement OnSettingsGUI so that an options indicator appears for this action button.
toolbarPriority
virtual int UnityEditor.ProBuilder.MenuAction.toolbarPriority get
Gets the value to optionally influence where this menu item appears in the toolbar. The default value is -1 (no preference).
0 is first, 1 is second, -1 is no preference.
tooltip
TooltipContent UnityEditor.ProBuilder.MenuAction.tooltip get abstract
Gets the contents of the tooltip to display for this menu action.
validSelectModes
virtual SelectMode UnityEditor.ProBuilder.MenuAction.validSelectModes get
Gets the SelectMode states where this action applies. This drives the hidden property unless you override it.
The documentation for this class was generated from the following file:
C:/Users/Lykos/Desktop/Projects/Capstone/VRGames/Library/PackageCache/com.unity.probuilder@5.0.6/Editor/EditorCore/MenuAction.cs