VRCapstoneGames: Oculus.Interaction.PoseDetection.FingerFeatureStateProvider Class Reference
Oculus.Interaction.PoseDetection.FingerFeatureStateProvider Class Reference
Interprets finger feature values using FingerShapes and uses the given FingerFeatureStateThresholds to quantize these values into states. To avoid rapid fluctuations at the edges of two states, this class uses the calculated feature state from the previous frame and the given state thresholds to apply a buffer between state transition edges.
Classes
struct FingerStateThresholds
Public Member Functions
bool GetCurrentState (HandFinger finger, FingerFeature fingerFeature, out string currentState)
float? GetFeatureValue (HandFinger finger, FingerFeature fingerFeature)
Returns the current value of the feature. If the finger joints are not populated with valid data (for instance, due to a disconnected hand), the method will return NaN.
FingerShapes GetValueProvider (HandFinger finger)
bool IsStateActive (HandFinger finger, FingerFeature feature, FeatureStateActiveMode mode, string stateId)
void InjectAllFingerFeatureStateProvider (IHand hand, List< FingerStateThresholds > fingerStateThresholds, FingerShapes fingerShapes, bool disableProactiveEvaluation)
void InjectHand (IHand hand)
void InjectFingerStateThresholds (List< FingerStateThresholds > fingerStateThresholds)
void InjectFingerShapes (FingerShapes fingerShapes)
void InjectDisableProactiveEvaluation (bool disableProactiveEvaluation)
void InjectOptionalTimeProvider (Func< float > timeProvider)
Protected Member Functions
virtual void Awake ()
virtual void Start ()
virtual void OnEnable ()
virtual void OnDisable ()
Protected Attributes
bool _started = false
Properties
IHand Hand [get]
static FingerShapes DefaultFingerShapes = new FingerShapes() [get]
Detailed Description
Interprets finger feature values using FingerShapes and uses the given FingerFeatureStateThresholds to quantize these values into states. To avoid rapid fluctuations at the edges of two states, this class uses the calculated feature state from the previous frame and the given state thresholds to apply a buffer between state transition edges.
Member Function Documentation
Awake()
virtual void Oculus.Interaction.PoseDetection.FingerFeatureStateProvider.Awake () protected virtual
GetCurrentState()
bool Oculus.Interaction.PoseDetection.FingerFeatureStateProvider.GetCurrentState (HandFinger finger, FingerFeature fingerFeature, out string currentState)
Implements Oculus.Interaction.PoseDetection.IFingerFeatureStateProvider.
GetFeatureValue()
float? Oculus.Interaction.PoseDetection.FingerFeatureStateProvider.GetFeatureValue (HandFinger finger, FingerFeature fingerFeature)
Returns the current value of the feature. If the finger joints are not populated with valid data (for instance, due to a disconnected hand), the method will return NaN.
GetValueProvider()
FingerShapes Oculus.Interaction.PoseDetection.FingerFeatureStateProvider.GetValueProvider (HandFinger finger)
InjectAllFingerFeatureStateProvider()
void Oculus.Interaction.PoseDetection.FingerFeatureStateProvider.InjectAllFingerFeatureStateProvider (IHand hand, List< FingerStateThresholds > fingerStateThresholds, FingerShapes fingerShapes, bool disableProactiveEvaluation)
InjectDisableProactiveEvaluation()
void Oculus.Interaction.PoseDetection.FingerFeatureStateProvider.InjectDisableProactiveEvaluation (bool disableProactiveEvaluation)
Referenced by Oculus.Interaction.PoseDetection.FingerFeatureStateProvider.InjectAllFingerFeatureStateProvider().
InjectFingerShapes()
void Oculus.Interaction.PoseDetection.FingerFeatureStateProvider.InjectFingerShapes (FingerShapes fingerShapes)
Referenced by Oculus.Interaction.PoseDetection.FingerFeatureStateProvider.InjectAllFingerFeatureStateProvider().
InjectFingerStateThresholds()
void Oculus.Interaction.PoseDetection.FingerFeatureStateProvider.InjectFingerStateThresholds (List< FingerStateThresholds > fingerStateThresholds)
Referenced by Oculus.Interaction.PoseDetection.FingerFeatureStateProvider.InjectAllFingerFeatureStateProvider().
InjectHand()
void Oculus.Interaction.PoseDetection.FingerFeatureStateProvider.InjectHand (IHand hand)
Referenced by Oculus.Interaction.PoseDetection.FingerFeatureStateProvider.InjectAllFingerFeatureStateProvider().
InjectOptionalTimeProvider()
void Oculus.Interaction.PoseDetection.FingerFeatureStateProvider.InjectOptionalTimeProvider (Func< float > timeProvider)
IsStateActive()
bool Oculus.Interaction.PoseDetection.FingerFeatureStateProvider.IsStateActive (HandFinger finger, FingerFeature feature, FeatureStateActiveMode mode, string stateId)
Implements Oculus.Interaction.PoseDetection.IFingerFeatureStateProvider.
OnDisable()
virtual void Oculus.Interaction.PoseDetection.FingerFeatureStateProvider.OnDisable () protected virtual
OnEnable()
virtual void Oculus.Interaction.PoseDetection.FingerFeatureStateProvider.OnEnable () protected virtual
Start()
virtual void Oculus.Interaction.PoseDetection.FingerFeatureStateProvider.Start () protected virtual
Member Data Documentation
_started
bool Oculus.Interaction.PoseDetection.FingerFeatureStateProvider._started = false protected
Referenced by Oculus.Interaction.PoseDetection.FingerFeatureStateProvider.OnDisable(), Oculus.Interaction.PoseDetection.FingerFeatureStateProvider.OnEnable(), and Oculus.Interaction.PoseDetection.FingerFeatureStateProvider.Start().
Property Documentation
DefaultFingerShapes
FingerShapes Oculus.Interaction.PoseDetection.FingerFeatureStateProvider.DefaultFingerShapes = new FingerShapes() static get
Hand
IHand Oculus.Interaction.PoseDetection.FingerFeatureStateProvider.Hand get
The documentation for this class was generated from the following file:
C:/Users/Lykos/Desktop/Projects/Capstone/VRGames/Assets/ThirdParty/Oculus/Interaction/Runtime/Scripts/PoseDetection/FingerFeatureStateProvider.cs