VRGames: Oculus.Interaction.Input.HandJointCache Class Reference
Oculus.Interaction.Input.HandJointCache Class Reference
Public Member Functions
HandJointCache (IReadOnlyHandSkeleton handSkeleton)
void Update (HandDataAsset data, int dataVersion)
bool GetAllLocalPoses (out ReadOnlyHandJointPoses localJointPoses)
bool GetAllPosesFromWrist (out ReadOnlyHandJointPoses jointPosesFromWrist)
Pose LocalJointPose (HandJointId jointid)
Pose PoseFromWrist (HandJointId jointid)
Pose WorldJointPose (HandJointId jointid, Pose rootPose, float handScale)
Properties
int LocalDataVersion = -1 [get]
Constructor & Destructor Documentation
HandJointCache()
Oculus.Interaction.Input.HandJointCache.HandJointCache (IReadOnlyHandSkeleton handSkeleton)
Member Function Documentation
GetAllLocalPoses()
bool Oculus.Interaction.Input.HandJointCache.GetAllLocalPoses (out ReadOnlyHandJointPoses localJointPoses)
Referenced by Oculus.Interaction.Input.Hand.GetJointPosesLocal().
GetAllPosesFromWrist()
bool Oculus.Interaction.Input.HandJointCache.GetAllPosesFromWrist (out ReadOnlyHandJointPoses jointPosesFromWrist)
Referenced by Oculus.Interaction.Input.Hand.GetJointPosesFromWrist().
LocalJointPose()
Pose Oculus.Interaction.Input.HandJointCache.LocalJointPose (HandJointId jointid)
PoseFromWrist()
Pose Oculus.Interaction.Input.HandJointCache.PoseFromWrist (HandJointId jointid)
Update()
void Oculus.Interaction.Input.HandJointCache.Update (HandDataAsset data, int dataVersion)
WorldJointPose()
Pose Oculus.Interaction.Input.HandJointCache.WorldJointPose (HandJointId jointid, Pose rootPose, float handScale)
Referenced by Oculus.Interaction.Input.Hand.GetJointPose().
Property Documentation
LocalDataVersion
int Oculus.Interaction.Input.HandJointCache.LocalDataVersion = -1 get
Referenced by Oculus.Interaction.Input.HandJointCache.HandJointCache(), and Oculus.Interaction.Input.HandJointCache.Update().
The documentation for this class was generated from the following file:
C:/Users/Lykos/Desktop/Projects/Capstone/VRGames/Assets/ThirdParty/Oculus/Interaction/Runtime/Scripts/Input/Hands/HandJointsCache.cs