VRCapstoneGames: Oculus.Interaction.Input.OVRSkeletonDataProviders Class Reference
Oculus.Interaction.Input.OVRSkeletonDataProviders Class Reference
Reads hand & HMD pose data from the DataSources, and copies them onto the given OVRSkeleton. Can also provide more sophisticated control of the mesh rendering, to keep hand meshes visible when tracking is lost.
Public Member Functions
void SetModifyCameraRigAndHandTransformState (bool modifyCameraRig, bool modifyLeftHand, bool modifyRightHand)
void InjectOVRSkeletonDataProviders (IOVRCameraRigRef cameraRigRef, IDataSource< HmdDataAsset > hmdData, Hand leftHand, Hand rightHand, bool modifyCameraRigAnchorTransforms, bool modifyHandTransformsLeft, bool modifyHandTransformsRight, bool replaceHandMeshRendererProviders, HandRenderPoseOriginBehavior handRenderBehavior)
void InjectCameraRigRef (IOVRCameraRigRef cameraRigRef)
void InjectHmdData (IDataSource< HmdDataAsset > hmdData)
void InjectLeftHand (Hand leftHand)
void InjectRightHand (Hand rightHand)
void InjectModifyCameraRigAnchorTransforms (bool modifyCameraRigAnchorTransforms)
void InjectModifyHandTransformsLeft (bool modifyHandTransformsLeft)
void InjectModifyHandTransformsRight (bool modifyHandTransformsRight)
void InjectReplaceHandMeshRendererProviders (bool replaceHandMeshRendererProviders)
void InjectHandRenderBehavior (HandRenderPoseOriginBehavior handRenderBehavior)
void InjectOptionalLeftHandMesh (Mesh handMesh)
void InjectOptionalRightHandMesh (Mesh handMesh)
Protected Member Functions
virtual void Awake ()
virtual void Start ()
virtual void OnEnable ()
virtual void OnDisable ()
virtual void Update ()
Protected Attributes
bool _started = false
Properties
IOVRCameraRigRef CameraRigRef [get]
Detailed Description
Reads hand & HMD pose data from the DataSources, and copies them onto the given OVRSkeleton. Can also provide more sophisticated control of the mesh rendering, to keep hand meshes visible when tracking is lost.
This class is not required if you are using the HandSkeletonVisual to render the hand.
Member Function Documentation
Awake()
virtual void Oculus.Interaction.Input.OVRSkeletonDataProviders.Awake () protected virtual
InjectCameraRigRef()
void Oculus.Interaction.Input.OVRSkeletonDataProviders.InjectCameraRigRef (IOVRCameraRigRef cameraRigRef)
Referenced by Oculus.Interaction.Input.OVRSkeletonDataProviders.InjectOVRSkeletonDataProviders().
InjectHandRenderBehavior()
void Oculus.Interaction.Input.OVRSkeletonDataProviders.InjectHandRenderBehavior (HandRenderPoseOriginBehavior handRenderBehavior)
Referenced by Oculus.Interaction.Input.OVRSkeletonDataProviders.InjectOVRSkeletonDataProviders().
InjectHmdData()
void Oculus.Interaction.Input.OVRSkeletonDataProviders.InjectHmdData (IDataSource< HmdDataAsset > hmdData)
Referenced by Oculus.Interaction.Input.OVRSkeletonDataProviders.InjectOVRSkeletonDataProviders().
InjectLeftHand()
void Oculus.Interaction.Input.OVRSkeletonDataProviders.InjectLeftHand (Hand leftHand)
Referenced by Oculus.Interaction.Input.OVRSkeletonDataProviders.InjectOVRSkeletonDataProviders().
InjectModifyCameraRigAnchorTransforms()
void Oculus.Interaction.Input.OVRSkeletonDataProviders.InjectModifyCameraRigAnchorTransforms (bool modifyCameraRigAnchorTransforms)
Referenced by Oculus.Interaction.Input.OVRSkeletonDataProviders.InjectOVRSkeletonDataProviders().
InjectModifyHandTransformsLeft()
void Oculus.Interaction.Input.OVRSkeletonDataProviders.InjectModifyHandTransformsLeft (bool modifyHandTransformsLeft)
Referenced by Oculus.Interaction.Input.OVRSkeletonDataProviders.InjectOVRSkeletonDataProviders().
InjectModifyHandTransformsRight()
void Oculus.Interaction.Input.OVRSkeletonDataProviders.InjectModifyHandTransformsRight (bool modifyHandTransformsRight)
Referenced by Oculus.Interaction.Input.OVRSkeletonDataProviders.InjectOVRSkeletonDataProviders().
InjectOptionalLeftHandMesh()
void Oculus.Interaction.Input.OVRSkeletonDataProviders.InjectOptionalLeftHandMesh (Mesh handMesh)
InjectOptionalRightHandMesh()
void Oculus.Interaction.Input.OVRSkeletonDataProviders.InjectOptionalRightHandMesh (Mesh handMesh)
InjectOVRSkeletonDataProviders()
void Oculus.Interaction.Input.OVRSkeletonDataProviders.InjectOVRSkeletonDataProviders (IOVRCameraRigRef cameraRigRef, IDataSource< HmdDataAsset > hmdData, Hand leftHand, Hand rightHand, bool modifyCameraRigAnchorTransforms, bool modifyHandTransformsLeft, bool modifyHandTransformsRight, bool replaceHandMeshRendererProviders, HandRenderPoseOriginBehavior handRenderBehavior)
InjectReplaceHandMeshRendererProviders()
void Oculus.Interaction.Input.OVRSkeletonDataProviders.InjectReplaceHandMeshRendererProviders (bool replaceHandMeshRendererProviders)
Referenced by Oculus.Interaction.Input.OVRSkeletonDataProviders.InjectOVRSkeletonDataProviders().
InjectRightHand()
void Oculus.Interaction.Input.OVRSkeletonDataProviders.InjectRightHand (Hand rightHand)
Referenced by Oculus.Interaction.Input.OVRSkeletonDataProviders.InjectOVRSkeletonDataProviders().
OnDisable()
virtual void Oculus.Interaction.Input.OVRSkeletonDataProviders.OnDisable () protected virtual
OnEnable()
virtual void Oculus.Interaction.Input.OVRSkeletonDataProviders.OnEnable () protected virtual
SetModifyCameraRigAndHandTransformState()
void Oculus.Interaction.Input.OVRSkeletonDataProviders.SetModifyCameraRigAndHandTransformState (bool modifyCameraRig, bool modifyLeftHand, bool modifyRightHand)
Start()
virtual void Oculus.Interaction.Input.OVRSkeletonDataProviders.Start () protected virtual
Update()
virtual void Oculus.Interaction.Input.OVRSkeletonDataProviders.Update () protected virtual
Member Data Documentation
_started
bool Oculus.Interaction.Input.OVRSkeletonDataProviders._started = false protected
Referenced by Oculus.Interaction.Input.OVRSkeletonDataProviders.OnDisable(), Oculus.Interaction.Input.OVRSkeletonDataProviders.OnEnable(), and Oculus.Interaction.Input.OVRSkeletonDataProviders.Start().
Property Documentation
CameraRigRef
IOVRCameraRigRef Oculus.Interaction.Input.OVRSkeletonDataProviders.CameraRigRef get
Referenced by Oculus.Interaction.Input.OVRSkeletonDataProviders.Awake(), Oculus.Interaction.Input.OVRSkeletonDataProviders.InjectCameraRigRef(), Oculus.Interaction.Input.OVRSkeletonDataProviders.Start(), and Oculus.Interaction.Input.OVRSkeletonDataProviders.Update().
The documentation for this class was generated from the following file:
C:/Users/Lykos/Desktop/Projects/Capstone/VRGames/Assets/ThirdParty/Oculus/Interaction/Runtime/Scripts/Input/OVRIntegration/OVRSkeletonDataProviders.cs