VRGames: OVRProjectConfigEditor Class Reference
OVRProjectConfigEditor Class Reference
Public Member Functions
override void OnInspectorGUI ()
Static Public Member Functions
static void DrawTargetDeviceInspector (OVRProjectConfig projectConfig)
static void DrawProjectConfigInspector (OVRProjectConfig projectConfig)
Member Function Documentation
DrawProjectConfigInspector()
static void OVRProjectConfigEditor.DrawProjectConfigInspector (OVRProjectConfig projectConfig) static
Referenced by OVRManagerEditor.OnInspectorGUI(), and OnInspectorGUI().
DrawTargetDeviceInspector()
static void OVRProjectConfigEditor.DrawTargetDeviceInspector (OVRProjectConfig projectConfig) static
Referenced by OVRManagerEditor.OnInspectorGUI(), and OnInspectorGUI().
OnInspectorGUI()
override void OVRProjectConfigEditor.OnInspectorGUI ()
The documentation for this class was generated from the following file:
C:/Users/Lykos/Desktop/Projects/Capstone/VRGames/Assets/ThirdParty/Oculus/VR/Scripts/Editor/OVRProjectConfigEditor.cs