VRGames: UnityEditor.ProBuilder.ProBuilderToolManager Class Reference
UnityEditor.ProBuilder.ProBuilderToolManager Class Reference
Public Member Functions
ProBuilderToolManager ()
void Dispose ()
void SetSelectMode (SelectMode mode)
void ResetToLastSelectMode ()
Static Public Member Functions
static void NextMeshSelectMode ()
Properties
static SelectMode selectMode [get]
static Tool activeTool [get]
Events
static Action selectModeChanged = () => {}
Constructor & Destructor Documentation
ProBuilderToolManager()
UnityEditor.ProBuilder.ProBuilderToolManager.ProBuilderToolManager ()
Member Function Documentation
Dispose()
void UnityEditor.ProBuilder.ProBuilderToolManager.Dispose ()
NextMeshSelectMode()
static void UnityEditor.ProBuilder.ProBuilderToolManager.NextMeshSelectMode () static
ResetToLastSelectMode()
void UnityEditor.ProBuilder.ProBuilderToolManager.ResetToLastSelectMode ()
Referenced by UnityEditor.ProBuilder.ProBuilderEditor.ResetToLastSelectMode().
SetSelectMode()
void UnityEditor.ProBuilder.ProBuilderToolManager.SetSelectMode (SelectMode mode)
Referenced by UnityEditor.ProBuilder.ProBuilderToolManager.Dispose(), UnityEditor.ProBuilder.ProBuilderToolManager.ProBuilderToolManager(), and UnityEditor.ProBuilder.ProBuilderToolManager.ResetToLastSelectMode().
Property Documentation
activeTool
Tool UnityEditor.ProBuilder.ProBuilderToolManager.activeTool static get
Referenced by UnityEditor.ProBuilder.ProBuilderToolManager.SetSelectMode().
selectMode
SelectMode UnityEditor.ProBuilder.ProBuilderToolManager.selectMode static get
Referenced by UnityEditor.ProBuilder.ProBuilderToolManager.NextMeshSelectMode(), and UnityEditor.ProBuilder.ProBuilderToolManager.SetSelectMode().
Event Documentation
selectModeChanged
Action UnityEditor.ProBuilder.ProBuilderToolManager.selectModeChanged = () => {} static
The documentation for this class was generated from the following file:
C:/Users/Lykos/Desktop/Projects/Capstone/VRGames/Library/PackageCache/com.unity.probuilder@5.0.6/Editor/EditorCore/ProBuilderToolManager.cs