VRCapstoneGames: UnityEngine.UI.GraphicRegistry Class Reference
UnityEngine.UI.GraphicRegistry Class Reference
Registry which maps a Graphic to the canvas it belongs to.
Static Public Member Functions
static void RegisterGraphicForCanvas (Canvas c, Graphic graphic)
Associates a Graphic with a Canvas and stores this association in the registry.
static void RegisterRaycastGraphicForCanvas (Canvas c, Graphic graphic)
Associates a raycastable Graphic with a Canvas and stores this association in the registry.
static void UnregisterGraphicForCanvas (Canvas c, Graphic graphic)
Dissociates a Graphic from a Canvas, removing this association from the registry.
static void UnregisterRaycastGraphicForCanvas (Canvas c, Graphic graphic)
Dissociates a Graphic from a Canvas, removing this association from the registry.
static void DisableGraphicForCanvas (Canvas c, Graphic graphic)
Disables a Graphic from a Canvas, disabling this association from the registry.
static void DisableRaycastGraphicForCanvas (Canvas c, Graphic graphic)
Disables the raycast for a Graphic from a Canvas, disabling this association from the registry.
static IList< Graphic > GetGraphicsForCanvas (Canvas canvas)
Retrieves the list of Graphics associated with a Canvas.
static IList< Graphic > GetRaycastableGraphicsForCanvas (Canvas canvas)
Retrieves the list of Graphics that are raycastable and associated with a Canvas.
Protected Member Functions
GraphicRegistry ()
Properties
static GraphicRegistry instance [get]
The singleton instance of the GraphicRegistry. Creates a new instance if it does not exist.
Detailed Description
Registry which maps a Graphic to the canvas it belongs to.
Constructor & Destructor Documentation
GraphicRegistry()
UnityEngine.UI.GraphicRegistry.GraphicRegistry () protected
Member Function Documentation
DisableGraphicForCanvas()
static void UnityEngine.UI.GraphicRegistry.DisableGraphicForCanvas (Canvas c, Graphic graphic) static
Disables a Graphic from a Canvas, disabling this association from the registry.
Parameters
c The Canvas to dissociate from the Graphic.
graphic The Graphic to dissociate from the Canvas.
DisableRaycastGraphicForCanvas()
static void UnityEngine.UI.GraphicRegistry.DisableRaycastGraphicForCanvas (Canvas c, Graphic graphic) static
Disables the raycast for a Graphic from a Canvas, disabling this association from the registry.
Parameters
c The Canvas to dissociate from the Graphic.
graphic The Graphic to dissociate from the Canvas.
Referenced by UnityEngine.UI.GraphicRegistry.DisableGraphicForCanvas().
GetGraphicsForCanvas()
static IList< Graphic > UnityEngine.UI.GraphicRegistry.GetGraphicsForCanvas (Canvas canvas) static
Retrieves the list of Graphics associated with a Canvas.
Parameters
canvas The Canvas to search
Returns
Returns a list of Graphics. Returns an empty list if no Graphics are associated with the specified Canvas.
GetRaycastableGraphicsForCanvas()
static IList< Graphic > UnityEngine.UI.GraphicRegistry.GetRaycastableGraphicsForCanvas (Canvas canvas) static
Retrieves the list of Graphics that are raycastable and associated with a Canvas.
Parameters
canvas The Canvas to search
Returns
Returns a list of Graphics. Returns an empty list if no Graphics are associated with the specified Canvas.
Referenced by UnityEngine.UI.GraphicRaycaster.Raycast().
RegisterGraphicForCanvas()
static void UnityEngine.UI.GraphicRegistry.RegisterGraphicForCanvas (Canvas c, Graphic graphic) static
Associates a Graphic with a Canvas and stores this association in the registry.
Parameters
c The canvas being associated with the Graphic.
graphic The Graphic being associated with the Canvas.
Referenced by TMPro.TextMeshProUGUI.OnEnable().
RegisterRaycastGraphicForCanvas()
static void UnityEngine.UI.GraphicRegistry.RegisterRaycastGraphicForCanvas (Canvas c, Graphic graphic) static
Associates a raycastable Graphic with a Canvas and stores this association in the registry.
Parameters
c The canvas being associated with the Graphic.
graphic The Graphic being associated with the Canvas.
Referenced by UnityEngine.UI.GraphicRegistry.RegisterGraphicForCanvas().
UnregisterGraphicForCanvas()
static void UnityEngine.UI.GraphicRegistry.UnregisterGraphicForCanvas (Canvas c, Graphic graphic) static
Dissociates a Graphic from a Canvas, removing this association from the registry.
Parameters
c The Canvas to dissociate from the Graphic.
graphic The Graphic to dissociate from the Canvas.
Referenced by TMPro.TextMeshProUGUI.OnDestroy(), and TMPro.TextMeshProUGUI.OnDisable().
UnregisterRaycastGraphicForCanvas()
static void UnityEngine.UI.GraphicRegistry.UnregisterRaycastGraphicForCanvas (Canvas c, Graphic graphic) static
Dissociates a Graphic from a Canvas, removing this association from the registry.
Parameters
c The Canvas to dissociate from the Graphic.
graphic The Graphic to dissociate from the Canvas.
Referenced by UnityEngine.UI.GraphicRegistry.UnregisterGraphicForCanvas().
Property Documentation
instance
GraphicRegistry UnityEngine.UI.GraphicRegistry.instance static get
The singleton instance of the GraphicRegistry. Creates a new instance if it does not exist.
Referenced by UnityEngine.UI.GraphicRegistry.DisableGraphicForCanvas(), UnityEngine.UI.GraphicRegistry.DisableRaycastGraphicForCanvas(), UnityEngine.UI.GraphicRegistry.GetGraphicsForCanvas(), UnityEngine.UI.GraphicRegistry.GetRaycastableGraphicsForCanvas(), UnityEngine.UI.GraphicRegistry.RegisterGraphicForCanvas(), UnityEngine.UI.GraphicRegistry.RegisterRaycastGraphicForCanvas(), UnityEngine.UI.GraphicRegistry.UnregisterGraphicForCanvas(), and UnityEngine.UI.GraphicRegistry.UnregisterRaycastGraphicForCanvas().
The documentation for this class was generated from the following file:
C:/Users/Lykos/Desktop/Projects/Capstone/VRGames/Library/PackageCache/com.unity.ugui@1.0.0/Runtime/UI/Core/GraphicRegistry.cs