VRGames: DartManager Class Reference
DartManager Class Reference
Public Member Functions
void DespawnDart (GameObject dart)
bool IsLeftDart (GameObject dart)
bool IsRightDart (GameObject dart)
void DestroyDarts ()
void AdjustLeftSpawn (float x, float y, float z)
void AdjustRightSpawn (float x, float y, float z)
void AdjustBothSpawns (float x, float y, float z)
Properties
static DartManager Instance [get]
Detailed Description
The DartManager class handles the spawning and despawning of darts in the scene.
Member Function Documentation
AdjustBothSpawns()
void DartManager.AdjustBothSpawns (float x, float y, float z)
The AdjustLeftSpawn adjusts the left and right spawns of the darts using the given offsets.
Parameters
x The offset in the x direction.
y The offset in the y direction.
z The offset in the z direction.
AdjustLeftSpawn()
void DartManager.AdjustLeftSpawn (float x, float y, float z)
The AdjustLeftSpawn adjusts the left spawn of the darts using the given offsets.
Parameters
x The offset in the x direction.
y The offset in the y direction.
z The offset in the z direction.
Referenced by AdjustBothSpawns().
AdjustRightSpawn()
void DartManager.AdjustRightSpawn (float x, float y, float z)
The AdjustRightSpawn adjusts the right spawn of the darts using the given offsets.
Parameters
x The offset in the x direction.
y The offset in the y direction.
z The offset in the z direction.
Referenced by AdjustBothSpawns().
DespawnDart()
void DartManager.DespawnDart (GameObject dart)
Despawns the dart and automatically spawns another dart in the appropriate location depending on whether the passed in dart is the left or right dart.
Parameters
dart The dart to despawn.
DestroyDarts()
void DartManager.DestroyDarts ()
Destroys all of the darts in the scene.
IsLeftDart()
bool DartManager.IsLeftDart (GameObject dart)
Checks to see if the dart is the left dart.
Parameters
dart The dart to be checked.
Referenced by DespawnDart().
IsRightDart()
bool DartManager.IsRightDart (GameObject dart)
Checks to see if the dart is the right dart.
Parameters
dart The dart to be checked.
Referenced by DespawnDart().
Property Documentation
Instance
DartManager DartManager.Instance static get
Referenced by BalloonsGame.Balloon.IsCorrectDart(), BalloonsGame.Balloon_Target_Bullseye.IsCorrectDart(), BalloonsGame.Balloon.OnTriggerEnter(), and BalloonsGame.Balloon_Target_Bullseye.OnTriggerEnter().
The documentation for this class was generated from the following file:
C:/Users/Lykos/Desktop/Projects/Capstone/VRGames/Assets/BalloonGame/Scripts/Managers/DartManager.cs