VRCapstoneGames: Unity.XR.CoreUtils.XROrigin Class Reference
Unity.XR.CoreUtils.XROrigin Class Reference
The XR Origin component is typically attached to the base object of the XR Origin, and stores the GameObject that will be manipulated via locomotion. It is also used for offsetting the camera.
Public Types
enum TrackingOriginMode { NotSpecified , Device , Floor }
Sets which Tracking Origin Mode to use when initializing the input device.
Public Member Functions
bool RotateAroundCameraUsingOriginUp (float angleDegrees)
Rotates the XR origin object around the camera object by the provided angleDegrees . This rotation only occurs around the origin's Up vector.
bool RotateAroundCameraPosition (Vector3 vector, float angleDegrees)
Rotates the XR origin object around the camera object's position in world space using the provided vector as the rotation axis. The XR Origin object is rotated by the amount of degrees provided in angleDegrees .
bool MatchOriginUp (Vector3 destinationUp)
This function will rotate the XR Origin object such that the XR Origin's up vector will match the provided vector.
bool MatchOriginUpCameraForward (Vector3 destinationUp, Vector3 destinationForward)
This function will rotate the XR Origin object around the camera object using the destinationUp vector such that:
The camera will look at the area in the direction of the destinationForward
The projection of camera's forward vector on the plane with the normal destinationUp will be in the direction of destinationForward
The up vector of the XR Origin object will match the provided destinationUp vector (note that the camera's Up vector can not be manipulated)
bool MatchOriginUpOriginForward (Vector3 destinationUp, Vector3 destinationForward)
This function will rotate the XR Origin object around the camera object using the destinationUp vector such that:
The forward vector of the XR Origin object, which is the direction the player moves in Unity when walking forward in the physical world, will match the provided destinationUp vector
The up vector of the XR Origin object will match the provided destinationUp vector
bool MoveCameraToWorldLocation (Vector3 desiredWorldLocation)
This function moves the camera to the world location provided by desiredWorldLocation . It does this by moving the XR Origin object so that the camera's world location matches the desiredWorldLocation.
Protected Member Functions
void Awake ()
See MonoBehaviour.
void OnEnable ()
See MonoBehaviour.
void OnDisable ()
See MonoBehaviour.
void OnValidate ()
See MonoBehaviour.
void Start ()
See MonoBehaviour.
void OnDestroy ()
See MonoBehaviour.
Properties
Camera Camera [get, set]
The Camera to associate with the XR device. It must be a child of this XROrigin.
Transform TrackablesParent [get]
The parent Transform for all "trackables" (for example, planes and feature points).
GameObject Origin [get, set]
The "Origin" GameObject is used to refer to the base of the XR Origin, by default it is this GameObject. This is the GameObject that will be manipulated via locomotion.
GameObject CameraFloorOffsetObject [get, set]
The GameObject to move to desired height off the floor (defaults to this object if none provided). This is used to transform the XR device from camera space to XR Origin space.
TrackingOriginMode RequestedTrackingOriginMode [get, set]
The type of tracking origin to use for this XROrigin. Tracking origins identify where (0, 0, 0) is in the world of tracking. Not all devices support all tracking origin modes.
float CameraYOffset [get, set]
Camera height to be used when in Device Tracking Origin Mode to define the height of the user from the floor. This is the amount that the camera is offset from the floor when moving the CameraFloorOffsetObject.
TrackingOriginModeFlags CurrentTrackingOriginMode [get]
(Read Only) The Tracking Origin Mode of this XR Origin.
Vector3 OriginInCameraSpacePos [get]
(Read Only) The origin's local position in camera space.
Vector3 CameraInOriginSpacePos [get]
(Read Only) The camera's local position in origin space.
float CameraInOriginSpaceHeight [get]
(Read Only) The camera's height relative to the origin.
Events
Action< ARTrackablesParentTransformChangedEventArgs > TrackablesParentTransformChanged
Invoked during Application.onBeforeRender whenever the TrackablesParent transform changes.
Detailed Description
The XR Origin component is typically attached to the base object of the XR Origin, and stores the GameObject that will be manipulated via locomotion. It is also used for offsetting the camera.
Member Enumeration Documentation
TrackingOriginMode
enum Unity.XR.CoreUtils.XROrigin.TrackingOriginMode
Sets which Tracking Origin Mode to use when initializing the input device.
See also
RequestedTrackingOriginMode, TrackingOriginModeFlags, XRInputSubsystem.TrySetTrackingOriginMode
Enumerator
NotSpecified
Uses the default Tracking Origin Mode of the input device.
When changing to this value after startup, the Tracking Origin Mode will not be changed.
Device
Sets the Tracking Origin Mode to TrackingOriginModeFlags.Device. Input devices will be tracked relative to the first known location.
Represents a device-relative tracking origin. A device-relative tracking origin defines a local origin at the position of the device in space at some previous point in time, usually at a recenter event, power-on, or AR/VR session start. Pose data provided by the device will be in this space relative to the local origin. This means that poses returned in this mode will not include the user height (for VR) or the device height (for AR) and any camera tracking from the XR device will need to be manually offset accordingly.
See also
TrackingOriginModeFlags.Device
Floor
Sets the Tracking Origin Mode to TrackingOriginModeFlags.Floor. Input devices will be tracked relative to a location on the floor.
Represents the tracking origin whereby (0, 0, 0) is on the "floor" or other surface determined by the XR device being used. The pose values reported by an XR device in this mode will include the height of the XR device above this surface, removing the need to offset the position of the camera tracking the XR device by the height of the user (VR) or the height of the device above the floor (AR).
See also
TrackingOriginModeFlags.Floor
Member Function Documentation
Awake()
void Unity.XR.CoreUtils.XROrigin.Awake () protected
See MonoBehaviour.
MatchOriginUp()
bool Unity.XR.CoreUtils.XROrigin.MatchOriginUp (Vector3 destinationUp)
This function will rotate the XR Origin object such that the XR Origin's up vector will match the provided vector.
Parameters
destinationUp the vector to which the XR Origin object's up vector will be matched.
Returns
Returns true if the rotation is performed or the vectors have already been matched. Otherwise, returns false.
Referenced by Unity.XR.CoreUtils.XROrigin.MatchOriginUpCameraForward(), and Unity.XR.CoreUtils.XROrigin.MatchOriginUpOriginForward().
MatchOriginUpCameraForward()
bool Unity.XR.CoreUtils.XROrigin.MatchOriginUpCameraForward (Vector3 destinationUp, Vector3 destinationForward)
This function will rotate the XR Origin object around the camera object using the destinationUp vector such that:
The camera will look at the area in the direction of the destinationForward
The projection of camera's forward vector on the plane with the normal destinationUp will be in the direction of destinationForward
The up vector of the XR Origin object will match the provided destinationUp vector (note that the camera's Up vector can not be manipulated)
Parameters
destinationUp The up vector that the origin's up vector will be matched to.
destinationForward The forward vector that will be matched to the projection of the camera's forward vector on the plane with the normal destinationUp .
Returns
Returns true if the rotation is performed. Otherwise, returns false.
MatchOriginUpOriginForward()
bool Unity.XR.CoreUtils.XROrigin.MatchOriginUpOriginForward (Vector3 destinationUp, Vector3 destinationForward)
This function will rotate the XR Origin object around the camera object using the destinationUp vector such that:
The forward vector of the XR Origin object, which is the direction the player moves in Unity when walking forward in the physical world, will match the provided destinationUp vector
The up vector of the XR Origin object will match the provided destinationUp vector
Parameters
destinationUp The up vector that the origin's up vector will be matched to.
destinationForward The forward vector that will be matched to the forward vector of the XR Origin object, which is the direction the player moves in Unity when walking forward in the physical world.
Returns
Returns true if the rotation is performed. Otherwise, returns false.
MoveCameraToWorldLocation()
bool Unity.XR.CoreUtils.XROrigin.MoveCameraToWorldLocation (Vector3 desiredWorldLocation)
This function moves the camera to the world location provided by desiredWorldLocation . It does this by moving the XR Origin object so that the camera's world location matches the desiredWorldLocation.
Parameters
desiredWorldLocation the position in world space that the camera should be moved to
Returns
Returns true if the move is performed. Otherwise, returns false.
OnDestroy()
void Unity.XR.CoreUtils.XROrigin.OnDestroy () protected
See MonoBehaviour.
OnDisable()
void Unity.XR.CoreUtils.XROrigin.OnDisable () protected
See MonoBehaviour.
OnEnable()
void Unity.XR.CoreUtils.XROrigin.OnEnable () protected
See MonoBehaviour.
OnValidate()
void Unity.XR.CoreUtils.XROrigin.OnValidate () protected
See MonoBehaviour.
RotateAroundCameraPosition()
bool Unity.XR.CoreUtils.XROrigin.RotateAroundCameraPosition (Vector3 vector, float angleDegrees)
Rotates the XR origin object around the camera object's position in world space using the provided vector as the rotation axis. The XR Origin object is rotated by the amount of degrees provided in angleDegrees .
Parameters
vector The axis of the rotation.
angleDegrees The amount of rotation in degrees.
Returns
Returns true if the rotation is performed. Otherwise, returns false.
Referenced by Unity.XR.CoreUtils.XROrigin.MatchOriginUpCameraForward(), Unity.XR.CoreUtils.XROrigin.MatchOriginUpOriginForward(), and Unity.XR.CoreUtils.XROrigin.RotateAroundCameraUsingOriginUp().
RotateAroundCameraUsingOriginUp()
bool Unity.XR.CoreUtils.XROrigin.RotateAroundCameraUsingOriginUp (float angleDegrees)
Rotates the XR origin object around the camera object by the provided angleDegrees . This rotation only occurs around the origin's Up vector.
Parameters
angleDegrees The amount of rotation in degrees.
Returns
Returns true if the rotation is performed. Otherwise, returns false.
Start()
void Unity.XR.CoreUtils.XROrigin.Start () protected
See MonoBehaviour.
Property Documentation
Camera
Camera Unity.XR.CoreUtils.XROrigin.Camera get set
The Camera to associate with the XR device. It must be a child of this XROrigin.
The Camera should update its position and rotation according to the XR device. This is typically accomplished by adding a TrackedPoseDriver component to the Camera.
Referenced by Unity.XR.CoreUtils.XROrigin.Awake(), and UnityEngine.XR.Interaction.Toolkit.XRRig.Awake().
CameraFloorOffsetObject
GameObject Unity.XR.CoreUtils.XROrigin.CameraFloorOffsetObject get set
The GameObject to move to desired height off the floor (defaults to this object if none provided). This is used to transform the XR device from camera space to XR Origin space.
CameraInOriginSpaceHeight
float Unity.XR.CoreUtils.XROrigin.CameraInOriginSpaceHeight get
(Read Only) The camera's height relative to the origin.
Referenced by UnityEngine.XR.Interaction.Toolkit.CharacterControllerDriver.UpdateCharacterController().
CameraInOriginSpacePos
Vector3 Unity.XR.CoreUtils.XROrigin.CameraInOriginSpacePos get
(Read Only) The camera's local position in origin space.
Referenced by UnityEngine.XR.Interaction.Toolkit.CharacterControllerDriver.UpdateCharacterController().
CameraYOffset
float Unity.XR.CoreUtils.XROrigin.CameraYOffset get set
Camera height to be used when in Device Tracking Origin Mode to define the height of the user from the floor. This is the amount that the camera is offset from the floor when moving the CameraFloorOffsetObject.
CurrentTrackingOriginMode
TrackingOriginModeFlags Unity.XR.CoreUtils.XROrigin.CurrentTrackingOriginMode get
(Read Only) The Tracking Origin Mode of this XR Origin.
See also
RequestedTrackingOriginMode
Origin
GameObject Unity.XR.CoreUtils.XROrigin.Origin get set
The "Origin" GameObject is used to refer to the base of the XR Origin, by default it is this GameObject. This is the GameObject that will be manipulated via locomotion.
OriginInCameraSpacePos
Vector3 Unity.XR.CoreUtils.XROrigin.OriginInCameraSpacePos get
(Read Only) The origin's local position in camera space.
Referenced by Unity.XR.CoreUtils.XROrigin.MoveCameraToWorldLocation().
RequestedTrackingOriginMode
TrackingOriginMode Unity.XR.CoreUtils.XROrigin.RequestedTrackingOriginMode get set
The type of tracking origin to use for this XROrigin. Tracking origins identify where (0, 0, 0) is in the world of tracking. Not all devices support all tracking origin modes.
See also
TrackingOriginMode
TrackablesParent
Transform Unity.XR.CoreUtils.XROrigin.TrackablesParent get
The parent Transform for all "trackables" (for example, planes and feature points).
Referenced by Unity.XR.CoreUtils.XROrigin.Awake(), and Unity.XR.CoreUtils.XROrigin.OnDisable().
Event Documentation
TrackablesParentTransformChanged
Action<ARTrackablesParentTransformChangedEventArgs> Unity.XR.CoreUtils.XROrigin.TrackablesParentTransformChanged
Invoked during Application.onBeforeRender whenever the TrackablesParent transform changes.
Referenced by Unity.XR.CoreUtils.XROrigin.OnDisable().
The documentation for this class was generated from the following file:
C:/Users/Lykos/Desktop/Projects/Capstone/VRGames/Library/PackageCache/com.unity.xr.core-utils@2.0.0/Runtime/XROrigin.cs