VRGames: UnityEngine.InputSystem.InputRecorder Class Reference
UnityEngine.InputSystem.InputRecorder Class Reference
A wrapper component around InputEventTrace that provides an easy interface for recording input from a GameObject.
Classes
class ChangeEvent
Public Types
enum Change {
None , EventCaptured , EventPlayed , CaptureStarted ,
CaptureStopped , ReplayStarted , ReplayStopped
}
Public Member Functions
void StartCapture ()
void StopCapture ()
void StartReplay ()
void StopReplay ()
void PauseReplay ()
void ClearCapture ()
void LoadCaptureFromFile (string fileName)
void SaveCaptureToFile (string fileName)
Protected Member Functions
void OnEnable ()
void OnDisable ()
void OnDestroy ()
Properties
bool captureIsRunning [get]
Whether a capture is currently in progress.
bool replayIsRunning [get]
Whether a replay is currently being run by the component.
bool startRecordingWhenEnabled [get, set]
If true, input recording is started immediately when the component is enabled. Disabled by default. Call StartCapture to manually start capturing.
long eventCount [get]
Total number of events captured.
long totalEventSizeInBytes [get]
Total size of captured events.
long allocatedSizeInBytes [get]
Total size of capture memory currently allocated.
bool recordFrames [get, set]
Whether to record frame marker events when capturing input. Enabled by default.
bool recordStateEventsOnly [get, set]
Whether to record only StateEvents and DeltaStateEvents. Disabled by default.
string devicePath [get, set]
Path that constrains the devices to record from.
string recordButtonPath [get, set]
string playButtonPath [get, set]
InputEventTrace capture [get]
The underlying event trace that contains the captured input events.
InputEventTrace.ReplayController replay [get]
The replay controller for when a replay is running.
int replayPosition [get]
bool replayOnNewDevices [get, set]
Whether a replay should create new devices or replay recorded events as is. Disabled by default.
bool simulateOriginalTimingOnReplay [get, set]
Whether to attempt to re-create the original event timing when replaying events. Disabled by default.
ChangeEvent changeEvent [get]
Detailed Description
A wrapper component around InputEventTrace that provides an easy interface for recording input from a GameObject.
This component comes with a custom inspector that provides an easy recording and playback interface and also gives feedback about what has been recorded in the trace. The interface also allows saving and loading event traces.
Capturing can either be constrained by a devicePath or capture all input occuring in the system.
Replay by default will happen frame by frame (see InputEventTrace.ReplayController.PlayAllFramesOneByOne). If frame markers are disabled (see recordFrames), all events are queued right away in the first frame and replay completes immediately.
Other than frame-by-frame, replay can be made to happen in a way that tries to simulate the original input timing. To do so, enable simulateOriginalTimingOnReplay. This will make use of InputEventTrace.ReplayController.PlayAllEventsAccordingToTimestamps
Member Enumeration Documentation
Change
enum UnityEngine.InputSystem.InputRecorder.Change
Enumerator
None
EventCaptured
EventPlayed
CaptureStarted
CaptureStopped
ReplayStarted
ReplayStopped
Member Function Documentation
ClearCapture()
void UnityEngine.InputSystem.InputRecorder.ClearCapture ()
LoadCaptureFromFile()
void UnityEngine.InputSystem.InputRecorder.LoadCaptureFromFile (string fileName)
OnDestroy()
void UnityEngine.InputSystem.InputRecorder.OnDestroy () protected
OnDisable()
void UnityEngine.InputSystem.InputRecorder.OnDisable () protected
OnEnable()
void UnityEngine.InputSystem.InputRecorder.OnEnable () protected
PauseReplay()
void UnityEngine.InputSystem.InputRecorder.PauseReplay ()
SaveCaptureToFile()
void UnityEngine.InputSystem.InputRecorder.SaveCaptureToFile (string fileName)
StartCapture()
void UnityEngine.InputSystem.InputRecorder.StartCapture ()
Referenced by UnityEngine.InputSystem.InputRecorder.OnEnable().
StartReplay()
void UnityEngine.InputSystem.InputRecorder.StartReplay ()
StopCapture()
void UnityEngine.InputSystem.InputRecorder.StopCapture ()
Referenced by UnityEngine.InputSystem.InputRecorder.OnDisable(), and UnityEngine.InputSystem.InputRecorder.StartReplay().
StopReplay()
void UnityEngine.InputSystem.InputRecorder.StopReplay ()
Referenced by UnityEngine.InputSystem.InputRecorder.OnDisable(), and UnityEngine.InputSystem.InputRecorder.StartReplay().
Property Documentation
allocatedSizeInBytes
long UnityEngine.InputSystem.InputRecorder.allocatedSizeInBytes get
Total size of capture memory currently allocated.
Size of memory allocated for capture.
capture
InputEventTrace UnityEngine.InputSystem.InputRecorder.capture get
The underlying event trace that contains the captured input events.
Underlying event trace.
This will be null if no capture is currently associated with the recorder.
captureIsRunning
bool UnityEngine.InputSystem.InputRecorder.captureIsRunning get
Whether a capture is currently in progress.
True if a capture is in progress.
changeEvent
ChangeEvent UnityEngine.InputSystem.InputRecorder.changeEvent get
devicePath
string UnityEngine.InputSystem.InputRecorder.devicePath get set
Path that constrains the devices to record from.
Input control path to match devices or null/empty.
By default, this is not set. Meaning that input will be recorded from all devices. By setting this property to a path, only events for devices that match the given path (as dictated by InputControlPath.Matches) will be recorded from.
By setting this property to the exact path of a device at runtime, recording can be restricted to just that device.
See also
InputControlPath, InputControlPath.Matches
eventCount
long UnityEngine.InputSystem.InputRecorder.eventCount get
Total number of events captured.
Number of captured events.
playButtonPath
string UnityEngine.InputSystem.InputRecorder.playButtonPath get set
recordButtonPath
string UnityEngine.InputSystem.InputRecorder.recordButtonPath get set
recordFrames
bool UnityEngine.InputSystem.InputRecorder.recordFrames get set
Whether to record frame marker events when capturing input. Enabled by default.
True if frame marker events will be recorded.
See also
InputEventTrace.recordFrameMarkers
recordStateEventsOnly
bool UnityEngine.InputSystem.InputRecorder.recordStateEventsOnly get set
Whether to record only StateEvents and DeltaStateEvents. Disabled by default.
True if anything but state events should be ignored.
replay
InputEventTrace.ReplayController UnityEngine.InputSystem.InputRecorder.replay get
The replay controller for when a replay is running.
Replay controller for the event trace while replay is running.
See also
replayIsRunning, StartReplay
Referenced by UnityEngine.InputSystem.InputRecorder.StartReplay().
replayIsRunning
bool UnityEngine.InputSystem.InputRecorder.replayIsRunning get
Whether a replay is currently being run by the component.
True if replay is running.
See also
replay, StartReplay, StopReplay
Referenced by UnityEngine.InputSystem.InputRecorder.StartReplay().
replayOnNewDevices
bool UnityEngine.InputSystem.InputRecorder.replayOnNewDevices get set
Whether a replay should create new devices or replay recorded events as is. Disabled by default.
True if replay should temporary create new devices.
See also
InputEventTrace.ReplayController.WithAllDevicesMappedToNewInstances
replayPosition
int UnityEngine.InputSystem.InputRecorder.replayPosition get
simulateOriginalTimingOnReplay
bool UnityEngine.InputSystem.InputRecorder.simulateOriginalTimingOnReplay get set
Whether to attempt to re-create the original event timing when replaying events. Disabled by default.
If true, events are queued based on their timestamp rather than based on their recorded frames (if any).
See also
InputEventTrace.ReplayController.PlayAllEventsAccordingToTimestamps
startRecordingWhenEnabled
bool UnityEngine.InputSystem.InputRecorder.startRecordingWhenEnabled get set
If true, input recording is started immediately when the component is enabled. Disabled by default. Call StartCapture to manually start capturing.
True if component will start recording automatically in OnEnable.
See also
StartCapture
totalEventSizeInBytes
long UnityEngine.InputSystem.InputRecorder.totalEventSizeInBytes get
Total size of captured events.
Size of captured events in bytes.
The documentation for this class was generated from the following file:
C:/Users/Lykos/Desktop/Projects/Capstone/VRGames/Library/PackageCache/com.unity.inputsystem@1.3.0/Samples~/InputRecorder/InputRecorder.cs