VRGames: UnityEngine.InputSystem.Utilities.InputActionTrace Class Reference
UnityEngine.InputSystem.Utilities.InputActionTrace Class Reference sealed
Records the triggering of actions into a sequence of events that can be replayed at will.
Classes
struct ActionEventPtr
A wrapper around ActionEvent that automatically translates all the information in events into their high-level representations.
Public Member Functions
InputActionTrace ()
InputActionTrace (InputAction action)
InputActionTrace (InputActionMap actionMap)
void SubscribeToAll ()
Record any action getting triggered anywhere.
void UnsubscribeFromAll ()
void SubscribeTo (InputAction action)
void SubscribeTo (InputActionMap actionMap)
void UnsubscribeFrom (InputAction action)
void UnsubscribeFrom (InputActionMap actionMap)
unsafe void RecordAction (InputAction.CallbackContext context)
Record the triggering of an action as an action event.
void Clear ()
override string ToString ()
void Dispose ()
IEnumerator< ActionEventPtr > GetEnumerator ()
Properties
InputEventBuffer buffer [get]
Directly access the underlying raw memory queue.
int count [get]
Detailed Description
Records the triggering of actions into a sequence of events that can be replayed at will.
This is an alternate way to the callback-based responses (such as InputAction.performed) of input actions. Instead of executing response code right away whenever an action triggers, an event is recorded which can then be queried on demand.
The recorded data will stay valid even if the bindings on the actions are changed (e.g. by enabling a different set of bindings through altering InputAction.bindingMask or InputActionMap.devices or when modifying the paths of bindings altogether). Note, however, that when this happens, a trace will have to make a private copy of the data that stores the binding resolution state. This means that there can be GC allocation spike when reconfiguring actions that have recorded data in traces.
var trace = new InputActionTrace();
// Subscribe trace to single action.
// (Use UnsubscribeFrom to unsubscribe)
trace.SubscribeTo(myAction);
// Subscribe trace to entire action map.
// (Use UnsubscribeFrom to unsubscribe)
trace.SubscribeTo(myActionMap);
// Subscribe trace to all actions in the system.
trace.SubscribeToAll();
// Record a single triggering of an action.
myAction.performed +=
    ctx =>
    {
        if (ctx.ReadValue<float>() > 0.5f)
            trace.RecordAction(ctx);
    };
// Output trace to console.
Debug.Log(string.Join(",\n", trace));
// Walk through all recorded actions and then clear trace.
foreach (var record in trace)
{
    Debug.Log($"{record.action} was {record.phase} by control {record.control} at {record.time}");
    // To read out the value, you either have to know the value type or read the
    // value out as a generic byte buffer. Here we assume that the value type is
    // float.
    Debug.Log("Value: " + record.ReadValue<float>());
    // An alternative is read the value as an object. In this case, you don't have
    // to know the value type but there will be a boxed object allocation.
    Debug.Log("Value: " + record.ReadValueAsObject());
}
trace.Clear();
// Unsubscribe trace from everything.
trace.UnsubscribeFromAll();
// Release memory held by trace.
trace.Dispose();
See also
InputAction.started, InputAction.performed, InputAction.canceled, InputSystem.onActionChange
Constructor & Destructor Documentation
InputActionTrace() [1/3]
UnityEngine.InputSystem.Utilities.InputActionTrace.InputActionTrace ()
InputActionTrace() [2/3]
UnityEngine.InputSystem.Utilities.InputActionTrace.InputActionTrace (InputAction action)
InputActionTrace() [3/3]
UnityEngine.InputSystem.Utilities.InputActionTrace.InputActionTrace (InputActionMap actionMap)
Member Function Documentation
Clear()
void UnityEngine.InputSystem.Utilities.InputActionTrace.Clear ()
Dispose()
void UnityEngine.InputSystem.Utilities.InputActionTrace.Dispose ()
GetEnumerator()
IEnumerator< ActionEventPtr > UnityEngine.InputSystem.Utilities.InputActionTrace.GetEnumerator ()
RecordAction()
unsafe void UnityEngine.InputSystem.Utilities.InputActionTrace.RecordAction (InputAction::CallbackContext context)
Record the triggering of an action as an action event.
Parameters
context
InputAction.performed InputAction.started InputAction.canceled InputActionMap.actionTriggered
Referenced by UnityEngine.InputSystem.Utilities.InputActionTrace.SubscribeTo(), and UnityEngine.InputSystem.Utilities.InputActionTrace.SubscribeTo().
SubscribeTo() [1/2]
void UnityEngine.InputSystem.Utilities.InputActionTrace.SubscribeTo (InputAction action)
Referenced by UnityEngine.InputSystem.Utilities.InputActionTrace.InputActionTrace(), and UnityEngine.InputSystem.Utilities.InputActionTrace.InputActionTrace().
SubscribeTo() [2/2]
void UnityEngine.InputSystem.Utilities.InputActionTrace.SubscribeTo (InputActionMap actionMap)
SubscribeToAll()
void UnityEngine.InputSystem.Utilities.InputActionTrace.SubscribeToAll ()
Record any action getting triggered anywhere.
This does not require the trace to actually hook into every single action or action map in the system. Instead, the trace will listen to InputSystem.onActionChange and automatically record every triggered action.
ToString()
override string UnityEngine.InputSystem.Utilities.InputActionTrace.ToString ()
UnsubscribeFrom() [1/2]
void UnityEngine.InputSystem.Utilities.InputActionTrace.UnsubscribeFrom (InputAction action)
Referenced by UnityEngine.InputSystem.Utilities.InputActionTrace.SubscribeToAll(), and UnityEngine.InputSystem.Utilities.InputActionTrace.UnsubscribeFromAll().
UnsubscribeFrom() [2/2]
void UnityEngine.InputSystem.Utilities.InputActionTrace.UnsubscribeFrom (InputActionMap actionMap)
UnsubscribeFromAll()
void UnityEngine.InputSystem.Utilities.InputActionTrace.UnsubscribeFromAll ()
Referenced by UnityEngine.InputSystem.Utilities.InputActionTrace.Dispose().
Property Documentation
buffer
InputEventBuffer UnityEngine.InputSystem.Utilities.InputActionTrace.buffer get
Directly access the underlying raw memory queue.
REVIEW: this is of limited use without having access to ActionEvent
Referenced by UnityEngine.InputSystem.Utilities.InputActionTrace.ActionEventPtr.ReadValue().
count
int UnityEngine.InputSystem.Utilities.InputActionTrace.count get
Referenced by UnityEngine.InputSystem.Utilities.InputActionTrace.ToString(), and UnityEngine.InputSystem.Utilities.InputActionTrace.UnsubscribeFromAll().
The documentation for this class was generated from the following file:
C:/Users/Lykos/Desktop/Projects/Capstone/VRGames/Library/PackageCache/com.unity.inputsystem@1.3.0/InputSystem/Actions/InputActionTrace.cs