VRCapstoneGames: Classes.Managers.BoxAndBlocksGameplayManager Class Reference
Classes.Managers.BoxAndBlocksGameplayManager Class Reference
Public Member Functions
void onFirstPointReached ()
void onTimeExpired ()
async void toggleButtons (bool toggle)
void startSpawning ()
void onBlockGrabbed (GameObject block)
void onBlockReleased (GameObject block)
void killBlock (GameObject block)
override void reset ()
GameObject genRandomBlock ()
void setStartSide (GameObject side)
void setGoalSide (GameObject side)
GameObject getGoalSide ()
Public Member Functions inherited from GameplayManager
GameSettingsSO GetGameSettings ()
virtual void onWinConditionPointsReached ()
void setDifficulty (int newDif)
int getDifficulty ()
void Update ()
virtual void RefreshSettings ()
void PauseGame ()
void ResumeGame ()
void IncreaseDifficulty ()
void DecreaseDifficulty ()
Public Attributes
int blockInterval
GameObject blockPrefab
Material[] blockMaterials
Material grabbedMat
bool leftHand
GameObject leftHandBtn
GameObject rightHandBtn
Public Attributes inherited from GameplayManager
int difficulty = 1
int winConditionPoints = 50
int maxTime
GameSettingsSO gameSettings
int playerLives
Properties
bool Grabbed [get, set]
bool ValidPoint [get, set]
Properties inherited from GameplayManager
static GameplayManager Instance [get]
Additional Inherited Members
Static Public Member Functions inherited from GameplayManager
static GameplayManager getManager ()
Protected Member Functions inherited from GameplayManager
void Start ()
Member Function Documentation
genRandomBlock()
GameObject Classes.Managers.BoxAndBlocksGameplayManager.genRandomBlock ()
getGoalSide()
GameObject Classes.Managers.BoxAndBlocksGameplayManager.getGoalSide ()
Referenced by Block.onGrab().
killBlock()
void Classes.Managers.BoxAndBlocksGameplayManager.killBlock (GameObject block)
onBlockGrabbed()
void Classes.Managers.BoxAndBlocksGameplayManager.onBlockGrabbed (GameObject block)
Referenced by Block.onGrab().
onBlockReleased()
void Classes.Managers.BoxAndBlocksGameplayManager.onBlockReleased (GameObject block)
Referenced by Block.onRelease().
onFirstPointReached()
void Classes.Managers.BoxAndBlocksGameplayManager.onFirstPointReached ()
onTimeExpired()
void Classes.Managers.BoxAndBlocksGameplayManager.onTimeExpired ()
reset()
override void Classes.Managers.BoxAndBlocksGameplayManager.reset () virtual
Reimplemented from GameplayManager.
Referenced by Classes.Managers.BoxAndBlocksGameplayManager.onTimeExpired().
setGoalSide()
void Classes.Managers.BoxAndBlocksGameplayManager.setGoalSide (GameObject side)
setStartSide()
void Classes.Managers.BoxAndBlocksGameplayManager.setStartSide (GameObject side)
startSpawning()
void Classes.Managers.BoxAndBlocksGameplayManager.startSpawning ()
toggleButtons()
async void Classes.Managers.BoxAndBlocksGameplayManager.toggleButtons (bool toggle)
Referenced by Classes.Managers.BoxAndBlocksGameplayManager.onTimeExpired().
Member Data Documentation
blockInterval
int Classes.Managers.BoxAndBlocksGameplayManager.blockInterval
blockMaterials
Material [] Classes.Managers.BoxAndBlocksGameplayManager.blockMaterials
Referenced by Classes.Managers.BoxAndBlocksGameplayManager.genRandomBlock().
blockPrefab
GameObject Classes.Managers.BoxAndBlocksGameplayManager.blockPrefab
Referenced by Classes.Managers.BoxAndBlocksGameplayManager.genRandomBlock().
grabbedMat
Material Classes.Managers.BoxAndBlocksGameplayManager.grabbedMat
leftHand
bool Classes.Managers.BoxAndBlocksGameplayManager.leftHand
leftHandBtn
GameObject Classes.Managers.BoxAndBlocksGameplayManager.leftHandBtn
Referenced by Classes.Managers.BoxAndBlocksGameplayManager.toggleButtons().
rightHandBtn
GameObject Classes.Managers.BoxAndBlocksGameplayManager.rightHandBtn
Referenced by Classes.Managers.BoxAndBlocksGameplayManager.toggleButtons().
Property Documentation
Grabbed
bool Classes.Managers.BoxAndBlocksGameplayManager.Grabbed get set
Referenced by Classes.Managers.BoxAndBlocksGameplayManager.onBlockGrabbed(), and Classes.Managers.BoxAndBlocksGameplayManager.onBlockReleased().
ValidPoint
bool Classes.Managers.BoxAndBlocksGameplayManager.ValidPoint get set
The documentation for this class was generated from the following file:
C:/Users/Lykos/Desktop/Projects/Capstone/VRGames/Assets/Shared/Scripts/Managers/BoxAndBlocksGameplayManager.cs