VRCapstoneGames: Oculus.Interaction.PoseDetection.JointDistanceActiveState Class Reference
Oculus.Interaction.PoseDetection.JointDistanceActiveState Class Reference
This component tracks the distance between two hand joints and reports IActiveState.Active when distance is under a provided threshold.
Public Member Functions
void InjectAllJointDistanceActiveState (IHand handA, HandJointId jointIdA, IHand handB, HandJointId jointIdB)
void InjectHandA (IHand handA)
void InjectJointIdA (HandJointId jointIdA)
void InjectHandB (IHand handB)
void InjectJointIdB (HandJointId jointIdB)
void InjectOptionalDistance (float val)
void InjectOptionalThresholdWidth (float val)
void InjectOptionalMinTimeInState (float val)
Protected Member Functions
virtual void Awake ()
virtual void Start ()
virtual void Update ()
Properties
bool Active [get]
Properties inherited from Oculus.Interaction.IActiveState
Detailed Description
This component tracks the distance between two hand joints and reports IActiveState.Active when distance is under a provided threshold.
Member Function Documentation
Awake()
virtual void Oculus.Interaction.PoseDetection.JointDistanceActiveState.Awake () protected virtual
InjectAllJointDistanceActiveState()
void Oculus.Interaction.PoseDetection.JointDistanceActiveState.InjectAllJointDistanceActiveState (IHand handA, HandJointId jointIdA, IHand handB, HandJointId jointIdB)
InjectHandA()
void Oculus.Interaction.PoseDetection.JointDistanceActiveState.InjectHandA (IHand handA)
Referenced by Oculus.Interaction.PoseDetection.JointDistanceActiveState.InjectAllJointDistanceActiveState().
InjectHandB()
void Oculus.Interaction.PoseDetection.JointDistanceActiveState.InjectHandB (IHand handB)
Referenced by Oculus.Interaction.PoseDetection.JointDistanceActiveState.InjectAllJointDistanceActiveState().
InjectJointIdA()
void Oculus.Interaction.PoseDetection.JointDistanceActiveState.InjectJointIdA (HandJointId jointIdA)
Referenced by Oculus.Interaction.PoseDetection.JointDistanceActiveState.InjectAllJointDistanceActiveState().
InjectJointIdB()
void Oculus.Interaction.PoseDetection.JointDistanceActiveState.InjectJointIdB (HandJointId jointIdB)
Referenced by Oculus.Interaction.PoseDetection.JointDistanceActiveState.InjectAllJointDistanceActiveState().
InjectOptionalDistance()
void Oculus.Interaction.PoseDetection.JointDistanceActiveState.InjectOptionalDistance (float val)
InjectOptionalMinTimeInState()
void Oculus.Interaction.PoseDetection.JointDistanceActiveState.InjectOptionalMinTimeInState (float val)
InjectOptionalThresholdWidth()
void Oculus.Interaction.PoseDetection.JointDistanceActiveState.InjectOptionalThresholdWidth (float val)
Start()
virtual void Oculus.Interaction.PoseDetection.JointDistanceActiveState.Start () protected virtual
Update()
virtual void Oculus.Interaction.PoseDetection.JointDistanceActiveState.Update () protected virtual
Property Documentation
Active
bool Oculus.Interaction.PoseDetection.JointDistanceActiveState.Active get
Implements Oculus.Interaction.IActiveState.
The documentation for this class was generated from the following file:
C:/Users/Lykos/Desktop/Projects/Capstone/VRGames/Assets/ThirdParty/Oculus/Interaction/Runtime/Scripts/PoseDetection/JointDistanceActiveState.cs