VRCapstoneGames: UnityEngine.ProBuilder.Csg.Node Class Reference
UnityEngine.ProBuilder.Csg.Node Class Reference sealed
Public Member Functions
Node ()
Node (List< Polygon > list)
Node (List< Polygon > list, Plane plane, Node front, Node back)
Node Clone ()
void ClipTo (Node other)
void Invert ()
void Build (List< Polygon > list)
List< Polygon > ClipPolygons (List< Polygon > list)
List< Polygon > AllPolygons ()
Static Public Member Functions
static Node Union (Node a1, Node b1)
static Node Subtract (Node a1, Node b1)
static Node Intersect (Node a1, Node b1)
Public Attributes
List< Polygon > polygons
Node front
Node back
Plane plane
Constructor & Destructor Documentation
Node() [1/3]
UnityEngine.ProBuilder.Csg.Node.Node ()
Referenced by UnityEngine.ProBuilder.Csg.Node.Build(), UnityEngine.ProBuilder.Csg.Node.Clone(), UnityEngine.ProBuilder.Csg.Node.Intersect(), UnityEngine.ProBuilder.Csg.Node.Subtract(), and UnityEngine.ProBuilder.Csg.Node.Union().
Node() [2/3]
UnityEngine.ProBuilder.Csg.Node.Node (List< Polygon > list)
Node() [3/3]
UnityEngine.ProBuilder.Csg.Node.Node (List< Polygon > list, Plane plane, Node front, Node back)
Member Function Documentation
AllPolygons()
List< Polygon > UnityEngine.ProBuilder.Csg.Node.AllPolygons ()
Referenced by UnityEngine.ProBuilder.Csg.Node.AllPolygons(), UnityEngine.ProBuilder.Csg.Node.Intersect(), UnityEngine.ProBuilder.Csg.Node.Subtract(), and UnityEngine.ProBuilder.Csg.Node.Union().
Build()
void UnityEngine.ProBuilder.Csg.Node.Build (List< Polygon > list)
Referenced by UnityEngine.ProBuilder.Csg.Node.Intersect(), UnityEngine.ProBuilder.Csg.Node.Subtract(), and UnityEngine.ProBuilder.Csg.Node.Union().
ClipPolygons()
List< Polygon > UnityEngine.ProBuilder.Csg.Node.ClipPolygons (List< Polygon > list)
Referenced by UnityEngine.ProBuilder.Csg.Node.ClipPolygons(), and UnityEngine.ProBuilder.Csg.Node.ClipTo().
ClipTo()
void UnityEngine.ProBuilder.Csg.Node.ClipTo (Node other)
Referenced by UnityEngine.ProBuilder.Csg.Node.ClipTo(), UnityEngine.ProBuilder.Csg.Node.Intersect(), UnityEngine.ProBuilder.Csg.Node.Subtract(), and UnityEngine.ProBuilder.Csg.Node.Union().
Clone()
Node UnityEngine.ProBuilder.Csg.Node.Clone ()
Referenced by UnityEngine.ProBuilder.Csg.Node.Intersect(), UnityEngine.ProBuilder.Csg.Node.Subtract(), and UnityEngine.ProBuilder.Csg.Node.Union().
Intersect()
static Node UnityEngine.ProBuilder.Csg.Node.Intersect (Node a1, Node b1) static
Invert()
void UnityEngine.ProBuilder.Csg.Node.Invert ()
Referenced by UnityEngine.ProBuilder.Csg.Node.Intersect(), UnityEngine.ProBuilder.Csg.Node.Invert(), UnityEngine.ProBuilder.Csg.Node.Subtract(), and UnityEngine.ProBuilder.Csg.Node.Union().
Subtract()
static Node UnityEngine.ProBuilder.Csg.Node.Subtract (Node a1, Node b1) static
Union()
static Node UnityEngine.ProBuilder.Csg.Node.Union (Node a1, Node b1) static
Member Data Documentation
back
Node UnityEngine.ProBuilder.Csg.Node.back
Referenced by UnityEngine.ProBuilder.Csg.Node.Build(), UnityEngine.ProBuilder.Csg.Node.Invert(), UnityEngine.ProBuilder.Csg.Node.Node(), and UnityEngine.ProBuilder.Csg.Node.Node().
front
Node UnityEngine.ProBuilder.Csg.Node.front
Referenced by UnityEngine.ProBuilder.Csg.Node.Build(), UnityEngine.ProBuilder.Csg.Node.Invert(), UnityEngine.ProBuilder.Csg.Node.Node(), and UnityEngine.ProBuilder.Csg.Node.Node().
plane
Plane UnityEngine.ProBuilder.Csg.Node.plane
Referenced by UnityEngine.ProBuilder.Csg.Node.Build(), and UnityEngine.ProBuilder.Csg.Node.Node().
polygons
List<Polygon> UnityEngine.ProBuilder.Csg.Node.polygons
Referenced by UnityEngine.ProBuilder.Csg.Node.AllPolygons(), and UnityEngine.ProBuilder.Csg.Node.Build().
The documentation for this class was generated from the following file:
C:/Users/Lykos/Desktop/Projects/Capstone/VRGames/Library/PackageCache/com.unity.probuilder@5.0.6/External/CSG/Classes/Node.cs