VRCapstoneGames: Oculus.Interaction.Input.FromOVRHandDataSource Class Reference
Oculus.Interaction.Input.FromOVRHandDataSource Class Reference
Public Member Functions
void InjectAllFromOVRHandDataSource (UpdateModeFlags updateMode, IDataSource updateAfter, Handedness handedness, ITrackingToWorldTransformer trackingToWorldTransformer, IHandSkeletonProvider handSkeletonProvider, IDataSource< HmdDataAsset > hmdData)
void InjectHandedness (Handedness handedness)
void InjectTrackingToWorldTransformer (ITrackingToWorldTransformer trackingToWorldTransformer)
void InjectHandSkeletonProvider (IHandSkeletonProvider handSkeletonProvider)
void InjectHmdData (IDataSource< HmdDataAsset > hmdData)
Public Member Functions inherited from Oculus.Interaction.Input.DataSource< HandDataAsset >
TData GetData ()
virtual void MarkInputDataRequiresUpdate ()
Marks the DataAsset stored as outdated, which means it will be re-processed JIT during the next call to GetData.
void InjectAllDataSource (UpdateModeFlags updateMode, IDataSource updateAfter)
void InjectUpdateMode (UpdateModeFlags updateMode)
void InjectUpdateAfter (IDataSource updateAfter)
Protected Member Functions
virtual void Awake ()
override void Start ()
override void UpdateData ()
Protected Member Functions inherited from Oculus.Interaction.Input.DataSource< HandDataAsset >
virtual void OnEnable ()
virtual void OnDisable ()
virtual void Update ()
virtual void FixedUpdate ()
virtual void LateUpdate ()
void ResetUpdateAfter (IDataSource updateAfter, UpdateModeFlags updateMode)
bool RequiresUpdate ()
void UpdateData ()
Properties
override HandDataAsset DataAsset [get]
static Quaternion WristFixupRotation [get]
Properties inherited from Oculus.Interaction.Input.DataSource< HandDataAsset >
bool Started [get]
UpdateModeFlags UpdateMode [get]
bool UpdateModeAfterPrevious [get]
virtual int CurrentDataVersion [get]
TData DataAsset [get]
Returns the current DataAsset, without performing any updates.
Additional Inherited Members
Protected Attributes inherited from Oculus.Interaction.Input.DataSource< HandDataAsset >
bool _started
Events inherited from Oculus.Interaction.Input.DataSource< HandDataAsset >
Action InputDataAvailable
Member Function Documentation
Awake()
virtual void Oculus.Interaction.Input.FromOVRHandDataSource.Awake () protected virtual
InjectAllFromOVRHandDataSource()
void Oculus.Interaction.Input.FromOVRHandDataSource.InjectAllFromOVRHandDataSource (UpdateModeFlags updateMode, IDataSource updateAfter, Handedness handedness, ITrackingToWorldTransformer trackingToWorldTransformer, IHandSkeletonProvider handSkeletonProvider, IDataSource< HmdDataAsset > hmdData)
InjectHandedness()
void Oculus.Interaction.Input.FromOVRHandDataSource.InjectHandedness (Handedness handedness)
Referenced by Oculus.Interaction.Input.FromOVRHandDataSource.InjectAllFromOVRHandDataSource().
InjectHandSkeletonProvider()
void Oculus.Interaction.Input.FromOVRHandDataSource.InjectHandSkeletonProvider (IHandSkeletonProvider handSkeletonProvider)
Referenced by Oculus.Interaction.Input.FromOVRHandDataSource.InjectAllFromOVRHandDataSource().
InjectHmdData()
void Oculus.Interaction.Input.FromOVRHandDataSource.InjectHmdData (IDataSource< HmdDataAsset > hmdData)
Referenced by Oculus.Interaction.Input.FromOVRHandDataSource.InjectAllFromOVRHandDataSource().
InjectTrackingToWorldTransformer()
void Oculus.Interaction.Input.FromOVRHandDataSource.InjectTrackingToWorldTransformer (ITrackingToWorldTransformer trackingToWorldTransformer)
Referenced by Oculus.Interaction.Input.FromOVRHandDataSource.InjectAllFromOVRHandDataSource().
Start()
override void Oculus.Interaction.Input.FromOVRHandDataSource.Start () protected virtual
Reimplemented from Oculus.Interaction.Input.DataSource< HandDataAsset >.
UpdateData()
override void Oculus.Interaction.Input.FromOVRHandDataSource.UpdateData () protected
Property Documentation
DataAsset
override HandDataAsset Oculus.Interaction.Input.FromOVRHandDataSource.DataAsset get protected
WristFixupRotation
Quaternion Oculus.Interaction.Input.FromOVRHandDataSource.WristFixupRotation static get
Initial value:
=
            new Quaternion(0.0f, 1.0f, 0.0f, 0.0f)
The documentation for this class was generated from the following file:
C:/Users/Lykos/Desktop/Projects/Capstone/VRGames/Assets/ThirdParty/Oculus/Interaction/Runtime/Scripts/Input/OVRIntegration/FromOVRHandDataSource.cs