VRGames: UnityEngine.ProBuilder.Vertex Class Reference
UnityEngine.ProBuilder.Vertex Class Reference sealed
Holds information about a single vertex, and provides methods for averaging between multiple Vertex objects.
Public Member Functions
bool HasArrays (MeshArrays attribute)
Tests whether the specified vertex attribute has been set.
Vertex ()
Initializes a Vertex with no values.
override bool Equals (object obj)
Determines whether the specified generic object is equal to this Vertex.
bool Equals (Vertex other)
Determines whether the specified Vertex object is equal to this Vertex by checking whether all components are within a certain distance of the other.
bool Equals (Vertex other, MeshArrays mask)
Determines whether the specified Vertex object is equal to this Vertex by checking whether each component for a specific set of attributes is within a certain distance of the other. The MeshArrays mask determines which set of attributes to compare.
override int GetHashCode ()
Creates a new hashcode from this Vertex's position, UV0, and normal.
Vertex (Vertex vertex)
Creates a new Vertex object as a copy of another Vertex object.
void Add (Vertex b)
Adds another Vertex object to this one using component-wise addition on each attribute.
void Subtract (Vertex b)
Subtracts another Vertex object from this one using component-wise subtraction on each attribute.
void Multiply (float value)
Multiples this Vertex object by the specified value using component-wise multiplication on each attribute.
void Divide (float value)
Divides this Vertex object by the specified value using component-wise division on each attribute.
void Normalize ()
Normalizes all vector values in place.
string ToString (string args=null)
Returns a multi-line string listing every populated attribute.
Static Public Member Functions
static bool operator== (Vertex a, Vertex b)
Determines whether the specified Vertex is equal to this one.
static bool operator!= (Vertex a, Vertex b)
Determines whether the specified Vertex is not equal to this one.
static Vertex operator+ (Vertex a, Vertex b)
Adds two Vertex objects together and returns the result in a new Vertex object. Addition is performed component-wise for every attribute on the Vertex.
static Vertex Add (Vertex a, Vertex b)
Adds two Vertex objects together and returns the result in a new Vertex object. Addition is performed component-wise for every attribute on the Vertex.
static Vertex operator- (Vertex a, Vertex b)
Subtracts two Vertex objects and returns the result in a new Vertex object. Subtraction is performed component-wise for every attribute.
static Vertex Subtract (Vertex a, Vertex b)
Subtracts two Vertex objects and returns the result in a new Vertex object. Subtraction is performed component-wise for every attribute on the Vertex.
static Vertex operator* (Vertex a, float value)
Multiples a Vertex object by the specified value and returns the result in a new Vertex object. Multiplication is performed component-wise for every attribute.
static Vertex Multiply (Vertex a, float value)
Multiples a Vertex object by the specified value and returns the result in a new Vertex object. Multiplication is performed component-wise for every attribute on the Vertex.
static Vertex operator/ (Vertex a, float value)
Divides a Vertex object by the specified value and returns the result in a new Vertex object. Division is performed component-wise for every attribute.
static Vertex Divide (Vertex a, float value)
Divides a Vertex object by the specified value and returns the result in a new Vertex object. Division is performed component-wise for every attribute.
static void GetArrays (IList< Vertex > vertices, out Vector3[] position, out Color[] color, out Vector2[] uv0, out Vector3[] normal, out Vector4[] tangent, out Vector2[] uv2, out List< Vector4 > uv3, out List< Vector4 > uv4)
Allocates and fills all attribute arrays. This method fills all arrays, regardless of whether or not real data populates the values. You can check which attributes a Vertex contains with HasAttribute()).
static void GetArrays (IList< Vertex > vertices, out Vector3[] position, out Color[] color, out Vector2[] uv0, out Vector3[] normal, out Vector4[] tangent, out Vector2[] uv2, out List< Vector4 > uv3, out List< Vector4 > uv4, MeshArrays attributes)
Allocates and fills the specified attribute arrays.
static void SetMesh (Mesh mesh, IList< Vertex > vertices)
Replaces mesh values with the specified vertex array. The mesh is cleared during this function, so you need to set the triangles after calling this method.
static Vertex Average (IList< Vertex > vertices, IList< int > indexes=null)
Averages all vertices to a single vertex and returns the result as a new Vertex object.
static Vertex Mix (Vertex x, Vertex y, float weight)
Linearly interpolates between two vertices using the specified weight.
Properties
Vector3 position [get, set]
Gets or sets the position in local space.
Color color [get, set]
Gets or sets the vertex color.
Vector3 normal [get, set]
Gets or sets the unit vector normal.
Vector4 tangent [get, set]
Gets or sets the vertex tangent (sometimes called binormal).
Vector2 uv0 [get, set]
Gets or sets the UV0 channel. Also called texture UVs.
Vector2 uv2 [get, set]
Gets or sets the UV2 channel.
Vector4 uv3 [get, set]
Gets or sets the UV3 channel.
Vector4 uv4 [get, set]
Gets or sets the UV4 channel.
Detailed Description
Holds information about a single vertex, and provides methods for averaging between multiple Vertex objects.
All values are optional; however, ProBuilder can use default values if necessary.
Constructor & Destructor Documentation
Vertex() [1/2]
UnityEngine.ProBuilder.Vertex.Vertex ()
Initializes a Vertex with no values.
Referenced by UnityEngine.ProBuilder.Vertex.Add(), UnityEngine.ProBuilder.Vertex.Average(), UnityEngine.ProBuilder.Vertex.Divide(), UnityEngine.ProBuilder.Vertex.GetArrays(), UnityEngine.ProBuilder.Vertex.Mix(), UnityEngine.ProBuilder.Vertex.Multiply(), and UnityEngine.ProBuilder.Vertex.Subtract().
Vertex() [2/2]
UnityEngine.ProBuilder.Vertex.Vertex (Vertex vertex)
Creates a new Vertex object as a copy of another Vertex object.
Parameters
vertex The Vertex to copy field data from.
Member Function Documentation
Add() [1/2]
static Vertex UnityEngine.ProBuilder.Vertex.Add (Vertex a, Vertex b) static
Adds two Vertex objects together and returns the result in a new Vertex object. Addition is performed component-wise for every attribute on the Vertex.
Color, normal, and tangent values are not normalized within this function. If you are expecting unit vectors, you need to normalize these attributes.
Parameters
a First Vertex object.
b Second Vertex object.
Returns
A new Vertex with the sum of a + b.
Referenced by UnityEngine.ProBuilder.Vertex.Add().
Add() [2/2]
void UnityEngine.ProBuilder.Vertex.Add (Vertex b)
Adds another Vertex object to this one using component-wise addition on each attribute.
Color, normal, and tangent values are not normalized within this function. If you are expecting unit vectors, you need to normalize these attributes.
Parameters
b The Vertex object to add.
Average()
static Vertex UnityEngine.ProBuilder.Vertex.Average (IList< Vertex > vertices, IList< int > indexes = null) static
Averages all vertices to a single vertex and returns the result as a new Vertex object.
Parameters
vertices The list of vertices to average.
indexes Specify a list of vertex points to calculate the average from. If not specified, it averages the entire set of vertices instead.
Returns
An averaged vertex value.
Divide() [1/2]
void UnityEngine.ProBuilder.Vertex.Divide (float value)
Divides this Vertex object by the specified value using component-wise division on each attribute.
Color, normal, and tangent values are not normalized within this function. If you are expecting unit vectors, you need to normalize these attributes.
Parameters
value Divisor.
Divide() [2/2]
static Vertex UnityEngine.ProBuilder.Vertex.Divide (Vertex a, float value) static
Divides a Vertex object by the specified value and returns the result in a new Vertex object. Division is performed component-wise for every attribute.
Color, normal, and tangent values are not normalized within this function. If you are expecting unit vectors, you need to normalize these attributes.
Parameters
a Vertex object to divide (dividend).
value Divisor.
Returns
A new Vertex with the quotient of a / b.
Referenced by UnityEngine.ProBuilder.Vertex.Divide(), and UnityEngine.ProBuilder.Vertex.operator/().
Equals() [1/3]
override bool UnityEngine.ProBuilder.Vertex.Equals (object obj)
Determines whether the specified generic object is equal to this Vertex.
Parameters
obj The object to compare this Vertex object to.
Returns
True if the other object is a Vertex and is equal to this.
Referenced by UnityEngine.ProBuilder.Vertex.Equals(), and UnityEngine.ProBuilder.Vertex.operator==().
Equals() [2/3]
bool UnityEngine.ProBuilder.Vertex.Equals (Vertex other)
Determines whether the specified Vertex object is equal to this Vertex by checking whether all components are within a certain distance of the other.
Parameters
other The other Vertex to compare to.
Returns
True if all values are the same (within float.Epsilon).
Equals() [3/3]
bool UnityEngine.ProBuilder.Vertex.Equals (Vertex other, MeshArrays mask)
Determines whether the specified Vertex object is equal to this Vertex by checking whether each component for a specific set of attributes is within a certain distance of the other. The MeshArrays mask determines which set of attributes to compare.
Parameters
other The other Vertex to compare to.
mask A bitmask that defines which attributes to compare.
Returns
True if all values are the same (within float.Epsilon).
GetArrays() [1/2]
static void UnityEngine.ProBuilder.Vertex.GetArrays (IList< Vertex > vertices, out Vector3[] position, out Color[] color, out Vector2[] uv0, out Vector3[] normal, out Vector4[] tangent, out Vector2[] uv2, out List< Vector4 > uv3, out List< Vector4 > uv4) static
Allocates and fills all attribute arrays. This method fills all arrays, regardless of whether or not real data populates the values. You can check which attributes a Vertex contains with HasAttribute()).
If you are using this function to rebuild a mesh, use SetMesh instead. SetMesh handles setting null arrays where appropriate.
Parameters
vertices The source vertices.
position A new array of the vertex position values.
color A new array of the vertex color values.
uv0 A new array of the vertex uv0 values.
normal A new array of the vertex normal values.
tangent A new array of the vertex tangent values.
uv2 A new array of the vertex uv2 values.
uv3 A new array of the vertex uv3 values.
uv4 A new array of the vertex uv4 values.
Referenced by UnityEngine.ProBuilder.Vertex.GetArrays(), UnityEngine.ProBuilder.Vertex.SetMesh(), and UnityEngine.ProBuilder.ProBuilderMesh.SetVertices().
GetArrays() [2/2]
static void UnityEngine.ProBuilder.Vertex.GetArrays (IList< Vertex > vertices, out Vector3[] position, out Color[] color, out Vector2[] uv0, out Vector3[] normal, out Vector4[] tangent, out Vector2[] uv2, out List< Vector4 > uv3, out List< Vector4 > uv4, MeshArrays attributes) static
Allocates and fills the specified attribute arrays.
If you are using this function to rebuild a mesh, use SetMesh instead. SetMesh handles setting null arrays where appropriate.
Parameters
vertices The source vertices.
position A new array of the vertex position values if requested by the attributes parameter, or null.
color A new array of the vertex color values if requested by the attributes parameter, or null.
uv0 A new array of the vertex uv0 values if requested by the attributes parameter, or null.
normal A new array of the vertex normal values if requested by the attributes parameter, or null.
tangent A new array of the vertex tangent values if requested by the attributes parameter, or null.
uv2 A new array of the vertex uv2 values if requested by the attributes parameter, or null.
uv3 A new array of the vertex uv3 values if requested by the attributes parameter, or null.
uv4 A new array of the vertex uv4 values if requested by the attributes parameter, or null.
attributes A bitmask of the set of MeshAttributes you want.
See also
HasArrays
GetHashCode()
override int UnityEngine.ProBuilder.Vertex.GetHashCode ()
Creates a new hashcode from this Vertex's position, UV0, and normal.
Returns
A hashcode for this object.
HasArrays()
bool UnityEngine.ProBuilder.Vertex.HasArrays (MeshArrays attribute)
Tests whether the specified vertex attribute has been set.
Parameters
attribute An array containing one or more attribute(s) to find.
Returns
True if this vertex has the specified attributes set; false if they are default values.
Mix()
static Vertex UnityEngine.ProBuilder.Vertex.Mix (Vertex x, Vertex y, float weight) static
Linearly interpolates between two vertices using the specified weight.
Parameters
x The first Vertex object.
y The second Vertex object.
weight The weight of the interpolation, where 0 is weighted fully towards the first Vertex object x, and 1 is weighted fully towards the second Vertex object y.
Returns
A new Vertex object interpolated between the two objects according to the specified weight.
Multiply() [1/2]
void UnityEngine.ProBuilder.Vertex.Multiply (float value)
Multiples this Vertex object by the specified value using component-wise multiplication on each attribute.
Color, normal, and tangent values are not normalized within this function. If you are expecting unit vectors, you need to normalize these attributes.
Parameters
value Multiplication factor.
Multiply() [2/2]
static Vertex UnityEngine.ProBuilder.Vertex.Multiply (Vertex a, float value) static
Multiples a Vertex object by the specified value and returns the result in a new Vertex object. Multiplication is performed component-wise for every attribute on the Vertex.
Color, normal, and tangent values are not normalized within this function. If you are expecting unit vectors, you need to normalize these attributes.
Parameters
a Vertex object to multiply
value Multiplication factor.
Returns
A new Vertex with the product of a * b.
Referenced by UnityEngine.ProBuilder.Vertex.Multiply().
Normalize()
void UnityEngine.ProBuilder.Vertex.Normalize ()
Normalizes all vector values in place.
operator!=()
static bool UnityEngine.ProBuilder.Vertex.operator!= (Vertex a, Vertex b) static
Determines whether the specified Vertex is not equal to this one.
Parameters
a Left operand.
b Right operand.
Returns
True if a does not equal b.
operator*()
static Vertex UnityEngine.ProBuilder.Vertex.operator* (Vertex a, float value) static
Multiples a Vertex object by the specified value and returns the result in a new Vertex object. Multiplication is performed component-wise for every attribute.
Color, normal, and tangent values are not normalized within this function. If you are expecting unit vectors, you need to normalize these attributes.
Parameters
a Vertex object to multiply
value Multiplication factor.
Returns
A new Vertex with the product of a * b.
operator+()
static Vertex UnityEngine.ProBuilder.Vertex.operator+ (Vertex a, Vertex b) static
Adds two Vertex objects together and returns the result in a new Vertex object. Addition is performed component-wise for every attribute on the Vertex.
Color, normal, and tangent values are not normalized within this function. If you are expecting unit vectors, you need to normalize these attributes.
Parameters
a Left operand.
b Right operand.
Returns
A new Vertex with the sum of a + b.
operator-()
static Vertex UnityEngine.ProBuilder.Vertex.operator- (Vertex a, Vertex b) static
Subtracts two Vertex objects and returns the result in a new Vertex object. Subtraction is performed component-wise for every attribute.
Color, normal, and tangent values are not normalized within this function. If you are expecting unit vectors, you need to normalize these attributes.
Parameters
a Left operand.
b Right operand.
Returns
A new Vertex with the difference of a - b.
operator/()
static Vertex UnityEngine.ProBuilder.Vertex.operator/ (Vertex a, float value) static
Divides a Vertex object by the specified value and returns the result in a new Vertex object. Division is performed component-wise for every attribute.
Color, normal, and tangent values are not normalized within this function. If you are expecting unit vectors, you need to normalize these attributes.
Parameters
a Vertex object to divide (dividend).
value Divisor.
Returns
A new Vertex with the quotient of a / b.
operator==()
static bool UnityEngine.ProBuilder.Vertex.operator== (Vertex a, Vertex b) static
Determines whether the specified Vertex is equal to this one.
Parameters
a Left operand.
b Right operand.
Returns
True if a equals b.
SetMesh()
static void UnityEngine.ProBuilder.Vertex.SetMesh (Mesh mesh, IList< Vertex > vertices) static
Replaces mesh values with the specified vertex array. The mesh is cleared during this function, so you need to set the triangles after calling this method.
Parameters
mesh The target mesh.
vertices The vertices to replace the mesh attributes with.
Subtract() [1/2]
static Vertex UnityEngine.ProBuilder.Vertex.Subtract (Vertex a, Vertex b) static
Subtracts two Vertex objects and returns the result in a new Vertex object. Subtraction is performed component-wise for every attribute on the Vertex.
Color, normal, and tangent values are not normalized within this function. If you are expecting unit vectors, you need to normalize these attributes.
Parameters
a First Vertex object.
b Second Vertex object.
Returns
A new Vertex with the difference of a - b.
Subtract() [2/2]
void UnityEngine.ProBuilder.Vertex.Subtract (Vertex b)
Subtracts another Vertex object from this one using component-wise subtraction on each attribute.
Color, normal, and tangent values are not normalized within this function. If you are expecting unit vectors, you need to normalize these attributes.
Parameters
b The Vertex object to subtract.
ToString()
string UnityEngine.ProBuilder.Vertex.ToString (string args = null)
Returns a multi-line string listing every populated attribute.
Parameters
args An optional string argument to pass to the component ToString calls.
Returns
A string with the values of all populated attributes.
Property Documentation
color
Color UnityEngine.ProBuilder.Vertex.color get set
Gets or sets the vertex color.
Returns
The color applied to this vertex.
See also
ProBuilderMesh.colors, UnityEngine.Color
Referenced by UnityEngine.ProBuilder.Vertex.GetArrays(), UnityEngine.ProBuilder.Vertex.GetArrays(), and UnityEngine.ProBuilder.ProBuilderMesh.GetVertices().
normal
Vector3 UnityEngine.ProBuilder.Vertex.normal get set
Gets or sets the unit vector normal.
Returns
The unit vector normal.
See also
ProBuilderMesh.GetNormals
Referenced by UnityEngine.ProBuilder.Vertex.GetArrays(), UnityEngine.ProBuilder.Vertex.GetArrays(), UnityEngine.ProBuilder.Vertex.GetHashCode(), and UnityEngine.ProBuilder.ProBuilderMesh.GetVertices().
position
Vector3 UnityEngine.ProBuilder.Vertex.position get set
Gets or sets the position in local space.
Returns
The position in local space.
See also
ProBuilderMesh.positions
Referenced by UnityEngine.ProBuilder.Vertex.GetArrays(), UnityEngine.ProBuilder.Vertex.GetArrays(), UnityEngine.ProBuilder.Vertex.GetHashCode(), and UnityEngine.ProBuilder.ProBuilderMesh.GetVertices().
tangent
Vector4 UnityEngine.ProBuilder.Vertex.tangent get set
Gets or sets the vertex tangent (sometimes called binormal).
Returns
The vertex tangent.
See also
ProBuilderMesh.tangents
Referenced by UnityEngine.ProBuilder.Vertex.GetArrays(), UnityEngine.ProBuilder.Vertex.GetArrays(), and UnityEngine.ProBuilder.ProBuilderMesh.GetVertices().
uv0
Vector2 UnityEngine.ProBuilder.Vertex.uv0 get set
Gets or sets the UV0 channel. Also called texture UVs.
Returns
The UV0 channel.
See also
ProBuilderMesh.textures, ProBuilderMesh.GetUVs
Referenced by UnityEngine.ProBuilder.Vertex.GetArrays(), UnityEngine.ProBuilder.Vertex.GetArrays(), UnityEngine.ProBuilder.Vertex.GetHashCode(), and UnityEngine.ProBuilder.ProBuilderMesh.GetVertices().
uv2
Vector2 UnityEngine.ProBuilder.Vertex.uv2 get set
Gets or sets the UV2 channel.
Returns
The UV2 channel.
See also
ProBuilderMesh.GetUVs
Referenced by UnityEngine.ProBuilder.Vertex.GetArrays(), UnityEngine.ProBuilder.Vertex.GetArrays(), and UnityEngine.ProBuilder.ProBuilderMesh.GetVertices().
uv3
Vector4 UnityEngine.ProBuilder.Vertex.uv3 get set
Gets or sets the UV3 channel.
Returns
The UV3 channel.
See also
ProBuilderMesh.GetUVs
Referenced by UnityEngine.ProBuilder.Vertex.GetArrays(), UnityEngine.ProBuilder.Vertex.GetArrays(), and UnityEngine.ProBuilder.ProBuilderMesh.GetVertices().
uv4
Vector4 UnityEngine.ProBuilder.Vertex.uv4 get set
Gets or sets the UV4 channel.
Returns
The UV4 channel.
See also
ProBuilderMesh.GetUVs
Referenced by UnityEngine.ProBuilder.Vertex.GetArrays(), UnityEngine.ProBuilder.Vertex.GetArrays(), and UnityEngine.ProBuilder.ProBuilderMesh.GetVertices().
The documentation for this class was generated from the following file:
C:/Users/Lykos/Desktop/Projects/Capstone/VRGames/Library/PackageCache/com.unity.probuilder@5.0.6/Runtime/Core/Vertex.cs