VRGames: UnityEngine.ProBuilder.Face Class Reference
UnityEngine.ProBuilder.Face Class Reference sealed
A face is composed of a set of triangles, and a material.
Public Member Functions
void SetIndexes (IEnumerable< int > indices)
Sets the triangles that compose this face.
Face ()
Creates a Face with an empty triangles array.
Face (IEnumerable< int > indices)
Creates a face with default values and the specified set of triangles.
Face (Face other)
Creates a new Face as a copy of another face.
void CopyFrom (Face other)
Copies properties and triangles from the specified face to this face.
bool Contains (int a, int b, int c)
Tests whether a triangle matches one of the triangles of this face.
bool IsQuad ()
Returns whether this face can be converted to a quad (a polygon with four sides).
int[] ToQuad ()
Converts a two-triangle face to a quad representation.
override string ToString ()
Returns a string representation of the face.
void ShiftIndexes (int offset)
Adds an offset to each value in the indices array.
void ShiftIndexesToZero ()
Finds the smallest value in the indices array, then offsets by subtracting that value from each index.
void Reverse ()
Reverses the order of the triangle array. This has the effect of reversing the direction that this face renders.
Properties
bool manualUV [get, set]
Gets or sets whether to map this face's UV coordinates manually or automatically. See Mapping Textures with UVs for an overview of the differences.
int textureGroup [get, set]
Gets or sets which texture group this face belongs to. ProBuilder uses texture groups when projecting Auto UVs. See Continuous tiling.
ReadOnlyCollection< int > indexes [get]
Gets the triangle indices that compose this face.
ReadOnlyCollection< int > distinctIndexes [get]
Gets a collection of the vertex indexes that the indexes array references, made distinct.
ReadOnlyCollection< Edge > edges [get]
Gets the perimeter edges that compose this face.
int smoothingGroup [get, set]
Gets or sets which smoothing group this face belongs to, if any. This is used to calculate vertex normals.
Material material [get, set]
Gets the material that this face uses.
int submeshIndex [get, set]
Gets or sets the index of the submesh that this face belongs to.
AutoUnwrapSettings uv [get, set]
Gets or sets a reference to the Auto UV mapping parameters.
int this[int i] [get]
Gets the index for the specified triangle in this face's array of triangle indices.
Detailed Description
A face is composed of a set of triangles, and a material.
Triangle indices may point to the same vertex index as long as the vertices are unique to the face. That is, every vertex that a face references should only be used by that face's indices. To associate vertices that share common attributes (usually position), use the sharedIndexes property.
ProBuilder automatically manages condensing common vertices in the EditorMeshUtility.Optimize function.
Constructor & Destructor Documentation
Face() [1/3]
UnityEngine.ProBuilder.Face.Face ()
Creates a Face with an empty triangles array.
Face() [2/3]
UnityEngine.ProBuilder.Face.Face (IEnumerable< int > indices)
Creates a face with default values and the specified set of triangles.
Parameters
indices The new triangles array.
Face() [3/3]
UnityEngine.ProBuilder.Face.Face (Face other)
Creates a new Face as a copy of another face.
Parameters
other The Face from which to copy properties and triangles.
Member Function Documentation
Contains()
bool UnityEngine.ProBuilder.Face.Contains (int a, int b, int c)
Tests whether a triangle matches one of the triangles of this face.
Parameters
a First index in the triangle
b Second index in the triangle
c Third index in the triangle
Returns
True if {a,b,c} is found in this face's list of triangles; otherwise false.
CopyFrom()
void UnityEngine.ProBuilder.Face.CopyFrom (Face other)
Copies properties and triangles from the specified face to this face.
Parameters
other The Face from which to copy properties and triangles.
Referenced by UnityEngine.ProBuilder.Face.Face().
IsQuad()
bool UnityEngine.ProBuilder.Face.IsQuad ()
Returns whether this face can be converted to a quad (a polygon with four sides).
Returns
True if this face is divisible by 4; false otherwise.
Referenced by UnityEngine.ProBuilder.Face.ToQuad().
Reverse()
void UnityEngine.ProBuilder.Face.Reverse ()
Reverses the order of the triangle array. This has the effect of reversing the direction that this face renders.
Referenced by UnityEditor.ProBuilder.Actions.FlipFaceNormals.PerformActionImplementation(), UnityEditor.ProBuilder.Actions.FreezeTransform.PerformActionImplementation(), UnityEngine.ProBuilder.Shapes.Arch.RebuildMesh(), UnityEngine.ProBuilder.Shapes.Cone.RebuildMesh(), UnityEngine.ProBuilder.Shapes.Door.RebuildMesh(), and UnityEngine.ProBuilder.Shapes.Prism.RebuildMesh().
SetIndexes()
void UnityEngine.ProBuilder.Face.SetIndexes (IEnumerable< int > indices)
Sets the triangles that compose this face.
Parameters
indices The new triangle array.
Referenced by UnityEngine.ProBuilder.Face.Face(), and ProBuilder.ExampleActions.CreateShadowObject.PerformActionImplementation().
ShiftIndexes()
void UnityEngine.ProBuilder.Face.ShiftIndexes (int offset)
Adds an offset to each value in the indices array.
Parameters
offset The value to add to each index.
ShiftIndexesToZero()
void UnityEngine.ProBuilder.Face.ShiftIndexesToZero ()
Finds the smallest value in the indices array, then offsets by subtracting that value from each index.
// sets the indexes array to `{0, 1, 2}`.
new Face(3,4,5).ShiftIndexesToZero();
ToQuad()
int[] UnityEngine.ProBuilder.Face.ToQuad ()
Converts a two-triangle face to a quad representation.
Returns
A quad (an array of four indices); or null if indices are not able to be represented as a quad.
ToString()
override string UnityEngine.ProBuilder.Face.ToString ()
Returns a string representation of the face.
Returns
String formatted as [a, b, c], ....
Referenced by UnityEngine.ProBuilder.WingedEdge.ToString().
Property Documentation
distinctIndexes
ReadOnlyCollection<int> UnityEngine.ProBuilder.Face.distinctIndexes get
Gets a collection of the vertex indexes that the indexes array references, made distinct.
Returns
A unique collection of vertices.
edges
ReadOnlyCollection<Edge> UnityEngine.ProBuilder.Face.edges get
Gets the perimeter edges that compose this face.
Returns
The collection of edges on this face.
indexes
ReadOnlyCollection<int> UnityEngine.ProBuilder.Face.indexes get
Gets the triangle indices that compose this face.
Returns
The array of indices representing this face's triangles.
Referenced by ProBuilder.ExampleActions.CreateShadowObject.PerformActionImplementation(), and UnityEngine.ProBuilder.Shapes.Sphere.RebuildMesh().
manualUV
bool UnityEngine.ProBuilder.Face.manualUV get set
Gets or sets whether to map this face's UV coordinates manually or automatically. See Mapping Textures with UVs for an overview of the differences.
Returns
True to set UV coordinates manually; false to use AutoUnwrapSettings.
Referenced by UnityEngine.ProBuilder.Face.CopyFrom(), and UnityEngine.ProBuilder.Shapes.Sphere.RebuildMesh().
material
Material UnityEngine.ProBuilder.Face.material get set
Gets the material that this face uses.
Referenced by UnityEngine.ProBuilder.Face.CopyFrom().
smoothingGroup
int UnityEngine.ProBuilder.Face.smoothingGroup get set
Gets or sets which smoothing group this face belongs to, if any. This is used to calculate vertex normals.
Returns
The ID of this smoothing group as an integer.
Referenced by UnityEngine.ProBuilder.Face.CopyFrom(), UnityEngine.ProBuilder.Shapes.Arch.RebuildMesh(), UnityEngine.ProBuilder.Shapes.Pipe.RebuildMesh(), and UnityEngine.ProBuilder.Shapes.Sphere.RebuildMesh().
submeshIndex
int UnityEngine.ProBuilder.Face.submeshIndex get set
Gets or sets the index of the submesh that this face belongs to.
Returns
The ID of the submesh as an integer.
textureGroup
int UnityEngine.ProBuilder.Face.textureGroup get set
Gets or sets which texture group this face belongs to. ProBuilder uses texture groups when projecting Auto UVs. See Continuous tiling.
Returns
ID of the texture group for this face.
Referenced by UnityEngine.ProBuilder.Face.CopyFrom(), UnityEngine.ProBuilder.Face.Face(), and UnityEngine.ProBuilder.Shapes.Sphere.RebuildMesh().
this[int i]
int UnityEngine.ProBuilder.Face.this[int i] get
Gets the index for the specified triangle in this face's array of triangle indices.
Parameters
i The triangle to access
Returns
The index of the specified triangle.
uv
AutoUnwrapSettings UnityEngine.ProBuilder.Face.uv get set
Gets or sets a reference to the Auto UV mapping parameters.
Returns
The ID of this submesh as an integer.
Referenced by UnityEngine.ProBuilder.Face.CopyFrom().
The documentation for this class was generated from the following file:
C:/Users/Lykos/Desktop/Projects/Capstone/VRGames/Library/PackageCache/com.unity.probuilder@5.0.6/Runtime/Core/Face.cs