VRCapstoneGames: UnityEngine.XR.Interaction.Toolkit.XRRayInteractor Class Reference
UnityEngine.XR.Interaction.Toolkit.XRRayInteractor Class Reference
Interactor used for interacting with interactables at a distance. This is handled via ray casts that update the current set of valid targets for this interactor.
Classes
class RaycastHitComparer
Compares ray cast hits by distance, to sort in ascending order.
Public Types
enum LineType { StraightLine , ProjectileCurve , BezierCurve }
Sets which trajectory path Unity uses for the cast when detecting collisions.
enum HitDetectionType { Raycast , SphereCast }
Sets which shape of physics cast to use for the cast when detecting collisions.
Public Types inherited from UnityEngine.XR.Interaction.Toolkit.XRBaseControllerInteractor
enum InputTriggerType { State , StateChange , Toggle , Sticky }
This defines the type of input that triggers an interaction.
Public Member Functions
bool GetLinePoints (ref Vector3[] linePoints, out int numPoints)
Gets the polygonal chain represented by a list of endpoints which form line segments to approximate the curve. Positions are in world space coordinates.
Parameters
linePoints When this method returns, contains the sample points if successful.
numPoints When this method returns, contains the number of sample points if successful.
Returns
Returns true if the sample points form a valid line, such as by having at least two points. Otherwise, returns false.
bool TryGetHitInfo (out Vector3 position, out Vector3 normal, out int positionInLine, out bool isValidTarget)
Gets the current ray cast hit information, if a hit occurs. It returns the world position and the normal vector of the hit point, and its position in linePoints.
Parameters
position When this method returns, contains the world position of the ray impact point if a hit occurred.
normal When this method returns, contains the world normal of the surface the ray hit if a hit occurred.
positionInLine When this method returns, contains the index of the sample endpoint within the list of points returned by GetLinePoints where a hit occurred. Otherwise, a value of 0 if no hit occurred.
isValidTarget When this method returns, contains whether both a hit occurred and it is a valid target for interaction.
Returns
Returns true if a hit occurs, implying the ray cast hit information is valid. Otherwise, returns false.
virtual void UpdateUIModel (ref TrackedDeviceModel model)
Updates the current UI Model to match the state of the Interactor.
Parameters
model The returned model that will match this Interactor.
bool TryGetUIModel (out TrackedDeviceModel model)
Attempts to retrieve the current UI Model.
Parameters
model The returned model that reflects the UI state of this Interactor.
Returns
Returns true if the model was able to retrieved. Otherwise, returns false.
bool TryGetCurrent3DRaycastHit (out RaycastHit raycastHit)
bool TryGetCurrent3DRaycastHit (out RaycastHit raycastHit, out int raycastEndpointIndex)
Gets the first 3D ray cast hit, if any ray cast hits are available.
bool TryGetCurrentUIRaycastResult (out RaycastResult raycastResult)
bool TryGetCurrentUIRaycastResult (out RaycastResult raycastResult, out int raycastEndpointIndex)
Gets the first UI ray cast result, if any ray cast results are available.
bool TryGetCurrentRaycast (out RaycastHit? raycastHit, out int raycastHitIndex, out RaycastResult? uiRaycastHit, out int uiRaycastHitIndex, out bool isUIHitClosest)
Gets the first 3D and UI ray cast hits, if any ray cast hits are available.
override void PreprocessInteractor (XRInteractionUpdateOrder.UpdatePhase updatePhase)
The XRInteractionManager calls this method to update the Interactor before interaction events occur. Interactors should use this method to do tasks like determine their valid targets.
Parameters
updatePhase The update phase this is called during.
Please see the XRInteractionManager and XRInteractionUpdateOrder.UpdatePhase documentation for more details on update order.
override void ProcessInteractor (XRInteractionUpdateOrder.UpdatePhase updatePhase)
The XRInteractionManager calls this method to update the Interactor after interaction events occur.
Parameters
updatePhase The update phase this is called during.
Please see the XRInteractionManager and XRInteractionUpdateOrder.UpdatePhase documentation for more details on update order.
override void GetValidTargets (List< IXRInteractable > targets)
Retrieve the list of Interactables that this Interactor could possibly interact with this frame. This list is sorted by priority (with highest priority first).
Parameters
targets The results list to populate with Interactables that are valid for selection or hover.
When implementing this method, Unity expects you to clear targets before adding to it.
override bool CanHover (IXRHoverInteractable interactable)
Determines if the Interactable is valid for hover this frame.
Parameters
interactable Interactable to check.
Returns
Returns true if the Interactable can be hovered over this frame.
See also
IXRHoverInteractable.IsHoverableBy
override bool CanSelect (IXRSelectInteractable interactable)
Determines if the Interactable is valid for selection this frame.
Parameters
interactable Interactable to check.
Returns
Returns true if the Interactable can be selected this frame.
See also
IXRSelectInteractable.IsSelectableBy
bool GetLinePoints (ref Vector3[] linePoints, ref int numPoints, int _=default)
(Obsolete) Use ILineRenderable.GetLinePoints instead.
bool TryGetHitInfo (ref Vector3 position, ref Vector3 normal, ref int positionInLine, ref bool isValidTarget, int _=default)
(Obsolete) Use ILineRenderable.TryGetHitInfo instead.
bool GetCurrentRaycastHit (out RaycastHit raycastHit)
override bool CanHover (XRBaseInteractable interactable)
override bool CanSelect (XRBaseInteractable interactable)
Public Member Functions inherited from UnityEngine.XR.Interaction.Toolkit.XRBaseControllerInteractor
virtual void GetActivateTargets (List< IXRActivateInteractable > targets)
Retrieve the list of Interactables that this Interactor could possibly activate or deactivate this frame.
Parameters
targets The results list to populate with Interactables that are valid for activate or deactivate.
When implementing this method, Unity expects you to clear targets before adding to it.
bool SendHapticImpulse (float amplitude, float duration)
Play a haptic impulse on the controller if one is available.
Public Member Functions inherited from UnityEngine.XR.Interaction.Toolkit.XRBaseInteractor
virtual Transform GetAttachTransform (IXRInteractable interactable)
Gets the Transform that is used as the attachment point for a given Interactable.
Parameters
interactable The specific Interactable as context to get the attachment point for.
Returns
Returns the attachment point Transform.
See also
IXRInteractable.GetAttachTransform
This should typically return the Transform of a child GameObject or the transform itself.
Pose GetAttachPoseOnSelect (IXRSelectInteractable interactable)
Gets the world position and rotation of the Attach Transform captured during the moment of selection.
Parameters
interactable The specific Interactable as context to get the attachment point for.
Returns
Returns the world pose of the attachment point during the moment of selection, and otherwise the identity Pose if it was not selected during the current selection stack.
See also
GetLocalAttachPoseOnSelect, IXRInteractor.GetAttachTransform, IXRSelectInteractable.GetAttachPoseOnSelect
Pose GetLocalAttachPoseOnSelect (IXRSelectInteractable interactable)
Gets the local position and rotation of the Attach Transform captured during the moment of selection.
Parameters
interactable The specific Interactable as context to get the attachment point for.
Returns
Returns the local pose of the attachment point during the moment of selection, and otherwise the identity Pose if it was not selected during the current selection stack.
See also
GetAttachPoseOnSelect, IXRInteractor.GetAttachTransform, IXRSelectInteractable.GetLocalAttachPoseOnSelect
bool IsHovering (IXRHoverInteractable interactable)
Determines whether this Interactor is currently hovering the Interactable.
Parameters
interactable Interactable to check.
Returns
Returns true if this Interactor is currently hovering the Interactable. Otherwise, returns .
In other words, returns whether interactablesHovered contains interactable .
bool IsSelecting (IXRSelectInteractable interactable)
Determines whether this Interactor is currently selecting the Interactable.
Parameters
interactable Interactable to check.
Returns
Returns true if this Interactor is currently selecting the Interactable. Otherwise, returns .
In other words, returns whether interactablesSelected contains interactable .
virtual void StartManualInteraction (IXRSelectInteractable interactable)
Manually initiate selection of an Interactable.
virtual void EndManualInteraction ()
Ends the manually initiated selection of an Interactable.
void GetHoverTargets (List< XRBaseInteractable > targets)
Retrieves a copy of the list of target Interactables that are currently being hovered over.
virtual void GetValidTargets (List< XRBaseInteractable > targets)
Retrieve the list of Interactables that this Interactor could possibly interact with this frame. This list is sorted by priority (with highest priority first).
virtual void StartManualInteraction (XRBaseInteractable interactable)
Manually initiate selection of an Interactable.
Protected Member Functions
void OnValidate ()
See MonoBehaviour.
override void Awake ()
See MonoBehaviour.
override void OnEnable ()
See MonoBehaviour.
override void OnDisable ()
See MonoBehaviour.
virtual void OnDrawGizmosSelected ()
See MonoBehaviour.
virtual void RotateAnchor (Transform anchor, float directionAmount)
Rotates the attach anchor for this interactor. This can be useful to rotate a held object.
virtual void TranslateAnchor (Transform rayOrigin, Transform anchor, float directionAmount)
Translates the attach anchor for this interactor. This can be useful to move a held object closer or further away from the interactor.
override void OnSelectEntering (SelectEnterEventArgs args)
The XRInteractionManager calls this method right before the Interactor first initiates selection of an Interactable in a first pass.
Parameters
args Event data containing the Interactable that is being selected.
args is only valid during this method call, do not hold a reference to it.
override void OnSelectExiting (SelectExitEventArgs args)
The XRInteractionManager calls this method right before the Interactor ends selection of an Interactable in a first pass.
Parameters
args Event data containing the Interactable that is no longer selected.
args is only valid during this method call, do not hold a reference to it.
Protected Member Functions inherited from UnityEngine.XR.Interaction.Toolkit.XRBaseControllerInteractor
override void OnHoverEntering (HoverEnterEventArgs args)
The XRInteractionManager calls this method right before the Interactor first initiates hovering over an Interactable in a first pass.
Parameters
args Event data containing the Interactable that is being hovered over.
args is only valid during this method call, do not hold a reference to it.
override void OnHoverExiting (HoverExitEventArgs args)
The XRInteractionManager calls this method right before the Interactor ends hovering over an Interactable in a first pass.
Parameters
args Event data containing the Interactable that is no longer hovered over.
args is only valid during this method call, do not hold a reference to it.
virtual void PlayAudio (AudioClip audioClip)
Play an AudioClip.
Protected Member Functions inherited from UnityEngine.XR.Interaction.Toolkit.XRBaseInteractor
virtual void Reset ()
See MonoBehaviour.
virtual void Start ()
See MonoBehaviour.
virtual void OnDestroy ()
See MonoBehaviour.
bool IsHovering (IXRInteractable interactable)
Determines whether this Interactor is currently hovering the Interactable.
bool IsSelecting (IXRInteractable interactable)
Determines whether this Interactor is currently selecting the Interactable.
void CaptureAttachPose (IXRSelectInteractable interactable)
Capture the current Attach Transform pose. This method is automatically called by Unity to capture the pose during the moment of selection.
virtual void OnRegistered (InteractorRegisteredEventArgs args)
The XRInteractionManager calls this method when this Interactor is registered with it.
virtual void OnUnregistered (InteractorUnregisteredEventArgs args)
The XRInteractionManager calls this method when this Interactor is unregistered from it.
virtual void OnHoverEntered (HoverEnterEventArgs args)
The XRInteractionManager calls this method when the Interactor first initiates hovering over an Interactable in a second pass.
virtual void OnHoverExited (HoverExitEventArgs args)
The XRInteractionManager calls this method when the Interactor ends hovering over an Interactable in a second pass.
virtual void OnSelectEntered (SelectEnterEventArgs args)
The XRInteractionManager calls this method when the Interactor first initiates selection of an Interactable in a second pass.
virtual void OnSelectExited (SelectExitEventArgs args)
The XRInteractionManager calls this method when the Interactor ends selection of an Interactable in a second pass.
virtual void OnHoverEntering (XRBaseInteractable interactable)
(Deprecated) The XRInteractionManager calls this method right before the Interactor first initiates hovering over an Interactable in a first pass.
virtual void OnHoverEntered (XRBaseInteractable interactable)
(Deprecated) The XRInteractionManager calls this method when the Interactor first initiates hovering over an Interactable in a second pass.
virtual void OnHoverExiting (XRBaseInteractable interactable)
(Deprecated) The XRInteractionManager calls this method right before the Interactor ends hovering over an Interactable in a first pass.
virtual void OnHoverExited (XRBaseInteractable interactable)
(Deprecated) The XRInteractionManager calls this method when the Interactor ends hovering over an Interactable in a second pass.
virtual void OnSelectEntering (XRBaseInteractable interactable)
(Deprecated) The XRInteractionManager calls this method right before the Interactor first initiates selection of an Interactable in a first pass.
virtual void OnSelectEntered (XRBaseInteractable interactable)
(Deprecated) The XRInteractionManager calls this method when the Interactor first initiates selection of an Interactable in a second pass.
virtual void OnSelectExiting (XRBaseInteractable interactable)
(Deprecated) The XRInteractionManager calls this method right before the Interactor ends selection of an Interactable in a first pass.
virtual void OnSelectExited (XRBaseInteractable interactable)
(Deprecated) The XRInteractionManager calls this method when the Interactor ends selection of an Interactable in a second pass.
Properties
LineType lineType [get, set]
Gets or sets the type of ray cast.
bool blendVisualLinePoints [get, set]
Blend the line sample points Unity uses for ray casting with the current pose of the controller. Use this to make the line visual stay connected with the controller instead of lagging behind.
float maxRaycastDistance [get, set]
Gets or sets the max distance of ray cast when the line type is a straight line. Increasing this value will make the line reach further.
Transform rayOriginTransform [get, set]
The starting position and direction of any ray casts.
Transform referenceFrame [get, set]
The reference frame of the curve to define the ground plane and up. If not set at startup it will try to find the XROrigin.Origin GameObject, and if that does not exist it will use global up and origin by default.
float velocity [get, set]
Initial velocity of the projectile. Increasing this value will make the curve reach further.
float acceleration [get, set]
Gravity of the projectile in the reference frame.
float additionalGroundHeight [get, set]
Additional height below ground level that the projectile will continue to. Increasing this value will make the end point drop lower in height.
float additionalFlightTime [get, set]
Additional flight time after the projectile lands at the adjusted ground level. Increasing this value will make the end point drop lower in height.
float endPointDistance [get, set]
Increase this value distance to make the end of the curve further from the start point.
float endPointHeight [get, set]
Decrease this value to make the end of the curve drop lower relative to the start point.
float controlPointDistance [get, set]
Increase this value to make the peak of the curve further from the start point.
float controlPointHeight [get, set]
Increase this value to make the peak of the curve higher relative to the start point.
int sampleFrequency [get, set]
The number of sample points Unity uses to approximate curved paths. Larger values produce a better quality approximate at the cost of reduced performance due to the number of ray casts.
HitDetectionType hitDetectionType [get, set]
Gets or sets which type of hit detection to use for the ray cast.
float sphereCastRadius [get, set]
Gets or sets radius used for sphere casting. Will use regular ray casting if set to 0 or less.
LayerMask raycastMask [get, set]
Gets or sets layer mask used for limiting ray cast targets.
QueryTriggerInteraction raycastTriggerInteraction [get, set]
Gets or sets type of interaction with trigger volumes via ray cast.
bool hitClosestOnly [get, set]
Whether Unity considers only the closest Interactable as a valid target for interaction.
bool hoverToSelect [get, set]
Whether this Interactor will automatically select an Interactable after hovering over it for a period of time.
float hoverTimeToSelect [get, set]
Number of seconds for which this Interactor must hover over an Interactable to select it if Hover To Select is enabled.
bool enableUIInteraction [get, set]
Gets or sets whether this Interactor is able to affect UI.
bool allowAnchorControl [get, set]
Allows the user to move the attach anchor point using the joystick.
bool useForceGrab [get, set]
Force grab moves the object to your hand rather than interacting with it at a distance.
float rotateSpeed [get, set]
Speed that the anchor is rotated.
float translateSpeed [get, set]
Speed that the anchor is translated.
Transform anchorRotateReferenceFrame [get, set]
The optional reference frame to define the up axis when rotating the attach anchor point. When not set, rotates about the local up axis of the attach transform.
float angle [get]
The launch angle of the Projectile Curve. More specifically, this is the signed angle in degrees between the original attach forward direction and the plane of the reference frame, with positive angles when pointing upward.
override bool isSelectActive [get]
(Read Only) Indicates whether this Interactor is in a state where it could select.
float Velocity [get, set]
(Deprecated) Initial velocity of the projectile. Increasing this value will make the curve reach further.
float Acceleration [get, set]
(Deprecated) Gravity of the projectile in the reference frame.
float AdditionalFlightTime [get, set]
float Angle [get]
Transform originalAttachTransform [get, set]
The Transform that upon entering selection (when this Interactor first initiates selection of an Interactable), this Interactor will copy the pose of the attach Transform values into.
Properties inherited from UnityEngine.XR.Interaction.Toolkit.XRBaseControllerInteractor
InputTriggerType selectActionTrigger [get, set]
Choose how Unity interprets the select input action from the controller. Controls between different input styles for determining if this Interactor can select, such as whether the button is currently pressed or just toggles the active state.
bool hideControllerOnSelect [get, set]
Controls whether this Interactor should hide the controller model on selection.
bool allowHoveredActivate [get, set]
Controls whether to send activate and deactivate events to interactables that this interactor is hovered over but not selected when there is no current selection. By default, the interactor will only send activate and deactivate events to interactables that it's selected.
bool playAudioClipOnSelectEntered [get, set]
Controls whether Unity plays an AudioClip on Select Entered.
AudioClip audioClipForOnSelectEntered [get, set]
The AudioClip Unity plays on Select Entered.
bool playAudioClipOnSelectExited [get, set]
Controls whether Unity plays an AudioClip on Select Exited.
AudioClip audioClipForOnSelectExited [get, set]
The AudioClip Unity plays on Select Exited.
bool playAudioClipOnSelectCanceled [get, set]
Controls whether Unity plays an AudioClip on Select Canceled.
AudioClip audioClipForOnSelectCanceled [get, set]
The AudioClip Unity plays on Select Canceled.
bool playAudioClipOnHoverEntered [get, set]
Controls whether Unity plays an AudioClip on Hover Entered.
AudioClip audioClipForOnHoverEntered [get, set]
The AudioClip Unity plays on Hover Entered.
bool playAudioClipOnHoverExited [get, set]
Controls whether Unity plays an AudioClip on Hover Exited.
AudioClip audioClipForOnHoverExited [get, set]
The AudioClip Unity plays on Hover Exited.
bool playAudioClipOnHoverCanceled [get, set]
Controls whether Unity plays an AudioClip on Hover Canceled.
AudioClip audioClipForOnHoverCanceled [get, set]
The AudioClip Unity plays on Hover Canceled.
bool playHapticsOnSelectEntered [get, set]
Controls whether Unity plays haptics on Select Entered.
float hapticSelectEnterIntensity [get, set]
The Haptics intensity Unity plays on Select Entered.
float hapticSelectEnterDuration [get, set]
The Haptics duration (in seconds) Unity plays on Select Entered.
bool playHapticsOnSelectExited [get, set]
Controls whether Unity plays haptics on Select Exited.
float hapticSelectExitIntensity [get, set]
The Haptics intensity Unity plays on Select Exited.
float hapticSelectExitDuration [get, set]
The Haptics duration (in seconds) Unity plays on Select Exited.
bool playHapticsOnSelectCanceled [get, set]
Controls whether Unity plays haptics on Select Canceled.
float hapticSelectCancelIntensity [get, set]
The Haptics intensity Unity plays on Select Canceled.
float hapticSelectCancelDuration [get, set]
The Haptics duration (in seconds) Unity plays on Select Canceled.
bool playHapticsOnHoverEntered [get, set]
Controls whether Unity plays haptics on Hover Entered.
float hapticHoverEnterIntensity [get, set]
The Haptics intensity Unity plays on Hover Entered.
float hapticHoverEnterDuration [get, set]
The Haptics duration (in seconds) Unity plays on Hover Entered.
bool playHapticsOnHoverExited [get, set]
Controls whether Unity plays haptics on Hover Exited.
float hapticHoverExitIntensity [get, set]
The Haptics intensity Unity plays on Hover Exited.
float hapticHoverExitDuration [get, set]
The Haptics duration (in seconds) Unity plays on Hover Exited.
bool playHapticsOnHoverCanceled [get, set]
Controls whether Unity plays haptics on Hover Canceled.
float hapticHoverCancelIntensity [get, set]
The Haptics intensity Unity plays on Hover Canceled.
float hapticHoverCancelDuration [get, set]
The Haptics duration (in seconds) Unity plays on Hover Canceled.
bool allowActivate [get, set]
Defines whether this interactor allows sending activate and deactivate events.
XRBaseController xrController [get, set]
The controller instance that is queried for input.
override bool isSelectActive [get]
(Read Only) Indicates whether this Interactor is in a state where it could select.
bool isUISelectActive [get]
(Read Only) Whether or not Unity considers the UI Press controller input pressed.
virtual bool shouldActivate [get]
(Read Only) Indicates whether this interactor is in a state where it should send the activate event this frame.
virtual bool shouldDeactivate [get]
(Read Only) Indicates whether this interactor is in a state where it should send the deactivate event this frame.
bool playAudioClipOnSelectEnter [get]
(Deprecated) Controls whether Unity plays an AudioClip on Select Entered.
AudioClip audioClipForOnSelectEnter [get]
(Deprecated) The AudioClip Unity plays on Select Entered.
AudioClip AudioClipForOnSelectEnter [get, set]
(Deprecated) The AudioClip Unity plays on Select Entered.
bool playAudioClipOnSelectExit [get]
(Deprecated) Controls whether Unity plays an AudioClip on Select Exited.
AudioClip audioClipForOnSelectExit [get]
(Deprecated) The AudioClip Unity plays on Select Exited.
AudioClip AudioClipForOnSelectExit [get, set]
(Deprecated) The AudioClip Unity plays on Select Exited.
bool playAudioClipOnHoverEnter [get]
(Deprecated) Controls whether Unity plays an AudioClip on Hover Entered.
AudioClip audioClipForOnHoverEnter [get]
(Deprecated) The AudioClip Unity plays on Hover Entered.
AudioClip AudioClipForOnHoverEnter [get, set]
(Deprecated) The AudioClip Unity plays on Hover Entered.
bool playAudioClipOnHoverExit [get]
(Deprecated) Controls whether Unity plays an AudioClip on Hover Exited.
AudioClip audioClipForOnHoverExit [get]
(Deprecated) The AudioClip Unity plays on Hover Exited.
AudioClip AudioClipForOnHoverExit [get, set]
(Deprecated) The AudioClip Unity plays on Hover Exited.
bool playHapticsOnSelectEnter [get]
(Deprecated) Controls whether Unity plays haptics on Select Entered.
bool playHapticsOnSelectExit [get]
(Deprecated) Controls whether Unity plays haptics on Select Exited.
bool playHapticsOnHoverEnter [get]
(Deprecated) Controls whether Unity plays haptics on Hover Entered.
virtual List< XRBaseInteractable > validTargets = new List<XRBaseInteractable>() [get]
(Deprecated) (Read Only) A list of Interactables that this Interactor could possibly interact with this frame.
Properties inherited from UnityEngine.XR.Interaction.Toolkit.XRBaseInteractor
XRInteractionManager interactionManager [get, set]
The XRInteractionManager that this Interactor will communicate with (will find one if null).
InteractionLayerMask interactionLayers [get, set]
Allows interaction with Interactables whose Interaction Layer Mask overlaps with any Layer in this Interaction Layer Mask.
Transform attachTransform [get, set]
The Transform that is used as the attach point for Interactables.
bool keepSelectedTargetValid [get, set]
Whether to keep selecting an Interactable after initially selecting it even when it is no longer a valid target.Return true to make the XRInteractionManager retain the selection even if the Interactable is not contained within the list of valid targets. Return false to make the Interaction Manager clear the selection if it isn't within the list of valid targets.
A common use for disabling this is for Ray Interactors used for teleportation to make the teleportation Interactable no longer selected when not currently pointing at it.
XRBaseInteractable startingSelectedInteractable [get, set]
The Interactable that this Interactor automatically selects at startup (optional, may be null).
HoverEnterEvent hoverEntered [get, set]
The event that is called when this Interactor begins hovering over an Interactable.The HoverEnterEventArgs passed to each listener is only valid while the event is invoked, do not hold a reference to it.
HoverExitEvent hoverExited [get, set]
The event that is called when this Interactor ends hovering over an Interactable.The HoverExitEventArgs passed to each listener is only valid while the event is invoked, do not hold a reference to it.
SelectEnterEvent selectEntered [get, set]
The event that is called when this Interactor begins selecting an Interactable.The SelectEnterEventArgs passed to each listener is only valid while the event is invoked, do not hold a reference to it.
SelectExitEvent selectExited [get, set]
The event that is called when this Interactor ends selecting an Interactable.The SelectEnterEventArgs passed to each listener is only valid while the event is invoked, do not hold a reference to it.
bool allowHover [get, set]
Defines whether this interactor allows hover events.
bool allowSelect [get, set]
Defines whether this interactor allows select events.
bool isPerformingManualInteraction [get]
Defines whether this interactor is performing a manual interaction or not.
List< IXRHoverInteractable > interactablesHovered = new List<IXRHoverInteractable>() [get]
(Read Only) The list of Interactables that are currently being hovered over (may by empty).You should treat this as a read only view of the list and should not modify it. It is exposed as a List<T> rather than an IReadOnlyList<T> to avoid GC Allocations when enumerating the list.
bool hasHover [get]
(Read Only) Indicates whether this Interactor is currently hovering an Interactable.In other words, returns whether interactablesHovered contains any Interactables.
interactablesHovered.Count > 0
List< IXRSelectInteractable > interactablesSelected = new List<IXRSelectInteractable>() [get]
(Read Only) The list of Interactables that are currently being selected (may by empty).This should be treated as a read only view of the list and should not be modified by external callers. It is exposed as a List<T> rather than an IReadOnlyList<T> to avoid GC Allocations when enumerating the list.
IXRSelectInteractable firstInteractableSelected [get]
(Read Only) The first Interactable selected since not having any selection. This Interactor may not currently be selecting the Interactable, which would be the case when it was released while multiple Interactables were selected.
See also
IXRSelectInteractable.firstInteractorSelecting
bool hasSelection [get]
(Read Only) Indicates whether this Interactor is currently selecting an Interactable.In other words, returns whether interactablesSelected contains any Interactables.
interactablesSelected.Count > 0
virtual bool isHoverActive [get]
(Read Only) Indicates whether this Interactor is in a state where it could hover.
virtual bool isSelectActive [get]
(Read Only) Indicates whether this Interactor is in a state where it could select.
virtual XRBaseInteractable.? MovementType selectedInteractableMovementTypeOverride [get]
(Read Only) Overriding movement type of the selected Interactable's movement. By default, this does not override the movement type.
LayerMask interactionLayerMask [get, set]
(Deprecated) Allows interaction with Interactables whose Interaction Layer Mask overlaps with any Layer in this Interaction Layer Mask.
bool enableInteractions [get, set]
(Deprecated) Defines whether interactions are enabled or not.
XRInteractorEvent onHoverEntered [get, set]
(Deprecated) Gets or sets the event that Unity calls when this Interactor begins hovering over an Interactable.
XRInteractorEvent onHoverExited [get, set]
(Deprecated) Gets or sets the event that Unity calls when this Interactor ends hovering over an Interactable.
XRInteractorEvent onSelectEntered [get, set]
(Deprecated) Gets or sets the event that Unity calls when this Interactor begins selecting an Interactable.
XRInteractorEvent onSelectExited [get, set]
(Deprecated) Gets or sets the event that Unity calls when this Interactor ends selecting an Interactable.
XRInteractorEvent onHoverEnter [get]
(Deprecated) Gets or sets the event that Unity calls when this Interactor begins hovering over an Interactable.
XRInteractorEvent onHoverExit [get]
(Deprecated) Gets or sets the event that Unity calls when this Interactor ends hovering over an Interactable.
XRInteractorEvent onSelectEnter [get]
(Deprecated) Gets or sets the event that Unity calls when this Interactor begins selecting an Interactable.
XRInteractorEvent onSelectExit [get]
(Deprecated) Gets or sets the event that Unity calls when this Interactor ends selecting an Interactable.
XRBaseInteractable selectTarget [get, protected set]
Selected Interactable for this Interactor (may be null).
List< XRBaseInteractable > hoverTargets = new List<XRBaseInteractable>() [get]
Target Interactables that are currently being hovered over (may by empty).
virtual bool requireSelectExclusive [get]
(Deprecated) (Read Only) Indicates whether this Interactor requires that an Interactable is not currently selected to begin selecting it.
Properties inherited from UnityEngine.XR.Interaction.Toolkit.IXRHoverInteractor
Properties inherited from UnityEngine.XR.Interaction.Toolkit.IXRInteractor
Transform transform [get]
(Read Only) The Transform associated with the Interactor.
Properties inherited from UnityEngine.XR.Interaction.Toolkit.IXRSelectInteractor
Properties inherited from UnityEngine.XR.Interaction.Toolkit.IXRActivateInteractor
Additional Inherited Members
Events inherited from UnityEngine.XR.Interaction.Toolkit.XRBaseInteractor
Action< InteractorRegisteredEventArgs > registered
Action< InteractorUnregisteredEventArgs > unregistered
Events inherited from UnityEngine.XR.Interaction.Toolkit.IXRInteractor
Action< InteractorRegisteredEventArgs > registered
Calls the methods in its invocation list when this Interactor is registered with an Interaction Manager.
Action< InteractorUnregisteredEventArgs > unregistered
Calls the methods in its invocation list when this Interactor is unregistered from an Interaction Manager.
Detailed Description
Interactor used for interacting with interactables at a distance. This is handled via ray casts that update the current set of valid targets for this interactor.
Member Enumeration Documentation
HitDetectionType
enum UnityEngine.XR.Interaction.Toolkit.XRRayInteractor.HitDetectionType
Sets which shape of physics cast to use for the cast when detecting collisions.
Enumerator
Raycast
Uses Physics Ray cast to detect collisions.
SphereCast
Uses Physics Sphere Cast to detect collisions.
LineType
enum UnityEngine.XR.Interaction.Toolkit.XRRayInteractor.LineType
Sets which trajectory path Unity uses for the cast when detecting collisions.
See also
lineType
Enumerator
StraightLine
Performs a single ray cast into the Scene with a set ray length.
ProjectileCurve
Samples the trajectory of a projectile to generate a projectile curve.
BezierCurve
Uses a control point and an end point to create a quadratic Bzier curve.
Member Function Documentation
Awake()
override void UnityEngine.XR.Interaction.Toolkit.XRRayInteractor.Awake () protected virtual
See MonoBehaviour.
Reimplemented from UnityEngine.XR.Interaction.Toolkit.XRBaseControllerInteractor.
CanHover() [1/2]
override bool UnityEngine.XR.Interaction.Toolkit.XRRayInteractor.CanHover (IXRHoverInteractable interactable) virtual
Determines if the Interactable is valid for hover this frame.
Parameters
interactable Interactable to check.
Returns
Returns true if the Interactable can be hovered over this frame.
See also
IXRHoverInteractable.IsHoverableBy
Reimplemented from UnityEngine.XR.Interaction.Toolkit.XRBaseInteractor.
CanHover() [2/2]
override bool UnityEngine.XR.Interaction.Toolkit.XRRayInteractor.CanHover (XRBaseInteractable interactable) virtual
Determines if the Interactable is valid for hover this frame.
Parameters
interactable Interactable to check.
Returns
Returns true if the interactable can be hovered over this frame.
See also
XRBaseInteractable.IsHoverableBy(XRBaseInteractor)
CanHover(XRBaseInteractable) has been deprecated. Use CanHover(IXRHoverInteractable) instead.
CanHover(XRBaseInteractable) has been deprecated. Use CanHover(IXRHoverInteractable) instead.
Reimplemented from UnityEngine.XR.Interaction.Toolkit.XRBaseInteractor.
CanSelect() [1/2]
override bool UnityEngine.XR.Interaction.Toolkit.XRRayInteractor.CanSelect (IXRSelectInteractable interactable) virtual
Determines if the Interactable is valid for selection this frame.
Parameters
interactable Interactable to check.
Returns
Returns true if the Interactable can be selected this frame.
See also
IXRSelectInteractable.IsSelectableBy
Reimplemented from UnityEngine.XR.Interaction.Toolkit.XRBaseInteractor.
CanSelect() [2/2]
override bool UnityEngine.XR.Interaction.Toolkit.XRRayInteractor.CanSelect (XRBaseInteractable interactable) virtual
Determines if the Interactable is valid for selection this frame.
Parameters
interactable Interactable to check.
Returns
Returns true if the Interactable can be selected this frame.
See also
XRBaseInteractable.IsSelectableBy(XRBaseInteractor)
CanSelect(XRBaseInteractable) has been deprecated. Use CanSelect(IXRSelectInteractable) instead.
CanSelect(XRBaseInteractable) has been deprecated. Use CanSelect(IXRSelectInteractable) instead.
Reimplemented from UnityEngine.XR.Interaction.Toolkit.XRBaseInteractor.
GetCurrentRaycastHit()
bool UnityEngine.XR.Interaction.Toolkit.XRRayInteractor.GetCurrentRaycastHit (out RaycastHit raycastHit)
GetCurrentRaycastHit has been deprecated. Use TryGetCurrent3DRaycastHit(out RaycastHit) instead.
GetLinePoints() [1/2]
bool UnityEngine.XR.Interaction.Toolkit.XRRayInteractor.GetLinePoints (ref Vector3[] linePoints, out int numPoints)
Gets the polygonal chain represented by a list of endpoints which form line segments to approximate the curve. Positions are in world space coordinates.
Parameters
linePoints When this method returns, contains the sample points if successful.
numPoints When this method returns, contains the number of sample points if successful.
Returns
Returns true if the sample points form a valid line, such as by having at least two points. Otherwise, returns false.
Implements UnityEngine.XR.Interaction.Toolkit.ILineRenderable.
Referenced by UnityEngine.XR.Interaction.Toolkit.XRRayInteractor.GetLinePoints().
GetLinePoints() [2/2]
bool UnityEngine.XR.Interaction.Toolkit.XRRayInteractor.GetLinePoints (ref Vector3[] linePoints, ref int numPoints, int _ = default)
(Obsolete) Use ILineRenderable.GetLinePoints instead.
Parameters
linePoints Obsolete.
numPoints Obsolete.
_ Dummy value to support old function signature.
Returns
Obsolete.
GetLinePoints with ref int parameter has been deprecated. Use signature with out int parameter instead.
GetValidTargets()
override void UnityEngine.XR.Interaction.Toolkit.XRRayInteractor.GetValidTargets (List< IXRInteractable > targets) virtual
Retrieve the list of Interactables that this Interactor could possibly interact with this frame. This list is sorted by priority (with highest priority first).
Parameters
targets The results list to populate with Interactables that are valid for selection or hover.
When implementing this method, Unity expects you to clear targets before adding to it.
Reimplemented from UnityEngine.XR.Interaction.Toolkit.XRBaseInteractor.
Referenced by UnityEngine.XR.Interaction.Toolkit.XRRayInteractor.PreprocessInteractor().
OnDisable()
override void UnityEngine.XR.Interaction.Toolkit.XRRayInteractor.OnDisable () protected virtual
See MonoBehaviour.
Reimplemented from UnityEngine.XR.Interaction.Toolkit.XRBaseInteractor.
OnDrawGizmosSelected()
virtual void UnityEngine.XR.Interaction.Toolkit.XRRayInteractor.OnDrawGizmosSelected () protected virtual
See MonoBehaviour.
OnEnable()
override void UnityEngine.XR.Interaction.Toolkit.XRRayInteractor.OnEnable () protected virtual
See MonoBehaviour.
Reimplemented from UnityEngine.XR.Interaction.Toolkit.XRBaseInteractor.
OnSelectEntering()
override void UnityEngine.XR.Interaction.Toolkit.XRRayInteractor.OnSelectEntering (SelectEnterEventArgs args) protected virtual
The XRInteractionManager calls this method right before the Interactor first initiates selection of an Interactable in a first pass.
Parameters
args Event data containing the Interactable that is being selected.
args is only valid during this method call, do not hold a reference to it.
Reimplemented from UnityEngine.XR.Interaction.Toolkit.XRBaseControllerInteractor.
OnSelectExiting()
override void UnityEngine.XR.Interaction.Toolkit.XRRayInteractor.OnSelectExiting (SelectExitEventArgs args) protected virtual
The XRInteractionManager calls this method right before the Interactor ends selection of an Interactable in a first pass.
Parameters
args Event data containing the Interactable that is no longer selected.
args is only valid during this method call, do not hold a reference to it.
Reimplemented from UnityEngine.XR.Interaction.Toolkit.XRBaseControllerInteractor.
OnValidate()
void UnityEngine.XR.Interaction.Toolkit.XRRayInteractor.OnValidate () protected
See MonoBehaviour.
PreprocessInteractor()
override void UnityEngine.XR.Interaction.Toolkit.XRRayInteractor.PreprocessInteractor (XRInteractionUpdateOrder::UpdatePhase updatePhase) virtual
The XRInteractionManager calls this method to update the Interactor before interaction events occur. Interactors should use this method to do tasks like determine their valid targets.
Parameters
updatePhase The update phase this is called during.
Please see the XRInteractionManager and XRInteractionUpdateOrder.UpdatePhase documentation for more details on update order.
Reimplemented from UnityEngine.XR.Interaction.Toolkit.XRBaseControllerInteractor.
ProcessInteractor()
override void UnityEngine.XR.Interaction.Toolkit.XRRayInteractor.ProcessInteractor (XRInteractionUpdateOrder::UpdatePhase updatePhase) virtual
The XRInteractionManager calls this method to update the Interactor after interaction events occur.
Parameters
updatePhase The update phase this is called during.
Please see the XRInteractionManager and XRInteractionUpdateOrder.UpdatePhase documentation for more details on update order.
Reimplemented from UnityEngine.XR.Interaction.Toolkit.XRBaseControllerInteractor.
RotateAnchor()
virtual void UnityEngine.XR.Interaction.Toolkit.XRRayInteractor.RotateAnchor (Transform anchor, float directionAmount) protected virtual
Rotates the attach anchor for this interactor. This can be useful to rotate a held object.
Parameters
anchor The attach transform of the interactor.
directionAmount The rotation amount.
Referenced by UnityEngine.XR.Interaction.Toolkit.XRRayInteractor.ProcessInteractor().
TranslateAnchor()
virtual void UnityEngine.XR.Interaction.Toolkit.XRRayInteractor.TranslateAnchor (Transform rayOrigin, Transform anchor, float directionAmount) protected virtual
Translates the attach anchor for this interactor. This can be useful to move a held object closer or further away from the interactor.
Parameters
rayOrigin The starting position and direction of any ray casts.
anchor The attach transform of the interactor.
directionAmount The translation amount.
Referenced by UnityEngine.XR.Interaction.Toolkit.XRRayInteractor.ProcessInteractor().
TryGetCurrent3DRaycastHit() [1/2]
bool UnityEngine.XR.Interaction.Toolkit.XRRayInteractor.TryGetCurrent3DRaycastHit (out RaycastHit raycastHit)
Referenced by UnityEngine.XR.Interaction.Toolkit.XRRayInteractor.GetCurrentRaycastHit(), UnityEngine.XR.Interaction.Toolkit.XRRayInteractor.OnDrawGizmosSelected(), UnityEngine.XR.Interaction.Toolkit.XRRayInteractor.OnSelectEntering(), UnityEngine.XR.Interaction.Toolkit.XRRayInteractor.TryGetCurrent3DRaycastHit(), and UnityEngine.XR.Interaction.Toolkit.XRRayInteractor.TryGetCurrentRaycast().
TryGetCurrent3DRaycastHit() [2/2]
bool UnityEngine.XR.Interaction.Toolkit.XRRayInteractor.TryGetCurrent3DRaycastHit (out RaycastHit raycastHit, out int raycastEndpointIndex)
Gets the first 3D ray cast hit, if any ray cast hits are available.
Parameters
raycastHit When this method returns, contains the ray cast hit if available; otherwise, the default value.
raycastEndpointIndex When this method returns, contains the index of the sample endpoint if a hit occurred. Otherwise, a value of 0 if no hit occurred.
Returns
Returns true if a hit occurred, implying the ray cast hit information is valid. Otherwise, returns false.
TryGetCurrentRaycast()
bool UnityEngine.XR.Interaction.Toolkit.XRRayInteractor.TryGetCurrentRaycast (out RaycastHit? raycastHit, out int raycastHitIndex, out RaycastResult? uiRaycastHit, out int uiRaycastHitIndex, out bool isUIHitClosest)
Gets the first 3D and UI ray cast hits, if any ray cast hits are available.
Parameters
raycastHit When this method returns, contains the ray cast hit if available; otherwise, the default value.
raycastHitIndex When this method returns, contains the index of the sample endpoint if a hit occurred. Otherwise, a value of 0 if no hit occurred.
uiRaycastHit When this method returns, contains the UI ray cast result if available; otherwise, the default value.
uiRaycastHitIndex When this method returns, contains the index of the sample endpoint if a hit occurred. Otherwise, a value of 0 if no hit occurred.
isUIHitClosest When this method returns, contains whether the UI ray cast result was the closest hit.
Returns
Returns true if either hit occurred, implying the ray cast hit information is valid. Otherwise, returns false.
Referenced by UnityEngine.XR.Interaction.Toolkit.XRRayInteractor.TryGetHitInfo().
TryGetCurrentUIRaycastResult() [1/2]
bool UnityEngine.XR.Interaction.Toolkit.XRRayInteractor.TryGetCurrentUIRaycastResult (out RaycastResult raycastResult)
Referenced by UnityEngine.XR.Interaction.Toolkit.XRRayInteractor.GetValidTargets(), UnityEngine.XR.Interaction.Toolkit.XRRayInteractor.OnDrawGizmosSelected(), UnityEngine.XR.Interaction.Toolkit.XRRayInteractor.TryGetCurrentRaycast(), and UnityEngine.XR.Interaction.Toolkit.XRRayInteractor.TryGetCurrentUIRaycastResult().
TryGetCurrentUIRaycastResult() [2/2]
bool UnityEngine.XR.Interaction.Toolkit.XRRayInteractor.TryGetCurrentUIRaycastResult (out RaycastResult raycastResult, out int raycastEndpointIndex)
Gets the first UI ray cast result, if any ray cast results are available.
Parameters
raycastResult When this method returns, contains the UI ray cast result if available; otherwise, the default value.
raycastEndpointIndex When this method returns, contains the index of the sample endpoint if a hit occurred. Otherwise, a value of 0 if no hit occurred.
Returns
Returns true if a hit occurred, implying the ray cast hit information is valid. Otherwise, returns false.
TryGetHitInfo() [1/2]
bool UnityEngine.XR.Interaction.Toolkit.XRRayInteractor.TryGetHitInfo (out Vector3 position, out Vector3 normal, out int positionInLine, out bool isValidTarget)
Gets the current ray cast hit information, if a hit occurs. It returns the world position and the normal vector of the hit point, and its position in linePoints.
Parameters
position When this method returns, contains the world position of the ray impact point if a hit occurred.
normal When this method returns, contains the world normal of the surface the ray hit if a hit occurred.
positionInLine When this method returns, contains the index of the sample endpoint within the list of points returned by GetLinePoints where a hit occurred. Otherwise, a value of 0 if no hit occurred.
isValidTarget When this method returns, contains whether both a hit occurred and it is a valid target for interaction.
Returns
Returns true if a hit occurs, implying the ray cast hit information is valid. Otherwise, returns false.
Implements UnityEngine.XR.Interaction.Toolkit.ILineRenderable.
Referenced by UnityEngine.XR.Interaction.Toolkit.XRRayInteractor.TryGetHitInfo().
TryGetHitInfo() [2/2]
bool UnityEngine.XR.Interaction.Toolkit.XRRayInteractor.TryGetHitInfo (ref Vector3 position, ref Vector3 normal, ref int positionInLine, ref bool isValidTarget, int _ = default)
(Obsolete) Use ILineRenderable.TryGetHitInfo instead.
Parameters
position Obsolete.
normal Obsolete.
positionInLine Obsolete.
isValidTarget Obsolete.
_ Dummy value to support old function signature.
Returns
Obsolete.
TryGetHitInfo with ref parameters has been deprecated. Use signature with out parameters instead.
TryGetUIModel()
bool UnityEngine.XR.Interaction.Toolkit.XRRayInteractor.TryGetUIModel (out TrackedDeviceModel model)
Attempts to retrieve the current UI Model.
Parameters
model The returned model that reflects the UI state of this Interactor.
Returns
Returns true if the model was able to retrieved. Otherwise, returns false.
Implements UnityEngine.XR.Interaction.Toolkit.UI.IUIInteractor.
Referenced by UnityEngine.XR.Interaction.Toolkit.XRRayInteractor.TryGetCurrentUIRaycastResult().
UpdateUIModel()
virtual void UnityEngine.XR.Interaction.Toolkit.XRRayInteractor.UpdateUIModel (ref TrackedDeviceModel model) virtual
Updates the current UI Model to match the state of the Interactor.
Parameters
model The returned model that will match this Interactor.
Implements UnityEngine.XR.Interaction.Toolkit.UI.IUIInteractor.
Property Documentation
acceleration
float UnityEngine.XR.Interaction.Toolkit.XRRayInteractor.acceleration get set
Gravity of the projectile in the reference frame.
See also
LineType.ProjectileCurve
Acceleration
float UnityEngine.XR.Interaction.Toolkit.XRRayInteractor.Acceleration get set
(Deprecated) Gravity of the projectile in the reference frame.
See also
LineType.ProjectileCurve
Acceleration has been deprecated. Use acceleration instead.
additionalFlightTime
float UnityEngine.XR.Interaction.Toolkit.XRRayInteractor.additionalFlightTime get set
Additional flight time after the projectile lands at the adjusted ground level. Increasing this value will make the end point drop lower in height.
See also
LineType.ProjectileCurve
AdditionalFlightTime
float UnityEngine.XR.Interaction.Toolkit.XRRayInteractor.AdditionalFlightTime get set add
AdditionalFlightTime has been deprecated. Use additionalFlightTime instead.
additionalGroundHeight
float UnityEngine.XR.Interaction.Toolkit.XRRayInteractor.additionalGroundHeight get set
Additional height below ground level that the projectile will continue to. Increasing this value will make the end point drop lower in height.
See also
LineType.ProjectileCurve
allowAnchorControl
bool UnityEngine.XR.Interaction.Toolkit.XRRayInteractor.allowAnchorControl get set
Allows the user to move the attach anchor point using the joystick.
See also
rotateSpeed, translateSpeed, anchorRotateReferenceFrame
anchorRotateReferenceFrame
Transform UnityEngine.XR.Interaction.Toolkit.XRRayInteractor.anchorRotateReferenceFrame get set
The optional reference frame to define the up axis when rotating the attach anchor point. When not set, rotates about the local up axis of the attach transform.
See also
allowAnchorControl, RotateAnchor
angle
float UnityEngine.XR.Interaction.Toolkit.XRRayInteractor.angle get
The launch angle of the Projectile Curve. More specifically, this is the signed angle in degrees between the original attach forward direction and the plane of the reference frame, with positive angles when pointing upward.
Angle
float UnityEngine.XR.Interaction.Toolkit.XRRayInteractor.Angle get
Angle has been deprecated. Use angle instead.
blendVisualLinePoints
bool UnityEngine.XR.Interaction.Toolkit.XRRayInteractor.blendVisualLinePoints get set
Blend the line sample points Unity uses for ray casting with the current pose of the controller. Use this to make the line visual stay connected with the controller instead of lagging behind.
When the controller is configured to sample tracking input directly before rendering to reduce input latency, the controller may be in a new position or rotation relative to the starting point of the sample curve used for ray casting.
A value of false will make the line visual stay at a fixed reference frame rather than bending or curving towards the end of the ray cast line.
controlPointDistance
float UnityEngine.XR.Interaction.Toolkit.XRRayInteractor.controlPointDistance get set
Increase this value to make the peak of the curve further from the start point.
See also
LineType.BezierCurve
controlPointHeight
float UnityEngine.XR.Interaction.Toolkit.XRRayInteractor.controlPointHeight get set
Increase this value to make the peak of the curve higher relative to the start point.
See also
LineType.BezierCurve
enableUIInteraction
bool UnityEngine.XR.Interaction.Toolkit.XRRayInteractor.enableUIInteraction get set
Gets or sets whether this Interactor is able to affect UI.
endPointDistance
float UnityEngine.XR.Interaction.Toolkit.XRRayInteractor.endPointDistance get set
Increase this value distance to make the end of the curve further from the start point.
See also
LineType.BezierCurve
endPointHeight
float UnityEngine.XR.Interaction.Toolkit.XRRayInteractor.endPointHeight get set
Decrease this value to make the end of the curve drop lower relative to the start point.
See also
LineType.BezierCurve
hitClosestOnly
bool UnityEngine.XR.Interaction.Toolkit.XRRayInteractor.hitClosestOnly get set
Whether Unity considers only the closest Interactable as a valid target for interaction.
Enable this to make only the closest Interactable receive hover events. Otherwise, all hit Interactables will be considered valid and this Interactor will multi-hover.
See also
GetValidTargets
hitDetectionType
HitDetectionType UnityEngine.XR.Interaction.Toolkit.XRRayInteractor.hitDetectionType get set
Gets or sets which type of hit detection to use for the ray cast.
hoverTimeToSelect
float UnityEngine.XR.Interaction.Toolkit.XRRayInteractor.hoverTimeToSelect get set
Number of seconds for which this Interactor must hover over an Interactable to select it if Hover To Select is enabled.
See also
hoverToSelect
hoverToSelect
bool UnityEngine.XR.Interaction.Toolkit.XRRayInteractor.hoverToSelect get set
Whether this Interactor will automatically select an Interactable after hovering over it for a period of time.
See also
hoverTimeToSelect
isSelectActive
override bool UnityEngine.XR.Interaction.Toolkit.XRRayInteractor.isSelectActive get
(Read Only) Indicates whether this Interactor is in a state where it could select.
Implements UnityEngine.XR.Interaction.Toolkit.IXRSelectInteractor.
lineType
LineType UnityEngine.XR.Interaction.Toolkit.XRRayInteractor.lineType get set
Gets or sets the type of ray cast.
maxRaycastDistance
float UnityEngine.XR.Interaction.Toolkit.XRRayInteractor.maxRaycastDistance get set
Gets or sets the max distance of ray cast when the line type is a straight line. Increasing this value will make the line reach further.
See also
LineType.StraightLine
originalAttachTransform
Transform UnityEngine.XR.Interaction.Toolkit.XRRayInteractor.originalAttachTransform get set protected
The Transform that upon entering selection (when this Interactor first initiates selection of an Interactable), this Interactor will copy the pose of the attach Transform values into.
Automatically instantiated and set in Awake. Setting this will not automatically destroy the previous object.
originalAttachTransform has been deprecated. Use rayOriginTransform instead.
See also
XRBaseInteractor.attachTransform
raycastMask
LayerMask UnityEngine.XR.Interaction.Toolkit.XRRayInteractor.raycastMask get set
Gets or sets layer mask used for limiting ray cast targets.
Referenced by UnityEngine.XR.Interaction.Toolkit.XRRayInteractor.UpdateUIModel().
raycastTriggerInteraction
QueryTriggerInteraction UnityEngine.XR.Interaction.Toolkit.XRRayInteractor.raycastTriggerInteraction get set
Gets or sets type of interaction with trigger volumes via ray cast.
rayOriginTransform
Transform UnityEngine.XR.Interaction.Toolkit.XRRayInteractor.rayOriginTransform get set
The starting position and direction of any ray casts.
Automatically instantiated and set in Awake if null and initialized with the pose of the XRBaseInteractor.attachTransform. Setting this will not automatically destroy the previous object.
referenceFrame
Transform UnityEngine.XR.Interaction.Toolkit.XRRayInteractor.referenceFrame get set
The reference frame of the curve to define the ground plane and up. If not set at startup it will try to find the XROrigin.Origin GameObject, and if that does not exist it will use global up and origin by default.
See also
LineType.ProjectileCurve, LineType.BezierCurve
rotateSpeed
float UnityEngine.XR.Interaction.Toolkit.XRRayInteractor.rotateSpeed get set
Speed that the anchor is rotated.
See also
allowAnchorControl, translateSpeed
sampleFrequency
int UnityEngine.XR.Interaction.Toolkit.XRRayInteractor.sampleFrequency get set
The number of sample points Unity uses to approximate curved paths. Larger values produce a better quality approximate at the cost of reduced performance due to the number of ray casts.
A value of n will result in n - 1 line segments for ray cast. This property is not used when using LineType.StraightLine since the value would always be 2.
See also
LineType.ProjectileCurve, LineType.BezierCurve
sphereCastRadius
float UnityEngine.XR.Interaction.Toolkit.XRRayInteractor.sphereCastRadius get set
Gets or sets radius used for sphere casting. Will use regular ray casting if set to 0 or less.
See also
HitDetectionType.SphereCast, hitDetectionType
translateSpeed
float UnityEngine.XR.Interaction.Toolkit.XRRayInteractor.translateSpeed get set
Speed that the anchor is translated.
See also
allowAnchorControl, rotateSpeed
useForceGrab
bool UnityEngine.XR.Interaction.Toolkit.XRRayInteractor.useForceGrab get set
Force grab moves the object to your hand rather than interacting with it at a distance.
velocity
float UnityEngine.XR.Interaction.Toolkit.XRRayInteractor.velocity get set
Initial velocity of the projectile. Increasing this value will make the curve reach further.
See also
LineType.ProjectileCurve
Velocity
float UnityEngine.XR.Interaction.Toolkit.XRRayInteractor.Velocity get set
(Deprecated) Initial velocity of the projectile. Increasing this value will make the curve reach further.
See also
LineType.ProjectileCurve
Velocity has been deprecated. Use velocity instead.
The documentation for this class was generated from the following files:
C:/Users/Lykos/Desktop/Projects/Capstone/VRGames/Library/PackageCache/com.unity.xr.interaction.toolkit@2.0.2/Runtime/Interaction/Interactors/XRRayInteractor.cs
C:/Users/Lykos/Desktop/Projects/Capstone/VRGames/Library/PackageCache/com.unity.xr.interaction.toolkit@2.0.2/Runtime/Interaction/Interactors/XRRayInteractor.deprecated.cs