VRGames: UnityEngine.XR.Management.XRLoader Class Reference
UnityEngine.XR.Management.XRLoader Class Reference abstract
XR Loader abstract class used as a base class for specific provider implementations. Providers should implement subclasses of this to provide specific initialization and management implementations that make sense for their supported scenarios and needs.
Public Member Functions
virtual bool Initialize ()
Initialize the loader. This should initialize all subsystems to support the desired runtime setup this loader represents.
virtual bool Start ()
Ask loader to start all initialized subsystems.
virtual bool Stop ()
Ask loader to stop all initialized subsystems.
virtual bool Deinitialize ()
Ask loader to deinitialize all initialized subsystems.
T GetLoadedSubsystem< T > ()
Gets the loaded subsystem of the specified type. Implementation dependent as only implemetnations know what they have loaded and how best to get it..
virtual List< GraphicsDeviceType > GetSupportedGraphicsDeviceTypes (bool buildingPlayer)
Gets the loader's supported graphics device types. If the list is empty, it is assumed that it supports all graphics device types.
Detailed Description
XR Loader abstract class used as a base class for specific provider implementations. Providers should implement subclasses of this to provide specific initialization and management implementations that make sense for their supported scenarios and needs.
Member Function Documentation
Deinitialize()
virtual bool UnityEngine.XR.Management.XRLoader.Deinitialize () virtual
Ask loader to deinitialize all initialized subsystems.
Returns
Whether or not deinitialization succeeded.
Reimplemented in UnityEngine.XR.Management.XRLoaderHelper, Samples.SampleLoader, UnityEngine.XR.Management.Tests.Standalone.StandaloneLoader, Unity.XR.Management.TestPackage.TestLoaderBase, and Unity.XR.Oculus.OculusLoader.
Referenced by UnityEngine.XR.Management.XRManagerSettings.DeinitializeLoader().
GetLoadedSubsystem< T >()
T UnityEngine.XR.Management.XRLoader.GetLoadedSubsystem< T > () abstract
Gets the loaded subsystem of the specified type. Implementation dependent as only implemetnations know what they have loaded and how best to get it..
Template Parameters
T Type of the subsystem to get
Returns
The loaded subsystem or null if not found.
Type Constraints
T : class
T : ISubsystem
GetSupportedGraphicsDeviceTypes()
virtual List< GraphicsDeviceType > UnityEngine.XR.Management.XRLoader.GetSupportedGraphicsDeviceTypes (bool buildingPlayer) virtual
Gets the loader's supported graphics device types. If the list is empty, it is assumed that it supports all graphics device types.
Parameters
buildingPlayer True if the player is being built. You may want to include or exclude graphics apis if the player is being built or not.
Returns
Returns the loader's supported graphics device types.
Initialize()
virtual bool UnityEngine.XR.Management.XRLoader.Initialize () virtual
Initialize the loader. This should initialize all subsystems to support the desired runtime setup this loader represents.
This is the only method on XRLoader that Management uses to determine the active loader to use. If this method returns true, Management locks this loader as the XRManagerSettings.activeLoader and and stops fall through processing on the XRManagerSettings.loaders list of current loaders.
If this method returns false, XRManagerSettings continues to process the next loader in the XRManagerSettings.loaders list, or fails completely when the list is exhausted.
Returns
Whether or not initialization succeeded.
Reimplemented in Samples.SampleLoader, UnityEngine.XR.Management.Tests.Standalone.StandaloneLoader, Unity.XR.Management.TestPackage.TestLoaderBase, and Unity.XR.Oculus.OculusLoader.
Start()
virtual bool UnityEngine.XR.Management.XRLoader.Start () virtual
Ask loader to start all initialized subsystems.
Returns
Whether or not all subsystems were successfully started.
Reimplemented in Samples.SampleLoader, UnityEngine.XR.Management.Tests.Standalone.StandaloneLoader, Unity.XR.Management.TestPackage.TestLoaderBase, and Unity.XR.Oculus.OculusLoader.
Referenced by UnityEngine.XR.Management.XRManagerSettings.StartSubsystems().
Stop()
virtual bool UnityEngine.XR.Management.XRLoader.Stop () virtual
Ask loader to stop all initialized subsystems.
Returns
Whether or not all subsystems were successfully stopped.
Reimplemented in Samples.SampleLoader, UnityEngine.XR.Management.Tests.Standalone.StandaloneLoader, Unity.XR.Management.TestPackage.TestLoaderBase, and Unity.XR.Oculus.OculusLoader.
Referenced by UnityEngine.XR.Management.XRManagerSettings.StopSubsystems().
The documentation for this class was generated from the following file:
C:/Users/Lykos/Desktop/Projects/Capstone/VRGames/Library/PackageCache/com.unity.xr.management@4.2.1/Runtime/XRLoader.cs