VRCapstoneGames: UnityEngine.ProBuilder.SharedVertex Class Reference
UnityEngine.ProBuilder.SharedVertex Class Reference sealed
Defines associations between vertex positions that are coincident. The indexes stored in this collection correspond to the ProBuilderMesh.positions array.
Public Member Functions
SharedVertex (IEnumerable< int > indexes)
Creates a new SharedVertex from the specified indices.
SharedVertex (SharedVertex sharedVertex)
Creates a new SharedVertex from the specified SharedVertex object.
IEnumerator< int > GetEnumerator ()
Returns an enumerator that iterates through this collection.
override string ToString ()
Returns a string that represents this SharedVertex.
void Add (int item)
Adds a new entry using the specified index.
void Clear ()
Resets this SharedVertex object to an empty collection.
bool Contains (int item)
Returns whether the specified item exists in this collection.
void CopyTo (int[] array, int arrayIndex)
Copies the elements of this collection to an array, starting at the specified arrayIndex.
bool Remove (int item)
Removes the specified item from this collection.
Static Public Member Functions
static void GetSharedVertexLookup (IList< SharedVertex > sharedVertices, Dictionary< int, int > lookup)
Creates a lookup Dictionary in order to quickly find the index of a SharedVertex in the ProBuilderMesh.sharedVertices array using a vertex index.
static SharedVertex[] GetSharedVerticesWithPositions (IList< Vector3 > positions)
Creates a new array of SharedVertex objects by comparing points in the specified positions collection.
Properties
int this[int i] [get, set]
Gets and sets the vertex by index.
int Count [get]
Gets the number of items in this collection.
bool IsReadOnly [get]
Gets whether this collection is read-only.
Detailed Description
Defines associations between vertex positions that are coincident. The indexes stored in this collection correspond to the ProBuilderMesh.positions array.
Coincident vertices are vertices that share the same coordinate position, but are separate entries in the vertex array.
Constructor & Destructor Documentation
SharedVertex() [1/2]
UnityEngine.ProBuilder.SharedVertex.SharedVertex (IEnumerable< int > indexes)
Creates a new SharedVertex from the specified indices.
Parameters
indexes An array of indices to set.
Referenced by UnityEngine.ProBuilder.SharedVertex.GetSharedVerticesWithPositions().
SharedVertex() [2/2]
UnityEngine.ProBuilder.SharedVertex.SharedVertex (SharedVertex sharedVertex)
Creates a new SharedVertex from the specified SharedVertex object.
Parameters
sharedVertex The SharedVertex object to copy.
Member Function Documentation
Add()
void UnityEngine.ProBuilder.SharedVertex.Add (int item)
Adds a new entry using the specified index.
Parameters
item The index to add.
Referenced by UnityEngine.ProBuilder.ProBuilderMesh.GetCoincidentVertices(), UnityEngine.ProBuilder.ProBuilderMesh.GetCoincidentVertices(), UnityEngine.ProBuilder.ProBuilderMesh.GetCoincidentVertices(), and UnityEngine.ProBuilder.ProBuilderMesh.GetCoincidentVertices().
Clear()
void UnityEngine.ProBuilder.SharedVertex.Clear ()
Resets this SharedVertex object to an empty collection.
Contains()
bool UnityEngine.ProBuilder.SharedVertex.Contains (int item)
Returns whether the specified item exists in this collection.
Parameters
item The index of the item to check.
Returns
True if the index was found; false otherwise
CopyTo()
void UnityEngine.ProBuilder.SharedVertex.CopyTo (int[] array, int arrayIndex)
Copies the elements of this collection to an array, starting at the specified arrayIndex.
Parameters
array The destination array.
arrayIndex The index in the destination array where the collection items will be copied.
GetEnumerator()
IEnumerator< int > UnityEngine.ProBuilder.SharedVertex.GetEnumerator ()
Returns an enumerator that iterates through this collection.
Returns
An IEnumerator object that you can use to iterate through the collection.
GetSharedVertexLookup()
static void UnityEngine.ProBuilder.SharedVertex.GetSharedVertexLookup (IList< SharedVertex > sharedVertices, Dictionary< int, int > lookup) static
Creates a lookup Dictionary in order to quickly find the index of a SharedVertex in the ProBuilderMesh.sharedVertices array using a vertex index.
Parameters
sharedVertices A collection of SharedVertex values.
lookup A Dictionary where the 'key' represents an index in the Mesh positions array, and the 'value' is the index of its placement in the sharedVertices array.
GetSharedVerticesWithPositions()
static SharedVertex[] UnityEngine.ProBuilder.SharedVertex.GetSharedVerticesWithPositions (IList< Vector3 > positions) static
Creates a new array of SharedVertex objects by comparing points in the specified positions collection.
 -csharp
<![CDATA[var mesh = gameObject.AdComponent<ProBuilderMesh>();
mesh.SetPositions(myNewPositions);
mesh.SetFaces(myNewFaces);
mesh.SetSharedIndexes(SharedVertex.GetSharedVerticesWithPositions(myNewPositions));]]>
Parameters
positions A collection of Vector3 positions to test for equality.
Returns
A new SharedVertex array where each item is a list of indices that share the same position.
Referenced by UnityEngine.ProBuilder.MeshOperations.MeshImporter.Import(), and UnityEngine.ProBuilder.ProBuilderMesh.RebuildWithPositionsAndFaces().
Remove()
bool UnityEngine.ProBuilder.SharedVertex.Remove (int item)
Removes the specified item from this collection.
Parameters
item The index of the item to remove.
Returns
True if the index was found and removed; false otherwise
ToString()
override string UnityEngine.ProBuilder.SharedVertex.ToString ()
Returns a string that represents this SharedVertex.
Returns
A comma-delimited string (for example "2,0,6,3").
Property Documentation
Count
int UnityEngine.ProBuilder.SharedVertex.Count get
Gets the number of items in this collection.
Returns
The length of this collection
Referenced by UnityEngine.ProBuilder.SharedVertex.SharedVertex().
IsReadOnly
bool UnityEngine.ProBuilder.SharedVertex.IsReadOnly get
Gets whether this collection is read-only.
Returns
The value of the IsReadOnly flag.
this[int i]
int UnityEngine.ProBuilder.SharedVertex.this[int i] get set
Gets and sets the vertex by index.
Parameters
i The index to access.
The documentation for this class was generated from the following file:
C:/Users/Lykos/Desktop/Projects/Capstone/VRGames/Library/PackageCache/com.unity.probuilder@5.0.6/Runtime/Core/SharedVertex.cs