VRCapstoneGames: Facebook.WitAi.Windows.WitConfigurationEditor Class Reference
Facebook.WitAi.Windows.WitConfigurationEditor Class Reference
Public Member Functions
void Initialize ()
override void OnInspectorGUI ()
Public Attributes
bool drawHeader = true
Protected Member Functions
virtual void LayoutContent ()
virtual void LayoutConfigurationData ()
virtual void LayoutConfigurationEndpoint ()
virtual void LayoutConfigurationRequestTabs ()
virtual void SafeRefresh ()
Properties
WitConfiguration configuration [get]
virtual Texture2D HeaderIcon [get]
virtual string HeaderUrl [get]
Member Function Documentation
Initialize()
void Facebook.WitAi.Windows.WitConfigurationEditor.Initialize ()
Referenced by Facebook.WitAi.Windows.WitConfigurationEditor.OnInspectorGUI(), and Facebook.WitAi.Windows.WitWindow.SetWitEditor().
LayoutConfigurationData()
virtual void Facebook.WitAi.Windows.WitConfigurationEditor.LayoutConfigurationData () protected virtual
Referenced by Facebook.WitAi.Windows.WitConfigurationEditor.LayoutContent().
LayoutConfigurationEndpoint()
virtual void Facebook.WitAi.Windows.WitConfigurationEditor.LayoutConfigurationEndpoint () protected virtual
Referenced by Facebook.WitAi.Windows.WitConfigurationEditor.LayoutConfigurationData().
LayoutConfigurationRequestTabs()
virtual void Facebook.WitAi.Windows.WitConfigurationEditor.LayoutConfigurationRequestTabs () protected virtual
Referenced by Facebook.WitAi.Windows.WitConfigurationEditor.LayoutContent().
LayoutContent()
virtual void Facebook.WitAi.Windows.WitConfigurationEditor.LayoutContent () protected virtual
Referenced by Facebook.WitAi.Windows.WitConfigurationEditor.OnInspectorGUI().
OnInspectorGUI()
override void Facebook.WitAi.Windows.WitConfigurationEditor.OnInspectorGUI ()
Referenced by Facebook.WitAi.Windows.WitWindow.LayoutContent().
SafeRefresh()
virtual void Facebook.WitAi.Windows.WitConfigurationEditor.SafeRefresh () protected virtual
Referenced by Facebook.WitAi.Windows.WitConfigurationEditor.Initialize(), and Facebook.WitAi.Windows.WitConfigurationEditor.LayoutContent().
Member Data Documentation
drawHeader
bool Facebook.WitAi.Windows.WitConfigurationEditor.drawHeader = true
Referenced by Facebook.WitAi.Windows.WitConfigurationEditor.OnInspectorGUI().
Property Documentation
configuration
WitConfiguration Facebook.WitAi.Windows.WitConfigurationEditor.configuration get
Referenced by Facebook.WitAi.Windows.WitConfigurationEditor.Initialize(), Facebook.WitAi.Windows.WitConfigurationEditor.LayoutConfigurationData(), Facebook.WitAi.Windows.WitConfigurationEditor.LayoutConfigurationEndpoint(), Facebook.WitAi.Windows.WitConfigurationEditor.LayoutConfigurationRequestTabs(), Facebook.WitAi.Windows.WitConfigurationEditor.LayoutContent(), Facebook.WitAi.Windows.WitWindow.LayoutContent(), Facebook.WitAi.Windows.WitConfigurationEditor.OnInspectorGUI(), and Facebook.WitAi.Windows.WitConfigurationEditor.SafeRefresh().
HeaderIcon
virtual Texture2D Facebook.WitAi.Windows.WitConfigurationEditor.HeaderIcon get protected
Referenced by Facebook.WitAi.Windows.WitConfigurationEditor.OnInspectorGUI().
HeaderUrl
virtual string Facebook.WitAi.Windows.WitConfigurationEditor.HeaderUrl get protected
Referenced by Facebook.WitAi.Windows.WitConfigurationEditor.LayoutContent(), and Facebook.WitAi.Windows.WitConfigurationEditor.OnInspectorGUI().
The documentation for this class was generated from the following file:
C:/Users/Lykos/Desktop/Projects/Capstone/VRGames/Assets/ThirdParty/Oculus/Voice/Lib/Wit.ai/Scripts/Editor/Data/Configuration/WitConfigurationEditor.cs