VRGames: UnityEditor.SettingsManagement.Settings Class Reference
UnityEditor.SettingsManagement.Settings Class Reference sealed
Settings manages a collection of ISettingsRepository.
Public Member Functions
Settings (string package, string settingsFileName="Settings")
Create a new Settings instance with a UserSettingsRepository and PackageSettingsRepository.
Settings (IEnumerable< ISettingsRepository > repositories)
Create a new Settings instance with a collection of ISettingsRepository.
ISettingsRepository GetRepository (SettingsScope scope)
Find a settings repository that matches the requested scope.
ISettingsRepository GetRepository (SettingsScope scope, string name)
Find a settings repository that matches the requested scope and name.
void Save ()
Serialize the state of all settings repositories.
void Set< T > (string key, T value, SettingsScope scope=SettingsScope.Project)
Set a value for key of type T.
void Set< T > (string key, T value, string repositoryName, SettingsScope scope=SettingsScope.Project)
Set a value for key of type T.
T Get< T > (string key, SettingsScope scope=SettingsScope.Project, T fallback=default(T))
Get a value with key of type T, or return the fallback value if no matching key is found.
T Get< T > (string key, string repositoryName, SettingsScope scope=SettingsScope.Project, T fallback=default(T))
Get a value with key of type T, or return the fallback value if no matching key is found.
bool ContainsKey< T > (string key, SettingsScope scope=SettingsScope.Project)
Does the repository contain a setting with key and type.
bool ContainsKey< T > (string key, string repositoryName, SettingsScope scope=SettingsScope.Project)
Does the repository contain a setting with key and type.
void DeleteKey< T > (string key, SettingsScope scope=SettingsScope.Project)
Remove a key value pair from a settings repository.
void DeleteKey< T > (string key, string repositoryName, SettingsScope scope=SettingsScope.Project)
Remove a key value pair from a settings repository.
Events
Action beforeSettingsSaved
Action afterSettingsSaved
Detailed Description
Settings manages a collection of ISettingsRepository.
Constructor & Destructor Documentation
Settings() [1/2]
UnityEditor.SettingsManagement.Settings.Settings (string package, string settingsFileName = "Settings")
Create a new Settings instance with a UserSettingsRepository and PackageSettingsRepository.
Parameters
package The package name. Ex, com.unity.my-package.
settingsFileName The name of the settings file. Defaults to "Settings."
Settings() [2/2]
UnityEditor.SettingsManagement.Settings.Settings (IEnumerable< ISettingsRepository > repositories)
Create a new Settings instance with a collection of ISettingsRepository.
Member Function Documentation
ContainsKey< T >() [1/2]
bool UnityEditor.SettingsManagement.Settings.ContainsKey< T > (string key, SettingsScope scope = SettingsScope::Project)
Does the repository contain a setting with key and type.
Parameters
key The settings key.
Template Parameters
T The type of value to search for.
Parameters
scope Which scope should be searched for matching key.
Returns
True if a setting matching both key and type is found, false if no entry is found.
ContainsKey< T >() [2/2]
bool UnityEditor.SettingsManagement.Settings.ContainsKey< T > (string key, string repositoryName, SettingsScope scope = SettingsScope::Project)
Does the repository contain a setting with key and type.
Parameters
key The settings key.
repositoryName The repository name to match.
Template Parameters
T The type of value to search for.
Parameters
scope Which scope should be searched for matching key.
Returns
True if a setting matching both key and type is found, false if no entry is found.
DeleteKey< T >() [1/2]
void UnityEditor.SettingsManagement.Settings.DeleteKey< T > (string key, SettingsScope scope = SettingsScope::Project)
Remove a key value pair from a settings repository.
Parameters
key The key to remove.
scope Which scope should be searched for matching key.
Template Parameters
T The type that this key is pointing to.
DeleteKey< T >() [2/2]
void UnityEditor.SettingsManagement.Settings.DeleteKey< T > (string key, string repositoryName, SettingsScope scope = SettingsScope::Project)
Remove a key value pair from a settings repository.
Parameters
key The key to remove.
repositoryName The repository name to match.
scope Which scope should be searched for matching key.
Template Parameters
T The type that this key is pointing to.
Get< T >() [1/2]
T UnityEditor.SettingsManagement.Settings.Get< T > (string key, SettingsScope scope = SettingsScope::Project, T fallback = default(T))
Get a value with key of type T, or return the fallback value if no matching key is found.
Parameters
key The settings key.
scope Which scope this settings should be retrieved from.
fallback If no key with a value of type T is found, this value is returned.
Template Parameters
T Type of value to search for.
Get< T >() [2/2]
T UnityEditor.SettingsManagement.Settings.Get< T > (string key, string repositoryName, SettingsScope scope = SettingsScope::Project, T fallback = default(T))
Get a value with key of type T, or return the fallback value if no matching key is found.
Parameters
key The settings key.
repositoryName The repository name to match.
scope Which scope this settings should be retrieved from.
fallback If no key with a value of type T is found, this value is returned.
Template Parameters
T Type of value to search for.
GetRepository() [1/2]
ISettingsRepository UnityEditor.SettingsManagement.Settings.GetRepository (SettingsScope scope)
Find a settings repository that matches the requested scope.
Parameters
scope The scope of the settings repository to match.
Returns
An ISettingsRepository instance that is implementing the requested scope. May return null if no matching repository is found.
GetRepository() [2/2]
ISettingsRepository UnityEditor.SettingsManagement.Settings.GetRepository (SettingsScope scope, string name)
Find a settings repository that matches the requested scope and name.
Parameters
scope The scope of the settings repository to match.
name The name of the ISettingsRepository to match.
Returns
An ISettingsRepository instance that is implementing the requested scope, and matches name. May return null if no matching repository is found.
Save()
void UnityEditor.SettingsManagement.Settings.Save ()
Serialize the state of all settings repositories.
Referenced by UnityEditor.SettingsManagement.UserSetting< T >.ApplyModifiedProperties(), UnityEditor.SettingsManagement.Examples.PerPlatformSettingsTool.OnToolGUI(), and UnityEditor.SettingsManagement.UserSetting< T >.SetValue().
Set< T >() [1/2]
void UnityEditor.SettingsManagement.Settings.Set< T > (string key, T value, SettingsScope scope = SettingsScope::Project)
Set a value for key of type T.
Parameters
key The settings key.
value The value to set. Must be serializable.
scope Which scope this settings should be saved in.
Template Parameters
T Type of value.
Set< T >() [2/2]
void UnityEditor.SettingsManagement.Settings.Set< T > (string key, T value, string repositoryName, SettingsScope scope = SettingsScope::Project)
Set a value for key of type T.
Parameters
key The settings key.
value The value to set. Must be serializable.
repositoryName The repository name to match.
scope Which scope this settings should be saved in.
Template Parameters
T Type of value.
Event Documentation
afterSettingsSaved
Action UnityEditor.SettingsManagement.Settings.afterSettingsSaved
An event that is raised after an ISettingsRepository has serialized it's current state.
Referenced by UnityEditor.SettingsManagement.Settings.Save().
beforeSettingsSaved
Action UnityEditor.SettingsManagement.Settings.beforeSettingsSaved
An event that is raised prior to an ISettingsRepository serializing it's current state.
Referenced by UnityEditor.SettingsManagement.Settings.Save().
The documentation for this class was generated from the following file:
C:/Users/Lykos/Desktop/Projects/Capstone/VRGames/Library/PackageCache/com.unity.settings-manager@1.0.3/Editor/Settings.cs