VRGames: UnityEditor.Timeline.TimelineCursors Class Reference
UnityEditor.Timeline.TimelineCursors Class Reference
Public Types
enum CursorType {
MixBoth , MixLeft , MixRight , Replace ,
Ripple , Pan
}
Static Public Member Functions
static void SetCursor (CursorType cursorType)
static void ClearCursor ()
Member Enumeration Documentation
CursorType
enum UnityEditor.Timeline.TimelineCursors.CursorType
Enumerator
MixBoth
MixLeft
MixRight
Replace
Ripple
Pan
Member Function Documentation
ClearCursor()
static void UnityEditor.Timeline.TimelineCursors.ClearCursor () static
Referenced by UnityEditor.Timeline.MoveItemModeMix.DrawGUI(), UnityEditor.Timeline.MoveItemModeReplace.DrawGUI(), UnityEditor.Timeline.TrimItemModeMix.DrawGUI(), UnityEditor.Timeline.TrimItemModeReplace.DrawGUI(), UnityEditor.Timeline.EaseClip.MouseUp(), UnityEditor.Timeline.SelectAndMoveItem.MouseUp(), UnityEditor.Timeline.TimelinePanManipulator.MouseUp(), and UnityEditor.Timeline.MoveItemHandler.OnGUI().
SetCursor()
static void UnityEditor.Timeline.TimelineCursors.SetCursor (CursorType cursorType) static
Referenced by UnityEditor.Timeline.MoveItemModeMix.DrawGUI(), UnityEditor.Timeline.MoveItemModeReplace.DrawGUI(), UnityEditor.Timeline.MoveItemModeRipple.DrawGUI(), UnityEditor.Timeline.TrimItemModeMix.DrawGUI(), UnityEditor.Timeline.TrimItemModeReplace.DrawGUI(), UnityEditor.Timeline.TrimItemModeRipple.DrawGUI(), UnityEditor.Timeline.TimelinePanManipulator.MouseDown(), and UnityEditor.Timeline.EaseClip.MouseDownInternal().
The documentation for this class was generated from the following file:
C:/Users/Lykos/Desktop/Projects/Capstone/VRGames/Library/PackageCache/com.unity.timeline@1.6.4/Editor/Manipulators/Cursors/TimelineCursors.cs