VRCapstoneGames: UnityEngine.EventSystems.UIBehaviour Class Reference
UnityEngine.EventSystems.UIBehaviour Class Reference abstract
Base behaviour that has protected implementations of Unity lifecycle functions.
Public Member Functions
virtual bool IsActive ()
Returns true if the GameObject and the Component are active.
bool IsDestroyed ()
Returns true if the native representation of the behaviour has been destroyed.
Protected Member Functions
virtual void Awake ()
virtual void OnEnable ()
virtual void Start ()
virtual void OnDisable ()
virtual void OnDestroy ()
virtual void OnRectTransformDimensionsChange ()
This callback is called when the dimensions of an associated RectTransform change. It is always called before Awake, OnEnable, or Start. The call is also made to all child RectTransforms, regardless of whether their dimensions change (which depends on how they are anchored).
virtual void OnBeforeTransformParentChanged ()
virtual void OnTransformParentChanged ()
virtual void OnDidApplyAnimationProperties ()
virtual void OnCanvasGroupChanged ()
virtual void OnCanvasHierarchyChanged ()
Called when the state of the parent Canvas is changed.
Detailed Description
Base behaviour that has protected implementations of Unity lifecycle functions.
Member Function Documentation
Awake()
virtual void UnityEngine.EventSystems.UIBehaviour.Awake () protected virtual
Reimplemented in TMPro.TextContainer, TMPro.TMP_Dropdown, and UnityEngine.XR.Interaction.Toolkit.UI.TrackedDevicePhysicsRaycaster.
IsActive()
virtual bool UnityEngine.EventSystems.UIBehaviour.IsActive () virtual
Returns true if the GameObject and the Component are active.
Referenced by TMPro.TMP_InputField.ActivateInputField(), TMPro.TMP_Dropdown.Hide(), UnityEngine.UI.Mask.MaskEnabled(), UnityEditor.UI.ToggleEditor.OnInspectorGUI(), UnityEngine.UI.Scrollbar.OnMove(), UnityEngine.UI.Scrollbar.OnRectTransformDimensionsChange(), TMPro.TMP_InputField.OnSubmit(), UnityEngine.UI.ContentSizeFitter.SetDirty(), UnityEngine.UI.LayoutGroup.SetDirty(), TMPro.TMP_Dropdown.Show(), and UnityEngine.EventSystems.EventSystem.UpdateModules().
IsDestroyed()
bool UnityEngine.EventSystems.UIBehaviour.IsDestroyed ()
Returns true if the native representation of the behaviour has been destroyed.
When a parent canvas is either enabled, disabled or a nested canvas's OverrideSorting is changed this function is called. You can for example use this to modify objects below a canvas that may depend on a parent canvas - for example, if a canvas is disabled you may want to halt some processing of a UI element.
OnBeforeTransformParentChanged()
virtual void UnityEngine.EventSystems.UIBehaviour.OnBeforeTransformParentChanged () protected virtual
OnCanvasGroupChanged()
virtual void UnityEngine.EventSystems.UIBehaviour.OnCanvasGroupChanged () protected virtual
OnCanvasHierarchyChanged()
virtual void UnityEngine.EventSystems.UIBehaviour.OnCanvasHierarchyChanged () protected virtual
Called when the state of the parent Canvas is changed.
Reimplemented in UnityEngine.EventSystems.BaseRaycaster, and UnityEngine.UI.RectMask2D.
OnDestroy()
virtual void UnityEngine.EventSystems.UIBehaviour.OnDestroy () protected virtual
Reimplemented in UnityEngine.UI.RectMask2D.
OnDidApplyAnimationProperties()
virtual void UnityEngine.EventSystems.UIBehaviour.OnDidApplyAnimationProperties () protected virtual
Reimplemented in UnityEngine.UI.LayoutGroup.
OnDisable()
virtual void UnityEngine.EventSystems.UIBehaviour.OnDisable () protected virtual
Reimplemented in Oculus.Interaction.UnityCanvas.CanvasRenderTexture, TMPro.TextContainer, TMPro.TMP_Dropdown, TMPro.TMP_InputField, UnityEngine.EventSystems.BaseRaycaster, UnityEngine.UI.AspectRatioFitter, UnityEngine.UI.CanvasScaler, UnityEngine.UI.ContentSizeFitter, UnityEngine.UI.LayoutGroup, UnityEngine.UI.Mask, UnityEngine.UI.RectMask2D, and UnityEngine.UI.Scrollbar.
OnEnable()
virtual void UnityEngine.EventSystems.UIBehaviour.OnEnable () protected virtual
Reimplemented in Oculus.Interaction.UnityCanvas.CanvasRenderTexture, TMPro.TextContainer, TMPro.TMP_InputField, UnityEngine.EventSystems.BaseRaycaster, UnityEngine.UI.AspectRatioFitter, UnityEngine.UI.CanvasScaler, UnityEngine.UI.ContentSizeFitter, UnityEngine.UI.LayoutGroup, UnityEngine.UI.Mask, UnityEngine.UI.RectMask2D, UnityEngine.UI.Scrollbar, and UnityEngine.UI.ToggleGroup.
OnRectTransformDimensionsChange()
virtual void UnityEngine.EventSystems.UIBehaviour.OnRectTransformDimensionsChange () protected virtual
This callback is called when the dimensions of an associated RectTransform change. It is always called before Awake, OnEnable, or Start. The call is also made to all child RectTransforms, regardless of whether their dimensions change (which depends on how they are anchored).
Reimplemented in Oculus.Interaction.UnityCanvas.CanvasRenderTexture, TMPro.TextContainer, UnityEngine.UI.AspectRatioFitter, UnityEngine.UI.ContentSizeFitter, UnityEngine.UI.LayoutGroup, and UnityEngine.UI.Scrollbar.
OnTransformParentChanged()
virtual void UnityEngine.EventSystems.UIBehaviour.OnTransformParentChanged () protected virtual
Reimplemented in UnityEngine.EventSystems.BaseRaycaster, UnityEngine.UI.AspectRatioFitter, and UnityEngine.UI.RectMask2D.
Start()
virtual void UnityEngine.EventSystems.UIBehaviour.Start () protected virtual
Reimplemented in Oculus.Interaction.UnityCanvas.CanvasRenderTexture, OVRRaycaster, TMPro.TMP_Dropdown, UnityEngine.UI.AspectRatioFitter, and UnityEngine.UI.ToggleGroup.
The documentation for this class was generated from the following file:
C:/Users/Lykos/Desktop/Projects/Capstone/VRGames/Library/PackageCache/com.unity.ugui@1.0.0/Runtime/EventSystem/UIBehaviour.cs