VRCapstoneGames: UnityEngine.ProBuilder.AssetIdRemapUtility.AssetId Class Reference
UnityEngine.ProBuilder.AssetIdRemapUtility.AssetId Class Reference
Public Member Functions
AssetId ()
AssetId (AssetId other)
AssetId (UObject obj, string file, string guid, string localPath=null)
bool Equals (AssetId other)
override bool Equals (object obj)
override int GetHashCode ()
void Clear ()
void SetPathRelativeTo (string dir)
bool IsMonoScript ()
bool AssetEquals (AssetId other)
bool ExistsInProject ()
Does the object this id reference exist in the project?
Static Public Member Functions
static bool IsValid (AssetId id)
Properties
string localPath [get]
A path relative to the root asset directory (ex, ProBuilder/About/Hello.cs). Stored per-asset because the path may change between upgrades. A single file name is stored at the tuple level.
string name [get]
string type [get]
Return the backing type of this asset. If the asset is a MonoScript, the associated mono class will be returned. To get the Unity asset type use assetType.
string assetType [get]
string fileId [get]
File Ids associated with this asset.
string guid [get]
Asset GUID.
Constructor & Destructor Documentation
AssetId() [1/3]
UnityEngine.ProBuilder.AssetIdRemapUtility.AssetId.AssetId ()
Referenced by UnityEngine.ProBuilder.AssetIdRemapUtility.AssetId.Equals().
AssetId() [2/3]
UnityEngine.ProBuilder.AssetIdRemapUtility.AssetId.AssetId (AssetId other)
AssetId() [3/3]
UnityEngine.ProBuilder.AssetIdRemapUtility.AssetId.AssetId (UObject obj, string file, string guid, string localPath = null)
Member Function Documentation
AssetEquals()
bool UnityEngine.ProBuilder.AssetIdRemapUtility.AssetId.AssetEquals (AssetId other)
Referenced by UnityEngine.ProBuilder.AssetIdRemapUtility.AssetIdentifierTuple.AssetEquals().
Clear()
void UnityEngine.ProBuilder.AssetIdRemapUtility.AssetId.Clear ()
Referenced by UnityEngine.ProBuilder.AssetIdRemapUtility.AssetId.AssetId().
Equals() [1/2]
bool UnityEngine.ProBuilder.AssetIdRemapUtility.AssetId.Equals (AssetId other)
Referenced by UnityEngine.ProBuilder.AssetIdRemapUtility.AssetId.Equals().
Equals() [2/2]
override bool UnityEngine.ProBuilder.AssetIdRemapUtility.AssetId.Equals (object obj)
ExistsInProject()
bool UnityEngine.ProBuilder.AssetIdRemapUtility.AssetId.ExistsInProject ()
Does the object this id reference exist in the project?
Returns
GetHashCode()
override int UnityEngine.ProBuilder.AssetIdRemapUtility.AssetId.GetHashCode ()
IsMonoScript()
bool UnityEngine.ProBuilder.AssetIdRemapUtility.AssetId.IsMonoScript ()
IsValid()
static bool UnityEngine.ProBuilder.AssetIdRemapUtility.AssetId.IsValid (AssetId id) static
Referenced by UnityEngine.ProBuilder.AssetIdRemapUtility.AssetIdentifierTuple.AssetEquals(), UnityEngine.ProBuilder.AssetIdRemapUtility.AssetIdRemapObject.Clear(), and UnityEngine.ProBuilder.AssetIdRemapUtility.AssetIdRemapObject.Merge().
SetPathRelativeTo()
void UnityEngine.ProBuilder.AssetIdRemapUtility.AssetId.SetPathRelativeTo (string dir)
Property Documentation
assetType
string UnityEngine.ProBuilder.AssetIdRemapUtility.AssetId.assetType get
Referenced by UnityEngine.ProBuilder.AssetIdRemapUtility.AssetId.AssetEquals().
fileId
string UnityEngine.ProBuilder.AssetIdRemapUtility.AssetId.fileId get
File Ids associated with this asset.
guid
string UnityEngine.ProBuilder.AssetIdRemapUtility.AssetId.guid get
Asset GUID.
Referenced by UnityEngine.ProBuilder.AssetIdRemapUtility.AssetId.AssetId(), and UnityEngine.ProBuilder.AssetIdRemapUtility.AssetId.IsMonoScript().
localPath
string UnityEngine.ProBuilder.AssetIdRemapUtility.AssetId.localPath get
A path relative to the root asset directory (ex, ProBuilder/About/Hello.cs). Stored per-asset because the path may change between upgrades. A single file name is stored at the tuple level.
Referenced by UnityEngine.ProBuilder.AssetIdRemapUtility.AssetId.AssetEquals(), and UnityEngine.ProBuilder.AssetIdRemapUtility.AssetId.AssetId().
name
string UnityEngine.ProBuilder.AssetIdRemapUtility.AssetId.name get
type
string UnityEngine.ProBuilder.AssetIdRemapUtility.AssetId.type get
Return the backing type of this asset. If the asset is a MonoScript, the associated mono class will be returned. To get the Unity asset type use assetType.
The documentation for this class was generated from the following file:
C:/Users/Lykos/Desktop/Projects/Capstone/VRGames/Library/PackageCache/com.unity.probuilder@5.0.6/AssetIdRemapUtility/Editor/AssetId.cs