VRCapstoneGames: UnityEngine.UI.Mask Class Reference
UnityEngine.UI.Mask Class Reference
A component for masking children elements.
Public Member Functions
virtual bool MaskEnabled ()
virtual void OnSiblingGraphicEnabledDisabled ()
virtual bool IsRaycastLocationValid (Vector2 sp, Camera eventCamera)
virtual Material GetModifiedMaterial (Material baseMaterial)
Stencil calculation time!
Public Member Functions inherited from UnityEngine.EventSystems.UIBehaviour
virtual bool IsActive ()
Returns true if the GameObject and the Component are active.
bool IsDestroyed ()
Returns true if the native representation of the behaviour has been destroyed.
Protected Member Functions
Mask ()
override void OnEnable ()
override void OnDisable ()
Protected Member Functions inherited from UnityEngine.EventSystems.UIBehaviour
virtual void Awake ()
virtual void Start ()
virtual void OnDestroy ()
virtual void OnRectTransformDimensionsChange ()
This callback is called when the dimensions of an associated RectTransform change. It is always called before Awake, OnEnable, or Start. The call is also made to all child RectTransforms, regardless of whether their dimensions change (which depends on how they are anchored).
virtual void OnBeforeTransformParentChanged ()
virtual void OnTransformParentChanged ()
virtual void OnDidApplyAnimationProperties ()
virtual void OnCanvasGroupChanged ()
virtual void OnCanvasHierarchyChanged ()
Called when the state of the parent Canvas is changed.
Properties
RectTransform rectTransform [get]
bool showMaskGraphic [get, set]
Show the graphic that is associated with the Mask render area.
Graphic graphic [get]
The graphic associated with the Mask.
Detailed Description
A component for masking children elements.
By using this element any children elements that have masking enabled will mask where a sibling Graphic would write 0 to the stencil buffer.
Constructor & Destructor Documentation
Mask()
UnityEngine.UI.Mask.Mask () protected
Member Function Documentation
GetModifiedMaterial()
virtual Material UnityEngine.UI.Mask.GetModifiedMaterial (Material baseMaterial) virtual
Stencil calculation time!
Implements UnityEngine.UI.IMaterialModifier.
Referenced by Graphics.MaskTests.GetModifiedMaterialReturnsDesiredMaterialWithMultipleMasks(), Graphics.MaskTests.GetModifiedMaterialReturnsDesiredMaterialWithSingleMask(), Graphics.MaskTests.GetModifiedMaterialReturnsOriginalMaterialWhenDepthIsEightOrMore(), and Graphics.MaskTests.GetModifiedMaterialReturnsOriginalMaterialWhenNoGraphicComponentIsAttached().
IsRaycastLocationValid()
virtual bool UnityEngine.UI.Mask.IsRaycastLocationValid (Vector2 sp, Camera eventCamera) virtual
MaskEnabled()
virtual bool UnityEngine.UI.Mask.MaskEnabled () virtual
Referenced by UnityEngine.UI.Mask.GetModifiedMaterial().
OnDisable()
override void UnityEngine.UI.Mask.OnDisable () protected virtual
Reimplemented from UnityEngine.EventSystems.UIBehaviour.
OnEnable()
override void UnityEngine.UI.Mask.OnEnable () protected virtual
Reimplemented from UnityEngine.EventSystems.UIBehaviour.
OnSiblingGraphicEnabledDisabled()
virtual void UnityEngine.UI.Mask.OnSiblingGraphicEnabledDisabled () virtual
Property Documentation
graphic
Graphic UnityEngine.UI.Mask.graphic get
The graphic associated with the Mask.
Referenced by UnityEngine.UI.Mask.GetModifiedMaterial(), UnityEngine.UI.Mask.MaskEnabled(), UnityEngine.UI.Mask.OnDisable(), and UnityEngine.UI.Mask.OnEnable().
rectTransform
RectTransform UnityEngine.UI.Mask.rectTransform get
Referenced by UnityEngine.UI.Mask.IsRaycastLocationValid().
showMaskGraphic
bool UnityEngine.UI.Mask.showMaskGraphic get set
Show the graphic that is associated with the Mask render area.
The documentation for this class was generated from the following file:
C:/Users/Lykos/Desktop/Projects/Capstone/VRGames/Library/PackageCache/com.unity.ugui@1.0.0/Runtime/UI/Core/Mask.cs