VRCapstoneGames: Unity.XR.CoreUtils.Editor.XROriginEditor Class Reference
Unity.XR.CoreUtils.Editor.XROriginEditor Class Reference
Custom editor for an XROrigin.
Classes
class Contents
Contents of GUI elements used by this editor.
Public Member Functions
override void OnInspectorGUI ()
Protected Member Functions
virtual void OnEnable ()
This function is called when the object becomes enabled and active.
virtual void DrawInspector ()
This method is automatically called by OnInspectorGUI to draw the custom inspector. Override this method to customize the inspector as a whole.
virtual void InitializeKnownSerializedPropertyNames ()
This method is automatically called by OnInspectorGUI to initialize knownSerializedPropertyNames if necessary. This is used together with DrawDerivedProperties to draw all unknown serialized fields from derived classes.
virtual List< string > GetDerivedSerializedPropertyNames ()
Returns a list containing the SerializeField names of all SerializedProperty fields defined in the Editor (including derived types).
virtual void DrawDerivedProperties ()
This method is automatically called by DrawInspector to draw the property fields of derived classes that are not explicitly defined in the Editor.
virtual void DrawScript ()
Draw the standard read-only Script property.
virtual void DrawBeforeProperties ()
This method is automatically called by DrawInspector to draw the section of the custom inspector before DrawProperties. By default, this draws the read-only Script property.
virtual void DrawProperties ()
This method is automatically called by DrawInspector to draw the property fields. Override this method to customize the properties shown in the Inspector. This is typically the method overridden when a derived behavior adds additional serialized properties that should be displayed in the Inspector.
void DrawCurrentTrackingOriginMode ()
Draw the current Tracking Origin Mode while the application is playing.
Protected Attributes
SerializedProperty m_OriginBaseGameObject
SerializedProperty of the SerializeField backing XROrigin.Origin.
SerializedProperty m_CameraFloorOffsetObject
SerializedProperty of the SerializeField backing XROrigin.CameraFloorOffsetObject.
SerializedProperty m_Camera
SerializedProperty of the SerializeField backing XROrigin.Camera.
SerializedProperty m_TrackingOriginMode
SerializedProperty of the SerializeField backing XROrigin.CurrentTrackingOriginMode.
SerializedProperty m_RequestedTrackingOriginMode
SerializedProperty of the SerializeField backing XROrigin.RequestedTrackingOriginMode.
SerializedProperty m_CameraYOffset
SerializedProperty of the SerializeField backing XROrigin.CameraYOffset.
Properties
string[] knownSerializedPropertyNames [get, set]
The SerializeField names of all SerializedProperty fields defined in the Editor (including derived types).
Detailed Description
Custom editor for an XROrigin.
Member Function Documentation
DrawBeforeProperties()
virtual void Unity.XR.CoreUtils.Editor.XROriginEditor.DrawBeforeProperties () protected virtual
This method is automatically called by DrawInspector to draw the section of the custom inspector before DrawProperties. By default, this draws the read-only Script property.
Referenced by Unity.XR.CoreUtils.Editor.XROriginEditor.DrawInspector().
DrawCurrentTrackingOriginMode()
void Unity.XR.CoreUtils.Editor.XROriginEditor.DrawCurrentTrackingOriginMode () protected
Draw the current Tracking Origin Mode while the application is playing.
See also
XROrigin.CurrentTrackingOriginMode
Referenced by Unity.XR.CoreUtils.Editor.XROriginEditor.DrawProperties().
DrawDerivedProperties()
virtual void Unity.XR.CoreUtils.Editor.XROriginEditor.DrawDerivedProperties () protected virtual
This method is automatically called by DrawInspector to draw the property fields of derived classes that are not explicitly defined in the Editor.
This method is used to allow users to add a SerializeField to a derived behavior and have it automatically appear in the Inspector while still having the custom Editor apply to that derived class.
When a derived Editor class adds a SerializedProperty, it will no longer automatically be drawn by this method. This is to allow users to customize where the property is drawn in the Inspector window. The derived Editor class does not need to explicitly add the SerializedProperty if the user is fine with the default location of where it will be drawn.
See also
InitializeKnownSerializedPropertyNames
Referenced by Unity.XR.CoreUtils.Editor.XROriginEditor.DrawInspector().
DrawInspector()
virtual void Unity.XR.CoreUtils.Editor.XROriginEditor.DrawInspector () protected virtual
This method is automatically called by OnInspectorGUI to draw the custom inspector. Override this method to customize the inspector as a whole.
See also
DrawBeforeProperties, DrawProperties, DrawDerivedProperties
Referenced by Unity.XR.CoreUtils.Editor.XROriginEditor.OnInspectorGUI().
DrawProperties()
virtual void Unity.XR.CoreUtils.Editor.XROriginEditor.DrawProperties () protected virtual
This method is automatically called by DrawInspector to draw the property fields. Override this method to customize the properties shown in the Inspector. This is typically the method overridden when a derived behavior adds additional serialized properties that should be displayed in the Inspector.
Referenced by Unity.XR.CoreUtils.Editor.XROriginEditor.DrawInspector().
DrawScript()
virtual void Unity.XR.CoreUtils.Editor.XROriginEditor.DrawScript () protected virtual
Draw the standard read-only Script property.
Referenced by Unity.XR.CoreUtils.Editor.XROriginEditor.DrawBeforeProperties().
GetDerivedSerializedPropertyNames()
virtual List< string > Unity.XR.CoreUtils.Editor.XROriginEditor.GetDerivedSerializedPropertyNames () protected virtual
Returns a list containing the SerializeField names of all SerializedProperty fields defined in the Editor (including derived types).
Returns
Returns a list of strings with property names.
Referenced by Unity.XR.CoreUtils.Editor.XROriginEditor.GetDerivedSerializedPropertyNames(), and Unity.XR.CoreUtils.Editor.XROriginEditor.InitializeKnownSerializedPropertyNames().
InitializeKnownSerializedPropertyNames()
virtual void Unity.XR.CoreUtils.Editor.XROriginEditor.InitializeKnownSerializedPropertyNames () protected virtual
This method is automatically called by OnInspectorGUI to initialize knownSerializedPropertyNames if necessary. This is used together with DrawDerivedProperties to draw all unknown serialized fields from derived classes.
See also
DrawDerivedProperties
Referenced by Unity.XR.CoreUtils.Editor.XROriginEditor.OnInspectorGUI().
OnEnable()
virtual void Unity.XR.CoreUtils.Editor.XROriginEditor.OnEnable () protected virtual
This function is called when the object becomes enabled and active.
See also
MonoBehaviour
OnInspectorGUI()
override void Unity.XR.CoreUtils.Editor.XROriginEditor.OnInspectorGUI ()
Member Data Documentation
m_Camera
SerializedProperty Unity.XR.CoreUtils.Editor.XROriginEditor.m_Camera protected
SerializedProperty of the SerializeField backing XROrigin.Camera.
Referenced by Unity.XR.CoreUtils.Editor.XROriginEditor.DrawProperties(), and Unity.XR.CoreUtils.Editor.XROriginEditor.OnEnable().
m_CameraFloorOffsetObject
SerializedProperty Unity.XR.CoreUtils.Editor.XROriginEditor.m_CameraFloorOffsetObject protected
SerializedProperty of the SerializeField backing XROrigin.CameraFloorOffsetObject.
Referenced by Unity.XR.CoreUtils.Editor.XROriginEditor.DrawProperties(), and Unity.XR.CoreUtils.Editor.XROriginEditor.OnEnable().
m_CameraYOffset
SerializedProperty Unity.XR.CoreUtils.Editor.XROriginEditor.m_CameraYOffset protected
SerializedProperty of the SerializeField backing XROrigin.CameraYOffset.
Referenced by Unity.XR.CoreUtils.Editor.XROriginEditor.DrawProperties(), and Unity.XR.CoreUtils.Editor.XROriginEditor.OnEnable().
m_OriginBaseGameObject
SerializedProperty Unity.XR.CoreUtils.Editor.XROriginEditor.m_OriginBaseGameObject protected
SerializedProperty of the SerializeField backing XROrigin.Origin.
Referenced by Unity.XR.CoreUtils.Editor.XROriginEditor.DrawProperties(), and Unity.XR.CoreUtils.Editor.XROriginEditor.OnEnable().
m_RequestedTrackingOriginMode
SerializedProperty Unity.XR.CoreUtils.Editor.XROriginEditor.m_RequestedTrackingOriginMode protected
SerializedProperty of the SerializeField backing XROrigin.RequestedTrackingOriginMode.
Referenced by Unity.XR.CoreUtils.Editor.XROriginEditor.DrawProperties(), and Unity.XR.CoreUtils.Editor.XROriginEditor.OnEnable().
m_TrackingOriginMode
SerializedProperty Unity.XR.CoreUtils.Editor.XROriginEditor.m_TrackingOriginMode protected
SerializedProperty of the SerializeField backing XROrigin.CurrentTrackingOriginMode.
Referenced by Unity.XR.CoreUtils.Editor.XROriginEditor.OnEnable().
Property Documentation
knownSerializedPropertyNames
string [] Unity.XR.CoreUtils.Editor.XROriginEditor.knownSerializedPropertyNames get set protected
The SerializeField names of all SerializedProperty fields defined in the Editor (including derived types).
See also
InitializeKnownSerializedPropertyNames
Referenced by Unity.XR.CoreUtils.Editor.XROriginEditor.DrawDerivedProperties(), and Unity.XR.CoreUtils.Editor.XROriginEditor.InitializeKnownSerializedPropertyNames().
The documentation for this class was generated from the following file:
C:/Users/Lykos/Desktop/Projects/Capstone/VRGames/Library/PackageCache/com.unity.xr.core-utils@2.0.0/Editor/XROriginEditor.cs