VRCapstoneGames: Oculus.Interaction.ControllerOffset Class Reference
Oculus.Interaction.ControllerOffset Class Reference
Public Member Functions
void GetOffset (ref Pose pose)
void GetWorldPose (ref Pose pose)
void InjectController (IController controller)
void InjectOffset (Vector3 offset)
void InjectRotation (Quaternion rotation)
void InjectAllControllerOffset (IController controller, Vector3 offset, Quaternion rotation)
Protected Member Functions
virtual void Awake ()
virtual void Start ()
virtual void OnEnable ()
virtual void OnDisable ()
Protected Attributes
bool _started = false
Properties
IController Controller [get]
Member Function Documentation
Awake()
virtual void Oculus.Interaction.ControllerOffset.Awake () protected virtual
GetOffset()
void Oculus.Interaction.ControllerOffset.GetOffset (ref Pose pose)
GetWorldPose()
void Oculus.Interaction.ControllerOffset.GetWorldPose (ref Pose pose)
InjectAllControllerOffset()
void Oculus.Interaction.ControllerOffset.InjectAllControllerOffset (IController controller, Vector3 offset, Quaternion rotation)
InjectController()
void Oculus.Interaction.ControllerOffset.InjectController (IController controller)
Referenced by Oculus.Interaction.ControllerOffset.InjectAllControllerOffset().
InjectOffset()
void Oculus.Interaction.ControllerOffset.InjectOffset (Vector3 offset)
Referenced by Oculus.Interaction.ControllerOffset.InjectAllControllerOffset().
InjectRotation()
void Oculus.Interaction.ControllerOffset.InjectRotation (Quaternion rotation)
Referenced by Oculus.Interaction.ControllerOffset.InjectAllControllerOffset().
OnDisable()
virtual void Oculus.Interaction.ControllerOffset.OnDisable () protected virtual
OnEnable()
virtual void Oculus.Interaction.ControllerOffset.OnEnable () protected virtual
Start()
virtual void Oculus.Interaction.ControllerOffset.Start () protected virtual
Member Data Documentation
_started
bool Oculus.Interaction.ControllerOffset._started = false protected
Referenced by Oculus.Interaction.ControllerOffset.OnDisable(), Oculus.Interaction.ControllerOffset.OnEnable(), and Oculus.Interaction.ControllerOffset.Start().
Property Documentation
Controller
IController Oculus.Interaction.ControllerOffset.Controller get
The documentation for this class was generated from the following file:
C:/Users/Lykos/Desktop/Projects/Capstone/VRGames/Assets/ThirdParty/Oculus/Interaction/Runtime/Scripts/Selection/Controllers/ControllerOffset.cs