VRGames: UnityEngine.InputSystem.InputActionAsset Class Reference
UnityEngine.InputSystem.InputActionAsset Class Reference
An asset that contains action maps and control schemes.
Classes
struct ReadFileJson
struct WriteFileJson
Public Member Functions
string ToJson ()
Return a JSON representation of the asset.
void LoadFromJson (string json)
Replace the contents of the asset with the data in the given JSON string.
InputAction FindAction (string actionNameOrId, bool throwIfNotFound=false)
Find an InputAction by its name in one of the InputActionMaps in the asset.
int FindBinding (InputBinding mask, out InputAction action)
Find the index of the first binding that matches the given mask.
Parameters
mask A binding. See InputBinding.Matches for details.
action Receives the action on which the binding was found. If none was found, will be set to null.
Returns
Index into InputAction.bindings of action of the binding that matches mask . If no binding matches, will return -1.
For details about matching bindings by a mask, see InputBinding.Matches.
var index = playerInput.actions.FindBinding(
    new InputBinding { path = "<Gamepad>/buttonSouth" },
    out var action);
if (index != -1)
    Debug.Log($"The A button is bound to {action}");
InputActionMap FindActionMap (string nameOrId, bool throwIfNotFound=false)
Find an InputActionMap in the asset by its name or ID.
InputActionMap FindActionMap (Guid id)
Find an InputActionMap in the asset by its ID.
InputAction FindAction (Guid guid)
Find an action by its ID (see InputAction.id).
int FindControlSchemeIndex (string name)
Find the control scheme with the given name and return its index in controlSchemes.
InputControlScheme? FindControlScheme (string name)
Find the control scheme with the given name and return it.
bool IsUsableWithDevice (InputDevice device)
Return true if the asset contains bindings (in any of its action maps) that are usable with the given device .
void Enable ()
Enable all action maps in the asset.
void Disable ()
Disable all action maps in the asset.
bool Contains (InputAction action)
Return true if the given action is part of the asset.
IEnumerator< InputAction > GetEnumerator ()
Enumerate all actions in the asset.
Static Public Member Functions
static InputActionAsset FromJson (string json)
Replace the contents of the asset with the data in the given JSON string.
Static Public Attributes
const string Extension = "inputactions"
File extension (without the dot) for InputActionAssets in JSON format.
Properties
bool enabled [get]
True if any action in the asset is currently enabled.
ReadOnlyArray< InputActionMap > actionMaps [get]
List of action maps defined in the asset.
ReadOnlyArray< InputControlScheme > controlSchemes [get]
List of control schemes defined in the asset.
IEnumerable< InputBinding > bindings [get]
Iterate over all bindings in the asset.
InputBinding? bindingMask [get, set]
Binding mask to apply to all action maps and actions in the asset.
ReadOnlyArray< InputDevice >? devices [get, set]
Set of devices that bindings in the asset can bind to.
InputAction this[string actionNameOrId] [get]
Look up an action by name or ID.
Properties inherited from UnityEngine.InputSystem.IInputActionCollection2
Properties inherited from UnityEngine.InputSystem.IInputActionCollection
Detailed Description
An asset that contains action maps and control schemes.
InputActionAssets can be created in code but are usually stored in JSON format on disk with the ".inputactions" extension. Unity imports them with a custom importer.
To create an InputActionAsset in code, use the Singleton API and populate the asset with the methods found in InputActionSetupExtensions. Alternatively, you can use FromJson to load an InputActionAsset directly from a string in JSON format.
// Create and configure an asset in code.
var asset1 = ScriptableObject.CreateInstance<InputActionAsset>();
var actionMap1 = asset1.AddActionMap("map1");
action1Map.AddAction("action1", binding: "<Keyboard>/space");
If you use the API to modify an InputActionAsset while in Play mode, it does not survive the transition back to Edit Mode. Unity tracks and reloads modified assets from disk when exiting Play mode. This is done so that you can realistically test the input related functionality of your application i.e. control rebinding etc, without inadvertently changing the input asset.
Each asset can contain arbitrary many action maps that you can enable and disable individually (see InputActionMap.Enable and InputActionMap.Disable) or in bulk (see Enable and Disable). The name of each action map must be unique. The list of action maps can be queried from actionMaps.
InputActionAssets can only define InputControlSchemes. They can be added to an asset with InputActionSetupExtensions.AddControlScheme(InputActionAsset,string) and can be queried from controlSchemes.
Be aware that input action assets do not separate between static (configuration) data and dynamic (instance) data. For audio, for example, AudioClip represents the static, shared data portion of audio playback whereas AudioSource"</c> represents the dynamic, per-instance audio playback portion (referencing the clip through <c>AudioSource.clip</c>). For input, such a split is less beneficial as the same input is generally not exercised multiple times in parallel. Keeping both static and dynamic data together simplifies using the system. However, there are scenarios where you indeed want to take the same input action and exercise it multiple times in parallel. A prominent example of such a use case is local multiplayer where each player gets the same set of actions but is controlling them with a different device (or devices) each. This is easily achieved by simply using <c>UnityEngine.Object.Instantiate</c> to instantiate the input action asset multiple times. <see cref="PlayerInput"/> will automatically do so in its internals.
Note also that all action maps in an asset share binding state. This means that if one map in an asset has to resolve its bindings, all maps in the asset have to.
Member Function Documentation
Contains()
bool UnityEngine.InputSystem.InputActionAsset.Contains (InputAction action)
Return true if the given action is part of the asset.
Parameters
action An action. Can be null.
Returns
True if the given action is part of the asset, false otherwise.
Implements UnityEngine.InputSystem.IInputActionCollection.
Referenced by UnityEngine.InputSystem.DefaultInputActions.Contains(), UnityEngine.InputSystem.Samples.InGameHints.InGameHintsActions.Contains(), and SimpleControls.Contains().
Disable()
void UnityEngine.InputSystem.InputActionAsset.Disable ()
Disable all action maps in the asset.
This method is equivalent to calling InputActionMap.Disable on all maps in actionMaps.
Implements UnityEngine.InputSystem.IInputActionCollection.
Referenced by UnityEngine.InputSystem.DefaultInputActions.Disable(), UnityEngine.InputSystem.Samples.InGameHints.InGameHintsActions.Disable(), and SimpleControls.Disable().
Enable()
void UnityEngine.InputSystem.InputActionAsset.Enable ()
Enable all action maps in the asset.
This method is equivalent to calling InputActionMap.Enable on all maps in actionMaps.
Implements UnityEngine.InputSystem.IInputActionCollection.
Referenced by UnityEngine.InputSystem.DefaultInputActions.Enable(), UnityEngine.InputSystem.Samples.InGameHints.InGameHintsActions.Enable(), and SimpleControls.Enable().
FindAction() [1/2]
InputAction UnityEngine.InputSystem.InputActionAsset.FindAction (Guid guid)
Find an action by its ID (see InputAction.id).
Parameters
guid ID of the action to look for.
Returns
The action in the asset with the given ID or null if no action in the asset has the given ID.
FindAction() [2/2]
InputAction UnityEngine.InputSystem.InputActionAsset.FindAction (string actionNameOrId, bool throwIfNotFound = false)
Find an InputAction by its name in one of the InputActionMaps in the asset.
Parameters
actionNameOrId Name of the action as either a "map/action" combination (e.g. "gameplay/fire") or a simple name. In the former case, the name is split at the '/' slash and the first part is used to find a map with that name and the second part is used to find an action with that name inside the map. In the latter case, all maps are searched in order and the first action that has the given name in any of the maps is returned. Note that name comparisons are case-insensitive.
Alternatively, the given string can be a GUID as given by InputAction.id.
Parameters
throwIfNotFound If true, instead of returning null when the action cannot be found, throw ArgumentException.
Returns
The action with the corresponding name or null if no matching action could be found.
Note that no lookup structures are used internally to speed the operation up. Instead, the search is done linearly. For repeated access of an action, it is thus generally best to look up actions once ahead of time and cache the result.
If multiple actions have the same name and actionNameOrId is not an ID and not an action name qualified by a map name (that is, in the form of "mapName/actionName"), the action that is returned will be from the first map in actionMaps that has an action with the given name. An exception is if, of the multiple actions with the same name, some are enabled and some are disabled. In this case, the first action that is enabled is returned.
var asset = ScriptableObject.CreateInstance<InputActionAsset>();
var map1 = new InputActionMap("map1");
var map2 = new InputActionMap("map2");
asset.AddActionMap(map1);
asset.AddActionMap(map2);
var action1 = map1.AddAction("action1");
var action2 = map1.AddAction("action2");
var action3 = map2.AddAction("action3");
// Search all maps in the asset for any action that has the given name.
asset.FindAction("action1") // Returns action1.
asset.FindAction("action2") // Returns action2
asset.FindAction("action3") // Returns action3.
// Search for a specific action in a specific map.
asset.FindAction("map1/action1") // Returns action1.
asset.FindAction("map2/action2") // Returns action2.
asset.FindAction("map3/action3") // Returns action3.
// Search by unique action ID.
asset.FindAction(action1.id.ToString()) // Returns action1.
asset.FindAction(action2.id.ToString()) // Returns action2.
asset.FindAction(action3.id.ToString()) // Returns action3.
Exceptions
ArgumentNullException actionNameOrId is null.
ArgumentException Thrown if throwIfNotFound is true and the action could not be found. -Or- If actionNameOrId contains a slash but is missing either the action or the map name.
Implements UnityEngine.InputSystem.IInputActionCollection2.
Referenced by UnityEngine.InputSystem.DefaultInputActions.FindAction(), UnityEngine.InputSystem.Samples.InGameHints.InGameHintsActions.FindAction(), and SimpleControls.FindAction().
FindActionMap() [1/2]
InputActionMap UnityEngine.InputSystem.InputActionAsset.FindActionMap (Guid id)
Find an InputActionMap in the asset by its ID.
Parameters
id ID (see InputActionMap.id) of the action map to look for.
Returns
The InputActionMap with ID matching id or null if no map in the asset has the given ID.
See also
actionMaps, FindActionMap
FindActionMap() [2/2]
InputActionMap UnityEngine.InputSystem.InputActionAsset.FindActionMap (string nameOrId, bool throwIfNotFound = false)
Find an InputActionMap in the asset by its name or ID.
Parameters
nameOrId Name or ID (see InputActionMap.id) of the action map to look for. Matching is case-insensitive.
throwIfNotFound If true, instead of returning null, throw ArgumentException.
Returns
The InputActionMap with a name or ID matching nameOrId or null if no matching map could be found.
Exceptions
ArgumentNullException nameOrId is null.
ArgumentException If throwIfNotFound is true, thrown if the action map cannot be found.
See also
actionMaps, FindActionMap(System.Guid)
Referenced by UnityEngine.InputSystem.DefaultInputActions.DefaultInputActions(), UnityEngine.InputSystem.Samples.InGameHints.InGameHintsActions.InGameHintsActions(), UnityEngine.InputSystem.InputActionReference.Set(), SimpleControls.SimpleControls(), and UnityEngine.InputSystem.PlayerInput.SwitchCurrentActionMap().
FindBinding()
int UnityEngine.InputSystem.InputActionAsset.FindBinding (InputBinding mask, out InputAction action)
Find the index of the first binding that matches the given mask.
Parameters
mask A binding. See InputBinding.Matches for details.
action Receives the action on which the binding was found. If none was found, will be set to null.
Returns
Index into InputAction.bindings of action of the binding that matches mask . If no binding matches, will return -1.
For details about matching bindings by a mask, see InputBinding.Matches.
var index = playerInput.actions.FindBinding(
    new InputBinding { path = "<Gamepad>/buttonSouth" },
    out var action);
if (index != -1)
    Debug.Log($"The A button is bound to {action}");
Implements UnityEngine.InputSystem.IInputActionCollection2.
Referenced by UnityEngine.InputSystem.DefaultInputActions.FindBinding(), UnityEngine.InputSystem.Samples.InGameHints.InGameHintsActions.FindBinding(), and SimpleControls.FindBinding().
FindControlScheme()
InputControlScheme? UnityEngine.InputSystem.InputActionAsset.FindControlScheme (string name)
Find the control scheme with the given name and return it.
Parameters
name Name of the control scheme. Matching is case-insensitive.
Returns
The control scheme with the given name or null if no scheme with the given name could be found in the asset.
Exceptions
ArgumentNullException name is null or empty.
FindControlSchemeIndex()
int UnityEngine.InputSystem.InputActionAsset.FindControlSchemeIndex (string name)
Find the control scheme with the given name and return its index in controlSchemes.
Parameters
name Name of the control scheme. Matching is case-insensitive.
Returns
The index of the given control scheme or -1 if no control scheme with the given name could be found.
Exceptions
ArgumentNullException name is null or empty.
Referenced by UnityEngine.InputSystem.InputActionAsset.FindControlScheme().
FromJson()
static InputActionAsset UnityEngine.InputSystem.InputActionAsset.FromJson (string json) static
Replace the contents of the asset with the data in the given JSON string.
Parameters
json JSON contents of an .inputactions asset.
Returns
The InputActionAsset instance created from the given JSON string.
.inputactions assets are stored in JSON format. This method allows turning the JSON source text of such an asset into a new InputActionMap instance.
Be aware that the format used by this method is different than what you get if you call JsonUtility.ToJson on an InputActionAsset instance. In other words, the JSON format is not identical to the Unity serialized object representation of the asset.
var asset = InputActionAsset.FromJson(@"
{
    ""maps"" : [
        {
            ""name"" : ""gameplay"",
            ""actions"" : [
                { ""name"" : ""fire"", ""type"" : ""button"" },
                { ""name"" : ""look"", ""type"" : ""value"" },
                { ""name"" : ""move"", ""type"" : ""value"" }
            ],
            ""bindings"" : [
                { ""path"" : ""<Gamepad>/buttonSouth"", ""action"" : ""fire"", ""groups"" : ""Gamepad"" },
                { ""path"" : ""<Gamepad>/leftTrigger"", ""action"" : ""fire"", ""groups"" : ""Gamepad"" },
                { ""path"" : ""<Gamepad>/leftStick"", ""action"" : ""move"", ""groups"" : ""Gamepad"" },
                { ""path"" : ""<Gamepad>/rightStick"", ""action"" : ""look"", ""groups"" : ""Gamepad"" },
                { ""path"" : ""dpad"", ""action"" : ""move"", ""groups"" : ""Gamepad"", ""isComposite"" : true },
                { ""path"" : ""<Keyboard>/a"", ""name"" : ""left"", ""action"" : ""move"", ""groups"" : ""Keyboard&amp;Mouse"", ""isPartOfComposite"" : true },
                { ""path"" : ""<Keyboard>/d"", ""name"" : ""right"", ""action"" : ""move"", ""groups"" : ""Keyboard&amp;Mouse"", ""isPartOfComposite"" : true },
                { ""path"" : ""<Keyboard>/w"", ""name"" : ""up"", ""action"" : ""move"", ""groups"" : ""Keyboard&amp;Mouse"", ""isPartOfComposite"" : true },
                { ""path"" : ""<Keyboard>/s"", ""name"" : ""down"", ""action"" : ""move"", ""groups"" : ""Keyboard&amp;Mouse"", ""isPartOfComposite"" : true },
                { ""path"" : ""<Mouse>/delta"", ""action"" : ""look"", ""groups"" : ""Keyboard&amp;Mouse"" },
                { ""path"" : ""<Mouse>/leftButton"", ""action"" : ""fire"", ""groups"" : ""Keyboard&amp;Mouse"" }
            ]
        },
        {
            ""name"" : ""ui"",
            ""actions"" : [
                { ""name"" : ""navigate"" }
            ],
            ""bindings"" : [
                { ""path"" : ""<Gamepad>/dpad"", ""action"" : ""navigate"", ""groups"" : ""Gamepad"" }
            ]
        }
    ],
    ""controlSchemes"" : [
        {
            ""name"" : ""Gamepad"",
            ""bindingGroup"" : ""Gamepad"",
            ""devices"" : [
                { ""devicePath"" : ""<Gamepad>"" }
            ]
        },
        {
            ""name"" : ""Keyboard&amp;Mouse"",
            ""bindingGroup"" : ""Keyboard&amp;Mouse"",
            ""devices"" : [
                { ""devicePath"" : ""<Keyboard>"" },
                { ""devicePath"" : ""<Mouse>"" }
            ]
        }
    ]
}");
Exceptions
ArgumentNullException json is null or empty.
See also
LoadFromJson, ToJson
Referenced by UnityEngine.InputSystem.DefaultInputActions.DefaultInputActions(), UnityEngine.InputSystem.Samples.InGameHints.InGameHintsActions.InGameHintsActions(), and SimpleControls.SimpleControls().
GetEnumerator()
IEnumerator< InputAction > UnityEngine.InputSystem.InputActionAsset.GetEnumerator ()
Enumerate all actions in the asset.
Returns
Enumerate over all actions in the asset.
Actions will be enumerated one action map in actionMaps after the other. The actions from each map will be yielded in turn.
This method will allocate GC heap memory.
Referenced by UnityEngine.InputSystem.DefaultInputActions.GetEnumerator(), UnityEngine.InputSystem.Samples.InGameHints.InGameHintsActions.GetEnumerator(), and SimpleControls.GetEnumerator().
IsUsableWithDevice()
bool UnityEngine.InputSystem.InputActionAsset.IsUsableWithDevice (InputDevice device)
Return true if the asset contains bindings (in any of its action maps) that are usable with the given device .
Parameters
device An arbitrary input device.
Returns
Exceptions
ArgumentNullException device is null.
// Find out if the actions of the given PlayerInput can be used with
// a gamepad.
if (playerInput.actions.IsUsableWithDevice(Gamepad.all[0]))
    /* ... *&zwj;/;
See also
InputActionMap.IsUsableWithDevice, InputControlScheme.SupportsDevice
Referenced by UnityEngine.InputSystem.InputActionAsset.IsUsableWithDevice().
LoadFromJson()
void UnityEngine.InputSystem.InputActionAsset.LoadFromJson (string json)
Replace the contents of the asset with the data in the given JSON string.
Parameters
json JSON contents of an .inputactions asset.
.inputactions assets are stored in JSON format. This method allows reading the JSON source text of such an asset into an existing InputActionMap instance.
var asset = ScriptableObject.CreateInstance<InputActionAsset>();
asset.LoadFromJson(@"
{
    ""maps"" : [
        {
            ""name"" : ""gameplay"",
            ""actions"" : [
                { ""name"" : ""fire"", ""type"" : ""button"" },
                { ""name"" : ""look"", ""type"" : ""value"" },
                { ""name"" : ""move"", ""type"" : ""value"" }
            ],
            ""bindings"" : [
                { ""path"" : ""<Gamepad>/buttonSouth"", ""action"" : ""fire"", ""groups"" : ""Gamepad"" },
                { ""path"" : ""<Gamepad>/leftTrigger"", ""action"" : ""fire"", ""groups"" : ""Gamepad"" },
                { ""path"" : ""<Gamepad>/leftStick"", ""action"" : ""move"", ""groups"" : ""Gamepad"" },
                { ""path"" : ""<Gamepad>/rightStick"", ""action"" : ""look"", ""groups"" : ""Gamepad"" },
                { ""path"" : ""dpad"", ""action"" : ""move"", ""groups"" : ""Gamepad"", ""isComposite"" : true },
                { ""path"" : ""<Keyboard>/a"", ""name"" : ""left"", ""action"" : ""move"", ""groups"" : ""Keyboard&amp;Mouse"", ""isPartOfComposite"" : true },
                { ""path"" : ""<Keyboard>/d"", ""name"" : ""right"", ""action"" : ""move"", ""groups"" : ""Keyboard&amp;Mouse"", ""isPartOfComposite"" : true },
                { ""path"" : ""<Keyboard>/w"", ""name"" : ""up"", ""action"" : ""move"", ""groups"" : ""Keyboard&amp;Mouse"", ""isPartOfComposite"" : true },
                { ""path"" : ""<Keyboard>/s"", ""name"" : ""down"", ""action"" : ""move"", ""groups"" : ""Keyboard&amp;Mouse"", ""isPartOfComposite"" : true },
                { ""path"" : ""<Mouse>/delta"", ""action"" : ""look"", ""groups"" : ""Keyboard&amp;Mouse"" },
                { ""path"" : ""<Mouse>/leftButton"", ""action"" : ""fire"", ""groups"" : ""Keyboard&amp;Mouse"" }
            ]
        },
        {
            ""name"" : ""ui"",
            ""actions"" : [
                { ""name"" : ""navigate"" }
            ],
            ""bindings"" : [
                { ""path"" : ""<Gamepad>/dpad"", ""action"" : ""navigate"", ""groups"" : ""Gamepad"" }
            ]
        }
    ],
    ""controlSchemes"" : [
        {
            ""name"" : ""Gamepad"",
            ""bindingGroup"" : ""Gamepad"",
            ""devices"" : [
                { ""devicePath"" : ""<Gamepad>"" }
            ]
        },
        {
            ""name"" : ""Keyboard&amp;Mouse"",
            ""bindingGroup"" : ""Keyboard&amp;Mouse"",
            ""devices"" : [
                { ""devicePath"" : ""<Keyboard>"" },
                { ""devicePath"" : ""<Mouse>"" }
            ]
        }
    ]
}");
Exceptions
ArgumentNullException json is null or empty.
See also
FromJson, ToJson
ToJson()
string UnityEngine.InputSystem.InputActionAsset.ToJson ()
Return a JSON representation of the asset.
Returns
A string in JSON format that represents the static/configuration data present in the asset.
This will not save dynamic execution state such as callbacks installed on actions or enabled/disabled states of individual maps and actions.
Use LoadFromJson to deserialize the JSON data back into an InputActionAsset.
Be aware that the format used by this method is different than what you get if you call JsonUtility.ToJson on an InputActionAsset instance. In other words, the JSON format is not identical to the Unity serialized object representation of the asset.
See also
FromJson
Member Data Documentation
Extension
const string UnityEngine.InputSystem.InputActionAsset.Extension = "inputactions" static
File extension (without the dot) for InputActionAssets in JSON format.
File extension for InputActionAsset source files.
Files with this extension will automatically be imported by Unity as InputActionAssets.
Property Documentation
actionMaps
ReadOnlyArray<InputActionMap> UnityEngine.InputSystem.InputActionAsset.actionMaps get
List of action maps defined in the asset.
Action maps contained in the asset.
See also
InputActionSetupExtensions.AddActionMap(InputActionAsset,string), InputActionSetupExtensions.RemoveActionMap(InputActionAsset,InputActionMap), FindActionMap(string,bool)
Referenced by UnityEngine.InputSystem.InputActionAsset.Disable(), and UnityEngine.InputSystem.InputActionAsset.Enable().
bindingMask
InputBinding? UnityEngine.InputSystem.InputActionAsset.bindingMask get set
Binding mask to apply to all action maps and actions in the asset.
Optional mask that determines which bindings in the asset to enable.
Binding masks can be applied at three different levels: for an entire asset through this property, for a specific map through InputActionMap.bindingMask, and for single actions through InputAction.bindingMask. By default, none of the masks will be set (i.e. they will be null).
When an action is enabled, all the binding masks that apply to it are taken into account. Specifically, this means that any given binding on the action will be enabled only if it matches the mask applied to the asset, the mask applied to the map that contains the action, and the mask applied to the action itself. All the masks are individually optional.
Masks are matched against bindings using InputBinding.Matches.
Note that if you modify the masks applicable to an action while it is enabled, the action's InputAction.controls will get updated immediately to respect the mask. To avoid repeated binding resolution, it is most efficient to apply binding masks before enabling actions.
Binding masks are non-destructive. All the bindings on the action are left in place. Setting a mask will not affect the value of the InputAction.bindings and InputActionMap.bindings properties.
See also
InputBinding.MaskByGroup, InputAction.bindingMask, InputActionMap.bindingMask
Implements UnityEngine.InputSystem.IInputActionCollection.
bindings
IEnumerable<InputBinding> UnityEngine.InputSystem.InputActionAsset.bindings get
Iterate over all bindings in the asset.
This iterates over all action maps in actionMaps and, within each map, over the set of InputActionMap.bindings.
See also
InputActionMap.bindings
Implements UnityEngine.InputSystem.IInputActionCollection2.
controlSchemes
ReadOnlyArray<InputControlScheme> UnityEngine.InputSystem.InputActionAsset.controlSchemes get
List of control schemes defined in the asset.
Control schemes defined for the asset.
See also
InputActionSetupExtensions.AddControlScheme(InputActionAsset,string), InputActionSetupExtensions.RemoveControlScheme
Implements UnityEngine.InputSystem.IInputActionCollection.
Referenced by UnityEngine.InputSystem.PlayerInput.SwitchCurrentControlScheme(), UnityEngine.InputSystem.InputActionAsset.ToJson(), and UnityEngine.InputSystem.InputActionRebindingExtensions.RebindingOperation.WithTargetBinding().
devices
ReadOnlyArray<InputDevice>? UnityEngine.InputSystem.InputActionAsset.devices get set
Set of devices that bindings in the asset can bind to.
Optional set of devices to use by bindings in the asset.
By default (with this property being null), bindings will bind to any of the controls available through InputSystem.devices, i.e. controls from all devices in the system will be used.
By setting this property, binding resolution can instead be restricted to just specific devices. This restriction can either be applied to an entire asset using this property or to specific action maps by using InputActionMap.devices. Note that if both this property and InputActionMap.devices is set for a specific action map, the list of devices on the action map will take precedence and the list on the asset will be ignored for bindings in that action map.
// Create an asset with a single action map and a single action with a
// gamepad binding.
var asset = ScriptableObject.CreateInstance<InputActionAsset>();
var actionMap = new InputActionMap();
var fireAction = actionMap.AddAction("Fire", binding: "<Gamepad>/buttonSouth");
asset.AddActionMap(actionMap);
// Let's assume we have two gamepads connected. If we enable the
// action map now, the 'Fire' action will bind to both.
actionMap.Enable();
// This will print two controls.
Debug.Log(string.Join("\n", fireAction.controls));
// To restrict the setup to just the first gamepad, we can assign
// to the 'devices' property (in this case, we could do so on either
// the action map or on the asset; we choose the latter here).
asset.devices = new InputDevice[] { Gamepad.all[0] };
// Now this will print only one control.
Debug.Log(string.Join("\n", fireAction.controls));
See also
InputActionMap.devices
Implements UnityEngine.InputSystem.IInputActionCollection.
enabled
bool UnityEngine.InputSystem.InputActionAsset.enabled get
True if any action in the asset is currently enabled.
See also
InputAction.enabled, InputActionMap.enabled, InputAction.Enable, InputActionMap.Enable, Enable
this[string actionNameOrId]
InputAction UnityEngine.InputSystem.InputActionAsset.this[string actionNameOrId] get
Look up an action by name or ID.
Parameters
actionNameOrId Name of the action as either a "map/action" combination (e.g. "gameplay/fire") or a simple name. In the former case, the name is split at the '/' slash and the first part is used to find a map with that name and the second part is used to find an action with that name inside the map. In the latter case, all maps are searched in order and the first action that has the given name in any of the maps is returned. Note that name comparisons are case-insensitive.
Alternatively, the given string can be a GUID as given by InputAction.id.
Returns
The action with the corresponding name or null if no matching action could be found.
This method is equivalent to FindAction(string,bool) except that it throws KeyNotFoundException if no action with the given name or ID could be found.
Exceptions
KeyNotFoundException No action was found matching actionNameOrId .
ArgumentNullException actionNameOrId is null or empty.
See also
FindAction(string,bool)
The documentation for this class was generated from the following file:
C:/Users/Lykos/Desktop/Projects/Capstone/VRGames/Library/PackageCache/com.unity.inputsystem@1.3.0/InputSystem/Actions/InputActionAsset.cs