VRGames: UnityEngine.InputSystem.PlayerInput Class Reference
UnityEngine.InputSystem.PlayerInput Class Reference
Represents a separate player in the game complete with a set of actions exclusive to the player and a set of paired device.
Classes
class ActionEvent
class ControlsChangedEvent
Event that is triggered when the set of controls used by a PlayerInput changes.
class DeviceLostEvent
Event that is triggered when an InputDevice paired to a PlayerInput is disconnected.
class DeviceRegainedEvent
Event that is triggered when a PlayerInput regains an InputDevice previously lost.
Public Member Functions
TDevice GetDevice< TDevice > ()
Return the first device of the given type from devices paired to the player. If no device of this type is paired to the player, return null.
void ActivateInput ()
Enable input on the player.
void DeactivateInput ()
Disable input on the player.
void PassivateInput ()
bool SwitchCurrentControlScheme (params InputDevice[] devices)
Switch the current control scheme to one that fits the given set of devices.
void SwitchCurrentControlScheme (string controlScheme, params InputDevice[] devices)
Switch the player to use the given control scheme together with the given devices.
void SwitchCurrentActionMap (string mapNameOrId)
void DebugLogAction (InputAction.CallbackContext context)
Debug helper method that can be hooked up to actions when using UnityEngine.InputSystem.PlayerNotifications.InvokeUnityEvents.
Static Public Member Functions
static PlayerInput GetPlayerByIndex (int playerIndex)
Return the Nth player.
static PlayerInput FindFirstPairedToDevice (InputDevice device)
Find the first PlayerInput who the given device is paired to.
static PlayerInput Instantiate (GameObject prefab, int playerIndex=-1, string controlScheme=null, int splitScreenIndex=-1, InputDevice pairWithDevice=null)
Instantiate a player object and set up and enable its inputs.
static PlayerInput Instantiate (GameObject prefab, int playerIndex=-1, string controlScheme=null, int splitScreenIndex=-1, params InputDevice[] pairWithDevices)
A wrapper around Object.Instantiate(Object) that allows instantiating a player prefab and automatically pair one or more specific devices to the newly created player.
Static Public Attributes
const string DeviceLostMessage = "OnDeviceLost"
Name of the message that is sent with UnityEngine.Object.SendMessage when a player loses a device.
const string DeviceRegainedMessage = "OnDeviceRegained"
Name of the message that is sent with UnityEngine.Object.SendMessage when a player regains a device.
const string ControlsChangedMessage = "OnControlsChanged"
Name of the message that is sent with UnityEngine.Object.SendMessage when the controls used by a player are changed.
Properties
bool inputIsActive [get]
Whether input is on the player is active.
bool active [get]
int playerIndex [get]
Unique, zero-based index of the player. For example, 2 for the third player.
int splitScreenIndex [get]
If split-screen is enabled (UnityEngine.InputSystem.PlayerInputManager.splitScreen), this is the index of the screen area used by the player.
InputActionAsset actions [get, set]
Input actions associated with the player.
string currentControlScheme [get]
Name of the currently active control scheme.
string defaultControlScheme [get, set]
The default control scheme to try.
bool neverAutoSwitchControlSchemes [get, set]
If true, do not automatically switch control schemes even when there is only a single player. By default, this property is false.
InputActionMap currentActionMap [get, set]
The currently enabled action map.
string defaultActionMap [get, set]
Name (see InputActionMap.name) or ID (see InputActionMap.id) of the action map to enable by default.
PlayerNotifications notificationBehavior [get, set]
Determines how the component notifies listeners about input actions and other input-related events pertaining to the player.
ReadOnlyArray< ActionEvent > actionEvents [get, set]
List of events invoked in response to actions being triggered.
DeviceLostEvent deviceLostEvent [get]
Event that is triggered when the player loses a device (e.g. the batteries run out).
DeviceRegainedEvent deviceRegainedEvent [get]
Event that is triggered when the player recovers from device loss and is good to go again.
ControlsChangedEvent controlsChangedEvent [get]
Event that is triggered when the controls used by the player change.
Action< InputAction.CallbackContext > onActionTriggered
If notificationBehavior is set to PlayerNotifications.InvokeCSharpEvents, this event is triggered when an action fires.
Action< PlayerInput > onDeviceLost
If notificationBehavior is PlayerNotifications.InvokeCSharpEvents, this event is triggered when a device paired to the player is disconnected.
Action< PlayerInput > onDeviceRegained
If notificationBehavior is PlayerNotifications.InvokeCSharpEvents, this event is triggered when the player previously lost a device and has now regained it or an equivalent device.
Action< PlayerInput > onControlsChanged
If notificationBehavior is PlayerNotifications.InvokeCSharpEvents, this event is triggered when the controls used by the players are changed.
Camera camera [get, set]
Optional camera associated with the player.
InputUser user [get]
The internal user tied to the player.
ReadOnlyArray< InputDevice > devices [get]
The devices paired to the player.
bool hasMissingRequiredDevices [get]
Whether the player is missed required devices. This means that the player's input setup is probably at least partially non-functional.
static ReadOnlyArray< PlayerInput > all [get]
List of all players that are currently joined. Sorted by playerIndex in increasing order.
static bool isSinglePlayer [get]
Whether PlayerInput operates in single-player mode.
Detailed Description
Represents a separate player in the game complete with a set of actions exclusive to the player and a set of paired device.
PlayerInput is a high-level wrapper around much of the input system's functionality which is meant to help getting set up with the new input system quickly. It takes care of InputAction bookkeeping and has a custom UI(requires the "Unity UI" package) to help setting up input.
The component supports local multiplayer implicitly. Each PlayerInput instance represents a distinct user with its own set of devices and actions. To orchestrate player management and facilitate mechanics such as joining by device activity, use UnityEngine.InputSystem.PlayerInputManager.
The way PlayerInput notifies script code of events is determined by notificationBehavior. By default, this is set to UnityEngine.InputSystem.PlayerNotifications.SendMessages which will use GameObject.SendMessage(string,object) to send messages to the GameObject that PlayerInput sits on.
// Component to sit next to PlayerInput.
[RequireComponent(typeof(PlayerInput))]
public class MyPlayerLogic : MonoBehaviour
{
    public GameObject projectilePrefab;
    private Vector2 m_Look;
    private Vector2 m_Move;
    private bool m_Fire;
    // 'Fire' input action has been triggered. For 'Fire' we want continuous
    // action (that is, firing) while the fire button is held such that the action
    // gets triggered repeatedly while the button is down. We can easily set this
    // up by having a "Press" interaction on the button and setting it to repeat
    // at fixed intervals.
    public void OnFire()
    {
        Instantiate(projectilePrefab);
    }
    // 'Move' input action has been triggered.
    public void OnMove(InputValue value)
    {
        m_Move = value.Get<Vector2>();
    }
    // 'Look' input action has been triggered.
    public void OnLook(InputValue value)
    {
        m_Look = value.Get<Vector2>();
    }
    public void OnUpdate()
    {
        // Update transform from m_Move and m_Look
    }
}
It is also possible to use the polling API of InputActions (see InputAction.triggered and InputAction.ReadValue<TValue>) in combination with PlayerInput.
// Component to sit next to PlayerInput.
[RequireComponent(typeof(PlayerInput))]
public class MyPlayerLogic : MonoBehaviour
{
    public GameObject projectilePrefab;
    private PlayerInput m_PlayerInput;
    private InputAction m_LookAction;
    private InputAction m_MoveAction;
    private InputAction m_FireAction;
    public void OnUpdate()
    {
        // First update we look up all the data we need.
        // NOTE: We don't do this in OnEnable as PlayerInput itself performing some
        //       initialization work in OnEnable.
        if (m_PlayerInput == null)
        {
            m_PlayerInput = GetComponent<PlayerInput>();
            m_FireAction = m_PlayerInput.actions["fire"];
            m_LookAction = m_PlayerInput.actions["look"];
            m_MoveAction = m_PlayerInput.actions["move"];
        }
        if (m_FireAction.triggered)
            /* firing logic... *&zwj;/;
        var move = m_MoveAction.ReadValue<Vector2>();
        var look = m_LookAction.ReadValue<Vector2>();
        /* Update transform from move&amp;look... *&zwj;/
    }
}
When enabled, PlayerInput will create an InputUser and pair devices to the user which are then specific to the player. The set of devices can be controlled explicitly when instantiating a PlayerInput through Instantiate(GameObject,int,string,int,InputDevice[]) or Instantiate(GameObject,int,string,int,InputDevice). This also makes it possible to assign the same device to two different players, e.g. for split-keyboard play.
var p1 = PlayerInput.Instantiate(playerPrefab,
    controlScheme: "KeyboardLeft", device: Keyboard.current);
var p2 = PlayerInput.Instantiate(playerPrefab,
    controlScheme: "KeyboardRight", device: Keyboard.current);
If no specific devices are given to a PlayerInput, the component will look for compatible devices present in the system and pair them to itself automatically. If the PlayerInput's actions have control schemes defined for them, PlayerInput will look for a control scheme for which all required devices are available and not paired to any other player. It will try defaultControlScheme first (if set), but then fall back to trying all available schemes in order. Once a scheme is found for which all required devices are available, PlayerInput will pair those devices to itself and select the given scheme.
If no control schemes are defined, PlayerInput will try to bind as many as-of-yet unpaired devices to itself as it can match to bindings present in the actions. This means that if, for example, there's binding for both keyboard and gamepad and there is one keyboard and two gamepads available when PlayerInput is enabled, all three devices will be paired to the player.
Note that when using PlayerInputManager, device pairing to players is controlled from the joining logic. In that case, PlayerInput will automatically pair the device from which the player joined. If control schemes are present in actions, the first one compatible with that device is chosen. If additional devices are required, these will be paired from the pool of currently unpaired devices.
Device pairings can be changed at any time by either manually controlling pairing through InputUser.PerformPairingWithDevice (and related methods) using a PlayerInput's assigned user or by switching control schemes (e.g. using SwitchCurrentControlScheme(string,InputDevice[])), if any are present in the PlayerInput's actions.
When a player loses a device paired to it (e.g. when it is unplugged or loses power), InputUser will signal InputUserChange.DeviceLost which is also surfaced as a message, deviceLostEvent, or onDeviceLost (depending on notificationBehavior). When a device is reconnected, InputUser will signal InputUserChange.DeviceRegained which also is surfaced as a message, as deviceRegainedEvent, or onDeviceRegained (depending on notificationBehavior).
When there is only a single active PlayerInput in the game, joining is not enabled (see PlayerInputManager.joiningEnabled), and neverAutoSwitchControlSchemes is not set to true, device pairings for the player will also update automatically based on device usage.
If control schemes are present in actions, then if a device is used (not merely plugged in but rather receives input on a non-noisy, non-synthetic control) which is compatible with a control scheme other than the currently used one, PlayerInput will attempt to switch to that control scheme. Success depends on whether all device requirements for that scheme are met from the set of available devices. If a control scheme happens, InputUser signals InputUserChange.ControlSchemeChanged on InputUser.onChange.
If no control schemes are present in actions, PlayerInput will automatically pair any newly available device to itself if the given device has any bindings available for it.
Both behaviors described in the previous two paragraphs are automatically disabled if more than one PlayerInput is active.
See also
UnityEngine.InputSystem.PlayerInputManager
Member Function Documentation
ActivateInput()
void UnityEngine.InputSystem.PlayerInput.ActivateInput ()
Enable input on the player.
Input will automatically be activated when the PlayerInput component is enabled. However, this method can be called to reactivate input after deactivating it with DeactivateInput.
Note that activating input will activate the current action map only (see currentActionMap).
inputIsActive
See also
DeactivateInput
Referenced by UIvsGameInputHandler.OnContinueClicked().
DeactivateInput()
void UnityEngine.InputSystem.PlayerInput.DeactivateInput ()
Disable input on the player.
Input is automatically activated when the PlayerInput component is enabled. This method can be used to deactivate input manually.
Note that activating input will deactivate the current action map only (see currentActionMap).
ActivateInput inputIsActive
Referenced by UnityEngine.InputSystem.PlayerInput.PassivateInput(), and UIvsGameInputHandler.Update().
DebugLogAction()
void UnityEngine.InputSystem.PlayerInput.DebugLogAction (InputAction::CallbackContext context)
Debug helper method that can be hooked up to actions when using UnityEngine.InputSystem.PlayerNotifications.InvokeUnityEvents.
FindFirstPairedToDevice()
static PlayerInput UnityEngine.InputSystem.PlayerInput.FindFirstPairedToDevice (InputDevice device) static
Find the first PlayerInput who the given device is paired to.
Parameters
device An input device.
Returns
The player who is paired to the given device or null if no PlayerInput currently is paired to device .
Exceptions
ArgumentNullException device is null.
// Find the player paired to first gamepad.
var player = PlayerInput.FindFirstPairedToDevice(Gamepad.all[0]);
Referenced by UnityEngine.InputSystem.PlayerInputManager.JoinPlayerFromActionIfNotAlreadyJoined().
GetDevice< TDevice >()
TDevice UnityEngine.InputSystem.PlayerInput.GetDevice< TDevice > ()
Return the first device of the given type from devices paired to the player. If no device of this type is paired to the player, return null.
Template Parameters
TDevice Type of device to look for (such as Mouse). Can be a supertype of the actual device type. For example, querying for Pointer, may return a Mouse.
Returns
The first device paired to the player that is of the given type or null if the player does not have a matching device.
See also
devices
Type Constraints
TDevice : InputDevice
GetPlayerByIndex()
static PlayerInput UnityEngine.InputSystem.PlayerInput.GetPlayerByIndex (int playerIndex) static
Return the Nth player.
Parameters
playerIndex Index of the player to return.
Returns
The player with the given player index or null if no such player exists.
See also
PlayerInput.playerIndex
Instantiate() [1/2]
static PlayerInput UnityEngine.InputSystem.PlayerInput.Instantiate (GameObject prefab, int playerIndex = -1, string controlScheme = null, int splitScreenIndex = -1, InputDevice pairWithDevice = null) static
Instantiate a player object and set up and enable its inputs.
Parameters
prefab Prefab to clone. Must contain a PlayerInput component somewhere in its hierarchy.
playerIndex Player index to assign to the player. See PlayerInput.playerIndex. By default will be assigned automatically based on how many players are in all.
controlScheme Control scheme to activate
splitScreenIndex
pairWithDevice Device to pair to the user. By default, this is null which means that PlayerInput will automatically pair with available, unpaired devices based on the control schemes (if any) present in actions or on the bindings therein (if no control schemes are present).
Returns
Exceptions
ArgumentNullException prefab is null.
Referenced by UnityEngine.InputSystem.PlayerInputManager.JoinPlayer(), and UnityEngine.InputSystem.PlayerInputManager.JoinPlayer().
Instantiate() [2/2]
static PlayerInput UnityEngine.InputSystem.PlayerInput.Instantiate (GameObject prefab, int playerIndex = -1, string controlScheme = null, int splitScreenIndex = -1, params InputDevice[] pairWithDevices) static
A wrapper around Object.Instantiate(Object) that allows instantiating a player prefab and automatically pair one or more specific devices to the newly created player.
Parameters
prefab A player prefab containing a PlayerInput component in its hierarchy.
playerIndex
controlScheme
splitScreenIndex
pairWithDevices
Returns
Note that unlike Object.Instantiate(Object), this method will always activate the resulting GameObject and its components.
PassivateInput()
void UnityEngine.InputSystem.PlayerInput.PassivateInput ()
SwitchCurrentActionMap()
void UnityEngine.InputSystem.PlayerInput.SwitchCurrentActionMap (string mapNameOrId)
Referenced by UnityEngine.InputSystem.PlayerInput.ActivateInput().
SwitchCurrentControlScheme() [1/2]
bool UnityEngine.InputSystem.PlayerInput.SwitchCurrentControlScheme (params InputDevice[] devices)
Switch the current control scheme to one that fits the given set of devices.
Parameters
devices A list of input devices. Note that if any of the devices is already paired to another player, the device will end up paired to both players.
Returns
True if the switch was successful, false otherwise. The latter can happen, for example, if actions does not have a control scheme that fits the given set of devices.
Exceptions
ArgumentNullException devices is null.
InvalidOperationException actions has not been assigned.
The player's currently paired devices (see devices) will get unpaired.
// Switch the first player to keyboard and mouse.
PlayerInput.all[0]
    .SwitchCurrentControlScheme(Keyboard.current, Mouse.current);
See also
currentControlScheme, InputActionAsset.controlSchemes
SwitchCurrentControlScheme() [2/2]
void UnityEngine.InputSystem.PlayerInput.SwitchCurrentControlScheme (string controlScheme, params InputDevice[] devices)
Switch the player to use the given control scheme together with the given devices.
Parameters
controlScheme Name of the control scheme. See InputControlScheme.name.
devices A list of devices.
Exceptions
ArgumentNullException devices is null -or- controlScheme is null or empty.
This method can be used to explicitly force a combination of control scheme and a specific set of devices.
// Put player 1 on the "Gamepad" control scheme together
// with the second gamepad.
PlayerInput.all[0].SwitchControlScheme(
    "Gamepad",
    Gamepad.all[1]);
The player's currently paired devices (see devices) will get unpaired.
See also
InputActionAsset.controlSchemes, currentControlScheme
Member Data Documentation
ControlsChangedMessage
const string UnityEngine.InputSystem.PlayerInput.ControlsChangedMessage = "OnControlsChanged" static
Name of the message that is sent with UnityEngine.Object.SendMessage when the controls used by a player are changed.
See also
onControlsChanged
DeviceLostMessage
const string UnityEngine.InputSystem.PlayerInput.DeviceLostMessage = "OnDeviceLost" static
Name of the message that is sent with UnityEngine.Object.SendMessage when a player loses a device.
See also
onDeviceLost
DeviceRegainedMessage
const string UnityEngine.InputSystem.PlayerInput.DeviceRegainedMessage = "OnDeviceRegained" static
Name of the message that is sent with UnityEngine.Object.SendMessage when a player regains a device.
See also
onDeviceRegained
Property Documentation
actionEvents
ReadOnlyArray<ActionEvent> UnityEngine.InputSystem.PlayerInput.actionEvents get set
List of events invoked in response to actions being triggered.
This array is only used if notificationBehavior is set to UnityEngine.InputSystem.PlayerNotifications.InvokeUnityEvents.
actions
InputActionAsset UnityEngine.InputSystem.PlayerInput.actions get set
Input actions associated with the player.
Asset holding the player's input actions.
Note that every player will maintain a unique copy of the given actions such that each player receives an identical copy. When assigning the same actions to multiple players, the first player will use the given actions as is but any subsequent player will make a copy of the actions using Object.Instantiate(Object).
The asset may contain an arbitrary number of action maps. By setting defaultActionMap, one of them can be selected to enabled automatically when PlayerInput is enabled. If no default action map is selected, none of the action maps will be enabled by PlayerInput itself. Use SwitchCurrentActionMap or just call InputActionMap.Enable directly to enable a specific map.
Notifications will be sent for all actions in the asset, not just for those in the first action map. This means that if additional maps are manually enabled and disabled, notifications will be sent for their actions as they receive input.
See also
InputUser.actions, SwitchCurrentActionMap
Referenced by UIvsGameInputHandler.OnEnable(), UnityEngine.InputSystem.PlayerInput.SwitchCurrentControlScheme(), and UnityEngine.InputSystem.Samples.InGameHints.InGameHintsExample.Update().
active
bool UnityEngine.InputSystem.PlayerInput.active get
all
ReadOnlyArray<PlayerInput> UnityEngine.InputSystem.PlayerInput.all static get
List of all players that are currently joined. Sorted by playerIndex in increasing order.
List of active PlayerInputs.
While the list is sorted by playerIndex, note that this does not mean that the playerIndex of a player corresponds to the index in this list. If, for example, three players join and then the second player leaves, the list will contain one player with playerIndex 0 followed by one player with playerIndex 2.
See also
PlayerInputManager.JoinPlayer(int,int,string,InputDevice), Instantiate(GameObject,int,string,int,InputDevice)
camera
Camera UnityEngine.InputSystem.PlayerInput.camera get set
Optional camera associated with the player.
TODO: clarify the relationship to raycasting in the UI input module
Camera specific to the player or null.
This is null by default.
Associating a camera with a player is necessary only when using split-screen (see PlayerInputManager.splitScreen).
controlsChangedEvent
ControlsChangedEvent UnityEngine.InputSystem.PlayerInput.controlsChangedEvent get
Event that is triggered when the controls used by the player change.
This event is only used if notificationBehavior is set to UnityEngine.InputSystem.PlayerNotifications.InvokeUnityEvents.
The event is trigger when the set of devices used by the player change, when the player switches to a different control scheme (see currentControlScheme), or when the bindings used by the player are changed (e.g. when rebinding them). Also, for Keyboard devices, the event is triggered when the currently used keyboard layout (see Keyboard.keyboardLayout) changes.
currentActionMap
InputActionMap UnityEngine.InputSystem.PlayerInput.currentActionMap get set
The currently enabled action map.
REVIEW: this is inconsistent; currentControlScheme is a string, this is an InputActionMap
Reference to the currently enabled action or null if no action map has been enabled by PlayerInput.
Note that the concept of "current action map" is local to PlayerInput. You can still freely enable and disable action maps directly on the actions asset. This property only tracks which action map has been enabled under the control of PlayerInput, i.e. either by means of defaultActionMap or by using SwitchCurrentActionMap.
See also
SwitchCurrentActionMap
Referenced by UnityEngine.InputSystem.PlayerInput.SwitchCurrentActionMap().
currentControlScheme
string UnityEngine.InputSystem.PlayerInput.currentControlScheme get
Name of the currently active control scheme.
Name of the currently active control scheme or null.
Note that this property will be null if there are no control schemes defined in actions.
See also
SwitchCurrentControlScheme(UnityEngine.InputSystem.InputDevice[]), defaultControlScheme, InputActionAsset.controlSchemes
Referenced by UIvsGameInputHandler.OnControlsChanged().
defaultActionMap
string UnityEngine.InputSystem.PlayerInput.defaultActionMap get set
Name (see InputActionMap.name) or ID (see InputActionMap.id) of the action map to enable by default.
Action map to enable by default or null.
By default, when enabled, PlayerInput will not enable any of the actions in the actions asset. By setting this property, however, PlayerInput can be made to automatically enable the respective action map.
See also
currentActionMap, SwitchCurrentActionMap
defaultControlScheme
string UnityEngine.InputSystem.PlayerInput.defaultControlScheme get set
The default control scheme to try.
Name of the default control scheme.
When PlayerInput is enabled and this is not null and not empty, the PlayerInput will look up the control scheme in InputActionAsset.controlSchemes of actions. If found, PlayerInput will try to activate the scheme. This will succeed only if all devices required by the control scheme are either already paired to the player or are available as devices not used by other PlayerInputs.
Note that this property only determines the first control scheme to try. If using the control scheme fails, PlayerInput will fall back to trying the other control schemes (if any) available from actions.
See also
SwitchCurrentControlScheme(InputDevice[]), currentControlScheme
deviceLostEvent
DeviceLostEvent UnityEngine.InputSystem.PlayerInput.deviceLostEvent get
Event that is triggered when the player loses a device (e.g. the batteries run out).
This event is only used if notificationBehavior is set to UnityEngine.InputSystem.PlayerNotifications.InvokeUnityEvents.
deviceRegainedEvent
DeviceRegainedEvent UnityEngine.InputSystem.PlayerInput.deviceRegainedEvent get
Event that is triggered when the player recovers from device loss and is good to go again.
This event is only used if notificationBehavior is set to UnityEngine.InputSystem.PlayerNotifications.InvokeUnityEvents.
devices
ReadOnlyArray<InputDevice> UnityEngine.InputSystem.PlayerInput.devices get
The devices paired to the player.
List of devices paired to player.
See also
InputUser.pairedDevices
Referenced by UnityEngine.InputSystem.PlayerInput.GetDevice< TDevice >(), UnityEngine.InputSystem.PlayerInput.SwitchCurrentControlScheme(), and UnityEngine.InputSystem.PlayerInput.SwitchCurrentControlScheme().
hasMissingRequiredDevices
bool UnityEngine.InputSystem.PlayerInput.hasMissingRequiredDevices get
Whether the player is missed required devices. This means that the player's input setup is probably at least partially non-functional.
True if the player is missing devices required by the control scheme.
This can happen, for example, if the a device is unplugged during the game.
See also
InputControlScheme.deviceRequirements, InputUser.hasMissingRequiredDevices
inputIsActive
bool UnityEngine.InputSystem.PlayerInput.inputIsActive get
Whether input is on the player is active.
If true, the player is receiving input.
See also
ActivateInput, DeactivateInput
isSinglePlayer
bool UnityEngine.InputSystem.PlayerInput.isSinglePlayer static get
Whether PlayerInput operates in single-player mode.
If true, there is at most a single PlayerInput.
Single-player mode is active while there is at most one PlayerInput (there can also be none) and while joining is not enabled in PlayerInputManager (if one exists). See PlayerInputManager.joiningEnabled.
Automatic control scheme switching (if enabled) is predicated on single-player mode being active.
See also
neverAutoSwitchControlSchemes
neverAutoSwitchControlSchemes
bool UnityEngine.InputSystem.PlayerInput.neverAutoSwitchControlSchemes get set
If true, do not automatically switch control schemes even when there is only a single player. By default, this property is false.
If true, do not switch control schemes when other devices are used.
By default, when there is only a single PlayerInput enabled, we assume that the game is in single-player mode and that the player should be able to freely switch between the control schemes supported by the game. For example, if the player is currently using mouse and keyboard, but is then switching to a gamepad, PlayerInput should automatically switch to the control scheme for gamepads, if present.
When there is more than one PlayerInput or when joining is enabled PlayerInputManager, this behavior is automatically turned off as we wouldn't know which player is switching if a currently unpaired device is used.
By setting this property to true, auto-switching of control schemes is forcibly turned off and will thus not be performed even if there is only a single PlayerInput in the game.
Note that you can still switch control schemes manually using SwitchCurrentControlScheme(string,InputDevice[]).
See also
currentControlScheme, isSinglePlayer
notificationBehavior
PlayerNotifications UnityEngine.InputSystem.PlayerInput.notificationBehavior get set
Determines how the component notifies listeners about input actions and other input-related events pertaining to the player.
How to trigger notifications on events.
By default, the component will use GameObject.SendMessage(string,object) to send messages to the GameObject. This can be changed by selecting a different UnityEngine.InputSystem.PlayerNotifications behavior.
See also
actionEvents, deviceLostEvent, deviceRegainedEvent
onActionTriggered
Action<InputAction.CallbackContext> UnityEngine.InputSystem.PlayerInput.onActionTriggered add remove
If notificationBehavior is set to PlayerNotifications.InvokeCSharpEvents, this event is triggered when an action fires.
Callbacks that get called when an action triggers.
If notificationBehavior is not set to PlayerNotifications.InvokeCSharpEvents, the value of this property is ignored.
The callbacks are called in sync (and with the same argument) with InputAction.started, InputAction.performed, and InputAction.canceled.
See also
InputActionMap.actionTriggered, InputAction.started, InputAction.performed, InputAction.canceled, actions
onControlsChanged
Action<PlayerInput> UnityEngine.InputSystem.PlayerInput.onControlsChanged add remove
If notificationBehavior is PlayerNotifications.InvokeCSharpEvents, this event is triggered when the controls used by the players are changed.
The callback is invoked when the set of devices used by the player change, when the player switches to a different control scheme (see currentControlScheme), or when the bindings used by the player are changed (e.g. when rebinding them). Also, for Keyboard devices, the callback is invoked when the currently used keyboard layout (see Keyboard.keyboardLayout) changes.
onDeviceLost
Action<PlayerInput> UnityEngine.InputSystem.PlayerInput.onDeviceLost add remove
If notificationBehavior is PlayerNotifications.InvokeCSharpEvents, this event is triggered when a device paired to the player is disconnected.
Callbacks that get called when the player loses a device.
If notificationBehavior is not PlayerNotifications.InvokeCSharpEvents, the value of this property is ignored.
The argument is the player that lost its device (i.e. the player on which the callback is installed).
See also
onDeviceRegained, InputUserChange.DeviceLost
onDeviceRegained
Action<PlayerInput> UnityEngine.InputSystem.PlayerInput.onDeviceRegained add remove
If notificationBehavior is PlayerNotifications.InvokeCSharpEvents, this event is triggered when the player previously lost a device and has now regained it or an equivalent device.
Callbacks that get called when the player regains a device.
If notificationBehavior is not PlayerNotifications.InvokeCSharpEvents, the value of this property is ignored.
The argument is the player that regained a device (i.e. the player on which the callback is installed).
See also
onDeviceLost, InputUserChange.DeviceRegained
playerIndex
int UnityEngine.InputSystem.PlayerInput.playerIndex get
Unique, zero-based index of the player. For example, 2 for the third player.
Unique index of the player.
Once assigned, a player index will not change.
Note that the player index does not necessarily correspond to the player's index in all. The array will always contain all currently enabled players so when a player is disabled or destroyed, it will be removed from the array. However, the player index of the remaining players will not change.
Referenced by UnityEngine.InputSystem.PlayerInput.GetPlayerByIndex(), UnityEngine.InputSystem.PlayerInput.Instantiate(), and UnityEngine.InputSystem.PlayerInput.Instantiate().
splitScreenIndex
int UnityEngine.InputSystem.PlayerInput.splitScreenIndex get
If split-screen is enabled (UnityEngine.InputSystem.PlayerInputManager.splitScreen), this is the index of the screen area used by the player.
Index of split-screen area assigned to player or -1 if the player is not using split-screen.
Split screen areas are enumerated row by row and within rows, column by column. So, if, for example, there are four separate split-screen areas, the upper left one is #0, the upper right one is #1, the lower left one is #2, and the lower right one is #3.
Split screen areas are usually assigned automatically but players can also be assigned to areas explicitly through Instantiate(GameObject,int,string,int,InputDevice) or PlayerInputManager.JoinPlayer(int,int,string,InputDevice).
See also
camera, PlayerInputManager.splitScreen
Referenced by UnityEngine.InputSystem.PlayerInput.Instantiate(), and UnityEngine.InputSystem.PlayerInput.Instantiate().
user
InputUser UnityEngine.InputSystem.PlayerInput.user get
The internal user tied to the player.
Referenced by UnityEngine.InputSystem.PlayerInput.SwitchCurrentControlScheme().
The documentation for this class was generated from the following file:
C:/Users/Lykos/Desktop/Projects/Capstone/VRGames/Library/PackageCache/com.unity.inputsystem@1.3.0/InputSystem/Plugins/PlayerInput/PlayerInput.cs