VRCapstoneGames: OVRSkeleton Class Reference
OVRSkeleton Class Reference
Classes
interface IOVRSkeletonDataProvider
struct SkeletonPoseData
Public Types
enum SkeletonType { None = OVRPlugin.SkeletonType.None , HandLeft = OVRPlugin.SkeletonType.HandLeft , HandRight = OVRPlugin.SkeletonType.HandRight }
enum BoneId {
Invalid = OVRPlugin.BoneId.Invalid , Hand_Start = OVRPlugin.BoneId.Hand_Start , Hand_WristRoot = OVRPlugin.BoneId.Hand_WristRoot , Hand_ForearmStub = OVRPlugin.BoneId.Hand_ForearmStub ,
Hand_Thumb0 = OVRPlugin.BoneId.Hand_Thumb0 , Hand_Thumb1 = OVRPlugin.BoneId.Hand_Thumb1 , Hand_Thumb2 = OVRPlugin.BoneId.Hand_Thumb2 , Hand_Thumb3 = OVRPlugin.BoneId.Hand_Thumb3 ,
Hand_Index1 = OVRPlugin.BoneId.Hand_Index1 , Hand_Index2 = OVRPlugin.BoneId.Hand_Index2 , Hand_Index3 = OVRPlugin.BoneId.Hand_Index3 , Hand_Middle1 = OVRPlugin.BoneId.Hand_Middle1 ,
Hand_Middle2 = OVRPlugin.BoneId.Hand_Middle2 , Hand_Middle3 = OVRPlugin.BoneId.Hand_Middle3 , Hand_Ring1 = OVRPlugin.BoneId.Hand_Ring1 , Hand_Ring2 = OVRPlugin.BoneId.Hand_Ring2 ,
Hand_Ring3 = OVRPlugin.BoneId.Hand_Ring3 , Hand_Pinky0 = OVRPlugin.BoneId.Hand_Pinky0 , Hand_Pinky1 = OVRPlugin.BoneId.Hand_Pinky1 , Hand_Pinky2 = OVRPlugin.BoneId.Hand_Pinky2 ,
Hand_Pinky3 = OVRPlugin.BoneId.Hand_Pinky3 , Hand_MaxSkinnable = OVRPlugin.BoneId.Hand_MaxSkinnable , Hand_ThumbTip = OVRPlugin.BoneId.Hand_ThumbTip , Hand_IndexTip = OVRPlugin.BoneId.Hand_IndexTip ,
Hand_MiddleTip = OVRPlugin.BoneId.Hand_MiddleTip , Hand_RingTip = OVRPlugin.BoneId.Hand_RingTip , Hand_PinkyTip = OVRPlugin.BoneId.Hand_PinkyTip , Hand_End = OVRPlugin.BoneId.Hand_End ,
Max = OVRPlugin.BoneId.Max
}
Public Member Functions
SkeletonType GetSkeletonType ()
BoneId GetCurrentStartBoneId ()
BoneId GetCurrentEndBoneId ()
int GetCurrentNumBones ()
int GetCurrentNumSkinnableBones ()
Static Public Member Functions
static string BoneLabelFromBoneId (OVRSkeleton.SkeletonType skeletonType, BoneId boneId)
Protected Member Functions
virtual void InitializeBones ()
Protected Attributes
SkeletonType _skeletonType = SkeletonType.None
List< OVRBone > _bones
OVRPlugin.Skeleton2 _skeleton = new OVRPlugin.Skeleton2()
Properties
bool IsInitialized [get]
bool IsDataValid [get]
bool IsDataHighConfidence [get]
IList< OVRBone > Bones [get, protected set]
IList< OVRBone > BindPoses [get]
IList< OVRBoneCapsule > Capsules [get]
int SkeletonChangedCount [get]
Member Enumeration Documentation
BoneId
enum OVRSkeleton.BoneId
Enumerator
Invalid
Hand_Start
Hand_WristRoot
Hand_ForearmStub
Hand_Thumb0
Hand_Thumb1
Hand_Thumb2
Hand_Thumb3
Hand_Index1
Hand_Index2
Hand_Index3
Hand_Middle1
Hand_Middle2
Hand_Middle3
Hand_Ring1
Hand_Ring2
Hand_Ring3
Hand_Pinky0
Hand_Pinky1
Hand_Pinky2
Hand_Pinky3
Hand_MaxSkinnable
Hand_ThumbTip
Hand_IndexTip
Hand_MiddleTip
Hand_RingTip
Hand_PinkyTip
Hand_End
Max
SkeletonType
enum OVRSkeleton.SkeletonType
Enumerator
None
HandLeft
HandRight
Member Function Documentation
BoneLabelFromBoneId()
static string OVRSkeleton.BoneLabelFromBoneId (OVRSkeleton::SkeletonType skeletonType, BoneId boneId) static
Referenced by InitializeBones(), and OVRCustomSkeletonEditor.OnInspectorGUI().
GetCurrentEndBoneId()
BoneId OVRSkeleton.GetCurrentEndBoneId ()
Referenced by GetCurrentNumBones(), and OVRCustomSkeletonEditor.OnInspectorGUI().
GetCurrentNumBones()
int OVRSkeleton.GetCurrentNumBones ()
GetCurrentNumSkinnableBones()
int OVRSkeleton.GetCurrentNumSkinnableBones ()
GetCurrentStartBoneId()
BoneId OVRSkeleton.GetCurrentStartBoneId ()
Referenced by GetCurrentNumBones(), GetCurrentNumSkinnableBones(), and OVRCustomSkeletonEditor.OnInspectorGUI().
GetSkeletonType()
SkeletonType OVRSkeleton.GetSkeletonType ()
Referenced by OVRCustomSkeletonEditor.OnInspectorGUI().
InitializeBones()
virtual void OVRSkeleton.InitializeBones () protected virtual
Reimplemented in OVRCustomSkeleton.
Member Data Documentation
_bones
List<OVRBone> OVRSkeleton._bones protected
Referenced by OVRCustomSkeleton.InitializeBones().
_skeleton
OVRPlugin.Skeleton2 OVRSkeleton._skeleton = new OVRPlugin.Skeleton2() protected
Referenced by OVRCustomSkeleton.InitializeBones().
_skeletonType
SkeletonType OVRSkeleton._skeletonType = SkeletonType.None protected
Referenced by OVRCustomSkeleton.InitializeBones().
Property Documentation
BindPoses
IList<OVRBone> OVRSkeleton.BindPoses get
Bones
IList<OVRBone> OVRSkeleton.Bones get protected set
Referenced by OVRCustomSkeleton.InitializeBones(), and InitializeBones().
Capsules
IList<OVRBoneCapsule> OVRSkeleton.Capsules get
Referenced by OculusSampleFramework.HandsManager.GetCapsulesPerBone().
IsDataHighConfidence
bool OVRSkeleton.IsDataHighConfidence get
IsDataValid
bool OVRSkeleton.IsDataValid get
IsInitialized
bool OVRSkeleton.IsInitialized get
SkeletonChangedCount
int OVRSkeleton.SkeletonChangedCount get
The documentation for this class was generated from the following file:
C:/Users/Lykos/Desktop/Projects/Capstone/VRGames/Assets/ThirdParty/Oculus/VR/Scripts/Util/OVRSkeleton.cs