VRCapstoneGames: UnityEngine.XR.Interaction.Toolkit.ActionBasedController Class Reference
UnityEngine.XR.Interaction.Toolkit.ActionBasedController Class Reference
Interprets feature values on a tracked input controller device using actions from the Input System into XR Interaction states, such as Select. Additionally, it applies the current Pose value of a tracked device to the transform of the GameObject.
Public Member Functions
override bool SendHapticImpulse (float amplitude, float duration)
Play a haptic impulse on the controller if one is available.
Parameters
amplitude Amplitude (from 0.0 to 1.0) to play impulse at.
duration Duration (in seconds) to play haptic impulse.
Returns
Returns true if successful. Otherwise, returns false.
Public Member Functions inherited from UnityEngine.XR.Interaction.Toolkit.XRBaseController
virtual bool GetControllerState (out XRControllerState controllerState)
(Deprecated) Gets the state of the controller.
virtual void SetControllerState (XRControllerState controllerState)
(Deprecated) Sets the state of the controller.
Protected Member Functions
override void OnEnable ()
See MonoBehaviour.
override void OnDisable ()
See MonoBehaviour.
override void UpdateTrackingInput (XRControllerState controllerState)
Updates the pose values in the given controller state based on the current tracking input of the controller device. Unity calls this automatically from OnBeforeRender and UpdateController so explicit calls to this function are not required.
Parameters
controllerState The state of the controller.
override void UpdateInput (XRControllerState controllerState)
Updates the XR Interaction states in the given controller state based on the current inputs of the controller device. Unity calls this automatically during UpdateController so explicit calls to this function are not required.
Parameters
controllerState The state of the controller.
virtual bool IsPressed (InputAction action)
Evaluates whether the given input action is considered performed. Unity automatically calls this method during UpdateInput to determine if the interaction state is active this frame.
virtual float ReadValue (InputAction action)
Reads and returns the given action value. Unity automatically calls this method during UpdateInput to determine the amount or strength of the interaction state this frame.
Protected Member Functions inherited from UnityEngine.XR.Interaction.Toolkit.XRBaseController
virtual void Awake ()
See MonoBehaviour.
void Update ()
See MonoBehaviour.
virtual GameObject GetModelPrefab ()
Gets the prefab that should be instantiated upon startup.
virtual void UpdateController ()
Updates the controller every frame. This is called automatically from Update.
virtual void OnBeforeRender ()
This method is automatically called for "Just Before Render" input updates for VR devices.
virtual void ApplyControllerState (XRInteractionUpdateOrder.UpdatePhase updatePhase, XRControllerState controllerState)
Applies the given controller state to this XRBaseController. Depending on the update phase, the XR Interaction states may be copied and/or the pose value may be applied to the transform of the GameObject. Unity calls this automatically from OnBeforeRender and UpdateController.
virtual void UpdateControllerModelAnimation ()
Updates the animation on the model instance (if the model contains an Animator). Unity calls this automatically from UpdateController.
Properties
InputActionProperty positionAction [get, set]
The Input System action to use for Position Tracking for this GameObject. Must be a Vector3Control Control.
InputActionProperty rotationAction [get, set]
The Input System action to use for Rotation Tracking for this GameObject. Must be a QuaternionControl Control.
InputActionProperty trackingStateAction [get, set]
The Input System action to get the Tracking State when updating this GameObject position and rotation; falls back to the tracked device's tracking state that drives the position or rotation action when not set. Must be an IntegerControl Control.
InputActionProperty selectAction [get, set]
The Input System action to use for selecting an Interactable. Must be an action with a button-like interaction where phase equals performed when pressed. Typically a ButtonControl Control or a Value type action with a Press or Sector interaction.
InputActionProperty selectActionValue [get, set]
The Input System action to read values for selecting an Interactable. Must be an AxisControl Control or Vector2Control Control.
InputActionProperty activateAction [get, set]
The Input System action to use for activating a selected Interactable. Must be an action with a button-like interaction where phase equals performed when pressed. Typically a ButtonControl Control or a Value type action with a Press or Sector interaction.
InputActionProperty activateActionValue [get, set]
The Input System action to read values for activating a selected Interactable. Must be an AxisControl Control or Vector2Control Control.
InputActionProperty uiPressAction [get, set]
The Input System action to use for Canvas UI interaction. Must be an action with a button-like interaction where phase equals performed when pressed. Typically a ButtonControl Control or a Value type action with a Press interaction.
InputActionProperty uiPressActionValue [get, set]
The Input System action to read values for Canvas UI interaction. Must be an AxisControl Control or Vector2Control Control.
InputActionProperty hapticDeviceAction [get, set]
The Input System action to use for identifying the device to send haptic impulses to. Can be any control type that will have an active control driving the action.
InputActionProperty rotateAnchorAction [get, set]
The Input System action to use for rotating the interactor's attach point. Must be a Vector2Control Control. Uses the X-axis as the rotation input.
InputActionProperty translateAnchorAction [get, set]
The Input System action to use for translating the interactor's attach point closer or further away from the interactor. Must be a Vector2Control Control. Uses the Y-axis as the translation input.
float buttonPressPoint [get, set]
(Deprecated) The value threshold for when a button is considered pressed to trigger an interaction event. If a button has a value equal to or greater than this value, it is considered pressed.
Properties inherited from UnityEngine.XR.Interaction.Toolkit.XRBaseController
UpdateType updateTrackingType [get, set]
The time within the frame that the controller samples tracking input.
bool enableInputTracking [get, set]
Whether input pose tracking is enabled for this controller. When enabled, Unity reads the current tracking pose input of the controller device each frame.
bool enableInputActions [get, set]
Whether input for XR Interaction events is enabled for this controller. When enabled, Unity reads the current input of the controller device each frame.
Transform modelPrefab [get, set]
The prefab of a controller model to show for this controller that this behavior automatically instantiates.
Transform modelParent [get, set]
The transform that this behavior uses as the parent for the model prefab when it is instantiated.
Transform model [get, set]
The instance of the controller model in the scene. You can set this to an existing object instead of using modelPrefab.
bool animateModel [get, set]
Whether to animate the model in response to interaction events. When enabled, the animation trigger will be set for the corresponding animator component on the controller model when a select or deselect interaction events occurs.
string modelSelectTransition [get, set]
The animation trigger name to activate upon selecting.
string modelDeSelectTransition [get, set]
The animation trigger name to activate upon deselecting.
bool hideControllerModel [get, set]
Whether to hide the controller model.
InteractionState selectInteractionState [get]
(Read Only) The current select interaction state.
InteractionState activateInteractionState [get]
(Read Only) The current activate interaction state.
InteractionState uiPressInteractionState [get]
(Read Only) The current UI press interaction state.
XRControllerState currentControllerState [get, set]
The current state of the controller.
Transform modelTransform [get, set]
float anchorControlDeadzone [get, set]
(Deprecated) Defines the deadzone values for device-based input when performing translate or rotate anchor actions.
float anchorControlOffAxisDeadzone [get, set]
(Deprecated) Defines the off-axis deadzone values for device-based input when performing translate or rotate anchor actions.
Additional Inherited Members
Public Types inherited from UnityEngine.XR.Interaction.Toolkit.XRBaseController
enum UpdateType { UpdateAndBeforeRender , Update , BeforeRender }
The time within the frame that controller pose will be sampled.
Detailed Description
Interprets feature values on a tracked input controller device using actions from the Input System into XR Interaction states, such as Select. Additionally, it applies the current Pose value of a tracked device to the transform of the GameObject.
This behavior requires that the Input System is enabled in the Active Input Handling setting in Edit > Project Settings > Player for input values to be read. Each input action must also be enabled to read the current value of the action. Referenced input actions in an Input Action Asset are not enabled by default.
See also
XRBaseController
Member Function Documentation
IsPressed()
virtual bool UnityEngine.XR.Interaction.Toolkit.ActionBasedController.IsPressed (InputAction action) protected virtual
Evaluates whether the given input action is considered performed. Unity automatically calls this method during UpdateInput to determine if the interaction state is active this frame.
Parameters
action The input action to check.
Returns
Returns true when the input action is considered performed. Otherwise, returns false.
More accurately, this evaluates whether the action with a button-like interaction is performed. Depending on the interaction of the input action, the control driving the value of the input action may technically be pressed and though the interaction may be in progress, it may not yet be performed, such as for a Hold interaction. In that example, this method returns false.
See also
InteractionState.active
Referenced by UnityEngine.XR.Interaction.Toolkit.ActionBasedController.ReadValue(), and UnityEngine.XR.Interaction.Toolkit.ActionBasedController.UpdateInput().
OnDisable()
override void UnityEngine.XR.Interaction.Toolkit.ActionBasedController.OnDisable () protected virtual
See MonoBehaviour.
Reimplemented from UnityEngine.XR.Interaction.Toolkit.XRBaseController.
OnEnable()
override void UnityEngine.XR.Interaction.Toolkit.ActionBasedController.OnEnable () protected virtual
See MonoBehaviour.
Reimplemented from UnityEngine.XR.Interaction.Toolkit.XRBaseController.
ReadValue()
virtual float UnityEngine.XR.Interaction.Toolkit.ActionBasedController.ReadValue (InputAction action) protected virtual
Reads and returns the given action value. Unity automatically calls this method during UpdateInput to determine the amount or strength of the interaction state this frame.
Parameters
action The action to read the value from.
Returns
Returns the action value. If the action is null returns the default float value (0f).
See also
InteractionState.value
Referenced by UnityEngine.XR.Interaction.Toolkit.ActionBasedController.UpdateInput().
SendHapticImpulse()
override bool UnityEngine.XR.Interaction.Toolkit.ActionBasedController.SendHapticImpulse (float amplitude, float duration) virtual
Play a haptic impulse on the controller if one is available.
Parameters
amplitude Amplitude (from 0.0 to 1.0) to play impulse at.
duration Duration (in seconds) to play haptic impulse.
Returns
Returns true if successful. Otherwise, returns false.
Reimplemented from UnityEngine.XR.Interaction.Toolkit.XRBaseController.
UpdateInput()
override void UnityEngine.XR.Interaction.Toolkit.ActionBasedController.UpdateInput (XRControllerState controllerState) protected virtual
Updates the XR Interaction states in the given controller state based on the current inputs of the controller device. Unity calls this automatically during UpdateController so explicit calls to this function are not required.
Parameters
controllerState The state of the controller.
Reimplemented from UnityEngine.XR.Interaction.Toolkit.XRBaseController.
UpdateTrackingInput()
override void UnityEngine.XR.Interaction.Toolkit.ActionBasedController.UpdateTrackingInput (XRControllerState controllerState) protected virtual
Updates the pose values in the given controller state based on the current tracking input of the controller device. Unity calls this automatically from OnBeforeRender and UpdateController so explicit calls to this function are not required.
Parameters
controllerState The state of the controller.
Reimplemented from UnityEngine.XR.Interaction.Toolkit.XRBaseController.
Property Documentation
activateAction
InputActionProperty UnityEngine.XR.Interaction.Toolkit.ActionBasedController.activateAction get set
The Input System action to use for activating a selected Interactable. Must be an action with a button-like interaction where phase equals performed when pressed. Typically a ButtonControl Control or a Value type action with a Press or Sector interaction.
See also
activateActionValue
activateActionValue
InputActionProperty UnityEngine.XR.Interaction.Toolkit.ActionBasedController.activateActionValue get set
The Input System action to read values for activating a selected Interactable. Must be an AxisControl Control or Vector2Control Control.
Optional, Unity uses activateAction when not set.
See also
activateAction
buttonPressPoint
float UnityEngine.XR.Interaction.Toolkit.ActionBasedController.buttonPressPoint get set
(Deprecated) The value threshold for when a button is considered pressed to trigger an interaction event. If a button has a value equal to or greater than this value, it is considered pressed.
hapticDeviceAction
InputActionProperty UnityEngine.XR.Interaction.Toolkit.ActionBasedController.hapticDeviceAction get set
The Input System action to use for identifying the device to send haptic impulses to. Can be any control type that will have an active control driving the action.
positionAction
InputActionProperty UnityEngine.XR.Interaction.Toolkit.ActionBasedController.positionAction get set
The Input System action to use for Position Tracking for this GameObject. Must be a Vector3Control Control.
rotateAnchorAction
InputActionProperty UnityEngine.XR.Interaction.Toolkit.ActionBasedController.rotateAnchorAction get set
The Input System action to use for rotating the interactor's attach point. Must be a Vector2Control Control. Uses the X-axis as the rotation input.
rotationAction
InputActionProperty UnityEngine.XR.Interaction.Toolkit.ActionBasedController.rotationAction get set
The Input System action to use for Rotation Tracking for this GameObject. Must be a QuaternionControl Control.
selectAction
InputActionProperty UnityEngine.XR.Interaction.Toolkit.ActionBasedController.selectAction get set
The Input System action to use for selecting an Interactable. Must be an action with a button-like interaction where phase equals performed when pressed. Typically a ButtonControl Control or a Value type action with a Press or Sector interaction.
See also
selectActionValue
selectActionValue
InputActionProperty UnityEngine.XR.Interaction.Toolkit.ActionBasedController.selectActionValue get set
The Input System action to read values for selecting an Interactable. Must be an AxisControl Control or Vector2Control Control.
Optional, Unity uses selectAction when not set.
See also
selectAction
trackingStateAction
InputActionProperty UnityEngine.XR.Interaction.Toolkit.ActionBasedController.trackingStateAction get set
The Input System action to get the Tracking State when updating this GameObject position and rotation; falls back to the tracked device's tracking state that drives the position or rotation action when not set. Must be an IntegerControl Control.
See also
InputTrackingState
translateAnchorAction
InputActionProperty UnityEngine.XR.Interaction.Toolkit.ActionBasedController.translateAnchorAction get set
The Input System action to use for translating the interactor's attach point closer or further away from the interactor. Must be a Vector2Control Control. Uses the Y-axis as the translation input.
uiPressAction
InputActionProperty UnityEngine.XR.Interaction.Toolkit.ActionBasedController.uiPressAction get set
The Input System action to use for Canvas UI interaction. Must be an action with a button-like interaction where phase equals performed when pressed. Typically a ButtonControl Control or a Value type action with a Press interaction.
See also
uiPressActionValue
uiPressActionValue
InputActionProperty UnityEngine.XR.Interaction.Toolkit.ActionBasedController.uiPressActionValue get set
The Input System action to read values for Canvas UI interaction. Must be an AxisControl Control or Vector2Control Control.
Optional, Unity uses uiPressAction when not set.
See also
uiPressAction
The documentation for this class was generated from the following files:
C:/Users/Lykos/Desktop/Projects/Capstone/VRGames/Library/PackageCache/com.unity.xr.interaction.toolkit@2.0.2/Runtime/Interaction/Controllers/ActionBasedController.cs
C:/Users/Lykos/Desktop/Projects/Capstone/VRGames/Library/PackageCache/com.unity.xr.interaction.toolkit@2.0.2/Runtime/Interaction/Controllers/ActionBasedController.deprecated.cs