VRCapstoneGames: UnityEngine.XR.Interaction.Toolkit.XRBaseController Class Reference
UnityEngine.XR.Interaction.Toolkit.XRBaseController Class Reference abstract
Interprets feature values on a tracked input controller device into XR Interaction states, such as Select. Additionally, it applies the current pose value of a tracked device to the transform of the GameObject.
Public Types
enum UpdateType { UpdateAndBeforeRender , Update , BeforeRender }
The time within the frame that controller pose will be sampled.
Public Member Functions
virtual bool SendHapticImpulse (float amplitude, float duration)
Play a haptic impulse on the controller if one is available.
virtual bool GetControllerState (out XRControllerState controllerState)
(Deprecated) Gets the state of the controller.
virtual void SetControllerState (XRControllerState controllerState)
(Deprecated) Sets the state of the controller.
Protected Member Functions
virtual void Awake ()
See MonoBehaviour.
virtual void OnEnable ()
See MonoBehaviour.
virtual void OnDisable ()
See MonoBehaviour.
void Update ()
See MonoBehaviour.
virtual GameObject GetModelPrefab ()
Gets the prefab that should be instantiated upon startup.
virtual void UpdateController ()
Updates the controller every frame. This is called automatically from Update.
virtual void OnBeforeRender ()
This method is automatically called for "Just Before Render" input updates for VR devices.
virtual void ApplyControllerState (XRInteractionUpdateOrder.UpdatePhase updatePhase, XRControllerState controllerState)
Applies the given controller state to this XRBaseController. Depending on the update phase, the XR Interaction states may be copied and/or the pose value may be applied to the transform of the GameObject. Unity calls this automatically from OnBeforeRender and UpdateController.
virtual void UpdateTrackingInput (XRControllerState controllerState)
Updates the pose values in the given controller state based on the current tracking input of the controller device. Unity calls this automatically from OnBeforeRender and UpdateController so explicit calls to this function are not required.
virtual void UpdateInput (XRControllerState controllerState)
Updates the XR Interaction states in the given controller state based on the current inputs of the controller device. Unity calls this automatically during UpdateController so explicit calls to this function are not required.
virtual void UpdateControllerModelAnimation ()
Updates the animation on the model instance (if the model contains an Animator). Unity calls this automatically from UpdateController.
Properties
UpdateType updateTrackingType [get, set]
The time within the frame that the controller samples tracking input.
bool enableInputTracking [get, set]
Whether input pose tracking is enabled for this controller. When enabled, Unity reads the current tracking pose input of the controller device each frame.
bool enableInputActions [get, set]
Whether input for XR Interaction events is enabled for this controller. When enabled, Unity reads the current input of the controller device each frame.
Transform modelPrefab [get, set]
The prefab of a controller model to show for this controller that this behavior automatically instantiates.
Transform modelParent [get, set]
The transform that this behavior uses as the parent for the model prefab when it is instantiated.
Transform model [get, set]
The instance of the controller model in the scene. You can set this to an existing object instead of using modelPrefab.
bool animateModel [get, set]
Whether to animate the model in response to interaction events. When enabled, the animation trigger will be set for the corresponding animator component on the controller model when a select or deselect interaction events occurs.
string modelSelectTransition [get, set]
The animation trigger name to activate upon selecting.
string modelDeSelectTransition [get, set]
The animation trigger name to activate upon deselecting.
bool hideControllerModel [get, set]
Whether to hide the controller model.
InteractionState selectInteractionState [get]
(Read Only) The current select interaction state.
InteractionState activateInteractionState [get]
(Read Only) The current activate interaction state.
InteractionState uiPressInteractionState [get]
(Read Only) The current UI press interaction state.
XRControllerState currentControllerState [get, set]
The current state of the controller.
Transform modelTransform [get, set]
float anchorControlDeadzone [get, set]
(Deprecated) Defines the deadzone values for device-based input when performing translate or rotate anchor actions.
float anchorControlOffAxisDeadzone [get, set]
(Deprecated) Defines the off-axis deadzone values for device-based input when performing translate or rotate anchor actions.
Detailed Description
Interprets feature values on a tracked input controller device into XR Interaction states, such as Select. Additionally, it applies the current pose value of a tracked device to the transform of the GameObject.
See also
ActionBasedController
Member Enumeration Documentation
UpdateType
enum UnityEngine.XR.Interaction.Toolkit.XRBaseController.UpdateType
The time within the frame that controller pose will be sampled.
See also
updateTrackingType
Enumerator
UpdateAndBeforeRender
Sample input at both update and directly before rendering. For smooth controller pose tracking, we recommend using this value as it will provide the lowest input latency for the device. This is the default value for the UpdateType option.
Update
Only sample input during the update phase of the frame.
BeforeRender
Only sample input directly before rendering.
Member Function Documentation
ApplyControllerState()
virtual void UnityEngine.XR.Interaction.Toolkit.XRBaseController.ApplyControllerState (XRInteractionUpdateOrder::UpdatePhase updatePhase, XRControllerState controllerState) protected virtual
Applies the given controller state to this XRBaseController. Depending on the update phase, the XR Interaction states may be copied and/or the pose value may be applied to the transform of the GameObject. Unity calls this automatically from OnBeforeRender and UpdateController.
Parameters
updatePhase The update phase during this call.
controllerState The state of the controller to apply.
Referenced by UnityEngine.XR.Interaction.Toolkit.XRBaseController.OnBeforeRender(), and UnityEngine.XR.Interaction.Toolkit.XRBaseController.UpdateController().
Awake()
virtual void UnityEngine.XR.Interaction.Toolkit.XRBaseController.Awake () protected virtual
See MonoBehaviour.
GetControllerState()
virtual bool UnityEngine.XR.Interaction.Toolkit.XRBaseController.GetControllerState (out XRControllerState controllerState) virtual
(Deprecated) Gets the state of the controller.
Parameters
controllerState When this method returns, contains the XRControllerState object representing the state of the controller.
Returns
Returns false.
See also
currentControllerState
GetModelPrefab()
virtual GameObject UnityEngine.XR.Interaction.Toolkit.XRBaseController.GetModelPrefab () protected virtual
Gets the prefab that should be instantiated upon startup.
Returns
Returns the prefab that should be instantiated upon startup.
OnBeforeRender()
virtual void UnityEngine.XR.Interaction.Toolkit.XRBaseController.OnBeforeRender () protected virtual
This method is automatically called for "Just Before Render" input updates for VR devices.
See also
Application.onBeforeRender
Referenced by UnityEngine.XR.Interaction.Toolkit.XRBaseController.OnDisable(), and UnityEngine.XR.Interaction.Toolkit.XRBaseController.OnEnable().
OnDisable()
virtual void UnityEngine.XR.Interaction.Toolkit.XRBaseController.OnDisable () protected virtual
See MonoBehaviour.
Reimplemented in UnityEngine.XR.Interaction.Toolkit.ActionBasedController.
OnEnable()
virtual void UnityEngine.XR.Interaction.Toolkit.XRBaseController.OnEnable () protected virtual
See MonoBehaviour.
Reimplemented in UnityEngine.XR.Interaction.Toolkit.ActionBasedController.
SendHapticImpulse()
virtual bool UnityEngine.XR.Interaction.Toolkit.XRBaseController.SendHapticImpulse (float amplitude, float duration) virtual
Play a haptic impulse on the controller if one is available.
Parameters
amplitude Amplitude (from 0.0 to 1.0) to play impulse at.
duration Duration (in seconds) to play haptic impulse.
Returns
Returns true if successful. Otherwise, returns false.
Reimplemented in UnityEngine.XR.Interaction.Toolkit.ActionBasedController, and UnityEngine.XR.Interaction.Toolkit.XRController.
Referenced by UnityEngine.XR.Interaction.Toolkit.XRBaseControllerInteractor.SendHapticImpulse().
SetControllerState()
virtual void UnityEngine.XR.Interaction.Toolkit.XRBaseController.SetControllerState (XRControllerState controllerState) virtual
(Deprecated) Sets the state of the controller.
Parameters
controllerState The state of the controller to set.
See also
currentControllerState
Update()
void UnityEngine.XR.Interaction.Toolkit.XRBaseController.Update () protected
See MonoBehaviour.
UpdateController()
virtual void UnityEngine.XR.Interaction.Toolkit.XRBaseController.UpdateController () protected virtual
Updates the controller every frame. This is called automatically from Update.
Referenced by UnityEngine.XR.Interaction.Toolkit.XRBaseController.Update().
UpdateControllerModelAnimation()
virtual void UnityEngine.XR.Interaction.Toolkit.XRBaseController.UpdateControllerModelAnimation () protected virtual
Updates the animation on the model instance (if the model contains an Animator). Unity calls this automatically from UpdateController.
See also
animateModel, modelSelectTransition, modelDeSelectTransition
Referenced by UnityEngine.XR.Interaction.Toolkit.XRBaseController.UpdateController().
UpdateInput()
virtual void UnityEngine.XR.Interaction.Toolkit.XRBaseController.UpdateInput (XRControllerState controllerState) protected virtual
Updates the XR Interaction states in the given controller state based on the current inputs of the controller device. Unity calls this automatically during UpdateController so explicit calls to this function are not required.
Parameters
controllerState The state of the controller.
Reimplemented in UnityEngine.XR.Interaction.Toolkit.ActionBasedController, and UnityEngine.XR.Interaction.Toolkit.XRController.
Referenced by UnityEngine.XR.Interaction.Toolkit.XRBaseController.UpdateController().
UpdateTrackingInput()
virtual void UnityEngine.XR.Interaction.Toolkit.XRBaseController.UpdateTrackingInput (XRControllerState controllerState) protected virtual
Updates the pose values in the given controller state based on the current tracking input of the controller device. Unity calls this automatically from OnBeforeRender and UpdateController so explicit calls to this function are not required.
Parameters
controllerState The state of the controller.
Reimplemented in UnityEngine.XR.Interaction.Toolkit.ActionBasedController, and UnityEngine.XR.Interaction.Toolkit.XRController.
Referenced by UnityEngine.XR.Interaction.Toolkit.XRBaseController.OnBeforeRender(), and UnityEngine.XR.Interaction.Toolkit.XRBaseController.UpdateController().
Property Documentation
activateInteractionState
InteractionState UnityEngine.XR.Interaction.Toolkit.XRBaseController.activateInteractionState get
(Read Only) The current activate interaction state.
anchorControlDeadzone
float UnityEngine.XR.Interaction.Toolkit.XRBaseController.anchorControlDeadzone get set
(Deprecated) Defines the deadzone values for device-based input when performing translate or rotate anchor actions.
See also
XRRayInteractor.TranslateAnchor, XRRayInteractor.RotateAnchor
anchorControlDeadzone has been deprecated. Please configure deadzone on the Rotate Anchor and Translate Anchor Actions.
anchorControlOffAxisDeadzone
float UnityEngine.XR.Interaction.Toolkit.XRBaseController.anchorControlOffAxisDeadzone get set
(Deprecated) Defines the off-axis deadzone values for device-based input when performing translate or rotate anchor actions.
See also
Application.onBeforeRender
anchorControlOffAxisDeadzone has been deprecated. Please configure deadzone on the Rotate Anchor and Translate Anchor Actions.
animateModel
bool UnityEngine.XR.Interaction.Toolkit.XRBaseController.animateModel get set
Whether to animate the model in response to interaction events. When enabled, the animation trigger will be set for the corresponding animator component on the controller model when a select or deselect interaction events occurs.
See also
modelSelectTransition, modelDeSelectTransition
currentControllerState
XRControllerState UnityEngine.XR.Interaction.Toolkit.XRBaseController.currentControllerState get set
The current state of the controller.
Referenced by UnityEngine.XR.Interaction.Toolkit.XRBaseController.GetControllerState(), and UnityEngine.XR.Interaction.Toolkit.XRBaseController.SetControllerState().
enableInputActions
bool UnityEngine.XR.Interaction.Toolkit.XRBaseController.enableInputActions get set
Whether input for XR Interaction events is enabled for this controller. When enabled, Unity reads the current input of the controller device each frame.
You can disable this in order to drive the controller state manually instead of from reading current inputs, such as when playing back recorded inputs.
See also
enableInputTracking
enableInputTracking
bool UnityEngine.XR.Interaction.Toolkit.XRBaseController.enableInputTracking get set
Whether input pose tracking is enabled for this controller. When enabled, Unity reads the current tracking pose input of the controller device each frame.
You can disable this in order to drive the controller state manually instead of from reading current inputs, such as when playing back recorded pose inputs.
See also
enableInputActions
hideControllerModel
bool UnityEngine.XR.Interaction.Toolkit.XRBaseController.hideControllerModel get set
Whether to hide the controller model.
See also
model, XRBaseControllerInteractor.hideControllerOnSelect
model
Transform UnityEngine.XR.Interaction.Toolkit.XRBaseController.model get set
The instance of the controller model in the scene. You can set this to an existing object instead of using modelPrefab.
If set, it should reference a child GameObject of this behavior so it will update with the controller pose.
modelDeSelectTransition
string UnityEngine.XR.Interaction.Toolkit.XRBaseController.modelDeSelectTransition get set
The animation trigger name to activate upon deselecting.
See also
Animator.SetTrigger(string)
modelParent
Transform UnityEngine.XR.Interaction.Toolkit.XRBaseController.modelParent get set
The transform that this behavior uses as the parent for the model prefab when it is instantiated.
Automatically instantiated and set in Awake if not already set. Setting this will not automatically destroy the previous object.
modelPrefab
Transform UnityEngine.XR.Interaction.Toolkit.XRBaseController.modelPrefab get set
The prefab of a controller model to show for this controller that this behavior automatically instantiates.
This behavior automatically instantiates an instance of the prefab as a child of modelParent upon startup unless model is already set, in which case this value is ignored.
See also
model
modelSelectTransition
string UnityEngine.XR.Interaction.Toolkit.XRBaseController.modelSelectTransition get set
The animation trigger name to activate upon selecting.
See also
Animator.SetTrigger(string)
modelTransform
Transform UnityEngine.XR.Interaction.Toolkit.XRBaseController.modelTransform get set
modelTransform has been deprecated due to being renamed. Use modelParent instead.
selectInteractionState
InteractionState UnityEngine.XR.Interaction.Toolkit.XRBaseController.selectInteractionState get
(Read Only) The current select interaction state.
Referenced by UnityEngine.XR.Interaction.Toolkit.XRBaseControllerInteractor.PreprocessInteractor().
uiPressInteractionState
InteractionState UnityEngine.XR.Interaction.Toolkit.XRBaseController.uiPressInteractionState get
(Read Only) The current UI press interaction state.
updateTrackingType
UpdateType UnityEngine.XR.Interaction.Toolkit.XRBaseController.updateTrackingType get set
The time within the frame that the controller samples tracking input.
See also
UpdateType
The documentation for this class was generated from the following files:
C:/Users/Lykos/Desktop/Projects/Capstone/VRGames/Library/PackageCache/com.unity.xr.interaction.toolkit@2.0.2/Runtime/Interaction/Controllers/XRBaseController.cs
C:/Users/Lykos/Desktop/Projects/Capstone/VRGames/Library/PackageCache/com.unity.xr.interaction.toolkit@2.0.2/Runtime/Interaction/Controllers/XRBaseController.deprecated.cs