VRCapstoneGames: UnityEngine.InputSystem.InputActionMap Class Reference
UnityEngine.InputSystem.InputActionMap Class Reference sealed
A mechanism for collecting a series of input actions (see InputAction) and treating them as a group.
Classes
struct BindingJson
struct BindingOverrideJson
struct BindingOverrideListJson
struct DeviceArray
struct ReadActionJson
struct ReadFileJson
struct ReadMapJson
struct WriteActionJson
struct WriteFileJson
struct WriteMapJson
Public Member Functions
InputActionMap ()
InputActionMap (string name)
Construct an action map with the given name.
void Dispose ()
Release internal state held on to by the action map.
InputAction FindAction (string actionNameOrId, bool throwIfNotFound=false)
Find an action in the map by name or ID.
InputAction FindAction (Guid id)
Find an action by ID.
bool IsUsableWithDevice (InputDevice device)
Check whether there are any bindings in the action map that can bind to controls on the given device.
void Enable ()
Enable all the actions in the map.
void Disable ()
Disable all the actions in the map.
InputActionMap Clone ()
Produce an identical copy of the action map with its actions and bindings.
bool Contains (InputAction action)
Return true if the action map contains the given action.
override string ToString ()
Return a string representation of the action map useful for debugging.
IEnumerator< InputAction > GetEnumerator ()
Enumerate the actions in the map.
int FindBinding (InputBinding mask, out InputAction action)
Find the index of the first binding that matches the given mask.
Parameters
mask A binding. See InputBinding.Matches for details.
action Receives the action on which the binding was found. If none was found, will be set to null.
Returns
Index into InputAction.bindings of action of the binding that matches mask . If no binding matches, will return -1.
For details about matching bindings by a mask, see InputBinding.Matches.
var index = playerInput.actions.FindBinding(
    new InputBinding { path = "<Gamepad>/buttonSouth" },
    out var action);
if (index != -1)
    Debug.Log($"The A button is bound to {action}");
string ToJson ()
Convert the action map to JSON format.
void OnBeforeSerialize ()
Called by Unity before the action map is serialized using Unity's serialization system.
void OnAfterDeserialize ()
Called by Unity after the action map has been deserialized using Unity's serialization system.
Static Public Member Functions
static InputActionMap[] FromJson (string json)
Load one or more action maps from JSON.
static string ToJson (IEnumerable< InputActionMap > maps)
Convert a set of action maps to JSON format.
Properties
string name [get]
Name of the action map.
InputActionAsset asset [get]
If the action map is part of an asset, this refers to the asset. Otherwise it is null.
Guid id [get]
A stable, unique identifier for the map.
bool enabled [get]
Whether any action in the map is currently enabled.
ReadOnlyArray< InputAction > actions [get]
List of actions contained in the map.
ReadOnlyArray< InputBinding > bindings [get]
List of bindings contained in the map.
ReadOnlyArray< InputControlScheme > controlSchemes [get]
Control schemes defined for the action map.
InputBinding? bindingMask [get, set]
Binding mask to apply to all actions in the asset.
ReadOnlyArray< InputDevice >? devices [get, set]
Set of devices that bindings in the action map can bind to.
InputAction this[string actionNameOrId] [get]
Look up an action by name or ID.
Action< InputAction.CallbackContext > actionTriggered
Add or remove a callback that is triggered when an action in the map changes its phase.
Properties inherited from UnityEngine.InputSystem.IInputActionCollection2
Properties inherited from UnityEngine.InputSystem.IInputActionCollection
Detailed Description
A mechanism for collecting a series of input actions (see InputAction) and treating them as a group.
Each action map is a named collection of bindings and actions. Both are stored as a flat list. The bindings are available through the bindings property and the actions are available through the actions property.
The actions in a map are owned by the map. No action can appear in two maps at the same time. To find the action map an action belongs to, use the InputAction.actionMap property. Note that actions can also stand on their own and thus do not necessarily need to belong to a map (in which case the InputAction.actionMap property is null).
Within a map, all actions have to have names and each action name must be unique. The InputBinding.action property of bindings in a map are resolved within the actions in the map. Looking up actions by name can be done through FindAction(string,bool).
The name of the map itself can be empty, except if the map is part of an InputActionAsset in which case it is required to have a name which also must be unique within the asset.
Action maps are most useful for grouping actions that contextually belong together. For example, one common usage is to separate the actions that can be performed in the UI or in the main menu from those that can be performed during gameplay. However, even within gameplay, multiple action maps can be employed. For example, one could have different action maps for driving and for walking plus one more map for the actions shared between the two modes.
Action maps are usually created in the action editor as part of InputActionAssets. However, they can also be created standing on their own directly in code or from JSON (see FromJson).
// Create a free-standing action map.
var map = new InputActionMap();
// Add some actions and bindings to it.
map.AddAction("action1", binding: "<Keyboard>/space");
map.AddAction("action2", binding: "<Gamepad>/buttonSouth");
Actions in action maps, like actions existing by themselves outside of action maps, do not actively process input except if enabled. Actions can either be enabled individually (see InputAction.Enable and InputAction.Disable) or in bulk by enabling and disabling the entire map (see Enable and Disable).
See also
InputActionAsset, InputAction
Constructor & Destructor Documentation
InputActionMap() [1/2]
UnityEngine.InputSystem.InputActionMap.InputActionMap ()
InputActionMap() [2/2]
UnityEngine.InputSystem.InputActionMap.InputActionMap (string name)
Construct an action map with the given name.
Parameters
name Name to give to the action map. By default null, i.e. does not assign a name to the map.
Member Function Documentation
Clone()
InputActionMap UnityEngine.InputSystem.InputActionMap.Clone ()
Produce an identical copy of the action map with its actions and bindings.
Returns
A copy of the action map.
If the action map is part of an InputActionAsset, the clone will not be. It will be a free-standing action map and asset will be null.
Note that the IDs for the map itself as well as for its actions and bindings are not copied. Instead, new IDs will be assigned. Also, callbacks installed on actions or on the map itself will not be copied over.
Contains()
bool UnityEngine.InputSystem.InputActionMap.Contains (InputAction action)
Return true if the action map contains the given action.
Parameters
action An input action. Can be null.
Returns
True if the action map contains action , false otherwise.
Implements UnityEngine.InputSystem.IInputActionCollection.
Disable()
void UnityEngine.InputSystem.InputActionMap.Disable ()
Disable all the actions in the map.
This is equivalent to calling InputAction.Disable on each action in actions, but is more efficient as the actions will get disabled in bulk.
See also
Enable, enabled
Implements UnityEngine.InputSystem.IInputActionCollection.
Referenced by UnityEngine.InputSystem.PlayerInput.DeactivateInput(), UnityEngine.InputSystem.DefaultInputActions.PlayerActions.Disable(), UnityEngine.InputSystem.DefaultInputActions.UIActions.Disable(), UnityEngine.InputSystem.Samples.InGameHints.InGameHintsActions.GameplayActions.Disable(), and SimpleControls.GameplayActions.Disable().
Dispose()
void UnityEngine.InputSystem.InputActionMap.Dispose ()
Release internal state held on to by the action map.
Once actions in a map are enabled, the map will allocate a block of state internally that it will hold on to until disposed of. All actions in the map will share the same internal state. Also, if the map is part of an InputActionAsset all maps and actions in the same asset will share the same internal state.
Note that the internal state holds on to GC heap memory as well as memory from the unmanaged, C++ heap.
Enable()
void UnityEngine.InputSystem.InputActionMap.Enable ()
Enable all the actions in the map.
This is equivalent to calling InputAction.Enable on each action in actions, but is more efficient as the actions will get enabled in bulk.
See also
Disable, enabled
Implements UnityEngine.InputSystem.IInputActionCollection.
Referenced by UnityEngine.InputSystem.PlayerInput.ActivateInput(), UnityEngine.InputSystem.DefaultInputActions.PlayerActions.Enable(), UnityEngine.InputSystem.DefaultInputActions.UIActions.Enable(), UnityEngine.InputSystem.Samples.InGameHints.InGameHintsActions.GameplayActions.Enable(), and SimpleControls.GameplayActions.Enable().
FindAction() [1/2]
InputAction UnityEngine.InputSystem.InputActionMap.FindAction (Guid id)
Find an action by ID.
Parameters
id ID (as in InputAction.id) of the action.
Returns
The action with the given ID or null if no action in the map has the given ID.
See also
FindAction(string,bool)
FindAction() [2/2]
InputAction UnityEngine.InputSystem.InputActionMap.FindAction (string actionNameOrId, bool throwIfNotFound = false)
Find an action in the map by name or ID.
Parameters
actionNameOrId Name (as in InputAction.name) or ID (as in InputAction.id) of the action. Note that matching of names is case-insensitive.
Returns
The action with the given name or ID or null if no matching action was found.
Exceptions
ArgumentNullException actionNameOrId is null.
See also
FindAction(Guid)
Implements UnityEngine.InputSystem.IInputActionCollection2.
Referenced by UnityEngine.InputSystem.DefaultInputActions.DefaultInputActions(), UnityEngine.InputSystem.InputActionAsset.FindAction(), UnityEngine.InputSystem.InputActionAsset.FindAction(), UnityEngine.InputSystem.InputActionMap.FindBinding(), UnityEngine.InputSystem.Samples.InGameHints.InGameHintsActions.InGameHintsActions(), and SimpleControls.SimpleControls().
FindBinding()
int UnityEngine.InputSystem.InputActionMap.FindBinding (InputBinding mask, out InputAction action)
Find the index of the first binding that matches the given mask.
Parameters
mask A binding. See InputBinding.Matches for details.
action Receives the action on which the binding was found. If none was found, will be set to null.
Returns
Index into InputAction.bindings of action of the binding that matches mask . If no binding matches, will return -1.
For details about matching bindings by a mask, see InputBinding.Matches.
var index = playerInput.actions.FindBinding(
    new InputBinding { path = "<Gamepad>/buttonSouth" },
    out var action);
if (index != -1)
    Debug.Log($"The A button is bound to {action}");
Implements UnityEngine.InputSystem.IInputActionCollection2.
Referenced by UnityEngine.InputSystem.InputActionAsset.FindBinding().
FromJson()
static InputActionMap[] UnityEngine.InputSystem.InputActionMap.FromJson (string json) static
Load one or more action maps from JSON.
Parameters
json JSON representation of the action maps. Can be empty.
Exceptions
ArgumentNullException json is null.
Returns
The array of action maps (may be empty) read from the given JSON string. Will not be null.
Note that the format used by this method is different than what you get if you call JsonUtility.ToJson on an InputActionMap instance. In other words, the JSON format is not identical to the Unity serialized object representation of the asset.
var maps = InputActionMap.FromJson(@"
    {
        ""maps"" : [
            {
                ""name"" : ""Gameplay"",
                ""actions"" : [
                    { ""name"" : ""fire"", ""type"" : ""button"" }
                ],
                ""bindings"" : [
                    { ""path"" : ""<Gamepad>/leftTrigger"", ""action"" : ""fire"" }
                ],
            }
        ]
    }
");
See also
InputActionAsset.FromJson, ToJson(IEnumerable<InputActionMap>)
GetEnumerator()
IEnumerator< InputAction > UnityEngine.InputSystem.InputActionMap.GetEnumerator ()
Enumerate the actions in the map.
Returns
An enumerator going over the actions in the map.
This method supports to generically iterate over the actions in a map. However, it will usually lead to GC allocation. Iterating directly over actions avoids allocating GC memory.
IsUsableWithDevice()
bool UnityEngine.InputSystem.InputActionMap.IsUsableWithDevice (InputDevice device)
Check whether there are any bindings in the action map that can bind to controls on the given device.
Parameters
device An input device.
Returns
True if any of the bindings in the map can resolve to controls on the device, false otherwise.
Exceptions
ArgumentNullException device is null.
The logic is entirely based on the contents of bindings and, more specifically, InputBinding.effectivePath of each binding. Each path is checked using InputControlPath.Matches. If any path matches, the method returns true.
Properties such as devices and bindingMask are ignored.
// Create action map with two actions and bindings.
var actionMap = new InputActionMap();
actionMap.AddAction("action1", binding: "<Gamepad>/buttonSouth");
actionMap.AddAction("action2", binding: "<XRController{LeftHand}>/{PrimaryAction}");
//
var gamepad = InputSystem.AddDevice<Gamepad>();
var xrController = InputSystem.AddDevice<XRController>();
// Returns true:
actionMap.IsUsableWith(gamepad);
// Returns false: (the XRController does not have the LeftHand usage assigned to it)
actionMap.IsUsableWith(xrController);
OnAfterDeserialize()
void UnityEngine.InputSystem.InputActionMap.OnAfterDeserialize ()
Called by Unity after the action map has been deserialized using Unity's serialization system.
OnBeforeSerialize()
void UnityEngine.InputSystem.InputActionMap.OnBeforeSerialize ()
Called by Unity before the action map is serialized using Unity's serialization system.
ToJson() [1/2]
string UnityEngine.InputSystem.InputActionMap.ToJson ()
Convert the action map to JSON format.
Returns
A JSON representation of the action map.
The result of this method can be loaded with FromJson.
Note that the format used by this method is different than what you get if you call JsonUtility.ToJson on an InputActionMap instance. In other words, the JSON format is not identical to the Unity serialized object representation of the asset.
ToJson() [2/2]
static string UnityEngine.InputSystem.InputActionMap.ToJson (IEnumerable< InputActionMap > maps) static
Convert a set of action maps to JSON format.
Parameters
maps List of action maps to serialize.
Exceptions
ArgumentNullException maps is null.
Returns
JSON representation of the given action maps.
The result of this method can be loaded with FromJson.
Note that the format used by this method is different than what you get if you call JsonUtility.ToJson on an InputActionMap instance. In other words, the JSON format is not identical to the Unity serialized object representation of the asset.
See also
FromJson
ToString()
override string UnityEngine.InputSystem.InputActionMap.ToString ()
Return a string representation of the action map useful for debugging.
Returns
A string representation of the action map.
For unnamed action maps, this will always be "&lt;Unnamed Action Map&gt;".
Property Documentation
actions
ReadOnlyArray<InputAction> UnityEngine.InputSystem.InputActionMap.actions get
List of actions contained in the map.
Collection of actions belonging to the map.
Actions are owned by their map. The same action cannot appear in multiple maps.
Accessing this property. Note that values returned by the property become invalid if the setup of actions in a map is changed.
See also
InputAction.actionMap
Referenced by UnityEngine.InputSystem.InputActionMap.Clone(), UnityEngine.InputSystem.InputActionAsset.GetEnumerator(), and UnityEngine.InputSystem.InputActionMap.GetEnumerator().
actionTriggered
Action<InputAction.CallbackContext> UnityEngine.InputSystem.InputActionMap.actionTriggered add remove
Add or remove a callback that is triggered when an action in the map changes its phase.
REVIEW: inconsistent naming; elsewhere we use "onActionTriggered" (which in turn is inconsistent with InputAction.started etc)
See also
InputAction.started, InputAction.performed, InputAction.canceled
asset
InputActionAsset UnityEngine.InputSystem.InputActionMap.asset get
If the action map is part of an asset, this refers to the asset. Otherwise it is null.
Asset to which the action map belongs.
Referenced by UnityEngine.InputSystem.PlayerInput.ActionEvent.ActionEvent(), and UnityEngine.InputSystem.InputActionRebindingExtensions.RebindingOperation.WithTargetBinding().
bindingMask
InputBinding? UnityEngine.InputSystem.InputActionMap.bindingMask get set
Binding mask to apply to all actions in the asset.
Optional mask that determines which bindings in the action map to enable.
Binding masks can be applied at three different levels: for an entire asset through InputActionAsset.bindingMask, for a specific map through this property, and for single actions through InputAction.bindingMask. By default, none of the masks will be set (that is, they will be null).
When an action is enabled, all the binding masks that apply to it are taken into account. Specifically, this means that any given binding on the action will be enabled only if it matches the mask applied to the asset, the mask applied to the map that contains the action, and the mask applied to the action itself. All the masks are individually optional.
Masks are matched against bindings using InputBinding.Matches.
Note that if you modify the masks applicable to an action while it is enabled, the action's InputAction.controls will get updated immediately to respect the mask. To avoid repeated binding resolution, it is most efficient to apply binding masks before enabling actions.
Binding masks are non-destructive. All the bindings on the action are left in place. Setting a mask will not affect the value of the InputAction.bindings and bindings properties.
See also
InputBinding.MaskByGroup, InputAction.bindingMask, InputActionAsset.bindingMask
Implements UnityEngine.InputSystem.IInputActionCollection.
bindings
ReadOnlyArray<InputBinding> UnityEngine.InputSystem.InputActionMap.bindings get
List of bindings contained in the map.
Collection of bindings in the map.
InputBindings are owned by action maps and not by individual actions.
Bindings that trigger actions refer to the action by InputAction.name or InputAction.id.
Accessing this property does not allocate. Note that values returned by the property become invalid if the setup of bindings in a map is changed.
See also
InputAction.bindings
Implements UnityEngine.InputSystem.IInputActionCollection2.
Referenced by UnityEngine.InputSystem.InputActionMap.Clone(), and UnityEngine.InputSystem.InputActionMap.FindBinding().
controlSchemes
ReadOnlyArray<InputControlScheme> UnityEngine.InputSystem.InputActionMap.controlSchemes get
Control schemes defined for the action map.
List of available control schemes.
Control schemes can only be defined at the level of InputActionAssets. For action maps that are part of assets, this property will return the control schemes from the asset. For free-standing action maps, this will return an empty list.
See also
InputActionAsset.controlSchemes
Implements UnityEngine.InputSystem.IInputActionCollection.
devices
ReadOnlyArray<InputDevice>? UnityEngine.InputSystem.InputActionMap.devices get set
Set of devices that bindings in the action map can bind to.
Optional set of devices to use by bindings in the map.
By default (with this property being null), bindings will bind to any of the controls available through InputSystem.devices, that is, controls from all devices in the system will be used.
By setting this property, binding resolution can instead be restricted to just specific devices. This restriction can either be applied to an entire asset using InputActionMap.devices or to specific action maps by using this property. Note that if both this property and InputActionAsset.devices is set for a specific action map, the list of devices on the action map will take precedence and the list on the asset will be ignored for bindings in that action map.
// Create an action map containing a single action with a gamepad binding.
var actionMap = new InputActionMap();
var fireAction = actionMap.AddAction("Fire", binding: "<Gamepad>/buttonSouth");
asset.AddActionMap(actionMap);
// Let's assume we have two gamepads connected. If we enable the
// action map now, the 'Fire' action will bind to both.
actionMap.Enable();
// This will print two controls.
Debug.Log(string.Join("\n", fireAction.controls));
// To restrict the setup to just the first gamepad, we can assign
// to the 'devices' property.
actionMap.devices = new InputDevice[] { Gamepad.all[0] };
// Now this will print only one control.
Debug.Log(string.Join("\n", fireAction.controls));
See also
InputActionAsset.devices
Implements UnityEngine.InputSystem.IInputActionCollection.
enabled
bool UnityEngine.InputSystem.InputActionMap.enabled get
Whether any action in the map is currently enabled.
True if any action in actions is currently enabled.
See also
InputAction.enabled, Enable, InputAction.Enable
Referenced by UnityEngine.InputSystem.InputActionMap.Disable().
id
Guid UnityEngine.InputSystem.InputActionMap.id get
A stable, unique identifier for the map.
Unique ID for the action map.
This can be used instead of the name to refer to the action map. Doing so allows referring to the map such that renaming it does not break references.
See also
InputAction.id
name
string UnityEngine.InputSystem.InputActionMap.name get
Name of the action map.
Name of the action map.
For action maps that are part of InputActionAssets, this will always be a non-null, non-empty string that is unique within the maps in the asset. For action maps that are standing on their own, this can be null or empty.
Referenced by UnityEngine.InputSystem.InputActionMap.InputActionMap(), and UnityEngine.InputSystem.InputAction.ToString().
this[string actionNameOrId]
InputAction UnityEngine.InputSystem.InputActionMap.this[string actionNameOrId] get
Look up an action by name or ID.
Parameters
actionNameOrId Name (as in InputAction.name) or ID (as in InputAction.id) of the action. Note that matching of names is case-insensitive.
Exceptions
ArgumentNullException actionNameOrId is null.
KeyNotFoundException No action with the name or ID of actionNameOrId was found in the action map.
This method is equivalent to FindAction(string,bool) except it throws KeyNotFoundException if no action with the given name or ID can be found.
See also
FindAction(string,bool), FindAction(Guid)
actions
The documentation for this class was generated from the following file:
C:/Users/Lykos/Desktop/Projects/Capstone/VRGames/Library/PackageCache/com.unity.inputsystem@1.3.0/InputSystem/Actions/InputActionMap.cs