VRCapstoneGames: OVROverlayMeshGenerator Class Reference
OVROverlayMeshGenerator Class Reference
When attached to a GameObject with an OVROverlay component, OVROverlayMeshGenerator will use a mesh renderer to preview the appearance of the OVROverlay as it would appear as a TimeWarp overlay on a headset.
Public Member Functions
void SetOverlay (OVROverlay overlay)
Static Public Member Functions
static void GenerateMesh (List< Vector3 > verts, List< Vector2 > uvs, List< int > tris, OVROverlay.OverlayShape shape, Vector3 position, Quaternion rotation, Vector3 scale, Rect rect)
static void BuildSphere (List< Vector3 > verts, List< Vector2 > uv, List< int > triangles, Vector3 position, Quaternion rotation, Vector3 scale, Rect rect, float worldScale=800, int latitudes=128, int longitudes=128, float expand_coef=1.0f)
static void BuildCube (List< Vector3 > verts, List< Vector2 > uv, List< int > triangles, Vector3 position, Quaternion rotation, Vector3 scale, float worldScale=800, int subQuads=1, float expand_coef=1.01f)
static void BuildQuad (List< Vector3 > verts, List< Vector2 > uv, List< int > triangles, Rect rect)
static void BuildHemicylinder (List< Vector3 > verts, List< Vector2 > uv, List< int > triangles, Vector3 scale, Rect rect, int longitudes=128)
Protected Member Functions
void Awake ()
void OnEnable ()
void OnDisable ()
Detailed Description
When attached to a GameObject with an OVROverlay component, OVROverlayMeshGenerator will use a mesh renderer to preview the appearance of the OVROverlay as it would appear as a TimeWarp overlay on a headset.
Member Function Documentation
Awake()
void OVROverlayMeshGenerator.Awake () protected
BuildCube()
static void OVROverlayMeshGenerator.BuildCube (List< Vector3 > verts, List< Vector2 > uv, List< int > triangles, Vector3 position, Quaternion rotation, Vector3 scale, float worldScale = 800, int subQuads = 1, float expand_coef = 1::01f) static
Referenced by GenerateMesh().
BuildHemicylinder()
static void OVROverlayMeshGenerator.BuildHemicylinder (List< Vector3 > verts, List< Vector2 > uv, List< int > triangles, Vector3 scale, Rect rect, int longitudes = 128) static
Referenced by GenerateMesh().
BuildQuad()
static void OVROverlayMeshGenerator.BuildQuad (List< Vector3 > verts, List< Vector2 > uv, List< int > triangles, Rect rect) static
Referenced by GenerateMesh().
BuildSphere()
static void OVROverlayMeshGenerator.BuildSphere (List< Vector3 > verts, List< Vector2 > uv, List< int > triangles, Vector3 position, Quaternion rotation, Vector3 scale, Rect rect, float worldScale = 800, int latitudes = 128, int longitudes = 128, float expand_coef = 1::0f) static
Referenced by GenerateMesh().
GenerateMesh()
static void OVROverlayMeshGenerator.GenerateMesh (List< Vector3 > verts, List< Vector2 > uvs, List< int > tris, OVROverlay::OverlayShape shape, Vector3 position, Quaternion rotation, Vector3 scale, Rect rect) static
OnDisable()
void OVROverlayMeshGenerator.OnDisable () protected
OnEnable()
void OVROverlayMeshGenerator.OnEnable () protected
SetOverlay()
void OVROverlayMeshGenerator.SetOverlay (OVROverlay overlay)
The documentation for this class was generated from the following file:
C:/Users/Lykos/Desktop/Projects/Capstone/VRGames/Assets/ThirdParty/Oculus/VR/Scripts/OVROverlayMeshGenerator.cs