VRCapstoneGames: UnityEngine.XR.InteractionSubsystems.SubsystemLifecycleManager< TSubsystem, TSubsystemDescriptor > Class Template Reference
UnityEngine.XR.InteractionSubsystems.SubsystemLifecycleManager< TSubsystem, TSubsystemDescriptor > Class Template Reference
A base class for subsystems whose lifetime is managed by a MonoBehaviour.
Protected Member Functions
virtual TSubsystem CreateSubsystem ()
Creates a TSubsystem.
void CreateSubsystemIfNecessary ()
Creates a subsystem if subsystem is null.
virtual void OnEnable ()
Creates the TSubsystem.
virtual void OnDisable ()
Stops the TSubsystem.
virtual void OnDestroy ()
Destroys the TSubsystem.
virtual void OnBeforeStart ()
Invoked after creating the subsystem and before calling Start on it. The subsystem is not null.
virtual void OnAfterStart ()
Invoked after calling Start on it the Subsystem. The subsystem is not null.
Properties
TSubsystem subsystem [get]
Get the TSubsystem whose lifetime this component manages.
Detailed Description
A base class for subsystems whose lifetime is managed by a MonoBehaviour.
Template Parameters
TSubsystem The Subsystem which provides this manager data.
TSubsystemDescriptor The SubsystemDescriptor required to create the Subsystem.
Type Constraints
TSubsystem : Subsystem<TSubsystemDescriptor>
TSubsystemDescriptor : SubsystemDescriptor<TSubsystem>
Member Function Documentation
CreateSubsystem()
virtual TSubsystem UnityEngine.XR.InteractionSubsystems.SubsystemLifecycleManager< TSubsystem, TSubsystemDescriptor >.CreateSubsystem () protected virtual
Creates a TSubsystem.
Returns
The first Subsystem of matching the TSubsystemDescriptor, or null if there aren't any.
Referenced by UnityEngine.XR.InteractionSubsystems.SubsystemLifecycleManager< TSubsystem, TSubsystemDescriptor >.CreateSubsystemIfNecessary().
CreateSubsystemIfNecessary()
void UnityEngine.XR.InteractionSubsystems.SubsystemLifecycleManager< TSubsystem, TSubsystemDescriptor >.CreateSubsystemIfNecessary () protected
Creates a subsystem if subsystem is null.
Referenced by UnityEngine.XR.InteractionSubsystems.SubsystemLifecycleManager< TSubsystem, TSubsystemDescriptor >.OnEnable().
OnAfterStart()
virtual void UnityEngine.XR.InteractionSubsystems.SubsystemLifecycleManager< TSubsystem, TSubsystemDescriptor >.OnAfterStart () protected virtual
Invoked after calling Start on it the Subsystem. The subsystem is not null.
Referenced by UnityEngine.XR.InteractionSubsystems.SubsystemLifecycleManager< TSubsystem, TSubsystemDescriptor >.OnEnable().
OnBeforeStart()
virtual void UnityEngine.XR.InteractionSubsystems.SubsystemLifecycleManager< TSubsystem, TSubsystemDescriptor >.OnBeforeStart () protected virtual
Invoked after creating the subsystem and before calling Start on it. The subsystem is not null.
Referenced by UnityEngine.XR.InteractionSubsystems.SubsystemLifecycleManager< TSubsystem, TSubsystemDescriptor >.OnEnable().
OnDestroy()
virtual void UnityEngine.XR.InteractionSubsystems.SubsystemLifecycleManager< TSubsystem, TSubsystemDescriptor >.OnDestroy () protected virtual
Destroys the TSubsystem.
OnDisable()
virtual void UnityEngine.XR.InteractionSubsystems.SubsystemLifecycleManager< TSubsystem, TSubsystemDescriptor >.OnDisable () protected virtual
Stops the TSubsystem.
OnEnable()
virtual void UnityEngine.XR.InteractionSubsystems.SubsystemLifecycleManager< TSubsystem, TSubsystemDescriptor >.OnEnable () protected virtual
Creates the TSubsystem.
Property Documentation
subsystem
TSubsystem UnityEngine.XR.InteractionSubsystems.SubsystemLifecycleManager< TSubsystem, TSubsystemDescriptor >.subsystem get
Get the TSubsystem whose lifetime this component manages.
Referenced by UnityEngine.XR.InteractionSubsystems.SubsystemLifecycleManager< TSubsystem, TSubsystemDescriptor >.CreateSubsystemIfNecessary(), UnityEngine.XR.InteractionSubsystems.SubsystemLifecycleManager< TSubsystem, TSubsystemDescriptor >.OnDestroy(), UnityEngine.XR.InteractionSubsystems.SubsystemLifecycleManager< TSubsystem, TSubsystemDescriptor >.OnDisable(), and UnityEngine.XR.InteractionSubsystems.SubsystemLifecycleManager< TSubsystem, TSubsystemDescriptor >.OnEnable().
The documentation for this class was generated from the following file:
C:/Users/Lykos/Desktop/Projects/Capstone/VRGames/Library/PackageCache/com.unity.xr.interactionsubsystems@1.0.1/Runtime/SubsystemLifecycleManager.cs