VRCapstoneGames: AnchorSession Class Reference
AnchorSession Class Reference abstract
Public Types
enum StorageLocation { LOCAL = 0 }
Public Member Functions
ulong CreateSpatialAnchor (Transform T_UnityWorld_Anchor)
void DestroyAnchor (ulong anchorHandle)
void SaveAnchor (ulong anchorHandle, StorageLocation location)
void EraseAnchor (ulong anchorHandle)
void QueryAllLocalAnchors ()
Static Public Member Functions
static void Log (string message)
Public Attributes
Dictionary< ulong, Anchor > handleToAnchor = new Dictionary<ulong, Anchor>()
Static Public Attributes
static AnchorSession Instance
const ulong kInvalidHandle = ulong.MaxValue
Protected Member Functions
virtual void Awake ()
Static Protected Member Functions
static bool isFlagSet (uint bitset, uint flag)
Protected Attributes
GameObject anchorPrefab_ = null
Static Protected Attributes
const int maxEvents = 5
const float eventPollingRate = 0.1f
Member Enumeration Documentation
StorageLocation
enum AnchorSession.StorageLocation
Enumerator
LOCAL
Member Function Documentation
Awake()
virtual void AnchorSession.Awake () protected virtual
CreateSpatialAnchor()
ulong AnchorSession.CreateSpatialAnchor (Transform T_UnityWorld_Anchor) abstract
DestroyAnchor()
void AnchorSession.DestroyAnchor (ulong anchorHandle) abstract
EraseAnchor()
void AnchorSession.EraseAnchor (ulong anchorHandle) abstract
isFlagSet()
static bool AnchorSession.isFlagSet (uint bitset, uint flag) static protected
Log()
static void AnchorSession.Log (string message) static
Referenced by SpatialAnchorSession.CreateSpatialAnchor(), SpatialAnchorSession.DestroyAnchor(), SpatialAnchorSession.EraseAnchor(), AnchorSpawner.PlaceAnchorAtTransform(), SpatialAnchorSession.QueryAllLocalAnchors(), SpatialAnchorSession.QueryAnchorByUuid(), SpatialAnchorSession.SaveAnchor(), AnchorHelpers.StringToUuid(), and AnchorHelpers.UuidToString().
QueryAllLocalAnchors()
void AnchorSession.QueryAllLocalAnchors () abstract
SaveAnchor()
void AnchorSession.SaveAnchor (ulong anchorHandle, StorageLocation location) abstract
Member Data Documentation
anchorPrefab_
GameObject AnchorSession.anchorPrefab_ = null protected
Referenced by Awake().
eventPollingRate
const float AnchorSession.eventPollingRate = 0.1f static protected
handleToAnchor
Dictionary<ulong, Anchor> AnchorSession.handleToAnchor = new Dictionary<ulong, Anchor>()
Referenced by SpatialAnchorSession.DestroyAnchor(), and SpatialAnchorSession.EraseAnchor().
Instance
AnchorSession AnchorSession.Instance static
Referenced by Awake(), Anchor.OnEraseButtonPressed(), Anchor.OnHideButtonPressed(), AnchorUIManager.OnLoadAnchorsButtonPressed(), Anchor.OnSaveLocalButtonPressed(), and AnchorSpawner.PlaceAnchorAtTransform().
kInvalidHandle
const ulong AnchorSession.kInvalidHandle = ulong.MaxValue static
Referenced by SpatialAnchorSession.CreateSpatialAnchor(), and AnchorSpawner.PlaceAnchorAtTransform().
maxEvents
const int AnchorSession.maxEvents = 5 static protected
The documentation for this class was generated from the following file:
C:/Users/Lykos/Desktop/Projects/Capstone/VRGames/Assets/ThirdParty/Oculus/SampleFramework/Usage/SpatialAnchor/Scripts/AnchorSession.cs