VRGames: Oculus.Interaction.InteractableColorVisual Class Reference
Oculus.Interaction.InteractableColorVisual Class Reference
Classes
class ColorState
Public Member Functions
void InjectAllInteractableColorVisual (IInteractableView interactableView, MaterialPropertyBlockEditor editor)
void InjectInteractableView (IInteractableView interactableview)
void InjectMaterialPropertyBlockEditor (MaterialPropertyBlockEditor editor)
void InjectOptionalColorShaderPropertyName (string colorShaderPropertyName)
void InjectOptionalNormalColorState (ColorState normalColorState)
void InjectOptionalHoverColorState (ColorState hoverColorState)
void InjectOptionalSelectColorState (ColorState selectColorState)
Protected Member Functions
virtual void Awake ()
virtual void Start ()
virtual void OnEnable ()
virtual void OnDisable ()
virtual void UpdateVisual ()
Protected Attributes
bool _started = false
Member Function Documentation
Awake()
virtual void Oculus.Interaction.InteractableColorVisual.Awake () protected virtual
InjectAllInteractableColorVisual()
void Oculus.Interaction.InteractableColorVisual.InjectAllInteractableColorVisual (IInteractableView interactableView, MaterialPropertyBlockEditor editor)
InjectInteractableView()
void Oculus.Interaction.InteractableColorVisual.InjectInteractableView (IInteractableView interactableview)
Referenced by Oculus.Interaction.InteractableColorVisual.InjectAllInteractableColorVisual().
InjectMaterialPropertyBlockEditor()
void Oculus.Interaction.InteractableColorVisual.InjectMaterialPropertyBlockEditor (MaterialPropertyBlockEditor editor)
Referenced by Oculus.Interaction.InteractableColorVisual.InjectAllInteractableColorVisual().
InjectOptionalColorShaderPropertyName()
void Oculus.Interaction.InteractableColorVisual.InjectOptionalColorShaderPropertyName (string colorShaderPropertyName)
InjectOptionalHoverColorState()
void Oculus.Interaction.InteractableColorVisual.InjectOptionalHoverColorState (ColorState hoverColorState)
InjectOptionalNormalColorState()
void Oculus.Interaction.InteractableColorVisual.InjectOptionalNormalColorState (ColorState normalColorState)
InjectOptionalSelectColorState()
void Oculus.Interaction.InteractableColorVisual.InjectOptionalSelectColorState (ColorState selectColorState)
OnDisable()
virtual void Oculus.Interaction.InteractableColorVisual.OnDisable () protected virtual
OnEnable()
virtual void Oculus.Interaction.InteractableColorVisual.OnEnable () protected virtual
Start()
virtual void Oculus.Interaction.InteractableColorVisual.Start () protected virtual
UpdateVisual()
virtual void Oculus.Interaction.InteractableColorVisual.UpdateVisual () protected virtual
Referenced by Oculus.Interaction.InteractableColorVisual.Start().
Member Data Documentation
_started
bool Oculus.Interaction.InteractableColorVisual._started = false protected
Referenced by Oculus.Interaction.InteractableColorVisual.OnDisable(), Oculus.Interaction.InteractableColorVisual.OnEnable(), and Oculus.Interaction.InteractableColorVisual.Start().
The documentation for this class was generated from the following file:
C:/Users/Lykos/Desktop/Projects/Capstone/VRGames/Assets/ThirdParty/Oculus/Interaction/Runtime/Scripts/Interaction/Visuals/InteractableColorVisual.cs