VRGames: UnityEngine.XR.Interaction.Toolkit.LocomotionProvider Class Reference
UnityEngine.XR.Interaction.Toolkit.LocomotionProvider Class Reference abstract
The LocomotionProvider is the base class for various locomotion implementations. This class provides simple ways to interrogate the LocomotionSystem for whether a locomotion can begin and simple events for hooking into a start/end locomotion.
Protected Member Functions
virtual void Awake ()
See MonoBehaviour.
bool CanBeginLocomotion ()
Checks if locomotion can begin.
bool BeginLocomotion ()
Invokes begin locomotion events.
bool EndLocomotion ()
Invokes end locomotion events.
Properties
LocomotionSystem system [get, set]
The LocomotionSystem that this LocomotionProvider communicates with for exclusive access to an XR Origin. If one is not provided, the behavior will attempt to locate one during its Awake call.
Events
Action< LocomotionSystem > beginLocomotion
Unity calls the beginLocomotion action when a LocomotionProvider successfully begins a locomotion event.
Action< LocomotionSystem > endLocomotion
Unity calls the endLocomotion action when a LocomotionProvider successfully ends a locomotion event.
Action< LocomotionSystem > startLocomotion
(Deprecated) The startLocomotion action will be called when a LocomotionProvider successfully begins a locomotion event.
Detailed Description
The LocomotionProvider is the base class for various locomotion implementations. This class provides simple ways to interrogate the LocomotionSystem for whether a locomotion can begin and simple events for hooking into a start/end locomotion.
Member Function Documentation
Awake()
virtual void UnityEngine.XR.Interaction.Toolkit.LocomotionProvider.Awake () protected virtual
See MonoBehaviour.
BeginLocomotion()
bool UnityEngine.XR.Interaction.Toolkit.LocomotionProvider.BeginLocomotion () protected
Invokes begin locomotion events.
Returns
Returns true if successful. Otherwise, returns false.
Referenced by UnityEngine.XR.Interaction.Toolkit.ContinuousMoveProviderBase.MoveRig(), UnityEngine.XR.Interaction.Toolkit.ContinuousTurnProviderBase.TurnRig(), UnityEngine.XR.Interaction.Toolkit.SnapTurnProviderBase.Update(), and UnityEngine.XR.Interaction.Toolkit.TeleportationProvider.Update().
CanBeginLocomotion()
bool UnityEngine.XR.Interaction.Toolkit.LocomotionProvider.CanBeginLocomotion () protected
Checks if locomotion can begin.
Returns
Returns true if locomotion can start. Otherwise, returns false.
Referenced by UnityEngine.XR.Interaction.Toolkit.ContinuousMoveProviderBase.MoveRig(), UnityEngine.XR.Interaction.Toolkit.SnapTurnProviderBase.StartTurn(), and UnityEngine.XR.Interaction.Toolkit.ContinuousTurnProviderBase.TurnRig().
EndLocomotion()
bool UnityEngine.XR.Interaction.Toolkit.LocomotionProvider.EndLocomotion () protected
Invokes end locomotion events.
Returns
Returns true if successful. Otherwise, returns false.
Referenced by UnityEngine.XR.Interaction.Toolkit.ContinuousMoveProviderBase.MoveRig(), UnityEngine.XR.Interaction.Toolkit.ContinuousTurnProviderBase.TurnRig(), UnityEngine.XR.Interaction.Toolkit.SnapTurnProviderBase.Update(), and UnityEngine.XR.Interaction.Toolkit.TeleportationProvider.Update().
Property Documentation
system
LocomotionSystem UnityEngine.XR.Interaction.Toolkit.LocomotionProvider.system get set
The LocomotionSystem that this LocomotionProvider communicates with for exclusive access to an XR Origin. If one is not provided, the behavior will attempt to locate one during its Awake call.
Referenced by UnityEngine.XR.Interaction.Toolkit.ContinuousMoveProviderBase.ComputeDesiredMove(), UnityEngine.XR.Interaction.Toolkit.ContinuousMoveProviderBase.MoveRig(), UnityEngine.XR.Interaction.Toolkit.ContinuousTurnProviderBase.TurnRig(), UnityEngine.XR.Interaction.Toolkit.ContinuousMoveProviderBase.Update(), UnityEngine.XR.Interaction.Toolkit.SnapTurnProviderBase.Update(), and UnityEngine.XR.Interaction.Toolkit.TeleportationProvider.Update().
Event Documentation
beginLocomotion
Action<LocomotionSystem> UnityEngine.XR.Interaction.Toolkit.LocomotionProvider.beginLocomotion
Unity calls the beginLocomotion action when a LocomotionProvider successfully begins a locomotion event.
Referenced by UnityEngine.XR.Interaction.Toolkit.LocomotionProvider.BeginLocomotion().
endLocomotion
Action<LocomotionSystem> UnityEngine.XR.Interaction.Toolkit.LocomotionProvider.endLocomotion
Unity calls the endLocomotion action when a LocomotionProvider successfully ends a locomotion event.
Referenced by UnityEngine.XR.Interaction.Toolkit.LocomotionProvider.EndLocomotion().
startLocomotion
Action<LocomotionSystem> UnityEngine.XR.Interaction.Toolkit.LocomotionProvider.startLocomotion
(Deprecated) The startLocomotion action will be called when a LocomotionProvider successfully begins a locomotion event.
See also
beginLocomotion
startLocomotion has been deprecated. Use beginLocomotion instead.
The documentation for this class was generated from the following files:
C:/Users/Lykos/Desktop/Projects/Capstone/VRGames/Library/PackageCache/com.unity.xr.interaction.toolkit@2.0.2/Runtime/Locomotion/LocomotionProvider.cs
C:/Users/Lykos/Desktop/Projects/Capstone/VRGames/Library/PackageCache/com.unity.xr.interaction.toolkit@2.0.2/Runtime/Locomotion/LocomotionProvider.deprecated.cs