VRCapstoneGames: Oculus.Interaction.HandWristOffset Class Reference
Oculus.Interaction.HandWristOffset Class Reference
Specifies a position and rotation offset from the wrist of the given hand.
Public Member Functions
void GetOffset (ref Pose pose)
void GetWorldPose (ref Pose pose)
void InjectHand (IHand hand)
void InjectOffset (Vector3 offset)
void InjectRotation (Quaternion rotation)
void InjectAllHandWristOffset (IHand hand, Vector3 offset, Quaternion rotation)
Protected Member Functions
virtual void Awake ()
virtual void Start ()
virtual void OnEnable ()
virtual void OnDisable ()
Protected Attributes
bool _started = false
Properties
IHand Hand [get]
Vector3 Offset [get, set]
Quaternion Rotation [get, set]
Detailed Description
Specifies a position and rotation offset from the wrist of the given hand.
Member Function Documentation
Awake()
virtual void Oculus.Interaction.HandWristOffset.Awake () protected virtual
GetOffset()
void Oculus.Interaction.HandWristOffset.GetOffset (ref Pose pose)
Referenced by Oculus.Interaction.HandPosing.HandGrabInteractor.DoEveryUpdate().
GetWorldPose()
void Oculus.Interaction.HandWristOffset.GetWorldPose (ref Pose pose)
Referenced by Oculus.Interaction.HandPosing.HandGrabInteractor.DoEveryUpdate().
InjectAllHandWristOffset()
void Oculus.Interaction.HandWristOffset.InjectAllHandWristOffset (IHand hand, Vector3 offset, Quaternion rotation)
InjectHand()
void Oculus.Interaction.HandWristOffset.InjectHand (IHand hand)
Referenced by Oculus.Interaction.HandWristOffset.InjectAllHandWristOffset().
InjectOffset()
void Oculus.Interaction.HandWristOffset.InjectOffset (Vector3 offset)
Referenced by Oculus.Interaction.HandWristOffset.InjectAllHandWristOffset().
InjectRotation()
void Oculus.Interaction.HandWristOffset.InjectRotation (Quaternion rotation)
Referenced by Oculus.Interaction.HandWristOffset.InjectAllHandWristOffset().
OnDisable()
virtual void Oculus.Interaction.HandWristOffset.OnDisable () protected virtual
OnEnable()
virtual void Oculus.Interaction.HandWristOffset.OnEnable () protected virtual
Start()
virtual void Oculus.Interaction.HandWristOffset.Start () protected virtual
Member Data Documentation
_started
bool Oculus.Interaction.HandWristOffset._started = false protected
Referenced by Oculus.Interaction.HandWristOffset.GetOffset(), Oculus.Interaction.HandWristOffset.OnDisable(), Oculus.Interaction.HandWristOffset.OnEnable(), and Oculus.Interaction.HandWristOffset.Start().
Property Documentation
Hand
IHand Oculus.Interaction.HandWristOffset.Hand get
Offset
Vector3 Oculus.Interaction.HandWristOffset.Offset get set
Rotation
Quaternion Oculus.Interaction.HandWristOffset.Rotation get set
The documentation for this class was generated from the following file:
C:/Users/Lykos/Desktop/Projects/Capstone/VRGames/Assets/ThirdParty/Oculus/Interaction/Runtime/Scripts/Selection/Hands/HandWristOffset.cs