VRCapstoneGames: UnityEngine.ProBuilder.PreferenceDictionary Class Reference
UnityEngine.ProBuilder.PreferenceDictionary Class Reference sealed
Store settings in a project local manner.
Public Member Functions
void OnBeforeSerialize ()
Perform the ritual "Please Serialize My Dictionary" dance.
void OnAfterDeserialize ()
Reconstruct preference dictionaries from serialized lists.
void SetDefaultValues ()
Clear dictionary values.
bool HasKey (string key)
Check if a key is contained within any type dictionary.
bool HasKey< T > (string key)
Test if specific type dictionary contains a key.
void DeleteKey (string key)
T Get< T > (string key, T fallback=default(T))
"Generic" Get preference for key function.
void Set< T > (string key, T value)
"Generic" set value. Only accepts:
bool GetBool (string key, bool fallback=default(bool))
Fetch a value from the stored preferences. If key is not found, a default value is returned.
int GetInt (string key, int fallback=default(int))
Fetch a value from the stored preferences. If key is not found, a default value is returned.
float GetFloat (string key, float fallback=default(float))
Fetch a value from the stored preferences. If key is not found, a default value is returned.
string GetString (string key, string fallback=default(string))
Fetch a value from the stored preferences. If key is not found, a default value is returned.
Color GetColor (string key, Color fallback=default(Color))
Fetch a value from the stored preferences. If key is not found, a default value is returned.
Material GetMaterial (string key, Material fallback=default(Material))
Fetch a value from the stored preferences. If key is not found, a default value is returned.
void SetBool (string key, bool value)
Set a value for key in the saved prefs.
void SetInt (string key, int value)
Set a value for key in the saved prefs.
void SetFloat (string key, float value)
Set a value for key in the saved prefs.
void SetString (string key, string value)
Set a value for key in the saved prefs.
void SetColor (string key, Color value)
Set a value for key in the saved prefs.
void SetMaterial (string key, Material value)
Set a value for key in the saved prefs.
Dictionary< string, bool > GetBoolDictionary ()
Get the internal <key, bool> dictionary.
Dictionary< string, int > GetIntDictionary ()
Get the internal <key, int> dictionary.
Dictionary< string, float > GetFloatDictionary ()
Get the internal <key, float> dictionary.
Dictionary< string, string > GetStringDictionary ()
Get the internal <key, string> dictionary.
Dictionary< string, Color > GetColorDictionary ()
Get the internal <key, Color> dictionary.
Dictionary< string, Material > GetMaterialDictionary ()
Get the internal <key, Material> dictionary.
void Clear ()
Clear all stored preference key value pairs.
Detailed Description
Store settings in a project local manner.
Member Function Documentation
Clear()
void UnityEngine.ProBuilder.PreferenceDictionary.Clear ()
Clear all stored preference key value pairs.
DeleteKey()
void UnityEngine.ProBuilder.PreferenceDictionary.DeleteKey (string key)
Get< T >()
T UnityEngine.ProBuilder.PreferenceDictionary.Get< T > (string key, T fallback = default(T))
"Generic" Get preference for key function.
Parameters
key
fallback
Template Parameters
T
Returns
GetBool()
bool UnityEngine.ProBuilder.PreferenceDictionary.GetBool (string key, bool fallback = default(bool))
Fetch a value from the stored preferences. If key is not found, a default value is returned.
Referenced by UnityEngine.ProBuilder.PreferenceDictionary.Get< T >().
GetBoolDictionary()
Dictionary< string, bool > UnityEngine.ProBuilder.PreferenceDictionary.GetBoolDictionary ()
Get the internal <key, bool> dictionary.
Referenced by UnityEditor.ProBuilder.PreferenceDictionaryEditor.OnInspectorGUI().
GetColor()
Color UnityEngine.ProBuilder.PreferenceDictionary.GetColor (string key, Color fallback = default(Color))
Fetch a value from the stored preferences. If key is not found, a default value is returned.
Referenced by UnityEngine.ProBuilder.PreferenceDictionary.Get< T >().
GetColorDictionary()
Dictionary< string, Color > UnityEngine.ProBuilder.PreferenceDictionary.GetColorDictionary ()
Get the internal <key, Color> dictionary.
Referenced by UnityEditor.ProBuilder.PreferenceDictionaryEditor.OnInspectorGUI().
GetFloat()
float UnityEngine.ProBuilder.PreferenceDictionary.GetFloat (string key, float fallback = default(float))
Fetch a value from the stored preferences. If key is not found, a default value is returned.
Referenced by UnityEngine.ProBuilder.PreferenceDictionary.Get< T >().
GetFloatDictionary()
Dictionary< string, float > UnityEngine.ProBuilder.PreferenceDictionary.GetFloatDictionary ()
Get the internal <key, float> dictionary.
Referenced by UnityEditor.ProBuilder.PreferenceDictionaryEditor.OnInspectorGUI().
GetInt()
int UnityEngine.ProBuilder.PreferenceDictionary.GetInt (string key, int fallback = default(int))
Fetch a value from the stored preferences. If key is not found, a default value is returned.
Referenced by UnityEngine.ProBuilder.PreferenceDictionary.Get< T >().
GetIntDictionary()
Dictionary< string, int > UnityEngine.ProBuilder.PreferenceDictionary.GetIntDictionary ()
Get the internal <key, int> dictionary.
Referenced by UnityEditor.ProBuilder.PreferenceDictionaryEditor.OnInspectorGUI().
GetMaterial()
Material UnityEngine.ProBuilder.PreferenceDictionary.GetMaterial (string key, Material fallback = default(Material))
Fetch a value from the stored preferences. If key is not found, a default value is returned.
Referenced by UnityEngine.ProBuilder.PreferenceDictionary.Get< T >().
GetMaterialDictionary()
Dictionary< string, Material > UnityEngine.ProBuilder.PreferenceDictionary.GetMaterialDictionary ()
Get the internal <key, Material> dictionary.
Referenced by UnityEditor.ProBuilder.PreferenceDictionaryEditor.OnInspectorGUI().
GetString()
string UnityEngine.ProBuilder.PreferenceDictionary.GetString (string key, string fallback = default(string))
Fetch a value from the stored preferences. If key is not found, a default value is returned.
Referenced by UnityEngine.ProBuilder.PreferenceDictionary.Get< T >().
GetStringDictionary()
Dictionary< string, string > UnityEngine.ProBuilder.PreferenceDictionary.GetStringDictionary ()
Get the internal <key, string> dictionary.
Referenced by UnityEditor.ProBuilder.PreferenceDictionaryEditor.OnInspectorGUI().
HasKey()
bool UnityEngine.ProBuilder.PreferenceDictionary.HasKey (string key)
Check if a key is contained within any type dictionary.
Parameters
key
Returns
HasKey< T >()
bool UnityEngine.ProBuilder.PreferenceDictionary.HasKey< T > (string key)
Test if specific type dictionary contains a key.
Parameters
key
Template Parameters
T
Returns
OnAfterDeserialize()
void UnityEngine.ProBuilder.PreferenceDictionary.OnAfterDeserialize ()
Reconstruct preference dictionaries from serialized lists.
OnBeforeSerialize()
void UnityEngine.ProBuilder.PreferenceDictionary.OnBeforeSerialize ()
Perform the ritual "Please Serialize My Dictionary" dance.
Set< T >()
void UnityEngine.ProBuilder.PreferenceDictionary.Set< T > (string key, T value)
"Generic" set value. Only accepts:
int,
float,
bool,
string,
Color,
Material
Parameters
key
value
Template Parameters
T
SetBool()
void UnityEngine.ProBuilder.PreferenceDictionary.SetBool (string key, bool value)
Set a value for key in the saved prefs.
Referenced by UnityEngine.ProBuilder.PreferenceDictionary.Set< T >().
SetColor()
void UnityEngine.ProBuilder.PreferenceDictionary.SetColor (string key, Color value)
Set a value for key in the saved prefs.
Referenced by UnityEngine.ProBuilder.PreferenceDictionary.Set< T >().
SetDefaultValues()
void UnityEngine.ProBuilder.PreferenceDictionary.SetDefaultValues ()
Clear dictionary values.
Implements UnityEngine.ProBuilder.IHasDefault.
SetFloat()
void UnityEngine.ProBuilder.PreferenceDictionary.SetFloat (string key, float value)
Set a value for key in the saved prefs.
Referenced by UnityEngine.ProBuilder.PreferenceDictionary.Set< T >().
SetInt()
void UnityEngine.ProBuilder.PreferenceDictionary.SetInt (string key, int value)
Set a value for key in the saved prefs.
Referenced by UnityEngine.ProBuilder.PreferenceDictionary.Set< T >().
SetMaterial()
void UnityEngine.ProBuilder.PreferenceDictionary.SetMaterial (string key, Material value)
Set a value for key in the saved prefs.
Referenced by UnityEngine.ProBuilder.PreferenceDictionary.Set< T >().
SetString()
void UnityEngine.ProBuilder.PreferenceDictionary.SetString (string key, string value)
Set a value for key in the saved prefs.
Referenced by UnityEngine.ProBuilder.PreferenceDictionary.Set< T >().
The documentation for this class was generated from the following file:
C:/Users/Lykos/Desktop/Projects/Capstone/VRGames/Library/PackageCache/com.unity.probuilder@5.0.6/Runtime/Core/PreferenceDictionary.cs