VRGames: Unity.XR.CoreUtils.ObjectPool< T > Class Template Reference
Unity.XR.CoreUtils.ObjectPool< T > Class Template Reference
Instance pool for objects.
Public Member Functions
virtual T Get ()
Get an instance of the object type.
void Recycle (T instance)
Return an object instance to the pool.
Protected Member Functions
virtual void ClearInstance (T instance)
Implement a clearing function in this in a derived class to have the
See also
Recycle
method automatically clear the item.
Protected Attributes
readonly Queue< T > PooledQueue = new Queue<T>()
All objects in the pool.
Detailed Description
Instance pool for objects.
Template Parameters
T The type of object to manage instances of
Type Constraints
T : class
T : new()
Member Function Documentation
ClearInstance()
virtual void Unity.XR.CoreUtils.ObjectPool< T >.ClearInstance (T instance) protected virtual
Implement a clearing function in this in a derived class to have the
See also
Recycle
method automatically clear the item.
Parameters
instance The object to return to the pool
Referenced by Unity.XR.CoreUtils.ObjectPool< T >.Recycle().
Get()
virtual T Unity.XR.CoreUtils.ObjectPool< T >.Get () virtual
Get an instance of the object type.
Returns
The object instance
Recycle()
void Unity.XR.CoreUtils.ObjectPool< T >.Recycle (T instance)
Return an object instance to the pool.
Parameters
instance The instance to return
Member Data Documentation
PooledQueue
readonly Queue<T> Unity.XR.CoreUtils.ObjectPool< T >.PooledQueue = new Queue<T>() protected
All objects in the pool.
Referenced by Unity.XR.CoreUtils.ObjectPool< T >.Get(), and Unity.XR.CoreUtils.ObjectPool< T >.Recycle().
The documentation for this class was generated from the following file:
C:/Users/Lykos/Desktop/Projects/Capstone/VRGames/Library/PackageCache/com.unity.xr.core-utils@2.0.0/Runtime/ObjectPool.cs