VRCapstoneGames: UnityEngine.InputSystem.InputControl< TValue > Class Template Reference
UnityEngine.InputSystem.InputControl< TValue > Class Template Reference abstract
A typed and named source of input values in a hierarchy of controls.
Public Member Functions
override string ToString ()
Return a string representation of the control useful for debugging.
unsafe float EvaluateMagnitude ()
Compute an absolute, normalized magnitude value that indicates the extent to which the control is actuated.
virtual unsafe float EvaluateMagnitude (void *statePtr)
Compute an absolute, normalized magnitude value that indicates the extent to which the control is actuated in the given state.
unsafe object ReadValueFromBufferAsObject (void *buffer, int bufferSize)
unsafe object ReadValueFromStateAsObject (void *statePtr)
Read the control's final, processed value from the given state and return the value as an object.
unsafe void ReadValueFromStateIntoBuffer (void *statePtr, void *bufferPtr, int bufferSize)
Read the control's final, processed value from the given state and store it in the given buffer.
virtual unsafe void WriteValueFromBufferIntoState (void *bufferPtr, int bufferSize, void *statePtr)
Read a value from the given memory and store it as state.
virtual unsafe void WriteValueFromObjectIntoState (object value, void *statePtr)
Read a value object and store it as state in the given memory.
unsafe bool CompareValue (void *firstStatePtr, void *secondStatePtr)
Compare the value of the control as read from firstStatePtr to that read from secondStatePtr and return true if they are equal.
InputControl TryGetChildControl (string path)
Try to find a child control matching the given path.
TControl TryGetChildControl< TControl > (string path)
InputControl GetChildControl (string path)
TControl GetChildControl< TControl > (string path)
TValue ReadValue ()
Get the control's current value as read from InputControl.currentStatePtr
TValue ReadValueFromPreviousFrame ()
Get the control's value from the previous frame (InputControl.previousFrameStatePtr).
TValue ReadDefaultValue ()
Get the control's default value.
unsafe TValue ReadValueFromState (void *statePtr)
TValue ReadUnprocessedValue ()
unsafe TValue ReadUnprocessedValueFromState (void *statePtr)
override unsafe object ReadValueFromStateAsObject (void *statePtr)
override unsafe void ReadValueFromStateIntoBuffer (void *statePtr, void *bufferPtr, int bufferSize)
override unsafe void WriteValueFromBufferIntoState (void *bufferPtr, int bufferSize, void *statePtr)
override unsafe void WriteValueFromObjectIntoState (object value, void *statePtr)
virtual unsafe void WriteValueIntoState (TValue value, void *statePtr)
override unsafe object ReadValueFromBufferAsObject (void *buffer, int bufferSize)
override unsafe bool CompareValue (void *firstStatePtr, void *secondStatePtr)
TValue ProcessValue (TValue value)
Protected Member Functions
InputControl ()
virtual void FinishSetup ()
Perform final initialization tasks after the control hierarchy has been put into place.
void RefreshConfigurationIfNeeded ()
Call RefreshConfiguration if the configuration has in the interim been invalidated by a DeviceConfigurationEvent.
virtual void RefreshConfiguration ()
Properties
string name [get]
The name of the control, i.e. the final name part in its path.
string displayName [get, protected set]
The text to display as the name of the control.
string shortDisplayName [get, protected set]
An alternate, abbreviated displayName (for example "LMB" instead of "Left Button").
string path [get]
Full path all the way from the root.
string layout [get]
Layout the control is based on.
string variants [get]
Semicolon-separated list of variants of the control layout or "default".
InputDevice device [get]
The device that this control is a part of.
InputControl parent [get]
The immediate parent of the control or null if the control has no parent (which, once fully constructed) will only be the case for InputDevices).
ReadOnlyArray< InputControl > children [get]
List of immediate children.
ReadOnlyArray< InternedString > usages [get]
List of usage tags associated with the control.
ReadOnlyArray< InternedString > aliases [get]
InputStateBlock stateBlock [get]
bool noisy [get, set]
Whether the control is considered noisy.
bool synthetic [get, set]
Whether the control is considered synthetic.
InputControl this[string path] [get]
Fetch a control from the control's hierarchy by name.
Type valueType [get]
Returns the underlying value type of this control.
int valueSizeInBytes [get]
Size in bytes of values that the control returns.
override Type valueType [get]
override int valueSizeInBytes [get]
Detailed Description
A typed and named source of input values in a hierarchy of controls.
Base class for input controls with a specific value type.
Controls can have children which in turn may have children. At the root of the child hierarchy is always an InputDevice (which themselves are InputControls).
Controls can be looked up by their path (see InputControlPath.TryFindControl).
Each control must have a unique name within the children of its parent. Multiple names can be assigned to controls using aliases (see aliases). Name lookup is case-insensitive.
For display purposes, a control may have a separate displayName. This name will usually correspond to what the control is caused on the actual underlying hardware. For example, on an Xbox gamepad, the control with the name "buttonSouth" will have a display name of "A". Controls that have very long display names may also have a shortDisplayName. This is the case for the "Left Button" on the Mouse, for example, which is commonly abbreviated "LMB".
In addition to names, a control may have usages associated with it (see usages). A usage indicates how a control is meant to be used. For example, a button can be assigned the "PrimaryAction" usage to indicate it is the primary action button the device. Within a device, usages have to be unique. See CommonUsages for a list of standardized usages.
Controls do not actually store values. Instead, every control receives an InputStateBlock which, after the control's device has been added to the system, is used to read out values from the device's backing store. This backing store is referred to as "state" in the API as opposed to "values" which represent the data resulting from reading state. The format that each control stores state in is specific to the control. It can vary not only between controls of different types but also between controls of the same type. An AxisControl, for example, can be stored as a float or as a byte or in a number of other formats. stateBlock identifies both where the control stores its state as well as the format it stores it in.
Controls are generally not created directly but are created internally by the input system from data known as "layouts" (see InputControlLayout). Each such layout describes the setup of a specific hierarchy of controls. The system internally maintains a registry of layouts and produces devices and controls from them as needed. The layout that a control has been created from can be queried using layout. For most purposes, the intricacies of the control layout mechanisms can be ignored and it is sufficient to know the names of a small set of common device layouts such as "Keyboard", "Mouse", "Gamepad", and "Touchscreen".
Each control has a single, fixed value type. The type can be queried at runtime using valueType. Most types of controls are derived from InputControl<TValue> which has APIs specific to the type of value of the control (e.g. InputControl<TValue>.ReadValue().
The following example demonstrates various common operations performed on input controls:
// Look up dpad/up control on current gamepad.
var dpadUpControl = Gamepad.current["dpad/up"];
// Look up the back button on the current gamepad.
var backButton = Gamepad.current["{Back}"];
// Look up all dpad/up controls on all gamepads in the system.
using (var controls = InputSystem.FindControls("<Gamepad>/dpad/up"))
    Debug.Log($"Found {controls.Count} controls");
// Display the value of all controls on the current gamepad.
foreach (var control in Gamepad.current.allControls)
    Debug.Log(controls.ReadValueAsObject());
// Track the value of the left stick on the current gamepad over time.
var leftStickHistory = new InputStateHistory(Gamepad.current.leftStick);
leftStickHistory.Enable();
InputControl<TValue>
See also
InputDevice, InputControlPath, InputStateBlock
Template Parameters
TValue Type of value captured by the control. Note that this does not mean that the control has to store data in the given value format. A control that captures float values, for example, may be stored in state as byte values instead.
Type Constraints
TValue : struct
Constructor & Destructor Documentation
InputControl()
UnityEngine.InputSystem.InputControl< TValue >.InputControl () protected
Member Function Documentation
CompareValue() [1/2]
unsafe bool UnityEngine.InputSystem.InputControl< TValue >.CompareValue (void * firstStatePtr, void * secondStatePtr) abstract
Compare the value of the control as read from firstStatePtr to that read from secondStatePtr and return true if they are equal.
Parameters
firstStatePtr Memory containing the control's stateBlock.
secondStatePtr Memory containing the control's stateBlock
Returns
True if the value of the control is equal in both firstStatePtr and secondStatePtr .
Unlike CompareValue, this method will have to do more than just compare the memory for the control in the two state buffers. It will have to read out state for the control and run the full processing machinery for the control to turn the state into a final, processed value. CompareValue is thus more costly than CompareValue.
This method will apply epsilons (Mathf.Epsilon) when comparing floats.
See also
CompareValue
CompareValue() [2/2]
override unsafe bool UnityEngine.InputSystem.InputControl< TValue >.CompareValue (void * firstStatePtr, void * secondStatePtr)
EvaluateMagnitude() [1/2]
unsafe float UnityEngine.InputSystem.InputControl< TValue >.EvaluateMagnitude ()
Compute an absolute, normalized magnitude value that indicates the extent to which the control is actuated.
REVIEW: The -1 behavior seems bad; probably better to just return 1 for controls that do not support finer levels of actuation
Returns
Amount of actuation of the control or -1 if it cannot be determined.
Magnitudes do not make sense for all types of controls. For example, for a control that represents an enumeration of values (such as TouchPhaseControl), there is no meaningful linear ordering of values (one could derive a linear ordering through the actual enum values but their assignment may be entirely arbitrary; it is unclear whether a state of TouchPhase.Canceled has a higher or lower "magnitude" as a state of TouchPhase.Began).
Controls that have no meaningful magnitude will return -1 when calling this method. Any negative return value should be considered an invalid value.
See also
EvaluateMagnitude(void*)
Referenced by UnityEngine.InputSystem.InputControl< TValue >.EvaluateMagnitude(), and UnityEngine.InputSystem.InputControlExtensions.InputEventControlEnumerator.MoveNext().
EvaluateMagnitude() [2/2]
virtual unsafe float UnityEngine.InputSystem.InputControl< TValue >.EvaluateMagnitude (void * statePtr) virtual
Compute an absolute, normalized magnitude value that indicates the extent to which the control is actuated in the given state.
Parameters
statePtr State containing the control's stateBlock.
Returns
Amount of actuation of the control or -1 if it cannot be determined.
See also
EvaluateMagnitude(), stateBlock
Reimplemented in UnityEngine.InputSystem.Controls.AxisControl, UnityEngine.InputSystem.Controls.Vector2Control, and UnityEngine.InputSystem.Controls.Vector3Control.
FinishSetup()
virtual void UnityEngine.InputSystem.InputControl< TValue >.FinishSetup () protected virtual
Perform final initialization tasks after the control hierarchy has been put into place.
This method can be overridden to perform control- or device-specific setup work. The most common use case is for looking up child controls and storing them in local getters.
public class MyDevice : InputDevice
{
    public ButtonControl button { get; private set; }
    public AxisControl axis { get; private set; }
    protected override void OnFinishSetup()
    {
        // Cache controls in getters.
        button = GetChildControl("button");
        axis = GetChildControl("axis");
    }
}
Reimplemented in UnityEngine.InputSystem.Controls.AxisControl, UnityEngine.InputSystem.Controls.DiscreteButtonControl, UnityEngine.InputSystem.Controls.DpadControl.DpadAxisControl, UnityEngine.InputSystem.Controls.DpadControl, UnityEngine.InputSystem.Controls.QuaternionControl, UnityEngine.InputSystem.Controls.StickControl, UnityEngine.InputSystem.Controls.TouchControl, UnityEngine.InputSystem.Controls.TouchPressControl, UnityEngine.InputSystem.Controls.Vector2Control, UnityEngine.InputSystem.Controls.Vector3Control, UnityEngine.InputSystem.Gamepad, UnityEngine.InputSystem.Joystick, UnityEngine.InputSystem.Keyboard, UnityEngine.InputSystem.Mouse, UnityEngine.InputSystem.Pen, UnityEngine.InputSystem.Pointer, UnityEngine.InputSystem.Accelerometer, UnityEngine.InputSystem.Gyroscope, UnityEngine.InputSystem.GravitySensor, UnityEngine.InputSystem.AttitudeSensor, UnityEngine.InputSystem.LinearAccelerationSensor, UnityEngine.InputSystem.MagneticFieldSensor, UnityEngine.InputSystem.LightSensor, UnityEngine.InputSystem.PressureSensor, UnityEngine.InputSystem.ProximitySensor, UnityEngine.InputSystem.HumiditySensor, UnityEngine.InputSystem.AmbientTemperatureSensor, UnityEngine.InputSystem.StepCounter, UnityEngine.InputSystem.Touchscreen, UnityEngine.InputSystem.TrackedDevice, UnityEngine.InputSystem.DualShock.DualShockGamepad, UnityEngine.InputSystem.XInput.XInputController, and CustomDevice.
GetChildControl()
InputControl UnityEngine.InputSystem.InputControl< TValue >.GetChildControl (string path)
Referenced by UnityEngine.InputSystem.InputControl< TValue >.GetChildControl< TControl >().
GetChildControl< TControl >()
TControl UnityEngine.InputSystem.InputControl< TValue >.GetChildControl< TControl > (string path)
Type Constraints
TControl : InputControl
ProcessValue()
TValue UnityEngine.InputSystem.InputControl< TValue >.ProcessValue (TValue value)
Referenced by UnityEngine.InputSystem.InputControl< TValue >.ReadValueFromState().
ReadDefaultValue()
TValue UnityEngine.InputSystem.InputControl< TValue >.ReadDefaultValue ()
Get the control's default value.
Returns
The control's default value.
This is not necessarily equivalent to default(TValue). A control's default value is determined by reading its value from the default state (InputControl.defaultStatePtr) which in turn is determined from settings in the control's registered layout (InputControlLayout.ControlItem.defaultState).
ReadUnprocessedValue()
TValue UnityEngine.InputSystem.InputControl< TValue >.ReadUnprocessedValue ()
Referenced by UnityEngine.InputSystem.InputTestFixture.AssertStickValues().
ReadUnprocessedValueFromState()
unsafe TValue UnityEngine.InputSystem.InputControl< TValue >.ReadUnprocessedValueFromState (void * statePtr) abstract
Referenced by UnityEngine.InputSystem.InputControl< TValue >.ReadUnprocessedValue(), and UnityEngine.InputSystem.InputControl< TValue >.ReadValueFromState().
ReadValue()
TValue UnityEngine.InputSystem.InputControl< TValue >.ReadValue ()
Get the control's current value as read from InputControl.currentStatePtr
Returns
The control's current value.
This can only be called on devices that have been added to the system (InputDevice.added).
Referenced by UnityEngine.InputSystem.InputTestFixture.Move(), and UnityEngine.XR.Interaction.Toolkit.ActionBasedController.UpdateTrackingInput().
ReadValueFromBufferAsObject() [1/2]
unsafe object UnityEngine.InputSystem.InputControl< TValue >.ReadValueFromBufferAsObject (void * buffer, int bufferSize) abstract
Referenced by UnityEngine.InputSystem.Utilities.InputActionTrace.ActionEventPtr.ReadValueAsObject().
ReadValueFromBufferAsObject() [2/2]
override unsafe object UnityEngine.InputSystem.InputControl< TValue >.ReadValueFromBufferAsObject (void * buffer, int bufferSize)
ReadValueFromPreviousFrame()
TValue UnityEngine.InputSystem.InputControl< TValue >.ReadValueFromPreviousFrame ()
Get the control's value from the previous frame (InputControl.previousFrameStatePtr).
REVIEW: is 'frame' really the best wording here?
Returns
The control's value in the previous frame.
ReadValueFromState()
unsafe TValue UnityEngine.InputSystem.InputControl< TValue >.ReadValueFromState (void * statePtr)
Referenced by UnityEngine.InputSystem.InputControl< TValue >.CompareValue(), UnityEngine.InputSystem.InputControl< TValue >.ReadDefaultValue(), UnityEngine.InputSystem.Controls.DpadControl.ReadUnprocessedValueFromState(), UnityEngine.InputSystem.Controls.QuaternionControl.ReadUnprocessedValueFromState(), UnityEngine.InputSystem.InputControl< TValue >.ReadValue(), UnityEngine.InputSystem.InputControl< TValue >.ReadValueFromPreviousFrame(), UnityEngine.InputSystem.InputControl< TValue >.ReadValueFromStateAsObject(), and UnityEngine.InputSystem.InputControl< TValue >.ReadValueFromStateIntoBuffer().
ReadValueFromStateAsObject() [1/2]
unsafe object UnityEngine.InputSystem.InputControl< TValue >.ReadValueFromStateAsObject (void * statePtr) abstract
Read the control's final, processed value from the given state and return the value as an object.
Parameters
statePtr
Returns
The control's value as stored in statePtr .
This method allocates GC memory and should not be used during normal gameplay operation.
Exceptions
ArgumentNullException statePtr is null.
See also
ReadValueFromStateIntoBuffer
ReadValueFromStateAsObject() [2/2]
override unsafe object UnityEngine.InputSystem.InputControl< TValue >.ReadValueFromStateAsObject (void * statePtr)
ReadValueFromStateIntoBuffer() [1/2]
unsafe void UnityEngine.InputSystem.InputControl< TValue >.ReadValueFromStateIntoBuffer (void * statePtr, void * bufferPtr, int bufferSize) abstract
Read the control's final, processed value from the given state and store it in the given buffer.
Parameters
statePtr State to read the value for the control from.
bufferPtr Buffer to store the value in.
bufferSize Size of bufferPtr in bytes. Must be at least valueSizeInBytes. If it is smaller, ArgumentException will be thrown.
Exceptions
ArgumentNullException statePtr is null, or bufferPtr is null.
ArgumentException bufferSize is smaller than valueSizeInBytes.
See also
ReadValueFromStateAsObject, WriteValueFromBufferIntoState
ReadValueFromStateIntoBuffer() [2/2]
override unsafe void UnityEngine.InputSystem.InputControl< TValue >.ReadValueFromStateIntoBuffer (void * statePtr, void * bufferPtr, int bufferSize)
RefreshConfiguration()
virtual void UnityEngine.InputSystem.InputControl< TValue >.RefreshConfiguration () protected virtual
Reimplemented in UnityEngine.InputSystem.Controls.KeyControl, and UnityEngine.InputSystem.Keyboard.
Referenced by UnityEngine.InputSystem.InputControl< TValue >.RefreshConfigurationIfNeeded().
RefreshConfigurationIfNeeded()
void UnityEngine.InputSystem.InputControl< TValue >.RefreshConfigurationIfNeeded () protected
Call RefreshConfiguration if the configuration has in the interim been invalidated by a DeviceConfigurationEvent.
This method is only relevant if you are implementing your own devices or new types of controls which are fetching configuration data from the devices (such as KeyControl which is fetching display names for individual keys from the underlying platform).
This method should be called if you are accessing cached data set up by RefreshConfiguration.
// Let's say your device has an associated orientation which it can be held with
// and you want to surface both as a property and as a usage on the device.
// Whenever your backend code detects a change in orientation, it should send
// a DeviceConfigurationEvent to your device to signal that the configuration
// of the device has changed. You can then implement RefreshConfiguration() to
// read out and update the device orientation on the managed InputDevice instance.
public class MyDevice : InputDevice
{
    public enum Orientation
    {
        Horizontal,
        Vertical,
    }
    private Orientation m_Orientation;
    public Orientation orientation
    {
        get
        {
            // Call RefreshOrientation if the configuration of the device has been
            // invalidated since last time we initialized m_Orientation.
            RefreshConfigurationIfNeeded();
            return m_Orientation;
        }
    }
    protected override void RefreshConfiguration()
    {
        // Fetch the current orientation from the backend. How you do this
        // depends on your device. Using DeviceCommands is one way.
        var fetchOrientationCommand = new FetchOrientationCommand();
        ExecuteCommand(ref fetchOrientationCommand);
        m_Orientation = fetchOrientation;
        // Reflect the orientation on the device.
        switch (m_Orientation)
        {
            case Orientation.Vertical:
                InputSystem.RemoveDeviceUsage(this, s_Horizontal);
                InputSystem.AddDeviceUsage(this, s_Vertical);
                break;
            case Orientation.Horizontal:
                InputSystem.RemoveDeviceUsage(this, s_Vertical);
                InputSystem.AddDeviceUsage(this, s_Horizontal);
                break;
        }
    }
    private static InternedString s_Vertical = new InternedString("Vertical");
    private static InternedString s_Horizontal = new InternedString("Horizontal");
}
See also
RefreshConfiguration
ToString()
override string UnityEngine.InputSystem.InputControl< TValue >.ToString ()
Return a string representation of the control useful for debugging.
Returns
A string representation of the control.
TryGetChildControl()
InputControl UnityEngine.InputSystem.InputControl< TValue >.TryGetChildControl (string path)
Try to find a child control matching the given path.
Parameters
path A control path. See InputControlPath.
Returns
The first direct or indirect child control that matches the given path or null if no control was found to match.
Exceptions
ArgumentNullException path is null or empty.
Note that if the given path matches multiple child controls, only the first control encountered in the search will be returned.
// Returns the leftStick control of the current gamepad.
Gamepad.current.TryGetChildControl("leftStick");
// Returns the X axis control of the leftStick on the current gamepad.
Gamepad.current.TryGetChildControl("leftStick/x");
// Returns the first control ending with "stick" in its name. Note that it
// undetermined whether this is leftStick or rightStick (or even another stick
// added by the given gamepad).
Gamepad.current.TryGetChildControl("*stick");
This method is equivalent to calling InputControlPath.TryFindChild.
Referenced by UnityEngine.InputSystem.InputControl< TValue >.GetChildControl(), UnityEngine.InputSystem.InputTestFixture.Move(), and UnityEngine.InputSystem.InputControl< TValue >.TryGetChildControl< TControl >().
TryGetChildControl< TControl >()
TControl UnityEngine.InputSystem.InputControl< TValue >.TryGetChildControl< TControl > (string path)
Type Constraints
TControl : InputControl
WriteValueFromBufferIntoState() [1/2]
virtual unsafe void UnityEngine.InputSystem.InputControl< TValue >.WriteValueFromBufferIntoState (void * bufferPtr, int bufferSize, void * statePtr) virtual
Read a value from the given memory and store it as state.
Parameters
bufferPtr Memory containing value.
bufferSize Size of bufferPtr in bytes. Must be at least valueSizeInBytes.
statePtr State containing the control's stateBlock. Will receive the state as converted from the given value.
Writing values will NOT apply processors to the given value. This can mean that when reading a value from a control after it has been written to its state, the resulting value differs from what was written.
Exceptions
NotSupportedException The control does not support writing. This is the case, for example, that compute values (such as the magnitude of a vector).
See also
ReadValueFromStateIntoBuffer, WriteValueFromObjectIntoState
WriteValueFromBufferIntoState() [2/2]
override unsafe void UnityEngine.InputSystem.InputControl< TValue >.WriteValueFromBufferIntoState (void * bufferPtr, int bufferSize, void * statePtr)
WriteValueFromObjectIntoState() [1/2]
virtual unsafe void UnityEngine.InputSystem.InputControl< TValue >.WriteValueFromObjectIntoState (object value, void * statePtr) virtual
Read a value object and store it as state in the given memory.
Parameters
value Value for the control.
statePtr State containing the control's stateBlock. Will receive the state state as converted from the given value.
Writing values will NOT apply processors to the given value. This can mean that when reading a value from a control after it has been written to its state, the resulting value differs from what was written.
Exceptions
NotSupportedException The control does not support writing. This is the case, for example, that compute values (such as the magnitude of a vector).
See also
WriteValueFromBufferIntoState
WriteValueFromObjectIntoState() [2/2]
override unsafe void UnityEngine.InputSystem.InputControl< TValue >.WriteValueFromObjectIntoState (object value, void * statePtr)
WriteValueIntoState()
virtual unsafe void UnityEngine.InputSystem.InputControl< TValue >.WriteValueIntoState (TValue value, void * statePtr) virtual
Referenced by UnityEngine.InputSystem.LowLevel.InputStateHistory< TValue >.RecordStateChange(), UnityEngine.InputSystem.InputControl< TValue >.WriteValueFromBufferIntoState(), and UnityEngine.InputSystem.InputControl< TValue >.WriteValueFromObjectIntoState().
Property Documentation
aliases
ReadOnlyArray<InternedString> UnityEngine.InputSystem.InputControl< TValue >.aliases get
children
ReadOnlyArray<InputControl> UnityEngine.InputSystem.InputControl< TValue >.children get
List of immediate children.
Does not allocate.
See also
parent
Referenced by UnityEngine.InputSystem.Touchscreen.FinishSetup().
device
InputDevice UnityEngine.InputSystem.InputControl< TValue >.device get
The device that this control is a part of.
This is the root of the control hierarchy. For the device at the root, this will point to itself.
See also
InputDevice.allControls
Referenced by UnityEngine.InputSystem.LowLevel.DeltaStateEvent.From(), UnityEngine.InputSystem.InputTestFixture.Move(), UnityEngine.InputSystem.OnScreen.OnScreenControl.OnDisable(), UnityEngine.InputSystem.LowLevel.InputStateHistory< TValue >.RecordStateChange(), UnityEngine.InputSystem.LowLevel.InputStateHistory< TValue >.RecordStateChange(), UnityEngine.XR.Interaction.Toolkit.ActionBasedController.SendHapticImpulse(), UnityEngine.InputSystem.InputTestFixture.Set< TValue >(), UnityEngine.XR.Interaction.Toolkit.ActionBasedController.UpdateTrackingInput(), UnityEngine.InputSystem.InputControlExtensions.ControlBuilder.WithAliases(), UnityEngine.InputSystem.InputControlExtensions.ControlBuilder.WithChildren(), UnityEngine.InputSystem.InputControlExtensions.DeviceBuilder.WithChildren(), and UnityEngine.InputSystem.InputControlExtensions.ControlBuilder.WithUsages().
displayName
string UnityEngine.InputSystem.InputControl< TValue >.displayName get protected set
The text to display as the name of the control.
TODO: protect against empty strings
Note that the display name of a control may change over time. For example, when changing from a QWERTY keyboard layout to an AZERTY keyboard layout, the "q" key (which will keep that name) will change its display name from "q" to "a".
By default, a control's display name will come from its layout. If it is not assigned a display name there, the display name will default to name. However, specific controls may override this behavior. KeyControl, for example, will set the display name to the actual key name corresponding to the current keyboard layout.
For nested controls, the display name will include the display names of all parent controls, i.e. the display name will fully identify the control on the device. For example, the display name for the left D-Pad button on a gamepad is "D-Pad Left" and not just "Left".
See also
shortDisplayName
Referenced by UnityEngine.InputSystem.Keyboard.FindKeyOnCurrentKeyboardLayout(), and UnityEngine.InputSystem.InputControlPath.ParsedPathComponent.Matches().
layout
string UnityEngine.InputSystem.InputControl< TValue >.layout get
Layout the control is based on.
This is the layout name rather than a reference to an InputControlLayout as we only create layout instances during device creation and treat them as temporaries in general so as to not waste heap space during normal operation.
Referenced by UnityEngine.InputSystem.InputControlPath.ParsedPathComponent.Matches().
name
string UnityEngine.InputSystem.InputControl< TValue >.name get
The name of the control, i.e. the final name part in its path.
Names of controls must be unique within the context of their parent.
Note that this is the name of the control as assigned internally (like "buttonSouth") and not necessarily a good display name. Use displayName for getting more readable names for display purposes (where available).
Lookup of names is case-insensitive.
This is set from the name of the control in the layout.
See also
path, aliases, InputControlAttribute.name, InputControlLayout.ControlItem.name
Referenced by UnityEngine.InputSystem.InputControlPath.ParsedPathComponent.Matches().
noisy
bool UnityEngine.InputSystem.InputControl< TValue >.noisy get set
Whether the control is considered noisy.
True if the control produces noisy input.
A control is considered "noisy" if it produces different values without necessarily requiring user interaction. A good example are sensors (see Sensor). For example, the PS4 controller which has a gyroscope sensor built into the device. Whereas sticks and buttons on the device require user interaction to produce non-default values, the gyro will produce varying values even if the device just sits there without user interaction.
The value of this property is determined by the layout (InputControlLayout) that the control has been built from.
Note that for devices (InputDevice) this property is true if any control on the device is marked as noisy.
The primary effect of being noise is on InputDevice.MakeCurrent and on interactive rebinding (see InputActionRebindingExtensions.RebindingOperation). However, being noisy also affects automatic resetting of controls that happens when the application loses focus. While other controls are reset to their default value (except if Application.runInBackground is true and the device the control belongs to is marked as InputDevice.canRunInBackground), noisy controls will not be reset but rather remain at their current value. This is based on the assumption that noisy controls most often represent sensor values and snapping the last sampling value back to default will usually have undesirable effects on an application's simulation logic.
See also
InputControlLayout.ControlItem.isNoisy, InputControlAttribute.noisy
Referenced by UnityEngine.InputSystem.InputControlExtensions.InputEventControlEnumerator.MoveNext().
parent
InputControl UnityEngine.InputSystem.InputControl< TValue >.parent get
The immediate parent of the control or null if the control has no parent (which, once fully constructed) will only be the case for InputDevices).
See also
children
Referenced by UnityEngine.InputSystem.InputControlExtensions.InputEventControlEnumerator.MoveNext().
path
string UnityEngine.InputSystem.InputControl< TValue >.path get
Full path all the way from the root.
This will always be the "effective" path of the control, i.e. it will not contain elements such as usages ("{Back}") and other elements that can be part of control paths used for matching. Instead, this property will always be a simple linear ordering of names leading from the device at the top to the control with each element being separated by a forward slash (/).
Allocates on first hit. Paths are not created until someone asks for them.
Example: "/gamepad/leftStick/x"
See also
InputControlPath
Referenced by UnityEngine.InputSystem.InputControl< TValue >.GetChildControl(), UnityEngine.InputSystem.InputControl< TValue >.GetChildControl< TControl >(), UnityEngine.InputSystem.InputControl< TValue >.TryGetChildControl(), UnityEngine.InputSystem.InputControl< TValue >.TryGetChildControl< TControl >(), and UnityEngine.InputSystem.InputActionRebindingExtensions.RebindingOperation.WithCancelingThrough().
shortDisplayName
string UnityEngine.InputSystem.InputControl< TValue >.shortDisplayName get protected set
An alternate, abbreviated displayName (for example "LMB" instead of "Left Button").
If the control has no abbreviated version, this will be null. Note that this behavior is different from displayName which will fall back to name if no display name has been assigned to the control.
For nested controls, the short display name will include the short display names of all parent controls, that is, the display name will fully identify the control on the device. For example, the display name for the left D-Pad button on a gamepad is "D-Pad \u2190" and not just "\u2190". Note that if a parent control has no short name, its long name will be used instead.
See also
displayName
stateBlock
InputStateBlock UnityEngine.InputSystem.InputControl< TValue >.stateBlock get
Referenced by UnityEngine.InputSystem.Touchscreen.OnNextUpdate(), UnityEngine.InputSystem.Touchscreen.OnStateEvent(), UnityEngine.InputSystem.InputDevice.ReadValueFromStateAsObject(), UnityEngine.InputSystem.LowLevel.InputStateHistory< TValue >.RecordStateChange(), UnityEngine.InputSystem.LowLevel.InputStateHistory< TValue >.RecordStateChange(), and UnityEngine.InputSystem.LowLevel.InputStateHistory< TValue >.RecordStateChange().
synthetic
bool UnityEngine.InputSystem.InputControl< TValue >.synthetic get set
Whether the control is considered synthetic.
True if the control does not represent an actual physical control on the device.
A control is considered "synthetic" if it does not correspond to an actual, physical control on the device. An example for this is Keyboard.anyKey or the up/down/left/right buttons added by StickControl.
The value of this property is determined by the layout (InputControlLayout) that the control has been built from.
The primary effect of being synthetic is in interactive rebinding (see InputActionRebindingExtensions.RebindingOperation) where non-synthetic controls will be favored over synthetic ones. This means, for example, that if both "&lt;Gamepad&gt;/leftStick/x" and "&lt;Gamepad&gt;/leftStick/left" are suitable picks, "&lt;Gamepad&gt;/leftStick/x" will be favored as it represents input from an actual physical control whereas "&lt;Gamepad&gt;/leftStick/left" represents input from a made-up control. If, however, the "left" button is the only viable pick, it will be accepted.
See also
InputControlLayout.ControlItem.isSynthetic, InputControlAttribute.synthetic
this[string path]
InputControl UnityEngine.InputSystem.InputControl< TValue >.this[string path] get
Fetch a control from the control's hierarchy by name.
Note that path matching is case-insensitive.
gamepad["leftStick"] // Returns Gamepad.leftStick
gamepad["leftStick/x"] // Returns Gamepad.leftStick.x
gamepad["{PrimaryAction}"] // Returns the control with PrimaryAction usage, that is, Gamepad.aButton
Exceptions
KeyNotFoundException path cannot be found.
See also
InputControlPath, path, TryGetChildControl
usages
ReadOnlyArray<InternedString> UnityEngine.InputSystem.InputControl< TValue >.usages get
List of usage tags associated with the control.
Usages apply "semantics" to a control. Whereas the name of a control identifies a particular "endpoint" within the control hierarchy, the usages of a control identify particular roles of specific control. A simple example is CommonUsages.Back which identifies a control generally used to move backwards in the navigation history of a UI. On a keyboard, it is the escape key that generally fulfills this role whereas on a gamepad, it is generally the "B" / "Circle" button. Some devices may not have a control that generally fulfills this function and thus may not have any control with the "Back" usage.
By looking up controls by usage rather than by name, it is possible to locate the correct control to use for certain standardized situation without having to know the particulars of the device or platform.
// Bind to any control which is tagged with the "Back" usage on any device.
var backAction = new InputAction(binding: "*&zwj;/{Back}");
Note that usages on devices work slightly differently than usages of controls on devices. They are also queried through this property but unlike the usages of controls, the set of usages of a device can be changed dynamically as the role of the device changes. For details, see InputSystem.SetDeviceUsage(InputDevice,string). Controls, on the other hand, can currently only be assigned usages through layouts (InputControlAttribute.usage or InputControlAttribute.usages).
See also
InputControlAttribute.usage, InputControlAttribute.usages, InputSystem.SetDeviceUsage(InputDevice,string), InputSystem.AddDeviceUsage(InputDevice,string), InputSystem.RemoveDeviceUsage(InputDevice,string), CommonUsages
Referenced by UnityEngine.InputSystem.InputControlPath.ParsedPathComponent.Matches().
valueSizeInBytes [1/2]
int UnityEngine.InputSystem.InputControl< TValue >.valueSizeInBytes get abstract
Size in bytes of values that the control returns.
See also
valueType
valueSizeInBytes [2/2]
override int UnityEngine.InputSystem.InputControl< TValue >.valueSizeInBytes get
valueType [1/2]
Type UnityEngine.InputSystem.InputControl< TValue >.valueType get abstract
Returns the underlying value type of this control.
Type of values produced by the control.
This is the type of values that are returned when reading the current value of a control or when reading a value of a control from an event.
See also
valueSizeInBytes, ReadValueFromStateAsObject
valueType [2/2]
override Type UnityEngine.InputSystem.InputControl< TValue >.valueType get
variants
string UnityEngine.InputSystem.InputControl< TValue >.variants get
Semicolon-separated list of variants of the control layout or "default".
"Lefty" when using the "Lefty" gamepad layout.
The documentation for this class was generated from the following file:
C:/Users/Lykos/Desktop/Projects/Capstone/VRGames/Library/PackageCache/com.unity.inputsystem@1.3.0/InputSystem/Controls/InputControl.cs