VRGames: UnityEngine.EventSystems.AbstractEventData Class Reference
UnityEngine.EventSystems.AbstractEventData Class Reference abstract
A class that can be used for sending simple events via the event system.
Public Member Functions
virtual void Reset ()
Reset the event.
virtual void Use ()
Use the event.
Protected Attributes
bool m_Used
Properties
virtual bool used [get]
Is the event used?
Detailed Description
A class that can be used for sending simple events via the event system.
Member Function Documentation
Reset()
virtual void UnityEngine.EventSystems.AbstractEventData.Reset () virtual
Reset the event.
Referenced by UnityEngine.EventSystems.OVRInputModule.GetCanvasPointerData(), UnityEngine.EventSystems.OVRInputModule.GetGazePointerData(), UnityEngine.EventSystems.PointerInputModule.GetMousePointerEventData(), and UnityEngine.EventSystems.PointerInputModule.GetTouchPointerEventData().
Use()
virtual void UnityEngine.EventSystems.AbstractEventData.Use () virtual
Use the event.
Internally sets a flag that can be checked via used to see if further processing should happen.
Referenced by TMPro.TMP_InputField.OnDrag(), TMPro.TMP_InputField.OnPointerDown(), and TMPro.TMP_InputField.OnUpdateSelected().
Member Data Documentation
m_Used
bool UnityEngine.EventSystems.AbstractEventData.m_Used protected
Referenced by UnityEngine.EventSystems.AbstractEventData.Reset(), and UnityEngine.EventSystems.AbstractEventData.Use().
Property Documentation
used
virtual bool UnityEngine.EventSystems.AbstractEventData.used get
Is the event used?
The documentation for this class was generated from the following file:
C:/Users/Lykos/Desktop/Projects/Capstone/VRGames/Library/PackageCache/com.unity.ugui@1.0.0/Runtime/EventSystem/EventData/BaseEventData.cs