VRCapstoneGames: Oculus.Interaction.HandPosing.HandGrabPoint Class Reference
Oculus.Interaction.HandPosing.HandGrabPoint Class Reference
Used in conjunction with HandGrabInteractable or DistanceHandGrabInteractable, the HandGrabPoint defines the local point in an object to which the grip point of the hand should align. It can also contain information about the final pose of the hand for perfect alignment as well as a surface that indicates the valid positions for the point.
Public Member Functions
void SetPose (HandPose handPose, in Pose gripPoint, Transform relativeTo)
Applies the given position/rotation to the HandGrabPoint.
HandGrabPointData SaveData ()
void LoadData (HandGrabPointData data, Transform relativeTo)
virtual bool CalculateBestPose (Pose userPose, Handedness handedness, ref HandPose bestHandPose, ref Pose bestSnapPoint, in PoseMeasureParameters scoringModifier, out bool usesHandPose, out float score)
void InjectRelativeTo (Transform relativeTo)
void InjectOptionalSurface (ISnapSurface surface)
void InjectOptionalHandPose (HandPose handPose)
void InjectAllHandGrabPoint (Transform relativeTo)
Protected Member Functions
virtual void Reset ()
virtual void Start ()
Properties
ISnapSurface SnapSurface [get]
HandPose HandPose [get]
float Scale [get]
Transform RelativeTo [get, set]
Pose RelativeGrip [get]
Detailed Description
Used in conjunction with HandGrabInteractable or DistanceHandGrabInteractable, the HandGrabPoint defines the local point in an object to which the grip point of the hand should align. It can also contain information about the final pose of the hand for perfect alignment as well as a surface that indicates the valid positions for the point.
Member Function Documentation
CalculateBestPose()
virtual bool Oculus.Interaction.HandPosing.HandGrabPoint.CalculateBestPose (Pose userPose, Handedness handedness, ref HandPose bestHandPose, ref Pose bestSnapPoint, in PoseMeasureParameters scoringModifier, out bool usesHandPose, out float score) virtual
InjectAllHandGrabPoint()
void Oculus.Interaction.HandPosing.HandGrabPoint.InjectAllHandGrabPoint (Transform relativeTo)
InjectOptionalHandPose()
void Oculus.Interaction.HandPosing.HandGrabPoint.InjectOptionalHandPose (HandPose handPose)
InjectOptionalSurface()
void Oculus.Interaction.HandPosing.HandGrabPoint.InjectOptionalSurface (ISnapSurface surface)
Referenced by Oculus.Interaction.HandPosing.Editor.HandGrabPointEditor.CloneHandGrabPoint(), and Oculus.Interaction.HandPosing.Editor.HandGrabPointEditor.MirrorHandGrabPoint().
InjectRelativeTo()
void Oculus.Interaction.HandPosing.HandGrabPoint.InjectRelativeTo (Transform relativeTo)
Referenced by Oculus.Interaction.HandPosing.HandGrabPoint.InjectAllHandGrabPoint().
LoadData()
void Oculus.Interaction.HandPosing.HandGrabPoint.LoadData (HandGrabPointData data, Transform relativeTo)
Referenced by Oculus.Interaction.HandPosing.Editor.HandGrabPointEditor.CloneHandGrabPoint(), Oculus.Interaction.HandPosing.HandGrabInteractable.LoadPoint(), and Oculus.Interaction.HandPosing.Editor.HandGrabPointEditor.MirrorHandGrabPoint().
Reset()
virtual void Oculus.Interaction.HandPosing.HandGrabPoint.Reset () protected virtual
SaveData()
HandGrabPointData Oculus.Interaction.HandPosing.HandGrabPoint.SaveData ()
Referenced by Oculus.Interaction.HandPosing.Editor.HandGrabPointEditor.CloneHandGrabPoint(), and Oculus.Interaction.HandPosing.Editor.HandGrabPointEditor.MirrorHandGrabPoint().
SetPose()
void Oculus.Interaction.HandPosing.HandGrabPoint.SetPose (HandPose handPose, in Pose gripPoint, Transform relativeTo)
Applies the given position/rotation to the HandGrabPoint.
Parameters
handPose Relative hand position/rotation.
relativeTo Reference coordinates for the pose.
Start()
virtual void Oculus.Interaction.HandPosing.HandGrabPoint.Start () protected virtual
Property Documentation
HandPose
HandPose Oculus.Interaction.HandPosing.HandGrabPoint.HandPose get
Referenced by Oculus.Interaction.HandPosing.HandGrabPoint.LoadData(), Oculus.Interaction.HandPosing.Editor.HandGrabPointEditor.MirrorHandGrabPoint(), Oculus.Interaction.HandPosing.Editor.HandGrabPointEditor.OnInspectorGUI(), Oculus.Interaction.HandPosing.HandGrabPoint.SaveData(), Oculus.Interaction.HandPosing.Visuals.HandGhost.SetPose(), and Oculus.Interaction.HandPosing.HandGrabPoint.SetPose().
RelativeGrip
Pose Oculus.Interaction.HandPosing.HandGrabPoint.RelativeGrip get
Referenced by Oculus.Interaction.HandPosing.Visuals.HandGhost.SetPose().
RelativeTo
Transform Oculus.Interaction.HandPosing.HandGrabPoint.RelativeTo get set
Referenced by Oculus.Interaction.HandPosing.Editor.HandGrabPointEditor.CloneHandGrabPoint(), Oculus.Interaction.HandPosing.Editor.HandGrabPointEditor.MirrorHandGrabPoint(), and Oculus.Interaction.HandPosing.Visuals.HandGhost.SetPose().
Scale
float Oculus.Interaction.HandPosing.HandGrabPoint.Scale get
Referenced by Oculus.Interaction.HandPosing.GrabPointsPoseFinder.FindInterpolationRange(), and Oculus.Interaction.HandPosing.HandGrabPoint.SaveData().
SnapSurface
ISnapSurface Oculus.Interaction.HandPosing.HandGrabPoint.SnapSurface get
Referenced by Oculus.Interaction.HandPosing.Editor.HandGrabPointEditor.CloneHandGrabPoint(), Oculus.Interaction.HandPosing.HandGrabPoint.InjectOptionalSurface(), and Oculus.Interaction.HandPosing.Editor.HandGrabPointEditor.MirrorHandGrabPoint().
The documentation for this class was generated from the following file:
C:/Users/Lykos/Desktop/Projects/Capstone/VRGames/Assets/ThirdParty/Oculus/Interaction/Runtime/Scripts/Interaction/Models/HandGrab/HandGrabPoint.cs