VRCapstoneGames: Oculus.Avatar.CAPI Class Reference
Oculus.Avatar.CAPI Class Reference
Public Types
enum Result {
Success = 0 , Failure = -1000 , Failure_InvalidParameter = -1001 , Failure_NotInitialized = -1002 ,
Failure_InvalidOperation = -1003 , Failure_Unsupported = -1004 , Failure_NotYetImplemented = -1005 , Failure_OperationFailed = -1006 ,
Failure_InsufficientSize = -1007
}
Public Member Functions
static void ovrAvatar_Initialize (string appID)
static void ovrAvatar_Shutdown ()
static IntPtr ovrAvatarMessage_Pop ()
static ovrAvatarMessageType ovrAvatarMessage_GetType (IntPtr msg)
static void ovrAvatarMessage_Free (IntPtr msg)
static IntPtr ovrAvatarSpecificationRequest_Create (UInt64 userID)
static void ovrAvatarSpecificationRequest_Destroy (IntPtr specificationRequest)
static void ovrAvatarSpecificationRequest_SetCombineMeshes (IntPtr specificationRequest, bool useCombinedMesh)
static void ovrAvatarSpecificationRequest_SetLookAndFeelVersion (IntPtr specificationRequest, ovrAvatarLookAndFeelVersion version)
static void ovrAvatarSpecificationRequest_SetLevelOfDetail (IntPtr specificationRequest, ovrAvatarAssetLevelOfDetail lod)
static void ovrAvatar_RequestAvatarSpecification (UInt64 userID)
static void ovrAvatar_RequestAvatarSpecificationFromSpecRequest (IntPtr specificationRequest)
static void ovrAvatarSpecificationRequest_SetFallbackLookAndFeelVersion (IntPtr specificationRequest, ovrAvatarLookAndFeelVersion version)
static void ovrAvatarSpecificationRequest_SetExpressiveFlag (IntPtr specificationRequest, bool enable)
static IntPtr ovrAvatar_Create (IntPtr avatarSpecification, ovrAvatarCapabilities capabilities)
static void ovrAvatar_Destroy (IntPtr avatar)
static void ovrAvatarPose_UpdateBody (IntPtr avatar, ovrAvatarTransform headPose)
static void ovrAvatarPose_UpdateHands (IntPtr avatar, ovrAvatarHandInputState inputStateLeft, ovrAvatarHandInputState inputStateRight)
static void ovrAvatarPose_UpdateHandsWithType (IntPtr avatar, ovrAvatarHandInputState inputStateLeft, ovrAvatarHandInputState inputStateRight, ovrAvatarControllerType type)
static void ovrAvatarPose_Finalize (IntPtr avatar, float elapsedSeconds)
static void ovrAvatar_SetLeftControllerVisibility (IntPtr avatar, bool show)
static void ovrAvatar_SetRightControllerVisibility (IntPtr avatar, bool show)
static void ovrAvatar_SetLeftHandVisibility (IntPtr avatar, bool show)
static void ovrAvatar_SetRightHandVisibility (IntPtr avatar, bool show)
static UInt32 ovrAvatarComponent_Count (IntPtr avatar)
static IntPtr ovrAvatarComponent_Get_Native (IntPtr avatar, UInt32 index)
static void ovrAvatarAsset_BeginLoading (UInt64 assetID)
static bool ovrAvatarAsset_BeginLoadingLOD (UInt64 assetId, ovrAvatarAssetLevelOfDetail lod)
static ovrAvatarAssetType ovrAvatarAsset_GetType (IntPtr assetHandle)
static UInt32 ovrAvatarAsset_GetMeshBlendShapeCount (IntPtr assetPtr)
static IntPtr ovrAvatarAsset_GetMeshBlendShapeName (IntPtr assetPtr, UInt32 index)
static UInt32 ovrAvatarAsset_GetSubmeshCount (IntPtr assetPtr)
static UInt32 ovrAvatarAsset_GetSubmeshLastIndex (IntPtr assetPtr, UInt32 index)
static IntPtr ovrAvatarAsset_GetMeshBlendShapeVertices (IntPtr assetPtr)
static IntPtr ovrAvatarAsset_GetAvatar (IntPtr assetHandle)
static IntPtr ovrAvatarAsset_GetCombinedMeshIDs_Native (IntPtr assetHandle, IntPtr count)
static IntPtr ovrAvatar_GetCombinedMeshAlphaData_Native (IntPtr avatar, IntPtr textureIDPtr, IntPtr offsetPtr)
static ovrAvatarRenderPartType ovrAvatarRenderPart_GetType (IntPtr renderPart)
static ovrAvatarTransform ovrAvatarSkinnedMeshRender_GetTransform (IntPtr renderPart)
static ovrAvatarTransform ovrAvatarSkinnedMeshRenderPBS_GetTransform (IntPtr renderPart)
static ovrAvatarTransform ovrAvatarSkinnedMeshRenderPBSV2_GetTransform (IntPtr renderPart)
static ovrAvatarVisibilityFlags ovrAvatarSkinnedMeshRender_GetVisibilityMask (IntPtr renderPart)
static bool ovrAvatarSkinnedMeshRender_MaterialStateChanged (IntPtr renderPart)
static bool ovrAvatarSkinnedMeshRenderPBSV2_MaterialStateChanged (IntPtr renderPart)
static ovrAvatarVisibilityFlags ovrAvatarSkinnedMeshRenderPBS_GetVisibilityMask (IntPtr renderPart)
static ovrAvatarVisibilityFlags ovrAvatarSkinnedMeshRenderPBSV2_GetVisibilityMask (IntPtr renderPart)
static ovrAvatarMaterialState ovrAvatarSkinnedMeshRender_GetMaterialState (IntPtr renderPart)
static ovrAvatarPBSMaterialState ovrAvatarSkinnedMeshRenderPBSV2_GetPBSMaterialState (IntPtr renderPart)
static ovrAvatarExpressiveParameters ovrAvatar_GetExpressiveParameters (IntPtr avatar)
static UInt64 ovrAvatarSkinnedMeshRender_GetDirtyJoints (IntPtr renderPart)
static UInt64 ovrAvatarSkinnedMeshRenderPBS_GetDirtyJoints (IntPtr renderPart)
static UInt64 ovrAvatarSkinnedMeshRenderPBSV2_GetDirtyJoints (IntPtr renderPart)
static ovrAvatarTransform ovrAvatarSkinnedMeshRender_GetJointTransform (IntPtr renderPart, UInt32 jointIndex)
static void ovrAvatar_SetActionUnitOnsetSpeed (IntPtr avatar, float onsetSpeed)
static void ovrAvatar_SetActionUnitFalloffSpeed (IntPtr avatar, float falloffSpeed)
static void ovrAvatar_SetVisemeMultiplier (IntPtr avatar, float visemeMultiplier)
static ovrAvatarTransform ovrAvatarSkinnedMeshRenderPBS_GetJointTransform (IntPtr renderPart, UInt32 jointIndex)
static ovrAvatarTransform ovrAvatarSkinnedMeshRenderPBSV2_GetJointTransform (IntPtr renderPart, UInt32 jointIndex)
static UInt64 ovrAvatarSkinnedMeshRenderPBS_GetAlbedoTextureAssetID (IntPtr renderPart)
static UInt64 ovrAvatarSkinnedMeshRenderPBS_GetSurfaceTextureAssetID (IntPtr renderPart)
static UInt32 ovrAvatar_GetReferencedAssetCount (IntPtr avatar)
static UInt64 ovrAvatar_GetReferencedAsset (IntPtr avatar, UInt32 index)
static void ovrAvatar_SetLeftHandGesture (IntPtr avatar, ovrAvatarHandGesture gesture)
static void ovrAvatar_SetRightHandGesture (IntPtr avatar, ovrAvatarHandGesture gesture)
static void ovrAvatar_SetLeftHandCustomGesture (IntPtr avatar, UInt32 jointCount, [In] ovrAvatarTransform[] customJointTransforms)
static void ovrAvatar_SetRightHandCustomGesture (IntPtr avatar, UInt32 jointCount, [In] ovrAvatarTransform[] customJointTransforms)
static void ovrAvatar_UpdatePoseFromPacket (IntPtr avatar, IntPtr packet, float secondsFromStart)
static void ovrAvatarPacket_BeginRecording (IntPtr avatar)
static IntPtr ovrAvatarPacket_EndRecording (IntPtr avatar)
static UInt32 ovrAvatarPacket_GetSize (IntPtr packet)
static float ovrAvatarPacket_GetDurationSeconds (IntPtr packet)
static void ovrAvatarPacket_Free (IntPtr packet)
static bool ovrAvatarPacket_Write (IntPtr packet, UInt32 bufferSize, [Out] byte[] buffer)
static IntPtr ovrAvatarPacket_Read (UInt32 bufferSize, [In] byte[] buffer)
static void ovrAvatar_UpdateWorldTransform (IntPtr avatar, ovrAvatarTransform transform)
static void ovrAvatar_RemoveGazeTargets (UInt32 targetCount, UInt32[] ids)
static void ovrAvatar_RemoveLights (UInt32 lightCount, UInt32[] ids)
delegate void LoggingDelegate (IntPtr str)
static void ovrAvatar_RegisterLoggingCallback (LoggingDelegate callback)
static void ovrAvatar_SetLoggingLevel (ovrAvatarLogLevel level)
static IntPtr ovrAvatar_GetDebugTransforms_Native (IntPtr count)
static IntPtr ovrAvatar_GetDebugLines_Native (IntPtr count)
static void ovrAvatar_SetDebugDrawContext (UInt32 context)
Static Public Member Functions
static void Initialize ()
static void Shutdown ()
static ovrAvatarMessage_AvatarSpecification ovrAvatarMessage_GetAvatarSpecification (IntPtr msg)
static ovrAvatarMessage_AssetLoaded ovrAvatarMessage_GetAssetLoaded (IntPtr msg)
static void ovrAvatarPose_UpdateVoiceVisualization (IntPtr avatar, float[] pcmData)
static void ovrAvatarComponent_Get (IntPtr avatar, UInt32 index, bool includeName, ref ovrAvatarComponent component)
static void ovrAvatarComponent_Get (IntPtr componentPtr, bool includeName, ref ovrAvatarComponent component)
static bool ovrAvatarPose_GetBaseComponent (IntPtr avatar, ref ovrAvatarBaseComponent component)
static IntPtr MarshalRenderComponent< T > (IntPtr ptr)
static bool ovrAvatarPose_GetBodyComponent (IntPtr avatar, ref ovrAvatarBodyComponent component)
static bool ovrAvatarPose_GetLeftControllerComponent (IntPtr avatar, ref ovrAvatarControllerComponent component)
static bool ovrAvatarPose_GetRightControllerComponent (IntPtr avatar, ref ovrAvatarControllerComponent component)
static bool ovrAvatarPose_GetLeftHandComponent (IntPtr avatar, ref ovrAvatarHandComponent component)
static bool ovrAvatarPose_GetRightHandComponent (IntPtr avatar, ref ovrAvatarHandComponent component)
static ovrAvatarMeshAssetData ovrAvatarAsset_GetMeshData (IntPtr assetPtr)
static ovrAvatarMeshAssetDataV2 ovrAvatarAsset_GetCombinedMeshData (IntPtr assetPtr)
static UInt64[] ovrAvatarAsset_GetCombinedMeshIDs (IntPtr assetHandle)
static void ovrAvatar_GetCombinedMeshAlphaData (IntPtr avatar, ref UInt64 textureID, ref Vector4 offset)
static ovrAvatarTextureAssetData ovrAvatarAsset_GetTextureData (IntPtr assetPtr)
static ovrAvatarMaterialState ovrAvatarAsset_GetMaterialState (IntPtr assetPtr)
static ovrAvatarRenderPart_SkinnedMeshRender ovrAvatarRenderPart_GetSkinnedMeshRender (IntPtr renderPart)
static ovrAvatarRenderPart_SkinnedMeshRenderPBS ovrAvatarRenderPart_GetSkinnedMeshRenderPBS (IntPtr renderPart)
static ovrAvatarRenderPart_SkinnedMeshRenderPBS_V2 ovrAvatarRenderPart_GetSkinnedMeshRenderPBSV2 (IntPtr renderPart)
static void ovrAvatarSkinnedMeshRender_GetBlendShapeParams (IntPtr renderPart, ref ovrAvatarBlendShapeParams blendParams)
static ovrAvatarRenderPart_ProjectorRender ovrAvatarRenderPart_GetProjectorRender (IntPtr renderPart)
static ovrAvatarPBSMaterialState[] ovrAvatar_GetBodyPBSMaterialStates (IntPtr renderPart)
static void ovrAvatar_SetForceASTCTextures (bool value)
static void ovrAvatar_OverrideExpressiveLogic (IntPtr avatar, ovrAvatarBlendShapeParams blendParams)
static void ovrAvatar_SetVisemes (IntPtr avatar, ovrAvatarVisemes visemes)
static void ovrAvatar_UpdateGazeTargets (ovrAvatarGazeTargets targets)
static void ovrAvatar_UpdateLights (ovrAvatarLights lights)
static void LoggingCallback (IntPtr str)
static void ovrAvatar_DrawDebugLines ()
static bool SendEvent (string name, string param="", string source="")
static string ovrp_GetVersion ()
Static Public Attributes
static readonly System.Version AvatarSDKVersion = new System.Version(1, 36, 0)
Member Enumeration Documentation
Result
enum Oculus.Avatar.CAPI.Result
Enumerator
Success
Success.
Failure
Failure.
Failure_InvalidParameter
Failure_NotInitialized
Failure_InvalidOperation
Failure_Unsupported
Failure_NotYetImplemented
Failure_OperationFailed
Failure_InsufficientSize
Member Function Documentation
Initialize()
static void Oculus.Avatar.CAPI.Initialize () static
LoggingCallback()
static void Oculus.Avatar.CAPI.LoggingCallback (IntPtr str) static
LoggingDelegate()
delegate void Oculus.Avatar.CAPI.LoggingDelegate (IntPtr str)
MarshalRenderComponent< T >()
static IntPtr Oculus.Avatar.CAPI.MarshalRenderComponent< T > (IntPtr ptr) static
Type Constraints
T : struct
ovrAvatar_Create()
static IntPtr Oculus.Avatar.CAPI.ovrAvatar_Create (IntPtr avatarSpecification, ovrAvatarCapabilities capabilities)
ovrAvatar_Destroy()
static void Oculus.Avatar.CAPI.ovrAvatar_Destroy (IntPtr avatar)
ovrAvatar_DrawDebugLines()
static void Oculus.Avatar.CAPI.ovrAvatar_DrawDebugLines () static
ovrAvatar_GetBodyPBSMaterialStates()
static ovrAvatarPBSMaterialState[] Oculus.Avatar.CAPI.ovrAvatar_GetBodyPBSMaterialStates (IntPtr renderPart) static
ovrAvatar_GetCombinedMeshAlphaData()
static void Oculus.Avatar.CAPI.ovrAvatar_GetCombinedMeshAlphaData (IntPtr avatar, ref UInt64 textureID, ref Vector4 offset) static
Referenced by OvrAvatar.CombinedMeshLoadedCallback().
ovrAvatar_GetCombinedMeshAlphaData_Native()
static IntPtr Oculus.Avatar.CAPI.ovrAvatar_GetCombinedMeshAlphaData_Native (IntPtr avatar, IntPtr textureIDPtr, IntPtr offsetPtr)
Referenced by Oculus.Avatar.CAPI.ovrAvatar_GetCombinedMeshAlphaData().
ovrAvatar_GetDebugLines_Native()
static IntPtr Oculus.Avatar.CAPI.ovrAvatar_GetDebugLines_Native (IntPtr count)
Referenced by Oculus.Avatar.CAPI.ovrAvatar_DrawDebugLines().
ovrAvatar_GetDebugTransforms_Native()
static IntPtr Oculus.Avatar.CAPI.ovrAvatar_GetDebugTransforms_Native (IntPtr count)
Referenced by Oculus.Avatar.CAPI.ovrAvatar_DrawDebugLines().
ovrAvatar_GetExpressiveParameters()
static ovrAvatarExpressiveParameters Oculus.Avatar.CAPI.ovrAvatar_GetExpressiveParameters (IntPtr avatar)
ovrAvatar_GetReferencedAsset()
static UInt64 Oculus.Avatar.CAPI.ovrAvatar_GetReferencedAsset (IntPtr avatar, UInt32 index)
ovrAvatar_GetReferencedAssetCount()
static UInt32 Oculus.Avatar.CAPI.ovrAvatar_GetReferencedAssetCount (IntPtr avatar)
ovrAvatar_Initialize()
static void Oculus.Avatar.CAPI.ovrAvatar_Initialize (string appID)
ovrAvatar_OverrideExpressiveLogic()
static void Oculus.Avatar.CAPI.ovrAvatar_OverrideExpressiveLogic (IntPtr avatar, ovrAvatarBlendShapeParams blendParams) static
ovrAvatar_RegisterLoggingCallback()
static void Oculus.Avatar.CAPI.ovrAvatar_RegisterLoggingCallback (LoggingDelegate callback)
ovrAvatar_RemoveGazeTargets()
static void Oculus.Avatar.CAPI.ovrAvatar_RemoveGazeTargets (UInt32 targetCount, UInt32[] ids)
ovrAvatar_RemoveLights()
static void Oculus.Avatar.CAPI.ovrAvatar_RemoveLights (UInt32 lightCount, UInt32[] ids)
ovrAvatar_RequestAvatarSpecification()
static void Oculus.Avatar.CAPI.ovrAvatar_RequestAvatarSpecification (UInt64 userID)
ovrAvatar_RequestAvatarSpecificationFromSpecRequest()
static void Oculus.Avatar.CAPI.ovrAvatar_RequestAvatarSpecificationFromSpecRequest (IntPtr specificationRequest)
ovrAvatar_SetActionUnitFalloffSpeed()
static void Oculus.Avatar.CAPI.ovrAvatar_SetActionUnitFalloffSpeed (IntPtr avatar, float falloffSpeed)
ovrAvatar_SetActionUnitOnsetSpeed()
static void Oculus.Avatar.CAPI.ovrAvatar_SetActionUnitOnsetSpeed (IntPtr avatar, float onsetSpeed)
ovrAvatar_SetDebugDrawContext()
static void Oculus.Avatar.CAPI.ovrAvatar_SetDebugDrawContext (UInt32 context)
ovrAvatar_SetForceASTCTextures()
static void Oculus.Avatar.CAPI.ovrAvatar_SetForceASTCTextures (bool value) static
ovrAvatar_SetLeftControllerVisibility()
static void Oculus.Avatar.CAPI.ovrAvatar_SetLeftControllerVisibility (IntPtr avatar, bool show)
Referenced by OvrAvatar.ShowLeftController().
ovrAvatar_SetLeftHandCustomGesture()
static void Oculus.Avatar.CAPI.ovrAvatar_SetLeftHandCustomGesture (IntPtr avatar, UInt32 jointCount, [In] ovrAvatarTransform[] customJointTransforms)
ovrAvatar_SetLeftHandGesture()
static void Oculus.Avatar.CAPI.ovrAvatar_SetLeftHandGesture (IntPtr avatar, ovrAvatarHandGesture gesture)
ovrAvatar_SetLeftHandVisibility()
static void Oculus.Avatar.CAPI.ovrAvatar_SetLeftHandVisibility (IntPtr avatar, bool show)
ovrAvatar_SetLoggingLevel()
static void Oculus.Avatar.CAPI.ovrAvatar_SetLoggingLevel (ovrAvatarLogLevel level)
ovrAvatar_SetRightControllerVisibility()
static void Oculus.Avatar.CAPI.ovrAvatar_SetRightControllerVisibility (IntPtr avatar, bool show)
Referenced by OvrAvatar.ShowRightController().
ovrAvatar_SetRightHandCustomGesture()
static void Oculus.Avatar.CAPI.ovrAvatar_SetRightHandCustomGesture (IntPtr avatar, UInt32 jointCount, [In] ovrAvatarTransform[] customJointTransforms)
ovrAvatar_SetRightHandGesture()
static void Oculus.Avatar.CAPI.ovrAvatar_SetRightHandGesture (IntPtr avatar, ovrAvatarHandGesture gesture)
ovrAvatar_SetRightHandVisibility()
static void Oculus.Avatar.CAPI.ovrAvatar_SetRightHandVisibility (IntPtr avatar, bool show)
ovrAvatar_SetVisemeMultiplier()
static void Oculus.Avatar.CAPI.ovrAvatar_SetVisemeMultiplier (IntPtr avatar, float visemeMultiplier)
ovrAvatar_SetVisemes()
static void Oculus.Avatar.CAPI.ovrAvatar_SetVisemes (IntPtr avatar, ovrAvatarVisemes visemes) static
ovrAvatar_Shutdown()
static void Oculus.Avatar.CAPI.ovrAvatar_Shutdown ()
ovrAvatar_UpdateGazeTargets()
static void Oculus.Avatar.CAPI.ovrAvatar_UpdateGazeTargets (ovrAvatarGazeTargets targets) static
ovrAvatar_UpdateLights()
static void Oculus.Avatar.CAPI.ovrAvatar_UpdateLights (ovrAvatarLights lights) static
ovrAvatar_UpdatePoseFromPacket()
static void Oculus.Avatar.CAPI.ovrAvatar_UpdatePoseFromPacket (IntPtr avatar, IntPtr packet, float secondsFromStart)
ovrAvatar_UpdateWorldTransform()
static void Oculus.Avatar.CAPI.ovrAvatar_UpdateWorldTransform (IntPtr avatar, ovrAvatarTransform transform)
ovrAvatarAsset_BeginLoading()
static void Oculus.Avatar.CAPI.ovrAvatarAsset_BeginLoading (UInt64 assetID)
ovrAvatarAsset_BeginLoadingLOD()
static bool Oculus.Avatar.CAPI.ovrAvatarAsset_BeginLoadingLOD (UInt64 assetId, ovrAvatarAssetLevelOfDetail lod)
Referenced by OvrAvatarSDKManager.BeginLoadingAsset().
ovrAvatarAsset_GetAvatar()
static IntPtr Oculus.Avatar.CAPI.ovrAvatarAsset_GetAvatar (IntPtr assetHandle)
ovrAvatarAsset_GetCombinedMeshData()
static ovrAvatarMeshAssetDataV2 Oculus.Avatar.CAPI.ovrAvatarAsset_GetCombinedMeshData (IntPtr assetPtr) static
ovrAvatarAsset_GetCombinedMeshIDs()
static UInt64[] Oculus.Avatar.CAPI.ovrAvatarAsset_GetCombinedMeshIDs (IntPtr assetHandle) static
Referenced by OvrAvatar.CombinedMeshLoadedCallback().
ovrAvatarAsset_GetCombinedMeshIDs_Native()
static IntPtr Oculus.Avatar.CAPI.ovrAvatarAsset_GetCombinedMeshIDs_Native (IntPtr assetHandle, IntPtr count)
Referenced by Oculus.Avatar.CAPI.ovrAvatarAsset_GetCombinedMeshIDs().
ovrAvatarAsset_GetMaterialState()
static ovrAvatarMaterialState Oculus.Avatar.CAPI.ovrAvatarAsset_GetMaterialState (IntPtr assetPtr) static
Referenced by OvrAvatarAssetMaterial.OvrAvatarAssetMaterial().
ovrAvatarAsset_GetMeshBlendShapeCount()
static UInt32 Oculus.Avatar.CAPI.ovrAvatarAsset_GetMeshBlendShapeCount (IntPtr assetPtr)
ovrAvatarAsset_GetMeshBlendShapeName()
static IntPtr Oculus.Avatar.CAPI.ovrAvatarAsset_GetMeshBlendShapeName (IntPtr assetPtr, UInt32 index)
ovrAvatarAsset_GetMeshBlendShapeVertices()
static IntPtr Oculus.Avatar.CAPI.ovrAvatarAsset_GetMeshBlendShapeVertices (IntPtr assetPtr)
ovrAvatarAsset_GetMeshData()
static ovrAvatarMeshAssetData Oculus.Avatar.CAPI.ovrAvatarAsset_GetMeshData (IntPtr assetPtr) static
ovrAvatarAsset_GetSubmeshCount()
static UInt32 Oculus.Avatar.CAPI.ovrAvatarAsset_GetSubmeshCount (IntPtr assetPtr)
ovrAvatarAsset_GetSubmeshLastIndex()
static UInt32 Oculus.Avatar.CAPI.ovrAvatarAsset_GetSubmeshLastIndex (IntPtr assetPtr, UInt32 index)
ovrAvatarAsset_GetTextureData()
static ovrAvatarTextureAssetData Oculus.Avatar.CAPI.ovrAvatarAsset_GetTextureData (IntPtr assetPtr) static
Referenced by OvrAvatarAssetTexture.OvrAvatarAssetTexture().
ovrAvatarAsset_GetType()
static ovrAvatarAssetType Oculus.Avatar.CAPI.ovrAvatarAsset_GetType (IntPtr assetHandle)
ovrAvatarComponent_Count()
static UInt32 Oculus.Avatar.CAPI.ovrAvatarComponent_Count (IntPtr avatar)
ovrAvatarComponent_Get() [1/2]
static void Oculus.Avatar.CAPI.ovrAvatarComponent_Get (IntPtr avatar, UInt32 index, bool includeName, ref ovrAvatarComponent component) static
Referenced by OvrAvatarBody.GetNativeAvatarComponent(), Oculus.Avatar.CAPI.ovrAvatarComponent_Get(), and OvrAvatarComponent.UpdateAvatar().
ovrAvatarComponent_Get() [2/2]
static void Oculus.Avatar.CAPI.ovrAvatarComponent_Get (IntPtr componentPtr, bool includeName, ref ovrAvatarComponent component) static
ovrAvatarComponent_Get_Native()
static IntPtr Oculus.Avatar.CAPI.ovrAvatarComponent_Get_Native (IntPtr avatar, UInt32 index)
Referenced by Oculus.Avatar.CAPI.ovrAvatarComponent_Get().
ovrAvatarMessage_Free()
static void Oculus.Avatar.CAPI.ovrAvatarMessage_Free (IntPtr msg)
ovrAvatarMessage_GetAssetLoaded()
static ovrAvatarMessage_AssetLoaded Oculus.Avatar.CAPI.ovrAvatarMessage_GetAssetLoaded (IntPtr msg) static
ovrAvatarMessage_GetAvatarSpecification()
static ovrAvatarMessage_AvatarSpecification Oculus.Avatar.CAPI.ovrAvatarMessage_GetAvatarSpecification (IntPtr msg) static
ovrAvatarMessage_GetType()
static ovrAvatarMessageType Oculus.Avatar.CAPI.ovrAvatarMessage_GetType (IntPtr msg)
ovrAvatarMessage_Pop()
static IntPtr Oculus.Avatar.CAPI.ovrAvatarMessage_Pop ()
ovrAvatarPacket_BeginRecording()
static void Oculus.Avatar.CAPI.ovrAvatarPacket_BeginRecording (IntPtr avatar)
ovrAvatarPacket_EndRecording()
static IntPtr Oculus.Avatar.CAPI.ovrAvatarPacket_EndRecording (IntPtr avatar)
ovrAvatarPacket_Free()
static void Oculus.Avatar.CAPI.ovrAvatarPacket_Free (IntPtr packet)
ovrAvatarPacket_GetDurationSeconds()
static float Oculus.Avatar.CAPI.ovrAvatarPacket_GetDurationSeconds (IntPtr packet)
ovrAvatarPacket_GetSize()
static UInt32 Oculus.Avatar.CAPI.ovrAvatarPacket_GetSize (IntPtr packet)
Referenced by SocialPlatformManager.OnLocalAvatarPacketRecorded().
ovrAvatarPacket_Read()
static IntPtr Oculus.Avatar.CAPI.ovrAvatarPacket_Read (UInt32 bufferSize, [In] byte[] buffer)
Referenced by P2PManager.processAvatarPacket().
ovrAvatarPacket_Write()
static bool Oculus.Avatar.CAPI.ovrAvatarPacket_Write (IntPtr packet, UInt32 bufferSize, [Out] byte[] buffer)
Referenced by SocialPlatformManager.OnLocalAvatarPacketRecorded().
ovrAvatarPose_Finalize()
static void Oculus.Avatar.CAPI.ovrAvatarPose_Finalize (IntPtr avatar, float elapsedSeconds)
ovrAvatarPose_GetBaseComponent()
static bool Oculus.Avatar.CAPI.ovrAvatarPose_GetBaseComponent (IntPtr avatar, ref ovrAvatarBaseComponent component) static
ovrAvatarPose_GetBodyComponent()
static bool Oculus.Avatar.CAPI.ovrAvatarPose_GetBodyComponent (IntPtr avatar, ref ovrAvatarBodyComponent component) static
Referenced by OvrAvatar.GetBodyComponent(), and OvrAvatarBody.GetNativeAvatarComponent().
ovrAvatarPose_GetLeftControllerComponent()
static bool Oculus.Avatar.CAPI.ovrAvatarPose_GetLeftControllerComponent (IntPtr avatar, ref ovrAvatarControllerComponent component) static
ovrAvatarPose_GetLeftHandComponent()
static bool Oculus.Avatar.CAPI.ovrAvatarPose_GetLeftHandComponent (IntPtr avatar, ref ovrAvatarHandComponent component) static
ovrAvatarPose_GetRightControllerComponent()
static bool Oculus.Avatar.CAPI.ovrAvatarPose_GetRightControllerComponent (IntPtr avatar, ref ovrAvatarControllerComponent component) static
ovrAvatarPose_GetRightHandComponent()
static bool Oculus.Avatar.CAPI.ovrAvatarPose_GetRightHandComponent (IntPtr avatar, ref ovrAvatarHandComponent component) static
ovrAvatarPose_UpdateBody()
static void Oculus.Avatar.CAPI.ovrAvatarPose_UpdateBody (IntPtr avatar, ovrAvatarTransform headPose)
Referenced by OvrAvatarDriver.UpdateTransformsFromPose().
ovrAvatarPose_UpdateHands()
static void Oculus.Avatar.CAPI.ovrAvatarPose_UpdateHands (IntPtr avatar, ovrAvatarHandInputState inputStateLeft, ovrAvatarHandInputState inputStateRight)
ovrAvatarPose_UpdateHandsWithType()
static void Oculus.Avatar.CAPI.ovrAvatarPose_UpdateHandsWithType (IntPtr avatar, ovrAvatarHandInputState inputStateLeft, ovrAvatarHandInputState inputStateRight, ovrAvatarControllerType type)
Referenced by OvrAvatarDriver.UpdateTransformsFromPose().
ovrAvatarPose_UpdateVoiceVisualization()
static void Oculus.Avatar.CAPI.ovrAvatarPose_UpdateVoiceVisualization (IntPtr avatar, float[] pcmData) static
ovrAvatarRenderPart_GetProjectorRender()
static ovrAvatarRenderPart_ProjectorRender Oculus.Avatar.CAPI.ovrAvatarRenderPart_GetProjectorRender (IntPtr renderPart) static
ovrAvatarRenderPart_GetSkinnedMeshRender()
static ovrAvatarRenderPart_SkinnedMeshRender Oculus.Avatar.CAPI.ovrAvatarRenderPart_GetSkinnedMeshRender (IntPtr renderPart) static
ovrAvatarRenderPart_GetSkinnedMeshRenderPBS()
static ovrAvatarRenderPart_SkinnedMeshRenderPBS Oculus.Avatar.CAPI.ovrAvatarRenderPart_GetSkinnedMeshRenderPBS (IntPtr renderPart) static
ovrAvatarRenderPart_GetSkinnedMeshRenderPBSV2()
static ovrAvatarRenderPart_SkinnedMeshRenderPBS_V2 Oculus.Avatar.CAPI.ovrAvatarRenderPart_GetSkinnedMeshRenderPBSV2 (IntPtr renderPart) static
ovrAvatarRenderPart_GetType()
static ovrAvatarRenderPartType Oculus.Avatar.CAPI.ovrAvatarRenderPart_GetType (IntPtr renderPart)
Referenced by OvrAvatarComponent.UpdateAvatar(), and OvrAvatarRenderComponent.UpdateSkinnedMesh().
ovrAvatarSkinnedMeshRender_GetBlendShapeParams()
static void Oculus.Avatar.CAPI.ovrAvatarSkinnedMeshRender_GetBlendShapeParams (IntPtr renderPart, ref ovrAvatarBlendShapeParams blendParams) static
Referenced by OvrAvatarSkinnedMeshPBSV2RenderComponent.UpdateSkinnedMeshRender().
ovrAvatarSkinnedMeshRender_GetDirtyJoints()
static UInt64 Oculus.Avatar.CAPI.ovrAvatarSkinnedMeshRender_GetDirtyJoints (IntPtr renderPart)
Referenced by OvrAvatarRenderComponent.UpdateSkinnedMesh().
ovrAvatarSkinnedMeshRender_GetJointTransform()
static ovrAvatarTransform Oculus.Avatar.CAPI.ovrAvatarSkinnedMeshRender_GetJointTransform (IntPtr renderPart, UInt32 jointIndex)
Referenced by OvrAvatarRenderComponent.UpdateSkinnedMesh().
ovrAvatarSkinnedMeshRender_GetMaterialState()
static ovrAvatarMaterialState Oculus.Avatar.CAPI.ovrAvatarSkinnedMeshRender_GetMaterialState (IntPtr renderPart)
Referenced by OvrAvatarSkinnedMeshRenderComponent.UpdateSkinnedMeshRender().
ovrAvatarSkinnedMeshRender_GetTransform()
static ovrAvatarTransform Oculus.Avatar.CAPI.ovrAvatarSkinnedMeshRender_GetTransform (IntPtr renderPart)
Referenced by OvrAvatarSkinnedMeshRenderComponent.UpdateSkinnedMeshRender().
ovrAvatarSkinnedMeshRender_GetVisibilityMask()
static ovrAvatarVisibilityFlags Oculus.Avatar.CAPI.ovrAvatarSkinnedMeshRender_GetVisibilityMask (IntPtr renderPart)
Referenced by OvrAvatarSkinnedMeshRenderComponent.UpdateSkinnedMeshRender().
ovrAvatarSkinnedMeshRender_MaterialStateChanged()
static bool Oculus.Avatar.CAPI.ovrAvatarSkinnedMeshRender_MaterialStateChanged (IntPtr renderPart)
Referenced by OvrAvatarSkinnedMeshRenderComponent.UpdateSkinnedMeshRender().
ovrAvatarSkinnedMeshRenderPBS_GetAlbedoTextureAssetID()
static UInt64 Oculus.Avatar.CAPI.ovrAvatarSkinnedMeshRenderPBS_GetAlbedoTextureAssetID (IntPtr renderPart)
ovrAvatarSkinnedMeshRenderPBS_GetDirtyJoints()
static UInt64 Oculus.Avatar.CAPI.ovrAvatarSkinnedMeshRenderPBS_GetDirtyJoints (IntPtr renderPart)
Referenced by OvrAvatarRenderComponent.UpdateSkinnedMesh().
ovrAvatarSkinnedMeshRenderPBS_GetJointTransform()
static ovrAvatarTransform Oculus.Avatar.CAPI.ovrAvatarSkinnedMeshRenderPBS_GetJointTransform (IntPtr renderPart, UInt32 jointIndex)
Referenced by OvrAvatarRenderComponent.UpdateSkinnedMesh().
ovrAvatarSkinnedMeshRenderPBS_GetSurfaceTextureAssetID()
static UInt64 Oculus.Avatar.CAPI.ovrAvatarSkinnedMeshRenderPBS_GetSurfaceTextureAssetID (IntPtr renderPart)
ovrAvatarSkinnedMeshRenderPBS_GetTransform()
static ovrAvatarTransform Oculus.Avatar.CAPI.ovrAvatarSkinnedMeshRenderPBS_GetTransform (IntPtr renderPart)
ovrAvatarSkinnedMeshRenderPBS_GetVisibilityMask()
static ovrAvatarVisibilityFlags Oculus.Avatar.CAPI.ovrAvatarSkinnedMeshRenderPBS_GetVisibilityMask (IntPtr renderPart)
ovrAvatarSkinnedMeshRenderPBSV2_GetDirtyJoints()
static UInt64 Oculus.Avatar.CAPI.ovrAvatarSkinnedMeshRenderPBSV2_GetDirtyJoints (IntPtr renderPart)
Referenced by OvrAvatarRenderComponent.UpdateSkinnedMesh().
ovrAvatarSkinnedMeshRenderPBSV2_GetJointTransform()
static ovrAvatarTransform Oculus.Avatar.CAPI.ovrAvatarSkinnedMeshRenderPBSV2_GetJointTransform (IntPtr renderPart, UInt32 jointIndex)
Referenced by OvrAvatarRenderComponent.UpdateSkinnedMesh().
ovrAvatarSkinnedMeshRenderPBSV2_GetPBSMaterialState()
static ovrAvatarPBSMaterialState Oculus.Avatar.CAPI.ovrAvatarSkinnedMeshRenderPBSV2_GetPBSMaterialState (IntPtr renderPart)
ovrAvatarSkinnedMeshRenderPBSV2_GetTransform()
static ovrAvatarTransform Oculus.Avatar.CAPI.ovrAvatarSkinnedMeshRenderPBSV2_GetTransform (IntPtr renderPart)
Referenced by OvrAvatarSkinnedMeshPBSV2RenderComponent.UpdateSkinnedMeshRender().
ovrAvatarSkinnedMeshRenderPBSV2_GetVisibilityMask()
static ovrAvatarVisibilityFlags Oculus.Avatar.CAPI.ovrAvatarSkinnedMeshRenderPBSV2_GetVisibilityMask (IntPtr renderPart)
Referenced by OvrAvatarSkinnedMeshPBSV2RenderComponent.UpdateSkinnedMeshRender().
ovrAvatarSkinnedMeshRenderPBSV2_MaterialStateChanged()
static bool Oculus.Avatar.CAPI.ovrAvatarSkinnedMeshRenderPBSV2_MaterialStateChanged (IntPtr renderPart)
ovrAvatarSpecificationRequest_Create()
static IntPtr Oculus.Avatar.CAPI.ovrAvatarSpecificationRequest_Create (UInt64 userID)
ovrAvatarSpecificationRequest_Destroy()
static void Oculus.Avatar.CAPI.ovrAvatarSpecificationRequest_Destroy (IntPtr specificationRequest)
ovrAvatarSpecificationRequest_SetCombineMeshes()
static void Oculus.Avatar.CAPI.ovrAvatarSpecificationRequest_SetCombineMeshes (IntPtr specificationRequest, bool useCombinedMesh)
ovrAvatarSpecificationRequest_SetExpressiveFlag()
static void Oculus.Avatar.CAPI.ovrAvatarSpecificationRequest_SetExpressiveFlag (IntPtr specificationRequest, bool enable)
ovrAvatarSpecificationRequest_SetFallbackLookAndFeelVersion()
static void Oculus.Avatar.CAPI.ovrAvatarSpecificationRequest_SetFallbackLookAndFeelVersion (IntPtr specificationRequest, ovrAvatarLookAndFeelVersion version)
ovrAvatarSpecificationRequest_SetLevelOfDetail()
static void Oculus.Avatar.CAPI.ovrAvatarSpecificationRequest_SetLevelOfDetail (IntPtr specificationRequest, ovrAvatarAssetLevelOfDetail lod)
ovrAvatarSpecificationRequest_SetLookAndFeelVersion()
static void Oculus.Avatar.CAPI.ovrAvatarSpecificationRequest_SetLookAndFeelVersion (IntPtr specificationRequest, ovrAvatarLookAndFeelVersion version)
ovrp_GetVersion()
static string Oculus.Avatar.CAPI.ovrp_GetVersion () static
Referenced by Oculus.Avatar.CAPI.SendEvent().
SendEvent()
static bool Oculus.Avatar.CAPI.SendEvent (string name, string param = "", string source = "") static
Shutdown()
static void Oculus.Avatar.CAPI.Shutdown () static
Member Data Documentation
AvatarSDKVersion
readonly System.Version Oculus.Avatar.CAPI.AvatarSDKVersion = new System.Version(1, 36, 0) static
The documentation for this class was generated from the following file:
C:/Users/Lykos/Desktop/Projects/Capstone/VRGames/Assets/ThirdParty/Oculus/Avatar/Scripts/OvrAvatarSDKCAPI.cs