VRCapstoneGames: UnityEngine.XR.Management.XRLoaderHelper Class Reference
UnityEngine.XR.Management.XRLoaderHelper Class Reference abstract
XR Loader abstract subclass used as a base class for specific provider implementations. Class provides some helper logic that can be used to handle subsystem handling in a typesafe manner, reducing potential boilerplate code.
Public Member Functions
override T GetLoadedSubsystem< T > ()
Gets the loaded subsystem of the specified type. Implementation dependent as only implemetnations know what they have loaded and how best to get it..
override bool Deinitialize ()
Override of XRLoader.Deinitialize to provide for clearing the instance map.true.
Public Member Functions inherited from UnityEngine.XR.Management.XRLoader
virtual bool Initialize ()
Initialize the loader. This should initialize all subsystems to support the desired runtime setup this loader represents.
virtual bool Start ()
Ask loader to start all initialized subsystems.
virtual bool Stop ()
Ask loader to stop all initialized subsystems.
T GetLoadedSubsystem< T > ()
Gets the loaded subsystem of the specified type. Implementation dependent as only implemetnations know what they have loaded and how best to get it..
virtual List< GraphicsDeviceType > GetSupportedGraphicsDeviceTypes (bool buildingPlayer)
Gets the loader's supported graphics device types. If the list is empty, it is assumed that it supports all graphics device types.
Protected Member Functions
void StartSubsystem< T > ()
Start a subsystem instance of a given type. Subsystem assumed to already be loaded from a previous call to CreateSubsystem.
void StopSubsystem< T > ()
Stop a subsystem instance of a given type. Subsystem assumed to already be loaded from a previous call to CreateSubsystem.
void DestroySubsystem< T > ()
Destroy a subsystem instance of a given type. Subsystem assumed to already be loaded from a previous call to CreateSubsystem.
void CreateSubsystem< TDescriptor, TSubsystem > (List< TDescriptor > descriptors, string id)
Creates a subsystem given a list of descriptors and a specific subsystem id.
void CreateIntegratedSubsystem< TDescriptor, TSubsystem > (List< TDescriptor > descriptors, string id)
Creates a native, integrated subsystem given a list of descriptors and a specific subsystem id. DEPRECATED: Please use the geenric CreateSubsystem method. This method is soley retained for backwards compatibility and will be removed in a future release.
void CreateStandaloneSubsystem< TDescriptor, TSubsystem > (List< TDescriptor > descriptors, string id)
Creates a managed, standalone subsystem given a list of descriptors and a specific subsystem id. DEPRECATED: Please use the geenric CreateSubsystem method. This method is soley retained for backwards compatibility and will be removed in a future release.
Protected Attributes
Dictionary< Type, ISubsystem > m_SubsystemInstanceMap = new Dictionary<Type, ISubsystem>()
Map of loaded susbsystems. Used so we don't always have to fo to XRSubsystemManger and do a manual search to find the instance we loaded.
Detailed Description
XR Loader abstract subclass used as a base class for specific provider implementations. Class provides some helper logic that can be used to handle subsystem handling in a typesafe manner, reducing potential boilerplate code.
Member Function Documentation
CreateIntegratedSubsystem< TDescriptor, TSubsystem >()
void UnityEngine.XR.Management.XRLoaderHelper.CreateIntegratedSubsystem< TDescriptor, TSubsystem > (List< TDescriptor > descriptors, string id) protected
Creates a native, integrated subsystem given a list of descriptors and a specific subsystem id. DEPRECATED: Please use the geenric CreateSubsystem method. This method is soley retained for backwards compatibility and will be removed in a future release.
Template Parameters
TDescriptor The descriptor type being passed in.
TSubsystem The subsystem type being requested
Parameters
descriptors List of TDescriptor instances to use for subsystem matching.
id The identifier key of the particualr subsystem implementation being requested.
Type Constraints
TDescriptor : IntegratedSubsystemDescriptor
TSubsystem : IntegratedSubsystem
CreateStandaloneSubsystem< TDescriptor, TSubsystem >()
void UnityEngine.XR.Management.XRLoaderHelper.CreateStandaloneSubsystem< TDescriptor, TSubsystem > (List< TDescriptor > descriptors, string id) protected
Creates a managed, standalone subsystem given a list of descriptors and a specific subsystem id. DEPRECATED: Please use the geenric CreateSubsystem method. This method is soley retained for backwards compatibility and will be removed in a future release.
Template Parameters
TDescriptor The descriptor type being passed in.
TSubsystem The subsystem type being requested
Parameters
descriptors List of TDescriptor instances to use for subsystem matching.
id The identifier key of the particualr subsystem implementation being requested.
Type Constraints
TDescriptor : SubsystemDescriptor
TSubsystem : Subsystem
CreateSubsystem< TDescriptor, TSubsystem >()
void UnityEngine.XR.Management.XRLoaderHelper.CreateSubsystem< TDescriptor, TSubsystem > (List< TDescriptor > descriptors, string id) protected
Creates a subsystem given a list of descriptors and a specific subsystem id.
You should make sure to destroy any subsystem that you created so that resources acquired by your subsystems are correctly cleaned up and released. This is especially important if you create them during initialization, but initialization fails. If that happens, you should clean up any subsystems created up to that point.
Template Parameters
TDescriptor The descriptor type being passed in.
TSubsystem The subsystem type being requested
Parameters
descriptors List of TDescriptor instances to use for subsystem matching.
id The identifier key of the particualr subsystem implementation being requested.
Type Constraints
TDescriptor : ISubsystemDescriptor
TSubsystem : ISubsystem
Referenced by UnityEngine.XR.Management.XRLoaderHelper.CreateIntegratedSubsystem< TDescriptor, TSubsystem >(), and UnityEngine.XR.Management.XRLoaderHelper.CreateStandaloneSubsystem< TDescriptor, TSubsystem >().
Deinitialize()
override bool UnityEngine.XR.Management.XRLoaderHelper.Deinitialize () virtual
Override of XRLoader.Deinitialize to provide for clearing the instance map.true.
If you override this method in your subclass, you must call the base implementation to allow the instance map tp be cleaned up correctly.
Returns
True if de-initialization was successful.
Reimplemented from UnityEngine.XR.Management.XRLoader.
DestroySubsystem< T >()
void UnityEngine.XR.Management.XRLoaderHelper.DestroySubsystem< T > () protected
Destroy a subsystem instance of a given type. Subsystem assumed to already be loaded from a previous call to CreateSubsystem.
Template Parameters
T A subclass of ISubsystem
Type Constraints
T : class
T : ISubsystem
GetLoadedSubsystem< T >()
override T UnityEngine.XR.Management.XRLoaderHelper.GetLoadedSubsystem< T > ()
Gets the loaded subsystem of the specified type. Implementation dependent as only implemetnations know what they have loaded and how best to get it..
Template Parameters
T Type of the subsystem to get.
Returns
The loaded subsystem or null if not found.
Referenced by UnityEngine.XR.Management.XRLoaderHelper.DestroySubsystem< T >(), UnityEngine.XR.Management.XRLoaderHelper.StartSubsystem< T >(), and UnityEngine.XR.Management.XRLoaderHelper.StopSubsystem< T >().
StartSubsystem< T >()
void UnityEngine.XR.Management.XRLoaderHelper.StartSubsystem< T > () protected
Start a subsystem instance of a given type. Subsystem assumed to already be loaded from a previous call to CreateSubsystem.
Template Parameters
T A subclass of ISubsystem
Type Constraints
T : class
T : ISubsystem
StopSubsystem< T >()
void UnityEngine.XR.Management.XRLoaderHelper.StopSubsystem< T > () protected
Stop a subsystem instance of a given type. Subsystem assumed to already be loaded from a previous call to CreateSubsystem.
Template Parameters
T A subclass of ISubsystem
Type Constraints
T : class
T : ISubsystem
Member Data Documentation
m_SubsystemInstanceMap
Dictionary<Type, ISubsystem> UnityEngine.XR.Management.XRLoaderHelper.m_SubsystemInstanceMap = new Dictionary<Type, ISubsystem>() protected
Map of loaded susbsystems. Used so we don't always have to fo to XRSubsystemManger and do a manual search to find the instance we loaded.
Referenced by UnityEngine.XR.Management.XRLoaderHelper.CreateSubsystem< TDescriptor, TSubsystem >(), UnityEngine.XR.Management.XRLoaderHelper.Deinitialize(), UnityEngine.XR.Management.XRLoaderHelper.DestroySubsystem< T >(), and UnityEngine.XR.Management.XRLoaderHelper.GetLoadedSubsystem< T >().
The documentation for this class was generated from the following file:
C:/Users/Lykos/Desktop/Projects/Capstone/VRGames/Library/PackageCache/com.unity.xr.management@4.2.1/Runtime/XRLoaderHelper.cs