VRCapstoneGames: Facebook.WitAi.Tests.End2EndTests Class Reference
Facebook.WitAi.Tests.End2EndTests Class Reference
Public Member Functions
IEnumerator TestConnection (ConnectionTest test)
IEnumerator End2EndTests_TestErrorCode_400 ()
IEnumerator End2EndTests_TestErrorCode_500 ()
IEnumerator End2EndTests_TestErrorCode_503 ()
IEnumerator End2EndTests_Message1024BoundaryTest_LessThan1024 ()
IEnumerator End2EndTests_Message1024BoundaryTest_Equal1024 ()
IEnumerator End2EndTests_Message1024BoundaryTest_MoreThan1024 ()
IEnumerator End2EndTests_Message1024BoundaryTest_LessThan1024_Chunked ()
IEnumerator End2EndTests_Message1024BoundaryTest_Equal1024_Chunked ()
IEnumerator End2EndTests_Message1024BoundaryTest_MoreThan1024_Chunked ()
IEnumerator SetupServer ()
Member Function Documentation
End2EndTests_Message1024BoundaryTest_Equal1024()
IEnumerator Facebook.WitAi.Tests.End2EndTests.End2EndTests_Message1024BoundaryTest_Equal1024 ()
End2EndTests_Message1024BoundaryTest_Equal1024_Chunked()
IEnumerator Facebook.WitAi.Tests.End2EndTests.End2EndTests_Message1024BoundaryTest_Equal1024_Chunked ()
End2EndTests_Message1024BoundaryTest_LessThan1024()
IEnumerator Facebook.WitAi.Tests.End2EndTests.End2EndTests_Message1024BoundaryTest_LessThan1024 ()
End2EndTests_Message1024BoundaryTest_LessThan1024_Chunked()
IEnumerator Facebook.WitAi.Tests.End2EndTests.End2EndTests_Message1024BoundaryTest_LessThan1024_Chunked ()
End2EndTests_Message1024BoundaryTest_MoreThan1024()
IEnumerator Facebook.WitAi.Tests.End2EndTests.End2EndTests_Message1024BoundaryTest_MoreThan1024 ()
End2EndTests_Message1024BoundaryTest_MoreThan1024_Chunked()
IEnumerator Facebook.WitAi.Tests.End2EndTests.End2EndTests_Message1024BoundaryTest_MoreThan1024_Chunked ()
End2EndTests_TestErrorCode_400()
IEnumerator Facebook.WitAi.Tests.End2EndTests.End2EndTests_TestErrorCode_400 ()
End2EndTests_TestErrorCode_500()
IEnumerator Facebook.WitAi.Tests.End2EndTests.End2EndTests_TestErrorCode_500 ()
End2EndTests_TestErrorCode_503()
IEnumerator Facebook.WitAi.Tests.End2EndTests.End2EndTests_TestErrorCode_503 ()
SetupServer()
IEnumerator Facebook.WitAi.Tests.End2EndTests.SetupServer ()
Referenced by Facebook.WitAi.Tests.End2EndTests.TestConnection().
TestConnection()
IEnumerator Facebook.WitAi.Tests.End2EndTests.TestConnection (ConnectionTest test)
Referenced by Facebook.WitAi.Tests.End2EndTests.End2EndTests_Message1024BoundaryTest_Equal1024(), Facebook.WitAi.Tests.End2EndTests.End2EndTests_Message1024BoundaryTest_Equal1024_Chunked(), Facebook.WitAi.Tests.End2EndTests.End2EndTests_Message1024BoundaryTest_LessThan1024(), Facebook.WitAi.Tests.End2EndTests.End2EndTests_Message1024BoundaryTest_LessThan1024_Chunked(), Facebook.WitAi.Tests.End2EndTests.End2EndTests_Message1024BoundaryTest_MoreThan1024(), Facebook.WitAi.Tests.End2EndTests.End2EndTests_Message1024BoundaryTest_MoreThan1024_Chunked(), Facebook.WitAi.Tests.End2EndTestsSlow.End2EndTests_Test_Timeout(), Facebook.WitAi.Tests.End2EndTestsSlow.End2EndTests_Test_Unclean_Termination(), Facebook.WitAi.Tests.End2EndTests.End2EndTests_TestErrorCode_400(), Facebook.WitAi.Tests.End2EndTests.End2EndTests_TestErrorCode_500(), and Facebook.WitAi.Tests.End2EndTests.End2EndTests_TestErrorCode_503().
The documentation for this class was generated from the following file:
C:/Users/Lykos/Desktop/Projects/Capstone/VRGames/Assets/ThirdParty/Oculus/Voice/Lib/Wit.ai/Tests/Runtime/End2EndTests/End2EndTests.cs