VRCapstoneGames: Oculus.Interaction.InteractorDriver Class Reference
Oculus.Interaction.InteractorDriver Class Reference
InteractorDriver provides a means to drive the update loop of an Interactor. Optionally can be provided an ActiveState to enable or disable the Interactor.
Public Member Functions
void UpdateInteraction ()
void UpdateHover ()
void UpdateSelection (bool selectionCanBeEmpty)
void Enable ()
void Disable ()
void InjectAllInteractorDriver (IInteractor interactor)
void InjectInteractor (IInteractor interactor)
void InjectOptionalActiveState (IActiveState activeState)
Public Attributes
IInteractor Interactor
Protected Member Functions
virtual void Awake ()
virtual void Start ()
virtual void OnDisable ()
virtual void Update ()
Protected Attributes
bool _started = false
Properties
bool IsRootInteractorDriver = true [get, set]
bool IsSelectingInteractable [get]
bool IsHovering [get]
bool IsSelecting [get]
bool HasCandidate [get]
IInteractor CandidateInteractor [get]
bool ShouldSelect [get]
Properties inherited from Oculus.Interaction.IInteractorDriver
Detailed Description
InteractorDriver provides a means to drive the update loop of an Interactor. Optionally can be provided an ActiveState to enable or disable the Interactor.
Member Function Documentation
Awake()
virtual void Oculus.Interaction.InteractorDriver.Awake () protected virtual
Disable()
void Oculus.Interaction.InteractorDriver.Disable ()
Implements Oculus.Interaction.IInteractorDriver.
Enable()
void Oculus.Interaction.InteractorDriver.Enable ()
Implements Oculus.Interaction.IInteractorDriver.
InjectAllInteractorDriver()
void Oculus.Interaction.InteractorDriver.InjectAllInteractorDriver (IInteractor interactor)
InjectInteractor()
void Oculus.Interaction.InteractorDriver.InjectInteractor (IInteractor interactor)
Referenced by Oculus.Interaction.InteractorDriver.InjectAllInteractorDriver().
InjectOptionalActiveState()
void Oculus.Interaction.InteractorDriver.InjectOptionalActiveState (IActiveState activeState)
OnDisable()
virtual void Oculus.Interaction.InteractorDriver.OnDisable () protected virtual
Start()
virtual void Oculus.Interaction.InteractorDriver.Start () protected virtual
Update()
virtual void Oculus.Interaction.InteractorDriver.Update () protected virtual
UpdateHover()
void Oculus.Interaction.InteractorDriver.UpdateHover ()
Implements Oculus.Interaction.IInteractorDriver.
Referenced by Oculus.Interaction.InteractorDriver.Update().
UpdateInteraction()
void Oculus.Interaction.InteractorDriver.UpdateInteraction ()
Implements Oculus.Interaction.IInteractorDriver.
Referenced by Oculus.Interaction.InteractorDriver.Update().
UpdateSelection()
void Oculus.Interaction.InteractorDriver.UpdateSelection (bool selectionCanBeEmpty)
Implements Oculus.Interaction.IInteractorDriver.
Referenced by Oculus.Interaction.InteractorDriver.Update().
Member Data Documentation
_started
bool Oculus.Interaction.InteractorDriver._started = false protected
Referenced by Oculus.Interaction.InteractorDriver.OnDisable(), and Oculus.Interaction.InteractorDriver.Start().
Interactor
IInteractor Oculus.Interaction.InteractorDriver.Interactor
Property Documentation
CandidateInteractor
IInteractor Oculus.Interaction.InteractorDriver.CandidateInteractor get
Implements Oculus.Interaction.IInteractorDriver.
HasCandidate
bool Oculus.Interaction.InteractorDriver.HasCandidate get
Implements Oculus.Interaction.IInteractorDriver.
IsHovering
bool Oculus.Interaction.InteractorDriver.IsHovering get
Implements Oculus.Interaction.IInteractorDriver.
IsRootInteractorDriver
bool Oculus.Interaction.InteractorDriver.IsRootInteractorDriver = true get set
Implements Oculus.Interaction.IInteractorDriver.
Referenced by Oculus.Interaction.InteractorDriver.Update().
IsSelecting
bool Oculus.Interaction.InteractorDriver.IsSelecting get
Implements Oculus.Interaction.IInteractorDriver.
IsSelectingInteractable
bool Oculus.Interaction.InteractorDriver.IsSelectingInteractable get
Implements Oculus.Interaction.IInteractorDriver.
ShouldSelect
bool Oculus.Interaction.InteractorDriver.ShouldSelect get
Implements Oculus.Interaction.IInteractorDriver.
The documentation for this class was generated from the following file:
C:/Users/Lykos/Desktop/Projects/Capstone/VRGames/Assets/ThirdParty/Oculus/Interaction/Runtime/Scripts/Interaction/Core/InteractorDriver.cs