VRCapstoneGames: UnityEngine.ProBuilder.Submesh Class Reference
UnityEngine.ProBuilder.Submesh Class Reference sealed
Defines a set of indices and material.
Public Member Functions
Submesh (int submeshIndex, MeshTopology topology, IEnumerable< int > indexes)
Creates a new Submesh from a submesh index for the material, the topology, and a set of indices.
Submesh (Mesh mesh, int subMeshIndex)
Creates a new Submesh from a source mesh and a submesh index for the material.
override string ToString ()
Returns a string that represents this Submesh.
Static Public Member Functions
static Submesh[] GetSubmeshes (IEnumerable< Face > faces, int submeshCount, MeshTopology preferredTopology=MeshTopology.Triangles)
Creates an array of submeshes from a set of faces. Currently only Quads and Triangles are supported.
Properties
IEnumerable< int > indexes [get, set]
Gets or sets the indices making up this submesh. Use the topology property to find out whether the submesh contains triangles or quads.
MeshTopology topology [get, set]
Gets or sets the topology (whether this submesh is made with triangles or quads).
int submeshIndex [get, set]
Gets or sets the index in the sharedMaterials array that this submesh aligns with.
Detailed Description
Defines a set of indices and material.
Constructor & Destructor Documentation
Submesh() [1/2]
UnityEngine.ProBuilder.Submesh.Submesh (int submeshIndex, MeshTopology topology, IEnumerable< int > indexes)
Creates a new Submesh from a submesh index for the material, the topology, and a set of indices.
Parameters
submeshIndex The index of this submesh that corresponds to the sharedMaterials property.
topology The topology of this submesh. ProBuilder only recognizes Triangles and Quads.
indexes The triangles or quads.
Referenced by UnityEngine.ProBuilder.Submesh.GetSubmeshes().
Submesh() [2/2]
UnityEngine.ProBuilder.Submesh.Submesh (Mesh mesh, int subMeshIndex)
Creates a new Submesh from a source mesh and a submesh index for the material.
Parameters
mesh The source mesh.
subMeshIndex Which submesh to read from.
Member Function Documentation
GetSubmeshes()
static Submesh[] UnityEngine.ProBuilder.Submesh.GetSubmeshes (IEnumerable< Face > faces, int submeshCount, MeshTopology preferredTopology = MeshTopology::Triangles) static
Creates an array of submeshes from a set of faces. Currently only Quads and Triangles are supported.
Parameters
faces The faces to be included in the list of submeshes. This method handles group submeshes by comparing the material property of each face.
submeshCount The number of submeshes to create. Usually you can set this value to the length of the Renderer.sharedMaterials array.
preferredTopology By default, ProBuilder creates triangles, but you can set this value to false to construct quads. However, ProBuilder falls back to creating triangles if it can't represent some faces in quad format.
Returns
An array of Submeshes.
Exceptions
NotImplementedException Thrown in the event that a MeshTopology other than Quads or Triangles is passed.
Referenced by UnityEditor.ProBuilder.Model.Model(), and UnityEngine.ProBuilder.ProBuilderMesh.ToMesh().
ToString()
override string UnityEngine.ProBuilder.Submesh.ToString ()
Returns a string that represents this Submesh.
Returns
A comma-delimited string (for example "[subMeshIndex],[topology],[indices]").
Property Documentation
indexes
IEnumerable<int> UnityEngine.ProBuilder.Submesh.indexes get set
Gets or sets the indices making up this submesh. Use the topology property to find out whether the submesh contains triangles or quads.
Referenced by UnityEngine.ProBuilder.Submesh.Submesh().
submeshIndex
int UnityEngine.ProBuilder.Submesh.submeshIndex get set
Gets or sets the index in the sharedMaterials array that this submesh aligns with.
Referenced by UnityEngine.ProBuilder.Submesh.GetSubmeshes(), and UnityEngine.ProBuilder.Submesh.Submesh().
topology
MeshTopology UnityEngine.ProBuilder.Submesh.topology get set
Gets or sets the topology (whether this submesh is made with triangles or quads).
Referenced by UnityEngine.ProBuilder.Submesh.Submesh().
The documentation for this class was generated from the following file:
C:/Users/Lykos/Desktop/Projects/Capstone/VRGames/Library/PackageCache/com.unity.probuilder@5.0.6/Runtime/Core/Submesh.cs