VRCapstoneGames: Oculus.Interaction.Interactor< TInteractor, TInteractable > Class Template Reference
Oculus.Interaction.Interactor< TInteractor, TInteractable > Class Template Reference abstract
Interactor provides a base template for any kind of interaction. Interactions can be wholly defined by three things: the concrete Interactor, the concrete Interactable, and the logic governing their coordination.
Public Member Functions
void UpdateInteractor ()
virtual void Select ()
virtual void Unselect ()
virtual bool IsFilterPassedBy (TInteractable interactable)
void Hover ()
void Enable ()
void Disable ()
void UpdateInteraction ()
void UpdateHover ()
void UpdateSelection (bool selectionCanBeEmpty)
void InjectOptionalActiveState (IActiveState activeState)
void InjectOptionalInteractableFilters (List< IInteractableFilter > interactableFilters)
Protected Member Functions
virtual void DoEveryUpdate ()
virtual void DoNormalUpdate ()
virtual void DoHoverUpdate ()
virtual void DoSelectUpdate (TInteractable interactable=null)
virtual void InteractableSet (TInteractable interactable)
virtual void InteractableUnset (TInteractable interactable)
virtual void InteractableSelected (TInteractable interactable)
virtual void InteractableUnselected (TInteractable interactable)
virtual void Awake ()
virtual void Start ()
virtual void OnEnable ()
virtual void OnDisable ()
virtual void OnDestroy ()
TInteractable ComputeCandidate ()
virtual void ComputeSelectActions ()
virtual void HandleSelected ()
virtual void HandleUnselected ()
virtual void Update ()
Protected Attributes
TInteractable _candidate
TInteractable _interactable
TInteractable _selectedInteractable
bool _started
Properties
virtual bool ShouldSelect [get, protected set]
virtual bool ShouldUnselect [get, protected set]
ISelector Selector [get, set]
InteractorState State [get]
TInteractable Candidate [get]
TInteractable Interactable [get]
TInteractable SelectedInteractable [get]
bool HasCandidate [get]
bool HasInteractable [get]
bool HasSelectedInteractable [get]
MAction< TInteractable > WhenInteractableSet [get]
MAction< TInteractable > WhenInteractableUnset [get]
MAction< TInteractable > WhenInteractableSelected [get]
MAction< TInteractable > WhenInteractableUnselected [get]
int Identifier [get]
bool IsRootInteractorDriver = true [get, set]
bool IsSelectingInteractable [get]
bool IsHovering [get]
bool IsSelecting [get]
IInteractor CandidateInteractor [get]
Properties inherited from Oculus.Interaction.IInteractor< TInteractable >
Properties inherited from Oculus.Interaction.IInteractorView< out TInteractable >
Properties inherited from Oculus.Interaction.IComponent
GameObject gameObject [get]
Properties inherited from Oculus.Interaction.IInteractorView< TInteractable >
int Identifier [get]
bool HasInteractable [get]
bool HasSelectedInteractable [get]
InteractorState State [get]
MAction< TInteractable > WhenInteractableSet [get]
MAction< TInteractable > WhenInteractableUnset [get]
MAction< TInteractable > WhenInteractableSelected [get]
MAction< TInteractable > WhenInteractableUnselected [get]
TInteractable Candidate [get]
TInteractable Interactable [get]
TInteractable SelectedInteractable [get]
Properties inherited from Oculus.Interaction.IInteractorDriver
Events
Action< InteractorStateChangeArgs > WhenStateChanged = delegate { }
Action WhenInteractorUpdated = delegate { }
Events inherited from Oculus.Interaction.IInteractorView< out TInteractable >
Action< InteractorStateChangeArgs > WhenStateChanged
Action WhenInteractorUpdated
Events inherited from Oculus.Interaction.IInteractorView< TInteractable >
Action< InteractorStateChangeArgs > WhenStateChanged
Action WhenInteractorUpdated
Detailed Description
Interactor provides a base template for any kind of interaction. Interactions can be wholly defined by three things: the concrete Interactor, the concrete Interactable, and the logic governing their coordination.
Subclasses are responsible for implementing that coordination logic via template methods that operate on the concrete interactor and interactable classes.
Type Constraints
TInteractor : class
TInteractor : IInteractor<TInteractable>
TInteractable : class
TInteractable : IInteractable<TInteractor>
Member Function Documentation
Awake()
virtual void Oculus.Interaction.Interactor< TInteractor, TInteractable >.Awake () protected virtual
Reimplemented in Oculus.Interaction.GrabInteractor, Oculus.Interaction.HandPosing.HandGrabInteractor, and Oculus.Interaction.RayInteractor.
ComputeCandidate()
TInteractable Oculus.Interaction.Interactor< TInteractor, TInteractable >.ComputeCandidate () abstract protected
ComputeSelectActions()
virtual void Oculus.Interaction.Interactor< TInteractor, TInteractable >.ComputeSelectActions () protected virtual
Disable()
void Oculus.Interaction.Interactor< TInteractor, TInteractable >.Disable ()
Implements Oculus.Interaction.IInteractor< TInteractable >.
Referenced by Oculus.Interaction.InteractorDriver.Disable(), and Oculus.Interaction.Interactor< TInteractor, TInteractable >.OnDisable().
DoEveryUpdate()
virtual void Oculus.Interaction.Interactor< TInteractor, TInteractable >.DoEveryUpdate () protected virtual
Reimplemented in Oculus.Interaction.GrabInteractor, Oculus.Interaction.HandPosing.HandGrabInteractor, Oculus.Interaction.PokeInteractor, and Oculus.Interaction.RayInteractor.
Referenced by Oculus.Interaction.Interactor< TInteractor, TInteractable >.UpdateInteractor().
DoHoverUpdate()
virtual void Oculus.Interaction.Interactor< TInteractor, TInteractable >.DoHoverUpdate () protected virtual
Reimplemented in Oculus.Interaction.HandPosing.HandGrabInteractor, and Oculus.Interaction.PokeInteractor.
DoNormalUpdate()
virtual void Oculus.Interaction.Interactor< TInteractor, TInteractable >.DoNormalUpdate () protected virtual
DoSelectUpdate()
virtual void Oculus.Interaction.Interactor< TInteractor, TInteractable >.DoSelectUpdate (TInteractable interactable = null) protected virtual
Enable()
void Oculus.Interaction.Interactor< TInteractor, TInteractable >.Enable ()
Implements Oculus.Interaction.IInteractor< TInteractable >.
Referenced by Oculus.Interaction.InteractorDriver.Enable(), Oculus.Interaction.Interactor< TInteractor, TInteractable >.OnEnable(), Oculus.Interaction.Interactor< TInteractor, TInteractable >.UpdateHover(), Oculus.Interaction.InteractorDriver.UpdateHover(), Oculus.Interaction.Interactor< TInteractor, TInteractable >.UpdateInteraction(), Oculus.Interaction.InteractorDriver.UpdateInteraction(), Oculus.Interaction.Interactor< TInteractor, TInteractable >.UpdateSelection(), and Oculus.Interaction.InteractorDriver.UpdateSelection().
HandleSelected()
virtual void Oculus.Interaction.Interactor< TInteractor, TInteractable >.HandleSelected () protected virtual
Referenced by Oculus.Interaction.Interactor< TInteractor, TInteractable >.Disable(), and Oculus.Interaction.Interactor< TInteractor, TInteractable >.Enable().
HandleUnselected()
virtual void Oculus.Interaction.Interactor< TInteractor, TInteractable >.HandleUnselected () protected virtual
Referenced by Oculus.Interaction.Interactor< TInteractor, TInteractable >.Disable(), and Oculus.Interaction.Interactor< TInteractor, TInteractable >.Enable().
Hover()
void Oculus.Interaction.Interactor< TInteractor, TInteractable >.Hover ()
Implements Oculus.Interaction.IInteractor< TInteractable >.
Referenced by Oculus.Interaction.Interactor< TInteractor, TInteractable >.UpdateHover(), and Oculus.Interaction.InteractorDriver.UpdateHover().
InjectOptionalActiveState()
void Oculus.Interaction.Interactor< TInteractor, TInteractable >.InjectOptionalActiveState (IActiveState activeState)
InjectOptionalInteractableFilters()
void Oculus.Interaction.Interactor< TInteractor, TInteractable >.InjectOptionalInteractableFilters (List< IInteractableFilter > interactableFilters)
InteractableSelected()
virtual void Oculus.Interaction.Interactor< TInteractor, TInteractable >.InteractableSelected (TInteractable interactable) protected virtual
InteractableSet()
virtual void Oculus.Interaction.Interactor< TInteractor, TInteractable >.InteractableSet (TInteractable interactable) protected virtual
InteractableUnselected()
virtual void Oculus.Interaction.Interactor< TInteractor, TInteractable >.InteractableUnselected (TInteractable interactable) protected virtual
InteractableUnset()
virtual void Oculus.Interaction.Interactor< TInteractor, TInteractable >.InteractableUnset (TInteractable interactable) protected virtual
IsFilterPassedBy()
virtual bool Oculus.Interaction.Interactor< TInteractor, TInteractable >.IsFilterPassedBy (TInteractable interactable) virtual
Implements Oculus.Interaction.IInteractor< TInteractable >.
OnDestroy()
virtual void Oculus.Interaction.Interactor< TInteractor, TInteractable >.OnDestroy () protected virtual
OnDisable()
virtual void Oculus.Interaction.Interactor< TInteractor, TInteractable >.OnDisable () protected virtual
OnEnable()
virtual void Oculus.Interaction.Interactor< TInteractor, TInteractable >.OnEnable () protected virtual
Select()
virtual void Oculus.Interaction.Interactor< TInteractor, TInteractable >.Select () virtual
Implements Oculus.Interaction.IInteractor< TInteractable >.
Referenced by Oculus.Interaction.Interactor< TInteractor, TInteractable >.UpdateSelection(), and Oculus.Interaction.InteractorDriver.UpdateSelection().
Start()
virtual void Oculus.Interaction.Interactor< TInteractor, TInteractable >.Start () protected virtual
Reimplemented in Oculus.Interaction.GrabInteractor, Oculus.Interaction.HandPosing.HandGrabInteractor, Oculus.Interaction.PokeInteractor, and Oculus.Interaction.RayInteractor.
Unselect()
virtual void Oculus.Interaction.Interactor< TInteractor, TInteractable >.Unselect () virtual
Implements Oculus.Interaction.IInteractor< TInteractable >.
Referenced by Oculus.Interaction.InteractorDriver.OnDisable(), Oculus.Interaction.Interactor< TInteractor, TInteractable >.UpdateSelection(), and Oculus.Interaction.InteractorDriver.UpdateSelection().
Update()
virtual void Oculus.Interaction.Interactor< TInteractor, TInteractable >.Update () protected virtual
UpdateHover()
void Oculus.Interaction.Interactor< TInteractor, TInteractable >.UpdateHover ()
Implements Oculus.Interaction.IInteractorDriver.
Referenced by Oculus.Interaction.Interactor< TInteractor, TInteractable >.Update().
UpdateInteraction()
void Oculus.Interaction.Interactor< TInteractor, TInteractable >.UpdateInteraction ()
Implements Oculus.Interaction.IInteractorDriver.
Referenced by Oculus.Interaction.Interactor< TInteractor, TInteractable >.Update().
UpdateInteractor()
void Oculus.Interaction.Interactor< TInteractor, TInteractable >.UpdateInteractor ()
Implements Oculus.Interaction.IInteractor< TInteractable >.
Referenced by Oculus.Interaction.Interactor< TInteractor, TInteractable >.Unselect(), Oculus.Interaction.Interactor< TInteractor, TInteractable >.UpdateInteraction(), and Oculus.Interaction.InteractorDriver.UpdateInteraction().
UpdateSelection()
void Oculus.Interaction.Interactor< TInteractor, TInteractable >.UpdateSelection (bool selectionCanBeEmpty)
Implements Oculus.Interaction.IInteractorDriver.
Referenced by Oculus.Interaction.Interactor< TInteractor, TInteractable >.Update().
Member Data Documentation
_candidate
TInteractable Oculus.Interaction.Interactor< TInteractor, TInteractable >._candidate protected
Referenced by Oculus.Interaction.Interactor< TInteractor, TInteractable >.Hover().
_interactable
TInteractable Oculus.Interaction.Interactor< TInteractor, TInteractable >._interactable protected
Referenced by Oculus.Interaction.Interactor< TInteractor, TInteractable >.Select().
_selectedInteractable
TInteractable Oculus.Interaction.Interactor< TInteractor, TInteractable >._selectedInteractable protected
_started
bool Oculus.Interaction.Interactor< TInteractor, TInteractable >._started protected
Referenced by Oculus.Interaction.Interactor< TInteractor, TInteractable >.OnDisable(), Oculus.Interaction.Interactor< TInteractor, TInteractable >.OnEnable(), and Oculus.Interaction.Interactor< TInteractor, TInteractable >.Start().
Property Documentation
Candidate
TInteractable Oculus.Interaction.Interactor< TInteractor, TInteractable >.Candidate get
Implements Oculus.Interaction.IInteractorView< out TInteractable >.
CandidateInteractor
IInteractor Oculus.Interaction.Interactor< TInteractor, TInteractable >.CandidateInteractor get
Implements Oculus.Interaction.IInteractorDriver.
HasCandidate
bool Oculus.Interaction.Interactor< TInteractor, TInteractable >.HasCandidate get
Implements Oculus.Interaction.IInteractor< TInteractable >.
HasInteractable
bool Oculus.Interaction.Interactor< TInteractor, TInteractable >.HasInteractable get
Implements Oculus.Interaction.IInteractorView< out TInteractable >.
Referenced by Oculus.Interaction.Interactor< TInteractor, TInteractable >.UpdateSelection(), and Oculus.Interaction.InteractorDriver.UpdateSelection().
HasSelectedInteractable
bool Oculus.Interaction.Interactor< TInteractor, TInteractable >.HasSelectedInteractable get
Implements Oculus.Interaction.IInteractorView< out TInteractable >.
Identifier
int Oculus.Interaction.Interactor< TInteractor, TInteractable >.Identifier get
Implements Oculus.Interaction.IInteractorView< out TInteractable >.
Interactable
TInteractable Oculus.Interaction.Interactor< TInteractor, TInteractable >.Interactable get
Implements Oculus.Interaction.IInteractorView< out TInteractable >.
IsHovering
bool Oculus.Interaction.Interactor< TInteractor, TInteractable >.IsHovering get
Implements Oculus.Interaction.IInteractorDriver.
IsRootInteractorDriver
bool Oculus.Interaction.Interactor< TInteractor, TInteractable >.IsRootInteractorDriver = true get set
Implements Oculus.Interaction.IInteractorDriver.
Referenced by Oculus.Interaction.Interactor< TInteractor, TInteractable >.Update().
IsSelecting
bool Oculus.Interaction.Interactor< TInteractor, TInteractable >.IsSelecting get
Implements Oculus.Interaction.IInteractorDriver.
IsSelectingInteractable
bool Oculus.Interaction.Interactor< TInteractor, TInteractable >.IsSelectingInteractable get
Implements Oculus.Interaction.IInteractorDriver.
SelectedInteractable
TInteractable Oculus.Interaction.Interactor< TInteractor, TInteractable >.SelectedInteractable get
Implements Oculus.Interaction.IInteractorView< out TInteractable >.
Referenced by Oculus.Interaction.HandPokeLimiterVisual.OnDisable(), and Oculus.Interaction.Samples.HideHandVisualOnGrab.Update().
Selector
ISelector Oculus.Interaction.Interactor< TInteractor, TInteractable >.Selector get set protected
Referenced by Oculus.Interaction.Interactor< TInteractor, TInteractable >.ComputeSelectActions().
ShouldSelect
virtual bool Oculus.Interaction.Interactor< TInteractor, TInteractable >.ShouldSelect get protected set
Implements Oculus.Interaction.IInteractor< TInteractable >.
Referenced by Oculus.Interaction.Interactor< TInteractor, TInteractable >.ComputeSelectActions(), Oculus.Interaction.Interactor< TInteractor, TInteractable >.Select(), Oculus.Interaction.Interactor< TInteractor, TInteractable >.UpdateSelection(), and Oculus.Interaction.InteractorDriver.UpdateSelection().
ShouldUnselect
virtual bool Oculus.Interaction.Interactor< TInteractor, TInteractable >.ShouldUnselect get protected set
Implements Oculus.Interaction.IInteractor< TInteractable >.
Referenced by Oculus.Interaction.Interactor< TInteractor, TInteractable >.ComputeSelectActions(), Oculus.Interaction.Interactor< TInteractor, TInteractable >.Unselect(), Oculus.Interaction.Interactor< TInteractor, TInteractable >.UpdateSelection(), and Oculus.Interaction.InteractorDriver.UpdateSelection().
State
InteractorState Oculus.Interaction.Interactor< TInteractor, TInteractable >.State get
Implements Oculus.Interaction.IInteractorView< out TInteractable >.
Referenced by Oculus.Interaction.Interactor< TInteractor, TInteractable >.Disable(), Oculus.Interaction.Interactor< TInteractor, TInteractable >.Enable(), Oculus.Interaction.Interactor< TInteractor, TInteractable >.Hover(), Oculus.Interaction.Interactor< TInteractor, TInteractable >.Select(), Oculus.Interaction.Interactor< TInteractor, TInteractable >.Unselect(), Oculus.Interaction.Samples.HideHandVisualOnGrab.Update(), and Oculus.Interaction.Interactor< TInteractor, TInteractable >.UpdateInteractor().
WhenInteractableSelected
MAction<TInteractable> Oculus.Interaction.Interactor< TInteractor, TInteractable >.WhenInteractableSelected get
Implements Oculus.Interaction.IInteractorView< out TInteractable >.
WhenInteractableSet
MAction<TInteractable> Oculus.Interaction.Interactor< TInteractor, TInteractable >.WhenInteractableSet get
Implements Oculus.Interaction.IInteractorView< out TInteractable >.
WhenInteractableUnselected
MAction<TInteractable> Oculus.Interaction.Interactor< TInteractor, TInteractable >.WhenInteractableUnselected get
Implements Oculus.Interaction.IInteractorView< out TInteractable >.
WhenInteractableUnset
MAction<TInteractable> Oculus.Interaction.Interactor< TInteractor, TInteractable >.WhenInteractableUnset get
Implements Oculus.Interaction.IInteractorView< out TInteractable >.
Event Documentation
WhenInteractorUpdated
Action Oculus.Interaction.Interactor< TInteractor, TInteractable >.WhenInteractorUpdated = delegate { }
Referenced by Oculus.Interaction.Interactor< TInteractor, TInteractable >.UpdateInteractor().
WhenStateChanged
Action<InteractorStateChangeArgs> Oculus.Interaction.Interactor< TInteractor, TInteractable >.WhenStateChanged = delegate { }
The documentation for this class was generated from the following file:
C:/Users/Lykos/Desktop/Projects/Capstone/VRGames/Assets/ThirdParty/Oculus/Interaction/Runtime/Scripts/Interaction/Core/Interactor.cs