VRGames: UnityEngine.ProBuilder.KdTree.KdTreeNode< TKey, TValue > Class Template Reference
UnityEngine.ProBuilder.KdTree.KdTreeNode< TKey, TValue > Class Template Reference
Public Member Functions
KdTreeNode ()
KdTreeNode (TKey[] point, TValue value)
void AddDuplicate (TValue value)
override string ToString ()
Public Attributes
TKey[] Point
TValue Value = default(TValue)
List< TValue > Duplicates = null
Properties
bool IsLeaf [get]
Constructor & Destructor Documentation
KdTreeNode() [1/2]
UnityEngine.ProBuilder.KdTree.KdTreeNode< TKey, TValue >.KdTreeNode ()
KdTreeNode() [2/2]
UnityEngine.ProBuilder.KdTree.KdTreeNode< TKey, TValue >.KdTreeNode (TKey[] point, TValue value)
Member Function Documentation
AddDuplicate()
void UnityEngine.ProBuilder.KdTree.KdTreeNode< TKey, TValue >.AddDuplicate (TValue value)
Referenced by UnityEngine.ProBuilder.KdTree.KdTree< TKey, TValue >.Add().
ToString()
override string UnityEngine.ProBuilder.KdTree.KdTreeNode< TKey, TValue >.ToString ()
Referenced by UnityEngine.ProBuilder.KdTree.KdTreeNode< TKey, TValue >.ToString().
Member Data Documentation
Duplicates
List<TValue> UnityEngine.ProBuilder.KdTree.KdTreeNode< TKey, TValue >.Duplicates = null
Referenced by UnityEngine.ProBuilder.KdTree.KdTreeNode< TKey, TValue >.AddDuplicate().
Point
TKey [] UnityEngine.ProBuilder.KdTree.KdTreeNode< TKey, TValue >.Point
Referenced by UnityEngine.ProBuilder.KdTree.KdTree< TKey, TValue >.Add(), and UnityEngine.ProBuilder.KdTree.KdTree< TKey, TValue >.RemoveAt().
Value
TValue UnityEngine.ProBuilder.KdTree.KdTreeNode< TKey, TValue >.Value = default(TValue)
Referenced by UnityEngine.ProBuilder.KdTree.KdTreeNode< TKey, TValue >.KdTreeNode(), UnityEngine.ProBuilder.KdTree.KdTreeNode< TKey, TValue >.ToString(), and UnityEngine.ProBuilder.KdTree.KdTree< TKey, TValue >.TryFindValueAt().
Property Documentation
IsLeaf
bool UnityEngine.ProBuilder.KdTree.KdTreeNode< TKey, TValue >.IsLeaf get
The documentation for this class was generated from the following file:
C:/Users/Lykos/Desktop/Projects/Capstone/VRGames/Library/PackageCache/com.unity.probuilder@5.0.6/External/KdTree/KdTreeLib/KdTreeNode.cs