VRCapstoneGames: UnityEditor.SettingsManagement.PackageSettingsRepository Class Reference
UnityEditor.SettingsManagement.PackageSettingsRepository Class Reference sealed
A settings repository that stores data local to a Unity project.
Public Member Functions
PackageSettingsRepository (string package, string name)
Constructor sets the serialized data path.
void Save ()
Save all settings to their serialized state.
void Set< T > (string key, T value)
Set a value for key of type T.
T Get< T > (string key, T fallback=default(T))
Get a value with key of type T, or return the fallback value if no matching key is found.
bool ContainsKey< T > (string key)
Does the repository contain a setting with key and type.
void Remove< T > (string key)
Remove a key value pair from the settings repository.
Static Public Member Functions
static string GetSettingsPath (string packageName, string name="Settings")
Get a path for a settings file relative to the calling assembly package directory.
Properties
SettingsScope scope [get]
string path [get]
string name [get]
The name of this settings file.
Properties inherited from UnityEditor.SettingsManagement.ISettingsRepository
Detailed Description
A settings repository that stores data local to a Unity project.
Constructor & Destructor Documentation
PackageSettingsRepository()
UnityEditor.SettingsManagement.PackageSettingsRepository.PackageSettingsRepository (string package, string name)
Constructor sets the serialized data path.
Parameters
package The package name.
name A name for this settings file. Settings are saved in ProjectSettings/Packages/{package}/{name}.json.
Member Function Documentation
ContainsKey< T >()
bool UnityEditor.SettingsManagement.PackageSettingsRepository.ContainsKey< T > (string key)
Does the repository contain a setting with key and type.
Parameters
key The settings key.
Template Parameters
T The type of value to search for.
Returns
True if a setting matching both key and type is found, false if no entry is found.
Does the repository contain a setting with key and type.
Parameters
key The settings key.
Template Parameters
T The type of value to search for.
Returns
True if a setting matching both key and type is found, false if no entry is found.
Implements UnityEditor.SettingsManagement.ISettingsRepository.
Get< T >()
T UnityEditor.SettingsManagement.PackageSettingsRepository.Get< T > (string key, T fallback = default(T))
Get a value with key of type T, or return the fallback value if no matching key is found.
Parameters
key The settings key.
fallback If no key with a value of type T is found, this value is returned.
Template Parameters
T Type of value to search for.
Get a value with key of type T, or return the fallback value if no matching key is found.
Parameters
key The settings key.
fallback If no key with a value of type T is found, this value is returned.
Template Parameters
T Type of value to search for.
Implements UnityEditor.SettingsManagement.ISettingsRepository.
GetSettingsPath()
static string UnityEditor.SettingsManagement.PackageSettingsRepository.GetSettingsPath (string packageName, string name = "Settings") static
Get a path for a settings file relative to the calling assembly package directory.
Parameters
packageName The name of the package requesting this setting.
name An optional name for the settings file. Default is "Settings."
Returns
A package-scoped path to the settings file within Project Settings.
Referenced by UnityEngine.SettingsManagement.EditorTests.MultipleProjectSettings.MultipleNamedProjectSettings_StoreSettingsSeparately(), UnityEngine.SettingsManagement.EditorTests.MultipleProjectSettings.NewSettingsInstance_CreatesUserAndProjectSettings(), UnityEngine.SettingsManagement.EditorTests.MultipleProjectSettings.NewSettingsInstance_SupportsMultipleProjectRepositories(), UnityEditor.SettingsManagement.PackageSettingsRepository.PackageSettingsRepository(), and UnityEngine.SettingsManagement.EditorTests.MultipleProjectSettings.Teardown().
Remove< T >()
void UnityEditor.SettingsManagement.PackageSettingsRepository.Remove< T > (string key)
Remove a key value pair from the settings repository.
Parameters
key
Template Parameters
T
Remove a key value pair from the settings repository.
Parameters
key
Template Parameters
T
Implements UnityEditor.SettingsManagement.ISettingsRepository.
Save()
void UnityEditor.SettingsManagement.PackageSettingsRepository.Save ()
Save all settings to their serialized state.
Save all settings to their serialized state.
Implements UnityEditor.SettingsManagement.ISettingsRepository.
Referenced by UnityEditor.SettingsManagement.PackageSettingsRepository.PackageSettingsRepository().
Set< T >()
void UnityEditor.SettingsManagement.PackageSettingsRepository.Set< T > (string key, T value)
Set a value for key of type T.
Parameters
key The settings key.
value The value to set. Must be serializable.
Template Parameters
T Type of value.
Set a value for key of type T.
Parameters
key The settings key.
value The value to set. Must be serializable.
Template Parameters
T Type of value.
Implements UnityEditor.SettingsManagement.ISettingsRepository.
Property Documentation
name
string UnityEditor.SettingsManagement.PackageSettingsRepository.name get
The name of this settings file.
Implements UnityEditor.SettingsManagement.ISettingsRepository.
Referenced by UnityEditor.SettingsManagement.PackageSettingsRepository.GetSettingsPath(), and UnityEditor.SettingsManagement.PackageSettingsRepository.PackageSettingsRepository().
path
string UnityEditor.SettingsManagement.PackageSettingsRepository.path get
The full path to the settings file. This corresponds to Unity Project/Project Settings/Packages/com.unity.package/name.
File path to the serialized settings data.
Implements UnityEditor.SettingsManagement.ISettingsRepository.
Referenced by UnityEditor.SettingsManagement.PackageSettingsRepository.Save().
scope
SettingsScope UnityEditor.SettingsManagement.PackageSettingsRepository.scope get
This repository implementation is relevant to the Project scope.
What SettingsScope this repository applies to.
Implements UnityEditor.SettingsManagement.ISettingsRepository.
The documentation for this class was generated from the following file:
C:/Users/Lykos/Desktop/Projects/Capstone/VRGames/Library/PackageCache/com.unity.settings-manager@1.0.3/Editor/PackageSettingsRepository.cs