VRCapstoneGames: Oculus.Interaction.HandPosing.HandGrabInteractor Class Reference
Oculus.Interaction.HandPosing.HandGrabInteractor Class Reference
The HandGrabInteractor allows grabbing objects while having the hands snap to them adopting a previously authored HandPose. There are different snapping techniques available, and when None is selected it will behave as a normal GrabInteractor.
Public Member Functions
HandFingerFlags SnappingFingers ()
void InjectAllHandGrabInteractor (HandGrabAPI handGrabApi, IHand hand, Rigidbody rigidbody, GrabTypeFlags supportedGrabTypes, HandWristOffset gripPoint)
void InjectHandGrabApi (HandGrabAPI handGrabAPI)
void InjectHand (IHand hand)
void InjectRigidbody (Rigidbody rigidbody)
void InjectSupportedGrabTypes (GrabTypeFlags supportedGrabTypes)
void InjectGripPoint (HandWristOffset gripPoint)
void InjectOptionalPinchPoint (Transform pinchPoint)
void InjectOptionalVelocityCalculator (IVelocityCalculator velocityCalculator)
Public Member Functions inherited from Oculus.Interaction.Interactor< HandGrabInteractor, HandGrabInteractable >
void UpdateInteractor ()
virtual void Select ()
virtual void Unselect ()
virtual bool IsFilterPassedBy (TInteractable interactable)
void Hover ()
void Enable ()
void Disable ()
void UpdateInteraction ()
void UpdateHover ()
void UpdateSelection (bool selectionCanBeEmpty)
void InjectOptionalActiveState (IActiveState activeState)
void InjectOptionalInteractableFilters (List< IInteractableFilter > interactableFilters)
Protected Member Functions
virtual void Reset ()
override void Awake ()
override void Start ()
override void DoEveryUpdate ()
During the update event, move the current interactor (containing also the trigger for detecting nearby interactableS) to the tracked position of the grip.
override void DoHoverUpdate ()
Each call while the interactor is hovering, it checks whether there is an interaction being hovered and sets the target snapping address to it. In the HandToObject snapping behaviors this is relevant as the hand can approach the object progressively even before a true grab starts.
override void DoSelectUpdate (HandGrabInteractable interactable)
Each call while the hand is selecting/grabbing an interactable, it moves the item to the new position while also attracting it towards the hand if the snapping mode requires it.
override void InteractableSelected (HandGrabInteractable interactable)
When a new interactable is selected, start the grab at the ideal point. When snapping is involved that can be a point in the interactable offset from the hand which will be stored to progressively reduced it in the next updates, effectively attracting the object towards the hand. When no snapping is involved the point will be the grip point of the hand directly. Note: ideally this code would be in InteractableSelected but it needs to be called before the object is marked as active.
override void InteractableUnselected (HandGrabInteractable interactable)
When releasing an active interactable, calculate the releasing point in similar fashion to InteractableSelected.
override void InteractableSet (HandGrabInteractable interactable)
override void InteractableUnset (HandGrabInteractable interactable)
override HandGrabInteractable ComputeCandidate ()
Compute the best interactable to snap to. In order to do it the method measures the score from the current grip pose to the closes pose in the surfaces of each one of the interactables in the registry. Even though it returns the best interactable, it also saves the entire SnapAddress to it in which the exact pose within the surface is already recorded to avoid recalculations within the same frame.
virtual void ComputeBestSnapAddress (ref SnapAddress snapAddress)
Protected Member Functions inherited from Oculus.Interaction.Interactor< HandGrabInteractor, HandGrabInteractable >
virtual void DoNormalUpdate ()
virtual void DoSelectUpdate (TInteractable interactable=null)
virtual void InteractableSet (TInteractable interactable)
virtual void InteractableUnset (TInteractable interactable)
virtual void InteractableSelected (TInteractable interactable)
virtual void InteractableUnselected (TInteractable interactable)
virtual void OnEnable ()
virtual void OnDisable ()
virtual void OnDestroy ()
TInteractable ComputeCandidate ()
virtual void ComputeSelectActions ()
virtual void HandleSelected ()
virtual void HandleUnselected ()
virtual void Update ()
Properties
IHand Hand [get]
IVelocityCalculator VelocityCalculator [get, set]
HandGrabAPI HandGrabApi [get]
GrabTypeFlags SupportedGrabTypes [get]
IHandGrabInteractable TargetInteractable [get]
virtual bool IsSnapping [get]
float SnapStrength [get]
Pose WristToSnapOffset [get]
ISnapData SnapData [get]
System.Action< ISnapper > WhenSnapStarted = delegate { } [get, set]
System.Action< ISnapper > WhenSnapEnded = delegate { } [get, set]
Rigidbody Rigidbody [get]
Properties inherited from Oculus.Interaction.Interactor< HandGrabInteractor, HandGrabInteractable >
virtual bool ShouldSelect [get, protected set]
virtual bool ShouldUnselect [get, protected set]
ISelector Selector [get, set]
InteractorState State [get]
TInteractable Candidate [get]
TInteractable Interactable [get]
TInteractable SelectedInteractable [get]
bool HasCandidate [get]
bool HasInteractable [get]
bool HasSelectedInteractable [get]
MAction< TInteractable > WhenInteractableSet [get]
MAction< TInteractable > WhenInteractableUnset [get]
MAction< TInteractable > WhenInteractableSelected [get]
MAction< TInteractable > WhenInteractableUnselected [get]
int Identifier [get]
bool IsRootInteractorDriver [get, set]
bool IsSelectingInteractable [get]
bool IsHovering [get]
bool IsSelecting [get]
IInteractor CandidateInteractor [get]
Properties inherited from Oculus.Interaction.HandPosing.ISnapper
Properties inherited from Oculus.Interaction.IRigidbodyRef
Properties inherited from Oculus.Interaction.Grab.IHandGrabInteractor
Additional Inherited Members
Protected Attributes inherited from Oculus.Interaction.Interactor< HandGrabInteractor, HandGrabInteractable >
TInteractable _candidate
TInteractable _interactable
TInteractable _selectedInteractable
bool _started
Events inherited from Oculus.Interaction.Interactor< HandGrabInteractor, HandGrabInteractable >
Action< InteractorStateChangeArgs > WhenStateChanged
Action WhenInteractorUpdated
Detailed Description
The HandGrabInteractor allows grabbing objects while having the hands snap to them adopting a previously authored HandPose. There are different snapping techniques available, and when None is selected it will behave as a normal GrabInteractor.
Member Function Documentation
Awake()
override void Oculus.Interaction.HandPosing.HandGrabInteractor.Awake () protected virtual
Reimplemented from Oculus.Interaction.Interactor< HandGrabInteractor, HandGrabInteractable >.
ComputeBestSnapAddress()
virtual void Oculus.Interaction.HandPosing.HandGrabInteractor.ComputeBestSnapAddress (ref SnapAddress snapAddress) protected virtual
Referenced by Oculus.Interaction.HandPosing.HandGrabInteractor.ComputeCandidate().
ComputeCandidate()
override HandGrabInteractable Oculus.Interaction.HandPosing.HandGrabInteractor.ComputeCandidate () protected
Compute the best interactable to snap to. In order to do it the method measures the score from the current grip pose to the closes pose in the surfaces of each one of the interactables in the registry. Even though it returns the best interactable, it also saves the entire SnapAddress to it in which the exact pose within the surface is already recorded to avoid recalculations within the same frame.
Returns
The best interactable to snap the hand to.
DoEveryUpdate()
override void Oculus.Interaction.HandPosing.HandGrabInteractor.DoEveryUpdate () protected virtual
During the update event, move the current interactor (containing also the trigger for detecting nearby interactableS) to the tracked position of the grip.
That is the tracked wrist plus a pregenerated position and rotation offset.
Reimplemented from Oculus.Interaction.Interactor< HandGrabInteractor, HandGrabInteractable >.
DoHoverUpdate()
override void Oculus.Interaction.HandPosing.HandGrabInteractor.DoHoverUpdate () protected virtual
Each call while the interactor is hovering, it checks whether there is an interaction being hovered and sets the target snapping address to it. In the HandToObject snapping behaviors this is relevant as the hand can approach the object progressively even before a true grab starts.
Reimplemented from Oculus.Interaction.Interactor< HandGrabInteractor, HandGrabInteractable >.
DoSelectUpdate()
override void Oculus.Interaction.HandPosing.HandGrabInteractor.DoSelectUpdate (HandGrabInteractable interactable) protected
Each call while the hand is selecting/grabbing an interactable, it moves the item to the new position while also attracting it towards the hand if the snapping mode requires it.
In some cases the parameter can be null, for example if the selection was interrupted by another hand grabbing the object. In those cases it will come out of the release state once the grabbing gesture properly finishes.
Parameters
interactable The selected item
InjectAllHandGrabInteractor()
void Oculus.Interaction.HandPosing.HandGrabInteractor.InjectAllHandGrabInteractor (HandGrabAPI handGrabApi, IHand hand, Rigidbody rigidbody, GrabTypeFlags supportedGrabTypes, HandWristOffset gripPoint)
InjectGripPoint()
void Oculus.Interaction.HandPosing.HandGrabInteractor.InjectGripPoint (HandWristOffset gripPoint)
Referenced by Oculus.Interaction.HandPosing.HandGrabInteractor.InjectAllHandGrabInteractor().
InjectHand()
void Oculus.Interaction.HandPosing.HandGrabInteractor.InjectHand (IHand hand)
Referenced by Oculus.Interaction.HandPosing.HandGrabInteractor.InjectAllHandGrabInteractor().
InjectHandGrabApi()
void Oculus.Interaction.HandPosing.HandGrabInteractor.InjectHandGrabApi (HandGrabAPI handGrabAPI)
Referenced by Oculus.Interaction.HandPosing.HandGrabInteractor.InjectAllHandGrabInteractor().
InjectOptionalPinchPoint()
void Oculus.Interaction.HandPosing.HandGrabInteractor.InjectOptionalPinchPoint (Transform pinchPoint)
InjectOptionalVelocityCalculator()
void Oculus.Interaction.HandPosing.HandGrabInteractor.InjectOptionalVelocityCalculator (IVelocityCalculator velocityCalculator)
InjectRigidbody()
void Oculus.Interaction.HandPosing.HandGrabInteractor.InjectRigidbody (Rigidbody rigidbody)
Referenced by Oculus.Interaction.HandPosing.HandGrabInteractor.InjectAllHandGrabInteractor().
InjectSupportedGrabTypes()
void Oculus.Interaction.HandPosing.HandGrabInteractor.InjectSupportedGrabTypes (GrabTypeFlags supportedGrabTypes)
Referenced by Oculus.Interaction.HandPosing.HandGrabInteractor.InjectAllHandGrabInteractor().
InteractableSelected()
override void Oculus.Interaction.HandPosing.HandGrabInteractor.InteractableSelected (HandGrabInteractable interactable) protected
When a new interactable is selected, start the grab at the ideal point. When snapping is involved that can be a point in the interactable offset from the hand which will be stored to progressively reduced it in the next updates, effectively attracting the object towards the hand. When no snapping is involved the point will be the grip point of the hand directly. Note: ideally this code would be in InteractableSelected but it needs to be called before the object is marked as active.
Parameters
snap The selected Snap Data
InteractableSet()
override void Oculus.Interaction.HandPosing.HandGrabInteractor.InteractableSet (HandGrabInteractable interactable) protected
InteractableUnselected()
override void Oculus.Interaction.HandPosing.HandGrabInteractor.InteractableUnselected (HandGrabInteractable interactable) protected
When releasing an active interactable, calculate the releasing point in similar fashion to InteractableSelected.
Parameters
interactable The released interactable
InteractableUnset()
override void Oculus.Interaction.HandPosing.HandGrabInteractor.InteractableUnset (HandGrabInteractable interactable) protected
Reset()
virtual void Oculus.Interaction.HandPosing.HandGrabInteractor.Reset () protected virtual
SnappingFingers()
HandFingerFlags Oculus.Interaction.HandPosing.HandGrabInteractor.SnappingFingers ()
Implements Oculus.Interaction.HandPosing.ISnapper.
Start()
override void Oculus.Interaction.HandPosing.HandGrabInteractor.Start () protected virtual
Reimplemented from Oculus.Interaction.Interactor< HandGrabInteractor, HandGrabInteractable >.
Property Documentation
Hand
IHand Oculus.Interaction.HandPosing.HandGrabInteractor.Hand get
Referenced by Oculus.Interaction.HandPosing.Editor.HandGrabPoseWizard.RecordPose().
HandGrabApi
HandGrabAPI Oculus.Interaction.HandPosing.HandGrabInteractor.HandGrabApi get
Implements Oculus.Interaction.Grab.IHandGrabInteractor.
IsSnapping
virtual bool Oculus.Interaction.HandPosing.HandGrabInteractor.IsSnapping get
Implements Oculus.Interaction.HandPosing.ISnapper.
Rigidbody
Rigidbody Oculus.Interaction.HandPosing.HandGrabInteractor.Rigidbody get
Implements Oculus.Interaction.IRigidbodyRef.
Referenced by Oculus.Interaction.HandPosing.HandGrabInteractor.Start().
SnapData
ISnapData Oculus.Interaction.HandPosing.HandGrabInteractor.SnapData get
Implements Oculus.Interaction.HandPosing.ISnapper.
Referenced by Oculus.Interaction.HandPosing.HandGrabInteractor.DoHoverUpdate().
SnapStrength
float Oculus.Interaction.HandPosing.HandGrabInteractor.SnapStrength get
Implements Oculus.Interaction.HandPosing.ISnapper.
Referenced by Oculus.Interaction.HandPosing.HandGrabInteractor.DoHoverUpdate().
SupportedGrabTypes
GrabTypeFlags Oculus.Interaction.HandPosing.HandGrabInteractor.SupportedGrabTypes get
Implements Oculus.Interaction.Grab.IHandGrabInteractor.
TargetInteractable
IHandGrabInteractable Oculus.Interaction.HandPosing.HandGrabInteractor.TargetInteractable get
Implements Oculus.Interaction.Grab.IHandGrabInteractor.
VelocityCalculator
IVelocityCalculator Oculus.Interaction.HandPosing.HandGrabInteractor.VelocityCalculator get set
Referenced by Oculus.Interaction.HandPosing.HandGrabInteractor.Awake(), Oculus.Interaction.HandPosing.HandGrabInteractor.InjectOptionalVelocityCalculator(), Oculus.Interaction.HandPosing.HandGrabInteractor.InteractableUnselected(), and Oculus.Interaction.HandPosing.HandGrabInteractor.Start().
WhenSnapEnded
System.Action<ISnapper> Oculus.Interaction.HandPosing.HandGrabInteractor.WhenSnapEnded = delegate { } get set
Implements Oculus.Interaction.HandPosing.ISnapper.
Referenced by Oculus.Interaction.HandPosing.HandGrabInteractor.InteractableUnset().
WhenSnapStarted
System.Action<ISnapper> Oculus.Interaction.HandPosing.HandGrabInteractor.WhenSnapStarted = delegate { } get set
Implements Oculus.Interaction.HandPosing.ISnapper.
Referenced by Oculus.Interaction.HandPosing.HandGrabInteractor.InteractableSet().
WristToSnapOffset
Pose Oculus.Interaction.HandPosing.HandGrabInteractor.WristToSnapOffset get
Implements Oculus.Interaction.HandPosing.ISnapper.
The documentation for this class was generated from the following file:
C:/Users/Lykos/Desktop/Projects/Capstone/VRGames/Assets/ThirdParty/Oculus/Interaction/Runtime/Scripts/Interaction/Models/HandGrab/HandGrabInteractor.cs