VRCapstoneGames: Oculus.Interaction.Tween Class Reference
Oculus.Interaction.Tween Class Reference
Public Member Functions
Tween (Pose start, float tweenTime=0.5f, float maxOverlapTime=0.25f, AnimationCurve curve=null)
void TweenTo (Pose target)
void UpdateTarget (Pose target)
void StopAndSetPose (Pose source)
void Tick ()
Properties
Pose Pose [get]
bool Stopped [get]
Properties inherited from Oculus.Interaction.ITween
Constructor & Destructor Documentation
Tween()
Oculus.Interaction.Tween.Tween (Pose start, float tweenTime = 0::5f, float maxOverlapTime = 0::25f, AnimationCurve curve = null)
Member Function Documentation
StopAndSetPose()
void Oculus.Interaction.Tween.StopAndSetPose (Pose source)
Implements Oculus.Interaction.ITween.
Referenced by Oculus.Interaction.GrabInteractor.InteractableSelected(), and Oculus.Interaction.Tween.TweenTo().
Tick()
void Oculus.Interaction.Tween.Tick ()
Implements Oculus.Interaction.ITween.
Referenced by Oculus.Interaction.GrabInteractor.DoSelectUpdate().
TweenTo()
void Oculus.Interaction.Tween.TweenTo (Pose target)
Implements Oculus.Interaction.ITween.
Referenced by Oculus.Interaction.HandPosing.HandGrabInteractable.GenerateObjectToHandTween(), and Oculus.Interaction.GrabInteractor.InteractableSelected().
UpdateTarget()
void Oculus.Interaction.Tween.UpdateTarget (Pose target)
Implements Oculus.Interaction.ITween.
Referenced by Oculus.Interaction.GrabInteractor.DoSelectUpdate().
Property Documentation
Pose
Pose Oculus.Interaction.Tween.Pose get
Implements Oculus.Interaction.ITween.
Referenced by Oculus.Interaction.GrabInteractor.DoSelectUpdate(), Oculus.Interaction.GrabInteractor.InteractableUnselected(), and Oculus.Interaction.Tween.Tick().
Stopped
bool Oculus.Interaction.Tween.Stopped get
Implements Oculus.Interaction.ITween.
The documentation for this class was generated from the following file:
C:/Users/Lykos/Desktop/Projects/Capstone/VRGames/Assets/ThirdParty/Oculus/Interaction/Runtime/Scripts/Interaction/Models/Grab/Tween.cs