VRCapstoneGames: UnityEngine.UI.Scrollbar Class Reference
UnityEngine.UI.Scrollbar Class Reference
A standard scrollbar with a variable sized handle that can be dragged between 0 and 1.
Classes
class ScrollEvent
UnityEvent callback for when a scrollbar is scrolled.
Public Types
enum Direction { LeftToRight , RightToLeft , BottomToTop , TopToBottom }
Setting that indicates one of four directions the scrollbar will travel.
Public Member Functions
virtual void SetValueWithoutNotify (float input)
Set the value of the scrollbar without invoking onValueChanged callback.
virtual void Rebuild (CanvasUpdate executing)
Rebuild the element for the given stage.
virtual void LayoutComplete ()
See ICanvasElement.LayoutComplete.
virtual void GraphicUpdateComplete ()
See ICanvasElement.GraphicUpdateComplete.
virtual void OnBeginDrag (PointerEventData eventData)
Handling for when the scrollbar value is begin being dragged.
virtual void OnDrag (PointerEventData eventData)
Handling for when the scrollbar value is dragged.
override void OnPointerDown (PointerEventData eventData)
Event triggered when pointer is pressed down on the scrollbar.
override void OnPointerUp (PointerEventData eventData)
Event triggered when pointer is released after pressing on the scrollbar.
override void OnMove (AxisEventData eventData)
Handling for movement events.
override Selectable FindSelectableOnLeft ()
Prevents selection if we we move on the Horizontal axis. See Selectable.FindSelectableOnLeft.
override Selectable FindSelectableOnRight ()
Prevents selection if we we move on the Horizontal axis. See Selectable.FindSelectableOnRight.
override Selectable FindSelectableOnUp ()
Prevents selection if we we move on the Vertical axis. See Selectable.FindSelectableOnUp.
override Selectable FindSelectableOnDown ()
Prevents selection if we we move on the Vertical axis. See Selectable.FindSelectableOnDown.
virtual void OnInitializePotentialDrag (PointerEventData eventData)
See: IInitializePotentialDragHandler.OnInitializePotentialDrag.
void SetDirection (Direction direction, bool includeRectLayouts)
Set the direction of the scrollbar, optionally setting the layout as well.
Public Member Functions inherited from UnityEngine.EventSystems.UIBehaviour
virtual bool IsActive ()
Returns true if the GameObject and the Component are active.
bool IsDestroyed ()
Returns true if the native representation of the behaviour has been destroyed.
Public Member Functions inherited from UnityEngine.EventSystems.IPointerEnterHandler
void OnPointerEnter (PointerEventData eventData)
Use this callback to detect pointer enter events.
Public Member Functions inherited from UnityEngine.EventSystems.IPointerExitHandler
void OnPointerExit (PointerEventData eventData)
Use this callback to detect pointer exit events.
Public Member Functions inherited from UnityEngine.UI.ICanvasElement
bool IsDestroyed ()
Used if the native representation has been destroyed.
Protected Member Functions
Scrollbar ()
override void OnEnable ()
override void OnDisable ()
virtual void Update ()
Update the rect based on the delayed update visuals. Got around issue of calling sendMessage from onValidate.
override void OnRectTransformDimensionsChange ()
This callback is called when the dimensions of an associated RectTransform change. It is always called before Awake, OnEnable, or Start. The call is also made to all child RectTransforms, regardless of whether their dimensions change (which depends on how they are anchored).
IEnumerator ClickRepeat (PointerEventData eventData)
IEnumerator ClickRepeat (Vector2 screenPosition, Camera camera)
Coroutine function for handling continual press during Scrollbar.OnPointerDown.
Protected Member Functions inherited from UnityEngine.EventSystems.UIBehaviour
virtual void Awake ()
virtual void Start ()
virtual void OnDestroy ()
virtual void OnBeforeTransformParentChanged ()
virtual void OnTransformParentChanged ()
virtual void OnDidApplyAnimationProperties ()
virtual void OnCanvasGroupChanged ()
virtual void OnCanvasHierarchyChanged ()
Called when the state of the parent Canvas is changed.
Properties
RectTransform handleRect [get, set]
The RectTransform to use for the handle.
Direction direction [get, set]
The direction of the scrollbar from minimum to maximum value.
float value [get, set]
The current value of the scrollbar, between 0 and 1.
float size [get, set]
The size of the scrollbar handle where 1 means it fills the entire scrollbar.
int numberOfSteps [get, set]
The number of steps to use for the value. A value of 0 disables use of steps.
ScrollEvent onValueChanged [get, set]
Handling for when the scrollbar value is changed.
Properties inherited from UnityEngine.UI.Selectable
SpriteState spriteState [get, set]
Copy of the array of all the selectable objects currently active in the scene.
AnimationTriggers animationTriggers [get, set]
The AnimationTriggers for this selectable object.
Properties inherited from UnityEngine.UI.ICanvasElement
Transform transform [get]
Get the transform associated with the ICanvasElement.
Additional Inherited Members
Static Protected Attributes inherited from UnityEngine.UI.Selectable
static Selectable[] s_Selectables = new Selectable[10]
static int s_SelectableCount = 0
Detailed Description
A standard scrollbar with a variable sized handle that can be dragged between 0 and 1.
The slider component is a Selectable that controls a handle which follow the current value and is sized according to the size property. The anchors of the handle RectTransforms are driven by the Scrollbar. The handle can be a direct child of the GameObject with the Scrollbar, or intermediary RectTransforms can be placed in between for additional control. When a change to the scrollbar value occurs, a callback is sent to any registered listeners of onValueChanged.
Member Enumeration Documentation
Direction
enum UnityEngine.UI.Scrollbar.Direction
Setting that indicates one of four directions the scrollbar will travel.
Enumerator
LeftToRight
Starting position is the Left.
RightToLeft
Starting position is the Right.
BottomToTop
Starting position is the Bottom.
TopToBottom
Starting position is the Top.
Constructor & Destructor Documentation
Scrollbar()
UnityEngine.UI.Scrollbar.Scrollbar () protected
Member Function Documentation
ClickRepeat() [1/2]
IEnumerator UnityEngine.UI.Scrollbar.ClickRepeat (PointerEventData eventData) protected
Referenced by UnityEngine.UI.Scrollbar.ClickRepeat(), and UnityEngine.UI.Scrollbar.OnPointerDown().
ClickRepeat() [2/2]
IEnumerator UnityEngine.UI.Scrollbar.ClickRepeat (Vector2 screenPosition, Camera camera) protected
Coroutine function for handling continual press during Scrollbar.OnPointerDown.
FindSelectableOnDown()
override Selectable UnityEngine.UI.Scrollbar.FindSelectableOnDown ()
Prevents selection if we we move on the Vertical axis. See Selectable.FindSelectableOnDown.
Referenced by UnityEditor.UI.ScrollbarEditor.OnInspectorGUI(), and UnityEngine.UI.Scrollbar.OnMove().
FindSelectableOnLeft()
override Selectable UnityEngine.UI.Scrollbar.FindSelectableOnLeft ()
Prevents selection if we we move on the Horizontal axis. See Selectable.FindSelectableOnLeft.
Referenced by UnityEditor.UI.ScrollbarEditor.OnInspectorGUI(), and UnityEngine.UI.Scrollbar.OnMove().
FindSelectableOnRight()
override Selectable UnityEngine.UI.Scrollbar.FindSelectableOnRight ()
Prevents selection if we we move on the Horizontal axis. See Selectable.FindSelectableOnRight.
Referenced by UnityEditor.UI.ScrollbarEditor.OnInspectorGUI(), and UnityEngine.UI.Scrollbar.OnMove().
FindSelectableOnUp()
override Selectable UnityEngine.UI.Scrollbar.FindSelectableOnUp ()
Prevents selection if we we move on the Vertical axis. See Selectable.FindSelectableOnUp.
Referenced by UnityEditor.UI.ScrollbarEditor.OnInspectorGUI(), and UnityEngine.UI.Scrollbar.OnMove().
GraphicUpdateComplete()
virtual void UnityEngine.UI.Scrollbar.GraphicUpdateComplete () virtual
See ICanvasElement.GraphicUpdateComplete.
Implements UnityEngine.UI.ICanvasElement.
LayoutComplete()
virtual void UnityEngine.UI.Scrollbar.LayoutComplete () virtual
See ICanvasElement.LayoutComplete.
Implements UnityEngine.UI.ICanvasElement.
OnBeginDrag()
virtual void UnityEngine.UI.Scrollbar.OnBeginDrag (PointerEventData eventData) virtual
Handling for when the scrollbar value is begin being dragged.
OnDisable()
override void UnityEngine.UI.Scrollbar.OnDisable () protected virtual
Reimplemented from UnityEngine.EventSystems.UIBehaviour.
OnDrag()
virtual void UnityEngine.UI.Scrollbar.OnDrag (PointerEventData eventData) virtual
Handling for when the scrollbar value is dragged.
OnEnable()
override void UnityEngine.UI.Scrollbar.OnEnable () protected virtual
Reimplemented from UnityEngine.EventSystems.UIBehaviour.
OnInitializePotentialDrag()
virtual void UnityEngine.UI.Scrollbar.OnInitializePotentialDrag (PointerEventData eventData) virtual
See: IInitializePotentialDragHandler.OnInitializePotentialDrag.
OnMove()
override void UnityEngine.UI.Scrollbar.OnMove (AxisEventData eventData)
Handling for movement events.
OnPointerDown()
override void UnityEngine.UI.Scrollbar.OnPointerDown (PointerEventData eventData)
Event triggered when pointer is pressed down on the scrollbar.
Implements UnityEngine.EventSystems.IPointerDownHandler.
OnPointerUp()
override void UnityEngine.UI.Scrollbar.OnPointerUp (PointerEventData eventData)
Event triggered when pointer is released after pressing on the scrollbar.
Implements UnityEngine.EventSystems.IPointerUpHandler.
OnRectTransformDimensionsChange()
override void UnityEngine.UI.Scrollbar.OnRectTransformDimensionsChange () protected virtual
This callback is called when the dimensions of an associated RectTransform change. It is always called before Awake, OnEnable, or Start. The call is also made to all child RectTransforms, regardless of whether their dimensions change (which depends on how they are anchored).
Reimplemented from UnityEngine.EventSystems.UIBehaviour.
Rebuild()
virtual void UnityEngine.UI.Scrollbar.Rebuild (CanvasUpdate executing) virtual
Rebuild the element for the given stage.
Parameters
executing The current CanvasUpdate stage being rebuild.
Implements UnityEngine.UI.ICanvasElement.
SetDirection()
void UnityEngine.UI.Scrollbar.SetDirection (Direction direction, bool includeRectLayouts)
Set the direction of the scrollbar, optionally setting the layout as well.
Parameters
direction The direction of the scrollbar.
includeRectLayouts Should the layout be flipped together with the direction?
Referenced by UnityEditor.UI.ScrollbarEditor.OnInspectorGUI().
SetValueWithoutNotify()
virtual void UnityEngine.UI.Scrollbar.SetValueWithoutNotify (float input) virtual
Set the value of the scrollbar without invoking onValueChanged callback.
Parameters
input The new value for the scrollbar.
Referenced by ScrollBarTests.ScrollBarSetValueWithoutNotifyWillNotNotify().
Update()
virtual void UnityEngine.UI.Scrollbar.Update () protected virtual
Update the rect based on the delayed update visuals. Got around issue of calling sendMessage from onValidate.
Property Documentation
direction
Direction UnityEngine.UI.Scrollbar.direction get set
The direction of the scrollbar from minimum to maximum value.
Referenced by UnityEditor.UI.ScrollbarEditor.OnInspectorGUI(), and UnityEngine.UI.Scrollbar.SetDirection().
handleRect
RectTransform UnityEngine.UI.Scrollbar.handleRect get set
The RectTransform to use for the handle.
numberOfSteps
int UnityEngine.UI.Scrollbar.numberOfSteps get set
The number of steps to use for the value. A value of 0 disables use of steps.
onValueChanged
ScrollEvent UnityEngine.UI.Scrollbar.onValueChanged get set
Handling for when the scrollbar value is changed.
Allow for delegate-based subscriptions for faster events than 'eventReceiver', and allowing for multiple receivers.
Referenced by TMPro.TMP_InputField.OnDisable(), TMPro.TMP_InputField.OnEnable(), UnityEngine.UI.Scrollbar.Rebuild(), ScrollBarTests.ScrollBarSetValueWithoutNotifyWillNotNotify(), and ScrollRectTests.SettingScrollbarShouldRemoveThenAddListeners().
size
float UnityEngine.UI.Scrollbar.size get set
The size of the scrollbar handle where 1 means it fills the entire scrollbar.
Referenced by UnityEngine.UI.Scrollbar.ClickRepeat().
value
float UnityEngine.UI.Scrollbar.value get set
The current value of the scrollbar, between 0 and 1.
Referenced by UnityEngine.UI.Scrollbar.ClickRepeat(), UnityEngine.UI.Scrollbar.OnMove(), UnityEngine.UI.Scrollbar.Rebuild(), and ScrollBarTests.ScrollBarSetValueWithoutNotifyWillNotNotify().
The documentation for this class was generated from the following file:
C:/Users/Lykos/Desktop/Projects/Capstone/VRGames/Library/PackageCache/com.unity.ugui@1.0.0/Runtime/UI/Core/Scrollbar.cs