VRGames: UnityEngine.InputSystem.InputDevice Class Reference
UnityEngine.InputSystem.InputDevice Class Reference
Represents an input device which is always the root of a hierarchy of InputControl instances.
Public Member Functions
InputDevice ()
This constructor is public for the sake of Activator.CreateInstance only. To construct devices, use methods such as InputSystem.AddDevice<TDevice>(string). Manually using new on InputDevice will not result in a usable device.
override unsafe object ReadValueFromBufferAsObject (void *buffer, int bufferSize)
override unsafe object ReadValueFromStateAsObject (void *statePtr)
override unsafe void ReadValueFromStateIntoBuffer (void *statePtr, void *bufferPtr, int bufferSize)
override unsafe bool CompareValue (void *firstStatePtr, void *secondStatePtr)
virtual void MakeCurrent ()
Make this the current device of its type.
unsafe long ExecuteCommand< TCommand > (ref TCommand command)
Perform a device-specific command.
Public Member Functions inherited from UnityEngine.InputSystem.InputControl< TValue >
override string ToString ()
Return a string representation of the control useful for debugging.
unsafe float EvaluateMagnitude ()
Compute an absolute, normalized magnitude value that indicates the extent to which the control is actuated.
virtual unsafe float EvaluateMagnitude (void *statePtr)
Compute an absolute, normalized magnitude value that indicates the extent to which the control is actuated in the given state.
unsafe object ReadValueFromBufferAsObject (void *buffer, int bufferSize)
unsafe object ReadValueFromStateAsObject (void *statePtr)
Read the control's final, processed value from the given state and return the value as an object.
unsafe void ReadValueFromStateIntoBuffer (void *statePtr, void *bufferPtr, int bufferSize)
Read the control's final, processed value from the given state and store it in the given buffer.
virtual unsafe void WriteValueFromBufferIntoState (void *bufferPtr, int bufferSize, void *statePtr)
Read a value from the given memory and store it as state.
virtual unsafe void WriteValueFromObjectIntoState (object value, void *statePtr)
Read a value object and store it as state in the given memory.
unsafe bool CompareValue (void *firstStatePtr, void *secondStatePtr)
Compare the value of the control as read from firstStatePtr to that read from secondStatePtr and return true if they are equal.
InputControl TryGetChildControl (string path)
Try to find a child control matching the given path.
TControl TryGetChildControl< TControl > (string path)
InputControl GetChildControl (string path)
TControl GetChildControl< TControl > (string path)
TValue ReadValue ()
Get the control's current value as read from InputControl.currentStatePtr
TValue ReadValueFromPreviousFrame ()
Get the control's value from the previous frame (InputControl.previousFrameStatePtr).
TValue ReadDefaultValue ()
Get the control's default value.
unsafe TValue ReadValueFromState (void *statePtr)
TValue ReadUnprocessedValue ()
unsafe TValue ReadUnprocessedValueFromState (void *statePtr)
override unsafe object ReadValueFromStateAsObject (void *statePtr)
override unsafe void ReadValueFromStateIntoBuffer (void *statePtr, void *bufferPtr, int bufferSize)
override unsafe void WriteValueFromBufferIntoState (void *bufferPtr, int bufferSize, void *statePtr)
override unsafe void WriteValueFromObjectIntoState (object value, void *statePtr)
virtual unsafe void WriteValueIntoState (TValue value, void *statePtr)
override unsafe object ReadValueFromBufferAsObject (void *buffer, int bufferSize)
override unsafe bool CompareValue (void *firstStatePtr, void *secondStatePtr)
TValue ProcessValue (TValue value)
Static Public Attributes
const int InvalidDeviceId = 0
Value of an invalid deviceId.
Protected Member Functions
virtual void OnAdded ()
Called by the system when the device is added to InputSystem.devices.
virtual void OnRemoved ()
Called by the system when the device is removed from InputSystem.devices.
virtual void OnConfigurationChanged ()
Called by the system when the device configuration is changed. This happens when the backend sends a DeviceConfigurationEvent for the device.
virtual unsafe long ExecuteCommand (InputDeviceCommand *commandPtr)
Protected Member Functions inherited from UnityEngine.InputSystem.InputControl< TValue >
InputControl ()
virtual void FinishSetup ()
Perform final initialization tasks after the control hierarchy has been put into place.
void RefreshConfigurationIfNeeded ()
Call RefreshConfiguration if the configuration has in the interim been invalidated by a DeviceConfigurationEvent.
virtual void RefreshConfiguration ()
Properties
InputDeviceDescription description [get]
Metadata describing the device (product name etc.).
bool enabled [get]
Whether the device is currently enabled (that is, sends and receives events).
bool canRunInBackground [get]
If true, the device is capable of delivering input while the application is running in the background, i.e. while Application.isFocused is false.
bool added [get]
Whether the device has been added to the system.
bool remote [get]
Whether the device is mirrored from a remote input system and not actually present as a "real" device in the local system.
bool native [get]
Whether the device comes from the runtime
bool updateBeforeRender [get]
Whether the device requires an extra update before rendering.
int deviceId [get]
Unique numeric ID for the device.
double lastUpdateTime [get]
Timestamp of last state event used to update the device.
bool wasUpdatedThisFrame [get]
ReadOnlyArray< InputControl > allControls [get]
A flattened list of controls that make up the device.
override Type valueType [get]
override int valueSizeInBytes [get]
static ReadOnlyArray< InputDevice > all [get]
Properties inherited from UnityEngine.InputSystem.InputControl< TValue >
string name [get]
The name of the control, i.e. the final name part in its path.
string displayName [get, protected set]
The text to display as the name of the control.
string shortDisplayName [get, protected set]
An alternate, abbreviated displayName (for example "LMB" instead of "Left Button").
string path [get]
Full path all the way from the root.
string layout [get]
Layout the control is based on.
string variants [get]
Semicolon-separated list of variants of the control layout or "default".
InputDevice device [get]
The device that this control is a part of.
InputControl parent [get]
The immediate parent of the control or null if the control has no parent (which, once fully constructed) will only be the case for InputDevices).
ReadOnlyArray< InputControl > children [get]
List of immediate children.
ReadOnlyArray< InternedString > usages [get]
List of usage tags associated with the control.
ReadOnlyArray< InternedString > aliases [get]
InputStateBlock stateBlock [get]
bool noisy [get, set]
Whether the control is considered noisy.
bool synthetic [get, set]
Whether the control is considered synthetic.
InputControl this[string path] [get]
Fetch a control from the control's hierarchy by name.
Type valueType [get]
Returns the underlying value type of this control.
int valueSizeInBytes [get]
Size in bytes of values that the control returns.
override Type valueType [get]
override int valueSizeInBytes [get]
Detailed Description
Represents an input device which is always the root of a hierarchy of InputControl instances.
Input devices act as the container for control hierarchies. Every hierarchy has to have a device at the root. Devices cannot occur as children of other controls.
Devices are usually created automatically in response to hardware being discovered by the Unity runtime. However, it is possible to manually add devices using methods such as InputSystem.AddDevice<TDevice>(string).
// Add a "synthetic" gamepad that isn't actually backed by hardware.
var gamepad = InputSystem.AddDevice<Gamepad>();
There are subclasses representing the most common types of devices, like Mouse, Keyboard, Gamepad, and Touchscreen.
To create your own types of devices, you can derive from InputDevice and register your device as a new "layout".
// InputControlLayoutAttribute attribute is only necessary if you want
// to override default behavior that occurs when registering your device
// as a layout.
// The most common use of InputControlLayoutAttribute is to direct the system
// to a custom "state struct" through the <tt>stateType</tt> property. See below for details.
[InputControlLayout(displayName = "My Device", stateType = typeof(MyDeviceState))]
#if UNITY_EDITOR
[InitializeOnLoad]
#endif
public class MyDevice : InputDevice
{
    public ButtonControl button { get; private set; }
    public AxisControl axis { get; private set; }
    // Register the device.
    static MyDevice()
    {
        // In case you want instance of your device to automatically be created
        // when specific hardware is detected by the Unity runtime, you have to
        // add one or more "device matchers" (InputDeviceMatcher) for the layout.
        // These matchers are compared to an InputDeviceDescription received from
        // the Unity runtime when a device is connected. You can add them either
        // using InputSystem.RegisterLayoutMatcher() or by directly specifying a
        // matcher when registering the layout.
        InputSystem.RegisterLayout<MyDevice>(
            // For the sake of demonstration, let's assume your device is a HID
            // and you want to match by PID and VID.
            matches: new InputDeviceMatcher()
                .WithInterface("HID")
                .WithCapability("PID", 1234)
                .WithCapability("VID", 5678));
    }
    // This is only to trigger the static class constructor to automatically run
    // in the player.
    [RuntimeInitializeOnLoadMethod(RuntimeInitializeLoadType.BeforeSceneLoad)]
    private static void InitializeInPlayer() {}
    protected override void FinishSetup()
    {
        base.FinishSetup();
        button = GetChildControl<ButtonControl>("button");
        axis = GetChildControl<AxisControl>("axis");
    }
}
// A "state struct" describes the memory format used by a device. Each device can
// receive and store memory in its custom format. InputControls are then connected
// the individual pieces of memory and read out values from them.
[StructLayout(LayoutKind.Explicit, Size = 32)]
public struct MyDeviceState : IInputStateTypeInfo
{
    // In the case of a HID (which we assume for the sake of this demonstration),
    // the format will be "HID". In practice, the format will depend on how your
    // particular device is connected and fed into the input system.
    // The format is a simple FourCC code that "tags" state memory blocks for the
    // device to give a base level of safety checks on memory operations.
    public FourCC format => return new FourCC('H', 'I', 'D');
    // InputControlAttributes on fields tell the input system to create controls
    // for the public fields found in the struct.
    // Assume a 16bit field of buttons. Create one button that is tied to
    // bit #3 (zero-based). Note that buttons do not need to be stored as bits.
    // They can also be stored as floats or shorts, for example.
    [InputControl(name = "button", layout = "Button", bit = 3)]
    public ushort buttons;
    // Create a floating-point axis. The name, if not supplied, is taken from
    // the field.
    [InputControl(layout = "Axis")]
    public short axis;
}
Devices can have usages like any other control (InputControl.usages). Unlike other controls, however, usages of InputDevices are allowed to be changed on the fly without requiring a change to the device layout (see InputSystem.SetDeviceUsage(InputDevice,string)).
For a more complete example of how to implement custom input devices, check out the "Custom Device" sample which you can install from the Unity package manager.
And, as always, you can also find more information in the manual.
See also
InputControl, Mouse, Keyboard, Gamepad, Touchscreen
Constructor & Destructor Documentation
InputDevice()
UnityEngine.InputSystem.InputDevice.InputDevice ()
This constructor is public for the sake of Activator.CreateInstance only. To construct devices, use methods such as InputSystem.AddDevice<TDevice>(string). Manually using new on InputDevice will not result in a usable device.
Member Function Documentation
CompareValue()
override unsafe bool UnityEngine.InputSystem.InputDevice.CompareValue (void * firstStatePtr, void * secondStatePtr)
ExecuteCommand()
virtual unsafe long UnityEngine.InputSystem.InputDevice.ExecuteCommand (InputDeviceCommand * commandPtr) protected virtual
Referenced by UnityEngine.InputSystem.InputDevice.ExecuteCommand< TCommand >(), UnityEngine.InputSystem.Controls.KeyControl.RefreshConfiguration(), UnityEngine.InputSystem.Keyboard.RefreshConfiguration(), UnityEngine.InputSystem.Keyboard.SetIMECursorPosition(), UnityEngine.InputSystem.Keyboard.SetIMEEnabled(), and UnityEngine.InputSystem.Mouse.WarpCursorPosition().
ExecuteCommand< TCommand >()
unsafe long UnityEngine.InputSystem.InputDevice.ExecuteCommand< TCommand > (ref TCommand command)
Perform a device-specific command.
REVIEW: return just bool instead of long and require everything else to go in the command?
Parameters
command Data for the command to be performed.
Returns
A transfer-specific return code. Negative values are considered failure codes.
Commands allow devices to set up custom protocols without having to extend the device API. This is most useful for devices implemented in the native Unity runtime which, through the command interface, may provide custom, device-specific functions.
This is a low-level API. It works in a similar way to DeviceIoControl on Windows and ioctl on UNIX-like systems.
Type Constraints
TCommand : struct
TCommand : IInputDeviceCommandInfo
MakeCurrent()
virtual void UnityEngine.InputSystem.InputDevice.MakeCurrent () virtual
Make this the current device of its type.
This method is called automatically by the input system when a device is added or when input is received on it. Many types of devices have .current getters that allow querying the last used device of a specific type directly (for example, see Gamepad.current).
There is one special case, however, related to noise. A device that has noisy controls (i.e. controls for which InputControl.noisy is true) may receive input events that contain no meaningful user interaction but are simply just noise from the device. A good example of this is the PS4 gamepad which has a built-in gyro and may thus constantly feed events into the input system even if not being actually in use. If, for example, an Xbox gamepad and PS4 gamepad are both connected to a PC and the user is playing with the Xbox gamepad, the PS4 gamepad would still constantly make itself Gamepad.current by simply flooding the system with events. Hence why by default, noise on .current getters will be filtered out and a device will only see MakeCurrent getting called if there input was detected on non-noisy controls.
See also
Pointer.current, Gamepad.current, Mouse.current, Pen.current
Reimplemented in UnityEngine.InputSystem.Gamepad, UnityEngine.InputSystem.Joystick, UnityEngine.InputSystem.Keyboard, UnityEngine.InputSystem.Mouse, UnityEngine.InputSystem.Pen, UnityEngine.InputSystem.Pointer, UnityEngine.InputSystem.Accelerometer, UnityEngine.InputSystem.Gyroscope, UnityEngine.InputSystem.GravitySensor, UnityEngine.InputSystem.AttitudeSensor, UnityEngine.InputSystem.LinearAccelerationSensor, UnityEngine.InputSystem.MagneticFieldSensor, UnityEngine.InputSystem.LightSensor, UnityEngine.InputSystem.PressureSensor, UnityEngine.InputSystem.ProximitySensor, UnityEngine.InputSystem.HumiditySensor, UnityEngine.InputSystem.AmbientTemperatureSensor, UnityEngine.InputSystem.StepCounter, UnityEngine.InputSystem.Touchscreen, UnityEngine.InputSystem.DualShock.DualShockGamepad, and CustomDevice.
OnAdded()
virtual void UnityEngine.InputSystem.InputDevice.OnAdded () protected virtual
Called by the system when the device is added to InputSystem.devices.
This is called after the device has already been added.
See also
InputSystem.devices, InputDeviceChange.Added, OnRemoved
Reimplemented in UnityEngine.InputSystem.Gamepad, UnityEngine.InputSystem.Joystick, and UnityEngine.InputSystem.Mouse.
OnConfigurationChanged()
virtual void UnityEngine.InputSystem.InputDevice.OnConfigurationChanged () protected virtual
Called by the system when the device configuration is changed. This happens when the backend sends a DeviceConfigurationEvent for the device.
This method can be used to flush out cached information. An example of where this happens is Controls.KeyControl caching information about the display name of a control. As this depends on the current keyboard layout, the information has to be fetched dynamically (this happens using QueryKeyNameCommand). Whenever the keyboard layout changes, the system sends a DeviceConfigurationEvent for the Keyboard at which point the device flushes all cached key names.
See also
InputManager.OnUpdate, InputDeviceChange.ConfigurationChanged, OnConfigurationChanged
///
OnRemoved()
virtual void UnityEngine.InputSystem.InputDevice.OnRemoved () protected virtual
Called by the system when the device is removed from InputSystem.devices.
This is called after the device has already been removed.
See also
InputSystem.devices, InputDeviceChange.Removed, OnRemoved
Reimplemented in UnityEngine.InputSystem.Gamepad, UnityEngine.InputSystem.Joystick, UnityEngine.InputSystem.Keyboard, UnityEngine.InputSystem.Mouse, UnityEngine.InputSystem.Pen, UnityEngine.InputSystem.Pointer, UnityEngine.InputSystem.Accelerometer, UnityEngine.InputSystem.Gyroscope, UnityEngine.InputSystem.GravitySensor, UnityEngine.InputSystem.AttitudeSensor, UnityEngine.InputSystem.LinearAccelerationSensor, UnityEngine.InputSystem.MagneticFieldSensor, UnityEngine.InputSystem.LightSensor, UnityEngine.InputSystem.PressureSensor, UnityEngine.InputSystem.ProximitySensor, UnityEngine.InputSystem.HumiditySensor, UnityEngine.InputSystem.AmbientTemperatureSensor, UnityEngine.InputSystem.StepCounter, UnityEngine.InputSystem.Touchscreen, UnityEngine.InputSystem.DualShock.DualShockGamepad, and CustomDevice.
ReadValueFromBufferAsObject()
override unsafe object UnityEngine.InputSystem.InputDevice.ReadValueFromBufferAsObject (void * buffer, int bufferSize)
ReadValueFromStateAsObject()
override unsafe object UnityEngine.InputSystem.InputDevice.ReadValueFromStateAsObject (void * statePtr)
ReadValueFromStateIntoBuffer()
override unsafe void UnityEngine.InputSystem.InputDevice.ReadValueFromStateIntoBuffer (void * statePtr, void * bufferPtr, int bufferSize)
Member Data Documentation
InvalidDeviceId
const int UnityEngine.InputSystem.InputDevice.InvalidDeviceId = 0 static
Value of an invalid deviceId.
The input system will not assigned this ID to any device.
Referenced by UnityEngine.InputSystem.InputDevice.InputDevice().
Property Documentation
added
bool UnityEngine.InputSystem.InputDevice.added get
Whether the device has been added to the system.
If true, the device is currently among the devices in InputSystem.devices.
Devices may be removed at any time. Either when their hardware is unplugged or when they are manually removed through InputSystem.RemoveDevice or by being excluded through InputSettings.supportedDevices. When a device is removed, its instance, however, will not disappear. This property can be used to check whether the device is part of the current set of active devices.
See also
InputSystem.devices
Referenced by UnityEngine.InputSystem.EnhancedTouch.TouchSimulation.OnDisable(), CustomDeviceUsages.OnDisable(), UnityEngine.InputSystem.EnhancedTouch.TouchSimulation.OnEnable(), UnityEngine.InputSystem.EnhancedTouch.TouchSimulation.RemovePointer(), and UnityEngine.InputSystem.InputTestFixture.Set< TValue >().
all
ReadOnlyArray<InputDevice> UnityEngine.InputSystem.InputDevice.all static get
allControls
ReadOnlyArray<InputControl> UnityEngine.InputSystem.InputDevice.allControls get
A flattened list of controls that make up the device.
Does not allocate.
canRunInBackground
bool UnityEngine.InputSystem.InputDevice.canRunInBackground get
If true, the device is capable of delivering input while the application is running in the background, i.e. while Application.isFocused is false.
TODO: rename this to canReceiveInputInBackground (once we can break API)
Whether the device can generate input while in the background.
The value of this property is determined by three separator factors.
For one, native devices have an inherent value for this property that can be retrieved through QueryCanRunInBackground. This determines whether at the input collection level, the device is capable of producing input independent of application. This is rare and only a select set of hardware, platform, and SDK/API combinations support this. The prominent class of input devices that in general do support this behavior are VR devices.
Furthermore, the property may be force-set through a device's InputControl.layout by means of InputControlLayout.canRunInBackground.
Lastly, in the editor, the value of the property may be overridden depending on InputSettings.editorInputBehaviorInPlayMode in case certain devices are automatically kept running in play mode even when no Game View has focus.
Be aware that as far as players are concerned, only certain platforms support running Unity while not having focus. On mobile platforms, for example, this is generally not supported. In this case, the value of this property has no impact on input while the application does not have focus. See InputSettings.backgroundBehavior for more details.
See also
InputSettings.backgroundBehavior, InputControlLayout.canRunInBackground
description
InputDeviceDescription UnityEngine.InputSystem.InputDevice.description get
Metadata describing the device (product name etc.).
The description of a device is unchanging over its lifetime and does not comprise data about a device's configuration (which is considered mutable).
In most cases, the description for a device is supplied by the Unity runtime. This it the case for all native input devices. However, it is also possible to inject new devices in the form of device descriptions into the system using InputSystem.AddDevice(InputDeviceDescription).
The description of a device is what is matched by an InputDeviceMatcher to find the InputControl.layout to use for a device.
deviceId
int UnityEngine.InputSystem.InputDevice.deviceId get
Unique numeric ID for the device.
This is only assigned once a device has been added to the system. No two devices will receive the same ID and no device will receive an ID that another device used before even if the device was removed. The only exception to this is if a device gets re-created as part of a layout change. For example, if a new layout is registered that replaces the Mouse layout, all Mouse devices will get recreated but will keep their existing device IDs.
IDs are assigned by the input runtime.
See also
IInputRuntime.AllocateDeviceId
Referenced by UnityEngine.InputSystem.InputDevice.ExecuteCommand(), UnityEngine.InputSystem.LowLevel.InputEventTrace.InputEventTrace(), and UnityEngine.InputSystem.LowLevel.InputEventTrace.ReplayController.WithDeviceMappedFromTo().
enabled
bool UnityEngine.InputSystem.InputDevice.enabled get
Whether the device is currently enabled (that is, sends and receives events).
REVIEW: When we can break the API, probably makes sense to replace this single bool with one for sending and one for receiving events
A device that is disabled will not receive events. I.e. events that are being sent to the device will be ignored.
When disabling a native device, a disable command will also be sent to the runtime. It depends on the specific runtime whether the device command is supported but if it is, the device will be disabled in the runtime and no longer send events. This is especially important for devices such as sensors that incur both computation and battery consumption overhead while enabled.
Specific types of devices can choose to start out in disabled state by default. This is generally the case for sensors to ensure that their overhead is only incurred when actually being used by the application.
See also
InputSystem.EnableDevice, InputSystem.DisableDevice
Referenced by UnityEngine.InputSystem.Keyboard.SetIMEEnabled().
lastUpdateTime
double UnityEngine.InputSystem.InputDevice.lastUpdateTime get
Timestamp of last state event used to update the device.
Events other than LowLevel.StateEvent and LowLevel.DeltaStateEvent will not cause lastUpdateTime to be changed. The "timeline" is reset to 0 when entering play mode. If there are any events incoming or device updates which occur prior to entering play mode, these will appear negative.
native
bool UnityEngine.InputSystem.InputDevice.native get
Whether the device comes from the runtime
Whether the device has been discovered by the Unity runtime.
Devices can be discovered when reported by the runtime or they can be added manually through the various AddDevice APIs. Devices reported by the runtime will return true for this property whereas devices added manually will return false.
Devices reported by the runtime will usually come from the Unity engine itself.
See also
IInputRuntime, IInputRuntime.onDeviceDiscovered
Referenced by UnityEngine.InputSystem.Mouse.OnAdded().
remote
bool UnityEngine.InputSystem.InputDevice.remote get
Whether the device is mirrored from a remote input system and not actually present as a "real" device in the local system.
Whether the device mirrors a device from a remotely connected input system.
See also
InputSystem.remoting, InputRemoting
updateBeforeRender
bool UnityEngine.InputSystem.InputDevice.updateBeforeRender get
Whether the device requires an extra update before rendering.
The value of this property is determined by InputControlLayout.updateBeforeRender in the device's control layout.
The extra update is necessary for tracking devices that are used in rendering code. For example, the eye transforms of an HMD should be refreshed right before rendering as refreshing only in the beginning of the frame will lead to a noticeable lag.
See also
InputUpdateType.BeforeRender
valueSizeInBytes
override int UnityEngine.InputSystem.InputDevice.valueSizeInBytes get
Referenced by UnityEngine.InputSystem.InputDevice.ReadValueFromStateIntoBuffer().
valueType
override Type UnityEngine.InputSystem.InputDevice.valueType get
REVIEW: This violates the constraint of controls being required to not have reference types as value types.
wasUpdatedThisFrame
bool UnityEngine.InputSystem.InputDevice.wasUpdatedThisFrame get
The documentation for this class was generated from the following file:
C:/Users/Lykos/Desktop/Projects/Capstone/VRGames/Library/PackageCache/com.unity.inputsystem@1.3.0/InputSystem/Devices/InputDevice.cs