VRGames: ToggleTest.ToggleGroupTests Class Reference
ToggleTest.ToggleGroupTests Class Reference
Public Member Functions
void Setup ()
Implement this method to call actions automatically before the build process.
void TestSetup ()
void TearDown ()
void OneTimeTearDown ()
void TogglingOneShouldDisableOthersInGroup ()
void DisallowSwitchOffShouldKeepToggleOnWhenClicking ()
void DisallowSwitchOffShouldDisableToggleWhenClicking ()
void ReEnablingGameObjectWithToggleGroupRetainsPreviouslySelectedToggle (int toggleIndex)
void ChangingToggleGroupUnregistersFromOriginalGroup ()
void DisabledToggleGroupDoesntControlChildren ()
Protected Attributes
GameObject m_PrefabRoot
List< Toggle > m_toggle = new List<Toggle>()
Static Protected Attributes
static int nbToggleInGroup = 2
Member Function Documentation
ChangingToggleGroupUnregistersFromOriginalGroup()
void ToggleTest.ToggleGroupTests.ChangingToggleGroupUnregistersFromOriginalGroup ()
DisabledToggleGroupDoesntControlChildren()
void ToggleTest.ToggleGroupTests.DisabledToggleGroupDoesntControlChildren ()
DisallowSwitchOffShouldDisableToggleWhenClicking()
void ToggleTest.ToggleGroupTests.DisallowSwitchOffShouldDisableToggleWhenClicking ()
DisallowSwitchOffShouldKeepToggleOnWhenClicking()
void ToggleTest.ToggleGroupTests.DisallowSwitchOffShouldKeepToggleOnWhenClicking ()
OneTimeTearDown()
void ToggleTest.ToggleGroupTests.OneTimeTearDown ()
ReEnablingGameObjectWithToggleGroupRetainsPreviouslySelectedToggle()
void ToggleTest.ToggleGroupTests.ReEnablingGameObjectWithToggleGroupRetainsPreviouslySelectedToggle (int toggleIndex)
Setup()
void ToggleTest.ToggleGroupTests.Setup ()
Implement this method to call actions automatically before the build process.
[TestFixture]
public class CreateSpriteTest : IPrebuildSetup
{
    Texture2D m_Texture;
    Sprite m_Sprite;
    public void Setup()
    {
        #if UNITY_EDITOR
        var spritePath = "Assets/Resources/Circle.png";
        var ti = UnityEditor.AssetImporter.GetAtPath(spritePath) as UnityEditor.TextureImporter;
        ti.textureCompression = UnityEditor.TextureImporterCompression.Uncompressed;
        ti.SaveAndReimport();
        #endif
    }
    [SetUp]
    public void SetUpTest()
    {
        m_Texture = Resources.Load<Texture2D>("Circle");
    }
    [Test]
    public void WhenNullTextureIsPassed_CreateShouldReturnNullSprite()
    {
        // Check with Valid Texture.
        LogAssert.Expect(LogType.Log, "Circle Sprite Created");
        Sprite.Create(m_Texture, new Rect(0, 0, m_Texture.width, m_Texture.height), new Vector2(0.5f, 0.5f));
        Debug.Log("Circle Sprite Created");
        // Check with NULL Texture. Should return NULL Sprite.
        m_Sprite = Sprite.Create(null, new Rect(0, 0, m_Texture.width, m_Texture.height), new Vector2(0.5f, 0.5f));
        Assert.That(m_Sprite, Is.Null, "Sprite created with null texture should be null");
    }
}
Implements UnityEngine.TestTools.IPrebuildSetup.
TearDown()
void ToggleTest.ToggleGroupTests.TearDown ()
TestSetup()
void ToggleTest.ToggleGroupTests.TestSetup ()
TogglingOneShouldDisableOthersInGroup()
void ToggleTest.ToggleGroupTests.TogglingOneShouldDisableOthersInGroup ()
Member Data Documentation
m_PrefabRoot
GameObject ToggleTest.ToggleGroupTests.m_PrefabRoot protected
Referenced by ToggleTest.ToggleGroupTests.ReEnablingGameObjectWithToggleGroupRetainsPreviouslySelectedToggle(), ToggleTest.ToggleGroupTests.TearDown(), and ToggleTest.ToggleGroupTests.TestSetup().
m_toggle
List<Toggle> ToggleTest.ToggleGroupTests.m_toggle = new List<Toggle>() protected
Referenced by ToggleTest.ToggleGroupTests.ChangingToggleGroupUnregistersFromOriginalGroup(), ToggleTest.ToggleGroupTests.DisabledToggleGroupDoesntControlChildren(), ToggleTest.ToggleGroupTests.DisallowSwitchOffShouldDisableToggleWhenClicking(), ToggleTest.ToggleGroupTests.DisallowSwitchOffShouldKeepToggleOnWhenClicking(), ToggleTest.ToggleGroupTests.ReEnablingGameObjectWithToggleGroupRetainsPreviouslySelectedToggle(), ToggleTest.ToggleGroupTests.TearDown(), ToggleTest.ToggleGroupTests.TestSetup(), and ToggleTest.ToggleGroupTests.TogglingOneShouldDisableOthersInGroup().
nbToggleInGroup
int ToggleTest.ToggleGroupTests.nbToggleInGroup = 2 static protected
The documentation for this class was generated from the following file:
C:/Users/Lykos/Desktop/Projects/Capstone/VRGames/Library/PackageCache/com.unity.ugui@1.0.0/Tests/Runtime/Toggle/ToggleGroupTests.cs