VRCapstoneGames: UnityEngine.EventSystems.OVRInputModule Class Reference
UnityEngine.EventSystems.OVRInputModule Class Reference
VR extension of PointerInputModule which supports gaze and controller pointing.
Public Types
enum InputMode { Mouse , Buttons }
Public Member Functions
override void UpdateModule ()
override bool IsModuleSupported ()
override bool ShouldActivateModule ()
override void ActivateModule ()
override void DeactivateModule ()
override void Process ()
Process this InputModule. Same as the StandaloneInputModule version, except that it calls ProcessMouseEvent twice, once for gaze pointers, and once for mouse pointers.
Public Member Functions inherited from UnityEngine.EventSystems.PointerInputModule
override bool IsPointerOverGameObject (int pointerId)
override string ToString ()
Public Attributes
Transform rayTransform
OVRCursor m_Cursor
OVRInput.Button joyPadClickButton = OVRInput.Button.One
KeyCode gazeClickKey = KeyCode.Space
bool performSphereCastForGazepointer
bool useRightStickScroll = true
float rightStickDeadZone = 0.15f
bool useSwipeScroll = true
float swipeDragThreshold = 2
float swipeDragScale = 1f
bool InvertSwipeXAxis = false
OVRRaycaster activeGraphicRaycaster
float angleDragThreshold = 1
Protected Member Functions
OVRInputModule ()
void CopyFromTo (OVRPointerEventData @from, OVRPointerEventData @to)
Convenience function for cloning PointerEventData.
new void CopyFromTo (PointerEventData @from, PointerEventData @to)
Convenience function for cloning PointerEventData.
bool GetPointerData (int id, out OVRPointerEventData data, bool create)
new void ClearSelection ()
Clear pointer state for both types of pointer.
virtual MouseState GetGazePointerData ()
State for a pointer controlled by a world space ray. E.g. gaze pointer.
MouseState GetCanvasPointerData ()
Get state for pointer which is a pointer moving in world space across the surface of a world space canvas.
Vector2 SwipeAdjustedPosition (Vector2 originalPosition, PointerEventData pointerEvent)
override void ProcessDrag (PointerEventData pointerEvent)
Exactly the same as the code from PointerInputModule, except that we call our own IsPointerMoving.
virtual PointerEventData.FramePressState GetGazeButtonState ()
Get state of button corresponding to gaze pointer.
Vector2 GetExtraScrollDelta ()
Get extra scroll delta from gamepad.
Protected Member Functions inherited from UnityEngine.EventSystems.PointerInputModule
bool GetPointerData (int id, out PointerEventData data, bool create)
Search the cache for currently active pointers, return true if found.
void RemovePointerData (PointerEventData data)
Remove the PointerEventData from the cache.
PointerEventData GetTouchPointerEventData (Touch input, out bool pressed, out bool released)
Given a touch populate the PointerEventData and return if we are pressed or released.
void CopyFromTo (PointerEventData @from, PointerEventData @to)
Copy one PointerEventData to another.
PointerEventData.FramePressState StateForMouseButton (int buttonId)
Given a mouse button return the current state for the frame.
virtual MouseState GetMousePointerEventData ()
Return the current MouseState. Using the default pointer.
virtual MouseState GetMousePointerEventData (int id)
Return the current MouseState.
PointerEventData GetLastPointerEventData (int id)
Return the last PointerEventData for the given touch / mouse id.
virtual void ProcessMove (PointerEventData pointerEvent)
Process movement for the current frame with the given pointer event.
void ClearSelection ()
Clear all pointers and deselect any selected objects in the EventSystem.
void DeselectIfSelectionChanged (GameObject currentOverGo, BaseEventData pointerEvent)
Deselect the current selected GameObject if the currently pointed-at GameObject is different.
Protected Attributes
Dictionary< int, OVRPointerEventData > m_VRRayPointerData = new Dictionary<int, OVRPointerEventData>()
Protected Attributes inherited from UnityEngine.EventSystems.PointerInputModule
Dictionary< int, PointerEventData > m_PointerData = new Dictionary<int, PointerEventData>()
Properties
InputMode inputMode [get]
bool allowActivationOnMobileDevice [get, set]
float inputActionsPerSecond [get, set]
string horizontalAxis [get, set]
Name of the horizontal axis for movement (if axis events are used).
string verticalAxis [get, set]
Name of the vertical axis for movement (if axis events are used).
string submitButton [get, set]
string cancelButton [get, set]
Additional Inherited Members
Static Public Attributes inherited from UnityEngine.EventSystems.PointerInputModule
const int kMouseLeftId = -1
Id of the cached left mouse pointer event.
const int kMouseRightId = -2
Id of the cached right mouse pointer event.
const int kMouseMiddleId = -3
Id of the cached middle mouse pointer event.
const int kFakeTouchesId = -4
Touch id for when simulating touches on a non touch device.
Detailed Description
VR extension of PointerInputModule which supports gaze and controller pointing.
Member Enumeration Documentation
InputMode
enum UnityEngine.EventSystems.OVRInputModule.InputMode
Enumerator
Mouse
Buttons
Constructor & Destructor Documentation
OVRInputModule()
UnityEngine.EventSystems.OVRInputModule.OVRInputModule () protected
Member Function Documentation
ActivateModule()
override void UnityEngine.EventSystems.OVRInputModule.ActivateModule ()
ClearSelection()
new void UnityEngine.EventSystems.OVRInputModule.ClearSelection () protected
Clear pointer state for both types of pointer.
Referenced by UnityEngine.EventSystems.OVRInputModule.DeactivateModule().
CopyFromTo() [1/2]
void UnityEngine.EventSystems.OVRInputModule.CopyFromTo (OVRPointerEventData @ from, OVRPointerEventData @ to) protected
Convenience function for cloning PointerEventData.
Parameters
from Copy this value
to to this object
Referenced by UnityEngine.EventSystems.OVRInputModule.GetCanvasPointerData(), and UnityEngine.EventSystems.OVRInputModule.GetGazePointerData().
CopyFromTo() [2/2]
new void UnityEngine.EventSystems.OVRInputModule.CopyFromTo (PointerEventData @ from, PointerEventData @ to) protected
Convenience function for cloning PointerEventData.
Parameters
from Copy this value
to to this object
DeactivateModule()
override void UnityEngine.EventSystems.OVRInputModule.DeactivateModule ()
GetCanvasPointerData()
MouseState UnityEngine.EventSystems.OVRInputModule.GetCanvasPointerData () protected
Get state for pointer which is a pointer moving in world space across the surface of a world space canvas.
Returns
Referenced by UnityEngine.EventSystems.OVRInputModule.Process().
GetExtraScrollDelta()
Vector2 UnityEngine.EventSystems.OVRInputModule.GetExtraScrollDelta () protected
Get extra scroll delta from gamepad.
Referenced by UnityEngine.EventSystems.OVRInputModule.GetGazePointerData().
GetGazeButtonState()
virtual PointerEventData.FramePressState UnityEngine.EventSystems.OVRInputModule.GetGazeButtonState () protected virtual
Get state of button corresponding to gaze pointer.
Returns
Referenced by UnityEngine.EventSystems.OVRInputModule.GetGazePointerData().
GetGazePointerData()
virtual MouseState UnityEngine.EventSystems.OVRInputModule.GetGazePointerData () protected virtual
State for a pointer controlled by a world space ray. E.g. gaze pointer.
Returns
Referenced by UnityEngine.EventSystems.OVRInputModule.Process().
GetPointerData()
bool UnityEngine.EventSystems.OVRInputModule.GetPointerData (int id, out OVRPointerEventData data, bool create) protected
Referenced by UnityEngine.EventSystems.OVRInputModule.GetCanvasPointerData(), and UnityEngine.EventSystems.OVRInputModule.GetGazePointerData().
IsModuleSupported()
override bool UnityEngine.EventSystems.OVRInputModule.IsModuleSupported ()
Process()
override void UnityEngine.EventSystems.OVRInputModule.Process ()
Process this InputModule. Same as the StandaloneInputModule version, except that it calls ProcessMouseEvent twice, once for gaze pointers, and once for mouse pointers.
ProcessDrag()
override void UnityEngine.EventSystems.OVRInputModule.ProcessDrag (PointerEventData pointerEvent) protected virtual
Exactly the same as the code from PointerInputModule, except that we call our own IsPointerMoving.
This would also not be necessary if PointerEventData.IsPointerMoving was virtual
Parameters
pointerEvent
Reimplemented from UnityEngine.EventSystems.PointerInputModule.
ShouldActivateModule()
override bool UnityEngine.EventSystems.OVRInputModule.ShouldActivateModule ()
SwipeAdjustedPosition()
Vector2 UnityEngine.EventSystems.OVRInputModule.SwipeAdjustedPosition (Vector2 originalPosition, PointerEventData pointerEvent) protected
Referenced by UnityEngine.EventSystems.OVRInputModule.ProcessDrag().
UpdateModule()
override void UnityEngine.EventSystems.OVRInputModule.UpdateModule ()
Member Data Documentation
activeGraphicRaycaster
OVRRaycaster UnityEngine.EventSystems.OVRInputModule.activeGraphicRaycaster
Referenced by UnityEngine.EventSystems.OVRInputModule.GetCanvasPointerData().
angleDragThreshold
float UnityEngine.EventSystems.OVRInputModule.angleDragThreshold = 1
gazeClickKey
KeyCode UnityEngine.EventSystems.OVRInputModule.gazeClickKey = KeyCode.Space
Referenced by UnityEngine.EventSystems.OVRInputModule.GetGazeButtonState().
InvertSwipeXAxis
bool UnityEngine.EventSystems.OVRInputModule.InvertSwipeXAxis = false
Referenced by UnityEngine.EventSystems.OVRInputModule.SwipeAdjustedPosition().
joyPadClickButton
OVRInput.Button UnityEngine.EventSystems.OVRInputModule.joyPadClickButton = OVRInput.Button.One
Referenced by UnityEngine.EventSystems.OVRInputModule.GetGazeButtonState().
m_Cursor
OVRCursor UnityEngine.EventSystems.OVRInputModule.m_Cursor
Referenced by UnityEngine.EventSystems.OVRInputModule.GetGazePointerData().
m_VRRayPointerData
Dictionary<int, OVRPointerEventData> UnityEngine.EventSystems.OVRInputModule.m_VRRayPointerData = new Dictionary<int, OVRPointerEventData>() protected
Referenced by UnityEngine.EventSystems.OVRInputModule.ClearSelection(), and UnityEngine.EventSystems.OVRInputModule.GetPointerData().
performSphereCastForGazepointer
bool UnityEngine.EventSystems.OVRInputModule.performSphereCastForGazepointer
Referenced by UnityEngine.EventSystems.OVRInputModule.GetGazePointerData().
rayTransform
Transform UnityEngine.EventSystems.OVRInputModule.rayTransform
Referenced by UnityEngine.EventSystems.OVRInputModule.GetGazePointerData().
rightStickDeadZone
float UnityEngine.EventSystems.OVRInputModule.rightStickDeadZone = 0.15f
Referenced by UnityEngine.EventSystems.OVRInputModule.GetExtraScrollDelta().
swipeDragScale
float UnityEngine.EventSystems.OVRInputModule.swipeDragScale = 1f
Referenced by UnityEngine.EventSystems.OVRInputModule.SwipeAdjustedPosition().
swipeDragThreshold
float UnityEngine.EventSystems.OVRInputModule.swipeDragThreshold = 2
useRightStickScroll
bool UnityEngine.EventSystems.OVRInputModule.useRightStickScroll = true
Referenced by UnityEngine.EventSystems.OVRInputModule.GetExtraScrollDelta().
useSwipeScroll
bool UnityEngine.EventSystems.OVRInputModule.useSwipeScroll = true
Referenced by UnityEngine.EventSystems.OVRInputModule.SwipeAdjustedPosition().
Property Documentation
allowActivationOnMobileDevice
bool UnityEngine.EventSystems.OVRInputModule.allowActivationOnMobileDevice get set
cancelButton
string UnityEngine.EventSystems.OVRInputModule.cancelButton get set
horizontalAxis
string UnityEngine.EventSystems.OVRInputModule.horizontalAxis get set
Name of the horizontal axis for movement (if axis events are used).
inputActionsPerSecond
float UnityEngine.EventSystems.OVRInputModule.inputActionsPerSecond get set
inputMode
InputMode UnityEngine.EventSystems.OVRInputModule.inputMode get
submitButton
string UnityEngine.EventSystems.OVRInputModule.submitButton get set
verticalAxis
string UnityEngine.EventSystems.OVRInputModule.verticalAxis get set
Name of the vertical axis for movement (if axis events are used).
The documentation for this class was generated from the following file:
C:/Users/Lykos/Desktop/Projects/Capstone/VRGames/Assets/ThirdParty/Oculus/VR/Scripts/Util/OVRInputModule.cs