VRCapstoneGames: UnityEngine.InputSystem.Controls.AxisControl Class Reference
UnityEngine.InputSystem.Controls.AxisControl Class Reference
A floating-point axis control.
Public Types
enum Clamp { None = 0 , BeforeNormalize = 1 , AfterNormalize = 2 , ToConstantBeforeNormalize = 3 }
Clamping behavior for an axis control.
Public Member Functions
AxisControl ()
Default-initialize the control.
override unsafe float ReadUnprocessedValueFromState (void *statePtr)
override unsafe void WriteValueIntoState (float value, void *statePtr)
override unsafe bool CompareValue (void *firstStatePtr, void *secondStatePtr)
override unsafe float EvaluateMagnitude (void *statePtr)
Compute an absolute, normalized magnitude value that indicates the extent to which the control is actuated in the given state.
Parameters
statePtr State containing the control's stateBlock.
Returns
Amount of actuation of the control or -1 if it cannot be determined.
See also
EvaluateMagnitude(), stateBlock
Public Member Functions inherited from UnityEngine.InputSystem.InputControl< float >
override string ToString ()
Return a string representation of the control useful for debugging.
unsafe float EvaluateMagnitude ()
Compute an absolute, normalized magnitude value that indicates the extent to which the control is actuated.
unsafe object ReadValueFromBufferAsObject (void *buffer, int bufferSize)
override unsafe object ReadValueFromBufferAsObject (void *buffer, int bufferSize)
unsafe object ReadValueFromStateAsObject (void *statePtr)
Read the control's final, processed value from the given state and return the value as an object.
override unsafe object ReadValueFromStateAsObject (void *statePtr)
unsafe void ReadValueFromStateIntoBuffer (void *statePtr, void *bufferPtr, int bufferSize)
Read the control's final, processed value from the given state and store it in the given buffer.
override unsafe void ReadValueFromStateIntoBuffer (void *statePtr, void *bufferPtr, int bufferSize)
virtual unsafe void WriteValueFromBufferIntoState (void *bufferPtr, int bufferSize, void *statePtr)
Read a value from the given memory and store it as state.
override unsafe void WriteValueFromBufferIntoState (void *bufferPtr, int bufferSize, void *statePtr)
virtual unsafe void WriteValueFromObjectIntoState (object value, void *statePtr)
Read a value object and store it as state in the given memory.
override unsafe void WriteValueFromObjectIntoState (object value, void *statePtr)
unsafe bool CompareValue (void *firstStatePtr, void *secondStatePtr)
Compare the value of the control as read from firstStatePtr to that read from secondStatePtr and return true if they are equal.
override unsafe bool CompareValue (void *firstStatePtr, void *secondStatePtr)
InputControl TryGetChildControl (string path)
Try to find a child control matching the given path.
TControl TryGetChildControl< TControl > (string path)
InputControl GetChildControl (string path)
TControl GetChildControl< TControl > (string path)
TValue ReadValue ()
Get the control's current value as read from InputControl.currentStatePtr
TValue ReadValueFromPreviousFrame ()
Get the control's value from the previous frame (InputControl.previousFrameStatePtr).
TValue ReadDefaultValue ()
Get the control's default value.
unsafe TValue ReadValueFromState (void *statePtr)
TValue ReadUnprocessedValue ()
unsafe TValue ReadUnprocessedValueFromState (void *statePtr)
virtual unsafe void WriteValueIntoState (TValue value, void *statePtr)
TValue ProcessValue (TValue value)
Public Attributes
Clamp clamp
Clamping behavior when reading values. Clamp.None by default.
float clampMin
Lower end of the clamping range when clamp is not Clamp.None.
float clampMax
Upper end of the clamping range when clamp is not Clamp.None.
float clampConstant
When clamp is set to Clamp.ToConstantBeforeNormalize and the value is outside of the range defined by clampMin and clampMax, this value is returned.
bool invert
If true, the input value will be inverted, i.e. multiplied by -1. Off by default.
bool normalize
If true, normalize the input value to [0..1] or [-1..1] (depending on the value of normalizeZero. Off by default.
float normalizeMin
If normalize is on, this is the input value that corresponds to 0 of the normalized [0..1] or [-1..1] range.
float normalizeMax
If normalize is on, this is the input value that corresponds to 1 of the normalized [0..1] or [-1..1] range.
float normalizeZero
Where to put the zero point of the normalization range. Only relevant if normalize is set to true. Defaults to 0.
bool scale
Whether the scale the input value by scaleFactor. Off by default.
float scaleFactor
Value to multiple input values with. Only applied if scale is true.
Protected Member Functions
float Preprocess (float value)
Apply modifications to the given value according to the parameters configured on the control (clamp, normalize, etc).
override void FinishSetup ()
Perform final initialization tasks after the control hierarchy has been put into place.
Protected Member Functions inherited from UnityEngine.InputSystem.InputControl< float >
InputControl ()
void RefreshConfigurationIfNeeded ()
Call RefreshConfiguration if the configuration has in the interim been invalidated by a DeviceConfigurationEvent.
virtual void RefreshConfiguration ()
Additional Inherited Members
Properties inherited from UnityEngine.InputSystem.InputControl< float >
string name [get]
The name of the control, i.e. the final name part in its path.
string displayName [get, protected set]
The text to display as the name of the control.
string shortDisplayName [get, protected set]
An alternate, abbreviated displayName (for example "LMB" instead of "Left Button").
string path [get]
Full path all the way from the root.
string layout [get]
Layout the control is based on.
string variants [get]
Semicolon-separated list of variants of the control layout or "default".
InputDevice device [get]
The device that this control is a part of.
InputControl parent [get]
The immediate parent of the control or null if the control has no parent (which, once fully constructed) will only be the case for InputDevices).
ReadOnlyArray< InputControl > children [get]
List of immediate children.
ReadOnlyArray< InternedString > usages [get]
List of usage tags associated with the control.
ReadOnlyArray< InternedString > aliases [get]
InputStateBlock stateBlock [get]
bool noisy [get, set]
Whether the control is considered noisy.
bool synthetic [get, set]
Whether the control is considered synthetic.
InputControl this[string path] [get]
Fetch a control from the control's hierarchy by name.
Type valueType [get]
Returns the underlying value type of this control.
override Type valueType [get]
int valueSizeInBytes [get]
Size in bytes of values that the control returns.
override int valueSizeInBytes [get]
Detailed Description
A floating-point axis control.
Can optionally be configured to perform normalization. Stored as either a float, a short, a byte, or a single bit.
Member Enumeration Documentation
Clamp
enum UnityEngine.InputSystem.Controls.AxisControl.Clamp
Clamping behavior for an axis control.
Enumerator
None
Do not clamp values.
BeforeNormalize
Clamp values to clampMin and clampMax before normalizing the value.
AfterNormalize
Clamp values to clampMin and clampMax after normalizing the value.
ToConstantBeforeNormalize
Clamp values any value below clampMin or above clampMax to clampConstant before normalizing the value.
Constructor & Destructor Documentation
AxisControl()
UnityEngine.InputSystem.Controls.AxisControl.AxisControl ()
Default-initialize the control.
Defaults the format to InputStateBlock.FormatFloat.
Member Function Documentation
CompareValue()
override unsafe bool UnityEngine.InputSystem.Controls.AxisControl.CompareValue (void * firstStatePtr, void * secondStatePtr)
EvaluateMagnitude()
override unsafe float UnityEngine.InputSystem.Controls.AxisControl.EvaluateMagnitude (void * statePtr) virtual
Compute an absolute, normalized magnitude value that indicates the extent to which the control is actuated in the given state.
Parameters
statePtr State containing the control's stateBlock.
Returns
Amount of actuation of the control or -1 if it cannot be determined.
See also
EvaluateMagnitude(), stateBlock
Reimplemented from UnityEngine.InputSystem.InputControl< float >.
FinishSetup()
override void UnityEngine.InputSystem.Controls.AxisControl.FinishSetup () protected virtual
Perform final initialization tasks after the control hierarchy has been put into place.
This method can be overridden to perform control- or device-specific setup work. The most common use case is for looking up child controls and storing them in local getters.
public class MyDevice : InputDevice
{
    public ButtonControl button { get; private set; }
    public AxisControl axis { get; private set; }
    protected override void OnFinishSetup()
    {
        // Cache controls in getters.
        button = GetChildControl("button");
        axis = GetChildControl("axis");
    }
}
Reimplemented from UnityEngine.InputSystem.InputControl< float >.
Reimplemented in UnityEngine.InputSystem.Controls.DiscreteButtonControl, UnityEngine.InputSystem.Controls.DpadControl.DpadAxisControl, and UnityEngine.InputSystem.Controls.TouchPressControl.
Preprocess()
float UnityEngine.InputSystem.Controls.AxisControl.Preprocess (float value) protected
Apply modifications to the given value according to the parameters configured on the control (clamp, normalize, etc).
Parameters
value Input value.
Returns
A processed value (clamped, normalized, etc).
See also
clamp, normalize, scale, invert
Referenced by UnityEngine.InputSystem.Controls.AxisControl.ReadUnprocessedValueFromState(), UnityEngine.InputSystem.Controls.DiscreteButtonControl.ReadUnprocessedValueFromState(), and UnityEngine.InputSystem.Controls.TouchPressControl.ReadUnprocessedValueFromState().
ReadUnprocessedValueFromState()
override unsafe float UnityEngine.InputSystem.Controls.AxisControl.ReadUnprocessedValueFromState (void * statePtr)
Referenced by UnityEngine.InputSystem.Controls.QuaternionControl.ReadUnprocessedValueFromState(), UnityEngine.InputSystem.Controls.Vector2Control.ReadUnprocessedValueFromState(), and UnityEngine.InputSystem.Controls.Vector3Control.ReadUnprocessedValueFromState().
WriteValueIntoState()
override unsafe void UnityEngine.InputSystem.Controls.AxisControl.WriteValueIntoState (float value, void * statePtr)
Referenced by UnityEngine.InputSystem.Controls.QuaternionControl.WriteValueIntoState(), UnityEngine.InputSystem.Controls.Vector2Control.WriteValueIntoState(), and UnityEngine.InputSystem.Controls.Vector3Control.WriteValueIntoState().
Member Data Documentation
clamp
Clamp UnityEngine.InputSystem.Controls.AxisControl.clamp
Clamping behavior when reading values. Clamp.None by default.
Clamping behavior.
When a value is read from the control's state, it is first converted to a floating-point number.
See also
clampMin, clampMax, clampConstant
Referenced by UnityEngine.InputSystem.Controls.AxisControl.Preprocess().
clampConstant
float UnityEngine.InputSystem.Controls.AxisControl.clampConstant
When clamp is set to Clamp.ToConstantBeforeNormalize and the value is outside of the range defined by clampMin and clampMax, this value is returned.
Constant value to return when value is outside of clamping range.
Referenced by UnityEngine.InputSystem.Controls.AxisControl.Preprocess().
clampMax
float UnityEngine.InputSystem.Controls.AxisControl.clampMax
Upper end of the clamping range when clamp is not Clamp.None.
Upper bound of clamping range. Inclusive.
Referenced by UnityEngine.InputSystem.Controls.AxisControl.Preprocess().
clampMin
float UnityEngine.InputSystem.Controls.AxisControl.clampMin
Lower end of the clamping range when clamp is not Clamp.None.
Lower bound of clamping range. Inclusive.
Referenced by UnityEngine.InputSystem.Controls.AxisControl.Preprocess().
invert
bool UnityEngine.InputSystem.Controls.AxisControl.invert
If true, the input value will be inverted, i.e. multiplied by -1. Off by default.
REVIEW: why not just roll this into scaleFactor?
Whether to invert the input value.
Referenced by UnityEngine.InputSystem.Controls.AxisControl.Preprocess().
normalize
bool UnityEngine.InputSystem.Controls.AxisControl.normalize
If true, normalize the input value to [0..1] or [-1..1] (depending on the value of normalizeZero. Off by default.
Whether to normalize input values or not.
See also
normalizeMin, normalizeMax
Referenced by UnityEngine.InputSystem.Controls.AxisControl.FinishSetup(), and UnityEngine.InputSystem.Controls.AxisControl.Preprocess().
normalizeMax
float UnityEngine.InputSystem.Controls.AxisControl.normalizeMax
If normalize is on, this is the input value that corresponds to 1 of the normalized [0..1] or [-1..1] range.
Input value that should become 1.
In other words, with normalize on, input values are mapped from the range of [normalizeMin..normalizeMax] to [0..1] or [-1..1] (depending on normalizeZero).
Referenced by UnityEngine.InputSystem.Controls.AxisControl.Preprocess().
normalizeMin
float UnityEngine.InputSystem.Controls.AxisControl.normalizeMin
If normalize is on, this is the input value that corresponds to 0 of the normalized [0..1] or [-1..1] range.
Input value that should become 0 or -1.
In other words, with normalize on, input values are mapped from the range of [normalizeMin..normalizeMax] to [0..1] or [-1..1] (depending on normalizeZero).
Referenced by UnityEngine.InputSystem.Controls.AxisControl.Preprocess().
normalizeZero
float UnityEngine.InputSystem.Controls.AxisControl.normalizeZero
Where to put the zero point of the normalization range. Only relevant if normalize is set to true. Defaults to 0.
Zero point of normalization range.
The value of this property determines where the zero point is located in the range established by normalizeMin and normalizeMax.
If normalizeZero is placed at normalizeMin, the normalization returns a value in the [0..1] range mapped from the input value range of normalizeMin and normalizeMax.
If normalizeZero is placed in-between normalizeMin and normalizeMax, normalization returns a value in the [-1..1] mapped from the input value range of normalizeMin and normalizeMax and the zero point between the two established by normalizeZero.
Referenced by UnityEngine.InputSystem.Controls.AxisControl.FinishSetup(), and UnityEngine.InputSystem.Controls.AxisControl.Preprocess().
scale
bool UnityEngine.InputSystem.Controls.AxisControl.scale
Whether the scale the input value by scaleFactor. Off by default.
True if inputs should be scaled by scaleFactor.
Referenced by UnityEngine.InputSystem.Controls.AxisControl.Preprocess().
scaleFactor
float UnityEngine.InputSystem.Controls.AxisControl.scaleFactor
Value to multiple input values with. Only applied if scale is true.
Multiplier for input values.
Referenced by UnityEngine.InputSystem.Controls.AxisControl.Preprocess().
The documentation for this class was generated from the following file:
C:/Users/Lykos/Desktop/Projects/Capstone/VRGames/Library/PackageCache/com.unity.inputsystem@1.3.0/InputSystem/Controls/AxisControl.cs