VRCapstoneGames: OVR.SoundFX Class Reference
OVR.SoundFX Class Reference
Public Member Functions
SoundFX ()
AudioClip GetClip ()
AudioMixerGroup GetMixerGroup (AudioMixerGroup defaultMixerGroup)
bool ReachedGroupPlayLimit ()
float GetClipLength (int idx)
float GetPitch ()
int PlaySound (float delaySecs=0.0f)
int PlaySoundAt (Vector3 pos, float delaySecs=0.0f, float volumeOverride=1.0f, float pitchMultiplier=1.0f)
void SetOnFinished (System.Action onFinished)
void SetOnFinished (System.Action< object > onFinished, object obj)
bool StopSound ()
void AttachToParent (Transform parent)
void DetachFromParent ()
Public Attributes
string name = string.Empty
SoundFXNext playback = SoundFXNext.Random
float volume = 1.0f
Vector2 pitchVariance = Vector2.one
Vector2 falloffDistance = new Vector2(1.0f, 25.0f)
AudioRolloffMode falloffCurve = AudioRolloffMode.Linear
AnimationCurve volumeFalloffCurve = new AnimationCurve(new Keyframe[2] { new Keyframe(0f, 1.0f), new Keyframe(1f, 1f) })
AnimationCurve reverbZoneMix = new AnimationCurve(new Keyframe[2] { new Keyframe(0f, 1.0f), new Keyframe(1f, 1f) })
float spread = 0.0f
float pctChanceToPlay = 1.0f
SoundPriority priority = SoundPriority.Default
Vector2 delay = Vector2.zero
bool looping = false
OSPProps ospProps = new OSPProps()
AudioClip[] soundClips = new AudioClip[1]
bool visibilityToggle = false
Properties
int Length [get]
bool IsValid [get]
SoundGroup Group [get, set]
float MaxFalloffDistSquared [get]
float GroupVolumeOverride [get]
Constructor & Destructor Documentation
SoundFX()
OVR.SoundFX.SoundFX ()
Member Function Documentation
AttachToParent()
void OVR.SoundFX.AttachToParent (Transform parent)
Referenced by OVR.SoundFXRef.AttachToParent().
DetachFromParent()
void OVR.SoundFX.DetachFromParent ()
Referenced by OVR.SoundFXRef.DetachFromParent().
GetClip()
AudioClip OVR.SoundFX.GetClip ()
Referenced by OVR.SoundFXRef.GetClip(), and OVR.AudioManager.PlaySoundAt().
GetClipLength()
float OVR.SoundFX.GetClipLength (int idx)
Referenced by OVR.SoundFXRef.GetClipLength().
GetMixerGroup()
AudioMixerGroup OVR.SoundFX.GetMixerGroup (AudioMixerGroup defaultMixerGroup)
Referenced by OVR.AudioManager.PlaySoundAt().
GetPitch()
float OVR.SoundFX.GetPitch ()
Referenced by OVR.AudioManager.PlaySoundAt().
PlaySound()
int OVR.SoundFX.PlaySound (float delaySecs = 0::0f)
Referenced by OVR.SoundFXRef.PlaySound().
PlaySoundAt()
int OVR.SoundFX.PlaySoundAt (Vector3 pos, float delaySecs = 0::0f, float volumeOverride = 1::0f, float pitchMultiplier = 1::0f)
Referenced by OVR.SoundFXRef.PlaySoundAt().
ReachedGroupPlayLimit()
bool OVR.SoundFX.ReachedGroupPlayLimit ()
Referenced by OVR.AudioManager.PlaySoundAt().
SetOnFinished() [1/2]
void OVR.SoundFX.SetOnFinished (System::Action onFinished)
Referenced by OVR.SoundFXRef.SetOnFinished(), and OVR.SoundFXRef.SetOnFinished().
SetOnFinished() [2/2]
void OVR.SoundFX.SetOnFinished (System::Action< object > onFinished, object obj)
StopSound()
bool OVR.SoundFX.StopSound ()
Referenced by OVR.SoundFXRef.StopSound().
Member Data Documentation
delay
Vector2 OVR.SoundFX.delay = Vector2.zero
Referenced by OVR.SoundFX.PlaySound(), OVR.SoundFX.PlaySoundAt(), and OVR.SoundFX.SoundFX().
falloffCurve
AudioRolloffMode OVR.SoundFX.falloffCurve = AudioRolloffMode.Linear
Referenced by OVR.AudioManager.PlaySoundAt(), and OVR.SoundFX.SoundFX().
falloffDistance
Vector2 OVR.SoundFX.falloffDistance = new Vector2(1.0f, 25.0f)
Referenced by OVR.AudioManager.PlaySoundAt(), and OVR.SoundFX.SoundFX().
looping
bool OVR.SoundFX.looping = false
Referenced by OVR.AudioManager.PlaySoundAt(), and OVR.SoundFX.SoundFX().
name
string OVR.SoundFX.name = string.Empty
Referenced by OVR.AudioManager.GetSoundFXNames(), and OVR.AudioManager.PlaySoundAt().
ospProps
OSPProps OVR.SoundFX.ospProps = new OSPProps()
Referenced by OVR.AudioManager.PlaySoundAt(), and OVR.SoundFX.SoundFX().
pctChanceToPlay
float OVR.SoundFX.pctChanceToPlay = 1.0f
Referenced by OVR.SoundFX.PlaySound(), OVR.SoundFX.PlaySoundAt(), and OVR.SoundFX.SoundFX().
pitchVariance
Vector2 OVR.SoundFX.pitchVariance = Vector2.one
Referenced by OVR.SoundFX.GetPitch(), and OVR.SoundFX.SoundFX().
playback
SoundFXNext OVR.SoundFX.playback = SoundFXNext.Random
Referenced by OVR.SoundFX.GetClip(), and OVR.SoundFX.SoundFX().
priority
SoundPriority OVR.SoundFX.priority = SoundPriority.Default
Referenced by OVR.AudioManager.PlaySoundAt(), and OVR.SoundFX.SoundFX().
reverbZoneMix
AnimationCurve OVR.SoundFX.reverbZoneMix = new AnimationCurve(new Keyframe[2] { new Keyframe(0f, 1.0f), new Keyframe(1f, 1f) })
Referenced by OVR.AudioManager.PlaySoundAt(), and OVR.SoundFX.SoundFX().
soundClips
AudioClip [] OVR.SoundFX.soundClips = new AudioClip[1]
Referenced by OVR.SoundFX.GetClip(), and OVR.SoundFX.GetClipLength().
spread
float OVR.SoundFX.spread = 0.0f
Referenced by OVR.AudioManager.PlaySoundAt(), and OVR.SoundFX.SoundFX().
visibilityToggle
bool OVR.SoundFX.visibilityToggle = false
volume
float OVR.SoundFX.volume = 1.0f
Referenced by OVR.AudioManager.PlaySoundAt(), and OVR.SoundFX.SoundFX().
volumeFalloffCurve
AnimationCurve OVR.SoundFX.volumeFalloffCurve = new AnimationCurve(new Keyframe[2] { new Keyframe(0f, 1.0f), new Keyframe(1f, 1f) })
Referenced by OVR.AudioManager.PlaySoundAt(), and OVR.SoundFX.SoundFX().
Property Documentation
Group
SoundGroup OVR.SoundFX.Group get set
Referenced by OVR.AudioManager.PlaySoundAt().
GroupVolumeOverride
float OVR.SoundFX.GroupVolumeOverride get
Referenced by OVR.AudioManager.PlaySoundAt().
IsValid
bool OVR.SoundFX.IsValid get
Referenced by OVR.SoundFX.PlaySound(), and OVR.SoundFX.PlaySoundAt().
Length
int OVR.SoundFX.Length get
Referenced by OVR.AudioManager.GetSoundFXNames().
MaxFalloffDistSquared
float OVR.SoundFX.MaxFalloffDistSquared get
Referenced by OVR.AudioManager.PlaySoundAt().
The documentation for this class was generated from the following file:
C:/Users/Lykos/Desktop/Projects/Capstone/VRGames/Assets/ThirdParty/Oculus/AudioManager/Scripts/Audio/SoundFX.cs