VRGames: OVRLipSync Class Reference
OVRLipSync Class Reference
OVRLipSync interfaces into the Oculus lip sync engine. This component should be added into the scene once.
Classes
class Frame
NOTE: Opaque typedef for lip-sync context is an unsigned int (uint)
Public Types
enum Result {
Success = 0 , Unknown = -2200 , CannotCreateContext = -2201 , InvalidParam = -2202 ,
BadSampleRate = -2203 , MissingDLL = -2204 , BadVersion = -2205 , UndefinedFunction = -2206
}
enum AudioDataType { S16_Mono , S16_Stereo , F32_Mono , F32_Stereo }
enum Viseme {
sil , PP , FF , TH ,
DD , kk , CH , SS ,
nn , RR , aa , E ,
ih , oh , ou
}
enum Signals {
VisemeOn , VisemeOff , VisemeAmount , VisemeSmoothing ,
LaughterAmount
}
enum ContextProviders { Original , Enhanced , Enhanced_with_Laughter }
Static Public Member Functions
static Result Initialize ()
static Result Initialize (int sampleRate, int bufferSize)
static void Shutdown ()
static Result IsInitialized ()
Determines if is initialized.
static Result CreateContext (ref uint context, ContextProviders provider, int sampleRate=0, bool enableAcceleration=false)
Creates a lip-sync context.
static Result CreateContextWithModelFile (ref uint context, ContextProviders provider, string modelPath, int sampleRate=0, bool enableAcceleration=false)
Creates a lip-sync context with specified model file.
static Result DestroyContext (uint context)
Destroy a lip-sync context.
static Result ResetContext (uint context)
Resets the context.
static Result SendSignal (uint context, Signals signal, int arg1, int arg2)
Sends a signal to the lip-sync engine.
static Result ProcessFrame (uint context, float[] audioBuffer, Frame frame, bool stereo=true)
Process float[] audio buffer by lip-sync engine.
static Result ProcessFrame (uint context, short[] audioBuffer, Frame frame, bool stereo=true)
Process short[] audio buffer by lip-sync engine.
Static Public Attributes
static readonly int VisemeCount = Enum.GetNames(typeof(Viseme)).Length
static readonly int SignalCount = Enum.GetNames(typeof(Signals)).Length
const string strOVRLS = "OVRLipSync"
static OVRLipSync sInstance = null
Detailed Description
OVRLipSync interfaces into the Oculus lip sync engine. This component should be added into the scene once.
Member Enumeration Documentation
AudioDataType
enum OVRLipSync.AudioDataType
Enumerator
S16_Mono
S16_Stereo
F32_Mono
F32_Stereo
ContextProviders
enum OVRLipSync.ContextProviders
Enumerator
Original
Enhanced
Enhanced_with_Laughter
Result
enum OVRLipSync.Result
Enumerator
Success
Unknown
CannotCreateContext
InvalidParam
BadSampleRate
MissingDLL
BadVersion
UndefinedFunction
Signals
enum OVRLipSync.Signals
Enumerator
VisemeOn
VisemeOff
VisemeAmount
VisemeSmoothing
LaughterAmount
Viseme
enum OVRLipSync.Viseme
Enumerator
sil
PP
FF
TH
DD
kk
CH
SS
nn
RR
aa
E
ih
oh
ou
Member Function Documentation
CreateContext()
static Result OVRLipSync.CreateContext (ref uint context, ContextProviders provider, int sampleRate = 0, bool enableAcceleration = false) static
Creates a lip-sync context.
Returns
error code
Parameters
context Context.
provider Provider.
enableAcceleration Enable DSP Acceleration.
CreateContextWithModelFile()
static Result OVRLipSync.CreateContextWithModelFile (ref uint context, ContextProviders provider, string modelPath, int sampleRate = 0, bool enableAcceleration = false) static
Creates a lip-sync context with specified model file.
Returns
error code
Parameters
context Context.
provider Provider.
modelPath Model Dir.
sampleRate Sampling Rate.
enableAcceleration Enable DSP Acceleration.
DestroyContext()
static Result OVRLipSync.DestroyContext (uint context) static
Destroy a lip-sync context.
Returns
The context.
Parameters
context Context.
Initialize() [1/2]
static Result OVRLipSync.Initialize () static
Referenced by CreateContext(), and CreateContextWithModelFile().
Initialize() [2/2]
static Result OVRLipSync.Initialize (int sampleRate, int bufferSize) static
IsInitialized()
static Result OVRLipSync.IsInitialized () static
Determines if is initialized.
Returns
true if is initialized; otherwise, false.
Referenced by CreateContext(), CreateContextWithModelFile(), DestroyContext(), OVRLipSyncContext.ProcessAudioSamples(), OVRLipSyncContext.ProcessAudioSamplesRaw(), OVRLipSyncContext.ProcessAudioSamplesRaw(), ProcessFrame(), ProcessFrame(), ResetContext(), and SendSignal().
ProcessFrame() [1/2]
static Result OVRLipSync.ProcessFrame (uint context, float[] audioBuffer, Frame frame, bool stereo = true) static
Process float[] audio buffer by lip-sync engine.
Returns
error code
Parameters
context Context.
audioBuffer PCM audio buffer.
frame Lip-sync Frame.
stereo Whether buffer is part of stereo or mono stream.
Referenced by OVRLipSyncContext.ProcessAudioSamplesRaw(), and OVRLipSyncContext.ProcessAudioSamplesRaw().
ProcessFrame() [2/2]
static Result OVRLipSync.ProcessFrame (uint context, short[] audioBuffer, Frame frame, bool stereo = true) static
Process short[] audio buffer by lip-sync engine.
Returns
error code
Parameters
context Context.
audioBuffer PCM audio buffer.
frame Lip-sync Frame.
stereo Whether buffer is part of stereo or mono stream.
ResetContext()
static Result OVRLipSync.ResetContext (uint context) static
Resets the context.
Returns
error code
Parameters
context Context.
Referenced by OVRLipSyncContextBase.ResetContext().
SendSignal()
static Result OVRLipSync.SendSignal (uint context, Signals signal, int arg1, int arg2) static
Sends a signal to the lip-sync engine.
Returns
error code
Parameters
context Context.
signal Signal.
arg1 Arg1.
arg2 Arg2.
Referenced by OVRLipSyncContextBase.SetLaughterBlend(), and OVRLipSyncContextBase.SetVisemeBlend().
Shutdown()
static void OVRLipSync.Shutdown () static
Member Data Documentation
SignalCount
readonly int OVRLipSync.SignalCount = Enum.GetNames(typeof(Signals)).Length static
sInstance
OVRLipSync OVRLipSync.sInstance = null static
strOVRLS
const string OVRLipSync.strOVRLS = "OVRLipSync" static
VisemeCount
readonly int OVRLipSync.VisemeCount = Enum.GetNames(typeof(Viseme)).Length static
Referenced by OVRLipSync.Frame.Reset().
The documentation for this class was generated from the following file:
C:/Users/Lykos/Desktop/Projects/Capstone/VRGames/Assets/ThirdParty/Oculus/LipSync/Scripts/OVRLipSync.cs