VRCapstoneGames: UnityEditor.Timeline.WindowState Class Reference
UnityEditor.Timeline.WindowState Class Reference
Public Member Functions
WindowState (TimelineWindow w, SequenceHierarchy hierarchy)
void AddCaptured (Manipulator manipulator)
void RemoveCaptured (Manipulator manipulator)
void OnDestroy ()
void OnSceneSaved ()
void SetCurrentSequence (TimelineAsset timelineAsset, PlayableDirector director, TimelineClip hostClip)
void PopSequencesUntilCount (int count)
SequencePath GetCurrentSequencePath ()
void SetCurrentSequencePath (SequencePath path, bool forceRebuild)
IEnumerable< ISequenceState > GetAllSequences ()
IEnumerable< SequenceContext > GetSubSequences ()
void Reset ()
double GetSnappedTimeAtMousePosition (Vector2 mousePos)
void SetTimeAreaTransform (Vector2 newTranslation, Vector2 newScale)
void SetTimeAreaShownRange (float min, float max)
void ResetPreviewMode ()
bool TimeIsInRange (float value)
bool RangeIsVisible (Range range)
void EnsurePlayHeadIsVisible ()
void SetPlayHeadToMiddle ()
TimelineWindow GetWindow ()
void Play ()
void Pause ()
void SetPlaying (bool start)
void Stop ()
void RebuildPlayableGraph ()
void Evaluate ()
void EvaluateImmediate ()
void Refresh ()
void UpdateViewStateHash ()
bool IsEditingASubTimeline ()
bool IsEditingAnEmptyTimeline ()
bool IsEditingAPrefabAsset ()
bool IsCurrentEditingASequencerTextField ()
float TimeToTimeAreaPixel (double t)
float TimeToScreenSpacePixel (double time)
float TimeToPixel (double time)
float PixelToTime (float pixel)
float PixelDeltaToDeltaTime (float p)
float TimeAreaPixelToTime (float pixel)
float ScreenSpacePixelToTimeAreaTime (float p)
float TrackSpacePixelToTimeAreaTime (float p)
void OffsetTimeArea (int pixels)
GameObject GetSceneReference (TrackAsset asset)
void CalculateRowRects ()
void ArmForRecord (TrackAsset track)
void UnarmForRecord (TrackAsset track)
void UpdateRecordingState ()
bool IsTrackRecordable (TrackAsset track)
bool IsArmedForRecord (TrackAsset track)
TrackAsset GetArmedTrack (TrackAsset track)
void GatherProperties (PlayableDirector director)
void AddStartFrameDelegate (PendingUpdateDelegate updateDelegate)
void AddEndFrameDelegate (PendingUpdateDelegate updateDelegate)
void UpdateRootPlayableDuration (double duration)
void InvokeTimeChangeCallback ()
bool IsPlayableGraphDone ()
Public Attributes
TimelineWindowAnalytics analytics = new TimelineWindowAnalytics()
Static Public Attributes
static readonly float kMaxShownTime = (float)TimeUtility.k_MaxTimelineDurationInSeconds
Properties
static double kTimeEpsilon [get]
static AnimationModeDriver previewDriver [get]
EditorWindow editorWindow [get]
ISequenceState editSequence [get]
ISequenceState masterSequence [get]
ISequenceState referenceSequence [get]
IEnumerable< ISequenceState > allSequences [get]
bool rebuildGraph [get, set]
float mouseDragLag [get, set]
SpacePartitioner spacePartitioner [get]
SpacePartitioner headerSpacePartitioner [get]
List< Manipulator > captured [get]
bool isJogging [get, set]
int viewStateHash [get]
float bindingAreaWidth [get, set]
float sequencerHeaderWidth [get, set]
float mainAreaWidth [get, set]
float trackScale [get, set]
int dirtyStamp [get]
bool showQuadTree [get, set]
bool canRecord [get]
bool recording [get, set]
bool previewMode [get, set]
bool playing [get]
float playbackSpeed [get, set]
bool frameSnap [get, set]
bool edgeSnaps [get, set]
bool muteAudioScrubbing [get, set]
TimeReferenceMode timeReferenceMode [get, set]
TimeFormat timeFormat [get, set]
bool showAudioWaveform [get, set]
Vector2 playRange [get, set]
bool showMarkerHeader [get, set]
EditMode.EditType editType [get, set]
PlaybackScrollMode autoScrollMode [get, set]
List< PlayableDirector > previewedDirectors [get]
Vector2 timeAreaShownRange [get, set]
Vector2 timeAreaTranslation [get]
Vector2 timeAreaScale [get]
Rect timeAreaRect [get]
float windowHeight [get]
bool playRangeEnabled [get, set]
bool ignorePreview [get]
Properties inherited from UnityEditor.Timeline.IWindowState
Events
Action< WindowState, Event > windowOnGuiStarted
Action< bool > OnPlayStateChange
System.Action OnDirtyStampChange
System.Action OnRebuildGraphChange
System.Action OnTimeChange
System.Action OnRecordingChange
System.Action OnBeforeSequenceChange
System.Action OnAfterSequenceChange
Constructor & Destructor Documentation
WindowState()
UnityEditor.Timeline.WindowState.WindowState (TimelineWindow w, SequenceHierarchy hierarchy)
Member Function Documentation
AddCaptured()
void UnityEditor.Timeline.WindowState.AddCaptured (Manipulator manipulator)
Referenced by UnityEditor.Timeline.HeaderSplitterManipulator.MouseDown(), UnityEditor.Timeline.TrimClip.MouseDown(), UnityEditor.Timeline.Scrub.MouseDown(), UnityEditor.Timeline.InlineCurveResize.MouseDown(), UnityEditor.Timeline.TrackResize.MouseDown(), UnityEditor.Timeline.EaseClip.MouseDownInternal(), and UnityEditor.Timeline.SelectAndMoveItem.MouseDrag().
AddEndFrameDelegate()
void UnityEditor.Timeline.WindowState.AddEndFrameDelegate (PendingUpdateDelegate updateDelegate)
AddStartFrameDelegate()
void UnityEditor.Timeline.WindowState.AddStartFrameDelegate (PendingUpdateDelegate updateDelegate)
ArmForRecord()
void UnityEditor.Timeline.WindowState.ArmForRecord (TrackAsset track)
CalculateRowRects()
void UnityEditor.Timeline.WindowState.CalculateRowRects ()
Referenced by UnityEditor.Timeline.WindowState.ArmForRecord(), and UnityEditor.Timeline.AnimationTrackRecorder.FinializeTrack().
EnsurePlayHeadIsVisible()
void UnityEditor.Timeline.WindowState.EnsurePlayHeadIsVisible ()
Evaluate()
void UnityEditor.Timeline.WindowState.Evaluate ()
Referenced by UnityEditor.Timeline.SelectAndMoveItem.MouseDrag(), UnityEditor.Timeline.SelectAndMoveItem.MouseUp(), and UnityEditor.Timeline.TimelineWindow.RebuildGraphIfNecessary().
EvaluateImmediate()
void UnityEditor.Timeline.WindowState.EvaluateImmediate ()
Referenced by UnityEditor.Timeline.AnimationTrackRecorder.FinalizeRecording(), and UnityEditor.Timeline.TimelineWindow.RebuildGraphIfNecessary().
GatherProperties()
void UnityEditor.Timeline.WindowState.GatherProperties (PlayableDirector director)
Referenced by UnityEditor.Timeline.WindowState.Evaluate(), UnityEditor.Timeline.WindowState.EvaluateImmediate(), and UnityEditor.Timeline.TimelineWindow.RebuildGraphIfNecessary().
GetAllSequences()
IEnumerable< ISequenceState > UnityEditor.Timeline.WindowState.GetAllSequences ()
GetArmedTrack()
TrackAsset UnityEditor.Timeline.WindowState.GetArmedTrack (TrackAsset track)
Referenced by UnityEditor.Timeline.WindowState.IsArmedForRecord().
GetCurrentSequencePath()
SequencePath UnityEditor.Timeline.WindowState.GetCurrentSequencePath ()
GetSceneReference()
GameObject UnityEditor.Timeline.WindowState.GetSceneReference (TrackAsset asset)
GetSnappedTimeAtMousePosition()
double UnityEditor.Timeline.WindowState.GetSnappedTimeAtMousePosition (Vector2 mousePos)
Referenced by UnityEditor.Timeline.Scrub.MouseDrag().
GetSubSequences()
IEnumerable< SequenceContext > UnityEditor.Timeline.WindowState.GetSubSequences ()
Implements UnityEditor.Timeline.IWindowState.
GetWindow()
TimelineWindow UnityEditor.Timeline.WindowState.GetWindow ()
Referenced by UnityEditor.Timeline.TimelineTrackGUI.Draw(), UnityEditor.Timeline.AnimationTrackRecorder.FinalizeRecording(), UnityEditor.Timeline.HeaderSplitterManipulator.MouseDown(), UnityEditor.Timeline.ClearSelection.MouseDown(), UnityEditor.Timeline.TrackResize.MouseDown(), UnityEditor.Timeline.InlineCurveResize.MouseDrag(), UnityEditor.Timeline.RectangleTool.OnGUI(), UnityEditor.Timeline.HeaderSplitterManipulator.Overlay(), UnityEditor.Timeline.InlineCurveResize.Overlay(), UnityEditor.Timeline.TrackResize.Overlay(), and UnityEditor.Timeline.TimeAreaAutoPanner.TimeAreaAutoPanner().
InvokeTimeChangeCallback()
void UnityEditor.Timeline.WindowState.InvokeTimeChangeCallback ()
IsArmedForRecord()
bool UnityEditor.Timeline.WindowState.IsArmedForRecord (TrackAsset track)
Referenced by UnityEditor.Timeline.InfiniteTrackDrawer.CanDraw(), UnityEditor.Timeline.InfiniteTrackDrawer.DrawTrack(), and UnityEditor.Timeline.WindowState.IsTrackRecordable().
IsCurrentEditingASequencerTextField()
bool UnityEditor.Timeline.WindowState.IsCurrentEditingASequencerTextField ()
Referenced by UnityEditor.Timeline.TimelineShortcutManipulator.ExecuteCommand(), UnityEditor.Timeline.InlineCurvesShortcutManipulator.ExecuteCommand(), and UnityEditor.Timeline.RectangleTool.OnGUI().
IsEditingAnEmptyTimeline()
bool UnityEditor.Timeline.WindowState.IsEditingAnEmptyTimeline ()
Referenced by UnityEditor.Timeline.TimelineMode.ShouldShowTimeArea().
IsEditingAPrefabAsset()
bool UnityEditor.Timeline.WindowState.IsEditingAPrefabAsset ()
IsEditingASubTimeline()
bool UnityEditor.Timeline.WindowState.IsEditingASubTimeline ()
Referenced by UnityEditor.Timeline.TimelineGroupGUI.Draw(), and UnityEditor.Timeline.SnapEngine.SnapEngine().
IsPlayableGraphDone()
bool UnityEditor.Timeline.WindowState.IsPlayableGraphDone ()
IsTrackRecordable()
bool UnityEditor.Timeline.WindowState.IsTrackRecordable (TrackAsset track)
OffsetTimeArea()
void UnityEditor.Timeline.WindowState.OffsetTimeArea (int pixels)
OnDestroy()
void UnityEditor.Timeline.WindowState.OnDestroy ()
OnSceneSaved()
void UnityEditor.Timeline.WindowState.OnSceneSaved ()
Pause()
void UnityEditor.Timeline.WindowState.Pause ()
Referenced by UnityEditor.Timeline.WindowState.SetPlaying().
PixelDeltaToDeltaTime()
float UnityEditor.Timeline.WindowState.PixelDeltaToDeltaTime (float p)
Referenced by UnityEditor.Timeline.ItemsLayer< T >.Draw(), and UnityEditor.Timeline.EaseClip.MouseDrag().
PixelToTime()
float UnityEditor.Timeline.WindowState.PixelToTime (float pixel)
Referenced by UnityEditor.Timeline.WindowState.EnsurePlayHeadIsVisible(), UnityEditor.Timeline.TimelineZoomManipulator.MouseDown(), UnityEditor.Timeline.TimelineZoomManipulator.MouseWheel(), UnityEditor.Timeline.RectangleZoom.OnFinish(), UnityEditor.Timeline.WindowState.PixelDeltaToDeltaTime(), UnityEditor.Timeline.WindowState.SetPlayHeadToMiddle(), and UnityEditor.Timeline.WindowState.TimeAreaPixelToTime().
Play()
void UnityEditor.Timeline.WindowState.Play ()
Referenced by UnityEditor.Timeline.Jog.MouseDown(), UnityEditor.Timeline.Jog.MouseDrag(), UnityEditor.Timeline.Jog.MouseUp(), UnityEditor.Timeline.TimelineWindow.RebuildGraphIfNecessary(), and UnityEditor.Timeline.WindowState.SetPlaying().
PopSequencesUntilCount()
void UnityEditor.Timeline.WindowState.PopSequencesUntilCount (int count)
Implements UnityEditor.Timeline.IWindowState.
RangeIsVisible()
bool UnityEditor.Timeline.WindowState.RangeIsVisible (Range range)
RebuildPlayableGraph()
void UnityEditor.Timeline.WindowState.RebuildPlayableGraph ()
Referenced by UnityEditor.Timeline.TimelineWindow.RebuildGraphIfNecessary().
Refresh()
void UnityEditor.Timeline.WindowState.Refresh ()
Referenced by UnityEditor.Timeline.TimelineRecordingContextualResponder.AddKey(), UnityEditor.Timeline.AnimationTrackRecorder.AddRecordableClip(), UnityEditor.Timeline.TimelineRecordingContextualResponder.RemoveCurve(), and UnityEditor.Timeline.TimelineRecordingContextualResponder.RemoveKey().
RemoveCaptured()
void UnityEditor.Timeline.WindowState.RemoveCaptured (Manipulator manipulator)
Referenced by UnityEditor.Timeline.HeaderSplitterManipulator.MouseUp(), UnityEditor.Timeline.SelectAndMoveItem.MouseUp(), UnityEditor.Timeline.Scrub.MouseUp(), and UnityEditor.Timeline.InlineCurveResize.MouseUp().
Reset()
void UnityEditor.Timeline.WindowState.Reset ()
ResetPreviewMode()
void UnityEditor.Timeline.WindowState.ResetPreviewMode ()
ScreenSpacePixelToTimeAreaTime()
float UnityEditor.Timeline.WindowState.ScreenSpacePixelToTimeAreaTime (float p)
Referenced by UnityEditor.Timeline.WindowState.GetSnappedTimeAtMousePosition().
SetCurrentSequence()
void UnityEditor.Timeline.WindowState.SetCurrentSequence (TimelineAsset timelineAsset, PlayableDirector director, TimelineClip hostClip)
Implements UnityEditor.Timeline.IWindowState.
SetCurrentSequencePath()
void UnityEditor.Timeline.WindowState.SetCurrentSequencePath (SequencePath path, bool forceRebuild)
SetPlayHeadToMiddle()
void UnityEditor.Timeline.WindowState.SetPlayHeadToMiddle ()
SetPlaying()
void UnityEditor.Timeline.WindowState.SetPlaying (bool start)
SetTimeAreaShownRange()
void UnityEditor.Timeline.WindowState.SetTimeAreaShownRange (float min, float max)
Referenced by UnityEditor.Timeline.WindowState.EnsurePlayHeadIsVisible(), UnityEditor.Timeline.RectangleZoom.OnFinish(), and UnityEditor.Timeline.WindowState.SetPlayHeadToMiddle().
SetTimeAreaTransform()
void UnityEditor.Timeline.WindowState.SetTimeAreaTransform (Vector2 newTranslation, Vector2 newScale)
Referenced by UnityEditor.Timeline.WindowState.OffsetTimeArea().
Stop()
void UnityEditor.Timeline.WindowState.Stop ()
Referenced by UnityEditor.Timeline.WindowState.OnDestroy().
TimeAreaPixelToTime()
float UnityEditor.Timeline.WindowState.TimeAreaPixelToTime (float pixel)
TimeIsInRange()
bool UnityEditor.Timeline.WindowState.TimeIsInRange (float value)
TimeToPixel()
float UnityEditor.Timeline.WindowState.TimeToPixel (double time)
Referenced by UnityEditor.Timeline.MoveItemModeRipple.AdjustStartTime(), UnityEditor.Timeline.TimeAreaItem.Draw(), and UnityEditor.ClipCurveEditor.DrawCurveEditor().
TimeToScreenSpacePixel()
float UnityEditor.Timeline.WindowState.TimeToScreenSpacePixel (double time)
TimeToTimeAreaPixel()
float UnityEditor.Timeline.WindowState.TimeToTimeAreaPixel (double t)
TrackSpacePixelToTimeAreaTime()
float UnityEditor.Timeline.WindowState.TrackSpacePixelToTimeAreaTime (float p)
Referenced by UnityEditor.Timeline.WindowState.ScreenSpacePixelToTimeAreaTime().
UnarmForRecord()
void UnityEditor.Timeline.WindowState.UnarmForRecord (TrackAsset track)
UpdateRecordingState()
void UnityEditor.Timeline.WindowState.UpdateRecordingState ()
UpdateRootPlayableDuration()
void UnityEditor.Timeline.WindowState.UpdateRootPlayableDuration (double duration)
Referenced by UnityEditor.Timeline.TrimClip.MouseDrag().
UpdateViewStateHash()
void UnityEditor.Timeline.WindowState.UpdateViewStateHash ()
Member Data Documentation
analytics
TimelineWindowAnalytics UnityEditor.Timeline.WindowState.analytics = new TimelineWindowAnalytics()
Referenced by UnityEditor.Timeline.WindowState.SetPlaying().
kMaxShownTime
readonly float UnityEditor.Timeline.WindowState.kMaxShownTime = (float)TimeUtility.k_MaxTimelineDurationInSeconds static
Property Documentation
allSequences
IEnumerable<ISequenceState> UnityEditor.Timeline.WindowState.allSequences get
Implements UnityEditor.Timeline.IWindowState.
autoScrollMode
PlaybackScrollMode UnityEditor.Timeline.WindowState.autoScrollMode get set
bindingAreaWidth
float UnityEditor.Timeline.WindowState.bindingAreaWidth get set
canRecord
bool UnityEditor.Timeline.WindowState.canRecord get
captured
List<Manipulator> UnityEditor.Timeline.WindowState.captured get
Referenced by UnityEditor.Timeline.EaseClip.MouseUp(), and UnityEditor.Timeline.TrimClip.MouseUp().
dirtyStamp
int UnityEditor.Timeline.WindowState.dirtyStamp get
Referenced by UnityEditor.Timeline.WindowState.Refresh().
edgeSnaps
bool UnityEditor.Timeline.WindowState.edgeSnaps get set
editorWindow
EditorWindow UnityEditor.Timeline.WindowState.editorWindow get
Referenced by UnityEditor.Timeline.TimelinePanManipulator.MouseUp().
editSequence
ISequenceState UnityEditor.Timeline.WindowState.editSequence get
Implements UnityEditor.Timeline.IWindowState.
Referenced by UnityEditor.Timeline.AnimationTrackRecorder.AddRecordableClip(), UnityEditor.Timeline.WindowState.ArmForRecord(), UnityEditor.Timeline.MarkerHeaderTrackManipulator.ContextClick(), UnityEditor.Timeline.PlayheadContextMenu.ContextClick(), UnityEditor.Timeline.WindowState.EnsurePlayHeadIsVisible(), UnityEditor.Timeline.CurveDataSource.GetBackgroundRect(), UnityEditor.Timeline.WindowState.GetSceneReference(), UnityEditor.Timeline.WindowState.GetSubSequences(), UnityEditor.Timeline.TimelineRecordingContextualResponder.IsAnimatable(), UnityEditor.Timeline.WindowState.IsCurrentEditingASequencerTextField(), UnityEditor.Timeline.WindowState.IsEditingAPrefabAsset(), UnityEditor.Timeline.WindowState.IsEditingASubTimeline(), UnityEditor.Timeline.MarkerHeaderTrackManipulator.MouseDown(), UnityEditor.Timeline.SelectAndMoveItem.MouseDrag(), UnityEditor.Timeline.TrimClip.MouseDrag(), UnityEditor.Timeline.AnimationTrackRecorder.PrepareTrack(), UnityEditor.Timeline.TimelineWindow.RebuildGraphIfNecessary(), UnityEditor.Timeline.WindowState.RebuildPlayableGraph(), UnityEditor.Timeline.WindowState.SetPlayHeadToMiddle(), UnityEditor.Timeline.SnapEngine.SnapEngine(), UnityEditor.Timeline.TimelineGroupGUI.TimelineGroupGUI(), UnityEditor.Timeline.WindowState.UnarmForRecord(), UnityEditor.Timeline.WindowState.UpdateRecordingState(), and UnityEditor.Timeline.WindowState.UpdateRootPlayableDuration().
editType
EditMode.EditType UnityEditor.Timeline.WindowState.editType get set
frameSnap
bool UnityEditor.Timeline.WindowState.frameSnap get set
headerSpacePartitioner
SpacePartitioner UnityEditor.Timeline.WindowState.headerSpacePartitioner get
Referenced by UnityEditor.Timeline.InlineCurveResizeHandle.Draw(), and UnityEditor.Timeline.TrackResizeHandle.Draw().
ignorePreview
bool UnityEditor.Timeline.WindowState.ignorePreview get
Referenced by UnityEditor.Timeline.WindowState.OnDestroy(), and UnityEditor.Timeline.TimelineWindow.RebuildGraphIfNecessary().
isJogging
bool UnityEditor.Timeline.WindowState.isJogging get set
Referenced by UnityEditor.Timeline.Jog.MouseDown(), UnityEditor.Timeline.Jog.MouseDrag(), and UnityEditor.Timeline.Jog.MouseUp().
kTimeEpsilon
double UnityEditor.Timeline.WindowState.kTimeEpsilon static get
mainAreaWidth
float UnityEditor.Timeline.WindowState.mainAreaWidth get set
masterSequence
ISequenceState UnityEditor.Timeline.WindowState.masterSequence get
Implements UnityEditor.Timeline.IWindowState.
Referenced by UnityEditor.Timeline.WindowState.Evaluate(), UnityEditor.Timeline.WindowState.EvaluateImmediate(), UnityEditor.Timeline.WindowState.IsEditingASubTimeline(), UnityEditor.Timeline.WindowState.IsPlayableGraphDone(), UnityEditor.Timeline.WindowState.Pause(), UnityEditor.Timeline.WindowState.Play(), UnityEditor.Timeline.TimelineWindow.RebuildGraphIfNecessary(), UnityEditor.Timeline.WindowState.RebuildPlayableGraph(), UnityEditor.Timeline.SnapEngine.SnapEngine(), and UnityEditor.Timeline.WindowState.Stop().
mouseDragLag
float UnityEditor.Timeline.WindowState.mouseDragLag get set
muteAudioScrubbing
bool UnityEditor.Timeline.WindowState.muteAudioScrubbing get set
Referenced by UnityEditor.Timeline.WindowState.WindowState().
playbackSpeed
float UnityEditor.Timeline.WindowState.playbackSpeed get set
playing
bool UnityEditor.Timeline.WindowState.playing get
Referenced by UnityEditor.Timeline.TimelineWindow.RebuildGraphIfNecessary(), and UnityEditor.Timeline.WindowState.SetPlaying().
playRange
Vector2 UnityEditor.Timeline.WindowState.playRange get set
Referenced by UnityEditor.Timeline.PlayheadContextMenu.ContextClick().
playRangeEnabled
bool UnityEditor.Timeline.WindowState.playRangeEnabled get set
Referenced by UnityEditor.Timeline.TimelineActiveMode.ShouldShowPlayRange(), and UnityEditor.Timeline.TimelineReadOnlyMode.ShouldShowPlayRange().
previewDriver
AnimationModeDriver UnityEditor.Timeline.WindowState.previewDriver static get
Referenced by UnityEditor.Timeline.WindowState.GatherProperties().
previewedDirectors
List<PlayableDirector> UnityEditor.Timeline.WindowState.previewedDirectors get
previewMode
bool UnityEditor.Timeline.WindowState.previewMode get set
Referenced by UnityEditor.Timeline.WindowState.Evaluate(), UnityEditor.Timeline.WindowState.EvaluateImmediate(), UnityEditor.Timeline.WindowState.GatherProperties(), UnityEditor.Timeline.WindowState.Play(), UnityEditor.Timeline.WindowState.Reset(), and UnityEditor.Timeline.WindowState.ResetPreviewMode().
rebuildGraph
bool UnityEditor.Timeline.WindowState.rebuildGraph get set
Referenced by UnityEditor.Timeline.TimelineWindow.RebuildGraphIfNecessary(), and UnityEditor.Timeline.WindowState.Refresh().
recording
bool UnityEditor.Timeline.WindowState.recording get set
Referenced by UnityEditor.Timeline.WindowState.ArmForRecord(), UnityEditor.Timeline.InfiniteTrackDrawer.DrawTrack(), UnityEditor.Timeline.WindowState.Reset(), UnityEditor.Timeline.WindowState.UnarmForRecord(), and UnityEditor.Timeline.WindowState.UpdateRecordingState().
referenceSequence
ISequenceState UnityEditor.Timeline.WindowState.referenceSequence get
Referenced by UnityEditor.Timeline.PlayheadContextMenu.ContextClick(), and UnityEditor.ClipCurveEditor.DrawCurveEditor().
sequencerHeaderWidth
float UnityEditor.Timeline.WindowState.sequencerHeaderWidth get set
Referenced by UnityEditor.Timeline.TimeAreaItem.Draw(), and UnityEditor.Timeline.WindowState.TimeToTimeAreaPixel().
showAudioWaveform
bool UnityEditor.Timeline.WindowState.showAudioWaveform get set
showMarkerHeader
bool UnityEditor.Timeline.WindowState.showMarkerHeader get set
Referenced by UnityEditor.Timeline.TimelineMarkerHeaderGUI.Draw().
showQuadTree
bool UnityEditor.Timeline.WindowState.showQuadTree get set
spacePartitioner
SpacePartitioner UnityEditor.Timeline.WindowState.spacePartitioner get
Referenced by UnityEditor.Timeline.TimelineClipHandle.Draw(), UnityEditor.Timeline.InlineCurveEditor.Draw(), UnityEditor.Timeline.TimelineMarkerHeaderGUI.Draw(), UnityEditor.Timeline.TimelineMarkerGUI.Draw(), UnityEditor.Timeline.SnapEngine.GetVisibleSnappables(), and UnityEditor.Timeline.RectangleSelect.OnFinish().
timeAreaRect
Rect UnityEditor.Timeline.WindowState.timeAreaRect get
Referenced by UnityEditor.Timeline.TimeAreaContextMenu.ContextClick(), UnityEditor.Timeline.TimelineMarkerHeaderGUI.Draw(), UnityEditor.Timeline.TimeAreaItem.Draw(), UnityEditor.Timeline.WindowState.EnsurePlayHeadIsVisible(), UnityEditor.Timeline.WindowState.PixelToTime(), UnityEditor.Timeline.WindowState.ScreenSpacePixelToTimeAreaTime(), UnityEditor.Timeline.WindowState.SetPlayHeadToMiddle(), UnityEditor.Timeline.TimeAreaItem.TimeAreaItem(), and UnityEditor.Timeline.WindowState.TimeToPixel().
timeAreaScale
Vector2 UnityEditor.Timeline.WindowState.timeAreaScale get
Referenced by UnityEditor.Timeline.TimelineClipUnion.Draw(), UnityEditor.Timeline.CurveDataSource.GetBackgroundRect(), UnityEditor.Timeline.WindowState.OffsetTimeArea(), UnityEditor.Timeline.TimelineClipGUI.RectToTimeline(), UnityEditor.Timeline.TimelineMarkerGUI.RectToTimeline(), UnityEditor.Timeline.WindowState.TimeToScreenSpacePixel(), UnityEditor.Timeline.WindowState.TimeToTimeAreaPixel(), UnityEditor.Timeline.WindowState.TrackSpacePixelToTimeAreaTime(), and UnityEditor.Timeline.WindowState.UpdateViewStateHash().
timeAreaShownRange
Vector2 UnityEditor.Timeline.WindowState.timeAreaShownRange get set
Referenced by UnityEditor.Timeline.TimelineTrackGUI.Draw(), UnityEditor.ClipCurveEditor.DrawCurveEditor(), UnityEditor.Timeline.TimelineZoomManipulator.MouseDrag(), and UnityEditor.Timeline.TimelineZoomManipulator.MouseWheel().
timeAreaTranslation
Vector2 UnityEditor.Timeline.WindowState.timeAreaTranslation get
Referenced by UnityEditor.Timeline.CurveDataSource.GetBackgroundRect(), UnityEditor.Timeline.WindowState.OffsetTimeArea(), UnityEditor.Timeline.WindowState.TimeToScreenSpacePixel(), UnityEditor.Timeline.WindowState.TrackSpacePixelToTimeAreaTime(), and UnityEditor.Timeline.WindowState.UpdateViewStateHash().
timeFormat
TimeFormat UnityEditor.Timeline.WindowState.timeFormat get set
timeReferenceMode
TimeReferenceMode UnityEditor.Timeline.WindowState.timeReferenceMode get set
trackScale
float UnityEditor.Timeline.WindowState.trackScale get set
Referenced by UnityEditor.Timeline.TrackResize.MouseDrag(), UnityEditor.Timeline.TrackZoom.MouseWheel(), and UnityEditor.Timeline.WindowState.UpdateViewStateHash().
viewStateHash
int UnityEditor.Timeline.WindowState.viewStateHash get
Referenced by UnityEditor.Timeline.WindowState.UpdateViewStateHash().
windowHeight
float UnityEditor.Timeline.WindowState.windowHeight get
Event Documentation
OnAfterSequenceChange
System.Action UnityEditor.Timeline.WindowState.OnAfterSequenceChange
Referenced by UnityEditor.Timeline.WindowState.PopSequencesUntilCount(), UnityEditor.Timeline.WindowState.SetCurrentSequence(), and UnityEditor.Timeline.WindowState.SetCurrentSequencePath().
OnBeforeSequenceChange
System.Action UnityEditor.Timeline.WindowState.OnBeforeSequenceChange
Referenced by UnityEditor.Timeline.WindowState.PopSequencesUntilCount(), UnityEditor.Timeline.WindowState.SetCurrentSequence(), and UnityEditor.Timeline.WindowState.SetCurrentSequencePath().
OnDirtyStampChange
System.Action UnityEditor.Timeline.WindowState.OnDirtyStampChange
OnPlayStateChange
Action<bool> UnityEditor.Timeline.WindowState.OnPlayStateChange
OnRebuildGraphChange
System.Action UnityEditor.Timeline.WindowState.OnRebuildGraphChange
OnRecordingChange
System.Action UnityEditor.Timeline.WindowState.OnRecordingChange
OnTimeChange
System.Action UnityEditor.Timeline.WindowState.OnTimeChange
Referenced by UnityEditor.Timeline.WindowState.InvokeTimeChangeCallback().
windowOnGuiStarted
Action<WindowState, Event> UnityEditor.Timeline.WindowState.windowOnGuiStarted
Referenced by UnityEditor.Timeline.WindowState.OnDestroy().
The documentation for this class was generated from the following file:
C:/Users/Lykos/Desktop/Projects/Capstone/VRGames/Library/PackageCache/com.unity.timeline@1.6.4/Editor/State/WindowState.cs