VRCapstoneGames: Unity.Services.Core.Threading.Internal.UnityThreadUtilsInternal Class Reference
Unity.Services.Core.Threading.Internal.UnityThreadUtilsInternal Class Reference
Static Public Member Functions
static Task PostAsync (Action action)
Create a task out of the given action that will be invoked on the Unity thread.
static Task PostAsync (Action< object > action, object state)
Create a task out of the given action that will be invoked on the Unity thread.
static Task< T > PostAsync< T > (Func< T > action)
Create a task out of the given action that will be invoked on the Unity thread.
static Task< T > PostAsync< T > (Func< object, T > action, object state)
Create a task out of the given action that will be invoked on the Unity thread.
static void Send (Action action)
Execute the given action on the Unity thread. Wait for the execution to finish before resuming this thread.
static void Send (Action< object > action, object state)
Execute the given action on the Unity thread. Wait for the execution to finish before resuming this thread.
static T Send< T > (Func< T > action)
Execute the given action on the Unity thread. Wait for the execution to finish before resuming this thread.
static T Send< T > (Func< object, T > action, object state)
Execute the given action on the Unity thread. Wait for the execution to finish before resuming this thread.
Additional Inherited Members
Properties inherited from Unity.Services.Core.Threading.Internal.IUnityThreadUtils
Member Function Documentation
PostAsync() [1/2]
static Task Unity.Services.Core.Threading.Internal.UnityThreadUtilsInternal.PostAsync (Action action) static
Create a task out of the given action that will be invoked on the Unity thread.
Parameters
action The action to invoke on the Unity thread.
Returns
Return the created task.
Implements Unity.Services.Core.Threading.Internal.IUnityThreadUtils.
Referenced by Unity.Services.Core.Threading.Internal.UnityThreadUtilsInternal.Send(), Unity.Services.Core.Threading.Internal.UnityThreadUtilsInternal.Send(), Unity.Services.Core.Threading.Internal.UnityThreadUtilsInternal.Send< T >(), and Unity.Services.Core.Threading.Internal.UnityThreadUtilsInternal.Send< T >().
PostAsync() [2/2]
static Task Unity.Services.Core.Threading.Internal.UnityThreadUtilsInternal.PostAsync (Action< object > action, object state) static
Create a task out of the given action that will be invoked on the Unity thread.
Parameters
action The action to invoke on the Unity thread. state will be passed as its argument.
state The captured state to pass to action when invoking it.
Returns
Return the created task.
Implements Unity.Services.Core.Threading.Internal.IUnityThreadUtils.
PostAsync< T >() [1/2]
static Task< T > Unity.Services.Core.Threading.Internal.UnityThreadUtilsInternal.PostAsync< T > (Func< object, T > action, object state) static
Create a task out of the given action that will be invoked on the Unity thread.
Parameters
action The action to invoke on the Unity thread. state will be passed as its argument.
state The captured state to pass to action when invoking it.
Template Parameters
T The type of the return of the invoked action. Can be any type.
Returns
Return the created task.
Implements Unity.Services.Core.Threading.Internal.IUnityThreadUtils.
PostAsync< T >() [2/2]
static Task< T > Unity.Services.Core.Threading.Internal.UnityThreadUtilsInternal.PostAsync< T > (Func< T > action) static
Create a task out of the given action that will be invoked on the Unity thread.
Parameters
action The action to invoke on the Unity thread.
Template Parameters
T The type of the return of the invoked action. Can be any type.
Returns
Return the created task.
Implements Unity.Services.Core.Threading.Internal.IUnityThreadUtils.
Send() [1/2]
static void Unity.Services.Core.Threading.Internal.UnityThreadUtilsInternal.Send (Action action) static
Execute the given action on the Unity thread. Wait for the execution to finish before resuming this thread.
Parameters
action The action to invoke on the Unity thread.
Implements Unity.Services.Core.Threading.Internal.IUnityThreadUtils.
Send() [2/2]
static void Unity.Services.Core.Threading.Internal.UnityThreadUtilsInternal.Send (Action< object > action, object state) static
Execute the given action on the Unity thread. Wait for the execution to finish before resuming this thread.
Parameters
action The action to invoke on the Unity thread. state will be passed as its argument.
state The captured state to pass to action when invoking it.
Implements Unity.Services.Core.Threading.Internal.IUnityThreadUtils.
Send< T >() [1/2]
static T Unity.Services.Core.Threading.Internal.UnityThreadUtilsInternal.Send< T > (Func< object, T > action, object state) static
Execute the given action on the Unity thread. Wait for the execution to finish before resuming this thread.
Parameters
action The action to invoke on the Unity thread. state will be passed as its argument.
state The captured state to pass to action when invoking it.
Template Parameters
T The type of the return of the invoked action. Can be any type.
Returns
Return what the action returned.
Implements Unity.Services.Core.Threading.Internal.IUnityThreadUtils.
Send< T >() [2/2]
static T Unity.Services.Core.Threading.Internal.UnityThreadUtilsInternal.Send< T > (Func< T > action) static
Execute the given action on the Unity thread. Wait for the execution to finish before resuming this thread.
Parameters
action The action to invoke on the Unity thread.
Template Parameters
T The type of the return of the invoked action. Can be any type.
Returns
Return what the action returned.
Implements Unity.Services.Core.Threading.Internal.IUnityThreadUtils.
The documentation for this class was generated from the following file:
C:/Users/Lykos/Desktop/Projects/Capstone/VRGames/Library/PackageCache/com.unity.services.core@1.4.0/Runtime/Threading/UnityThreadUtilsInternal.cs