VRGames: Oculus.Interaction.ControllerRayVisual Class Reference
Oculus.Interaction.ControllerRayVisual Class Reference
Public Member Functions
void InjectAllControllerRayVisual (RayInteractor rayInteractor, Renderer renderer, MaterialPropertyBlockEditor materialPropertyBlockEditor)
void InjectRayInteractor (RayInteractor rayInteractor)
void InjectRenderer (Renderer renderer)
void InjectMaterialPropertyBlockEditor (MaterialPropertyBlockEditor materialPropertyBlockEditor)
Protected Member Functions
virtual void Start ()
virtual void OnEnable ()
virtual void OnDisable ()
Properties
float MaxRayVisualLength [get, set]
Color HoverColor0 [get, set]
Color HoverColor1 [get, set]
Color SelectColor0 [get, set]
Color SelectColor1 [get, set]
Member Function Documentation
InjectAllControllerRayVisual()
void Oculus.Interaction.ControllerRayVisual.InjectAllControllerRayVisual (RayInteractor rayInteractor, Renderer renderer, MaterialPropertyBlockEditor materialPropertyBlockEditor)
InjectMaterialPropertyBlockEditor()
void Oculus.Interaction.ControllerRayVisual.InjectMaterialPropertyBlockEditor (MaterialPropertyBlockEditor materialPropertyBlockEditor)
Referenced by Oculus.Interaction.ControllerRayVisual.InjectAllControllerRayVisual().
InjectRayInteractor()
void Oculus.Interaction.ControllerRayVisual.InjectRayInteractor (RayInteractor rayInteractor)
Referenced by Oculus.Interaction.ControllerRayVisual.InjectAllControllerRayVisual().
InjectRenderer()
void Oculus.Interaction.ControllerRayVisual.InjectRenderer (Renderer renderer)
Referenced by Oculus.Interaction.ControllerRayVisual.InjectAllControllerRayVisual().
OnDisable()
virtual void Oculus.Interaction.ControllerRayVisual.OnDisable () protected virtual
OnEnable()
virtual void Oculus.Interaction.ControllerRayVisual.OnEnable () protected virtual
Start()
virtual void Oculus.Interaction.ControllerRayVisual.Start () protected virtual
Property Documentation
HoverColor0
Color Oculus.Interaction.ControllerRayVisual.HoverColor0 get set
HoverColor1
Color Oculus.Interaction.ControllerRayVisual.HoverColor1 get set
MaxRayVisualLength
float Oculus.Interaction.ControllerRayVisual.MaxRayVisualLength get set
SelectColor0
Color Oculus.Interaction.ControllerRayVisual.SelectColor0 get set
SelectColor1
Color Oculus.Interaction.ControllerRayVisual.SelectColor1 get set
The documentation for this class was generated from the following file:
C:/Users/Lykos/Desktop/Projects/Capstone/VRGames/Assets/ThirdParty/Oculus/Interaction/Runtime/Scripts/Interaction/Models/Ray/Visuals/ControllerRayVisual.cs