VRGames: UnityEngine.UI.CanvasUpdateRegistry Class Reference
UnityEngine.UI.CanvasUpdateRegistry Class Reference
A place where CanvasElements can register themselves for rebuilding.
Static Public Member Functions
static void RegisterCanvasElementForLayoutRebuild (ICanvasElement element)
Try and add the given element to the layout rebuild list. Will not return if successfully added.
static bool TryRegisterCanvasElementForLayoutRebuild (ICanvasElement element)
Try and add the given element to the layout rebuild list.
static void RegisterCanvasElementForGraphicRebuild (ICanvasElement element)
Try and add the given element to the rebuild list. Will not return if successfully added.
static bool TryRegisterCanvasElementForGraphicRebuild (ICanvasElement element)
Try and add the given element to the rebuild list.
static void UnRegisterCanvasElementForRebuild (ICanvasElement element)
Remove the given element from both the graphic and the layout rebuild lists.
static void DisableCanvasElementForRebuild (ICanvasElement element)
Disable the given element from both the graphic and the layout rebuild lists.
static bool IsRebuildingLayout ()
Are graphics layouts currently being calculated..
static bool IsRebuildingGraphics ()
Are graphics currently being rebuild.
Protected Member Functions
CanvasUpdateRegistry ()
Properties
static CanvasUpdateRegistry instance [get]
Get the singleton registry instance.
Detailed Description
A place where CanvasElements can register themselves for rebuilding.
Constructor & Destructor Documentation
CanvasUpdateRegistry()
UnityEngine.UI.CanvasUpdateRegistry.CanvasUpdateRegistry () protected
Member Function Documentation
DisableCanvasElementForRebuild()
static void UnityEngine.UI.CanvasUpdateRegistry.DisableCanvasElementForRebuild (ICanvasElement element) static
Disable the given element from both the graphic and the layout rebuild lists.
Parameters
element
IsRebuildingGraphics()
static bool UnityEngine.UI.CanvasUpdateRegistry.IsRebuildingGraphics () static
Are graphics currently being rebuild.
Returns
True if the rebuild loop is CanvasUpdate.PreRender or CanvasUpdate.Render
Referenced by UnityEngine.UI.Text.FontTextureChanged(), TMPro.TextMeshProUGUI.SetMaterialDirty(), and TMPro.TextMeshProUGUI.SetVerticesDirty().
IsRebuildingLayout()
static bool UnityEngine.UI.CanvasUpdateRegistry.IsRebuildingLayout () static
Are graphics layouts currently being calculated..
Returns
True if the rebuild loop is CanvasUpdate.Prelayout, CanvasUpdate.Layout or CanvasUpdate.Postlayout
Referenced by UnityEngine.UI.Text.FontTextureChanged(), and UnityEngine.UI.LayoutGroup.SetDirty().
RegisterCanvasElementForGraphicRebuild()
static void UnityEngine.UI.CanvasUpdateRegistry.RegisterCanvasElementForGraphicRebuild (ICanvasElement element) static
Try and add the given element to the rebuild list. Will not return if successfully added.
Parameters
element The element that is needing rebuilt.
Referenced by TMPro.TMP_SelectionCaret.Cull(), TMPro.TextMeshProUGUI.SetMaterialDirty(), and TMPro.TextMeshProUGUI.SetVerticesDirty().
RegisterCanvasElementForLayoutRebuild()
static void UnityEngine.UI.CanvasUpdateRegistry.RegisterCanvasElementForLayoutRebuild (ICanvasElement element) static
Try and add the given element to the layout rebuild list. Will not return if successfully added.
Parameters
element The element that is needing rebuilt.
TryRegisterCanvasElementForGraphicRebuild()
static bool UnityEngine.UI.CanvasUpdateRegistry.TryRegisterCanvasElementForGraphicRebuild (ICanvasElement element) static
Try and add the given element to the rebuild list.
Parameters
element The element that is needing rebuilt.
Returns
True if the element was successfully added to the rebuilt list. False if either already inside a Graphic Update loop OR has already been added to the list.
TryRegisterCanvasElementForLayoutRebuild()
static bool UnityEngine.UI.CanvasUpdateRegistry.TryRegisterCanvasElementForLayoutRebuild (ICanvasElement element) static
Try and add the given element to the layout rebuild list.
Parameters
element The element that is needing rebuilt.
Returns
True if the element was successfully added to the rebuilt list. False if either already inside a Graphic Update loop OR has already been added to the list.
UnRegisterCanvasElementForRebuild()
static void UnityEngine.UI.CanvasUpdateRegistry.UnRegisterCanvasElementForRebuild (ICanvasElement element) static
Remove the given element from both the graphic and the layout rebuild lists.
Parameters
element
Referenced by TMPro.TMP_InputField.OnDisable(), and TMPro.TextMeshProUGUI.OnDisable().
Property Documentation
instance
CanvasUpdateRegistry UnityEngine.UI.CanvasUpdateRegistry.instance static get
Get the singleton registry instance.
Referenced by UnityEngine.UI.CanvasUpdateRegistry.DisableCanvasElementForRebuild(), UnityEngine.UI.CanvasUpdateRegistry.IsRebuildingGraphics(), UnityEngine.UI.CanvasUpdateRegistry.IsRebuildingLayout(), UnityEngine.UI.CanvasUpdateRegistry.RegisterCanvasElementForGraphicRebuild(), UnityEngine.UI.CanvasUpdateRegistry.RegisterCanvasElementForLayoutRebuild(), UnityEngine.UI.CanvasUpdateRegistry.TryRegisterCanvasElementForGraphicRebuild(), UnityEngine.UI.CanvasUpdateRegistry.TryRegisterCanvasElementForLayoutRebuild(), and UnityEngine.UI.CanvasUpdateRegistry.UnRegisterCanvasElementForRebuild().
The documentation for this class was generated from the following file:
C:/Users/Lykos/Desktop/Projects/Capstone/VRGames/Library/PackageCache/com.unity.ugui@1.0.0/Runtime/UI/Core/CanvasUpdateRegistry.cs