VRCapstoneGames: Oculus.Interaction.GrabAPI.HandGrabAPI Class Reference
Oculus.Interaction.GrabAPI.HandGrabAPI Class Reference
Public Member Functions
HandFingerFlags HandPinchGrabbingFingers ()
HandFingerFlags HandPalmGrabbingFingers ()
bool IsHandPinchGrabbing (in GrabbingRule fingers)
bool IsHandPalmGrabbing (in GrabbingRule fingers)
bool IsSustainingGrab (in GrabbingRule fingers, HandFingerFlags grabbingFingers)
bool IsHandSelectPinchFingersChanged (in GrabbingRule fingers)
Determine whether the state of any of the finger pinches have changed this frame to the target pinching state (on/off).
bool IsHandSelectPalmFingersChanged (in GrabbingRule fingers)
Determine whether the state of any of the finger grabs have changed this frame to the target grabbing state (on/off).
bool IsHandUnselectPinchFingersChanged (in GrabbingRule fingers)
bool IsHandUnselectPalmFingersChanged (in GrabbingRule fingers)
Vector3 GetPinchCenter ()
Vector3 GetPalmCenter ()
float GetHandPinchStrength (in GrabbingRule fingers, bool includePinching=true)
float GetHandPalmStrength (in GrabbingRule fingers, bool includeGrabbing=true)
float GetFingerPinchStrength (HandFinger finger)
float GetFingerPalmStrength (HandFinger finger)
void InjectAllHandGrabAPI (IHand hand)
void InjectHand (IHand hand)
void InjectOptionalFingerPinchAPI (IFingerAPI fingerPinchAPI)
void InjectOptionalFingerGrabAPI (IFingerAPI fingerGrabAPI)
Protected Member Functions
virtual void Awake ()
virtual void Start ()
Properties
IHand Hand [get]
Member Function Documentation
Awake()
virtual void Oculus.Interaction.GrabAPI.HandGrabAPI.Awake () protected virtual
GetFingerPalmStrength()
float Oculus.Interaction.GrabAPI.HandGrabAPI.GetFingerPalmStrength (HandFinger finger)
GetFingerPinchStrength()
float Oculus.Interaction.GrabAPI.HandGrabAPI.GetFingerPinchStrength (HandFinger finger)
GetHandPalmStrength()
float Oculus.Interaction.GrabAPI.HandGrabAPI.GetHandPalmStrength (in GrabbingRule fingers, bool includeGrabbing = true)
GetHandPinchStrength()
float Oculus.Interaction.GrabAPI.HandGrabAPI.GetHandPinchStrength (in GrabbingRule fingers, bool includePinching = true)
GetPalmCenter()
Vector3 Oculus.Interaction.GrabAPI.HandGrabAPI.GetPalmCenter ()
GetPinchCenter()
Vector3 Oculus.Interaction.GrabAPI.HandGrabAPI.GetPinchCenter ()
HandPalmGrabbingFingers()
HandFingerFlags Oculus.Interaction.GrabAPI.HandGrabAPI.HandPalmGrabbingFingers ()
Referenced by Oculus.Interaction.GrabAPI.HandGrabAPI.IsHandPalmGrabbing().
HandPinchGrabbingFingers()
HandFingerFlags Oculus.Interaction.GrabAPI.HandGrabAPI.HandPinchGrabbingFingers ()
Referenced by Oculus.Interaction.GrabAPI.HandGrabAPI.IsHandPinchGrabbing().
InjectAllHandGrabAPI()
void Oculus.Interaction.GrabAPI.HandGrabAPI.InjectAllHandGrabAPI (IHand hand)
InjectHand()
void Oculus.Interaction.GrabAPI.HandGrabAPI.InjectHand (IHand hand)
Referenced by Oculus.Interaction.GrabAPI.HandGrabAPI.InjectAllHandGrabAPI().
InjectOptionalFingerGrabAPI()
void Oculus.Interaction.GrabAPI.HandGrabAPI.InjectOptionalFingerGrabAPI (IFingerAPI fingerGrabAPI)
InjectOptionalFingerPinchAPI()
void Oculus.Interaction.GrabAPI.HandGrabAPI.InjectOptionalFingerPinchAPI (IFingerAPI fingerPinchAPI)
Referenced by Oculus.Interaction.GrabAPI.FingerRawPinchInjector.Awake().
IsHandPalmGrabbing()
bool Oculus.Interaction.GrabAPI.HandGrabAPI.IsHandPalmGrabbing (in GrabbingRule fingers)
IsHandPinchGrabbing()
bool Oculus.Interaction.GrabAPI.HandGrabAPI.IsHandPinchGrabbing (in GrabbingRule fingers)
IsHandSelectPalmFingersChanged()
bool Oculus.Interaction.GrabAPI.HandGrabAPI.IsHandSelectPalmFingersChanged (in GrabbingRule fingers)
Determine whether the state of any of the finger grabs have changed this frame to the target grabbing state (on/off).
Parameters
fingers Finger rules to check.
IsHandSelectPinchFingersChanged()
bool Oculus.Interaction.GrabAPI.HandGrabAPI.IsHandSelectPinchFingersChanged (in GrabbingRule fingers)
Determine whether the state of any of the finger pinches have changed this frame to the target pinching state (on/off).
Parameters
fingers Finger rules to check.
IsHandUnselectPalmFingersChanged()
bool Oculus.Interaction.GrabAPI.HandGrabAPI.IsHandUnselectPalmFingersChanged (in GrabbingRule fingers)
IsHandUnselectPinchFingersChanged()
bool Oculus.Interaction.GrabAPI.HandGrabAPI.IsHandUnselectPinchFingersChanged (in GrabbingRule fingers)
IsSustainingGrab()
bool Oculus.Interaction.GrabAPI.HandGrabAPI.IsSustainingGrab (in GrabbingRule fingers, HandFingerFlags grabbingFingers)
Referenced by Oculus.Interaction.GrabAPI.HandGrabAPI.IsHandPalmGrabbing(), and Oculus.Interaction.GrabAPI.HandGrabAPI.IsHandPinchGrabbing().
Start()
virtual void Oculus.Interaction.GrabAPI.HandGrabAPI.Start () protected virtual
Property Documentation
Hand
IHand Oculus.Interaction.GrabAPI.HandGrabAPI.Hand get
The documentation for this class was generated from the following file:
C:/Users/Lykos/Desktop/Projects/Capstone/VRGames/Assets/ThirdParty/Oculus/Interaction/Runtime/Scripts/Grab/HandGrabAPI.cs