VRGames: Oculus.Interaction.IInteractableRegistry< TInteractor, TInteractable > Interface Template Reference
Oculus.Interaction.IInteractableRegistry< TInteractor, TInteractable > Interface Template Reference
A interface for a registry that houses a set of concrete Interactables.
Public Member Functions
void Register (TInteractable interactable)
void Unregister (TInteractable interactable)
IEnumerable< TInteractable > List ()
IEnumerable< TInteractable > List (TInteractor interactor)
Detailed Description
A interface for a registry that houses a set of concrete Interactables.
Type Constraints
TInteractable : IInteractable<TInteractor>
Member Function Documentation
List() [1/2]
IEnumerable< TInteractable > Oculus.Interaction.IInteractableRegistry< TInteractor, TInteractable >.List ()
Implemented in Oculus.Interaction.InteractableRegistry< TInteractor, TInteractable >.
Referenced by Oculus.Interaction.Interactable< TInteractor, TInteractable >.SetRegistry().
List() [2/2]
IEnumerable< TInteractable > Oculus.Interaction.IInteractableRegistry< TInteractor, TInteractable >.List (TInteractor interactor)
Implemented in Oculus.Interaction.CollisionInteractionRegistry< TInteractor, TInteractable >, and Oculus.Interaction.InteractableRegistry< TInteractor, TInteractable >.
Register()
void Oculus.Interaction.IInteractableRegistry< TInteractor, TInteractable >.Register (TInteractable interactable)
Implemented in Oculus.Interaction.CollisionInteractionRegistry< TInteractor, TInteractable >, and Oculus.Interaction.InteractableRegistry< TInteractor, TInteractable >.
Referenced by Oculus.Interaction.Interactable< TInteractor, TInteractable >.Enable().
Unregister()
void Oculus.Interaction.IInteractableRegistry< TInteractor, TInteractable >.Unregister (TInteractable interactable)
Implemented in Oculus.Interaction.CollisionInteractionRegistry< TInteractor, TInteractable >, and Oculus.Interaction.InteractableRegistry< TInteractor, TInteractable >.
Referenced by Oculus.Interaction.Interactable< TInteractor, TInteractable >.Disable(), and Oculus.Interaction.Interactable< TInteractor, TInteractable >.SetRegistry().
The documentation for this interface was generated from the following file:
C:/Users/Lykos/Desktop/Projects/Capstone/VRGames/Assets/ThirdParty/Oculus/Interaction/Runtime/Scripts/Interaction/Core/IInteractableRegistry.cs