VRGames: UnityEditor.Timeline.IZOrderProvider Interface Reference
UnityEditor.Timeline.IZOrderProvider Interface Reference
Public Member Functions
LayerZOrder Next ()
Member Function Documentation
Next()
LayerZOrder UnityEditor.Timeline.IZOrderProvider.Next ()
Implemented in UnityEditor.Timeline.ItemsLayer< T >.
Referenced by UnityEditor.Timeline.TimelineMarkerGUI.Select(), UnityEditor.Timeline.TimelineClipGUI.TimelineClipGUI(), and UnityEditor.Timeline.TimelineMarkerGUI.TimelineMarkerGUI().
The documentation for this interface was generated from the following file:
C:/Users/Lykos/Desktop/Projects/Capstone/VRGames/Library/PackageCache/com.unity.timeline@1.6.4/Editor/treeview/Drawers/Layers/ItemsLayer.cs