VRCapstoneGames: Oculus.Interaction.Input.ITrackingToWorldTransformer Interface Reference
Oculus.Interaction.Input.ITrackingToWorldTransformer Interface Reference
Public Member Functions
Pose ToWorldPose (Pose poseRh)
Converts a tracking space pose to a pose in in Unity's world coordinate space (i.e. teleportation applied)
Pose ToTrackingPose (in Pose worldPose)
Converts a world space pose in Unity's coordinate space to a pose in tracking space (i.e. no teleportation applied)
Properties
Transform Transform [get]
Quaternion WorldToTrackingWristJointFixup [get]
Member Function Documentation
ToTrackingPose()
Pose Oculus.Interaction.Input.ITrackingToWorldTransformer.ToTrackingPose (in Pose worldPose)
Converts a world space pose in Unity's coordinate space to a pose in tracking space (i.e. no teleportation applied)
Implemented in Oculus.Interaction.Input.TrackingToWorldTransformerOVR.
Referenced by Oculus.Interaction.Input.SyntheticHand.LockWristPose().
ToWorldPose()
Pose Oculus.Interaction.Input.ITrackingToWorldTransformer.ToWorldPose (Pose poseRh)
Converts a tracking space pose to a pose in in Unity's world coordinate space (i.e. teleportation applied)
Implemented in Oculus.Interaction.Input.TrackingToWorldTransformerOVR.
Referenced by Oculus.Interaction.Input.Hand.GetCenterEyePose(), and Oculus.Interaction.Input.Hmd.GetRootPose().
Property Documentation
Transform
Transform Oculus.Interaction.Input.ITrackingToWorldTransformer.Transform get
Implemented in Oculus.Interaction.Input.TrackingToWorldTransformerOVR.
WorldToTrackingWristJointFixup
Quaternion Oculus.Interaction.Input.ITrackingToWorldTransformer.WorldToTrackingWristJointFixup get
Implemented in Oculus.Interaction.Input.TrackingToWorldTransformerOVR.
The documentation for this interface was generated from the following file:
C:/Users/Lykos/Desktop/Projects/Capstone/VRGames/Assets/ThirdParty/Oculus/Interaction/Runtime/Scripts/Input/ITrackingToWorldTransformer.cs