VRCapstoneGames: UnityEngine.XR.Interaction.Toolkit.IXRHoverInteractor Interface Reference
UnityEngine.XR.Interaction.Toolkit.IXRHoverInteractor Interface Reference
An interface that represents an Interactor component that can hover over an Interactable component.
Public Member Functions
bool CanHover (IXRHoverInteractable interactable)
Determines if the Interactable is valid for hover this frame.
bool IsHovering (IXRHoverInteractable interactable)
Determines whether this Interactor is currently hovering the Interactable.
void OnHoverEntering (HoverEnterEventArgs args)
The XRInteractionManager calls this method right before the Interactor first initiates hovering over an Interactable in a first pass.
void OnHoverEntered (HoverEnterEventArgs args)
The XRInteractionManager calls this method when the Interactor first initiates hovering over an Interactable in a second pass.
void OnHoverExiting (HoverExitEventArgs args)
The XRInteractionManager calls this method right before the Interactor ends hovering over an Interactable in a first pass.
void OnHoverExited (HoverExitEventArgs args)
The XRInteractionManager calls this method when the Interactor ends hovering over an Interactable in a second pass.
Public Member Functions inherited from UnityEngine.XR.Interaction.Toolkit.IXRInteractor
Transform GetAttachTransform (IXRInteractable interactable)
Gets the Transform that is used as the attachment point for a given Interactable.
void GetValidTargets (List< IXRInteractable > targets)
Retrieve the list of Interactables that this Interactor could possibly interact with this frame. This list is sorted by priority (with highest priority first).
void OnRegistered (InteractorRegisteredEventArgs args)
The XRInteractionManager calls this method when this Interactor is registered with it.
void OnUnregistered (InteractorUnregisteredEventArgs args)
The XRInteractionManager calls this method when this Interactor is unregistered from it.
void PreprocessInteractor (XRInteractionUpdateOrder.UpdatePhase updatePhase)
The XRInteractionManager calls this method to update the Interactor before interaction events occur. Interactors should use this method to do tasks like determine their valid targets.
void ProcessInteractor (XRInteractionUpdateOrder.UpdatePhase updatePhase)
The XRInteractionManager calls this method to update the Interactor after interaction events occur.
Properties
HoverEnterEvent hoverEntered [get]
The event that is called when this Interactor begins hovering over an Interactable.
HoverExitEvent hoverExited [get]
The event that is called when this Interactor ends hovering over an Interactable.
List< IXRHoverInteractable > interactablesHovered [get]
(Read Only) The list of Interactables that are currently being hovered over (may by empty).
bool hasHover [get]
(Read Only) Indicates whether this Interactor is currently hovering an Interactable.
bool isHoverActive [get]
(Read Only) Indicates whether this Interactor is in a state where it could hover.
Properties inherited from UnityEngine.XR.Interaction.Toolkit.IXRInteractor
InteractionLayerMask interactionLayers [get]
(Read Only) Allows interaction with Interactables whose Interaction Layer Mask overlaps with any Layer in this Interaction Layer Mask.
Transform transform [get]
(Read Only) The Transform associated with the Interactor.
Additional Inherited Members
Events inherited from UnityEngine.XR.Interaction.Toolkit.IXRInteractor
Action< InteractorRegisteredEventArgs > registered
Calls the methods in its invocation list when this Interactor is registered with an Interaction Manager.
Action< InteractorUnregisteredEventArgs > unregistered
Calls the methods in its invocation list when this Interactor is unregistered from an Interaction Manager.
Detailed Description
An interface that represents an Interactor component that can hover over an Interactable component.
See also
IXRHoverInteractable
Member Function Documentation
CanHover()
bool UnityEngine.XR.Interaction.Toolkit.IXRHoverInteractor.CanHover (IXRHoverInteractable interactable)
Determines if the Interactable is valid for hover this frame.
Parameters
interactable Interactable to check.
Returns
Returns true if the interactable can be hovered over this frame.
See also
IXRHoverInteractable.IsHoverableBy
Implemented in UnityEngine.XR.Interaction.Toolkit.XRBaseInteractor, UnityEngine.XR.Interaction.Toolkit.XRDirectInteractor, UnityEngine.XR.Interaction.Toolkit.XRRayInteractor, and UnityEngine.XR.Interaction.Toolkit.XRSocketInteractor.
Referenced by UnityEngine.XR.Interaction.Toolkit.XRInteractionManager.ClearInteractorHover().
IsHovering()
bool UnityEngine.XR.Interaction.Toolkit.IXRHoverInteractor.IsHovering (IXRHoverInteractable interactable)
Determines whether this Interactor is currently hovering the Interactable.
Parameters
interactable Interactable to check.
Returns
Returns true if this Interactor is currently hovering the Interactable. Otherwise, returns .
In other words, returns whether interactablesHovered contains interactable .
See also
interactablesHovered
Implemented in UnityEngine.XR.Interaction.Toolkit.XRBaseInteractor.
OnHoverEntered()
void UnityEngine.XR.Interaction.Toolkit.IXRHoverInteractor.OnHoverEntered (HoverEnterEventArgs args)
The XRInteractionManager calls this method when the Interactor first initiates hovering over an Interactable in a second pass.
Parameters
args Event data containing the Interactable that is being hovered over.
args is only valid during this method call, do not hold a reference to it.
See also
OnHoverExited(HoverExitEventArgs)
Implemented in UnityEngine.XR.Interaction.Toolkit.XRBaseInteractor.
Referenced by UnityEngine.XR.Interaction.Toolkit.XRInteractionManager.HoverEnter().
OnHoverEntering()
void UnityEngine.XR.Interaction.Toolkit.IXRHoverInteractor.OnHoverEntering (HoverEnterEventArgs args)
The XRInteractionManager calls this method right before the Interactor first initiates hovering over an Interactable in a first pass.
Parameters
args Event data containing the Interactable that is being hovered over.
args is only valid during this method call, do not hold a reference to it.
See also
OnHoverEntered(HoverEnterEventArgs)
Implemented in UnityEngine.XR.Interaction.Toolkit.XRBaseControllerInteractor, UnityEngine.XR.Interaction.Toolkit.XRBaseInteractor, and UnityEngine.XR.Interaction.Toolkit.XRSocketInteractor.
Referenced by UnityEngine.XR.Interaction.Toolkit.XRInteractionManager.HoverEnter().
OnHoverExited()
void UnityEngine.XR.Interaction.Toolkit.IXRHoverInteractor.OnHoverExited (HoverExitEventArgs args)
The XRInteractionManager calls this method when the Interactor ends hovering over an Interactable in a second pass.
Parameters
args Event data containing the Interactable that is no longer hovered over.
args is only valid during this method call, do not hold a reference to it.
See also
OnHoverEntered(HoverEnterEventArgs)
Implemented in UnityEngine.XR.Interaction.Toolkit.XRBaseInteractor.
Referenced by UnityEngine.XR.Interaction.Toolkit.XRInteractionManager.HoverExit().
OnHoverExiting()
void UnityEngine.XR.Interaction.Toolkit.IXRHoverInteractor.OnHoverExiting (HoverExitEventArgs args)
The XRInteractionManager calls this method right before the Interactor ends hovering over an Interactable in a first pass.
Parameters
args Event data containing the Interactable that is no longer hovered over.
args is only valid during this method call, do not hold a reference to it.
See also
OnHoverExited(HoverExitEventArgs)
Implemented in UnityEngine.XR.Interaction.Toolkit.XRBaseControllerInteractor, UnityEngine.XR.Interaction.Toolkit.XRBaseInteractor, and UnityEngine.XR.Interaction.Toolkit.XRSocketInteractor.
Referenced by UnityEngine.XR.Interaction.Toolkit.XRInteractionManager.HoverExit().
Property Documentation
hasHover
bool UnityEngine.XR.Interaction.Toolkit.IXRHoverInteractor.hasHover get
(Read Only) Indicates whether this Interactor is currently hovering an Interactable.
In other words, returns whether interactablesHovered contains any Interactables.
interactablesHovered.Count > 0
See also
interactablesHovered, IXRHoverInteractable.isHovered
Implemented in UnityEngine.XR.Interaction.Toolkit.XRBaseInteractor.
hoverEntered
HoverEnterEvent UnityEngine.XR.Interaction.Toolkit.IXRHoverInteractor.hoverEntered get
The event that is called when this Interactor begins hovering over an Interactable.
The HoverEnterEventArgs passed to each listener is only valid while the event is invoked, do not hold a reference to it.
See also
hoverExited
Implemented in UnityEngine.XR.Interaction.Toolkit.XRBaseInteractor.
hoverExited
HoverExitEvent UnityEngine.XR.Interaction.Toolkit.IXRHoverInteractor.hoverExited get
The event that is called when this Interactor ends hovering over an Interactable.
The HoverExitEventArgs passed to each listener is only valid while the event is invoked, do not hold a reference to it.
See also
hoverEntered
Implemented in UnityEngine.XR.Interaction.Toolkit.XRBaseInteractor.
interactablesHovered
List<IXRHoverInteractable> UnityEngine.XR.Interaction.Toolkit.IXRHoverInteractor.interactablesHovered get
(Read Only) The list of Interactables that are currently being hovered over (may by empty).
You should treat this as a read only view of the list and should not modify it. It is exposed as a List<T> rather than an IReadOnlyList<T> to avoid GC Allocations when enumerating the list.
See also
hasHover, IXRHoverInteractable.interactorsHovering
Implemented in UnityEngine.XR.Interaction.Toolkit.XRBaseInteractor.
Referenced by UnityEngine.XR.Interaction.Toolkit.XRInteractionManager.CancelInteractorHover(), and UnityEngine.XR.Interaction.Toolkit.XRInteractionManager.ClearInteractorHover().
isHoverActive
bool UnityEngine.XR.Interaction.Toolkit.IXRHoverInteractor.isHoverActive get
(Read Only) Indicates whether this Interactor is in a state where it could hover.
Implemented in UnityEngine.XR.Interaction.Toolkit.XRBaseInteractor, and UnityEngine.XR.Interaction.Toolkit.XRSocketInteractor.
Referenced by UnityEngine.XR.Interaction.Toolkit.XRInteractionManager.ClearInteractorHover().
The documentation for this interface was generated from the following file:
C:/Users/Lykos/Desktop/Projects/Capstone/VRGames/Library/PackageCache/com.unity.xr.interaction.toolkit@2.0.2/Runtime/Interaction/Interactors/IXRHoverInteractor.cs