VRCapstoneGames: SimpleControls.IGameplayActions Interface Reference
SimpleControls.IGameplayActions Interface Reference
Public Member Functions
void OnFire (InputAction.CallbackContext context)
void OnMove (InputAction.CallbackContext context)
void OnLook (InputAction.CallbackContext context)
Member Function Documentation
OnFire()
void SimpleControls.IGameplayActions.OnFire (InputAction.CallbackContext context)
Referenced by SimpleControls.GameplayActions.SetCallbacks().
OnLook()
void SimpleControls.IGameplayActions.OnLook (InputAction.CallbackContext context)
Referenced by SimpleControls.GameplayActions.SetCallbacks().
OnMove()
void SimpleControls.IGameplayActions.OnMove (InputAction.CallbackContext context)
Referenced by SimpleControls.GameplayActions.SetCallbacks().
The documentation for this interface was generated from the following file:
C:/Users/Lykos/Desktop/Projects/Capstone/VRGames/Library/PackageCache/com.unity.inputsystem@1.3.0/Samples~/SimpleDemo/SimpleControls.cs