VRCapstoneGames: UnityEngine.XR.Interaction.Toolkit.IXRHoverInteractable Interface Reference
UnityEngine.XR.Interaction.Toolkit.IXRHoverInteractable Interface Reference
An interface that represents an Interactable component which Interactor components can hover over.
Public Member Functions
bool IsHoverableBy (IXRHoverInteractor interactor)
Determines if a given Interactor can hover over this Interactable.
void OnHoverEntering (HoverEnterEventArgs args)
The XRInteractionManager calls this method right before the Interactor first initiates hovering over an Interactable in a first pass.
void OnHoverEntered (HoverEnterEventArgs args)
The XRInteractionManager calls this method when the Interactor first initiates hovering over an Interactable in a second pass.
void OnHoverExiting (HoverExitEventArgs args)
The XRInteractionManager calls this method right before the Interactor ends hovering over an Interactable in a first pass.
void OnHoverExited (HoverExitEventArgs args)
The XRInteractionManager calls this method when the Interactor ends hovering over an Interactable in a second pass.
Public Member Functions inherited from UnityEngine.XR.Interaction.Toolkit.IXRInteractable
Transform GetAttachTransform (IXRInteractor interactor)
Gets the Transform that serves as the attachment point for a given Interactor.
void OnRegistered (InteractableRegisteredEventArgs args)
The XRInteractionManager calls this method when this Interactable is registered with it.
void OnUnregistered (InteractableUnregisteredEventArgs args)
The XRInteractionManager calls this method when this Interactable is unregistered from it.
void ProcessInteractable (XRInteractionUpdateOrder.UpdatePhase updatePhase)
The XRInteractionManager calls this method to update the Interactable.
float GetDistanceSqrToInteractor (IXRInteractor interactor)
Calculates squared distance to an Interactor (based on colliders).
Properties
HoverEnterEvent firstHoverEntered [get]
The event that is called only when the first Interactor begins hovering over this Interactable as the sole hovering Interactor. Subsequent Interactors that begin hovering over this Interactable will not cause this event to be invoked as long as any others are still hovering.
HoverExitEvent lastHoverExited [get]
The event that is called only when the last remaining hovering Interactor ends hovering over this Interactable.
HoverEnterEvent hoverEntered [get]
The event that is called when an Interactor begins hovering over this Interactable.
HoverExitEvent hoverExited [get]
The event that is called when an Interactor ends hovering over this Interactable.
List< IXRHoverInteractor > interactorsHovering [get]
(Read Only) The list of Interactors that are hovering on this Interactable (may by empty).
bool isHovered [get]
(Read Only) Indicates whether an Interactor currently hovers over this Interactable.
Properties inherited from UnityEngine.XR.Interaction.Toolkit.IXRInteractable
InteractionLayerMask interactionLayers [get]
(Read Only) Allows interaction with Interactors whose Interaction Layer Mask overlaps with any Layer in this Interaction Layer Mask.
List< Collider > colliders [get]
(Read Only) Colliders to use for interaction with this Interactable.
Transform transform [get]
(Read Only) The Transform associated with the Interactable.
Additional Inherited Members
Events inherited from UnityEngine.XR.Interaction.Toolkit.IXRInteractable
Action< InteractableRegisteredEventArgs > registered
Unity calls the methods in this invocation list when this Interactable is registered with an XRInteractionManager.
Action< InteractableUnregisteredEventArgs > unregistered
Unity calls the methods in this invocation list when this Interactable is unregistered from an XRInteractionManager.
Detailed Description
An interface that represents an Interactable component which Interactor components can hover over.
See also
IXRHoverInteractor
Member Function Documentation
IsHoverableBy()
bool UnityEngine.XR.Interaction.Toolkit.IXRHoverInteractable.IsHoverableBy (IXRHoverInteractor interactor)
Determines if a given Interactor can hover over this Interactable.
Parameters
interactor Interactor to check for a valid hover state with.
Returns
Returns true if hovering is valid this frame. Returns false if not.
See also
IXRHoverInteractor.CanHover
Implemented in UnityEngine.XR.Interaction.Toolkit.XRBaseInteractable.
OnHoverEntered()
void UnityEngine.XR.Interaction.Toolkit.IXRHoverInteractable.OnHoverEntered (HoverEnterEventArgs args)
The XRInteractionManager calls this method when the Interactor first initiates hovering over an Interactable in a second pass.
Parameters
args Event data containing the Interactor that is initiating the hover.
args is only valid during this method call, do not hold a reference to it.
See also
OnHoverExited(HoverExitEventArgs)
Implemented in UnityEngine.XR.Interaction.Toolkit.XRBaseInteractable.
Referenced by UnityEngine.XR.Interaction.Toolkit.XRInteractionManager.HoverEnter().
OnHoverEntering()
void UnityEngine.XR.Interaction.Toolkit.IXRHoverInteractable.OnHoverEntering (HoverEnterEventArgs args)
The XRInteractionManager calls this method right before the Interactor first initiates hovering over an Interactable in a first pass.
Parameters
args Event data containing the Interactor that is initiating the hover.
args is only valid during this method call, do not hold a reference to it.
See also
OnHoverEntered(HoverEnterEventArgs)
Implemented in UnityEngine.XR.Interaction.Toolkit.XRBaseInteractable.
Referenced by UnityEngine.XR.Interaction.Toolkit.XRInteractionManager.HoverEnter().
OnHoverExited()
void UnityEngine.XR.Interaction.Toolkit.IXRHoverInteractable.OnHoverExited (HoverExitEventArgs args)
The XRInteractionManager calls this method when the Interactor ends hovering over an Interactable in a second pass.
Parameters
args Event data containing the Interactor that is ending the hover.
args is only valid during this method call, do not hold a reference to it.
See also
OnHoverEntered(HoverEnterEventArgs)
Implemented in UnityEngine.XR.Interaction.Toolkit.XRBaseInteractable.
Referenced by UnityEngine.XR.Interaction.Toolkit.XRInteractionManager.HoverExit().
OnHoverExiting()
void UnityEngine.XR.Interaction.Toolkit.IXRHoverInteractable.OnHoverExiting (HoverExitEventArgs args)
The XRInteractionManager calls this method right before the Interactor ends hovering over an Interactable in a first pass.
Parameters
args Event data containing the Interactor that is ending the hover.
args is only valid during this method call, do not hold a reference to it.
See also
OnHoverExited(HoverExitEventArgs)
Implemented in UnityEngine.XR.Interaction.Toolkit.XRBaseInteractable.
Referenced by UnityEngine.XR.Interaction.Toolkit.XRInteractionManager.HoverExit().
Property Documentation
firstHoverEntered
HoverEnterEvent UnityEngine.XR.Interaction.Toolkit.IXRHoverInteractable.firstHoverEntered get
The event that is called only when the first Interactor begins hovering over this Interactable as the sole hovering Interactor. Subsequent Interactors that begin hovering over this Interactable will not cause this event to be invoked as long as any others are still hovering.
The HoverEnterEventArgs passed to each listener is only valid while the event is invoked, do not hold a reference to it.
See also
lastHoverExited, hoverEntered
Implemented in UnityEngine.XR.Interaction.Toolkit.XRBaseInteractable.
Referenced by UnityEngine.XR.Interaction.Toolkit.XRTintInteractableVisual.Awake(), and UnityEngine.XR.Interaction.Toolkit.XRTintInteractableVisual.OnDestroy().
hoverEntered
HoverEnterEvent UnityEngine.XR.Interaction.Toolkit.IXRHoverInteractable.hoverEntered get
The event that is called when an Interactor begins hovering over this Interactable.
The HoverEnterEventArgs passed to each listener is only valid while the event is invoked, do not hold a reference to it.
See also
hoverExited
Implemented in UnityEngine.XR.Interaction.Toolkit.XRBaseInteractable.
Referenced by UnityEngine.XR.Interaction.Toolkit.Tests.InteractionManagerTests.NestedHoverEnterEventHasCorrectEventArgs().
hoverExited
HoverExitEvent UnityEngine.XR.Interaction.Toolkit.IXRHoverInteractable.hoverExited get
The event that is called when an Interactor ends hovering over this Interactable.
The HoverExitEventArgs passed to each listener is only valid while the event is invoked, do not hold a reference to it.
See also
hoverEntered
Implemented in UnityEngine.XR.Interaction.Toolkit.XRBaseInteractable.
Referenced by UnityEngine.XR.Interaction.Toolkit.Tests.InteractionManagerTests.NestedHoverExitEventHasCorrectEventArgs().
interactorsHovering
List<IXRHoverInteractor> UnityEngine.XR.Interaction.Toolkit.IXRHoverInteractable.interactorsHovering get
(Read Only) The list of Interactors that are hovering on this Interactable (may by empty).
You should treat this as a read only view of the list and should not modify it. Unity exposes this as a List<T> rather than an IReadOnlyList<T> to avoid GC Allocations when enumerating the list.
See also
isHovered, IXRHoverInteractor.interactablesHovered
Implemented in UnityEngine.XR.Interaction.Toolkit.XRBaseInteractable.
Referenced by UnityEngine.XR.Interaction.Toolkit.XRInteractionManager.CancelInteractableHover().
isHovered
bool UnityEngine.XR.Interaction.Toolkit.IXRHoverInteractable.isHovered get
(Read Only) Indicates whether an Interactor currently hovers over this Interactable.
In other words, returns whether interactorsHovering contains any interactors.
interactorsHovering.Count > 0
See also
interactorsHovering, IXRHoverInteractor.hasHover
Implemented in UnityEngine.XR.Interaction.Toolkit.XRBaseInteractable.
lastHoverExited
HoverExitEvent UnityEngine.XR.Interaction.Toolkit.IXRHoverInteractable.lastHoverExited get
The event that is called only when the last remaining hovering Interactor ends hovering over this Interactable.
The HoverExitEventArgs passed to each listener is only valid while the event is invoked, do not hold a reference to it.
See also
firstHoverEntered, hoverExited
Implemented in UnityEngine.XR.Interaction.Toolkit.XRBaseInteractable.
Referenced by UnityEngine.XR.Interaction.Toolkit.XRTintInteractableVisual.Awake(), and UnityEngine.XR.Interaction.Toolkit.XRTintInteractableVisual.OnDestroy().
The documentation for this interface was generated from the following file:
C:/Users/Lykos/Desktop/Projects/Capstone/VRGames/Library/PackageCache/com.unity.xr.interaction.toolkit@2.0.2/Runtime/Interaction/Interactables/IXRHoverInteractable.cs