VRCapstoneGames: UnityEngine.XR.Interaction.Toolkit.IXRSelectInteractor Interface Reference
UnityEngine.XR.Interaction.Toolkit.IXRSelectInteractor Interface Reference
An interface that represents an Interactor component that can select an Interactable component.
Public Member Functions
bool CanSelect (IXRSelectInteractable interactable)
Determines if the Interactable is valid for selection this frame.
bool IsSelecting (IXRSelectInteractable interactable)
Determines whether this Interactor is currently selecting the Interactable.
Pose GetAttachPoseOnSelect (IXRSelectInteractable interactable)
Gets the world position and rotation of the Attach Transform captured during the moment of selection.
Pose GetLocalAttachPoseOnSelect (IXRSelectInteractable interactable)
Gets the local position and rotation of the Attach Transform captured during the moment of selection.
void OnSelectEntering (SelectEnterEventArgs args)
The XRInteractionManager calls this method right before the Interactor first initiates selection of an Interactable in a first pass.
void OnSelectEntered (SelectEnterEventArgs args)
The XRInteractionManager calls this method when the Interactor first initiates selection of an Interactable in a second pass.
void OnSelectExiting (SelectExitEventArgs args)
The XRInteractionManager calls this method right before the Interactor ends selection of an Interactable in a first pass.
void OnSelectExited (SelectExitEventArgs args)
The XRInteractionManager calls this method when the Interactor ends selection of an Interactable in a second pass.
Public Member Functions inherited from UnityEngine.XR.Interaction.Toolkit.IXRInteractor
Transform GetAttachTransform (IXRInteractable interactable)
Gets the Transform that is used as the attachment point for a given Interactable.
void GetValidTargets (List< IXRInteractable > targets)
Retrieve the list of Interactables that this Interactor could possibly interact with this frame. This list is sorted by priority (with highest priority first).
void OnRegistered (InteractorRegisteredEventArgs args)
The XRInteractionManager calls this method when this Interactor is registered with it.
void OnUnregistered (InteractorUnregisteredEventArgs args)
The XRInteractionManager calls this method when this Interactor is unregistered from it.
void PreprocessInteractor (XRInteractionUpdateOrder.UpdatePhase updatePhase)
The XRInteractionManager calls this method to update the Interactor before interaction events occur. Interactors should use this method to do tasks like determine their valid targets.
void ProcessInteractor (XRInteractionUpdateOrder.UpdatePhase updatePhase)
The XRInteractionManager calls this method to update the Interactor after interaction events occur.
Properties
SelectEnterEvent selectEntered [get]
The event that is called when this Interactor begins selecting an Interactable.
SelectExitEvent selectExited [get]
The event that is called when this Interactor ends selecting an Interactable.
List< IXRSelectInteractable > interactablesSelected [get]
(Read Only) The list of Interactables that are currently being selected (may by empty).
IXRSelectInteractable firstInteractableSelected [get]
(Read Only) The first Interactable selected since not having any selection. This Interactor may not currently be selecting the Interactable, which would be the case when it was released while multiple Interactables were selected.
bool hasSelection [get]
(Read Only) Indicates whether this Interactor is currently selecting an Interactable.
bool isSelectActive [get]
(Read Only) Indicates whether this Interactor is in a state where it could select.
bool keepSelectedTargetValid [get]
Whether to keep selecting an Interactable after initially selecting it even when it is no longer a valid target.
Properties inherited from UnityEngine.XR.Interaction.Toolkit.IXRInteractor
InteractionLayerMask interactionLayers [get]
(Read Only) Allows interaction with Interactables whose Interaction Layer Mask overlaps with any Layer in this Interaction Layer Mask.
Transform transform [get]
(Read Only) The Transform associated with the Interactor.
Additional Inherited Members
Events inherited from UnityEngine.XR.Interaction.Toolkit.IXRInteractor
Action< InteractorRegisteredEventArgs > registered
Calls the methods in its invocation list when this Interactor is registered with an Interaction Manager.
Action< InteractorUnregisteredEventArgs > unregistered
Calls the methods in its invocation list when this Interactor is unregistered from an Interaction Manager.
Detailed Description
An interface that represents an Interactor component that can select an Interactable component.
See also
IXRSelectInteractable
Member Function Documentation
CanSelect()
bool UnityEngine.XR.Interaction.Toolkit.IXRSelectInteractor.CanSelect (IXRSelectInteractable interactable)
Determines if the Interactable is valid for selection this frame.
Parameters
interactable Interactable to check.
Returns
Returns true if the interactable can be selected this frame.
See also
IXRSelectInteractable.IsSelectableBy
Implemented in UnityEngine.XR.Interaction.Toolkit.XRBaseInteractor, UnityEngine.XR.Interaction.Toolkit.XRDirectInteractor, UnityEngine.XR.Interaction.Toolkit.XRRayInteractor, and UnityEngine.XR.Interaction.Toolkit.XRSocketInteractor.
Referenced by UnityEngine.XR.Interaction.Toolkit.XRInteractionManager.ClearInteractorSelection().
GetAttachPoseOnSelect()
Pose UnityEngine.XR.Interaction.Toolkit.IXRSelectInteractor.GetAttachPoseOnSelect (IXRSelectInteractable interactable)
Gets the world position and rotation of the Attach Transform captured during the moment of selection.
Parameters
interactable The specific Interactable as context to get the attachment point for.
Returns
Returns the world pose of the attachment point during the moment of selection, and otherwise the identity Pose if it was not selected during the current selection stack.
See also
GetLocalAttachPoseOnSelect, IXRInteractor.GetAttachTransform, IXRSelectInteractable.GetAttachPoseOnSelect
Implemented in UnityEngine.XR.Interaction.Toolkit.XRBaseInteractor.
GetLocalAttachPoseOnSelect()
Pose UnityEngine.XR.Interaction.Toolkit.IXRSelectInteractor.GetLocalAttachPoseOnSelect (IXRSelectInteractable interactable)
Gets the local position and rotation of the Attach Transform captured during the moment of selection.
Parameters
interactable The specific Interactable as context to get the attachment point for.
Returns
Returns the local pose of the attachment point during the moment of selection, and otherwise the identity Pose if it was not selected during the current selection stack.
See also
GetAttachPoseOnSelect, IXRInteractor.GetAttachTransform, IXRSelectInteractable.GetLocalAttachPoseOnSelect
Implemented in UnityEngine.XR.Interaction.Toolkit.XRBaseInteractor.
IsSelecting()
bool UnityEngine.XR.Interaction.Toolkit.IXRSelectInteractor.IsSelecting (IXRSelectInteractable interactable)
Determines whether this Interactor is currently selecting the Interactable.
Parameters
interactable Interactable to check.
Returns
Returns true if this Interactor is currently selecting the Interactable. Otherwise, returns .
In other words, returns whether interactablesSelected contains interactable .
See also
interactablesSelected
Implemented in UnityEngine.XR.Interaction.Toolkit.XRBaseInteractor.
Referenced by UnityEngine.XR.Interaction.Toolkit.XRInteractionManager.ResolveExistingSelect().
OnSelectEntered()
void UnityEngine.XR.Interaction.Toolkit.IXRSelectInteractor.OnSelectEntered (SelectEnterEventArgs args)
The XRInteractionManager calls this method when the Interactor first initiates selection of an Interactable in a second pass.
Parameters
args Event data containing the Interactable that is being selected.
args is only valid during this method call, do not hold a reference to it.
See also
OnSelectExited(SelectExitEventArgs)
Implemented in UnityEngine.XR.Interaction.Toolkit.XRBaseInteractor.
Referenced by UnityEngine.XR.Interaction.Toolkit.XRInteractionManager.SelectEnter().
OnSelectEntering()
void UnityEngine.XR.Interaction.Toolkit.IXRSelectInteractor.OnSelectEntering (SelectEnterEventArgs args)
The XRInteractionManager calls this method right before the Interactor first initiates selection of an Interactable in a first pass.
Parameters
args Event data containing the Interactable that is being selected.
args is only valid during this method call, do not hold a reference to it.
See also
OnSelectEntered(SelectEnterEventArgs)
Implemented in UnityEngine.XR.Interaction.Toolkit.XRBaseControllerInteractor, UnityEngine.XR.Interaction.Toolkit.XRBaseInteractor, and UnityEngine.XR.Interaction.Toolkit.XRRayInteractor.
Referenced by UnityEngine.XR.Interaction.Toolkit.XRInteractionManager.SelectEnter().
OnSelectExited()
void UnityEngine.XR.Interaction.Toolkit.IXRSelectInteractor.OnSelectExited (SelectExitEventArgs args)
The XRInteractionManager calls this method when the Interactor ends selection of an Interactable in a second pass.
Parameters
args Event data containing the Interactable that is no longer selected.
args is only valid during this method call, do not hold a reference to it.
See also
OnSelectEntered(SelectEnterEventArgs)
Implemented in UnityEngine.XR.Interaction.Toolkit.XRBaseInteractor.
Referenced by UnityEngine.XR.Interaction.Toolkit.XRInteractionManager.SelectExit().
OnSelectExiting()
void UnityEngine.XR.Interaction.Toolkit.IXRSelectInteractor.OnSelectExiting (SelectExitEventArgs args)
The XRInteractionManager calls this method right before the Interactor ends selection of an Interactable in a first pass.
Parameters
args Event data containing the Interactable that is no longer selected.
args is only valid during this method call, do not hold a reference to it.
See also
OnSelectExited(SelectExitEventArgs)
Implemented in UnityEngine.XR.Interaction.Toolkit.XRBaseControllerInteractor, UnityEngine.XR.Interaction.Toolkit.XRBaseInteractor, UnityEngine.XR.Interaction.Toolkit.XRRayInteractor, and UnityEngine.XR.Interaction.Toolkit.XRSocketInteractor.
Referenced by UnityEngine.XR.Interaction.Toolkit.XRInteractionManager.SelectExit().
Property Documentation
firstInteractableSelected
IXRSelectInteractable UnityEngine.XR.Interaction.Toolkit.IXRSelectInteractor.firstInteractableSelected get
(Read Only) The first Interactable selected since not having any selection. This Interactor may not currently be selecting the Interactable, which would be the case when it was released while multiple Interactables were selected.
See also
IXRSelectInteractable.firstInteractorSelecting
Implemented in UnityEngine.XR.Interaction.Toolkit.XRBaseInteractor.
hasSelection
bool UnityEngine.XR.Interaction.Toolkit.IXRSelectInteractor.hasSelection get
(Read Only) Indicates whether this Interactor is currently selecting an Interactable.
In other words, returns whether interactablesSelected contains any Interactables.
interactablesSelected.Count > 0
See also
interactablesSelected, IXRSelectInteractable.isSelected
Implemented in UnityEngine.XR.Interaction.Toolkit.XRBaseInteractor.
interactablesSelected
List<IXRSelectInteractable> UnityEngine.XR.Interaction.Toolkit.IXRSelectInteractor.interactablesSelected get
(Read Only) The list of Interactables that are currently being selected (may by empty).
This should be treated as a read only view of the list and should not be modified by external callers. It is exposed as a List<T> rather than an IReadOnlyList<T> to avoid GC Allocations when enumerating the list.
See also
hasSelection, IXRSelectInteractable.interactorsSelecting
Implemented in UnityEngine.XR.Interaction.Toolkit.XRBaseInteractor.
Referenced by UnityEngine.XR.Interaction.Toolkit.XRInteractionManager.CancelInteractorSelection(), and UnityEngine.XR.Interaction.Toolkit.XRInteractionManager.ClearInteractorSelection().
isSelectActive
bool UnityEngine.XR.Interaction.Toolkit.IXRSelectInteractor.isSelectActive get
(Read Only) Indicates whether this Interactor is in a state where it could select.
Implemented in UnityEngine.XR.Interaction.Toolkit.XRBaseControllerInteractor, UnityEngine.XR.Interaction.Toolkit.XRBaseInteractor, UnityEngine.XR.Interaction.Toolkit.XRRayInteractor, and UnityEngine.XR.Interaction.Toolkit.XRSocketInteractor.
Referenced by UnityEngine.XR.Interaction.Toolkit.XRInteractionManager.ClearInteractorSelection().
keepSelectedTargetValid
bool UnityEngine.XR.Interaction.Toolkit.IXRSelectInteractor.keepSelectedTargetValid get
Whether to keep selecting an Interactable after initially selecting it even when it is no longer a valid target.
Return true to make the XRInteractionManager retain the selection even if the Interactable is not contained within the list of valid targets. Return false to make the Interaction Manager clear the selection if it isn't within the list of valid targets.
A common use for disabling this is for Ray Interactors used for teleportation to make the teleportation Interactable no longer selected when not currently pointing at it.
Implemented in UnityEngine.XR.Interaction.Toolkit.XRBaseInteractor.
selectEntered
SelectEnterEvent UnityEngine.XR.Interaction.Toolkit.IXRSelectInteractor.selectEntered get
The event that is called when this Interactor begins selecting an Interactable.
The SelectEnterEventArgs passed to each listener is only valid while the event is invoked, do not hold a reference to it.
See also
selectExited
Implemented in UnityEngine.XR.Interaction.Toolkit.XRBaseInteractor.
selectExited
SelectExitEvent UnityEngine.XR.Interaction.Toolkit.IXRSelectInteractor.selectExited get
The event that is called when this Interactor ends selecting an Interactable.
The SelectEnterEventArgs passed to each listener is only valid while the event is invoked, do not hold a reference to it.
See also
selectEntered
Implemented in UnityEngine.XR.Interaction.Toolkit.XRBaseInteractor.
The documentation for this interface was generated from the following file:
C:/Users/Lykos/Desktop/Projects/Capstone/VRGames/Library/PackageCache/com.unity.xr.interaction.toolkit@2.0.2/Runtime/Interaction/Interactors/IXRSelectInteractor.cs