VRCapstoneGames: UnityEngine.ProBuilder.KdTree.ITypeMath< T > Interface Template Reference
UnityEngine.ProBuilder.KdTree.ITypeMath< T > Interface Template Reference
Public Member Functions
int Compare (T a, T b)
T Min (T a, T b)
T Max (T a, T b)
bool AreEqual (T a, T b)
bool AreEqual (T[] a, T[] b)
T Add (T a, T b)
T Subtract (T a, T b)
T Multiply (T a, T b)
T DistanceSquaredBetweenPoints (T[] a, T[] b)
Properties
T MinValue [get]
T MaxValue [get]
T Zero [get]
T NegativeInfinity [get]
T PositiveInfinity [get]
Member Function Documentation
Add()
T UnityEngine.ProBuilder.KdTree.ITypeMath< T >.Add (T a, T b)
Implemented in UnityEngine.ProBuilder.KdTree.Math.TypeMath< T >.
AreEqual() [1/2]
bool UnityEngine.ProBuilder.KdTree.ITypeMath< T >.AreEqual (T a, T b)
Implemented in UnityEngine.ProBuilder.KdTree.Math.TypeMath< T >.
Referenced by UnityEngine.ProBuilder.KdTree.KdTree< TKey, TValue >.Add(), UnityEngine.ProBuilder.KdTree.KdTree< TKey, TValue >.RemoveAt(), and UnityEngine.ProBuilder.KdTree.KdTree< TKey, TValue >.TryFindValueAt().
AreEqual() [2/2]
bool UnityEngine.ProBuilder.KdTree.ITypeMath< T >.AreEqual (T[] a, T[] b)
Implemented in UnityEngine.ProBuilder.KdTree.Math.TypeMath< T >.
Compare()
int UnityEngine.ProBuilder.KdTree.ITypeMath< T >.Compare (T a, T b)
Implemented in UnityEngine.ProBuilder.KdTree.Math.TypeMath< T >.
Referenced by UnityEngine.ProBuilder.KdTree.NearestNeighbourList< TItem, TDistance >.Add(), UnityEngine.ProBuilder.KdTree.KdTree< TKey, TValue >.Add(), UnityEngine.ProBuilder.KdTree.HyperRect< T >.GetClosestPoint(), UnityEngine.ProBuilder.KdTree.KdTree< TKey, TValue >.RemoveAt(), and UnityEngine.ProBuilder.KdTree.KdTree< TKey, TValue >.TryFindValueAt().
DistanceSquaredBetweenPoints()
T UnityEngine.ProBuilder.KdTree.ITypeMath< T >.DistanceSquaredBetweenPoints (T[] a, T[] b)
Implemented in UnityEngine.ProBuilder.KdTree.Math.TypeMath< T >.
Max()
T UnityEngine.ProBuilder.KdTree.ITypeMath< T >.Max (T a, T b)
Implemented in UnityEngine.ProBuilder.KdTree.Math.TypeMath< T >.
Min()
T UnityEngine.ProBuilder.KdTree.ITypeMath< T >.Min (T a, T b)
Implemented in UnityEngine.ProBuilder.KdTree.Math.TypeMath< T >.
Multiply()
T UnityEngine.ProBuilder.KdTree.ITypeMath< T >.Multiply (T a, T b)
Implemented in UnityEngine.ProBuilder.KdTree.Math.TypeMath< T >.
Referenced by UnityEngine.ProBuilder.KdTree.KdTree< TKey, TValue >.RadialSearch().
Subtract()
T UnityEngine.ProBuilder.KdTree.ITypeMath< T >.Subtract (T a, T b)
Implemented in UnityEngine.ProBuilder.KdTree.Math.TypeMath< T >.
Property Documentation
MaxValue
T UnityEngine.ProBuilder.KdTree.ITypeMath< T >.MaxValue get
Implemented in UnityEngine.ProBuilder.KdTree.Math.DoubleMath, UnityEngine.ProBuilder.KdTree.Math.FloatMath, and UnityEngine.ProBuilder.KdTree.Math.TypeMath< T >.
Referenced by UnityEngine.ProBuilder.KdTree.KdTree< TKey, TValue >.GetNearestNeighbours().
MinValue
T UnityEngine.ProBuilder.KdTree.ITypeMath< T >.MinValue get
Implemented in UnityEngine.ProBuilder.KdTree.Math.DoubleMath, UnityEngine.ProBuilder.KdTree.Math.FloatMath, and UnityEngine.ProBuilder.KdTree.Math.TypeMath< T >.
Referenced by UnityEngine.ProBuilder.KdTree.PriorityQueue< TItem, TPriority >.Dequeue().
NegativeInfinity
T UnityEngine.ProBuilder.KdTree.ITypeMath< T >.NegativeInfinity get
Implemented in UnityEngine.ProBuilder.KdTree.Math.DoubleMath, UnityEngine.ProBuilder.KdTree.Math.FloatMath, and UnityEngine.ProBuilder.KdTree.Math.TypeMath< T >.
Referenced by UnityEngine.ProBuilder.KdTree.HyperRect< T >.Infinite().
PositiveInfinity
T UnityEngine.ProBuilder.KdTree.ITypeMath< T >.PositiveInfinity get
Implemented in UnityEngine.ProBuilder.KdTree.Math.DoubleMath, UnityEngine.ProBuilder.KdTree.Math.FloatMath, and UnityEngine.ProBuilder.KdTree.Math.TypeMath< T >.
Referenced by UnityEngine.ProBuilder.KdTree.HyperRect< T >.Infinite().
Zero
T UnityEngine.ProBuilder.KdTree.ITypeMath< T >.Zero get
Implemented in UnityEngine.ProBuilder.KdTree.Math.DoubleMath, UnityEngine.ProBuilder.KdTree.Math.FloatMath, and UnityEngine.ProBuilder.KdTree.Math.TypeMath< T >.
The documentation for this interface was generated from the following file:
C:/Users/Lykos/Desktop/Projects/Capstone/VRGames/Library/PackageCache/com.unity.probuilder@5.0.6/External/KdTree/KdTreeLib/Math/ITypeMath.cs