VRCapstoneGames: UnityEngine.XR.Interaction.Toolkit.IXRInteractor Interface Reference
UnityEngine.XR.Interaction.Toolkit.IXRInteractor Interface Reference
An interface that represents an Interactor component that controls how a GameObject interacts with an Interactable component. An example is a Ray Interactor which uses ray casting to find valid Interactable objects to manipulate.
Public Member Functions
Transform GetAttachTransform (IXRInteractable interactable)
Gets the Transform that is used as the attachment point for a given Interactable.
void GetValidTargets (List< IXRInteractable > targets)
Retrieve the list of Interactables that this Interactor could possibly interact with this frame. This list is sorted by priority (with highest priority first).
void OnRegistered (InteractorRegisteredEventArgs args)
The XRInteractionManager calls this method when this Interactor is registered with it.
void OnUnregistered (InteractorUnregisteredEventArgs args)
The XRInteractionManager calls this method when this Interactor is unregistered from it.
void PreprocessInteractor (XRInteractionUpdateOrder.UpdatePhase updatePhase)
The XRInteractionManager calls this method to update the Interactor before interaction events occur. Interactors should use this method to do tasks like determine their valid targets.
void ProcessInteractor (XRInteractionUpdateOrder.UpdatePhase updatePhase)
The XRInteractionManager calls this method to update the Interactor after interaction events occur.
Properties
InteractionLayerMask interactionLayers [get]
(Read Only) Allows interaction with Interactables whose Interaction Layer Mask overlaps with any Layer in this Interaction Layer Mask.
Transform transform [get]
(Read Only) The Transform associated with the Interactor.
Events
Action< InteractorRegisteredEventArgs > registered
Calls the methods in its invocation list when this Interactor is registered with an Interaction Manager.
Action< InteractorUnregisteredEventArgs > unregistered
Calls the methods in its invocation list when this Interactor is unregistered from an Interaction Manager.
Detailed Description
An interface that represents an Interactor component that controls how a GameObject interacts with an Interactable component. An example is a Ray Interactor which uses ray casting to find valid Interactable objects to manipulate.
When scripting, you can typically write custom behaviors that derive from XRBaseInteractor or one of its derived classes rather than implementing this interface directly.
See also
XRBaseInteractor, IXRActivateInteractor, IXRHoverInteractor, IXRSelectInteractor, IXRInteractable
Member Function Documentation
GetAttachTransform()
Transform UnityEngine.XR.Interaction.Toolkit.IXRInteractor.GetAttachTransform (IXRInteractable interactable)
Gets the Transform that is used as the attachment point for a given Interactable.
Parameters
interactable The specific Interactable as context to get the attachment point for.
Returns
Returns the attachment point Transform.
See also
IXRInteractable.GetAttachTransform
This should typically return the Transform of a child GameObject or the transform itself.
Implemented in UnityEngine.XR.Interaction.Toolkit.XRBaseInteractor.
Referenced by UnityEngine.XR.Interaction.Toolkit.XRBaseInteractable.GetDistanceSqrToInteractor().
GetValidTargets()
void UnityEngine.XR.Interaction.Toolkit.IXRInteractor.GetValidTargets (List< IXRInteractable > targets)
Retrieve the list of Interactables that this Interactor could possibly interact with this frame. This list is sorted by priority (with highest priority first).
Parameters
targets The results list to populate with Interactables that are valid for selection or hover.
When implementing this method, Unity expects you to clear targets before adding to it.
Implemented in UnityEngine.XR.Interaction.Toolkit.XRBaseInteractor, UnityEngine.XR.Interaction.Toolkit.XRDirectInteractor, UnityEngine.XR.Interaction.Toolkit.XRRayInteractor, UnityEngine.XR.Interaction.Toolkit.XRSocketInteractor, and UnityEngine.XR.Interaction.Toolkit.Tests.MockInteractor.
Referenced by UnityEngine.XR.Interaction.Toolkit.XRInteractionManager.GetValidTargets().
OnRegistered()
void UnityEngine.XR.Interaction.Toolkit.IXRInteractor.OnRegistered (InteractorRegisteredEventArgs args)
The XRInteractionManager calls this method when this Interactor is registered with it.
Parameters
args Event data containing the Interaction Manager that registered this Interactor.
args is only valid during this method call, do not hold a reference to it.
See also
XRInteractionManager.RegisterInteractor(IXRInteractor)
Implemented in UnityEngine.XR.Interaction.Toolkit.XRBaseInteractor, UnityEngine.XR.Interaction.Toolkit.XRDirectInteractor, and UnityEngine.XR.Interaction.Toolkit.XRSocketInteractor.
Referenced by UnityEngine.XR.Interaction.Toolkit.XRInteractionManager.OnRegistered().
OnUnregistered()
void UnityEngine.XR.Interaction.Toolkit.IXRInteractor.OnUnregistered (InteractorUnregisteredEventArgs args)
The XRInteractionManager calls this method when this Interactor is unregistered from it.
Parameters
args Event data containing the Interaction Manager that unregistered this Interactor.
args is only valid during this method call, do not hold a reference to it.
See also
XRInteractionManager.UnregisterInteractor(IXRInteractor)
Implemented in UnityEngine.XR.Interaction.Toolkit.XRBaseInteractor, UnityEngine.XR.Interaction.Toolkit.XRDirectInteractor, and UnityEngine.XR.Interaction.Toolkit.XRSocketInteractor.
Referenced by UnityEngine.XR.Interaction.Toolkit.XRInteractionManager.OnUnregistered().
PreprocessInteractor()
void UnityEngine.XR.Interaction.Toolkit.IXRInteractor.PreprocessInteractor (XRInteractionUpdateOrder.UpdatePhase updatePhase)
The XRInteractionManager calls this method to update the Interactor before interaction events occur. Interactors should use this method to do tasks like determine their valid targets.
Parameters
updatePhase The update phase this is called during.
Please see the XRInteractionManager and XRInteractionUpdateOrder.UpdatePhase documentation for more details on update order.
See also
XRInteractionUpdateOrder.UpdatePhase
Implemented in UnityEngine.XR.Interaction.Toolkit.XRBaseControllerInteractor, UnityEngine.XR.Interaction.Toolkit.XRBaseInteractor, and UnityEngine.XR.Interaction.Toolkit.XRRayInteractor.
ProcessInteractor()
void UnityEngine.XR.Interaction.Toolkit.IXRInteractor.ProcessInteractor (XRInteractionUpdateOrder.UpdatePhase updatePhase)
The XRInteractionManager calls this method to update the Interactor after interaction events occur.
Parameters
updatePhase The update phase this is called during.
Please see the XRInteractionManager and XRInteractionUpdateOrder.UpdatePhase documentation for more details on update order.
See also
XRInteractionUpdateOrder.UpdatePhase, IXRInteractable.ProcessInteractable
Implemented in UnityEngine.XR.Interaction.Toolkit.XRBaseControllerInteractor, UnityEngine.XR.Interaction.Toolkit.XRBaseInteractor, UnityEngine.XR.Interaction.Toolkit.XRDirectInteractor, UnityEngine.XR.Interaction.Toolkit.XRRayInteractor, and UnityEngine.XR.Interaction.Toolkit.XRSocketInteractor.
Property Documentation
interactionLayers
InteractionLayerMask UnityEngine.XR.Interaction.Toolkit.IXRInteractor.interactionLayers get
(Read Only) Allows interaction with Interactables whose Interaction Layer Mask overlaps with any Layer in this Interaction Layer Mask.
See also
IXRInteractable.interactionLayers
Implemented in UnityEngine.XR.Interaction.Toolkit.XRBaseInteractor.
Referenced by UnityEngine.XR.Interaction.Toolkit.XRInteractionManager.HasInteractionLayerOverlap().
transform
Transform UnityEngine.XR.Interaction.Toolkit.IXRInteractor.transform get
(Read Only) The Transform associated with the Interactor.
When this Interactor is a component, this property is the Transform of the GameObject the component is attached to.
Referenced by UnityEngine.XR.Interaction.Toolkit.XRBaseInteractable.AttachCustomReticle(), UnityEngine.XR.Interaction.Toolkit.XRBaseInteractor.Awake(), UnityEngine.XR.Interaction.Toolkit.XRBaseInteractor.GetAttachTransform(), and UnityEngine.XR.Interaction.Toolkit.XRBaseInteractable.RemoveCustomReticle().
Event Documentation
registered
Action<InteractorRegisteredEventArgs> UnityEngine.XR.Interaction.Toolkit.IXRInteractor.registered
Calls the methods in its invocation list when this Interactor is registered with an Interaction Manager.
The InteractorRegisteredEventArgs passed to each listener is only valid while the event is invoked, do not hold a reference to it.
See also
XRInteractionManager.interactorRegistered
unregistered
Action<InteractorUnregisteredEventArgs> UnityEngine.XR.Interaction.Toolkit.IXRInteractor.unregistered
Calls the methods in its invocation list when this Interactor is unregistered from an Interaction Manager.
The InteractorUnregisteredEventArgs passed to each listener is only valid while the event is invoked, do not hold a reference to it.
See also
XRInteractionManager.interactorUnregistered
The documentation for this interface was generated from the following file:
C:/Users/Lykos/Desktop/Projects/Capstone/VRGames/Library/PackageCache/com.unity.xr.interaction.toolkit@2.0.2/Runtime/Interaction/Interactors/IXRInteractor.cs