VRCapstoneGames: Oculus.Interaction.GrabAPI.IFingerAPI Interface Reference
Oculus.Interaction.GrabAPI.IFingerAPI Interface Reference
Public Member Functions
bool GetFingerIsGrabbing (HandFinger finger)
bool GetFingerIsGrabbingChanged (HandFinger finger, bool targetPinchState)
float GetFingerGrabStrength (HandFinger finger)
Vector3 GetCenterOffset ()
void Update (IHand hand)
Member Function Documentation
GetCenterOffset()
Vector3 Oculus.Interaction.GrabAPI.IFingerAPI.GetCenterOffset ()
Implemented in Oculus.Interaction.GrabAPI.FingerPalmGrabAPI, Oculus.Interaction.GrabAPI.FingerPinchGrabAPI, and Oculus.Interaction.GrabAPI.FingerRawPinchAPI.
Referenced by Oculus.Interaction.GrabAPI.HandGrabAPI.GetPalmCenter(), and Oculus.Interaction.GrabAPI.HandGrabAPI.GetPinchCenter().
GetFingerGrabStrength()
float Oculus.Interaction.GrabAPI.IFingerAPI.GetFingerGrabStrength (HandFinger finger)
Implemented in Oculus.Interaction.GrabAPI.FingerPalmGrabAPI, Oculus.Interaction.GrabAPI.FingerPinchGrabAPI, and Oculus.Interaction.GrabAPI.FingerRawPinchAPI.
Referenced by Oculus.Interaction.GrabAPI.HandGrabAPI.GetFingerPalmStrength(), and Oculus.Interaction.GrabAPI.HandGrabAPI.GetFingerPinchStrength().
GetFingerIsGrabbing()
bool Oculus.Interaction.GrabAPI.IFingerAPI.GetFingerIsGrabbing (HandFinger finger)
Implemented in Oculus.Interaction.GrabAPI.FingerPalmGrabAPI, Oculus.Interaction.GrabAPI.FingerPinchGrabAPI, and Oculus.Interaction.GrabAPI.FingerRawPinchAPI.
GetFingerIsGrabbingChanged()
bool Oculus.Interaction.GrabAPI.IFingerAPI.GetFingerIsGrabbingChanged (HandFinger finger, bool targetPinchState)
Implemented in Oculus.Interaction.GrabAPI.FingerPalmGrabAPI, Oculus.Interaction.GrabAPI.FingerPinchGrabAPI, and Oculus.Interaction.GrabAPI.FingerRawPinchAPI.
Update()
void Oculus.Interaction.GrabAPI.IFingerAPI.Update (IHand hand)
Implemented in Oculus.Interaction.GrabAPI.FingerPalmGrabAPI, Oculus.Interaction.GrabAPI.FingerPinchGrabAPI, and Oculus.Interaction.GrabAPI.FingerRawPinchAPI.
The documentation for this interface was generated from the following file:
C:/Users/Lykos/Desktop/Projects/Capstone/VRGames/Assets/ThirdParty/Oculus/Interaction/Runtime/Scripts/Grab/IFingerAPI.cs