VRCapstoneGames: UnityEngine.InputSystem.LowLevel.StateEvent Struct Reference
UnityEngine.InputSystem.LowLevel.StateEvent Struct Reference
A complete state snapshot for an entire input device.
Public Member Functions
InputEventPtr ToEventPtr ()
TState GetState< TState > ()
Retrieve the state stored in the event.
Static Public Member Functions
static TState GetState< TState > (InputEventPtr ptr)
Retrieve the state stored in the event.
static int GetEventSizeWithPayload< TState > ()
static StateEvent * From (InputEventPtr ptr)
Return the given InputEventPtr as a StateEvent pointer.
static NativeArray< byte > From (InputDevice device, out InputEventPtr eventPtr, Allocator allocator=Allocator.Temp)
Read the current state of device and create a state event from it.
static NativeArray< byte > FromDefaultStateFor (InputDevice device, out InputEventPtr eventPtr, Allocator allocator=Allocator.Temp)
Create a state event for the given device and copy the default state of the device into the event.
Public Attributes
InputEvent baseEvent
FourCC stateFormat
Type code for the state stored in the event.
Static Public Attributes
const int Type = 0x53544154
Properties
uint stateSizeInBytes [get]
void * state [get]
FourCC typeStatic [get]
Properties inherited from UnityEngine.InputSystem.LowLevel.IInputEventTypeInfo
Detailed Description
A complete state snapshot for an entire input device.
This is a variable-sized event.
Member Function Documentation
From() [1/2]
static NativeArray< byte > UnityEngine.InputSystem.LowLevel.StateEvent.From (InputDevice device, out InputEventPtr eventPtr, Allocator allocator = Allocator::Temp) static
Read the current state of device and create a state event from it.
Parameters
device Device to grab the state from. Must be a device that has been added to the system.
eventPtr Receives a pointer to the newly created state event.
allocator Which native allocator to allocate memory for the event from. By default, the buffer is allocated as temporary memory (Allocator.Temp. Note that this means the buffer will not be valid past the current frame. Use Allocator.Persistent if the buffer for the state event is meant to persist for longer.
Returns
Buffer of unmanaged memory allocated for the event.
Exceptions
ArgumentException device has not been added to the system.
ArgumentNullException device is null.
From() [2/2]
static StateEvent * UnityEngine.InputSystem.LowLevel.StateEvent.From (InputEventPtr ptr) static
Return the given InputEventPtr as a StateEvent pointer.
Parameters
ptr A pointer to an input event. The pointer is checked for null and for whether the type of event it refers to is indeed a StateEvent.
Returns
Pointer ptr converted to a StateEvent pointer.
Exceptions
ArgumentNullException ptr is default(InputEventPtr).
InvalidCastException ptr does not refer to a StateEvent.
Referenced by UnityEngine.InputSystem.LowLevel.StateEvent.From(), UnityEngine.InputSystem.LowLevel.StateEvent.FromDefaultStateFor(), UnityEngine.InputSystem.LowLevel.StateEvent.GetState< TState >(), UnityEngine.InputSystem.LowLevel.InputStateHistory< TValue >.RecordStateChange(), UnityEngine.InputSystem.LowLevel.InputStateHistory< TValue >.RecordStateChange(), and UnityEngine.InputSystem.InputTestFixture.Set< TValue >().
FromDefaultStateFor()
static NativeArray< byte > UnityEngine.InputSystem.LowLevel.StateEvent.FromDefaultStateFor (InputDevice device, out InputEventPtr eventPtr, Allocator allocator = Allocator::Temp) static
Create a state event for the given device and copy the default state of the device into the event.
Parameters
device Device to create a state event for. Must be a device that has been added to the system.
eventPtr Receives a pointer to the newly created state event.
allocator Which native allocator to allocate memory for the event from. By default, the buffer is allocated as temporary memory (Allocator.Temp. Note that this means the buffer will not be valid past the current frame. Use Allocator.Persistent if the buffer for the state event is meant to persist for longer.
Returns
Buffer of unmanaged memory allocated for the event.
Exceptions
ArgumentException device has not been added to the system.
ArgumentNullException device is null.
GetEventSizeWithPayload< TState >()
static int UnityEngine.InputSystem.LowLevel.StateEvent.GetEventSizeWithPayload< TState > () static
Type Constraints
TState : struct
GetState< TState >() [1/2]
TState UnityEngine.InputSystem.LowLevel.StateEvent.GetState< TState > ()
Retrieve the state stored in the event.
Template Parameters
TState Type of state expected to be stored in the event. IInputStateTypeInfo.format must match stateFormat.
Returns
Copy of the state stored in the event.
Exceptions
InvalidOperationException stateFormat does not match IInputStateTypeInfo.format of TState .
The event may contain less or more data than what is found in the struct. Only the data found in the event is copied. The remainder of the struct is left at default values.
See also
GetState<T>(InputEventPtr)
Type Constraints
TState : struct
TState : IInputStateTypeInfo
GetState< TState >() [2/2]
static TState UnityEngine.InputSystem.LowLevel.StateEvent.GetState< TState > (InputEventPtr ptr) static
Retrieve the state stored in the event.
Template Parameters
TState Type of state expected to be stored in the event. IInputStateTypeInfo.format must match stateFormat.
Parameters
ptr A pointer to an input event. The pointer is checked for null and for whether the type of event it refers to is indeed a StateEvent.
Returns
Copy of the state stored in the event.
The event may contain less or more data than what is found in the struct. Only the data found in the event is copied. The remainder of the struct is left at default values.
Exceptions
InvalidOperationException stateFormat does not match IInputStateTypeInfo.format of TState .
ArgumentNullException ptr is default(InputEventPtr).
InvalidCastException ptr does not refer to a StateEvent.
See also
GetState<T>()
Type Constraints
TState : struct
TState : IInputStateTypeInfo
ToEventPtr()
InputEventPtr UnityEngine.InputSystem.LowLevel.StateEvent.ToEventPtr ()
Member Data Documentation
baseEvent
InputEvent UnityEngine.InputSystem.LowLevel.StateEvent.baseEvent
stateFormat
FourCC UnityEngine.InputSystem.LowLevel.StateEvent.stateFormat
Type code for the state stored in the event.
Referenced by UnityEngine.InputSystem.LowLevel.StateEvent.GetState< TState >().
Type
const int UnityEngine.InputSystem.LowLevel.StateEvent.Type = 0x53544154 static
Referenced by UnityEngine.InputSystem.InputControlExtensions.InputEventControlEnumerator.Reset().
Property Documentation
state
void* UnityEngine.InputSystem.LowLevel.StateEvent.state get
Referenced by UnityEngine.InputSystem.LowLevel.StateEvent.GetState< TState >().
stateSizeInBytes
uint UnityEngine.InputSystem.LowLevel.StateEvent.stateSizeInBytes get
Referenced by UnityEngine.InputSystem.LowLevel.StateEvent.GetState< TState >().
typeStatic
FourCC UnityEngine.InputSystem.LowLevel.StateEvent.typeStatic get
Implements UnityEngine.InputSystem.LowLevel.IInputEventTypeInfo.
The documentation for this struct was generated from the following file:
C:/Users/Lykos/Desktop/Projects/Capstone/VRGames/Library/PackageCache/com.unity.inputsystem@1.3.0/InputSystem/Events/StateEvent.cs