VRCapstoneGames: UnityEditor.Timeline.MarkerDrawOptions Struct Reference
UnityEditor.Timeline.MarkerDrawOptions Struct Reference
The user-defined options for drawing a marker.
Public Member Functions
override bool Equals (object obj)
Indicates whether this instance and a specified object are equal.
bool Equals (MarkerDrawOptions other)
Compares this object with another MarkerDrawOptions.
override int GetHashCode ()
Returns the hash code for this instance.
Static Public Member Functions
static bool operator== (MarkerDrawOptions options1, MarkerDrawOptions options2)
Compares two MarkerDrawOptions objects.
static bool operator!= (MarkerDrawOptions options1, MarkerDrawOptions options2)
Compares two MarkerDrawOptions objects.
Properties
string tooltip [get, set]
The tooltip for the marker.
string errorText [get, set]
Text that indicates if the marker should display an error.
Detailed Description
The user-defined options for drawing a marker.
Member Function Documentation
Equals() [1/2]
bool UnityEditor.Timeline.MarkerDrawOptions.Equals (MarkerDrawOptions other)
Compares this object with another MarkerDrawOptions.
Parameters
other The object to compare with.
Returns
Returns true if this and other are equal.
Equals() [2/2]
override bool UnityEditor.Timeline.MarkerDrawOptions.Equals (object obj)
Indicates whether this instance and a specified object are equal.
Parameters
obj The object to compare with the current instance.
Returns
Returns true if obj and this instance are the same type and represent the same value.
Referenced by UnityEditor.Timeline.MarkerDrawOptions.Equals(), UnityEditor.Timeline.MarkerDrawOptions.operator!=(), and UnityEditor.Timeline.MarkerDrawOptions.operator==().
GetHashCode()
override int UnityEditor.Timeline.MarkerDrawOptions.GetHashCode ()
Returns the hash code for this instance.
Returns
A 32-bit signed integer that is the hash code for this instance.
operator!=()
static bool UnityEditor.Timeline.MarkerDrawOptions.operator!= (MarkerDrawOptions options1, MarkerDrawOptions options2) static
Compares two MarkerDrawOptions objects.
Parameters
options1 The first object.
options2 The second object.
Returns
Returns true if they are not equal.
operator==()
static bool UnityEditor.Timeline.MarkerDrawOptions.operator== (MarkerDrawOptions options1, MarkerDrawOptions options2) static
Compares two MarkerDrawOptions objects.
Parameters
options1 The first object.
options2 The second object.
Returns
Returns true if they are equal.
Property Documentation
errorText
string UnityEditor.Timeline.MarkerDrawOptions.errorText get set
Text that indicates if the marker should display an error.
If the error text is not empty or null, then the marker displays a warning. The error text is used as the tooltip.
Referenced by UnityEditor.Timeline.MarkerDrawOptions.Equals(), and UnityEditor.Timeline.MarkerDrawOptions.GetHashCode().
tooltip
string UnityEditor.Timeline.MarkerDrawOptions.tooltip get set
The tooltip for the marker.
Referenced by UnityEditor.Timeline.MarkerDrawOptions.Equals(), and UnityEditor.Timeline.MarkerDrawOptions.GetHashCode().
The documentation for this struct was generated from the following file:
C:/Users/Lykos/Desktop/Projects/Capstone/VRGames/Library/PackageCache/com.unity.timeline@1.6.4/Editor/CustomEditors/MarkerEditor.cs