VRCapstoneGames: UnityEngine.Timeline.DiscreteTime Struct Reference
UnityEngine.Timeline.DiscreteTime Struct Reference
Public Member Functions
DiscreteTime (DiscreteTime time)
DiscreteTime (Int64 time)
DiscreteTime (double time)
DiscreteTime (float time)
DiscreteTime (int time)
DiscreteTime (int frame, double fps)
DiscreteTime OneTickBefore ()
DiscreteTime OneTickAfter ()
Int64 GetTick ()
int CompareTo (object obj)
bool Equals (DiscreteTime other)
override bool Equals (object obj)
override string ToString ()
override int GetHashCode ()
Static Public Member Functions
static DiscreteTime FromTicks (Int64 ticks)
static Int64 DoubleToDiscreteTime (double time)
static Int64 FloatToDiscreteTime (float time)
static Int64 IntToDiscreteTime (int time)
static double ToDouble (Int64 time)
static float ToFloat (Int64 time)
static operator double (DiscreteTime b)
static operator float (DiscreteTime b)
static operator Int64 (DiscreteTime b)
static operator DiscreteTime (double time)
static operator DiscreteTime (float time)
static implicit operator DiscreteTime (Int32 time)
static operator DiscreteTime (Int64 time)
static bool operator== (DiscreteTime lhs, DiscreteTime rhs)
static bool operator!= (DiscreteTime lhs, DiscreteTime rhs)
static bool operator> (DiscreteTime lhs, DiscreteTime rhs)
static bool operator< (DiscreteTime lhs, DiscreteTime rhs)
static bool operator<= (DiscreteTime lhs, DiscreteTime rhs)
static bool operator>= (DiscreteTime lhs, DiscreteTime rhs)
static DiscreteTime operator+ (DiscreteTime lhs, DiscreteTime rhs)
static DiscreteTime operator- (DiscreteTime lhs, DiscreteTime rhs)
static DiscreteTime Min (DiscreteTime lhs, DiscreteTime rhs)
static DiscreteTime Max (DiscreteTime lhs, DiscreteTime rhs)
static double SnapToNearestTick (double time)
static float SnapToNearestTick (float time)
static Int64 GetNearestTick (double time)
Public Attributes
readonly Int64 m_DiscreteTime
Static Public Attributes
const double k_Tick = 1e-12
static readonly DiscreteTime kMaxTime = new DiscreteTime(Int64.MaxValue)
Properties
static double tickValue [get]
Constructor & Destructor Documentation
DiscreteTime() [1/6]
UnityEngine.Timeline.DiscreteTime.DiscreteTime (DiscreteTime time)
Referenced by UnityEngine.Timeline.DiscreteTime.FromTicks(), UnityEngine.Timeline.DiscreteTime.Max(), UnityEngine.Timeline.DiscreteTime.Min(), UnityEngine.Timeline.DiscreteTime.OneTickAfter(), UnityEngine.Timeline.DiscreteTime.OneTickBefore(), UnityEngine.Timeline.DiscreteTime.operator DiscreteTime(), UnityEngine.Timeline.DiscreteTime.operator DiscreteTime(), UnityEngine.Timeline.DiscreteTime.operator DiscreteTime(), UnityEngine.Timeline.DiscreteTime.operator DiscreteTime(), UnityEngine.Timeline.DiscreteTime.operator+(), and UnityEngine.Timeline.DiscreteTime.operator-().
DiscreteTime() [2/6]
UnityEngine.Timeline.DiscreteTime.DiscreteTime (Int64 time)
DiscreteTime() [3/6]
UnityEngine.Timeline.DiscreteTime.DiscreteTime (double time)
DiscreteTime() [4/6]
UnityEngine.Timeline.DiscreteTime.DiscreteTime (float time)
DiscreteTime() [5/6]
UnityEngine.Timeline.DiscreteTime.DiscreteTime (int time)
DiscreteTime() [6/6]
UnityEngine.Timeline.DiscreteTime.DiscreteTime (int frame, double fps)
Member Function Documentation
CompareTo()
int UnityEngine.Timeline.DiscreteTime.CompareTo (object obj)
DoubleToDiscreteTime()
static Int64 UnityEngine.Timeline.DiscreteTime.DoubleToDiscreteTime (double time) static
Referenced by UnityEngine.Timeline.DiscreteTime.DiscreteTime(), UnityEngine.Timeline.DiscreteTime.DiscreteTime(), UnityEngine.Timeline.DiscreteTime.GetNearestTick(), UnityEngine.Timeline.DiscreteTime.IntToDiscreteTime(), and UnityEngine.Timeline.DiscreteTime.SnapToNearestTick().
Equals() [1/2]
bool UnityEngine.Timeline.DiscreteTime.Equals (DiscreteTime other)
Referenced by UnityEngine.Timeline.DiscreteTime.Equals().
Equals() [2/2]
override bool UnityEngine.Timeline.DiscreteTime.Equals (object obj)
FloatToDiscreteTime()
static Int64 UnityEngine.Timeline.DiscreteTime.FloatToDiscreteTime (float time) static
Referenced by UnityEngine.Timeline.DiscreteTime.DiscreteTime(), and UnityEngine.Timeline.DiscreteTime.SnapToNearestTick().
FromTicks()
static DiscreteTime UnityEngine.Timeline.DiscreteTime.FromTicks (Int64 ticks) static
Referenced by UnityEngine.Timeline.RuntimeClip.DisableAt().
GetHashCode()
override int UnityEngine.Timeline.DiscreteTime.GetHashCode ()
GetNearestTick()
static Int64 UnityEngine.Timeline.DiscreteTime.GetNearestTick (double time) static
GetTick()
Int64 UnityEngine.Timeline.DiscreteTime.GetTick ()
IntToDiscreteTime()
static Int64 UnityEngine.Timeline.DiscreteTime.IntToDiscreteTime (int time) static
Referenced by UnityEngine.Timeline.DiscreteTime.DiscreteTime().
Max()
static DiscreteTime UnityEngine.Timeline.DiscreteTime.Max (DiscreteTime lhs, DiscreteTime rhs) static
Min()
static DiscreteTime UnityEngine.Timeline.DiscreteTime.Min (DiscreteTime lhs, DiscreteTime rhs) static
OneTickAfter()
DiscreteTime UnityEngine.Timeline.DiscreteTime.OneTickAfter ()
OneTickBefore()
DiscreteTime UnityEngine.Timeline.DiscreteTime.OneTickBefore ()
operator DiscreteTime() [1/4]
static UnityEngine.Timeline.DiscreteTime.operator DiscreteTime (double time) explicit static
operator DiscreteTime() [2/4]
static UnityEngine.Timeline.DiscreteTime.operator DiscreteTime (float time) explicit static
operator DiscreteTime() [3/4]
static implicit UnityEngine.Timeline.DiscreteTime.operator DiscreteTime (Int32 time) static
operator DiscreteTime() [4/4]
static UnityEngine.Timeline.DiscreteTime.operator DiscreteTime (Int64 time) explicit static
operator double()
static UnityEngine.Timeline.DiscreteTime.operator double (DiscreteTime b) explicit static
operator float()
static UnityEngine.Timeline.DiscreteTime.operator float (DiscreteTime b) explicit static
operator Int64()
static UnityEngine.Timeline.DiscreteTime.operator Int64 (DiscreteTime b) explicit static
operator!=()
static bool UnityEngine.Timeline.DiscreteTime.operator!= (DiscreteTime lhs, DiscreteTime rhs) static
operator+()
static DiscreteTime UnityEngine.Timeline.DiscreteTime.operator+ (DiscreteTime lhs, DiscreteTime rhs) static
operator-()
static DiscreteTime UnityEngine.Timeline.DiscreteTime.operator- (DiscreteTime lhs, DiscreteTime rhs) static
operator<()
static bool UnityEngine.Timeline.DiscreteTime.operator< (DiscreteTime lhs, DiscreteTime rhs) static
operator<=()
static bool UnityEngine.Timeline.DiscreteTime.operator<= (DiscreteTime lhs, DiscreteTime rhs) static
operator==()
static bool UnityEngine.Timeline.DiscreteTime.operator== (DiscreteTime lhs, DiscreteTime rhs) static
operator>()
static bool UnityEngine.Timeline.DiscreteTime.operator> (DiscreteTime lhs, DiscreteTime rhs) static
operator>=()
static bool UnityEngine.Timeline.DiscreteTime.operator>= (DiscreteTime lhs, DiscreteTime rhs) static
SnapToNearestTick() [1/2]
static double UnityEngine.Timeline.DiscreteTime.SnapToNearestTick (double time) static
SnapToNearestTick() [2/2]
static float UnityEngine.Timeline.DiscreteTime.SnapToNearestTick (float time) static
ToDouble()
static double UnityEngine.Timeline.DiscreteTime.ToDouble (Int64 time) static
Referenced by UnityEngine.Timeline.DiscreteTime.operator double(), UnityEngine.Timeline.DiscreteTime.SnapToNearestTick(), and UnityEngine.Timeline.DiscreteTime.ToFloat().
ToFloat()
static float UnityEngine.Timeline.DiscreteTime.ToFloat (Int64 time) static
Referenced by UnityEngine.Timeline.DiscreteTime.operator float(), and UnityEngine.Timeline.DiscreteTime.SnapToNearestTick().
ToString()
override string UnityEngine.Timeline.DiscreteTime.ToString ()
Member Data Documentation
k_Tick
const double UnityEngine.Timeline.DiscreteTime.k_Tick = 1e-12 static
Referenced by UnityEngine.Timeline.DiscreteTime.DoubleToDiscreteTime(), UnityEngine.Timeline.DiscreteTime.FloatToDiscreteTime(), and UnityEngine.Timeline.DiscreteTime.ToDouble().
kMaxTime
readonly DiscreteTime UnityEngine.Timeline.DiscreteTime.kMaxTime = new DiscreteTime(Int64.MaxValue) static
m_DiscreteTime
readonly Int64 UnityEngine.Timeline.DiscreteTime.m_DiscreteTime
Referenced by UnityEngine.Timeline.DiscreteTime.CompareTo(), UnityEngine.Timeline.DiscreteTime.DiscreteTime(), UnityEngine.Timeline.DiscreteTime.DiscreteTime(), UnityEngine.Timeline.DiscreteTime.DiscreteTime(), UnityEngine.Timeline.DiscreteTime.DiscreteTime(), UnityEngine.Timeline.DiscreteTime.DiscreteTime(), UnityEngine.Timeline.DiscreteTime.DiscreteTime(), UnityEngine.Timeline.DiscreteTime.Equals(), UnityEngine.Timeline.DiscreteTime.GetHashCode(), UnityEngine.Timeline.DiscreteTime.GetTick(), UnityEngine.Timeline.DiscreteTime.Max(), UnityEngine.Timeline.DiscreteTime.Min(), UnityEngine.Timeline.DiscreteTime.OneTickAfter(), UnityEngine.Timeline.DiscreteTime.OneTickBefore(), UnityEngine.Timeline.DiscreteTime.operator double(), UnityEngine.Timeline.DiscreteTime.operator float(), UnityEngine.Timeline.DiscreteTime.operator Int64(), UnityEngine.Timeline.DiscreteTime.operator+(), UnityEngine.Timeline.DiscreteTime.operator-(), UnityEngine.Timeline.DiscreteTime.operator<(), UnityEngine.Timeline.DiscreteTime.operator<=(), UnityEngine.Timeline.DiscreteTime.operator==(), UnityEngine.Timeline.DiscreteTime.operator>(), UnityEngine.Timeline.DiscreteTime.operator>=(), and UnityEngine.Timeline.DiscreteTime.ToString().
Property Documentation
tickValue
double UnityEngine.Timeline.DiscreteTime.tickValue static get
Referenced by UnityEngine.Timeline.RuntimeClip.DisableAt(), and UnityEngine.Timeline.RuntimeClip.EvaluateAt().
The documentation for this struct was generated from the following file:
C:/Users/Lykos/Desktop/Projects/Capstone/VRGames/Library/PackageCache/com.unity.timeline@1.6.4/Runtime/DiscreteTime.cs