VRCapstoneGames: Windows.Kinect.CameraSpacePoint Struct Reference
Windows.Kinect.CameraSpacePoint Struct Reference
Public Member Functions
override int GetHashCode ()
override bool Equals (object obj)
bool Equals (CameraSpacePoint obj)
Static Public Member Functions
static bool operator== (CameraSpacePoint a, CameraSpacePoint b)
static bool operator!= (CameraSpacePoint a, CameraSpacePoint b)
Properties
float X [get, set]
float Y [get, set]
float Z [get, set]
Member Function Documentation
Equals() [1/2]
bool Windows.Kinect.CameraSpacePoint.Equals (CameraSpacePoint obj)
Equals() [2/2]
override bool Windows.Kinect.CameraSpacePoint.Equals (object obj)
Referenced by Windows.Kinect.CameraSpacePoint.Equals(), Windows.Kinect.CameraSpacePoint.operator!=(), and Windows.Kinect.CameraSpacePoint.operator==().
GetHashCode()
override int Windows.Kinect.CameraSpacePoint.GetHashCode ()
operator!=()
static bool Windows.Kinect.CameraSpacePoint.operator!= (CameraSpacePoint a, CameraSpacePoint b) static
operator==()
static bool Windows.Kinect.CameraSpacePoint.operator== (CameraSpacePoint a, CameraSpacePoint b) static
Property Documentation
X
float Windows.Kinect.CameraSpacePoint.X get set
Referenced by Windows.Kinect.CameraSpacePoint.Equals(), and Windows.Kinect.CameraSpacePoint.GetHashCode().
Y
float Windows.Kinect.CameraSpacePoint.Y get set
Referenced by Windows.Kinect.CameraSpacePoint.Equals(), and Windows.Kinect.CameraSpacePoint.GetHashCode().
Z
float Windows.Kinect.CameraSpacePoint.Z get set
Referenced by Windows.Kinect.CameraSpacePoint.Equals(), and Windows.Kinect.CameraSpacePoint.GetHashCode().
The documentation for this struct was generated from the following file:
C:/Users/Lykos/Desktop/Projects/Capstone/VRGames/Assets/ThirdParty/Standard Assets/Windows/Kinect/CameraSpacePoint.cs