VRGames: UnityEngine.ProBuilder.PickerOptions Struct Reference
UnityEngine.ProBuilder.PickerOptions Struct Reference
A collection of settings that define how mesh element picking behaves.
Public Member Functions
override bool Equals (object obj)
Evaluates whether the specified object is equivalent to this one.
bool Equals (PickerOptions other)
Evaluates whether the specified PickerOptions object contains the same settings as this one has.
override int GetHashCode ()
Returns the hash code for this object.
Static Public Member Functions
static bool operator== (PickerOptions a, PickerOptions b)
Returns true if the two PickerOptions objects have matching values.
static bool operator!= (PickerOptions a, PickerOptions b)
Returns true if the values for the two PickerOptions objects don't match.
Static Public Attributes
static readonly PickerOptions k_Default
Properties
bool depthTest [get, set]
Gets or sets whether to perform depth testing when testing elements with raycasting.
RectSelectMode rectSelectMode [get, set]
Gets or sets whether to require elements to be completely encompassed by the rect selection (RectSelectMode.Complete) or to allow elements only partially inside the rect selection (RectSelectMode.Partial).
static PickerOptions Default [get]
Represents a set of picking options with default values. By default, the depthTest property is set to true and the rectSelectMode property is set to RectSelectMode.Partial.
Detailed Description
A collection of settings that define how mesh element picking behaves.
Member Function Documentation
Equals() [1/2]
override bool UnityEngine.ProBuilder.PickerOptions.Equals (object obj)
Evaluates whether the specified object is equivalent to this one.
Parameters
obj The object to compare to this object.
Returns
True if both objects are PickerOptions and their property values match; false otherwise.
Referenced by UnityEngine.ProBuilder.PickerOptions.Equals(), UnityEngine.ProBuilder.PickerOptions.operator!=(), and UnityEngine.ProBuilder.PickerOptions.operator==().
Equals() [2/2]
bool UnityEngine.ProBuilder.PickerOptions.Equals (PickerOptions other)
Evaluates whether the specified PickerOptions object contains the same settings as this one has.
Parameters
other The PickerOptions object to compare to this object.
Returns
True if the depthTest and rectSelectMode property values match; false otherwise.
GetHashCode()
override int UnityEngine.ProBuilder.PickerOptions.GetHashCode ()
Returns the hash code for this object.
Returns
A hash code for the current object.
operator!=()
static bool UnityEngine.ProBuilder.PickerOptions.operator!= (PickerOptions a, PickerOptions b) static
Returns true if the values for the two PickerOptions objects don't match.
Parameters
a The first object to compare.
b The second object to compare.
Returns
True if the values for the two PickerOptions objects don't match; false otherwise.
operator==()
static bool UnityEngine.ProBuilder.PickerOptions.operator== (PickerOptions a, PickerOptions b) static
Returns true if the two PickerOptions objects have matching values.
Parameters
a The first object to compare.
b The second object to compare.
Returns
True if the objects have matching values; false otherwise.
Member Data Documentation
k_Default
readonly PickerOptions UnityEngine.ProBuilder.PickerOptions.k_Default static
Initial value:
= new PickerOptions()
        {
            depthTest = true,
            rectSelectMode = RectSelectMode.Partial,
        }
Property Documentation
Default
PickerOptions UnityEngine.ProBuilder.PickerOptions.Default static get
Represents a set of picking options with default values. By default, the depthTest property is set to true and the rectSelectMode property is set to RectSelectMode.Partial.
depthTest
bool UnityEngine.ProBuilder.PickerOptions.depthTest get set
Gets or sets whether to perform depth testing when testing elements with raycasting.
Returns
True to select only visible elements; false to select all elements regardless of visibility.
Referenced by UnityEngine.ProBuilder.PickerOptions.Equals(), and UnityEngine.ProBuilder.PickerOptions.GetHashCode().
rectSelectMode
RectSelectMode UnityEngine.ProBuilder.PickerOptions.rectSelectMode get set
Gets or sets whether to require elements to be completely encompassed by the rect selection (RectSelectMode.Complete) or to allow elements only partially inside the rect selection (RectSelectMode.Partial).
Does not apply to vertex picking.
Referenced by UnityEngine.ProBuilder.PickerOptions.Equals(), and UnityEngine.ProBuilder.PickerOptions.GetHashCode().
The documentation for this struct was generated from the following file:
C:/Users/Lykos/Desktop/Projects/Capstone/VRGames/Library/PackageCache/com.unity.probuilder@5.0.6/Runtime/Core/SelectionPickerRenderer.cs