VRCapstoneGames: UnityEngine.InputSystem.Utilities.InternedString Struct Reference
UnityEngine.InputSystem.Utilities.InternedString Struct Reference
Wraps around a string to allow for faster case-insensitive string comparisons while preserving original casing.
Public Member Functions
InternedString (string text)
Initialize the InternedString with the given string. Except if the string is null or empty, this requires an internal lookup (this is the reason the conversion from string to InternedString is not implicit).
bool IsEmpty ()
Whether the string is empty, i.e. has a length of zero. If so, the InternedString corresponds to default(InternedString).
string ToLower ()
Return a lower-case version of the string.
override bool Equals (object obj)
Compare the InternedString to given object.
bool Equals (InternedString other)
Compare two InternedStrings for equality. They are equal if, ignoring case and culture, their text is equal.
int CompareTo (InternedString other)
override int GetHashCode ()
Compute a hash code for the string. Equivalent to string.GetHashCode.
override string ToString ()
Static Public Member Functions
static bool operator== (InternedString a, InternedString b)
static bool operator!= (InternedString a, InternedString b)
static bool operator== (InternedString a, string b)
static bool operator!= (InternedString a, string b)
static bool operator== (string a, InternedString b)
static bool operator!= (string a, InternedString b)
static bool operator< (InternedString left, InternedString right)
static bool operator> (InternedString left, InternedString right)
static implicit operator string (InternedString str)
Convert the given InternedString back to a string. Equivalent to ToString().
Properties
int length [get]
Length of the string in characters. Equivalent to string.Length.
Detailed Description
Wraps around a string to allow for faster case-insensitive string comparisons while preserving original casing.
Unlike string, InternedStrings can be compared with a quick Object.ReferenceEquals comparison and without actually comparing string contents.
Also, unlike string, the representation of an empty and a null string is identical.
Note that all string comparisons using InternedStrings are both case-insensitive and culture-insensitive.
There is a non-zero cost to creating an InternedString. The first time a new unique InternedString is encountered, there may also be a GC heap allocation.
Constructor & Destructor Documentation
InternedString()
UnityEngine.InputSystem.Utilities.InternedString.InternedString (string text)
Initialize the InternedString with the given string. Except if the string is null or empty, this requires an internal lookup (this is the reason the conversion from string to InternedString is not implicit).
Parameters
text A string. Can be null.
The InternedString preserves the original casing. Meaning that ToString() will return the string as it was supplied through text . However, comparison between two InternedStrings is still always just a reference comparisons regardless of case and culture.
var lowerCase = new InternedString("text");
var upperCase = new InternedString("TEXT");
// This is still just a quick reference comparison:
if (lowerCase == upperCase)
    Debug.Log("True");
// But this prints the strings in their original casing.
Debug.Log(lowerCase);
Debug.Log(upperCase);
Member Function Documentation
CompareTo()
int UnityEngine.InputSystem.Utilities.InternedString.CompareTo (InternedString other)
Equals() [1/2]
bool UnityEngine.InputSystem.Utilities.InternedString.Equals (InternedString other)
Compare two InternedStrings for equality. They are equal if, ignoring case and culture, their text is equal.
Parameters
other Another InternedString.
Returns
True if the two InternedStrings are equal.
This operation is cheap and does not involve an actual string comparison. Instead, a simple Object.ReferenceEquals comparison is performed.
Equals() [2/2]
override bool UnityEngine.InputSystem.Utilities.InternedString.Equals (object obj)
Compare the InternedString to given object.
Parameters
obj An object. If it is a string, performs a string comparison. If it is an InternedString, performs an InternedString-comparison. Otherwise returns false.
Returns
True if the InternedString is equal to obj .
Referenced by UnityEngine.InputSystem.Utilities.InternedString.operator!=(), and UnityEngine.InputSystem.Utilities.InternedString.operator==().
GetHashCode()
override int UnityEngine.InputSystem.Utilities.InternedString.GetHashCode ()
Compute a hash code for the string. Equivalent to string.GetHashCode.
Returns
A hash code.
IsEmpty()
bool UnityEngine.InputSystem.Utilities.InternedString.IsEmpty ()
Whether the string is empty, i.e. has a length of zero. If so, the InternedString corresponds to default(InternedString).
Returns
True if the string is empty.
Referenced by UnityEngine.InputSystem.Layouts.InputControlLayout.ControlItem.Merge(), UnityEngine.InputSystem.Layouts.InputControlLayout.MergeLayout(), UnityEngine.InputSystem.InputControlExtensions.DeviceBuilder.WithControlAlias(), UnityEngine.InputSystem.InputControlExtensions.DeviceBuilder.WithControlUsage(), UnityEngine.InputSystem.InputControlExtensions.ControlBuilder.WithLayout(), and UnityEngine.InputSystem.InputControlExtensions.DeviceBuilder.WithLayout().
operator string()
static implicit UnityEngine.InputSystem.Utilities.InternedString.operator string (InternedString str) static
Convert the given InternedString back to a string. Equivalent to ToString().
Parameters
str An InternedString.
Returns
A string.
operator!=() [1/3]
static bool UnityEngine.InputSystem.Utilities.InternedString.operator!= (InternedString a, InternedString b) static
operator!=() [2/3]
static bool UnityEngine.InputSystem.Utilities.InternedString.operator!= (InternedString a, string b) static
operator!=() [3/3]
static bool UnityEngine.InputSystem.Utilities.InternedString.operator!= (string a, InternedString b) static
operator<()
static bool UnityEngine.InputSystem.Utilities.InternedString.operator< (InternedString left, InternedString right) static
operator==() [1/3]
static bool UnityEngine.InputSystem.Utilities.InternedString.operator== (InternedString a, InternedString b) static
operator==() [2/3]
static bool UnityEngine.InputSystem.Utilities.InternedString.operator== (InternedString a, string b) static
operator==() [3/3]
static bool UnityEngine.InputSystem.Utilities.InternedString.operator== (string a, InternedString b) static
operator>()
static bool UnityEngine.InputSystem.Utilities.InternedString.operator> (InternedString left, InternedString right) static
ToLower()
string UnityEngine.InputSystem.Utilities.InternedString.ToLower ()
Return a lower-case version of the string.
Returns
A lower-case version of the string.
InternedStrings internally always store a lower-case version which means that this method does not incur a GC heap allocation cost.
Referenced by UnityEngine.InputSystem.Layouts.InputControlLayout.MergeLayout().
ToString()
override string UnityEngine.InputSystem.Utilities.InternedString.ToString ()
Referenced by UnityEngine.InputSystem.Utilities.InternedString.operator string().
Property Documentation
length
int UnityEngine.InputSystem.Utilities.InternedString.length get
Length of the string in characters. Equivalent to string.Length.
Length of the string.
The documentation for this struct was generated from the following file:
C:/Users/Lykos/Desktop/Projects/Capstone/VRGames/Library/PackageCache/com.unity.inputsystem@1.3.0/InputSystem/Utilities/InternedString.cs