VRCapstoneGames: UnityEngine.InputSystem.Utilities.JsonParser.JsonString Struct Reference
UnityEngine.InputSystem.Utilities.JsonParser.JsonString Struct Reference
Public Member Functions
override string ToString ()
bool Equals (JsonString other)
override bool Equals (object obj)
override int GetHashCode ()
Static Public Member Functions
static bool operator== (JsonString left, JsonString right)
static bool operator!= (JsonString left, JsonString right)
static implicit operator JsonString (string str)
Public Attributes
Substring text
bool hasEscapes
Member Function Documentation
Equals() [1/2]
bool UnityEngine.InputSystem.Utilities.JsonParser.JsonString.Equals (JsonString other)
Referenced by UnityEngine.InputSystem.Utilities.JsonParser.JsonString.operator!=(), and UnityEngine.InputSystem.Utilities.JsonParser.JsonString.operator==().
Equals() [2/2]
override bool UnityEngine.InputSystem.Utilities.JsonParser.JsonString.Equals (object obj)
GetHashCode()
override int UnityEngine.InputSystem.Utilities.JsonParser.JsonString.GetHashCode ()
Referenced by UnityEngine.InputSystem.Utilities.JsonParser.JsonValue.GetHashCode().
operator JsonString()
static implicit UnityEngine.InputSystem.Utilities.JsonParser.JsonString.operator JsonString (string str) static
operator!=()
static bool UnityEngine.InputSystem.Utilities.JsonParser.JsonString.operator!= (JsonString left, JsonString right) static
operator==()
static bool UnityEngine.InputSystem.Utilities.JsonParser.JsonString.operator== (JsonString left, JsonString right) static
ToString()
override string UnityEngine.InputSystem.Utilities.JsonParser.JsonString.ToString ()
Referenced by UnityEngine.InputSystem.Utilities.JsonParser.JsonValue.ToString().
Member Data Documentation
hasEscapes
bool UnityEngine.InputSystem.Utilities.JsonParser.JsonString.hasEscapes
Referenced by UnityEngine.InputSystem.Utilities.JsonParser.JsonString.Equals(), UnityEngine.InputSystem.Utilities.JsonParser.JsonString.GetHashCode(), and UnityEngine.InputSystem.Utilities.JsonParser.JsonString.ToString().
text
Substring UnityEngine.InputSystem.Utilities.JsonParser.JsonString.text
Referenced by UnityEngine.InputSystem.Utilities.JsonParser.JsonString.Equals(), UnityEngine.InputSystem.Utilities.JsonParser.JsonString.GetHashCode(), UnityEngine.InputSystem.Utilities.JsonParser.JsonString.operator JsonString(), and UnityEngine.InputSystem.Utilities.JsonParser.JsonString.ToString().
The documentation for this struct was generated from the following file:
C:/Users/Lykos/Desktop/Projects/Capstone/VRGames/Library/PackageCache/com.unity.inputsystem@1.3.0/InputSystem/Utilities/JsonParser.cs