VRCapstoneGames: Windows.Kinect.PointF Struct Reference
Windows.Kinect.PointF Struct Reference
Public Member Functions
override int GetHashCode ()
override bool Equals (object obj)
bool Equals (ColorSpacePoint obj)
Static Public Member Functions
static bool operator== (PointF a, PointF b)
static bool operator!= (PointF a, PointF b)
Properties
float X [get, set]
float Y [get, set]
Member Function Documentation
Equals() [1/2]
bool Windows.Kinect.PointF.Equals (ColorSpacePoint obj)
Equals() [2/2]
override bool Windows.Kinect.PointF.Equals (object obj)
Referenced by Windows.Kinect.PointF.Equals(), Windows.Kinect.PointF.operator!=(), and Windows.Kinect.PointF.operator==().
GetHashCode()
override int Windows.Kinect.PointF.GetHashCode ()
operator!=()
static bool Windows.Kinect.PointF.operator!= (PointF a, PointF b) static
operator==()
static bool Windows.Kinect.PointF.operator== (PointF a, PointF b) static
Property Documentation
X
float Windows.Kinect.PointF.X get set
Referenced by Windows.Kinect.PointF.Equals(), and Windows.Kinect.PointF.GetHashCode().
Y
float Windows.Kinect.PointF.Y get set
Referenced by Windows.Kinect.PointF.Equals(), and Windows.Kinect.PointF.GetHashCode().
The documentation for this struct was generated from the following file:
C:/Users/Lykos/Desktop/Projects/Capstone/VRGames/Assets/ThirdParty/Standard Assets/KinectSpecialCases.cs