VRCapstoneGames: OVRSimpleJSON.JSONNode.Enumerator Struct Reference
OVRSimpleJSON.JSONNode.Enumerator Struct Reference
Public Member Functions
Enumerator (List< JSONNode >.Enumerator aArrayEnum)
Enumerator (Dictionary< string, JSONNode >.Enumerator aDictEnum)
bool MoveNext ()
Properties
bool IsValid [get]
KeyValuePair< string, JSONNode > Current [get]
Constructor & Destructor Documentation
Enumerator() [1/2]
OVRSimpleJSON.JSONNode.Enumerator.Enumerator (List< JSONNode >::Enumerator aArrayEnum)
Enumerator() [2/2]
OVRSimpleJSON.JSONNode.Enumerator.Enumerator (Dictionary< string, JSONNode >::Enumerator aDictEnum)
Member Function Documentation
MoveNext()
bool OVRSimpleJSON.JSONNode.Enumerator.MoveNext ()
Referenced by OVRSimpleJSON.JSONNode.Enumerator.MoveNext(), OVRSimpleJSON.JSONNode.ValueEnumerator.MoveNext(), OVRSimpleJSON.JSONNode.KeyEnumerator.MoveNext(), and OVRSimpleJSON.JSONNode.LinqEnumerator.MoveNext().
Property Documentation
Current
KeyValuePair<string, JSONNode> OVRSimpleJSON.JSONNode.Enumerator.Current get
IsValid
bool OVRSimpleJSON.JSONNode.Enumerator.IsValid get
The documentation for this struct was generated from the following file:
C:/Users/Lykos/Desktop/Projects/Capstone/VRGames/Assets/ThirdParty/Oculus/VR/ThirdParty/SimpleJSON.cs