VRCapstoneGames: UnityEngine.InputSystem.Utilities.NameAndParameters Struct Reference
UnityEngine.InputSystem.Utilities.NameAndParameters Struct Reference
A combination of a name and an optional list of named parameter values. For example, "Clamp(min=1,max=2)".
Public Member Functions
override string ToString ()
Static Public Member Functions
static IEnumerable< NameAndParameters > ParseMultiple (string text)
static NameAndParameters Parse (string text)
Properties
string name [get, set]
ReadOnlyArray< NamedValue > parameters [get, set]
Detailed Description
A combination of a name and an optional list of named parameter values. For example, "Clamp(min=1,max=2)".
Member Function Documentation
Parse()
static NameAndParameters UnityEngine.InputSystem.Utilities.NameAndParameters.Parse (string text) static
Referenced by UnityEngine.InputSystem.InputBinding.GetNameOfComposite().
ParseMultiple()
static IEnumerable< NameAndParameters > UnityEngine.InputSystem.Utilities.NameAndParameters.ParseMultiple (string text) static
Referenced by UnityEngine.InputSystem.Utilities.NameAndParameters.ParseMultiple(), UnityEngine.InputSystem.InputBinding.ToDisplayString(), and UnityEngine.InputSystem.Layouts.InputControlLayout.Builder.ControlBuilder.WithProcessors().
ToString()
override string UnityEngine.InputSystem.Utilities.NameAndParameters.ToString ()
Property Documentation
name
string UnityEngine.InputSystem.Utilities.NameAndParameters.name get set
Referenced by UnityEngine.InputSystem.Utilities.NameAndParameters.ToString().
parameters
ReadOnlyArray<NamedValue> UnityEngine.InputSystem.Utilities.NameAndParameters.parameters get set
Referenced by UnityEngine.InputSystem.Utilities.NameAndParameters.ToString().
The documentation for this struct was generated from the following file:
C:/Users/Lykos/Desktop/Projects/Capstone/VRGames/Library/PackageCache/com.unity.inputsystem@1.3.0/InputSystem/Utilities/NameAndParameters.cs