VRCapstoneGames: UnityEditor.Timeline.ClipBorder Struct Reference
UnityEditor.Timeline.ClipBorder Struct Reference
Public Member Functions
ClipBorder (Color color, float thickness)
Static Public Member Functions
static ClipBorder Recording ()
static ClipBorder Selection ()
static ClipBorder Default ()
Public Attributes
readonly Color color
readonly float thickness
Static Public Attributes
const float k_ClipSelectionBorder = 1.0f
const float k_ClipRecordingBorder = 2.0f
Constructor & Destructor Documentation
ClipBorder()
UnityEditor.Timeline.ClipBorder.ClipBorder (Color color, float thickness)
Referenced by UnityEditor.Timeline.ClipBorder.Default(), UnityEditor.Timeline.ClipBorder.Recording(), and UnityEditor.Timeline.ClipBorder.Selection().
Member Function Documentation
Default()
static ClipBorder UnityEditor.Timeline.ClipBorder.Default () static
Recording()
static ClipBorder UnityEditor.Timeline.ClipBorder.Recording () static
Selection()
static ClipBorder UnityEditor.Timeline.ClipBorder.Selection () static
Referenced by UnityEditor.Timeline.TimelineClipGUI.DrawGhostClip(), and UnityEditor.Timeline.TimelineClipGUI.DrawInvalidClip().
Member Data Documentation
color
readonly Color UnityEditor.Timeline.ClipBorder.color
Referenced by UnityEditor.Timeline.ClipBorder.ClipBorder().
k_ClipRecordingBorder
const float UnityEditor.Timeline.ClipBorder.k_ClipRecordingBorder = 2.0f static
Referenced by UnityEditor.Timeline.ClipBorder.Recording().
k_ClipSelectionBorder
const float UnityEditor.Timeline.ClipBorder.k_ClipSelectionBorder = 1.0f static
Referenced by UnityEditor.Timeline.ClipBorder.Default(), and UnityEditor.Timeline.ClipBorder.Selection().
thickness
readonly float UnityEditor.Timeline.ClipBorder.thickness
Referenced by UnityEditor.Timeline.ClipBorder.ClipBorder().
The documentation for this struct was generated from the following file:
C:/Users/Lykos/Desktop/Projects/Capstone/VRGames/Library/PackageCache/com.unity.timeline@1.6.4/Editor/treeview/Drawers/ClipDrawer.cs