VRGames: UnityEditor.Timeline.UndoScope Struct Reference
UnityEditor.Timeline.UndoScope Struct Reference
Disposable scope object used to collect multiple items for Undo. Automatically filters out duplicates.
Public Member Functions
UndoScope (string name)
void Dispose ()
void AddObject (UnityEngine.Object asset)
void AddClip (TimelineClip clip, bool includeAsset)
void Add (IEnumerable< TrackAsset > tracks)
void Add (IEnumerable< TimelineClip > clips, bool includeAssets)
void Add (IEnumerable< IMarker > markers)
Detailed Description
Disposable scope object used to collect multiple items for Undo. Automatically filters out duplicates.
Constructor & Destructor Documentation
UndoScope()
UnityEditor.Timeline.UndoScope.UndoScope (string name)
Member Function Documentation
Add() [1/3]
void UnityEditor.Timeline.UndoScope.Add (IEnumerable< IMarker > markers)
Add() [2/3]
void UnityEditor.Timeline.UndoScope.Add (IEnumerable< TimelineClip > clips, bool includeAssets)
Add() [3/3]
void UnityEditor.Timeline.UndoScope.Add (IEnumerable< TrackAsset > tracks)
AddClip()
void UnityEditor.Timeline.UndoScope.AddClip (TimelineClip clip, bool includeAsset)
Referenced by UnityEditor.Timeline.UndoScope.Add().
AddObject()
void UnityEditor.Timeline.UndoScope.AddObject (UnityEngine::Object asset)
Referenced by UnityEditor.Timeline.UndoScope.Add(), and UnityEditor.Timeline.UndoScope.Add().
Dispose()
void UnityEditor.Timeline.UndoScope.Dispose ()
The documentation for this struct was generated from the following file:
C:/Users/Lykos/Desktop/Projects/Capstone/VRGames/Library/PackageCache/com.unity.timeline@1.6.4/Editor/Undo/UndoScope.cs