VRCapstoneGames: Windows.Kinect.JointOrientation Struct Reference
Windows.Kinect.JointOrientation Struct Reference
Public Member Functions
override int GetHashCode ()
override bool Equals (object obj)
bool Equals (JointOrientation obj)
Static Public Member Functions
static bool operator== (JointOrientation a, JointOrientation b)
static bool operator!= (JointOrientation a, JointOrientation b)
Properties
Windows.Kinect.JointType JointType [get, set]
Windows.Kinect.Vector4 Orientation [get, set]
Member Function Documentation
Equals() [1/2]
bool Windows.Kinect.JointOrientation.Equals (JointOrientation obj)
Equals() [2/2]
override bool Windows.Kinect.JointOrientation.Equals (object obj)
Referenced by Windows.Kinect.JointOrientation.Equals(), Windows.Kinect.JointOrientation.operator!=(), and Windows.Kinect.JointOrientation.operator==().
GetHashCode()
override int Windows.Kinect.JointOrientation.GetHashCode ()
operator!=()
static bool Windows.Kinect.JointOrientation.operator!= (JointOrientation a, JointOrientation b) static
operator==()
static bool Windows.Kinect.JointOrientation.operator== (JointOrientation a, JointOrientation b) static
Property Documentation
JointType
Windows.Kinect.JointType Windows.Kinect.JointOrientation.JointType get set
Referenced by Windows.Kinect.JointOrientation.Equals().
Orientation
Windows.Kinect.Vector4 Windows.Kinect.JointOrientation.Orientation get set
Referenced by Windows.Kinect.JointOrientation.Equals().
The documentation for this struct was generated from the following file:
C:/Users/Lykos/Desktop/Projects/Capstone/VRGames/Assets/ThirdParty/Standard Assets/Windows/Kinect/JointOrientation.cs