VRCapstoneGames: UnityEngine.XR.Interaction.Toolkit.InteractionLayerMask Struct Reference
UnityEngine.XR.Interaction.Toolkit.InteractionLayerMask Struct Reference
Specifies Interaction Layers to use in XR interactions.
Public Member Functions
void OnAfterDeserialize ()
See ISerializationCallbackReceiver.
void OnBeforeSerialize ()
See ISerializationCallbackReceiver.
Static Public Member Functions
static implicit operator int (InteractionLayerMask mask)
Implicitly converts an InteractionLayerMask to an integer.
static implicit operator InteractionLayerMask (int intVal)
Implicitly converts an integer to an InteractionLayerMask.
static string LayerToName (int layer)
Given a layer number, returns the name of the Interaction Layer as defined in either a Builtin or a User Layer.
static int NameToLayer (string layerName)
Given an Interaction Layer name, returns the index as defined by either a Builtin or a User Layer.
static int GetMask (params string[] layerNames)
Given a set of Interaction Layer names, returns the equivalent mask for all of them.
Public Attributes
uint m_Bits
int m_Mask
Properties
int value [get, set]
Converts an interaction layer mask value to an integer value.
Detailed Description
Specifies Interaction Layers to use in XR interactions.
Member Function Documentation
GetMask()
static int UnityEngine.XR.Interaction.Toolkit.InteractionLayerMask.GetMask (params string[] layerNames) static
Given a set of Interaction Layer names, returns the equivalent mask for all of them.
Parameters
layerNames The interaction layer names to be converted to a mask
Returns
Returns the equivalent mask for all the supplied Interaction Layer names.
Exceptions
ArgumentNullException
LayerToName()
static string UnityEngine.XR.Interaction.Toolkit.InteractionLayerMask.LayerToName (int layer) static
Given a layer number, returns the name of the Interaction Layer as defined in either a Builtin or a User Layer.
Parameters
layer The interaction layer bit index.
Returns
Returns the name of the supplied Interaction Layer value.
NameToLayer()
static int UnityEngine.XR.Interaction.Toolkit.InteractionLayerMask.NameToLayer (string layerName) static
Given an Interaction Layer name, returns the index as defined by either a Builtin or a User Layer.
Parameters
layerName The interaction layer name.
Returns
Returns the index of the supplied Interaction Layer name.
Referenced by UnityEditor.XR.Interaction.Toolkit.Tests.InteractionLayerUpdaterTest.EverythingMaskUpdate(), UnityEngine.XR.Interaction.Toolkit.InteractionLayerMask.GetMask(), and UnityEditor.XR.Interaction.Toolkit.Tests.InteractionLayerUpdaterTest.InteractableUpdate().
OnAfterDeserialize()
void UnityEngine.XR.Interaction.Toolkit.InteractionLayerMask.OnAfterDeserialize ()
See ISerializationCallbackReceiver.
OnBeforeSerialize()
void UnityEngine.XR.Interaction.Toolkit.InteractionLayerMask.OnBeforeSerialize ()
See ISerializationCallbackReceiver.
operator int()
static implicit UnityEngine.XR.Interaction.Toolkit.InteractionLayerMask.operator int (InteractionLayerMask mask) static
Implicitly converts an InteractionLayerMask to an integer.
Parameters
mask The mask to be converted.
Returns
Returns the integer value of the Interaction Layer Mask.
operator InteractionLayerMask()
static implicit UnityEngine.XR.Interaction.Toolkit.InteractionLayerMask.operator InteractionLayerMask (int intVal) static
Implicitly converts an integer to an InteractionLayerMask.
Parameters
intVal The mask value.
Returns
Returns the Interaction Layer Mask for the integer value.
Member Data Documentation
m_Bits
uint UnityEngine.XR.Interaction.Toolkit.InteractionLayerMask.m_Bits
Referenced by UnityEngine.XR.Interaction.Toolkit.InteractionLayerMask.OnAfterDeserialize().
m_Mask
int UnityEngine.XR.Interaction.Toolkit.InteractionLayerMask.m_Mask
Referenced by UnityEngine.XR.Interaction.Toolkit.InteractionLayerMask.OnAfterDeserialize(), and UnityEngine.XR.Interaction.Toolkit.InteractionLayerMask.operator int().
Property Documentation
value
int UnityEngine.XR.Interaction.Toolkit.InteractionLayerMask.value get set
Converts an interaction layer mask value to an integer value.
Returns
Returns the integer value equivalent to this Interaction Layer Mask.
The documentation for this struct was generated from the following file:
C:/Users/Lykos/Desktop/Projects/Capstone/VRGames/Library/PackageCache/com.unity.xr.interaction.toolkit@2.0.2/Runtime/Interaction/Layers/InteractionLayerMask.cs