VRGames: Facebook.WitAi.Windows.WitSimplePropertyDrawer Class Reference
Facebook.WitAi.Windows.WitSimplePropertyDrawer Class Reference abstract
Public Member Functions
override float GetPropertyHeight (SerializedProperty property, GUIContent label)
override void OnGUI (Rect position, SerializedProperty property, GUIContent label)
Protected Member Functions
string GetKeyFieldName ()
string GetValueFieldName ()
virtual string GetFieldStringValue (SerializedProperty property, string fieldName)
virtual string GetFieldStringValue (SerializedProperty subfieldProperty)
Member Function Documentation
GetFieldStringValue() [1/2]
virtual string Facebook.WitAi.Windows.WitSimplePropertyDrawer.GetFieldStringValue (SerializedProperty property, string fieldName) protected virtual
Referenced by Facebook.WitAi.Windows.WitSimplePropertyDrawer.GetFieldStringValue(), and Facebook.WitAi.Windows.WitSimplePropertyDrawer.OnGUI().
GetFieldStringValue() [2/2]
virtual string Facebook.WitAi.Windows.WitSimplePropertyDrawer.GetFieldStringValue (SerializedProperty subfieldProperty) protected virtual
GetKeyFieldName()
string Facebook.WitAi.Windows.WitSimplePropertyDrawer.GetKeyFieldName () abstract protected
Referenced by Facebook.WitAi.Windows.WitSimplePropertyDrawer.OnGUI().
GetPropertyHeight()
override float Facebook.WitAi.Windows.WitSimplePropertyDrawer.GetPropertyHeight (SerializedProperty property, GUIContent label)
GetValueFieldName()
string Facebook.WitAi.Windows.WitSimplePropertyDrawer.GetValueFieldName () abstract protected
Referenced by Facebook.WitAi.Windows.WitSimplePropertyDrawer.OnGUI().
OnGUI()
override void Facebook.WitAi.Windows.WitSimplePropertyDrawer.OnGUI (Rect position, SerializedProperty property, GUIContent label)
The documentation for this class was generated from the following file:
C:/Users/Lykos/Desktop/Projects/Capstone/VRGames/Assets/ThirdParty/Oculus/Voice/Lib/Wit.ai/Scripts/Editor/Windows/PropertyDrawers/WitSimplePropertyDrawer.cs