VRGames: TimerManager Class Reference
TimerManager Class Reference
Public Member Functions
void resumeTimer ()
void pauseTimer ()
void startTimer ()
void stopTimer ()
void startCountdown (float time)
Public Attributes
float timerUpdateInterval = .1f
Member Function Documentation
pauseTimer()
void TimerManager.pauseTimer ()
Referenced by stopTimer().
resumeTimer()
void TimerManager.resumeTimer ()
Referenced by startTimer().
startCountdown()
void TimerManager.startCountdown (float time)
References stopTimer().
startTimer()
void TimerManager.startTimer ()
References resumeTimer(), and stopTimer().
stopTimer()
void TimerManager.stopTimer ()
References pauseTimer().
Referenced by startCountdown(), and startTimer().
Member Data Documentation
timerUpdateInterval
float TimerManager.timerUpdateInterval = .1f
The documentation for this class was generated from the following file:
C:/Users/Lykos/Desktop/Projects/Capstone/VRGames/Assets/Shared/Scripts/Managers/TimerManager.cs