VRGames: UnityEngine.XR.Management.Tests.Standalone.StandaloneSubsystemDescriptor Class Reference
UnityEngine.XR.Management.Tests.Standalone.StandaloneSubsystemDescriptor Class Reference
Public Member Functions
StandaloneSubsystemDescriptor (string id, System.Type subsystemImplType)
Static Public Member Functions
static void Create (Providing.StandaloneSubsystemParams parms)
Constructor & Destructor Documentation
StandaloneSubsystemDescriptor()
UnityEngine.XR.Management.Tests.Standalone.StandaloneSubsystemDescriptor.StandaloneSubsystemDescriptor (string id, System::Type subsystemImplType)
Referenced by UnityEngine.XR.Management.Tests.Standalone.StandaloneSubsystemDescriptor.Create().
Member Function Documentation
Create()
static void UnityEngine.XR.Management.Tests.Standalone.StandaloneSubsystemDescriptor.Create (Providing::StandaloneSubsystemParams parms) static
Referenced by UnityEditor.XR.Management.Tests.EditorTests.OneTimeSetUp(), and UnityEngine.XR.Management.Tests.RuntimeLoaderTests.OneTimeSetUp().
The documentation for this class was generated from the following file:
C:/Users/Lykos/Desktop/Projects/Capstone/VRGames/Library/PackageCache/com.unity.xr.management@4.2.1/Tests/StandaloneSubsystem/StandaloneSubsystemDescriptor.cs