VRGames: Oculus.Interaction.PoseDetection.TransformFeatureValueProvider Class Reference
Oculus.Interaction.PoseDetection.TransformFeatureValueProvider Class Reference
Classes
struct TransformProperties
Static Public Member Functions
static float GetValue (TransformFeature transformFeature, TransformJointData transformJointData, TransformConfig transformConfig)
static Vector3 GetHandVectorForFeature (TransformFeature transformFeature, in TransformJointData transformJointData, in TransformConfig transformConfig)
static Vector3 GetTargetVectorForFeature (TransformFeature transformFeature, in TransformJointData transformJointData, in TransformConfig transformConfig)
Member Function Documentation
GetHandVectorForFeature()
static Vector3 Oculus.Interaction.PoseDetection.TransformFeatureValueProvider.GetHandVectorForFeature (TransformFeature transformFeature, in TransformJointData transformJointData, in TransformConfig transformConfig) static
Referenced by Oculus.Interaction.PoseDetection.TransformFeatureStateProvider.GetFeatureVectorAndWristPos(), and Oculus.Interaction.PoseDetection.TransformFeatureValueProvider.GetHandVectorForFeature().
GetTargetVectorForFeature()
static Vector3 Oculus.Interaction.PoseDetection.TransformFeatureValueProvider.GetTargetVectorForFeature (TransformFeature transformFeature, in TransformJointData transformJointData, in TransformConfig transformConfig) static
Referenced by Oculus.Interaction.PoseDetection.TransformFeatureStateProvider.GetFeatureVectorAndWristPos(), and Oculus.Interaction.PoseDetection.TransformFeatureValueProvider.GetTargetVectorForFeature().
GetValue()
static float Oculus.Interaction.PoseDetection.TransformFeatureValueProvider.GetValue (TransformFeature transformFeature, TransformJointData transformJointData, TransformConfig transformConfig) static
Referenced by Oculus.Interaction.PoseDetection.TransformFeatureStateProvider.GetFeatureValue().
The documentation for this class was generated from the following file:
C:/Users/Lykos/Desktop/Projects/Capstone/VRGames/Assets/ThirdParty/Oculus/Interaction/Runtime/Scripts/PoseDetection/TransformFeatureValueProvider.cs