VRGames: Classes.Managers.LavaClimbGameplayManager Class Reference
Classes.Managers.LavaClimbGameplayManager Class Reference
Public Member Functions
override void onWinConditionPointsReached ()
void onStart ()
void onRockGrabbed (GameObject rock)
void onRockReleased (GameObject rock)
void killRock (GameObject rock)
void respawnRock (GameObject rock)
override void reset ()
Public Member Functions inherited from GameplayManager
GameSettingsSO GetGameSettings ()
void setDifficulty (int newDif)
int getDifficulty ()
void Update ()
virtual void RefreshSettings ()
void PauseGame ()
void ResumeGame ()
void IncreaseDifficulty ()
void DecreaseDifficulty ()
Public Attributes
GameObject rockPrefab
GameObject climbingWall
float secondsTilDespawn = 2
Public Attributes inherited from GameplayManager
int difficulty = 1
int winConditionPoints = 50
int maxTime
GameSettingsSO gameSettings
int playerLives
Additional Inherited Members
Static Public Member Functions inherited from GameplayManager
static GameplayManager getManager ()
Protected Member Functions inherited from GameplayManager
void Start ()
Properties inherited from GameplayManager
static GameplayManager Instance [get]
Member Function Documentation
killRock()
void Classes.Managers.LavaClimbGameplayManager.killRock (GameObject rock)
Referenced by Classes.Managers.LavaClimbGameplayManager.reset(), and Classes.Managers.LavaClimbGameplayManager.respawnRock().
onRockGrabbed()
void Classes.Managers.LavaClimbGameplayManager.onRockGrabbed (GameObject rock)
References PointsManager.addPoints(), PointsManager.getPoints(), and Classes.Managers.PlayerManager.movePlayer().
Referenced by Classes.ClimbingRock.onGrab().
onRockReleased()
void Classes.Managers.LavaClimbGameplayManager.onRockReleased (GameObject rock)
Referenced by Classes.ClimbingRock.onRelease().
onStart()
void Classes.Managers.LavaClimbGameplayManager.onStart ()
onWinConditionPointsReached()
override void Classes.Managers.LavaClimbGameplayManager.onWinConditionPointsReached () virtual
Reimplemented from GameplayManager.
References PointsManager.updateScoreboardMessage().
reset()
override void Classes.Managers.LavaClimbGameplayManager.reset () virtual
Reimplemented from GameplayManager.
References Classes.Managers.LavaClimbGameplayManager.killRock().
respawnRock()
void Classes.Managers.LavaClimbGameplayManager.respawnRock (GameObject rock)
References Classes.Managers.LavaClimbGameplayManager.killRock().
Member Data Documentation
climbingWall
GameObject Classes.Managers.LavaClimbGameplayManager.climbingWall
rockPrefab
GameObject Classes.Managers.LavaClimbGameplayManager.rockPrefab
secondsTilDespawn
float Classes.Managers.LavaClimbGameplayManager.secondsTilDespawn = 2
The documentation for this class was generated from the following file:
C:/Users/Lykos/Desktop/Projects/Capstone/VRGames/Assets/Shared/Scripts/Managers/LavaClimbGameplayManager.cs