VRGames: MasterArchitectureGameplayManager Class Reference
MasterArchitectureGameplayManager Class Reference
Public Member Functions
void onFirstPointReached ()
override void onWinConditionPointsReached ()
void onPlaneGrabbed (GameObject plane)
void onPlaneReleased (GameObject plane)
void killPlane (GameObject plane)
void respawnPlane (GameObject plane)
override void reset ()
Public Member Functions inherited from GameplayManager
GameSettingsSO GetGameSettings ()
void setDifficulty (int newDif)
int getDifficulty ()
void Update ()
virtual void RefreshSettings ()
void PauseGame ()
void ResumeGame ()
void IncreaseDifficulty ()
void DecreaseDifficulty ()
Public Attributes
int maxHoops
GameObject planePrefab
GameObject hoopPrefab
GameObject hoopSpawn
GameObject leftTable
GameObject rightTable
float secondsTilDespawn = 3
Public Attributes inherited from GameplayManager
int difficulty = 1
int winConditionPoints = 50
int maxTime
GameSettingsSO gameSettings
int playerLives
Additional Inherited Members
Static Public Member Functions inherited from GameplayManager
static GameplayManager getManager ()
Protected Member Functions inherited from GameplayManager
void Start ()
Properties inherited from GameplayManager
static GameplayManager Instance [get]
Member Function Documentation
killPlane()
void MasterArchitectureGameplayManager.killPlane (GameObject plane)
Referenced by reset(), and respawnPlane().
onFirstPointReached()
void MasterArchitectureGameplayManager.onFirstPointReached ()
onPlaneGrabbed()
void MasterArchitectureGameplayManager.onPlaneGrabbed (GameObject plane)
References reset().
onPlaneReleased()
void MasterArchitectureGameplayManager.onPlaneReleased (GameObject plane)
onWinConditionPointsReached()
override void MasterArchitectureGameplayManager.onWinConditionPointsReached () virtual
Reimplemented from GameplayManager.
References PointsManager.updateScoreboardMessage().
reset()
override void MasterArchitectureGameplayManager.reset () virtual
Reimplemented from GameplayManager.
References killPlane().
Referenced by onPlaneGrabbed().
respawnPlane()
void MasterArchitectureGameplayManager.respawnPlane (GameObject plane)
References killPlane().
Member Data Documentation
hoopPrefab
GameObject MasterArchitectureGameplayManager.hoopPrefab
hoopSpawn
GameObject MasterArchitectureGameplayManager.hoopSpawn
leftTable
GameObject MasterArchitectureGameplayManager.leftTable
maxHoops
int MasterArchitectureGameplayManager.maxHoops
planePrefab
GameObject MasterArchitectureGameplayManager.planePrefab
rightTable
GameObject MasterArchitectureGameplayManager.rightTable
secondsTilDespawn
float MasterArchitectureGameplayManager.secondsTilDespawn = 3
The documentation for this class was generated from the following file:
C:/Users/Lykos/Desktop/Projects/Capstone/VRGames/Assets/Shared/Scripts/Managers/MasterArchitectureGameplayManager.cs