VRGames: OvrAvatarTextureCopyManager Class Reference
OvrAvatarTextureCopyManager Class Reference
Classes
struct FallbackTextureSet
struct TextureSet
Public Member Functions
OvrAvatarTextureCopyManager ()
void Update ()
int GetTextureCount ()
void CopyTexture (Texture src, Texture dst, int mipLevel, int mipSize, int dstElement, bool useQueue=true)
void AddTextureIDToTextureSet (int gameobjectID, ulong textureID, bool isSingleMesh)
void DeleteTextureSet (int gameobjectID)
void CheckFallbackTextureSet (ovrAvatarAssetLevelOfDetail lod)
Public Attributes
FallbackTextureSet[] FallbackTextureSets = new FallbackTextureSet[(int)ovrAvatarAssetLevelOfDetail.Highest + 1]
Constructor & Destructor Documentation
OvrAvatarTextureCopyManager()
OvrAvatarTextureCopyManager.OvrAvatarTextureCopyManager ()
Member Function Documentation
AddTextureIDToTextureSet()
void OvrAvatarTextureCopyManager.AddTextureIDToTextureSet (int gameobjectID, ulong textureID, bool isSingleMesh)
CheckFallbackTextureSet()
void OvrAvatarTextureCopyManager.CheckFallbackTextureSet (ovrAvatarAssetLevelOfDetail lod)
CopyTexture()
void OvrAvatarTextureCopyManager.CopyTexture (Texture src, Texture dst, int mipLevel, int mipSize, int dstElement, bool useQueue = true)
Referenced by CopyTexture(), and Update().
DeleteTextureSet()
void OvrAvatarTextureCopyManager.DeleteTextureSet (int gameobjectID)
GetTextureCount()
int OvrAvatarTextureCopyManager.GetTextureCount ()
Update()
void OvrAvatarTextureCopyManager.Update ()
Member Data Documentation
FallbackTextureSets
FallbackTextureSet [] OvrAvatarTextureCopyManager.FallbackTextureSets = new FallbackTextureSet[(int)ovrAvatarAssetLevelOfDetail.Highest + 1]
Referenced by CheckFallbackTextureSet().
The documentation for this class was generated from the following file:
C:/Users/Lykos/Desktop/Projects/Capstone/VRGames/Assets/ThirdParty/Oculus/Avatar/Scripts/OvrAvatarTextureCopyManager.cs