VRGames: BalloonsGame.GameManager Class Reference
BalloonsGame.GameManager Class Reference
Public Member Functions
GameSettingsSO GetGameSettings ()
Protected Member Functions
void Restart ()
void AllLivesLostHandler (object sender, EventArgs e)
void GoalReachedHandler (object sender, EventArgs e)
Protected Attributes
GameSettingsSO gameSettings
Properties
static GameManager Instance [get]
Member Function Documentation
AllLivesLostHandler()
void BalloonsGame.GameManager.AllLivesLostHandler (object sender, EventArgs e) protected
References BalloonsGame.GameManager.Restart().
GetGameSettings()
GameSettingsSO BalloonsGame.GameManager.GetGameSettings ()
References BalloonsGame.GameManager.gameSettings.
GoalReachedHandler()
void BalloonsGame.GameManager.GoalReachedHandler (object sender, EventArgs e) protected
References BalloonsGame.GameManager.Restart().
Restart()
void BalloonsGame.GameManager.Restart () protected
Referenced by BalloonsGame.GameManager.AllLivesLostHandler(), and BalloonsGame.GameManager.GoalReachedHandler().
Member Data Documentation
gameSettings
GameSettingsSO BalloonsGame.GameManager.gameSettings protected
Referenced by BalloonsGame.GameManager.GetGameSettings().
Property Documentation
Instance
GameManager BalloonsGame.GameManager.Instance static get
The documentation for this class was generated from the following file:
C:/Users/Lykos/Desktop/Projects/Capstone/VRGames/Assets/BalloonGame/Scripts/Managers/GameManager.cs