VRGames: UnityEngine.UI.Shadow Class Reference
UnityEngine.UI.Shadow Class Reference
Adds an outline to a graphic using IVertexModifier.
Public Member Functions
override void ModifyMesh (VertexHelper vh)
Protected Member Functions
Shadow ()
void ApplyShadowZeroAlloc (List< UIVertex > verts, Color32 color, int start, int end, float x, float y)
void ApplyShadow (List< UIVertex > verts, Color32 color, int start, int end, float x, float y)
Duplicate vertices from start to end and turn them into shadows with the given offset.
Properties
Color effectColor [get, set]
Color for the effect.
Vector2 effectDistance [get, set]
How far is the shadow from the graphic.
bool useGraphicAlpha [get, set]
Should the shadow inherit the alpha from the graphic?
Detailed Description
Adds an outline to a graphic using IVertexModifier.
Constructor & Destructor Documentation
Shadow()
UnityEngine.UI.Shadow.Shadow () protected
Member Function Documentation
ApplyShadow()
void UnityEngine.UI.Shadow.ApplyShadow (List< UIVertex > verts, Color32 color, int start, int end, float x, float y) protected
Duplicate vertices from start to end and turn them into shadows with the given offset.
Parameters
verts Vert list to copy
color Shadow color
start The start index in the verts list
end The end index in the vers list
x The shadows x offset
y The shadows y offset
Referenced by UnityEngine.UI.Shadow.ModifyMesh().
ApplyShadowZeroAlloc()
void UnityEngine.UI.Shadow.ApplyShadowZeroAlloc (List< UIVertex > verts, Color32 color, int start, int end, float x, float y) protected
Referenced by UnityEngine.UI.Shadow.ApplyShadow(), and UnityEngine.UI.Outline.ModifyMesh().
ModifyMesh()
override void UnityEngine.UI.Shadow.ModifyMesh (VertexHelper vh)
Property Documentation
effectColor
Color UnityEngine.UI.Shadow.effectColor get set
Color for the effect.
Referenced by UnityEngine.UI.Outline.ModifyMesh(), and UnityEngine.UI.Shadow.ModifyMesh().
effectDistance
Vector2 UnityEngine.UI.Shadow.effectDistance get set
How far is the shadow from the graphic.
Referenced by UnityEngine.UI.Outline.ModifyMesh(), and UnityEngine.UI.Shadow.ModifyMesh().
useGraphicAlpha
bool UnityEngine.UI.Shadow.useGraphicAlpha get set
Should the shadow inherit the alpha from the graphic?
The documentation for this class was generated from the following file:
C:/Users/Lykos/Desktop/Projects/Capstone/VRGames/Library/PackageCache/com.unity.ugui@1.0.0/Runtime/UI/Core/VertexModifiers/Shadow.cs