VRGames: BalloonsGame.Balloon Class Reference
BalloonsGame.Balloon Class Reference
Public Member Functions
delegate void BalloonPoppedEventHandler (string senderTag)
virtual void OnTriggerEnter (Collider other)
virtual void PlayEffects (bool persist)
virtual void OnMouseDown ()
virtual void PopBalloonEvent ()
virtual void ExtraPopEffects ()
Public Member Functions inherited from BalloonsGame._BaseBalloon
GameObject GetSpawnLoc ()
virtual void SetSpawnLoc (GameObject spawnLoc)
Public Attributes
string messageOverride = ""
bool isPersistent = false
Protected Member Functions
void AddPoints ()
bool IsCorrectDart (GameObject dart)
Events
static BalloonPoppedEventHandler OnPop
Additional Inherited Members
Protected Attributes inherited from BalloonsGame._BaseBalloon
float floatStrength
float rotationSpeed
int pointValue
GameObject spawnLoc
Detailed Description
The Balloon class represent a generic balloon. A generic balloon is a balloon that is worth one point. In the normal and endless modes, it is the only balloon that results in loss of lives.
Member Function Documentation
AddPoints()
void BalloonsGame.Balloon.AddPoints () protected
The AddPoints method adds the point value of the balloon to the total points and to the left or right points depending on where the balloon was spawned.
Referenced by BalloonsGame.Balloon.OnMouseDown(), BalloonsGame.Balloon.OnTriggerEnter(), BalloonsGame.Balloon_Stream.OnTriggerEnter(), BalloonsGame.Balloon_Stream_Powerup.OnTriggerEnter(), and BalloonsGame.Balloon_Target_Base.TargetHit().
BalloonPoppedEventHandler()
delegate void BalloonsGame.Balloon.BalloonPoppedEventHandler (string senderTag)
ExtraPopEffects()
virtual void BalloonsGame.Balloon.ExtraPopEffects () virtual
The ExtraPopEffects method is where extra effects (like adding extra lives for the life balloon) go.
Reimplemented in BalloonsGame.Balloon_Onion, BalloonsGame.Balloon_RestoreLife, BalloonsGame.Balloon_Stream, BalloonsGame.Balloon_Stream_Powerup, and BalloonsGame.Balloon_Target_Base.
Referenced by BalloonsGame.Balloon.OnMouseDown(), and BalloonsGame.Balloon.OnTriggerEnter().
IsCorrectDart()
bool BalloonsGame.Balloon.IsCorrectDart (GameObject dart) protected
The IsCorrectDart method returns true or false depending on whether the balloon and the dart are on the same side.
Parameters
dart The dart to be checked against.
OnMouseDown()
virtual void BalloonsGame.Balloon.OnMouseDown () virtual
The OnMouseDown method is for testing purposes. It is useful for testing on the computer rather than in the headset.
Reimplemented in BalloonsGame.Balloon_Target_Base.
OnTriggerEnter()
virtual void BalloonsGame.Balloon.OnTriggerEnter (Collider other) virtual
The OnTriggerEnter method handles the logic for when another object collides with the object this script is attached to.
Parameters
other The object that collided with the collider of the gameobject this script is attached to.
Reimplemented in BalloonsGame.Balloon_Stream, BalloonsGame.Balloon_Stream_Powerup, and BalloonsGame.Balloon_Target_Base.
PlayEffects()
virtual void BalloonsGame.Balloon.PlayEffects (bool persist) virtual
The PlayEffects method handles the effects of a balloon when it is popped.
Parameters
persist determines whether the effects should be destroyed or not upon completion.
Referenced by BalloonsGame.Balloon.OnMouseDown(), BalloonsGame.Balloon.OnTriggerEnter(), BalloonsGame.Balloon_Stream.OnTriggerEnter(), BalloonsGame.Balloon_Stream_Powerup.OnTriggerEnter(), and BalloonsGame.Balloon_Target_Base.TargetHit().
PopBalloonEvent()
virtual void BalloonsGame.Balloon.PopBalloonEvent () virtual
The PopBalloonEvent method handles any events that must take place for any type of balloon that is popped.
Referenced by BalloonsGame.Balloon.ExtraPopEffects(), BalloonsGame.Balloon_Onion.ExtraPopEffects(), BalloonsGame.Balloon_RestoreLife.ExtraPopEffects(), BalloonsGame.Balloon_Stream.ExtraPopEffects(), BalloonsGame.Balloon_Stream_Powerup.ExtraPopEffects(), and BalloonsGame.Balloon_Target_Base.ExtraPopEffects().
Member Data Documentation
isPersistent
bool BalloonsGame.Balloon.isPersistent = false
Referenced by BalloonsGame.Balloon_Stream.OnTriggerEnter(), BalloonsGame.Balloon_Stream_Powerup.OnTriggerEnter(), and BalloonsGame.Balloon_Target_Base.TargetHit().
messageOverride
string BalloonsGame.Balloon.messageOverride = ""
Event Documentation
OnPop
BalloonPoppedEventHandler BalloonsGame.Balloon.OnPop static
Referenced by BalloonsGame.Balloon.PopBalloonEvent().
The documentation for this class was generated from the following file:
C:/Users/Lykos/Desktop/Projects/Capstone/VRGames/Assets/BalloonGame/Scripts/Balloons/Balloon.cs