VRGames: UnityEditor.ProBuilder.PositionTool Class Reference
UnityEditor.ProBuilder.PositionTool Class Reference abstract
Classes
class MeshAndPositions
Protected Member Functions
void DrawDeltaInfo (string text)
override void DoToolGUI ()
void Apply (Matrix4x4 delta)
Protected Member Functions inherited from UnityEditor.ProBuilder.VertexManipulationTool
float GetSnapValueForAxis (Vector3Mask axes)
virtual void OnToolEngaged ()
virtual void OnToolDisengaged ()
void BeginEdit (string undoMessage)
void FinishEdit ()
Properties
bool showHandleInfo [get]
Properties inherited from UnityEditor.ProBuilder.VertexManipulationTool
static PivotPoint pivotPoint [get]
static HandleOrientation handleOrientation [get, set]
bool isEditing [get]
Event currentEvent [get]
Vector3 handlePositionOrigin [get]
Quaternion handleRotationOriginInverse [get]
Quaternion handleRotationOrigin [get]
Vector3 snapValue [get]
bool snapAxisConstraint [get]
Additional Inherited Members
Public Member Functions inherited from UnityEditor.ProBuilder.VertexManipulationTool
override void OnToolGUI (EditorWindow window)
Static Protected Member Functions inherited from UnityEditor.ProBuilder.VertexManipulationTool
static bool FindNearestVertex (Vector2 mousePosition, out Vector3 vertex)
Find the nearest vertex among all visible objects.
Protected Attributes inherited from UnityEditor.ProBuilder.VertexManipulationTool
Vector3 m_HandlePosition
Quaternion m_HandleRotation
Events inherited from UnityEditor.ProBuilder.VertexManipulationTool
static Action< IEnumerable< ProBuilderMesh > > afterMeshModification
static Action< IEnumerable< ProBuilderMesh > > beforeMeshModification
Member Function Documentation
Apply()
void UnityEditor.ProBuilder.PositionTool.Apply (Matrix4x4 delta) protected
Referenced by UnityEditor.ProBuilder.ProbuilderScaleTool.DoToolGUI().
DoToolGUI()
override void UnityEditor.ProBuilder.PositionTool.DoToolGUI () protected virtual
Reimplemented from UnityEditor.ProBuilder.VertexManipulationTool.
Reimplemented in UnityEditor.ProBuilder.ProbuilderMoveTool, UnityEditor.ProBuilder.ProbuilderRotateTool, and UnityEditor.ProBuilder.ProbuilderScaleTool.
DrawDeltaInfo()
void UnityEditor.ProBuilder.PositionTool.DrawDeltaInfo (string text) protected
Referenced by UnityEditor.ProBuilder.ProbuilderMoveTool.DoToolGUI(), UnityEditor.ProBuilder.ProbuilderRotateTool.DoToolGUI(), and UnityEditor.ProBuilder.ProbuilderScaleTool.DoToolGUI().
Property Documentation
showHandleInfo
bool UnityEditor.ProBuilder.PositionTool.showHandleInfo get protected
Referenced by UnityEditor.ProBuilder.ProbuilderMoveTool.DoToolGUI(), UnityEditor.ProBuilder.ProbuilderRotateTool.DoToolGUI(), and UnityEditor.ProBuilder.ProbuilderScaleTool.DoToolGUI().
The documentation for this class was generated from the following file:
C:/Users/Lykos/Desktop/Projects/Capstone/VRGames/Library/PackageCache/com.unity.probuilder@5.0.6/Editor/EditorCore/PositionTool.cs