VRGames: UnityEngine.XR.InteractionSubsystems.XRGestureSubsystem.Provider Class Reference
UnityEngine.XR.InteractionSubsystems.XRGestureSubsystem.Provider Class Reference abstract
The API this subsystem uses to interop with different provider implementations.
Public Member Functions
void Start ()
Invoked to start or resume a Gesture subsystem.
void Stop ()
Invoked to stop a running Gesture subsystem.
void Update ()
Perform any per-frame update logic here.
virtual void Destroy ()
Stop the Gesture subsystem and destroy all associated resources.
Protected Attributes
NativeArray< ActivateGestureEvent > m_ActivateGestureEvents = new NativeArray<ActivateGestureEvent>(0, Allocator.Persistent)
Properties
NativeArray< ActivateGestureEvent > activateGestureEvents [get]
Detailed Description
The API this subsystem uses to interop with different provider implementations.
Member Function Documentation
Destroy()
virtual void UnityEngine.XR.InteractionSubsystems.XRGestureSubsystem.Provider.Destroy () virtual
Stop the Gesture subsystem and destroy all associated resources.
Referenced by UnityEngine.XR.InteractionSubsystems.XRGestureSubsystem.Destroy().
Start()
void UnityEngine.XR.InteractionSubsystems.XRGestureSubsystem.Provider.Start () abstract
Invoked to start or resume a Gesture subsystem.
Referenced by UnityEngine.XR.InteractionSubsystems.XRGestureSubsystem.Start().
Stop()
void UnityEngine.XR.InteractionSubsystems.XRGestureSubsystem.Provider.Stop () abstract
Invoked to stop a running Gesture subsystem.
Referenced by UnityEngine.XR.InteractionSubsystems.XRGestureSubsystem.Stop().
Update()
void UnityEngine.XR.InteractionSubsystems.XRGestureSubsystem.Provider.Update () abstract
Perform any per-frame update logic here.
Referenced by UnityEngine.XR.InteractionSubsystems.XRGestureSubsystem.Update().
Member Data Documentation
m_ActivateGestureEvents
NativeArray<ActivateGestureEvent> UnityEngine.XR.InteractionSubsystems.XRGestureSubsystem.Provider.m_ActivateGestureEvents = new NativeArray<ActivateGestureEvent>(0, Allocator.Persistent) protected
Referenced by UnityEngine.XR.InteractionSubsystems.XRGestureSubsystem.Provider.Destroy().
Property Documentation
activateGestureEvents
NativeArray<ActivateGestureEvent> UnityEngine.XR.InteractionSubsystems.XRGestureSubsystem.Provider.activateGestureEvents get
The documentation for this class was generated from the following file:
C:/Users/Lykos/Desktop/Projects/Capstone/VRGames/Library/PackageCache/com.unity.xr.interactionsubsystems@1.0.1/Runtime/GestureSubsystem/XRGestureSubsystem.cs