VRGames: UnityEngine.UI.ToggleGroup Class Reference
UnityEngine.UI.ToggleGroup Class Reference
A component that represents a group of UI.Toggles.
Public Member Functions
void NotifyToggleOn (Toggle toggle, bool sendCallback=true)
Notify the group that the given toggle is enabled.
void UnregisterToggle (Toggle toggle)
Unregister a toggle from the group.
void RegisterToggle (Toggle toggle)
Register a toggle with the toggle group so it is watched for changes and notified if another toggle in the group changes.
void EnsureValidState ()
Ensure that the toggle group still has a valid state. This is only relevant when a ToggleGroup is Started or a Toggle has been deleted from the group.
bool AnyTogglesOn ()
Are any of the toggles on?
IEnumerable< Toggle > ActiveToggles ()
Returns the toggles in this group that are active.
Toggle GetFirstActiveToggle ()
Returns the toggle that is the first in the list of active toggles.
void SetAllTogglesOff (bool sendCallback=true)
Switch all toggles off.
Public Member Functions inherited from UnityEngine.EventSystems.UIBehaviour
virtual bool IsActive ()
Returns true if the GameObject and the Component are active.
bool IsDestroyed ()
Returns true if the native representation of the behaviour has been destroyed.
Protected Member Functions
ToggleGroup ()
override void Start ()
Because all the Toggles have registered themselves in the OnEnabled, Start should check to make sure at least one Toggle is active in groups that do not AllowSwitchOff.
override void OnEnable ()
Protected Member Functions inherited from UnityEngine.EventSystems.UIBehaviour
virtual void Awake ()
virtual void OnDisable ()
virtual void OnDestroy ()
virtual void OnRectTransformDimensionsChange ()
This callback is called when the dimensions of an associated RectTransform change. It is always called before Awake, OnEnable, or Start. The call is also made to all child RectTransforms, regardless of whether their dimensions change (which depends on how they are anchored).
virtual void OnBeforeTransformParentChanged ()
virtual void OnTransformParentChanged ()
virtual void OnDidApplyAnimationProperties ()
virtual void OnCanvasGroupChanged ()
virtual void OnCanvasHierarchyChanged ()
Called when the state of the parent Canvas is changed.
Protected Attributes
List< Toggle > m_Toggles = new List<Toggle>()
Properties
bool allowSwitchOff [get, set]
Is it allowed that no toggle is switched on?
Detailed Description
A component that represents a group of UI.Toggles.
When using a group reference the group from a UI.Toggle. Only one member of a group can be active at a time.
Constructor & Destructor Documentation
ToggleGroup()
UnityEngine.UI.ToggleGroup.ToggleGroup () protected
Member Function Documentation
ActiveToggles()
IEnumerable< Toggle > UnityEngine.UI.ToggleGroup.ActiveToggles ()
Returns the toggles in this group that are active.
Returns
The active toggles in the group.
Toggles belonging to this group but are not active either because their GameObject is inactive or because the Toggle component is disabled, are not returned as part of the list.
Referenced by ToggleTest.ToggleGroupTests.DisabledToggleGroupDoesntControlChildren(), UnityEngine.UI.ToggleGroup.EnsureValidState(), and UnityEngine.UI.ToggleGroup.GetFirstActiveToggle().
AnyTogglesOn()
bool UnityEngine.UI.ToggleGroup.AnyTogglesOn ()
Are any of the toggles on?
Returns
Are and of the toggles on?
Referenced by UnityEngine.UI.ToggleGroup.EnsureValidState(), and UnityEditor.UI.ToggleEditor.OnInspectorGUI().
EnsureValidState()
void UnityEngine.UI.ToggleGroup.EnsureValidState ()
Ensure that the toggle group still has a valid state. This is only relevant when a ToggleGroup is Started or a Toggle has been deleted from the group.
Referenced by UnityEngine.UI.ToggleGroup.OnEnable(), and UnityEngine.UI.ToggleGroup.Start().
GetFirstActiveToggle()
Toggle UnityEngine.UI.ToggleGroup.GetFirstActiveToggle ()
Returns the toggle that is the first in the list of active toggles.
Returns
The first active toggle from m_Toggles
Get the active toggle for this group. As the group
Referenced by UnityEngine.UI.ToggleGroup.EnsureValidState().
NotifyToggleOn()
void UnityEngine.UI.ToggleGroup.NotifyToggleOn (Toggle toggle, bool sendCallback = true)
Notify the group that the given toggle is enabled.
Parameters
toggle The toggle that got triggered on.
sendCallback If other toggles should send onValueChanged.
Referenced by UnityEngine.UI.ToggleGroup.EnsureValidState(), and UnityEditor.UI.ToggleEditor.OnInspectorGUI().
OnEnable()
override void UnityEngine.UI.ToggleGroup.OnEnable () protected virtual
Reimplemented from UnityEngine.EventSystems.UIBehaviour.
RegisterToggle()
void UnityEngine.UI.ToggleGroup.RegisterToggle (Toggle toggle)
Register a toggle with the toggle group so it is watched for changes and notified if another toggle in the group changes.
Parameters
toggle The toggle to register with the group.
SetAllTogglesOff()
void UnityEngine.UI.ToggleGroup.SetAllTogglesOff (bool sendCallback = true)
Switch all toggles off.
This method can be used to switch all toggles off, regardless of whether the allowSwitchOff property is enabled or not.
Start()
override void UnityEngine.UI.ToggleGroup.Start () protected virtual
Because all the Toggles have registered themselves in the OnEnabled, Start should check to make sure at least one Toggle is active in groups that do not AllowSwitchOff.
Reimplemented from UnityEngine.EventSystems.UIBehaviour.
UnregisterToggle()
void UnityEngine.UI.ToggleGroup.UnregisterToggle (Toggle toggle)
Unregister a toggle from the group.
Parameters
toggle The toggle to remove.
Member Data Documentation
m_Toggles
List<Toggle> UnityEngine.UI.ToggleGroup.m_Toggles = new List<Toggle>() protected
Referenced by UnityEngine.UI.ToggleGroup.ActiveToggles(), UnityEngine.UI.ToggleGroup.AnyTogglesOn(), UnityEngine.UI.ToggleGroup.EnsureValidState(), UnityEngine.UI.ToggleGroup.NotifyToggleOn(), UnityEngine.UI.ToggleGroup.RegisterToggle(), UnityEngine.UI.ToggleGroup.SetAllTogglesOff(), ToggleTest.TestableToggleGroup.ToggleListContains(), and UnityEngine.UI.ToggleGroup.UnregisterToggle().
Property Documentation
allowSwitchOff
bool UnityEngine.UI.ToggleGroup.allowSwitchOff get set
Is it allowed that no toggle is switched on?
If this setting is enabled, pressing the toggle that is currently switched on will switch it off, so that no toggle is switched on. If this setting is disabled, pressing the toggle that is currently switched on will not change its state. Note that even if allowSwitchOff is false, the Toggle Group will not enforce its constraint right away if no toggles in the group are switched on when the scene is loaded or when the group is instantiated. It will only prevent the user from switching a toggle off.
Referenced by UnityEngine.UI.ToggleGroup.EnsureValidState(), and UnityEditor.UI.ToggleEditor.OnInspectorGUI().
The documentation for this class was generated from the following file:
C:/Users/Lykos/Desktop/Projects/Capstone/VRGames/Library/PackageCache/com.unity.ugui@1.0.0/Runtime/UI/Core/ToggleGroup.cs