VRGames: UnityEngine.ProBuilder.AssetIdRemapUtility.AssetIdRemapObject Class Reference
UnityEngine.ProBuilder.AssetIdRemapUtility.AssetIdRemapObject Class Reference
Public Member Functions
void Clear (Origin origin)
void Delete (IEnumerable< AssetIdentifierTuple > entries)
void Merge (IEnumerable< AssetIdentifierTuple > entries)
Public Attributes
List< string > sourceDirectory = new List<string>()
string destinationDirectory = null
List< AssetIdentifierTuple > map = new List<AssetIdentifierTuple>()
Properties
AssetIdentifierTuple this[int i] [get, set]
Member Function Documentation
Clear()
void UnityEngine.ProBuilder.AssetIdRemapUtility.AssetIdRemapObject.Clear (Origin origin)
Delete()
void UnityEngine.ProBuilder.AssetIdRemapUtility.AssetIdRemapObject.Delete (IEnumerable< AssetIdentifierTuple > entries)
Merge()
void UnityEngine.ProBuilder.AssetIdRemapUtility.AssetIdRemapObject.Merge (IEnumerable< AssetIdentifierTuple > entries)
Member Data Documentation
destinationDirectory
string UnityEngine.ProBuilder.AssetIdRemapUtility.AssetIdRemapObject.destinationDirectory = null
Referenced by UnityEngine.ProBuilder.AssetIdRemapUtility.AssetIdRemapObject.Clear().
map
List<AssetIdentifierTuple> UnityEngine.ProBuilder.AssetIdRemapUtility.AssetIdRemapObject.map = new List<AssetIdentifierTuple>()
Referenced by UnityEngine.ProBuilder.AssetIdRemapUtility.AssetIdRemapObject.Clear(), UnityEngine.ProBuilder.AssetIdRemapUtility.AssetIdRemapObject.Delete(), and UnityEngine.ProBuilder.AssetIdRemapUtility.AssetIdRemapObject.Merge().
sourceDirectory
List<string> UnityEngine.ProBuilder.AssetIdRemapUtility.AssetIdRemapObject.sourceDirectory = new List<string>()
Referenced by UnityEngine.ProBuilder.AssetIdRemapUtility.AssetIdRemapObject.Clear().
Property Documentation
this[int i]
AssetIdentifierTuple UnityEngine.ProBuilder.AssetIdRemapUtility.AssetIdRemapObject.this[int i] get set
The documentation for this class was generated from the following file:
C:/Users/Lykos/Desktop/Projects/Capstone/VRGames/Library/PackageCache/com.unity.probuilder@5.0.6/AssetIdRemapUtility/Editor/AssetId.cs