VRGames: UnityEngine.ProBuilder.KdTree.PriorityQueue< TItem, TPriority > Class Template Reference
UnityEngine.ProBuilder.KdTree.PriorityQueue< TItem, TPriority > Class Template Reference
Public Member Functions
PriorityQueue (int capacity, ITypeMath< TPriority > priorityMath)
void Enqueue (TItem item, TPriority priority)
TItem Dequeue ()
TItem GetHighest ()
TPriority GetHighestPriority ()
Properties
int Count [get]
Properties inherited from UnityEngine.ProBuilder.KdTree.IPriorityQueue< TItem, TPriority >
Constructor & Destructor Documentation
PriorityQueue()
UnityEngine.ProBuilder.KdTree.PriorityQueue< TItem, TPriority >.PriorityQueue (int capacity, ITypeMath< TPriority > priorityMath)
Member Function Documentation
Dequeue()
TItem UnityEngine.ProBuilder.KdTree.PriorityQueue< TItem, TPriority >.Dequeue ()
Implements UnityEngine.ProBuilder.KdTree.IPriorityQueue< TItem, TPriority >.
Referenced by UnityEngine.ProBuilder.KdTree.NearestNeighbourList< TItem, TDistance >.Add(), and UnityEngine.ProBuilder.KdTree.NearestNeighbourList< TItem, TDistance >.RemoveFurtherest().
Enqueue()
void UnityEngine.ProBuilder.KdTree.PriorityQueue< TItem, TPriority >.Enqueue (TItem item, TPriority priority)
Implements UnityEngine.ProBuilder.KdTree.IPriorityQueue< TItem, TPriority >.
Referenced by UnityEngine.ProBuilder.KdTree.NearestNeighbourList< TItem, TDistance >.Add().
GetHighest()
TItem UnityEngine.ProBuilder.KdTree.PriorityQueue< TItem, TPriority >.GetHighest ()
Referenced by UnityEngine.ProBuilder.KdTree.NearestNeighbourList< TItem, TDistance >.GetFurtherest().
GetHighestPriority()
TPriority UnityEngine.ProBuilder.KdTree.PriorityQueue< TItem, TPriority >.GetHighestPriority ()
Referenced by UnityEngine.ProBuilder.KdTree.NearestNeighbourList< TItem, TDistance >.Add(), and UnityEngine.ProBuilder.KdTree.NearestNeighbourList< TItem, TDistance >.GetFurtherestDistance().
Property Documentation
Count
int UnityEngine.ProBuilder.KdTree.PriorityQueue< TItem, TPriority >.Count get
Implements UnityEngine.ProBuilder.KdTree.IPriorityQueue< TItem, TPriority >.
Referenced by UnityEngine.ProBuilder.KdTree.NearestNeighbourList< TItem, TDistance >.Add().
The documentation for this class was generated from the following file:
C:/Users/Lykos/Desktop/Projects/Capstone/VRGames/Library/PackageCache/com.unity.probuilder@5.0.6/External/KdTree/KdTreeLib/PriorityQueue.cs