VRGames: UnityEngine.ProBuilder.Poly2Tri.AdvancingFront Class Reference
UnityEngine.ProBuilder.Poly2Tri.AdvancingFront Class Reference
Public Member Functions
AdvancingFront (AdvancingFrontNode head, AdvancingFrontNode tail)
void AddNode (AdvancingFrontNode node)
void RemoveNode (AdvancingFrontNode node)
override string ToString ()
AdvancingFrontNode LocateNode (TriangulationPoint point)
We use a balancing tree to locate a node smaller or equal to given key value (in theory)
AdvancingFrontNode LocatePoint (TriangulationPoint point)
This implementation will use simple node traversal algorithm to find a point on the front.
Public Attributes
AdvancingFrontNode Head
AdvancingFrontNode Tail
Protected Attributes
AdvancingFrontNode Search
Detailed Description
Author
Thomas Åhlen (thahl.nosp@m.en@g.nosp@m.mail..nosp@m.com)
Constructor & Destructor Documentation
AdvancingFront()
UnityEngine.ProBuilder.Poly2Tri.AdvancingFront.AdvancingFront (AdvancingFrontNode head, AdvancingFrontNode tail)
Member Function Documentation
AddNode()
void UnityEngine.ProBuilder.Poly2Tri.AdvancingFront.AddNode (AdvancingFrontNode node)
Referenced by UnityEngine.ProBuilder.Poly2Tri.DTSweepContext.AddNode(), UnityEngine.ProBuilder.Poly2Tri.AdvancingFront.AdvancingFront(), and UnityEngine.ProBuilder.Poly2Tri.DTSweepContext.CreateAdvancingFront().
LocateNode()
AdvancingFrontNode UnityEngine.ProBuilder.Poly2Tri.AdvancingFront.LocateNode (TriangulationPoint point)
We use a balancing tree to locate a node smaller or equal to given key value (in theory)
Referenced by UnityEngine.ProBuilder.Poly2Tri.AdvancingFront.LocateNode(), and UnityEngine.ProBuilder.Poly2Tri.DTSweepContext.LocateNode().
LocatePoint()
AdvancingFrontNode UnityEngine.ProBuilder.Poly2Tri.AdvancingFront.LocatePoint (TriangulationPoint point)
This implementation will use simple node traversal algorithm to find a point on the front.
Referenced by UnityEngine.ProBuilder.Poly2Tri.DTSweepContext.MapTriangleToNodes().
RemoveNode()
void UnityEngine.ProBuilder.Poly2Tri.AdvancingFront.RemoveNode (AdvancingFrontNode node)
Referenced by UnityEngine.ProBuilder.Poly2Tri.DTSweepContext.RemoveNode().
ToString()
override string UnityEngine.ProBuilder.Poly2Tri.AdvancingFront.ToString ()
Member Data Documentation
Head
AdvancingFrontNode UnityEngine.ProBuilder.Poly2Tri.AdvancingFront.Head
Referenced by UnityEngine.ProBuilder.Poly2Tri.DTSweepContext.CreateAdvancingFront(), and UnityEngine.ProBuilder.Poly2Tri.AdvancingFront.ToString().
Search
AdvancingFrontNode UnityEngine.ProBuilder.Poly2Tri.AdvancingFront.Search protected
Referenced by UnityEngine.ProBuilder.Poly2Tri.AdvancingFront.LocatePoint().
Tail
AdvancingFrontNode UnityEngine.ProBuilder.Poly2Tri.AdvancingFront.Tail
Referenced by UnityEngine.ProBuilder.Poly2Tri.DTSweepContext.CreateAdvancingFront(), and UnityEngine.ProBuilder.Poly2Tri.AdvancingFront.ToString().
The documentation for this class was generated from the following file:
C:/Users/Lykos/Desktop/Projects/Capstone/VRGames/Library/PackageCache/com.unity.probuilder@5.0.6/External/Poly2Tri/Triangulation/Delaunay/Sweep/AdvancingFront.cs