VRGames: OvrAvatar Class Reference
OvrAvatar Class Reference
Classes
class PacketEventArgs
Public Types
enum HandType { Right , Left , Max }
enum HandJoint {
HandBase , IndexBase , IndexTip , ThumbBase ,
ThumbTip , Max
}
Public Member Functions
void AssetLoadedCallback (OvrAvatarAsset asset)
void CombinedMeshLoadedCallback (IntPtr assetPtr)
void ShowControllers (bool show)
void ShowLeftController (bool show)
void ShowRightController (bool show)
void UpdateVoiceVisualization (float[] voiceSamples)
void RefreshBodyParts ()
ovrAvatarBodyComponent? GetBodyComponent ()
Transform GetHandTransform (HandType hand, HandJoint joint)
void GetPointingDirection (HandType hand, ref Vector3 forward, ref Vector3 up)
void DestroyHelperObjects ()
GameObject CreateHelperObject (Transform parent, Vector3 localPositionOffset, string helperName, string helperTag="")
void UpdateVoiceData (short[] pcmData, int numChannels)
void UpdateVoiceData (float[] pcmData, int numChannels)
Static Public Member Functions
static IntPtr GetRenderPart (ovrAvatarComponent component, UInt32 renderPartIndex)
static ovrAvatarTransform CreateOvrAvatarTransform (Vector3 position, Quaternion orientation)
static ovrAvatarHandInputState CreateInputState (ovrAvatarTransform transform, OvrAvatarDriver.ControllerPose pose)
Public Attributes
IntPtr sdkAvatar = IntPtr.Zero
string oculusUserID
OvrAvatarDriver Driver
bool EnableBody = true
bool EnableHands = true
bool EnableBase = true
bool EnableExpressive = false
bool RecordPackets
bool UseSDKPackets = true
PacketRecordSettings PacketSettings = new PacketRecordSettings()
bool StartWithControllers
AvatarLayer FirstPersonLayer
AvatarLayer ThirdPersonLayer
bool ShowFirstPerson = true
bool ShowThirdPerson
bool UseTransparentRenderQueue = true
Shader Monochrome_SurfaceShader
Shader Monochrome_SurfaceShader_SelfOccluding
Shader Monochrome_SurfaceShader_PBS
Shader Skinshaded_SurfaceShader_SingleComponent
Shader Skinshaded_VertFrag_SingleComponent
Shader Skinshaded_VertFrag_CombinedMesh
Shader Skinshaded_Expressive_SurfaceShader_SingleComponent
Shader Skinshaded_Expressive_VertFrag_SingleComponent
Shader Skinshaded_Expressive_VertFrag_CombinedMesh
Shader Loader_VertFrag_CombinedMesh
Shader EyeLens
Shader ControllerShader
bool CanOwnMicrophone = true
bool EnableLaughter = true
GameObject MouthAnchor
Transform LeftHandCustomPose
Transform RightHandCustomPose
EventHandler< PacketEventArgs > PacketRecorded
float VoiceAmplitude = 0f
bool EnableMouthVertexAnimation = false
Member Enumeration Documentation
HandJoint
enum OvrAvatar.HandJoint
Enumerator
HandBase
IndexBase
IndexTip
ThumbBase
ThumbTip
Max
HandType
enum OvrAvatar.HandType
Enumerator
Right
Left
Max
Member Function Documentation
AssetLoadedCallback()
void OvrAvatar.AssetLoadedCallback (OvrAvatarAsset asset)
CombinedMeshLoadedCallback()
void OvrAvatar.CombinedMeshLoadedCallback (IntPtr assetPtr)
CreateHelperObject()
GameObject OvrAvatar.CreateHelperObject (Transform parent, Vector3 localPositionOffset, string helperName, string helperTag = "")
CreateInputState()
static ovrAvatarHandInputState OvrAvatar.CreateInputState (ovrAvatarTransform transform, OvrAvatarDriver::ControllerPose pose) static
Referenced by OvrAvatarDriver.UpdateTransformsFromPose().
CreateOvrAvatarTransform()
static ovrAvatarTransform OvrAvatar.CreateOvrAvatarTransform (Vector3 position, Quaternion orientation) static
Referenced by OvrAvatarDriver.UpdateTransformsFromPose().
DestroyHelperObjects()
void OvrAvatar.DestroyHelperObjects ()
GetBodyComponent()
ovrAvatarBodyComponent? OvrAvatar.GetBodyComponent ()
GetHandTransform()
Transform OvrAvatar.GetHandTransform (HandType hand, HandJoint joint)
Referenced by GetPointingDirection().
GetPointingDirection()
void OvrAvatar.GetPointingDirection (HandType hand, ref Vector3 forward, ref Vector3 up)
GetRenderPart()
static IntPtr OvrAvatar.GetRenderPart (ovrAvatarComponent component, UInt32 renderPartIndex) static
Referenced by OvrAvatarComponent.UpdateAvatar().
RefreshBodyParts()
void OvrAvatar.RefreshBodyParts ()
ShowControllers()
void OvrAvatar.ShowControllers (bool show)
ShowLeftController()
void OvrAvatar.ShowLeftController (bool show)
Referenced by ShowControllers().
ShowRightController()
void OvrAvatar.ShowRightController (bool show)
Referenced by ShowControllers().
UpdateVoiceData() [1/2]
void OvrAvatar.UpdateVoiceData (float[] pcmData, int numChannels)
UpdateVoiceData() [2/2]
void OvrAvatar.UpdateVoiceData (short[] pcmData, int numChannels)
Referenced by SocialPlatformManager.UpdateVoiceData().
UpdateVoiceVisualization()
void OvrAvatar.UpdateVoiceVisualization (float[] voiceSamples)
Member Data Documentation
CanOwnMicrophone
bool OvrAvatar.CanOwnMicrophone = true
ControllerShader
Shader OvrAvatar.ControllerShader
Driver
OvrAvatarDriver OvrAvatar.Driver
EnableBase
bool OvrAvatar.EnableBase = true
EnableBody
bool OvrAvatar.EnableBody = true
EnableExpressive
bool OvrAvatar.EnableExpressive = false
EnableHands
bool OvrAvatar.EnableHands = true
EnableLaughter
bool OvrAvatar.EnableLaughter = true
EnableMouthVertexAnimation
bool OvrAvatar.EnableMouthVertexAnimation = false
EyeLens
Shader OvrAvatar.EyeLens
FirstPersonLayer
AvatarLayer OvrAvatar.FirstPersonLayer
LeftHandCustomPose
Transform OvrAvatar.LeftHandCustomPose
Loader_VertFrag_CombinedMesh
Shader OvrAvatar.Loader_VertFrag_CombinedMesh
Monochrome_SurfaceShader
Shader OvrAvatar.Monochrome_SurfaceShader
Monochrome_SurfaceShader_PBS
Shader OvrAvatar.Monochrome_SurfaceShader_PBS
Monochrome_SurfaceShader_SelfOccluding
Shader OvrAvatar.Monochrome_SurfaceShader_SelfOccluding
MouthAnchor
GameObject OvrAvatar.MouthAnchor
Referenced by DestroyHelperObjects(), and SocialPlatformManager.RemoveRemoteUser().
oculusUserID
string OvrAvatar.oculusUserID
PacketRecorded
EventHandler<PacketEventArgs> OvrAvatar.PacketRecorded
PacketSettings
PacketRecordSettings OvrAvatar.PacketSettings = new PacketRecordSettings()
RecordPackets
bool OvrAvatar.RecordPackets
RightHandCustomPose
Transform OvrAvatar.RightHandCustomPose
sdkAvatar
IntPtr OvrAvatar.sdkAvatar = IntPtr.Zero
Referenced by CombinedMeshLoadedCallback(), GetBodyComponent(), OvrAvatarBody.GetNativeAvatarComponent(), ShowLeftController(), and ShowRightController().
ShowFirstPerson
bool OvrAvatar.ShowFirstPerson = true
ShowThirdPerson
bool OvrAvatar.ShowThirdPerson
Referenced by OvrAvatarRenderComponent.UpdateActive().
Skinshaded_Expressive_SurfaceShader_SingleComponent
Shader OvrAvatar.Skinshaded_Expressive_SurfaceShader_SingleComponent
Skinshaded_Expressive_VertFrag_CombinedMesh
Shader OvrAvatar.Skinshaded_Expressive_VertFrag_CombinedMesh
Skinshaded_Expressive_VertFrag_SingleComponent
Shader OvrAvatar.Skinshaded_Expressive_VertFrag_SingleComponent
Skinshaded_SurfaceShader_SingleComponent
Shader OvrAvatar.Skinshaded_SurfaceShader_SingleComponent
Skinshaded_VertFrag_CombinedMesh
Shader OvrAvatar.Skinshaded_VertFrag_CombinedMesh
Skinshaded_VertFrag_SingleComponent
Shader OvrAvatar.Skinshaded_VertFrag_SingleComponent
StartWithControllers
bool OvrAvatar.StartWithControllers
ThirdPersonLayer
AvatarLayer OvrAvatar.ThirdPersonLayer
UseSDKPackets
bool OvrAvatar.UseSDKPackets = true
UseTransparentRenderQueue
bool OvrAvatar.UseTransparentRenderQueue = true
VoiceAmplitude
float OvrAvatar.VoiceAmplitude = 0f
The documentation for this class was generated from the following file:
C:/Users/Lykos/Desktop/Projects/Capstone/VRGames/Assets/ThirdParty/Oculus/Avatar/Scripts/OvrAvatar.cs