VRGames: Calibrator Class Reference
Calibrator Class Reference
Public Member Functions
void ResetScene ()
void ResetCalibration ()
void Calibrate (CalibrationManager.CalibrationType calibrationType, OVRInput.Controller unaffectedController)
void LHandMirrorCalibrate ()
void RHandMirrorCalibrate ()
void LHandScaleCalibrate ()
void RHandScaleCalibrate ()
Member Function Documentation
Calibrate()
void Calibrator.Calibrate (CalibrationManager::CalibrationType calibrationType, OVRInput::Controller unaffectedController)
Referenced by LHandMirrorCalibrate(), LHandScaleCalibrate(), RHandMirrorCalibrate(), and RHandScaleCalibrate().
LHandMirrorCalibrate()
void Calibrator.LHandMirrorCalibrate ()
LHandScaleCalibrate()
void Calibrator.LHandScaleCalibrate ()
ResetCalibration()
void Calibrator.ResetCalibration ()
ResetScene()
void Calibrator.ResetScene ()
RHandMirrorCalibrate()
void Calibrator.RHandMirrorCalibrate ()
RHandScaleCalibrate()
void Calibrator.RHandScaleCalibrate ()
The documentation for this class was generated from the following file:
C:/Users/Lykos/Desktop/Projects/Capstone/VRGames/Assets/Shared/Scripts/Calibration Scripts/Calibrator.cs