VRGames: UnityEngine.InputSystem.XR.TrackedPoseDriver Class Reference
UnityEngine.InputSystem.XR.TrackedPoseDriver Class Reference
The TrackedPoseDriver component applies the current pose value of a tracked device to the Transform of the GameObject. TrackedPoseDriver can track multiple types of devices including XR HMDs, controllers, and remotes.
Public Types
enum TrackingType { RotationAndPosition , RotationOnly , PositionOnly }
Options for which Transform properties to update.
enum UpdateType { UpdateAndBeforeRender , Update , BeforeRender }
Options for which phases of the player loop will update Transform properties.
Protected Member Functions
virtual void Awake ()
This function is called when the script instance is being loaded.
void OnEnable ()
This function is called when the object becomes enabled and active.
void OnDisable ()
This function is called when the object becomes disabled or inactive.
virtual void OnDestroy ()
This function is called when the MonoBehaviour will be destroyed.
void UpdateCallback ()
virtual void OnUpdate ()
virtual void OnBeforeRender ()
virtual void SetLocalTransform (Vector3 newPosition, Quaternion newRotation)
virtual void PerformUpdate ()
void Reset ()
This function is called when the user hits the Reset button in the Inspector's context menu or when adding the component the first time. This function is only called in editor mode.
Properties
TrackingType trackingType [get, set]
The tracking type being used by the Tracked Pose Driver to control which Transform properties to update.
UpdateType updateType [get, set]
The update type being used by the Tracked Pose Driver to control which phases of the player loop will update Transform properties.
InputActionProperty positionInput [get, set]
The action to read the position value of a tracked device. Must support reading a value of type Vector3.
InputActionProperty rotationInput [get, set]
The action to read the rotation value of a tracked device. Must support reading a value of type Quaternion.
InputAction positionAction [get, set]
InputAction rotationAction [get, set]
Detailed Description
The TrackedPoseDriver component applies the current pose value of a tracked device to the Transform of the GameObject. TrackedPoseDriver can track multiple types of devices including XR HMDs, controllers, and remotes.
For positionInput and rotationInput, if an action is directly defined in the InputActionProperty, as opposed to a reference to an action externally defined in an InputActionAsset, the action will automatically be enabled and disabled by this behavior during OnEnable and OnDisable. The enabled state for actions externally defined must be managed externally from this behavior.
Member Enumeration Documentation
TrackingType
enum UnityEngine.InputSystem.XR.TrackedPoseDriver.TrackingType
Options for which Transform properties to update.
See also
trackingType
Enumerator
RotationAndPosition
Update both rotation and position.
RotationOnly
Update rotation only.
PositionOnly
Update position only.
UpdateType
enum UnityEngine.InputSystem.XR.TrackedPoseDriver.UpdateType
Options for which phases of the player loop will update Transform properties.
See also
updateType
Enumerator
UpdateAndBeforeRender
Update after the Input System has completed an update and right before rendering.
See also
InputUpdateType.Dynamic, InputUpdateType.BeforeRender
Update
Update after the Input System has completed an update.
See also
InputUpdateType.Dynamic
BeforeRender
Update right before rendering.
See also
InputUpdateType.BeforeRender
Member Function Documentation
Awake()
virtual void UnityEngine.InputSystem.XR.TrackedPoseDriver.Awake () protected virtual
This function is called when the script instance is being loaded.
OnBeforeRender()
virtual void UnityEngine.InputSystem.XR.TrackedPoseDriver.OnBeforeRender () protected virtual
Referenced by UnityEngine.InputSystem.XR.TrackedPoseDriver.UpdateCallback().
OnDestroy()
virtual void UnityEngine.InputSystem.XR.TrackedPoseDriver.OnDestroy () protected virtual
This function is called when the MonoBehaviour will be destroyed.
OnDisable()
void UnityEngine.InputSystem.XR.TrackedPoseDriver.OnDisable () protected
This function is called when the object becomes disabled or inactive.
OnEnable()
void UnityEngine.InputSystem.XR.TrackedPoseDriver.OnEnable () protected
This function is called when the object becomes enabled and active.
OnUpdate()
virtual void UnityEngine.InputSystem.XR.TrackedPoseDriver.OnUpdate () protected virtual
Referenced by UnityEngine.InputSystem.XR.TrackedPoseDriver.UpdateCallback().
PerformUpdate()
virtual void UnityEngine.InputSystem.XR.TrackedPoseDriver.PerformUpdate () protected virtual
Referenced by UnityEngine.InputSystem.XR.TrackedPoseDriver.OnBeforeRender(), and UnityEngine.InputSystem.XR.TrackedPoseDriver.OnUpdate().
Reset()
void UnityEngine.InputSystem.XR.TrackedPoseDriver.Reset () protected
This function is called when the user hits the Reset button in the Inspector's context menu or when adding the component the first time. This function is only called in editor mode.
SetLocalTransform()
virtual void UnityEngine.InputSystem.XR.TrackedPoseDriver.SetLocalTransform (Vector3 newPosition, Quaternion newRotation) protected virtual
Referenced by UnityEngine.InputSystem.XR.TrackedPoseDriver.PerformUpdate().
UpdateCallback()
void UnityEngine.InputSystem.XR.TrackedPoseDriver.UpdateCallback () protected
Referenced by UnityEngine.InputSystem.XR.TrackedPoseDriver.OnDisable(), and UnityEngine.InputSystem.XR.TrackedPoseDriver.OnEnable().
Property Documentation
positionAction
InputAction UnityEngine.InputSystem.XR.TrackedPoseDriver.positionAction get set
positionInput
InputActionProperty UnityEngine.InputSystem.XR.TrackedPoseDriver.positionInput get set
The action to read the position value of a tracked device. Must support reading a value of type Vector3.
rotationAction
InputAction UnityEngine.InputSystem.XR.TrackedPoseDriver.rotationAction get set
rotationInput
InputActionProperty UnityEngine.InputSystem.XR.TrackedPoseDriver.rotationInput get set
The action to read the rotation value of a tracked device. Must support reading a value of type Quaternion.
trackingType
TrackingType UnityEngine.InputSystem.XR.TrackedPoseDriver.trackingType get set
The tracking type being used by the Tracked Pose Driver to control which Transform properties to update.
See also
TrackingType
updateType
UpdateType UnityEngine.InputSystem.XR.TrackedPoseDriver.updateType get set
The update type being used by the Tracked Pose Driver to control which phases of the player loop will update Transform properties.
See also
UpdateType
The documentation for this class was generated from the following file:
C:/Users/Lykos/Desktop/Projects/Capstone/VRGames/Library/PackageCache/com.unity.inputsystem@1.3.0/InputSystem/Plugins/XR/TrackedPoseDriver.cs