VRGames: Oculus.Interaction.HandPosing.HandGrabInteractable Class Reference
Oculus.Interaction.HandPosing.HandGrabInteractable Class Reference
A HandGrabInteractable indicates the properties about how a hand can snap to an object. The most important is the position/rotation and finger rotations for the hand, but it can also contain extra information like a valid holding surface (instead of just a single point) or a visual representation (using a hand-ghost)
Public Member Functions
Tween GenerateObjectToHandTween (in Pose from, in Pose to)
bool CalculateBestPose (Pose userPose, float handScale, Handedness handedness, ref HandPose result, ref Pose snapPoint, out bool usesHandPose, out float score)
bool UsesHandPose ()
HandGrabPoint CreatePoint ()
HandGrabInteractableData SaveData ()
Serializes the data of the HandGrabInteractable so it can be stored.
void LoadData (HandGrabInteractableData data)
Populates the HandGrabInteractable with the serialized data version.
HandGrabPoint LoadPoint (HandGrabPointData pointData)
void ApplyVelocities (Vector3 linearVelocity, Vector3 angularVelocity)
void InjectAllHandGrabInteractable (Transform relativeTo, Rigidbody rigidbody, Grabbable grabbable, GrabTypeFlags supportedGrabTypes, GrabbingRule pinchGrabRules, GrabbingRule palmGrabRules, float travelSpeed, bool useFixedTravelTime, SnapType snapType)
void InjectRelativeTo (Transform relativeTo)
void InjectRigidbody (Rigidbody rigidbody)
void InjectGrabbable (Grabbable grabbable)
void InjectSupportedGrabTypes (GrabTypeFlags supportedGrabTypes)
void InjectPinchGrabRules (GrabbingRule pinchGrabRules)
void InjectPalmGrabRules (GrabbingRule palmGrabRules)
void InjectOptionalPhysicsGrabbable (PhysicsGrabbable physicsGrabbable)
void InjectSnapType (SnapType snapType)
void InjectTravelSpeed (float travelSpeed)
void InjectUseFixedTravelTime (bool useFixedTravelTime)
void InjectOptionalTravelCurve (AnimationCurve travelCurve)
void InjectOptionalHandGrabPoints (List< HandGrabPoint > handGrabPoints)
Public Member Functions inherited from Oculus.Interaction.Interactable< HandGrabInteractor, HandGrabInteractable >
void AddInteractor (TInteractor interactor)
void RemoveInteractor (TInteractor interactor)
void AddSelectingInteractor (TInteractor interactor)
void RemoveSelectingInteractor (TInteractor interactor)
bool CanBeSelectedBy (TInteractor interactor)
bool HasInteractor (TInteractor interactor)
bool HasSelectingInteractor (TInteractor interactor)
void Enable ()
void Disable ()
void RemoveInteractorById (int id)
Static Public Member Functions
static HandGrabInteractable Create (Transform parent, string name=null)
Creates a new HandGrabInteractable under the given object.
Protected Member Functions
virtual void Reset ()
virtual void Awake ()
virtual void Start ()
override void OnEnable ()
override void OnDisable ()
Protected Member Functions inherited from Oculus.Interaction.Interactable< HandGrabInteractor, HandGrabInteractable >
virtual void InteractorAdded (TInteractor interactor)
virtual void InteractorRemoved (TInteractor interactor)
virtual void SelectingInteractorAdded (TInteractor interactor)
virtual void SelectingInteractorRemoved (TInteractor interactor)
virtual void SetRegistry (IInteractableRegistry< TInteractor, TInteractable > registry)
Protected Attributes
bool _started = false
Properties
Rigidbody Rigidbody [get]
Grabbable Grabbable [get]
bool ResetGrabOnGrabsUpdated [get, set]
Transform RelativeTo [get]
General getter for the transform of the object this interactable refers to.
SnapType SnapType [get]
General getter indicating how the hand and object will align for the grab.
GrabTypeFlags SupportedGrabTypes [get]
GrabbingRule PinchGrabRules [get]
GrabbingRule PalmGrabRules [get]
List< HandGrabPoint > GrabPoints [get]
Collider[] Colliders [get]
Properties inherited from Oculus.Interaction.Interactable< HandGrabInteractor, HandGrabInteractable >
int MaxInteractors [get, set]
int MaxSelectingInteractors [get, set]
MAction< TInteractor > WhenInteractorAdded [get]
MAction< TInteractor > WhenInteractorRemoved [get]
MAction< TInteractor > WhenSelectingInteractorAdded [get]
MAction< TInteractor > WhenSelectingInteractorRemoved [get]
InteractableState State [get]
static IInteractableRegistry< TInteractor, TInteractable > Registry [get]
int InteractorsCount [get]
int SelectingInteractorsCount [get]
IEnumerable< TInteractor > Interactors [get]
IEnumerable< TInteractor > SelectingInteractors [get]
Properties inherited from Oculus.Interaction.HandPosing.ISnappable
Properties inherited from Oculus.Interaction.IRigidbodyRef
Properties inherited from Oculus.Interaction.Grab.IHandGrabInteractable
Additional Inherited Members
Events inherited from Oculus.Interaction.Interactable< HandGrabInteractor, HandGrabInteractable >
Action WhenInteractorsCountUpdated
Action WhenSelectingInteractorsCountUpdated
Action< InteractableStateChangeArgs > WhenStateChanged
Detailed Description
A HandGrabInteractable indicates the properties about how a hand can snap to an object. The most important is the position/rotation and finger rotations for the hand, but it can also contain extra information like a valid holding surface (instead of just a single point) or a visual representation (using a hand-ghost)
Member Function Documentation
ApplyVelocities()
void Oculus.Interaction.HandPosing.HandGrabInteractable.ApplyVelocities (Vector3 linearVelocity, Vector3 angularVelocity)
Referenced by Oculus.Interaction.HandPosing.HandGrabInteractor.InteractableUnselected().
Awake()
virtual void Oculus.Interaction.HandPosing.HandGrabInteractable.Awake () protected virtual
CalculateBestPose()
bool Oculus.Interaction.HandPosing.HandGrabInteractable.CalculateBestPose (Pose userPose, float handScale, Handedness handedness, ref HandPose result, ref Pose snapPoint, out bool usesHandPose, out float score)
Create()
static HandGrabInteractable Oculus.Interaction.HandPosing.HandGrabInteractable.Create (Transform parent, string name = null) static
Creates a new HandGrabInteractable under the given object.
Parameters
parent The relative object for the interactable
name Name for the GameObject holding this interactable
Returns
An non-populated HandGrabInteractable
Referenced by Oculus.Interaction.HandPosing.Editor.HandGrabPoseWizard.AddHandGrabPoint().
CreatePoint()
HandGrabPoint Oculus.Interaction.HandPosing.HandGrabInteractable.CreatePoint ()
Referenced by Oculus.Interaction.HandPosing.HandGrabInteractable.LoadPoint().
GenerateObjectToHandTween()
Tween Oculus.Interaction.HandPosing.HandGrabInteractable.GenerateObjectToHandTween (in Pose from, in Pose to)
Referenced by Oculus.Interaction.HandPosing.HandGrabInteractor.InteractableSelected().
InjectAllHandGrabInteractable()
void Oculus.Interaction.HandPosing.HandGrabInteractable.InjectAllHandGrabInteractable (Transform relativeTo, Rigidbody rigidbody, Grabbable grabbable, GrabTypeFlags supportedGrabTypes, GrabbingRule pinchGrabRules, GrabbingRule palmGrabRules, float travelSpeed, bool useFixedTravelTime, SnapType snapType)
InjectGrabbable()
void Oculus.Interaction.HandPosing.HandGrabInteractable.InjectGrabbable (Grabbable grabbable)
Referenced by Oculus.Interaction.HandPosing.HandGrabInteractable.InjectAllHandGrabInteractable().
InjectOptionalHandGrabPoints()
void Oculus.Interaction.HandPosing.HandGrabInteractable.InjectOptionalHandGrabPoints (List< HandGrabPoint > handGrabPoints)
InjectOptionalPhysicsGrabbable()
void Oculus.Interaction.HandPosing.HandGrabInteractable.InjectOptionalPhysicsGrabbable (PhysicsGrabbable physicsGrabbable)
InjectOptionalTravelCurve()
void Oculus.Interaction.HandPosing.HandGrabInteractable.InjectOptionalTravelCurve (AnimationCurve travelCurve)
InjectPalmGrabRules()
void Oculus.Interaction.HandPosing.HandGrabInteractable.InjectPalmGrabRules (GrabbingRule palmGrabRules)
Referenced by Oculus.Interaction.HandPosing.HandGrabInteractable.InjectAllHandGrabInteractable().
InjectPinchGrabRules()
void Oculus.Interaction.HandPosing.HandGrabInteractable.InjectPinchGrabRules (GrabbingRule pinchGrabRules)
Referenced by Oculus.Interaction.HandPosing.HandGrabInteractable.InjectAllHandGrabInteractable().
InjectRelativeTo()
void Oculus.Interaction.HandPosing.HandGrabInteractable.InjectRelativeTo (Transform relativeTo)
Referenced by Oculus.Interaction.HandPosing.HandGrabInteractable.InjectAllHandGrabInteractable().
InjectRigidbody()
void Oculus.Interaction.HandPosing.HandGrabInteractable.InjectRigidbody (Rigidbody rigidbody)
Referenced by Oculus.Interaction.HandPosing.HandGrabInteractable.InjectAllHandGrabInteractable().
InjectSnapType()
void Oculus.Interaction.HandPosing.HandGrabInteractable.InjectSnapType (SnapType snapType)
Referenced by Oculus.Interaction.HandPosing.HandGrabInteractable.InjectAllHandGrabInteractable().
InjectSupportedGrabTypes()
void Oculus.Interaction.HandPosing.HandGrabInteractable.InjectSupportedGrabTypes (GrabTypeFlags supportedGrabTypes)
Referenced by Oculus.Interaction.HandPosing.HandGrabInteractable.InjectAllHandGrabInteractable().
InjectTravelSpeed()
void Oculus.Interaction.HandPosing.HandGrabInteractable.InjectTravelSpeed (float travelSpeed)
Referenced by Oculus.Interaction.HandPosing.HandGrabInteractable.InjectAllHandGrabInteractable().
InjectUseFixedTravelTime()
void Oculus.Interaction.HandPosing.HandGrabInteractable.InjectUseFixedTravelTime (bool useFixedTravelTime)
Referenced by Oculus.Interaction.HandPosing.HandGrabInteractable.InjectAllHandGrabInteractable().
LoadData()
void Oculus.Interaction.HandPosing.HandGrabInteractable.LoadData (HandGrabInteractableData data)
Populates the HandGrabInteractable with the serialized data version.
Parameters
data The serialized data for the HandGrabInteractable.
LoadPoint()
HandGrabPoint Oculus.Interaction.HandPosing.HandGrabInteractable.LoadPoint (HandGrabPointData pointData)
Referenced by Oculus.Interaction.HandPosing.Editor.HandGrabPoseWizard.AddHandGrabPoint(), and Oculus.Interaction.HandPosing.HandGrabInteractable.LoadData().
OnDisable()
override void Oculus.Interaction.HandPosing.HandGrabInteractable.OnDisable () protected virtual
Reimplemented from Oculus.Interaction.Interactable< HandGrabInteractor, HandGrabInteractable >.
OnEnable()
override void Oculus.Interaction.HandPosing.HandGrabInteractable.OnEnable () protected virtual
Reimplemented from Oculus.Interaction.Interactable< HandGrabInteractor, HandGrabInteractable >.
Reset()
virtual void Oculus.Interaction.HandPosing.HandGrabInteractable.Reset () protected virtual
SaveData()
HandGrabInteractableData Oculus.Interaction.HandPosing.HandGrabInteractable.SaveData ()
Serializes the data of the HandGrabInteractable so it can be stored.
Returns
The struct data to recreate the interactable
Start()
virtual void Oculus.Interaction.HandPosing.HandGrabInteractable.Start () protected virtual
UsesHandPose()
bool Oculus.Interaction.HandPosing.HandGrabInteractable.UsesHandPose ()
Implements Oculus.Interaction.HandPosing.ISnappable.
Member Data Documentation
_started
bool Oculus.Interaction.HandPosing.HandGrabInteractable._started = false protected
Referenced by Oculus.Interaction.HandPosing.HandGrabInteractable.OnDisable(), Oculus.Interaction.HandPosing.HandGrabInteractable.OnEnable(), and Oculus.Interaction.HandPosing.HandGrabInteractable.Start().
Property Documentation
Colliders
Collider [] Oculus.Interaction.HandPosing.HandGrabInteractable.Colliders get
Implements Oculus.Interaction.HandPosing.ISnappable.
Referenced by Oculus.Interaction.HandPosing.HandGrabInteractable.Start().
Grabbable
Grabbable Oculus.Interaction.HandPosing.HandGrabInteractable.Grabbable get
Referenced by Oculus.Interaction.HandPosing.HandGrabInteractor.DoSelectUpdate(), Oculus.Interaction.HandPosing.HandGrabInteractor.InteractableSelected(), and Oculus.Interaction.HandPosing.HandGrabInteractor.InteractableUnselected().
GrabPoints
List<HandGrabPoint> Oculus.Interaction.HandPosing.HandGrabInteractable.GrabPoints get
PalmGrabRules
GrabbingRule Oculus.Interaction.HandPosing.HandGrabInteractable.PalmGrabRules get
Implements Oculus.Interaction.Grab.IHandGrabInteractable.
PinchGrabRules
GrabbingRule Oculus.Interaction.HandPosing.HandGrabInteractable.PinchGrabRules get
Implements Oculus.Interaction.Grab.IHandGrabInteractable.
RelativeTo
Transform Oculus.Interaction.HandPosing.HandGrabInteractable.RelativeTo get
General getter for the transform of the object this interactable refers to.
Implements Oculus.Interaction.HandPosing.ISnappable.
ResetGrabOnGrabsUpdated
bool Oculus.Interaction.HandPosing.HandGrabInteractable.ResetGrabOnGrabsUpdated get set
Rigidbody
Rigidbody Oculus.Interaction.HandPosing.HandGrabInteractable.Rigidbody get
Implements Oculus.Interaction.IRigidbodyRef.
Referenced by Oculus.Interaction.HandPosing.HandGrabInteractable.Start().
SnapType
SnapType Oculus.Interaction.HandPosing.HandGrabInteractable.SnapType get
General getter indicating how the hand and object will align for the grab.
Implements Oculus.Interaction.HandPosing.ISnappable.
SupportedGrabTypes
GrabTypeFlags Oculus.Interaction.HandPosing.HandGrabInteractable.SupportedGrabTypes get
Implements Oculus.Interaction.Grab.IHandGrabInteractable.
The documentation for this class was generated from the following file:
C:/Users/Lykos/Desktop/Projects/Capstone/VRGames/Assets/ThirdParty/Oculus/Interaction/Runtime/Scripts/Interaction/Models/HandGrab/HandGrabInteractable.cs