VRGames: Oculus.Interaction.Input.FromOVRControllerHandDataSource Class Reference
Oculus.Interaction.Input.FromOVRControllerHandDataSource Class Reference
Public Member Functions
void InjectAllFromOVRControllerHandDataSource (UpdateModeFlags updateMode, IDataSource updateAfter, Handedness handedness, ITrackingToWorldTransformer trackingToWorldTransformer, IDataSource< HmdDataAsset > hmdData, Transform[] bones, AnimationCurve pinchCurve, Vector3 rootOffset, Vector3 rootAngleOffset)
void InjectHandedness (Handedness handedness)
void InjectTrackingToWorldTransformer (ITrackingToWorldTransformer trackingToWorldTransformer)
void InjectHmdData (IDataSource< HmdDataAsset > hmdData)
void InjectBones (Transform[] bones)
void InjectPinchCurve (AnimationCurve pinchCurve)
void InjectRootOffset (Vector3 rootOffset)
void InjectRootAngleOffset (Vector3 rootAngleOffset)
Public Member Functions inherited from Oculus.Interaction.Input.DataSource< HandDataAsset >
TData GetData ()
virtual void MarkInputDataRequiresUpdate ()
Marks the DataAsset stored as outdated, which means it will be re-processed JIT during the next call to GetData.
void InjectAllDataSource (UpdateModeFlags updateMode, IDataSource updateAfter)
void InjectUpdateMode (UpdateModeFlags updateMode)
void InjectUpdateAfter (IDataSource updateAfter)
Protected Member Functions
void Awake ()
override void Start ()
override void UpdateData ()
Protected Member Functions inherited from Oculus.Interaction.Input.DataSource< HandDataAsset >
virtual void OnEnable ()
virtual void OnDisable ()
virtual void Update ()
virtual void FixedUpdate ()
virtual void LateUpdate ()
void ResetUpdateAfter (IDataSource updateAfter, UpdateModeFlags updateMode)
bool RequiresUpdate ()
void UpdateData ()
Properties
static Quaternion WristFixupRotation [get]
override HandDataAsset DataAsset [get]
Properties inherited from Oculus.Interaction.Input.DataSource< HandDataAsset >
bool Started [get]
UpdateModeFlags UpdateMode [get]
bool UpdateModeAfterPrevious [get]
virtual int CurrentDataVersion [get]
TData DataAsset [get]
Returns the current DataAsset, without performing any updates.
Additional Inherited Members
Protected Attributes inherited from Oculus.Interaction.Input.DataSource< HandDataAsset >
bool _started
Events inherited from Oculus.Interaction.Input.DataSource< HandDataAsset >
Action InputDataAvailable
Member Function Documentation
Awake()
void Oculus.Interaction.Input.FromOVRControllerHandDataSource.Awake () protected
InjectAllFromOVRControllerHandDataSource()
void Oculus.Interaction.Input.FromOVRControllerHandDataSource.InjectAllFromOVRControllerHandDataSource (UpdateModeFlags updateMode, IDataSource updateAfter, Handedness handedness, ITrackingToWorldTransformer trackingToWorldTransformer, IDataSource< HmdDataAsset > hmdData, Transform[] bones, AnimationCurve pinchCurve, Vector3 rootOffset, Vector3 rootAngleOffset)
InjectBones()
void Oculus.Interaction.Input.FromOVRControllerHandDataSource.InjectBones (Transform[] bones)
Referenced by Oculus.Interaction.Input.FromOVRControllerHandDataSource.InjectAllFromOVRControllerHandDataSource().
InjectHandedness()
void Oculus.Interaction.Input.FromOVRControllerHandDataSource.InjectHandedness (Handedness handedness)
Referenced by Oculus.Interaction.Input.FromOVRControllerHandDataSource.InjectAllFromOVRControllerHandDataSource().
InjectHmdData()
void Oculus.Interaction.Input.FromOVRControllerHandDataSource.InjectHmdData (IDataSource< HmdDataAsset > hmdData)
Referenced by Oculus.Interaction.Input.FromOVRControllerHandDataSource.InjectAllFromOVRControllerHandDataSource().
InjectPinchCurve()
void Oculus.Interaction.Input.FromOVRControllerHandDataSource.InjectPinchCurve (AnimationCurve pinchCurve)
Referenced by Oculus.Interaction.Input.FromOVRControllerHandDataSource.InjectAllFromOVRControllerHandDataSource().
InjectRootAngleOffset()
void Oculus.Interaction.Input.FromOVRControllerHandDataSource.InjectRootAngleOffset (Vector3 rootAngleOffset)
Referenced by Oculus.Interaction.Input.FromOVRControllerHandDataSource.InjectAllFromOVRControllerHandDataSource().
InjectRootOffset()
void Oculus.Interaction.Input.FromOVRControllerHandDataSource.InjectRootOffset (Vector3 rootOffset)
Referenced by Oculus.Interaction.Input.FromOVRControllerHandDataSource.InjectAllFromOVRControllerHandDataSource().
InjectTrackingToWorldTransformer()
void Oculus.Interaction.Input.FromOVRControllerHandDataSource.InjectTrackingToWorldTransformer (ITrackingToWorldTransformer trackingToWorldTransformer)
Referenced by Oculus.Interaction.Input.FromOVRControllerHandDataSource.InjectAllFromOVRControllerHandDataSource().
Start()
override void Oculus.Interaction.Input.FromOVRControllerHandDataSource.Start () protected virtual
Reimplemented from Oculus.Interaction.Input.DataSource< HandDataAsset >.
UpdateData()
override void Oculus.Interaction.Input.FromOVRControllerHandDataSource.UpdateData () protected
Property Documentation
DataAsset
override HandDataAsset Oculus.Interaction.Input.FromOVRControllerHandDataSource.DataAsset get protected
WristFixupRotation
Quaternion Oculus.Interaction.Input.FromOVRControllerHandDataSource.WristFixupRotation static get
Initial value:
=
            new Quaternion(0.0f, 1.0f, 0.0f, 0.0f)
Referenced by Oculus.Interaction.Input.FromOVRControllerHandDataSource.UpdateData().
The documentation for this class was generated from the following file:
C:/Users/Lykos/Desktop/Projects/Capstone/VRGames/Assets/ThirdParty/Oculus/Interaction/Runtime/Scripts/Input/OVRIntegration/FromOVRControllerHandDataSource.cs