VRGames: Oculus.Platform.Samples.VrVoiceChat.PlatformManager Class Reference
Oculus.Platform.Samples.VrVoiceChat.PlatformManager Class Reference
Public Types
enum State {
INITIALIZING , WAITING_TO_CALL_OR_ANSWER , WAITING_FOR_ANSWER , CONNECTED_IN_A_ROOM ,
HANGUP
}
Public Member Functions
void CallFriendOnClick ()
void HangupOnClick ()
void QuitOnClick ()
Static Public Member Functions
static void TerminateWithError (Message msg)
static void AnswerCallOnClick (ulong roomID)
static void TransitionToState (State newState)
static void SetBackgroundColorForState ()
static void SetActiveInvites (List< RoomManager.Invite > invites)
Properties
static State CurrentState [get]
static ulong MyID [get]
static string MyOculusID [get]
Member Enumeration Documentation
State
enum Oculus.Platform.Samples.VrVoiceChat.PlatformManager.State
Enumerator
INITIALIZING
WAITING_TO_CALL_OR_ANSWER
WAITING_FOR_ANSWER
CONNECTED_IN_A_ROOM
HANGUP
Member Function Documentation
AnswerCallOnClick()
static void Oculus.Platform.Samples.VrVoiceChat.PlatformManager.AnswerCallOnClick (ulong roomID) static
Referenced by Oculus.Platform.Samples.VrVoiceChat.PlatformManager.SetActiveInvites().
CallFriendOnClick()
void Oculus.Platform.Samples.VrVoiceChat.PlatformManager.CallFriendOnClick ()
HangupOnClick()
void Oculus.Platform.Samples.VrVoiceChat.PlatformManager.HangupOnClick ()
QuitOnClick()
void Oculus.Platform.Samples.VrVoiceChat.PlatformManager.QuitOnClick ()
SetActiveInvites()
static void Oculus.Platform.Samples.VrVoiceChat.PlatformManager.SetActiveInvites (List< RoomManager::Invite > invites) static
SetBackgroundColorForState()
static void Oculus.Platform.Samples.VrVoiceChat.PlatformManager.SetBackgroundColorForState () static
Referenced by Oculus.Platform.Samples.VrVoiceChat.PlatformManager.TransitionToState().
TerminateWithError()
static void Oculus.Platform.Samples.VrVoiceChat.PlatformManager.TerminateWithError (Message msg) static
TransitionToState()
static void Oculus.Platform.Samples.VrVoiceChat.PlatformManager.TransitionToState (State newState) static
Referenced by Oculus.Platform.Samples.VrVoiceChat.RoomManager.LeaveCurrentRoom().
Property Documentation
CurrentState
State Oculus.Platform.Samples.VrVoiceChat.PlatformManager.CurrentState static get
Referenced by Oculus.Platform.Samples.VrVoiceChat.PlatformManager.CallFriendOnClick().
MyID
ulong Oculus.Platform.Samples.VrVoiceChat.PlatformManager.MyID static get
Referenced by Oculus.Platform.Samples.VrVoiceChat.P2PManager.ConnectTo(), and Oculus.Platform.Samples.VrVoiceChat.VoipManager.ConnectTo().
MyOculusID
string Oculus.Platform.Samples.VrVoiceChat.PlatformManager.MyOculusID static get
The documentation for this class was generated from the following file:
C:/Users/Lykos/Desktop/Projects/Capstone/VRGames/Assets/ThirdParty/Oculus/Platform/Samples/VrVoiceChat/Scripts/PlatformManager.cs