VRGames: Block Class Reference
Block Class Reference
Public Member Functions
void onGrab (GameObject hand)
void onRelease (GameObject hand)
Member Function Documentation
onGrab()
void Block.onGrab (GameObject hand)
Implements IGrabEvent.
References Classes.Managers.BoxAndBlocksGameplayManager.getGoalSide(), and Classes.Managers.BoxAndBlocksGameplayManager.onBlockGrabbed().
onRelease()
void Block.onRelease (GameObject hand)
Implements IGrabEvent.
References Classes.Managers.BoxAndBlocksGameplayManager.onBlockReleased().
The documentation for this class was generated from the following file:
C:/Users/Lykos/Desktop/Projects/Capstone/VRGames/Assets/Shared/Scripts/BlockGameClasses/Block.cs