VRGames: Oculus.Interaction.HandPosing.SnapSurfaces.CylinderSurface Class Reference
Oculus.Interaction.HandPosing.SnapSurfaces.CylinderSurface Class Reference
This type of surface defines a cylinder in which the grip pose is valid around an object. An angle can be used to constrain the cylinder and not use a full circle. The radius is automatically specified as the distance from the axis of the cylinder to the original grip position.
Public Member Functions
Pose MirrorPose (in Pose pose)
Method for mirroring a Pose around the surface. Different surfaces will prefer mirroring along different axis.
float CalculateBestPoseAtSurface (in Pose targetPose, in Pose reference, out Pose bestPose, in PoseMeasureParameters scoringModifier)
Finds the Pose at the surface that is the closest to the given pose.
ISnapSurface CreateMirroredSurface (GameObject gameObject)
Creates a new ISnapSurface under the selected gameobject that is a mirror version of the current.
ISnapSurface CreateDuplicatedSurface (GameObject gameObject)
Creates a new ISnapSurface under the selected gameobject with the same data as this one.
bool CalculateBestPoseAtSurface (Ray targetRay, in Pose recordedPose, out Pose bestPose)
Finds the Pose at the surface that is the closest to the given ray.
void InjectAllCylinderSurface (CylinderSurfaceData data, Transform relativeTo, Transform gripPoint)
void InjectData (CylinderSurfaceData data)
void InjectRelativeTo (Transform relativeTo)
void InjectGripPoint (Transform gripPoint)
Protected Member Functions
virtual void Start ()
Vector3 NearestPointInSurface (Vector3 targetPosition)
Pose MinimalRotationPoseAtSurface (in Pose userPose, in Pose snapPose)
Pose MinimalTranslationPoseAtSurface (in Pose userPose, in Pose snapPose)
Quaternion CalculateRotationOffset (Vector3 surfacePoint)
Protected Attributes
CylinderSurfaceData _data = new CylinderSurfaceData()
Properties
CylinderSurfaceData Data [get, set]
Getter for the data-only version of this surface. Used so it can be stored when created at Play-Mode.
Transform RelativeTo [get, set]
Transform to which the surface refers to.
Transform GripPoint [get, set]
Valid point at which the hand can snap, typically the SnapPoint position itself.
Vector3 StartAngleDir [get]
Direction from the axis of the cylinder to the original grip position.
Vector3 EndAngleDir [get]
Direction from the axis of the cylinder to the maximum angle allowance.
Vector3 StartPoint [get, set]
Base cap of the cylinder, in world coordinates.
Vector3 EndPoint [get, set]
End cap of the cylinder, in world coordinates.
float Angle [get, set]
The maximum angle for the surface of the cylinder, starting from the original grip position. To invert the direction of the angle, swap the caps order.
float Radius [get]
The generated radius of the cylinder. Represents the distance from the axis of the cylinder to the original grip position.
Vector3 Direction [get]
The direction of the central axis of the cylinder.
Detailed Description
This type of surface defines a cylinder in which the grip pose is valid around an object. An angle can be used to constrain the cylinder and not use a full circle. The radius is automatically specified as the distance from the axis of the cylinder to the original grip position.
Member Function Documentation
CalculateBestPoseAtSurface() [1/2]
float Oculus.Interaction.HandPosing.SnapSurfaces.CylinderSurface.CalculateBestPoseAtSurface (in Pose targetPose, in Pose reference, out Pose bestPose, in PoseMeasureParameters scoringModifier)
Finds the Pose at the surface that is the closest to the given pose.
Parameters
targetPose The pose to find the nearest to.
reference The reference snap point to use for measuring at the surface.
bestPose The best found pose at the surface.<
Returns
The score indicating how good the found pose was, -1 for invalid result.
Implements Oculus.Interaction.HandPosing.SnapSurfaces.ISnapSurface.
CalculateBestPoseAtSurface() [2/2]
bool Oculus.Interaction.HandPosing.SnapSurfaces.CylinderSurface.CalculateBestPoseAtSurface (Ray targetRay, in Pose reference, out Pose bestPose)
Finds the Pose at the surface that is the closest to the given ray.
Parameters
targetRay Ray searching for the nearest snap pose
reference The reference snap point to use for measuring at the surface.
bestPose The best found pose at the surface.
Returns
True if the pose was found
Implements Oculus.Interaction.HandPosing.SnapSurfaces.ISnapSurface.
CalculateRotationOffset()
Quaternion Oculus.Interaction.HandPosing.SnapSurfaces.CylinderSurface.CalculateRotationOffset (Vector3 surfacePoint) protected
Referenced by Oculus.Interaction.HandPosing.SnapSurfaces.CylinderSurface.MinimalRotationPoseAtSurface(), and Oculus.Interaction.HandPosing.SnapSurfaces.CylinderSurface.MinimalTranslationPoseAtSurface().
CreateDuplicatedSurface()
ISnapSurface Oculus.Interaction.HandPosing.SnapSurfaces.CylinderSurface.CreateDuplicatedSurface (GameObject gameObject)
Creates a new ISnapSurface under the selected gameobject with the same data as this one.
Parameters
gameObject The gameobject in which to place the new ISnapSurface.
Returns
A clone of this ISnapSurface.
Implements Oculus.Interaction.HandPosing.SnapSurfaces.ISnapSurface.
CreateMirroredSurface()
ISnapSurface Oculus.Interaction.HandPosing.SnapSurfaces.CylinderSurface.CreateMirroredSurface (GameObject gameObject)
Creates a new ISnapSurface under the selected gameobject that is a mirror version of the current.
Parameters
gameObject The gameobject in which to place the new ISnapSurface.
Returns
A mirror of this ISnapSurface.
Implements Oculus.Interaction.HandPosing.SnapSurfaces.ISnapSurface.
InjectAllCylinderSurface()
void Oculus.Interaction.HandPosing.SnapSurfaces.CylinderSurface.InjectAllCylinderSurface (CylinderSurfaceData data, Transform relativeTo, Transform gripPoint)
InjectData()
void Oculus.Interaction.HandPosing.SnapSurfaces.CylinderSurface.InjectData (CylinderSurfaceData data)
Referenced by Oculus.Interaction.HandPosing.SnapSurfaces.CylinderSurface.InjectAllCylinderSurface().
InjectGripPoint()
void Oculus.Interaction.HandPosing.SnapSurfaces.CylinderSurface.InjectGripPoint (Transform gripPoint)
Referenced by Oculus.Interaction.HandPosing.SnapSurfaces.CylinderSurface.InjectAllCylinderSurface().
InjectRelativeTo()
void Oculus.Interaction.HandPosing.SnapSurfaces.CylinderSurface.InjectRelativeTo (Transform relativeTo)
Referenced by Oculus.Interaction.HandPosing.SnapSurfaces.CylinderSurface.InjectAllCylinderSurface().
MinimalRotationPoseAtSurface()
Pose Oculus.Interaction.HandPosing.SnapSurfaces.CylinderSurface.MinimalRotationPoseAtSurface (in Pose userPose, in Pose snapPose) protected
Referenced by Oculus.Interaction.HandPosing.SnapSurfaces.CylinderSurface.CalculateBestPoseAtSurface().
MinimalTranslationPoseAtSurface()
Pose Oculus.Interaction.HandPosing.SnapSurfaces.CylinderSurface.MinimalTranslationPoseAtSurface (in Pose userPose, in Pose snapPose) protected
Referenced by Oculus.Interaction.HandPosing.SnapSurfaces.CylinderSurface.CalculateBestPoseAtSurface(), and Oculus.Interaction.HandPosing.SnapSurfaces.CylinderSurface.CalculateBestPoseAtSurface().
MirrorPose()
Pose Oculus.Interaction.HandPosing.SnapSurfaces.CylinderSurface.MirrorPose (in Pose gripPose)
Method for mirroring a Pose around the surface. Different surfaces will prefer mirroring along different axis.
Parameters
gripPose The Pose to be mirrored.
Returns
A new pose mirrored at this surface.
Implements Oculus.Interaction.HandPosing.SnapSurfaces.ISnapSurface.
NearestPointInSurface()
Vector3 Oculus.Interaction.HandPosing.SnapSurfaces.CylinderSurface.NearestPointInSurface (Vector3 targetPosition) protected
Referenced by Oculus.Interaction.HandPosing.SnapSurfaces.CylinderSurface.CalculateBestPoseAtSurface(), Oculus.Interaction.HandPosing.SnapSurfaces.CylinderSurface.MinimalRotationPoseAtSurface(), and Oculus.Interaction.HandPosing.SnapSurfaces.CylinderSurface.MinimalTranslationPoseAtSurface().
Start()
virtual void Oculus.Interaction.HandPosing.SnapSurfaces.CylinderSurface.Start () protected virtual
Member Data Documentation
_data
CylinderSurfaceData Oculus.Interaction.HandPosing.SnapSurfaces.CylinderSurface._data = new CylinderSurfaceData() protected
Referenced by Oculus.Interaction.HandPosing.SnapSurfaces.CylinderSurface.CreateDuplicatedSurface(), Oculus.Interaction.HandPosing.SnapSurfaces.CylinderSurface.CreateMirroredSurface(), Oculus.Interaction.HandPosing.SnapSurfaces.CylinderSurface.InjectData(), and Oculus.Interaction.HandPosing.SnapSurfaces.CylinderSurface.Start().
Property Documentation
Angle
float Oculus.Interaction.HandPosing.SnapSurfaces.CylinderSurface.Angle get set
The maximum angle for the surface of the cylinder, starting from the original grip position. To invert the direction of the angle, swap the caps order.
Referenced by Oculus.Interaction.HandPosing.SnapSurfaces.CylinderSurface.NearestPointInSurface().
Data
CylinderSurfaceData Oculus.Interaction.HandPosing.SnapSurfaces.CylinderSurface.Data get set
Getter for the data-only version of this surface. Used so it can be stored when created at Play-Mode.
Direction
Vector3 Oculus.Interaction.HandPosing.SnapSurfaces.CylinderSurface.Direction get
The direction of the central axis of the cylinder.
Referenced by Oculus.Interaction.HandPosing.SnapSurfaces.CylinderSurface.CalculateBestPoseAtSurface(), Oculus.Interaction.HandPosing.SnapSurfaces.CylinderSurface.CalculateRotationOffset(), Oculus.Interaction.HandPosing.SnapSurfaces.CylinderSurface.MinimalRotationPoseAtSurface(), Oculus.Interaction.HandPosing.SnapSurfaces.CylinderSurface.MirrorPose(), and Oculus.Interaction.HandPosing.SnapSurfaces.CylinderSurface.NearestPointInSurface().
EndAngleDir
Vector3 Oculus.Interaction.HandPosing.SnapSurfaces.CylinderSurface.EndAngleDir get
Direction from the axis of the cylinder to the maximum angle allowance.
Referenced by Oculus.Interaction.HandPosing.SnapSurfaces.CylinderSurface.NearestPointInSurface().
EndPoint
Vector3 Oculus.Interaction.HandPosing.SnapSurfaces.CylinderSurface.EndPoint get set
End cap of the cylinder, in world coordinates.
GripPoint
Transform Oculus.Interaction.HandPosing.SnapSurfaces.CylinderSurface.GripPoint get set
Valid point at which the hand can snap, typically the SnapPoint position itself.
Referenced by Oculus.Interaction.HandPosing.SnapSurfaces.CylinderSurface.CalculateRotationOffset().
Radius
float Oculus.Interaction.HandPosing.SnapSurfaces.CylinderSurface.Radius get
The generated radius of the cylinder. Represents the distance from the axis of the cylinder to the original grip position.
Referenced by Oculus.Interaction.HandPosing.SnapSurfaces.CylinderSurface.CalculateBestPoseAtSurface(), Oculus.Interaction.HandPosing.SnapSurfaces.CylinderSurface.MinimalRotationPoseAtSurface(), and Oculus.Interaction.HandPosing.SnapSurfaces.CylinderSurface.NearestPointInSurface().
RelativeTo
Transform Oculus.Interaction.HandPosing.SnapSurfaces.CylinderSurface.RelativeTo get set
Transform to which the surface refers to.
Referenced by Oculus.Interaction.HandPosing.SnapSurfaces.CylinderSurface.MirrorPose().
StartAngleDir
Vector3 Oculus.Interaction.HandPosing.SnapSurfaces.CylinderSurface.StartAngleDir get
Direction from the axis of the cylinder to the original grip position.
Referenced by Oculus.Interaction.HandPosing.SnapSurfaces.CylinderSurface.MirrorPose(), and Oculus.Interaction.HandPosing.SnapSurfaces.CylinderSurface.NearestPointInSurface().
StartPoint
Vector3 Oculus.Interaction.HandPosing.SnapSurfaces.CylinderSurface.StartPoint get set
Base cap of the cylinder, in world coordinates.
Referenced by Oculus.Interaction.HandPosing.SnapSurfaces.CylinderSurface.CalculateBestPoseAtSurface(), Oculus.Interaction.HandPosing.SnapSurfaces.CylinderSurface.CalculateRotationOffset(), and Oculus.Interaction.HandPosing.SnapSurfaces.CylinderSurface.NearestPointInSurface().
The documentation for this class was generated from the following file:
C:/Users/Lykos/Desktop/Projects/Capstone/VRGames/Assets/ThirdParty/Oculus/Interaction/Runtime/Scripts/HandPosing/SnapSurfaces/CylinderSurface.cs