VRGames: UnityEngine.XR.InteractionSubsystems.XRGestureSubsystem Class Reference
UnityEngine.XR.InteractionSubsystems.XRGestureSubsystem Class Reference abstract
This class controls the lifecycle of an XR Gesture subsystem.
Classes
class Provider
The API this subsystem uses to interop with different provider implementations.
Public Member Functions
XRGestureSubsystem ()
Do not call this directly. Call create on a valid XRGestureSubsystemDescriptor instead.
override void Start ()
Starts or resumes the Gesture subsystem.
override void Stop ()
Pauses the Gesture subsystem.
override void Destroy ()
Destroys the Gesture subsystem.
void Update ()
Trigger the Gesture's update loop.
Protected Member Functions
Provider CreateProvider ()
Implement this to provide this class with an interface to platform specific implementations.
Properties
override bool running [get]
Whether the Gesture subsystem is currently running.
NativeArray< ActivateGestureEvent > activateGestureEvents [get]
A collection of all ActivateGestureEvents managed by this subsystem. This is cleared every frame and refreshed with new gesture events.
Detailed Description
This class controls the lifecycle of an XR Gesture subsystem.
Constructor & Destructor Documentation
XRGestureSubsystem()
UnityEngine.XR.InteractionSubsystems.XRGestureSubsystem.XRGestureSubsystem ()
Do not call this directly. Call create on a valid XRGestureSubsystemDescriptor instead.
Member Function Documentation
CreateProvider()
Provider UnityEngine.XR.InteractionSubsystems.XRGestureSubsystem.CreateProvider () abstract protected
Implement this to provide this class with an interface to platform specific implementations.
Returns
An implementation specific provider.
Referenced by UnityEngine.XR.InteractionSubsystems.XRGestureSubsystem.XRGestureSubsystem().
Destroy()
override void UnityEngine.XR.InteractionSubsystems.XRGestureSubsystem.Destroy () sealed
Destroys the Gesture subsystem.
Start()
override void UnityEngine.XR.InteractionSubsystems.XRGestureSubsystem.Start () sealed
Starts or resumes the Gesture subsystem.
Referenced by UnityEngine.XR.InteractionSubsystems.Tests.XRGestureSubsystemTestFixture.RunningStateTests().
Stop()
override void UnityEngine.XR.InteractionSubsystems.XRGestureSubsystem.Stop () sealed
Pauses the Gesture subsystem.
Referenced by UnityEngine.XR.InteractionSubsystems.XRGestureSubsystem.Destroy(), and UnityEngine.XR.InteractionSubsystems.Tests.XRGestureSubsystemTestFixture.RunningStateTests().
Update()
void UnityEngine.XR.InteractionSubsystems.XRGestureSubsystem.Update ()
Trigger the Gesture's update loop.
Property Documentation
activateGestureEvents
NativeArray<ActivateGestureEvent> UnityEngine.XR.InteractionSubsystems.XRGestureSubsystem.activateGestureEvents get
A collection of all ActivateGestureEvents managed by this subsystem. This is cleared every frame and refreshed with new gesture events.
running
override bool UnityEngine.XR.InteractionSubsystems.XRGestureSubsystem.running get sealed
Whether the Gesture subsystem is currently running.
Referenced by UnityEngine.XR.InteractionSubsystems.Tests.XRGestureSubsystemTestFixture.RunningStateTests().
The documentation for this class was generated from the following file:
C:/Users/Lykos/Desktop/Projects/Capstone/VRGames/Library/PackageCache/com.unity.xr.interactionsubsystems@1.0.1/Runtime/GestureSubsystem/XRGestureSubsystem.cs