VRGames: OvrAvatarRenderComponent Class Reference
OvrAvatarRenderComponent Class Reference
Public Attributes
SkinnedMeshRenderer mesh
Transform[] bones
Protected Member Functions
void UpdateActive (OvrAvatar avatar, ovrAvatarVisibilityFlags mask)
SkinnedMeshRenderer CreateSkinnedMesh (ulong assetID, ovrAvatarVisibilityFlags visibilityMask, int thirdPersonLayer, int firstPersonLayer)
void UpdateSkinnedMesh (OvrAvatar avatar, Transform[] bones, ovrAvatarTransform localTransform, ovrAvatarVisibilityFlags visibilityMask, IntPtr renderPart)
Material CreateAvatarMaterial (string name, Shader shader)
Member Function Documentation
CreateAvatarMaterial()
Material OvrAvatarRenderComponent.CreateAvatarMaterial (string name, Shader shader) protected
CreateSkinnedMesh()
SkinnedMeshRenderer OvrAvatarRenderComponent.CreateSkinnedMesh (ulong assetID, ovrAvatarVisibilityFlags visibilityMask, int thirdPersonLayer, int firstPersonLayer) protected
UpdateActive()
void OvrAvatarRenderComponent.UpdateActive (OvrAvatar avatar, ovrAvatarVisibilityFlags mask) protected
Referenced by UpdateSkinnedMesh().
UpdateSkinnedMesh()
void OvrAvatarRenderComponent.UpdateSkinnedMesh (OvrAvatar avatar, Transform[] bones, ovrAvatarTransform localTransform, ovrAvatarVisibilityFlags visibilityMask, IntPtr renderPart) protected
Referenced by OvrAvatarSkinnedMeshRenderComponent.UpdateSkinnedMeshRender(), and OvrAvatarSkinnedMeshPBSV2RenderComponent.UpdateSkinnedMeshRender().
Member Data Documentation
bones
Transform [] OvrAvatarRenderComponent.bones
Referenced by UpdateSkinnedMesh(), OvrAvatarSkinnedMeshRenderComponent.UpdateSkinnedMeshRender(), and OvrAvatarSkinnedMeshPBSV2RenderComponent.UpdateSkinnedMeshRender().
mesh
SkinnedMeshRenderer OvrAvatarRenderComponent.mesh
Referenced by OvrAvatarSkinnedMeshRenderComponent.UpdateSkinnedMeshRender(), and OvrAvatarSkinnedMeshPBSV2RenderComponent.UpdateSkinnedMeshRender().
The documentation for this class was generated from the following file:
C:/Users/Lykos/Desktop/Projects/Capstone/VRGames/Assets/ThirdParty/Oculus/Avatar/Scripts/OvrAvatarRenderComponent.cs