VRGames: Oculus.Interaction.RayInteractorPinchVisual Class Reference
Oculus.Interaction.RayInteractorPinchVisual Class Reference
Public Member Functions
void InjectAllRayInteractorPinchVisual (IHand hand, RayInteractor rayInteractor, SkinnedMeshRenderer skinnedMeshRenderer)
void InjectHand (IHand hand)
void InjectRayInteractor (RayInteractor rayInteractor)
void InjectSkinnedMeshRenderer (SkinnedMeshRenderer skinnedMeshRenderer)
Protected Member Functions
virtual void Awake ()
virtual void Start ()
virtual void OnEnable ()
virtual void OnDisable ()
Protected Attributes
bool _started = false
Properties
AnimationCurve RemapCurve [get, set]
Vector2 AlphaRange [get, set]
Member Function Documentation
Awake()
virtual void Oculus.Interaction.RayInteractorPinchVisual.Awake () protected virtual
InjectAllRayInteractorPinchVisual()
void Oculus.Interaction.RayInteractorPinchVisual.InjectAllRayInteractorPinchVisual (IHand hand, RayInteractor rayInteractor, SkinnedMeshRenderer skinnedMeshRenderer)
InjectHand()
void Oculus.Interaction.RayInteractorPinchVisual.InjectHand (IHand hand)
Referenced by Oculus.Interaction.RayInteractorPinchVisual.InjectAllRayInteractorPinchVisual().
InjectRayInteractor()
void Oculus.Interaction.RayInteractorPinchVisual.InjectRayInteractor (RayInteractor rayInteractor)
Referenced by Oculus.Interaction.RayInteractorPinchVisual.InjectAllRayInteractorPinchVisual().
InjectSkinnedMeshRenderer()
void Oculus.Interaction.RayInteractorPinchVisual.InjectSkinnedMeshRenderer (SkinnedMeshRenderer skinnedMeshRenderer)
Referenced by Oculus.Interaction.RayInteractorPinchVisual.InjectAllRayInteractorPinchVisual().
OnDisable()
virtual void Oculus.Interaction.RayInteractorPinchVisual.OnDisable () protected virtual
OnEnable()
virtual void Oculus.Interaction.RayInteractorPinchVisual.OnEnable () protected virtual
Start()
virtual void Oculus.Interaction.RayInteractorPinchVisual.Start () protected virtual
Member Data Documentation
_started
bool Oculus.Interaction.RayInteractorPinchVisual._started = false protected
Referenced by Oculus.Interaction.RayInteractorPinchVisual.OnDisable(), Oculus.Interaction.RayInteractorPinchVisual.OnEnable(), and Oculus.Interaction.RayInteractorPinchVisual.Start().
Property Documentation
AlphaRange
Vector2 Oculus.Interaction.RayInteractorPinchVisual.AlphaRange get set
RemapCurve
AnimationCurve Oculus.Interaction.RayInteractorPinchVisual.RemapCurve get set
The documentation for this class was generated from the following file:
C:/Users/Lykos/Desktop/Projects/Capstone/VRGames/Assets/ThirdParty/Oculus/Interaction/Runtime/Scripts/Interaction/Models/Ray/Visuals/RayInteractorPinchVisual.cs