VRGames: UnityEngine.EventSystems.StandaloneInputModule Class Reference
UnityEngine.EventSystems.StandaloneInputModule Class Reference
A BaseInputModule designed for mouse / keyboard / controller input.
Public Types
enum InputMode { Mouse , Buttons }
Public Member Functions
override void UpdateModule ()
override bool ShouldActivateModule ()
override void ActivateModule ()
See BaseInputModule.
override void DeactivateModule ()
See BaseInputModule.
override void Process ()
Public Member Functions inherited from UnityEngine.EventSystems.PointerInputModule
override bool IsPointerOverGameObject (int pointerId)
override string ToString ()
Protected Member Functions
StandaloneInputModule ()
void ProcessTouchPress (PointerEventData pointerEvent, bool pressed, bool released)
This method is called by Unity whenever a touch event is processed. Override this method with a custom implementation to process touch events yourself.
bool SendSubmitEventToSelectedObject ()
Calculate and send a submit event to the current selected object.
bool SendMoveEventToSelectedObject ()
Calculate and send a move event to the current selected object.
void ProcessMouseEvent ()
virtual bool ForceAutoSelect ()
void ProcessMouseEvent (int id)
Process all mouse events.
bool SendUpdateEventToSelectedObject ()
void ProcessMousePress (MouseButtonEventData data)
Calculate and process any mouse button state changes.
GameObject GetCurrentFocusedGameObject ()
Protected Member Functions inherited from UnityEngine.EventSystems.PointerInputModule
bool GetPointerData (int id, out PointerEventData data, bool create)
Search the cache for currently active pointers, return true if found.
void RemovePointerData (PointerEventData data)
Remove the PointerEventData from the cache.
PointerEventData GetTouchPointerEventData (Touch input, out bool pressed, out bool released)
Given a touch populate the PointerEventData and return if we are pressed or released.
void CopyFromTo (PointerEventData @from, PointerEventData @to)
Copy one PointerEventData to another.
PointerEventData.FramePressState StateForMouseButton (int buttonId)
Given a mouse button return the current state for the frame.
virtual MouseState GetMousePointerEventData ()
Return the current MouseState. Using the default pointer.
virtual MouseState GetMousePointerEventData (int id)
Return the current MouseState.
PointerEventData GetLastPointerEventData (int id)
Return the last PointerEventData for the given touch / mouse id.
virtual void ProcessMove (PointerEventData pointerEvent)
Process movement for the current frame with the given pointer event.
virtual void ProcessDrag (PointerEventData pointerEvent)
Process the drag for the current frame with the given pointer event.
void ClearSelection ()
Clear all pointers and deselect any selected objects in the EventSystem.
void DeselectIfSelectionChanged (GameObject currentOverGo, BaseEventData pointerEvent)
Deselect the current selected GameObject if the currently pointed-at GameObject is different.
Properties
InputMode inputMode [get]
bool allowActivationOnMobileDevice [get, set]
bool forceModuleActive [get, set]
Force this module to be active.
float inputActionsPerSecond [get, set]
Number of keyboard / controller inputs allowed per second.
float repeatDelay [get, set]
Delay in seconds before the input actions per second repeat rate takes effect.
string horizontalAxis [get, set]
Name of the horizontal axis for movement (if axis events are used).
string verticalAxis [get, set]
Name of the vertical axis for movement (if axis events are used).
string submitButton [get, set]
Maximum number of input events handled per second.
string cancelButton [get, set]
Input manager name for the 'cancel' button.
Additional Inherited Members
Static Public Attributes inherited from UnityEngine.EventSystems.PointerInputModule
const int kMouseLeftId = -1
Id of the cached left mouse pointer event.
const int kMouseRightId = -2
Id of the cached right mouse pointer event.
const int kMouseMiddleId = -3
Id of the cached middle mouse pointer event.
const int kFakeTouchesId = -4
Touch id for when simulating touches on a non touch device.
Protected Attributes inherited from UnityEngine.EventSystems.PointerInputModule
Dictionary< int, PointerEventData > m_PointerData = new Dictionary<int, PointerEventData>()
Detailed Description
A BaseInputModule designed for mouse / keyboard / controller input.
Input module for working with, mouse, keyboard, or controller.
Member Enumeration Documentation
InputMode
enum UnityEngine.EventSystems.StandaloneInputModule.InputMode
Enumerator
Mouse
Buttons
Constructor & Destructor Documentation
StandaloneInputModule()
UnityEngine.EventSystems.StandaloneInputModule.StandaloneInputModule () protected
Member Function Documentation
ActivateModule()
override void UnityEngine.EventSystems.StandaloneInputModule.ActivateModule ()
See BaseInputModule.
DeactivateModule()
override void UnityEngine.EventSystems.StandaloneInputModule.DeactivateModule ()
See BaseInputModule.
ForceAutoSelect()
virtual bool UnityEngine.EventSystems.StandaloneInputModule.ForceAutoSelect () protected virtual
GetCurrentFocusedGameObject()
GameObject UnityEngine.EventSystems.StandaloneInputModule.GetCurrentFocusedGameObject () protected
Process()
override void UnityEngine.EventSystems.StandaloneInputModule.Process ()
ProcessMouseEvent() [1/2]
void UnityEngine.EventSystems.StandaloneInputModule.ProcessMouseEvent () protected
Referenced by UnityEngine.EventSystems.StandaloneInputModule.Process(), and UnityEngine.EventSystems.StandaloneInputModule.ProcessMouseEvent().
ProcessMouseEvent() [2/2]
void UnityEngine.EventSystems.StandaloneInputModule.ProcessMouseEvent (int id) protected
Process all mouse events.
ProcessMousePress()
void UnityEngine.EventSystems.StandaloneInputModule.ProcessMousePress (MouseButtonEventData data) protected
Calculate and process any mouse button state changes.
Referenced by UnityEngine.EventSystems.StandaloneInputModule.ProcessMouseEvent().
ProcessTouchPress()
void UnityEngine.EventSystems.StandaloneInputModule.ProcessTouchPress (PointerEventData pointerEvent, bool pressed, bool released) protected
This method is called by Unity whenever a touch event is processed. Override this method with a custom implementation to process touch events yourself.
Parameters
pointerEvent Event data relating to the touch event, such as position and ID to be passed to the touch event destination object.
pressed This is true for the first frame of a touch event, and false thereafter. This can therefore be used to determine the instant a touch event occurred.
released This is true only for the last frame of a touch event.
This method can be overridden in derived classes to change how touch press events are handled.
SendMoveEventToSelectedObject()
bool UnityEngine.EventSystems.StandaloneInputModule.SendMoveEventToSelectedObject () protected
Calculate and send a move event to the current selected object.
Returns
If the move event was used by the selected object.
Referenced by UnityEngine.EventSystems.StandaloneInputModule.Process().
SendSubmitEventToSelectedObject()
bool UnityEngine.EventSystems.StandaloneInputModule.SendSubmitEventToSelectedObject () protected
Calculate and send a submit event to the current selected object.
Returns
If the submit event was used by the selected object.
Referenced by UnityEngine.EventSystems.StandaloneInputModule.Process().
SendUpdateEventToSelectedObject()
bool UnityEngine.EventSystems.StandaloneInputModule.SendUpdateEventToSelectedObject () protected
Referenced by UnityEngine.EventSystems.StandaloneInputModule.Process().
ShouldActivateModule()
override bool UnityEngine.EventSystems.StandaloneInputModule.ShouldActivateModule ()
UpdateModule()
override void UnityEngine.EventSystems.StandaloneInputModule.UpdateModule ()
Property Documentation
allowActivationOnMobileDevice
bool UnityEngine.EventSystems.StandaloneInputModule.allowActivationOnMobileDevice get set
cancelButton
string UnityEngine.EventSystems.StandaloneInputModule.cancelButton get set
Input manager name for the 'cancel' button.
forceModuleActive
bool UnityEngine.EventSystems.StandaloneInputModule.forceModuleActive get set
Force this module to be active.
If there is no module active with higher priority (ordered in the inspector) this module will be forced active even if valid enabling conditions are not met.
horizontalAxis
string UnityEngine.EventSystems.StandaloneInputModule.horizontalAxis get set
Name of the horizontal axis for movement (if axis events are used).
inputActionsPerSecond
float UnityEngine.EventSystems.StandaloneInputModule.inputActionsPerSecond get set
Number of keyboard / controller inputs allowed per second.
inputMode
InputMode UnityEngine.EventSystems.StandaloneInputModule.inputMode get
repeatDelay
float UnityEngine.EventSystems.StandaloneInputModule.repeatDelay get set
Delay in seconds before the input actions per second repeat rate takes effect.
If the same direction is sustained, the inputActionsPerSecond property can be used to control the rate at which events are fired. However, it can be desirable that the first repetition is delayed, so the user doesn't get repeated actions by accident.
submitButton
string UnityEngine.EventSystems.StandaloneInputModule.submitButton get set
Maximum number of input events handled per second.
verticalAxis
string UnityEngine.EventSystems.StandaloneInputModule.verticalAxis get set
Name of the vertical axis for movement (if axis events are used).
The documentation for this class was generated from the following file:
C:/Users/Lykos/Desktop/Projects/Capstone/VRGames/Library/PackageCache/com.unity.ugui@1.0.0/Runtime/EventSystem/InputModules/StandaloneInputModule.cs