VRGames: OculusSampleFramework.TrainLocomotive Class Reference
OculusSampleFramework.TrainLocomotive Class Reference
Public Member Functions
override void UpdatePosition ()
void StartStopStateChanged ()
void DecreaseSpeedStateChanged ()
void IncreaseSpeedStateChanged ()
void SmokeButtonStateChanged ()
void WhistleButtonStateChanged ()
void ReverseButtonStateChanged ()
Public Member Functions inherited from OculusSampleFramework.TrainCarBase
void UpdatePose (float distance, TrainCarBase train, Pose pose)
void UpdatePosition ()
Protected Attributes
float _initialSpeed = 0f
Protected Attributes inherited from OculusSampleFramework.TrainCarBase
Transform _frontWheels = null
Transform _rearWheels = null
TrainTrack _trainTrack = null
Transform[] _individualWheels = null
float scale = 1.0f
Additional Inherited Members
Protected Member Functions inherited from OculusSampleFramework.TrainCarBase
virtual void Awake ()
void UpdateCarPosition ()
void RotateCarWheels ()
Properties inherited from OculusSampleFramework.TrainCarBase
float Distance [get, protected set]
float Scale [get, set]
Member Function Documentation
DecreaseSpeedStateChanged()
void OculusSampleFramework.TrainLocomotive.DecreaseSpeedStateChanged ()
Referenced by OculusSampleFramework.ControllerBoxController.DecreaseSpeedStateChanged().
IncreaseSpeedStateChanged()
void OculusSampleFramework.TrainLocomotive.IncreaseSpeedStateChanged ()
Referenced by OculusSampleFramework.ControllerBoxController.IncreaseSpeedStateChanged().
ReverseButtonStateChanged()
void OculusSampleFramework.TrainLocomotive.ReverseButtonStateChanged ()
Referenced by OculusSampleFramework.ControllerBoxController.ReverseButtonStateChanged().
SmokeButtonStateChanged()
void OculusSampleFramework.TrainLocomotive.SmokeButtonStateChanged ()
Referenced by OculusSampleFramework.ControllerBoxController.SmokeButtonStateChanged().
StartStopStateChanged()
void OculusSampleFramework.TrainLocomotive.StartStopStateChanged ()
Referenced by OculusSampleFramework.ControllerBoxController.StartStopStateChanged().
UpdatePosition()
override void OculusSampleFramework.TrainLocomotive.UpdatePosition ()
WhistleButtonStateChanged()
void OculusSampleFramework.TrainLocomotive.WhistleButtonStateChanged ()
Referenced by OculusSampleFramework.ControllerBoxController.WhistleButtonStateChanged().
Member Data Documentation
_initialSpeed
float OculusSampleFramework.TrainLocomotive._initialSpeed = 0f protected
The documentation for this class was generated from the following file:
C:/Users/Lykos/Desktop/Projects/Capstone/VRGames/Assets/ThirdParty/Oculus/SampleFramework/Usage/HandsTrainExample/Scripts/TrainLocomotive.cs