VRGames: UnityEngine.ProBuilder.Poly2Tri.Polygon Class Reference
UnityEngine.ProBuilder.Poly2Tri.Polygon Class Reference
Public Member Functions
Polygon (IList< PolygonPoint > points)
Create a polygon from a list of at least 3 points with no duplicates.
Polygon (IEnumerable< PolygonPoint > points)
Create a polygon from a list of at least 3 points with no duplicates.
Polygon (params PolygonPoint[] points)
Create a polygon from a list of at least 3 points with no duplicates.
void AddSteinerPoint (TriangulationPoint point)
void AddSteinerPoints (List< TriangulationPoint > points)
void ClearSteinerPoints ()
void AddHole (Polygon poly)
Add a hole to the polygon.
void InsertPointAfter (PolygonPoint point, PolygonPoint newPoint)
Inserts newPoint after point.
void AddPoints (IEnumerable< PolygonPoint > list)
Inserts list (after last point in polygon?)
void AddPoint (PolygonPoint p)
Adds a point after the last in the polygon.
void RemovePoint (PolygonPoint p)
Removes a point from the polygon.
void AddTriangle (DelaunayTriangle t)
void AddTriangles (IEnumerable< DelaunayTriangle > list)
void ClearTriangles ()
void Prepare (TriangulationContext tcx)
Creates constraints and populates the context with points.
Protected Attributes
List< TriangulationPoint > _points = new List<TriangulationPoint>()
List< TriangulationPoint > _steinerPoints
List< Polygon > _holes
List< DelaunayTriangle > _triangles
PolygonPoint _last
Properties
TriangulationMode TriangulationMode [get]
IList< TriangulationPoint > Points [get]
IList< DelaunayTriangle > Triangles [get]
IList< Polygon > Holes [get]
Properties inherited from UnityEngine.ProBuilder.Poly2Tri.Triangulatable
Constructor & Destructor Documentation
Polygon() [1/3]
UnityEngine.ProBuilder.Poly2Tri.Polygon.Polygon (IList< PolygonPoint > points)
Create a polygon from a list of at least 3 points with no duplicates.
Parameters
points A list of unique points
Polygon() [2/3]
UnityEngine.ProBuilder.Poly2Tri.Polygon.Polygon (IEnumerable< PolygonPoint > points)
Create a polygon from a list of at least 3 points with no duplicates.
Parameters
points A list of unique points.
Polygon() [3/3]
UnityEngine.ProBuilder.Poly2Tri.Polygon.Polygon (params PolygonPoint[] points)
Create a polygon from a list of at least 3 points with no duplicates.
Parameters
points A list of unique points.
Member Function Documentation
AddHole()
void UnityEngine.ProBuilder.Poly2Tri.Polygon.AddHole (Polygon poly)
Add a hole to the polygon.
Parameters
poly A subtraction polygon fully contained inside this polygon.
AddPoint()
void UnityEngine.ProBuilder.Poly2Tri.Polygon.AddPoint (PolygonPoint p)
Adds a point after the last in the polygon.
Parameters
p The point to add
AddPoints()
void UnityEngine.ProBuilder.Poly2Tri.Polygon.AddPoints (IEnumerable< PolygonPoint > list)
Inserts list (after last point in polygon?)
Parameters
list
AddSteinerPoint()
void UnityEngine.ProBuilder.Poly2Tri.Polygon.AddSteinerPoint (TriangulationPoint point)
AddSteinerPoints()
void UnityEngine.ProBuilder.Poly2Tri.Polygon.AddSteinerPoints (List< TriangulationPoint > points)
AddTriangle()
void UnityEngine.ProBuilder.Poly2Tri.Polygon.AddTriangle (DelaunayTriangle t)
Implements UnityEngine.ProBuilder.Poly2Tri.Triangulatable.
AddTriangles()
void UnityEngine.ProBuilder.Poly2Tri.Polygon.AddTriangles (IEnumerable< DelaunayTriangle > list)
Implements UnityEngine.ProBuilder.Poly2Tri.Triangulatable.
ClearSteinerPoints()
void UnityEngine.ProBuilder.Poly2Tri.Polygon.ClearSteinerPoints ()
ClearTriangles()
void UnityEngine.ProBuilder.Poly2Tri.Polygon.ClearTriangles ()
Implements UnityEngine.ProBuilder.Poly2Tri.Triangulatable.
InsertPointAfter()
void UnityEngine.ProBuilder.Poly2Tri.Polygon.InsertPointAfter (PolygonPoint point, PolygonPoint newPoint)
Inserts newPoint after point.
Parameters
point The point to insert after in the polygon
newPoint The point to insert into the polygon
Prepare()
void UnityEngine.ProBuilder.Poly2Tri.Polygon.Prepare (TriangulationContext tcx)
Creates constraints and populates the context with points.
Parameters
tcx The context
Implements UnityEngine.ProBuilder.Poly2Tri.Triangulatable.
RemovePoint()
void UnityEngine.ProBuilder.Poly2Tri.Polygon.RemovePoint (PolygonPoint p)
Removes a point from the polygon.
Parameters
p
Member Data Documentation
_holes
List<Polygon> UnityEngine.ProBuilder.Poly2Tri.Polygon._holes protected
Referenced by UnityEngine.ProBuilder.Poly2Tri.Polygon.AddHole(), and UnityEngine.ProBuilder.Poly2Tri.Polygon.Prepare().
_last
PolygonPoint UnityEngine.ProBuilder.Poly2Tri.Polygon._last protected
Referenced by UnityEngine.ProBuilder.Poly2Tri.Polygon.AddPoint(), and UnityEngine.ProBuilder.Poly2Tri.Polygon.AddPoints().
_points
List<TriangulationPoint> UnityEngine.ProBuilder.Poly2Tri.Polygon._points = new List<TriangulationPoint>() protected
Referenced by UnityEngine.ProBuilder.Poly2Tri.Polygon.AddPoint(), UnityEngine.ProBuilder.Poly2Tri.Polygon.AddPoints(), UnityEngine.ProBuilder.Poly2Tri.Polygon.InsertPointAfter(), UnityEngine.ProBuilder.Poly2Tri.Polygon.Polygon(), UnityEngine.ProBuilder.Poly2Tri.Polygon.Prepare(), and UnityEngine.ProBuilder.Poly2Tri.Polygon.RemovePoint().
_steinerPoints
List<TriangulationPoint> UnityEngine.ProBuilder.Poly2Tri.Polygon._steinerPoints protected
Referenced by UnityEngine.ProBuilder.Poly2Tri.Polygon.AddSteinerPoint(), UnityEngine.ProBuilder.Poly2Tri.Polygon.AddSteinerPoints(), UnityEngine.ProBuilder.Poly2Tri.Polygon.ClearSteinerPoints(), and UnityEngine.ProBuilder.Poly2Tri.Polygon.Prepare().
_triangles
List<DelaunayTriangle> UnityEngine.ProBuilder.Poly2Tri.Polygon._triangles protected
Referenced by UnityEngine.ProBuilder.Poly2Tri.Polygon.AddTriangle(), UnityEngine.ProBuilder.Poly2Tri.Polygon.AddTriangles(), UnityEngine.ProBuilder.Poly2Tri.Polygon.ClearTriangles(), and UnityEngine.ProBuilder.Poly2Tri.Polygon.Prepare().
Property Documentation
Holes
IList<Polygon> UnityEngine.ProBuilder.Poly2Tri.Polygon.Holes get
Points
IList<TriangulationPoint> UnityEngine.ProBuilder.Poly2Tri.Polygon.Points get
Implements UnityEngine.ProBuilder.Poly2Tri.Triangulatable.
Triangles
IList<DelaunayTriangle> UnityEngine.ProBuilder.Poly2Tri.Polygon.Triangles get
Implements UnityEngine.ProBuilder.Poly2Tri.Triangulatable.
TriangulationMode
TriangulationMode UnityEngine.ProBuilder.Poly2Tri.Polygon.TriangulationMode get
Implements UnityEngine.ProBuilder.Poly2Tri.Triangulatable.
The documentation for this class was generated from the following file:
C:/Users/Lykos/Desktop/Projects/Capstone/VRGames/Library/PackageCache/com.unity.probuilder@5.0.6/External/Poly2Tri/Polygon/Polygon.cs