VRGames: OVR.AudioManager Class Reference
OVR.AudioManager Class Reference
Public Types
enum Fade { In , Out }
Public Member Functions
void MuteAllSounds (bool mute, bool muteReserved=false)
void UnMuteAllSounds (bool unmute, bool unmuteReserved=false)
Static Public Member Functions
static SoundFX FindSoundFX (string name, bool rebuildCache=false)
static GameObject GetGameObject ()
static string NameMinusGroup (string name)
static string[] GetSoundFXNames (string currentValue, out int currentIdx)
static void FadeOutSoundChannel (int channel, float delaySecs, float fadeTime)
static bool StopSound (int idx, bool fadeOut=true, bool stopReserved=false)
static void FadeInSound (int idx, float fadeTime, float volume)
static void FadeInSound (int idx, float fadeTime)
static void FadeOutSound (int idx, float fadeTime)
static void StopAllSounds (bool fadeOut, bool stopReserved=false)
static float GetEmitterEndTime (int idx)
static float SetEmitterTime (int idx, float time)
static int PlaySound (AudioClip clip, float volume, EmitterChannel src=EmitterChannel.Any, float delay=0.0f, float pitchVariance=1.0f, bool loop=false)
static int PlaySound (SoundFX soundFX, EmitterChannel src=EmitterChannel.Any, float delay=0.0f)
static int PlaySoundAt (Vector3 position, SoundFX soundFX, EmitterChannel src=EmitterChannel.Any, float delay=0.0f, float volumeOverride=1.0f, float pitchMultiplier=1.0f)
static int PlayRandomSoundAt (Vector3 position, AudioClip[] clips, float volume, EmitterChannel src=EmitterChannel.Any, float delay=0.0f, float pitch=1.0f, bool loop=false)
static int PlaySoundAt (Vector3 position, AudioClip clip, float volume=1.0f, EmitterChannel src=EmitterChannel.Any, float delay=0.0f, float pitch=1.0f, bool loop=false)
static void SetOnFinished (int emitterIdx, System.Action onFinished)
static void SetOnFinished (int emitterIdx, System.Action< object > onFinished, object obj)
static void AttachSoundToParent (int idx, Transform parent)
static void DetachSoundFromParent (int idx)
static void DetachSoundsFromParent (SoundEmitter[] emitters, bool stopSounds=true)
static void SetEmitterMixerGroup (int idx, AudioMixerGroup mixerGroup)
static MixerSnapshot GetActiveSnapshot ()
static void SetCurrentSnapshot (MixerSnapshot mixerSnapshot)
static void BlendWithCurrentSnapshot (MixerSnapshot blendSnapshot, float weight, float blendTime=0.0f)
Public Attributes
bool makePersistent = true
bool enableSpatializedAudio = true
bool enableSpatializedFastOverride = false
AudioMixer audioMixer = null
AudioMixerGroup defaultMixerGroup = null
AudioMixerGroup reservedMixerGroup = null
AudioMixerGroup voiceChatMixerGroup = null
bool verboseLogging = false
int maxSoundEmitters = 32
float volumeSoundFX = 1.0f
float soundFxFadeSecs = 1.0f
float audioMinFallOffDistance = 1.0f
float audioMaxFallOffDistance = 25.0f
SoundGroup[] soundGroupings = new SoundGroup[0]
Properties
static bool enableSpatialization [get]
static AudioManager Instance [get]
static float NearFallOff [get]
static float FarFallOff [get]
static AudioMixerGroup EmitterGroup [get]
static AudioMixerGroup ReservedGroup [get]
static AudioMixerGroup VoipGroup [get]
static bool SoundEnabled [get]
Member Enumeration Documentation
Fade
enum OVR.AudioManager.Fade
Enumerator
In
Out
Member Function Documentation
AttachSoundToParent()
static void OVR.AudioManager.AttachSoundToParent (int idx, Transform parent) static
Referenced by OVR.SoundFX.AttachToParent().
BlendWithCurrentSnapshot()
static void OVR.AudioManager.BlendWithCurrentSnapshot (MixerSnapshot blendSnapshot, float weight, float blendTime = 0::0f) static
DetachSoundFromParent()
static void OVR.AudioManager.DetachSoundFromParent (int idx) static
Referenced by OVR.SoundFX.DetachFromParent().
DetachSoundsFromParent()
static void OVR.AudioManager.DetachSoundsFromParent (SoundEmitter[] emitters, bool stopSounds = true) static
FadeInSound() [1/2]
static void OVR.AudioManager.FadeInSound (int idx, float fadeTime) static
FadeInSound() [2/2]
static void OVR.AudioManager.FadeInSound (int idx, float fadeTime, float volume) static
Referenced by OVR.AmbienceEmitter.Play().
FadeOutSound()
static void OVR.AudioManager.FadeOutSound (int idx, float fadeTime) static
Referenced by OVR.AmbienceEmitter.EnableEmitter().
FadeOutSoundChannel()
static void OVR.AudioManager.FadeOutSoundChannel (int channel, float delaySecs, float fadeTime) static
FindSoundFX()
static SoundFX OVR.AudioManager.FindSoundFX (string name, bool rebuildCache = false) static
GetActiveSnapshot()
static MixerSnapshot OVR.AudioManager.GetActiveSnapshot () static
GetEmitterEndTime()
static float OVR.AudioManager.GetEmitterEndTime (int idx) static
GetGameObject()
static GameObject OVR.AudioManager.GetGameObject () static
Referenced by OVR.SoundFXRefPropertyDrawer.OnGUI().
GetSoundFXNames()
static string[] OVR.AudioManager.GetSoundFXNames (string currentValue, out int currentIdx) static
Referenced by OVR.SoundFXRefPropertyDrawer.OnGUI().
MuteAllSounds()
void OVR.AudioManager.MuteAllSounds (bool mute, bool muteReserved = false)
NameMinusGroup()
static string OVR.AudioManager.NameMinusGroup (string name) static
Referenced by OVR.SoundFXRefPropertyDrawer.OnGUI().
PlayRandomSoundAt()
static int OVR.AudioManager.PlayRandomSoundAt (Vector3 position, AudioClip[] clips, float volume, EmitterChannel src = EmitterChannel::Any, float delay = 0::0f, float pitch = 1::0f, bool loop = false) static
PlaySound() [1/2]
static int OVR.AudioManager.PlaySound (AudioClip clip, float volume, EmitterChannel src = EmitterChannel::Any, float delay = 0::0f, float pitchVariance = 1::0f, bool loop = false) static
Referenced by OVR.SoundFXRefPropertyDrawer.OnGUI(), and OVR.SoundFX.PlaySound().
PlaySound() [2/2]
static int OVR.AudioManager.PlaySound (SoundFX soundFX, EmitterChannel src = EmitterChannel::Any, float delay = 0::0f) static
PlaySoundAt() [1/2]
static int OVR.AudioManager.PlaySoundAt (Vector3 position, AudioClip clip, float volume = 1::0f, EmitterChannel src = EmitterChannel::Any, float delay = 0::0f, float pitch = 1::0f, bool loop = false) static
PlaySoundAt() [2/2]
static int OVR.AudioManager.PlaySoundAt (Vector3 position, SoundFX soundFX, EmitterChannel src = EmitterChannel::Any, float delay = 0::0f, float volumeOverride = 1::0f, float pitchMultiplier = 1::0f) static
Referenced by OVR.AudioManager.PlayRandomSoundAt(), OVR.AudioManager.PlaySound(), OVR.AudioManager.PlaySound(), and OVR.SoundFX.PlaySoundAt().
SetCurrentSnapshot()
static void OVR.AudioManager.SetCurrentSnapshot (MixerSnapshot mixerSnapshot) static
SetEmitterMixerGroup()
static void OVR.AudioManager.SetEmitterMixerGroup (int idx, AudioMixerGroup mixerGroup) static
SetEmitterTime()
static float OVR.AudioManager.SetEmitterTime (int idx, float time) static
SetOnFinished() [1/2]
static void OVR.AudioManager.SetOnFinished (int emitterIdx, System::Action onFinished) static
Referenced by OVR.SoundFX.SetOnFinished(), and OVR.SoundFX.SetOnFinished().
SetOnFinished() [2/2]
static void OVR.AudioManager.SetOnFinished (int emitterIdx, System::Action< object > onFinished, object obj) static
StopAllSounds()
static void OVR.AudioManager.StopAllSounds (bool fadeOut, bool stopReserved = false) static
StopSound()
static bool OVR.AudioManager.StopSound (int idx, bool fadeOut = true, bool stopReserved = false) static
Referenced by OVR.SoundFXRefPropertyDrawer.OnGUI(), OVR.AudioManager.StopAllSounds(), and OVR.SoundFX.StopSound().
UnMuteAllSounds()
void OVR.AudioManager.UnMuteAllSounds (bool unmute, bool unmuteReserved = false)
Member Data Documentation
audioMaxFallOffDistance
float OVR.AudioManager.audioMaxFallOffDistance = 25.0f
audioMinFallOffDistance
float OVR.AudioManager.audioMinFallOffDistance = 1.0f
audioMixer
AudioMixer OVR.AudioManager.audioMixer = null
defaultMixerGroup
AudioMixerGroup OVR.AudioManager.defaultMixerGroup = null
enableSpatializedAudio
bool OVR.AudioManager.enableSpatializedAudio = true
enableSpatializedFastOverride
bool OVR.AudioManager.enableSpatializedFastOverride = false
makePersistent
bool OVR.AudioManager.makePersistent = true
maxSoundEmitters
int OVR.AudioManager.maxSoundEmitters = 32
reservedMixerGroup
AudioMixerGroup OVR.AudioManager.reservedMixerGroup = null
soundFxFadeSecs
float OVR.AudioManager.soundFxFadeSecs = 1.0f
soundGroupings
SoundGroup [] OVR.AudioManager.soundGroupings = new SoundGroup[0]
Referenced by OVR.AudioManager.GetSoundFXNames().
verboseLogging
bool OVR.AudioManager.verboseLogging = false
voiceChatMixerGroup
AudioMixerGroup OVR.AudioManager.voiceChatMixerGroup = null
volumeSoundFX
float OVR.AudioManager.volumeSoundFX = 1.0f
Property Documentation
EmitterGroup
AudioMixerGroup OVR.AudioManager.EmitterGroup static get
Referenced by OVR.AudioManager.PlaySoundAt(), and OVR.AudioManager.PlaySoundAt().
enableSpatialization
bool OVR.AudioManager.enableSpatialization static get
FarFallOff
float OVR.AudioManager.FarFallOff static get
Instance
AudioManager OVR.AudioManager.Instance static get
NearFallOff
float OVR.AudioManager.NearFallOff static get
ReservedGroup
AudioMixerGroup OVR.AudioManager.ReservedGroup static get
SoundEnabled
bool OVR.AudioManager.SoundEnabled static get
Referenced by OVR.AudioManager.PlaySound(), OVR.AudioManager.PlaySound(), OVR.AudioManager.PlaySoundAt(), and OVR.AudioManager.PlaySoundAt().
VoipGroup
AudioMixerGroup OVR.AudioManager.VoipGroup static get
The documentation for this class was generated from the following files:
C:/Users/Lykos/Desktop/Projects/Capstone/VRGames/Assets/ThirdParty/Oculus/AudioManager/Scripts/Audio/AudioManager.cs
C:/Users/Lykos/Desktop/Projects/Capstone/VRGames/Assets/ThirdParty/Oculus/AudioManager/Scripts/Audio/AudioManager_Sound.cs