VRGames: Helper.SmartGCHandle Class Reference
Helper.SmartGCHandle Class Reference
Public Member Functions
SmartGCHandle (GCHandle handle)
System.IntPtr AddrOfPinnedObject ()
virtual void Dispose ()
Static Public Member Functions
static implicit operator GCHandle (SmartGCHandle other)
Protected Member Functions
virtual void Dispose (bool disposing)
Constructor & Destructor Documentation
SmartGCHandle()
Helper.SmartGCHandle.SmartGCHandle (GCHandle handle)
Member Function Documentation
AddrOfPinnedObject()
System.IntPtr Helper.SmartGCHandle.AddrOfPinnedObject ()
Referenced by Windows.Kinect.ColorFrame.CopyConvertedFrameDataToArray(), Windows.Kinect.AudioBeamSubFrame.CopyFrameDataToArray(), Windows.Kinect.BodyIndexFrame.CopyFrameDataToArray(), Windows.Kinect.DepthFrame.CopyFrameDataToArray(), Windows.Kinect.InfraredFrame.CopyFrameDataToArray(), Windows.Kinect.LongExposureInfraredFrame.CopyFrameDataToArray(), Windows.Kinect.ColorFrame.CopyRawFrameDataToArray(), Windows.Kinect.CoordinateMapper.GetDepthFrameToCameraSpaceTable(), Windows.Kinect.CoordinateMapper.MapCameraPointsToColorSpace(), Windows.Kinect.CoordinateMapper.MapCameraPointsToDepthSpace(), Windows.Kinect.CoordinateMapper.MapColorFrameToCameraSpace(), Windows.Kinect.CoordinateMapper.MapColorFrameToDepthSpace(), Windows.Kinect.CoordinateMapper.MapDepthFrameToCameraSpace(), Windows.Kinect.CoordinateMapper.MapDepthFrameToColorSpace(), Windows.Kinect.CoordinateMapper.MapDepthPointsToCameraSpace(), and Windows.Kinect.CoordinateMapper.MapDepthPointsToColorSpace().
Dispose() [1/2]
virtual void Helper.SmartGCHandle.Dispose () virtual
Referenced by Helper.SmartGCHandle.Dispose().
Dispose() [2/2]
virtual void Helper.SmartGCHandle.Dispose (bool disposing) protected virtual
operator GCHandle()
static implicit Helper.SmartGCHandle.operator GCHandle (SmartGCHandle other) static
The documentation for this class was generated from the following file:
C:/Users/Lykos/Desktop/Projects/Capstone/VRGames/Assets/ThirdParty/Standard Assets/SmartGCHandle.cs