VRGames: UnityEditor.XR.Management.Metadata.XRPackageMetadataStore Class Reference
UnityEditor.XR.Management.Metadata.XRPackageMetadataStore Class Reference
Provide access to the metadata store. Currently only usable as a way to assign and remove loaders to/from an XRManagerSettings instance.
Classes
struct LoaderBuildTargetQueryResult
Static Public Member Functions
static IReadOnlyList< IXRPackage > GetAllPackageMetadata ()
Return a read only list of all package metadata information currently known.
static IReadOnlyList< IXRPackage > GetAllPackageMetadataForBuildTarget (BuildTargetGroup buildTargetGroup)
Return a read only list of all package metadata information currently known that has loaders that support the given build.
static IXRPackageMetadata GetMetadataForPackage (string packageId)
Given a package id, return the metadata for that package.
static bool IsLoaderAssigned (string loaderTypeName, BuildTargetGroup buildTargetGroup)
Given a loader type and a build target group will return whether or not that loader is currently assigned to be active for that build target.
static bool AssignLoader (XRManagerSettings settings, string loaderTypeName, BuildTargetGroup buildTargetGroup)
Assigns a loader of type loaderTypeName to the settings instance. Will instantiate an instance if one can't be found in the users project folder before assigning it.
static bool RemoveLoader (XRManagerSettings settings, string loaderTypeName, BuildTargetGroup buildTargetGroup)
Remove a previously assigned loader from settings. If the loader type is unknown or an instance of the loader can't be found in the project folder no action is taken.
Detailed Description
Provide access to the metadata store. Currently only usable as a way to assign and remove loaders to/from an XRManagerSettings instance.
Member Function Documentation
AssignLoader()
static bool UnityEditor.XR.Management.Metadata.XRPackageMetadataStore.AssignLoader (XRManagerSettings settings, string loaderTypeName, BuildTargetGroup buildTargetGroup) static
Assigns a loader of type loaderTypeName to the settings instance. Will instantiate an instance if one can't be found in the users project folder before assigning it.
Parameters
settings An instance of XRManagerSettings to add the loader to.
loaderTypeName The full type name for the loader instance to assign to settings.
buildTargetGroup The build target group being assigned to.
Returns
True if assignment succeeds, false if not.
Referenced by UnityEditor.XR.Management.Tests.PackageManagementTests.TestLoaderAssignment().
GetAllPackageMetadata()
static IReadOnlyList< IXRPackage > UnityEditor.XR.Management.Metadata.XRPackageMetadataStore.GetAllPackageMetadata () static
Return a read only list of all package metadata information currently known.
Returns
Read only list of IXRPackage.
Referenced by UnityEditor.XR.Management.Tests.MetadataTests.CanGetAllPackageMetadata().
GetAllPackageMetadataForBuildTarget()
static IReadOnlyList< IXRPackage > UnityEditor.XR.Management.Metadata.XRPackageMetadataStore.GetAllPackageMetadataForBuildTarget (BuildTargetGroup buildTargetGroup) static
Return a read only list of all package metadata information currently known that has loaders that support the given build.
Returns
Read only list of IXRPackage.
Referenced by UnityEditor.XR.Management.Tests.MetadataTests.FilteringAllMetadataByBuildTargetGroup(), and UnityEditor.XR.Management.Tests.MetadataTests.FilteringAllMetadataByBuildTargetGroupReturnsSameSet().
GetMetadataForPackage()
static IXRPackageMetadata UnityEditor.XR.Management.Metadata.XRPackageMetadataStore.GetMetadataForPackage (string packageId) static
Given a package id, return the metadata for that package.
Parameters
packageId The package id to check for.
Returns
An instance of IXRPackageMetadata if the package has metadata or null.
Referenced by UnityEditor.XR.Management.Tests.MetadataTests.AccessSettings().
IsLoaderAssigned()
static bool UnityEditor.XR.Management.Metadata.XRPackageMetadataStore.IsLoaderAssigned (string loaderTypeName, BuildTargetGroup buildTargetGroup) static
Given a loader type and a build target group will return whether or not that loader is currently assigned to be active for that build target.
Parameters
loaderTypeName Loader type to check.
buildTargetGroup Build target group to check for assignment in.
Returns
RemoveLoader()
static bool UnityEditor.XR.Management.Metadata.XRPackageMetadataStore.RemoveLoader (XRManagerSettings settings, string loaderTypeName, BuildTargetGroup buildTargetGroup) static
Remove a previously assigned loader from settings. If the loader type is unknown or an instance of the loader can't be found in the project folder no action is taken.
Removal will not delete the instance from the project folder.
Parameters
settings An instance of XRManagerSettings to add the loader to.
loaderTypeName The full type name for the loader instance to remove from settings.
buildTargetGroup The build target group being removed from.
Returns
True if removal succeeds, false if not.
Referenced by UnityEditor.XR.Management.Tests.PackageManagementTests.TestLoaderRemoval().
The documentation for this class was generated from the following file:
C:/Users/Lykos/Desktop/Projects/Capstone/VRGames/Library/PackageCache/com.unity.xr.management@4.2.1/Editor/Metadata/XRPackageMetadataStore.cs