VRGames: UnityEngine.XR.Interaction.Toolkit.XRGrabInteractable Class Reference
UnityEngine.XR.Interaction.Toolkit.XRGrabInteractable Class Reference
Interactable component that allows basic "grab" functionality. Can attach to a selecting Interactor and follow it around while obeying physics (and inherit velocity when released).
Public Types
enum AttachPointCompatibilityMode { Default , Legacy }
Controls the method used when calculating the target position of the object.
Public Types inherited from UnityEngine.XR.Interaction.Toolkit.XRBaseInteractable
enum MovementType { VelocityTracking , Kinematic , Instantaneous }
Options for how to process and perform movement of an Interactable.
Public Member Functions
override void ProcessInteractable (XRInteractionUpdateOrder.UpdatePhase updatePhase)
The XRInteractionManager calls this method to update the Interactable.
Parameters
updatePhase The update phase this is called during.
Please see the XRInteractionManager and XRInteractionUpdateOrder.UpdatePhase documentation for more details on update order.
override Transform GetAttachTransform (IXRInteractor interactor)
Gets the Transform that serves as the attachment point for a given Interactor.
Parameters
interactor The specific Interactor as context to get the attachment point for.
Returns
Returns the attachment point Transform.
See also
IXRInteractor.GetAttachTransform
This should typically return the Transform of a child GameObject or the transform itself.
Public Member Functions inherited from UnityEngine.XR.Interaction.Toolkit.XRBaseInteractable
Pose GetAttachPoseOnSelect (IXRSelectInteractor interactor)
Gets the world position and rotation of the Attach Transform captured during the moment of selection.
Parameters
interactor The specific Interactor as context to get the attachment point for.
Returns
Returns the world pose of the attachment point during the moment of selection, and otherwise the identity Pose if it was not selected by it during the current selection stack.
See also
GetLocalAttachPoseOnSelect, IXRInteractable.GetAttachTransform, IXRSelectInteractor.GetAttachPoseOnSelect
Pose GetLocalAttachPoseOnSelect (IXRSelectInteractor interactor)
Gets the local position and rotation of the Attach Transform captured during the moment of selection.
Parameters
interactor The specific Interactor as context to get the attachment point for.
Returns
Returns the local pose of the attachment point during the moment of selection, and otherwise the identity Pose if it was not selected by it during the current selection stack.
See also
GetAttachPoseOnSelect, IXRInteractable.GetAttachTransform, IXRSelectInteractor.GetLocalAttachPoseOnSelect
virtual float GetDistanceSqrToInteractor (IXRInteractor interactor)
Calculates squared distance to an Interactor (based on colliders).
Parameters
interactor Interactor to calculate distance against.
Returns
Returns the minimum squared distance between the Interactor and this Interactable's colliders.
virtual bool IsHoverableBy (IXRHoverInteractor interactor)
Determines if a given Interactor can hover over this Interactable.
virtual bool IsSelectableBy (IXRSelectInteractor interactor)
Determines if a given Interactor can select this Interactable.
virtual void AttachCustomReticle (IXRInteractor interactor)
Attaches the custom reticle to the Interactor.
virtual void RemoveCustomReticle (IXRInteractor interactor)
Removes the custom reticle from the Interactor.
virtual float GetDistanceSqrToInteractor (XRBaseInteractor interactor)
(Deprecated) Calculates distance squared to interactor (based on colliders).
virtual void AttachCustomReticle (XRBaseInteractor interactor)
(Deprecated) Attaches the custom reticle to the Interactor.
virtual void RemoveCustomReticle (XRBaseInteractor interactor)
(Deprecated) Removes the custom reticle from the Interactor.
virtual bool IsHoverableBy (XRBaseInteractor interactor)
(Deprecated) Determines if this interactable can be hovered by a given interactor.
virtual bool IsSelectableBy (XRBaseInteractor interactor)
(Deprecated) Determines if a given Interactor can select this Interactable.
Protected Member Functions
override void Awake ()
See MonoBehaviour.
override void OnSelectEntering (SelectEnterEventArgs args)
The XRInteractionManager calls this method right before the Interactor first initiates selection of an Interactable in a first pass.
Parameters
args Event data containing the Interactor that is initiating the selection.
args is only valid during this method call, do not hold a reference to it.
override void OnSelectExiting (SelectExitEventArgs args)
The XRInteractionManager calls this method right before the Interactor ends selection of an Interactable in a first pass.
Parameters
args Event data containing the Interactor that is ending the selection.
args is only valid during this method call, do not hold a reference to it.
virtual void Grab ()
Updates the state of the object due to being grabbed. Automatically called when entering the Select state.
virtual void Drop ()
Updates the state of the object due to being dropped and schedule to finish the detach during the end of the frame. Automatically called when exiting the Select state.
virtual void Detach ()
Updates the state of the object to finish the detach after being dropped. Automatically called during the end of the frame after being dropped.
virtual void SetupRigidbodyGrab (Rigidbody rigidbody)
Setup the Rigidbody on this object due to being grabbed. Automatically called when entering the Select state.
virtual void SetupRigidbodyDrop (Rigidbody rigidbody)
Setup the Rigidbody on this object due to being dropped. Automatically called when exiting the Select state.
Protected Member Functions inherited from UnityEngine.XR.Interaction.Toolkit.XRBaseInteractable
virtual void Reset ()
See MonoBehaviour.
virtual void OnEnable ()
See MonoBehaviour.
virtual void OnDisable ()
See MonoBehaviour.
virtual void OnDestroy ()
See MonoBehaviour.
void CaptureAttachPose (IXRSelectInteractor interactor)
Capture the current Attach Transform pose. This method is automatically called by Unity to capture the pose during the moment of selection.
virtual void OnRegistered (InteractableRegisteredEventArgs args)
The XRInteractionManager calls this method when this Interactable is registered with it.
virtual void OnUnregistered (InteractableUnregisteredEventArgs args)
The XRInteractionManager calls this method when this Interactable is unregistered from it.
virtual void OnHoverEntering (HoverEnterEventArgs args)
The XRInteractionManager calls this method right before the Interactor first initiates hovering over an Interactable in a first pass.
virtual void OnHoverEntered (HoverEnterEventArgs args)
The XRInteractionManager calls this method when the Interactor first initiates hovering over an Interactable in a second pass.
virtual void OnHoverExiting (HoverExitEventArgs args)
The XRInteractionManager calls this method right before the Interactor ends hovering over an Interactable in a first pass.
virtual void OnHoverExited (HoverExitEventArgs args)
The XRInteractionManager calls this method when the Interactor ends hovering over an Interactable in a second pass.
virtual void OnSelectEntered (SelectEnterEventArgs args)
The XRInteractionManager calls this method when the Interactor first initiates selection of an Interactable in a second pass.
virtual void OnSelectExited (SelectExitEventArgs args)
The XRInteractionManager calls this method when the Interactor ends selection of an Interactable in a second pass.
virtual void OnActivated (ActivateEventArgs args)
XRBaseControllerInteractor calls this method when the Interactor begins an activation event on this Interactable.
virtual void OnDeactivated (DeactivateEventArgs args)
XRBaseControllerInteractor calls this method when the Interactor ends an activation event on this Interactable.
virtual void OnHoverEntering (XRBaseInteractor interactor)
(Deprecated) The XRInteractionManager calls this method right before the Interactor first initiates hovering over an Interactable in a first pass.
virtual void OnHoverEntered (XRBaseInteractor interactor)
(Deprecated) The XRInteractionManager calls this method when the Interactor first initiates hovering over an Interactable in a second pass.
virtual void OnHoverExiting (XRBaseInteractor interactor)
(Deprecated) The XRInteractionManager calls this method right before the Interactor ends hovering over an Interactable in a first pass.
virtual void OnHoverExited (XRBaseInteractor interactor)
(Deprecated) The XRInteractionManager calls this method when the Interactor ends hovering over an Interactable in a second pass.
virtual void OnSelectEntering (XRBaseInteractor interactor)
(Deprecated) The XRInteractionManager calls this method right before the Interactor first initiates selection of an Interactable in a first pass.
virtual void OnSelectEntered (XRBaseInteractor interactor)
(Deprecated) The XRInteractionManager calls this method when the Interactor first initiates selection of an Interactable in a second pass.
virtual void OnSelectExiting (XRBaseInteractor interactor)
(Deprecated) The XRInteractionManager calls this method right before the Interactor ends selection of an Interactable in a first pass.
virtual void OnSelectExited (XRBaseInteractor interactor)
(Deprecated) The XRInteractionManager calls this method when the Interactor ends selection of an Interactable in a second pass.
virtual void OnSelectCanceling (XRBaseInteractor interactor)
(Deprecated) The XRInteractionManager calls this method while this Interactable is selected by an Interactor right before either is unregistered (such as from being disabled or destroyed) in a first pass.
virtual void OnSelectCanceled (XRBaseInteractor interactor)
(Deprecated) The XRInteractionManager calls this method while an Interactor selects this Interactable when either is unregistered (such as from being disabled or destroyed) in a second pass.
virtual void OnActivate (XRBaseInteractor interactor)
(Deprecated) The XRBaseControllerInteractor calls this method when the Interactor begins an activation event on this Interactable.
virtual void OnDeactivate (XRBaseInteractor interactor)
(Deprecated) The XRBaseControllerInteractor calls this method when the Interactor ends an activation event on this Interactable.
Properties
Transform attachTransform [get, set]
The attachment point Unity uses on this Interactable (will use this object's position if none set).
float attachEaseInTime [get, set]
Time in seconds Unity eases in the attach when selected (a value of 0 indicates no easing).
MovementType movementType [get, set]
Specifies how this object moves when selected, either through setting the velocity of the Rigidbody, moving the kinematic Rigidbody during Fixed Update, or by directly updating the Transform each frame.
float velocityDamping [get, set]
Scale factor of how much to dampen the existing velocity when tracking the position of the Interactor. The smaller the value, the longer it takes for the velocity to decay.
float velocityScale [get, set]
Scale factor Unity applies to the tracked velocity while updating the Rigidbody when tracking the position of the Interactor.
float angularVelocityDamping [get, set]
Scale factor of how much Unity dampens the existing angular velocity when tracking the rotation of the Interactor. The smaller the value, the longer it takes for the angular velocity to decay.
float angularVelocityScale [get, set]
Scale factor Unity applies to the tracked angular velocity while updating the Rigidbody when tracking the rotation of the Interactor.
bool trackPosition [get, set]
Whether this object should follow the position of the Interactor when selected.
bool smoothPosition [get, set]
Whether Unity applies smoothing while following the position of the Interactor when selected.
float smoothPositionAmount [get, set]
Scale factor for how much smoothing is applied while following the position of the Interactor when selected. The larger the value, the closer this object will remain to the position of the Interactor.
float tightenPosition [get, set]
Reduces the maximum follow position difference when using smoothing.
bool trackRotation [get, set]
Whether this object should follow the rotation of the Interactor when selected.
bool smoothRotation [get, set]
Apply smoothing while following the rotation of the Interactor when selected.
float smoothRotationAmount [get, set]
Scale factor for how much smoothing is applied while following the rotation of the Interactor when selected. The larger the value, the closer this object will remain to the rotation of the Interactor.
float tightenRotation [get, set]
Reduces the maximum follow rotation difference when using smoothing.
bool throwOnDetach [get, set]
Whether this object inherits the velocity of the Interactor when released.
float throwSmoothingDuration [get, set]
Time period to average thrown velocity over.
AnimationCurve throwSmoothingCurve [get, set]
The curve to use to weight thrown velocity smoothing (most recent frames to the right).
float throwVelocityScale [get, set]
Scale factor Unity applies to this object's velocity inherited from the Interactor when released.
float throwAngularVelocityScale [get, set]
Scale factor Unity applies to this object's angular velocity inherited from the Interactor when released.
bool forceGravityOnDetach [get, set]
Forces this object to have gravity when released (will still use pre-grab value if this is false).
bool retainTransformParent [get, set]
Whether Unity sets the parent of this object back to its original parent this object was a child of after this object is dropped.
AttachPointCompatibilityMode attachPointCompatibilityMode [get, set]
Controls the method used when calculating the target position of the object. Use AttachPointCompatibilityMode.Default for consistent attach points between all XRBaseInteractable.MovementType values. Marked for deprecation, this property will be removed in a future version.
bool gravityOnDetach [get, set]
(Deprecated) Forces this object to have gravity when released (will still use pre-grab value if this is false).
Properties inherited from UnityEngine.XR.Interaction.Toolkit.XRBaseInteractable
XRInteractionManager interactionManager [get, set]
The XRInteractionManager that this Interactable will communicate with (will find one if null).
List< Collider > colliders [get]
(Read Only) Colliders to use for interaction with this Interactable (if empty, will use any child Colliders).
InteractionLayerMask interactionLayers [get, set]
Allows interaction with Interactors whose Interaction Layer Mask overlaps with any Layer in this Interaction Layer Mask.
InteractableSelectMode selectMode [get, set]
Indicates the selection policy of an Interactable.
See also
InteractableSelectMode
GameObject customReticle [get, set]
The reticle that appears at the end of the line when valid.
HoverEnterEvent firstHoverEntered [get, set]
The event that is called only when the first Interactor begins hovering over this Interactable as the sole hovering Interactor. Subsequent Interactors that begin hovering over this Interactable will not cause this event to be invoked as long as any others are still hovering.The HoverEnterEventArgs passed to each listener is only valid while the event is invoked, do not hold a reference to it.
HoverExitEvent lastHoverExited [get, set]
The event that is called only when the last remaining hovering Interactor ends hovering over this Interactable.The HoverExitEventArgs passed to each listener is only valid while the event is invoked, do not hold a reference to it.
HoverEnterEvent hoverEntered [get, set]
The event that is called when an Interactor begins hovering over this Interactable.The HoverEnterEventArgs passed to each listener is only valid while the event is invoked, do not hold a reference to it.
HoverExitEvent hoverExited [get, set]
The event that is called when an Interactor ends hovering over this Interactable.The HoverExitEventArgs passed to each listener is only valid while the event is invoked, do not hold a reference to it.
SelectEnterEvent firstSelectEntered [get, set]
The event that is called only when the first Interactor begins selecting this Interactable as the sole selecting Interactor. Subsequent Interactors that begin selecting this Interactable will not cause this event to be invoked as long as any others are still selecting.The SelectEnterEventArgs passed to each listener is only valid while the event is invoked, do not hold a reference to it.
SelectExitEvent lastSelectExited [get, set]
The event that is called only when the last remaining selecting Interactor ends selecting this Interactable.The SelectExitEventArgs passed to each listener is only valid while the event is invoked, do not hold a reference to it.
SelectEnterEvent selectEntered [get, set]
The event that is called when an Interactor begins selecting this Interactable.The SelectEnterEventArgs passed to each listener is only valid while the event is invoked, do not hold a reference to it.
SelectExitEvent selectExited [get, set]
The event that is called when an Interactor ends selecting this Interactable.The SelectExitEventArgs passed to each listener is only valid while the event is invoked, do not hold a reference to it.
ActivateEvent activated [get, set]
The event that is called when the selecting Interactor activates this Interactable.Not to be confused with activating or deactivating a GameObject with GameObject.SetActive. This is a generic event when an Interactor wants to activate an Interactable, such as from a trigger pull on a controller.
The ActivateEventArgs passed to each listener is only valid while the event is invoked, do not hold a reference to it.
DeactivateEvent deactivated [get, set]
The event that is called when an Interactor deactivates this Interactable.Not to be confused with activating or deactivating a GameObject with GameObject.SetActive. This is a generic event when an Interactor wants to deactivate an Interactable, such as from a trigger release on a controller.
The DeactivateEventArgs passed to each listener is only valid while the event is invoked, do not hold a reference to it.
List< IXRHoverInteractor > interactorsHovering = new List<IXRHoverInteractor>() [get]
(Read Only) The list of Interactors that are hovering on this Interactable (may by empty).You should treat this as a read only view of the list and should not modify it. Unity exposes this as a List<T> rather than an IReadOnlyList<T> to avoid GC Allocations when enumerating the list.
bool isHovered [get]
(Read Only) Indicates whether an Interactor currently hovers over this Interactable.In other words, returns whether interactorsHovering contains any interactors.
interactorsHovering.Count > 0
List< IXRSelectInteractor > interactorsSelecting = new List<IXRSelectInteractor>() [get]
(Read Only) The list of Interactors currently selecting this Interactable (may by empty).You should treat this as a read only view of the list and should not modify it. It is exposed as a List<T> rather than an IReadOnlyList<T> to avoid GC Allocations when enumerating the list.
IXRSelectInteractor firstInteractorSelecting [get]
(Read Only) The first interactor that selected this interactable since not being selected by any interactor. The interactor may not currently be selecting this interactable, which would be the case when it released while multiple interactors were selecting this interactable.
See also
IXRSelectInteractor.firstInteractableSelected
bool isSelected [get]
(Read Only) Indicates whether this interactable is currently being selected by any interactor.In other words, returns whether interactorsSelecting contains any interactors.
interactorsSelecting.Count > 0
LayerMask interactionLayerMask [get, set]
(Deprecated) Allows interaction with Interactors whose Interaction Layer Mask overlaps with any Layer in this Interaction Layer Mask.
XRInteractableEvent onFirstHoverEntered [get, set]
(Deprecated) Gets or sets the event that Unity calls only when the first Interactor begins hovering over this Interactable as the sole hovering Interactor. Subsequent Interactors that begin hovering over this Interactable will not cause this event to be invoked as long as any others are still hovering.
XRInteractableEvent onLastHoverExited [get, set]
(Deprecated) Gets or sets the event that Unity calls only when the last remaining hovering Interactor ends hovering over this Interactable.
XRInteractableEvent onHoverEntered [get, set]
(Deprecated) Gets or sets the event that Unity calls when an Interactor begins hovering over this Interactable.
XRInteractableEvent onHoverExited [get, set]
(Deprecated) Gets or sets the event that Unity calls when an Interactor ends hovering over this Interactable.
XRInteractableEvent onSelectEntered [get, set]
(Deprecated) Gets or sets the event that Unity calls when an Interactor begins selecting this Interactable.
XRInteractableEvent onSelectExited [get, set]
(Deprecated) Gets or sets the event that Unity calls when an Interactor ends selecting this Interactable.
XRInteractableEvent onSelectCanceled [get, set]
(Deprecated) Gets or sets the event that Unity calls when this Interactable is selected by an Interactor and either is unregistered (such as from being disabled or destroyed).
XRInteractableEvent onActivate [get, set]
(Deprecated) Gets or sets the event that Unity calls when an Interactor activates this selected Interactable.
XRInteractableEvent onDeactivate [get, set]
(Deprecated) Gets or sets the event that Unity calls when an Interactor deactivates this selected Interactable.
XRInteractableEvent onFirstHoverEnter [get]
(Deprecated) Unity calls this only when the first Interactor begins hovering over this Interactable.
XRInteractableEvent onHoverEnter [get]
(Deprecated) Unity calls this every time an Interactor begins hovering over this Interactable.
XRInteractableEvent onHoverExit [get]
(Deprecated) Unity calls this every time an Interactor ends hovering over this Interactable.
XRInteractableEvent onLastHoverExit [get]
(Deprecated) Unity calls this only when the last Interactor ends hovering over this Interactable.
XRInteractableEvent onSelectEnter [get]
(Deprecated) Unity calls this when an Interactor begins selecting this Interactable.
XRInteractableEvent onSelectExit [get]
(Deprecated) Unity calls this when an Interactor ends selecting this Interactable.
XRInteractableEvent onSelectCancel [get]
(Deprecated) Unity calls this when the Interactor selecting this Interactable is disabled or destroyed.
List< XRBaseInteractor > hoveringInteractors = new List<XRBaseInteractor>() [get]
(Deprecated) (Read Only) The list of interactors that are hovering on this interactable.
XRBaseInteractor selectingInteractor [get, protected set]
(Deprecated) The Interactor selecting this Interactable (may be null).
Properties inherited from UnityEngine.XR.Interaction.Toolkit.IXRActivateInteractable
Properties inherited from UnityEngine.XR.Interaction.Toolkit.IXRInteractable
Transform transform [get]
(Read Only) The Transform associated with the Interactable.
Properties inherited from UnityEngine.XR.Interaction.Toolkit.IXRHoverInteractable
Properties inherited from UnityEngine.XR.Interaction.Toolkit.IXRSelectInteractable
Additional Inherited Members
Events inherited from UnityEngine.XR.Interaction.Toolkit.XRBaseInteractable
Action< InteractableRegisteredEventArgs > registered
Action< InteractableUnregisteredEventArgs > unregistered
Events inherited from UnityEngine.XR.Interaction.Toolkit.IXRInteractable
Action< InteractableRegisteredEventArgs > registered
Unity calls the methods in this invocation list when this Interactable is registered with an XRInteractionManager.
Action< InteractableUnregisteredEventArgs > unregistered
Unity calls the methods in this invocation list when this Interactable is unregistered from an XRInteractionManager.
Detailed Description
Interactable component that allows basic "grab" functionality. Can attach to a selecting Interactor and follow it around while obeying physics (and inherit velocity when released).
Member Enumeration Documentation
AttachPointCompatibilityMode
enum UnityEngine.XR.Interaction.Toolkit.XRGrabInteractable.AttachPointCompatibilityMode
Controls the method used when calculating the target position of the object.
See also
attachPointCompatibilityMode
Enumerator
Default
Use the default, correct method for calculating the target position of the object.
Legacy
Use an additional offset from the center of mass when calculating the target position of the object. Also incorporate the scale of the Interactor's Attach Transform. Marked for deprecation. This is the backwards compatible support mode for projects that accounted for the unintended difference when using XR Interaction Toolkit prior to version 1.0.0-pre.4. To have the effective attach position be the same between all XRBaseInteractable.MovementType values, use Default.
Member Function Documentation
Awake()
override void UnityEngine.XR.Interaction.Toolkit.XRGrabInteractable.Awake () protected virtual
See MonoBehaviour.
Reimplemented from UnityEngine.XR.Interaction.Toolkit.XRBaseInteractable.
Detach()
virtual void UnityEngine.XR.Interaction.Toolkit.XRGrabInteractable.Detach () protected virtual
Updates the state of the object to finish the detach after being dropped. Automatically called during the end of the frame after being dropped.
This method updates the velocity of the Rigidbody if configured to do so.
See also
Drop
Referenced by UnityEngine.XR.Interaction.Toolkit.XRGrabInteractable.ProcessInteractable().
Drop()
virtual void UnityEngine.XR.Interaction.Toolkit.XRGrabInteractable.Drop () protected virtual
Updates the state of the object due to being dropped and schedule to finish the detach during the end of the frame. Automatically called when exiting the Select state.
See also
Detach, Grab
Referenced by UnityEngine.XR.Interaction.Toolkit.XRGrabInteractable.OnSelectExiting().
GetAttachTransform()
override Transform UnityEngine.XR.Interaction.Toolkit.XRGrabInteractable.GetAttachTransform (IXRInteractor interactor) virtual
Gets the Transform that serves as the attachment point for a given Interactor.
Parameters
interactor The specific Interactor as context to get the attachment point for.
Returns
Returns the attachment point Transform.
See also
IXRInteractor.GetAttachTransform
This should typically return the Transform of a child GameObject or the transform itself.
Reimplemented from UnityEngine.XR.Interaction.Toolkit.XRBaseInteractable.
Grab()
virtual void UnityEngine.XR.Interaction.Toolkit.XRGrabInteractable.Grab () protected virtual
Updates the state of the object due to being grabbed. Automatically called when entering the Select state.
See also
Drop
Referenced by UnityEngine.XR.Interaction.Toolkit.XRGrabInteractable.OnSelectEntering().
OnSelectEntering()
override void UnityEngine.XR.Interaction.Toolkit.XRGrabInteractable.OnSelectEntering (SelectEnterEventArgs args) protected virtual
The XRInteractionManager calls this method right before the Interactor first initiates selection of an Interactable in a first pass.
Parameters
args Event data containing the Interactor that is initiating the selection.
args is only valid during this method call, do not hold a reference to it.
Reimplemented from UnityEngine.XR.Interaction.Toolkit.XRBaseInteractable.
OnSelectExiting()
override void UnityEngine.XR.Interaction.Toolkit.XRGrabInteractable.OnSelectExiting (SelectExitEventArgs args) protected virtual
The XRInteractionManager calls this method right before the Interactor ends selection of an Interactable in a first pass.
Parameters
args Event data containing the Interactor that is ending the selection.
args is only valid during this method call, do not hold a reference to it.
Reimplemented from UnityEngine.XR.Interaction.Toolkit.XRBaseInteractable.
ProcessInteractable()
override void UnityEngine.XR.Interaction.Toolkit.XRGrabInteractable.ProcessInteractable (XRInteractionUpdateOrder::UpdatePhase updatePhase) virtual
The XRInteractionManager calls this method to update the Interactable.
Parameters
updatePhase The update phase this is called during.
Please see the XRInteractionManager and XRInteractionUpdateOrder.UpdatePhase documentation for more details on update order.
Reimplemented from UnityEngine.XR.Interaction.Toolkit.XRBaseInteractable.
SetupRigidbodyDrop()
virtual void UnityEngine.XR.Interaction.Toolkit.XRGrabInteractable.SetupRigidbodyDrop (Rigidbody rigidbody) protected virtual
Setup the Rigidbody on this object due to being dropped. Automatically called when exiting the Select state.
Parameters
rigidbody The Rigidbody on this object.
See also
SetupRigidbodyGrab
Referenced by UnityEngine.XR.Interaction.Toolkit.XRGrabInteractable.Drop().
SetupRigidbodyGrab()
virtual void UnityEngine.XR.Interaction.Toolkit.XRGrabInteractable.SetupRigidbodyGrab (Rigidbody rigidbody) protected virtual
Setup the Rigidbody on this object due to being grabbed. Automatically called when entering the Select state.
Parameters
rigidbody The Rigidbody on this object.
See also
SetupRigidbodyDrop
Referenced by UnityEngine.XR.Interaction.Toolkit.XRGrabInteractable.Grab().
Property Documentation
angularVelocityDamping
float UnityEngine.XR.Interaction.Toolkit.XRGrabInteractable.angularVelocityDamping get set
Scale factor of how much Unity dampens the existing angular velocity when tracking the rotation of the Interactor. The smaller the value, the longer it takes for the angular velocity to decay.
Only applies when in XRBaseInteractable.MovementType.VelocityTracking mode.
See also
XRBaseInteractable.MovementType.VelocityTracking, trackRotation
angularVelocityScale
float UnityEngine.XR.Interaction.Toolkit.XRGrabInteractable.angularVelocityScale get set
Scale factor Unity applies to the tracked angular velocity while updating the Rigidbody when tracking the rotation of the Interactor.
Only applies when in XRBaseInteractable.MovementType.VelocityTracking mode.
See also
XRBaseInteractable.MovementType.VelocityTracking, trackRotation
attachEaseInTime
float UnityEngine.XR.Interaction.Toolkit.XRGrabInteractable.attachEaseInTime get set
Time in seconds Unity eases in the attach when selected (a value of 0 indicates no easing).
attachPointCompatibilityMode
AttachPointCompatibilityMode UnityEngine.XR.Interaction.Toolkit.XRGrabInteractable.attachPointCompatibilityMode get set
Controls the method used when calculating the target position of the object. Use AttachPointCompatibilityMode.Default for consistent attach points between all XRBaseInteractable.MovementType values. Marked for deprecation, this property will be removed in a future version.
This is a backwards compatibility option in order to keep the old, incorrect method of calculating the attach point. Projects that already accounted for the difference can use the Legacy option to maintain the same attach positioning from older versions without needing to modify the Attach Transform position.
See also
AttachPointCompatibilityMode
attachTransform
Transform UnityEngine.XR.Interaction.Toolkit.XRGrabInteractable.attachTransform get set
The attachment point Unity uses on this Interactable (will use this object's position if none set).
forceGravityOnDetach
bool UnityEngine.XR.Interaction.Toolkit.XRGrabInteractable.forceGravityOnDetach get set
Forces this object to have gravity when released (will still use pre-grab value if this is false).
gravityOnDetach
bool UnityEngine.XR.Interaction.Toolkit.XRGrabInteractable.gravityOnDetach get set
(Deprecated) Forces this object to have gravity when released (will still use pre-grab value if this is false).
gravityOnDetach has been deprecated. Use forceGravityOnDetach instead.
movementType
MovementType UnityEngine.XR.Interaction.Toolkit.XRGrabInteractable.movementType get set
Specifies how this object moves when selected, either through setting the velocity of the Rigidbody, moving the kinematic Rigidbody during Fixed Update, or by directly updating the Transform each frame.
See also
XRBaseInteractable.MovementType
retainTransformParent
bool UnityEngine.XR.Interaction.Toolkit.XRGrabInteractable.retainTransformParent get set
Whether Unity sets the parent of this object back to its original parent this object was a child of after this object is dropped.
smoothPosition
bool UnityEngine.XR.Interaction.Toolkit.XRGrabInteractable.smoothPosition get set
Whether Unity applies smoothing while following the position of the Interactor when selected.
See also
smoothPositionAmount, tightenPosition
smoothPositionAmount
float UnityEngine.XR.Interaction.Toolkit.XRGrabInteractable.smoothPositionAmount get set
Scale factor for how much smoothing is applied while following the position of the Interactor when selected. The larger the value, the closer this object will remain to the position of the Interactor.
See also
smoothPosition, tightenPosition
smoothRotation
bool UnityEngine.XR.Interaction.Toolkit.XRGrabInteractable.smoothRotation get set
Apply smoothing while following the rotation of the Interactor when selected.
See also
smoothRotationAmount, tightenRotation
smoothRotationAmount
float UnityEngine.XR.Interaction.Toolkit.XRGrabInteractable.smoothRotationAmount get set
Scale factor for how much smoothing is applied while following the rotation of the Interactor when selected. The larger the value, the closer this object will remain to the rotation of the Interactor.
See also
smoothRotation, tightenRotation
throwAngularVelocityScale
float UnityEngine.XR.Interaction.Toolkit.XRGrabInteractable.throwAngularVelocityScale get set
Scale factor Unity applies to this object's angular velocity inherited from the Interactor when released.
See also
throwOnDetach
throwOnDetach
bool UnityEngine.XR.Interaction.Toolkit.XRGrabInteractable.throwOnDetach get set
Whether this object inherits the velocity of the Interactor when released.
throwSmoothingCurve
AnimationCurve UnityEngine.XR.Interaction.Toolkit.XRGrabInteractable.throwSmoothingCurve get set
The curve to use to weight thrown velocity smoothing (most recent frames to the right).
See also
throwOnDetach
throwSmoothingDuration
float UnityEngine.XR.Interaction.Toolkit.XRGrabInteractable.throwSmoothingDuration get set
Time period to average thrown velocity over.
See also
throwOnDetach
throwVelocityScale
float UnityEngine.XR.Interaction.Toolkit.XRGrabInteractable.throwVelocityScale get set
Scale factor Unity applies to this object's velocity inherited from the Interactor when released.
See also
throwOnDetach
tightenPosition
float UnityEngine.XR.Interaction.Toolkit.XRGrabInteractable.tightenPosition get set
Reduces the maximum follow position difference when using smoothing.
Fractional amount of how close the smoothed position should remain to the position of the Interactor when using smoothing. The value ranges from 0 meaning no bias in the smoothed follow distance, to 1 meaning effectively no smoothing at all.
See also
smoothPosition, smoothPositionAmount
tightenRotation
float UnityEngine.XR.Interaction.Toolkit.XRGrabInteractable.tightenRotation get set
Reduces the maximum follow rotation difference when using smoothing.
Fractional amount of how close the smoothed rotation should remain to the rotation of the Interactor when using smoothing. The value ranges from 0 meaning no bias in the smoothed follow rotation, to 1 meaning effectively no smoothing at all.
See also
smoothRotation, smoothRotationAmount
trackPosition
bool UnityEngine.XR.Interaction.Toolkit.XRGrabInteractable.trackPosition get set
Whether this object should follow the position of the Interactor when selected.
See also
trackRotation
trackRotation
bool UnityEngine.XR.Interaction.Toolkit.XRGrabInteractable.trackRotation get set
Whether this object should follow the rotation of the Interactor when selected.
See also
trackPosition
velocityDamping
float UnityEngine.XR.Interaction.Toolkit.XRGrabInteractable.velocityDamping get set
Scale factor of how much to dampen the existing velocity when tracking the position of the Interactor. The smaller the value, the longer it takes for the velocity to decay.
Only applies when in XRBaseInteractable.MovementType.VelocityTracking mode.
See also
XRBaseInteractable.MovementType.VelocityTracking, trackPosition
velocityScale
float UnityEngine.XR.Interaction.Toolkit.XRGrabInteractable.velocityScale get set
Scale factor Unity applies to the tracked velocity while updating the Rigidbody when tracking the position of the Interactor.
Only applies when in XRBaseInteractable.MovementType.VelocityTracking mode.
See also
XRBaseInteractable.MovementType.VelocityTracking, trackPosition
The documentation for this class was generated from the following files:
C:/Users/Lykos/Desktop/Projects/Capstone/VRGames/Library/PackageCache/com.unity.xr.interaction.toolkit@2.0.2/Runtime/Interaction/Interactables/XRGrabInteractable.cs
C:/Users/Lykos/Desktop/Projects/Capstone/VRGames/Library/PackageCache/com.unity.xr.interaction.toolkit@2.0.2/Runtime/Interaction/Interactables/XRGrabInteractable.deprecated.cs