VRGames: Facebook.WitAi.WitResponseReference Class Reference
Facebook.WitAi.WitResponseReference Class Reference
Public Member Functions
virtual string GetStringValue (WitResponseNode response)
virtual int GetIntValue (WitResponseNode response)
virtual float GetFloatValue (WitResponseNode response)
Public Attributes
WitResponseReference child
string path
Member Function Documentation
GetFloatValue()
virtual float Facebook.WitAi.WitResponseReference.GetFloatValue (WitResponseNode response) virtual
Reimplemented in Facebook.WitAi.ArrayNodeReference, and Facebook.WitAi.ObjectNodeReference.
Referenced by Facebook.WitAi.Data.WitFloatValue.GetFloatValue(), Facebook.WitAi.WitResponseReference.GetFloatValue(), Facebook.WitAi.ArrayNodeReference.GetFloatValue(), and Facebook.WitAi.ObjectNodeReference.GetFloatValue().
GetIntValue()
virtual int Facebook.WitAi.WitResponseReference.GetIntValue (WitResponseNode response) virtual
Reimplemented in Facebook.WitAi.ArrayNodeReference, and Facebook.WitAi.ObjectNodeReference.
Referenced by Facebook.WitAi.Data.WitIntValue.GetIntValue(), Facebook.WitAi.WitResponseReference.GetIntValue(), Facebook.WitAi.ArrayNodeReference.GetIntValue(), and Facebook.WitAi.ObjectNodeReference.GetIntValue().
GetStringValue()
virtual string Facebook.WitAi.WitResponseReference.GetStringValue (WitResponseNode response) virtual
Reimplemented in Facebook.WitAi.ArrayNodeReference, and Facebook.WitAi.ObjectNodeReference.
Referenced by Facebook.WitAi.Data.WitStringValue.GetStringValue(), Facebook.WitAi.WitResponseReference.GetStringValue(), Facebook.WitAi.ArrayNodeReference.GetStringValue(), Facebook.WitAi.ObjectNodeReference.GetStringValue(), Facebook.WitAi.CallbackHandlers.WitResponseMatcher.OnHandleResponse(), and Facebook.WitAi.Data.WitValue.ToString().
Member Data Documentation
child
WitResponseReference Facebook.WitAi.WitResponseReference.child
Referenced by Facebook.WitAi.WitResponseReference.GetFloatValue(), Facebook.WitAi.ArrayNodeReference.GetFloatValue(), Facebook.WitAi.ObjectNodeReference.GetFloatValue(), Facebook.WitAi.WitResponseReference.GetIntValue(), Facebook.WitAi.ArrayNodeReference.GetIntValue(), Facebook.WitAi.ObjectNodeReference.GetIntValue(), Facebook.WitAi.WitResponseReference.GetStringValue(), Facebook.WitAi.ArrayNodeReference.GetStringValue(), and Facebook.WitAi.ObjectNodeReference.GetStringValue().
path
string Facebook.WitAi.WitResponseReference.path
The documentation for this class was generated from the following file:
C:/Users/Lykos/Desktop/Projects/Capstone/VRGames/Assets/ThirdParty/Oculus/Voice/Lib/Wit.ai/Scripts/Runtime/WitResultUtilities.cs