VRGames: UnityEngine.UI.MaskUtilities Class Reference
UnityEngine.UI.MaskUtilities Class Reference
Mask related utility class. This class provides masking-specific utility functions.
Static Public Member Functions
static void Notify2DMaskStateChanged (Component mask)
Notify all IClippables under the given component that they need to recalculate clipping.
static void NotifyStencilStateChanged (Component mask)
Notify all IMaskable under the given component that they need to recalculate masking.
static Transform FindRootSortOverrideCanvas (Transform start)
Find a root Canvas.
static int GetStencilDepth (Transform transform, Transform stopAfter)
Find the stencil depth for a given element.
static bool IsDescendantOrSelf (Transform father, Transform child)
Helper function to determine if the child is a descendant of father or is father.
static RectMask2D GetRectMaskForClippable (IClippable clippable)
Find the correct RectMask2D for a given IClippable.
static void GetRectMasksForClip (RectMask2D clipper, List< RectMask2D > masks)
Search for all RectMask2D that apply to the given RectMask2D (includes self).
Detailed Description
Mask related utility class. This class provides masking-specific utility functions.
Member Function Documentation
FindRootSortOverrideCanvas()
static Transform UnityEngine.UI.MaskUtilities.FindRootSortOverrideCanvas (Transform start) static
Find a root Canvas.
Parameters
start Transform to start the search at going up the hierarchy.
Returns
Finds either the most root canvas, or the first canvas that overrides sorting.
Referenced by TMPro.TextMeshProUGUI.GetModifiedMaterial(), TMPro.TMP_SubMeshUI.GetModifiedMaterial(), UnityEngine.UI.Mask.GetModifiedMaterial(), and UnityEngine.UI.MaskableGraphic.GetModifiedMaterial().
GetRectMaskForClippable()
static RectMask2D UnityEngine.UI.MaskUtilities.GetRectMaskForClippable (IClippable clippable) static
Find the correct RectMask2D for a given IClippable.
Parameters
clippable Clippable to search from.
Returns
The Correct RectMask2D
GetRectMasksForClip()
static void UnityEngine.UI.MaskUtilities.GetRectMasksForClip (RectMask2D clipper, List< RectMask2D > masks) static
Search for all RectMask2D that apply to the given RectMask2D (includes self).
Parameters
clipper Starting clipping object.
masks The list of Rect masks
Referenced by UnityEngine.UI.RectMask2D.PerformClipping().
GetStencilDepth()
static int UnityEngine.UI.MaskUtilities.GetStencilDepth (Transform transform, Transform stopAfter) static
Find the stencil depth for a given element.
Parameters
transform The starting transform to search.
stopAfter Where the search of parents should stop
Returns
What the proper stencil buffer index should be.
Referenced by TMPro.TextMeshProUGUI.GetModifiedMaterial(), TMPro.TMP_SubMeshUI.GetModifiedMaterial(), UnityEngine.UI.Mask.GetModifiedMaterial(), UnityEngine.UI.MaskableGraphic.GetModifiedMaterial(), and Graphics.MaskTests.GetModifiedMaterialReturnsDesiredMaterialWithMultipleMasks().
IsDescendantOrSelf()
static bool UnityEngine.UI.MaskUtilities.IsDescendantOrSelf (Transform father, Transform child) static
Helper function to determine if the child is a descendant of father or is father.
Parameters
father The transform to compare against.
child The starting transform to search up the hierarchy.
Returns
Is child equal to father or is a descendant.
Referenced by UnityEngine.UI.MaskUtilities.GetRectMaskForClippable(), and UnityEngine.UI.MaskUtilities.GetRectMasksForClip().
Notify2DMaskStateChanged()
static void UnityEngine.UI.MaskUtilities.Notify2DMaskStateChanged (Component mask) static
Notify all IClippables under the given component that they need to recalculate clipping.
Parameters
mask The object thats changed for whose children should be notified.
Referenced by UnityEngine.UI.RectMask2D.OnDisable(), and UnityEngine.UI.RectMask2D.OnEnable().
NotifyStencilStateChanged()
static void UnityEngine.UI.MaskUtilities.NotifyStencilStateChanged (Component mask) static
Notify all IMaskable under the given component that they need to recalculate masking.
Parameters
mask The object thats changed for whose children should be notified.
Referenced by UnityEngine.UI.Mask.OnDisable(), UnityEngine.UI.MaskableGraphic.OnDisable(), UnityEngine.UI.Mask.OnEnable(), and UnityEngine.UI.MaskableGraphic.OnEnable().
The documentation for this class was generated from the following file:
C:/Users/Lykos/Desktop/Projects/Capstone/VRGames/Library/PackageCache/com.unity.ugui@1.0.0/Runtime/UI/Core/MaskUtilities.cs