VRGames: UnityEditor.Timeline.ClipItem Class Reference
UnityEditor.Timeline.ClipItem Class Reference
Public Member Functions
ClipItem (TimelineClip clip)
bool IsCompatibleWithTrack (TrackAsset track)
void PushUndo (string operation)
void SetStart (double time, bool affectTimeScale)
void SetEnd (double time, bool affectTimeScale)
void Delete ()
void TrimStart (double time)
void TrimEnd (double time)
ITimelineItem CloneTo (TrackAsset parent, double time)
override string ToString ()
bool Equals (ClipItem otherClip)
override int GetHashCode ()
bool Equals (ITimelineItem other)
override bool Equals (object obj)
Properties
TimelineClip clip [get]
TrackAsset parentTrack [get, set]
double start [get, set]
double end [get]
double duration [get]
TimelineItemGUI gui [get]
bool supportsBlending [get]
bool hasLeftBlend [get]
bool hasRightBlend [get]
double leftBlendDuration [get]
double rightBlendDuration [get]
Properties inherited from UnityEditor.Timeline.IBlendable
Properties inherited from UnityEditor.Timeline.ITimelineItem
Constructor & Destructor Documentation
ClipItem()
UnityEditor.Timeline.ClipItem.ClipItem (TimelineClip clip)
Referenced by UnityEditor.Timeline.ClipItem.CloneTo(), and UnityEditor.Timeline.ClipItem.Equals().
Member Function Documentation
CloneTo()
ITimelineItem UnityEditor.Timeline.ClipItem.CloneTo (TrackAsset parent, double time)
Implements UnityEditor.Timeline.ITimelineItem.
Delete()
void UnityEditor.Timeline.ClipItem.Delete ()
Implements UnityEditor.Timeline.ITimelineItem.
Equals() [1/3]
bool UnityEditor.Timeline.ClipItem.Equals (ClipItem otherClip)
Referenced by UnityEditor.Timeline.ClipItem.Equals(), UnityEditor.Timeline.ClipItem.Equals(), and UnityEditor.Timeline.ClipItem.Equals().
Equals() [2/3]
bool UnityEditor.Timeline.ClipItem.Equals (ITimelineItem other)
Equals() [3/3]
override bool UnityEditor.Timeline.ClipItem.Equals (object obj)
GetHashCode()
override int UnityEditor.Timeline.ClipItem.GetHashCode ()
IsCompatibleWithTrack()
bool UnityEditor.Timeline.ClipItem.IsCompatibleWithTrack (TrackAsset track)
Implements UnityEditor.Timeline.ITimelineItem.
PushUndo()
void UnityEditor.Timeline.ClipItem.PushUndo (string operation)
Implements UnityEditor.Timeline.ITimelineItem.
SetEnd()
void UnityEditor.Timeline.ClipItem.SetEnd (double time, bool affectTimeScale)
Implements UnityEditor.Timeline.ITrimmable.
SetStart()
void UnityEditor.Timeline.ClipItem.SetStart (double time, bool affectTimeScale)
Implements UnityEditor.Timeline.ITrimmable.
ToString()
override string UnityEditor.Timeline.ClipItem.ToString ()
TrimEnd()
void UnityEditor.Timeline.ClipItem.TrimEnd (double time)
Implements UnityEditor.Timeline.ITrimmable.
TrimStart()
void UnityEditor.Timeline.ClipItem.TrimStart (double time)
Implements UnityEditor.Timeline.ITrimmable.
Property Documentation
clip
TimelineClip UnityEditor.Timeline.ClipItem.clip get
Referenced by UnityEditor.Timeline.ClipItem.ClipItem().
duration
double UnityEditor.Timeline.ClipItem.duration get
Implements UnityEditor.Timeline.ITimelineItem.
end
double UnityEditor.Timeline.ClipItem.end get
Implements UnityEditor.Timeline.ITimelineItem.
gui
TimelineItemGUI UnityEditor.Timeline.ClipItem.gui get
Implements UnityEditor.Timeline.ITimelineItem.
hasLeftBlend
bool UnityEditor.Timeline.ClipItem.hasLeftBlend get
Implements UnityEditor.Timeline.IBlendable.
hasRightBlend
bool UnityEditor.Timeline.ClipItem.hasRightBlend get
Implements UnityEditor.Timeline.IBlendable.
leftBlendDuration
double UnityEditor.Timeline.ClipItem.leftBlendDuration get
Implements UnityEditor.Timeline.IBlendable.
parentTrack
TrackAsset UnityEditor.Timeline.ClipItem.parentTrack get set
Implements UnityEditor.Timeline.ITimelineItem.
rightBlendDuration
double UnityEditor.Timeline.ClipItem.rightBlendDuration get
Implements UnityEditor.Timeline.IBlendable.
start
double UnityEditor.Timeline.ClipItem.start get set
Implements UnityEditor.Timeline.ITimelineItem.
supportsBlending
bool UnityEditor.Timeline.ClipItem.supportsBlending get
Implements UnityEditor.Timeline.IBlendable.
The documentation for this class was generated from the following file:
C:/Users/Lykos/Desktop/Projects/Capstone/VRGames/Library/PackageCache/com.unity.timeline@1.6.4/Editor/Items/ClipItem.cs