VRGames: UnityEngine.ProBuilder.Poly2Tri.TriangulationContext Class Reference
UnityEngine.ProBuilder.Poly2Tri.TriangulationContext Class Reference abstract
Public Member Functions
void Done ()
virtual void PrepareTriangulation (Triangulatable t)
TriangulationConstraint NewConstraint (TriangulationPoint a, TriangulationPoint b)
void Update (string message)
virtual void Clear ()
Public Attributes
readonly List< DelaunayTriangle > Triangles = new List<DelaunayTriangle>()
readonly List< TriangulationPoint > Points = new List<TriangulationPoint>()
Properties
TriangulationDebugContext DebugContext [get, protected set]
TriangulationMode TriangulationMode [get, protected set]
Triangulatable Triangulatable [get]
int StepCount [get]
TriangulationAlgorithm Algorithm [get]
virtual bool IsDebugEnabled [get, protected set]
DTSweepDebugContext DTDebugContext [get]
Member Function Documentation
Clear()
virtual void UnityEngine.ProBuilder.Poly2Tri.TriangulationContext.Clear () virtual
Reimplemented in UnityEngine.ProBuilder.Poly2Tri.DTSweepContext.
Done()
void UnityEngine.ProBuilder.Poly2Tri.TriangulationContext.Done ()
NewConstraint()
TriangulationConstraint UnityEngine.ProBuilder.Poly2Tri.TriangulationContext.NewConstraint (TriangulationPoint a, TriangulationPoint b) abstract
Referenced by UnityEngine.ProBuilder.Poly2Tri.Polygon.Prepare(), and UnityEngine.ProBuilder.Poly2Tri.ConstrainedPointSet.Prepare().
PrepareTriangulation()
virtual void UnityEngine.ProBuilder.Poly2Tri.TriangulationContext.PrepareTriangulation (Triangulatable t) virtual
Reimplemented in UnityEngine.ProBuilder.Poly2Tri.DTSweepContext.
Update()
void UnityEngine.ProBuilder.Poly2Tri.TriangulationContext.Update (string message)
Member Data Documentation
Points
readonly List<TriangulationPoint> UnityEngine.ProBuilder.Poly2Tri.TriangulationContext.Points = new List<TriangulationPoint>()
Referenced by UnityEngine.ProBuilder.Poly2Tri.TriangulationContext.Clear(), UnityEngine.ProBuilder.Poly2Tri.DTSweepContext.CreateAdvancingFront(), UnityEngine.ProBuilder.Poly2Tri.Polygon.Prepare(), UnityEngine.ProBuilder.Poly2Tri.PointSet.Prepare(), and UnityEngine.ProBuilder.Poly2Tri.DTSweepContext.PrepareTriangulation().
Triangles
readonly List<DelaunayTriangle> UnityEngine.ProBuilder.Poly2Tri.TriangulationContext.Triangles = new List<DelaunayTriangle>()
Referenced by UnityEngine.ProBuilder.Poly2Tri.DTSweepContext.Clear(), UnityEngine.ProBuilder.Poly2Tri.DTSweepContext.CreateAdvancingFront(), UnityEngine.ProBuilder.Poly2Tri.DTSweepContext.FinalizeTriangulation(), and UnityEngine.ProBuilder.Poly2Tri.DTSweepContext.RemoveFromList().
Property Documentation
Algorithm
TriangulationAlgorithm UnityEngine.ProBuilder.Poly2Tri.TriangulationContext.Algorithm get abstract
DebugContext
TriangulationDebugContext UnityEngine.ProBuilder.Poly2Tri.TriangulationContext.DebugContext get protected set
Referenced by UnityEngine.ProBuilder.Poly2Tri.TriangulationContext.Clear().
DTDebugContext
DTSweepDebugContext UnityEngine.ProBuilder.Poly2Tri.TriangulationContext.DTDebugContext get
IsDebugEnabled
virtual bool UnityEngine.ProBuilder.Poly2Tri.TriangulationContext.IsDebugEnabled get protected set
StepCount
int UnityEngine.ProBuilder.Poly2Tri.TriangulationContext.StepCount get
Referenced by UnityEngine.ProBuilder.Poly2Tri.TriangulationContext.Clear(), and UnityEngine.ProBuilder.Poly2Tri.TriangulationContext.Done().
Triangulatable
Triangulatable UnityEngine.ProBuilder.Poly2Tri.TriangulationContext.Triangulatable get
TriangulationMode
TriangulationMode UnityEngine.ProBuilder.Poly2Tri.TriangulationContext.TriangulationMode get protected set
The documentation for this class was generated from the following file:
C:/Users/Lykos/Desktop/Projects/Capstone/VRGames/Library/PackageCache/com.unity.probuilder@5.0.6/External/Poly2Tri/Triangulation/TriangulationContext.cs