VRGames: OVR.AudioManagerInspector Class Reference
OVR.AudioManagerInspector Class Reference
Classes
class CustomDragData
class ItemRect
Public Member Functions
override void OnInspectorGUI ()
Static Public Member Functions
static bool DrawHeader (string text)
static bool DrawHeader (string text, string key)
static bool DrawHeader (string text, bool forceOn)
static bool DrawHeader (string text, string key, bool forceOn)
static void BeginContents ()
static void EndContents ()
Member Function Documentation
BeginContents()
static void OVR.AudioManagerInspector.BeginContents () static
DrawHeader() [1/4]
static bool OVR.AudioManagerInspector.DrawHeader (string text) static
Referenced by OVR.AudioManagerInspector.DrawHeader().
DrawHeader() [2/4]
static bool OVR.AudioManagerInspector.DrawHeader (string text, bool forceOn) static
Referenced by OVR.AudioManagerInspector.DrawHeader().
DrawHeader() [3/4]
static bool OVR.AudioManagerInspector.DrawHeader (string text, string key) static
Referenced by OVR.AudioManagerInspector.DrawHeader().
DrawHeader() [4/4]
static bool OVR.AudioManagerInspector.DrawHeader (string text, string key, bool forceOn) static
EndContents()
static void OVR.AudioManagerInspector.EndContents () static
OnInspectorGUI()
override void OVR.AudioManagerInspector.OnInspectorGUI ()
The documentation for this class was generated from the following file:
C:/Users/Lykos/Desktop/Projects/Capstone/VRGames/Assets/ThirdParty/Oculus/AudioManager/Scripts/Audio/Editor/AudioManagerInspector.cs