VRGames: PlanesGame.PlaneGameplayManager Class Reference
PlanesGame.PlaneGameplayManager Class Reference
Manages the gameplay logic for plane interactions, including spawning and lifecycle management.
Public Member Functions
void ToggleTimedTargets ()
Toggles the timed target feature and resets the game state, respawning planes.
void OnFirstPointReached ()
Callback for when the first point is reached in the game.
void OnPlaneGrabbed (GameObject plane)
Handles the event when a plane is grabbed, updating the scoreboard message.
void OnPlaneReleased (GameObject plane)
Handles the event when a plane is released, spawning new planes as needed.
void KillPlane (GameObject plane)
Removes a plane from the game, destroying its GameObject and removing it from the active list.
void RespawnPlane (GameObject plane)
Respawns a plane by first removing the old one and then spawning a new one.
override void reset ()
Clears all planes from the game, removing their GameObjects and clearing the list.
Public Member Functions inherited from GameplayManager
GameSettingsSO GetGameSettings ()
virtual void onWinConditionPointsReached ()
void setDifficulty (int newDif)
int getDifficulty ()
void Update ()
virtual void RefreshSettings ()
void PauseGame ()
void ResumeGame ()
void IncreaseDifficulty ()
void DecreaseDifficulty ()
Public Attributes
GameObject planePrefab
GameObject newTable
float secondsTilDespawn
Public Attributes inherited from GameplayManager
int difficulty = 1
int winConditionPoints = 50
int maxTime
GameSettingsSO gameSettings
int playerLives
Static Public Attributes
static int exactDegrees
static bool useExactAngle = false
static bool rightSpawnOnly = false
static bool leftSpawnOnly = false
Additional Inherited Members
Static Public Member Functions inherited from GameplayManager
static GameplayManager getManager ()
Protected Member Functions inherited from GameplayManager
void Start ()
Properties inherited from GameplayManager
static GameplayManager Instance [get]
Detailed Description
Manages the gameplay logic for plane interactions, including spawning and lifecycle management.
This class is responsible for spawning planes, handling their grab and release events, and managing their lifecycle within the game. It also provides mechanisms to clear planes and reset the gameplay state.
Member Function Documentation
KillPlane()
void PlanesGame.PlaneGameplayManager.KillPlane (GameObject plane)
Removes a plane from the game, destroying its GameObject and removing it from the active list.
Parameters
plane The plane GameObject to be removed.
Referenced by PlanesGame.PlaneGameplayManager.RespawnPlane().
OnFirstPointReached()
void PlanesGame.PlaneGameplayManager.OnFirstPointReached ()
Callback for when the first point is reached in the game.
OnPlaneGrabbed()
void PlanesGame.PlaneGameplayManager.OnPlaneGrabbed (GameObject plane)
Handles the event when a plane is grabbed, updating the scoreboard message.
Parameters
plane The plane GameObject that was grabbed.
References PointsManager.updateScoreboardMessage(), and GameplayManager.winConditionPoints.
Referenced by PlanesGame.PaperPlane.onGrab().
OnPlaneReleased()
void PlanesGame.PlaneGameplayManager.OnPlaneReleased (GameObject plane)
Handles the event when a plane is released, spawning new planes as needed.
Parameters
plane The plane GameObject that was released.
Referenced by PlanesGame.PaperPlane.onRelease().
reset()
override void PlanesGame.PlaneGameplayManager.reset () virtual
Clears all planes from the game, removing their GameObjects and clearing the list.
Reimplemented from GameplayManager.
Referenced by PlanesGame.PlaneGameplayManager.ToggleTimedTargets().
RespawnPlane()
void PlanesGame.PlaneGameplayManager.RespawnPlane (GameObject plane)
Respawns a plane by first removing the old one and then spawning a new one.
Parameters
plane The plane GameObject to be respawned.
References PlanesGame.PlaneGameplayManager.KillPlane().
ToggleTimedTargets()
void PlanesGame.PlaneGameplayManager.ToggleTimedTargets ()
Toggles the timed target feature and resets the game state, respawning planes.
References PlanesGame.PlaneGameplayManager.reset().
Member Data Documentation
exactDegrees
int PlanesGame.PlaneGameplayManager.exactDegrees static
leftSpawnOnly
bool PlanesGame.PlaneGameplayManager.leftSpawnOnly = false static
newTable
GameObject PlanesGame.PlaneGameplayManager.newTable
planePrefab
GameObject PlanesGame.PlaneGameplayManager.planePrefab
rightSpawnOnly
bool PlanesGame.PlaneGameplayManager.rightSpawnOnly = false static
secondsTilDespawn
float PlanesGame.PlaneGameplayManager.secondsTilDespawn
useExactAngle
bool PlanesGame.PlaneGameplayManager.useExactAngle = false static
The documentation for this class was generated from the following file:
C:/Users/Lykos/Desktop/Projects/Capstone/VRGames/Assets/Shared/Scripts/Managers/PlaneGameplayManager.cs