VRGames: PlaneGameplayManager Class Reference
PlaneGameplayManager Class Reference
Manages the gameplay logic for plane interactions, including spawning and lifecycle management.
Public Member Functions
void ToggleTimedTargets ()
Toggles the timed target feature and resets the game state, respawning planes.
void OnFirstPointReached ()
Callback for when the first point is reached in the game.
void OnPlaneGrabbed (GameObject plane)
Handles the event when a plane is grabbed, updating the scoreboard message.
void OnPlaneReleased (GameObject plane)
Handles the event when a plane is released, spawning new planes as needed.
void KillPlane (GameObject plane)
Removes a plane from the game, destroying its GameObject and removing it from the active list.
void RespawnPlane (GameObject plane)
Respawns a plane by first removing the old one and then spawning a new one.
override void reset ()
Clears all planes from the game, removing their GameObjects and clearing the list.
Public Member Functions inherited from GameplayManager
GameSettingsSO GetGameSettings ()
virtual void onWinConditionPointsReached ()
void setDifficulty (int newDif)
int getDifficulty ()
void Update ()
virtual void RefreshSettings ()
void PauseGame ()
void ResumeGame ()
void IncreaseDifficulty ()
void DecreaseDifficulty ()
Public Attributes
GameObject planePrefab
GameObject newTable
float secondsTilDespawn
Public Attributes inherited from GameplayManager
int difficulty = 1
int winConditionPoints = 50
int maxTime
GameSettingsSO gameSettings
int playerLives
Additional Inherited Members
Static Public Member Functions inherited from GameplayManager
static GameplayManager getManager ()
Protected Member Functions inherited from GameplayManager
void Start ()
Properties inherited from GameplayManager
static GameplayManager Instance [get]
Detailed Description
Manages the gameplay logic for plane interactions, including spawning and lifecycle management.
This class is responsible for spawning planes, handling their grab and release events, and managing their lifecycle within the game. It also provides mechanisms to clear planes and reset the gameplay state.
Member Function Documentation
KillPlane()
void PlaneGameplayManager.KillPlane (GameObject plane)
Removes a plane from the game, destroying its GameObject and removing it from the active list.
Parameters
plane The plane GameObject to be removed.
Referenced by RespawnPlane().
OnFirstPointReached()
void PlaneGameplayManager.OnFirstPointReached ()
Callback for when the first point is reached in the game.
OnPlaneGrabbed()
void PlaneGameplayManager.OnPlaneGrabbed (GameObject plane)
Handles the event when a plane is grabbed, updating the scoreboard message.
Parameters
plane The plane GameObject that was grabbed.
Referenced by PaperPlane.onGrab().
OnPlaneReleased()
void PlaneGameplayManager.OnPlaneReleased (GameObject plane)
Handles the event when a plane is released, spawning new planes as needed.
Parameters
plane The plane GameObject that was released.
Referenced by PaperPlane.onRelease().
reset()
override void PlaneGameplayManager.reset () virtual
Clears all planes from the game, removing their GameObjects and clearing the list.
Reimplemented from GameplayManager.
Referenced by ToggleTimedTargets().
RespawnPlane()
void PlaneGameplayManager.RespawnPlane (GameObject plane)
Respawns a plane by first removing the old one and then spawning a new one.
Parameters
plane The plane GameObject to be respawned.
ToggleTimedTargets()
void PlaneGameplayManager.ToggleTimedTargets ()
Toggles the timed target feature and resets the game state, respawning planes.
Member Data Documentation
newTable
GameObject PlaneGameplayManager.newTable
planePrefab
GameObject PlaneGameplayManager.planePrefab
secondsTilDespawn
float PlaneGameplayManager.secondsTilDespawn
The documentation for this class was generated from the following file:
C:/Users/Lykos/Desktop/Projects/Capstone/VRGames/Assets/Shared/Scripts/Managers/PlaneGameplayManager.cs