VRGames: Oculus.Interaction.Input.FromOVRControllerDataSource Class Reference
Oculus.Interaction.Input.FromOVRControllerDataSource Class Reference
Public Member Functions
void InjectAllFromOVRControllerDataSource (UpdateModeFlags updateMode, IDataSource updateAfter, Handedness handedness, ITrackingToWorldTransformer trackingToWorldTransformer, IDataSource< HmdDataAsset > hmdData)
void InjectHandedness (Handedness handedness)
void InjectTrackingToWorldTransformer (ITrackingToWorldTransformer trackingToWorldTransformer)
void InjectHmdData (IDataSource< HmdDataAsset > hmdData)
Public Member Functions inherited from Oculus.Interaction.Input.DataSource< ControllerDataAsset >
TData GetData ()
virtual void MarkInputDataRequiresUpdate ()
Marks the DataAsset stored as outdated, which means it will be re-processed JIT during the next call to GetData.
void InjectAllDataSource (UpdateModeFlags updateMode, IDataSource updateAfter)
void InjectUpdateMode (UpdateModeFlags updateMode)
void InjectUpdateAfter (IDataSource updateAfter)
Protected Member Functions
void Awake ()
override void Start ()
override void UpdateData ()
Protected Member Functions inherited from Oculus.Interaction.Input.DataSource< ControllerDataAsset >
virtual void OnEnable ()
virtual void OnDisable ()
virtual void Update ()
virtual void FixedUpdate ()
virtual void LateUpdate ()
void ResetUpdateAfter (IDataSource updateAfter, UpdateModeFlags updateMode)
bool RequiresUpdate ()
void UpdateData ()
Properties
IOVRCameraRigRef CameraRigRef [get]
override ControllerDataAsset DataAsset [get]
Properties inherited from Oculus.Interaction.Input.DataSource< ControllerDataAsset >
bool Started [get]
UpdateModeFlags UpdateMode [get]
bool UpdateModeAfterPrevious [get]
virtual int CurrentDataVersion [get]
TData DataAsset [get]
Returns the current DataAsset, without performing any updates.
Additional Inherited Members
Protected Attributes inherited from Oculus.Interaction.Input.DataSource< ControllerDataAsset >
bool _started
Events inherited from Oculus.Interaction.Input.DataSource< ControllerDataAsset >
Action InputDataAvailable
Member Function Documentation
Awake()
void Oculus.Interaction.Input.FromOVRControllerDataSource.Awake () protected
InjectAllFromOVRControllerDataSource()
void Oculus.Interaction.Input.FromOVRControllerDataSource.InjectAllFromOVRControllerDataSource (UpdateModeFlags updateMode, IDataSource updateAfter, Handedness handedness, ITrackingToWorldTransformer trackingToWorldTransformer, IDataSource< HmdDataAsset > hmdData)
InjectHandedness()
void Oculus.Interaction.Input.FromOVRControllerDataSource.InjectHandedness (Handedness handedness)
Referenced by Oculus.Interaction.Input.FromOVRControllerDataSource.InjectAllFromOVRControllerDataSource().
InjectHmdData()
void Oculus.Interaction.Input.FromOVRControllerDataSource.InjectHmdData (IDataSource< HmdDataAsset > hmdData)
Referenced by Oculus.Interaction.Input.FromOVRControllerDataSource.InjectAllFromOVRControllerDataSource().
InjectTrackingToWorldTransformer()
void Oculus.Interaction.Input.FromOVRControllerDataSource.InjectTrackingToWorldTransformer (ITrackingToWorldTransformer trackingToWorldTransformer)
Referenced by Oculus.Interaction.Input.FromOVRControllerDataSource.InjectAllFromOVRControllerDataSource().
Start()
override void Oculus.Interaction.Input.FromOVRControllerDataSource.Start () protected virtual
Reimplemented from Oculus.Interaction.Input.DataSource< ControllerDataAsset >.
UpdateData()
override void Oculus.Interaction.Input.FromOVRControllerDataSource.UpdateData () protected
Property Documentation
CameraRigRef
IOVRCameraRigRef Oculus.Interaction.Input.FromOVRControllerDataSource.CameraRigRef get
Referenced by Oculus.Interaction.Input.FromOVRControllerDataSource.Awake(), Oculus.Interaction.Input.FromOVRControllerDataSource.Start(), and Oculus.Interaction.Input.FromOVRControllerDataSource.UpdateData().
DataAsset
override ControllerDataAsset Oculus.Interaction.Input.FromOVRControllerDataSource.DataAsset get protected
The documentation for this class was generated from the following file:
C:/Users/Lykos/Desktop/Projects/Capstone/VRGames/Assets/ThirdParty/Oculus/Interaction/Runtime/Scripts/Input/OVRIntegration/FromOVRControllerDataSource.cs