VRGames: Facebook.WitAi.Data.WitDataCreation Class Reference
Facebook.WitAi.Data.WitDataCreation Class Reference
Static Public Member Functions
static WitConfiguration FindDefaultWitConfig ()
static void AddWitToScene ()
static WitStringValue CreateStringValue (string path)
static WitFloatValue CreateFloatValue (string path)
static WitIntValue CreateIntValue (string path)
Member Function Documentation
AddWitToScene()
static void Facebook.WitAi.Data.WitDataCreation.AddWitToScene () static
CreateFloatValue()
static WitFloatValue Facebook.WitAi.Data.WitDataCreation.CreateFloatValue (string path) static
Referenced by Oculus.Voice.Data.VoiceSDKDataCreation.WitFloatValue().
CreateIntValue()
static WitIntValue Facebook.WitAi.Data.WitDataCreation.CreateIntValue (string path) static
Referenced by Oculus.Voice.Data.VoiceSDKDataCreation.WitIntValue().
CreateStringValue()
static WitStringValue Facebook.WitAi.Data.WitDataCreation.CreateStringValue (string path) static
Referenced by Oculus.Voice.Data.VoiceSDKDataCreation.WitStringValue().
FindDefaultWitConfig()
static WitConfiguration Facebook.WitAi.Data.WitDataCreation.FindDefaultWitConfig () static
Referenced by Oculus.Voice.Data.VoiceSDKDataCreation.AddVoiceCommandServiceToScene(), and Facebook.WitAi.Data.WitDataCreation.AddWitToScene().
The documentation for this class was generated from the following file:
C:/Users/Lykos/Desktop/Projects/Capstone/VRGames/Assets/ThirdParty/Oculus/Voice/Lib/Wit.ai/Scripts/Editor/Data/WitDataCreation.cs