VRGames: UnityEngine.XR.Interaction.Toolkit.XRInteractionManager Class Reference
UnityEngine.XR.Interaction.Toolkit.XRInteractionManager Class Reference
The Interaction Manager acts as an intermediary between Interactors and Interactables. It is possible to have multiple Interaction Managers, each with their own valid set of Interactors and Interactables. Upon being enabled, both Interactors and Interactables register themselves with a valid Interaction Manager (if a specific one has not already been assigned in the inspector). The loaded scenes must have at least one Interaction Manager for Interactors and Interactables to be able to communicate.
Classes
class RegistrationList
Use this class to maintain a registration of Interactors or Interactables. This maintains a synchronized list that stays constant until buffered registration status changes are explicitly committed.
Public Member Functions
virtual void RegisterInteractor (IXRInteractor interactor)
Registers a new Interactor to be processed.
virtual void UnregisterInteractor (IXRInteractor interactor)
Unregister an Interactor so it is no longer processed.
virtual void RegisterInteractable (IXRInteractable interactable)
Registers a new Interactable to be processed.
virtual void UnregisterInteractable (IXRInteractable interactable)
Unregister an Interactable so it is no longer processed.
void GetRegisteredInteractors (List< IXRInteractor > results)
Returns all registered Interactors into List results .
void GetRegisteredInteractables (List< IXRInteractable > results)
Returns all registered Interactables into List results .
bool IsRegistered (IXRInteractor interactor)
Checks whether the interactor is registered with this Interaction Manager.
bool IsRegistered (IXRInteractable interactable)
Checks whether the interactable is registered with this Interaction Manager.
bool TryGetInteractableForCollider (Collider interactableCollider, out IXRInteractable interactable)
Gets the Interactable a specific Collider is attached to.
void GetValidTargets (IXRInteractor interactor, List< IXRInteractable > targets)
Retrieves the list of Interactables that the given Interactor could possibly interact with this frame. This list is sorted by priority (with highest priority first), and will only contain Interactables that are registered with this Interaction Manager.
virtual void CancelInteractorSelection (IXRSelectInteractor interactor)
Automatically called when an Interactor is unregistered to cancel the selection of the Interactor if necessary.
virtual void CancelInteractableSelection (IXRSelectInteractable interactable)
Automatically called when an Interactable is unregistered to cancel the selection of the Interactable if necessary.
virtual void CancelInteractorHover (IXRHoverInteractor interactor)
Automatically called when an Interactor is unregistered to cancel the hover state of the Interactor if necessary.
virtual void CancelInteractableHover (IXRHoverInteractable interactable)
Automatically called when an Interactable is unregistered to cancel the hover state of the Interactable if necessary.
virtual void SelectEnter (IXRSelectInteractor interactor, IXRSelectInteractable interactable)
Initiates selection of an Interactable by an Interactor. This method may first result in other interaction events such as causing the Interactable to first exit being selected.
virtual void SelectExit (IXRSelectInteractor interactor, IXRSelectInteractable interactable)
Initiates ending selection of an Interactable by an Interactor.
virtual void SelectCancel (IXRSelectInteractor interactor, IXRSelectInteractable interactable)
Initiates ending selection of an Interactable by an Interactor due to cancellation, such as from either being unregistered due to being disabled or destroyed.
virtual void HoverEnter (IXRHoverInteractor interactor, IXRHoverInteractable interactable)
Initiates hovering of an Interactable by an Interactor.
virtual void HoverExit (IXRHoverInteractor interactor, IXRHoverInteractable interactable)
Initiates ending hovering of an Interactable by an Interactor.
virtual void HoverCancel (IXRHoverInteractor interactor, IXRHoverInteractable interactable)
Initiates ending hovering of an Interactable by an Interactor due to cancellation, such as from either being unregistered due to being disabled or destroyed.
virtual void RegisterInteractor (XRBaseInteractor interactor)
virtual void UnregisterInteractor (XRBaseInteractor interactor)
virtual void RegisterInteractable (XRBaseInteractable interactable)
virtual void UnregisterInteractable (XRBaseInteractable interactable)
void GetRegisteredInteractors (List< XRBaseInteractor > results)
void GetRegisteredInteractables (List< XRBaseInteractable > results)
bool IsRegistered (XRBaseInteractor interactor)
bool IsRegistered (XRBaseInteractable interactable)
XRBaseInteractable TryGetInteractableForCollider (Collider interactableCollider)
XRBaseInteractable GetInteractableForCollider (Collider interactableCollider)
Gets the Interactable a specific collider is attached to.
void GetColliderToInteractableMap (ref Dictionary< Collider, XRBaseInteractable > map)
Gets the dictionary that has all the registered colliders and their associated Interactable.
List< XRBaseInteractable > GetValidTargets (XRBaseInteractor interactor, List< XRBaseInteractable > validTargets)
For the provided interactor , returns a list of the valid Interactables that can be hovered over or selected.
void ForceSelect (XRBaseInteractor interactor, XRBaseInteractable interactable)
Manually forces selection of an Interactable. This is different than starting manual interaction.
virtual void ClearInteractorSelection (XRBaseInteractor interactor)
Automatically called each frame during Update to clear the selection of the Interactor if necessary due to current conditions.
virtual void CancelInteractorSelection (XRBaseInteractor interactor)
Automatically called when an Interactor is unregistered to cancel the selection of the Interactor if necessary.
virtual void CancelInteractableSelection (XRBaseInteractable interactable)
Automatically called when an Interactable is unregistered to cancel the selection of the Interactable if necessary.
virtual void ClearInteractorHover (XRBaseInteractor interactor, List< XRBaseInteractable > validTargets)
Automatically called each frame during Update to clear the hover state of the Interactor if necessary due to current conditions.
virtual void CancelInteractorHover (XRBaseInteractor interactor)
Automatically called when an Interactor is unregistered to cancel the hover state of the Interactor if necessary.
virtual void CancelInteractableHover (XRBaseInteractable interactable)
Automatically called when an Interactable is unregistered to cancel the hover state of the Interactable if necessary.
virtual void SelectEnter (XRBaseInteractor interactor, XRBaseInteractable interactable)
Initiates selection of an Interactable by an Interactor. This method may first result in other interaction events such as causing the Interactable to first exit being selected.
virtual void SelectExit (XRBaseInteractor interactor, XRBaseInteractable interactable)
Initiates ending selection of an Interactable by an Interactor.
virtual void SelectCancel (XRBaseInteractor interactor, XRBaseInteractable interactable)
Initiates ending selection of an Interactable by an Interactor due to cancellation, such as from either being unregistered due to being disabled or destroyed.
virtual void HoverEnter (XRBaseInteractor interactor, XRBaseInteractable interactable)
Initiates hovering of an Interactable by an Interactor.
virtual void HoverExit (XRBaseInteractor interactor, XRBaseInteractable interactable)
Initiates ending hovering of an Interactable by an Interactor.
virtual void HoverCancel (XRBaseInteractor interactor, XRBaseInteractable interactable)
Initiates ending hovering of an Interactable by an Interactor due to cancellation, such as from either being unregistered due to being disabled or destroyed.
Protected Member Functions
virtual void OnEnable ()
See MonoBehaviour.
virtual void OnDisable ()
See MonoBehaviour.
virtual void Update ()
See MonoBehaviour.
virtual void LateUpdate ()
See MonoBehaviour.
virtual void FixedUpdate ()
See MonoBehaviour.
virtual void OnBeforeRender ()
Delegate method used to register for "Just Before Render" input updates for VR devices.
virtual void PreprocessInteractors (XRInteractionUpdateOrder.UpdatePhase updatePhase)
Automatically called each frame to preprocess all interactors registered with this manager.
virtual void ProcessInteractors (XRInteractionUpdateOrder.UpdatePhase updatePhase)
Automatically called each frame to process all interactors registered with this manager.
virtual void ProcessInteractables (XRInteractionUpdateOrder.UpdatePhase updatePhase)
Automatically called each frame to process all interactables registered with this manager.
virtual void OnRegistered (InteractorRegisteredEventArgs args)
Automatically called when an Interactor is registered with this Interaction Manager. Notifies the Interactor, passing the given args .
virtual void OnUnregistered (InteractorUnregisteredEventArgs args)
Automatically called when an Interactor is unregistered from this Interaction Manager. Notifies the Interactor, passing the given args .
virtual void OnRegistered (InteractableRegisteredEventArgs args)
Automatically called when an Interactable is registered with this Interaction Manager. Notifies the Interactable, passing the given args .
virtual void OnUnregistered (InteractableUnregisteredEventArgs args)
Automatically called when an Interactable is unregistered from this Interaction Manager. Notifies the Interactable, passing the given args .
virtual void ClearInteractorSelection (IXRSelectInteractor interactor, List< IXRInteractable > validTargets)
Automatically called each frame during Update to clear the selection of the Interactor if necessary due to current conditions.
virtual void ClearInteractorHover (IXRHoverInteractor interactor, List< IXRInteractable > validTargets)
Automatically called each frame during Update to clear the hover state of the Interactor if necessary due to current conditions.
virtual void SelectEnter (IXRSelectInteractor interactor, IXRSelectInteractable interactable, SelectEnterEventArgs args)
Initiates selection of an Interactable by an Interactor, passing the given args .
virtual void SelectExit (IXRSelectInteractor interactor, IXRSelectInteractable interactable, SelectExitEventArgs args)
Initiates ending selection of an Interactable by an Interactor, passing the given args .
virtual void HoverEnter (IXRHoverInteractor interactor, IXRHoverInteractable interactable, HoverEnterEventArgs args)
Initiates hovering of an Interactable by an Interactor, passing the given args .
virtual void HoverExit (IXRHoverInteractor interactor, IXRHoverInteractable interactable, HoverExitEventArgs args)
Initiates ending hovering of an Interactable by an Interactor, passing the given args .
virtual void InteractorSelectValidTargets (IXRSelectInteractor interactor, List< IXRInteractable > validTargets)
Automatically called each frame during Update to enter the selection state of the Interactor if necessary due to current conditions.
virtual void InteractorHoverValidTargets (IXRHoverInteractor interactor, List< IXRInteractable > validTargets)
Automatically called each frame during Update to enter the hover state of the Interactor if necessary due to current conditions.
virtual bool ResolveExistingSelect (IXRSelectInteractor interactor, IXRSelectInteractable interactable)
Automatically called when selection of an Interactable by an Interactor is initiated and the Interactable is already selected.
virtual void SelectEnter (XRBaseInteractor interactor, XRBaseInteractable interactable, SelectEnterEventArgs args)
Initiates selection of an Interactable by an Interactor, passing the given args .
virtual void SelectExit (XRBaseInteractor interactor, XRBaseInteractable interactable, SelectExitEventArgs args)
Initiates ending selection of an Interactable by an Interactor, passing the given args .
virtual void HoverEnter (XRBaseInteractor interactor, XRBaseInteractable interactable, HoverEnterEventArgs args)
Initiates hovering of an Interactable by an Interactor, passing the given args .
virtual void HoverExit (XRBaseInteractor interactor, XRBaseInteractable interactable, HoverExitEventArgs args)
Initiates ending hovering of an Interactable by an Interactor, passing the given args .
virtual void InteractorSelectValidTargets (XRBaseInteractor interactor, List< XRBaseInteractable > validTargets)
Automatically called each frame during Update to enter the selection state of the Interactor if necessary due to current conditions.
virtual void InteractorHoverValidTargets (XRBaseInteractor interactor, List< XRBaseInteractable > validTargets)
Automatically called each frame during Update to enter the hover state of the Interactor if necessary due to current conditions.
Static Protected Member Functions
static bool HasInteractionLayerOverlap (IXRInteractor interactor, IXRInteractable interactable)
Determines whether the Interactor and Interactable share at least one interaction layer between their Interaction Layer Masks.
Events
Action< InteractorRegisteredEventArgs > interactorRegistered
Calls the methods in its invocation list when an IXRInteractor is registered.
Action< InteractorUnregisteredEventArgs > interactorUnregistered
Calls the methods in its invocation list when an IXRInteractor is unregistered.
Action< InteractableRegisteredEventArgs > interactableRegistered
Calls the methods in its invocation list when an IXRInteractable is registered.
Action< InteractableUnregisteredEventArgs > interactableUnregistered
Calls the methods in its invocation list when an IXRInteractable is unregistered.
Detailed Description
The Interaction Manager acts as an intermediary between Interactors and Interactables. It is possible to have multiple Interaction Managers, each with their own valid set of Interactors and Interactables. Upon being enabled, both Interactors and Interactables register themselves with a valid Interaction Manager (if a specific one has not already been assigned in the inspector). The loaded scenes must have at least one Interaction Manager for Interactors and Interactables to be able to communicate.
Many of the methods on the Interactors and Interactables are designed to be called by this Interaction Manager rather than being called directly in order to maintain consistency between both targets of an interaction event.
See also
IXRInteractor, IXRInteractable
Member Function Documentation
CancelInteractableHover() [1/2]
virtual void UnityEngine.XR.Interaction.Toolkit.XRInteractionManager.CancelInteractableHover (IXRHoverInteractable interactable) virtual
Automatically called when an Interactable is unregistered to cancel the hover state of the Interactable if necessary.
Parameters
interactable The Interactable to potentially exit its hover state due to cancellation.
CancelInteractableHover() [2/2]
virtual void UnityEngine.XR.Interaction.Toolkit.XRInteractionManager.CancelInteractableHover (XRBaseInteractable interactable) virtual
Automatically called when an Interactable is unregistered to cancel the hover state of the Interactable if necessary.
Parameters
interactable The Interactable to potentially exit its hover state due to cancellation.
CancelInteractableHover(XRBaseInteractable) has been deprecated. Use CancelInteractableHover(IXRHoverInteractable) instead.
CancelInteractableSelection() [1/2]
virtual void UnityEngine.XR.Interaction.Toolkit.XRInteractionManager.CancelInteractableSelection (IXRSelectInteractable interactable) virtual
Automatically called when an Interactable is unregistered to cancel the selection of the Interactable if necessary.
Parameters
interactable The Interactable to potentially exit its selection state due to cancellation.
CancelInteractableSelection() [2/2]
virtual void UnityEngine.XR.Interaction.Toolkit.XRInteractionManager.CancelInteractableSelection (XRBaseInteractable interactable) virtual
Automatically called when an Interactable is unregistered to cancel the selection of the Interactable if necessary.
Parameters
interactable The Interactable to potentially exit its selection state due to cancellation.
CancelInteractableSelection(XRBaseInteractable) has been deprecated. Use CancelInteractableSelection(IXRSelectInteractable) instead.
CancelInteractorHover() [1/2]
virtual void UnityEngine.XR.Interaction.Toolkit.XRInteractionManager.CancelInteractorHover (IXRHoverInteractor interactor) virtual
Automatically called when an Interactor is unregistered to cancel the hover state of the Interactor if necessary.
Parameters
interactor The Interactor to potentially exit its hover state due to cancellation.
CancelInteractorHover() [2/2]
virtual void UnityEngine.XR.Interaction.Toolkit.XRInteractionManager.CancelInteractorHover (XRBaseInteractor interactor) virtual
Automatically called when an Interactor is unregistered to cancel the hover state of the Interactor if necessary.
Parameters
interactor The Interactor to potentially exit its hover state due to cancellation.
CancelInteractorHover(XRBaseInteractor) has been deprecated. Use CancelInteractorHover(IXRHoverInteractor) instead.
CancelInteractorSelection() [1/2]
virtual void UnityEngine.XR.Interaction.Toolkit.XRInteractionManager.CancelInteractorSelection (IXRSelectInteractor interactor) virtual
Automatically called when an Interactor is unregistered to cancel the selection of the Interactor if necessary.
Parameters
interactor The Interactor to potentially exit its selection state due to cancellation.
CancelInteractorSelection() [2/2]
virtual void UnityEngine.XR.Interaction.Toolkit.XRInteractionManager.CancelInteractorSelection (XRBaseInteractor interactor) virtual
Automatically called when an Interactor is unregistered to cancel the selection of the Interactor if necessary.
Parameters
interactor The Interactor to potentially exit its selection state due to cancellation.
CancelInteractorSelection(XRBaseInteractor) has been deprecated. Use CancelInteractorSelection(IXRSelectInteractor) instead.
ClearInteractorHover() [1/2]
virtual void UnityEngine.XR.Interaction.Toolkit.XRInteractionManager.ClearInteractorHover (IXRHoverInteractor interactor, List< IXRInteractable > validTargets) protected virtual
Automatically called each frame during Update to clear the hover state of the Interactor if necessary due to current conditions.
Parameters
interactor The Interactor to potentially exit its hover state.
validTargets The list of interactables that this Interactor could possibly interact with this frame.
See also
ClearInteractorSelection(IXRSelectInteractor, List<IXRInteractable>)
ClearInteractorHover() [2/2]
virtual void UnityEngine.XR.Interaction.Toolkit.XRInteractionManager.ClearInteractorHover (XRBaseInteractor interactor, List< XRBaseInteractable > validTargets) virtual
Automatically called each frame during Update to clear the hover state of the Interactor if necessary due to current conditions.
Parameters
interactor The Interactor to potentially exit its hover state.
validTargets The list of interactables that this Interactor could possibly interact with this frame.
ClearInteractorHover(XRBaseInteractor, List<XRBaseInteractable>) has been deprecated. Use ClearInteractorHover(IXRHoverInteractor, List<IXRInteractable>) instead.
ClearInteractorSelection() [1/2]
virtual void UnityEngine.XR.Interaction.Toolkit.XRInteractionManager.ClearInteractorSelection (IXRSelectInteractor interactor, List< IXRInteractable > validTargets) protected virtual
Automatically called each frame during Update to clear the selection of the Interactor if necessary due to current conditions.
Parameters
interactor The Interactor to potentially exit its selection state.
validTargets The list of interactables that this Interactor could possibly interact with this frame.
See also
ClearInteractorHover(IXRHoverInteractor, List<IXRInteractable>)
ClearInteractorSelection() [2/2]
virtual void UnityEngine.XR.Interaction.Toolkit.XRInteractionManager.ClearInteractorSelection (XRBaseInteractor interactor) virtual
Automatically called each frame during Update to clear the selection of the Interactor if necessary due to current conditions.
Parameters
interactor The Interactor to potentially exit its selection state.
ClearInteractorSelection(XRBaseInteractor) has been deprecated. Use ClearInteractorSelection(IXRSelectInteractor, List<IXRInteractable>) instead.
FixedUpdate()
virtual void UnityEngine.XR.Interaction.Toolkit.XRInteractionManager.FixedUpdate () protected virtual
See MonoBehaviour.
ForceSelect()
void UnityEngine.XR.Interaction.Toolkit.XRInteractionManager.ForceSelect (XRBaseInteractor interactor, XRBaseInteractable interactable)
Manually forces selection of an Interactable. This is different than starting manual interaction.
Parameters
interactor The Interactor that will select the Interactable.
interactable The Interactable to be selected.
ForceSelect(XRBaseInteractor, XRBaseInteractable) has been deprecated. Use SelectEnter(IXRSelectInteractor, IXRSelectInteractable) instead.
GetColliderToInteractableMap()
void UnityEngine.XR.Interaction.Toolkit.XRInteractionManager.GetColliderToInteractableMap (ref Dictionary< Collider, XRBaseInteractable > map)
Gets the dictionary that has all the registered colliders and their associated Interactable.
Parameters
map When this method returns, contains the dictionary that has all the registered colliders and their associated Interactable.
Clears map before adding to it.
GetColliderToInteractableMap has been deprecated. GetColliderToInteractableMap has been deprecated. The signature no longer matches the field used by the XRInteractionManager, so a copy is returned instead of a ref. Changes to the returned Dictionary will not be observed by the XRInteractionManager.
GetInteractableForCollider()
XRBaseInteractable UnityEngine.XR.Interaction.Toolkit.XRInteractionManager.GetInteractableForCollider (Collider interactableCollider)
Gets the Interactable a specific collider is attached to.
Parameters
interactableCollider The collider of the Interactable to retrieve.
Returns
Returns the Interactable that the collider is attached to. Otherwise returns null if no such Interactable exists.
GetInteractableForCollider has been deprecated. Use TryGetInteractableForCollider(Collider, out IXRInteractable) instead.
Referenced by UnityEngine.XR.Interaction.Toolkit.XRInteractionManager.TryGetInteractableForCollider().
GetRegisteredInteractables() [1/2]
void UnityEngine.XR.Interaction.Toolkit.XRInteractionManager.GetRegisteredInteractables (List< IXRInteractable > results)
Returns all registered Interactables into List results .
Parameters
results List to receive registered Interactables.
This method populates the list with the registered Interactables at the time the method is called. It is not a live view, meaning Interactables registered or unregistered afterward will not be reflected in the results of this method. Clears results before adding to it.
See also
GetRegisteredInteractors(List<IXRInteractor>)
Referenced by UnityEngine.XR.Interaction.Toolkit.XRInteractionManager.GetRegisteredInteractables().
GetRegisteredInteractables() [2/2]
void UnityEngine.XR.Interaction.Toolkit.XRInteractionManager.GetRegisteredInteractables (List< XRBaseInteractable > results)
GetRegisteredInteractables(List<XRBaseInteractable>) has been deprecated. Use GetRegisteredInteractables(List<IXRInteractable>) instead.
GetRegisteredInteractors() [1/2]
void UnityEngine.XR.Interaction.Toolkit.XRInteractionManager.GetRegisteredInteractors (List< IXRInteractor > results)
Returns all registered Interactors into List results .
Parameters
results List to receive registered Interactors.
This method populates the list with the registered Interactors at the time the method is called. It is not a live view, meaning Interactors registered or unregistered afterward will not be reflected in the results of this method. Clears results before adding to it.
See also
GetRegisteredInteractables(List<IXRInteractable>)
Referenced by UnityEngine.XR.Interaction.Toolkit.XRInteractionManager.GetRegisteredInteractors().
GetRegisteredInteractors() [2/2]
void UnityEngine.XR.Interaction.Toolkit.XRInteractionManager.GetRegisteredInteractors (List< XRBaseInteractor > results)
GetRegisteredInteractors(List<XRBaseInteractor>) has been deprecated. Use GetRegisteredInteractors(List<IXRInteractor>) instead.
GetValidTargets() [1/2]
void UnityEngine.XR.Interaction.Toolkit.XRInteractionManager.GetValidTargets (IXRInteractor interactor, List< IXRInteractable > targets)
Retrieves the list of Interactables that the given Interactor could possibly interact with this frame. This list is sorted by priority (with highest priority first), and will only contain Interactables that are registered with this Interaction Manager.
Parameters
interactor The Interactor to get valid targets for.
targets The results list to populate with Interactables that are valid for selection or hover.
Unity expects the interactor 's implementation of IXRInteractor.GetValidTargets to clear targets before adding to it.
See also
IXRInteractor.GetValidTargets
Referenced by UnityEngine.XR.Interaction.Toolkit.XRInteractionManager.GetValidTargets(), and UnityEngine.XR.Interaction.Toolkit.XRInteractionManager.Update().
GetValidTargets() [2/2]
List< XRBaseInteractable > UnityEngine.XR.Interaction.Toolkit.XRInteractionManager.GetValidTargets (XRBaseInteractor interactor, List< XRBaseInteractable > validTargets)
For the provided interactor , returns a list of the valid Interactables that can be hovered over or selected.
Parameters
interactor The Interactor whose valid targets we want to find.
validTargets List to be filled with valid targets of the Interactor.
Returns
The list of valid targets of the Interactor.
See also
IXRInteractor.GetValidTargets
GetValidTargets(XRBaseInteractor, List<XRBaseInteractable>) has been deprecated. Use GetValidTargets(IXRInteractor, List<IXRInteractable>) instead.
HasInteractionLayerOverlap()
static bool UnityEngine.XR.Interaction.Toolkit.XRInteractionManager.HasInteractionLayerOverlap (IXRInteractor interactor, IXRInteractable interactable) static protected
Determines whether the Interactor and Interactable share at least one interaction layer between their Interaction Layer Masks.
Parameters
interactor The Interactor to check.
interactable The Interactable to check.
Returns
Returns true if the Interactor and Interactable share at least one interaction layer. Otherwise, returns false.
See also
IXRInteractor.interactionLayers, IXRInteractable.interactionLayers
Referenced by UnityEngine.XR.Interaction.Toolkit.XRInteractionManager.ClearInteractorHover(), UnityEngine.XR.Interaction.Toolkit.XRInteractionManager.ClearInteractorSelection(), UnityEngine.XR.Interaction.Toolkit.XRInteractionManager.InteractorHoverValidTargets(), and UnityEngine.XR.Interaction.Toolkit.XRInteractionManager.InteractorSelectValidTargets().
HoverCancel() [1/2]
virtual void UnityEngine.XR.Interaction.Toolkit.XRInteractionManager.HoverCancel (IXRHoverInteractor interactor, IXRHoverInteractable interactable) virtual
Initiates ending hovering of an Interactable by an Interactor due to cancellation, such as from either being unregistered due to being disabled or destroyed.
Parameters
interactor The Interactor that is no longer hovering.
interactable The Interactable that is no longer being hovered over.
HoverCancel() [2/2]
virtual void UnityEngine.XR.Interaction.Toolkit.XRInteractionManager.HoverCancel (XRBaseInteractor interactor, XRBaseInteractable interactable) virtual
Initiates ending hovering of an Interactable by an Interactor due to cancellation, such as from either being unregistered due to being disabled or destroyed.
Parameters
interactor The Interactor that is no longer hovering.
interactable The Interactable that is no longer being hovered over.
HoverCancel(XRBaseInteractor, XRBaseInteractable) has been deprecated. Use HoverCancel(IXRHoverInteractor, IXRHoverInteractable) instead.
HoverEnter() [1/4]
virtual void UnityEngine.XR.Interaction.Toolkit.XRInteractionManager.HoverEnter (IXRHoverInteractor interactor, IXRHoverInteractable interactable) virtual
Initiates hovering of an Interactable by an Interactor.
Parameters
interactor The Interactor that is hovering.
interactable The Interactable being hovered over.
HoverEnter() [2/4]
virtual void UnityEngine.XR.Interaction.Toolkit.XRInteractionManager.HoverEnter (IXRHoverInteractor interactor, IXRHoverInteractable interactable, HoverEnterEventArgs args) protected virtual
Initiates hovering of an Interactable by an Interactor, passing the given args .
Parameters
interactor The Interactor that is hovering.
interactable The Interactable being hovered over.
args Event data containing the Interactor and Interactable involved in the event.
The interactor and interactable are notified immediately without waiting for a previous call to finish in the case when this method is called again in a nested way. This means that if this method is called during the handling of the first event, the second will start and finish before the first event finishes calling all methods in the sequence to notify of the first event.
HoverEnter() [3/4]
virtual void UnityEngine.XR.Interaction.Toolkit.XRInteractionManager.HoverEnter (XRBaseInteractor interactor, XRBaseInteractable interactable) virtual
Initiates hovering of an Interactable by an Interactor.
Parameters
interactor The Interactor that is hovering.
interactable The Interactable being hovered over.
HoverEnter(XRBaseInteractor, XRBaseInteractable) has been deprecated. Use HoverEnter(IXRHoverInteractor, IXRHoverInteractable) instead.
HoverEnter() [4/4]
virtual void UnityEngine.XR.Interaction.Toolkit.XRInteractionManager.HoverEnter (XRBaseInteractor interactor, XRBaseInteractable interactable, HoverEnterEventArgs args) protected virtual
Initiates hovering of an Interactable by an Interactor, passing the given args .
Parameters
interactor The Interactor that is hovering.
interactable The Interactable being hovered over.
args Event data containing the Interactor and Interactable involved in the event.
HoverEnter(XRBaseInteractor, XRBaseInteractable, HoverEnterEventArgs) has been deprecated. Use HoverEnter(IXRHoverInteractor, IXRHoverInteractable, HoverEnterEventArgs) instead.
HoverExit() [1/4]
virtual void UnityEngine.XR.Interaction.Toolkit.XRInteractionManager.HoverExit (IXRHoverInteractor interactor, IXRHoverInteractable interactable) virtual
Initiates ending hovering of an Interactable by an Interactor.
Parameters
interactor The Interactor that is no longer hovering.
interactable The Interactable that is no longer being hovered over.
HoverExit() [2/4]
virtual void UnityEngine.XR.Interaction.Toolkit.XRInteractionManager.HoverExit (IXRHoverInteractor interactor, IXRHoverInteractable interactable, HoverExitEventArgs args) protected virtual
Initiates ending hovering of an Interactable by an Interactor, passing the given args .
Parameters
interactor The Interactor that is no longer hovering.
interactable The Interactable that is no longer being hovered over.
args Event data containing the Interactor and Interactable involved in the event.
The interactor and interactable are notified immediately without waiting for a previous call to finish in the case when this method is called again in a nested way. This means that if this method is called during the handling of the first event, the second will start and finish before the first event finishes calling all methods in the sequence to notify of the first event.
HoverExit() [3/4]
virtual void UnityEngine.XR.Interaction.Toolkit.XRInteractionManager.HoverExit (XRBaseInteractor interactor, XRBaseInteractable interactable) virtual
Initiates ending hovering of an Interactable by an Interactor.
Parameters
interactor The Interactor that is no longer hovering.
interactable The Interactable that is no longer being hovered over.
HoverExit(XRBaseInteractor, XRBaseInteractable) has been deprecated. Use HoverExit(IXRHoverInteractor, IXRHoverInteractable) instead.
HoverExit() [4/4]
virtual void UnityEngine.XR.Interaction.Toolkit.XRInteractionManager.HoverExit (XRBaseInteractor interactor, XRBaseInteractable interactable, HoverExitEventArgs args) protected virtual
Initiates ending hovering of an Interactable by an Interactor, passing the given args .
Parameters
interactor The Interactor that is no longer hovering.
interactable The Interactable that is no longer being hovered over.
args Event data containing the Interactor and Interactable involved in the event.
HoverExit(XRBaseInteractor, XRBaseInteractable, HoverExitEventArgs) has been deprecated. Use HoverExit(IXRHoverInteractor, IXRHoverInteractable, HoverExitEventArgs) instead.
InteractorHoverValidTargets() [1/2]
virtual void UnityEngine.XR.Interaction.Toolkit.XRInteractionManager.InteractorHoverValidTargets (IXRHoverInteractor interactor, List< IXRInteractable > validTargets) protected virtual
Automatically called each frame during Update to enter the hover state of the Interactor if necessary due to current conditions.
Parameters
interactor The Interactor to potentially enter its hover state.
validTargets The list of interactables that this Interactor could possibly interact with this frame.
See also
InteractorSelectValidTargets(IXRSelectInteractor, List<IXRInteractable>)
InteractorHoverValidTargets() [2/2]
virtual void UnityEngine.XR.Interaction.Toolkit.XRInteractionManager.InteractorHoverValidTargets (XRBaseInteractor interactor, List< XRBaseInteractable > validTargets) protected virtual
Automatically called each frame during Update to enter the hover state of the Interactor if necessary due to current conditions.
Parameters
interactor The Interactor to potentially enter its hover state.
validTargets The list of interactables that this Interactor could possibly interact with this frame.
InteractorHoverValidTargets(XRBaseInteractor, List<XRBaseInteractable>) has been deprecated. Use InteractorHoverValidTargets(IXRHoverInteractor, List<IXRInteractable>) instead.
InteractorSelectValidTargets() [1/2]
virtual void UnityEngine.XR.Interaction.Toolkit.XRInteractionManager.InteractorSelectValidTargets (IXRSelectInteractor interactor, List< IXRInteractable > validTargets) protected virtual
Automatically called each frame during Update to enter the selection state of the Interactor if necessary due to current conditions.
Parameters
interactor The Interactor to potentially enter its selection state.
validTargets The list of interactables that this Interactor could possibly interact with this frame.
See also
InteractorHoverValidTargets(IXRHoverInteractor, List<IXRInteractable>)
InteractorSelectValidTargets() [2/2]
virtual void UnityEngine.XR.Interaction.Toolkit.XRInteractionManager.InteractorSelectValidTargets (XRBaseInteractor interactor, List< XRBaseInteractable > validTargets) protected virtual
Automatically called each frame during Update to enter the selection state of the Interactor if necessary due to current conditions.
Parameters
interactor The Interactor to potentially enter its selection state.
validTargets The list of interactables that this Interactor could possibly interact with this frame.
InteractorSelectValidTargets(XRBaseInteractor, List<XRBaseInteractable>) has been deprecated. Use InteractorSelectValidTargets(IXRSelectInteractor, List<IXRInteractable>) instead.
IsRegistered() [1/4]
bool UnityEngine.XR.Interaction.Toolkit.XRInteractionManager.IsRegistered (IXRInteractable interactable)
Checks whether the interactable is registered with this Interaction Manager.
Parameters
interactable The Interactable to check.
Returns
Returns true if registered. Otherwise, returns false.
See also
RegisterInteractable(IXRInteractable)
IsRegistered() [2/4]
bool UnityEngine.XR.Interaction.Toolkit.XRInteractionManager.IsRegistered (IXRInteractor interactor)
Checks whether the interactor is registered with this Interaction Manager.
Parameters
interactor The Interactor to check.
Returns
Returns true if registered. Otherwise, returns false.
See also
RegisterInteractor(IXRInteractor)
Referenced by UnityEngine.XR.Interaction.Toolkit.XRInteractionManager.UnregisterInteractable(), and UnityEngine.XR.Interaction.Toolkit.XRInteractionManager.UnregisterInteractor().
IsRegistered() [3/4]
bool UnityEngine.XR.Interaction.Toolkit.XRInteractionManager.IsRegistered (XRBaseInteractable interactable)
IsRegistered(XRBaseInteractable) has been deprecated. Use IsRegistered(IXRInteractable) instead.
IsRegistered() [4/4]
bool UnityEngine.XR.Interaction.Toolkit.XRInteractionManager.IsRegistered (XRBaseInteractor interactor)
IsRegistered(XRBaseInteractor) has been deprecated. Use IsRegistered(IXRInteractor) instead.
LateUpdate()
virtual void UnityEngine.XR.Interaction.Toolkit.XRInteractionManager.LateUpdate () protected virtual
See MonoBehaviour.
OnBeforeRender()
virtual void UnityEngine.XR.Interaction.Toolkit.XRInteractionManager.OnBeforeRender () protected virtual
Delegate method used to register for "Just Before Render" input updates for VR devices.
See also
Application
Referenced by UnityEngine.XR.Interaction.Toolkit.XRInteractionManager.OnDisable(), and UnityEngine.XR.Interaction.Toolkit.XRInteractionManager.OnEnable().
OnDisable()
virtual void UnityEngine.XR.Interaction.Toolkit.XRInteractionManager.OnDisable () protected virtual
See MonoBehaviour.
OnEnable()
virtual void UnityEngine.XR.Interaction.Toolkit.XRInteractionManager.OnEnable () protected virtual
See MonoBehaviour.
OnRegistered() [1/2]
virtual void UnityEngine.XR.Interaction.Toolkit.XRInteractionManager.OnRegistered (InteractableRegisteredEventArgs args) protected virtual
Automatically called when an Interactable is registered with this Interaction Manager. Notifies the Interactable, passing the given args .
Parameters
args Event data containing the registered Interactable.
args is only valid during this method call, do not hold a reference to it.
See also
RegisterInteractable(IXRInteractable)
OnRegistered() [2/2]
virtual void UnityEngine.XR.Interaction.Toolkit.XRInteractionManager.OnRegistered (InteractorRegisteredEventArgs args) protected virtual
Automatically called when an Interactor is registered with this Interaction Manager. Notifies the Interactor, passing the given args .
Parameters
args Event data containing the registered Interactor.
args is only valid during this method call, do not hold a reference to it.
See also
RegisterInteractor(IXRInteractor)
Referenced by UnityEngine.XR.Interaction.Toolkit.XRInteractionManager.RegisterInteractable(), and UnityEngine.XR.Interaction.Toolkit.XRInteractionManager.RegisterInteractor().
OnUnregistered() [1/2]
virtual void UnityEngine.XR.Interaction.Toolkit.XRInteractionManager.OnUnregistered (InteractableUnregisteredEventArgs args) protected virtual
Automatically called when an Interactable is unregistered from this Interaction Manager. Notifies the Interactable, passing the given args .
Parameters
args Event data containing the unregistered Interactable.
args is only valid during this method call, do not hold a reference to it.
See also
UnregisterInteractable(IXRInteractable)
OnUnregistered() [2/2]
virtual void UnityEngine.XR.Interaction.Toolkit.XRInteractionManager.OnUnregistered (InteractorUnregisteredEventArgs args) protected virtual
Automatically called when an Interactor is unregistered from this Interaction Manager. Notifies the Interactor, passing the given args .
Parameters
args Event data containing the unregistered Interactor.
args is only valid during this method call, do not hold a reference to it.
See also
UnregisterInteractor(IXRInteractor)
Referenced by UnityEngine.XR.Interaction.Toolkit.XRInteractionManager.UnregisterInteractable(), and UnityEngine.XR.Interaction.Toolkit.XRInteractionManager.UnregisterInteractor().
PreprocessInteractors()
virtual void UnityEngine.XR.Interaction.Toolkit.XRInteractionManager.PreprocessInteractors (XRInteractionUpdateOrder::UpdatePhase updatePhase) protected virtual
Automatically called each frame to preprocess all interactors registered with this manager.
Parameters
updatePhase The update phase.
Please see the XRInteractionUpdateOrder.UpdatePhase documentation for more details on update order.
See also
IXRInteractor.PreprocessInteractor, XRInteractionUpdateOrder.UpdatePhase
Referenced by UnityEngine.XR.Interaction.Toolkit.XRInteractionManager.Update().
ProcessInteractables()
virtual void UnityEngine.XR.Interaction.Toolkit.XRInteractionManager.ProcessInteractables (XRInteractionUpdateOrder::UpdatePhase updatePhase) protected virtual
Automatically called each frame to process all interactables registered with this manager.
Parameters
updatePhase The update phase.
Please see the XRInteractionUpdateOrder.UpdatePhase documentation for more details on update order.
See also
IXRInteractable.ProcessInteractable, XRInteractionUpdateOrder.UpdatePhase
Referenced by UnityEngine.XR.Interaction.Toolkit.XRInteractionManager.FixedUpdate(), UnityEngine.XR.Interaction.Toolkit.XRInteractionManager.LateUpdate(), UnityEngine.XR.Interaction.Toolkit.XRInteractionManager.OnBeforeRender(), and UnityEngine.XR.Interaction.Toolkit.XRInteractionManager.Update().
ProcessInteractors()
virtual void UnityEngine.XR.Interaction.Toolkit.XRInteractionManager.ProcessInteractors (XRInteractionUpdateOrder::UpdatePhase updatePhase) protected virtual
Automatically called each frame to process all interactors registered with this manager.
Parameters
updatePhase The update phase.
Please see the XRInteractionUpdateOrder.UpdatePhase documentation for more details on update order.
See also
IXRInteractor.PreprocessInteractor, XRInteractionUpdateOrder.UpdatePhase
Referenced by UnityEngine.XR.Interaction.Toolkit.XRInteractionManager.FixedUpdate(), UnityEngine.XR.Interaction.Toolkit.XRInteractionManager.LateUpdate(), UnityEngine.XR.Interaction.Toolkit.XRInteractionManager.OnBeforeRender(), and UnityEngine.XR.Interaction.Toolkit.XRInteractionManager.Update().
RegisterInteractable() [1/2]
virtual void UnityEngine.XR.Interaction.Toolkit.XRInteractionManager.RegisterInteractable (IXRInteractable interactable) virtual
Registers a new Interactable to be processed.
Parameters
interactable The Interactable to be registered.
RegisterInteractable() [2/2]
virtual void UnityEngine.XR.Interaction.Toolkit.XRInteractionManager.RegisterInteractable (XRBaseInteractable interactable) virtual
RegisterInteractable(XRBaseInteractable) has been deprecated. Use RegisterInteractable(IXRInteractable) instead.
RegisterInteractor() [1/2]
virtual void UnityEngine.XR.Interaction.Toolkit.XRInteractionManager.RegisterInteractor (IXRInteractor interactor) virtual
Registers a new Interactor to be processed.
Parameters
interactor The Interactor to be registered.
RegisterInteractor() [2/2]
virtual void UnityEngine.XR.Interaction.Toolkit.XRInteractionManager.RegisterInteractor (XRBaseInteractor interactor) virtual
RegisterInteractor(XRBaseInteractor) has been deprecated. Use RegisterInteractor(IXRInteractor) instead.
ResolveExistingSelect()
virtual bool UnityEngine.XR.Interaction.Toolkit.XRInteractionManager.ResolveExistingSelect (IXRSelectInteractor interactor, IXRSelectInteractable interactable) protected virtual
Automatically called when selection of an Interactable by an Interactor is initiated and the Interactable is already selected.
Parameters
interactor The Interactor that is selecting.
interactable The Interactable being selected.
Returns
Returns true if the existing selection was successfully resolved and selection should continue. Otherwise, returns false if the select should be ignored.
See also
SelectEnter(IXRSelectInteractor, IXRSelectInteractable)
Referenced by UnityEngine.XR.Interaction.Toolkit.XRInteractionManager.SelectEnter().
SelectCancel() [1/2]
virtual void UnityEngine.XR.Interaction.Toolkit.XRInteractionManager.SelectCancel (IXRSelectInteractor interactor, IXRSelectInteractable interactable) virtual
Initiates ending selection of an Interactable by an Interactor due to cancellation, such as from either being unregistered due to being disabled or destroyed.
Parameters
interactor The Interactor that is no longer selecting.
interactable The Interactable that is no longer being selected.
SelectCancel() [2/2]
virtual void UnityEngine.XR.Interaction.Toolkit.XRInteractionManager.SelectCancel (XRBaseInteractor interactor, XRBaseInteractable interactable) virtual
Initiates ending selection of an Interactable by an Interactor due to cancellation, such as from either being unregistered due to being disabled or destroyed.
Parameters
interactor The Interactor that is no longer selecting.
interactable The Interactable that is no longer being selected.
SelectCancel(XRBaseInteractor, XRBaseInteractable) has been deprecated. Use SelectCancel(IXRSelectInteractor, IXRSelectInteractable) instead.
SelectEnter() [1/4]
virtual void UnityEngine.XR.Interaction.Toolkit.XRInteractionManager.SelectEnter (IXRSelectInteractor interactor, IXRSelectInteractable interactable) virtual
Initiates selection of an Interactable by an Interactor. This method may first result in other interaction events such as causing the Interactable to first exit being selected.
Parameters
interactor The Interactor that is selecting.
interactable The Interactable being selected.
This attempt may be ignored depending on the selection policy of the Interactor and/or the Interactable.
Referenced by UnityEngine.XR.Interaction.Toolkit.XRBaseInteractor.Start(), and UnityEngine.XR.Interaction.Toolkit.XRBaseInteractor.StartManualInteraction().
SelectEnter() [2/4]
virtual void UnityEngine.XR.Interaction.Toolkit.XRInteractionManager.SelectEnter (IXRSelectInteractor interactor, IXRSelectInteractable interactable, SelectEnterEventArgs args) protected virtual
Initiates selection of an Interactable by an Interactor, passing the given args .
Parameters
interactor The Interactor that is selecting.
interactable The Interactable being selected.
args Event data containing the Interactor and Interactable involved in the event.
The interactor and interactable are notified immediately without waiting for a previous call to finish in the case when this method is called again in a nested way. This means that if this method is called during the handling of the first event, the second will start and finish before the first event finishes calling all methods in the sequence to notify of the first event.
SelectEnter() [3/4]
virtual void UnityEngine.XR.Interaction.Toolkit.XRInteractionManager.SelectEnter (XRBaseInteractor interactor, XRBaseInteractable interactable) virtual
Initiates selection of an Interactable by an Interactor. This method may first result in other interaction events such as causing the Interactable to first exit being selected.
Parameters
interactor The Interactor that is selecting.
interactable The Interactable being selected.
This attempt may be ignored depending on the selection policy of the Interactor and/or the Interactable.
SelectEnter(XRBaseInteractor, XRBaseInteractable) has been deprecated. Use SelectEnter(IXRSelectInteractor, IXRSelectInteractable) instead.
SelectEnter() [4/4]
virtual void UnityEngine.XR.Interaction.Toolkit.XRInteractionManager.SelectEnter (XRBaseInteractor interactor, XRBaseInteractable interactable, SelectEnterEventArgs args) protected virtual
Initiates selection of an Interactable by an Interactor, passing the given args .
Parameters
interactor The Interactor that is selecting.
interactable The Interactable being selected.
args Event data containing the Interactor and Interactable involved in the event.
SelectExit(XRBaseInteractor, XRBaseInteractable, SelectExitEventArgs) has been deprecated. Use SelectExit(IXRSelectInteractor, IXRSelectInteractable, SelectExitEventArgs) instead.
SelectExit() [1/4]
virtual void UnityEngine.XR.Interaction.Toolkit.XRInteractionManager.SelectExit (IXRSelectInteractor interactor, IXRSelectInteractable interactable) virtual
Initiates ending selection of an Interactable by an Interactor.
Parameters
interactor The Interactor that is no longer selecting.
interactable The Interactable that is no longer being selected.
Referenced by UnityEngine.XR.Interaction.Toolkit.XRBaseInteractor.EndManualInteraction().
SelectExit() [2/4]
virtual void UnityEngine.XR.Interaction.Toolkit.XRInteractionManager.SelectExit (IXRSelectInteractor interactor, IXRSelectInteractable interactable, SelectExitEventArgs args) protected virtual
Initiates ending selection of an Interactable by an Interactor, passing the given args .
Parameters
interactor The Interactor that is no longer selecting.
interactable The Interactable that is no longer being selected.
args Event data containing the Interactor and Interactable involved in the event.
The interactor and interactable are notified immediately without waiting for a previous call to finish in the case when this method is called again in a nested way. This means that if this method is called during the handling of the first event, the second will start and finish before the first event finishes calling all methods in the sequence to notify of the first event.
SelectExit() [3/4]
virtual void UnityEngine.XR.Interaction.Toolkit.XRInteractionManager.SelectExit (XRBaseInteractor interactor, XRBaseInteractable interactable) virtual
Initiates ending selection of an Interactable by an Interactor.
Parameters
interactor The Interactor that is no longer selecting.
interactable The Interactable that is no longer being selected.
SelectExit(XRBaseInteractor, XRBaseInteractable) has been deprecated. Use SelectExit(IXRSelectInteractor, IXRSelectInteractable) instead.
SelectExit() [4/4]
virtual void UnityEngine.XR.Interaction.Toolkit.XRInteractionManager.SelectExit (XRBaseInteractor interactor, XRBaseInteractable interactable, SelectExitEventArgs args) protected virtual
Initiates ending selection of an Interactable by an Interactor, passing the given args .
Parameters
interactor The Interactor that is no longer selecting.
interactable The Interactable that is no longer being selected.
args Event data containing the Interactor and Interactable involved in the event.
SelectExit(XRBaseInteractor, XRBaseInteractable, SelectExitEventArgs) has been deprecated. Use SelectExit(IXRSelectInteractor, IXRSelectInteractable, SelectExitEventArgs) instead.
TryGetInteractableForCollider() [1/2]
XRBaseInteractable UnityEngine.XR.Interaction.Toolkit.XRInteractionManager.TryGetInteractableForCollider (Collider interactableCollider)
TryGetInteractableForCollider has been deprecated. Use GetInteractableForCollider instead.
TryGetInteractableForCollider() [2/2]
bool UnityEngine.XR.Interaction.Toolkit.XRInteractionManager.TryGetInteractableForCollider (Collider interactableCollider, out IXRInteractable interactable)
Gets the Interactable a specific Collider is attached to.
Parameters
interactableCollider The collider of the Interactable to retrieve.
interactable The returned Interactable associated with the collider.
Returns
Returns true if an Interactable was associated with the collider. Otherwise, returns false.
Referenced by UnityEngine.XR.Interaction.Toolkit.Utilities.TriggerContactMonitor.AddCollider(), UnityEngine.XR.Interaction.Toolkit.XRInteractionManager.GetInteractableForCollider(), UnityEngine.XR.Interaction.Toolkit.XRRayInteractor.GetValidTargets(), UnityEngine.XR.Interaction.Toolkit.Utilities.TriggerContactMonitor.ResolveUnassociatedColliders(), UnityEngine.XR.Interaction.Toolkit.Utilities.TriggerContactMonitor.ResolveUnassociatedColliders(), and UnityEngine.XR.Interaction.Toolkit.XRRayInteractor.TryGetHitInfo().
UnregisterInteractable() [1/2]
virtual void UnityEngine.XR.Interaction.Toolkit.XRInteractionManager.UnregisterInteractable (IXRInteractable interactable) virtual
Unregister an Interactable so it is no longer processed.
Parameters
interactable The Interactable to be unregistered.
UnregisterInteractable() [2/2]
virtual void UnityEngine.XR.Interaction.Toolkit.XRInteractionManager.UnregisterInteractable (XRBaseInteractable interactable) virtual
UnregisterInteractable(XRBaseInteractable) has been deprecated. Use UnregisterInteractable(IXRInteractable) instead.
UnregisterInteractor() [1/2]
virtual void UnityEngine.XR.Interaction.Toolkit.XRInteractionManager.UnregisterInteractor (IXRInteractor interactor) virtual
Unregister an Interactor so it is no longer processed.
Parameters
interactor The Interactor to be unregistered.
UnregisterInteractor() [2/2]
virtual void UnityEngine.XR.Interaction.Toolkit.XRInteractionManager.UnregisterInteractor (XRBaseInteractor interactor) virtual
UnregisterInteractor(XRBaseInteractor) has been deprecated. Use UnregisterInteractor(IXRInteractor) instead.
Update()
virtual void UnityEngine.XR.Interaction.Toolkit.XRInteractionManager.Update () protected virtual
See MonoBehaviour.
Event Documentation
interactableRegistered
Action<InteractableRegisteredEventArgs> UnityEngine.XR.Interaction.Toolkit.XRInteractionManager.interactableRegistered
Calls the methods in its invocation list when an IXRInteractable is registered.
The InteractableRegisteredEventArgs passed to each listener is only valid while the event is invoked, do not hold a reference to it.
See also
RegisterInteractable(IXRInteractable), IXRInteractable.registered
Referenced by UnityEngine.XR.Interaction.Toolkit.XRInteractionManager.OnRegistered().
interactableUnregistered
Action<InteractableUnregisteredEventArgs> UnityEngine.XR.Interaction.Toolkit.XRInteractionManager.interactableUnregistered
Calls the methods in its invocation list when an IXRInteractable is unregistered.
The InteractableUnregisteredEventArgs passed to each listener is only valid while the event is invoked, do not hold a reference to it.
See also
UnregisterInteractable(IXRInteractable), IXRInteractable.unregistered
Referenced by UnityEngine.XR.Interaction.Toolkit.XRInteractionManager.OnUnregistered().
interactorRegistered
Action<InteractorRegisteredEventArgs> UnityEngine.XR.Interaction.Toolkit.XRInteractionManager.interactorRegistered
Calls the methods in its invocation list when an IXRInteractor is registered.
The InteractorRegisteredEventArgs passed to each listener is only valid while the event is invoked, do not hold a reference to it.
See also
RegisterInteractor(IXRInteractor), IXRInteractor.registered
Referenced by UnityEngine.XR.Interaction.Toolkit.XRInteractionManager.OnRegistered().
interactorUnregistered
Action<InteractorUnregisteredEventArgs> UnityEngine.XR.Interaction.Toolkit.XRInteractionManager.interactorUnregistered
Calls the methods in its invocation list when an IXRInteractor is unregistered.
The InteractorUnregisteredEventArgs passed to each listener is only valid while the event is invoked, do not hold a reference to it.
See also
UnregisterInteractor(IXRInteractor), IXRInteractor.unregistered
Referenced by UnityEngine.XR.Interaction.Toolkit.XRInteractionManager.OnUnregistered().
The documentation for this class was generated from the following files:
C:/Users/Lykos/Desktop/Projects/Capstone/VRGames/Library/PackageCache/com.unity.xr.interaction.toolkit@2.0.2/Runtime/Interaction/XRInteractionManager.cs
C:/Users/Lykos/Desktop/Projects/Capstone/VRGames/Library/PackageCache/com.unity.xr.interaction.toolkit@2.0.2/Runtime/Interaction/XRInteractionManager.deprecated.cs