VRGames: UnityEditor.Timeline.PropertyCollector Class Reference
UnityEditor.Timeline.PropertyCollector Class Reference
Public Member Functions
void Reset ()
void Clear ()
void PushActiveGameObject (GameObject gameObject)
Sets the active game object for subsequent property modifications.
void PopActiveGameObject ()
Removes the active GameObject from the modification stack, restoring the previous value.
void AddFromClip (AnimationClip clip)
Add properties modified by an animation clip.
void AddFromClips (IEnumerable< AnimationClip > clips)
Add property modifications specified by a list of animation clips.
void AddFromName< T > (string name)
Add property modifications using the serialized property name.
void AddFromName (string name)
Add property modifications using the serialized property name.
void AddFromClip (GameObject obj, AnimationClip clip)
Add property modifications modified by an animation clip.
void AddFromClips (GameObject animatorRoot, IEnumerable< AnimationClip > clips)
Add property modifications specified by a list of animation clips.
void AddFromName< T > (GameObject obj, string name)
Add property modifications using the serialized property name.
void AddFromName (GameObject obj, string name)
Add property modifications using the serialized property name.
void AddFromName (Component component, string name)
Add property modifications using the serialized property name.
void AddFromComponent (GameObject obj, Component component)
Set all serializable properties on a component to be under preview control.
void AddObjectProperties (Object obj, AnimationClip clip)
Add property modifications modified by an animation clip.
Member Function Documentation
AddFromClip() [1/2]
void UnityEditor.Timeline.PropertyCollector.AddFromClip (AnimationClip clip)
Add properties modified by an animation clip.
Parameters
clip The animation clip that contains the properties
Implements UnityEngine.Timeline.IPropertyCollector.
Referenced by UnityEditor.Timeline.PropertyCollector.AddFromClip().
AddFromClip() [2/2]
void UnityEditor.Timeline.PropertyCollector.AddFromClip (GameObject obj, AnimationClip clip)
Add property modifications modified by an animation clip.
Parameters
obj The GameObject where the properties exist
clip The animation clip that contains the properties
Implements UnityEngine.Timeline.IPropertyCollector.
AddFromClips() [1/2]
void UnityEditor.Timeline.PropertyCollector.AddFromClips (GameObject obj, IEnumerable< AnimationClip > clips)
Add property modifications specified by a list of animation clips.
Parameters
obj The gameObject that will be animated
clips The list of animation clips used to determine which property modifications to apply.
Implements UnityEngine.Timeline.IPropertyCollector.
AddFromClips() [2/2]
void UnityEditor.Timeline.PropertyCollector.AddFromClips (IEnumerable< AnimationClip > clips)
Add property modifications specified by a list of animation clips.
Parameters
clips The list of animation clips used to determine which property modifications to apply.
Implements UnityEngine.Timeline.IPropertyCollector.
Referenced by UnityEditor.Timeline.PropertyCollector.AddFromClips().
AddFromComponent()
void UnityEditor.Timeline.PropertyCollector.AddFromComponent (GameObject obj, Component component)
Set all serializable properties on a component to be under preview control.
Parameters
obj The gameObject where the properties exist
component The component to set in preview mode
Implements UnityEngine.Timeline.IPropertyCollector.
AddFromName() [1/3]
void UnityEditor.Timeline.PropertyCollector.AddFromName (Component component, string name)
Add property modifications using the serialized property name.
Parameters
name The name of the serialized property
component The component where the properties exist
Implements UnityEngine.Timeline.IPropertyCollector.
AddFromName() [2/3]
void UnityEditor.Timeline.PropertyCollector.AddFromName (GameObject obj, string name)
Add property modifications using the serialized property name.
Parameters
obj The gameObject where the properties exist
name The name of the serialized property
Implements UnityEngine.Timeline.IPropertyCollector.
AddFromName() [3/3]
void UnityEditor.Timeline.PropertyCollector.AddFromName (string name)
Add property modifications using the serialized property name.
Parameters
name The name of the serialized property
This method uses the most recent gameObject from PushActiveGameObject
Implements UnityEngine.Timeline.IPropertyCollector.
Referenced by UnityEditor.Timeline.PropertyCollector.AddFromName().
AddFromName< T >() [1/2]
void UnityEditor.Timeline.PropertyCollector.AddFromName< T > (GameObject obj, string name)
Add property modifications using the serialized property name.
Parameters
name The name of the serialized property
obj The gameObject where the properties exist
Template Parameters
T The type of the component the property exists on
>
Implements UnityEngine.Timeline.IPropertyCollector.
Type Constraints
T : Component
AddFromName< T >() [2/2]
void UnityEditor.Timeline.PropertyCollector.AddFromName< T > (string name)
Add property modifications using the serialized property name.
Parameters
name The name of the serialized property
Template Parameters
T The type of the component the property exists on
This method uses the most recent gameObject from PushActiveGameObject
Implements UnityEngine.Timeline.IPropertyCollector.
Type Constraints
T : Component
Referenced by UnityEditor.Timeline.PropertyCollector.AddFromName< T >().
AddObjectProperties()
void UnityEditor.Timeline.PropertyCollector.AddObjectProperties (Object obj, AnimationClip clip)
Add property modifications modified by an animation clip.
Parameters
obj The Object where the properties exist
clip The animation clip that contains the properties
Implements UnityEngine.Timeline.IPropertyCollector.
Clear()
void UnityEditor.Timeline.PropertyCollector.Clear ()
Referenced by UnityEditor.Timeline.WindowState.SetCurrentSequence().
PopActiveGameObject()
void UnityEditor.Timeline.PropertyCollector.PopActiveGameObject ()
Removes the active GameObject from the modification stack, restoring the previous value.
Implements UnityEngine.Timeline.IPropertyCollector.
PushActiveGameObject()
void UnityEditor.Timeline.PropertyCollector.PushActiveGameObject (GameObject gameObject)
Sets the active game object for subsequent property modifications.
Parameters
gameObject The GameObject to push.
Implements UnityEngine.Timeline.IPropertyCollector.
Referenced by UnityEditor.Timeline.WindowState.GatherProperties().
Reset()
void UnityEditor.Timeline.PropertyCollector.Reset ()
Referenced by UnityEditor.Timeline.WindowState.GatherProperties().
The documentation for this class was generated from the following file:
C:/Users/Lykos/Desktop/Projects/Capstone/VRGames/Library/PackageCache/com.unity.timeline@1.6.4/Editor/Utilities/PropertyCollector.cs