VRGames: UnityEngine.UI.HorizontalOrVerticalLayoutGroup Class Reference
UnityEngine.UI.HorizontalOrVerticalLayoutGroup Class Reference abstract
Abstract base class for HorizontalLayoutGroup and VerticalLayoutGroup to generalize common functionality.
Protected Member Functions
void CalcAlongAxis (int axis, bool isVertical)
Calculate the layout element properties for this layout element along the given axis.
void SetChildrenAlongAxis (int axis, bool isVertical)
Set the positions and sizes of the child layout elements for the given axis.
Protected Member Functions inherited from UnityEngine.UI.LayoutGroup
LayoutGroup ()
override void OnEnable ()
override void OnDisable ()
override void OnDidApplyAnimationProperties ()
Callback for when properties have been changed by animation.
float GetTotalMinSize (int axis)
The min size for the layout group on the given axis.
float GetTotalPreferredSize (int axis)
The preferred size for the layout group on the given axis.
float GetTotalFlexibleSize (int axis)
The flexible size for the layout group on the given axis.
float GetStartOffset (int axis, float requiredSpaceWithoutPadding)
Returns the calculated position of the first child layout element along the given axis.
float GetAlignmentOnAxis (int axis)
Returns the alignment on the specified axis as a fraction where 0 is left/top, 0.5 is middle, and 1 is right/bottom.
void SetLayoutInputForAxis (float totalMin, float totalPreferred, float totalFlexible, int axis)
Used to set the calculated layout properties for the given axis.
void SetChildAlongAxis (RectTransform rect, int axis, float pos)
Set the position and size of a child layout element along the given axis.
void SetChildAlongAxisWithScale (RectTransform rect, int axis, float pos, float scaleFactor)
Set the position and size of a child layout element along the given axis.
void SetChildAlongAxis (RectTransform rect, int axis, float pos, float size)
Set the position and size of a child layout element along the given axis.
void SetChildAlongAxisWithScale (RectTransform rect, int axis, float pos, float size, float scaleFactor)
Set the position and size of a child layout element along the given axis.
override void OnRectTransformDimensionsChange ()
This callback is called when the dimensions of an associated RectTransform change. It is always called before Awake, OnEnable, or Start. The call is also made to all child RectTransforms, regardless of whether their dimensions change (which depends on how they are anchored).
virtual void OnTransformChildrenChanged ()
void SetProperty< T > (ref T currentValue, T newValue)
Helper method used to set a given property if it has changed.
void SetDirty ()
Mark the LayoutGroup as dirty.
Protected Member Functions inherited from UnityEngine.EventSystems.UIBehaviour
virtual void Awake ()
virtual void Start ()
virtual void OnDestroy ()
virtual void OnBeforeTransformParentChanged ()
virtual void OnTransformParentChanged ()
virtual void OnCanvasGroupChanged ()
virtual void OnCanvasHierarchyChanged ()
Called when the state of the parent Canvas is changed.
Protected Attributes
float m_Spacing = 0
bool m_ChildForceExpandWidth = true
bool m_ChildForceExpandHeight = true
bool m_ChildControlWidth = true
bool m_ChildControlHeight = true
bool m_ChildScaleWidth = false
bool m_ChildScaleHeight = false
bool m_ReverseArrangement = false
Protected Attributes inherited from UnityEngine.UI.LayoutGroup
RectOffset m_Padding = new RectOffset()
TextAnchor m_ChildAlignment = TextAnchor.UpperLeft
DrivenRectTransformTracker m_Tracker
Properties
float spacing [get, set]
The spacing to use between layout elements in the layout group.
bool childForceExpandWidth [get, set]
Whether to force the children to expand to fill additional available horizontal space.
bool childForceExpandHeight [get, set]
Whether to force the children to expand to fill additional available vertical space.
bool childControlWidth [get, set]
Returns true if the Layout Group controls the widths of its children. Returns false if children control their own widths.
bool childControlHeight [get, set]
Returns true if the Layout Group controls the heights of its children. Returns false if children control their own heights.
bool childScaleWidth [get, set]
Whether to use the x scale of each child when calculating its width.
bool childScaleHeight [get, set]
Whether to use the y scale of each child when calculating its height.
bool reverseArrangement [get, set]
Whether the order of children objects should be sorted in reverse.
Properties inherited from UnityEngine.UI.LayoutGroup
RectOffset padding [get, set]
The padding to add around the child layout elements.
TextAnchor childAlignment [get, set]
The alignment to use for the child layout elements in the layout group.
RectTransform rectTransform [get]
List< RectTransform > rectChildren [get]
virtual float minWidth [get]
See LayoutElement.minWidth.
virtual float preferredWidth [get]
See LayoutElement.preferredWidth.
virtual float flexibleWidth [get]
See LayoutElement.flexibleWidth.
virtual float minHeight [get]
See LayoutElement.minHeight.
virtual float preferredHeight [get]
See LayoutElement.preferredHeight.
virtual float flexibleHeight [get]
See LayoutElement.flexibleHeight.
virtual int layoutPriority [get]
See LayoutElement.layoutPriority.
Properties inherited from UnityEngine.UI.ILayoutElement
Additional Inherited Members
Public Member Functions inherited from UnityEngine.UI.LayoutGroup
virtual void CalculateLayoutInputHorizontal ()
After this method is invoked, layout horizontal input properties should return up-to-date values. Children will already have up-to-date layout horizontal inputs when this methods is called.
void CalculateLayoutInputVertical ()
After this method is invoked, layout vertical input properties should return up-to-date values. Children will already have up-to-date layout vertical inputs when this methods is called.
void SetLayoutHorizontal ()
Callback invoked by the auto layout system which handles horizontal aspects of the layout.
void SetLayoutVertical ()
Callback invoked by the auto layout system which handles vertical aspects of the layout.
Public Member Functions inherited from UnityEngine.EventSystems.UIBehaviour
virtual bool IsActive ()
Returns true if the GameObject and the Component are active.
bool IsDestroyed ()
Returns true if the native representation of the behaviour has been destroyed.
Detailed Description
Abstract base class for HorizontalLayoutGroup and VerticalLayoutGroup to generalize common functionality.
Member Function Documentation
CalcAlongAxis()
void UnityEngine.UI.HorizontalOrVerticalLayoutGroup.CalcAlongAxis (int axis, bool isVertical) protected
Calculate the layout element properties for this layout element along the given axis.
Parameters
axis The axis to calculate for. 0 is horizontal and 1 is vertical.
isVertical Is this group a vertical group?
Referenced by UnityEngine.UI.HorizontalLayoutGroup.CalculateLayoutInputHorizontal(), UnityEngine.UI.VerticalLayoutGroup.CalculateLayoutInputHorizontal(), UnityEngine.UI.HorizontalLayoutGroup.CalculateLayoutInputVertical(), and UnityEngine.UI.VerticalLayoutGroup.CalculateLayoutInputVertical().
SetChildrenAlongAxis()
void UnityEngine.UI.HorizontalOrVerticalLayoutGroup.SetChildrenAlongAxis (int axis, bool isVertical) protected
Set the positions and sizes of the child layout elements for the given axis.
Parameters
axis The axis to handle. 0 is horizontal and 1 is vertical.
isVertical Is this group a vertical group?
Referenced by UnityEngine.UI.HorizontalLayoutGroup.SetLayoutHorizontal(), UnityEngine.UI.VerticalLayoutGroup.SetLayoutHorizontal(), UnityEngine.UI.HorizontalLayoutGroup.SetLayoutVertical(), and UnityEngine.UI.VerticalLayoutGroup.SetLayoutVertical().
Member Data Documentation
m_ChildControlHeight
bool UnityEngine.UI.HorizontalOrVerticalLayoutGroup.m_ChildControlHeight = true protected
Referenced by UnityEngine.UI.HorizontalOrVerticalLayoutGroup.CalcAlongAxis(), and UnityEngine.UI.HorizontalOrVerticalLayoutGroup.SetChildrenAlongAxis().
m_ChildControlWidth
bool UnityEngine.UI.HorizontalOrVerticalLayoutGroup.m_ChildControlWidth = true protected
Referenced by UnityEngine.UI.HorizontalOrVerticalLayoutGroup.CalcAlongAxis(), and UnityEngine.UI.HorizontalOrVerticalLayoutGroup.SetChildrenAlongAxis().
m_ChildForceExpandHeight
bool UnityEngine.UI.HorizontalOrVerticalLayoutGroup.m_ChildForceExpandHeight = true protected
Referenced by UnityEngine.UI.HorizontalOrVerticalLayoutGroup.CalcAlongAxis(), and UnityEngine.UI.HorizontalOrVerticalLayoutGroup.SetChildrenAlongAxis().
m_ChildForceExpandWidth
bool UnityEngine.UI.HorizontalOrVerticalLayoutGroup.m_ChildForceExpandWidth = true protected
Referenced by UnityEngine.UI.HorizontalOrVerticalLayoutGroup.CalcAlongAxis(), and UnityEngine.UI.HorizontalOrVerticalLayoutGroup.SetChildrenAlongAxis().
m_ChildScaleHeight
bool UnityEngine.UI.HorizontalOrVerticalLayoutGroup.m_ChildScaleHeight = false protected
Referenced by UnityEngine.UI.HorizontalOrVerticalLayoutGroup.CalcAlongAxis(), and UnityEngine.UI.HorizontalOrVerticalLayoutGroup.SetChildrenAlongAxis().
m_ChildScaleWidth
bool UnityEngine.UI.HorizontalOrVerticalLayoutGroup.m_ChildScaleWidth = false protected
Referenced by UnityEngine.UI.HorizontalOrVerticalLayoutGroup.CalcAlongAxis(), and UnityEngine.UI.HorizontalOrVerticalLayoutGroup.SetChildrenAlongAxis().
m_ReverseArrangement
bool UnityEngine.UI.HorizontalOrVerticalLayoutGroup.m_ReverseArrangement = false protected
Referenced by UnityEngine.UI.HorizontalOrVerticalLayoutGroup.SetChildrenAlongAxis().
m_Spacing
float UnityEngine.UI.HorizontalOrVerticalLayoutGroup.m_Spacing = 0 protected
Property Documentation
childControlHeight
bool UnityEngine.UI.HorizontalOrVerticalLayoutGroup.childControlHeight get set
Returns true if the Layout Group controls the heights of its children. Returns false if children control their own heights.
If set to false, the layout group will only affect the positions of the children while leaving the heights untouched. The heights of the children can be set via the respective RectTransforms in this case.
If set to true, the heights of the children are automatically driven by the layout group according to their respective minimum, preferred, and flexible heights. This is useful if the heights of the children should change depending on how much space is available.In this case the height of each child cannot be set manually in the RectTransform, but the minimum, preferred and flexible height for each child can be controlled by adding a LayoutElement component to it.
childControlWidth
bool UnityEngine.UI.HorizontalOrVerticalLayoutGroup.childControlWidth get set
Returns true if the Layout Group controls the widths of its children. Returns false if children control their own widths.
If set to false, the layout group will only affect the positions of the children while leaving the widths untouched. The widths of the children can be set via the respective RectTransforms in this case.
If set to true, the widths of the children are automatically driven by the layout group according to their respective minimum, preferred, and flexible widths. This is useful if the widths of the children should change depending on how much space is available.In this case the width of each child cannot be set manually in the RectTransform, but the minimum, preferred and flexible width for each child can be controlled by adding a LayoutElement component to it.
childForceExpandHeight
bool UnityEngine.UI.HorizontalOrVerticalLayoutGroup.childForceExpandHeight get set
Whether to force the children to expand to fill additional available vertical space.
childForceExpandWidth
bool UnityEngine.UI.HorizontalOrVerticalLayoutGroup.childForceExpandWidth get set
Whether to force the children to expand to fill additional available horizontal space.
childScaleHeight
bool UnityEngine.UI.HorizontalOrVerticalLayoutGroup.childScaleHeight get set
Whether to use the y scale of each child when calculating its height.
childScaleWidth
bool UnityEngine.UI.HorizontalOrVerticalLayoutGroup.childScaleWidth get set
Whether to use the x scale of each child when calculating its width.
reverseArrangement
bool UnityEngine.UI.HorizontalOrVerticalLayoutGroup.reverseArrangement get set
Whether the order of children objects should be sorted in reverse.
If False the first child object will be positioned first. If True the last child object will be positioned first.
spacing
float UnityEngine.UI.HorizontalOrVerticalLayoutGroup.spacing get set
The spacing to use between layout elements in the layout group.
Referenced by UnityEngine.UI.HorizontalOrVerticalLayoutGroup.CalcAlongAxis(), and UnityEngine.UI.HorizontalOrVerticalLayoutGroup.SetChildrenAlongAxis().
The documentation for this class was generated from the following file:
C:/Users/Lykos/Desktop/Projects/Capstone/VRGames/Library/PackageCache/com.unity.ugui@1.0.0/Runtime/UI/Core/Layout/HorizontalOrVerticalLayoutGroup.cs