VRGames: Oculus.Interaction.PoseDetection.TransformFeatureStateProvider Class Reference
Oculus.Interaction.PoseDetection.TransformFeatureStateProvider Class Reference
Interprets transform feature values from a TransformFeatureValueProvider and uses the given TransformFeatureStateThresholds to quantize these values into states. To avoid rapid fluctuations at the edges of two states, this classes uses the calculated feature states from the previous frame and the given state thresholds to apply a buffer between state transition edges.
Public Member Functions
void RegisterNewConfig (TransformConfig transformConfig)
void UnRegisterConfig (TransformConfig transformConfig)
bool IsHandDataValid ()
bool IsStateActive (TransformConfig config, TransformFeature feature, FeatureStateActiveMode mode, string stateId)
bool GetCurrentState (TransformConfig config, TransformFeature transformFeature, out string currentState)
float? GetFeatureValue (TransformConfig config, TransformFeature transformFeature)
Returns the current value of the feature. If the hand joints are not populated with valid data (for instance, due to a disconnected hand), the method will return null;.
void GetFeatureVectorAndWristPos (TransformConfig config, TransformFeature transformFeature, bool isHandVector, ref Vector3? featureVec, ref Vector3? wristPos)
void InjectAllTransformFeatureStateProvider (IHand hand, bool disableProactiveEvaluation)
void InjectHand (IHand hand)
void InjectDisableProactiveEvaluation (bool disabled)
void InjectOptionalTimeProvider (Func< float > timeProvider)
Protected Member Functions
virtual void Awake ()
virtual void Start ()
virtual void OnEnable ()
virtual void OnDisable ()
Protected Attributes
bool _started = false
Properties
IHand Hand [get]
ITrackingToWorldTransformer TrackingToWorldTransformer [get]
Detailed Description
Interprets transform feature values from a TransformFeatureValueProvider and uses the given TransformFeatureStateThresholds to quantize these values into states. To avoid rapid fluctuations at the edges of two states, this classes uses the calculated feature states from the previous frame and the given state thresholds to apply a buffer between state transition edges.
Member Function Documentation
Awake()
virtual void Oculus.Interaction.PoseDetection.TransformFeatureStateProvider.Awake () protected virtual
GetCurrentState()
bool Oculus.Interaction.PoseDetection.TransformFeatureStateProvider.GetCurrentState (TransformConfig config, TransformFeature transformFeature, out string currentState)
Referenced by Oculus.Interaction.PoseDetection.Debug.TransformFeatureDebugVisual.Update().
GetFeatureValue()
float? Oculus.Interaction.PoseDetection.TransformFeatureStateProvider.GetFeatureValue (TransformConfig config, TransformFeature transformFeature)
Returns the current value of the feature. If the hand joints are not populated with valid data (for instance, due to a disconnected hand), the method will return null;.
Referenced by Oculus.Interaction.PoseDetection.Debug.TransformFeatureDebugVisual.Update().
GetFeatureVectorAndWristPos()
void Oculus.Interaction.PoseDetection.TransformFeatureStateProvider.GetFeatureVectorAndWristPos (TransformConfig config, TransformFeature transformFeature, bool isHandVector, ref Vector3? featureVec, ref Vector3? wristPos)
InjectAllTransformFeatureStateProvider()
void Oculus.Interaction.PoseDetection.TransformFeatureStateProvider.InjectAllTransformFeatureStateProvider (IHand hand, bool disableProactiveEvaluation)
InjectDisableProactiveEvaluation()
void Oculus.Interaction.PoseDetection.TransformFeatureStateProvider.InjectDisableProactiveEvaluation (bool disabled)
InjectHand()
void Oculus.Interaction.PoseDetection.TransformFeatureStateProvider.InjectHand (IHand hand)
InjectOptionalTimeProvider()
void Oculus.Interaction.PoseDetection.TransformFeatureStateProvider.InjectOptionalTimeProvider (Func< float > timeProvider)
IsHandDataValid()
bool Oculus.Interaction.PoseDetection.TransformFeatureStateProvider.IsHandDataValid ()
Referenced by Oculus.Interaction.PoseDetection.TransformFeatureStateProvider.GetCurrentState(), Oculus.Interaction.PoseDetection.TransformFeatureStateProvider.GetFeatureValue(), and Oculus.Interaction.PoseDetection.TransformFeatureStateProvider.GetFeatureVectorAndWristPos().
IsStateActive()
bool Oculus.Interaction.PoseDetection.TransformFeatureStateProvider.IsStateActive (TransformConfig config, TransformFeature feature, FeatureStateActiveMode mode, string stateId)
Referenced by Oculus.Interaction.PoseDetection.Debug.TransformFeatureDebugVisual.Update().
OnDisable()
virtual void Oculus.Interaction.PoseDetection.TransformFeatureStateProvider.OnDisable () protected virtual
OnEnable()
virtual void Oculus.Interaction.PoseDetection.TransformFeatureStateProvider.OnEnable () protected virtual
RegisterNewConfig()
void Oculus.Interaction.PoseDetection.TransformFeatureStateProvider.RegisterNewConfig (TransformConfig transformConfig)
Start()
virtual void Oculus.Interaction.PoseDetection.TransformFeatureStateProvider.Start () protected virtual
UnRegisterConfig()
void Oculus.Interaction.PoseDetection.TransformFeatureStateProvider.UnRegisterConfig (TransformConfig transformConfig)
Member Data Documentation
_started
bool Oculus.Interaction.PoseDetection.TransformFeatureStateProvider._started = false protected
Referenced by Oculus.Interaction.PoseDetection.TransformFeatureStateProvider.OnDisable(), Oculus.Interaction.PoseDetection.TransformFeatureStateProvider.OnEnable(), and Oculus.Interaction.PoseDetection.TransformFeatureStateProvider.Start().
Property Documentation
Hand
IHand Oculus.Interaction.PoseDetection.TransformFeatureStateProvider.Hand get
TrackingToWorldTransformer
ITrackingToWorldTransformer Oculus.Interaction.PoseDetection.TransformFeatureStateProvider.TrackingToWorldTransformer get
Referenced by Oculus.Interaction.PoseDetection.TransformFeatureStateProvider.Start().
The documentation for this class was generated from the following file:
C:/Users/Lykos/Desktop/Projects/Capstone/VRGames/Assets/ThirdParty/Oculus/Interaction/Runtime/Scripts/PoseDetection/TransformFeatureStateProvider.cs