VRGames: UnityEditor.ProBuilder.ConfigurableWindow Class Reference
UnityEditor.ProBuilder.ConfigurableWindow Class Reference abstract
Public Member Functions
virtual void AddItemsToMenu (GenericMenu menu)
Static Public Member Functions
static new T GetWindow< T > (string title, bool focus=true)
static new T GetWindow< T > (bool utility, string title, bool focus)
Get or create an instance of EditorWindow. Note that utility may be overridden by user set preference.
Protected Member Functions
void DoContextMenu ()
Static Protected Member Functions
static bool IsUtilityWindow< T > (bool defaultIsUtility=false)
Properties
virtual bool defaultIsUtilityWindow [get]
Member Function Documentation
AddItemsToMenu()
virtual void UnityEditor.ProBuilder.ConfigurableWindow.AddItemsToMenu (GenericMenu menu) virtual
Reimplemented in UnityEditor.ProBuilder.UVEditor.
Referenced by UnityEditor.ProBuilder.ConfigurableWindow.DoContextMenu().
DoContextMenu()
void UnityEditor.ProBuilder.ConfigurableWindow.DoContextMenu () protected
GetWindow< T >() [1/2]
static new T UnityEditor.ProBuilder.ConfigurableWindow.GetWindow< T > (bool utility, string title, bool focus) static
Get or create an instance of EditorWindow. Note that utility may be overridden by user set preference.
Type Constraints
T : ConfigurableWindow
GetWindow< T >() [2/2]
static new T UnityEditor.ProBuilder.ConfigurableWindow.GetWindow< T > (string title, bool focus = true) static
Type Constraints
T : ConfigurableWindow
IsUtilityWindow< T >()
static bool UnityEditor.ProBuilder.ConfigurableWindow.IsUtilityWindow< T > (bool defaultIsUtility = false) static protected
Type Constraints
T : ConfigurableWindow
Referenced by UnityEditor.ProBuilder.ConfigurableWindow.GetWindow< T >(), and UnityEditor.ProBuilder.ConfigurableWindow.GetWindow< T >().
Property Documentation
defaultIsUtilityWindow
virtual bool UnityEditor.ProBuilder.ConfigurableWindow.defaultIsUtilityWindow get protected
The documentation for this class was generated from the following file:
C:/Users/Lykos/Desktop/Projects/Capstone/VRGames/Library/PackageCache/com.unity.probuilder@5.0.6/Editor/EditorCore/ConfigurableWindow.cs