VRGames: Oculus.Platform.CAPI Class Reference
Oculus.Platform.CAPI Class Reference
Classes
struct OculusInitParams
struct ovrKeyValuePair
struct ovrMatchmakingCriterion
struct ovrMatchmakingCustomQueryData
struct ovrNetSyncVec3
Public Member Functions
static bool ovr_UnityInitWrapper (string appId)
static void ovr_UnityInitGlobals (IntPtr loggingCB)
static ulong ovr_UnityInitWrapperAsynchronous (string appId)
static bool ovr_UnityInitWrapperStandalone (string accessToken, IntPtr loggingCB)
static ulong ovr_Platform_InitializeStandaloneOculus (ref OculusInitParams init)
static ulong ovr_PlatformInitializeWithAccessToken (UInt64 appId, string accessToken)
static bool ovr_UnityInitWrapperWindows (string appId, IntPtr loggingCB)
static ulong ovr_UnityInitWrapperWindowsAsynchronous (string appId, IntPtr loggingCB)
static bool ovr_SetDeveloperAccessToken (string accessToken)
static IntPtr ovr_PopMessage ()
static void ovr_FreeMessage (IntPtr message)
static IntPtr ovr_Voip_CreateEncoder ()
static void ovr_Voip_DestroyEncoder (IntPtr encoder)
static IntPtr ovr_Voip_CreateDecoder ()
static void ovr_Voip_DestroyDecoder (IntPtr decoder)
static void ovr_VoipDecoder_Decode (IntPtr obj, byte[] compressedData, ulong compressedSize)
static IntPtr ovr_Microphone_Create ()
static void ovr_Microphone_Destroy (IntPtr obj)
static void ovr_Voip_SetSystemVoipPassthrough (bool passthrough)
static void ovr_Voip_SetSystemVoipMicrophoneMuted (VoipMuteState muted)
static void ovr_UnityResetTestPlatform ()
static ulong ovr_HTTP_GetWithMessageType (string url, int messageType)
static void ovr_CrashApplication ()
delegate void FilterCallback ([MarshalAs(UnmanagedType.LPArray, SizeConst=VoipFilterBufferSize), In, Out] short[] pcmData, UIntPtr pcmDataLength, int frequency, int numChannels)
static void ovr_Voip_SetMicrophoneFilterCallback (FilterCallback cb)
static void ovr_Voip_SetMicrophoneFilterCallbackWithFixedSizeBuffer (FilterCallback cb, UIntPtr bufferSizeElements)
static void ovr_Log_NewEvent (IntPtr eventName, IntPtr[] values, UIntPtr length)
static IntPtr ovr_ApplicationLifecycle_GetLaunchDetails ()
static bool ovr_HTTP_Write (ulong transferId, byte[] bytes, UIntPtr length)
static void ovr_HTTP_WriteEOM (ulong transferId)
static UIntPtr ovr_NetSync_GetAmbisonicFloatPCM (long connection_id, float[] outputBuffer, UIntPtr outputBufferNumElements)
static UIntPtr ovr_NetSync_GetAmbisonicInt16PCM (long connection_id, Int16[] outputBuffer, UIntPtr outputBufferNumElements)
static UIntPtr ovr_NetSync_GetAmbisonicInterleavedFloatPCM (long connection_id, float[] outputBuffer, UIntPtr outputBufferNumElements)
static UIntPtr ovr_NetSync_GetAmbisonicInterleavedInt16PCM (long connection_id, Int16[] outputBuffer, UIntPtr outputBufferNumElements)
static bool ovr_NetSync_GetListenerPosition (long connection_id, UInt64 sessionId, ref ovrNetSyncVec3 position)
static UIntPtr ovr_NetSync_GetMonostreamFloatPCM (long connection_id, UInt64 sessionId, float[] outputBuffer, UIntPtr outputBufferNumElements)
static UIntPtr ovr_NetSync_GetMonostreamInt16PCM (long connection_id, UInt64 session_id, Int16[] outputBuffer, UIntPtr outputBufferNumElements)
static UIntPtr ovr_NetSync_GetPcmBufferMaxSamples ()
static bool ovr_NetSync_GetVoipAmplitude (long connection_id, UInt64 sessionId, ref float amplitude)
static void ovr_NetSync_SetListenerPosition (long connection_id, ref ovrNetSyncVec3 position)
static void ovr_Net_Accept (UInt64 peerID)
static bool ovr_Net_AcceptForCurrentRoom ()
static void ovr_Net_Close (UInt64 peerID)
static void ovr_Net_CloseForCurrentRoom ()
static void ovr_Net_Connect (UInt64 peerID)
static bool ovr_Net_IsConnected (UInt64 peerID)
static ulong ovr_Net_Ping (UInt64 peerID)
static IntPtr ovr_Net_ReadPacket ()
static bool ovr_Net_SendPacket (UInt64 userID, UIntPtr length, byte[] bytes, SendPolicy policy)
static bool ovr_Net_SendPacketToCurrentRoom (UIntPtr length, byte[] bytes, SendPolicy policy)
static int ovr_Party_PluginGetSharedMemHandle ()
static VoipMuteState ovr_Party_PluginGetVoipMicrophoneMuted ()
static bool ovr_Party_PluginGetVoipPassthrough ()
static SystemVoipStatus ovr_Party_PluginGetVoipStatus ()
static void ovr_Voip_Accept (UInt64 userID)
static VoipDtxState ovr_Voip_GetIsConnectionUsingDtx (UInt64 peerID)
static VoipBitrate ovr_Voip_GetLocalBitrate (UInt64 peerID)
static UIntPtr ovr_Voip_GetOutputBufferMaxSize ()
static UIntPtr ovr_Voip_GetPCM (UInt64 senderID, Int16[] outputBuffer, UIntPtr outputBufferNumElements)
static UIntPtr ovr_Voip_GetPCMFloat (UInt64 senderID, float[] outputBuffer, UIntPtr outputBufferNumElements)
static UIntPtr ovr_Voip_GetPCMSize (UInt64 senderID)
static UIntPtr ovr_Voip_GetPCMWithTimestamp (UInt64 senderID, Int16[] outputBuffer, UIntPtr outputBufferNumElements, UInt32[] timestamp)
static UIntPtr ovr_Voip_GetPCMWithTimestampFloat (UInt64 senderID, float[] outputBuffer, UIntPtr outputBufferNumElements, UInt32[] timestamp)
static VoipBitrate ovr_Voip_GetRemoteBitrate (UInt64 peerID)
static UInt32 ovr_Voip_GetSyncTimestamp (UInt64 userID)
static long ovr_Voip_GetSyncTimestampDifference (UInt32 lhs, UInt32 rhs)
static VoipMuteState ovr_Voip_GetSystemVoipMicrophoneMuted ()
static SystemVoipStatus ovr_Voip_GetSystemVoipStatus ()
static void ovr_Voip_SetMicrophoneMuted (VoipMuteState state)
static void ovr_Voip_SetNewConnectionOptions (IntPtr voipOptions)
static void ovr_Voip_SetOutputSampleRate (VoipSampleRate rate)
static void ovr_Voip_Start (UInt64 userID)
static void ovr_Voip_Stop (UInt64 userID)
static ulong ovr_AbuseReport_LaunchAdvancedReportFlow (UInt64 content_id, IntPtr abuse_report_options)
static ulong ovr_Achievements_GetAllDefinitions ()
static ulong ovr_Achievements_GetAllProgress ()
static ulong ovr_Achievements_GetDefinitionsByName (string[] names, int count)
static ulong ovr_Achievements_GetProgressByName (string[] names, int count)
static ulong ovr_Application_ExecuteCoordinatedLaunch (ulong appID, ulong roomID)
static ulong ovr_Application_GetInstalledApplications ()
static ulong ovr_Application_GetVersion ()
static ulong ovr_Application_LaunchOtherApp (UInt64 appID, IntPtr deeplink_options)
static ulong ovr_ApplicationLifecycle_GetRegisteredPIDs ()
static ulong ovr_ApplicationLifecycle_GetSessionKey ()
static ulong ovr_AssetFile_Delete (UInt64 assetFileID)
static ulong ovr_AssetFile_DeleteById (UInt64 assetFileID)
static ulong ovr_AssetFile_Download (UInt64 assetFileID)
static ulong ovr_AssetFile_DownloadById (UInt64 assetFileID)
static ulong ovr_AssetFile_DownloadCancel (UInt64 assetFileID)
static ulong ovr_AssetFile_DownloadCancelById (UInt64 assetFileID)
static ulong ovr_AssetFile_GetList ()
static ulong ovr_AssetFile_Status (UInt64 assetFileID)
static ulong ovr_AssetFile_StatusById (UInt64 assetFileID)
static ulong ovr_Cal_FinalizeApplication (UInt64 groupingObject, UInt64[] userIDs, int numUserIDs, UInt64 finalized_application_ID)
static ulong ovr_Cal_GetSuggestedApplications (UInt64 groupingObject, UInt64[] userIDs, int numUserIDs)
static ulong ovr_Cal_ProposeApplication (UInt64 groupingObject, UInt64[] userIDs, int numUserIDs, UInt64 proposed_application_ID)
static ulong ovr_Challenges_DeclineInvite (UInt64 challengeID)
static ulong ovr_Challenges_Delete (UInt64 challengeID)
static ulong ovr_Challenges_Get (UInt64 challengeID)
static ulong ovr_Challenges_GetEntries (UInt64 challengeID, int limit, LeaderboardFilterType filter, LeaderboardStartAt startAt)
static ulong ovr_Challenges_GetEntriesAfterRank (UInt64 challengeID, int limit, ulong afterRank)
static ulong ovr_Challenges_GetEntriesByIds (UInt64 challengeID, int limit, LeaderboardStartAt startAt, UInt64[] userIDs, uint userIDLength)
static ulong ovr_Challenges_GetList (IntPtr challengeOptions, int limit)
static ulong ovr_Challenges_GetNextChallenges (IntPtr handle)
static ulong ovr_Challenges_GetNextEntries (IntPtr handle)
static ulong ovr_Challenges_GetPreviousChallenges (IntPtr handle)
static ulong ovr_Challenges_GetPreviousEntries (IntPtr handle)
static ulong ovr_Challenges_Join (UInt64 challengeID)
static ulong ovr_Challenges_Leave (UInt64 challengeID)
static ulong ovr_Challenges_UpdateInfo (UInt64 challengeID, IntPtr challengeOptions)
static ulong ovr_CloudStorage2_GetUserDirectoryPath ()
static ulong ovr_Colocation_GetCurrentMapUuid ()
static ulong ovr_Entitlement_GetIsViewerEntitled ()
static ulong ovr_GroupPresence_Clear ()
static ulong ovr_GroupPresence_GetInvitableUsers (IntPtr options)
static ulong ovr_GroupPresence_GetSentInvites ()
static ulong ovr_GroupPresence_LaunchInvitePanel (IntPtr options)
static ulong ovr_GroupPresence_LaunchMultiplayerErrorDialog (IntPtr options)
static ulong ovr_GroupPresence_LaunchRosterPanel (IntPtr options)
static ulong ovr_GroupPresence_SendInvites (UInt64[] userIDs, uint userIDLength)
static ulong ovr_GroupPresence_Set (IntPtr groupPresenceOptions)
static ulong ovr_GroupPresence_SetIsJoinable (bool is_joinable)
static ulong ovr_IAP_GetProductsBySKU (string[] skus, int count)
static ulong ovr_IAP_GetViewerPurchases ()
static ulong ovr_IAP_GetViewerPurchasesDurableCache ()
static ulong ovr_LanguagePack_GetCurrent ()
static ulong ovr_Leaderboard_GetNextEntries (IntPtr handle)
static ulong ovr_Leaderboard_GetPreviousEntries (IntPtr handle)
static ulong ovr_Livestreaming_StartPartyStream ()
static ulong ovr_Livestreaming_StartStream (LivestreamingAudience audience, LivestreamingMicrophoneStatus micStatus)
static ulong ovr_Livestreaming_StopPartyStream ()
static ulong ovr_Livestreaming_StopStream ()
static ulong ovr_Livestreaming_UpdateMicStatus (LivestreamingMicrophoneStatus micStatus)
static ulong ovr_Matchmaking_Cancel2 ()
static ulong ovr_Matchmaking_EnqueueRoom (UInt64 roomID, IntPtr customQueryData)
static ulong ovr_Matchmaking_EnqueueRoom2 (UInt64 roomID, IntPtr matchmakingOptions)
static ulong ovr_Matchmaking_GetAdminSnapshot ()
static ulong ovr_Matchmaking_JoinRoom (UInt64 roomID, bool subscribeToUpdates)
static ulong ovr_Matchmaking_StartMatch (UInt64 roomID)
static ulong ovr_NetSync_Connect (IntPtr connect_options)
static ulong ovr_NetSync_Disconnect (long connection_id)
static ulong ovr_NetSync_GetSessions (long connection_id)
static ulong ovr_NetSync_GetVoipAttenuation (long connection_id)
static ulong ovr_NetSync_GetVoipAttenuationDefault ()
static ulong ovr_NetSync_SetVoipAttenuation (long connection_id, float[] distances, float[] decibels, UIntPtr count)
static ulong ovr_NetSync_SetVoipListentoChannels (long connection_id, string[] listento_channels, UIntPtr count)
static ulong ovr_NetSync_SetVoipMicSource (long connection_id, NetSyncVoipMicSource mic_source)
static ulong ovr_NetSync_SetVoipSessionMuted (long connection_id, UInt64 session_id, bool muted)
static ulong ovr_NetSync_SetVoipSpeaktoChannels (long connection_id, string[] speakto_channels, UIntPtr count)
static ulong ovr_NetSync_SetVoipStreamMode (long connection_id, UInt64 sessionId, NetSyncVoipStreamMode streamMode)
static ulong ovr_Notification_GetRoomInvites ()
static ulong ovr_Notification_MarkAsRead (UInt64 notificationID)
static ulong ovr_Party_Create ()
static ulong ovr_Party_GatherInApplication (UInt64 partyID, UInt64 appID)
static ulong ovr_Party_Get (UInt64 partyID)
static ulong ovr_Party_GetCurrent ()
static ulong ovr_Party_GetCurrentForUser (UInt64 userID)
static ulong ovr_Party_Invite (UInt64 partyID, UInt64 userID)
static ulong ovr_Party_Join (UInt64 partyID)
static ulong ovr_Party_Leave (UInt64 partyID)
static ulong ovr_RichPresence_Clear ()
static ulong ovr_RichPresence_GetDestinations ()
static ulong ovr_RichPresence_Set (IntPtr richPresenceOptions)
static ulong ovr_RichPresence_SetIsJoinable (bool is_joinable)
static ulong ovr_Room_CreateAndJoinPrivate (RoomJoinPolicy joinPolicy, uint maxUsers, bool subscribeToUpdates)
static ulong ovr_Room_CreateAndJoinPrivate2 (RoomJoinPolicy joinPolicy, uint maxUsers, IntPtr roomOptions)
static ulong ovr_Room_Get (UInt64 roomID)
static ulong ovr_Room_GetCurrent ()
static ulong ovr_Room_GetCurrentForUser (UInt64 userID)
static ulong ovr_Room_GetInvitableUsers ()
static ulong ovr_Room_GetInvitableUsers2 (IntPtr roomOptions)
static ulong ovr_Room_GetModeratedRooms ()
static ulong ovr_Room_GetSocialRooms (UInt64 appID)
static ulong ovr_Room_Join (UInt64 roomID, bool subscribeToUpdates)
static ulong ovr_Room_Join2 (UInt64 roomID, IntPtr roomOptions)
static ulong ovr_Room_KickUser (UInt64 roomID, UInt64 userID, int kickDurationSeconds)
static ulong ovr_Room_LaunchInvitableUserFlow (UInt64 roomID)
static ulong ovr_Room_Leave (UInt64 roomID)
static ulong ovr_Room_UpdateMembershipLockStatus (UInt64 roomID, RoomMembershipLockStatus membershipLockStatus)
static ulong ovr_Room_UpdateOwner (UInt64 roomID, UInt64 userID)
static ulong ovr_Room_UpdatePrivateRoomJoinPolicy (UInt64 roomID, RoomJoinPolicy newJoinPolicy)
static ulong ovr_User_Get (UInt64 userID)
static ulong ovr_User_GetAccessToken ()
static ulong ovr_User_GetLinkedAccounts (IntPtr userOptions)
static ulong ovr_User_GetLoggedInUser ()
static ulong ovr_User_GetLoggedInUserFriends ()
static ulong ovr_User_GetLoggedInUserFriendsAndRooms ()
static ulong ovr_User_GetLoggedInUserRecentlyMetUsersAndRooms (IntPtr userOptions)
static ulong ovr_User_GetOrgScopedID (UInt64 userID)
static ulong ovr_User_GetSdkAccounts ()
static ulong ovr_User_GetUserCapabilities ()
static ulong ovr_User_GetUserProof ()
static ulong ovr_User_LaunchBlockFlow (UInt64 userID)
static ulong ovr_User_LaunchFriendRequestFlow (UInt64 userID)
static ulong ovr_User_LaunchReportFlow (UInt64 userID)
static ulong ovr_User_LaunchReportFlow2 (UInt64 optionalUserID, IntPtr abuseReportOptions)
static ulong ovr_User_LaunchUnblockFlow (UInt64 userID)
static ulong ovr_User_NewEntitledTestUser ()
static ulong ovr_User_NewTestUser ()
static ulong ovr_User_NewTestUserFriends ()
static ulong ovr_User_StartRecordingForReportFlow ()
static ulong ovr_UserDataStore_PrivateGetEntries (UInt64 userID)
static ulong ovr_UserDataStore_PublicGetEntries (UInt64 userID)
static ulong ovr_Voip_GetMicrophoneAvailability ()
static ulong ovr_Voip_SetSystemVoipSuppressed (bool suppressed)
static uint ovr_AchievementDefinition_GetBitfieldLength (IntPtr obj)
static ulong ovr_AchievementDefinition_GetTarget (IntPtr obj)
static AchievementType ovr_AchievementDefinition_GetType (IntPtr obj)
static IntPtr ovr_AchievementDefinitionArray_GetElement (IntPtr obj, UIntPtr index)
static UIntPtr ovr_AchievementDefinitionArray_GetSize (IntPtr obj)
static bool ovr_AchievementDefinitionArray_HasNextPage (IntPtr obj)
static ulong ovr_AchievementProgress_GetCount (IntPtr obj)
static bool ovr_AchievementProgress_GetIsUnlocked (IntPtr obj)
static IntPtr ovr_AchievementProgressArray_GetElement (IntPtr obj, UIntPtr index)
static UIntPtr ovr_AchievementProgressArray_GetSize (IntPtr obj)
static bool ovr_AchievementProgressArray_HasNextPage (IntPtr obj)
static bool ovr_AchievementUpdate_GetJustUnlocked (IntPtr obj)
static UInt64 ovr_Application_GetID (IntPtr obj)
static IntPtr ovr_ApplicationInvite_GetDestination (IntPtr obj)
static UInt64 ovr_ApplicationInvite_GetID (IntPtr obj)
static bool ovr_ApplicationInvite_GetIsActive (IntPtr obj)
static IntPtr ovr_ApplicationInvite_GetRecipient (IntPtr obj)
static IntPtr ovr_ApplicationInviteArray_GetElement (IntPtr obj, UIntPtr index)
static UIntPtr ovr_ApplicationInviteArray_GetSize (IntPtr obj)
static bool ovr_ApplicationInviteArray_HasNextPage (IntPtr obj)
static int ovr_ApplicationVersion_GetCurrentCode (IntPtr obj)
static int ovr_ApplicationVersion_GetLatestCode (IntPtr obj)
static UInt64 ovr_AssetDetails_GetAssetId (IntPtr obj)
static IntPtr ovr_AssetDetails_GetLanguage (IntPtr obj)
static IntPtr ovr_AssetDetailsArray_GetElement (IntPtr obj, UIntPtr index)
static UIntPtr ovr_AssetDetailsArray_GetSize (IntPtr obj)
static UInt64 ovr_AssetFileDeleteResult_GetAssetFileId (IntPtr obj)
static UInt64 ovr_AssetFileDeleteResult_GetAssetId (IntPtr obj)
static bool ovr_AssetFileDeleteResult_GetSuccess (IntPtr obj)
static UInt64 ovr_AssetFileDownloadCancelResult_GetAssetFileId (IntPtr obj)
static UInt64 ovr_AssetFileDownloadCancelResult_GetAssetId (IntPtr obj)
static bool ovr_AssetFileDownloadCancelResult_GetSuccess (IntPtr obj)
static UInt64 ovr_AssetFileDownloadResult_GetAssetId (IntPtr obj)
static UInt64 ovr_AssetFileDownloadUpdate_GetAssetFileId (IntPtr obj)
static UInt64 ovr_AssetFileDownloadUpdate_GetAssetId (IntPtr obj)
static uint ovr_AssetFileDownloadUpdate_GetBytesTotal (IntPtr obj)
static ulong ovr_AssetFileDownloadUpdate_GetBytesTotalLong (IntPtr obj)
static int ovr_AssetFileDownloadUpdate_GetBytesTransferred (IntPtr obj)
static long ovr_AssetFileDownloadUpdate_GetBytesTransferredLong (IntPtr obj)
static bool ovr_AssetFileDownloadUpdate_GetCompleted (IntPtr obj)
static int ovr_CalApplicationFinalized_GetCountdownMS (IntPtr obj)
static UInt64 ovr_CalApplicationFinalized_GetID (IntPtr obj)
static UInt64 ovr_CalApplicationProposed_GetID (IntPtr obj)
static UInt64 ovr_CalApplicationSuggestion_GetID (IntPtr obj)
static IntPtr ovr_CalApplicationSuggestionArray_GetElement (IntPtr obj, UIntPtr index)
static UIntPtr ovr_CalApplicationSuggestionArray_GetSize (IntPtr obj)
static ChallengeCreationType ovr_Challenge_GetCreationType (IntPtr obj)
static UInt64 ovr_Challenge_GetID (IntPtr obj)
static IntPtr ovr_Challenge_GetInvitedUsers (IntPtr obj)
static IntPtr ovr_Challenge_GetLeaderboard (IntPtr obj)
static IntPtr ovr_Challenge_GetParticipants (IntPtr obj)
static ChallengeVisibility ovr_Challenge_GetVisibility (IntPtr obj)
static IntPtr ovr_ChallengeArray_GetElement (IntPtr obj, UIntPtr index)
static UIntPtr ovr_ChallengeArray_GetSize (IntPtr obj)
static ulong ovr_ChallengeArray_GetTotalCount (IntPtr obj)
static bool ovr_ChallengeArray_HasNextPage (IntPtr obj)
static bool ovr_ChallengeArray_HasPreviousPage (IntPtr obj)
static uint ovr_ChallengeEntry_GetExtraDataLength (IntPtr obj)
static UInt64 ovr_ChallengeEntry_GetID (IntPtr obj)
static int ovr_ChallengeEntry_GetRank (IntPtr obj)
static long ovr_ChallengeEntry_GetScore (IntPtr obj)
static IntPtr ovr_ChallengeEntry_GetUser (IntPtr obj)
static IntPtr ovr_ChallengeEntryArray_GetElement (IntPtr obj, UIntPtr index)
static UIntPtr ovr_ChallengeEntryArray_GetSize (IntPtr obj)
static ulong ovr_ChallengeEntryArray_GetTotalCount (IntPtr obj)
static bool ovr_ChallengeEntryArray_HasNextPage (IntPtr obj)
static bool ovr_ChallengeEntryArray_HasPreviousPage (IntPtr obj)
static IntPtr ovr_CloudStorageConflictMetadata_GetLocal (IntPtr obj)
static IntPtr ovr_CloudStorageConflictMetadata_GetRemote (IntPtr obj)
static uint ovr_CloudStorageData_GetDataSize (IntPtr obj)
static long ovr_CloudStorageMetadata_GetCounter (IntPtr obj)
static uint ovr_CloudStorageMetadata_GetDataSize (IntPtr obj)
static ulong ovr_CloudStorageMetadata_GetSaveTime (IntPtr obj)
static CloudStorageDataStatus ovr_CloudStorageMetadata_GetStatus (IntPtr obj)
static IntPtr ovr_CloudStorageMetadataArray_GetElement (IntPtr obj, UIntPtr index)
static UIntPtr ovr_CloudStorageMetadataArray_GetSize (IntPtr obj)
static bool ovr_CloudStorageMetadataArray_HasNextPage (IntPtr obj)
static CloudStorageUpdateStatus ovr_CloudStorageUpdateResponse_GetStatus (IntPtr obj)
static UIntPtr ovr_DataStore_GetNumKeys (IntPtr obj)
static IntPtr ovr_DestinationArray_GetElement (IntPtr obj, UIntPtr index)
static UIntPtr ovr_DestinationArray_GetSize (IntPtr obj)
static bool ovr_DestinationArray_HasNextPage (IntPtr obj)
static int ovr_Error_GetCode (IntPtr obj)
static int ovr_Error_GetHttpCode (IntPtr obj)
static IntPtr ovr_HttpTransferUpdate_GetBytes (IntPtr obj)
static ulong ovr_HttpTransferUpdate_GetID (IntPtr obj)
static UIntPtr ovr_HttpTransferUpdate_GetSize (IntPtr obj)
static bool ovr_HttpTransferUpdate_IsCompleted (IntPtr obj)
static int ovr_InstalledApplication_GetVersionCode (IntPtr obj)
static IntPtr ovr_InstalledApplicationArray_GetElement (IntPtr obj, UIntPtr index)
static UIntPtr ovr_InstalledApplicationArray_GetSize (IntPtr obj)
static bool ovr_InvitePanelResultInfo_GetInvitesSent (IntPtr obj)
static bool ovr_LaunchBlockFlowResult_GetDidBlock (IntPtr obj)
static bool ovr_LaunchBlockFlowResult_GetDidCancel (IntPtr obj)
static LaunchType ovr_LaunchDetails_GetLaunchType (IntPtr obj)
static UInt64 ovr_LaunchDetails_GetRoomID (IntPtr obj)
static IntPtr ovr_LaunchDetails_GetUsers (IntPtr obj)
static bool ovr_LaunchFriendRequestFlowResult_GetDidCancel (IntPtr obj)
static bool ovr_LaunchFriendRequestFlowResult_GetDidSendRequest (IntPtr obj)
static IntPtr ovr_LaunchInvitePanelFlowResult_GetInvitedUsers (IntPtr obj)
static bool ovr_LaunchReportFlowResult_GetDidCancel (IntPtr obj)
static UInt64 ovr_LaunchReportFlowResult_GetUserReportId (IntPtr obj)
static bool ovr_LaunchUnblockFlowResult_GetDidCancel (IntPtr obj)
static bool ovr_LaunchUnblockFlowResult_GetDidUnblock (IntPtr obj)
static IntPtr ovr_Leaderboard_GetDestination (IntPtr obj)
static UInt64 ovr_Leaderboard_GetID (IntPtr obj)
static IntPtr ovr_LeaderboardArray_GetElement (IntPtr obj, UIntPtr index)
static UIntPtr ovr_LeaderboardArray_GetSize (IntPtr obj)
static bool ovr_LeaderboardArray_HasNextPage (IntPtr obj)
static uint ovr_LeaderboardEntry_GetExtraDataLength (IntPtr obj)
static UInt64 ovr_LeaderboardEntry_GetID (IntPtr obj)
static int ovr_LeaderboardEntry_GetRank (IntPtr obj)
static long ovr_LeaderboardEntry_GetScore (IntPtr obj)
static IntPtr ovr_LeaderboardEntry_GetSupplementaryMetric (IntPtr obj)
static IntPtr ovr_LeaderboardEntry_GetUser (IntPtr obj)
static IntPtr ovr_LeaderboardEntryArray_GetElement (IntPtr obj, UIntPtr index)
static UIntPtr ovr_LeaderboardEntryArray_GetSize (IntPtr obj)
static ulong ovr_LeaderboardEntryArray_GetTotalCount (IntPtr obj)
static bool ovr_LeaderboardEntryArray_HasNextPage (IntPtr obj)
static bool ovr_LeaderboardEntryArray_HasPreviousPage (IntPtr obj)
static bool ovr_LeaderboardUpdateStatus_GetDidUpdate (IntPtr obj)
static UInt64 ovr_LeaderboardUpdateStatus_GetUpdatedChallengeId (IntPtr obj, uint index)
static uint ovr_LeaderboardUpdateStatus_GetUpdatedChallengeIdsSize (IntPtr obj)
static ServiceProvider ovr_LinkedAccount_GetServiceProvider (IntPtr obj)
static IntPtr ovr_LinkedAccountArray_GetElement (IntPtr obj, UIntPtr index)
static UIntPtr ovr_LinkedAccountArray_GetSize (IntPtr obj)
static bool ovr_LivestreamingApplicationStatus_GetStreamingEnabled (IntPtr obj)
static LivestreamingStartStatus ovr_LivestreamingStartResult_GetStreamingResult (IntPtr obj)
static bool ovr_LivestreamingStatus_GetCommentsVisible (IntPtr obj)
static bool ovr_LivestreamingStatus_GetIsPaused (IntPtr obj)
static bool ovr_LivestreamingStatus_GetLivestreamingEnabled (IntPtr obj)
static int ovr_LivestreamingStatus_GetLivestreamingType (IntPtr obj)
static bool ovr_LivestreamingStatus_GetMicEnabled (IntPtr obj)
static int ovr_LivestreamingVideoStats_GetCommentCount (IntPtr obj)
static int ovr_LivestreamingVideoStats_GetReactionCount (IntPtr obj)
static IntPtr ovr_MatchmakingAdminSnapshot_GetCandidates (IntPtr obj)
static double ovr_MatchmakingAdminSnapshot_GetMyCurrentThreshold (IntPtr obj)
static bool ovr_MatchmakingAdminSnapshotCandidate_GetCanMatch (IntPtr obj)
static double ovr_MatchmakingAdminSnapshotCandidate_GetMyTotalScore (IntPtr obj)
static double ovr_MatchmakingAdminSnapshotCandidate_GetTheirCurrentThreshold (IntPtr obj)
static double ovr_MatchmakingAdminSnapshotCandidate_GetTheirTotalScore (IntPtr obj)
static IntPtr ovr_MatchmakingAdminSnapshotCandidateArray_GetElement (IntPtr obj, UIntPtr index)
static UIntPtr ovr_MatchmakingAdminSnapshotCandidateArray_GetSize (IntPtr obj)
static IntPtr ovr_MatchmakingBrowseResult_GetEnqueueResult (IntPtr obj)
static IntPtr ovr_MatchmakingBrowseResult_GetRooms (IntPtr obj)
static ulong ovr_MatchmakingCandidate_GetUserId (IntPtr obj)
static IntPtr ovr_MatchmakingCandidateArray_GetElement (IntPtr obj, UIntPtr index)
static UIntPtr ovr_MatchmakingCandidateArray_GetSize (IntPtr obj)
static bool ovr_MatchmakingCandidateArray_HasNextPage (IntPtr obj)
static IntPtr ovr_MatchmakingEnqueueResult_GetAdminSnapshot (IntPtr obj)
static uint ovr_MatchmakingEnqueueResult_GetAverageWait (IntPtr obj)
static uint ovr_MatchmakingEnqueueResult_GetMatchesInLastHourCount (IntPtr obj)
static uint ovr_MatchmakingEnqueueResult_GetMaxExpectedWait (IntPtr obj)
static uint ovr_MatchmakingEnqueueResult_GetRecentMatchPercentage (IntPtr obj)
static IntPtr ovr_MatchmakingEnqueueResultAndRoom_GetMatchmakingEnqueueResult (IntPtr obj)
static IntPtr ovr_MatchmakingEnqueueResultAndRoom_GetRoom (IntPtr obj)
static UInt64 ovr_MatchmakingEnqueuedUser_GetAdditionalUserID (IntPtr obj, uint index)
static uint ovr_MatchmakingEnqueuedUser_GetAdditionalUserIDsSize (IntPtr obj)
static IntPtr ovr_MatchmakingEnqueuedUser_GetCustomData (IntPtr obj)
static IntPtr ovr_MatchmakingEnqueuedUser_GetUser (IntPtr obj)
static IntPtr ovr_MatchmakingEnqueuedUserArray_GetElement (IntPtr obj, UIntPtr index)
static UIntPtr ovr_MatchmakingEnqueuedUserArray_GetSize (IntPtr obj)
static ulong ovr_MatchmakingNotification_GetAddedByUserId (IntPtr obj)
static IntPtr ovr_MatchmakingNotification_GetRoom (IntPtr obj)
static uint ovr_MatchmakingRoom_GetPingTime (IntPtr obj)
static IntPtr ovr_MatchmakingRoom_GetRoom (IntPtr obj)
static bool ovr_MatchmakingRoom_HasPingTime (IntPtr obj)
static IntPtr ovr_MatchmakingRoomArray_GetElement (IntPtr obj, UIntPtr index)
static UIntPtr ovr_MatchmakingRoomArray_GetSize (IntPtr obj)
static uint ovr_MatchmakingStats_GetDrawCount (IntPtr obj)
static uint ovr_MatchmakingStats_GetLossCount (IntPtr obj)
static uint ovr_MatchmakingStats_GetSkillLevel (IntPtr obj)
static double ovr_MatchmakingStats_GetSkillMean (IntPtr obj)
static double ovr_MatchmakingStats_GetSkillStandardDeviation (IntPtr obj)
static uint ovr_MatchmakingStats_GetWinCount (IntPtr obj)
static IntPtr ovr_Message_GetAbuseReportRecording (IntPtr obj)
static IntPtr ovr_Message_GetAchievementDefinitionArray (IntPtr obj)
static IntPtr ovr_Message_GetAchievementProgressArray (IntPtr obj)
static IntPtr ovr_Message_GetAchievementUpdate (IntPtr obj)
static IntPtr ovr_Message_GetApplicationInviteArray (IntPtr obj)
static IntPtr ovr_Message_GetApplicationVersion (IntPtr obj)
static IntPtr ovr_Message_GetAssetDetails (IntPtr obj)
static IntPtr ovr_Message_GetAssetDetailsArray (IntPtr obj)
static IntPtr ovr_Message_GetAssetFileDeleteResult (IntPtr obj)
static IntPtr ovr_Message_GetAssetFileDownloadCancelResult (IntPtr obj)
static IntPtr ovr_Message_GetAssetFileDownloadResult (IntPtr obj)
static IntPtr ovr_Message_GetAssetFileDownloadUpdate (IntPtr obj)
static IntPtr ovr_Message_GetCalApplicationFinalized (IntPtr obj)
static IntPtr ovr_Message_GetCalApplicationProposed (IntPtr obj)
static IntPtr ovr_Message_GetCalApplicationSuggestionArray (IntPtr obj)
static IntPtr ovr_Message_GetChallenge (IntPtr obj)
static IntPtr ovr_Message_GetChallengeArray (IntPtr obj)
static IntPtr ovr_Message_GetChallengeEntryArray (IntPtr obj)
static IntPtr ovr_Message_GetCloudStorageConflictMetadata (IntPtr obj)
static IntPtr ovr_Message_GetCloudStorageData (IntPtr obj)
static IntPtr ovr_Message_GetCloudStorageMetadata (IntPtr obj)
static IntPtr ovr_Message_GetCloudStorageMetadataArray (IntPtr obj)
static IntPtr ovr_Message_GetCloudStorageUpdateResponse (IntPtr obj)
static IntPtr ovr_Message_GetDataStore (IntPtr obj)
static IntPtr ovr_Message_GetDestinationArray (IntPtr obj)
static IntPtr ovr_Message_GetError (IntPtr obj)
static IntPtr ovr_Message_GetGroupPresenceJoinIntent (IntPtr obj)
static IntPtr ovr_Message_GetGroupPresenceLeaveIntent (IntPtr obj)
static IntPtr ovr_Message_GetHttpTransferUpdate (IntPtr obj)
static IntPtr ovr_Message_GetInstalledApplicationArray (IntPtr obj)
static IntPtr ovr_Message_GetInvitePanelResultInfo (IntPtr obj)
static IntPtr ovr_Message_GetLaunchBlockFlowResult (IntPtr obj)
static IntPtr ovr_Message_GetLaunchFriendRequestFlowResult (IntPtr obj)
static IntPtr ovr_Message_GetLaunchInvitePanelFlowResult (IntPtr obj)
static IntPtr ovr_Message_GetLaunchReportFlowResult (IntPtr obj)
static IntPtr ovr_Message_GetLaunchUnblockFlowResult (IntPtr obj)
static IntPtr ovr_Message_GetLeaderboardArray (IntPtr obj)
static IntPtr ovr_Message_GetLeaderboardEntryArray (IntPtr obj)
static IntPtr ovr_Message_GetLeaderboardUpdateStatus (IntPtr obj)
static IntPtr ovr_Message_GetLinkedAccountArray (IntPtr obj)
static IntPtr ovr_Message_GetLivestreamingApplicationStatus (IntPtr obj)
static IntPtr ovr_Message_GetLivestreamingStartResult (IntPtr obj)
static IntPtr ovr_Message_GetLivestreamingStatus (IntPtr obj)
static IntPtr ovr_Message_GetLivestreamingVideoStats (IntPtr obj)
static IntPtr ovr_Message_GetMatchmakingAdminSnapshot (IntPtr obj)
static IntPtr ovr_Message_GetMatchmakingBrowseResult (IntPtr obj)
static IntPtr ovr_Message_GetMatchmakingEnqueueResult (IntPtr obj)
static IntPtr ovr_Message_GetMatchmakingEnqueueResultAndRoom (IntPtr obj)
static IntPtr ovr_Message_GetMatchmakingRoomArray (IntPtr obj)
static IntPtr ovr_Message_GetMatchmakingStats (IntPtr obj)
static IntPtr ovr_Message_GetMicrophoneAvailabilityState (IntPtr obj)
static IntPtr ovr_Message_GetNativeMessage (IntPtr obj)
static IntPtr ovr_Message_GetNetSyncConnection (IntPtr obj)
static IntPtr ovr_Message_GetNetSyncSessionArray (IntPtr obj)
static IntPtr ovr_Message_GetNetSyncSessionsChangedNotification (IntPtr obj)
static IntPtr ovr_Message_GetNetSyncSetSessionPropertyResult (IntPtr obj)
static IntPtr ovr_Message_GetNetSyncVoipAttenuationValueArray (IntPtr obj)
static IntPtr ovr_Message_GetNetworkingPeer (IntPtr obj)
static IntPtr ovr_Message_GetOrgScopedID (IntPtr obj)
static IntPtr ovr_Message_GetParty (IntPtr obj)
static IntPtr ovr_Message_GetPartyID (IntPtr obj)
static IntPtr ovr_Message_GetPartyUpdateNotification (IntPtr obj)
static IntPtr ovr_Message_GetPidArray (IntPtr obj)
static IntPtr ovr_Message_GetPingResult (IntPtr obj)
static IntPtr ovr_Message_GetPlatformInitialize (IntPtr obj)
static IntPtr ovr_Message_GetProductArray (IntPtr obj)
static IntPtr ovr_Message_GetPurchase (IntPtr obj)
static IntPtr ovr_Message_GetPurchaseArray (IntPtr obj)
static IntPtr ovr_Message_GetRejoinDialogResult (IntPtr obj)
static ulong ovr_Message_GetRequestID (IntPtr obj)
static IntPtr ovr_Message_GetRoom (IntPtr obj)
static IntPtr ovr_Message_GetRoomArray (IntPtr obj)
static IntPtr ovr_Message_GetRoomInviteNotification (IntPtr obj)
static IntPtr ovr_Message_GetRoomInviteNotificationArray (IntPtr obj)
static IntPtr ovr_Message_GetSdkAccountArray (IntPtr obj)
static IntPtr ovr_Message_GetSendInvitesResult (IntPtr obj)
static IntPtr ovr_Message_GetShareMediaResult (IntPtr obj)
static IntPtr ovr_Message_GetSystemVoipState (IntPtr obj)
static Message.MessageType ovr_Message_GetType (IntPtr obj)
static IntPtr ovr_Message_GetUser (IntPtr obj)
static IntPtr ovr_Message_GetUserAndRoomArray (IntPtr obj)
static IntPtr ovr_Message_GetUserArray (IntPtr obj)
static IntPtr ovr_Message_GetUserCapabilityArray (IntPtr obj)
static IntPtr ovr_Message_GetUserDataStoreUpdateResponse (IntPtr obj)
static IntPtr ovr_Message_GetUserProof (IntPtr obj)
static IntPtr ovr_Message_GetUserReportID (IntPtr obj)
static bool ovr_Message_IsError (IntPtr obj)
static UIntPtr ovr_Microphone_GetNumSamplesAvailable (IntPtr obj)
static UIntPtr ovr_Microphone_GetOutputBufferMaxSize (IntPtr obj)
static UIntPtr ovr_Microphone_GetPCM (IntPtr obj, Int16[] outputBuffer, UIntPtr outputBufferNumElements)
static UIntPtr ovr_Microphone_GetPCMFloat (IntPtr obj, float[] outputBuffer, UIntPtr outputBufferNumElements)
static UIntPtr ovr_Microphone_ReadData (IntPtr obj, float[] outputBuffer, UIntPtr outputBufferSize)
static void ovr_Microphone_SetAcceptableRecordingDelayHint (IntPtr obj, UIntPtr delayMs)
static void ovr_Microphone_Start (IntPtr obj)
static void ovr_Microphone_Stop (IntPtr obj)
static bool ovr_MicrophoneAvailabilityState_GetMicrophoneAvailable (IntPtr obj)
static long ovr_NetSyncConnection_GetConnectionId (IntPtr obj)
static NetSyncDisconnectReason ovr_NetSyncConnection_GetDisconnectReason (IntPtr obj)
static UInt64 ovr_NetSyncConnection_GetSessionId (IntPtr obj)
static NetSyncConnectionStatus ovr_NetSyncConnection_GetStatus (IntPtr obj)
static long ovr_NetSyncSession_GetConnectionId (IntPtr obj)
static bool ovr_NetSyncSession_GetMuted (IntPtr obj)
static UInt64 ovr_NetSyncSession_GetSessionId (IntPtr obj)
static UInt64 ovr_NetSyncSession_GetUserId (IntPtr obj)
static IntPtr ovr_NetSyncSessionArray_GetElement (IntPtr obj, UIntPtr index)
static UIntPtr ovr_NetSyncSessionArray_GetSize (IntPtr obj)
static long ovr_NetSyncSessionsChangedNotification_GetConnectionId (IntPtr obj)
static IntPtr ovr_NetSyncSessionsChangedNotification_GetSessions (IntPtr obj)
static IntPtr ovr_NetSyncSetSessionPropertyResult_GetSession (IntPtr obj)
static float ovr_NetSyncVoipAttenuationValue_GetDecibels (IntPtr obj)
static float ovr_NetSyncVoipAttenuationValue_GetDistance (IntPtr obj)
static IntPtr ovr_NetSyncVoipAttenuationValueArray_GetElement (IntPtr obj, UIntPtr index)
static UIntPtr ovr_NetSyncVoipAttenuationValueArray_GetSize (IntPtr obj)
static UInt64 ovr_NetworkingPeer_GetID (IntPtr obj)
static PeerConnectionState ovr_NetworkingPeer_GetState (IntPtr obj)
static UInt64 ovr_OrgScopedID_GetID (IntPtr obj)
static void ovr_Packet_Free (IntPtr obj)
static IntPtr ovr_Packet_GetBytes (IntPtr obj)
static SendPolicy ovr_Packet_GetSendPolicy (IntPtr obj)
static UInt64 ovr_Packet_GetSenderID (IntPtr obj)
static UIntPtr ovr_Packet_GetSize (IntPtr obj)
static UInt64 ovr_Party_GetID (IntPtr obj)
static IntPtr ovr_Party_GetInvitedUsers (IntPtr obj)
static IntPtr ovr_Party_GetLeader (IntPtr obj)
static IntPtr ovr_Party_GetRoom (IntPtr obj)
static IntPtr ovr_Party_GetUsers (IntPtr obj)
static UInt64 ovr_PartyID_GetID (IntPtr obj)
static PartyUpdateAction ovr_PartyUpdateNotification_GetAction (IntPtr obj)
static UInt64 ovr_PartyUpdateNotification_GetPartyId (IntPtr obj)
static UInt64 ovr_PartyUpdateNotification_GetSenderId (IntPtr obj)
static UInt64 ovr_PartyUpdateNotification_GetUserId (IntPtr obj)
static IntPtr ovr_PidArray_GetElement (IntPtr obj, UIntPtr index)
static UIntPtr ovr_PidArray_GetSize (IntPtr obj)
static UInt64 ovr_PingResult_GetID (IntPtr obj)
static ulong ovr_PingResult_GetPingTimeUsec (IntPtr obj)
static bool ovr_PingResult_IsTimeout (IntPtr obj)
static PlatformInitializeResult ovr_PlatformInitialize_GetResult (IntPtr obj)
static uint ovr_Price_GetAmountInHundredths (IntPtr obj)
static IntPtr ovr_ProductArray_GetElement (IntPtr obj, UIntPtr index)
static UIntPtr ovr_ProductArray_GetSize (IntPtr obj)
static bool ovr_ProductArray_HasNextPage (IntPtr obj)
static UInt64 ovr_Purchase_GetPurchaseID (IntPtr obj)
static IntPtr ovr_PurchaseArray_GetElement (IntPtr obj, UIntPtr index)
static UIntPtr ovr_PurchaseArray_GetSize (IntPtr obj)
static bool ovr_PurchaseArray_HasNextPage (IntPtr obj)
static bool ovr_RejoinDialogResult_GetRejoinSelected (IntPtr obj)
static UInt64 ovr_Room_GetApplicationID (IntPtr obj)
static IntPtr ovr_Room_GetDataStore (IntPtr obj)
static UInt64 ovr_Room_GetID (IntPtr obj)
static IntPtr ovr_Room_GetInvitedUsers (IntPtr obj)
static bool ovr_Room_GetIsMembershipLocked (IntPtr obj)
static RoomJoinPolicy ovr_Room_GetJoinPolicy (IntPtr obj)
static RoomJoinability ovr_Room_GetJoinability (IntPtr obj)
static IntPtr ovr_Room_GetMatchedUsers (IntPtr obj)
static uint ovr_Room_GetMaxUsers (IntPtr obj)
static IntPtr ovr_Room_GetOwner (IntPtr obj)
static IntPtr ovr_Room_GetTeams (IntPtr obj)
static RoomType ovr_Room_GetType (IntPtr obj)
static IntPtr ovr_Room_GetUsers (IntPtr obj)
static uint ovr_Room_GetVersion (IntPtr obj)
static IntPtr ovr_RoomArray_GetElement (IntPtr obj, UIntPtr index)
static UIntPtr ovr_RoomArray_GetSize (IntPtr obj)
static bool ovr_RoomArray_HasNextPage (IntPtr obj)
static UInt64 ovr_RoomInviteNotification_GetID (IntPtr obj)
static UInt64 ovr_RoomInviteNotification_GetRoomID (IntPtr obj)
static UInt64 ovr_RoomInviteNotification_GetSenderID (IntPtr obj)
static IntPtr ovr_RoomInviteNotificationArray_GetElement (IntPtr obj, UIntPtr index)
static UIntPtr ovr_RoomInviteNotificationArray_GetSize (IntPtr obj)
static bool ovr_RoomInviteNotificationArray_HasNextPage (IntPtr obj)
static SdkAccountType ovr_SdkAccount_GetAccountType (IntPtr obj)
static UInt64 ovr_SdkAccount_GetUserId (IntPtr obj)
static IntPtr ovr_SdkAccountArray_GetElement (IntPtr obj, UIntPtr index)
static UIntPtr ovr_SdkAccountArray_GetSize (IntPtr obj)
static IntPtr ovr_SendInvitesResult_GetInvites (IntPtr obj)
static ShareMediaStatus ovr_ShareMediaResult_GetStatus (IntPtr obj)
static UInt64 ovr_SupplementaryMetric_GetID (IntPtr obj)
static long ovr_SupplementaryMetric_GetMetric (IntPtr obj)
static VoipMuteState ovr_SystemVoipState_GetMicrophoneMuted (IntPtr obj)
static SystemVoipStatus ovr_SystemVoipState_GetStatus (IntPtr obj)
static IntPtr ovr_Team_GetAssignedUsers (IntPtr obj)
static int ovr_Team_GetMaxUsers (IntPtr obj)
static int ovr_Team_GetMinUsers (IntPtr obj)
static IntPtr ovr_TeamArray_GetElement (IntPtr obj, UIntPtr index)
static UIntPtr ovr_TeamArray_GetSize (IntPtr obj)
static IntPtr ovr_TestUser_GetAppAccessArray (IntPtr obj)
static IntPtr ovr_TestUser_GetFbAppAccessArray (IntPtr obj)
static IntPtr ovr_TestUser_GetFriendAppAccessArray (IntPtr obj)
static UInt64 ovr_TestUser_GetUserFbid (IntPtr obj)
static UInt64 ovr_TestUser_GetUserId (IntPtr obj)
static UInt64 ovr_TestUserAppAccess_GetAppId (IntPtr obj)
static UInt64 ovr_TestUserAppAccess_GetUserId (IntPtr obj)
static IntPtr ovr_TestUserAppAccessArray_GetElement (IntPtr obj, UIntPtr index)
static UIntPtr ovr_TestUserAppAccessArray_GetSize (IntPtr obj)
static UInt64 ovr_User_GetID (IntPtr obj)
static UserPresenceStatus ovr_User_GetPresenceStatus (IntPtr obj)
static IntPtr ovr_UserAndRoom_GetRoom (IntPtr obj)
static IntPtr ovr_UserAndRoom_GetUser (IntPtr obj)
static IntPtr ovr_UserAndRoomArray_GetElement (IntPtr obj, UIntPtr index)
static UIntPtr ovr_UserAndRoomArray_GetSize (IntPtr obj)
static bool ovr_UserAndRoomArray_HasNextPage (IntPtr obj)
static IntPtr ovr_UserArray_GetElement (IntPtr obj, UIntPtr index)
static UIntPtr ovr_UserArray_GetSize (IntPtr obj)
static bool ovr_UserArray_HasNextPage (IntPtr obj)
static bool ovr_UserCapability_GetIsEnabled (IntPtr obj)
static IntPtr ovr_UserCapabilityArray_GetElement (IntPtr obj, UIntPtr index)
static UIntPtr ovr_UserCapabilityArray_GetSize (IntPtr obj)
static bool ovr_UserCapabilityArray_HasNextPage (IntPtr obj)
static bool ovr_UserDataStoreUpdateResponse_GetSuccess (IntPtr obj)
static bool ovr_UserReportID_GetDidCancel (IntPtr obj)
static UInt64 ovr_UserReportID_GetID (IntPtr obj)
static void ovr_VoipDecoder_Decode (IntPtr obj, byte[] compressedData, UIntPtr compressedSize)
static UIntPtr ovr_VoipDecoder_GetDecodedPCM (IntPtr obj, float[] outputBuffer, UIntPtr outputBufferSize)
static void ovr_VoipEncoder_AddPCM (IntPtr obj, float[] inputData, uint inputSize)
static UIntPtr ovr_VoipEncoder_GetCompressedData (IntPtr obj, byte[] outputBuffer, UIntPtr intputSize)
static UIntPtr ovr_VoipEncoder_GetCompressedDataSize (IntPtr obj)
static IntPtr ovr_AbuseReportOptions_Create ()
static void ovr_AbuseReportOptions_Destroy (IntPtr handle)
static void ovr_AbuseReportOptions_SetPreventPeopleChooser (IntPtr handle, bool value)
static void ovr_AbuseReportOptions_SetReportType (IntPtr handle, AbuseReportType value)
static IntPtr ovr_AdvancedAbuseReportOptions_Create ()
static void ovr_AdvancedAbuseReportOptions_Destroy (IntPtr handle)
static void ovr_AdvancedAbuseReportOptions_SetReportType (IntPtr handle, AbuseReportType value)
static void ovr_AdvancedAbuseReportOptions_SetVideoMode (IntPtr handle, AbuseReportVideoMode value)
static IntPtr ovr_ApplicationOptions_Create ()
static void ovr_ApplicationOptions_Destroy (IntPtr handle)
static IntPtr ovr_ChallengeOptions_Create ()
static void ovr_ChallengeOptions_Destroy (IntPtr handle)
static void ovr_ChallengeOptions_SetIncludeActiveChallenges (IntPtr handle, bool value)
static void ovr_ChallengeOptions_SetIncludeFutureChallenges (IntPtr handle, bool value)
static void ovr_ChallengeOptions_SetIncludePastChallenges (IntPtr handle, bool value)
static void ovr_ChallengeOptions_SetViewerFilter (IntPtr handle, ChallengeViewerFilter value)
static void ovr_ChallengeOptions_SetVisibility (IntPtr handle, ChallengeVisibility value)
static IntPtr ovr_GroupPresenceOptions_Create ()
static void ovr_GroupPresenceOptions_Destroy (IntPtr handle)
static void ovr_GroupPresenceOptions_SetIsJoinable (IntPtr handle, bool value)
static IntPtr ovr_InviteOptions_Create ()
static void ovr_InviteOptions_Destroy (IntPtr handle)
static void ovr_InviteOptions_AddSuggestedUser (IntPtr handle, UInt64 value)
static void ovr_InviteOptions_ClearSuggestedUsers (IntPtr handle)
static IntPtr ovr_MatchmakingOptions_Create ()
static void ovr_MatchmakingOptions_Destroy (IntPtr handle)
static void ovr_MatchmakingOptions_ClearCreateRoomDataStore (IntPtr handle)
static void ovr_MatchmakingOptions_SetCreateRoomJoinPolicy (IntPtr handle, RoomJoinPolicy value)
static void ovr_MatchmakingOptions_SetCreateRoomMaxUsers (IntPtr handle, uint value)
static void ovr_MatchmakingOptions_AddEnqueueAdditionalUser (IntPtr handle, UInt64 value)
static void ovr_MatchmakingOptions_ClearEnqueueAdditionalUsers (IntPtr handle)
static void ovr_MatchmakingOptions_ClearEnqueueDataSettings (IntPtr handle)
static void ovr_MatchmakingOptions_SetEnqueueIsDebug (IntPtr handle, bool value)
static IntPtr ovr_MultiplayerErrorOptions_Create ()
static void ovr_MultiplayerErrorOptions_Destroy (IntPtr handle)
static void ovr_MultiplayerErrorOptions_SetErrorKey (IntPtr handle, MultiplayerErrorErrorKey value)
static IntPtr ovr_NetSyncOptions_Create ()
static void ovr_NetSyncOptions_Destroy (IntPtr handle)
static void ovr_NetSyncOptions_SetVoipStreamDefault (IntPtr handle, NetSyncVoipStreamMode value)
static IntPtr ovr_RichPresenceOptions_Create ()
static void ovr_RichPresenceOptions_Destroy (IntPtr handle)
static void ovr_RichPresenceOptions_ClearArgs (IntPtr handle)
static void ovr_RichPresenceOptions_SetCurrentCapacity (IntPtr handle, uint value)
static void ovr_RichPresenceOptions_SetExtraContext (IntPtr handle, RichPresenceExtraContext value)
static void ovr_RichPresenceOptions_SetIsIdle (IntPtr handle, bool value)
static void ovr_RichPresenceOptions_SetIsJoinable (IntPtr handle, bool value)
static void ovr_RichPresenceOptions_SetMaxCapacity (IntPtr handle, uint value)
static IntPtr ovr_RoomOptions_Create ()
static void ovr_RoomOptions_Destroy (IntPtr handle)
static void ovr_RoomOptions_ClearDataStore (IntPtr handle)
static void ovr_RoomOptions_SetExcludeRecentlyMet (IntPtr handle, bool value)
static void ovr_RoomOptions_SetMaxUserResults (IntPtr handle, uint value)
static void ovr_RoomOptions_SetOrdering (IntPtr handle, UserOrdering value)
static void ovr_RoomOptions_SetRecentlyMetTimeWindow (IntPtr handle, TimeWindow value)
static void ovr_RoomOptions_SetRoomId (IntPtr handle, UInt64 value)
static void ovr_RoomOptions_SetTurnOffUpdates (IntPtr handle, bool value)
static IntPtr ovr_RosterOptions_Create ()
static void ovr_RosterOptions_Destroy (IntPtr handle)
static void ovr_RosterOptions_AddSuggestedUser (IntPtr handle, UInt64 value)
static void ovr_RosterOptions_ClearSuggestedUsers (IntPtr handle)
static IntPtr ovr_UserOptions_Create ()
static void ovr_UserOptions_Destroy (IntPtr handle)
static void ovr_UserOptions_SetMaxUsers (IntPtr handle, uint value)
static void ovr_UserOptions_AddServiceProvider (IntPtr handle, ServiceProvider value)
static void ovr_UserOptions_ClearServiceProviders (IntPtr handle)
static void ovr_UserOptions_SetTimeWindow (IntPtr handle, TimeWindow value)
static IntPtr ovr_VoipOptions_Create ()
static void ovr_VoipOptions_Destroy (IntPtr handle)
static void ovr_VoipOptions_SetBitrateForNewConnections (IntPtr handle, VoipBitrate value)
static void ovr_VoipOptions_SetCreateNewConnectionUseDtx (IntPtr handle, VoipDtxState value)
Static Public Member Functions
static IntPtr ArrayOfStructsToIntPtr (Array ar)
static CAPI.ovrKeyValuePair[] DictionaryToOVRKeyValuePairs (Dictionary< string, object > dict)
static byte[] IntPtrToByteArray (IntPtr data, ulong size)
static Dictionary< string, string > DataStoreFromNative (IntPtr pointer)
static string StringFromNative (IntPtr pointer)
static int GetNativeStringLengthNotIncludingNullTerminator (IntPtr pointer)
static DateTime DateTimeFromNative (ulong seconds_since_the_one_true_epoch)
static ulong DateTimeToNative (DateTime dt)
static byte[] BlobFromNative (uint size, IntPtr pointer)
static byte[] FiledataFromNative (uint size, IntPtr pointer)
static IntPtr StringToNative (string s)
static string ovr_GetLoggedInUserLocale ()
static void LogNewEvent (string eventName, Dictionary< string, string > values)
static void ovr_ApplicationLifecycle_LogDeeplinkResult (string trackingID, LaunchResult result)
static ulong ovr_HTTP_StartTransfer (string url, ovrKeyValuePair[] headers)
static string ovr_Message_GetStringForJavascript (IntPtr message)
static ulong ovr_Achievements_AddCount (string name, ulong count)
static ulong ovr_Achievements_AddFields (string name, string fields)
static ulong ovr_Achievements_Unlock (string name)
static ulong ovr_ApplicationLifecycle_RegisterSessionKey (string sessionKey)
static ulong ovr_AssetFile_DeleteByName (string assetFileName)
static ulong ovr_AssetFile_DownloadByName (string assetFileName)
static ulong ovr_AssetFile_DownloadCancelByName (string assetFileName)
static ulong ovr_AssetFile_StatusByName (string assetFileName)
static ulong ovr_Avatar_UpdateMetaData (string avatarMetaData, string imageFilePath)
static ulong ovr_Challenges_Create (string leaderboardName, IntPtr challengeOptions)
static ulong ovr_CloudStorage_Delete (string bucket, string key)
static ulong ovr_CloudStorage_Load (string bucket, string key)
static ulong ovr_CloudStorage_LoadBucketMetadata (string bucket)
static ulong ovr_CloudStorage_LoadConflictMetadata (string bucket, string key)
static ulong ovr_CloudStorage_LoadHandle (string handle)
static ulong ovr_CloudStorage_LoadMetadata (string bucket, string key)
static ulong ovr_CloudStorage_ResolveKeepLocal (string bucket, string key, string remoteHandle)
static ulong ovr_CloudStorage_ResolveKeepRemote (string bucket, string key, string remoteHandle)
static ulong ovr_CloudStorage_Save (string bucket, string key, byte[] data, uint dataSize, long counter, string extraData)
static ulong ovr_Colocation_RequestMap (string uuid)
static ulong ovr_Colocation_ShareMap (string uuid)
static ulong ovr_GraphAPI_Get (string url)
static ulong ovr_GraphAPI_Post (string url)
static ulong ovr_GroupPresence_LaunchRejoinDialog (string lobby_session_id, string match_session_id, string destination_api_name)
static ulong ovr_GroupPresence_SetDestination (string api_name)
static ulong ovr_GroupPresence_SetLobbySession (string id)
static ulong ovr_GroupPresence_SetMatchSession (string id)
static ulong ovr_HTTP_Get (string url)
static ulong ovr_HTTP_GetToFile (string url, string diskFile)
static ulong ovr_HTTP_MultiPartPost (string url, string filepath_param_name, string filepath, string access_token, ovrKeyValuePair[] post_params)
static ulong ovr_HTTP_Post (string url)
static ulong ovr_IAP_ConsumePurchase (string sku)
static ulong ovr_IAP_LaunchCheckoutFlow (string sku)
static ulong ovr_LanguagePack_SetCurrent (string tag)
static ulong ovr_Leaderboard_Get (string leaderboardName)
static ulong ovr_Leaderboard_GetEntries (string leaderboardName, int limit, LeaderboardFilterType filter, LeaderboardStartAt startAt)
static ulong ovr_Leaderboard_GetEntriesAfterRank (string leaderboardName, int limit, ulong afterRank)
static ulong ovr_Leaderboard_GetEntriesByIds (string leaderboardName, int limit, LeaderboardStartAt startAt, UInt64[] userIDs, uint userIDLength)
static ulong ovr_Leaderboard_WriteEntry (string leaderboardName, long score, byte[] extraData, uint extraDataLength, bool forceUpdate)
static ulong ovr_Leaderboard_WriteEntryWithSupplementaryMetric (string leaderboardName, long score, long supplementaryMetric, byte[] extraData, uint extraDataLength, bool forceUpdate)
static ulong ovr_Livestreaming_IsAllowedForApplication (string packageName)
static ulong ovr_Matchmaking_Browse (string pool, IntPtr customQueryData)
static ulong ovr_Matchmaking_Browse2 (string pool, IntPtr matchmakingOptions)
static ulong ovr_Matchmaking_Cancel (string pool, string requestHash)
static ulong ovr_Matchmaking_CreateAndEnqueueRoom (string pool, uint maxUsers, bool subscribeToUpdates, IntPtr customQueryData)
static ulong ovr_Matchmaking_CreateAndEnqueueRoom2 (string pool, IntPtr matchmakingOptions)
static ulong ovr_Matchmaking_CreateRoom (string pool, uint maxUsers, bool subscribeToUpdates)
static ulong ovr_Matchmaking_CreateRoom2 (string pool, IntPtr matchmakingOptions)
static ulong ovr_Matchmaking_Enqueue (string pool, IntPtr customQueryData)
static ulong ovr_Matchmaking_Enqueue2 (string pool, IntPtr matchmakingOptions)
static ulong ovr_Matchmaking_GetStats (string pool, uint maxLevel, MatchmakingStatApproach approach)
static ulong ovr_Matchmaking_ReportResultInsecure (UInt64 roomID, ovrKeyValuePair[] data)
static ulong ovr_Media_ShareToFacebook (string postTextSuggestion, string filePath, MediaContentType contentType)
static ulong ovr_NetSync_SetVoipAttenuationModel (long connection_id, string name, float[] distances, float[] decibels, UIntPtr count)
static ulong ovr_NetSync_SetVoipChannelCfg (long connection_id, string channel_name, string attnmodel, bool disable_spatialization)
static ulong ovr_NetSync_SetVoipGroup (long connection_id, string group_id)
static ulong ovr_RichPresence_SetDestination (string api_name)
static ulong ovr_RichPresence_SetLobbySession (string id)
static ulong ovr_RichPresence_SetMatchSession (string id)
static ulong ovr_Room_InviteUser (UInt64 roomID, string inviteToken)
static ulong ovr_Room_SetDescription (UInt64 roomID, string description)
static ulong ovr_Room_UpdateDataStore (UInt64 roomID, ovrKeyValuePair[] data)
static ulong ovr_User_CancelRecordingForReportFlow (string recordingUUID)
static ulong ovr_User_StopRecordingAndLaunchReportFlow (UInt64 optionalUserID, string optionalRecordingUUID)
static ulong ovr_User_StopRecordingAndLaunchReportFlow2 (UInt64 optionalUserID, string optionalRecordingUUID, IntPtr abuseReportOptions)
static ulong ovr_User_TestUserCreateDeviceManifest (string deviceID, UInt64[] appIDs, int numAppIDs)
static ulong ovr_UserDataStore_PrivateDeleteEntryByKey (UInt64 userID, string key)
static ulong ovr_UserDataStore_PrivateGetEntryByKey (UInt64 userID, string key)
static ulong ovr_UserDataStore_PrivateWriteEntry (UInt64 userID, string key, string value)
static ulong ovr_UserDataStore_PublicDeleteEntryByKey (UInt64 userID, string key)
static ulong ovr_UserDataStore_PublicGetEntryByKey (UInt64 userID, string key)
static ulong ovr_UserDataStore_PublicWriteEntry (UInt64 userID, string key, string value)
static string ovr_AbuseReportRecording_GetRecordingUuid (IntPtr obj)
static string ovr_AchievementDefinition_GetName (IntPtr obj)
static string ovr_AchievementDefinitionArray_GetNextUrl (IntPtr obj)
static string ovr_AchievementProgress_GetBitfield (IntPtr obj)
static string ovr_AchievementProgress_GetName (IntPtr obj)
static DateTime ovr_AchievementProgress_GetUnlockTime (IntPtr obj)
static string ovr_AchievementProgressArray_GetNextUrl (IntPtr obj)
static string ovr_AchievementUpdate_GetName (IntPtr obj)
static string ovr_ApplicationInvite_GetLobbySessionId (IntPtr obj)
static string ovr_ApplicationInvite_GetMatchSessionId (IntPtr obj)
static string ovr_ApplicationInviteArray_GetNextUrl (IntPtr obj)
static string ovr_ApplicationVersion_GetCurrentName (IntPtr obj)
static string ovr_ApplicationVersion_GetLatestName (IntPtr obj)
static string ovr_AssetDetails_GetAssetType (IntPtr obj)
static string ovr_AssetDetails_GetDownloadStatus (IntPtr obj)
static string ovr_AssetDetails_GetFilepath (IntPtr obj)
static string ovr_AssetDetails_GetIapStatus (IntPtr obj)
static string ovr_AssetDetails_GetMetadata (IntPtr obj)
static string ovr_AssetFileDeleteResult_GetFilepath (IntPtr obj)
static string ovr_AssetFileDownloadCancelResult_GetFilepath (IntPtr obj)
static string ovr_AssetFileDownloadResult_GetFilepath (IntPtr obj)
static string ovr_CalApplicationFinalized_GetLaunchDetails (IntPtr obj)
static string ovr_CalApplicationSuggestion_GetSocialContext (IntPtr obj)
static string ovr_Challenge_GetDescription (IntPtr obj)
static DateTime ovr_Challenge_GetEndDate (IntPtr obj)
static DateTime ovr_Challenge_GetStartDate (IntPtr obj)
static string ovr_Challenge_GetTitle (IntPtr obj)
static string ovr_ChallengeArray_GetNextUrl (IntPtr obj)
static string ovr_ChallengeArray_GetPreviousUrl (IntPtr obj)
static string ovr_ChallengeEntry_GetDisplayScore (IntPtr obj)
static byte[] ovr_ChallengeEntry_GetExtraData (IntPtr obj)
static DateTime ovr_ChallengeEntry_GetTimestamp (IntPtr obj)
static string ovr_ChallengeEntryArray_GetNextUrl (IntPtr obj)
static string ovr_ChallengeEntryArray_GetPreviousUrl (IntPtr obj)
static string ovr_CloudStorage2UserDirectoryPathResponse_GetPath (IntPtr obj)
static string ovr_CloudStorageData_GetBucket (IntPtr obj)
static byte[] ovr_CloudStorageData_GetData (IntPtr obj)
static string ovr_CloudStorageData_GetKey (IntPtr obj)
static string ovr_CloudStorageMetadata_GetBucket (IntPtr obj)
static string ovr_CloudStorageMetadata_GetExtraData (IntPtr obj)
static string ovr_CloudStorageMetadata_GetKey (IntPtr obj)
static string ovr_CloudStorageMetadata_GetVersionHandle (IntPtr obj)
static string ovr_CloudStorageMetadataArray_GetNextUrl (IntPtr obj)
static string ovr_CloudStorageUpdateResponse_GetBucket (IntPtr obj)
static string ovr_CloudStorageUpdateResponse_GetKey (IntPtr obj)
static string ovr_CloudStorageUpdateResponse_GetVersionHandle (IntPtr obj)
static uint ovr_DataStore_Contains (IntPtr obj, string key)
static string ovr_DataStore_GetKey (IntPtr obj, int index)
static string ovr_DataStore_GetValue (IntPtr obj, string key)
static string ovr_Destination_GetApiName (IntPtr obj)
static string ovr_Destination_GetDeeplinkMessage (IntPtr obj)
static string ovr_Destination_GetDisplayName (IntPtr obj)
static string ovr_DestinationArray_GetNextUrl (IntPtr obj)
static string ovr_Error_GetDisplayableMessage (IntPtr obj)
static string ovr_Error_GetMessage (IntPtr obj)
static string ovr_GroupPresenceJoinIntent_GetDeeplinkMessage (IntPtr obj)
static string ovr_GroupPresenceJoinIntent_GetDestinationApiName (IntPtr obj)
static string ovr_GroupPresenceJoinIntent_GetLobbySessionId (IntPtr obj)
static string ovr_GroupPresenceJoinIntent_GetMatchSessionId (IntPtr obj)
static string ovr_GroupPresenceLeaveIntent_GetDestinationApiName (IntPtr obj)
static string ovr_GroupPresenceLeaveIntent_GetLobbySessionId (IntPtr obj)
static string ovr_GroupPresenceLeaveIntent_GetMatchSessionId (IntPtr obj)
static string ovr_InstalledApplication_GetApplicationId (IntPtr obj)
static string ovr_InstalledApplication_GetPackageName (IntPtr obj)
static string ovr_InstalledApplication_GetStatus (IntPtr obj)
static string ovr_InstalledApplication_GetVersionName (IntPtr obj)
static string ovr_LanguagePackInfo_GetEnglishName (IntPtr obj)
static string ovr_LanguagePackInfo_GetNativeName (IntPtr obj)
static string ovr_LanguagePackInfo_GetTag (IntPtr obj)
static string ovr_LaunchDetails_GetDeeplinkMessage (IntPtr obj)
static string ovr_LaunchDetails_GetDestinationApiName (IntPtr obj)
static string ovr_LaunchDetails_GetLaunchSource (IntPtr obj)
static string ovr_LaunchDetails_GetTrackingID (IntPtr obj)
static string ovr_Leaderboard_GetApiName (IntPtr obj)
static string ovr_LeaderboardArray_GetNextUrl (IntPtr obj)
static string ovr_LeaderboardEntry_GetDisplayScore (IntPtr obj)
static byte[] ovr_LeaderboardEntry_GetExtraData (IntPtr obj)
static DateTime ovr_LeaderboardEntry_GetTimestamp (IntPtr obj)
static string ovr_LeaderboardEntryArray_GetNextUrl (IntPtr obj)
static string ovr_LeaderboardEntryArray_GetPreviousUrl (IntPtr obj)
static string ovr_LinkedAccount_GetAccessToken (IntPtr obj)
static string ovr_LinkedAccount_GetUserId (IntPtr obj)
static string ovr_LivestreamingVideoStats_GetTotalViews (IntPtr obj)
static string ovr_MatchmakingAdminSnapshotCandidate_GetTraceId (IntPtr obj)
static string ovr_MatchmakingCandidate_GetEntryHash (IntPtr obj)
static string ovr_MatchmakingCandidateArray_GetNextUrl (IntPtr obj)
static string ovr_MatchmakingEnqueueResult_GetPool (IntPtr obj)
static string ovr_MatchmakingEnqueueResult_GetRequestHash (IntPtr obj)
static string ovr_MatchmakingNotification_GetTraceId (IntPtr obj)
static string ovr_Message_GetString (IntPtr obj)
static string ovr_NetSyncConnection_GetZoneId (IntPtr obj)
static string ovr_NetSyncSession_GetVoipGroup (IntPtr obj)
static string ovr_PartyUpdateNotification_GetUpdateTimestamp (IntPtr obj)
static string ovr_PartyUpdateNotification_GetUserAlias (IntPtr obj)
static string ovr_PartyUpdateNotification_GetUserName (IntPtr obj)
static string ovr_Pid_GetId (IntPtr obj)
static string ovr_Price_GetCurrency (IntPtr obj)
static string ovr_Price_GetFormatted (IntPtr obj)
static string ovr_Product_GetDescription (IntPtr obj)
static string ovr_Product_GetFormattedPrice (IntPtr obj)
static string ovr_Product_GetName (IntPtr obj)
static string ovr_Product_GetSKU (IntPtr obj)
static string ovr_ProductArray_GetNextUrl (IntPtr obj)
static DateTime ovr_Purchase_GetExpirationTime (IntPtr obj)
static DateTime ovr_Purchase_GetGrantTime (IntPtr obj)
static string ovr_Purchase_GetPurchaseStrID (IntPtr obj)
static string ovr_Purchase_GetSKU (IntPtr obj)
static string ovr_PurchaseArray_GetNextUrl (IntPtr obj)
static string ovr_Room_GetDescription (IntPtr obj)
static string ovr_Room_GetName (IntPtr obj)
static string ovr_RoomArray_GetNextUrl (IntPtr obj)
static DateTime ovr_RoomInviteNotification_GetSentTime (IntPtr obj)
static string ovr_RoomInviteNotificationArray_GetNextUrl (IntPtr obj)
static string ovr_Team_GetName (IntPtr obj)
static string ovr_TestUser_GetAccessToken (IntPtr obj)
static string ovr_TestUser_GetFriendAccessToken (IntPtr obj)
static string ovr_TestUser_GetUserAlias (IntPtr obj)
static string ovr_TestUserAppAccess_GetAccessToken (IntPtr obj)
static string ovr_User_GetDisplayName (IntPtr obj)
static string ovr_User_GetImageUrl (IntPtr obj)
static string ovr_User_GetInviteToken (IntPtr obj)
static string ovr_User_GetOculusID (IntPtr obj)
static string ovr_User_GetPresence (IntPtr obj)
static string ovr_User_GetPresenceDeeplinkMessage (IntPtr obj)
static string ovr_User_GetPresenceDestinationApiName (IntPtr obj)
static string ovr_User_GetPresenceLobbySessionId (IntPtr obj)
static string ovr_User_GetPresenceMatchSessionId (IntPtr obj)
static string ovr_User_GetSmallImageUrl (IntPtr obj)
static string ovr_UserAndRoomArray_GetNextUrl (IntPtr obj)
static string ovr_UserArray_GetNextUrl (IntPtr obj)
static string ovr_UserCapability_GetDescription (IntPtr obj)
static string ovr_UserCapability_GetName (IntPtr obj)
static string ovr_UserCapability_GetReasonCode (IntPtr obj)
static string ovr_UserCapabilityArray_GetNextUrl (IntPtr obj)
static string ovr_UserProof_GetNonce (IntPtr obj)
static void ovr_AdvancedAbuseReportOptions_SetObjectType (IntPtr handle, string value)
static void ovr_ApplicationOptions_SetDeeplinkMessage (IntPtr handle, string value)
static void ovr_ChallengeOptions_SetDescription (IntPtr handle, string value)
static void ovr_ChallengeOptions_SetEndDate (IntPtr handle, DateTime value)
static void ovr_ChallengeOptions_SetLeaderboardName (IntPtr handle, string value)
static void ovr_ChallengeOptions_SetStartDate (IntPtr handle, DateTime value)
static void ovr_ChallengeOptions_SetTitle (IntPtr handle, string value)
static void ovr_GroupPresenceOptions_SetDestinationApiName (IntPtr handle, string value)
static void ovr_GroupPresenceOptions_SetLobbySessionId (IntPtr handle, string value)
static void ovr_GroupPresenceOptions_SetMatchSessionId (IntPtr handle, string value)
static void ovr_MatchmakingOptions_SetCreateRoomDataStoreString (IntPtr handle, string key, string value)
static void ovr_MatchmakingOptions_SetEnqueueDataSettingsInt (IntPtr handle, string key, int value)
static void ovr_MatchmakingOptions_SetEnqueueDataSettingsDouble (IntPtr handle, string key, double value)
static void ovr_MatchmakingOptions_SetEnqueueDataSettingsString (IntPtr handle, string key, string value)
static void ovr_MatchmakingOptions_SetEnqueueQueryKey (IntPtr handle, string value)
static void ovr_NetSyncOptions_SetVoipGroup (IntPtr handle, string value)
static void ovr_NetSyncOptions_SetZoneId (IntPtr handle, string value)
static void ovr_RichPresenceOptions_SetApiName (IntPtr handle, string value)
static void ovr_RichPresenceOptions_SetArgsString (IntPtr handle, string key, string value)
static void ovr_RichPresenceOptions_SetDeeplinkMessageOverride (IntPtr handle, string value)
static void ovr_RichPresenceOptions_SetEndTime (IntPtr handle, DateTime value)
static void ovr_RichPresenceOptions_SetInstanceId (IntPtr handle, string value)
static void ovr_RichPresenceOptions_SetJoinableId (IntPtr handle, string value)
static void ovr_RichPresenceOptions_SetLobbySessionId (IntPtr handle, string value)
static void ovr_RichPresenceOptions_SetMatchSessionId (IntPtr handle, string value)
static void ovr_RichPresenceOptions_SetStartTime (IntPtr handle, DateTime value)
static void ovr_RoomOptions_SetDataStoreString (IntPtr handle, string key, string value)
Static Public Attributes
const string DLL_NAME = "ovrplatformloader"
const int VoipFilterBufferSize = 480
Member Function Documentation
ArrayOfStructsToIntPtr()
static IntPtr Oculus.Platform.CAPI.ArrayOfStructsToIntPtr (Array ar) static
Referenced by Oculus.Platform.Matchmaking.CustomQuery.ToUnmanaged().
BlobFromNative()
static byte[] Oculus.Platform.CAPI.BlobFromNative (uint size, IntPtr pointer) static
Referenced by Oculus.Platform.CAPI.ovr_ChallengeEntry_GetExtraData(), and Oculus.Platform.CAPI.ovr_LeaderboardEntry_GetExtraData().
DataStoreFromNative()
static Dictionary< string, string > Oculus.Platform.CAPI.DataStoreFromNative (IntPtr pointer) static
Referenced by Oculus.Platform.MessageWithDataStoreUnderPrivateUserDataStore.GetDataFromMessage(), Oculus.Platform.MessageWithDataStoreUnderPublicUserDataStore.GetDataFromMessage(), Oculus.Platform.Models.MatchmakingEnqueuedUser.MatchmakingEnqueuedUser(), and Oculus.Platform.Models.Room.Room().
DateTimeFromNative()
static DateTime Oculus.Platform.CAPI.DateTimeFromNative (ulong seconds_since_the_one_true_epoch) static
Referenced by Oculus.Platform.CAPI.ovr_AchievementProgress_GetUnlockTime(), Oculus.Platform.CAPI.ovr_Challenge_GetEndDate(), Oculus.Platform.CAPI.ovr_Challenge_GetStartDate(), Oculus.Platform.CAPI.ovr_ChallengeEntry_GetTimestamp(), Oculus.Platform.CAPI.ovr_LeaderboardEntry_GetTimestamp(), Oculus.Platform.CAPI.ovr_Purchase_GetExpirationTime(), Oculus.Platform.CAPI.ovr_Purchase_GetGrantTime(), and Oculus.Platform.CAPI.ovr_RoomInviteNotification_GetSentTime().
DateTimeToNative()
static ulong Oculus.Platform.CAPI.DateTimeToNative (DateTime dt) static
Referenced by Oculus.Platform.CAPI.ovr_ChallengeOptions_SetEndDate(), Oculus.Platform.CAPI.ovr_ChallengeOptions_SetStartDate(), Oculus.Platform.CAPI.ovr_RichPresenceOptions_SetEndTime(), and Oculus.Platform.CAPI.ovr_RichPresenceOptions_SetStartTime().
DictionaryToOVRKeyValuePairs()
static CAPI.ovrKeyValuePair[] Oculus.Platform.CAPI.DictionaryToOVRKeyValuePairs (Dictionary< string, object > dict) static
Referenced by Oculus.Platform.Matchmaking.CustomQuery.ToUnmanaged().
FiledataFromNative()
static byte[] Oculus.Platform.CAPI.FiledataFromNative (uint size, IntPtr pointer) static
Referenced by Oculus.Platform.CAPI.ovr_CloudStorageData_GetData().
FilterCallback()
delegate void Oculus.Platform.CAPI.FilterCallback ([MarshalAs(UnmanagedType.LPArray, SizeConst=VoipFilterBufferSize), In, Out] short[] pcmData, UIntPtr pcmDataLength, int frequency, int numChannels)
GetNativeStringLengthNotIncludingNullTerminator()
static int Oculus.Platform.CAPI.GetNativeStringLengthNotIncludingNullTerminator (IntPtr pointer) static
Referenced by Oculus.Platform.CAPI.StringFromNative().
IntPtrToByteArray()
static byte[] Oculus.Platform.CAPI.IntPtrToByteArray (IntPtr data, ulong size) static
LogNewEvent()
static void Oculus.Platform.CAPI.LogNewEvent (string eventName, Dictionary< string, string > values) static
ovr_AbuseReport_LaunchAdvancedReportFlow()
static ulong Oculus.Platform.CAPI.ovr_AbuseReport_LaunchAdvancedReportFlow (UInt64 content_id, IntPtr abuse_report_options)
ovr_AbuseReportOptions_Create()
static IntPtr Oculus.Platform.CAPI.ovr_AbuseReportOptions_Create ()
Referenced by Oculus.Platform.AbuseReportOptions.AbuseReportOptions().
ovr_AbuseReportOptions_Destroy()
static void Oculus.Platform.CAPI.ovr_AbuseReportOptions_Destroy (IntPtr handle)
ovr_AbuseReportOptions_SetPreventPeopleChooser()
static void Oculus.Platform.CAPI.ovr_AbuseReportOptions_SetPreventPeopleChooser (IntPtr handle, bool value)
Referenced by Oculus.Platform.AbuseReportOptions.SetPreventPeopleChooser().
ovr_AbuseReportOptions_SetReportType()
static void Oculus.Platform.CAPI.ovr_AbuseReportOptions_SetReportType (IntPtr handle, AbuseReportType value)
Referenced by Oculus.Platform.AbuseReportOptions.SetReportType().
ovr_AbuseReportRecording_GetRecordingUuid()
static string Oculus.Platform.CAPI.ovr_AbuseReportRecording_GetRecordingUuid (IntPtr obj) static
Referenced by Oculus.Platform.Models.AbuseReportRecording.AbuseReportRecording().
ovr_AchievementDefinition_GetBitfieldLength()
static uint Oculus.Platform.CAPI.ovr_AchievementDefinition_GetBitfieldLength (IntPtr obj)
Referenced by Oculus.Platform.Models.AchievementDefinition.AchievementDefinition().
ovr_AchievementDefinition_GetName()
static string Oculus.Platform.CAPI.ovr_AchievementDefinition_GetName (IntPtr obj) static
Referenced by Oculus.Platform.Models.AchievementDefinition.AchievementDefinition().
ovr_AchievementDefinition_GetTarget()
static ulong Oculus.Platform.CAPI.ovr_AchievementDefinition_GetTarget (IntPtr obj)
Referenced by Oculus.Platform.Models.AchievementDefinition.AchievementDefinition().
ovr_AchievementDefinition_GetType()
static AchievementType Oculus.Platform.CAPI.ovr_AchievementDefinition_GetType (IntPtr obj)
Referenced by Oculus.Platform.Models.AchievementDefinition.AchievementDefinition().
ovr_AchievementDefinitionArray_GetElement()
static IntPtr Oculus.Platform.CAPI.ovr_AchievementDefinitionArray_GetElement (IntPtr obj, UIntPtr index)
Referenced by Oculus.Platform.Models.AchievementDefinitionList.AchievementDefinitionList().
ovr_AchievementDefinitionArray_GetNextUrl()
static string Oculus.Platform.CAPI.ovr_AchievementDefinitionArray_GetNextUrl (IntPtr obj) static
Referenced by Oculus.Platform.Models.AchievementDefinitionList.AchievementDefinitionList().
ovr_AchievementDefinitionArray_GetSize()
static UIntPtr Oculus.Platform.CAPI.ovr_AchievementDefinitionArray_GetSize (IntPtr obj)
Referenced by Oculus.Platform.Models.AchievementDefinitionList.AchievementDefinitionList().
ovr_AchievementDefinitionArray_HasNextPage()
static bool Oculus.Platform.CAPI.ovr_AchievementDefinitionArray_HasNextPage (IntPtr obj)
ovr_AchievementProgress_GetBitfield()
static string Oculus.Platform.CAPI.ovr_AchievementProgress_GetBitfield (IntPtr obj) static
Referenced by Oculus.Platform.Models.AchievementProgress.AchievementProgress().
ovr_AchievementProgress_GetCount()
static ulong Oculus.Platform.CAPI.ovr_AchievementProgress_GetCount (IntPtr obj)
Referenced by Oculus.Platform.Models.AchievementProgress.AchievementProgress().
ovr_AchievementProgress_GetIsUnlocked()
static bool Oculus.Platform.CAPI.ovr_AchievementProgress_GetIsUnlocked (IntPtr obj)
Referenced by Oculus.Platform.Models.AchievementProgress.AchievementProgress().
ovr_AchievementProgress_GetName()
static string Oculus.Platform.CAPI.ovr_AchievementProgress_GetName (IntPtr obj) static
Referenced by Oculus.Platform.Models.AchievementProgress.AchievementProgress().
ovr_AchievementProgress_GetUnlockTime()
static DateTime Oculus.Platform.CAPI.ovr_AchievementProgress_GetUnlockTime (IntPtr obj) static
Referenced by Oculus.Platform.Models.AchievementProgress.AchievementProgress().
ovr_AchievementProgressArray_GetElement()
static IntPtr Oculus.Platform.CAPI.ovr_AchievementProgressArray_GetElement (IntPtr obj, UIntPtr index)
Referenced by Oculus.Platform.Models.AchievementProgressList.AchievementProgressList().
ovr_AchievementProgressArray_GetNextUrl()
static string Oculus.Platform.CAPI.ovr_AchievementProgressArray_GetNextUrl (IntPtr obj) static
Referenced by Oculus.Platform.Models.AchievementProgressList.AchievementProgressList().
ovr_AchievementProgressArray_GetSize()
static UIntPtr Oculus.Platform.CAPI.ovr_AchievementProgressArray_GetSize (IntPtr obj)
Referenced by Oculus.Platform.Models.AchievementProgressList.AchievementProgressList().
ovr_AchievementProgressArray_HasNextPage()
static bool Oculus.Platform.CAPI.ovr_AchievementProgressArray_HasNextPage (IntPtr obj)
ovr_Achievements_AddCount()
static ulong Oculus.Platform.CAPI.ovr_Achievements_AddCount (string name, ulong count) static
ovr_Achievements_AddFields()
static ulong Oculus.Platform.CAPI.ovr_Achievements_AddFields (string name, string fields) static
ovr_Achievements_GetAllDefinitions()
static ulong Oculus.Platform.CAPI.ovr_Achievements_GetAllDefinitions ()
ovr_Achievements_GetAllProgress()
static ulong Oculus.Platform.CAPI.ovr_Achievements_GetAllProgress ()
ovr_Achievements_GetDefinitionsByName()
static ulong Oculus.Platform.CAPI.ovr_Achievements_GetDefinitionsByName (string[] names, int count)
ovr_Achievements_GetProgressByName()
static ulong Oculus.Platform.CAPI.ovr_Achievements_GetProgressByName (string[] names, int count)
ovr_Achievements_Unlock()
static ulong Oculus.Platform.CAPI.ovr_Achievements_Unlock (string name) static
ovr_AchievementUpdate_GetJustUnlocked()
static bool Oculus.Platform.CAPI.ovr_AchievementUpdate_GetJustUnlocked (IntPtr obj)
Referenced by Oculus.Platform.Models.AchievementUpdate.AchievementUpdate().
ovr_AchievementUpdate_GetName()
static string Oculus.Platform.CAPI.ovr_AchievementUpdate_GetName (IntPtr obj) static
Referenced by Oculus.Platform.Models.AchievementUpdate.AchievementUpdate().
ovr_AdvancedAbuseReportOptions_Create()
static IntPtr Oculus.Platform.CAPI.ovr_AdvancedAbuseReportOptions_Create ()
Referenced by Oculus.Platform.AdvancedAbuseReportOptions.AdvancedAbuseReportOptions().
ovr_AdvancedAbuseReportOptions_Destroy()
static void Oculus.Platform.CAPI.ovr_AdvancedAbuseReportOptions_Destroy (IntPtr handle)
ovr_AdvancedAbuseReportOptions_SetObjectType()
static void Oculus.Platform.CAPI.ovr_AdvancedAbuseReportOptions_SetObjectType (IntPtr handle, string value) static
Referenced by Oculus.Platform.AdvancedAbuseReportOptions.SetObjectType().
ovr_AdvancedAbuseReportOptions_SetReportType()
static void Oculus.Platform.CAPI.ovr_AdvancedAbuseReportOptions_SetReportType (IntPtr handle, AbuseReportType value)
Referenced by Oculus.Platform.AdvancedAbuseReportOptions.SetReportType().
ovr_AdvancedAbuseReportOptions_SetVideoMode()
static void Oculus.Platform.CAPI.ovr_AdvancedAbuseReportOptions_SetVideoMode (IntPtr handle, AbuseReportVideoMode value)
Referenced by Oculus.Platform.AdvancedAbuseReportOptions.SetVideoMode().
ovr_Application_ExecuteCoordinatedLaunch()
static ulong Oculus.Platform.CAPI.ovr_Application_ExecuteCoordinatedLaunch (ulong appID, ulong roomID)
ovr_Application_GetID()
static UInt64 Oculus.Platform.CAPI.ovr_Application_GetID (IntPtr obj)
ovr_Application_GetInstalledApplications()
static ulong Oculus.Platform.CAPI.ovr_Application_GetInstalledApplications ()
ovr_Application_GetVersion()
static ulong Oculus.Platform.CAPI.ovr_Application_GetVersion ()
ovr_Application_LaunchOtherApp()
static ulong Oculus.Platform.CAPI.ovr_Application_LaunchOtherApp (UInt64 appID, IntPtr deeplink_options)
ovr_ApplicationInvite_GetDestination()
static IntPtr Oculus.Platform.CAPI.ovr_ApplicationInvite_GetDestination (IntPtr obj)
Referenced by Oculus.Platform.Models.ApplicationInvite.ApplicationInvite().
ovr_ApplicationInvite_GetID()
static UInt64 Oculus.Platform.CAPI.ovr_ApplicationInvite_GetID (IntPtr obj)
Referenced by Oculus.Platform.Models.ApplicationInvite.ApplicationInvite().
ovr_ApplicationInvite_GetIsActive()
static bool Oculus.Platform.CAPI.ovr_ApplicationInvite_GetIsActive (IntPtr obj)
Referenced by Oculus.Platform.Models.ApplicationInvite.ApplicationInvite().
ovr_ApplicationInvite_GetLobbySessionId()
static string Oculus.Platform.CAPI.ovr_ApplicationInvite_GetLobbySessionId (IntPtr obj) static
Referenced by Oculus.Platform.Models.ApplicationInvite.ApplicationInvite().
ovr_ApplicationInvite_GetMatchSessionId()
static string Oculus.Platform.CAPI.ovr_ApplicationInvite_GetMatchSessionId (IntPtr obj) static
Referenced by Oculus.Platform.Models.ApplicationInvite.ApplicationInvite().
ovr_ApplicationInvite_GetRecipient()
static IntPtr Oculus.Platform.CAPI.ovr_ApplicationInvite_GetRecipient (IntPtr obj)
Referenced by Oculus.Platform.Models.ApplicationInvite.ApplicationInvite().
ovr_ApplicationInviteArray_GetElement()
static IntPtr Oculus.Platform.CAPI.ovr_ApplicationInviteArray_GetElement (IntPtr obj, UIntPtr index)
Referenced by Oculus.Platform.Models.ApplicationInviteList.ApplicationInviteList().
ovr_ApplicationInviteArray_GetNextUrl()
static string Oculus.Platform.CAPI.ovr_ApplicationInviteArray_GetNextUrl (IntPtr obj) static
Referenced by Oculus.Platform.Models.ApplicationInviteList.ApplicationInviteList().
ovr_ApplicationInviteArray_GetSize()
static UIntPtr Oculus.Platform.CAPI.ovr_ApplicationInviteArray_GetSize (IntPtr obj)
Referenced by Oculus.Platform.Models.ApplicationInviteList.ApplicationInviteList().
ovr_ApplicationInviteArray_HasNextPage()
static bool Oculus.Platform.CAPI.ovr_ApplicationInviteArray_HasNextPage (IntPtr obj)
ovr_ApplicationLifecycle_GetLaunchDetails()
static IntPtr Oculus.Platform.CAPI.ovr_ApplicationLifecycle_GetLaunchDetails ()
ovr_ApplicationLifecycle_GetRegisteredPIDs()
static ulong Oculus.Platform.CAPI.ovr_ApplicationLifecycle_GetRegisteredPIDs ()
ovr_ApplicationLifecycle_GetSessionKey()
static ulong Oculus.Platform.CAPI.ovr_ApplicationLifecycle_GetSessionKey ()
ovr_ApplicationLifecycle_LogDeeplinkResult()
static void Oculus.Platform.CAPI.ovr_ApplicationLifecycle_LogDeeplinkResult (string trackingID, LaunchResult result) static
ovr_ApplicationLifecycle_RegisterSessionKey()
static ulong Oculus.Platform.CAPI.ovr_ApplicationLifecycle_RegisterSessionKey (string sessionKey) static
ovr_ApplicationOptions_Create()
static IntPtr Oculus.Platform.CAPI.ovr_ApplicationOptions_Create ()
Referenced by Oculus.Platform.ApplicationOptions.ApplicationOptions().
ovr_ApplicationOptions_Destroy()
static void Oculus.Platform.CAPI.ovr_ApplicationOptions_Destroy (IntPtr handle)
ovr_ApplicationOptions_SetDeeplinkMessage()
static void Oculus.Platform.CAPI.ovr_ApplicationOptions_SetDeeplinkMessage (IntPtr handle, string value) static
Referenced by Oculus.Platform.ApplicationOptions.SetDeeplinkMessage().
ovr_ApplicationVersion_GetCurrentCode()
static int Oculus.Platform.CAPI.ovr_ApplicationVersion_GetCurrentCode (IntPtr obj)
Referenced by Oculus.Platform.Models.ApplicationVersion.ApplicationVersion().
ovr_ApplicationVersion_GetCurrentName()
static string Oculus.Platform.CAPI.ovr_ApplicationVersion_GetCurrentName (IntPtr obj) static
Referenced by Oculus.Platform.Models.ApplicationVersion.ApplicationVersion().
ovr_ApplicationVersion_GetLatestCode()
static int Oculus.Platform.CAPI.ovr_ApplicationVersion_GetLatestCode (IntPtr obj)
Referenced by Oculus.Platform.Models.ApplicationVersion.ApplicationVersion().
ovr_ApplicationVersion_GetLatestName()
static string Oculus.Platform.CAPI.ovr_ApplicationVersion_GetLatestName (IntPtr obj) static
Referenced by Oculus.Platform.Models.ApplicationVersion.ApplicationVersion().
ovr_AssetDetails_GetAssetId()
static UInt64 Oculus.Platform.CAPI.ovr_AssetDetails_GetAssetId (IntPtr obj)
Referenced by Oculus.Platform.Models.AssetDetails.AssetDetails().
ovr_AssetDetails_GetAssetType()
static string Oculus.Platform.CAPI.ovr_AssetDetails_GetAssetType (IntPtr obj) static
Referenced by Oculus.Platform.Models.AssetDetails.AssetDetails().
ovr_AssetDetails_GetDownloadStatus()
static string Oculus.Platform.CAPI.ovr_AssetDetails_GetDownloadStatus (IntPtr obj) static
Referenced by Oculus.Platform.Models.AssetDetails.AssetDetails().
ovr_AssetDetails_GetFilepath()
static string Oculus.Platform.CAPI.ovr_AssetDetails_GetFilepath (IntPtr obj) static
Referenced by Oculus.Platform.Models.AssetDetails.AssetDetails().
ovr_AssetDetails_GetIapStatus()
static string Oculus.Platform.CAPI.ovr_AssetDetails_GetIapStatus (IntPtr obj) static
Referenced by Oculus.Platform.Models.AssetDetails.AssetDetails().
ovr_AssetDetails_GetLanguage()
static IntPtr Oculus.Platform.CAPI.ovr_AssetDetails_GetLanguage (IntPtr obj)
Referenced by Oculus.Platform.Models.AssetDetails.AssetDetails().
ovr_AssetDetails_GetMetadata()
static string Oculus.Platform.CAPI.ovr_AssetDetails_GetMetadata (IntPtr obj) static
Referenced by Oculus.Platform.Models.AssetDetails.AssetDetails().
ovr_AssetDetailsArray_GetElement()
static IntPtr Oculus.Platform.CAPI.ovr_AssetDetailsArray_GetElement (IntPtr obj, UIntPtr index)
Referenced by Oculus.Platform.Models.AssetDetailsList.AssetDetailsList().
ovr_AssetDetailsArray_GetSize()
static UIntPtr Oculus.Platform.CAPI.ovr_AssetDetailsArray_GetSize (IntPtr obj)
Referenced by Oculus.Platform.Models.AssetDetailsList.AssetDetailsList().
ovr_AssetFile_Delete()
static ulong Oculus.Platform.CAPI.ovr_AssetFile_Delete (UInt64 assetFileID)
ovr_AssetFile_DeleteById()
static ulong Oculus.Platform.CAPI.ovr_AssetFile_DeleteById (UInt64 assetFileID)
ovr_AssetFile_DeleteByName()
static ulong Oculus.Platform.CAPI.ovr_AssetFile_DeleteByName (string assetFileName) static
ovr_AssetFile_Download()
static ulong Oculus.Platform.CAPI.ovr_AssetFile_Download (UInt64 assetFileID)
ovr_AssetFile_DownloadById()
static ulong Oculus.Platform.CAPI.ovr_AssetFile_DownloadById (UInt64 assetFileID)
ovr_AssetFile_DownloadByName()
static ulong Oculus.Platform.CAPI.ovr_AssetFile_DownloadByName (string assetFileName) static
ovr_AssetFile_DownloadCancel()
static ulong Oculus.Platform.CAPI.ovr_AssetFile_DownloadCancel (UInt64 assetFileID)
ovr_AssetFile_DownloadCancelById()
static ulong Oculus.Platform.CAPI.ovr_AssetFile_DownloadCancelById (UInt64 assetFileID)
ovr_AssetFile_DownloadCancelByName()
static ulong Oculus.Platform.CAPI.ovr_AssetFile_DownloadCancelByName (string assetFileName) static
ovr_AssetFile_GetList()
static ulong Oculus.Platform.CAPI.ovr_AssetFile_GetList ()
ovr_AssetFile_Status()
static ulong Oculus.Platform.CAPI.ovr_AssetFile_Status (UInt64 assetFileID)
ovr_AssetFile_StatusById()
static ulong Oculus.Platform.CAPI.ovr_AssetFile_StatusById (UInt64 assetFileID)
ovr_AssetFile_StatusByName()
static ulong Oculus.Platform.CAPI.ovr_AssetFile_StatusByName (string assetFileName) static
ovr_AssetFileDeleteResult_GetAssetFileId()
static UInt64 Oculus.Platform.CAPI.ovr_AssetFileDeleteResult_GetAssetFileId (IntPtr obj)
Referenced by Oculus.Platform.Models.AssetFileDeleteResult.AssetFileDeleteResult().
ovr_AssetFileDeleteResult_GetAssetId()
static UInt64 Oculus.Platform.CAPI.ovr_AssetFileDeleteResult_GetAssetId (IntPtr obj)
Referenced by Oculus.Platform.Models.AssetFileDeleteResult.AssetFileDeleteResult().
ovr_AssetFileDeleteResult_GetFilepath()
static string Oculus.Platform.CAPI.ovr_AssetFileDeleteResult_GetFilepath (IntPtr obj) static
Referenced by Oculus.Platform.Models.AssetFileDeleteResult.AssetFileDeleteResult().
ovr_AssetFileDeleteResult_GetSuccess()
static bool Oculus.Platform.CAPI.ovr_AssetFileDeleteResult_GetSuccess (IntPtr obj)
Referenced by Oculus.Platform.Models.AssetFileDeleteResult.AssetFileDeleteResult().
ovr_AssetFileDownloadCancelResult_GetAssetFileId()
static UInt64 Oculus.Platform.CAPI.ovr_AssetFileDownloadCancelResult_GetAssetFileId (IntPtr obj)
Referenced by Oculus.Platform.Models.AssetFileDownloadCancelResult.AssetFileDownloadCancelResult().
ovr_AssetFileDownloadCancelResult_GetAssetId()
static UInt64 Oculus.Platform.CAPI.ovr_AssetFileDownloadCancelResult_GetAssetId (IntPtr obj)
Referenced by Oculus.Platform.Models.AssetFileDownloadCancelResult.AssetFileDownloadCancelResult().
ovr_AssetFileDownloadCancelResult_GetFilepath()
static string Oculus.Platform.CAPI.ovr_AssetFileDownloadCancelResult_GetFilepath (IntPtr obj) static
Referenced by Oculus.Platform.Models.AssetFileDownloadCancelResult.AssetFileDownloadCancelResult().
ovr_AssetFileDownloadCancelResult_GetSuccess()
static bool Oculus.Platform.CAPI.ovr_AssetFileDownloadCancelResult_GetSuccess (IntPtr obj)
Referenced by Oculus.Platform.Models.AssetFileDownloadCancelResult.AssetFileDownloadCancelResult().
ovr_AssetFileDownloadResult_GetAssetId()
static UInt64 Oculus.Platform.CAPI.ovr_AssetFileDownloadResult_GetAssetId (IntPtr obj)
Referenced by Oculus.Platform.Models.AssetFileDownloadResult.AssetFileDownloadResult().
ovr_AssetFileDownloadResult_GetFilepath()
static string Oculus.Platform.CAPI.ovr_AssetFileDownloadResult_GetFilepath (IntPtr obj) static
Referenced by Oculus.Platform.Models.AssetFileDownloadResult.AssetFileDownloadResult().
ovr_AssetFileDownloadUpdate_GetAssetFileId()
static UInt64 Oculus.Platform.CAPI.ovr_AssetFileDownloadUpdate_GetAssetFileId (IntPtr obj)
Referenced by Oculus.Platform.Models.AssetFileDownloadUpdate.AssetFileDownloadUpdate().
ovr_AssetFileDownloadUpdate_GetAssetId()
static UInt64 Oculus.Platform.CAPI.ovr_AssetFileDownloadUpdate_GetAssetId (IntPtr obj)
Referenced by Oculus.Platform.Models.AssetFileDownloadUpdate.AssetFileDownloadUpdate().
ovr_AssetFileDownloadUpdate_GetBytesTotal()
static uint Oculus.Platform.CAPI.ovr_AssetFileDownloadUpdate_GetBytesTotal (IntPtr obj)
ovr_AssetFileDownloadUpdate_GetBytesTotalLong()
static ulong Oculus.Platform.CAPI.ovr_AssetFileDownloadUpdate_GetBytesTotalLong (IntPtr obj)
Referenced by Oculus.Platform.Models.AssetFileDownloadUpdate.AssetFileDownloadUpdate().
ovr_AssetFileDownloadUpdate_GetBytesTransferred()
static int Oculus.Platform.CAPI.ovr_AssetFileDownloadUpdate_GetBytesTransferred (IntPtr obj)
ovr_AssetFileDownloadUpdate_GetBytesTransferredLong()
static long Oculus.Platform.CAPI.ovr_AssetFileDownloadUpdate_GetBytesTransferredLong (IntPtr obj)
Referenced by Oculus.Platform.Models.AssetFileDownloadUpdate.AssetFileDownloadUpdate().
ovr_AssetFileDownloadUpdate_GetCompleted()
static bool Oculus.Platform.CAPI.ovr_AssetFileDownloadUpdate_GetCompleted (IntPtr obj)
Referenced by Oculus.Platform.Models.AssetFileDownloadUpdate.AssetFileDownloadUpdate().
ovr_Avatar_UpdateMetaData()
static ulong Oculus.Platform.CAPI.ovr_Avatar_UpdateMetaData (string avatarMetaData, string imageFilePath) static
ovr_Cal_FinalizeApplication()
static ulong Oculus.Platform.CAPI.ovr_Cal_FinalizeApplication (UInt64 groupingObject, UInt64[] userIDs, int numUserIDs, UInt64 finalized_application_ID)
ovr_Cal_GetSuggestedApplications()
static ulong Oculus.Platform.CAPI.ovr_Cal_GetSuggestedApplications (UInt64 groupingObject, UInt64[] userIDs, int numUserIDs)
ovr_Cal_ProposeApplication()
static ulong Oculus.Platform.CAPI.ovr_Cal_ProposeApplication (UInt64 groupingObject, UInt64[] userIDs, int numUserIDs, UInt64 proposed_application_ID)
ovr_CalApplicationFinalized_GetCountdownMS()
static int Oculus.Platform.CAPI.ovr_CalApplicationFinalized_GetCountdownMS (IntPtr obj)
Referenced by Oculus.Platform.Models.CalApplicationFinalized.CalApplicationFinalized().
ovr_CalApplicationFinalized_GetID()
static UInt64 Oculus.Platform.CAPI.ovr_CalApplicationFinalized_GetID (IntPtr obj)
Referenced by Oculus.Platform.Models.CalApplicationFinalized.CalApplicationFinalized().
ovr_CalApplicationFinalized_GetLaunchDetails()
static string Oculus.Platform.CAPI.ovr_CalApplicationFinalized_GetLaunchDetails (IntPtr obj) static
Referenced by Oculus.Platform.Models.CalApplicationFinalized.CalApplicationFinalized().
ovr_CalApplicationProposed_GetID()
static UInt64 Oculus.Platform.CAPI.ovr_CalApplicationProposed_GetID (IntPtr obj)
Referenced by Oculus.Platform.Models.CalApplicationProposed.CalApplicationProposed().
ovr_CalApplicationSuggestion_GetID()
static UInt64 Oculus.Platform.CAPI.ovr_CalApplicationSuggestion_GetID (IntPtr obj)
Referenced by Oculus.Platform.Models.CalApplicationSuggestion.CalApplicationSuggestion().
ovr_CalApplicationSuggestion_GetSocialContext()
static string Oculus.Platform.CAPI.ovr_CalApplicationSuggestion_GetSocialContext (IntPtr obj) static
Referenced by Oculus.Platform.Models.CalApplicationSuggestion.CalApplicationSuggestion().
ovr_CalApplicationSuggestionArray_GetElement()
static IntPtr Oculus.Platform.CAPI.ovr_CalApplicationSuggestionArray_GetElement (IntPtr obj, UIntPtr index)
Referenced by Oculus.Platform.Models.CalApplicationSuggestionList.CalApplicationSuggestionList().
ovr_CalApplicationSuggestionArray_GetSize()
static UIntPtr Oculus.Platform.CAPI.ovr_CalApplicationSuggestionArray_GetSize (IntPtr obj)
Referenced by Oculus.Platform.Models.CalApplicationSuggestionList.CalApplicationSuggestionList().
ovr_Challenge_GetCreationType()
static ChallengeCreationType Oculus.Platform.CAPI.ovr_Challenge_GetCreationType (IntPtr obj)
Referenced by Oculus.Platform.Models.Challenge.Challenge().
ovr_Challenge_GetDescription()
static string Oculus.Platform.CAPI.ovr_Challenge_GetDescription (IntPtr obj) static
Referenced by Oculus.Platform.Models.Challenge.Challenge().
ovr_Challenge_GetEndDate()
static DateTime Oculus.Platform.CAPI.ovr_Challenge_GetEndDate (IntPtr obj) static
Referenced by Oculus.Platform.Models.Challenge.Challenge().
ovr_Challenge_GetID()
static UInt64 Oculus.Platform.CAPI.ovr_Challenge_GetID (IntPtr obj)
Referenced by Oculus.Platform.Models.Challenge.Challenge().
ovr_Challenge_GetInvitedUsers()
static IntPtr Oculus.Platform.CAPI.ovr_Challenge_GetInvitedUsers (IntPtr obj)
Referenced by Oculus.Platform.Models.Challenge.Challenge().
ovr_Challenge_GetLeaderboard()
static IntPtr Oculus.Platform.CAPI.ovr_Challenge_GetLeaderboard (IntPtr obj)
Referenced by Oculus.Platform.Models.Challenge.Challenge().
ovr_Challenge_GetParticipants()
static IntPtr Oculus.Platform.CAPI.ovr_Challenge_GetParticipants (IntPtr obj)
Referenced by Oculus.Platform.Models.Challenge.Challenge().
ovr_Challenge_GetStartDate()
static DateTime Oculus.Platform.CAPI.ovr_Challenge_GetStartDate (IntPtr obj) static
Referenced by Oculus.Platform.Models.Challenge.Challenge().
ovr_Challenge_GetTitle()
static string Oculus.Platform.CAPI.ovr_Challenge_GetTitle (IntPtr obj) static
Referenced by Oculus.Platform.Models.Challenge.Challenge().
ovr_Challenge_GetVisibility()
static ChallengeVisibility Oculus.Platform.CAPI.ovr_Challenge_GetVisibility (IntPtr obj)
Referenced by Oculus.Platform.Models.Challenge.Challenge().
ovr_ChallengeArray_GetElement()
static IntPtr Oculus.Platform.CAPI.ovr_ChallengeArray_GetElement (IntPtr obj, UIntPtr index)
Referenced by Oculus.Platform.Models.ChallengeList.ChallengeList().
ovr_ChallengeArray_GetNextUrl()
static string Oculus.Platform.CAPI.ovr_ChallengeArray_GetNextUrl (IntPtr obj) static
Referenced by Oculus.Platform.Models.ChallengeList.ChallengeList().
ovr_ChallengeArray_GetPreviousUrl()
static string Oculus.Platform.CAPI.ovr_ChallengeArray_GetPreviousUrl (IntPtr obj) static
Referenced by Oculus.Platform.Models.ChallengeList.ChallengeList().
ovr_ChallengeArray_GetSize()
static UIntPtr Oculus.Platform.CAPI.ovr_ChallengeArray_GetSize (IntPtr obj)
Referenced by Oculus.Platform.Models.ChallengeList.ChallengeList().
ovr_ChallengeArray_GetTotalCount()
static ulong Oculus.Platform.CAPI.ovr_ChallengeArray_GetTotalCount (IntPtr obj)
Referenced by Oculus.Platform.Models.ChallengeList.ChallengeList().
ovr_ChallengeArray_HasNextPage()
static bool Oculus.Platform.CAPI.ovr_ChallengeArray_HasNextPage (IntPtr obj)
ovr_ChallengeArray_HasPreviousPage()
static bool Oculus.Platform.CAPI.ovr_ChallengeArray_HasPreviousPage (IntPtr obj)
ovr_ChallengeEntry_GetDisplayScore()
static string Oculus.Platform.CAPI.ovr_ChallengeEntry_GetDisplayScore (IntPtr obj) static
Referenced by Oculus.Platform.Models.ChallengeEntry.ChallengeEntry().
ovr_ChallengeEntry_GetExtraData()
static byte[] Oculus.Platform.CAPI.ovr_ChallengeEntry_GetExtraData (IntPtr obj) static
Referenced by Oculus.Platform.Models.ChallengeEntry.ChallengeEntry().
ovr_ChallengeEntry_GetExtraDataLength()
static uint Oculus.Platform.CAPI.ovr_ChallengeEntry_GetExtraDataLength (IntPtr obj)
ovr_ChallengeEntry_GetID()
static UInt64 Oculus.Platform.CAPI.ovr_ChallengeEntry_GetID (IntPtr obj)
Referenced by Oculus.Platform.Models.ChallengeEntry.ChallengeEntry().
ovr_ChallengeEntry_GetRank()
static int Oculus.Platform.CAPI.ovr_ChallengeEntry_GetRank (IntPtr obj)
Referenced by Oculus.Platform.Models.ChallengeEntry.ChallengeEntry().
ovr_ChallengeEntry_GetScore()
static long Oculus.Platform.CAPI.ovr_ChallengeEntry_GetScore (IntPtr obj)
Referenced by Oculus.Platform.Models.ChallengeEntry.ChallengeEntry().
ovr_ChallengeEntry_GetTimestamp()
static DateTime Oculus.Platform.CAPI.ovr_ChallengeEntry_GetTimestamp (IntPtr obj) static
Referenced by Oculus.Platform.Models.ChallengeEntry.ChallengeEntry().
ovr_ChallengeEntry_GetUser()
static IntPtr Oculus.Platform.CAPI.ovr_ChallengeEntry_GetUser (IntPtr obj)
Referenced by Oculus.Platform.Models.ChallengeEntry.ChallengeEntry().
ovr_ChallengeEntryArray_GetElement()
static IntPtr Oculus.Platform.CAPI.ovr_ChallengeEntryArray_GetElement (IntPtr obj, UIntPtr index)
Referenced by Oculus.Platform.Models.ChallengeEntryList.ChallengeEntryList().
ovr_ChallengeEntryArray_GetNextUrl()
static string Oculus.Platform.CAPI.ovr_ChallengeEntryArray_GetNextUrl (IntPtr obj) static
Referenced by Oculus.Platform.Models.ChallengeEntryList.ChallengeEntryList().
ovr_ChallengeEntryArray_GetPreviousUrl()
static string Oculus.Platform.CAPI.ovr_ChallengeEntryArray_GetPreviousUrl (IntPtr obj) static
Referenced by Oculus.Platform.Models.ChallengeEntryList.ChallengeEntryList().
ovr_ChallengeEntryArray_GetSize()
static UIntPtr Oculus.Platform.CAPI.ovr_ChallengeEntryArray_GetSize (IntPtr obj)
Referenced by Oculus.Platform.Models.ChallengeEntryList.ChallengeEntryList().
ovr_ChallengeEntryArray_GetTotalCount()
static ulong Oculus.Platform.CAPI.ovr_ChallengeEntryArray_GetTotalCount (IntPtr obj)
Referenced by Oculus.Platform.Models.ChallengeEntryList.ChallengeEntryList().
ovr_ChallengeEntryArray_HasNextPage()
static bool Oculus.Platform.CAPI.ovr_ChallengeEntryArray_HasNextPage (IntPtr obj)
ovr_ChallengeEntryArray_HasPreviousPage()
static bool Oculus.Platform.CAPI.ovr_ChallengeEntryArray_HasPreviousPage (IntPtr obj)
ovr_ChallengeOptions_Create()
static IntPtr Oculus.Platform.CAPI.ovr_ChallengeOptions_Create ()
Referenced by Oculus.Platform.ChallengeOptions.ChallengeOptions().
ovr_ChallengeOptions_Destroy()
static void Oculus.Platform.CAPI.ovr_ChallengeOptions_Destroy (IntPtr handle)
ovr_ChallengeOptions_SetDescription()
static void Oculus.Platform.CAPI.ovr_ChallengeOptions_SetDescription (IntPtr handle, string value) static
Referenced by Oculus.Platform.ChallengeOptions.SetDescription().
ovr_ChallengeOptions_SetEndDate()
static void Oculus.Platform.CAPI.ovr_ChallengeOptions_SetEndDate (IntPtr handle, DateTime value) static
Referenced by Oculus.Platform.ChallengeOptions.SetEndDate().
ovr_ChallengeOptions_SetIncludeActiveChallenges()
static void Oculus.Platform.CAPI.ovr_ChallengeOptions_SetIncludeActiveChallenges (IntPtr handle, bool value)
Referenced by Oculus.Platform.ChallengeOptions.SetIncludeActiveChallenges().
ovr_ChallengeOptions_SetIncludeFutureChallenges()
static void Oculus.Platform.CAPI.ovr_ChallengeOptions_SetIncludeFutureChallenges (IntPtr handle, bool value)
Referenced by Oculus.Platform.ChallengeOptions.SetIncludeFutureChallenges().
ovr_ChallengeOptions_SetIncludePastChallenges()
static void Oculus.Platform.CAPI.ovr_ChallengeOptions_SetIncludePastChallenges (IntPtr handle, bool value)
Referenced by Oculus.Platform.ChallengeOptions.SetIncludePastChallenges().
ovr_ChallengeOptions_SetLeaderboardName()
static void Oculus.Platform.CAPI.ovr_ChallengeOptions_SetLeaderboardName (IntPtr handle, string value) static
Referenced by Oculus.Platform.ChallengeOptions.SetLeaderboardName().
ovr_ChallengeOptions_SetStartDate()
static void Oculus.Platform.CAPI.ovr_ChallengeOptions_SetStartDate (IntPtr handle, DateTime value) static
Referenced by Oculus.Platform.ChallengeOptions.SetStartDate().
ovr_ChallengeOptions_SetTitle()
static void Oculus.Platform.CAPI.ovr_ChallengeOptions_SetTitle (IntPtr handle, string value) static
Referenced by Oculus.Platform.ChallengeOptions.SetTitle().
ovr_ChallengeOptions_SetViewerFilter()
static void Oculus.Platform.CAPI.ovr_ChallengeOptions_SetViewerFilter (IntPtr handle, ChallengeViewerFilter value)
Referenced by Oculus.Platform.ChallengeOptions.SetViewerFilter().
ovr_ChallengeOptions_SetVisibility()
static void Oculus.Platform.CAPI.ovr_ChallengeOptions_SetVisibility (IntPtr handle, ChallengeVisibility value)
Referenced by Oculus.Platform.ChallengeOptions.SetVisibility().
ovr_Challenges_Create()
static ulong Oculus.Platform.CAPI.ovr_Challenges_Create (string leaderboardName, IntPtr challengeOptions) static
ovr_Challenges_DeclineInvite()
static ulong Oculus.Platform.CAPI.ovr_Challenges_DeclineInvite (UInt64 challengeID)
ovr_Challenges_Delete()
static ulong Oculus.Platform.CAPI.ovr_Challenges_Delete (UInt64 challengeID)
ovr_Challenges_Get()
static ulong Oculus.Platform.CAPI.ovr_Challenges_Get (UInt64 challengeID)
ovr_Challenges_GetEntries()
static ulong Oculus.Platform.CAPI.ovr_Challenges_GetEntries (UInt64 challengeID, int limit, LeaderboardFilterType filter, LeaderboardStartAt startAt)
ovr_Challenges_GetEntriesAfterRank()
static ulong Oculus.Platform.CAPI.ovr_Challenges_GetEntriesAfterRank (UInt64 challengeID, int limit, ulong afterRank)
ovr_Challenges_GetEntriesByIds()
static ulong Oculus.Platform.CAPI.ovr_Challenges_GetEntriesByIds (UInt64 challengeID, int limit, LeaderboardStartAt startAt, UInt64[] userIDs, uint userIDLength)
ovr_Challenges_GetList()
static ulong Oculus.Platform.CAPI.ovr_Challenges_GetList (IntPtr challengeOptions, int limit)
ovr_Challenges_GetNextChallenges()
static ulong Oculus.Platform.CAPI.ovr_Challenges_GetNextChallenges (IntPtr handle)
ovr_Challenges_GetNextEntries()
static ulong Oculus.Platform.CAPI.ovr_Challenges_GetNextEntries (IntPtr handle)
ovr_Challenges_GetPreviousChallenges()
static ulong Oculus.Platform.CAPI.ovr_Challenges_GetPreviousChallenges (IntPtr handle)
ovr_Challenges_GetPreviousEntries()
static ulong Oculus.Platform.CAPI.ovr_Challenges_GetPreviousEntries (IntPtr handle)
ovr_Challenges_Join()
static ulong Oculus.Platform.CAPI.ovr_Challenges_Join (UInt64 challengeID)
ovr_Challenges_Leave()
static ulong Oculus.Platform.CAPI.ovr_Challenges_Leave (UInt64 challengeID)
ovr_Challenges_UpdateInfo()
static ulong Oculus.Platform.CAPI.ovr_Challenges_UpdateInfo (UInt64 challengeID, IntPtr challengeOptions)
ovr_CloudStorage2_GetUserDirectoryPath()
static ulong Oculus.Platform.CAPI.ovr_CloudStorage2_GetUserDirectoryPath ()
ovr_CloudStorage2UserDirectoryPathResponse_GetPath()
static string Oculus.Platform.CAPI.ovr_CloudStorage2UserDirectoryPathResponse_GetPath (IntPtr obj) static
ovr_CloudStorage_Delete()
static ulong Oculus.Platform.CAPI.ovr_CloudStorage_Delete (string bucket, string key) static
ovr_CloudStorage_Load()
static ulong Oculus.Platform.CAPI.ovr_CloudStorage_Load (string bucket, string key) static
ovr_CloudStorage_LoadBucketMetadata()
static ulong Oculus.Platform.CAPI.ovr_CloudStorage_LoadBucketMetadata (string bucket) static
ovr_CloudStorage_LoadConflictMetadata()
static ulong Oculus.Platform.CAPI.ovr_CloudStorage_LoadConflictMetadata (string bucket, string key) static
ovr_CloudStorage_LoadHandle()
static ulong Oculus.Platform.CAPI.ovr_CloudStorage_LoadHandle (string handle) static
ovr_CloudStorage_LoadMetadata()
static ulong Oculus.Platform.CAPI.ovr_CloudStorage_LoadMetadata (string bucket, string key) static
ovr_CloudStorage_ResolveKeepLocal()
static ulong Oculus.Platform.CAPI.ovr_CloudStorage_ResolveKeepLocal (string bucket, string key, string remoteHandle) static
ovr_CloudStorage_ResolveKeepRemote()
static ulong Oculus.Platform.CAPI.ovr_CloudStorage_ResolveKeepRemote (string bucket, string key, string remoteHandle) static
ovr_CloudStorage_Save()
static ulong Oculus.Platform.CAPI.ovr_CloudStorage_Save (string bucket, string key, byte[] data, uint dataSize, long counter, string extraData) static
ovr_CloudStorageConflictMetadata_GetLocal()
static IntPtr Oculus.Platform.CAPI.ovr_CloudStorageConflictMetadata_GetLocal (IntPtr obj)
Referenced by Oculus.Platform.Models.CloudStorageConflictMetadata.CloudStorageConflictMetadata().
ovr_CloudStorageConflictMetadata_GetRemote()
static IntPtr Oculus.Platform.CAPI.ovr_CloudStorageConflictMetadata_GetRemote (IntPtr obj)
Referenced by Oculus.Platform.Models.CloudStorageConflictMetadata.CloudStorageConflictMetadata().
ovr_CloudStorageData_GetBucket()
static string Oculus.Platform.CAPI.ovr_CloudStorageData_GetBucket (IntPtr obj) static
Referenced by Oculus.Platform.Models.CloudStorageData.CloudStorageData().
ovr_CloudStorageData_GetData()
static byte[] Oculus.Platform.CAPI.ovr_CloudStorageData_GetData (IntPtr obj) static
Referenced by Oculus.Platform.Models.CloudStorageData.CloudStorageData().
ovr_CloudStorageData_GetDataSize()
static uint Oculus.Platform.CAPI.ovr_CloudStorageData_GetDataSize (IntPtr obj)
Referenced by Oculus.Platform.Models.CloudStorageData.CloudStorageData(), and Oculus.Platform.CAPI.ovr_CloudStorageData_GetData().
ovr_CloudStorageData_GetKey()
static string Oculus.Platform.CAPI.ovr_CloudStorageData_GetKey (IntPtr obj) static
Referenced by Oculus.Platform.Models.CloudStorageData.CloudStorageData().
ovr_CloudStorageMetadata_GetBucket()
static string Oculus.Platform.CAPI.ovr_CloudStorageMetadata_GetBucket (IntPtr obj) static
Referenced by Oculus.Platform.Models.CloudStorageMetadata.CloudStorageMetadata().
ovr_CloudStorageMetadata_GetCounter()
static long Oculus.Platform.CAPI.ovr_CloudStorageMetadata_GetCounter (IntPtr obj)
Referenced by Oculus.Platform.Models.CloudStorageMetadata.CloudStorageMetadata().
ovr_CloudStorageMetadata_GetDataSize()
static uint Oculus.Platform.CAPI.ovr_CloudStorageMetadata_GetDataSize (IntPtr obj)
Referenced by Oculus.Platform.Models.CloudStorageMetadata.CloudStorageMetadata().
ovr_CloudStorageMetadata_GetExtraData()
static string Oculus.Platform.CAPI.ovr_CloudStorageMetadata_GetExtraData (IntPtr obj) static
Referenced by Oculus.Platform.Models.CloudStorageMetadata.CloudStorageMetadata().
ovr_CloudStorageMetadata_GetKey()
static string Oculus.Platform.CAPI.ovr_CloudStorageMetadata_GetKey (IntPtr obj) static
Referenced by Oculus.Platform.Models.CloudStorageMetadata.CloudStorageMetadata().
ovr_CloudStorageMetadata_GetSaveTime()
static ulong Oculus.Platform.CAPI.ovr_CloudStorageMetadata_GetSaveTime (IntPtr obj)
Referenced by Oculus.Platform.Models.CloudStorageMetadata.CloudStorageMetadata().
ovr_CloudStorageMetadata_GetStatus()
static CloudStorageDataStatus Oculus.Platform.CAPI.ovr_CloudStorageMetadata_GetStatus (IntPtr obj)
Referenced by Oculus.Platform.Models.CloudStorageMetadata.CloudStorageMetadata().
ovr_CloudStorageMetadata_GetVersionHandle()
static string Oculus.Platform.CAPI.ovr_CloudStorageMetadata_GetVersionHandle (IntPtr obj) static
Referenced by Oculus.Platform.Models.CloudStorageMetadata.CloudStorageMetadata().
ovr_CloudStorageMetadataArray_GetElement()
static IntPtr Oculus.Platform.CAPI.ovr_CloudStorageMetadataArray_GetElement (IntPtr obj, UIntPtr index)
Referenced by Oculus.Platform.Models.CloudStorageMetadataList.CloudStorageMetadataList().
ovr_CloudStorageMetadataArray_GetNextUrl()
static string Oculus.Platform.CAPI.ovr_CloudStorageMetadataArray_GetNextUrl (IntPtr obj) static
Referenced by Oculus.Platform.Models.CloudStorageMetadataList.CloudStorageMetadataList().
ovr_CloudStorageMetadataArray_GetSize()
static UIntPtr Oculus.Platform.CAPI.ovr_CloudStorageMetadataArray_GetSize (IntPtr obj)
Referenced by Oculus.Platform.Models.CloudStorageMetadataList.CloudStorageMetadataList().
ovr_CloudStorageMetadataArray_HasNextPage()
static bool Oculus.Platform.CAPI.ovr_CloudStorageMetadataArray_HasNextPage (IntPtr obj)
ovr_CloudStorageUpdateResponse_GetBucket()
static string Oculus.Platform.CAPI.ovr_CloudStorageUpdateResponse_GetBucket (IntPtr obj) static
Referenced by Oculus.Platform.Models.CloudStorageUpdateResponse.CloudStorageUpdateResponse().
ovr_CloudStorageUpdateResponse_GetKey()
static string Oculus.Platform.CAPI.ovr_CloudStorageUpdateResponse_GetKey (IntPtr obj) static
Referenced by Oculus.Platform.Models.CloudStorageUpdateResponse.CloudStorageUpdateResponse().
ovr_CloudStorageUpdateResponse_GetStatus()
static CloudStorageUpdateStatus Oculus.Platform.CAPI.ovr_CloudStorageUpdateResponse_GetStatus (IntPtr obj)
Referenced by Oculus.Platform.Models.CloudStorageUpdateResponse.CloudStorageUpdateResponse().
ovr_CloudStorageUpdateResponse_GetVersionHandle()
static string Oculus.Platform.CAPI.ovr_CloudStorageUpdateResponse_GetVersionHandle (IntPtr obj) static
Referenced by Oculus.Platform.Models.CloudStorageUpdateResponse.CloudStorageUpdateResponse().
ovr_Colocation_GetCurrentMapUuid()
static ulong Oculus.Platform.CAPI.ovr_Colocation_GetCurrentMapUuid ()
ovr_Colocation_RequestMap()
static ulong Oculus.Platform.CAPI.ovr_Colocation_RequestMap (string uuid) static
ovr_Colocation_ShareMap()
static ulong Oculus.Platform.CAPI.ovr_Colocation_ShareMap (string uuid) static
ovr_CrashApplication()
static void Oculus.Platform.CAPI.ovr_CrashApplication ()
ovr_DataStore_Contains()
static uint Oculus.Platform.CAPI.ovr_DataStore_Contains (IntPtr obj, string key) static
ovr_DataStore_GetKey()
static string Oculus.Platform.CAPI.ovr_DataStore_GetKey (IntPtr obj, int index) static
Referenced by Oculus.Platform.CAPI.DataStoreFromNative().
ovr_DataStore_GetNumKeys()
static UIntPtr Oculus.Platform.CAPI.ovr_DataStore_GetNumKeys (IntPtr obj)
Referenced by Oculus.Platform.CAPI.DataStoreFromNative().
ovr_DataStore_GetValue()
static string Oculus.Platform.CAPI.ovr_DataStore_GetValue (IntPtr obj, string key) static
Referenced by Oculus.Platform.CAPI.DataStoreFromNative().
ovr_Destination_GetApiName()
static string Oculus.Platform.CAPI.ovr_Destination_GetApiName (IntPtr obj) static
Referenced by Oculus.Platform.Models.Destination.Destination().
ovr_Destination_GetDeeplinkMessage()
static string Oculus.Platform.CAPI.ovr_Destination_GetDeeplinkMessage (IntPtr obj) static
Referenced by Oculus.Platform.Models.Destination.Destination().
ovr_Destination_GetDisplayName()
static string Oculus.Platform.CAPI.ovr_Destination_GetDisplayName (IntPtr obj) static
Referenced by Oculus.Platform.Models.Destination.Destination().
ovr_DestinationArray_GetElement()
static IntPtr Oculus.Platform.CAPI.ovr_DestinationArray_GetElement (IntPtr obj, UIntPtr index)
Referenced by Oculus.Platform.Models.DestinationList.DestinationList().
ovr_DestinationArray_GetNextUrl()
static string Oculus.Platform.CAPI.ovr_DestinationArray_GetNextUrl (IntPtr obj) static
Referenced by Oculus.Platform.Models.DestinationList.DestinationList().
ovr_DestinationArray_GetSize()
static UIntPtr Oculus.Platform.CAPI.ovr_DestinationArray_GetSize (IntPtr obj)
Referenced by Oculus.Platform.Models.DestinationList.DestinationList().
ovr_DestinationArray_HasNextPage()
static bool Oculus.Platform.CAPI.ovr_DestinationArray_HasNextPage (IntPtr obj)
ovr_Entitlement_GetIsViewerEntitled()
static ulong Oculus.Platform.CAPI.ovr_Entitlement_GetIsViewerEntitled ()
ovr_Error_GetCode()
static int Oculus.Platform.CAPI.ovr_Error_GetCode (IntPtr obj)
Referenced by Oculus.Platform.Message< T >.Message().
ovr_Error_GetDisplayableMessage()
static string Oculus.Platform.CAPI.ovr_Error_GetDisplayableMessage (IntPtr obj) static
ovr_Error_GetHttpCode()
static int Oculus.Platform.CAPI.ovr_Error_GetHttpCode (IntPtr obj)
Referenced by Oculus.Platform.Message< T >.Message().
ovr_Error_GetMessage()
static string Oculus.Platform.CAPI.ovr_Error_GetMessage (IntPtr obj) static
Referenced by Oculus.Platform.Message< T >.Message().
ovr_FreeMessage()
static void Oculus.Platform.CAPI.ovr_FreeMessage (IntPtr message)
Referenced by Oculus.Platform.Message< T >.PopMessage().
ovr_GetLoggedInUserLocale()
static string Oculus.Platform.CAPI.ovr_GetLoggedInUserLocale () static
ovr_GraphAPI_Get()
static ulong Oculus.Platform.CAPI.ovr_GraphAPI_Get (string url) static
ovr_GraphAPI_Post()
static ulong Oculus.Platform.CAPI.ovr_GraphAPI_Post (string url) static
ovr_GroupPresence_Clear()
static ulong Oculus.Platform.CAPI.ovr_GroupPresence_Clear ()
ovr_GroupPresence_GetInvitableUsers()
static ulong Oculus.Platform.CAPI.ovr_GroupPresence_GetInvitableUsers (IntPtr options)
ovr_GroupPresence_GetSentInvites()
static ulong Oculus.Platform.CAPI.ovr_GroupPresence_GetSentInvites ()
ovr_GroupPresence_LaunchInvitePanel()
static ulong Oculus.Platform.CAPI.ovr_GroupPresence_LaunchInvitePanel (IntPtr options)
ovr_GroupPresence_LaunchMultiplayerErrorDialog()
static ulong Oculus.Platform.CAPI.ovr_GroupPresence_LaunchMultiplayerErrorDialog (IntPtr options)
ovr_GroupPresence_LaunchRejoinDialog()
static ulong Oculus.Platform.CAPI.ovr_GroupPresence_LaunchRejoinDialog (string lobby_session_id, string match_session_id, string destination_api_name) static
ovr_GroupPresence_LaunchRosterPanel()
static ulong Oculus.Platform.CAPI.ovr_GroupPresence_LaunchRosterPanel (IntPtr options)
ovr_GroupPresence_SendInvites()
static ulong Oculus.Platform.CAPI.ovr_GroupPresence_SendInvites (UInt64[] userIDs, uint userIDLength)
ovr_GroupPresence_Set()
static ulong Oculus.Platform.CAPI.ovr_GroupPresence_Set (IntPtr groupPresenceOptions)
ovr_GroupPresence_SetDestination()
static ulong Oculus.Platform.CAPI.ovr_GroupPresence_SetDestination (string api_name) static
ovr_GroupPresence_SetIsJoinable()
static ulong Oculus.Platform.CAPI.ovr_GroupPresence_SetIsJoinable (bool is_joinable)
ovr_GroupPresence_SetLobbySession()
static ulong Oculus.Platform.CAPI.ovr_GroupPresence_SetLobbySession (string id) static
ovr_GroupPresence_SetMatchSession()
static ulong Oculus.Platform.CAPI.ovr_GroupPresence_SetMatchSession (string id) static
ovr_GroupPresenceJoinIntent_GetDeeplinkMessage()
static string Oculus.Platform.CAPI.ovr_GroupPresenceJoinIntent_GetDeeplinkMessage (IntPtr obj) static
Referenced by Oculus.Platform.Models.GroupPresenceJoinIntent.GroupPresenceJoinIntent().
ovr_GroupPresenceJoinIntent_GetDestinationApiName()
static string Oculus.Platform.CAPI.ovr_GroupPresenceJoinIntent_GetDestinationApiName (IntPtr obj) static
Referenced by Oculus.Platform.Models.GroupPresenceJoinIntent.GroupPresenceJoinIntent().
ovr_GroupPresenceJoinIntent_GetLobbySessionId()
static string Oculus.Platform.CAPI.ovr_GroupPresenceJoinIntent_GetLobbySessionId (IntPtr obj) static
Referenced by Oculus.Platform.Models.GroupPresenceJoinIntent.GroupPresenceJoinIntent().
ovr_GroupPresenceJoinIntent_GetMatchSessionId()
static string Oculus.Platform.CAPI.ovr_GroupPresenceJoinIntent_GetMatchSessionId (IntPtr obj) static
Referenced by Oculus.Platform.Models.GroupPresenceJoinIntent.GroupPresenceJoinIntent().
ovr_GroupPresenceLeaveIntent_GetDestinationApiName()
static string Oculus.Platform.CAPI.ovr_GroupPresenceLeaveIntent_GetDestinationApiName (IntPtr obj) static
Referenced by Oculus.Platform.Models.GroupPresenceLeaveIntent.GroupPresenceLeaveIntent().
ovr_GroupPresenceLeaveIntent_GetLobbySessionId()
static string Oculus.Platform.CAPI.ovr_GroupPresenceLeaveIntent_GetLobbySessionId (IntPtr obj) static
Referenced by Oculus.Platform.Models.GroupPresenceLeaveIntent.GroupPresenceLeaveIntent().
ovr_GroupPresenceLeaveIntent_GetMatchSessionId()
static string Oculus.Platform.CAPI.ovr_GroupPresenceLeaveIntent_GetMatchSessionId (IntPtr obj) static
Referenced by Oculus.Platform.Models.GroupPresenceLeaveIntent.GroupPresenceLeaveIntent().
ovr_GroupPresenceOptions_Create()
static IntPtr Oculus.Platform.CAPI.ovr_GroupPresenceOptions_Create ()
Referenced by Oculus.Platform.GroupPresenceOptions.GroupPresenceOptions().
ovr_GroupPresenceOptions_Destroy()
static void Oculus.Platform.CAPI.ovr_GroupPresenceOptions_Destroy (IntPtr handle)
ovr_GroupPresenceOptions_SetDestinationApiName()
static void Oculus.Platform.CAPI.ovr_GroupPresenceOptions_SetDestinationApiName (IntPtr handle, string value) static
Referenced by Oculus.Platform.GroupPresenceOptions.SetDestinationApiName().
ovr_GroupPresenceOptions_SetIsJoinable()
static void Oculus.Platform.CAPI.ovr_GroupPresenceOptions_SetIsJoinable (IntPtr handle, bool value)
Referenced by Oculus.Platform.GroupPresenceOptions.SetIsJoinable().
ovr_GroupPresenceOptions_SetLobbySessionId()
static void Oculus.Platform.CAPI.ovr_GroupPresenceOptions_SetLobbySessionId (IntPtr handle, string value) static
Referenced by Oculus.Platform.GroupPresenceOptions.SetLobbySessionId().
ovr_GroupPresenceOptions_SetMatchSessionId()
static void Oculus.Platform.CAPI.ovr_GroupPresenceOptions_SetMatchSessionId (IntPtr handle, string value) static
Referenced by Oculus.Platform.GroupPresenceOptions.SetMatchSessionId().
ovr_HTTP_Get()
static ulong Oculus.Platform.CAPI.ovr_HTTP_Get (string url) static
ovr_HTTP_GetToFile()
static ulong Oculus.Platform.CAPI.ovr_HTTP_GetToFile (string url, string diskFile) static
ovr_HTTP_GetWithMessageType()
static ulong Oculus.Platform.CAPI.ovr_HTTP_GetWithMessageType (string url, int messageType)
ovr_HTTP_MultiPartPost()
static ulong Oculus.Platform.CAPI.ovr_HTTP_MultiPartPost (string url, string filepath_param_name, string filepath, string access_token, ovrKeyValuePair[] post_params) static
ovr_HTTP_Post()
static ulong Oculus.Platform.CAPI.ovr_HTTP_Post (string url) static
ovr_HTTP_StartTransfer()
static ulong Oculus.Platform.CAPI.ovr_HTTP_StartTransfer (string url, ovrKeyValuePair[] headers) static
ovr_HTTP_Write()
static bool Oculus.Platform.CAPI.ovr_HTTP_Write (ulong transferId, byte[] bytes, UIntPtr length)
ovr_HTTP_WriteEOM()
static void Oculus.Platform.CAPI.ovr_HTTP_WriteEOM (ulong transferId)
ovr_HttpTransferUpdate_GetBytes()
static IntPtr Oculus.Platform.CAPI.ovr_HttpTransferUpdate_GetBytes (IntPtr obj)
ovr_HttpTransferUpdate_GetID()
static ulong Oculus.Platform.CAPI.ovr_HttpTransferUpdate_GetID (IntPtr obj)
Referenced by Oculus.Platform.Models.HttpTransferUpdate.HttpTransferUpdate().
ovr_HttpTransferUpdate_GetSize()
static UIntPtr Oculus.Platform.CAPI.ovr_HttpTransferUpdate_GetSize (IntPtr obj)
Referenced by Oculus.Platform.Models.HttpTransferUpdate.HttpTransferUpdate().
ovr_HttpTransferUpdate_IsCompleted()
static bool Oculus.Platform.CAPI.ovr_HttpTransferUpdate_IsCompleted (IntPtr obj)
Referenced by Oculus.Platform.Models.HttpTransferUpdate.HttpTransferUpdate().
ovr_IAP_ConsumePurchase()
static ulong Oculus.Platform.CAPI.ovr_IAP_ConsumePurchase (string sku) static
ovr_IAP_GetProductsBySKU()
static ulong Oculus.Platform.CAPI.ovr_IAP_GetProductsBySKU (string[] skus, int count)
ovr_IAP_GetViewerPurchases()
static ulong Oculus.Platform.CAPI.ovr_IAP_GetViewerPurchases ()
ovr_IAP_GetViewerPurchasesDurableCache()
static ulong Oculus.Platform.CAPI.ovr_IAP_GetViewerPurchasesDurableCache ()
ovr_IAP_LaunchCheckoutFlow()
static ulong Oculus.Platform.CAPI.ovr_IAP_LaunchCheckoutFlow (string sku) static
ovr_InstalledApplication_GetApplicationId()
static string Oculus.Platform.CAPI.ovr_InstalledApplication_GetApplicationId (IntPtr obj) static
Referenced by Oculus.Platform.Models.InstalledApplication.InstalledApplication().
ovr_InstalledApplication_GetPackageName()
static string Oculus.Platform.CAPI.ovr_InstalledApplication_GetPackageName (IntPtr obj) static
Referenced by Oculus.Platform.Models.InstalledApplication.InstalledApplication().
ovr_InstalledApplication_GetStatus()
static string Oculus.Platform.CAPI.ovr_InstalledApplication_GetStatus (IntPtr obj) static
Referenced by Oculus.Platform.Models.InstalledApplication.InstalledApplication().
ovr_InstalledApplication_GetVersionCode()
static int Oculus.Platform.CAPI.ovr_InstalledApplication_GetVersionCode (IntPtr obj)
Referenced by Oculus.Platform.Models.InstalledApplication.InstalledApplication().
ovr_InstalledApplication_GetVersionName()
static string Oculus.Platform.CAPI.ovr_InstalledApplication_GetVersionName (IntPtr obj) static
Referenced by Oculus.Platform.Models.InstalledApplication.InstalledApplication().
ovr_InstalledApplicationArray_GetElement()
static IntPtr Oculus.Platform.CAPI.ovr_InstalledApplicationArray_GetElement (IntPtr obj, UIntPtr index)
Referenced by Oculus.Platform.Models.InstalledApplicationList.InstalledApplicationList().
ovr_InstalledApplicationArray_GetSize()
static UIntPtr Oculus.Platform.CAPI.ovr_InstalledApplicationArray_GetSize (IntPtr obj)
Referenced by Oculus.Platform.Models.InstalledApplicationList.InstalledApplicationList().
ovr_InviteOptions_AddSuggestedUser()
static void Oculus.Platform.CAPI.ovr_InviteOptions_AddSuggestedUser (IntPtr handle, UInt64 value)
Referenced by Oculus.Platform.InviteOptions.AddSuggestedUser().
ovr_InviteOptions_ClearSuggestedUsers()
static void Oculus.Platform.CAPI.ovr_InviteOptions_ClearSuggestedUsers (IntPtr handle)
Referenced by Oculus.Platform.InviteOptions.ClearSuggestedUsers().
ovr_InviteOptions_Create()
static IntPtr Oculus.Platform.CAPI.ovr_InviteOptions_Create ()
Referenced by Oculus.Platform.InviteOptions.InviteOptions().
ovr_InviteOptions_Destroy()
static void Oculus.Platform.CAPI.ovr_InviteOptions_Destroy (IntPtr handle)
ovr_InvitePanelResultInfo_GetInvitesSent()
static bool Oculus.Platform.CAPI.ovr_InvitePanelResultInfo_GetInvitesSent (IntPtr obj)
Referenced by Oculus.Platform.Models.InvitePanelResultInfo.InvitePanelResultInfo().
ovr_LanguagePack_GetCurrent()
static ulong Oculus.Platform.CAPI.ovr_LanguagePack_GetCurrent ()
ovr_LanguagePack_SetCurrent()
static ulong Oculus.Platform.CAPI.ovr_LanguagePack_SetCurrent (string tag) static
ovr_LanguagePackInfo_GetEnglishName()
static string Oculus.Platform.CAPI.ovr_LanguagePackInfo_GetEnglishName (IntPtr obj) static
Referenced by Oculus.Platform.Models.LanguagePackInfo.LanguagePackInfo().
ovr_LanguagePackInfo_GetNativeName()
static string Oculus.Platform.CAPI.ovr_LanguagePackInfo_GetNativeName (IntPtr obj) static
Referenced by Oculus.Platform.Models.LanguagePackInfo.LanguagePackInfo().
ovr_LanguagePackInfo_GetTag()
static string Oculus.Platform.CAPI.ovr_LanguagePackInfo_GetTag (IntPtr obj) static
Referenced by Oculus.Platform.Models.LanguagePackInfo.LanguagePackInfo().
ovr_LaunchBlockFlowResult_GetDidBlock()
static bool Oculus.Platform.CAPI.ovr_LaunchBlockFlowResult_GetDidBlock (IntPtr obj)
Referenced by Oculus.Platform.Models.LaunchBlockFlowResult.LaunchBlockFlowResult().
ovr_LaunchBlockFlowResult_GetDidCancel()
static bool Oculus.Platform.CAPI.ovr_LaunchBlockFlowResult_GetDidCancel (IntPtr obj)
Referenced by Oculus.Platform.Models.LaunchBlockFlowResult.LaunchBlockFlowResult().
ovr_LaunchDetails_GetDeeplinkMessage()
static string Oculus.Platform.CAPI.ovr_LaunchDetails_GetDeeplinkMessage (IntPtr obj) static
Referenced by Oculus.Platform.Models.LaunchDetails.LaunchDetails().
ovr_LaunchDetails_GetDestinationApiName()
static string Oculus.Platform.CAPI.ovr_LaunchDetails_GetDestinationApiName (IntPtr obj) static
Referenced by Oculus.Platform.Models.LaunchDetails.LaunchDetails().
ovr_LaunchDetails_GetLaunchSource()
static string Oculus.Platform.CAPI.ovr_LaunchDetails_GetLaunchSource (IntPtr obj) static
Referenced by Oculus.Platform.Models.LaunchDetails.LaunchDetails().
ovr_LaunchDetails_GetLaunchType()
static LaunchType Oculus.Platform.CAPI.ovr_LaunchDetails_GetLaunchType (IntPtr obj)
Referenced by Oculus.Platform.Models.LaunchDetails.LaunchDetails().
ovr_LaunchDetails_GetRoomID()
static UInt64 Oculus.Platform.CAPI.ovr_LaunchDetails_GetRoomID (IntPtr obj)
Referenced by Oculus.Platform.Models.LaunchDetails.LaunchDetails().
ovr_LaunchDetails_GetTrackingID()
static string Oculus.Platform.CAPI.ovr_LaunchDetails_GetTrackingID (IntPtr obj) static
Referenced by Oculus.Platform.Models.LaunchDetails.LaunchDetails().
ovr_LaunchDetails_GetUsers()
static IntPtr Oculus.Platform.CAPI.ovr_LaunchDetails_GetUsers (IntPtr obj)
Referenced by Oculus.Platform.Models.LaunchDetails.LaunchDetails().
ovr_LaunchFriendRequestFlowResult_GetDidCancel()
static bool Oculus.Platform.CAPI.ovr_LaunchFriendRequestFlowResult_GetDidCancel (IntPtr obj)
Referenced by Oculus.Platform.Models.LaunchFriendRequestFlowResult.LaunchFriendRequestFlowResult().
ovr_LaunchFriendRequestFlowResult_GetDidSendRequest()
static bool Oculus.Platform.CAPI.ovr_LaunchFriendRequestFlowResult_GetDidSendRequest (IntPtr obj)
Referenced by Oculus.Platform.Models.LaunchFriendRequestFlowResult.LaunchFriendRequestFlowResult().
ovr_LaunchInvitePanelFlowResult_GetInvitedUsers()
static IntPtr Oculus.Platform.CAPI.ovr_LaunchInvitePanelFlowResult_GetInvitedUsers (IntPtr obj)
Referenced by Oculus.Platform.Models.LaunchInvitePanelFlowResult.LaunchInvitePanelFlowResult().
ovr_LaunchReportFlowResult_GetDidCancel()
static bool Oculus.Platform.CAPI.ovr_LaunchReportFlowResult_GetDidCancel (IntPtr obj)
Referenced by Oculus.Platform.Models.LaunchReportFlowResult.LaunchReportFlowResult().
ovr_LaunchReportFlowResult_GetUserReportId()
static UInt64 Oculus.Platform.CAPI.ovr_LaunchReportFlowResult_GetUserReportId (IntPtr obj)
Referenced by Oculus.Platform.Models.LaunchReportFlowResult.LaunchReportFlowResult().
ovr_LaunchUnblockFlowResult_GetDidCancel()
static bool Oculus.Platform.CAPI.ovr_LaunchUnblockFlowResult_GetDidCancel (IntPtr obj)
Referenced by Oculus.Platform.Models.LaunchUnblockFlowResult.LaunchUnblockFlowResult().
ovr_LaunchUnblockFlowResult_GetDidUnblock()
static bool Oculus.Platform.CAPI.ovr_LaunchUnblockFlowResult_GetDidUnblock (IntPtr obj)
Referenced by Oculus.Platform.Models.LaunchUnblockFlowResult.LaunchUnblockFlowResult().
ovr_Leaderboard_Get()
static ulong Oculus.Platform.CAPI.ovr_Leaderboard_Get (string leaderboardName) static
ovr_Leaderboard_GetApiName()
static string Oculus.Platform.CAPI.ovr_Leaderboard_GetApiName (IntPtr obj) static
Referenced by Oculus.Platform.Models.Leaderboard.Leaderboard().
ovr_Leaderboard_GetDestination()
static IntPtr Oculus.Platform.CAPI.ovr_Leaderboard_GetDestination (IntPtr obj)
Referenced by Oculus.Platform.Models.Leaderboard.Leaderboard().
ovr_Leaderboard_GetEntries()
static ulong Oculus.Platform.CAPI.ovr_Leaderboard_GetEntries (string leaderboardName, int limit, LeaderboardFilterType filter, LeaderboardStartAt startAt) static
ovr_Leaderboard_GetEntriesAfterRank()
static ulong Oculus.Platform.CAPI.ovr_Leaderboard_GetEntriesAfterRank (string leaderboardName, int limit, ulong afterRank) static
ovr_Leaderboard_GetEntriesByIds()
static ulong Oculus.Platform.CAPI.ovr_Leaderboard_GetEntriesByIds (string leaderboardName, int limit, LeaderboardStartAt startAt, UInt64[] userIDs, uint userIDLength) static
ovr_Leaderboard_GetID()
static UInt64 Oculus.Platform.CAPI.ovr_Leaderboard_GetID (IntPtr obj)
Referenced by Oculus.Platform.Models.Leaderboard.Leaderboard().
ovr_Leaderboard_GetNextEntries()
static ulong Oculus.Platform.CAPI.ovr_Leaderboard_GetNextEntries (IntPtr handle)
ovr_Leaderboard_GetPreviousEntries()
static ulong Oculus.Platform.CAPI.ovr_Leaderboard_GetPreviousEntries (IntPtr handle)
ovr_Leaderboard_WriteEntry()
static ulong Oculus.Platform.CAPI.ovr_Leaderboard_WriteEntry (string leaderboardName, long score, byte[] extraData, uint extraDataLength, bool forceUpdate) static
ovr_Leaderboard_WriteEntryWithSupplementaryMetric()
static ulong Oculus.Platform.CAPI.ovr_Leaderboard_WriteEntryWithSupplementaryMetric (string leaderboardName, long score, long supplementaryMetric, byte[] extraData, uint extraDataLength, bool forceUpdate) static
ovr_LeaderboardArray_GetElement()
static IntPtr Oculus.Platform.CAPI.ovr_LeaderboardArray_GetElement (IntPtr obj, UIntPtr index)
Referenced by Oculus.Platform.Models.LeaderboardList.LeaderboardList().
ovr_LeaderboardArray_GetNextUrl()
static string Oculus.Platform.CAPI.ovr_LeaderboardArray_GetNextUrl (IntPtr obj) static
Referenced by Oculus.Platform.Models.LeaderboardList.LeaderboardList().
ovr_LeaderboardArray_GetSize()
static UIntPtr Oculus.Platform.CAPI.ovr_LeaderboardArray_GetSize (IntPtr obj)
Referenced by Oculus.Platform.Models.LeaderboardList.LeaderboardList().
ovr_LeaderboardArray_HasNextPage()
static bool Oculus.Platform.CAPI.ovr_LeaderboardArray_HasNextPage (IntPtr obj)
ovr_LeaderboardEntry_GetDisplayScore()
static string Oculus.Platform.CAPI.ovr_LeaderboardEntry_GetDisplayScore (IntPtr obj) static
Referenced by Oculus.Platform.Models.LeaderboardEntry.LeaderboardEntry().
ovr_LeaderboardEntry_GetExtraData()
static byte[] Oculus.Platform.CAPI.ovr_LeaderboardEntry_GetExtraData (IntPtr obj) static
Referenced by Oculus.Platform.Models.LeaderboardEntry.LeaderboardEntry().
ovr_LeaderboardEntry_GetExtraDataLength()
static uint Oculus.Platform.CAPI.ovr_LeaderboardEntry_GetExtraDataLength (IntPtr obj)
Referenced by Oculus.Platform.CAPI.ovr_ChallengeEntry_GetExtraData(), and Oculus.Platform.CAPI.ovr_LeaderboardEntry_GetExtraData().
ovr_LeaderboardEntry_GetID()
static UInt64 Oculus.Platform.CAPI.ovr_LeaderboardEntry_GetID (IntPtr obj)
Referenced by Oculus.Platform.Models.LeaderboardEntry.LeaderboardEntry().
ovr_LeaderboardEntry_GetRank()
static int Oculus.Platform.CAPI.ovr_LeaderboardEntry_GetRank (IntPtr obj)
Referenced by Oculus.Platform.Models.LeaderboardEntry.LeaderboardEntry().
ovr_LeaderboardEntry_GetScore()
static long Oculus.Platform.CAPI.ovr_LeaderboardEntry_GetScore (IntPtr obj)
Referenced by Oculus.Platform.Models.LeaderboardEntry.LeaderboardEntry().
ovr_LeaderboardEntry_GetSupplementaryMetric()
static IntPtr Oculus.Platform.CAPI.ovr_LeaderboardEntry_GetSupplementaryMetric (IntPtr obj)
Referenced by Oculus.Platform.Models.LeaderboardEntry.LeaderboardEntry().
ovr_LeaderboardEntry_GetTimestamp()
static DateTime Oculus.Platform.CAPI.ovr_LeaderboardEntry_GetTimestamp (IntPtr obj) static
Referenced by Oculus.Platform.Models.LeaderboardEntry.LeaderboardEntry().
ovr_LeaderboardEntry_GetUser()
static IntPtr Oculus.Platform.CAPI.ovr_LeaderboardEntry_GetUser (IntPtr obj)
Referenced by Oculus.Platform.Models.LeaderboardEntry.LeaderboardEntry().
ovr_LeaderboardEntryArray_GetElement()
static IntPtr Oculus.Platform.CAPI.ovr_LeaderboardEntryArray_GetElement (IntPtr obj, UIntPtr index)
Referenced by Oculus.Platform.Models.LeaderboardEntryList.LeaderboardEntryList().
ovr_LeaderboardEntryArray_GetNextUrl()
static string Oculus.Platform.CAPI.ovr_LeaderboardEntryArray_GetNextUrl (IntPtr obj) static
Referenced by Oculus.Platform.Models.LeaderboardEntryList.LeaderboardEntryList().
ovr_LeaderboardEntryArray_GetPreviousUrl()
static string Oculus.Platform.CAPI.ovr_LeaderboardEntryArray_GetPreviousUrl (IntPtr obj) static
Referenced by Oculus.Platform.Models.LeaderboardEntryList.LeaderboardEntryList().
ovr_LeaderboardEntryArray_GetSize()
static UIntPtr Oculus.Platform.CAPI.ovr_LeaderboardEntryArray_GetSize (IntPtr obj)
Referenced by Oculus.Platform.Models.LeaderboardEntryList.LeaderboardEntryList().
ovr_LeaderboardEntryArray_GetTotalCount()
static ulong Oculus.Platform.CAPI.ovr_LeaderboardEntryArray_GetTotalCount (IntPtr obj)
Referenced by Oculus.Platform.Models.LeaderboardEntryList.LeaderboardEntryList().
ovr_LeaderboardEntryArray_HasNextPage()
static bool Oculus.Platform.CAPI.ovr_LeaderboardEntryArray_HasNextPage (IntPtr obj)
ovr_LeaderboardEntryArray_HasPreviousPage()
static bool Oculus.Platform.CAPI.ovr_LeaderboardEntryArray_HasPreviousPage (IntPtr obj)
ovr_LeaderboardUpdateStatus_GetDidUpdate()
static bool Oculus.Platform.CAPI.ovr_LeaderboardUpdateStatus_GetDidUpdate (IntPtr obj)
Referenced by Oculus.Platform.MessageWithLeaderboardDidUpdate.GetDataFromMessage().
ovr_LeaderboardUpdateStatus_GetUpdatedChallengeId()
static UInt64 Oculus.Platform.CAPI.ovr_LeaderboardUpdateStatus_GetUpdatedChallengeId (IntPtr obj, uint index)
ovr_LeaderboardUpdateStatus_GetUpdatedChallengeIdsSize()
static uint Oculus.Platform.CAPI.ovr_LeaderboardUpdateStatus_GetUpdatedChallengeIdsSize (IntPtr obj)
ovr_LinkedAccount_GetAccessToken()
static string Oculus.Platform.CAPI.ovr_LinkedAccount_GetAccessToken (IntPtr obj) static
Referenced by Oculus.Platform.Models.LinkedAccount.LinkedAccount().
ovr_LinkedAccount_GetServiceProvider()
static ServiceProvider Oculus.Platform.CAPI.ovr_LinkedAccount_GetServiceProvider (IntPtr obj)
Referenced by Oculus.Platform.Models.LinkedAccount.LinkedAccount().
ovr_LinkedAccount_GetUserId()
static string Oculus.Platform.CAPI.ovr_LinkedAccount_GetUserId (IntPtr obj) static
Referenced by Oculus.Platform.Models.LinkedAccount.LinkedAccount().
ovr_LinkedAccountArray_GetElement()
static IntPtr Oculus.Platform.CAPI.ovr_LinkedAccountArray_GetElement (IntPtr obj, UIntPtr index)
Referenced by Oculus.Platform.Models.LinkedAccountList.LinkedAccountList().
ovr_LinkedAccountArray_GetSize()
static UIntPtr Oculus.Platform.CAPI.ovr_LinkedAccountArray_GetSize (IntPtr obj)
Referenced by Oculus.Platform.Models.LinkedAccountList.LinkedAccountList().
ovr_Livestreaming_IsAllowedForApplication()
static ulong Oculus.Platform.CAPI.ovr_Livestreaming_IsAllowedForApplication (string packageName) static
ovr_Livestreaming_StartPartyStream()
static ulong Oculus.Platform.CAPI.ovr_Livestreaming_StartPartyStream ()
ovr_Livestreaming_StartStream()
static ulong Oculus.Platform.CAPI.ovr_Livestreaming_StartStream (LivestreamingAudience audience, LivestreamingMicrophoneStatus micStatus)
ovr_Livestreaming_StopPartyStream()
static ulong Oculus.Platform.CAPI.ovr_Livestreaming_StopPartyStream ()
ovr_Livestreaming_StopStream()
static ulong Oculus.Platform.CAPI.ovr_Livestreaming_StopStream ()
ovr_Livestreaming_UpdateMicStatus()
static ulong Oculus.Platform.CAPI.ovr_Livestreaming_UpdateMicStatus (LivestreamingMicrophoneStatus micStatus)
ovr_LivestreamingApplicationStatus_GetStreamingEnabled()
static bool Oculus.Platform.CAPI.ovr_LivestreamingApplicationStatus_GetStreamingEnabled (IntPtr obj)
Referenced by Oculus.Platform.Models.LivestreamingApplicationStatus.LivestreamingApplicationStatus().
ovr_LivestreamingStartResult_GetStreamingResult()
static LivestreamingStartStatus Oculus.Platform.CAPI.ovr_LivestreamingStartResult_GetStreamingResult (IntPtr obj)
Referenced by Oculus.Platform.Models.LivestreamingStartResult.LivestreamingStartResult().
ovr_LivestreamingStatus_GetCommentsVisible()
static bool Oculus.Platform.CAPI.ovr_LivestreamingStatus_GetCommentsVisible (IntPtr obj)
Referenced by Oculus.Platform.Models.LivestreamingStatus.LivestreamingStatus().
ovr_LivestreamingStatus_GetIsPaused()
static bool Oculus.Platform.CAPI.ovr_LivestreamingStatus_GetIsPaused (IntPtr obj)
Referenced by Oculus.Platform.Models.LivestreamingStatus.LivestreamingStatus().
ovr_LivestreamingStatus_GetLivestreamingEnabled()
static bool Oculus.Platform.CAPI.ovr_LivestreamingStatus_GetLivestreamingEnabled (IntPtr obj)
Referenced by Oculus.Platform.Models.LivestreamingStatus.LivestreamingStatus().
ovr_LivestreamingStatus_GetLivestreamingType()
static int Oculus.Platform.CAPI.ovr_LivestreamingStatus_GetLivestreamingType (IntPtr obj)
Referenced by Oculus.Platform.Models.LivestreamingStatus.LivestreamingStatus().
ovr_LivestreamingStatus_GetMicEnabled()
static bool Oculus.Platform.CAPI.ovr_LivestreamingStatus_GetMicEnabled (IntPtr obj)
Referenced by Oculus.Platform.Models.LivestreamingStatus.LivestreamingStatus().
ovr_LivestreamingVideoStats_GetCommentCount()
static int Oculus.Platform.CAPI.ovr_LivestreamingVideoStats_GetCommentCount (IntPtr obj)
Referenced by Oculus.Platform.Models.LivestreamingVideoStats.LivestreamingVideoStats().
ovr_LivestreamingVideoStats_GetReactionCount()
static int Oculus.Platform.CAPI.ovr_LivestreamingVideoStats_GetReactionCount (IntPtr obj)
Referenced by Oculus.Platform.Models.LivestreamingVideoStats.LivestreamingVideoStats().
ovr_LivestreamingVideoStats_GetTotalViews()
static string Oculus.Platform.CAPI.ovr_LivestreamingVideoStats_GetTotalViews (IntPtr obj) static
Referenced by Oculus.Platform.Models.LivestreamingVideoStats.LivestreamingVideoStats().
ovr_Log_NewEvent()
static void Oculus.Platform.CAPI.ovr_Log_NewEvent (IntPtr eventName, IntPtr[] values, UIntPtr length)
Referenced by Oculus.Platform.CAPI.LogNewEvent().
ovr_Matchmaking_Browse()
static ulong Oculus.Platform.CAPI.ovr_Matchmaking_Browse (string pool, IntPtr customQueryData) static
ovr_Matchmaking_Browse2()
static ulong Oculus.Platform.CAPI.ovr_Matchmaking_Browse2 (string pool, IntPtr matchmakingOptions) static
ovr_Matchmaking_Cancel()
static ulong Oculus.Platform.CAPI.ovr_Matchmaking_Cancel (string pool, string requestHash) static
ovr_Matchmaking_Cancel2()
static ulong Oculus.Platform.CAPI.ovr_Matchmaking_Cancel2 ()
ovr_Matchmaking_CreateAndEnqueueRoom()
static ulong Oculus.Platform.CAPI.ovr_Matchmaking_CreateAndEnqueueRoom (string pool, uint maxUsers, bool subscribeToUpdates, IntPtr customQueryData) static
ovr_Matchmaking_CreateAndEnqueueRoom2()
static ulong Oculus.Platform.CAPI.ovr_Matchmaking_CreateAndEnqueueRoom2 (string pool, IntPtr matchmakingOptions) static
ovr_Matchmaking_CreateRoom()
static ulong Oculus.Platform.CAPI.ovr_Matchmaking_CreateRoom (string pool, uint maxUsers, bool subscribeToUpdates) static
ovr_Matchmaking_CreateRoom2()
static ulong Oculus.Platform.CAPI.ovr_Matchmaking_CreateRoom2 (string pool, IntPtr matchmakingOptions) static
ovr_Matchmaking_Enqueue()
static ulong Oculus.Platform.CAPI.ovr_Matchmaking_Enqueue (string pool, IntPtr customQueryData) static
ovr_Matchmaking_Enqueue2()
static ulong Oculus.Platform.CAPI.ovr_Matchmaking_Enqueue2 (string pool, IntPtr matchmakingOptions) static
ovr_Matchmaking_EnqueueRoom()
static ulong Oculus.Platform.CAPI.ovr_Matchmaking_EnqueueRoom (UInt64 roomID, IntPtr customQueryData)
ovr_Matchmaking_EnqueueRoom2()
static ulong Oculus.Platform.CAPI.ovr_Matchmaking_EnqueueRoom2 (UInt64 roomID, IntPtr matchmakingOptions)
ovr_Matchmaking_GetAdminSnapshot()
static ulong Oculus.Platform.CAPI.ovr_Matchmaking_GetAdminSnapshot ()
ovr_Matchmaking_GetStats()
static ulong Oculus.Platform.CAPI.ovr_Matchmaking_GetStats (string pool, uint maxLevel, MatchmakingStatApproach approach) static
ovr_Matchmaking_JoinRoom()
static ulong Oculus.Platform.CAPI.ovr_Matchmaking_JoinRoom (UInt64 roomID, bool subscribeToUpdates)
ovr_Matchmaking_ReportResultInsecure()
static ulong Oculus.Platform.CAPI.ovr_Matchmaking_ReportResultInsecure (UInt64 roomID, ovrKeyValuePair[] data) static
ovr_Matchmaking_StartMatch()
static ulong Oculus.Platform.CAPI.ovr_Matchmaking_StartMatch (UInt64 roomID)
ovr_MatchmakingAdminSnapshot_GetCandidates()
static IntPtr Oculus.Platform.CAPI.ovr_MatchmakingAdminSnapshot_GetCandidates (IntPtr obj)
Referenced by Oculus.Platform.Models.MatchmakingAdminSnapshot.MatchmakingAdminSnapshot().
ovr_MatchmakingAdminSnapshot_GetMyCurrentThreshold()
static double Oculus.Platform.CAPI.ovr_MatchmakingAdminSnapshot_GetMyCurrentThreshold (IntPtr obj)
Referenced by Oculus.Platform.Models.MatchmakingAdminSnapshot.MatchmakingAdminSnapshot().
ovr_MatchmakingAdminSnapshotCandidate_GetCanMatch()
static bool Oculus.Platform.CAPI.ovr_MatchmakingAdminSnapshotCandidate_GetCanMatch (IntPtr obj)
Referenced by Oculus.Platform.Models.MatchmakingAdminSnapshotCandidate.MatchmakingAdminSnapshotCandidate().
ovr_MatchmakingAdminSnapshotCandidate_GetMyTotalScore()
static double Oculus.Platform.CAPI.ovr_MatchmakingAdminSnapshotCandidate_GetMyTotalScore (IntPtr obj)
Referenced by Oculus.Platform.Models.MatchmakingAdminSnapshotCandidate.MatchmakingAdminSnapshotCandidate().
ovr_MatchmakingAdminSnapshotCandidate_GetTheirCurrentThreshold()
static double Oculus.Platform.CAPI.ovr_MatchmakingAdminSnapshotCandidate_GetTheirCurrentThreshold (IntPtr obj)
Referenced by Oculus.Platform.Models.MatchmakingAdminSnapshotCandidate.MatchmakingAdminSnapshotCandidate().
ovr_MatchmakingAdminSnapshotCandidate_GetTheirTotalScore()
static double Oculus.Platform.CAPI.ovr_MatchmakingAdminSnapshotCandidate_GetTheirTotalScore (IntPtr obj)
Referenced by Oculus.Platform.Models.MatchmakingAdminSnapshotCandidate.MatchmakingAdminSnapshotCandidate().
ovr_MatchmakingAdminSnapshotCandidate_GetTraceId()
static string Oculus.Platform.CAPI.ovr_MatchmakingAdminSnapshotCandidate_GetTraceId (IntPtr obj) static
Referenced by Oculus.Platform.Models.MatchmakingAdminSnapshotCandidate.MatchmakingAdminSnapshotCandidate().
ovr_MatchmakingAdminSnapshotCandidateArray_GetElement()
static IntPtr Oculus.Platform.CAPI.ovr_MatchmakingAdminSnapshotCandidateArray_GetElement (IntPtr obj, UIntPtr index)
Referenced by Oculus.Platform.Models.MatchmakingAdminSnapshotCandidateList.MatchmakingAdminSnapshotCandidateList().
ovr_MatchmakingAdminSnapshotCandidateArray_GetSize()
static UIntPtr Oculus.Platform.CAPI.ovr_MatchmakingAdminSnapshotCandidateArray_GetSize (IntPtr obj)
Referenced by Oculus.Platform.Models.MatchmakingAdminSnapshotCandidateList.MatchmakingAdminSnapshotCandidateList().
ovr_MatchmakingBrowseResult_GetEnqueueResult()
static IntPtr Oculus.Platform.CAPI.ovr_MatchmakingBrowseResult_GetEnqueueResult (IntPtr obj)
Referenced by Oculus.Platform.Models.MatchmakingBrowseResult.MatchmakingBrowseResult().
ovr_MatchmakingBrowseResult_GetRooms()
static IntPtr Oculus.Platform.CAPI.ovr_MatchmakingBrowseResult_GetRooms (IntPtr obj)
Referenced by Oculus.Platform.Models.MatchmakingBrowseResult.MatchmakingBrowseResult().
ovr_MatchmakingCandidate_GetEntryHash()
static string Oculus.Platform.CAPI.ovr_MatchmakingCandidate_GetEntryHash (IntPtr obj) static
ovr_MatchmakingCandidate_GetUserId()
static ulong Oculus.Platform.CAPI.ovr_MatchmakingCandidate_GetUserId (IntPtr obj)
ovr_MatchmakingCandidateArray_GetElement()
static IntPtr Oculus.Platform.CAPI.ovr_MatchmakingCandidateArray_GetElement (IntPtr obj, UIntPtr index)
ovr_MatchmakingCandidateArray_GetNextUrl()
static string Oculus.Platform.CAPI.ovr_MatchmakingCandidateArray_GetNextUrl (IntPtr obj) static
ovr_MatchmakingCandidateArray_GetSize()
static UIntPtr Oculus.Platform.CAPI.ovr_MatchmakingCandidateArray_GetSize (IntPtr obj)
ovr_MatchmakingCandidateArray_HasNextPage()
static bool Oculus.Platform.CAPI.ovr_MatchmakingCandidateArray_HasNextPage (IntPtr obj)
ovr_MatchmakingEnqueuedUser_GetAdditionalUserID()
static UInt64 Oculus.Platform.CAPI.ovr_MatchmakingEnqueuedUser_GetAdditionalUserID (IntPtr obj, uint index)
ovr_MatchmakingEnqueuedUser_GetAdditionalUserIDsSize()
static uint Oculus.Platform.CAPI.ovr_MatchmakingEnqueuedUser_GetAdditionalUserIDsSize (IntPtr obj)
ovr_MatchmakingEnqueuedUser_GetCustomData()
static IntPtr Oculus.Platform.CAPI.ovr_MatchmakingEnqueuedUser_GetCustomData (IntPtr obj)
Referenced by Oculus.Platform.Models.MatchmakingEnqueuedUser.MatchmakingEnqueuedUser().
ovr_MatchmakingEnqueuedUser_GetUser()
static IntPtr Oculus.Platform.CAPI.ovr_MatchmakingEnqueuedUser_GetUser (IntPtr obj)
Referenced by Oculus.Platform.Models.MatchmakingEnqueuedUser.MatchmakingEnqueuedUser().
ovr_MatchmakingEnqueuedUserArray_GetElement()
static IntPtr Oculus.Platform.CAPI.ovr_MatchmakingEnqueuedUserArray_GetElement (IntPtr obj, UIntPtr index)
Referenced by Oculus.Platform.Models.MatchmakingEnqueuedUserList.MatchmakingEnqueuedUserList().
ovr_MatchmakingEnqueuedUserArray_GetSize()
static UIntPtr Oculus.Platform.CAPI.ovr_MatchmakingEnqueuedUserArray_GetSize (IntPtr obj)
Referenced by Oculus.Platform.Models.MatchmakingEnqueuedUserList.MatchmakingEnqueuedUserList().
ovr_MatchmakingEnqueueResult_GetAdminSnapshot()
static IntPtr Oculus.Platform.CAPI.ovr_MatchmakingEnqueueResult_GetAdminSnapshot (IntPtr obj)
Referenced by Oculus.Platform.Models.MatchmakingEnqueueResult.MatchmakingEnqueueResult().
ovr_MatchmakingEnqueueResult_GetAverageWait()
static uint Oculus.Platform.CAPI.ovr_MatchmakingEnqueueResult_GetAverageWait (IntPtr obj)
Referenced by Oculus.Platform.Models.MatchmakingEnqueueResult.MatchmakingEnqueueResult().
ovr_MatchmakingEnqueueResult_GetMatchesInLastHourCount()
static uint Oculus.Platform.CAPI.ovr_MatchmakingEnqueueResult_GetMatchesInLastHourCount (IntPtr obj)
Referenced by Oculus.Platform.Models.MatchmakingEnqueueResult.MatchmakingEnqueueResult().
ovr_MatchmakingEnqueueResult_GetMaxExpectedWait()
static uint Oculus.Platform.CAPI.ovr_MatchmakingEnqueueResult_GetMaxExpectedWait (IntPtr obj)
Referenced by Oculus.Platform.Models.MatchmakingEnqueueResult.MatchmakingEnqueueResult().
ovr_MatchmakingEnqueueResult_GetPool()
static string Oculus.Platform.CAPI.ovr_MatchmakingEnqueueResult_GetPool (IntPtr obj) static
Referenced by Oculus.Platform.Models.MatchmakingEnqueueResult.MatchmakingEnqueueResult().
ovr_MatchmakingEnqueueResult_GetRecentMatchPercentage()
static uint Oculus.Platform.CAPI.ovr_MatchmakingEnqueueResult_GetRecentMatchPercentage (IntPtr obj)
Referenced by Oculus.Platform.Models.MatchmakingEnqueueResult.MatchmakingEnqueueResult().
ovr_MatchmakingEnqueueResult_GetRequestHash()
static string Oculus.Platform.CAPI.ovr_MatchmakingEnqueueResult_GetRequestHash (IntPtr obj) static
Referenced by Oculus.Platform.Models.MatchmakingEnqueueResult.MatchmakingEnqueueResult().
ovr_MatchmakingEnqueueResultAndRoom_GetMatchmakingEnqueueResult()
static IntPtr Oculus.Platform.CAPI.ovr_MatchmakingEnqueueResultAndRoom_GetMatchmakingEnqueueResult (IntPtr obj)
Referenced by Oculus.Platform.Models.MatchmakingEnqueueResultAndRoom.MatchmakingEnqueueResultAndRoom().
ovr_MatchmakingEnqueueResultAndRoom_GetRoom()
static IntPtr Oculus.Platform.CAPI.ovr_MatchmakingEnqueueResultAndRoom_GetRoom (IntPtr obj)
Referenced by Oculus.Platform.Models.MatchmakingEnqueueResultAndRoom.MatchmakingEnqueueResultAndRoom().
ovr_MatchmakingNotification_GetAddedByUserId()
static ulong Oculus.Platform.CAPI.ovr_MatchmakingNotification_GetAddedByUserId (IntPtr obj)
ovr_MatchmakingNotification_GetRoom()
static IntPtr Oculus.Platform.CAPI.ovr_MatchmakingNotification_GetRoom (IntPtr obj)
ovr_MatchmakingNotification_GetTraceId()
static string Oculus.Platform.CAPI.ovr_MatchmakingNotification_GetTraceId (IntPtr obj) static
ovr_MatchmakingOptions_AddEnqueueAdditionalUser()
static void Oculus.Platform.CAPI.ovr_MatchmakingOptions_AddEnqueueAdditionalUser (IntPtr handle, UInt64 value)
Referenced by Oculus.Platform.MatchmakingOptions.AddEnqueueAdditionalUser().
ovr_MatchmakingOptions_ClearCreateRoomDataStore()
static void Oculus.Platform.CAPI.ovr_MatchmakingOptions_ClearCreateRoomDataStore (IntPtr handle)
Referenced by Oculus.Platform.MatchmakingOptions.ClearCreateRoomDataStore().
ovr_MatchmakingOptions_ClearEnqueueAdditionalUsers()
static void Oculus.Platform.CAPI.ovr_MatchmakingOptions_ClearEnqueueAdditionalUsers (IntPtr handle)
Referenced by Oculus.Platform.MatchmakingOptions.ClearEnqueueAdditionalUsers().
ovr_MatchmakingOptions_ClearEnqueueDataSettings()
static void Oculus.Platform.CAPI.ovr_MatchmakingOptions_ClearEnqueueDataSettings (IntPtr handle)
Referenced by Oculus.Platform.MatchmakingOptions.ClearEnqueueDataSettings().
ovr_MatchmakingOptions_Create()
static IntPtr Oculus.Platform.CAPI.ovr_MatchmakingOptions_Create ()
Referenced by Oculus.Platform.MatchmakingOptions.MatchmakingOptions().
ovr_MatchmakingOptions_Destroy()
static void Oculus.Platform.CAPI.ovr_MatchmakingOptions_Destroy (IntPtr handle)
ovr_MatchmakingOptions_SetCreateRoomDataStoreString()
static void Oculus.Platform.CAPI.ovr_MatchmakingOptions_SetCreateRoomDataStoreString (IntPtr handle, string key, string value) static
Referenced by Oculus.Platform.MatchmakingOptions.SetCreateRoomDataStore().
ovr_MatchmakingOptions_SetCreateRoomJoinPolicy()
static void Oculus.Platform.CAPI.ovr_MatchmakingOptions_SetCreateRoomJoinPolicy (IntPtr handle, RoomJoinPolicy value)
Referenced by Oculus.Platform.MatchmakingOptions.SetCreateRoomJoinPolicy().
ovr_MatchmakingOptions_SetCreateRoomMaxUsers()
static void Oculus.Platform.CAPI.ovr_MatchmakingOptions_SetCreateRoomMaxUsers (IntPtr handle, uint value)
Referenced by Oculus.Platform.MatchmakingOptions.SetCreateRoomMaxUsers().
ovr_MatchmakingOptions_SetEnqueueDataSettingsDouble()
static void Oculus.Platform.CAPI.ovr_MatchmakingOptions_SetEnqueueDataSettingsDouble (IntPtr handle, string key, double value) static
Referenced by Oculus.Platform.MatchmakingOptions.SetEnqueueDataSettings().
ovr_MatchmakingOptions_SetEnqueueDataSettingsInt()
static void Oculus.Platform.CAPI.ovr_MatchmakingOptions_SetEnqueueDataSettingsInt (IntPtr handle, string key, int value) static
Referenced by Oculus.Platform.MatchmakingOptions.SetEnqueueDataSettings().
ovr_MatchmakingOptions_SetEnqueueDataSettingsString()
static void Oculus.Platform.CAPI.ovr_MatchmakingOptions_SetEnqueueDataSettingsString (IntPtr handle, string key, string value) static
Referenced by Oculus.Platform.MatchmakingOptions.SetEnqueueDataSettings().
ovr_MatchmakingOptions_SetEnqueueIsDebug()
static void Oculus.Platform.CAPI.ovr_MatchmakingOptions_SetEnqueueIsDebug (IntPtr handle, bool value)
Referenced by Oculus.Platform.MatchmakingOptions.SetEnqueueIsDebug().
ovr_MatchmakingOptions_SetEnqueueQueryKey()
static void Oculus.Platform.CAPI.ovr_MatchmakingOptions_SetEnqueueQueryKey (IntPtr handle, string value) static
Referenced by Oculus.Platform.MatchmakingOptions.SetEnqueueQueryKey().
ovr_MatchmakingRoom_GetPingTime()
static uint Oculus.Platform.CAPI.ovr_MatchmakingRoom_GetPingTime (IntPtr obj)
ovr_MatchmakingRoom_GetRoom()
static IntPtr Oculus.Platform.CAPI.ovr_MatchmakingRoom_GetRoom (IntPtr obj)
ovr_MatchmakingRoom_HasPingTime()
static bool Oculus.Platform.CAPI.ovr_MatchmakingRoom_HasPingTime (IntPtr obj)
ovr_MatchmakingRoomArray_GetElement()
static IntPtr Oculus.Platform.CAPI.ovr_MatchmakingRoomArray_GetElement (IntPtr obj, UIntPtr index)
ovr_MatchmakingRoomArray_GetSize()
static UIntPtr Oculus.Platform.CAPI.ovr_MatchmakingRoomArray_GetSize (IntPtr obj)
ovr_MatchmakingStats_GetDrawCount()
static uint Oculus.Platform.CAPI.ovr_MatchmakingStats_GetDrawCount (IntPtr obj)
Referenced by Oculus.Platform.Models.MatchmakingStats.MatchmakingStats().
ovr_MatchmakingStats_GetLossCount()
static uint Oculus.Platform.CAPI.ovr_MatchmakingStats_GetLossCount (IntPtr obj)
Referenced by Oculus.Platform.Models.MatchmakingStats.MatchmakingStats().
ovr_MatchmakingStats_GetSkillLevel()
static uint Oculus.Platform.CAPI.ovr_MatchmakingStats_GetSkillLevel (IntPtr obj)
Referenced by Oculus.Platform.Models.MatchmakingStats.MatchmakingStats().
ovr_MatchmakingStats_GetSkillMean()
static double Oculus.Platform.CAPI.ovr_MatchmakingStats_GetSkillMean (IntPtr obj)
Referenced by Oculus.Platform.Models.MatchmakingStats.MatchmakingStats().
ovr_MatchmakingStats_GetSkillStandardDeviation()
static double Oculus.Platform.CAPI.ovr_MatchmakingStats_GetSkillStandardDeviation (IntPtr obj)
Referenced by Oculus.Platform.Models.MatchmakingStats.MatchmakingStats().
ovr_MatchmakingStats_GetWinCount()
static uint Oculus.Platform.CAPI.ovr_MatchmakingStats_GetWinCount (IntPtr obj)
Referenced by Oculus.Platform.Models.MatchmakingStats.MatchmakingStats().
ovr_Media_ShareToFacebook()
static ulong Oculus.Platform.CAPI.ovr_Media_ShareToFacebook (string postTextSuggestion, string filePath, MediaContentType contentType) static
ovr_Message_GetAbuseReportRecording()
static IntPtr Oculus.Platform.CAPI.ovr_Message_GetAbuseReportRecording (IntPtr obj)
Referenced by Oculus.Platform.MessageWithAbuseReportRecording.GetDataFromMessage().
ovr_Message_GetAchievementDefinitionArray()
static IntPtr Oculus.Platform.CAPI.ovr_Message_GetAchievementDefinitionArray (IntPtr obj)
Referenced by Oculus.Platform.MessageWithAchievementDefinitions.GetDataFromMessage().
ovr_Message_GetAchievementProgressArray()
static IntPtr Oculus.Platform.CAPI.ovr_Message_GetAchievementProgressArray (IntPtr obj)
Referenced by Oculus.Platform.MessageWithAchievementProgressList.GetDataFromMessage().
ovr_Message_GetAchievementUpdate()
static IntPtr Oculus.Platform.CAPI.ovr_Message_GetAchievementUpdate (IntPtr obj)
Referenced by Oculus.Platform.MessageWithAchievementUpdate.GetDataFromMessage().
ovr_Message_GetApplicationInviteArray()
static IntPtr Oculus.Platform.CAPI.ovr_Message_GetApplicationInviteArray (IntPtr obj)
Referenced by Oculus.Platform.MessageWithApplicationInviteList.GetDataFromMessage().
ovr_Message_GetApplicationVersion()
static IntPtr Oculus.Platform.CAPI.ovr_Message_GetApplicationVersion (IntPtr obj)
Referenced by Oculus.Platform.MessageWithApplicationVersion.GetDataFromMessage().
ovr_Message_GetAssetDetails()
static IntPtr Oculus.Platform.CAPI.ovr_Message_GetAssetDetails (IntPtr obj)
Referenced by Oculus.Platform.MessageWithAssetDetails.GetDataFromMessage().
ovr_Message_GetAssetDetailsArray()
static IntPtr Oculus.Platform.CAPI.ovr_Message_GetAssetDetailsArray (IntPtr obj)
Referenced by Oculus.Platform.MessageWithAssetDetailsList.GetDataFromMessage().
ovr_Message_GetAssetFileDeleteResult()
static IntPtr Oculus.Platform.CAPI.ovr_Message_GetAssetFileDeleteResult (IntPtr obj)
Referenced by Oculus.Platform.MessageWithAssetFileDeleteResult.GetDataFromMessage().
ovr_Message_GetAssetFileDownloadCancelResult()
static IntPtr Oculus.Platform.CAPI.ovr_Message_GetAssetFileDownloadCancelResult (IntPtr obj)
Referenced by Oculus.Platform.MessageWithAssetFileDownloadCancelResult.GetDataFromMessage().
ovr_Message_GetAssetFileDownloadResult()
static IntPtr Oculus.Platform.CAPI.ovr_Message_GetAssetFileDownloadResult (IntPtr obj)
Referenced by Oculus.Platform.MessageWithAssetFileDownloadResult.GetDataFromMessage().
ovr_Message_GetAssetFileDownloadUpdate()
static IntPtr Oculus.Platform.CAPI.ovr_Message_GetAssetFileDownloadUpdate (IntPtr obj)
Referenced by Oculus.Platform.MessageWithAssetFileDownloadUpdate.GetDataFromMessage().
ovr_Message_GetCalApplicationFinalized()
static IntPtr Oculus.Platform.CAPI.ovr_Message_GetCalApplicationFinalized (IntPtr obj)
Referenced by Oculus.Platform.MessageWithCalApplicationFinalized.GetDataFromMessage().
ovr_Message_GetCalApplicationProposed()
static IntPtr Oculus.Platform.CAPI.ovr_Message_GetCalApplicationProposed (IntPtr obj)
Referenced by Oculus.Platform.MessageWithCalApplicationProposed.GetDataFromMessage().
ovr_Message_GetCalApplicationSuggestionArray()
static IntPtr Oculus.Platform.CAPI.ovr_Message_GetCalApplicationSuggestionArray (IntPtr obj)
Referenced by Oculus.Platform.MessageWithCalApplicationSuggestionList.GetDataFromMessage().
ovr_Message_GetChallenge()
static IntPtr Oculus.Platform.CAPI.ovr_Message_GetChallenge (IntPtr obj)
Referenced by Oculus.Platform.MessageWithChallenge.GetDataFromMessage().
ovr_Message_GetChallengeArray()
static IntPtr Oculus.Platform.CAPI.ovr_Message_GetChallengeArray (IntPtr obj)
Referenced by Oculus.Platform.MessageWithChallengeList.GetDataFromMessage().
ovr_Message_GetChallengeEntryArray()
static IntPtr Oculus.Platform.CAPI.ovr_Message_GetChallengeEntryArray (IntPtr obj)
Referenced by Oculus.Platform.MessageWithChallengeEntryList.GetDataFromMessage().
ovr_Message_GetCloudStorageConflictMetadata()
static IntPtr Oculus.Platform.CAPI.ovr_Message_GetCloudStorageConflictMetadata (IntPtr obj)
Referenced by Oculus.Platform.MessageWithCloudStorageConflictMetadata.GetDataFromMessage().
ovr_Message_GetCloudStorageData()
static IntPtr Oculus.Platform.CAPI.ovr_Message_GetCloudStorageData (IntPtr obj)
Referenced by Oculus.Platform.MessageWithCloudStorageData.GetDataFromMessage().
ovr_Message_GetCloudStorageMetadata()
static IntPtr Oculus.Platform.CAPI.ovr_Message_GetCloudStorageMetadata (IntPtr obj)
Referenced by Oculus.Platform.MessageWithCloudStorageMetadataUnderLocal.GetDataFromMessage().
ovr_Message_GetCloudStorageMetadataArray()
static IntPtr Oculus.Platform.CAPI.ovr_Message_GetCloudStorageMetadataArray (IntPtr obj)
Referenced by Oculus.Platform.MessageWithCloudStorageMetadataList.GetDataFromMessage().
ovr_Message_GetCloudStorageUpdateResponse()
static IntPtr Oculus.Platform.CAPI.ovr_Message_GetCloudStorageUpdateResponse (IntPtr obj)
Referenced by Oculus.Platform.MessageWithCloudStorageUpdateResponse.GetDataFromMessage().
ovr_Message_GetDataStore()
static IntPtr Oculus.Platform.CAPI.ovr_Message_GetDataStore (IntPtr obj)
Referenced by Oculus.Platform.MessageWithDataStoreUnderPrivateUserDataStore.GetDataFromMessage(), and Oculus.Platform.MessageWithDataStoreUnderPublicUserDataStore.GetDataFromMessage().
ovr_Message_GetDestinationArray()
static IntPtr Oculus.Platform.CAPI.ovr_Message_GetDestinationArray (IntPtr obj)
Referenced by Oculus.Platform.MessageWithDestinationList.GetDataFromMessage().
ovr_Message_GetError()
static IntPtr Oculus.Platform.CAPI.ovr_Message_GetError (IntPtr obj)
Referenced by Oculus.Platform.Message< T >.Message().
ovr_Message_GetGroupPresenceJoinIntent()
static IntPtr Oculus.Platform.CAPI.ovr_Message_GetGroupPresenceJoinIntent (IntPtr obj)
Referenced by Oculus.Platform.MessageWithGroupPresenceJoinIntent.GetDataFromMessage().
ovr_Message_GetGroupPresenceLeaveIntent()
static IntPtr Oculus.Platform.CAPI.ovr_Message_GetGroupPresenceLeaveIntent (IntPtr obj)
Referenced by Oculus.Platform.MessageWithGroupPresenceLeaveIntent.GetDataFromMessage().
ovr_Message_GetHttpTransferUpdate()
static IntPtr Oculus.Platform.CAPI.ovr_Message_GetHttpTransferUpdate (IntPtr obj)
Referenced by Oculus.Platform.MessageWithHttpTransferUpdate.GetDataFromMessage().
ovr_Message_GetInstalledApplicationArray()
static IntPtr Oculus.Platform.CAPI.ovr_Message_GetInstalledApplicationArray (IntPtr obj)
Referenced by Oculus.Platform.MessageWithInstalledApplicationList.GetDataFromMessage().
ovr_Message_GetInvitePanelResultInfo()
static IntPtr Oculus.Platform.CAPI.ovr_Message_GetInvitePanelResultInfo (IntPtr obj)
Referenced by Oculus.Platform.MessageWithInvitePanelResultInfo.GetDataFromMessage().
ovr_Message_GetLaunchBlockFlowResult()
static IntPtr Oculus.Platform.CAPI.ovr_Message_GetLaunchBlockFlowResult (IntPtr obj)
Referenced by Oculus.Platform.MessageWithLaunchBlockFlowResult.GetDataFromMessage().
ovr_Message_GetLaunchFriendRequestFlowResult()
static IntPtr Oculus.Platform.CAPI.ovr_Message_GetLaunchFriendRequestFlowResult (IntPtr obj)
Referenced by Oculus.Platform.MessageWithLaunchFriendRequestFlowResult.GetDataFromMessage().
ovr_Message_GetLaunchInvitePanelFlowResult()
static IntPtr Oculus.Platform.CAPI.ovr_Message_GetLaunchInvitePanelFlowResult (IntPtr obj)
Referenced by Oculus.Platform.MessageWithLaunchInvitePanelFlowResult.GetDataFromMessage().
ovr_Message_GetLaunchReportFlowResult()
static IntPtr Oculus.Platform.CAPI.ovr_Message_GetLaunchReportFlowResult (IntPtr obj)
Referenced by Oculus.Platform.MessageWithLaunchReportFlowResult.GetDataFromMessage().
ovr_Message_GetLaunchUnblockFlowResult()
static IntPtr Oculus.Platform.CAPI.ovr_Message_GetLaunchUnblockFlowResult (IntPtr obj)
Referenced by Oculus.Platform.MessageWithLaunchUnblockFlowResult.GetDataFromMessage().
ovr_Message_GetLeaderboardArray()
static IntPtr Oculus.Platform.CAPI.ovr_Message_GetLeaderboardArray (IntPtr obj)
Referenced by Oculus.Platform.MessageWithLeaderboardList.GetDataFromMessage().
ovr_Message_GetLeaderboardEntryArray()
static IntPtr Oculus.Platform.CAPI.ovr_Message_GetLeaderboardEntryArray (IntPtr obj)
Referenced by Oculus.Platform.MessageWithLeaderboardEntryList.GetDataFromMessage().
ovr_Message_GetLeaderboardUpdateStatus()
static IntPtr Oculus.Platform.CAPI.ovr_Message_GetLeaderboardUpdateStatus (IntPtr obj)
Referenced by Oculus.Platform.MessageWithLeaderboardDidUpdate.GetDataFromMessage().
ovr_Message_GetLinkedAccountArray()
static IntPtr Oculus.Platform.CAPI.ovr_Message_GetLinkedAccountArray (IntPtr obj)
Referenced by Oculus.Platform.MessageWithLinkedAccountList.GetDataFromMessage().
ovr_Message_GetLivestreamingApplicationStatus()
static IntPtr Oculus.Platform.CAPI.ovr_Message_GetLivestreamingApplicationStatus (IntPtr obj)
Referenced by Oculus.Platform.MessageWithLivestreamingApplicationStatus.GetDataFromMessage().
ovr_Message_GetLivestreamingStartResult()
static IntPtr Oculus.Platform.CAPI.ovr_Message_GetLivestreamingStartResult (IntPtr obj)
Referenced by Oculus.Platform.MessageWithLivestreamingStartResult.GetDataFromMessage().
ovr_Message_GetLivestreamingStatus()
static IntPtr Oculus.Platform.CAPI.ovr_Message_GetLivestreamingStatus (IntPtr obj)
Referenced by Oculus.Platform.MessageWithLivestreamingStatus.GetDataFromMessage().
ovr_Message_GetLivestreamingVideoStats()
static IntPtr Oculus.Platform.CAPI.ovr_Message_GetLivestreamingVideoStats (IntPtr obj)
Referenced by Oculus.Platform.MessageWithLivestreamingVideoStats.GetDataFromMessage().
ovr_Message_GetMatchmakingAdminSnapshot()
static IntPtr Oculus.Platform.CAPI.ovr_Message_GetMatchmakingAdminSnapshot (IntPtr obj)
Referenced by Oculus.Platform.MessageWithMatchmakingAdminSnapshot.GetDataFromMessage().
ovr_Message_GetMatchmakingBrowseResult()
static IntPtr Oculus.Platform.CAPI.ovr_Message_GetMatchmakingBrowseResult (IntPtr obj)
Referenced by Oculus.Platform.MessageWithMatchmakingBrowseResult.GetDataFromMessage().
ovr_Message_GetMatchmakingEnqueueResult()
static IntPtr Oculus.Platform.CAPI.ovr_Message_GetMatchmakingEnqueueResult (IntPtr obj)
Referenced by Oculus.Platform.MessageWithMatchmakingEnqueueResult.GetDataFromMessage().
ovr_Message_GetMatchmakingEnqueueResultAndRoom()
static IntPtr Oculus.Platform.CAPI.ovr_Message_GetMatchmakingEnqueueResultAndRoom (IntPtr obj)
Referenced by Oculus.Platform.MessageWithMatchmakingEnqueueResultAndRoom.GetDataFromMessage().
ovr_Message_GetMatchmakingRoomArray()
static IntPtr Oculus.Platform.CAPI.ovr_Message_GetMatchmakingRoomArray (IntPtr obj)
ovr_Message_GetMatchmakingStats()
static IntPtr Oculus.Platform.CAPI.ovr_Message_GetMatchmakingStats (IntPtr obj)
Referenced by Oculus.Platform.MessageWithMatchmakingStatsUnderMatchmakingStats.GetDataFromMessage().
ovr_Message_GetMicrophoneAvailabilityState()
static IntPtr Oculus.Platform.CAPI.ovr_Message_GetMicrophoneAvailabilityState (IntPtr obj)
Referenced by Oculus.Platform.MessageWithMicrophoneAvailabilityState.GetDataFromMessage().
ovr_Message_GetNativeMessage()
static IntPtr Oculus.Platform.CAPI.ovr_Message_GetNativeMessage (IntPtr obj)
Referenced by Oculus.Platform.MessageWithAbuseReportRecording.GetDataFromMessage(), Oculus.Platform.MessageWithAchievementDefinitions.GetDataFromMessage(), Oculus.Platform.MessageWithAchievementProgressList.GetDataFromMessage(), Oculus.Platform.MessageWithAchievementUpdate.GetDataFromMessage(), Oculus.Platform.MessageWithApplicationInviteList.GetDataFromMessage(), Oculus.Platform.MessageWithApplicationVersion.GetDataFromMessage(), Oculus.Platform.MessageWithAssetDetails.GetDataFromMessage(), Oculus.Platform.MessageWithAssetDetailsList.GetDataFromMessage(), Oculus.Platform.MessageWithAssetFileDeleteResult.GetDataFromMessage(), Oculus.Platform.MessageWithAssetFileDownloadCancelResult.GetDataFromMessage(), Oculus.Platform.MessageWithAssetFileDownloadResult.GetDataFromMessage(), Oculus.Platform.MessageWithAssetFileDownloadUpdate.GetDataFromMessage(), Oculus.Platform.MessageWithCalApplicationFinalized.GetDataFromMessage(), Oculus.Platform.MessageWithCalApplicationProposed.GetDataFromMessage(), Oculus.Platform.MessageWithCalApplicationSuggestionList.GetDataFromMessage(), Oculus.Platform.MessageWithChallenge.GetDataFromMessage(), Oculus.Platform.MessageWithChallengeList.GetDataFromMessage(), Oculus.Platform.MessageWithChallengeEntryList.GetDataFromMessage(), Oculus.Platform.MessageWithCloudStorageConflictMetadata.GetDataFromMessage(), Oculus.Platform.MessageWithCloudStorageData.GetDataFromMessage(), Oculus.Platform.MessageWithCloudStorageMetadataUnderLocal.GetDataFromMessage(), Oculus.Platform.MessageWithCloudStorageMetadataList.GetDataFromMessage(), Oculus.Platform.MessageWithCloudStorageUpdateResponse.GetDataFromMessage(), Oculus.Platform.MessageWithDataStoreUnderPrivateUserDataStore.GetDataFromMessage(), Oculus.Platform.MessageWithDataStoreUnderPublicUserDataStore.GetDataFromMessage(), Oculus.Platform.MessageWithDestinationList.GetDataFromMessage(), Oculus.Platform.MessageWithGroupPresenceJoinIntent.GetDataFromMessage(), Oculus.Platform.MessageWithGroupPresenceLeaveIntent.GetDataFromMessage(), Oculus.Platform.MessageWithInstalledApplicationList.GetDataFromMessage(), Oculus.Platform.MessageWithInvitePanelResultInfo.GetDataFromMessage(), Oculus.Platform.MessageWithLaunchBlockFlowResult.GetDataFromMessage(), Oculus.Platform.MessageWithLaunchFriendRequestFlowResult.GetDataFromMessage(), Oculus.Platform.MessageWithLaunchInvitePanelFlowResult.GetDataFromMessage(), Oculus.Platform.MessageWithLaunchReportFlowResult.GetDataFromMessage(), Oculus.Platform.MessageWithLaunchUnblockFlowResult.GetDataFromMessage(), Oculus.Platform.MessageWithLeaderboardList.GetDataFromMessage(), Oculus.Platform.MessageWithLeaderboardEntryList.GetDataFromMessage(), Oculus.Platform.MessageWithLinkedAccountList.GetDataFromMessage(), Oculus.Platform.MessageWithLivestreamingApplicationStatus.GetDataFromMessage(), Oculus.Platform.MessageWithLivestreamingStartResult.GetDataFromMessage(), Oculus.Platform.MessageWithLivestreamingStatus.GetDataFromMessage(), Oculus.Platform.MessageWithLivestreamingVideoStats.GetDataFromMessage(), Oculus.Platform.MessageWithMatchmakingAdminSnapshot.GetDataFromMessage(), Oculus.Platform.MessageWithMatchmakingEnqueueResult.GetDataFromMessage(), Oculus.Platform.MessageWithMatchmakingEnqueueResultAndRoom.GetDataFromMessage(), Oculus.Platform.MessageWithMatchmakingStatsUnderMatchmakingStats.GetDataFromMessage(), Oculus.Platform.MessageWithMicrophoneAvailabilityState.GetDataFromMessage(), Oculus.Platform.MessageWithNetSyncConnection.GetDataFromMessage(), Oculus.Platform.MessageWithNetSyncSessionList.GetDataFromMessage(), Oculus.Platform.MessageWithNetSyncSessionsChangedNotification.GetDataFromMessage(), Oculus.Platform.MessageWithNetSyncSetSessionPropertyResult.GetDataFromMessage(), Oculus.Platform.MessageWithNetSyncVoipAttenuationValueList.GetDataFromMessage(), Oculus.Platform.MessageWithOrgScopedID.GetDataFromMessage(), Oculus.Platform.MessageWithParty.GetDataFromMessage(), Oculus.Platform.MessageWithPartyUnderCurrentParty.GetDataFromMessage(), Oculus.Platform.MessageWithPartyID.GetDataFromMessage(), Oculus.Platform.MessageWithPartyUpdateNotification.GetDataFromMessage(), Oculus.Platform.MessageWithPidList.GetDataFromMessage(), Oculus.Platform.MessageWithProductList.GetDataFromMessage(), Oculus.Platform.MessageWithPurchase.GetDataFromMessage(), Oculus.Platform.MessageWithPurchaseList.GetDataFromMessage(), Oculus.Platform.MessageWithRejoinDialogResult.GetDataFromMessage(), Oculus.Platform.MessageWithRoom.GetDataFromMessage(), Oculus.Platform.MessageWithRoomUnderCurrentRoom.GetDataFromMessage(), Oculus.Platform.MessageWithRoomUnderViewerRoom.GetDataFromMessage(), Oculus.Platform.MessageWithRoomList.GetDataFromMessage(), Oculus.Platform.MessageWithRoomInviteNotification.GetDataFromMessage(), Oculus.Platform.MessageWithRoomInviteNotificationList.GetDataFromMessage(), Oculus.Platform.MessageWithSdkAccountList.GetDataFromMessage(), Oculus.Platform.MessageWithSendInvitesResult.GetDataFromMessage(), Oculus.Platform.MessageWithShareMediaResult.GetDataFromMessage(), Oculus.Platform.MessageWithSystemVoipState.GetDataFromMessage(), Oculus.Platform.MessageWithUser.GetDataFromMessage(), Oculus.Platform.MessageWithUserAndRoomList.GetDataFromMessage(), Oculus.Platform.MessageWithUserList.GetDataFromMessage(), Oculus.Platform.MessageWithUserCapabilityList.GetDataFromMessage(), Oculus.Platform.MessageWithUserDataStoreUpdateResponse.GetDataFromMessage(), Oculus.Platform.MessageWithUserProof.GetDataFromMessage(), Oculus.Platform.MessageWithUserReportID.GetDataFromMessage(), Oculus.Platform.MessageWithLeaderboardDidUpdate.GetDataFromMessage(), Oculus.Platform.MessageWithMatchmakingNotification.GetDataFromMessage(), Oculus.Platform.MessageWithMatchmakingBrowseResult.GetDataFromMessage(), Oculus.Platform.MessageWithHttpTransferUpdate.GetDataFromMessage(), Oculus.Platform.MessageWithPlatformInitialize.GetDataFromMessage(), and Oculus.Platform.Message< T >.Message().
ovr_Message_GetNetSyncConnection()
static IntPtr Oculus.Platform.CAPI.ovr_Message_GetNetSyncConnection (IntPtr obj)
Referenced by Oculus.Platform.MessageWithNetSyncConnection.GetDataFromMessage().
ovr_Message_GetNetSyncSessionArray()
static IntPtr Oculus.Platform.CAPI.ovr_Message_GetNetSyncSessionArray (IntPtr obj)
Referenced by Oculus.Platform.MessageWithNetSyncSessionList.GetDataFromMessage().
ovr_Message_GetNetSyncSessionsChangedNotification()
static IntPtr Oculus.Platform.CAPI.ovr_Message_GetNetSyncSessionsChangedNotification (IntPtr obj)
Referenced by Oculus.Platform.MessageWithNetSyncSessionsChangedNotification.GetDataFromMessage().
ovr_Message_GetNetSyncSetSessionPropertyResult()
static IntPtr Oculus.Platform.CAPI.ovr_Message_GetNetSyncSetSessionPropertyResult (IntPtr obj)
Referenced by Oculus.Platform.MessageWithNetSyncSetSessionPropertyResult.GetDataFromMessage().
ovr_Message_GetNetSyncVoipAttenuationValueArray()
static IntPtr Oculus.Platform.CAPI.ovr_Message_GetNetSyncVoipAttenuationValueArray (IntPtr obj)
Referenced by Oculus.Platform.MessageWithNetSyncVoipAttenuationValueList.GetDataFromMessage().
ovr_Message_GetNetworkingPeer()
static IntPtr Oculus.Platform.CAPI.ovr_Message_GetNetworkingPeer (IntPtr obj)
Referenced by Oculus.Platform.MessageWithNetworkingPeer.GetDataFromMessage().
ovr_Message_GetOrgScopedID()
static IntPtr Oculus.Platform.CAPI.ovr_Message_GetOrgScopedID (IntPtr obj)
Referenced by Oculus.Platform.MessageWithOrgScopedID.GetDataFromMessage().
ovr_Message_GetParty()
static IntPtr Oculus.Platform.CAPI.ovr_Message_GetParty (IntPtr obj)
Referenced by Oculus.Platform.MessageWithParty.GetDataFromMessage(), and Oculus.Platform.MessageWithPartyUnderCurrentParty.GetDataFromMessage().
ovr_Message_GetPartyID()
static IntPtr Oculus.Platform.CAPI.ovr_Message_GetPartyID (IntPtr obj)
Referenced by Oculus.Platform.MessageWithPartyID.GetDataFromMessage().
ovr_Message_GetPartyUpdateNotification()
static IntPtr Oculus.Platform.CAPI.ovr_Message_GetPartyUpdateNotification (IntPtr obj)
Referenced by Oculus.Platform.MessageWithPartyUpdateNotification.GetDataFromMessage().
ovr_Message_GetPidArray()
static IntPtr Oculus.Platform.CAPI.ovr_Message_GetPidArray (IntPtr obj)
Referenced by Oculus.Platform.MessageWithPidList.GetDataFromMessage().
ovr_Message_GetPingResult()
static IntPtr Oculus.Platform.CAPI.ovr_Message_GetPingResult (IntPtr obj)
Referenced by Oculus.Platform.MessageWithPingResult.GetDataFromMessage().
ovr_Message_GetPlatformInitialize()
static IntPtr Oculus.Platform.CAPI.ovr_Message_GetPlatformInitialize (IntPtr obj)
Referenced by Oculus.Platform.MessageWithPlatformInitialize.GetDataFromMessage().
ovr_Message_GetProductArray()
static IntPtr Oculus.Platform.CAPI.ovr_Message_GetProductArray (IntPtr obj)
Referenced by Oculus.Platform.MessageWithProductList.GetDataFromMessage().
ovr_Message_GetPurchase()
static IntPtr Oculus.Platform.CAPI.ovr_Message_GetPurchase (IntPtr obj)
Referenced by Oculus.Platform.MessageWithPurchase.GetDataFromMessage().
ovr_Message_GetPurchaseArray()
static IntPtr Oculus.Platform.CAPI.ovr_Message_GetPurchaseArray (IntPtr obj)
Referenced by Oculus.Platform.MessageWithPurchaseList.GetDataFromMessage().
ovr_Message_GetRejoinDialogResult()
static IntPtr Oculus.Platform.CAPI.ovr_Message_GetRejoinDialogResult (IntPtr obj)
Referenced by Oculus.Platform.MessageWithRejoinDialogResult.GetDataFromMessage().
ovr_Message_GetRequestID()
static ulong Oculus.Platform.CAPI.ovr_Message_GetRequestID (IntPtr obj)
Referenced by Oculus.Platform.Message< T >.Message().
ovr_Message_GetRoom()
static IntPtr Oculus.Platform.CAPI.ovr_Message_GetRoom (IntPtr obj)
Referenced by Oculus.Platform.MessageWithRoom.GetDataFromMessage(), Oculus.Platform.MessageWithRoomUnderCurrentRoom.GetDataFromMessage(), Oculus.Platform.MessageWithRoomUnderViewerRoom.GetDataFromMessage(), and Oculus.Platform.MessageWithMatchmakingNotification.GetDataFromMessage().
ovr_Message_GetRoomArray()
static IntPtr Oculus.Platform.CAPI.ovr_Message_GetRoomArray (IntPtr obj)
Referenced by Oculus.Platform.MessageWithRoomList.GetDataFromMessage().
ovr_Message_GetRoomInviteNotification()
static IntPtr Oculus.Platform.CAPI.ovr_Message_GetRoomInviteNotification (IntPtr obj)
Referenced by Oculus.Platform.MessageWithRoomInviteNotification.GetDataFromMessage().
ovr_Message_GetRoomInviteNotificationArray()
static IntPtr Oculus.Platform.CAPI.ovr_Message_GetRoomInviteNotificationArray (IntPtr obj)
Referenced by Oculus.Platform.MessageWithRoomInviteNotificationList.GetDataFromMessage().
ovr_Message_GetSdkAccountArray()
static IntPtr Oculus.Platform.CAPI.ovr_Message_GetSdkAccountArray (IntPtr obj)
Referenced by Oculus.Platform.MessageWithSdkAccountList.GetDataFromMessage().
ovr_Message_GetSendInvitesResult()
static IntPtr Oculus.Platform.CAPI.ovr_Message_GetSendInvitesResult (IntPtr obj)
Referenced by Oculus.Platform.MessageWithSendInvitesResult.GetDataFromMessage().
ovr_Message_GetShareMediaResult()
static IntPtr Oculus.Platform.CAPI.ovr_Message_GetShareMediaResult (IntPtr obj)
Referenced by Oculus.Platform.MessageWithShareMediaResult.GetDataFromMessage().
ovr_Message_GetString()
static string Oculus.Platform.CAPI.ovr_Message_GetString (IntPtr obj) static
Referenced by Oculus.Platform.MessageWithString.GetDataFromMessage(), and Oculus.Platform.Message< T >.Message().
ovr_Message_GetStringForJavascript()
static string Oculus.Platform.CAPI.ovr_Message_GetStringForJavascript (IntPtr message) static
ovr_Message_GetSystemVoipState()
static IntPtr Oculus.Platform.CAPI.ovr_Message_GetSystemVoipState (IntPtr obj)
Referenced by Oculus.Platform.MessageWithSystemVoipState.GetDataFromMessage().
ovr_Message_GetType()
static Message.MessageType Oculus.Platform.CAPI.ovr_Message_GetType (IntPtr obj)
Referenced by Oculus.Platform.Message< T >.Message().
ovr_Message_GetUser()
static IntPtr Oculus.Platform.CAPI.ovr_Message_GetUser (IntPtr obj)
Referenced by Oculus.Platform.MessageWithUser.GetDataFromMessage().
ovr_Message_GetUserAndRoomArray()
static IntPtr Oculus.Platform.CAPI.ovr_Message_GetUserAndRoomArray (IntPtr obj)
Referenced by Oculus.Platform.MessageWithUserAndRoomList.GetDataFromMessage().
ovr_Message_GetUserArray()
static IntPtr Oculus.Platform.CAPI.ovr_Message_GetUserArray (IntPtr obj)
Referenced by Oculus.Platform.MessageWithUserList.GetDataFromMessage().
ovr_Message_GetUserCapabilityArray()
static IntPtr Oculus.Platform.CAPI.ovr_Message_GetUserCapabilityArray (IntPtr obj)
Referenced by Oculus.Platform.MessageWithUserCapabilityList.GetDataFromMessage().
ovr_Message_GetUserDataStoreUpdateResponse()
static IntPtr Oculus.Platform.CAPI.ovr_Message_GetUserDataStoreUpdateResponse (IntPtr obj)
Referenced by Oculus.Platform.MessageWithUserDataStoreUpdateResponse.GetDataFromMessage().
ovr_Message_GetUserProof()
static IntPtr Oculus.Platform.CAPI.ovr_Message_GetUserProof (IntPtr obj)
Referenced by Oculus.Platform.MessageWithUserProof.GetDataFromMessage().
ovr_Message_GetUserReportID()
static IntPtr Oculus.Platform.CAPI.ovr_Message_GetUserReportID (IntPtr obj)
Referenced by Oculus.Platform.MessageWithUserReportID.GetDataFromMessage().
ovr_Message_IsError()
static bool Oculus.Platform.CAPI.ovr_Message_IsError (IntPtr obj)
Referenced by Oculus.Platform.Message< T >.Message().
ovr_Microphone_Create()
static IntPtr Oculus.Platform.CAPI.ovr_Microphone_Create ()
ovr_Microphone_Destroy()
static void Oculus.Platform.CAPI.ovr_Microphone_Destroy (IntPtr obj)
ovr_Microphone_GetNumSamplesAvailable()
static UIntPtr Oculus.Platform.CAPI.ovr_Microphone_GetNumSamplesAvailable (IntPtr obj)
ovr_Microphone_GetOutputBufferMaxSize()
static UIntPtr Oculus.Platform.CAPI.ovr_Microphone_GetOutputBufferMaxSize (IntPtr obj)
ovr_Microphone_GetPCM()
static UIntPtr Oculus.Platform.CAPI.ovr_Microphone_GetPCM (IntPtr obj, Int16[] outputBuffer, UIntPtr outputBufferNumElements)
ovr_Microphone_GetPCMFloat()
static UIntPtr Oculus.Platform.CAPI.ovr_Microphone_GetPCMFloat (IntPtr obj, float[] outputBuffer, UIntPtr outputBufferNumElements)
ovr_Microphone_ReadData()
static UIntPtr Oculus.Platform.CAPI.ovr_Microphone_ReadData (IntPtr obj, float[] outputBuffer, UIntPtr outputBufferSize)
ovr_Microphone_SetAcceptableRecordingDelayHint()
static void Oculus.Platform.CAPI.ovr_Microphone_SetAcceptableRecordingDelayHint (IntPtr obj, UIntPtr delayMs)
ovr_Microphone_Start()
static void Oculus.Platform.CAPI.ovr_Microphone_Start (IntPtr obj)
ovr_Microphone_Stop()
static void Oculus.Platform.CAPI.ovr_Microphone_Stop (IntPtr obj)
ovr_MicrophoneAvailabilityState_GetMicrophoneAvailable()
static bool Oculus.Platform.CAPI.ovr_MicrophoneAvailabilityState_GetMicrophoneAvailable (IntPtr obj)
Referenced by Oculus.Platform.Models.MicrophoneAvailabilityState.MicrophoneAvailabilityState().
ovr_MultiplayerErrorOptions_Create()
static IntPtr Oculus.Platform.CAPI.ovr_MultiplayerErrorOptions_Create ()
Referenced by Oculus.Platform.MultiplayerErrorOptions.MultiplayerErrorOptions().
ovr_MultiplayerErrorOptions_Destroy()
static void Oculus.Platform.CAPI.ovr_MultiplayerErrorOptions_Destroy (IntPtr handle)
ovr_MultiplayerErrorOptions_SetErrorKey()
static void Oculus.Platform.CAPI.ovr_MultiplayerErrorOptions_SetErrorKey (IntPtr handle, MultiplayerErrorErrorKey value)
Referenced by Oculus.Platform.MultiplayerErrorOptions.SetErrorKey().
ovr_Net_Accept()
static void Oculus.Platform.CAPI.ovr_Net_Accept (UInt64 peerID)
ovr_Net_AcceptForCurrentRoom()
static bool Oculus.Platform.CAPI.ovr_Net_AcceptForCurrentRoom ()
ovr_Net_Close()
static void Oculus.Platform.CAPI.ovr_Net_Close (UInt64 peerID)
ovr_Net_CloseForCurrentRoom()
static void Oculus.Platform.CAPI.ovr_Net_CloseForCurrentRoom ()
ovr_Net_Connect()
static void Oculus.Platform.CAPI.ovr_Net_Connect (UInt64 peerID)
ovr_Net_IsConnected()
static bool Oculus.Platform.CAPI.ovr_Net_IsConnected (UInt64 peerID)
ovr_Net_Ping()
static ulong Oculus.Platform.CAPI.ovr_Net_Ping (UInt64 peerID)
ovr_Net_ReadPacket()
static IntPtr Oculus.Platform.CAPI.ovr_Net_ReadPacket ()
ovr_Net_SendPacket()
static bool Oculus.Platform.CAPI.ovr_Net_SendPacket (UInt64 userID, UIntPtr length, byte[] bytes, SendPolicy policy)
ovr_Net_SendPacketToCurrentRoom()
static bool Oculus.Platform.CAPI.ovr_Net_SendPacketToCurrentRoom (UIntPtr length, byte[] bytes, SendPolicy policy)
ovr_NetSync_Connect()
static ulong Oculus.Platform.CAPI.ovr_NetSync_Connect (IntPtr connect_options)
ovr_NetSync_Disconnect()
static ulong Oculus.Platform.CAPI.ovr_NetSync_Disconnect (long connection_id)
ovr_NetSync_GetAmbisonicFloatPCM()
static UIntPtr Oculus.Platform.CAPI.ovr_NetSync_GetAmbisonicFloatPCM (long connection_id, float[] outputBuffer, UIntPtr outputBufferNumElements)
ovr_NetSync_GetAmbisonicInt16PCM()
static UIntPtr Oculus.Platform.CAPI.ovr_NetSync_GetAmbisonicInt16PCM (long connection_id, Int16[] outputBuffer, UIntPtr outputBufferNumElements)
ovr_NetSync_GetAmbisonicInterleavedFloatPCM()
static UIntPtr Oculus.Platform.CAPI.ovr_NetSync_GetAmbisonicInterleavedFloatPCM (long connection_id, float[] outputBuffer, UIntPtr outputBufferNumElements)
ovr_NetSync_GetAmbisonicInterleavedInt16PCM()
static UIntPtr Oculus.Platform.CAPI.ovr_NetSync_GetAmbisonicInterleavedInt16PCM (long connection_id, Int16[] outputBuffer, UIntPtr outputBufferNumElements)
ovr_NetSync_GetListenerPosition()
static bool Oculus.Platform.CAPI.ovr_NetSync_GetListenerPosition (long connection_id, UInt64 sessionId, ref ovrNetSyncVec3 position)
ovr_NetSync_GetMonostreamFloatPCM()
static UIntPtr Oculus.Platform.CAPI.ovr_NetSync_GetMonostreamFloatPCM (long connection_id, UInt64 sessionId, float[] outputBuffer, UIntPtr outputBufferNumElements)
ovr_NetSync_GetMonostreamInt16PCM()
static UIntPtr Oculus.Platform.CAPI.ovr_NetSync_GetMonostreamInt16PCM (long connection_id, UInt64 session_id, Int16[] outputBuffer, UIntPtr outputBufferNumElements)
ovr_NetSync_GetPcmBufferMaxSamples()
static UIntPtr Oculus.Platform.CAPI.ovr_NetSync_GetPcmBufferMaxSamples ()
ovr_NetSync_GetSessions()
static ulong Oculus.Platform.CAPI.ovr_NetSync_GetSessions (long connection_id)
ovr_NetSync_GetVoipAmplitude()
static bool Oculus.Platform.CAPI.ovr_NetSync_GetVoipAmplitude (long connection_id, UInt64 sessionId, ref float amplitude)
ovr_NetSync_GetVoipAttenuation()
static ulong Oculus.Platform.CAPI.ovr_NetSync_GetVoipAttenuation (long connection_id)
ovr_NetSync_GetVoipAttenuationDefault()
static ulong Oculus.Platform.CAPI.ovr_NetSync_GetVoipAttenuationDefault ()
ovr_NetSync_SetListenerPosition()
static void Oculus.Platform.CAPI.ovr_NetSync_SetListenerPosition (long connection_id, ref ovrNetSyncVec3 position)
ovr_NetSync_SetVoipAttenuation()
static ulong Oculus.Platform.CAPI.ovr_NetSync_SetVoipAttenuation (long connection_id, float[] distances, float[] decibels, UIntPtr count)
ovr_NetSync_SetVoipAttenuationModel()
static ulong Oculus.Platform.CAPI.ovr_NetSync_SetVoipAttenuationModel (long connection_id, string name, float[] distances, float[] decibels, UIntPtr count) static
ovr_NetSync_SetVoipChannelCfg()
static ulong Oculus.Platform.CAPI.ovr_NetSync_SetVoipChannelCfg (long connection_id, string channel_name, string attnmodel, bool disable_spatialization) static
ovr_NetSync_SetVoipGroup()
static ulong Oculus.Platform.CAPI.ovr_NetSync_SetVoipGroup (long connection_id, string group_id) static
ovr_NetSync_SetVoipListentoChannels()
static ulong Oculus.Platform.CAPI.ovr_NetSync_SetVoipListentoChannels (long connection_id, string[] listento_channels, UIntPtr count)
ovr_NetSync_SetVoipMicSource()
static ulong Oculus.Platform.CAPI.ovr_NetSync_SetVoipMicSource (long connection_id, NetSyncVoipMicSource mic_source)
ovr_NetSync_SetVoipSessionMuted()
static ulong Oculus.Platform.CAPI.ovr_NetSync_SetVoipSessionMuted (long connection_id, UInt64 session_id, bool muted)
ovr_NetSync_SetVoipSpeaktoChannels()
static ulong Oculus.Platform.CAPI.ovr_NetSync_SetVoipSpeaktoChannels (long connection_id, string[] speakto_channels, UIntPtr count)
ovr_NetSync_SetVoipStreamMode()
static ulong Oculus.Platform.CAPI.ovr_NetSync_SetVoipStreamMode (long connection_id, UInt64 sessionId, NetSyncVoipStreamMode streamMode)
ovr_NetSyncConnection_GetConnectionId()
static long Oculus.Platform.CAPI.ovr_NetSyncConnection_GetConnectionId (IntPtr obj)
Referenced by Oculus.Platform.Models.NetSyncConnection.NetSyncConnection().
ovr_NetSyncConnection_GetDisconnectReason()
static NetSyncDisconnectReason Oculus.Platform.CAPI.ovr_NetSyncConnection_GetDisconnectReason (IntPtr obj)
Referenced by Oculus.Platform.Models.NetSyncConnection.NetSyncConnection().
ovr_NetSyncConnection_GetSessionId()
static UInt64 Oculus.Platform.CAPI.ovr_NetSyncConnection_GetSessionId (IntPtr obj)
Referenced by Oculus.Platform.Models.NetSyncConnection.NetSyncConnection().
ovr_NetSyncConnection_GetStatus()
static NetSyncConnectionStatus Oculus.Platform.CAPI.ovr_NetSyncConnection_GetStatus (IntPtr obj)
Referenced by Oculus.Platform.Models.NetSyncConnection.NetSyncConnection().
ovr_NetSyncConnection_GetZoneId()
static string Oculus.Platform.CAPI.ovr_NetSyncConnection_GetZoneId (IntPtr obj) static
Referenced by Oculus.Platform.Models.NetSyncConnection.NetSyncConnection().
ovr_NetSyncOptions_Create()
static IntPtr Oculus.Platform.CAPI.ovr_NetSyncOptions_Create ()
Referenced by Oculus.Platform.NetSyncOptions.NetSyncOptions().
ovr_NetSyncOptions_Destroy()
static void Oculus.Platform.CAPI.ovr_NetSyncOptions_Destroy (IntPtr handle)
ovr_NetSyncOptions_SetVoipGroup()
static void Oculus.Platform.CAPI.ovr_NetSyncOptions_SetVoipGroup (IntPtr handle, string value) static
Referenced by Oculus.Platform.NetSyncOptions.SetVoipGroup().
ovr_NetSyncOptions_SetVoipStreamDefault()
static void Oculus.Platform.CAPI.ovr_NetSyncOptions_SetVoipStreamDefault (IntPtr handle, NetSyncVoipStreamMode value)
Referenced by Oculus.Platform.NetSyncOptions.SetVoipStreamDefault().
ovr_NetSyncOptions_SetZoneId()
static void Oculus.Platform.CAPI.ovr_NetSyncOptions_SetZoneId (IntPtr handle, string value) static
Referenced by Oculus.Platform.NetSyncOptions.SetZoneId().
ovr_NetSyncSession_GetConnectionId()
static long Oculus.Platform.CAPI.ovr_NetSyncSession_GetConnectionId (IntPtr obj)
Referenced by Oculus.Platform.Models.NetSyncSession.NetSyncSession().
ovr_NetSyncSession_GetMuted()
static bool Oculus.Platform.CAPI.ovr_NetSyncSession_GetMuted (IntPtr obj)
Referenced by Oculus.Platform.Models.NetSyncSession.NetSyncSession().
ovr_NetSyncSession_GetSessionId()
static UInt64 Oculus.Platform.CAPI.ovr_NetSyncSession_GetSessionId (IntPtr obj)
Referenced by Oculus.Platform.Models.NetSyncSession.NetSyncSession().
ovr_NetSyncSession_GetUserId()
static UInt64 Oculus.Platform.CAPI.ovr_NetSyncSession_GetUserId (IntPtr obj)
Referenced by Oculus.Platform.Models.NetSyncSession.NetSyncSession().
ovr_NetSyncSession_GetVoipGroup()
static string Oculus.Platform.CAPI.ovr_NetSyncSession_GetVoipGroup (IntPtr obj) static
Referenced by Oculus.Platform.Models.NetSyncSession.NetSyncSession().
ovr_NetSyncSessionArray_GetElement()
static IntPtr Oculus.Platform.CAPI.ovr_NetSyncSessionArray_GetElement (IntPtr obj, UIntPtr index)
Referenced by Oculus.Platform.Models.NetSyncSessionList.NetSyncSessionList().
ovr_NetSyncSessionArray_GetSize()
static UIntPtr Oculus.Platform.CAPI.ovr_NetSyncSessionArray_GetSize (IntPtr obj)
Referenced by Oculus.Platform.Models.NetSyncSessionList.NetSyncSessionList().
ovr_NetSyncSessionsChangedNotification_GetConnectionId()
static long Oculus.Platform.CAPI.ovr_NetSyncSessionsChangedNotification_GetConnectionId (IntPtr obj)
Referenced by Oculus.Platform.Models.NetSyncSessionsChangedNotification.NetSyncSessionsChangedNotification().
ovr_NetSyncSessionsChangedNotification_GetSessions()
static IntPtr Oculus.Platform.CAPI.ovr_NetSyncSessionsChangedNotification_GetSessions (IntPtr obj)
Referenced by Oculus.Platform.Models.NetSyncSessionsChangedNotification.NetSyncSessionsChangedNotification().
ovr_NetSyncSetSessionPropertyResult_GetSession()
static IntPtr Oculus.Platform.CAPI.ovr_NetSyncSetSessionPropertyResult_GetSession (IntPtr obj)
Referenced by Oculus.Platform.Models.NetSyncSetSessionPropertyResult.NetSyncSetSessionPropertyResult().
ovr_NetSyncVoipAttenuationValue_GetDecibels()
static float Oculus.Platform.CAPI.ovr_NetSyncVoipAttenuationValue_GetDecibels (IntPtr obj)
Referenced by Oculus.Platform.Models.NetSyncVoipAttenuationValue.NetSyncVoipAttenuationValue().
ovr_NetSyncVoipAttenuationValue_GetDistance()
static float Oculus.Platform.CAPI.ovr_NetSyncVoipAttenuationValue_GetDistance (IntPtr obj)
Referenced by Oculus.Platform.Models.NetSyncVoipAttenuationValue.NetSyncVoipAttenuationValue().
ovr_NetSyncVoipAttenuationValueArray_GetElement()
static IntPtr Oculus.Platform.CAPI.ovr_NetSyncVoipAttenuationValueArray_GetElement (IntPtr obj, UIntPtr index)
Referenced by Oculus.Platform.Models.NetSyncVoipAttenuationValueList.NetSyncVoipAttenuationValueList().
ovr_NetSyncVoipAttenuationValueArray_GetSize()
static UIntPtr Oculus.Platform.CAPI.ovr_NetSyncVoipAttenuationValueArray_GetSize (IntPtr obj)
Referenced by Oculus.Platform.Models.NetSyncVoipAttenuationValueList.NetSyncVoipAttenuationValueList().
ovr_NetworkingPeer_GetID()
static UInt64 Oculus.Platform.CAPI.ovr_NetworkingPeer_GetID (IntPtr obj)
Referenced by Oculus.Platform.MessageWithNetworkingPeer.GetDataFromMessage().
ovr_NetworkingPeer_GetState()
static PeerConnectionState Oculus.Platform.CAPI.ovr_NetworkingPeer_GetState (IntPtr obj)
Referenced by Oculus.Platform.MessageWithNetworkingPeer.GetDataFromMessage().
ovr_Notification_GetRoomInvites()
static ulong Oculus.Platform.CAPI.ovr_Notification_GetRoomInvites ()
ovr_Notification_MarkAsRead()
static ulong Oculus.Platform.CAPI.ovr_Notification_MarkAsRead (UInt64 notificationID)
ovr_OrgScopedID_GetID()
static UInt64 Oculus.Platform.CAPI.ovr_OrgScopedID_GetID (IntPtr obj)
Referenced by Oculus.Platform.Models.OrgScopedID.OrgScopedID().
ovr_Packet_Free()
static void Oculus.Platform.CAPI.ovr_Packet_Free (IntPtr obj)
Referenced by Oculus.Platform.Packet.Dispose().
ovr_Packet_GetBytes()
static IntPtr Oculus.Platform.CAPI.ovr_Packet_GetBytes (IntPtr obj)
Referenced by Oculus.Platform.Models.HttpTransferUpdate.HttpTransferUpdate(), and Oculus.Platform.Packet.ReadBytes().
ovr_Packet_GetSenderID()
static UInt64 Oculus.Platform.CAPI.ovr_Packet_GetSenderID (IntPtr obj)
ovr_Packet_GetSendPolicy()
static SendPolicy Oculus.Platform.CAPI.ovr_Packet_GetSendPolicy (IntPtr obj)
ovr_Packet_GetSize()
static UIntPtr Oculus.Platform.CAPI.ovr_Packet_GetSize (IntPtr obj)
Referenced by Oculus.Platform.Packet.Packet().
ovr_Party_Create()
static ulong Oculus.Platform.CAPI.ovr_Party_Create ()
ovr_Party_GatherInApplication()
static ulong Oculus.Platform.CAPI.ovr_Party_GatherInApplication (UInt64 partyID, UInt64 appID)
ovr_Party_Get()
static ulong Oculus.Platform.CAPI.ovr_Party_Get (UInt64 partyID)
ovr_Party_GetCurrent()
static ulong Oculus.Platform.CAPI.ovr_Party_GetCurrent ()
ovr_Party_GetCurrentForUser()
static ulong Oculus.Platform.CAPI.ovr_Party_GetCurrentForUser (UInt64 userID)
ovr_Party_GetID()
static UInt64 Oculus.Platform.CAPI.ovr_Party_GetID (IntPtr obj)
Referenced by Oculus.Platform.Models.Party.Party().
ovr_Party_GetInvitedUsers()
static IntPtr Oculus.Platform.CAPI.ovr_Party_GetInvitedUsers (IntPtr obj)
Referenced by Oculus.Platform.Models.Party.Party().
ovr_Party_GetLeader()
static IntPtr Oculus.Platform.CAPI.ovr_Party_GetLeader (IntPtr obj)
Referenced by Oculus.Platform.Models.Party.Party().
ovr_Party_GetRoom()
static IntPtr Oculus.Platform.CAPI.ovr_Party_GetRoom (IntPtr obj)
Referenced by Oculus.Platform.Models.Party.Party().
ovr_Party_GetUsers()
static IntPtr Oculus.Platform.CAPI.ovr_Party_GetUsers (IntPtr obj)
Referenced by Oculus.Platform.Models.Party.Party().
ovr_Party_Invite()
static ulong Oculus.Platform.CAPI.ovr_Party_Invite (UInt64 partyID, UInt64 userID)
ovr_Party_Join()
static ulong Oculus.Platform.CAPI.ovr_Party_Join (UInt64 partyID)
ovr_Party_Leave()
static ulong Oculus.Platform.CAPI.ovr_Party_Leave (UInt64 partyID)
ovr_Party_PluginGetSharedMemHandle()
static int Oculus.Platform.CAPI.ovr_Party_PluginGetSharedMemHandle ()
ovr_Party_PluginGetVoipMicrophoneMuted()
static VoipMuteState Oculus.Platform.CAPI.ovr_Party_PluginGetVoipMicrophoneMuted ()
ovr_Party_PluginGetVoipPassthrough()
static bool Oculus.Platform.CAPI.ovr_Party_PluginGetVoipPassthrough ()
ovr_Party_PluginGetVoipStatus()
static SystemVoipStatus Oculus.Platform.CAPI.ovr_Party_PluginGetVoipStatus ()
ovr_PartyID_GetID()
static UInt64 Oculus.Platform.CAPI.ovr_PartyID_GetID (IntPtr obj)
Referenced by Oculus.Platform.Models.PartyID.PartyID().
ovr_PartyUpdateNotification_GetAction()
static PartyUpdateAction Oculus.Platform.CAPI.ovr_PartyUpdateNotification_GetAction (IntPtr obj)
Referenced by Oculus.Platform.Models.PartyUpdateNotification.PartyUpdateNotification().
ovr_PartyUpdateNotification_GetPartyId()
static UInt64 Oculus.Platform.CAPI.ovr_PartyUpdateNotification_GetPartyId (IntPtr obj)
Referenced by Oculus.Platform.Models.PartyUpdateNotification.PartyUpdateNotification().
ovr_PartyUpdateNotification_GetSenderId()
static UInt64 Oculus.Platform.CAPI.ovr_PartyUpdateNotification_GetSenderId (IntPtr obj)
Referenced by Oculus.Platform.Models.PartyUpdateNotification.PartyUpdateNotification().
ovr_PartyUpdateNotification_GetUpdateTimestamp()
static string Oculus.Platform.CAPI.ovr_PartyUpdateNotification_GetUpdateTimestamp (IntPtr obj) static
Referenced by Oculus.Platform.Models.PartyUpdateNotification.PartyUpdateNotification().
ovr_PartyUpdateNotification_GetUserAlias()
static string Oculus.Platform.CAPI.ovr_PartyUpdateNotification_GetUserAlias (IntPtr obj) static
Referenced by Oculus.Platform.Models.PartyUpdateNotification.PartyUpdateNotification().
ovr_PartyUpdateNotification_GetUserId()
static UInt64 Oculus.Platform.CAPI.ovr_PartyUpdateNotification_GetUserId (IntPtr obj)
Referenced by Oculus.Platform.Models.PartyUpdateNotification.PartyUpdateNotification().
ovr_PartyUpdateNotification_GetUserName()
static string Oculus.Platform.CAPI.ovr_PartyUpdateNotification_GetUserName (IntPtr obj) static
Referenced by Oculus.Platform.Models.PartyUpdateNotification.PartyUpdateNotification().
ovr_Pid_GetId()
static string Oculus.Platform.CAPI.ovr_Pid_GetId (IntPtr obj) static
Referenced by Oculus.Platform.Models.Pid.Pid().
ovr_PidArray_GetElement()
static IntPtr Oculus.Platform.CAPI.ovr_PidArray_GetElement (IntPtr obj, UIntPtr index)
Referenced by Oculus.Platform.Models.PidList.PidList().
ovr_PidArray_GetSize()
static UIntPtr Oculus.Platform.CAPI.ovr_PidArray_GetSize (IntPtr obj)
Referenced by Oculus.Platform.Models.PidList.PidList().
ovr_PingResult_GetID()
static UInt64 Oculus.Platform.CAPI.ovr_PingResult_GetID (IntPtr obj)
Referenced by Oculus.Platform.MessageWithPingResult.GetDataFromMessage().
ovr_PingResult_GetPingTimeUsec()
static ulong Oculus.Platform.CAPI.ovr_PingResult_GetPingTimeUsec (IntPtr obj)
Referenced by Oculus.Platform.MessageWithPingResult.GetDataFromMessage().
ovr_PingResult_IsTimeout()
static bool Oculus.Platform.CAPI.ovr_PingResult_IsTimeout (IntPtr obj)
Referenced by Oculus.Platform.MessageWithPingResult.GetDataFromMessage().
ovr_Platform_InitializeStandaloneOculus()
static ulong Oculus.Platform.CAPI.ovr_Platform_InitializeStandaloneOculus (ref OculusInitParams init)
ovr_PlatformInitialize_GetResult()
static PlatformInitializeResult Oculus.Platform.CAPI.ovr_PlatformInitialize_GetResult (IntPtr obj)
Referenced by Oculus.Platform.Models.PlatformInitialize.PlatformInitialize().
ovr_PlatformInitializeWithAccessToken()
static ulong Oculus.Platform.CAPI.ovr_PlatformInitializeWithAccessToken (UInt64 appId, string accessToken)
Referenced by Oculus.Platform.StandalonePlatform.AsyncInitialize().
ovr_PopMessage()
static IntPtr Oculus.Platform.CAPI.ovr_PopMessage ()
Referenced by Oculus.Platform.Message< T >.PopMessage().
ovr_Price_GetAmountInHundredths()
static uint Oculus.Platform.CAPI.ovr_Price_GetAmountInHundredths (IntPtr obj)
ovr_Price_GetCurrency()
static string Oculus.Platform.CAPI.ovr_Price_GetCurrency (IntPtr obj) static
ovr_Price_GetFormatted()
static string Oculus.Platform.CAPI.ovr_Price_GetFormatted (IntPtr obj) static
ovr_Product_GetDescription()
static string Oculus.Platform.CAPI.ovr_Product_GetDescription (IntPtr obj) static
Referenced by Oculus.Platform.Models.Product.Product().
ovr_Product_GetFormattedPrice()
static string Oculus.Platform.CAPI.ovr_Product_GetFormattedPrice (IntPtr obj) static
Referenced by Oculus.Platform.Models.Product.Product().
ovr_Product_GetName()
static string Oculus.Platform.CAPI.ovr_Product_GetName (IntPtr obj) static
Referenced by Oculus.Platform.Models.Product.Product().
ovr_Product_GetSKU()
static string Oculus.Platform.CAPI.ovr_Product_GetSKU (IntPtr obj) static
Referenced by Oculus.Platform.Models.Product.Product().
ovr_ProductArray_GetElement()
static IntPtr Oculus.Platform.CAPI.ovr_ProductArray_GetElement (IntPtr obj, UIntPtr index)
Referenced by Oculus.Platform.Models.ProductList.ProductList().
ovr_ProductArray_GetNextUrl()
static string Oculus.Platform.CAPI.ovr_ProductArray_GetNextUrl (IntPtr obj) static
Referenced by Oculus.Platform.Models.ProductList.ProductList().
ovr_ProductArray_GetSize()
static UIntPtr Oculus.Platform.CAPI.ovr_ProductArray_GetSize (IntPtr obj)
Referenced by Oculus.Platform.Models.ProductList.ProductList().
ovr_ProductArray_HasNextPage()
static bool Oculus.Platform.CAPI.ovr_ProductArray_HasNextPage (IntPtr obj)
ovr_Purchase_GetExpirationTime()
static DateTime Oculus.Platform.CAPI.ovr_Purchase_GetExpirationTime (IntPtr obj) static
Referenced by Oculus.Platform.Models.Purchase.Purchase().
ovr_Purchase_GetGrantTime()
static DateTime Oculus.Platform.CAPI.ovr_Purchase_GetGrantTime (IntPtr obj) static
Referenced by Oculus.Platform.Models.Purchase.Purchase().
ovr_Purchase_GetPurchaseID()
static UInt64 Oculus.Platform.CAPI.ovr_Purchase_GetPurchaseID (IntPtr obj)
ovr_Purchase_GetPurchaseStrID()
static string Oculus.Platform.CAPI.ovr_Purchase_GetPurchaseStrID (IntPtr obj) static
Referenced by Oculus.Platform.Models.Purchase.Purchase().
ovr_Purchase_GetSKU()
static string Oculus.Platform.CAPI.ovr_Purchase_GetSKU (IntPtr obj) static
Referenced by Oculus.Platform.Models.Purchase.Purchase().
ovr_PurchaseArray_GetElement()
static IntPtr Oculus.Platform.CAPI.ovr_PurchaseArray_GetElement (IntPtr obj, UIntPtr index)
Referenced by Oculus.Platform.Models.PurchaseList.PurchaseList().
ovr_PurchaseArray_GetNextUrl()
static string Oculus.Platform.CAPI.ovr_PurchaseArray_GetNextUrl (IntPtr obj) static
Referenced by Oculus.Platform.Models.PurchaseList.PurchaseList().
ovr_PurchaseArray_GetSize()
static UIntPtr Oculus.Platform.CAPI.ovr_PurchaseArray_GetSize (IntPtr obj)
Referenced by Oculus.Platform.Models.PurchaseList.PurchaseList().
ovr_PurchaseArray_HasNextPage()
static bool Oculus.Platform.CAPI.ovr_PurchaseArray_HasNextPage (IntPtr obj)
ovr_RejoinDialogResult_GetRejoinSelected()
static bool Oculus.Platform.CAPI.ovr_RejoinDialogResult_GetRejoinSelected (IntPtr obj)
Referenced by Oculus.Platform.Models.RejoinDialogResult.RejoinDialogResult().
ovr_RichPresence_Clear()
static ulong Oculus.Platform.CAPI.ovr_RichPresence_Clear ()
ovr_RichPresence_GetDestinations()
static ulong Oculus.Platform.CAPI.ovr_RichPresence_GetDestinations ()
ovr_RichPresence_Set()
static ulong Oculus.Platform.CAPI.ovr_RichPresence_Set (IntPtr richPresenceOptions)
ovr_RichPresence_SetDestination()
static ulong Oculus.Platform.CAPI.ovr_RichPresence_SetDestination (string api_name) static
ovr_RichPresence_SetIsJoinable()
static ulong Oculus.Platform.CAPI.ovr_RichPresence_SetIsJoinable (bool is_joinable)
ovr_RichPresence_SetLobbySession()
static ulong Oculus.Platform.CAPI.ovr_RichPresence_SetLobbySession (string id) static
ovr_RichPresence_SetMatchSession()
static ulong Oculus.Platform.CAPI.ovr_RichPresence_SetMatchSession (string id) static
ovr_RichPresenceOptions_ClearArgs()
static void Oculus.Platform.CAPI.ovr_RichPresenceOptions_ClearArgs (IntPtr handle)
ovr_RichPresenceOptions_Create()
static IntPtr Oculus.Platform.CAPI.ovr_RichPresenceOptions_Create ()
Referenced by Oculus.Platform.RichPresenceOptions.RichPresenceOptions().
ovr_RichPresenceOptions_Destroy()
static void Oculus.Platform.CAPI.ovr_RichPresenceOptions_Destroy (IntPtr handle)
ovr_RichPresenceOptions_SetApiName()
static void Oculus.Platform.CAPI.ovr_RichPresenceOptions_SetApiName (IntPtr handle, string value) static
Referenced by Oculus.Platform.RichPresenceOptions.SetApiName().
ovr_RichPresenceOptions_SetArgsString()
static void Oculus.Platform.CAPI.ovr_RichPresenceOptions_SetArgsString (IntPtr handle, string key, string value) static
ovr_RichPresenceOptions_SetCurrentCapacity()
static void Oculus.Platform.CAPI.ovr_RichPresenceOptions_SetCurrentCapacity (IntPtr handle, uint value)
Referenced by Oculus.Platform.RichPresenceOptions.SetCurrentCapacity().
ovr_RichPresenceOptions_SetDeeplinkMessageOverride()
static void Oculus.Platform.CAPI.ovr_RichPresenceOptions_SetDeeplinkMessageOverride (IntPtr handle, string value) static
Referenced by Oculus.Platform.RichPresenceOptions.SetDeeplinkMessageOverride().
ovr_RichPresenceOptions_SetEndTime()
static void Oculus.Platform.CAPI.ovr_RichPresenceOptions_SetEndTime (IntPtr handle, DateTime value) static
Referenced by Oculus.Platform.RichPresenceOptions.SetEndTime().
ovr_RichPresenceOptions_SetExtraContext()
static void Oculus.Platform.CAPI.ovr_RichPresenceOptions_SetExtraContext (IntPtr handle, RichPresenceExtraContext value)
Referenced by Oculus.Platform.RichPresenceOptions.SetExtraContext().
ovr_RichPresenceOptions_SetInstanceId()
static void Oculus.Platform.CAPI.ovr_RichPresenceOptions_SetInstanceId (IntPtr handle, string value) static
Referenced by Oculus.Platform.RichPresenceOptions.SetInstanceId().
ovr_RichPresenceOptions_SetIsIdle()
static void Oculus.Platform.CAPI.ovr_RichPresenceOptions_SetIsIdle (IntPtr handle, bool value)
Referenced by Oculus.Platform.RichPresenceOptions.SetIsIdle().
ovr_RichPresenceOptions_SetIsJoinable()
static void Oculus.Platform.CAPI.ovr_RichPresenceOptions_SetIsJoinable (IntPtr handle, bool value)
Referenced by Oculus.Platform.RichPresenceOptions.SetIsJoinable().
ovr_RichPresenceOptions_SetJoinableId()
static void Oculus.Platform.CAPI.ovr_RichPresenceOptions_SetJoinableId (IntPtr handle, string value) static
ovr_RichPresenceOptions_SetLobbySessionId()
static void Oculus.Platform.CAPI.ovr_RichPresenceOptions_SetLobbySessionId (IntPtr handle, string value) static
ovr_RichPresenceOptions_SetMatchSessionId()
static void Oculus.Platform.CAPI.ovr_RichPresenceOptions_SetMatchSessionId (IntPtr handle, string value) static
ovr_RichPresenceOptions_SetMaxCapacity()
static void Oculus.Platform.CAPI.ovr_RichPresenceOptions_SetMaxCapacity (IntPtr handle, uint value)
Referenced by Oculus.Platform.RichPresenceOptions.SetMaxCapacity().
ovr_RichPresenceOptions_SetStartTime()
static void Oculus.Platform.CAPI.ovr_RichPresenceOptions_SetStartTime (IntPtr handle, DateTime value) static
Referenced by Oculus.Platform.RichPresenceOptions.SetStartTime().
ovr_Room_CreateAndJoinPrivate()
static ulong Oculus.Platform.CAPI.ovr_Room_CreateAndJoinPrivate (RoomJoinPolicy joinPolicy, uint maxUsers, bool subscribeToUpdates)
ovr_Room_CreateAndJoinPrivate2()
static ulong Oculus.Platform.CAPI.ovr_Room_CreateAndJoinPrivate2 (RoomJoinPolicy joinPolicy, uint maxUsers, IntPtr roomOptions)
ovr_Room_Get()
static ulong Oculus.Platform.CAPI.ovr_Room_Get (UInt64 roomID)
ovr_Room_GetApplicationID()
static UInt64 Oculus.Platform.CAPI.ovr_Room_GetApplicationID (IntPtr obj)
Referenced by Oculus.Platform.Models.Room.Room().
ovr_Room_GetCurrent()
static ulong Oculus.Platform.CAPI.ovr_Room_GetCurrent ()
ovr_Room_GetCurrentForUser()
static ulong Oculus.Platform.CAPI.ovr_Room_GetCurrentForUser (UInt64 userID)
ovr_Room_GetDataStore()
static IntPtr Oculus.Platform.CAPI.ovr_Room_GetDataStore (IntPtr obj)
Referenced by Oculus.Platform.Models.Room.Room().
ovr_Room_GetDescription()
static string Oculus.Platform.CAPI.ovr_Room_GetDescription (IntPtr obj) static
Referenced by Oculus.Platform.Models.Room.Room().
ovr_Room_GetID()
static UInt64 Oculus.Platform.CAPI.ovr_Room_GetID (IntPtr obj)
Referenced by Oculus.Platform.Models.Room.Room().
ovr_Room_GetInvitableUsers()
static ulong Oculus.Platform.CAPI.ovr_Room_GetInvitableUsers ()
ovr_Room_GetInvitableUsers2()
static ulong Oculus.Platform.CAPI.ovr_Room_GetInvitableUsers2 (IntPtr roomOptions)
ovr_Room_GetInvitedUsers()
static IntPtr Oculus.Platform.CAPI.ovr_Room_GetInvitedUsers (IntPtr obj)
Referenced by Oculus.Platform.Models.Room.Room().
ovr_Room_GetIsMembershipLocked()
static bool Oculus.Platform.CAPI.ovr_Room_GetIsMembershipLocked (IntPtr obj)
Referenced by Oculus.Platform.Models.Room.Room().
ovr_Room_GetJoinability()
static RoomJoinability Oculus.Platform.CAPI.ovr_Room_GetJoinability (IntPtr obj)
Referenced by Oculus.Platform.Models.Room.Room().
ovr_Room_GetJoinPolicy()
static RoomJoinPolicy Oculus.Platform.CAPI.ovr_Room_GetJoinPolicy (IntPtr obj)
Referenced by Oculus.Platform.Models.Room.Room().
ovr_Room_GetMatchedUsers()
static IntPtr Oculus.Platform.CAPI.ovr_Room_GetMatchedUsers (IntPtr obj)
Referenced by Oculus.Platform.Models.Room.Room().
ovr_Room_GetMaxUsers()
static uint Oculus.Platform.CAPI.ovr_Room_GetMaxUsers (IntPtr obj)
Referenced by Oculus.Platform.Models.Room.Room().
ovr_Room_GetModeratedRooms()
static ulong Oculus.Platform.CAPI.ovr_Room_GetModeratedRooms ()
ovr_Room_GetName()
static string Oculus.Platform.CAPI.ovr_Room_GetName (IntPtr obj) static
Referenced by Oculus.Platform.Models.Room.Room().
ovr_Room_GetOwner()
static IntPtr Oculus.Platform.CAPI.ovr_Room_GetOwner (IntPtr obj)
Referenced by Oculus.Platform.Models.Room.Room().
ovr_Room_GetSocialRooms()
static ulong Oculus.Platform.CAPI.ovr_Room_GetSocialRooms (UInt64 appID)
ovr_Room_GetTeams()
static IntPtr Oculus.Platform.CAPI.ovr_Room_GetTeams (IntPtr obj)
Referenced by Oculus.Platform.Models.Room.Room().
ovr_Room_GetType()
static RoomType Oculus.Platform.CAPI.ovr_Room_GetType (IntPtr obj)
Referenced by Oculus.Platform.Models.Room.Room().
ovr_Room_GetUsers()
static IntPtr Oculus.Platform.CAPI.ovr_Room_GetUsers (IntPtr obj)
Referenced by Oculus.Platform.Models.Room.Room().
ovr_Room_GetVersion()
static uint Oculus.Platform.CAPI.ovr_Room_GetVersion (IntPtr obj)
Referenced by Oculus.Platform.Models.Room.Room().
ovr_Room_InviteUser()
static ulong Oculus.Platform.CAPI.ovr_Room_InviteUser (UInt64 roomID, string inviteToken) static
ovr_Room_Join()
static ulong Oculus.Platform.CAPI.ovr_Room_Join (UInt64 roomID, bool subscribeToUpdates)
ovr_Room_Join2()
static ulong Oculus.Platform.CAPI.ovr_Room_Join2 (UInt64 roomID, IntPtr roomOptions)
ovr_Room_KickUser()
static ulong Oculus.Platform.CAPI.ovr_Room_KickUser (UInt64 roomID, UInt64 userID, int kickDurationSeconds)
ovr_Room_LaunchInvitableUserFlow()
static ulong Oculus.Platform.CAPI.ovr_Room_LaunchInvitableUserFlow (UInt64 roomID)
ovr_Room_Leave()
static ulong Oculus.Platform.CAPI.ovr_Room_Leave (UInt64 roomID)
ovr_Room_SetDescription()
static ulong Oculus.Platform.CAPI.ovr_Room_SetDescription (UInt64 roomID, string description) static
ovr_Room_UpdateDataStore()
static ulong Oculus.Platform.CAPI.ovr_Room_UpdateDataStore (UInt64 roomID, ovrKeyValuePair[] data) static
ovr_Room_UpdateMembershipLockStatus()
static ulong Oculus.Platform.CAPI.ovr_Room_UpdateMembershipLockStatus (UInt64 roomID, RoomMembershipLockStatus membershipLockStatus)
ovr_Room_UpdateOwner()
static ulong Oculus.Platform.CAPI.ovr_Room_UpdateOwner (UInt64 roomID, UInt64 userID)
ovr_Room_UpdatePrivateRoomJoinPolicy()
static ulong Oculus.Platform.CAPI.ovr_Room_UpdatePrivateRoomJoinPolicy (UInt64 roomID, RoomJoinPolicy newJoinPolicy)
ovr_RoomArray_GetElement()
static IntPtr Oculus.Platform.CAPI.ovr_RoomArray_GetElement (IntPtr obj, UIntPtr index)
Referenced by Oculus.Platform.Models.RoomList.RoomList().
ovr_RoomArray_GetNextUrl()
static string Oculus.Platform.CAPI.ovr_RoomArray_GetNextUrl (IntPtr obj) static
Referenced by Oculus.Platform.Models.RoomList.RoomList().
ovr_RoomArray_GetSize()
static UIntPtr Oculus.Platform.CAPI.ovr_RoomArray_GetSize (IntPtr obj)
Referenced by Oculus.Platform.Models.RoomList.RoomList().
ovr_RoomArray_HasNextPage()
static bool Oculus.Platform.CAPI.ovr_RoomArray_HasNextPage (IntPtr obj)
ovr_RoomInviteNotification_GetID()
static UInt64 Oculus.Platform.CAPI.ovr_RoomInviteNotification_GetID (IntPtr obj)
Referenced by Oculus.Platform.Models.RoomInviteNotification.RoomInviteNotification().
ovr_RoomInviteNotification_GetRoomID()
static UInt64 Oculus.Platform.CAPI.ovr_RoomInviteNotification_GetRoomID (IntPtr obj)
Referenced by Oculus.Platform.Models.RoomInviteNotification.RoomInviteNotification().
ovr_RoomInviteNotification_GetSenderID()
static UInt64 Oculus.Platform.CAPI.ovr_RoomInviteNotification_GetSenderID (IntPtr obj)
Referenced by Oculus.Platform.Models.RoomInviteNotification.RoomInviteNotification().
ovr_RoomInviteNotification_GetSentTime()
static DateTime Oculus.Platform.CAPI.ovr_RoomInviteNotification_GetSentTime (IntPtr obj) static
Referenced by Oculus.Platform.Models.RoomInviteNotification.RoomInviteNotification().
ovr_RoomInviteNotificationArray_GetElement()
static IntPtr Oculus.Platform.CAPI.ovr_RoomInviteNotificationArray_GetElement (IntPtr obj, UIntPtr index)
Referenced by Oculus.Platform.Models.RoomInviteNotificationList.RoomInviteNotificationList().
ovr_RoomInviteNotificationArray_GetNextUrl()
static string Oculus.Platform.CAPI.ovr_RoomInviteNotificationArray_GetNextUrl (IntPtr obj) static
Referenced by Oculus.Platform.Models.RoomInviteNotificationList.RoomInviteNotificationList().
ovr_RoomInviteNotificationArray_GetSize()
static UIntPtr Oculus.Platform.CAPI.ovr_RoomInviteNotificationArray_GetSize (IntPtr obj)
Referenced by Oculus.Platform.Models.RoomInviteNotificationList.RoomInviteNotificationList().
ovr_RoomInviteNotificationArray_HasNextPage()
static bool Oculus.Platform.CAPI.ovr_RoomInviteNotificationArray_HasNextPage (IntPtr obj)
ovr_RoomOptions_ClearDataStore()
static void Oculus.Platform.CAPI.ovr_RoomOptions_ClearDataStore (IntPtr handle)
Referenced by Oculus.Platform.RoomOptions.ClearDataStore().
ovr_RoomOptions_Create()
static IntPtr Oculus.Platform.CAPI.ovr_RoomOptions_Create ()
Referenced by Oculus.Platform.RoomOptions.RoomOptions().
ovr_RoomOptions_Destroy()
static void Oculus.Platform.CAPI.ovr_RoomOptions_Destroy (IntPtr handle)
ovr_RoomOptions_SetDataStoreString()
static void Oculus.Platform.CAPI.ovr_RoomOptions_SetDataStoreString (IntPtr handle, string key, string value) static
Referenced by Oculus.Platform.RoomOptions.SetDataStore().
ovr_RoomOptions_SetExcludeRecentlyMet()
static void Oculus.Platform.CAPI.ovr_RoomOptions_SetExcludeRecentlyMet (IntPtr handle, bool value)
Referenced by Oculus.Platform.RoomOptions.SetExcludeRecentlyMet().
ovr_RoomOptions_SetMaxUserResults()
static void Oculus.Platform.CAPI.ovr_RoomOptions_SetMaxUserResults (IntPtr handle, uint value)
Referenced by Oculus.Platform.RoomOptions.SetMaxUserResults().
ovr_RoomOptions_SetOrdering()
static void Oculus.Platform.CAPI.ovr_RoomOptions_SetOrdering (IntPtr handle, UserOrdering value)
Referenced by Oculus.Platform.RoomOptions.SetOrdering().
ovr_RoomOptions_SetRecentlyMetTimeWindow()
static void Oculus.Platform.CAPI.ovr_RoomOptions_SetRecentlyMetTimeWindow (IntPtr handle, TimeWindow value)
Referenced by Oculus.Platform.RoomOptions.SetRecentlyMetTimeWindow().
ovr_RoomOptions_SetRoomId()
static void Oculus.Platform.CAPI.ovr_RoomOptions_SetRoomId (IntPtr handle, UInt64 value)
Referenced by Oculus.Platform.RoomOptions.SetRoomId().
ovr_RoomOptions_SetTurnOffUpdates()
static void Oculus.Platform.CAPI.ovr_RoomOptions_SetTurnOffUpdates (IntPtr handle, bool value)
Referenced by Oculus.Platform.RoomOptions.SetTurnOffUpdates().
ovr_RosterOptions_AddSuggestedUser()
static void Oculus.Platform.CAPI.ovr_RosterOptions_AddSuggestedUser (IntPtr handle, UInt64 value)
Referenced by Oculus.Platform.RosterOptions.AddSuggestedUser().
ovr_RosterOptions_ClearSuggestedUsers()
static void Oculus.Platform.CAPI.ovr_RosterOptions_ClearSuggestedUsers (IntPtr handle)
Referenced by Oculus.Platform.RosterOptions.ClearSuggestedUsers().
ovr_RosterOptions_Create()
static IntPtr Oculus.Platform.CAPI.ovr_RosterOptions_Create ()
Referenced by Oculus.Platform.RosterOptions.RosterOptions().
ovr_RosterOptions_Destroy()
static void Oculus.Platform.CAPI.ovr_RosterOptions_Destroy (IntPtr handle)
ovr_SdkAccount_GetAccountType()
static SdkAccountType Oculus.Platform.CAPI.ovr_SdkAccount_GetAccountType (IntPtr obj)
Referenced by Oculus.Platform.Models.SdkAccount.SdkAccount().
ovr_SdkAccount_GetUserId()
static UInt64 Oculus.Platform.CAPI.ovr_SdkAccount_GetUserId (IntPtr obj)
Referenced by Oculus.Platform.Models.SdkAccount.SdkAccount().
ovr_SdkAccountArray_GetElement()
static IntPtr Oculus.Platform.CAPI.ovr_SdkAccountArray_GetElement (IntPtr obj, UIntPtr index)
Referenced by Oculus.Platform.Models.SdkAccountList.SdkAccountList().
ovr_SdkAccountArray_GetSize()
static UIntPtr Oculus.Platform.CAPI.ovr_SdkAccountArray_GetSize (IntPtr obj)
Referenced by Oculus.Platform.Models.SdkAccountList.SdkAccountList().
ovr_SendInvitesResult_GetInvites()
static IntPtr Oculus.Platform.CAPI.ovr_SendInvitesResult_GetInvites (IntPtr obj)
Referenced by Oculus.Platform.Models.SendInvitesResult.SendInvitesResult().
ovr_SetDeveloperAccessToken()
static bool Oculus.Platform.CAPI.ovr_SetDeveloperAccessToken (string accessToken)
ovr_ShareMediaResult_GetStatus()
static ShareMediaStatus Oculus.Platform.CAPI.ovr_ShareMediaResult_GetStatus (IntPtr obj)
Referenced by Oculus.Platform.Models.ShareMediaResult.ShareMediaResult().
ovr_SupplementaryMetric_GetID()
static UInt64 Oculus.Platform.CAPI.ovr_SupplementaryMetric_GetID (IntPtr obj)
Referenced by Oculus.Platform.Models.SupplementaryMetric.SupplementaryMetric().
ovr_SupplementaryMetric_GetMetric()
static long Oculus.Platform.CAPI.ovr_SupplementaryMetric_GetMetric (IntPtr obj)
Referenced by Oculus.Platform.Models.SupplementaryMetric.SupplementaryMetric().
ovr_SystemVoipState_GetMicrophoneMuted()
static VoipMuteState Oculus.Platform.CAPI.ovr_SystemVoipState_GetMicrophoneMuted (IntPtr obj)
Referenced by Oculus.Platform.Models.SystemVoipState.SystemVoipState().
ovr_SystemVoipState_GetStatus()
static SystemVoipStatus Oculus.Platform.CAPI.ovr_SystemVoipState_GetStatus (IntPtr obj)
Referenced by Oculus.Platform.Models.SystemVoipState.SystemVoipState().
ovr_Team_GetAssignedUsers()
static IntPtr Oculus.Platform.CAPI.ovr_Team_GetAssignedUsers (IntPtr obj)
Referenced by Oculus.Platform.Models.Team.Team().
ovr_Team_GetMaxUsers()
static int Oculus.Platform.CAPI.ovr_Team_GetMaxUsers (IntPtr obj)
Referenced by Oculus.Platform.Models.Team.Team().
ovr_Team_GetMinUsers()
static int Oculus.Platform.CAPI.ovr_Team_GetMinUsers (IntPtr obj)
Referenced by Oculus.Platform.Models.Team.Team().
ovr_Team_GetName()
static string Oculus.Platform.CAPI.ovr_Team_GetName (IntPtr obj) static
Referenced by Oculus.Platform.Models.Team.Team().
ovr_TeamArray_GetElement()
static IntPtr Oculus.Platform.CAPI.ovr_TeamArray_GetElement (IntPtr obj, UIntPtr index)
Referenced by Oculus.Platform.Models.TeamList.TeamList().
ovr_TeamArray_GetSize()
static UIntPtr Oculus.Platform.CAPI.ovr_TeamArray_GetSize (IntPtr obj)
Referenced by Oculus.Platform.Models.TeamList.TeamList().
ovr_TestUser_GetAccessToken()
static string Oculus.Platform.CAPI.ovr_TestUser_GetAccessToken (IntPtr obj) static
ovr_TestUser_GetAppAccessArray()
static IntPtr Oculus.Platform.CAPI.ovr_TestUser_GetAppAccessArray (IntPtr obj)
ovr_TestUser_GetFbAppAccessArray()
static IntPtr Oculus.Platform.CAPI.ovr_TestUser_GetFbAppAccessArray (IntPtr obj)
ovr_TestUser_GetFriendAccessToken()
static string Oculus.Platform.CAPI.ovr_TestUser_GetFriendAccessToken (IntPtr obj) static
ovr_TestUser_GetFriendAppAccessArray()
static IntPtr Oculus.Platform.CAPI.ovr_TestUser_GetFriendAppAccessArray (IntPtr obj)
ovr_TestUser_GetUserAlias()
static string Oculus.Platform.CAPI.ovr_TestUser_GetUserAlias (IntPtr obj) static
ovr_TestUser_GetUserFbid()
static UInt64 Oculus.Platform.CAPI.ovr_TestUser_GetUserFbid (IntPtr obj)
ovr_TestUser_GetUserId()
static UInt64 Oculus.Platform.CAPI.ovr_TestUser_GetUserId (IntPtr obj)
ovr_TestUserAppAccess_GetAccessToken()
static string Oculus.Platform.CAPI.ovr_TestUserAppAccess_GetAccessToken (IntPtr obj) static
ovr_TestUserAppAccess_GetAppId()
static UInt64 Oculus.Platform.CAPI.ovr_TestUserAppAccess_GetAppId (IntPtr obj)
ovr_TestUserAppAccess_GetUserId()
static UInt64 Oculus.Platform.CAPI.ovr_TestUserAppAccess_GetUserId (IntPtr obj)
ovr_TestUserAppAccessArray_GetElement()
static IntPtr Oculus.Platform.CAPI.ovr_TestUserAppAccessArray_GetElement (IntPtr obj, UIntPtr index)
ovr_TestUserAppAccessArray_GetSize()
static UIntPtr Oculus.Platform.CAPI.ovr_TestUserAppAccessArray_GetSize (IntPtr obj)
ovr_UnityInitGlobals()
static void Oculus.Platform.CAPI.ovr_UnityInitGlobals (IntPtr loggingCB)
Referenced by Oculus.Platform.StandalonePlatform.AsyncInitialize().
ovr_UnityInitWrapper()
static bool Oculus.Platform.CAPI.ovr_UnityInitWrapper (string appId)
Referenced by Oculus.Platform.AndroidPlatform.Initialize().
ovr_UnityInitWrapperAsynchronous()
static ulong Oculus.Platform.CAPI.ovr_UnityInitWrapperAsynchronous (string appId)
Referenced by Oculus.Platform.AndroidPlatform.AsyncInitialize().
ovr_UnityInitWrapperStandalone()
static bool Oculus.Platform.CAPI.ovr_UnityInitWrapperStandalone (string accessToken, IntPtr loggingCB)
ovr_UnityInitWrapperWindows()
static bool Oculus.Platform.CAPI.ovr_UnityInitWrapperWindows (string appId, IntPtr loggingCB)
Referenced by Oculus.Platform.WindowsPlatform.Initialize().
ovr_UnityInitWrapperWindowsAsynchronous()
static ulong Oculus.Platform.CAPI.ovr_UnityInitWrapperWindowsAsynchronous (string appId, IntPtr loggingCB)
Referenced by Oculus.Platform.WindowsPlatform.AsyncInitialize().
ovr_UnityResetTestPlatform()
static void Oculus.Platform.CAPI.ovr_UnityResetTestPlatform ()
Referenced by Oculus.Platform.StandalonePlatform.AsyncInitialize().
ovr_User_CancelRecordingForReportFlow()
static ulong Oculus.Platform.CAPI.ovr_User_CancelRecordingForReportFlow (string recordingUUID) static
ovr_User_Get()
static ulong Oculus.Platform.CAPI.ovr_User_Get (UInt64 userID)
ovr_User_GetAccessToken()
static ulong Oculus.Platform.CAPI.ovr_User_GetAccessToken ()
ovr_User_GetDisplayName()
static string Oculus.Platform.CAPI.ovr_User_GetDisplayName (IntPtr obj) static
Referenced by Oculus.Platform.Models.User.User().
ovr_User_GetID()
static UInt64 Oculus.Platform.CAPI.ovr_User_GetID (IntPtr obj)
Referenced by Oculus.Platform.Models.User.User().
ovr_User_GetImageUrl()
static string Oculus.Platform.CAPI.ovr_User_GetImageUrl (IntPtr obj) static
Referenced by Oculus.Platform.Models.User.User().
ovr_User_GetInviteToken()
static string Oculus.Platform.CAPI.ovr_User_GetInviteToken (IntPtr obj) static
Referenced by Oculus.Platform.Models.User.User().
ovr_User_GetLinkedAccounts()
static ulong Oculus.Platform.CAPI.ovr_User_GetLinkedAccounts (IntPtr userOptions)
ovr_User_GetLoggedInUser()
static ulong Oculus.Platform.CAPI.ovr_User_GetLoggedInUser ()
ovr_User_GetLoggedInUserFriends()
static ulong Oculus.Platform.CAPI.ovr_User_GetLoggedInUserFriends ()
ovr_User_GetLoggedInUserFriendsAndRooms()
static ulong Oculus.Platform.CAPI.ovr_User_GetLoggedInUserFriendsAndRooms ()
ovr_User_GetLoggedInUserRecentlyMetUsersAndRooms()
static ulong Oculus.Platform.CAPI.ovr_User_GetLoggedInUserRecentlyMetUsersAndRooms (IntPtr userOptions)
ovr_User_GetOculusID()
static string Oculus.Platform.CAPI.ovr_User_GetOculusID (IntPtr obj) static
Referenced by Oculus.Platform.Models.User.User().
ovr_User_GetOrgScopedID()
static ulong Oculus.Platform.CAPI.ovr_User_GetOrgScopedID (UInt64 userID)
ovr_User_GetPresence()
static string Oculus.Platform.CAPI.ovr_User_GetPresence (IntPtr obj) static
Referenced by Oculus.Platform.Models.User.User().
ovr_User_GetPresenceDeeplinkMessage()
static string Oculus.Platform.CAPI.ovr_User_GetPresenceDeeplinkMessage (IntPtr obj) static
Referenced by Oculus.Platform.Models.User.User().
ovr_User_GetPresenceDestinationApiName()
static string Oculus.Platform.CAPI.ovr_User_GetPresenceDestinationApiName (IntPtr obj) static
Referenced by Oculus.Platform.Models.User.User().
ovr_User_GetPresenceLobbySessionId()
static string Oculus.Platform.CAPI.ovr_User_GetPresenceLobbySessionId (IntPtr obj) static
Referenced by Oculus.Platform.Models.User.User().
ovr_User_GetPresenceMatchSessionId()
static string Oculus.Platform.CAPI.ovr_User_GetPresenceMatchSessionId (IntPtr obj) static
Referenced by Oculus.Platform.Models.User.User().
ovr_User_GetPresenceStatus()
static UserPresenceStatus Oculus.Platform.CAPI.ovr_User_GetPresenceStatus (IntPtr obj)
Referenced by Oculus.Platform.Models.User.User().
ovr_User_GetSdkAccounts()
static ulong Oculus.Platform.CAPI.ovr_User_GetSdkAccounts ()
ovr_User_GetSmallImageUrl()
static string Oculus.Platform.CAPI.ovr_User_GetSmallImageUrl (IntPtr obj) static
Referenced by Oculus.Platform.Models.User.User().
ovr_User_GetUserCapabilities()
static ulong Oculus.Platform.CAPI.ovr_User_GetUserCapabilities ()
ovr_User_GetUserProof()
static ulong Oculus.Platform.CAPI.ovr_User_GetUserProof ()
ovr_User_LaunchBlockFlow()
static ulong Oculus.Platform.CAPI.ovr_User_LaunchBlockFlow (UInt64 userID)
ovr_User_LaunchFriendRequestFlow()
static ulong Oculus.Platform.CAPI.ovr_User_LaunchFriendRequestFlow (UInt64 userID)
ovr_User_LaunchReportFlow()
static ulong Oculus.Platform.CAPI.ovr_User_LaunchReportFlow (UInt64 userID)
ovr_User_LaunchReportFlow2()
static ulong Oculus.Platform.CAPI.ovr_User_LaunchReportFlow2 (UInt64 optionalUserID, IntPtr abuseReportOptions)
ovr_User_LaunchUnblockFlow()
static ulong Oculus.Platform.CAPI.ovr_User_LaunchUnblockFlow (UInt64 userID)
ovr_User_NewEntitledTestUser()
static ulong Oculus.Platform.CAPI.ovr_User_NewEntitledTestUser ()
ovr_User_NewTestUser()
static ulong Oculus.Platform.CAPI.ovr_User_NewTestUser ()
ovr_User_NewTestUserFriends()
static ulong Oculus.Platform.CAPI.ovr_User_NewTestUserFriends ()
ovr_User_StartRecordingForReportFlow()
static ulong Oculus.Platform.CAPI.ovr_User_StartRecordingForReportFlow ()
ovr_User_StopRecordingAndLaunchReportFlow()
static ulong Oculus.Platform.CAPI.ovr_User_StopRecordingAndLaunchReportFlow (UInt64 optionalUserID, string optionalRecordingUUID) static
ovr_User_StopRecordingAndLaunchReportFlow2()
static ulong Oculus.Platform.CAPI.ovr_User_StopRecordingAndLaunchReportFlow2 (UInt64 optionalUserID, string optionalRecordingUUID, IntPtr abuseReportOptions) static
ovr_User_TestUserCreateDeviceManifest()
static ulong Oculus.Platform.CAPI.ovr_User_TestUserCreateDeviceManifest (string deviceID, UInt64[] appIDs, int numAppIDs) static
ovr_UserAndRoom_GetRoom()
static IntPtr Oculus.Platform.CAPI.ovr_UserAndRoom_GetRoom (IntPtr obj)
Referenced by Oculus.Platform.Models.UserAndRoom.UserAndRoom().
ovr_UserAndRoom_GetUser()
static IntPtr Oculus.Platform.CAPI.ovr_UserAndRoom_GetUser (IntPtr obj)
Referenced by Oculus.Platform.Models.UserAndRoom.UserAndRoom().
ovr_UserAndRoomArray_GetElement()
static IntPtr Oculus.Platform.CAPI.ovr_UserAndRoomArray_GetElement (IntPtr obj, UIntPtr index)
Referenced by Oculus.Platform.Models.UserAndRoomList.UserAndRoomList().
ovr_UserAndRoomArray_GetNextUrl()
static string Oculus.Platform.CAPI.ovr_UserAndRoomArray_GetNextUrl (IntPtr obj) static
Referenced by Oculus.Platform.Models.UserAndRoomList.UserAndRoomList().
ovr_UserAndRoomArray_GetSize()
static UIntPtr Oculus.Platform.CAPI.ovr_UserAndRoomArray_GetSize (IntPtr obj)
Referenced by Oculus.Platform.Models.UserAndRoomList.UserAndRoomList().
ovr_UserAndRoomArray_HasNextPage()
static bool Oculus.Platform.CAPI.ovr_UserAndRoomArray_HasNextPage (IntPtr obj)
ovr_UserArray_GetElement()
static IntPtr Oculus.Platform.CAPI.ovr_UserArray_GetElement (IntPtr obj, UIntPtr index)
Referenced by Oculus.Platform.Models.UserList.UserList().
ovr_UserArray_GetNextUrl()
static string Oculus.Platform.CAPI.ovr_UserArray_GetNextUrl (IntPtr obj) static
Referenced by Oculus.Platform.Models.UserList.UserList().
ovr_UserArray_GetSize()
static UIntPtr Oculus.Platform.CAPI.ovr_UserArray_GetSize (IntPtr obj)
Referenced by Oculus.Platform.Models.UserList.UserList().
ovr_UserArray_HasNextPage()
static bool Oculus.Platform.CAPI.ovr_UserArray_HasNextPage (IntPtr obj)
ovr_UserCapability_GetDescription()
static string Oculus.Platform.CAPI.ovr_UserCapability_GetDescription (IntPtr obj) static
Referenced by Oculus.Platform.Models.UserCapability.UserCapability().
ovr_UserCapability_GetIsEnabled()
static bool Oculus.Platform.CAPI.ovr_UserCapability_GetIsEnabled (IntPtr obj)
Referenced by Oculus.Platform.Models.UserCapability.UserCapability().
ovr_UserCapability_GetName()
static string Oculus.Platform.CAPI.ovr_UserCapability_GetName (IntPtr obj) static
Referenced by Oculus.Platform.Models.UserCapability.UserCapability().
ovr_UserCapability_GetReasonCode()
static string Oculus.Platform.CAPI.ovr_UserCapability_GetReasonCode (IntPtr obj) static
Referenced by Oculus.Platform.Models.UserCapability.UserCapability().
ovr_UserCapabilityArray_GetElement()
static IntPtr Oculus.Platform.CAPI.ovr_UserCapabilityArray_GetElement (IntPtr obj, UIntPtr index)
Referenced by Oculus.Platform.Models.UserCapabilityList.UserCapabilityList().
ovr_UserCapabilityArray_GetNextUrl()
static string Oculus.Platform.CAPI.ovr_UserCapabilityArray_GetNextUrl (IntPtr obj) static
Referenced by Oculus.Platform.Models.UserCapabilityList.UserCapabilityList().
ovr_UserCapabilityArray_GetSize()
static UIntPtr Oculus.Platform.CAPI.ovr_UserCapabilityArray_GetSize (IntPtr obj)
Referenced by Oculus.Platform.Models.UserCapabilityList.UserCapabilityList().
ovr_UserCapabilityArray_HasNextPage()
static bool Oculus.Platform.CAPI.ovr_UserCapabilityArray_HasNextPage (IntPtr obj)
ovr_UserDataStore_PrivateDeleteEntryByKey()
static ulong Oculus.Platform.CAPI.ovr_UserDataStore_PrivateDeleteEntryByKey (UInt64 userID, string key) static
ovr_UserDataStore_PrivateGetEntries()
static ulong Oculus.Platform.CAPI.ovr_UserDataStore_PrivateGetEntries (UInt64 userID)
ovr_UserDataStore_PrivateGetEntryByKey()
static ulong Oculus.Platform.CAPI.ovr_UserDataStore_PrivateGetEntryByKey (UInt64 userID, string key) static
ovr_UserDataStore_PrivateWriteEntry()
static ulong Oculus.Platform.CAPI.ovr_UserDataStore_PrivateWriteEntry (UInt64 userID, string key, string value) static
ovr_UserDataStore_PublicDeleteEntryByKey()
static ulong Oculus.Platform.CAPI.ovr_UserDataStore_PublicDeleteEntryByKey (UInt64 userID, string key) static
ovr_UserDataStore_PublicGetEntries()
static ulong Oculus.Platform.CAPI.ovr_UserDataStore_PublicGetEntries (UInt64 userID)
ovr_UserDataStore_PublicGetEntryByKey()
static ulong Oculus.Platform.CAPI.ovr_UserDataStore_PublicGetEntryByKey (UInt64 userID, string key) static
ovr_UserDataStore_PublicWriteEntry()
static ulong Oculus.Platform.CAPI.ovr_UserDataStore_PublicWriteEntry (UInt64 userID, string key, string value) static
ovr_UserDataStoreUpdateResponse_GetSuccess()
static bool Oculus.Platform.CAPI.ovr_UserDataStoreUpdateResponse_GetSuccess (IntPtr obj)
Referenced by Oculus.Platform.Models.UserDataStoreUpdateResponse.UserDataStoreUpdateResponse().
ovr_UserOptions_AddServiceProvider()
static void Oculus.Platform.CAPI.ovr_UserOptions_AddServiceProvider (IntPtr handle, ServiceProvider value)
Referenced by Oculus.Platform.UserOptions.AddServiceProvider().
ovr_UserOptions_ClearServiceProviders()
static void Oculus.Platform.CAPI.ovr_UserOptions_ClearServiceProviders (IntPtr handle)
Referenced by Oculus.Platform.UserOptions.ClearServiceProviders().
ovr_UserOptions_Create()
static IntPtr Oculus.Platform.CAPI.ovr_UserOptions_Create ()
Referenced by Oculus.Platform.UserOptions.UserOptions().
ovr_UserOptions_Destroy()
static void Oculus.Platform.CAPI.ovr_UserOptions_Destroy (IntPtr handle)
ovr_UserOptions_SetMaxUsers()
static void Oculus.Platform.CAPI.ovr_UserOptions_SetMaxUsers (IntPtr handle, uint value)
Referenced by Oculus.Platform.UserOptions.SetMaxUsers().
ovr_UserOptions_SetTimeWindow()
static void Oculus.Platform.CAPI.ovr_UserOptions_SetTimeWindow (IntPtr handle, TimeWindow value)
Referenced by Oculus.Platform.UserOptions.SetTimeWindow().
ovr_UserProof_GetNonce()
static string Oculus.Platform.CAPI.ovr_UserProof_GetNonce (IntPtr obj) static
Referenced by Oculus.Platform.Models.UserProof.UserProof().
ovr_UserReportID_GetDidCancel()
static bool Oculus.Platform.CAPI.ovr_UserReportID_GetDidCancel (IntPtr obj)
Referenced by Oculus.Platform.Models.UserReportID.UserReportID().
ovr_UserReportID_GetID()
static UInt64 Oculus.Platform.CAPI.ovr_UserReportID_GetID (IntPtr obj)
Referenced by Oculus.Platform.Models.UserReportID.UserReportID().
ovr_Voip_Accept()
static void Oculus.Platform.CAPI.ovr_Voip_Accept (UInt64 userID)
ovr_Voip_CreateDecoder()
static IntPtr Oculus.Platform.CAPI.ovr_Voip_CreateDecoder ()
ovr_Voip_CreateEncoder()
static IntPtr Oculus.Platform.CAPI.ovr_Voip_CreateEncoder ()
ovr_Voip_DestroyDecoder()
static void Oculus.Platform.CAPI.ovr_Voip_DestroyDecoder (IntPtr decoder)
ovr_Voip_DestroyEncoder()
static void Oculus.Platform.CAPI.ovr_Voip_DestroyEncoder (IntPtr encoder)
ovr_Voip_GetIsConnectionUsingDtx()
static VoipDtxState Oculus.Platform.CAPI.ovr_Voip_GetIsConnectionUsingDtx (UInt64 peerID)
ovr_Voip_GetLocalBitrate()
static VoipBitrate Oculus.Platform.CAPI.ovr_Voip_GetLocalBitrate (UInt64 peerID)
ovr_Voip_GetMicrophoneAvailability()
static ulong Oculus.Platform.CAPI.ovr_Voip_GetMicrophoneAvailability ()
ovr_Voip_GetOutputBufferMaxSize()
static UIntPtr Oculus.Platform.CAPI.ovr_Voip_GetOutputBufferMaxSize ()
ovr_Voip_GetPCM()
static UIntPtr Oculus.Platform.CAPI.ovr_Voip_GetPCM (UInt64 senderID, Int16[] outputBuffer, UIntPtr outputBufferNumElements)
ovr_Voip_GetPCMFloat()
static UIntPtr Oculus.Platform.CAPI.ovr_Voip_GetPCMFloat (UInt64 senderID, float[] outputBuffer, UIntPtr outputBufferNumElements)
Referenced by Oculus.Platform.VoipPCMSourceNative.GetPCM().
ovr_Voip_GetPCMSize()
static UIntPtr Oculus.Platform.CAPI.ovr_Voip_GetPCMSize (UInt64 senderID)
Referenced by Oculus.Platform.VoipPCMSourceNative.PeekSizeElements().
ovr_Voip_GetPCMWithTimestamp()
static UIntPtr Oculus.Platform.CAPI.ovr_Voip_GetPCMWithTimestamp (UInt64 senderID, Int16[] outputBuffer, UIntPtr outputBufferNumElements, UInt32[] timestamp)
ovr_Voip_GetPCMWithTimestampFloat()
static UIntPtr Oculus.Platform.CAPI.ovr_Voip_GetPCMWithTimestampFloat (UInt64 senderID, float[] outputBuffer, UIntPtr outputBufferNumElements, UInt32[] timestamp)
ovr_Voip_GetRemoteBitrate()
static VoipBitrate Oculus.Platform.CAPI.ovr_Voip_GetRemoteBitrate (UInt64 peerID)
ovr_Voip_GetSyncTimestamp()
static UInt32 Oculus.Platform.CAPI.ovr_Voip_GetSyncTimestamp (UInt64 userID)
ovr_Voip_GetSyncTimestampDifference()
static long Oculus.Platform.CAPI.ovr_Voip_GetSyncTimestampDifference (UInt32 lhs, UInt32 rhs)
ovr_Voip_GetSystemVoipMicrophoneMuted()
static VoipMuteState Oculus.Platform.CAPI.ovr_Voip_GetSystemVoipMicrophoneMuted ()
ovr_Voip_GetSystemVoipStatus()
static SystemVoipStatus Oculus.Platform.CAPI.ovr_Voip_GetSystemVoipStatus ()
ovr_Voip_SetMicrophoneFilterCallback()
static void Oculus.Platform.CAPI.ovr_Voip_SetMicrophoneFilterCallback (FilterCallback cb)
ovr_Voip_SetMicrophoneFilterCallbackWithFixedSizeBuffer()
static void Oculus.Platform.CAPI.ovr_Voip_SetMicrophoneFilterCallbackWithFixedSizeBuffer (FilterCallback cb, UIntPtr bufferSizeElements)
ovr_Voip_SetMicrophoneMuted()
static void Oculus.Platform.CAPI.ovr_Voip_SetMicrophoneMuted (VoipMuteState state)
ovr_Voip_SetNewConnectionOptions()
static void Oculus.Platform.CAPI.ovr_Voip_SetNewConnectionOptions (IntPtr voipOptions)
ovr_Voip_SetOutputSampleRate()
static void Oculus.Platform.CAPI.ovr_Voip_SetOutputSampleRate (VoipSampleRate rate)
Referenced by Oculus.Platform.VoipAudioSourceHiLevel.Awake().
ovr_Voip_SetSystemVoipMicrophoneMuted()
static void Oculus.Platform.CAPI.ovr_Voip_SetSystemVoipMicrophoneMuted (VoipMuteState muted)
ovr_Voip_SetSystemVoipPassthrough()
static void Oculus.Platform.CAPI.ovr_Voip_SetSystemVoipPassthrough (bool passthrough)
ovr_Voip_SetSystemVoipSuppressed()
static ulong Oculus.Platform.CAPI.ovr_Voip_SetSystemVoipSuppressed (bool suppressed)
ovr_Voip_Start()
static void Oculus.Platform.CAPI.ovr_Voip_Start (UInt64 userID)
ovr_Voip_Stop()
static void Oculus.Platform.CAPI.ovr_Voip_Stop (UInt64 userID)
ovr_VoipDecoder_Decode() [1/2]
static void Oculus.Platform.CAPI.ovr_VoipDecoder_Decode (IntPtr obj, byte[] compressedData, UIntPtr compressedSize)
ovr_VoipDecoder_Decode() [2/2]
static void Oculus.Platform.CAPI.ovr_VoipDecoder_Decode (IntPtr obj, byte[] compressedData, ulong compressedSize)
ovr_VoipDecoder_GetDecodedPCM()
static UIntPtr Oculus.Platform.CAPI.ovr_VoipDecoder_GetDecodedPCM (IntPtr obj, float[] outputBuffer, UIntPtr outputBufferSize)
ovr_VoipEncoder_AddPCM()
static void Oculus.Platform.CAPI.ovr_VoipEncoder_AddPCM (IntPtr obj, float[] inputData, uint inputSize)
ovr_VoipEncoder_GetCompressedData()
static UIntPtr Oculus.Platform.CAPI.ovr_VoipEncoder_GetCompressedData (IntPtr obj, byte[] outputBuffer, UIntPtr intputSize)
ovr_VoipEncoder_GetCompressedDataSize()
static UIntPtr Oculus.Platform.CAPI.ovr_VoipEncoder_GetCompressedDataSize (IntPtr obj)
ovr_VoipOptions_Create()
static IntPtr Oculus.Platform.CAPI.ovr_VoipOptions_Create ()
Referenced by Oculus.Platform.VoipOptions.VoipOptions().
ovr_VoipOptions_Destroy()
static void Oculus.Platform.CAPI.ovr_VoipOptions_Destroy (IntPtr handle)
ovr_VoipOptions_SetBitrateForNewConnections()
static void Oculus.Platform.CAPI.ovr_VoipOptions_SetBitrateForNewConnections (IntPtr handle, VoipBitrate value)
Referenced by Oculus.Platform.VoipOptions.SetBitrateForNewConnections().
ovr_VoipOptions_SetCreateNewConnectionUseDtx()
static void Oculus.Platform.CAPI.ovr_VoipOptions_SetCreateNewConnectionUseDtx (IntPtr handle, VoipDtxState value)
Referenced by Oculus.Platform.VoipOptions.SetCreateNewConnectionUseDtx().
StringFromNative()
static string Oculus.Platform.CAPI.StringFromNative (IntPtr pointer) static
Referenced by Oculus.Platform.CAPI.ovr_AbuseReportRecording_GetRecordingUuid(), Oculus.Platform.CAPI.ovr_AchievementDefinition_GetName(), Oculus.Platform.CAPI.ovr_AchievementDefinitionArray_GetNextUrl(), Oculus.Platform.CAPI.ovr_AchievementProgress_GetBitfield(), Oculus.Platform.CAPI.ovr_AchievementProgress_GetName(), Oculus.Platform.CAPI.ovr_AchievementProgressArray_GetNextUrl(), Oculus.Platform.CAPI.ovr_AchievementUpdate_GetName(), Oculus.Platform.CAPI.ovr_ApplicationInvite_GetLobbySessionId(), Oculus.Platform.CAPI.ovr_ApplicationInvite_GetMatchSessionId(), Oculus.Platform.CAPI.ovr_ApplicationInviteArray_GetNextUrl(), Oculus.Platform.CAPI.ovr_ApplicationVersion_GetCurrentName(), Oculus.Platform.CAPI.ovr_ApplicationVersion_GetLatestName(), Oculus.Platform.CAPI.ovr_AssetDetails_GetAssetType(), Oculus.Platform.CAPI.ovr_AssetDetails_GetDownloadStatus(), Oculus.Platform.CAPI.ovr_AssetDetails_GetFilepath(), Oculus.Platform.CAPI.ovr_AssetDetails_GetIapStatus(), Oculus.Platform.CAPI.ovr_AssetDetails_GetMetadata(), Oculus.Platform.CAPI.ovr_AssetFileDeleteResult_GetFilepath(), Oculus.Platform.CAPI.ovr_AssetFileDownloadCancelResult_GetFilepath(), Oculus.Platform.CAPI.ovr_AssetFileDownloadResult_GetFilepath(), Oculus.Platform.CAPI.ovr_CalApplicationFinalized_GetLaunchDetails(), Oculus.Platform.CAPI.ovr_CalApplicationSuggestion_GetSocialContext(), Oculus.Platform.CAPI.ovr_Challenge_GetDescription(), Oculus.Platform.CAPI.ovr_Challenge_GetTitle(), Oculus.Platform.CAPI.ovr_ChallengeArray_GetNextUrl(), Oculus.Platform.CAPI.ovr_ChallengeArray_GetPreviousUrl(), Oculus.Platform.CAPI.ovr_ChallengeEntry_GetDisplayScore(), Oculus.Platform.CAPI.ovr_ChallengeEntryArray_GetNextUrl(), Oculus.Platform.CAPI.ovr_ChallengeEntryArray_GetPreviousUrl(), Oculus.Platform.CAPI.ovr_CloudStorage2UserDirectoryPathResponse_GetPath(), Oculus.Platform.CAPI.ovr_CloudStorageData_GetBucket(), Oculus.Platform.CAPI.ovr_CloudStorageData_GetKey(), Oculus.Platform.CAPI.ovr_CloudStorageMetadata_GetBucket(), Oculus.Platform.CAPI.ovr_CloudStorageMetadata_GetExtraData(), Oculus.Platform.CAPI.ovr_CloudStorageMetadata_GetKey(), Oculus.Platform.CAPI.ovr_CloudStorageMetadata_GetVersionHandle(), Oculus.Platform.CAPI.ovr_CloudStorageMetadataArray_GetNextUrl(), Oculus.Platform.CAPI.ovr_CloudStorageUpdateResponse_GetBucket(), Oculus.Platform.CAPI.ovr_CloudStorageUpdateResponse_GetKey(), Oculus.Platform.CAPI.ovr_CloudStorageUpdateResponse_GetVersionHandle(), Oculus.Platform.CAPI.ovr_DataStore_GetKey(), Oculus.Platform.CAPI.ovr_DataStore_GetValue(), Oculus.Platform.CAPI.ovr_Destination_GetApiName(), Oculus.Platform.CAPI.ovr_Destination_GetDeeplinkMessage(), Oculus.Platform.CAPI.ovr_Destination_GetDisplayName(), Oculus.Platform.CAPI.ovr_DestinationArray_GetNextUrl(), Oculus.Platform.CAPI.ovr_Error_GetDisplayableMessage(), Oculus.Platform.CAPI.ovr_Error_GetMessage(), Oculus.Platform.CAPI.ovr_GetLoggedInUserLocale(), Oculus.Platform.CAPI.ovr_GroupPresenceJoinIntent_GetDeeplinkMessage(), Oculus.Platform.CAPI.ovr_GroupPresenceJoinIntent_GetDestinationApiName(), Oculus.Platform.CAPI.ovr_GroupPresenceJoinIntent_GetLobbySessionId(), Oculus.Platform.CAPI.ovr_GroupPresenceJoinIntent_GetMatchSessionId(), Oculus.Platform.CAPI.ovr_GroupPresenceLeaveIntent_GetDestinationApiName(), Oculus.Platform.CAPI.ovr_GroupPresenceLeaveIntent_GetLobbySessionId(), Oculus.Platform.CAPI.ovr_GroupPresenceLeaveIntent_GetMatchSessionId(), Oculus.Platform.CAPI.ovr_InstalledApplication_GetApplicationId(), Oculus.Platform.CAPI.ovr_InstalledApplication_GetPackageName(), Oculus.Platform.CAPI.ovr_InstalledApplication_GetStatus(), Oculus.Platform.CAPI.ovr_InstalledApplication_GetVersionName(), Oculus.Platform.CAPI.ovr_LanguagePackInfo_GetEnglishName(), Oculus.Platform.CAPI.ovr_LanguagePackInfo_GetNativeName(), Oculus.Platform.CAPI.ovr_LanguagePackInfo_GetTag(), Oculus.Platform.CAPI.ovr_LaunchDetails_GetDeeplinkMessage(), Oculus.Platform.CAPI.ovr_LaunchDetails_GetDestinationApiName(), Oculus.Platform.CAPI.ovr_LaunchDetails_GetLaunchSource(), Oculus.Platform.CAPI.ovr_LaunchDetails_GetTrackingID(), Oculus.Platform.CAPI.ovr_Leaderboard_GetApiName(), Oculus.Platform.CAPI.ovr_LeaderboardArray_GetNextUrl(), Oculus.Platform.CAPI.ovr_LeaderboardEntry_GetDisplayScore(), Oculus.Platform.CAPI.ovr_LeaderboardEntryArray_GetNextUrl(), Oculus.Platform.CAPI.ovr_LeaderboardEntryArray_GetPreviousUrl(), Oculus.Platform.CAPI.ovr_LinkedAccount_GetAccessToken(), Oculus.Platform.CAPI.ovr_LinkedAccount_GetUserId(), Oculus.Platform.CAPI.ovr_LivestreamingVideoStats_GetTotalViews(), Oculus.Platform.CAPI.ovr_MatchmakingAdminSnapshotCandidate_GetTraceId(), Oculus.Platform.CAPI.ovr_MatchmakingCandidate_GetEntryHash(), Oculus.Platform.CAPI.ovr_MatchmakingCandidateArray_GetNextUrl(), Oculus.Platform.CAPI.ovr_MatchmakingEnqueueResult_GetPool(), Oculus.Platform.CAPI.ovr_MatchmakingEnqueueResult_GetRequestHash(), Oculus.Platform.CAPI.ovr_MatchmakingNotification_GetTraceId(), Oculus.Platform.CAPI.ovr_Message_GetString(), Oculus.Platform.CAPI.ovr_Message_GetStringForJavascript(), Oculus.Platform.CAPI.ovr_NetSyncConnection_GetZoneId(), Oculus.Platform.CAPI.ovr_NetSyncSession_GetVoipGroup(), Oculus.Platform.CAPI.ovr_PartyUpdateNotification_GetUpdateTimestamp(), Oculus.Platform.CAPI.ovr_PartyUpdateNotification_GetUserAlias(), Oculus.Platform.CAPI.ovr_PartyUpdateNotification_GetUserName(), Oculus.Platform.CAPI.ovr_Pid_GetId(), Oculus.Platform.CAPI.ovr_Price_GetCurrency(), Oculus.Platform.CAPI.ovr_Price_GetFormatted(), Oculus.Platform.CAPI.ovr_Product_GetDescription(), Oculus.Platform.CAPI.ovr_Product_GetFormattedPrice(), Oculus.Platform.CAPI.ovr_Product_GetName(), Oculus.Platform.CAPI.ovr_Product_GetSKU(), Oculus.Platform.CAPI.ovr_ProductArray_GetNextUrl(), Oculus.Platform.CAPI.ovr_Purchase_GetPurchaseStrID(), Oculus.Platform.CAPI.ovr_Purchase_GetSKU(), Oculus.Platform.CAPI.ovr_PurchaseArray_GetNextUrl(), Oculus.Platform.CAPI.ovr_Room_GetDescription(), Oculus.Platform.CAPI.ovr_Room_GetName(), Oculus.Platform.CAPI.ovr_RoomArray_GetNextUrl(), Oculus.Platform.CAPI.ovr_RoomInviteNotificationArray_GetNextUrl(), Oculus.Platform.CAPI.ovr_Team_GetName(), Oculus.Platform.CAPI.ovr_TestUser_GetAccessToken(), Oculus.Platform.CAPI.ovr_TestUser_GetFriendAccessToken(), Oculus.Platform.CAPI.ovr_TestUser_GetUserAlias(), Oculus.Platform.CAPI.ovr_TestUserAppAccess_GetAccessToken(), Oculus.Platform.CAPI.ovr_User_GetDisplayName(), Oculus.Platform.CAPI.ovr_User_GetImageUrl(), Oculus.Platform.CAPI.ovr_User_GetInviteToken(), Oculus.Platform.CAPI.ovr_User_GetOculusID(), Oculus.Platform.CAPI.ovr_User_GetPresence(), Oculus.Platform.CAPI.ovr_User_GetPresenceDeeplinkMessage(), Oculus.Platform.CAPI.ovr_User_GetPresenceDestinationApiName(), Oculus.Platform.CAPI.ovr_User_GetPresenceLobbySessionId(), Oculus.Platform.CAPI.ovr_User_GetPresenceMatchSessionId(), Oculus.Platform.CAPI.ovr_User_GetSmallImageUrl(), Oculus.Platform.CAPI.ovr_UserAndRoomArray_GetNextUrl(), Oculus.Platform.CAPI.ovr_UserArray_GetNextUrl(), Oculus.Platform.CAPI.ovr_UserCapability_GetDescription(), Oculus.Platform.CAPI.ovr_UserCapability_GetName(), Oculus.Platform.CAPI.ovr_UserCapability_GetReasonCode(), Oculus.Platform.CAPI.ovr_UserCapabilityArray_GetNextUrl(), and Oculus.Platform.CAPI.ovr_UserProof_GetNonce().
StringToNative()
static IntPtr Oculus.Platform.CAPI.StringToNative (string s) static
Referenced by Oculus.Platform.CAPI.LogNewEvent(), Oculus.Platform.CAPI.ovr_Achievements_AddCount(), Oculus.Platform.CAPI.ovr_Achievements_AddFields(), Oculus.Platform.CAPI.ovr_Achievements_Unlock(), Oculus.Platform.CAPI.ovr_AdvancedAbuseReportOptions_SetObjectType(), Oculus.Platform.CAPI.ovr_ApplicationLifecycle_LogDeeplinkResult(), Oculus.Platform.CAPI.ovr_ApplicationLifecycle_RegisterSessionKey(), Oculus.Platform.CAPI.ovr_ApplicationOptions_SetDeeplinkMessage(), Oculus.Platform.CAPI.ovr_AssetFile_DeleteByName(), Oculus.Platform.CAPI.ovr_AssetFile_DownloadByName(), Oculus.Platform.CAPI.ovr_AssetFile_DownloadCancelByName(), Oculus.Platform.CAPI.ovr_AssetFile_StatusByName(), Oculus.Platform.CAPI.ovr_Avatar_UpdateMetaData(), Oculus.Platform.CAPI.ovr_ChallengeOptions_SetDescription(), Oculus.Platform.CAPI.ovr_ChallengeOptions_SetLeaderboardName(), Oculus.Platform.CAPI.ovr_ChallengeOptions_SetTitle(), Oculus.Platform.CAPI.ovr_Challenges_Create(), Oculus.Platform.CAPI.ovr_CloudStorage_Delete(), Oculus.Platform.CAPI.ovr_CloudStorage_Load(), Oculus.Platform.CAPI.ovr_CloudStorage_LoadBucketMetadata(), Oculus.Platform.CAPI.ovr_CloudStorage_LoadConflictMetadata(), Oculus.Platform.CAPI.ovr_CloudStorage_LoadHandle(), Oculus.Platform.CAPI.ovr_CloudStorage_LoadMetadata(), Oculus.Platform.CAPI.ovr_CloudStorage_ResolveKeepLocal(), Oculus.Platform.CAPI.ovr_CloudStorage_ResolveKeepRemote(), Oculus.Platform.CAPI.ovr_CloudStorage_Save(), Oculus.Platform.CAPI.ovr_Colocation_RequestMap(), Oculus.Platform.CAPI.ovr_Colocation_ShareMap(), Oculus.Platform.CAPI.ovr_DataStore_Contains(), Oculus.Platform.CAPI.ovr_DataStore_GetValue(), Oculus.Platform.CAPI.ovr_GraphAPI_Get(), Oculus.Platform.CAPI.ovr_GraphAPI_Post(), Oculus.Platform.CAPI.ovr_GroupPresence_LaunchRejoinDialog(), Oculus.Platform.CAPI.ovr_GroupPresence_SetDestination(), Oculus.Platform.CAPI.ovr_GroupPresence_SetLobbySession(), Oculus.Platform.CAPI.ovr_GroupPresence_SetMatchSession(), Oculus.Platform.CAPI.ovr_GroupPresenceOptions_SetDestinationApiName(), Oculus.Platform.CAPI.ovr_GroupPresenceOptions_SetLobbySessionId(), Oculus.Platform.CAPI.ovr_GroupPresenceOptions_SetMatchSessionId(), Oculus.Platform.CAPI.ovr_HTTP_Get(), Oculus.Platform.CAPI.ovr_HTTP_GetToFile(), Oculus.Platform.CAPI.ovr_HTTP_MultiPartPost(), Oculus.Platform.CAPI.ovr_HTTP_Post(), Oculus.Platform.CAPI.ovr_HTTP_StartTransfer(), Oculus.Platform.CAPI.ovr_IAP_ConsumePurchase(), Oculus.Platform.CAPI.ovr_IAP_LaunchCheckoutFlow(), Oculus.Platform.CAPI.ovr_LanguagePack_SetCurrent(), Oculus.Platform.CAPI.ovr_Leaderboard_Get(), Oculus.Platform.CAPI.ovr_Leaderboard_GetEntries(), Oculus.Platform.CAPI.ovr_Leaderboard_GetEntriesAfterRank(), Oculus.Platform.CAPI.ovr_Leaderboard_GetEntriesByIds(), Oculus.Platform.CAPI.ovr_Leaderboard_WriteEntry(), Oculus.Platform.CAPI.ovr_Leaderboard_WriteEntryWithSupplementaryMetric(), Oculus.Platform.CAPI.ovr_Livestreaming_IsAllowedForApplication(), Oculus.Platform.CAPI.ovr_Matchmaking_Browse(), Oculus.Platform.CAPI.ovr_Matchmaking_Browse2(), Oculus.Platform.CAPI.ovr_Matchmaking_Cancel(), Oculus.Platform.CAPI.ovr_Matchmaking_CreateAndEnqueueRoom(), Oculus.Platform.CAPI.ovr_Matchmaking_CreateAndEnqueueRoom2(), Oculus.Platform.CAPI.ovr_Matchmaking_CreateRoom(), Oculus.Platform.CAPI.ovr_Matchmaking_CreateRoom2(), Oculus.Platform.CAPI.ovr_Matchmaking_Enqueue(), Oculus.Platform.CAPI.ovr_Matchmaking_Enqueue2(), Oculus.Platform.CAPI.ovr_Matchmaking_GetStats(), Oculus.Platform.CAPI.ovr_MatchmakingOptions_SetCreateRoomDataStoreString(), Oculus.Platform.CAPI.ovr_MatchmakingOptions_SetEnqueueDataSettingsDouble(), Oculus.Platform.CAPI.ovr_MatchmakingOptions_SetEnqueueDataSettingsInt(), Oculus.Platform.CAPI.ovr_MatchmakingOptions_SetEnqueueDataSettingsString(), Oculus.Platform.CAPI.ovr_MatchmakingOptions_SetEnqueueQueryKey(), Oculus.Platform.CAPI.ovr_Media_ShareToFacebook(), Oculus.Platform.CAPI.ovr_NetSync_SetVoipAttenuationModel(), Oculus.Platform.CAPI.ovr_NetSync_SetVoipChannelCfg(), Oculus.Platform.CAPI.ovr_NetSync_SetVoipGroup(), Oculus.Platform.CAPI.ovr_NetSyncOptions_SetVoipGroup(), Oculus.Platform.CAPI.ovr_NetSyncOptions_SetZoneId(), Oculus.Platform.CAPI.ovr_RichPresence_SetDestination(), Oculus.Platform.CAPI.ovr_RichPresence_SetLobbySession(), Oculus.Platform.CAPI.ovr_RichPresence_SetMatchSession(), Oculus.Platform.CAPI.ovr_RichPresenceOptions_SetApiName(), Oculus.Platform.CAPI.ovr_RichPresenceOptions_SetArgsString(), Oculus.Platform.CAPI.ovr_RichPresenceOptions_SetDeeplinkMessageOverride(), Oculus.Platform.CAPI.ovr_RichPresenceOptions_SetInstanceId(), Oculus.Platform.CAPI.ovr_RichPresenceOptions_SetJoinableId(), Oculus.Platform.CAPI.ovr_RichPresenceOptions_SetLobbySessionId(), Oculus.Platform.CAPI.ovr_RichPresenceOptions_SetMatchSessionId(), Oculus.Platform.CAPI.ovr_Room_InviteUser(), Oculus.Platform.CAPI.ovr_Room_SetDescription(), Oculus.Platform.CAPI.ovr_RoomOptions_SetDataStoreString(), Oculus.Platform.CAPI.ovr_User_CancelRecordingForReportFlow(), Oculus.Platform.CAPI.ovr_User_StopRecordingAndLaunchReportFlow(), Oculus.Platform.CAPI.ovr_User_StopRecordingAndLaunchReportFlow2(), Oculus.Platform.CAPI.ovr_User_TestUserCreateDeviceManifest(), Oculus.Platform.CAPI.ovr_UserDataStore_PrivateDeleteEntryByKey(), Oculus.Platform.CAPI.ovr_UserDataStore_PrivateGetEntryByKey(), Oculus.Platform.CAPI.ovr_UserDataStore_PrivateWriteEntry(), Oculus.Platform.CAPI.ovr_UserDataStore_PublicDeleteEntryByKey(), Oculus.Platform.CAPI.ovr_UserDataStore_PublicGetEntryByKey(), and Oculus.Platform.CAPI.ovr_UserDataStore_PublicWriteEntry().
Member Data Documentation
DLL_NAME
const string Oculus.Platform.CAPI.DLL_NAME = "ovrplatformloader" static
VoipFilterBufferSize
const int Oculus.Platform.CAPI.VoipFilterBufferSize = 480 static
The documentation for this class was generated from the following file:
C:/Users/Lykos/Desktop/Projects/Capstone/VRGames/Assets/ThirdParty/Oculus/Platform/Scripts/CAPI.cs