VRGames: Oculus.Interaction.VirtualSelector Class Reference
Oculus.Interaction.VirtualSelector Class Reference
This Virtual Selector can provide interactions with a sample selector that can be toggled from within the Unity insepctor using the HandleSelected Flag.
Public Member Functions
void Select ()
void Unselect ()
Protected Member Functions
virtual void OnValidate ()
void UpdateSelection ()
Events
Action WhenSelected = delegate { }
Action WhenUnselected = delegate { }
Events inherited from Oculus.Interaction.ISelector
Action WhenSelected
Action WhenUnselected
Detailed Description
This Virtual Selector can provide interactions with a sample selector that can be toggled from within the Unity insepctor using the HandleSelected Flag.
Member Function Documentation
OnValidate()
virtual void Oculus.Interaction.VirtualSelector.OnValidate () protected virtual
Select()
void Oculus.Interaction.VirtualSelector.Select ()
Unselect()
void Oculus.Interaction.VirtualSelector.Unselect ()
UpdateSelection()
void Oculus.Interaction.VirtualSelector.UpdateSelection () protected
Referenced by Oculus.Interaction.VirtualSelector.OnValidate(), Oculus.Interaction.VirtualSelector.Select(), and Oculus.Interaction.VirtualSelector.Unselect().
Event Documentation
WhenSelected
Action Oculus.Interaction.VirtualSelector.WhenSelected = delegate { }
Referenced by Oculus.Interaction.VirtualSelector.UpdateSelection().
WhenUnselected
Action Oculus.Interaction.VirtualSelector.WhenUnselected = delegate { }
Referenced by Oculus.Interaction.VirtualSelector.UpdateSelection().
The documentation for this class was generated from the following file:
C:/Users/Lykos/Desktop/Projects/Capstone/VRGames/Assets/ThirdParty/Oculus/Interaction/Runtime/Scripts/Selection/Virtual/VirtualSelector.cs