VRGames: Facebook.WitAi.VoiceService Class Reference
Facebook.WitAi.VoiceService Class Reference abstract
Public Member Functions
void Activate ()
Start listening for sound or speech from the user and start sending data to Wit.ai once sound or speech has been detected.
void Activate (WitRequestOptions requestOptions)
Activate the microphone and send data for NLU processing. Includes optional additional request parameters like dynamic entities and maximum results.
void ActivateImmediately ()
Activate the microphone and send data for NLU processing immediately without waiting for sound/speech from the user to begin.
void ActivateImmediately (WitRequestOptions requestOptions)
Activate the microphone and send data for NLU processing immediately without waiting for sound/speech from the user to begin. Includes optional additional request parameters like dynamic entities and maximum results.
void Deactivate ()
Stop listening and submit any remaining buffered microphone data for processing.
void DeactivateAndAbortRequest ()
Stop listening and abort any requests that may be active without waiting for a response.
void Activate (string text)
Send text data for NLU processing. Results will return the same way a voice based activation would.
void Activate (string text, WitRequestOptions requestOptions)
Send text data for NLU processing with custom request options.
Public Attributes
VoiceEvents events = new VoiceEvents()
Properties
bool Active [get]
Returns true if this voice service is currently active and listening with the mic.
bool IsRequestActive [get]
Returns true if the service is actively communicating with Wit.ai during an Activation. The mic may or may not still be active while this is true.
ITranscriptionProvider TranscriptionProvider [get, set]
Gets/Sets a custom transcription provider. This can be used to replace any built in asr with an on device model or other provided source.
bool MicActive [get]
Returns true if this voice service is currently reading data from the microphone.
VoiceEvents VoiceEvents [get, set]
bool ShouldSendMicData [get]
Returns true if the audio input should be read in an activation.
Properties inherited from Facebook.WitAi.IVoiceService
Member Function Documentation
Activate() [1/4]
void Facebook.WitAi.VoiceService.Activate () abstract
Start listening for sound or speech from the user and start sending data to Wit.ai once sound or speech has been detected.
Implements Facebook.WitAi.IVoiceService.
Referenced by Facebook.WitAi.Windows.WitUnderstandingViewer.LayoutContent(), and Facebook.WitAi.Inspectors.WitInspector.OnInspectorGUI().
Activate() [2/4]
void Facebook.WitAi.VoiceService.Activate (string text) abstract
Send text data for NLU processing. Results will return the same way a voice based activation would.
Parameters
text
Implements Facebook.WitAi.IVoiceService.
Activate() [3/4]
void Facebook.WitAi.VoiceService.Activate (string text, WitRequestOptions requestOptions) abstract
Send text data for NLU processing with custom request options.
Parameters
text
requestOptions
Implements Facebook.WitAi.IVoiceService.
Activate() [4/4]
void Facebook.WitAi.VoiceService.Activate (WitRequestOptions requestOptions) abstract
Activate the microphone and send data for NLU processing. Includes optional additional request parameters like dynamic entities and maximum results.
Parameters
requestOptions
Implements Facebook.WitAi.IVoiceService.
ActivateImmediately() [1/2]
void Facebook.WitAi.VoiceService.ActivateImmediately () abstract
Activate the microphone and send data for NLU processing immediately without waiting for sound/speech from the user to begin.
Implements Facebook.WitAi.IVoiceService.
ActivateImmediately() [2/2]
void Facebook.WitAi.VoiceService.ActivateImmediately (WitRequestOptions requestOptions) abstract
Activate the microphone and send data for NLU processing immediately without waiting for sound/speech from the user to begin. Includes optional additional request parameters like dynamic entities and maximum results.
Implements Facebook.WitAi.IVoiceService.
Deactivate()
void Facebook.WitAi.VoiceService.Deactivate () abstract
Stop listening and submit any remaining buffered microphone data for processing.
Implements Facebook.WitAi.IVoiceService.
Referenced by Facebook.WitAi.Windows.WitUnderstandingViewer.LayoutContent(), and Facebook.WitAi.Inspectors.WitInspector.OnInspectorGUI().
DeactivateAndAbortRequest()
void Facebook.WitAi.VoiceService.DeactivateAndAbortRequest () abstract
Stop listening and abort any requests that may be active without waiting for a response.
Implements Facebook.WitAi.IVoiceService.
Referenced by Facebook.WitAi.Windows.WitUnderstandingViewer.LayoutContent().
Member Data Documentation
events
VoiceEvents Facebook.WitAi.VoiceService.events = new VoiceEvents()
Referenced by Facebook.WitAi.Wit.Activate(), Facebook.WitAi.Wit.ActivateImmediately(), Facebook.WitAi.Wit.Deactivate(), Facebook.WitAi.Wit.DeactivateAndAbortRequest(), and Oculus.Voice.Upgrade.WitUpgrader.OnInspectorGUI().
Property Documentation
Active
bool Facebook.WitAi.VoiceService.Active get abstract
Returns true if this voice service is currently active and listening with the mic.
Implements Facebook.WitAi.IVoiceService.
Referenced by Facebook.WitAi.Windows.WitUnderstandingViewer.LayoutContent(), and Facebook.WitAi.Inspectors.WitInspector.OnInspectorGUI().
IsRequestActive
bool Facebook.WitAi.VoiceService.IsRequestActive get abstract
Returns true if the service is actively communicating with Wit.ai during an Activation. The mic may or may not still be active while this is true.
Implements Facebook.WitAi.IVoiceService.
Referenced by Facebook.WitAi.Windows.WitUnderstandingViewer.LayoutContent().
MicActive
bool Facebook.WitAi.VoiceService.MicActive get abstract
Returns true if this voice service is currently reading data from the microphone.
Implements Facebook.WitAi.IVoiceService.
Referenced by Facebook.WitAi.Windows.WitUnderstandingViewer.LayoutContent(), and Facebook.WitAi.Inspectors.WitInspector.OnInspectorGUI().
ShouldSendMicData
bool Facebook.WitAi.VoiceService.ShouldSendMicData get abstract protected
Returns true if the audio input should be read in an activation.
TranscriptionProvider
ITranscriptionProvider Facebook.WitAi.VoiceService.TranscriptionProvider get set abstract
Gets/Sets a custom transcription provider. This can be used to replace any built in asr with an on device model or other provided source.
Implements Facebook.WitAi.IVoiceService.
VoiceEvents
VoiceEvents Facebook.WitAi.VoiceService.VoiceEvents get set
Implements Facebook.WitAi.IVoiceService.
The documentation for this class was generated from the following file:
C:/Users/Lykos/Desktop/Projects/Capstone/VRGames/Assets/ThirdParty/Oculus/Voice/Lib/Wit.ai/Scripts/Runtime/VoiceService.cs