VRGames: Oculus.Interaction.Input.Controller Class Reference
Oculus.Interaction.Input.Controller Class Reference
Public Member Functions
bool IsButtonUsageAnyActive (ControllerButtonUsage buttonUsage)
bool IsButtonUsageAllActive (ControllerButtonUsage buttonUsage)
bool TryGetPose (out Pose pose)
Retrieves the current controller pose, in world space.
bool TryGetPointerPose (out Pose pose)
Retrieves the current controller pointer pose, in world space.
override void MarkInputDataRequiresUpdate ()
Public Member Functions inherited from Oculus.Interaction.Input.DataModifier< ControllerDataAsset >
void ResetSources (IDataSource< TData > modifyDataFromSource, IDataSource updateAfter, UpdateModeFlags updateMode)
void InjectAllDataModifier (UpdateModeFlags updateMode, IDataSource updateAfter, IDataSource< TData > modifyDataFromSource, bool applyModifier)
void InjectModifyDataFromSource (IDataSource< TData > modifyDataFromSource)
void InjectApplyModifier (bool applyModifier)
Protected Member Functions
override void Apply (ControllerDataAsset data)
Protected Member Functions inherited from Oculus.Interaction.Input.DataModifier< ControllerDataAsset >
override void UpdateData ()
void Apply (TData data)
override void Start ()
Properties
Handedness Handedness [get]
bool IsConnected [get]
bool IsPoseValid [get]
bool IsPointerPoseValid [get]
Properties inherited from Oculus.Interaction.Input.DataModifier< ControllerDataAsset >
override TData DataAsset [get]
virtual IDataSource< TData > ModifyDataFromSource [get]
override int CurrentDataVersion [get]
Properties inherited from Oculus.Interaction.Input.IController
Events
Action ControllerUpdated = delegate { }
Events inherited from Oculus.Interaction.Input.IController
Action ControllerUpdated
Additional Inherited Members
Protected Attributes inherited from Oculus.Interaction.Input.DataModifier< ControllerDataAsset >
MonoBehaviour _iModifyDataFromSourceMono
Member Function Documentation
Apply()
override void Oculus.Interaction.Input.Controller.Apply (ControllerDataAsset data) protected
IsButtonUsageAllActive()
bool Oculus.Interaction.Input.Controller.IsButtonUsageAllActive (ControllerButtonUsage buttonUsage)
Implements Oculus.Interaction.Input.IController.
Referenced by Oculus.Interaction.Input.ControllerRef.IsButtonUsageAllActive(), and Oculus.Interaction.ControllerSelector.Update().
IsButtonUsageAnyActive()
bool Oculus.Interaction.Input.Controller.IsButtonUsageAnyActive (ControllerButtonUsage buttonUsage)
Implements Oculus.Interaction.Input.IController.
Referenced by Oculus.Interaction.Input.ControllerRef.IsButtonUsageAnyActive(), and Oculus.Interaction.ControllerSelector.Update().
MarkInputDataRequiresUpdate()
override void Oculus.Interaction.Input.Controller.MarkInputDataRequiresUpdate ()
TryGetPointerPose()
bool Oculus.Interaction.Input.Controller.TryGetPointerPose (out Pose pose)
Retrieves the current controller pointer pose, in world space.
Parameters
pose Set to current pose if IsPoseValid; Pose.identity otherwise
Returns
Value of IsPoseValid
Implements Oculus.Interaction.Input.IController.
Referenced by Oculus.Interaction.Input.ControllerRef.TryGetPointerPose().
TryGetPose()
bool Oculus.Interaction.Input.Controller.TryGetPose (out Pose pose)
Retrieves the current controller pose, in world space.
Parameters
pose Set to current pose if IsPoseValid; Pose.identity otherwise
Returns
Value of IsPoseValid
Implements Oculus.Interaction.Input.IController.
Referenced by Oculus.Interaction.Throw.ControllerPoseInputDevice.GetRootPose(), and Oculus.Interaction.Input.ControllerRef.TryGetPose().
Property Documentation
Handedness
Handedness Oculus.Interaction.Input.Controller.Handedness get
Implements Oculus.Interaction.Input.IController.
IsConnected
bool Oculus.Interaction.Input.Controller.IsConnected get
Implements Oculus.Interaction.Input.IController.
IsPointerPoseValid
bool Oculus.Interaction.Input.Controller.IsPointerPoseValid get
Referenced by Oculus.Interaction.Input.Controller.TryGetPointerPose().
IsPoseValid
bool Oculus.Interaction.Input.Controller.IsPoseValid get
Implements Oculus.Interaction.Input.IController.
Referenced by Oculus.Interaction.Input.Controller.TryGetPose().
Event Documentation
ControllerUpdated
Action Oculus.Interaction.Input.Controller.ControllerUpdated = delegate { }
Referenced by Oculus.Interaction.Input.Controller.MarkInputDataRequiresUpdate().
The documentation for this class was generated from the following file:
C:/Users/Lykos/Desktop/Projects/Capstone/VRGames/Assets/ThirdParty/Oculus/Interaction/Runtime/Scripts/Input/Controllers/Controller.cs