VRGames: UnityEditor.SettingsManagement.ValueWrapper< T > Class Template Reference
UnityEditor.SettingsManagement.ValueWrapper< T > Class Template Reference sealed
Static Public Member Functions
static string Serialize (T value)
static T Deserialize (string json)
static T DeepCopy (T value)
Member Function Documentation
DeepCopy()
static T UnityEditor.SettingsManagement.ValueWrapper< T >.DeepCopy (T value) static
Referenced by UnityEditor.SettingsManagement.UserSetting< T >.Delete().
Deserialize()
static T UnityEditor.SettingsManagement.ValueWrapper< T >.Deserialize (string json) static
Referenced by UnityEditor.SettingsManagement.ValueWrapper< T >.DeepCopy(), and UnityEditor.SettingsManagement.SettingsDictionary.Get< T >().
Serialize()
static string UnityEditor.SettingsManagement.ValueWrapper< T >.Serialize (T value) static
Referenced by UnityEditor.SettingsManagement.ValueWrapper< T >.DeepCopy().
The documentation for this class was generated from the following file:
C:/Users/Lykos/Desktop/Projects/Capstone/VRGames/Library/PackageCache/com.unity.settings-manager@1.0.3/Editor/ValueWrapper.cs