VRGames: Facebook.WitAi.Lib.WitResponseClass Class Reference
Facebook.WitAi.Lib.WitResponseClass Class Reference
Public Member Functions
override void Add (string aKey, WitResponseNode aItem)
override WitResponseNode Remove (string aKey)
override WitResponseNode Remove (int aIndex)
override WitResponseNode Remove (WitResponseNode aNode)
IEnumerator GetEnumerator ()
override string ToString ()
override string ToString (string aPrefix)
override void Serialize (System.IO.BinaryWriter aWriter)
Public Member Functions inherited from Facebook.WitAi.Lib.WitResponseNode
virtual void Add (WitResponseNode aItem)
override string ToString ()
override bool Equals (object obj)
override int GetHashCode ()
void SaveToStream (System.IO.Stream aData)
void SaveToCompressedStream (System.IO.Stream aData)
void SaveToCompressedFile (string aFileName)
string SaveToCompressedBase64 ()
void SaveToFile (string aFileName)
string SaveToBase64 ()
Properties
string[] ChildNodeNames [get]
override WitResponseNode this[string aKey] [get, set]
override WitResponseNode this[int aIndex] [get, set]
override int Count [get]
override IEnumerable< WitResponseNode > Childs [get]
Properties inherited from Facebook.WitAi.Lib.WitResponseNode
virtual WitResponseNode this[int aIndex] [get, set]
virtual WitResponseNode this[string aKey] [get, set]
virtual string Value [get, set]
virtual int Count [get]
virtual IEnumerable< WitResponseNode > Childs [get]
IEnumerable< WitResponseNode > DeepChilds [get]
virtual int AsInt [get, set]
virtual float AsFloat [get, set]
virtual double AsDouble [get, set]
virtual bool AsBool [get, set]
virtual WitResponseArray AsArray [get]
virtual string[] AsStringArray [get]
virtual WitResponseClass AsObject [get]
Additional Inherited Members
Static Public Member Functions inherited from Facebook.WitAi.Lib.WitResponseNode
static implicit operator WitResponseNode (string s)
static implicit operator string (WitResponseNode d)
static bool operator== (WitResponseNode a, object b)
static bool operator!= (WitResponseNode a, object b)
static WitResponseNode Parse (string aJSON)
static WitResponseNode Deserialize (System.IO.BinaryReader aReader)
static WitResponseNode LoadFromCompressedFile (string aFileName)
static WitResponseNode LoadFromCompressedStream (System.IO.Stream aData)
static WitResponseNode LoadFromCompressedBase64 (string aBase64)
static WitResponseNode LoadFromStream (System.IO.Stream aData)
static WitResponseNode LoadFromFile (string aFileName)
static WitResponseNode LoadFromBase64 (string aBase64)
Member Function Documentation
Add()
override void Facebook.WitAi.Lib.WitResponseClass.Add (string aKey, WitResponseNode aItem) virtual
Reimplemented from Facebook.WitAi.Lib.WitResponseNode.
Referenced by Facebook.WitAi.Data.Entities.WitDynamicEntities.Add(), Facebook.WitAi.Data.Entities.WitDynamicEntities.Add(), and Facebook.WitAi.Lib.WitResponseNode.Deserialize().
GetEnumerator()
IEnumerator Facebook.WitAi.Lib.WitResponseClass.GetEnumerator ()
Remove() [1/3]
override WitResponseNode Facebook.WitAi.Lib.WitResponseClass.Remove (int aIndex) virtual
Reimplemented from Facebook.WitAi.Lib.WitResponseNode.
Remove() [2/3]
override WitResponseNode Facebook.WitAi.Lib.WitResponseClass.Remove (string aKey) virtual
Reimplemented from Facebook.WitAi.Lib.WitResponseNode.
Remove() [3/3]
override WitResponseNode Facebook.WitAi.Lib.WitResponseClass.Remove (WitResponseNode aNode) virtual
Reimplemented from Facebook.WitAi.Lib.WitResponseNode.
Serialize()
override void Facebook.WitAi.Lib.WitResponseClass.Serialize (System::IO::BinaryWriter aWriter) virtual
Reimplemented from Facebook.WitAi.Lib.WitResponseNode.
ToString() [1/2]
override string Facebook.WitAi.Lib.WitResponseClass.ToString ()
Referenced by Facebook.WitAi.Data.Entities.WitDynamicEntities.ToJSON(), Facebook.WitAi.Data.Entities.WitDynamicEntity.ToJSON(), and Facebook.WitAi.Data.Entities.WitSimpleDynamicEntity.ToJSON().
ToString() [2/2]
override string Facebook.WitAi.Lib.WitResponseClass.ToString (string aPrefix) virtual
Reimplemented from Facebook.WitAi.Lib.WitResponseNode.
Property Documentation
ChildNodeNames
string [] Facebook.WitAi.Lib.WitResponseClass.ChildNodeNames get
Childs
override IEnumerable<WitResponseNode> Facebook.WitAi.Lib.WitResponseClass.Childs get
Count
override int Facebook.WitAi.Lib.WitResponseClass.Count get
this[int aIndex]
override WitResponseNode Facebook.WitAi.Lib.WitResponseClass.this[int aIndex] get set
this[string aKey]
override WitResponseNode Facebook.WitAi.Lib.WitResponseClass.this[string aKey] get set
The documentation for this class was generated from the following file:
C:/Users/Lykos/Desktop/Projects/Capstone/VRGames/Assets/ThirdParty/Oculus/Voice/Lib/Wit.ai/Scripts/Runtime/Lib/WitResponse.cs