VRGames: UnityEngine.SpatialTracking.TrackedPoseDriver Class Reference
UnityEngine.SpatialTracking.TrackedPoseDriver Class Reference
The TrackedPoseDriver component applies the current Pose value of a tracked device to the transform of the GameObject. TrackedPoseDriver can track multiple types of devices including XR HMDs, controllers, and remotes.
Public Types
enum DeviceType { GenericXRDevice = 0 , GenericXRController = 1 , GenericXRRemote = 2 }
The device being tracked by the tracked pose driver.
enum TrackedPose {
LeftEye = 0 , RightEye = 1 , Center = 2 , Head = 3 ,
LeftPose = 4 , RightPose = 5 , ColorCamera = 6 , DepthCameraDeprecated = 7 ,
FisheyeCameraDeprected = 8 , DeviceDeprecated = 9 , RemotePose = 10
}
The list of endpoints that users can track with the TrackedPoseDriver
enum TrackingType { RotationAndPosition , RotationOnly , PositionOnly }
This enum is used to indicate which parts of the pose will be applied to the parent transform.
enum UpdateType { UpdateAndBeforeRender , Update , BeforeRender }
The update type being used by the tracked pose driver.
Public Member Functions
bool SetPoseSource (DeviceType deviceType, TrackedPose pose)
This method is used to set the device / pose pair for the SpatialTracking.TrackedPoseDriver. setting an invalid combination of these values will return false.
Protected Member Functions
virtual void Awake ()
virtual void OnDestroy ()
virtual void OnEnable ()
virtual void OnDisable ()
virtual void FixedUpdate ()
virtual void Update ()
virtual void OnBeforeRender ()
virtual void SetLocalTransform (Vector3 newPosition, Quaternion newRotation, PoseDataFlags poseFlags)
Sets the transform that is being driven by the TrackedPoseDriver. will only correct set the rotation or position depending on the PoseDataFlags
Pose TransformPoseByOriginIfNeeded (Pose pose)
This is only used when running in legacy mode, and will fake the behavior of the old implicit camera tracking. This will transform by the origin pose if necessary.
virtual void PerformUpdate ()
PerformUpdate queries the data from the selected pose source, and then calls SetLocalTransform to apply the pose.
Protected Attributes
Pose m_OriginPose
The origin pose is the offset applied to any tracking data. This is only used when in legacy compatibility mode.
Properties
DeviceType deviceType [get, set]
This is used to indicate which pose the TrackedPoseDriver is currently tracking.
TrackedPose poseSource [get, set]
The pose being tracked by the tracked pose driver.
TrackingType trackingType [get, set]
The tracking type being used by the tracked pose driver.
UpdateType updateType [get, set]
The update type being used by the tracked pose driver.
bool UseRelativeTransform [get, set]
This is used to indicate whether the TrackedPoseDriver will use the object's original transform as its basis.
Pose originPose [get, set]
originPose is an offset applied to any tracking data read from this object. Setting this value should be reserved for dealing with edge-cases, such as achieving parity between room-scale (floor centered) and stationary (head centered) tracking - without having to alter the transform hierarchy. For user locomotion and gameplay purposes you are usually better off just moving the parent transform of this object.
Detailed Description
The TrackedPoseDriver component applies the current Pose value of a tracked device to the transform of the GameObject. TrackedPoseDriver can track multiple types of devices including XR HMDs, controllers, and remotes.
Member Enumeration Documentation
DeviceType
enum UnityEngine.SpatialTracking.TrackedPoseDriver.DeviceType
The device being tracked by the tracked pose driver.
Enumerator
GenericXRDevice
An XR Controller, use this value for controllers.
GenericXRController
An Generic XR Devices, use this value for HMD and AR Mobile device tracking.
GenericXRRemote
An XR Remote, use this value for mobile remotes.
TrackedPose
enum UnityEngine.SpatialTracking.TrackedPoseDriver.TrackedPose
The list of endpoints that users can track with the TrackedPoseDriver
Enumerator
LeftEye
The left eye of a HMD style device.
RightEye
The right eye of a HMD style device.
Center
The center eye of a HMD style device, this is usually the default for most HMDs.
Head
The head eye of a HMD style device.
LeftPose
The left hand controller pose.
RightPose
The right hand controller pose.
ColorCamera
The color camera of a mobile device.
DepthCameraDeprecated
No Longer Used.
FisheyeCameraDeprected
No Longer Used.
DeviceDeprecated
No Longer Used.
RemotePose
The pose of a mobile remote.
TrackingType
enum UnityEngine.SpatialTracking.TrackedPoseDriver.TrackingType
This enum is used to indicate which parts of the pose will be applied to the parent transform.
Enumerator
RotationAndPosition
With this setting, both the pose's rotation and position will be applied to the parent transform.
RotationOnly
With this setting, only the pose's rotation will be applied to the parent transform.
PositionOnly
With this setting, only the pose's position will be applied to the parent transform.
UpdateType
enum UnityEngine.SpatialTracking.TrackedPoseDriver.UpdateType
The update type being used by the tracked pose driver.
Enumerator
UpdateAndBeforeRender
Sample input at both update, and directly before rendering. For smooth head pose tracking, we recommend using this value as it will provide the lowest input latency for the device. This is the default value for the UpdateType option.
Update
Only sample input during the update phase of the frame.
BeforeRender
Only sample input directly before rendering.
Member Function Documentation
Awake()
virtual void UnityEngine.SpatialTracking.TrackedPoseDriver.Awake () protected virtual
FixedUpdate()
virtual void UnityEngine.SpatialTracking.TrackedPoseDriver.FixedUpdate () protected virtual
OnBeforeRender()
virtual void UnityEngine.SpatialTracking.TrackedPoseDriver.OnBeforeRender () protected virtual
Referenced by UnityEngine.SpatialTracking.TrackedPoseDriver.OnDisable(), and UnityEngine.SpatialTracking.TrackedPoseDriver.OnEnable().
OnDestroy()
virtual void UnityEngine.SpatialTracking.TrackedPoseDriver.OnDestroy () protected virtual
OnDisable()
virtual void UnityEngine.SpatialTracking.TrackedPoseDriver.OnDisable () protected virtual
OnEnable()
virtual void UnityEngine.SpatialTracking.TrackedPoseDriver.OnEnable () protected virtual
PerformUpdate()
virtual void UnityEngine.SpatialTracking.TrackedPoseDriver.PerformUpdate () protected virtual
PerformUpdate queries the data from the selected pose source, and then calls SetLocalTransform to apply the pose.
Referenced by UnityEngine.SpatialTracking.TrackedPoseDriver.FixedUpdate(), UnityEngine.SpatialTracking.TrackedPoseDriver.OnBeforeRender(), and UnityEngine.SpatialTracking.TrackedPoseDriver.Update().
SetLocalTransform()
virtual void UnityEngine.SpatialTracking.TrackedPoseDriver.SetLocalTransform (Vector3 newPosition, Quaternion newRotation, PoseDataFlags poseFlags) protected virtual
Sets the transform that is being driven by the TrackedPoseDriver. will only correct set the rotation or position depending on the PoseDataFlags
Parameters
newPosition The position to apply.
newRotation The rotation to apply.
poseFlags The flags indiciating which of the position/rotation values are provided by the calling code.
Referenced by UnityEngine.SpatialTracking.TrackedPoseDriver.PerformUpdate().
SetPoseSource()
bool UnityEngine.SpatialTracking.TrackedPoseDriver.SetPoseSource (DeviceType deviceType, TrackedPose pose)
This method is used to set the device / pose pair for the SpatialTracking.TrackedPoseDriver. setting an invalid combination of these values will return false.
Parameters
deviceType The device type that we wish to track
pose The pose source that we wish to track
Returns
true if the values provided are sensible, otherwise false
TransformPoseByOriginIfNeeded()
Pose UnityEngine.SpatialTracking.TrackedPoseDriver.TransformPoseByOriginIfNeeded (Pose pose) protected
This is only used when running in legacy mode, and will fake the behavior of the old implicit camera tracking. This will transform by the origin pose if necessary.
Parameters
pose Pose to transform by the origin if in relative transform mode.
Returns
The pose, with the applied transform if in Relative Transform mode.
Referenced by UnityEngine.SpatialTracking.TrackedPoseDriver.PerformUpdate().
Update()
virtual void UnityEngine.SpatialTracking.TrackedPoseDriver.Update () protected virtual
Member Data Documentation
m_OriginPose
Pose UnityEngine.SpatialTracking.TrackedPoseDriver.m_OriginPose protected
The origin pose is the offset applied to any tracking data. This is only used when in legacy compatibility mode.
Referenced by UnityEngine.SpatialTracking.TrackedPoseDriver.TransformPoseByOriginIfNeeded().
Property Documentation
deviceType
DeviceType UnityEngine.SpatialTracking.TrackedPoseDriver.deviceType get set
This is used to indicate which pose the TrackedPoseDriver is currently tracking.
Referenced by UnityEngine.SpatialTracking.TrackedPoseDriver.SetPoseSource().
originPose
Pose UnityEngine.SpatialTracking.TrackedPoseDriver.originPose get set
originPose is an offset applied to any tracking data read from this object. Setting this value should be reserved for dealing with edge-cases, such as achieving parity between room-scale (floor centered) and stationary (head centered) tracking - without having to alter the transform hierarchy. For user locomotion and gameplay purposes you are usually better off just moving the parent transform of this object.
poseSource
TrackedPose UnityEngine.SpatialTracking.TrackedPoseDriver.poseSource get set
The pose being tracked by the tracked pose driver.
Referenced by UnityEngine.SpatialTracking.TrackedPoseDriver.SetPoseSource().
trackingType
TrackingType UnityEngine.SpatialTracking.TrackedPoseDriver.trackingType get set
The tracking type being used by the tracked pose driver.
updateType
UpdateType UnityEngine.SpatialTracking.TrackedPoseDriver.updateType get set
The update type being used by the tracked pose driver.
UseRelativeTransform
bool UnityEngine.SpatialTracking.TrackedPoseDriver.UseRelativeTransform get set
This is used to indicate whether the TrackedPoseDriver will use the object's original transform as its basis.
The documentation for this class was generated from the following file:
C:/Users/Lykos/Desktop/Projects/Capstone/VRGames/Library/PackageCache/com.unity.xr.legacyinputhelpers@2.1.9/Runtime/TrackedPoseDriver/TrackedPoseDriver.cs