VRGames: Facebook.WitAi.Events.VoiceEvents Class Reference
Facebook.WitAi.Events.VoiceEvents Class Reference
Public Attributes
WitResponseEvent OnResponse = new WitResponseEvent()
WitErrorEvent OnError = new WitErrorEvent()
UnityEvent OnAborted = new UnityEvent()
UnityEvent OnRequestCompleted = new UnityEvent()
WitMicLevelChangedEvent OnMicLevelChanged = new WitMicLevelChangedEvent()
WitRequestCreatedEvent OnRequestCreated = new WitRequestCreatedEvent()
Called when a request is created. This happens at the beginning of an activation before the microphone is activated (if in use).
UnityEvent OnStartListening = new UnityEvent()
UnityEvent OnStoppedListening = new UnityEvent()
UnityEvent OnStoppedListeningDueToInactivity = new UnityEvent()
UnityEvent OnStoppedListeningDueToTimeout = new UnityEvent()
UnityEvent OnStoppedListeningDueToDeactivation = new UnityEvent()
UnityEvent OnMicDataSent = new UnityEvent()
UnityEvent OnMinimumWakeThresholdHit = new UnityEvent()
WitTranscriptionEvent OnPartialTranscription = new WitTranscriptionEvent()
WitTranscriptionEvent OnFullTranscription = new WitTranscriptionEvent()
Member Data Documentation
OnAborted
UnityEvent Facebook.WitAi.Events.VoiceEvents.OnAborted = new UnityEvent()
OnError
WitErrorEvent Facebook.WitAi.Events.VoiceEvents.OnError = new WitErrorEvent()
Referenced by Oculus.Voice.Bindings.Android.VoiceSDKListenerBinding.onError().
OnFullTranscription
WitTranscriptionEvent Facebook.WitAi.Events.VoiceEvents.OnFullTranscription = new WitTranscriptionEvent()
Referenced by Oculus.Voice.Bindings.Android.VoiceSDKListenerBinding.onFullTranscription().
OnMicDataSent
UnityEvent Facebook.WitAi.Events.VoiceEvents.OnMicDataSent = new UnityEvent()
Referenced by Oculus.Voice.Bindings.Android.VoiceSDKListenerBinding.onMicDataSent().
OnMicLevelChanged
WitMicLevelChangedEvent Facebook.WitAi.Events.VoiceEvents.OnMicLevelChanged = new WitMicLevelChangedEvent()
Referenced by Oculus.Voice.Bindings.Android.VoiceSDKListenerBinding.onMicLevelChanged().
OnMinimumWakeThresholdHit
UnityEvent Facebook.WitAi.Events.VoiceEvents.OnMinimumWakeThresholdHit = new UnityEvent()
Referenced by Oculus.Voice.Bindings.Android.VoiceSDKListenerBinding.onMinimumWakeThresholdHit().
OnPartialTranscription
WitTranscriptionEvent Facebook.WitAi.Events.VoiceEvents.OnPartialTranscription = new WitTranscriptionEvent()
Referenced by Oculus.Voice.Bindings.Android.VoiceSDKListenerBinding.onPartialTranscription().
OnRequestCompleted
UnityEvent Facebook.WitAi.Events.VoiceEvents.OnRequestCompleted = new UnityEvent()
OnRequestCreated
WitRequestCreatedEvent Facebook.WitAi.Events.VoiceEvents.OnRequestCreated = new WitRequestCreatedEvent()
Called when a request is created. This happens at the beginning of an activation before the microphone is activated (if in use).
Referenced by Oculus.Voice.Bindings.Android.VoiceSDKListenerBinding.onRequestCreated().
OnResponse
WitResponseEvent Facebook.WitAi.Events.VoiceEvents.OnResponse = new WitResponseEvent()
Referenced by Oculus.Voice.Bindings.Android.VoiceSDKListenerBinding.onResponse().
OnStartListening
UnityEvent Facebook.WitAi.Events.VoiceEvents.OnStartListening = new UnityEvent()
Referenced by Oculus.Voice.Bindings.Android.VoiceSDKListenerBinding.onStartListening().
OnStoppedListening
UnityEvent Facebook.WitAi.Events.VoiceEvents.OnStoppedListening = new UnityEvent()
Referenced by Oculus.Voice.Bindings.Android.VoiceSDKListenerBinding.onStoppedListening().
OnStoppedListeningDueToDeactivation
UnityEvent Facebook.WitAi.Events.VoiceEvents.OnStoppedListeningDueToDeactivation = new UnityEvent()
Referenced by Oculus.Voice.Bindings.Android.VoiceSDKListenerBinding.onStoppedListeningDueToDeactivation().
OnStoppedListeningDueToInactivity
UnityEvent Facebook.WitAi.Events.VoiceEvents.OnStoppedListeningDueToInactivity = new UnityEvent()
Referenced by Oculus.Voice.Bindings.Android.VoiceSDKListenerBinding.onStoppedListeningDueToInactivity().
OnStoppedListeningDueToTimeout
UnityEvent Facebook.WitAi.Events.VoiceEvents.OnStoppedListeningDueToTimeout = new UnityEvent()
Referenced by Oculus.Voice.Bindings.Android.VoiceSDKListenerBinding.onStoppedListeningDueToTimeout().
The documentation for this class was generated from the following file:
C:/Users/Lykos/Desktop/Projects/Capstone/VRGames/Assets/ThirdParty/Oculus/Voice/Lib/Wit.ai/Scripts/Runtime/Events/VoiceEvents.cs