VRGames: Facebook.WitAi.WitAuthUtility Class Reference
Facebook.WitAi.WitAuthUtility Class Reference
Classes
class DefaultTokenValidatorProvider
interface ITokenValidationProvider
Static Public Member Functions
static bool IsServerTokenValid ()
static bool IsServerTokenValid (string token)
static string GetAppServerToken (WitConfiguration configuration, string defaultValue="")
static string GetAppServerToken (string appId, string defaultValue="")
static string GetAppId (string serverToken, string defaultValue="")
static void SetAppServerToken (string appId, string token)
Static Public Attributes
static ITokenValidationProvider tokenValidator = new DefaultTokenValidatorProvider()
Properties
static string ServerToken [get]
Member Function Documentation
GetAppId()
static string Facebook.WitAi.WitAuthUtility.GetAppId (string serverToken, string defaultValue = "") static
GetAppServerToken() [1/2]
static string Facebook.WitAi.WitAuthUtility.GetAppServerToken (string appId, string defaultValue = "") static
GetAppServerToken() [2/2]
static string Facebook.WitAi.WitAuthUtility.GetAppServerToken (WitConfiguration configuration, string defaultValue = "") static
Referenced by Facebook.WitAi.WitAuthUtility.GetAppServerToken(), Facebook.WitAi.Windows.WitConfigurationEditor.Initialize(), and Facebook.WitAi.WitRequest.WitRequest().
IsServerTokenValid() [1/2]
static bool Facebook.WitAi.WitAuthUtility.IsServerTokenValid () static
Referenced by Facebook.WitAi.WitAuthUtility.DefaultTokenValidatorProvider.IsTokenValid(), and Facebook.WitAi.Windows.WitWelcomeWizard.ValidateAndClose().
IsServerTokenValid() [2/2]
static bool Facebook.WitAi.WitAuthUtility.IsServerTokenValid (string token) static
SetAppServerToken()
static void Facebook.WitAi.WitAuthUtility.SetAppServerToken (string appId, string token) static
Member Data Documentation
tokenValidator
ITokenValidationProvider Facebook.WitAi.WitAuthUtility.tokenValidator = new DefaultTokenValidatorProvider() static
Referenced by Facebook.WitAi.WitAuthUtility.IsServerTokenValid(), and Facebook.WitAi.WitAuthUtility.IsServerTokenValid().
Property Documentation
ServerToken
string Facebook.WitAi.WitAuthUtility.ServerToken static get
Referenced by Oculus.Voice.Data.VoiceSDKDataCreation.CreateWitConfiguration(), Facebook.WitAi.WitAuthUtility.IsServerTokenValid(), Oculus.Voice.Windows.WelcomeWizard.LayoutFields(), Facebook.WitAi.Windows.WitWelcomeWizard.OnEnable(), and Facebook.WitAi.Windows.WitWindow.OnEnable().
The documentation for this class was generated from the following file:
C:/Users/Lykos/Desktop/Projects/Capstone/VRGames/Assets/ThirdParty/Oculus/Voice/Lib/Wit.ai/Scripts/Runtime/WitAuthUtility.cs