VRGames: UnityEditor.XR.Interaction.Toolkit.BaseInteractionEditor Class Reference
UnityEditor.XR.Interaction.Toolkit.BaseInteractionEditor Class Reference abstract
Base class for custom editors in the XR Interaction Toolkit.
Public Member Functions
override void OnInspectorGUI ()
Protected Member Functions
void DrawInspector ()
This method is automatically called by OnInspectorGUI to draw the custom inspector. Override this method to customize the inspector as a whole.
virtual void InitializeKnownSerializedPropertyNames ()
This method is automatically called by OnInspectorGUI to initialize knownSerializedPropertyNames if necessary. This is used together with DrawDerivedProperties to draw all unknown serialized fields from derived classes.
virtual List< string > GetDerivedSerializedPropertyNames ()
Returns a list containing the SerializeField names of all SerializedProperty fields defined in the Editor (including derived types).
virtual void DrawDerivedProperties ()
This method is automatically called by DrawInspector to draw the property fields of derived classes that are not explicitly defined in the Editor.
virtual void DrawScript ()
Draw the standard read-only Script property.
Properties
string[] knownSerializedPropertyNames [get, set]
The SerializeField names of all SerializedProperty fields defined in the Editor (including derived types).
Detailed Description
Base class for custom editors in the XR Interaction Toolkit.
Member Function Documentation
DrawDerivedProperties()
virtual void UnityEditor.XR.Interaction.Toolkit.BaseInteractionEditor.DrawDerivedProperties () protected virtual
This method is automatically called by DrawInspector to draw the property fields of derived classes that are not explicitly defined in the Editor.
This method is used to allow users to add a SerializeField to a derived behavior and have it automatically appear in the Inspector while still having the custom Editor apply to that derived class.
When a derived Editor class adds a SerializedProperty, it will no longer automatically be drawn by this method. This is to allow users to customize where the property is drawn in the Inspector window. The derived Editor class does not need to explicitly add the SerializedProperty if the user is fine with the default location of where it will be drawn.
See also
InitializeKnownSerializedPropertyNames
Reimplemented in UnityEditor.XR.Interaction.Toolkit.XRRayInteractorEditor.
Referenced by UnityEditor.XR.Interaction.Toolkit.XRBaseControllerEditor.DrawInspector(), UnityEditor.XR.Interaction.Toolkit.XRControllerRecordingEditor.DrawInspector(), UnityEditor.XR.Interaction.Toolkit.XRBaseInteractableEditor.DrawInspector(), UnityEditor.XR.Interaction.Toolkit.XRInteractorLineVisualEditor.DrawInspector(), UnityEditor.XR.Interaction.Toolkit.XRBaseInteractorEditor.DrawInspector(), UnityEditor.XR.Interaction.Toolkit.DeviceBasedSnapTurnProviderEditor.DrawInspector(), and UnityEditor.XR.Interaction.Toolkit.XRRigEditor.DrawInspector().
DrawInspector()
void UnityEditor.XR.Interaction.Toolkit.BaseInteractionEditor.DrawInspector () abstract protected
This method is automatically called by OnInspectorGUI to draw the custom inspector. Override this method to customize the inspector as a whole.
Referenced by UnityEditor.XR.Interaction.Toolkit.BaseInteractionEditor.OnInspectorGUI().
DrawScript()
virtual void UnityEditor.XR.Interaction.Toolkit.BaseInteractionEditor.DrawScript () protected virtual
Draw the standard read-only Script property.
Referenced by UnityEditor.XR.Interaction.Toolkit.XRBaseControllerEditor.DrawBeforeProperties(), UnityEditor.XR.Interaction.Toolkit.XRControllerRecordingEditor.DrawBeforeProperties(), UnityEditor.XR.Interaction.Toolkit.XRBaseInteractableEditor.DrawBeforeProperties(), UnityEditor.XR.Interaction.Toolkit.XRInteractorLineVisualEditor.DrawBeforeProperties(), UnityEditor.XR.Interaction.Toolkit.XRBaseInteractorEditor.DrawBeforeProperties(), UnityEditor.XR.Interaction.Toolkit.DeviceBasedSnapTurnProviderEditor.DrawBeforeProperties(), and UnityEditor.XR.Interaction.Toolkit.XRRigEditor.DrawBeforeProperties().
GetDerivedSerializedPropertyNames()
virtual List< string > UnityEditor.XR.Interaction.Toolkit.BaseInteractionEditor.GetDerivedSerializedPropertyNames () protected virtual
Returns a list containing the SerializeField names of all SerializedProperty fields defined in the Editor (including derived types).
Returns
Returns a list of strings with property names.
Reimplemented in UnityEditor.XR.Interaction.Toolkit.XRBaseControllerEditor, and UnityEditor.XR.Interaction.Toolkit.XRRigEditor.
Referenced by UnityEditor.XR.Interaction.Toolkit.BaseInteractionEditor.InitializeKnownSerializedPropertyNames().
InitializeKnownSerializedPropertyNames()
virtual void UnityEditor.XR.Interaction.Toolkit.BaseInteractionEditor.InitializeKnownSerializedPropertyNames () protected virtual
This method is automatically called by OnInspectorGUI to initialize knownSerializedPropertyNames if necessary. This is used together with DrawDerivedProperties to draw all unknown serialized fields from derived classes.
See also
DrawDerivedProperties
Referenced by UnityEditor.XR.Interaction.Toolkit.BaseInteractionEditor.OnInspectorGUI().
OnInspectorGUI()
override void UnityEditor.XR.Interaction.Toolkit.BaseInteractionEditor.OnInspectorGUI ()
Property Documentation
knownSerializedPropertyNames
string [] UnityEditor.XR.Interaction.Toolkit.BaseInteractionEditor.knownSerializedPropertyNames get set protected
The SerializeField names of all SerializedProperty fields defined in the Editor (including derived types).
See also
InitializeKnownSerializedPropertyNames
Referenced by UnityEditor.XR.Interaction.Toolkit.BaseInteractionEditor.DrawDerivedProperties(), and UnityEditor.XR.Interaction.Toolkit.BaseInteractionEditor.InitializeKnownSerializedPropertyNames().
The documentation for this class was generated from the following file:
C:/Users/Lykos/Desktop/Projects/Capstone/VRGames/Library/PackageCache/com.unity.xr.interaction.toolkit@2.0.2/Editor/BaseInteractionEditor.cs