VRGames: Oculus.Interaction.Throw.VelocityCalculatorUtilMethods Class Reference
Oculus.Interaction.Throw.VelocityCalculatorUtilMethods Class Reference
Based on modified LeapMotion's PhysicsUtility class. See associated license.
Static Public Member Functions
static Vector3 ToLinearVelocity (Vector3 startPosition, Vector3 destinationPosition, float deltaTime)
static Vector3 ToAngularVelocity (Quaternion startQuaternion, Quaternion destinationQuaternion, float deltaTime)
static Quaternion AngularVelocityToQuat (Vector3 angularVelocity)
static Vector3 QuatToAngleAxis (Quaternion inputQuat)
static Vector3 QuatToAngularVeloc (Quaternion inputQuat)
static Vector3 DeltaRotationToAngularVelocity (Quaternion deltaRotation, float deltaTime)
static Vector3 GetVelocityAndAngularVelocity (TransformSample startSample, TransformSample endSample, float duration)
Static Public Attributes
static float
static Vector3
Detailed Description
Based on modified LeapMotion's PhysicsUtility class. See associated license.
Member Function Documentation
AngularVelocityToQuat()
static Quaternion Oculus.Interaction.Throw.VelocityCalculatorUtilMethods.AngularVelocityToQuat (Vector3 angularVelocity) static
DeltaRotationToAngularVelocity()
static Vector3 Oculus.Interaction.Throw.VelocityCalculatorUtilMethods.DeltaRotationToAngularVelocity (Quaternion deltaRotation, float deltaTime) static
Referenced by Oculus.Interaction.Throw.VelocityCalculatorUtilMethods.ToAngularVelocity().
GetVelocityAndAngularVelocity()
static Vector3 Oculus.Interaction.Throw.VelocityCalculatorUtilMethods.GetVelocityAndAngularVelocity (TransformSample startSample, TransformSample endSample, float duration) static
QuatToAngleAxis()
static Vector3 Oculus.Interaction.Throw.VelocityCalculatorUtilMethods.QuatToAngleAxis (Quaternion inputQuat) static
Referenced by Oculus.Interaction.Throw.VelocityCalculatorUtilMethods.DeltaRotationToAngularVelocity(), and Oculus.Interaction.Throw.VelocityCalculatorUtilMethods.QuatToAngularVeloc().
QuatToAngularVeloc()
static Vector3 Oculus.Interaction.Throw.VelocityCalculatorUtilMethods.QuatToAngularVeloc (Quaternion inputQuat) static
ToAngularVelocity()
static Vector3 Oculus.Interaction.Throw.VelocityCalculatorUtilMethods.ToAngularVelocity (Quaternion startQuaternion, Quaternion destinationQuaternion, float deltaTime) static
Referenced by Oculus.Interaction.Throw.VelocityCalculatorUtilMethods.GetVelocityAndAngularVelocity().
ToLinearVelocity()
static Vector3 Oculus.Interaction.Throw.VelocityCalculatorUtilMethods.ToLinearVelocity (Vector3 startPosition, Vector3 destinationPosition, float deltaTime) static
Referenced by Oculus.Interaction.Throw.VelocityCalculatorUtilMethods.GetVelocityAndAngularVelocity().
Member Data Documentation
float
Oculus.Interaction.Throw.VelocityCalculatorUtilMethods.float static
Vector3
Oculus.Interaction.Throw.VelocityCalculatorUtilMethods.Vector3 static
The documentation for this class was generated from the following file:
C:/Users/Lykos/Desktop/Projects/Capstone/VRGames/Assets/ThirdParty/Oculus/Interaction/Runtime/ThirdParty/LeapMotion/VelocityCalculatorUtilMethods.cs