VRGames: UnityEngine.UI.LayoutRebuilder Class Reference
UnityEngine.UI.LayoutRebuilder Class Reference
Wrapper class for managing layout rebuilding of CanvasElement.
Public Member Functions
bool IsDestroyed ()
Has the native representation of this LayoutRebuilder been destroyed?
void Rebuild (CanvasUpdate executing)
Rebuild the element for the given stage.
void LayoutComplete ()
Callback sent when this ICanvasElement has completed layout.
void GraphicUpdateComplete ()
Callback sent when this ICanvasElement has completed Graphic rebuild.
override int GetHashCode ()
override bool Equals (object obj)
Does the passed rebuilder point to the same CanvasElement.
override string ToString ()
Static Public Member Functions
static void ForceRebuildLayoutImmediate (RectTransform layoutRoot)
Forces an immediate rebuild of the layout element and child layout elements affected by the calculations.
static void MarkLayoutForRebuild (RectTransform rect)
Mark the given RectTransform as needing it's layout to be recalculated during the next layout pass.
Properties
Transform transform [get]
Get the transform associated with the ICanvasElement.
Properties inherited from UnityEngine.UI.ICanvasElement
Detailed Description
Wrapper class for managing layout rebuilding of CanvasElement.
Member Function Documentation
Equals()
override bool UnityEngine.UI.LayoutRebuilder.Equals (object obj)
Does the passed rebuilder point to the same CanvasElement.
Parameters
obj The other object to compare
Returns
Are they equal
ForceRebuildLayoutImmediate()
static void UnityEngine.UI.LayoutRebuilder.ForceRebuildLayoutImmediate (RectTransform layoutRoot) static
Forces an immediate rebuild of the layout element and child layout elements affected by the calculations.
Parameters
layoutRoot The layout element to perform the layout rebuild on.
Normal use of the layout system should not use this method. Instead MarkLayoutForRebuild should be used instead, which triggers a delayed layout rebuild during the next layout pass. The delayed rebuild automatically handles objects in the entire layout hierarchy in the correct order, and prevents multiple recalculations for the same layout elements. However, for special layout calculation needs, ::ref::ForceRebuildLayoutImmediate can be used to get the layout of a sub-tree resolved immediately. This can even be done from inside layout calculation methods such as ILayoutController.SetLayoutHorizontal orILayoutController.SetLayoutVertical. Usage should be restricted to cases where multiple layout passes are unavaoidable despite the extra cost in performance.
Referenced by GridLayoutGroupTests.TestFlexibleCalculateLayout(), GridLayoutGroupTests.TestHorizontallyContrainedCalculateLayoutHorizontal(), GridLayoutGroupTests.TestHorizontallyContrainedCalculateLayoutVertical(), and GridLayoutGroupTests.TestVerticallyContrainedCalculateLayoutHorizontal().
GetHashCode()
override int UnityEngine.UI.LayoutRebuilder.GetHashCode ()
Referenced by UnityEngine.UI.LayoutRebuilder.Equals().
GraphicUpdateComplete()
void UnityEngine.UI.LayoutRebuilder.GraphicUpdateComplete ()
Callback sent when this ICanvasElement has completed Graphic rebuild.
Implements UnityEngine.UI.ICanvasElement.
IsDestroyed()
bool UnityEngine.UI.LayoutRebuilder.IsDestroyed ()
Has the native representation of this LayoutRebuilder been destroyed?
Implements UnityEngine.UI.ICanvasElement.
LayoutComplete()
void UnityEngine.UI.LayoutRebuilder.LayoutComplete ()
Callback sent when this ICanvasElement has completed layout.
Implements UnityEngine.UI.ICanvasElement.
MarkLayoutForRebuild()
static void UnityEngine.UI.LayoutRebuilder.MarkLayoutForRebuild (RectTransform rect) static
Mark the given RectTransform as needing it's layout to be recalculated during the next layout pass.
Parameters
rect Rect to rebuild.
Referenced by InputfieldTests.GenericInputFieldTests.CaretRectSameSizeAsTextRect(), TMPro.TextMeshProUGUI.OnDisable(), UnityEngine.UI.AspectRatioFitter.OnDisable(), UnityEngine.UI.ContentSizeFitter.OnDisable(), UnityEngine.UI.LayoutGroup.OnDisable(), UnityEngine.UI.ContentSizeFitter.SetDirty(), UnityEngine.UI.LayoutGroup.SetDirty(), TMPro.TextMeshPro.SetLayoutDirty(), TMPro.TextMeshProUGUI.SetLayoutDirty(), and TMPro.TMP_InputField.UpdateLabel().
Rebuild()
void UnityEngine.UI.LayoutRebuilder.Rebuild (CanvasUpdate executing)
Rebuild the element for the given stage.
Parameters
executing The current CanvasUpdate stage being rebuild.
Implements UnityEngine.UI.ICanvasElement.
ToString()
override string UnityEngine.UI.LayoutRebuilder.ToString ()
Property Documentation
transform
Transform UnityEngine.UI.LayoutRebuilder.transform get
Get the transform associated with the ICanvasElement.
Implements UnityEngine.UI.ICanvasElement.
The documentation for this class was generated from the following file:
C:/Users/Lykos/Desktop/Projects/Capstone/VRGames/Library/PackageCache/com.unity.ugui@1.0.0/Runtime/UI/Core/Layout/LayoutRebuilder.cs