VRGames: PointsManager Class Reference
PointsManager Class Reference
Manages points and related functionality in the game.
Static Public Member Functions
static int getLeftPoints ()
Retrieves the points accumulated by the left hand.
static int getRightPoints ()
Retrieves the points accumulated by the right hand.
static int getPoints ()
Retrieves the total points accumulated.
static void resetPoints ()
Resets all points to zero.
static void resetBothHandPoints ()
Resets points for both left and right hands to zero.
static void addPoints (int p)
Adds points to the total score.
static void addLeftPoints (int p)
Adds points to the left hand's score.
static void addRightPoints (int p)
Adds points to the right hand's score.
static void subPoints (int p)
Subtracts points from the total score.
static void multPoints (int p)
Multiplies the total score by a factor.
static void divPoints (int p)
Divides the total score by a factor.
static bool isGoalReached (GameSettingsSO.HandSetting handSetting, int goal)
Checks if a goal is reached based on the current hand setting.
static void addPointTrigger (string equality, int points, string function)
Adds a point trigger to the list.
static void updateScoreboardMessage (string s)
Updates the message displayed on the scoreboard.
static void updateScoreboard ()
Updates the scoreboard with current scores and display settings.
Public Attributes
bool useSeparateScores
Detailed Description
Manages points and related functionality in the game.
The PointsManager class is responsible for managing points and related functionality in the game, including updating scores, checking goals, and handling point triggers.
Member Function Documentation
addLeftPoints()
static void PointsManager.addLeftPoints (int p) static
Adds points to the left hand's score.
Parameters
p The points to add.
addPoints()
static void PointsManager.addPoints (int p) static
Adds points to the total score.
Parameters
p The points to add.
References updateScoreboard().
Referenced by Classes.Target.HitTarget(), and Classes.Managers.LavaClimbGameplayManager.onRockGrabbed().
addPointTrigger()
static void PointsManager.addPointTrigger (string equality, int points, string function) static
Adds a point trigger to the list.
Parameters
equality The condition to trigger the point trigger.
points The points required for the trigger.
function The function to execute when triggered.
addRightPoints()
static void PointsManager.addRightPoints (int p) static
Adds points to the right hand's score.
Parameters
p The points to add.
divPoints()
static void PointsManager.divPoints (int p) static
Divides the total score by a factor.
Parameters
p The factor to divide by.
References updateScoreboard().
getLeftPoints()
static int PointsManager.getLeftPoints () static
Retrieves the points accumulated by the left hand.
getPoints()
static int PointsManager.getPoints () static
Retrieves the total points accumulated.
Referenced by Classes.Managers.LavaClimbGameplayManager.onRockGrabbed(), and PointTrigger.testEquality().
getRightPoints()
static int PointsManager.getRightPoints () static
Retrieves the points accumulated by the right hand.
isGoalReached()
static bool PointsManager.isGoalReached (GameSettingsSO::HandSetting handSetting, int goal) static
Checks if a goal is reached based on the current hand setting.
Parameters
handSetting The hand setting to check against.
goal The goal to compare against.
Returns
True if the goal is reached, otherwise false.
multPoints()
static void PointsManager.multPoints (int p) static
Multiplies the total score by a factor.
Parameters
p The factor to multiply by.
References updateScoreboard().
resetBothHandPoints()
static void PointsManager.resetBothHandPoints () static
Resets points for both left and right hands to zero.
Referenced by Classes.Managers.BoxAndBlocksGameplayManager.startSpawning().
resetPoints()
static void PointsManager.resetPoints () static
Resets all points to zero.
References updateScoreboard().
subPoints()
static void PointsManager.subPoints (int p) static
Subtracts points from the total score.
Parameters
p The points to subtract.
References updateScoreboard().
updateScoreboard()
static void PointsManager.updateScoreboard () static
Updates the scoreboard with current scores and display settings.
Referenced by addPoints(), divPoints(), multPoints(), resetPoints(), and subPoints().
updateScoreboardMessage()
static void PointsManager.updateScoreboardMessage (string s) static
Updates the message displayed on the scoreboard.
Parameters
s The message to display.
Referenced by Classes.Managers.BoxAndBlocksGameplayManager.onFirstPointReached(), PlanesGame.PlaneGameplayManager.OnPlaneGrabbed(), Classes.Managers.BoxAndBlocksGameplayManager.onTimeExpired(), Classes.Managers.LavaClimbGameplayManager.onWinConditionPointsReached(), and MasterArchitectureGameplayManager.onWinConditionPointsReached().
Member Data Documentation
useSeparateScores
bool PointsManager.useSeparateScores
The documentation for this class was generated from the following file:
C:/Users/Lykos/Desktop/Projects/Capstone/VRGames/Assets/Shared/Scripts/Managers/PointsManager.cs