VRGames: UnityEngine.InputSystem.PlayerInputManager Class Reference
UnityEngine.InputSystem.PlayerInputManager Class Reference
Manages joining and leaving of players.
Classes
class PlayerJoinedEvent
class PlayerLeftEvent
Public Member Functions
void EnableJoining ()
Allow players to join the game based on joinBehavior.
void DisableJoining ()
Inhibit players from joining the game.
void JoinPlayerFromAction (InputAction.CallbackContext context)
Join a new player based on input received through an InputAction.
void JoinPlayerFromActionIfNotAlreadyJoined (InputAction.CallbackContext context)
PlayerInput JoinPlayer (int playerIndex=-1, int splitScreenIndex=-1, string controlScheme=null, InputDevice pairWithDevice=null)
Spawn a new player from playerPrefab.
PlayerInput JoinPlayer (int playerIndex=-1, int splitScreenIndex=-1, string controlScheme=null, params InputDevice[] pairWithDevices)
Spawn a new player from playerPrefab.
Static Public Attributes
const string PlayerJoinedMessage = "OnPlayerJoined"
Name of the message that is sent when a player joins the game.
const string PlayerLeftMessage = "OnPlayerLeft"
Properties
bool splitScreen [get, set]
If enabled, each player will automatically be assigned a portion of the available screen area.
bool maintainAspectRatioInSplitScreen [get]
If splitScreen is enabled, this property determines whether subdividing the screen is allowed to produce screen areas that have an aspect ratio different from the screen resolution.
int fixedNumberOfSplitScreens [get]
Rect splitScreenArea [get]
The normalized screen rectangle available for allocating player split-screens into.
int playerCount [get]
The current number of active players.
int maxPlayerCount [get]
Maximum number of players allowed concurrently in the game.
bool joiningEnabled [get]
Whether new players can currently join.
PlayerJoinBehavior joinBehavior [get, set]
Determines the mechanism by which players can join when joining is enabled (joiningEnabled).
InputActionProperty joinAction [get, set]
The input action that a player must trigger to join the game.
PlayerNotifications notificationBehavior [get, set]
PlayerJoinedEvent playerJoinedEvent [get]
PlayerLeftEvent playerLeftEvent [get]
Action< PlayerInput > onPlayerJoined
Action< PlayerInput > onPlayerLeft
GameObject playerPrefab [get, set]
Reference to the prefab that the manager will instantiate when players join.
static PlayerInputManager instance [get]
Singleton instance of the manager.
Detailed Description
Manages joining and leaving of players.
This is a singleton component. Only one instance is meant to be active in a game at any one time. To retrieve the current instance, use instance.
Note that a PlayerInputManager is not strictly required to have multiple PlayerInput components. What PlayerInputManager provides is the implementation of specific player join mechanisms (joinBehavior) as well as automatic assignment of split-screen areas (splitScreen). However, you can always implement your own custom logic instead and simply instantiate multiple GameObjects with PlayerInput yourself.
Member Function Documentation
DisableJoining()
void UnityEngine.InputSystem.PlayerInputManager.DisableJoining ()
Inhibit players from joining the game.
See also
EnableJoining, joiningEnabled
EnableJoining()
void UnityEngine.InputSystem.PlayerInputManager.EnableJoining ()
Allow players to join the game based on joinBehavior.
See also
DisableJoining, joiningEnabled
JoinPlayer() [1/2]
PlayerInput UnityEngine.InputSystem.PlayerInputManager.JoinPlayer (int playerIndex = -1, int splitScreenIndex = -1, string controlScheme = null, InputDevice pairWithDevice = null)
Spawn a new player from playerPrefab.
Parameters
playerIndex Optional explicit PlayerInput.playerIndex to assign to the player. Must be unique within PlayerInput.all. If not supplied, a player index will be assigned automatically (smallest unused index will be used).
splitScreenIndex Optional PlayerInput.splitScreenIndex. If supplied, this assigns a split-screen area to the player. For example, a split-screen index of
controlScheme Control scheme to activate on the player (optional). If not supplied, a control scheme will be selected based on pairWithDevice . If no device is given either, the first control scheme that matches the currently available unpaired devices (see InputUser.GetUnpairedInputDevices()) is used.
pairWithDevice Device to pair to the player. Also determines which control scheme to use if controlScheme is not given.
Returns
The newly instantiated player or null if joining failed.
Joining must be enabled (see joiningEnabled) or the method will fail.
To pair multiple devices, use JoinPlayer(int,int,string,InputDevice[]).
Referenced by UnityEngine.InputSystem.PlayerInputManager.JoinPlayerFromAction(), and UnityEngine.InputSystem.PlayerInputManager.JoinPlayerFromActionIfNotAlreadyJoined().
JoinPlayer() [2/2]
PlayerInput UnityEngine.InputSystem.PlayerInputManager.JoinPlayer (int playerIndex = -1, int splitScreenIndex = -1, string controlScheme = null, params InputDevice[] pairWithDevices)
Spawn a new player from playerPrefab.
Parameters
playerIndex Optional explicit PlayerInput.playerIndex to assign to the player. Must be unique within PlayerInput.all. If not supplied, a player index will be assigned automatically (smallest unused index will be used).
splitScreenIndex Optional PlayerInput.splitScreenIndex. If supplied, this assigns a split-screen area to the player. For example, a split-screen index of
controlScheme Control scheme to activate on the player (optional). If not supplied, a control scheme will be selected based on pairWithDevices . If no device is given either, the first control scheme that matches the currently available unpaired devices (see InputUser.GetUnpairedInputDevices()) is used.
pairWithDevices Devices to pair to the player. Also determines which control scheme to use if controlScheme is not given.
Returns
The newly instantiated player or null if joining failed.
Joining must be enabled (see joiningEnabled) or the method will fail.
JoinPlayerFromAction()
void UnityEngine.InputSystem.PlayerInputManager.JoinPlayerFromAction (InputAction::CallbackContext context)
Join a new player based on input received through an InputAction.
Parameters
context
JoinPlayerFromActionIfNotAlreadyJoined()
void UnityEngine.InputSystem.PlayerInputManager.JoinPlayerFromActionIfNotAlreadyJoined (InputAction::CallbackContext context)
Referenced by UnityEngine.InputSystem.PlayerInputManager.EnableJoining().
Member Data Documentation
PlayerJoinedMessage
const string UnityEngine.InputSystem.PlayerInputManager.PlayerJoinedMessage = "OnPlayerJoined" static
Name of the message that is sent when a player joins the game.
PlayerLeftMessage
const string UnityEngine.InputSystem.PlayerInputManager.PlayerLeftMessage = "OnPlayerLeft" static
Property Documentation
fixedNumberOfSplitScreens
int UnityEngine.InputSystem.PlayerInputManager.fixedNumberOfSplitScreens get
instance
PlayerInputManager UnityEngine.InputSystem.PlayerInputManager.instance static get
Singleton instance of the manager.
Singleton instance or null.
joinAction
InputActionProperty UnityEngine.InputSystem.PlayerInputManager.joinAction get set
The input action that a player must trigger to join the game.
If the join action is a reference to an existing input action, it will be cloned when the PlayerInputManager is enabled. This avoids the situation where the join action can become disabled after the first user joins which can happen when the join action is the same as a player in-game action. When a player joins, input bindings from devices other than the device they joined with are disabled. If the join action had a binding for keyboard and one for gamepad for example, and the first player joined using the keyboard, the expectation is that the next player could still join by pressing the gamepad join button. Without the cloning behavior, the gamepad input would have been disabled.
For more details about joining behavior, see PlayerInput.
Referenced by UnityEngine.InputSystem.PlayerInputManager.DisableJoining().
joinBehavior
PlayerJoinBehavior UnityEngine.InputSystem.PlayerInputManager.joinBehavior get set
Determines the mechanism by which players can join when joining is enabled (joiningEnabled).
joiningEnabled
bool UnityEngine.InputSystem.PlayerInputManager.joiningEnabled get
Whether new players can currently join.
While this is true, new players can join via the mechanism determined by joinBehavior.
See also
EnableJoining, DisableJoining
maintainAspectRatioInSplitScreen
bool UnityEngine.InputSystem.PlayerInputManager.maintainAspectRatioInSplitScreen get
If splitScreen is enabled, this property determines whether subdividing the screen is allowed to produce screen areas that have an aspect ratio different from the screen resolution.
REVIEW: we probably need support for filling unused screen areas automatically
By default, when splitScreen is enabled, the manager will add or remove screen subdivisions in steps of two. This means that when, for example, the second player is added, the screen will be subdivided into a left and a right screen area; the left one allocated to the first player and the right one allocated to the second player.
This behavior makes optimal use of screen real estate but will result in screen areas that have aspect ratios different from the screen resolution. If this is not acceptable, this property can be set to true to enforce split-screen to only create screen areas that have the same aspect ratio of the screen.
This results in the screen being subdivided more aggressively. When, for example, a second player is added, the screen will immediately be divided into a four-way split-screen setup with the lower two screen areas not being used.
This property is irrelevant if fixedNumberOfSplitScreens is used.
maxPlayerCount
int UnityEngine.InputSystem.PlayerInputManager.maxPlayerCount get
Maximum number of players allowed concurrently in the game.
FIXME: this needs to be settable
If this limit is reached, joining is turned off automatically.
By default this is set to -1. Any negative value deactivates the player limit and allows arbitrary many players to join.
notificationBehavior
PlayerNotifications UnityEngine.InputSystem.PlayerInputManager.notificationBehavior get set
onPlayerJoined
Action<PlayerInput> UnityEngine.InputSystem.PlayerInputManager.onPlayerJoined add remove
onPlayerLeft
Action<PlayerInput> UnityEngine.InputSystem.PlayerInputManager.onPlayerLeft add remove
playerCount
int UnityEngine.InputSystem.PlayerInputManager.playerCount get
The current number of active players.
This count corresponds to all PlayerInput instances that are currently enabled.
playerJoinedEvent
PlayerJoinedEvent UnityEngine.InputSystem.PlayerInputManager.playerJoinedEvent get
playerLeftEvent
PlayerLeftEvent UnityEngine.InputSystem.PlayerInputManager.playerLeftEvent get
playerPrefab
GameObject UnityEngine.InputSystem.PlayerInputManager.playerPrefab get set
Reference to the prefab that the manager will instantiate when players join.
Prefab to instantiate for new players.
splitScreen
bool UnityEngine.InputSystem.PlayerInputManager.splitScreen get set
If enabled, each player will automatically be assigned a portion of the available screen area.
For this to work, each PlayerInput component must have an associated Camera object through PlayerInput.camera.
Note that as player join, the screen may be increasingly subdivided and players may see their previous screen area getting resized.
splitScreenArea
Rect UnityEngine.InputSystem.PlayerInputManager.splitScreenArea get
The normalized screen rectangle available for allocating player split-screens into.
This is only used if splitScreen is true.
By default it is set to (0,0,1,1), i.e. the entire screen area will be used for player screens. If, for example, part of the screen should display a UI/information shared by all players, this property can be used to cut off the area and not have it used by PlayerInputManager.
The documentation for this class was generated from the following file:
C:/Users/Lykos/Desktop/Projects/Capstone/VRGames/Library/PackageCache/com.unity.inputsystem@1.3.0/InputSystem/Plugins/PlayerInput/PlayerInputManager.cs