VRGames: OVRNetwork.OVRNetworkTcpServer Class Reference
OVRNetwork.OVRNetworkTcpServer Class Reference
Public Member Functions
void StartListening (int listeningPort)
void StopListening ()
bool HasConnectedClient ()
void Broadcast (int payloadType, byte[] payload)
Public Attributes
TcpListener tcpListener = null
readonly List< TcpClient > clients = new List<TcpClient>()
Member Function Documentation
Broadcast()
void OVRNetwork.OVRNetworkTcpServer.Broadcast (int payloadType, byte[] payload)
HasConnectedClient()
bool OVRNetwork.OVRNetworkTcpServer.HasConnectedClient ()
StartListening()
void OVRNetwork.OVRNetworkTcpServer.StartListening (int listeningPort)
StopListening()
void OVRNetwork.OVRNetworkTcpServer.StopListening ()
Member Data Documentation
clients
readonly List<TcpClient> OVRNetwork.OVRNetworkTcpServer.clients = new List<TcpClient>()
Referenced by OVRNetwork.OVRNetworkTcpServer.Broadcast(), OVRNetwork.OVRNetworkTcpServer.HasConnectedClient(), and OVRNetwork.OVRNetworkTcpServer.StopListening().
tcpListener
TcpListener OVRNetwork.OVRNetworkTcpServer.tcpListener = null
Referenced by OVRNetwork.OVRNetworkTcpServer.StartListening(), and OVRNetwork.OVRNetworkTcpServer.StopListening().
The documentation for this class was generated from the following file:
C:/Users/Lykos/Desktop/Projects/Capstone/VRGames/Assets/ThirdParty/Oculus/VR/Scripts/Util/OVRNetwork.cs