VRGames: UnityEngine.EventSystems.PointerInputModule Class Reference
UnityEngine.EventSystems.PointerInputModule Class Reference abstract
A BaseInputModule for pointer input.
Classes
class ButtonState
class MouseButtonEventData
Information about a mouse button event.
class MouseState
Public Member Functions
override bool IsPointerOverGameObject (int pointerId)
override string ToString ()
Static Public Attributes
const int kMouseLeftId = -1
Id of the cached left mouse pointer event.
const int kMouseRightId = -2
Id of the cached right mouse pointer event.
const int kMouseMiddleId = -3
Id of the cached middle mouse pointer event.
const int kFakeTouchesId = -4
Touch id for when simulating touches on a non touch device.
Protected Member Functions
bool GetPointerData (int id, out PointerEventData data, bool create)
Search the cache for currently active pointers, return true if found.
void RemovePointerData (PointerEventData data)
Remove the PointerEventData from the cache.
PointerEventData GetTouchPointerEventData (Touch input, out bool pressed, out bool released)
Given a touch populate the PointerEventData and return if we are pressed or released.
void CopyFromTo (PointerEventData @from, PointerEventData @to)
Copy one PointerEventData to another.
PointerEventData.FramePressState StateForMouseButton (int buttonId)
Given a mouse button return the current state for the frame.
virtual MouseState GetMousePointerEventData ()
Return the current MouseState. Using the default pointer.
virtual MouseState GetMousePointerEventData (int id)
Return the current MouseState.
PointerEventData GetLastPointerEventData (int id)
Return the last PointerEventData for the given touch / mouse id.
virtual void ProcessMove (PointerEventData pointerEvent)
Process movement for the current frame with the given pointer event.
virtual void ProcessDrag (PointerEventData pointerEvent)
Process the drag for the current frame with the given pointer event.
void ClearSelection ()
Clear all pointers and deselect any selected objects in the EventSystem.
void DeselectIfSelectionChanged (GameObject currentOverGo, BaseEventData pointerEvent)
Deselect the current selected GameObject if the currently pointed-at GameObject is different.
Protected Attributes
Dictionary< int, PointerEventData > m_PointerData = new Dictionary<int, PointerEventData>()
Detailed Description
A BaseInputModule for pointer input.
Member Function Documentation
ClearSelection()
void UnityEngine.EventSystems.PointerInputModule.ClearSelection () protected
Clear all pointers and deselect any selected objects in the EventSystem.
Referenced by UnityEngine.EventSystems.StandaloneInputModule.DeactivateModule(), and UnityEngine.EventSystems.TouchInputModule.DeactivateModule().
CopyFromTo()
void UnityEngine.EventSystems.PointerInputModule.CopyFromTo (PointerEventData @ from, PointerEventData @ to) protected
Copy one PointerEventData to another.
Referenced by UnityEngine.EventSystems.PointerInputModule.GetMousePointerEventData().
DeselectIfSelectionChanged()
void UnityEngine.EventSystems.PointerInputModule.DeselectIfSelectionChanged (GameObject currentOverGo, BaseEventData pointerEvent) protected
Deselect the current selected GameObject if the currently pointed-at GameObject is different.
Parameters
currentOverGo The GameObject the pointer is currently over.
pointerEvent Current event data.
Referenced by UnityEngine.EventSystems.StandaloneInputModule.ProcessMousePress(), UnityEngine.EventSystems.StandaloneInputModule.ProcessTouchPress(), UnityEngine.EventSystems.TouchInputModule.ProcessTouchPress(), and Oculus.Interaction.PointableCanvasModule.UpdatePointerEventData().
GetLastPointerEventData()
PointerEventData UnityEngine.EventSystems.PointerInputModule.GetLastPointerEventData (int id) protected
Return the last PointerEventData for the given touch / mouse id.
Referenced by UnityEngine.EventSystems.PointerInputModule.IsPointerOverGameObject(), and UnityEngine.EventSystems.TouchInputModule.ToString().
GetMousePointerEventData() [1/2]
virtual MouseState UnityEngine.EventSystems.PointerInputModule.GetMousePointerEventData () protected virtual
Return the current MouseState. Using the default pointer.
Referenced by UnityEngine.EventSystems.PointerInputModule.GetMousePointerEventData(), and UnityEngine.EventSystems.StandaloneInputModule.ProcessMouseEvent().
GetMousePointerEventData() [2/2]
virtual MouseState UnityEngine.EventSystems.PointerInputModule.GetMousePointerEventData (int id) protected virtual
Return the current MouseState.
GetPointerData()
bool UnityEngine.EventSystems.PointerInputModule.GetPointerData (int id, out PointerEventData data, bool create) protected
Search the cache for currently active pointers, return true if found.
Parameters
id Touch ID
data Found data
create If not found should it be created
Returns
True if pointer is found.
Referenced by UnityEngine.EventSystems.PointerInputModule.GetLastPointerEventData(), UnityEngine.EventSystems.PointerInputModule.GetMousePointerEventData(), and UnityEngine.EventSystems.PointerInputModule.GetTouchPointerEventData().
GetTouchPointerEventData()
PointerEventData UnityEngine.EventSystems.PointerInputModule.GetTouchPointerEventData (Touch input, out bool pressed, out bool released) protected
Given a touch populate the PointerEventData and return if we are pressed or released.
Parameters
input Touch being processed
pressed Are we pressed this frame
released Are we released this frame
Returns
IsPointerOverGameObject()
override bool UnityEngine.EventSystems.PointerInputModule.IsPointerOverGameObject (int pointerId)
ProcessDrag()
virtual void UnityEngine.EventSystems.PointerInputModule.ProcessDrag (PointerEventData pointerEvent) protected virtual
Process the drag for the current frame with the given pointer event.
Reimplemented in Oculus.Interaction.PointableCanvasModule, and UnityEngine.EventSystems.OVRInputModule.
Referenced by UnityEngine.EventSystems.StandaloneInputModule.ProcessMouseEvent().
ProcessMove()
virtual void UnityEngine.EventSystems.PointerInputModule.ProcessMove (PointerEventData pointerEvent) protected virtual
Process movement for the current frame with the given pointer event.
Referenced by UnityEngine.EventSystems.StandaloneInputModule.ProcessMouseEvent().
RemovePointerData()
void UnityEngine.EventSystems.PointerInputModule.RemovePointerData (PointerEventData data) protected
Remove the PointerEventData from the cache.
StateForMouseButton()
PointerEventData.FramePressState UnityEngine.EventSystems.PointerInputModule.StateForMouseButton (int buttonId) protected
Given a mouse button return the current state for the frame.
Parameters
buttonId Mouse button ID
Referenced by UnityEngine.EventSystems.OVRInputModule.GetCanvasPointerData(), and UnityEngine.EventSystems.PointerInputModule.GetMousePointerEventData().
ToString()
override string UnityEngine.EventSystems.PointerInputModule.ToString ()
Member Data Documentation
kFakeTouchesId
const int UnityEngine.EventSystems.PointerInputModule.kFakeTouchesId = -4 static
Touch id for when simulating touches on a non touch device.
kMouseLeftId
const int UnityEngine.EventSystems.PointerInputModule.kMouseLeftId = -1 static
Id of the cached left mouse pointer event.
Referenced by UnityEngine.EventSystems.OVRInputModule.GetCanvasPointerData(), UnityEngine.EventSystems.OVRInputModule.GetGazePointerData(), UnityEngine.EventSystems.PointerInputModule.GetMousePointerEventData(), UnityEngine.EventSystems.EventSystem.IsPointerOverGameObject(), and UnityEngine.EventSystems.TouchInputModule.ToString().
kMouseMiddleId
const int UnityEngine.EventSystems.PointerInputModule.kMouseMiddleId = -3 static
Id of the cached middle mouse pointer event.
Referenced by UnityEngine.EventSystems.OVRInputModule.GetCanvasPointerData(), UnityEngine.EventSystems.OVRInputModule.GetGazePointerData(), and UnityEngine.EventSystems.PointerInputModule.GetMousePointerEventData().
kMouseRightId
const int UnityEngine.EventSystems.PointerInputModule.kMouseRightId = -2 static
Id of the cached right mouse pointer event.
Referenced by UnityEngine.EventSystems.OVRInputModule.GetCanvasPointerData(), UnityEngine.EventSystems.OVRInputModule.GetGazePointerData(), and UnityEngine.EventSystems.PointerInputModule.GetMousePointerEventData().
m_PointerData
Dictionary<int, PointerEventData> UnityEngine.EventSystems.PointerInputModule.m_PointerData = new Dictionary<int, PointerEventData>() protected
Referenced by UnityEngine.EventSystems.OVRInputModule.ClearSelection(), UnityEngine.EventSystems.PointerInputModule.ClearSelection(), UnityEngine.EventSystems.PointerInputModule.GetPointerData(), UnityEngine.EventSystems.PointerInputModule.RemovePointerData(), UnityEngine.EventSystems.PointerInputModule.ToString(), and UnityEngine.EventSystems.TouchInputModule.ToString().
The documentation for this class was generated from the following file:
C:/Users/Lykos/Desktop/Projects/Capstone/VRGames/Library/PackageCache/com.unity.ugui@1.0.0/Runtime/EventSystem/InputModules/PointerInputModule.cs