VRGames: Unity.XR.TestTooling.LoaderTestSetup< L, S > Class Template Reference
Unity.XR.TestTooling.LoaderTestSetup< L, S > Class Template Reference abstract
Public Member Functions
override void SetupTest ()
override void TearDownTest ()
Protected Member Functions
void InitializeAndStart ()
void StopAndShutdown ()
void RestartProvider ()
Protected Attributes
L loader = null
S settings = null
Protected Attributes inherited from Unity.XR.TestTooling.ManagementTestSetup
string testPathToGeneralSettings
string testPathToSettings
XRManagerSettings testManager = null
XRGeneralSettings xrGeneralSettings = null
XRGeneralSettingsPerBuildTarget buildTargetSettings = null
Properties
string settingsKey [get]
Properties inherited from Unity.XR.TestTooling.ManagementTestSetup
virtual bool TestManagerUpgradePath [get]
When true, AssetDatabase.AddObjectToAsset will not be called to add XRManagerSettings to XRGeneralSettings.
Additional Inherited Members
Static Public Member Functions inherited from Unity.XR.TestTooling.ManagementTestSetup
static string GetAssetPathForComponents (string[] pathComponents, string root="Assets")
Static Protected Attributes inherited from Unity.XR.TestTooling.ManagementTestSetup
static readonly string[] s_TestGeneralSettings = { "Temp", "Test" }
static readonly string[] s_TempSettingsPath = {"Temp", "Test", "Settings" }
Member Function Documentation
InitializeAndStart()
void Unity.XR.TestTooling.LoaderTestSetup< L, S >.InitializeAndStart () protected
Referenced by Unity.XR.TestTooling.LoaderTestSetup< L, S >.RestartProvider().
RestartProvider()
void Unity.XR.TestTooling.LoaderTestSetup< L, S >.RestartProvider () protected
SetupTest()
override void Unity.XR.TestTooling.LoaderTestSetup< L, S >.SetupTest () virtual
Reimplemented from Unity.XR.TestTooling.ManagementTestSetup.
StopAndShutdown()
void Unity.XR.TestTooling.LoaderTestSetup< L, S >.StopAndShutdown () protected
Referenced by Unity.XR.TestTooling.LoaderTestSetup< L, S >.RestartProvider(), and Unity.XR.TestTooling.LoaderTestSetup< L, S >.TearDownTest().
TearDownTest()
override void Unity.XR.TestTooling.LoaderTestSetup< L, S >.TearDownTest () virtual
Reimplemented from Unity.XR.TestTooling.ManagementTestSetup.
Member Data Documentation
loader
L Unity.XR.TestTooling.LoaderTestSetup< L, S >.loader = null protected
Referenced by Unity.XR.TestTooling.LoaderTestSetup< L, S >.InitializeAndStart(), Unity.XR.TestTooling.LoaderTestSetup< L, S >.SetupTest(), Unity.XR.TestTooling.LoaderTestSetup< L, S >.StopAndShutdown(), and Unity.XR.TestTooling.LoaderTestSetup< L, S >.TearDownTest().
settings
S Unity.XR.TestTooling.LoaderTestSetup< L, S >.settings = null protected
Referenced by Unity.XR.TestTooling.LoaderTestSetup< L, S >.SetupTest().
Property Documentation
settingsKey
string Unity.XR.TestTooling.LoaderTestSetup< L, S >.settingsKey get abstract protected
Referenced by Unity.XR.TestTooling.LoaderTestSetup< L, S >.SetupTest().
The documentation for this class was generated from the following file:
C:/Users/Lykos/Desktop/Projects/Capstone/VRGames/Library/PackageCache/com.unity.xr.management@4.2.1/Tests/TestTooling/LoaderTestSetup.cs