VRGames: Oculus.Interaction.PokeInteractable Class Reference
Oculus.Interaction.PokeInteractable Class Reference
Public Member Functions
Vector3 ComputeClosestPoint (Vector3 point)
Vector3 ClosestSurfacePoint (Vector3 point)
Vector3 ClosestSurfaceNormal (Vector3 point)
void InjectAllPokeInteractable (IPointableSurface surface, IProximityField proximityField)
void InjectSurface (IPointableSurface surface)
void InjectProximityField (IProximityField proximityField)
void InjectOptionalMaxDistance (float maxDistance)
void InjectOptionalReleaseDistance (float releaseDistance)
void InjectOptionalHorizontalDragThreshold (float horizontalDragThreshold)
void InjectOptionalVerticalDragThreshold (float verticalDragThreshold)
void InjectOptionalEnterHoverDistance (float enterHoverDistance)
void InjectOptionalVolumeMask (Collider volumeMask)
Public Member Functions inherited from Oculus.Interaction.Interactable< PokeInteractor, PokeInteractable >
void AddInteractor (TInteractor interactor)
void RemoveInteractor (TInteractor interactor)
void AddSelectingInteractor (TInteractor interactor)
void RemoveSelectingInteractor (TInteractor interactor)
bool CanBeSelectedBy (TInteractor interactor)
bool HasInteractor (TInteractor interactor)
bool HasSelectingInteractor (TInteractor interactor)
void Enable ()
void Disable ()
void RemoveInteractorById (int id)
Public Attributes
IProximityField ProximityField
IPointableSurface Surface
Protected Member Functions
virtual void Awake ()
virtual void Start ()
override void OnEnable ()
override void OnDisable ()
virtual void OnDestroy ()
Protected Member Functions inherited from Oculus.Interaction.Interactable< PokeInteractor, PokeInteractable >
virtual void InteractorAdded (TInteractor interactor)
virtual void InteractorRemoved (TInteractor interactor)
virtual void SelectingInteractorAdded (TInteractor interactor)
virtual void SelectingInteractorRemoved (TInteractor interactor)
virtual void SetRegistry (IInteractableRegistry< TInteractor, TInteractable > registry)
Protected Attributes
bool _started = false
Properties
float MaxDistance [get]
float ReleaseDistance [get]
float EnterHoverDistance [get]
float HorizontalDragThreshold [get]
float VerticalDragThreshold [get]
Collider VolumeMask [get]
Properties inherited from Oculus.Interaction.Interactable< PokeInteractor, PokeInteractable >
int MaxInteractors [get, set]
int MaxSelectingInteractors [get, set]
MAction< TInteractor > WhenInteractorAdded [get]
MAction< TInteractor > WhenInteractorRemoved [get]
MAction< TInteractor > WhenSelectingInteractorAdded [get]
MAction< TInteractor > WhenSelectingInteractorRemoved [get]
InteractableState State [get]
static IInteractableRegistry< TInteractor, TInteractable > Registry [get]
int InteractorsCount [get]
int SelectingInteractorsCount [get]
IEnumerable< TInteractor > Interactors [get]
IEnumerable< TInteractor > SelectingInteractors [get]
Events
Action< PointerArgs > OnPointerEvent = delegate { }
Events inherited from Oculus.Interaction.Interactable< PokeInteractor, PokeInteractable >
Action WhenInteractorsCountUpdated
Action WhenSelectingInteractorsCountUpdated
Action< InteractableStateChangeArgs > WhenStateChanged
Events inherited from Oculus.Interaction.IPointable
Action< PointerArgs > OnPointerEvent
Member Function Documentation
Awake()
virtual void Oculus.Interaction.PokeInteractable.Awake () protected virtual
ClosestSurfaceNormal()
Vector3 Oculus.Interaction.PokeInteractable.ClosestSurfaceNormal (Vector3 point)
Referenced by Oculus.Interaction.PokeInteractor.DoSelectUpdate().
ClosestSurfacePoint()
Vector3 Oculus.Interaction.PokeInteractable.ClosestSurfacePoint (Vector3 point)
Referenced by Oculus.Interaction.PokeInteractor.DoSelectUpdate(), and Oculus.Interaction.PokeInteractor.InteractableSelected().
ComputeClosestPoint()
Vector3 Oculus.Interaction.PokeInteractable.ComputeClosestPoint (Vector3 point)
Referenced by Oculus.Interaction.PokeInteractor.DoSelectUpdate().
InjectAllPokeInteractable()
void Oculus.Interaction.PokeInteractable.InjectAllPokeInteractable (IPointableSurface surface, IProximityField proximityField)
InjectOptionalEnterHoverDistance()
void Oculus.Interaction.PokeInteractable.InjectOptionalEnterHoverDistance (float enterHoverDistance)
InjectOptionalHorizontalDragThreshold()
void Oculus.Interaction.PokeInteractable.InjectOptionalHorizontalDragThreshold (float horizontalDragThreshold)
InjectOptionalMaxDistance()
void Oculus.Interaction.PokeInteractable.InjectOptionalMaxDistance (float maxDistance)
InjectOptionalReleaseDistance()
void Oculus.Interaction.PokeInteractable.InjectOptionalReleaseDistance (float releaseDistance)
InjectOptionalVerticalDragThreshold()
void Oculus.Interaction.PokeInteractable.InjectOptionalVerticalDragThreshold (float verticalDragThreshold)
InjectOptionalVolumeMask()
void Oculus.Interaction.PokeInteractable.InjectOptionalVolumeMask (Collider volumeMask)
InjectProximityField()
void Oculus.Interaction.PokeInteractable.InjectProximityField (IProximityField proximityField)
Referenced by Oculus.Interaction.PokeInteractable.InjectAllPokeInteractable().
InjectSurface()
void Oculus.Interaction.PokeInteractable.InjectSurface (IPointableSurface surface)
Referenced by Oculus.Interaction.PokeInteractable.InjectAllPokeInteractable().
OnDestroy()
virtual void Oculus.Interaction.PokeInteractable.OnDestroy () protected virtual
OnDisable()
override void Oculus.Interaction.PokeInteractable.OnDisable () protected virtual
Reimplemented from Oculus.Interaction.Interactable< PokeInteractor, PokeInteractable >.
OnEnable()
override void Oculus.Interaction.PokeInteractable.OnEnable () protected virtual
Reimplemented from Oculus.Interaction.Interactable< PokeInteractor, PokeInteractable >.
Start()
virtual void Oculus.Interaction.PokeInteractable.Start () protected virtual
Member Data Documentation
_started
bool Oculus.Interaction.PokeInteractable._started = false protected
Referenced by Oculus.Interaction.PokeInteractable.OnDisable(), Oculus.Interaction.PokeInteractable.OnEnable(), and Oculus.Interaction.PokeInteractable.Start().
ProximityField
IProximityField Oculus.Interaction.PokeInteractable.ProximityField
Referenced by Oculus.Interaction.PokeInteractable.Awake(), Oculus.Interaction.PokeInteractable.ComputeClosestPoint(), Oculus.Interaction.PokeInteractable.InjectProximityField(), and Oculus.Interaction.PokeInteractable.Start().
Surface
IPointableSurface Oculus.Interaction.PokeInteractable.Surface
Referenced by Oculus.Interaction.PokeInteractor.DoSelectUpdate().
Property Documentation
EnterHoverDistance
float Oculus.Interaction.PokeInteractable.EnterHoverDistance get
HorizontalDragThreshold
float Oculus.Interaction.PokeInteractable.HorizontalDragThreshold get
MaxDistance
float Oculus.Interaction.PokeInteractable.MaxDistance get
Referenced by Oculus.Interaction.Editor.PokeInteractableEditor.OnSceneGUI().
ReleaseDistance
float Oculus.Interaction.PokeInteractable.ReleaseDistance get
Referenced by Oculus.Interaction.PokeInteractor.DoSelectUpdate().
VerticalDragThreshold
float Oculus.Interaction.PokeInteractable.VerticalDragThreshold get
VolumeMask
Collider Oculus.Interaction.PokeInteractable.VolumeMask get
Event Documentation
OnPointerEvent
Action<PointerArgs> Oculus.Interaction.PokeInteractable.OnPointerEvent = delegate { }
The documentation for this class was generated from the following file:
C:/Users/Lykos/Desktop/Projects/Capstone/VRGames/Assets/ThirdParty/Oculus/Interaction/Runtime/Scripts/Interaction/Models/Poke/PokeInteractable.cs