VRGames: Oculus.Interaction.Input.HandJointUtils Class Reference
Oculus.Interaction.Input.HandJointUtils Class Reference
Static Public Member Functions
static HandJointId GetHandFingerTip (HandFinger finger)
static HandJointId GetHandFingerProximal (HandFinger finger)
Returns the "proximal" JointId for the given finger. This is commonly known as the Knuckle. For fingers, proximal is the join with index 1; eg HandIndex1. For thumb, proximal is the joint with index 2; eg HandThumb2.
Static Public Attributes
static List< HandJointId[]> FingerToJointList
static List< HandJointId > JointIds
Member Function Documentation
GetHandFingerProximal()
static HandJointId Oculus.Interaction.Input.HandJointUtils.GetHandFingerProximal (HandFinger finger) static
Returns the "proximal" JointId for the given finger. This is commonly known as the Knuckle. For fingers, proximal is the join with index 1; eg HandIndex1. For thumb, proximal is the joint with index 2; eg HandThumb2.
Referenced by Oculus.Interaction.PoseDetection.FingerShapes.GetAbductionValue().
GetHandFingerTip()
static HandJointId Oculus.Interaction.Input.HandJointUtils.GetHandFingerTip (HandFinger finger) static
Referenced by Oculus.Interaction.PoseDetection.FingerShapes.GetAbductionValue(), and Oculus.Interaction.PoseDetection.FingerShapes.GetOppositionValue().
Member Data Documentation
FingerToJointList
List<HandJointId[]> Oculus.Interaction.Input.HandJointUtils.FingerToJointList static
Initial value:
= new List<HandJointId[]>()
        {
            new[] {HandJointId.HandThumb0,HandJointId.HandThumb1,HandJointId.HandThumb2,HandJointId.HandThumb3},
            new[] {HandJointId.HandIndex1, HandJointId.HandIndex2, HandJointId.HandIndex3},
            new[] {HandJointId.HandMiddle1, HandJointId.HandMiddle2, HandJointId.HandMiddle3},
            new[] {HandJointId.HandRing1,HandJointId.HandRing2,HandJointId.HandRing3},
            new[] {HandJointId.HandPinky0, HandJointId.HandPinky1, HandJointId.HandPinky2, HandJointId.HandPinky3}
        }
JointIds
List<HandJointId> Oculus.Interaction.Input.HandJointUtils.JointIds static
Initial value:
= new List<HandJointId>()
        {
            HandJointId.HandIndex1,
            HandJointId.HandIndex2,
            HandJointId.HandIndex3,
            HandJointId.HandMiddle1,
            HandJointId.HandMiddle2,
            HandJointId.HandMiddle3,
            HandJointId.HandRing1,
            HandJointId.HandRing2,
            HandJointId.HandRing3,
            HandJointId.HandPinky0,
            HandJointId.HandPinky1,
            HandJointId.HandPinky2,
            HandJointId.HandPinky3,
            HandJointId.HandThumb0,
            HandJointId.HandThumb1,
            HandJointId.HandThumb2,
            HandJointId.HandThumb3
        }
The documentation for this class was generated from the following file:
C:/Users/Lykos/Desktop/Projects/Capstone/VRGames/Assets/ThirdParty/Oculus/Interaction/Runtime/Scripts/Input/Hands/HandPrimitives.cs