VRGames: UnityEngine.UI.ClipperRegistry Class Reference
UnityEngine.UI.ClipperRegistry Class Reference
Registry class to keep track of all IClippers that exist in the scene.
Public Member Functions
void Cull ()
Perform the clipping on all registered IClipper.
Static Public Member Functions
static void Register (IClipper c)
Register a unique IClipper element.
static void Unregister (IClipper c)
UnRegister a IClipper element.
static void Disable (IClipper c)
Disable a IClipper element.
Protected Member Functions
ClipperRegistry ()
Properties
static ClipperRegistry instance [get]
The singleton instance of the clipper registry.
Detailed Description
Registry class to keep track of all IClippers that exist in the scene.
This is used during the CanvasUpdate loop to cull clippable elements. The clipping is called after layout, but before Graphic update.
Constructor & Destructor Documentation
ClipperRegistry()
UnityEngine.UI.ClipperRegistry.ClipperRegistry () protected
Member Function Documentation
Cull()
void UnityEngine.UI.ClipperRegistry.Cull ()
Perform the clipping on all registered IClipper.
Disable()
static void UnityEngine.UI.ClipperRegistry.Disable (IClipper c) static
Disable a IClipper element.
Parameters
c The Element to try and disable.
Referenced by UnityEngine.UI.RectMask2D.OnDisable().
Register()
static void UnityEngine.UI.ClipperRegistry.Register (IClipper c) static
Register a unique IClipper element.
Parameters
c The clipper element to add
Referenced by UnityEngine.UI.RectMask2D.OnEnable().
Unregister()
static void UnityEngine.UI.ClipperRegistry.Unregister (IClipper c) static
UnRegister a IClipper element.
Parameters
c The Element to try and remove.
Referenced by UnityEngine.UI.RectMask2D.OnDestroy().
Property Documentation
instance
ClipperRegistry UnityEngine.UI.ClipperRegistry.instance static get
The singleton instance of the clipper registry.
Referenced by UnityEngine.UI.ClipperRegistry.Disable(), UnityEngine.UI.ClipperRegistry.Register(), and UnityEngine.UI.ClipperRegistry.Unregister().
The documentation for this class was generated from the following file:
C:/Users/Lykos/Desktop/Projects/Capstone/VRGames/Library/PackageCache/com.unity.ugui@1.0.0/Runtime/UI/Core/Culling/ClipperRegistry.cs