VRGames: UnityEditor.ProBuilder.ProBuilderShapeEditor Class Reference
UnityEditor.ProBuilder.ProBuilderShapeEditor Class Reference
Public Member Functions
override void OnInspectorGUI ()
void DrawShapeGUI (DrawShapeTool tool=null)
void DrawShapeParametersGUI (DrawShapeTool tool=null)
Public Attributes
GUIContent m_ShapePropertyLabel = new GUIContent("Shape Properties")
Member Function Documentation
DrawShapeGUI()
void UnityEditor.ProBuilder.ProBuilderShapeEditor.DrawShapeGUI (DrawShapeTool tool = null)
Referenced by UnityEditor.ProBuilder.ProBuilderShapeEditor.OnInspectorGUI().
DrawShapeParametersGUI()
void UnityEditor.ProBuilder.ProBuilderShapeEditor.DrawShapeParametersGUI (DrawShapeTool tool = null)
Referenced by UnityEditor.ProBuilder.ProBuilderShapeEditor.OnInspectorGUI().
OnInspectorGUI()
override void UnityEditor.ProBuilder.ProBuilderShapeEditor.OnInspectorGUI ()
Member Data Documentation
m_ShapePropertyLabel
GUIContent UnityEditor.ProBuilder.ProBuilderShapeEditor.m_ShapePropertyLabel = new GUIContent("Shape Properties")
Referenced by UnityEditor.ProBuilder.ProBuilderShapeEditor.DrawShapeParametersGUI().
The documentation for this class was generated from the following file:
C:/Users/Lykos/Desktop/Projects/Capstone/VRGames/Library/PackageCache/com.unity.probuilder@5.0.6/Editor/EditorCore/ProBuilderShapeEditor.cs