VRGames: OVR.OpenVR.OpenVR Class Reference
OVR.OpenVR.OpenVR Class Reference
Static Public Member Functions
static uint InitInternal (ref EVRInitError peError, EVRApplicationType eApplicationType)
static uint InitInternal2 (ref EVRInitError peError, EVRApplicationType eApplicationType, string pchStartupInfo)
static void ShutdownInternal ()
static bool IsHmdPresent ()
static bool IsRuntimeInstalled ()
static string GetStringForHmdError (EVRInitError error)
static IntPtr GetGenericInterface (string pchInterfaceVersion, ref EVRInitError peError)
static bool IsInterfaceVersionValid (string pchInterfaceVersion)
static uint GetInitToken ()
static CVRSystem Init (ref EVRInitError peError, EVRApplicationType eApplicationType=EVRApplicationType.VRApplication_Scene, string pchStartupInfo="")
static void Shutdown ()
Static Public Attributes
const uint k_nDriverNone = 4294967295
const uint k_unMaxDriverDebugResponseSize = 32768
const uint k_unTrackedDeviceIndex_Hmd = 0
const uint k_unMaxTrackedDeviceCount = 64
const uint k_unTrackedDeviceIndexOther = 4294967294
const uint k_unTrackedDeviceIndexInvalid = 4294967295
const ulong k_ulInvalidPropertyContainer = 0
const uint k_unInvalidPropertyTag = 0
const ulong k_ulInvalidDriverHandle = 0
const uint k_unFloatPropertyTag = 1
const uint k_unInt32PropertyTag = 2
const uint k_unUint64PropertyTag = 3
const uint k_unBoolPropertyTag = 4
const uint k_unStringPropertyTag = 5
const uint k_unHmdMatrix34PropertyTag = 20
const uint k_unHmdMatrix44PropertyTag = 21
const uint k_unHmdVector3PropertyTag = 22
const uint k_unHmdVector4PropertyTag = 23
const uint k_unHiddenAreaPropertyTag = 30
const uint k_unPathHandleInfoTag = 31
const uint k_unActionPropertyTag = 32
const uint k_unInputValuePropertyTag = 33
const uint k_unWildcardPropertyTag = 34
const uint k_unHapticVibrationPropertyTag = 35
const uint k_unSkeletonPropertyTag = 36
const uint k_unSpatialAnchorPosePropertyTag = 40
const uint k_unOpenVRInternalReserved_Start = 1000
const uint k_unOpenVRInternalReserved_End = 10000
const uint k_unMaxPropertyStringSize = 32768
const ulong k_ulInvalidActionHandle = 0
const ulong k_ulInvalidActionSetHandle = 0
const ulong k_ulInvalidInputValueHandle = 0
const uint k_unControllerStateAxisCount = 5
const ulong k_ulOverlayHandleInvalid = 0
const uint k_unScreenshotHandleInvalid = 0
const string IVRSystem_Version = "IVRSystem_019"
const string IVRExtendedDisplay_Version = "IVRExtendedDisplay_001"
const string IVRTrackedCamera_Version = "IVRTrackedCamera_003"
const uint k_unMaxApplicationKeyLength = 128
const string k_pch_MimeType_HomeApp = "vr/home"
const string k_pch_MimeType_GameTheater = "vr/game_theater"
const string IVRApplications_Version = "IVRApplications_006"
const string IVRChaperone_Version = "IVRChaperone_003"
const string IVRChaperoneSetup_Version = "IVRChaperoneSetup_005"
const string IVRCompositor_Version = "IVRCompositor_022"
const uint k_unVROverlayMaxKeyLength = 128
const uint k_unVROverlayMaxNameLength = 128
const uint k_unMaxOverlayCount = 64
const uint k_unMaxOverlayIntersectionMaskPrimitivesCount = 32
const string IVROverlay_Version = "IVROverlay_018"
const string k_pch_Controller_Component_GDC2015 = "gdc2015"
const string k_pch_Controller_Component_Base = "base"
const string k_pch_Controller_Component_Tip = "tip"
const string k_pch_Controller_Component_HandGrip = "handgrip"
const string k_pch_Controller_Component_Status = "status"
const string IVRRenderModels_Version = "IVRRenderModels_006"
const uint k_unNotificationTextMaxSize = 256
const string IVRNotifications_Version = "IVRNotifications_002"
const uint k_unMaxSettingsKeyLength = 128
const string IVRSettings_Version = "IVRSettings_002"
const string k_pch_SteamVR_Section = "steamvr"
const string k_pch_SteamVR_RequireHmd_String = "requireHmd"
const string k_pch_SteamVR_ForcedDriverKey_String = "forcedDriver"
const string k_pch_SteamVR_ForcedHmdKey_String = "forcedHmd"
const string k_pch_SteamVR_DisplayDebug_Bool = "displayDebug"
const string k_pch_SteamVR_DebugProcessPipe_String = "debugProcessPipe"
const string k_pch_SteamVR_DisplayDebugX_Int32 = "displayDebugX"
const string k_pch_SteamVR_DisplayDebugY_Int32 = "displayDebugY"
const string k_pch_SteamVR_SendSystemButtonToAllApps_Bool = "sendSystemButtonToAllApps"
const string k_pch_SteamVR_LogLevel_Int32 = "loglevel"
const string k_pch_SteamVR_IPD_Float = "ipd"
const string k_pch_SteamVR_Background_String = "background"
const string k_pch_SteamVR_BackgroundUseDomeProjection_Bool = "backgroundUseDomeProjection"
const string k_pch_SteamVR_BackgroundCameraHeight_Float = "backgroundCameraHeight"
const string k_pch_SteamVR_BackgroundDomeRadius_Float = "backgroundDomeRadius"
const string k_pch_SteamVR_GridColor_String = "gridColor"
const string k_pch_SteamVR_PlayAreaColor_String = "playAreaColor"
const string k_pch_SteamVR_ShowStage_Bool = "showStage"
const string k_pch_SteamVR_ActivateMultipleDrivers_Bool = "activateMultipleDrivers"
const string k_pch_SteamVR_DirectMode_Bool = "directMode"
const string k_pch_SteamVR_DirectModeEdidVid_Int32 = "directModeEdidVid"
const string k_pch_SteamVR_DirectModeEdidPid_Int32 = "directModeEdidPid"
const string k_pch_SteamVR_UsingSpeakers_Bool = "usingSpeakers"
const string k_pch_SteamVR_SpeakersForwardYawOffsetDegrees_Float = "speakersForwardYawOffsetDegrees"
const string k_pch_SteamVR_BaseStationPowerManagement_Bool = "basestationPowerManagement"
const string k_pch_SteamVR_NeverKillProcesses_Bool = "neverKillProcesses"
const string k_pch_SteamVR_SupersampleScale_Float = "supersampleScale"
const string k_pch_SteamVR_AllowAsyncReprojection_Bool = "allowAsyncReprojection"
const string k_pch_SteamVR_AllowReprojection_Bool = "allowInterleavedReprojection"
const string k_pch_SteamVR_ForceReprojection_Bool = "forceReprojection"
const string k_pch_SteamVR_ForceFadeOnBadTracking_Bool = "forceFadeOnBadTracking"
const string k_pch_SteamVR_DefaultMirrorView_Int32 = "defaultMirrorView"
const string k_pch_SteamVR_ShowMirrorView_Bool = "showMirrorView"
const string k_pch_SteamVR_MirrorViewGeometry_String = "mirrorViewGeometry"
const string k_pch_SteamVR_StartMonitorFromAppLaunch = "startMonitorFromAppLaunch"
const string k_pch_SteamVR_StartCompositorFromAppLaunch_Bool = "startCompositorFromAppLaunch"
const string k_pch_SteamVR_StartDashboardFromAppLaunch_Bool = "startDashboardFromAppLaunch"
const string k_pch_SteamVR_StartOverlayAppsFromDashboard_Bool = "startOverlayAppsFromDashboard"
const string k_pch_SteamVR_EnableHomeApp = "enableHomeApp"
const string k_pch_SteamVR_CycleBackgroundImageTimeSec_Int32 = "CycleBackgroundImageTimeSec"
const string k_pch_SteamVR_RetailDemo_Bool = "retailDemo"
const string k_pch_SteamVR_IpdOffset_Float = "ipdOffset"
const string k_pch_SteamVR_AllowSupersampleFiltering_Bool = "allowSupersampleFiltering"
const string k_pch_SteamVR_SupersampleManualOverride_Bool = "supersampleManualOverride"
const string k_pch_SteamVR_EnableLinuxVulkanAsync_Bool = "enableLinuxVulkanAsync"
const string k_pch_SteamVR_AllowDisplayLockedMode_Bool = "allowDisplayLockedMode"
const string k_pch_SteamVR_HaveStartedTutorialForNativeChaperoneDriver_Bool = "haveStartedTutorialForNativeChaperoneDriver"
const string k_pch_SteamVR_ForceWindows32bitVRMonitor = "forceWindows32BitVRMonitor"
const string k_pch_SteamVR_DebugInput = "debugInput"
const string k_pch_SteamVR_LegacyInputRebinding = "legacyInputRebinding"
const string k_pch_SteamVR_DebugInputBinding = "debugInputBinding"
const string k_pch_SteamVR_InputBindingUIBlock = "inputBindingUI"
const string k_pch_SteamVR_RenderCameraMode = "renderCameraMode"
const string k_pch_Lighthouse_Section = "driver_lighthouse"
const string k_pch_Lighthouse_DisableIMU_Bool = "disableimu"
const string k_pch_Lighthouse_DisableIMUExceptHMD_Bool = "disableimuexcepthmd"
const string k_pch_Lighthouse_UseDisambiguation_String = "usedisambiguation"
const string k_pch_Lighthouse_DisambiguationDebug_Int32 = "disambiguationdebug"
const string k_pch_Lighthouse_PrimaryBasestation_Int32 = "primarybasestation"
const string k_pch_Lighthouse_DBHistory_Bool = "dbhistory"
const string k_pch_Lighthouse_EnableBluetooth_Bool = "enableBluetooth"
const string k_pch_Lighthouse_PowerManagedBaseStations_String = "PowerManagedBaseStations"
const string k_pch_Null_Section = "driver_null"
const string k_pch_Null_SerialNumber_String = "serialNumber"
const string k_pch_Null_ModelNumber_String = "modelNumber"
const string k_pch_Null_WindowX_Int32 = "windowX"
const string k_pch_Null_WindowY_Int32 = "windowY"
const string k_pch_Null_WindowWidth_Int32 = "windowWidth"
const string k_pch_Null_WindowHeight_Int32 = "windowHeight"
const string k_pch_Null_RenderWidth_Int32 = "renderWidth"
const string k_pch_Null_RenderHeight_Int32 = "renderHeight"
const string k_pch_Null_SecondsFromVsyncToPhotons_Float = "secondsFromVsyncToPhotons"
const string k_pch_Null_DisplayFrequency_Float = "displayFrequency"
const string k_pch_UserInterface_Section = "userinterface"
const string k_pch_UserInterface_StatusAlwaysOnTop_Bool = "StatusAlwaysOnTop"
const string k_pch_UserInterface_MinimizeToTray_Bool = "MinimizeToTray"
const string k_pch_UserInterface_Screenshots_Bool = "screenshots"
const string k_pch_UserInterface_ScreenshotType_Int = "screenshotType"
const string k_pch_Notifications_Section = "notifications"
const string k_pch_Notifications_DoNotDisturb_Bool = "DoNotDisturb"
const string k_pch_Keyboard_Section = "keyboard"
const string k_pch_Keyboard_TutorialCompletions = "TutorialCompletions"
const string k_pch_Keyboard_ScaleX = "ScaleX"
const string k_pch_Keyboard_ScaleY = "ScaleY"
const string k_pch_Keyboard_OffsetLeftX = "OffsetLeftX"
const string k_pch_Keyboard_OffsetRightX = "OffsetRightX"
const string k_pch_Keyboard_OffsetY = "OffsetY"
const string k_pch_Keyboard_Smoothing = "Smoothing"
const string k_pch_Perf_Section = "perfcheck"
const string k_pch_Perf_HeuristicActive_Bool = "heuristicActive"
const string k_pch_Perf_NotifyInHMD_Bool = "warnInHMD"
const string k_pch_Perf_NotifyOnlyOnce_Bool = "warnOnlyOnce"
const string k_pch_Perf_AllowTimingStore_Bool = "allowTimingStore"
const string k_pch_Perf_SaveTimingsOnExit_Bool = "saveTimingsOnExit"
const string k_pch_Perf_TestData_Float = "perfTestData"
const string k_pch_Perf_LinuxGPUProfiling_Bool = "linuxGPUProfiling"
const string k_pch_CollisionBounds_Section = "collisionBounds"
const string k_pch_CollisionBounds_Style_Int32 = "CollisionBoundsStyle"
const string k_pch_CollisionBounds_GroundPerimeterOn_Bool = "CollisionBoundsGroundPerimeterOn"
const string k_pch_CollisionBounds_CenterMarkerOn_Bool = "CollisionBoundsCenterMarkerOn"
const string k_pch_CollisionBounds_PlaySpaceOn_Bool = "CollisionBoundsPlaySpaceOn"
const string k_pch_CollisionBounds_FadeDistance_Float = "CollisionBoundsFadeDistance"
const string k_pch_CollisionBounds_ColorGammaR_Int32 = "CollisionBoundsColorGammaR"
const string k_pch_CollisionBounds_ColorGammaG_Int32 = "CollisionBoundsColorGammaG"
const string k_pch_CollisionBounds_ColorGammaB_Int32 = "CollisionBoundsColorGammaB"
const string k_pch_CollisionBounds_ColorGammaA_Int32 = "CollisionBoundsColorGammaA"
const string k_pch_Camera_Section = "camera"
const string k_pch_Camera_EnableCamera_Bool = "enableCamera"
const string k_pch_Camera_EnableCameraInDashboard_Bool = "enableCameraInDashboard"
const string k_pch_Camera_EnableCameraForCollisionBounds_Bool = "enableCameraForCollisionBounds"
const string k_pch_Camera_EnableCameraForRoomView_Bool = "enableCameraForRoomView"
const string k_pch_Camera_BoundsColorGammaR_Int32 = "cameraBoundsColorGammaR"
const string k_pch_Camera_BoundsColorGammaG_Int32 = "cameraBoundsColorGammaG"
const string k_pch_Camera_BoundsColorGammaB_Int32 = "cameraBoundsColorGammaB"
const string k_pch_Camera_BoundsColorGammaA_Int32 = "cameraBoundsColorGammaA"
const string k_pch_Camera_BoundsStrength_Int32 = "cameraBoundsStrength"
const string k_pch_Camera_RoomViewMode_Int32 = "cameraRoomViewMode"
const string k_pch_audio_Section = "audio"
const string k_pch_audio_OnPlaybackDevice_String = "onPlaybackDevice"
const string k_pch_audio_OnRecordDevice_String = "onRecordDevice"
const string k_pch_audio_OnPlaybackMirrorDevice_String = "onPlaybackMirrorDevice"
const string k_pch_audio_OffPlaybackDevice_String = "offPlaybackDevice"
const string k_pch_audio_OffRecordDevice_String = "offRecordDevice"
const string k_pch_audio_VIVEHDMIGain = "viveHDMIGain"
const string k_pch_Power_Section = "power"
const string k_pch_Power_PowerOffOnExit_Bool = "powerOffOnExit"
const string k_pch_Power_TurnOffScreensTimeout_Float = "turnOffScreensTimeout"
const string k_pch_Power_TurnOffControllersTimeout_Float = "turnOffControllersTimeout"
const string k_pch_Power_ReturnToWatchdogTimeout_Float = "returnToWatchdogTimeout"
const string k_pch_Power_AutoLaunchSteamVROnButtonPress = "autoLaunchSteamVROnButtonPress"
const string k_pch_Power_PauseCompositorOnStandby_Bool = "pauseCompositorOnStandby"
const string k_pch_Dashboard_Section = "dashboard"
const string k_pch_Dashboard_EnableDashboard_Bool = "enableDashboard"
const string k_pch_Dashboard_ArcadeMode_Bool = "arcadeMode"
const string k_pch_Dashboard_EnableWebUI = "webUI"
const string k_pch_Dashboard_EnableWebUIDevTools = "webUIDevTools"
const string k_pch_Dashboard_EnableWebUIDashboardReplacement = "webUIDashboard"
const string k_pch_modelskin_Section = "modelskins"
const string k_pch_Driver_Enable_Bool = "enable"
const string k_pch_WebInterface_Section = "WebInterface"
const string k_pch_WebInterface_WebEnable_Bool = "WebEnable"
const string k_pch_WebInterface_WebPort_String = "WebPort"
const string k_pch_TrackingOverride_Section = "TrackingOverrides"
const string k_pch_App_BindingAutosaveURLSuffix_String = "AutosaveURL"
const string k_pch_App_BindingCurrentURLSuffix_String = "CurrentURL"
const string k_pch_App_NeedToUpdateAutosaveSuffix_Bool = "NeedToUpdateAutosave"
const string k_pch_App_ActionManifestURL_String = "ActionManifestURL"
const string k_pch_Trackers_Section = "trackers"
const string IVRScreenshots_Version = "IVRScreenshots_001"
const string IVRResources_Version = "IVRResources_001"
const string IVRDriverManager_Version = "IVRDriverManager_001"
const uint k_unMaxActionNameLength = 64
const uint k_unMaxActionSetNameLength = 64
const uint k_unMaxActionOriginCount = 16
const string IVRInput_Version = "IVRInput_004"
const ulong k_ulInvalidIOBufferHandle = 0
const string IVRIOBuffer_Version = "IVRIOBuffer_001"
const uint k_ulInvalidSpatialAnchorHandle = 0
const string IVRSpatialAnchors_Version = "IVRSpatialAnchors_001"
Properties
static CVRSystem System [get]
static CVRChaperone Chaperone [get]
static CVRChaperoneSetup ChaperoneSetup [get]
static CVRCompositor Compositor [get]
static CVROverlay Overlay [get]
static CVRRenderModels RenderModels [get]
static CVRExtendedDisplay ExtendedDisplay [get]
static CVRSettings Settings [get]
static CVRApplications Applications [get]
static CVRScreenshots Screenshots [get]
static CVRTrackedCamera TrackedCamera [get]
static CVRInput Input [get]
static CVRSpatialAnchors SpatialAnchors [get]
Member Function Documentation
GetGenericInterface()
static IntPtr OVR.OpenVR.OpenVR.GetGenericInterface (string pchInterfaceVersion, ref EVRInitError peError) static
GetInitToken()
static uint OVR.OpenVR.OpenVR.GetInitToken () static
GetStringForHmdError()
static string OVR.OpenVR.OpenVR.GetStringForHmdError (EVRInitError error) static
Init()
static CVRSystem OVR.OpenVR.OpenVR.Init (ref EVRInitError peError, EVRApplicationType eApplicationType = EVRApplicationType::VRApplication_Scene, string pchStartupInfo = "") static
Finds the active installation of vrclient.dll and initializes it
InitInternal()
static uint OVR.OpenVR.OpenVR.InitInternal (ref EVRInitError peError, EVRApplicationType eApplicationType) static
Referenced by OVR.OpenVR.OpenVR.Init().
InitInternal2()
static uint OVR.OpenVR.OpenVR.InitInternal2 (ref EVRInitError peError, EVRApplicationType eApplicationType, string pchStartupInfo) static
Referenced by OVR.OpenVR.OpenVR.Init().
IsHmdPresent()
static bool OVR.OpenVR.OpenVR.IsHmdPresent () static
IsInterfaceVersionValid()
static bool OVR.OpenVR.OpenVR.IsInterfaceVersionValid (string pchInterfaceVersion) static
Referenced by OVR.OpenVR.OpenVR.Init().
IsRuntimeInstalled()
static bool OVR.OpenVR.OpenVR.IsRuntimeInstalled () static
Shutdown()
static void OVR.OpenVR.OpenVR.Shutdown () static
unloads vrclient.dll. Any interface pointers from the interface are invalid after this point
ShutdownInternal()
static void OVR.OpenVR.OpenVR.ShutdownInternal () static
Referenced by OVR.OpenVR.OpenVR.Init(), and OVR.OpenVR.OpenVR.Shutdown().
Member Data Documentation
IVRApplications_Version
const string OVR.OpenVR.OpenVR.IVRApplications_Version = "IVRApplications_006" static
IVRChaperone_Version
const string OVR.OpenVR.OpenVR.IVRChaperone_Version = "IVRChaperone_003" static
IVRChaperoneSetup_Version
const string OVR.OpenVR.OpenVR.IVRChaperoneSetup_Version = "IVRChaperoneSetup_005" static
IVRCompositor_Version
const string OVR.OpenVR.OpenVR.IVRCompositor_Version = "IVRCompositor_022" static
IVRDriverManager_Version
const string OVR.OpenVR.OpenVR.IVRDriverManager_Version = "IVRDriverManager_001" static
IVRExtendedDisplay_Version
const string OVR.OpenVR.OpenVR.IVRExtendedDisplay_Version = "IVRExtendedDisplay_001" static
IVRInput_Version
const string OVR.OpenVR.OpenVR.IVRInput_Version = "IVRInput_004" static
IVRIOBuffer_Version
const string OVR.OpenVR.OpenVR.IVRIOBuffer_Version = "IVRIOBuffer_001" static
IVRNotifications_Version
const string OVR.OpenVR.OpenVR.IVRNotifications_Version = "IVRNotifications_002" static
IVROverlay_Version
const string OVR.OpenVR.OpenVR.IVROverlay_Version = "IVROverlay_018" static
IVRRenderModels_Version
const string OVR.OpenVR.OpenVR.IVRRenderModels_Version = "IVRRenderModels_006" static
IVRResources_Version
const string OVR.OpenVR.OpenVR.IVRResources_Version = "IVRResources_001" static
IVRScreenshots_Version
const string OVR.OpenVR.OpenVR.IVRScreenshots_Version = "IVRScreenshots_001" static
IVRSettings_Version
const string OVR.OpenVR.OpenVR.IVRSettings_Version = "IVRSettings_002" static
IVRSpatialAnchors_Version
const string OVR.OpenVR.OpenVR.IVRSpatialAnchors_Version = "IVRSpatialAnchors_001" static
IVRSystem_Version
const string OVR.OpenVR.OpenVR.IVRSystem_Version = "IVRSystem_019" static
Referenced by OVR.OpenVR.OpenVR.Init().
IVRTrackedCamera_Version
const string OVR.OpenVR.OpenVR.IVRTrackedCamera_Version = "IVRTrackedCamera_003" static
k_nDriverNone
const uint OVR.OpenVR.OpenVR.k_nDriverNone = 4294967295 static
k_pch_App_ActionManifestURL_String
const string OVR.OpenVR.OpenVR.k_pch_App_ActionManifestURL_String = "ActionManifestURL" static
k_pch_App_BindingAutosaveURLSuffix_String
const string OVR.OpenVR.OpenVR.k_pch_App_BindingAutosaveURLSuffix_String = "AutosaveURL" static
k_pch_App_BindingCurrentURLSuffix_String
const string OVR.OpenVR.OpenVR.k_pch_App_BindingCurrentURLSuffix_String = "CurrentURL" static
k_pch_App_NeedToUpdateAutosaveSuffix_Bool
const string OVR.OpenVR.OpenVR.k_pch_App_NeedToUpdateAutosaveSuffix_Bool = "NeedToUpdateAutosave" static
k_pch_audio_OffPlaybackDevice_String
const string OVR.OpenVR.OpenVR.k_pch_audio_OffPlaybackDevice_String = "offPlaybackDevice" static
k_pch_audio_OffRecordDevice_String
const string OVR.OpenVR.OpenVR.k_pch_audio_OffRecordDevice_String = "offRecordDevice" static
k_pch_audio_OnPlaybackDevice_String
const string OVR.OpenVR.OpenVR.k_pch_audio_OnPlaybackDevice_String = "onPlaybackDevice" static
k_pch_audio_OnPlaybackMirrorDevice_String
const string OVR.OpenVR.OpenVR.k_pch_audio_OnPlaybackMirrorDevice_String = "onPlaybackMirrorDevice" static
k_pch_audio_OnRecordDevice_String
const string OVR.OpenVR.OpenVR.k_pch_audio_OnRecordDevice_String = "onRecordDevice" static
k_pch_audio_Section
const string OVR.OpenVR.OpenVR.k_pch_audio_Section = "audio" static
k_pch_audio_VIVEHDMIGain
const string OVR.OpenVR.OpenVR.k_pch_audio_VIVEHDMIGain = "viveHDMIGain" static
k_pch_Camera_BoundsColorGammaA_Int32
const string OVR.OpenVR.OpenVR.k_pch_Camera_BoundsColorGammaA_Int32 = "cameraBoundsColorGammaA" static
k_pch_Camera_BoundsColorGammaB_Int32
const string OVR.OpenVR.OpenVR.k_pch_Camera_BoundsColorGammaB_Int32 = "cameraBoundsColorGammaB" static
k_pch_Camera_BoundsColorGammaG_Int32
const string OVR.OpenVR.OpenVR.k_pch_Camera_BoundsColorGammaG_Int32 = "cameraBoundsColorGammaG" static
k_pch_Camera_BoundsColorGammaR_Int32
const string OVR.OpenVR.OpenVR.k_pch_Camera_BoundsColorGammaR_Int32 = "cameraBoundsColorGammaR" static
k_pch_Camera_BoundsStrength_Int32
const string OVR.OpenVR.OpenVR.k_pch_Camera_BoundsStrength_Int32 = "cameraBoundsStrength" static
k_pch_Camera_EnableCamera_Bool
const string OVR.OpenVR.OpenVR.k_pch_Camera_EnableCamera_Bool = "enableCamera" static
k_pch_Camera_EnableCameraForCollisionBounds_Bool
const string OVR.OpenVR.OpenVR.k_pch_Camera_EnableCameraForCollisionBounds_Bool = "enableCameraForCollisionBounds" static
k_pch_Camera_EnableCameraForRoomView_Bool
const string OVR.OpenVR.OpenVR.k_pch_Camera_EnableCameraForRoomView_Bool = "enableCameraForRoomView" static
k_pch_Camera_EnableCameraInDashboard_Bool
const string OVR.OpenVR.OpenVR.k_pch_Camera_EnableCameraInDashboard_Bool = "enableCameraInDashboard" static
k_pch_Camera_RoomViewMode_Int32
const string OVR.OpenVR.OpenVR.k_pch_Camera_RoomViewMode_Int32 = "cameraRoomViewMode" static
k_pch_Camera_Section
const string OVR.OpenVR.OpenVR.k_pch_Camera_Section = "camera" static
k_pch_CollisionBounds_CenterMarkerOn_Bool
const string OVR.OpenVR.OpenVR.k_pch_CollisionBounds_CenterMarkerOn_Bool = "CollisionBoundsCenterMarkerOn" static
k_pch_CollisionBounds_ColorGammaA_Int32
const string OVR.OpenVR.OpenVR.k_pch_CollisionBounds_ColorGammaA_Int32 = "CollisionBoundsColorGammaA" static
k_pch_CollisionBounds_ColorGammaB_Int32
const string OVR.OpenVR.OpenVR.k_pch_CollisionBounds_ColorGammaB_Int32 = "CollisionBoundsColorGammaB" static
k_pch_CollisionBounds_ColorGammaG_Int32
const string OVR.OpenVR.OpenVR.k_pch_CollisionBounds_ColorGammaG_Int32 = "CollisionBoundsColorGammaG" static
k_pch_CollisionBounds_ColorGammaR_Int32
const string OVR.OpenVR.OpenVR.k_pch_CollisionBounds_ColorGammaR_Int32 = "CollisionBoundsColorGammaR" static
k_pch_CollisionBounds_FadeDistance_Float
const string OVR.OpenVR.OpenVR.k_pch_CollisionBounds_FadeDistance_Float = "CollisionBoundsFadeDistance" static
k_pch_CollisionBounds_GroundPerimeterOn_Bool
const string OVR.OpenVR.OpenVR.k_pch_CollisionBounds_GroundPerimeterOn_Bool = "CollisionBoundsGroundPerimeterOn" static
k_pch_CollisionBounds_PlaySpaceOn_Bool
const string OVR.OpenVR.OpenVR.k_pch_CollisionBounds_PlaySpaceOn_Bool = "CollisionBoundsPlaySpaceOn" static
k_pch_CollisionBounds_Section
const string OVR.OpenVR.OpenVR.k_pch_CollisionBounds_Section = "collisionBounds" static
k_pch_CollisionBounds_Style_Int32
const string OVR.OpenVR.OpenVR.k_pch_CollisionBounds_Style_Int32 = "CollisionBoundsStyle" static
k_pch_Controller_Component_Base
const string OVR.OpenVR.OpenVR.k_pch_Controller_Component_Base = "base" static
k_pch_Controller_Component_GDC2015
const string OVR.OpenVR.OpenVR.k_pch_Controller_Component_GDC2015 = "gdc2015" static
k_pch_Controller_Component_HandGrip
const string OVR.OpenVR.OpenVR.k_pch_Controller_Component_HandGrip = "handgrip" static
k_pch_Controller_Component_Status
const string OVR.OpenVR.OpenVR.k_pch_Controller_Component_Status = "status" static
k_pch_Controller_Component_Tip
const string OVR.OpenVR.OpenVR.k_pch_Controller_Component_Tip = "tip" static
k_pch_Dashboard_ArcadeMode_Bool
const string OVR.OpenVR.OpenVR.k_pch_Dashboard_ArcadeMode_Bool = "arcadeMode" static
k_pch_Dashboard_EnableDashboard_Bool
const string OVR.OpenVR.OpenVR.k_pch_Dashboard_EnableDashboard_Bool = "enableDashboard" static
k_pch_Dashboard_EnableWebUI
const string OVR.OpenVR.OpenVR.k_pch_Dashboard_EnableWebUI = "webUI" static
k_pch_Dashboard_EnableWebUIDashboardReplacement
const string OVR.OpenVR.OpenVR.k_pch_Dashboard_EnableWebUIDashboardReplacement = "webUIDashboard" static
k_pch_Dashboard_EnableWebUIDevTools
const string OVR.OpenVR.OpenVR.k_pch_Dashboard_EnableWebUIDevTools = "webUIDevTools" static
k_pch_Dashboard_Section
const string OVR.OpenVR.OpenVR.k_pch_Dashboard_Section = "dashboard" static
k_pch_Driver_Enable_Bool
const string OVR.OpenVR.OpenVR.k_pch_Driver_Enable_Bool = "enable" static
k_pch_Keyboard_OffsetLeftX
const string OVR.OpenVR.OpenVR.k_pch_Keyboard_OffsetLeftX = "OffsetLeftX" static
k_pch_Keyboard_OffsetRightX
const string OVR.OpenVR.OpenVR.k_pch_Keyboard_OffsetRightX = "OffsetRightX" static
k_pch_Keyboard_OffsetY
const string OVR.OpenVR.OpenVR.k_pch_Keyboard_OffsetY = "OffsetY" static
k_pch_Keyboard_ScaleX
const string OVR.OpenVR.OpenVR.k_pch_Keyboard_ScaleX = "ScaleX" static
k_pch_Keyboard_ScaleY
const string OVR.OpenVR.OpenVR.k_pch_Keyboard_ScaleY = "ScaleY" static
k_pch_Keyboard_Section
const string OVR.OpenVR.OpenVR.k_pch_Keyboard_Section = "keyboard" static
k_pch_Keyboard_Smoothing
const string OVR.OpenVR.OpenVR.k_pch_Keyboard_Smoothing = "Smoothing" static
k_pch_Keyboard_TutorialCompletions
const string OVR.OpenVR.OpenVR.k_pch_Keyboard_TutorialCompletions = "TutorialCompletions" static
k_pch_Lighthouse_DBHistory_Bool
const string OVR.OpenVR.OpenVR.k_pch_Lighthouse_DBHistory_Bool = "dbhistory" static
k_pch_Lighthouse_DisableIMU_Bool
const string OVR.OpenVR.OpenVR.k_pch_Lighthouse_DisableIMU_Bool = "disableimu" static
k_pch_Lighthouse_DisableIMUExceptHMD_Bool
const string OVR.OpenVR.OpenVR.k_pch_Lighthouse_DisableIMUExceptHMD_Bool = "disableimuexcepthmd" static
k_pch_Lighthouse_DisambiguationDebug_Int32
const string OVR.OpenVR.OpenVR.k_pch_Lighthouse_DisambiguationDebug_Int32 = "disambiguationdebug" static
k_pch_Lighthouse_EnableBluetooth_Bool
const string OVR.OpenVR.OpenVR.k_pch_Lighthouse_EnableBluetooth_Bool = "enableBluetooth" static
k_pch_Lighthouse_PowerManagedBaseStations_String
const string OVR.OpenVR.OpenVR.k_pch_Lighthouse_PowerManagedBaseStations_String = "PowerManagedBaseStations" static
k_pch_Lighthouse_PrimaryBasestation_Int32
const string OVR.OpenVR.OpenVR.k_pch_Lighthouse_PrimaryBasestation_Int32 = "primarybasestation" static
k_pch_Lighthouse_Section
const string OVR.OpenVR.OpenVR.k_pch_Lighthouse_Section = "driver_lighthouse" static
k_pch_Lighthouse_UseDisambiguation_String
const string OVR.OpenVR.OpenVR.k_pch_Lighthouse_UseDisambiguation_String = "usedisambiguation" static
k_pch_MimeType_GameTheater
const string OVR.OpenVR.OpenVR.k_pch_MimeType_GameTheater = "vr/game_theater" static
k_pch_MimeType_HomeApp
const string OVR.OpenVR.OpenVR.k_pch_MimeType_HomeApp = "vr/home" static
k_pch_modelskin_Section
const string OVR.OpenVR.OpenVR.k_pch_modelskin_Section = "modelskins" static
k_pch_Notifications_DoNotDisturb_Bool
const string OVR.OpenVR.OpenVR.k_pch_Notifications_DoNotDisturb_Bool = "DoNotDisturb" static
k_pch_Notifications_Section
const string OVR.OpenVR.OpenVR.k_pch_Notifications_Section = "notifications" static
k_pch_Null_DisplayFrequency_Float
const string OVR.OpenVR.OpenVR.k_pch_Null_DisplayFrequency_Float = "displayFrequency" static
k_pch_Null_ModelNumber_String
const string OVR.OpenVR.OpenVR.k_pch_Null_ModelNumber_String = "modelNumber" static
k_pch_Null_RenderHeight_Int32
const string OVR.OpenVR.OpenVR.k_pch_Null_RenderHeight_Int32 = "renderHeight" static
k_pch_Null_RenderWidth_Int32
const string OVR.OpenVR.OpenVR.k_pch_Null_RenderWidth_Int32 = "renderWidth" static
k_pch_Null_SecondsFromVsyncToPhotons_Float
const string OVR.OpenVR.OpenVR.k_pch_Null_SecondsFromVsyncToPhotons_Float = "secondsFromVsyncToPhotons" static
k_pch_Null_Section
const string OVR.OpenVR.OpenVR.k_pch_Null_Section = "driver_null" static
k_pch_Null_SerialNumber_String
const string OVR.OpenVR.OpenVR.k_pch_Null_SerialNumber_String = "serialNumber" static
k_pch_Null_WindowHeight_Int32
const string OVR.OpenVR.OpenVR.k_pch_Null_WindowHeight_Int32 = "windowHeight" static
k_pch_Null_WindowWidth_Int32
const string OVR.OpenVR.OpenVR.k_pch_Null_WindowWidth_Int32 = "windowWidth" static
k_pch_Null_WindowX_Int32
const string OVR.OpenVR.OpenVR.k_pch_Null_WindowX_Int32 = "windowX" static
k_pch_Null_WindowY_Int32
const string OVR.OpenVR.OpenVR.k_pch_Null_WindowY_Int32 = "windowY" static
k_pch_Perf_AllowTimingStore_Bool
const string OVR.OpenVR.OpenVR.k_pch_Perf_AllowTimingStore_Bool = "allowTimingStore" static
k_pch_Perf_HeuristicActive_Bool
const string OVR.OpenVR.OpenVR.k_pch_Perf_HeuristicActive_Bool = "heuristicActive" static
k_pch_Perf_LinuxGPUProfiling_Bool
const string OVR.OpenVR.OpenVR.k_pch_Perf_LinuxGPUProfiling_Bool = "linuxGPUProfiling" static
k_pch_Perf_NotifyInHMD_Bool
const string OVR.OpenVR.OpenVR.k_pch_Perf_NotifyInHMD_Bool = "warnInHMD" static
k_pch_Perf_NotifyOnlyOnce_Bool
const string OVR.OpenVR.OpenVR.k_pch_Perf_NotifyOnlyOnce_Bool = "warnOnlyOnce" static
k_pch_Perf_SaveTimingsOnExit_Bool
const string OVR.OpenVR.OpenVR.k_pch_Perf_SaveTimingsOnExit_Bool = "saveTimingsOnExit" static
k_pch_Perf_Section
const string OVR.OpenVR.OpenVR.k_pch_Perf_Section = "perfcheck" static
k_pch_Perf_TestData_Float
const string OVR.OpenVR.OpenVR.k_pch_Perf_TestData_Float = "perfTestData" static
k_pch_Power_AutoLaunchSteamVROnButtonPress
const string OVR.OpenVR.OpenVR.k_pch_Power_AutoLaunchSteamVROnButtonPress = "autoLaunchSteamVROnButtonPress" static
k_pch_Power_PauseCompositorOnStandby_Bool
const string OVR.OpenVR.OpenVR.k_pch_Power_PauseCompositorOnStandby_Bool = "pauseCompositorOnStandby" static
k_pch_Power_PowerOffOnExit_Bool
const string OVR.OpenVR.OpenVR.k_pch_Power_PowerOffOnExit_Bool = "powerOffOnExit" static
k_pch_Power_ReturnToWatchdogTimeout_Float
const string OVR.OpenVR.OpenVR.k_pch_Power_ReturnToWatchdogTimeout_Float = "returnToWatchdogTimeout" static
k_pch_Power_Section
const string OVR.OpenVR.OpenVR.k_pch_Power_Section = "power" static
k_pch_Power_TurnOffControllersTimeout_Float
const string OVR.OpenVR.OpenVR.k_pch_Power_TurnOffControllersTimeout_Float = "turnOffControllersTimeout" static
k_pch_Power_TurnOffScreensTimeout_Float
const string OVR.OpenVR.OpenVR.k_pch_Power_TurnOffScreensTimeout_Float = "turnOffScreensTimeout" static
k_pch_SteamVR_ActivateMultipleDrivers_Bool
const string OVR.OpenVR.OpenVR.k_pch_SteamVR_ActivateMultipleDrivers_Bool = "activateMultipleDrivers" static
k_pch_SteamVR_AllowAsyncReprojection_Bool
const string OVR.OpenVR.OpenVR.k_pch_SteamVR_AllowAsyncReprojection_Bool = "allowAsyncReprojection" static
k_pch_SteamVR_AllowDisplayLockedMode_Bool
const string OVR.OpenVR.OpenVR.k_pch_SteamVR_AllowDisplayLockedMode_Bool = "allowDisplayLockedMode" static
k_pch_SteamVR_AllowReprojection_Bool
const string OVR.OpenVR.OpenVR.k_pch_SteamVR_AllowReprojection_Bool = "allowInterleavedReprojection" static
k_pch_SteamVR_AllowSupersampleFiltering_Bool
const string OVR.OpenVR.OpenVR.k_pch_SteamVR_AllowSupersampleFiltering_Bool = "allowSupersampleFiltering" static
k_pch_SteamVR_Background_String
const string OVR.OpenVR.OpenVR.k_pch_SteamVR_Background_String = "background" static
k_pch_SteamVR_BackgroundCameraHeight_Float
const string OVR.OpenVR.OpenVR.k_pch_SteamVR_BackgroundCameraHeight_Float = "backgroundCameraHeight" static
k_pch_SteamVR_BackgroundDomeRadius_Float
const string OVR.OpenVR.OpenVR.k_pch_SteamVR_BackgroundDomeRadius_Float = "backgroundDomeRadius" static
k_pch_SteamVR_BackgroundUseDomeProjection_Bool
const string OVR.OpenVR.OpenVR.k_pch_SteamVR_BackgroundUseDomeProjection_Bool = "backgroundUseDomeProjection" static
k_pch_SteamVR_BaseStationPowerManagement_Bool
const string OVR.OpenVR.OpenVR.k_pch_SteamVR_BaseStationPowerManagement_Bool = "basestationPowerManagement" static
k_pch_SteamVR_CycleBackgroundImageTimeSec_Int32
const string OVR.OpenVR.OpenVR.k_pch_SteamVR_CycleBackgroundImageTimeSec_Int32 = "CycleBackgroundImageTimeSec" static
k_pch_SteamVR_DebugInput
const string OVR.OpenVR.OpenVR.k_pch_SteamVR_DebugInput = "debugInput" static
k_pch_SteamVR_DebugInputBinding
const string OVR.OpenVR.OpenVR.k_pch_SteamVR_DebugInputBinding = "debugInputBinding" static
k_pch_SteamVR_DebugProcessPipe_String
const string OVR.OpenVR.OpenVR.k_pch_SteamVR_DebugProcessPipe_String = "debugProcessPipe" static
k_pch_SteamVR_DefaultMirrorView_Int32
const string OVR.OpenVR.OpenVR.k_pch_SteamVR_DefaultMirrorView_Int32 = "defaultMirrorView" static
k_pch_SteamVR_DirectMode_Bool
const string OVR.OpenVR.OpenVR.k_pch_SteamVR_DirectMode_Bool = "directMode" static
k_pch_SteamVR_DirectModeEdidPid_Int32
const string OVR.OpenVR.OpenVR.k_pch_SteamVR_DirectModeEdidPid_Int32 = "directModeEdidPid" static
k_pch_SteamVR_DirectModeEdidVid_Int32
const string OVR.OpenVR.OpenVR.k_pch_SteamVR_DirectModeEdidVid_Int32 = "directModeEdidVid" static
k_pch_SteamVR_DisplayDebug_Bool
const string OVR.OpenVR.OpenVR.k_pch_SteamVR_DisplayDebug_Bool = "displayDebug" static
k_pch_SteamVR_DisplayDebugX_Int32
const string OVR.OpenVR.OpenVR.k_pch_SteamVR_DisplayDebugX_Int32 = "displayDebugX" static
k_pch_SteamVR_DisplayDebugY_Int32
const string OVR.OpenVR.OpenVR.k_pch_SteamVR_DisplayDebugY_Int32 = "displayDebugY" static
k_pch_SteamVR_EnableHomeApp
const string OVR.OpenVR.OpenVR.k_pch_SteamVR_EnableHomeApp = "enableHomeApp" static
k_pch_SteamVR_EnableLinuxVulkanAsync_Bool
const string OVR.OpenVR.OpenVR.k_pch_SteamVR_EnableLinuxVulkanAsync_Bool = "enableLinuxVulkanAsync" static
k_pch_SteamVR_ForcedDriverKey_String
const string OVR.OpenVR.OpenVR.k_pch_SteamVR_ForcedDriverKey_String = "forcedDriver" static
k_pch_SteamVR_ForcedHmdKey_String
const string OVR.OpenVR.OpenVR.k_pch_SteamVR_ForcedHmdKey_String = "forcedHmd" static
k_pch_SteamVR_ForceFadeOnBadTracking_Bool
const string OVR.OpenVR.OpenVR.k_pch_SteamVR_ForceFadeOnBadTracking_Bool = "forceFadeOnBadTracking" static
k_pch_SteamVR_ForceReprojection_Bool
const string OVR.OpenVR.OpenVR.k_pch_SteamVR_ForceReprojection_Bool = "forceReprojection" static
k_pch_SteamVR_ForceWindows32bitVRMonitor
const string OVR.OpenVR.OpenVR.k_pch_SteamVR_ForceWindows32bitVRMonitor = "forceWindows32BitVRMonitor" static
k_pch_SteamVR_GridColor_String
const string OVR.OpenVR.OpenVR.k_pch_SteamVR_GridColor_String = "gridColor" static
k_pch_SteamVR_HaveStartedTutorialForNativeChaperoneDriver_Bool
const string OVR.OpenVR.OpenVR.k_pch_SteamVR_HaveStartedTutorialForNativeChaperoneDriver_Bool = "haveStartedTutorialForNativeChaperoneDriver" static
k_pch_SteamVR_InputBindingUIBlock
const string OVR.OpenVR.OpenVR.k_pch_SteamVR_InputBindingUIBlock = "inputBindingUI" static
k_pch_SteamVR_IPD_Float
const string OVR.OpenVR.OpenVR.k_pch_SteamVR_IPD_Float = "ipd" static
k_pch_SteamVR_IpdOffset_Float
const string OVR.OpenVR.OpenVR.k_pch_SteamVR_IpdOffset_Float = "ipdOffset" static
k_pch_SteamVR_LegacyInputRebinding
const string OVR.OpenVR.OpenVR.k_pch_SteamVR_LegacyInputRebinding = "legacyInputRebinding" static
k_pch_SteamVR_LogLevel_Int32
const string OVR.OpenVR.OpenVR.k_pch_SteamVR_LogLevel_Int32 = "loglevel" static
k_pch_SteamVR_MirrorViewGeometry_String
const string OVR.OpenVR.OpenVR.k_pch_SteamVR_MirrorViewGeometry_String = "mirrorViewGeometry" static
k_pch_SteamVR_NeverKillProcesses_Bool
const string OVR.OpenVR.OpenVR.k_pch_SteamVR_NeverKillProcesses_Bool = "neverKillProcesses" static
k_pch_SteamVR_PlayAreaColor_String
const string OVR.OpenVR.OpenVR.k_pch_SteamVR_PlayAreaColor_String = "playAreaColor" static
k_pch_SteamVR_RenderCameraMode
const string OVR.OpenVR.OpenVR.k_pch_SteamVR_RenderCameraMode = "renderCameraMode" static
k_pch_SteamVR_RequireHmd_String
const string OVR.OpenVR.OpenVR.k_pch_SteamVR_RequireHmd_String = "requireHmd" static
k_pch_SteamVR_RetailDemo_Bool
const string OVR.OpenVR.OpenVR.k_pch_SteamVR_RetailDemo_Bool = "retailDemo" static
k_pch_SteamVR_Section
const string OVR.OpenVR.OpenVR.k_pch_SteamVR_Section = "steamvr" static
k_pch_SteamVR_SendSystemButtonToAllApps_Bool
const string OVR.OpenVR.OpenVR.k_pch_SteamVR_SendSystemButtonToAllApps_Bool = "sendSystemButtonToAllApps" static
k_pch_SteamVR_ShowMirrorView_Bool
const string OVR.OpenVR.OpenVR.k_pch_SteamVR_ShowMirrorView_Bool = "showMirrorView" static
k_pch_SteamVR_ShowStage_Bool
const string OVR.OpenVR.OpenVR.k_pch_SteamVR_ShowStage_Bool = "showStage" static
k_pch_SteamVR_SpeakersForwardYawOffsetDegrees_Float
const string OVR.OpenVR.OpenVR.k_pch_SteamVR_SpeakersForwardYawOffsetDegrees_Float = "speakersForwardYawOffsetDegrees" static
k_pch_SteamVR_StartCompositorFromAppLaunch_Bool
const string OVR.OpenVR.OpenVR.k_pch_SteamVR_StartCompositorFromAppLaunch_Bool = "startCompositorFromAppLaunch" static
k_pch_SteamVR_StartDashboardFromAppLaunch_Bool
const string OVR.OpenVR.OpenVR.k_pch_SteamVR_StartDashboardFromAppLaunch_Bool = "startDashboardFromAppLaunch" static
k_pch_SteamVR_StartMonitorFromAppLaunch
const string OVR.OpenVR.OpenVR.k_pch_SteamVR_StartMonitorFromAppLaunch = "startMonitorFromAppLaunch" static
k_pch_SteamVR_StartOverlayAppsFromDashboard_Bool
const string OVR.OpenVR.OpenVR.k_pch_SteamVR_StartOverlayAppsFromDashboard_Bool = "startOverlayAppsFromDashboard" static
k_pch_SteamVR_SupersampleManualOverride_Bool
const string OVR.OpenVR.OpenVR.k_pch_SteamVR_SupersampleManualOverride_Bool = "supersampleManualOverride" static
k_pch_SteamVR_SupersampleScale_Float
const string OVR.OpenVR.OpenVR.k_pch_SteamVR_SupersampleScale_Float = "supersampleScale" static
k_pch_SteamVR_UsingSpeakers_Bool
const string OVR.OpenVR.OpenVR.k_pch_SteamVR_UsingSpeakers_Bool = "usingSpeakers" static
k_pch_Trackers_Section
const string OVR.OpenVR.OpenVR.k_pch_Trackers_Section = "trackers" static
k_pch_TrackingOverride_Section
const string OVR.OpenVR.OpenVR.k_pch_TrackingOverride_Section = "TrackingOverrides" static
k_pch_UserInterface_MinimizeToTray_Bool
const string OVR.OpenVR.OpenVR.k_pch_UserInterface_MinimizeToTray_Bool = "MinimizeToTray" static
k_pch_UserInterface_Screenshots_Bool
const string OVR.OpenVR.OpenVR.k_pch_UserInterface_Screenshots_Bool = "screenshots" static
k_pch_UserInterface_ScreenshotType_Int
const string OVR.OpenVR.OpenVR.k_pch_UserInterface_ScreenshotType_Int = "screenshotType" static
k_pch_UserInterface_Section
const string OVR.OpenVR.OpenVR.k_pch_UserInterface_Section = "userinterface" static
k_pch_UserInterface_StatusAlwaysOnTop_Bool
const string OVR.OpenVR.OpenVR.k_pch_UserInterface_StatusAlwaysOnTop_Bool = "StatusAlwaysOnTop" static
k_pch_WebInterface_Section
const string OVR.OpenVR.OpenVR.k_pch_WebInterface_Section = "WebInterface" static
k_pch_WebInterface_WebEnable_Bool
const string OVR.OpenVR.OpenVR.k_pch_WebInterface_WebEnable_Bool = "WebEnable" static
k_pch_WebInterface_WebPort_String
const string OVR.OpenVR.OpenVR.k_pch_WebInterface_WebPort_String = "WebPort" static
k_ulInvalidActionHandle
const ulong OVR.OpenVR.OpenVR.k_ulInvalidActionHandle = 0 static
k_ulInvalidActionSetHandle
const ulong OVR.OpenVR.OpenVR.k_ulInvalidActionSetHandle = 0 static
k_ulInvalidDriverHandle
const ulong OVR.OpenVR.OpenVR.k_ulInvalidDriverHandle = 0 static
k_ulInvalidInputValueHandle
const ulong OVR.OpenVR.OpenVR.k_ulInvalidInputValueHandle = 0 static
k_ulInvalidIOBufferHandle
const ulong OVR.OpenVR.OpenVR.k_ulInvalidIOBufferHandle = 0 static
k_ulInvalidPropertyContainer
const ulong OVR.OpenVR.OpenVR.k_ulInvalidPropertyContainer = 0 static
k_ulInvalidSpatialAnchorHandle
const uint OVR.OpenVR.OpenVR.k_ulInvalidSpatialAnchorHandle = 0 static
k_ulOverlayHandleInvalid
const ulong OVR.OpenVR.OpenVR.k_ulOverlayHandleInvalid = 0 static
k_unActionPropertyTag
const uint OVR.OpenVR.OpenVR.k_unActionPropertyTag = 32 static
k_unBoolPropertyTag
const uint OVR.OpenVR.OpenVR.k_unBoolPropertyTag = 4 static
k_unControllerStateAxisCount
const uint OVR.OpenVR.OpenVR.k_unControllerStateAxisCount = 5 static
k_unFloatPropertyTag
const uint OVR.OpenVR.OpenVR.k_unFloatPropertyTag = 1 static
k_unHapticVibrationPropertyTag
const uint OVR.OpenVR.OpenVR.k_unHapticVibrationPropertyTag = 35 static
k_unHiddenAreaPropertyTag
const uint OVR.OpenVR.OpenVR.k_unHiddenAreaPropertyTag = 30 static
k_unHmdMatrix34PropertyTag
const uint OVR.OpenVR.OpenVR.k_unHmdMatrix34PropertyTag = 20 static
k_unHmdMatrix44PropertyTag
const uint OVR.OpenVR.OpenVR.k_unHmdMatrix44PropertyTag = 21 static
k_unHmdVector3PropertyTag
const uint OVR.OpenVR.OpenVR.k_unHmdVector3PropertyTag = 22 static
k_unHmdVector4PropertyTag
const uint OVR.OpenVR.OpenVR.k_unHmdVector4PropertyTag = 23 static
k_unInputValuePropertyTag
const uint OVR.OpenVR.OpenVR.k_unInputValuePropertyTag = 33 static
k_unInt32PropertyTag
const uint OVR.OpenVR.OpenVR.k_unInt32PropertyTag = 2 static
k_unInvalidPropertyTag
const uint OVR.OpenVR.OpenVR.k_unInvalidPropertyTag = 0 static
k_unMaxActionNameLength
const uint OVR.OpenVR.OpenVR.k_unMaxActionNameLength = 64 static
k_unMaxActionOriginCount
const uint OVR.OpenVR.OpenVR.k_unMaxActionOriginCount = 16 static
k_unMaxActionSetNameLength
const uint OVR.OpenVR.OpenVR.k_unMaxActionSetNameLength = 64 static
k_unMaxApplicationKeyLength
const uint OVR.OpenVR.OpenVR.k_unMaxApplicationKeyLength = 128 static
k_unMaxDriverDebugResponseSize
const uint OVR.OpenVR.OpenVR.k_unMaxDriverDebugResponseSize = 32768 static
k_unMaxOverlayCount
const uint OVR.OpenVR.OpenVR.k_unMaxOverlayCount = 64 static
k_unMaxOverlayIntersectionMaskPrimitivesCount
const uint OVR.OpenVR.OpenVR.k_unMaxOverlayIntersectionMaskPrimitivesCount = 32 static
k_unMaxPropertyStringSize
const uint OVR.OpenVR.OpenVR.k_unMaxPropertyStringSize = 32768 static
k_unMaxSettingsKeyLength
const uint OVR.OpenVR.OpenVR.k_unMaxSettingsKeyLength = 128 static
k_unMaxTrackedDeviceCount
const uint OVR.OpenVR.OpenVR.k_unMaxTrackedDeviceCount = 64 static
k_unNotificationTextMaxSize
const uint OVR.OpenVR.OpenVR.k_unNotificationTextMaxSize = 256 static
k_unOpenVRInternalReserved_End
const uint OVR.OpenVR.OpenVR.k_unOpenVRInternalReserved_End = 10000 static
k_unOpenVRInternalReserved_Start
const uint OVR.OpenVR.OpenVR.k_unOpenVRInternalReserved_Start = 1000 static
k_unPathHandleInfoTag
const uint OVR.OpenVR.OpenVR.k_unPathHandleInfoTag = 31 static
k_unScreenshotHandleInvalid
const uint OVR.OpenVR.OpenVR.k_unScreenshotHandleInvalid = 0 static
k_unSkeletonPropertyTag
const uint OVR.OpenVR.OpenVR.k_unSkeletonPropertyTag = 36 static
k_unSpatialAnchorPosePropertyTag
const uint OVR.OpenVR.OpenVR.k_unSpatialAnchorPosePropertyTag = 40 static
k_unStringPropertyTag
const uint OVR.OpenVR.OpenVR.k_unStringPropertyTag = 5 static
k_unTrackedDeviceIndex_Hmd
const uint OVR.OpenVR.OpenVR.k_unTrackedDeviceIndex_Hmd = 0 static
k_unTrackedDeviceIndexInvalid
const uint OVR.OpenVR.OpenVR.k_unTrackedDeviceIndexInvalid = 4294967295 static
k_unTrackedDeviceIndexOther
const uint OVR.OpenVR.OpenVR.k_unTrackedDeviceIndexOther = 4294967294 static
k_unUint64PropertyTag
const uint OVR.OpenVR.OpenVR.k_unUint64PropertyTag = 3 static
k_unVROverlayMaxKeyLength
const uint OVR.OpenVR.OpenVR.k_unVROverlayMaxKeyLength = 128 static
k_unVROverlayMaxNameLength
const uint OVR.OpenVR.OpenVR.k_unVROverlayMaxNameLength = 128 static
k_unWildcardPropertyTag
const uint OVR.OpenVR.OpenVR.k_unWildcardPropertyTag = 34 static
Property Documentation
Applications
CVRApplications OVR.OpenVR.OpenVR.Applications static get
Chaperone
CVRChaperone OVR.OpenVR.OpenVR.Chaperone static get
ChaperoneSetup
CVRChaperoneSetup OVR.OpenVR.OpenVR.ChaperoneSetup static get
Compositor
CVRCompositor OVR.OpenVR.OpenVR.Compositor static get
ExtendedDisplay
CVRExtendedDisplay OVR.OpenVR.OpenVR.ExtendedDisplay static get
Input
CVRInput OVR.OpenVR.OpenVR.Input static get
Overlay
CVROverlay OVR.OpenVR.OpenVR.Overlay static get
RenderModels
CVRRenderModels OVR.OpenVR.OpenVR.RenderModels static get
Screenshots
CVRScreenshots OVR.OpenVR.OpenVR.Screenshots static get
Settings
CVRSettings OVR.OpenVR.OpenVR.Settings static get
SpatialAnchors
CVRSpatialAnchors OVR.OpenVR.OpenVR.SpatialAnchors static get
System
CVRSystem OVR.OpenVR.OpenVR.System static get
Referenced by OVR.OpenVR.OpenVR.Init().
TrackedCamera
CVRTrackedCamera OVR.OpenVR.OpenVR.TrackedCamera static get
The documentation for this class was generated from the following file:
C:/Users/Lykos/Desktop/Projects/Capstone/VRGames/Assets/ThirdParty/Oculus/VR/ThirdParty/openvr_api.cs