VRGames: Oculus.Interaction.Editor.EditorBase Class Reference
Oculus.Interaction.Editor.EditorBase Class Reference
A utility class for building custom editors with less work required.
Public Member Functions
override void OnInspectorGUI ()
Protected Member Functions
virtual void OnEnable ()
virtual void OnDisable ()
virtual void OnInit ()
You must put all of the editor specifications into OnInit.
void Hide (params string[] properties)
Call in OnInit with one or more property names to hide them from the inspector.
void Defer (params string[] properties)
Call in OnInit with one or more property names to defer drawing them until after all non-deferred properties have been drawn. All deferred properties will be drawn in the order they are passed in to calls to Defer.
void Defer (string property, Action< SerializedProperty > customDrawer)
Call in OnInit with a single property name and a custom property drawer. Equivalent to calling Draw and then Defer for the property.
void Defer (Action deferredAction)
Call in OnInit with a single delegate to have it be called after all other non-deferred properties have been drawn.
void Draw (string property, Action< SerializedProperty > drawer)
Call in OnInit to specify a custom drawer for a single property. Whenever the property is drawn, it will use the provided property drawer instead of the default one.
void Draw (string property, string withExtra0, Action< SerializedProperty, SerializedProperty > drawer)
Call in OnInit to specify a custom drawer for a single property. Include an extra property that gets lumped in with the primary property. The extra property is not drawn normally, and is instead grouped in with the primary property. Can be used in situations where a collection of properties need to be drawn together.
void Draw (string property, string withExtra0, string withExtra1, Action< SerializedProperty, SerializedProperty, SerializedProperty > drawer)
void Draw (string property, string withExtra0, string withExtra1, string withExtra2, Action< SerializedProperty, SerializedProperty, SerializedProperty, SerializedProperty > drawer)
void Draw (string property, string withExtra0, string withExtra1, string withExtra2, string withExtra3, Action< SerializedProperty, SerializedProperty, SerializedProperty, SerializedProperty, SerializedProperty > drawer)
void Conditional (string boolPropName, bool showIf, params string[] toHide)
void Conditional< T > (string enumPropName, T showIf, params string[] toHide)
void Decorate (string property, Action< SerializedProperty > decorator)
Call in OnInit to specify a custom decorator for a single property. Before a property is drawn, all of the decorators will be drawn first.
void Group (string firstProperty, string lastProperty, Action beginGroup, Action endGroup)
Call in OnInit to specify a custom grouping behaviour for a range of properties. Specify the first and last property (inclusive) and the action to take BEFORE the first property is drawn, and the action to take AFTER the last property is drawn.
void Group (string firstProperty, string lastProperty, GUIStyle style)
A utility version of the more generic Group method. Call in OnInit to specify a range of properties that should be grouped within a styled vertical layout group.
void Foldout (string firstProperty, string lastProperty, string foldoutName, bool showByDefault=false)
Groups the given properties into a foldout with a given name.
virtual void OnBeforeInspector ()
virtual void OnAfterInspector (bool anyPropertiesModified)
Detailed Description
A utility class for building custom editors with less work required.
Member Function Documentation
Conditional()
void Oculus.Interaction.Editor.EditorBase.Conditional (string boolPropName, bool showIf, params string[] toHide) protected
Conditional< T >()
void Oculus.Interaction.Editor.EditorBase.Conditional< T > (string enumPropName, T showIf, params string[] toHide) protected
Type Constraints
T : Enum
Decorate()
void Oculus.Interaction.Editor.EditorBase.Decorate (string property, Action< SerializedProperty > decorator) protected
Call in OnInit to specify a custom decorator for a single property. Before a property is drawn, all of the decorators will be drawn first.
Defer() [1/3]
void Oculus.Interaction.Editor.EditorBase.Defer (Action deferredAction) protected
Call in OnInit with a single delegate to have it be called after all other non-deferred properties have been drawn.
Defer() [2/3]
void Oculus.Interaction.Editor.EditorBase.Defer (params string[] properties) protected
Call in OnInit with one or more property names to defer drawing them until after all non-deferred properties have been drawn. All deferred properties will be drawn in the order they are passed in to calls to Defer.
Referenced by Oculus.Interaction.Editor.EditorBase.Defer().
Defer() [3/3]
void Oculus.Interaction.Editor.EditorBase.Defer (string property, Action< SerializedProperty > customDrawer) protected
Call in OnInit with a single property name and a custom property drawer. Equivalent to calling Draw and then Defer for the property.
Draw() [1/5]
void Oculus.Interaction.Editor.EditorBase.Draw (string property, Action< SerializedProperty > drawer) protected
Call in OnInit to specify a custom drawer for a single property. Whenever the property is drawn, it will use the provided property drawer instead of the default one.
Referenced by Oculus.Interaction.Editor.EditorBase.Defer(), Oculus.Interaction.Editor.EditorBase.Draw(), Oculus.Interaction.Editor.EditorBase.Draw(), Oculus.Interaction.Editor.EditorBase.Draw(), Oculus.Interaction.Editor.EditorBase.Draw(), and Oculus.Interaction.UnityCanvas.Editor.CanvasRenderTextureEditor.OnEnable().
Draw() [2/5]
void Oculus.Interaction.Editor.EditorBase.Draw (string property, string withExtra0, Action< SerializedProperty, SerializedProperty > drawer) protected
Call in OnInit to specify a custom drawer for a single property. Include an extra property that gets lumped in with the primary property. The extra property is not drawn normally, and is instead grouped in with the primary property. Can be used in situations where a collection of properties need to be drawn together.
Draw() [3/5]
void Oculus.Interaction.Editor.EditorBase.Draw (string property, string withExtra0, string withExtra1, Action< SerializedProperty, SerializedProperty, SerializedProperty > drawer) protected
Draw() [4/5]
void Oculus.Interaction.Editor.EditorBase.Draw (string property, string withExtra0, string withExtra1, string withExtra2, Action< SerializedProperty, SerializedProperty, SerializedProperty, SerializedProperty > drawer) protected
Draw() [5/5]
void Oculus.Interaction.Editor.EditorBase.Draw (string property, string withExtra0, string withExtra1, string withExtra2, string withExtra3, Action< SerializedProperty, SerializedProperty, SerializedProperty, SerializedProperty, SerializedProperty > drawer) protected
Foldout()
void Oculus.Interaction.Editor.EditorBase.Foldout (string firstProperty, string lastProperty, string foldoutName, bool showByDefault = false) protected
Groups the given properties into a foldout with a given name.
Group() [1/2]
void Oculus.Interaction.Editor.EditorBase.Group (string firstProperty, string lastProperty, Action beginGroup, Action endGroup) protected
Call in OnInit to specify a custom grouping behaviour for a range of properties. Specify the first and last property (inclusive) and the action to take BEFORE the first property is drawn, and the action to take AFTER the last property is drawn.
Referenced by Oculus.Interaction.Editor.EditorBase.Foldout(), and Oculus.Interaction.Editor.EditorBase.Group().
Group() [2/2]
void Oculus.Interaction.Editor.EditorBase.Group (string firstProperty, string lastProperty, GUIStyle style) protected
A utility version of the more generic Group method. Call in OnInit to specify a range of properties that should be grouped within a styled vertical layout group.
Hide()
void Oculus.Interaction.Editor.EditorBase.Hide (params string[] properties) protected
Call in OnInit with one or more property names to hide them from the inspector.
This is preferable to using [HideInInspector] because it still allows the property to be viewed when using the Inspector debug mode.
Referenced by Oculus.Interaction.Editor.EditorBase.Draw(), Oculus.Interaction.Editor.EditorBase.Draw(), Oculus.Interaction.Editor.EditorBase.Draw(), and Oculus.Interaction.Editor.EditorBase.Draw().
OnAfterInspector()
virtual void Oculus.Interaction.Editor.EditorBase.OnAfterInspector (bool anyPropertiesModified) protected virtual
Referenced by Oculus.Interaction.Editor.EditorBase.OnInspectorGUI().
OnBeforeInspector()
virtual void Oculus.Interaction.Editor.EditorBase.OnBeforeInspector () protected virtual
Reimplemented in Oculus.Interaction.UnityCanvas.Editor.CanvasRenderTextureEditor.
Referenced by Oculus.Interaction.Editor.EditorBase.OnInspectorGUI().
OnDisable()
virtual void Oculus.Interaction.Editor.EditorBase.OnDisable () protected virtual
OnEnable()
virtual void Oculus.Interaction.Editor.EditorBase.OnEnable () protected virtual
Reimplemented in Oculus.Interaction.UnityCanvas.Editor.CanvasRenderTextureEditor.
OnInit()
virtual void Oculus.Interaction.Editor.EditorBase.OnInit () protected virtual
You must put all of the editor specifications into OnInit.
Referenced by Oculus.Interaction.Editor.EditorBase.OnInspectorGUI().
OnInspectorGUI()
override void Oculus.Interaction.Editor.EditorBase.OnInspectorGUI ()
The documentation for this class was generated from the following file:
C:/Users/Lykos/Desktop/Projects/Capstone/VRGames/Assets/ThirdParty/Oculus/Interaction/Editor/EditorBase.cs