VRGames: Classes.Managers.CalibrationManager Class Reference
Classes.Managers.CalibrationManager Class Reference
Public Types
enum CalibrationType { None , Mirror , Scale }
Public Member Functions
void Start ()
void SetCalBtnsActive (bool val)
void Reset ()
void Calibrate (CalibrationType calibrationType, OVRInput.Controller unaffectedController)
void changeScaleAmt (float scaleAmount)
Static Public Member Functions
static CalibrationManager getManager ()
Public Attributes
HandStruct affectedHand
HandStruct nonAffectedHand
OVRInput.Controller affectedController
OVRInput.Controller naController
CalibrationType calibrationType
bool spawnSpheres = false
Properties
static CalibrationManager Instance [get]
Member Enumeration Documentation
CalibrationType
enum Classes.Managers.CalibrationManager.CalibrationType
Enumerator
None
Mirror
Scale
Member Function Documentation
Calibrate()
void Classes.Managers.CalibrationManager.Calibrate (CalibrationType calibrationType, OVRInput::Controller unaffectedController)
References Classes.Managers.CalibrationManager.calibrationType, and Classes.Managers.CalibrationManager.SetCalBtnsActive().
Referenced by Calibrator.Calibrate().
changeScaleAmt()
void Classes.Managers.CalibrationManager.changeScaleAmt (float scaleAmount)
getManager()
static CalibrationManager Classes.Managers.CalibrationManager.getManager () static
References Classes.Managers.CalibrationManager.Instance.
Reset()
void Classes.Managers.CalibrationManager.Reset ()
References Classes.Managers.CalibrationManager.SetCalBtnsActive().
Referenced by CalibrationSphereSelector.ButtonCalibrate(), and Calibrator.ResetCalibration().
SetCalBtnsActive()
void Classes.Managers.CalibrationManager.SetCalBtnsActive (bool val)
Referenced by CalibrationSphereSelector.ButtonCalibrate(), Classes.Managers.CalibrationManager.Calibrate(), and Classes.Managers.CalibrationManager.Reset().
Start()
void Classes.Managers.CalibrationManager.Start ()
References Classes.Managers.CalibrationManager.spawnSpheres.
Member Data Documentation
affectedController
OVRInput.Controller Classes.Managers.CalibrationManager.affectedController
affectedHand
HandStruct Classes.Managers.CalibrationManager.affectedHand
calibrationType
CalibrationType Classes.Managers.CalibrationManager.calibrationType
Referenced by Classes.Managers.CalibrationManager.Calibrate().
naController
OVRInput.Controller Classes.Managers.CalibrationManager.naController
nonAffectedHand
HandStruct Classes.Managers.CalibrationManager.nonAffectedHand
spawnSpheres
bool Classes.Managers.CalibrationManager.spawnSpheres = false
Referenced by Classes.Managers.CalibrationManager.Start().
Property Documentation
Instance
CalibrationManager Classes.Managers.CalibrationManager.Instance static get
Referenced by CalibrationSphereSelector.ButtonCalibrate(), Calibrator.Calibrate(), Classes.Managers.CalibrationManager.getManager(), and Calibrator.ResetCalibration().
The documentation for this class was generated from the following file:
C:/Users/Lykos/Desktop/Projects/Capstone/VRGames/Assets/Shared/Scripts/Managers/CalibrationManager.cs