VRGames: Classes.Managers.PlayerManager Class Reference
Classes.Managers.PlayerManager Class Reference
Static Public Member Functions
static GameObject getPlayer ()
static void resetPosition ()
static GameObject getLeftHand ()
static GameObject getRightHand ()
static void movePlayerX (float x)
static void movePlayerY (float y)
static void movePlayerZ (float z)
static void movePlayer (GameObject warp)
static void offsetMovePlayer (GameObject warp, Vector3 offset)
static void setPlayerPositionX (float x)
static void setPlayerPositionY (float y)
static void setPlayerPositionZ (float z)
static void SetIKShoulderWidth (float width)
static void SetIKHeadHeight (float height)
static void SetIKArmLength (float length)
static void SetExtendArmThreshold (float extendRot)
static void SetRetractArmThreshold (float retractRot)
static void ShowIKSkeleton (bool show)
Shows or hides the player IK rig based on the passed boolean value.
static void ToggleIKSkeleton ()
When called, toggles the view of the player's IK skeleton.
Public Attributes
GameObject playerPrefab
GameObject playerIK
Static Public Attributes
static bool isIKRendering
Member Function Documentation
getLeftHand()
static GameObject Classes.Managers.PlayerManager.getLeftHand () static
getPlayer()
static GameObject Classes.Managers.PlayerManager.getPlayer () static
getRightHand()
static GameObject Classes.Managers.PlayerManager.getRightHand () static
movePlayer()
static void Classes.Managers.PlayerManager.movePlayer (GameObject warp) static
Referenced by Classes.Managers.LavaClimbGameplayManager.onRockGrabbed(), and GameplayManager.Start().
movePlayerX()
static void Classes.Managers.PlayerManager.movePlayerX (float x) static
movePlayerY()
static void Classes.Managers.PlayerManager.movePlayerY (float y) static
movePlayerZ()
static void Classes.Managers.PlayerManager.movePlayerZ (float z) static
offsetMovePlayer()
static void Classes.Managers.PlayerManager.offsetMovePlayer (GameObject warp, Vector3 offset) static
resetPosition()
static void Classes.Managers.PlayerManager.resetPosition () static
SetExtendArmThreshold()
static void Classes.Managers.PlayerManager.SetExtendArmThreshold (float extendRot) static
SetIKArmLength()
static void Classes.Managers.PlayerManager.SetIKArmLength (float length) static
SetIKHeadHeight()
static void Classes.Managers.PlayerManager.SetIKHeadHeight (float height) static
SetIKShoulderWidth()
static void Classes.Managers.PlayerManager.SetIKShoulderWidth (float width) static
setPlayerPositionX()
static void Classes.Managers.PlayerManager.setPlayerPositionX (float x) static
setPlayerPositionY()
static void Classes.Managers.PlayerManager.setPlayerPositionY (float y) static
setPlayerPositionZ()
static void Classes.Managers.PlayerManager.setPlayerPositionZ (float z) static
SetRetractArmThreshold()
static void Classes.Managers.PlayerManager.SetRetractArmThreshold (float retractRot) static
ShowIKSkeleton()
static void Classes.Managers.PlayerManager.ShowIKSkeleton (bool show) static
Shows or hides the player IK rig based on the passed boolean value.
Parameters
show If True, shows the skeleton. If False, hides the skeleton
References Classes.Managers.PlayerManager.isIKRendering.
Referenced by Classes.Managers.PlayerManager.ToggleIKSkeleton().
ToggleIKSkeleton()
static void Classes.Managers.PlayerManager.ToggleIKSkeleton () static
When called, toggles the view of the player's IK skeleton.
References Classes.Managers.PlayerManager.isIKRendering, and Classes.Managers.PlayerManager.ShowIKSkeleton().
Member Data Documentation
isIKRendering
bool Classes.Managers.PlayerManager.isIKRendering static
Referenced by Classes.Managers.PlayerManager.ShowIKSkeleton(), and Classes.Managers.PlayerManager.ToggleIKSkeleton().
playerIK
GameObject Classes.Managers.PlayerManager.playerIK
playerPrefab
GameObject Classes.Managers.PlayerManager.playerPrefab
The documentation for this class was generated from the following file:
C:/Users/Lykos/Desktop/Projects/Capstone/VRGames/Assets/Shared/Scripts/Managers/PlayerManager.cs