VRGames: UnityEngine.XR.Interaction.Toolkit.XRBaseInteractable Class Reference
UnityEngine.XR.Interaction.Toolkit.XRBaseInteractable Class Reference abstract
Abstract base class from which all interactable behaviours derive. This class hooks into the interaction system (via XRInteractionManager) and provides base virtual methods for handling hover and selection.
Public Types
enum MovementType { VelocityTracking , Kinematic , Instantaneous }
Options for how to process and perform movement of an Interactable.
Public Member Functions
virtual Transform GetAttachTransform (IXRInteractor interactor)
Gets the Transform that serves as the attachment point for a given Interactor.
Parameters
interactor The specific Interactor as context to get the attachment point for.
Returns
Returns the attachment point Transform.
See also
IXRInteractor.GetAttachTransform
This should typically return the Transform of a child GameObject or the transform itself.
Pose GetAttachPoseOnSelect (IXRSelectInteractor interactor)
Gets the world position and rotation of the Attach Transform captured during the moment of selection.
Parameters
interactor The specific Interactor as context to get the attachment point for.
Returns
Returns the world pose of the attachment point during the moment of selection, and otherwise the identity Pose if it was not selected by it during the current selection stack.
See also
GetLocalAttachPoseOnSelect, IXRInteractable.GetAttachTransform, IXRSelectInteractor.GetAttachPoseOnSelect
Pose GetLocalAttachPoseOnSelect (IXRSelectInteractor interactor)
Gets the local position and rotation of the Attach Transform captured during the moment of selection.
Parameters
interactor The specific Interactor as context to get the attachment point for.
Returns
Returns the local pose of the attachment point during the moment of selection, and otherwise the identity Pose if it was not selected by it during the current selection stack.
See also
GetAttachPoseOnSelect, IXRInteractable.GetAttachTransform, IXRSelectInteractor.GetLocalAttachPoseOnSelect
virtual float GetDistanceSqrToInteractor (IXRInteractor interactor)
Calculates squared distance to an Interactor (based on colliders).
Parameters
interactor Interactor to calculate distance against.
Returns
Returns the minimum squared distance between the Interactor and this Interactable's colliders.
virtual bool IsHoverableBy (IXRHoverInteractor interactor)
Determines if a given Interactor can hover over this Interactable.
virtual bool IsSelectableBy (IXRSelectInteractor interactor)
Determines if a given Interactor can select this Interactable.
virtual void AttachCustomReticle (IXRInteractor interactor)
Attaches the custom reticle to the Interactor.
virtual void RemoveCustomReticle (IXRInteractor interactor)
Removes the custom reticle from the Interactor.
virtual void ProcessInteractable (XRInteractionUpdateOrder.UpdatePhase updatePhase)
The XRInteractionManager calls this method to update the Interactable.
Parameters
updatePhase The update phase this is called during.
Please see the XRInteractionManager and XRInteractionUpdateOrder.UpdatePhase documentation for more details on update order.
virtual float GetDistanceSqrToInteractor (XRBaseInteractor interactor)
(Deprecated) Calculates distance squared to interactor (based on colliders).
virtual void AttachCustomReticle (XRBaseInteractor interactor)
(Deprecated) Attaches the custom reticle to the Interactor.
virtual void RemoveCustomReticle (XRBaseInteractor interactor)
(Deprecated) Removes the custom reticle from the Interactor.
virtual bool IsHoverableBy (XRBaseInteractor interactor)
(Deprecated) Determines if this interactable can be hovered by a given interactor.
virtual bool IsSelectableBy (XRBaseInteractor interactor)
(Deprecated) Determines if a given Interactor can select this Interactable.
Protected Member Functions
virtual void Reset ()
See MonoBehaviour.
virtual void Awake ()
See MonoBehaviour.
virtual void OnEnable ()
See MonoBehaviour.
virtual void OnDisable ()
See MonoBehaviour.
virtual void OnDestroy ()
See MonoBehaviour.
void CaptureAttachPose (IXRSelectInteractor interactor)
Capture the current Attach Transform pose. This method is automatically called by Unity to capture the pose during the moment of selection.
virtual void OnRegistered (InteractableRegisteredEventArgs args)
The XRInteractionManager calls this method when this Interactable is registered with it.
virtual void OnUnregistered (InteractableUnregisteredEventArgs args)
The XRInteractionManager calls this method when this Interactable is unregistered from it.
virtual void OnHoverEntering (HoverEnterEventArgs args)
The XRInteractionManager calls this method right before the Interactor first initiates hovering over an Interactable in a first pass.
virtual void OnHoverEntered (HoverEnterEventArgs args)
The XRInteractionManager calls this method when the Interactor first initiates hovering over an Interactable in a second pass.
virtual void OnHoverExiting (HoverExitEventArgs args)
The XRInteractionManager calls this method right before the Interactor ends hovering over an Interactable in a first pass.
virtual void OnHoverExited (HoverExitEventArgs args)
The XRInteractionManager calls this method when the Interactor ends hovering over an Interactable in a second pass.
virtual void OnSelectEntering (SelectEnterEventArgs args)
The XRInteractionManager calls this method right before the Interactor first initiates selection of an Interactable in a first pass.
virtual void OnSelectEntered (SelectEnterEventArgs args)
The XRInteractionManager calls this method when the Interactor first initiates selection of an Interactable in a second pass.
virtual void OnSelectExiting (SelectExitEventArgs args)
The XRInteractionManager calls this method right before the Interactor ends selection of an Interactable in a first pass.
virtual void OnSelectExited (SelectExitEventArgs args)
The XRInteractionManager calls this method when the Interactor ends selection of an Interactable in a second pass.
virtual void OnActivated (ActivateEventArgs args)
XRBaseControllerInteractor calls this method when the Interactor begins an activation event on this Interactable.
virtual void OnDeactivated (DeactivateEventArgs args)
XRBaseControllerInteractor calls this method when the Interactor ends an activation event on this Interactable.
virtual void OnHoverEntering (XRBaseInteractor interactor)
(Deprecated) The XRInteractionManager calls this method right before the Interactor first initiates hovering over an Interactable in a first pass.
virtual void OnHoverEntered (XRBaseInteractor interactor)
(Deprecated) The XRInteractionManager calls this method when the Interactor first initiates hovering over an Interactable in a second pass.
virtual void OnHoverExiting (XRBaseInteractor interactor)
(Deprecated) The XRInteractionManager calls this method right before the Interactor ends hovering over an Interactable in a first pass.
virtual void OnHoverExited (XRBaseInteractor interactor)
(Deprecated) The XRInteractionManager calls this method when the Interactor ends hovering over an Interactable in a second pass.
virtual void OnSelectEntering (XRBaseInteractor interactor)
(Deprecated) The XRInteractionManager calls this method right before the Interactor first initiates selection of an Interactable in a first pass.
virtual void OnSelectEntered (XRBaseInteractor interactor)
(Deprecated) The XRInteractionManager calls this method when the Interactor first initiates selection of an Interactable in a second pass.
virtual void OnSelectExiting (XRBaseInteractor interactor)
(Deprecated) The XRInteractionManager calls this method right before the Interactor ends selection of an Interactable in a first pass.
virtual void OnSelectExited (XRBaseInteractor interactor)
(Deprecated) The XRInteractionManager calls this method when the Interactor ends selection of an Interactable in a second pass.
virtual void OnSelectCanceling (XRBaseInteractor interactor)
(Deprecated) The XRInteractionManager calls this method while this Interactable is selected by an Interactor right before either is unregistered (such as from being disabled or destroyed) in a first pass.
virtual void OnSelectCanceled (XRBaseInteractor interactor)
(Deprecated) The XRInteractionManager calls this method while an Interactor selects this Interactable when either is unregistered (such as from being disabled or destroyed) in a second pass.
virtual void OnActivate (XRBaseInteractor interactor)
(Deprecated) The XRBaseControllerInteractor calls this method when the Interactor begins an activation event on this Interactable.
virtual void OnDeactivate (XRBaseInteractor interactor)
(Deprecated) The XRBaseControllerInteractor calls this method when the Interactor ends an activation event on this Interactable.
Properties
XRInteractionManager interactionManager [get, set]
The XRInteractionManager that this Interactable will communicate with (will find one if null).
List< Collider > colliders [get]
(Read Only) Colliders to use for interaction with this Interactable (if empty, will use any child Colliders).
InteractionLayerMask interactionLayers [get, set]
Allows interaction with Interactors whose Interaction Layer Mask overlaps with any Layer in this Interaction Layer Mask.
InteractableSelectMode selectMode [get, set]
Indicates the selection policy of an Interactable.
See also
InteractableSelectMode
GameObject customReticle [get, set]
The reticle that appears at the end of the line when valid.
HoverEnterEvent firstHoverEntered [get, set]
The event that is called only when the first Interactor begins hovering over this Interactable as the sole hovering Interactor. Subsequent Interactors that begin hovering over this Interactable will not cause this event to be invoked as long as any others are still hovering.The HoverEnterEventArgs passed to each listener is only valid while the event is invoked, do not hold a reference to it.
HoverExitEvent lastHoverExited [get, set]
The event that is called only when the last remaining hovering Interactor ends hovering over this Interactable.The HoverExitEventArgs passed to each listener is only valid while the event is invoked, do not hold a reference to it.
HoverEnterEvent hoverEntered [get, set]
The event that is called when an Interactor begins hovering over this Interactable.The HoverEnterEventArgs passed to each listener is only valid while the event is invoked, do not hold a reference to it.
HoverExitEvent hoverExited [get, set]
The event that is called when an Interactor ends hovering over this Interactable.The HoverExitEventArgs passed to each listener is only valid while the event is invoked, do not hold a reference to it.
SelectEnterEvent firstSelectEntered [get, set]
The event that is called only when the first Interactor begins selecting this Interactable as the sole selecting Interactor. Subsequent Interactors that begin selecting this Interactable will not cause this event to be invoked as long as any others are still selecting.The SelectEnterEventArgs passed to each listener is only valid while the event is invoked, do not hold a reference to it.
SelectExitEvent lastSelectExited [get, set]
The event that is called only when the last remaining selecting Interactor ends selecting this Interactable.The SelectExitEventArgs passed to each listener is only valid while the event is invoked, do not hold a reference to it.
SelectEnterEvent selectEntered [get, set]
The event that is called when an Interactor begins selecting this Interactable.The SelectEnterEventArgs passed to each listener is only valid while the event is invoked, do not hold a reference to it.
SelectExitEvent selectExited [get, set]
The event that is called when an Interactor ends selecting this Interactable.The SelectExitEventArgs passed to each listener is only valid while the event is invoked, do not hold a reference to it.
ActivateEvent activated [get, set]
The event that is called when the selecting Interactor activates this Interactable.Not to be confused with activating or deactivating a GameObject with GameObject.SetActive. This is a generic event when an Interactor wants to activate an Interactable, such as from a trigger pull on a controller.
The ActivateEventArgs passed to each listener is only valid while the event is invoked, do not hold a reference to it.
DeactivateEvent deactivated [get, set]
The event that is called when an Interactor deactivates this Interactable.Not to be confused with activating or deactivating a GameObject with GameObject.SetActive. This is a generic event when an Interactor wants to deactivate an Interactable, such as from a trigger release on a controller.
The DeactivateEventArgs passed to each listener is only valid while the event is invoked, do not hold a reference to it.
List< IXRHoverInteractor > interactorsHovering = new List<IXRHoverInteractor>() [get]
(Read Only) The list of Interactors that are hovering on this Interactable (may by empty).You should treat this as a read only view of the list and should not modify it. Unity exposes this as a List<T> rather than an IReadOnlyList<T> to avoid GC Allocations when enumerating the list.
bool isHovered [get]
(Read Only) Indicates whether an Interactor currently hovers over this Interactable.In other words, returns whether interactorsHovering contains any interactors.
interactorsHovering.Count > 0
List< IXRSelectInteractor > interactorsSelecting = new List<IXRSelectInteractor>() [get]
(Read Only) The list of Interactors currently selecting this Interactable (may by empty).You should treat this as a read only view of the list and should not modify it. It is exposed as a List<T> rather than an IReadOnlyList<T> to avoid GC Allocations when enumerating the list.
IXRSelectInteractor firstInteractorSelecting [get]
(Read Only) The first interactor that selected this interactable since not being selected by any interactor. The interactor may not currently be selecting this interactable, which would be the case when it released while multiple interactors were selecting this interactable.
See also
IXRSelectInteractor.firstInteractableSelected
bool isSelected [get]
(Read Only) Indicates whether this interactable is currently being selected by any interactor.In other words, returns whether interactorsSelecting contains any interactors.
interactorsSelecting.Count > 0
LayerMask interactionLayerMask [get, set]
(Deprecated) Allows interaction with Interactors whose Interaction Layer Mask overlaps with any Layer in this Interaction Layer Mask.
XRInteractableEvent onFirstHoverEntered [get, set]
(Deprecated) Gets or sets the event that Unity calls only when the first Interactor begins hovering over this Interactable as the sole hovering Interactor. Subsequent Interactors that begin hovering over this Interactable will not cause this event to be invoked as long as any others are still hovering.
XRInteractableEvent onLastHoverExited [get, set]
(Deprecated) Gets or sets the event that Unity calls only when the last remaining hovering Interactor ends hovering over this Interactable.
XRInteractableEvent onHoverEntered [get, set]
(Deprecated) Gets or sets the event that Unity calls when an Interactor begins hovering over this Interactable.
XRInteractableEvent onHoverExited [get, set]
(Deprecated) Gets or sets the event that Unity calls when an Interactor ends hovering over this Interactable.
XRInteractableEvent onSelectEntered [get, set]
(Deprecated) Gets or sets the event that Unity calls when an Interactor begins selecting this Interactable.
XRInteractableEvent onSelectExited [get, set]
(Deprecated) Gets or sets the event that Unity calls when an Interactor ends selecting this Interactable.
XRInteractableEvent onSelectCanceled [get, set]
(Deprecated) Gets or sets the event that Unity calls when this Interactable is selected by an Interactor and either is unregistered (such as from being disabled or destroyed).
XRInteractableEvent onActivate [get, set]
(Deprecated) Gets or sets the event that Unity calls when an Interactor activates this selected Interactable.
XRInteractableEvent onDeactivate [get, set]
(Deprecated) Gets or sets the event that Unity calls when an Interactor deactivates this selected Interactable.
XRInteractableEvent onFirstHoverEnter [get]
(Deprecated) Unity calls this only when the first Interactor begins hovering over this Interactable.
XRInteractableEvent onHoverEnter [get]
(Deprecated) Unity calls this every time an Interactor begins hovering over this Interactable.
XRInteractableEvent onHoverExit [get]
(Deprecated) Unity calls this every time an Interactor ends hovering over this Interactable.
XRInteractableEvent onLastHoverExit [get]
(Deprecated) Unity calls this only when the last Interactor ends hovering over this Interactable.
XRInteractableEvent onSelectEnter [get]
(Deprecated) Unity calls this when an Interactor begins selecting this Interactable.
XRInteractableEvent onSelectExit [get]
(Deprecated) Unity calls this when an Interactor ends selecting this Interactable.
XRInteractableEvent onSelectCancel [get]
(Deprecated) Unity calls this when the Interactor selecting this Interactable is disabled or destroyed.
List< XRBaseInteractor > hoveringInteractors = new List<XRBaseInteractor>() [get]
(Deprecated) (Read Only) The list of interactors that are hovering on this interactable.
XRBaseInteractor selectingInteractor [get, protected set]
(Deprecated) The Interactor selecting this Interactable (may be null).
Properties inherited from UnityEngine.XR.Interaction.Toolkit.IXRActivateInteractable
Properties inherited from UnityEngine.XR.Interaction.Toolkit.IXRInteractable
Transform transform [get]
(Read Only) The Transform associated with the Interactable.
Properties inherited from UnityEngine.XR.Interaction.Toolkit.IXRHoverInteractable
Properties inherited from UnityEngine.XR.Interaction.Toolkit.IXRSelectInteractable
Events
Action< InteractableRegisteredEventArgs > registered
Action< InteractableUnregisteredEventArgs > unregistered
Events inherited from UnityEngine.XR.Interaction.Toolkit.IXRInteractable
Action< InteractableRegisteredEventArgs > registered
Unity calls the methods in this invocation list when this Interactable is registered with an XRInteractionManager.
Action< InteractableUnregisteredEventArgs > unregistered
Unity calls the methods in this invocation list when this Interactable is unregistered from an XRInteractionManager.
Detailed Description
Abstract base class from which all interactable behaviours derive. This class hooks into the interaction system (via XRInteractionManager) and provides base virtual methods for handling hover and selection.
Member Enumeration Documentation
MovementType
enum UnityEngine.XR.Interaction.Toolkit.XRBaseInteractable.MovementType
Options for how to process and perform movement of an Interactable.
Each method of movement has tradeoffs, and different values may be more appropriate for each type of Interactable object in a project.
See also
XRGrabInteractable.movementType
Enumerator
VelocityTracking
Move the Interactable object by setting the velocity and angular velocity of the Rigidbody. Use this if you don't want the object to be able to move through other Colliders without a Rigidbody as it follows the Interactor, however with the tradeoff that it can appear to lag behind and not move as smoothly as Instantaneous.
Unity sets the velocity values during the FixedUpdate function. This Interactable will move at the framerate-independent interval of the Physics update, which may be slower than the Update rate. If the Rigidbody is not set to use interpolation or extrapolation, as the Interactable follows the Interactor, it may not visually update position each frame and be a slight distance behind the Interactor or controller due to the difference between the Physics update rate and the render update rate.
See also
Rigidbody.velocity, Rigidbody.angularVelocity
Kinematic
Move the Interactable object by moving the kinematic Rigidbody towards the target position and orientation. Use this if you want to keep the visual representation synchronized to match its Physics state, and if you want to allow the object to be able to move through other Colliders without a Rigidbody as it follows the Interactor.
Unity will call the movement methods during the FixedUpdate function. This Interactable will move at the framerate-independent interval of the Physics update, which may be slower than the Update rate. If the Rigidbody is not set to use interpolation or extrapolation, as the Interactable follows the Interactor, it may not visually update position each frame and be a slight distance behind the Interactor or controller due to the difference between the Physics update rate and the render update rate. Collisions will be more accurate as compared to Instantaneous since with this method, the Rigidbody will be moved by settings its internal velocity rather than instantly teleporting to match the Transform pose.
See also
Rigidbody.MovePosition, Rigidbody.MoveRotation
Instantaneous
Move the Interactable object by setting the position and rotation of the Transform every frame. Use this if you want the visual representation to be updated each frame, minimizing latency, however with the tradeoff that it will be able to move through other Colliders without a Rigidbody as it follows the Interactor.
Unity will set the Transform values each frame, which may be faster than the framerate-independent interval of the Physics update. The Collider of the Interactable object may be a slight distance behind the visual as it follows the Interactor due to the difference between the Physics update rate and the render update rate. Collisions will not be computed as accurately as Kinematic since with this method, the Rigidbody will be forced to instantly teleport poses to match the Transform pose rather than moving the Rigidbody through setting its internal velocity.
See also
Transform.position, Transform.rotation
Member Function Documentation
AttachCustomReticle() [1/2]
virtual void UnityEngine.XR.Interaction.Toolkit.XRBaseInteractable.AttachCustomReticle (IXRInteractor interactor) virtual
Attaches the custom reticle to the Interactor.
Parameters
interactor Interactor that is interacting with this Interactable.
Referenced by UnityEngine.XR.Interaction.Toolkit.XRBaseInteractable.OnHoverEntering().
AttachCustomReticle() [2/2]
virtual void UnityEngine.XR.Interaction.Toolkit.XRBaseInteractable.AttachCustomReticle (XRBaseInteractor interactor) virtual
(Deprecated) Attaches the custom reticle to the Interactor.
Parameters
interactor Interactor that is interacting with this Interactable.
AttachCustomReticle(XRBaseInteractor) has been deprecated. Use AttachCustomReticle(IXRInteractor) instead.
Awake()
virtual void UnityEngine.XR.Interaction.Toolkit.XRBaseInteractable.Awake () protected virtual
See MonoBehaviour.
Reimplemented in UnityEngine.XR.Interaction.Toolkit.XRGrabInteractable, and UnityEngine.XR.Interaction.Toolkit.BaseTeleportationInteractable.
CaptureAttachPose()
void UnityEngine.XR.Interaction.Toolkit.XRBaseInteractable.CaptureAttachPose (IXRSelectInteractor interactor) protected
Capture the current Attach Transform pose. This method is automatically called by Unity to capture the pose during the moment of selection.
Parameters
interactor The specific Interactor as context to get the attachment point for.
Unity automatically calls this method during OnSelectEntering(SelectEnterEventArgs) and should not typically need to be called by a user.
See also
GetAttachPoseOnSelect, GetLocalAttachPoseOnSelect, XRBaseInteractor.CaptureAttachPose
Referenced by UnityEngine.XR.Interaction.Toolkit.XRBaseInteractable.OnSelectEntering().
GetAttachPoseOnSelect()
Pose UnityEngine.XR.Interaction.Toolkit.XRBaseInteractable.GetAttachPoseOnSelect (IXRSelectInteractor interactor)
Gets the world position and rotation of the Attach Transform captured during the moment of selection.
Parameters
interactor The specific Interactor as context to get the attachment point for.
Returns
Returns the world pose of the attachment point during the moment of selection, and otherwise the identity Pose if it was not selected by it during the current selection stack.
See also
GetLocalAttachPoseOnSelect, IXRInteractable.GetAttachTransform, IXRSelectInteractor.GetAttachPoseOnSelect
Implements UnityEngine.XR.Interaction.Toolkit.IXRSelectInteractable.
GetAttachTransform()
virtual Transform UnityEngine.XR.Interaction.Toolkit.XRBaseInteractable.GetAttachTransform (IXRInteractor interactor) virtual
Gets the Transform that serves as the attachment point for a given Interactor.
Parameters
interactor The specific Interactor as context to get the attachment point for.
Returns
Returns the attachment point Transform.
See also
IXRInteractor.GetAttachTransform
This should typically return the Transform of a child GameObject or the transform itself.
Implements UnityEngine.XR.Interaction.Toolkit.IXRInteractable.
Reimplemented in UnityEngine.XR.Interaction.Toolkit.XRGrabInteractable.
Referenced by UnityEngine.XR.Interaction.Toolkit.XRBaseInteractable.CaptureAttachPose().
GetDistanceSqrToInteractor() [1/2]
virtual float UnityEngine.XR.Interaction.Toolkit.XRBaseInteractable.GetDistanceSqrToInteractor (IXRInteractor interactor) virtual
Calculates squared distance to an Interactor (based on colliders).
Parameters
interactor Interactor to calculate distance against.
Returns
Returns the minimum squared distance between the Interactor and this Interactable's colliders.
Implements UnityEngine.XR.Interaction.Toolkit.IXRInteractable.
GetDistanceSqrToInteractor() [2/2]
virtual float UnityEngine.XR.Interaction.Toolkit.XRBaseInteractable.GetDistanceSqrToInteractor (XRBaseInteractor interactor) virtual
(Deprecated) Calculates distance squared to interactor (based on colliders).
Parameters
interactor Interactor to calculate distance against.
Returns
Returns the minimum distance between the interactor and this interactable's colliders.
GetDistanceSqrToInteractor(XRBaseInteractor) has been deprecated. Use GetDistanceSqrToInteractor(IXRInteractor) instead.
GetLocalAttachPoseOnSelect()
Pose UnityEngine.XR.Interaction.Toolkit.XRBaseInteractable.GetLocalAttachPoseOnSelect (IXRSelectInteractor interactor)
Gets the local position and rotation of the Attach Transform captured during the moment of selection.
Parameters
interactor The specific Interactor as context to get the attachment point for.
Returns
Returns the local pose of the attachment point during the moment of selection, and otherwise the identity Pose if it was not selected by it during the current selection stack.
See also
GetAttachPoseOnSelect, IXRInteractable.GetAttachTransform, IXRSelectInteractor.GetLocalAttachPoseOnSelect
Implements UnityEngine.XR.Interaction.Toolkit.IXRSelectInteractable.
IsHoverableBy() [1/2]
virtual bool UnityEngine.XR.Interaction.Toolkit.XRBaseInteractable.IsHoverableBy (IXRHoverInteractor interactor) virtual
Determines if a given Interactor can hover over this Interactable.
Parameters
interactor Interactor to check for a valid hover state with.
Returns
Returns true if hovering is valid this frame. Returns false if not.
See also
IXRHoverInteractor.CanHover
Implements UnityEngine.XR.Interaction.Toolkit.IXRHoverInteractable.
IsHoverableBy() [2/2]
virtual bool UnityEngine.XR.Interaction.Toolkit.XRBaseInteractable.IsHoverableBy (XRBaseInteractor interactor) virtual
(Deprecated) Determines if this interactable can be hovered by a given interactor.
Parameters
interactor Interactor to check for a valid hover state with.
Returns
Returns true if hovering is valid this frame. Returns false if not.
See also
XRBaseInteractor.CanHover(XRBaseInteractable)
IsHoverableBy(XRBaseInteractor) has been deprecated. Use IsHoverableBy(IXRHoverInteractor) instead.
IsSelectableBy() [1/2]
virtual bool UnityEngine.XR.Interaction.Toolkit.XRBaseInteractable.IsSelectableBy (IXRSelectInteractor interactor) virtual
Determines if a given Interactor can select this Interactable.
Parameters
interactor Interactor to check for a valid selection with.
Returns
Returns true if selection is valid this frame. Returns false if not.
See also
IXRSelectInteractor.CanSelect
Implements UnityEngine.XR.Interaction.Toolkit.IXRSelectInteractable.
IsSelectableBy() [2/2]
virtual bool UnityEngine.XR.Interaction.Toolkit.XRBaseInteractable.IsSelectableBy (XRBaseInteractor interactor) virtual
(Deprecated) Determines if a given Interactor can select this Interactable.
Parameters
interactor Interactor to check for a valid selection with.
Returns
Returns true if selection is valid this frame. Returns false if not.
See also
XRBaseInteractor.CanSelect(XRBaseInteractable)
IsSelectableBy(XRBaseInteractor) has been deprecated. Use IsSelectableBy(IXRSelectInteractor) instead.
OnActivate()
virtual void UnityEngine.XR.Interaction.Toolkit.XRBaseInteractable.OnActivate (XRBaseInteractor interactor) protected virtual
(Deprecated) The XRBaseControllerInteractor calls this method when the Interactor begins an activation event on this Interactable.
Parameters
interactor Interactor that is sending the activate event.
See also
OnDeactivate
OnActivate(XRBaseInteractor) has been deprecated. Use OnActivated(ActivateEventArgs) instead.
Referenced by UnityEngine.XR.Interaction.Toolkit.XRBaseInteractable.OnActivated().
OnActivated()
virtual void UnityEngine.XR.Interaction.Toolkit.XRBaseInteractable.OnActivated (ActivateEventArgs args) protected virtual
XRBaseControllerInteractor calls this method when the Interactor begins an activation event on this Interactable.
Parameters
args Event data containing the Interactor that is sending the activate event.
args is only valid during this method call, do not hold a reference to it.
See also
OnDeactivated
Implements UnityEngine.XR.Interaction.Toolkit.IXRActivateInteractable.
Reimplemented in UnityEngine.XR.Interaction.Toolkit.BaseTeleportationInteractable.
OnDeactivate()
virtual void UnityEngine.XR.Interaction.Toolkit.XRBaseInteractable.OnDeactivate (XRBaseInteractor interactor) protected virtual
(Deprecated) The XRBaseControllerInteractor calls this method when the Interactor ends an activation event on this Interactable.
Parameters
interactor Interactor that is sending the deactivate event.
See also
OnActivate
OnDeactivate(XRBaseInteractor) has been deprecated. Use OnDeactivated(DeactivateEventArgs) instead.
Referenced by UnityEngine.XR.Interaction.Toolkit.XRBaseInteractable.OnDeactivated().
OnDeactivated()
virtual void UnityEngine.XR.Interaction.Toolkit.XRBaseInteractable.OnDeactivated (DeactivateEventArgs args) protected virtual
XRBaseControllerInteractor calls this method when the Interactor ends an activation event on this Interactable.
Parameters
args Event data containing the Interactor that is sending the deactivate event.
args is only valid during this method call, do not hold a reference to it.
See also
OnActivated
Implements UnityEngine.XR.Interaction.Toolkit.IXRActivateInteractable.
Reimplemented in UnityEngine.XR.Interaction.Toolkit.BaseTeleportationInteractable.
OnDestroy()
virtual void UnityEngine.XR.Interaction.Toolkit.XRBaseInteractable.OnDestroy () protected virtual
See MonoBehaviour.
OnDisable()
virtual void UnityEngine.XR.Interaction.Toolkit.XRBaseInteractable.OnDisable () protected virtual
See MonoBehaviour.
OnEnable()
virtual void UnityEngine.XR.Interaction.Toolkit.XRBaseInteractable.OnEnable () protected virtual
See MonoBehaviour.
OnHoverEntered() [1/2]
virtual void UnityEngine.XR.Interaction.Toolkit.XRBaseInteractable.OnHoverEntered (HoverEnterEventArgs args) protected virtual
The XRInteractionManager calls this method when the Interactor first initiates hovering over an Interactable in a second pass.
Parameters
args Event data containing the Interactor that is initiating the hover.
args is only valid during this method call, do not hold a reference to it.
See also
OnHoverExited(HoverExitEventArgs)
Implements UnityEngine.XR.Interaction.Toolkit.IXRHoverInteractable.
OnHoverEntered() [2/2]
virtual void UnityEngine.XR.Interaction.Toolkit.XRBaseInteractable.OnHoverEntered (XRBaseInteractor interactor) protected virtual
(Deprecated) The XRInteractionManager calls this method when the Interactor first initiates hovering over an Interactable in a second pass.
Parameters
interactor Interactor that is initiating the hover.
See also
OnHoverExited(XRBaseInteractor)
OnHoverEntered(XRBaseInteractor) has been deprecated. Use OnHoverEntered(HoverEnterEventArgs) instead.
OnHoverEntering() [1/2]
virtual void UnityEngine.XR.Interaction.Toolkit.XRBaseInteractable.OnHoverEntering (HoverEnterEventArgs args) protected virtual
The XRInteractionManager calls this method right before the Interactor first initiates hovering over an Interactable in a first pass.
Parameters
args Event data containing the Interactor that is initiating the hover.
args is only valid during this method call, do not hold a reference to it.
See also
OnHoverEntered(HoverEnterEventArgs)
Implements UnityEngine.XR.Interaction.Toolkit.IXRHoverInteractable.
OnHoverEntering() [2/2]
virtual void UnityEngine.XR.Interaction.Toolkit.XRBaseInteractable.OnHoverEntering (XRBaseInteractor interactor) protected virtual
(Deprecated) The XRInteractionManager calls this method right before the Interactor first initiates hovering over an Interactable in a first pass.
Parameters
interactor Interactor that is initiating the hover.
See also
OnHoverEntered(XRBaseInteractor)
OnHoverEntering(XRBaseInteractor) has been deprecated. Use OnHoverEntering(HoverEnterEventArgs) instead.
OnHoverExited() [1/2]
virtual void UnityEngine.XR.Interaction.Toolkit.XRBaseInteractable.OnHoverExited (HoverExitEventArgs args) protected virtual
The XRInteractionManager calls this method when the Interactor ends hovering over an Interactable in a second pass.
Parameters
args Event data containing the Interactor that is ending the hover.
args is only valid during this method call, do not hold a reference to it.
See also
OnHoverEntered(HoverEnterEventArgs)
Implements UnityEngine.XR.Interaction.Toolkit.IXRHoverInteractable.
OnHoverExited() [2/2]
virtual void UnityEngine.XR.Interaction.Toolkit.XRBaseInteractable.OnHoverExited (XRBaseInteractor interactor) protected virtual
(Deprecated) The XRInteractionManager calls this method when the Interactor ends hovering over an Interactable in a second pass.
Parameters
interactor Interactor that is ending the hover.
See also
OnHoverEntered(XRBaseInteractor)
OnHoverExited(XRBaseInteractor) has been deprecated. Use OnHoverExited(HoverExitEventArgs) instead.
OnHoverExiting() [1/2]
virtual void UnityEngine.XR.Interaction.Toolkit.XRBaseInteractable.OnHoverExiting (HoverExitEventArgs args) protected virtual
The XRInteractionManager calls this method right before the Interactor ends hovering over an Interactable in a first pass.
Parameters
args Event data containing the Interactor that is ending the hover.
args is only valid during this method call, do not hold a reference to it.
See also
OnHoverExited(HoverExitEventArgs)
Implements UnityEngine.XR.Interaction.Toolkit.IXRHoverInteractable.
OnHoverExiting() [2/2]
virtual void UnityEngine.XR.Interaction.Toolkit.XRBaseInteractable.OnHoverExiting (XRBaseInteractor interactor) protected virtual
(Deprecated) The XRInteractionManager calls this method right before the Interactor ends hovering over an Interactable in a first pass.
Parameters
interactor Interactor that is ending the hover.
See also
OnHoverExited(XRBaseInteractor)
OnHoverExiting(XRBaseInteractor) has been deprecated. Use OnHoverExiting(HoverExitEventArgs) instead.
OnRegistered()
virtual void UnityEngine.XR.Interaction.Toolkit.XRBaseInteractable.OnRegistered (InteractableRegisteredEventArgs args) protected virtual
The XRInteractionManager calls this method when this Interactable is registered with it.
Parameters
args Event data containing the Interaction Manager that registered this Interactable.
args is only valid during this method call, do not hold a reference to it.
See also
XRInteractionManager.RegisterInteractable(IXRInteractable)
Implements UnityEngine.XR.Interaction.Toolkit.IXRInteractable.
OnSelectCanceled()
virtual void UnityEngine.XR.Interaction.Toolkit.XRBaseInteractable.OnSelectCanceled (XRBaseInteractor interactor) protected virtual
(Deprecated) The XRInteractionManager calls this method while an Interactor selects this Interactable when either is unregistered (such as from being disabled or destroyed) in a second pass.
Parameters
interactor Interactor that is ending the selection.
See also
OnSelectEntered(XRBaseInteractor), OnSelectExited(XRBaseInteractor), OnSelectCanceling
OnSelectCanceled(XRBaseInteractor) has been deprecated. Use OnSelectExited(SelectExitEventArgs) instead.
Referenced by UnityEngine.XR.Interaction.Toolkit.XRBaseInteractable.OnSelectExited().
OnSelectCanceling()
virtual void UnityEngine.XR.Interaction.Toolkit.XRBaseInteractable.OnSelectCanceling (XRBaseInteractor interactor) protected virtual
(Deprecated) The XRInteractionManager calls this method while this Interactable is selected by an Interactor right before either is unregistered (such as from being disabled or destroyed) in a first pass.
Parameters
interactor Interactor that is ending the selection.
See also
OnSelectEntered(XRBaseInteractor), OnSelectExited(XRBaseInteractor), OnSelectCanceled
OnSelectCanceling(XRBaseInteractor) has been deprecated. Use OnSelectExiting(SelectExitEventArgs) instead.
Referenced by UnityEngine.XR.Interaction.Toolkit.XRBaseInteractable.OnSelectExiting().
OnSelectEntered() [1/2]
virtual void UnityEngine.XR.Interaction.Toolkit.XRBaseInteractable.OnSelectEntered (SelectEnterEventArgs args) protected virtual
The XRInteractionManager calls this method when the Interactor first initiates selection of an Interactable in a second pass.
Parameters
args Event data containing the Interactor that is initiating the selection.
args is only valid during this method call, do not hold a reference to it.
See also
OnSelectExited(SelectExitEventArgs)
Implements UnityEngine.XR.Interaction.Toolkit.IXRSelectInteractable.
Reimplemented in UnityEngine.XR.Interaction.Toolkit.BaseTeleportationInteractable.
OnSelectEntered() [2/2]
virtual void UnityEngine.XR.Interaction.Toolkit.XRBaseInteractable.OnSelectEntered (XRBaseInteractor interactor) protected virtual
(Deprecated) The XRInteractionManager calls this method when the Interactor first initiates selection of an Interactable in a second pass.
Parameters
interactor Interactor that is initiating the selection.
See also
OnSelectExited(XRBaseInteractor), OnSelectCanceled
OnSelectEntered(XRBaseInteractor) has been deprecated. Use OnSelectEntered(SelectEnterEventArgs) instead.
OnSelectEntering() [1/2]
virtual void UnityEngine.XR.Interaction.Toolkit.XRBaseInteractable.OnSelectEntering (SelectEnterEventArgs args) protected virtual
The XRInteractionManager calls this method right before the Interactor first initiates selection of an Interactable in a first pass.
Parameters
args Event data containing the Interactor that is initiating the selection.
args is only valid during this method call, do not hold a reference to it.
See also
OnSelectEntered(SelectEnterEventArgs)
Implements UnityEngine.XR.Interaction.Toolkit.IXRSelectInteractable.
Reimplemented in UnityEngine.XR.Interaction.Toolkit.XRGrabInteractable.
OnSelectEntering() [2/2]
virtual void UnityEngine.XR.Interaction.Toolkit.XRBaseInteractable.OnSelectEntering (XRBaseInteractor interactor) protected virtual
(Deprecated) The XRInteractionManager calls this method right before the Interactor first initiates selection of an Interactable in a first pass.
Parameters
interactor Interactor that is initiating the selection.
See also
OnSelectEntered(XRBaseInteractor)
OnSelectEntering(XRBaseInteractor) has been deprecated. Use OnSelectEntering(SelectEnterEventArgs) instead.
OnSelectExited() [1/2]
virtual void UnityEngine.XR.Interaction.Toolkit.XRBaseInteractable.OnSelectExited (SelectExitEventArgs args) protected virtual
The XRInteractionManager calls this method when the Interactor ends selection of an Interactable in a second pass.
Parameters
args Event data containing the Interactor that is ending the selection.
args is only valid during this method call, do not hold a reference to it.
See also
OnSelectEntered(SelectEnterEventArgs)
Implements UnityEngine.XR.Interaction.Toolkit.IXRSelectInteractable.
Reimplemented in UnityEngine.XR.Interaction.Toolkit.BaseTeleportationInteractable.
OnSelectExited() [2/2]
virtual void UnityEngine.XR.Interaction.Toolkit.XRBaseInteractable.OnSelectExited (XRBaseInteractor interactor) protected virtual
(Deprecated) The XRInteractionManager calls this method when the Interactor ends selection of an Interactable in a second pass.
Parameters
interactor Interactor that is ending the selection.
See also
OnSelectEntered(XRBaseInteractor), OnSelectCanceled
OnSelectExited(XRBaseInteractor) has been deprecated. Use OnSelectExited(SelectExitEventArgs) instead.
OnSelectExiting() [1/2]
virtual void UnityEngine.XR.Interaction.Toolkit.XRBaseInteractable.OnSelectExiting (SelectExitEventArgs args) protected virtual
The XRInteractionManager calls this method right before the Interactor ends selection of an Interactable in a first pass.
Parameters
args Event data containing the Interactor that is ending the selection.
args is only valid during this method call, do not hold a reference to it.
See also
OnSelectExited(SelectExitEventArgs)
Implements UnityEngine.XR.Interaction.Toolkit.IXRSelectInteractable.
Reimplemented in UnityEngine.XR.Interaction.Toolkit.XRGrabInteractable.
OnSelectExiting() [2/2]
virtual void UnityEngine.XR.Interaction.Toolkit.XRBaseInteractable.OnSelectExiting (XRBaseInteractor interactor) protected virtual
(Deprecated) The XRInteractionManager calls this method right before the Interactor ends selection of an Interactable in a first pass.
Parameters
interactor Interactor that is ending the selection.
See also
OnSelectExited(XRBaseInteractor)
OnSelectExiting(XRBaseInteractor) has been deprecated. Use OnSelectExiting(SelectExitEventArgs) instead.
OnUnregistered()
virtual void UnityEngine.XR.Interaction.Toolkit.XRBaseInteractable.OnUnregistered (InteractableUnregisteredEventArgs args) protected virtual
The XRInteractionManager calls this method when this Interactable is unregistered from it.
Parameters
args Event data containing the Interaction Manager that unregistered this Interactable.
args is only valid during this method call, do not hold a reference to it.
See also
XRInteractionManager.UnregisterInteractable(IXRInteractable)
Implements UnityEngine.XR.Interaction.Toolkit.IXRInteractable.
ProcessInteractable()
virtual void UnityEngine.XR.Interaction.Toolkit.XRBaseInteractable.ProcessInteractable (XRInteractionUpdateOrder::UpdatePhase updatePhase) virtual
The XRInteractionManager calls this method to update the Interactable.
Parameters
updatePhase The update phase this is called during.
Please see the XRInteractionManager and XRInteractionUpdateOrder.UpdatePhase documentation for more details on update order.
Implements UnityEngine.XR.Interaction.Toolkit.IXRInteractable.
Reimplemented in UnityEngine.XR.Interaction.Toolkit.XRGrabInteractable.
RemoveCustomReticle() [1/2]
virtual void UnityEngine.XR.Interaction.Toolkit.XRBaseInteractable.RemoveCustomReticle (IXRInteractor interactor) virtual
Removes the custom reticle from the Interactor.
Parameters
interactor Interactor that is no longer interacting with this Interactable.
Referenced by UnityEngine.XR.Interaction.Toolkit.XRBaseInteractable.OnHoverExiting().
RemoveCustomReticle() [2/2]
virtual void UnityEngine.XR.Interaction.Toolkit.XRBaseInteractable.RemoveCustomReticle (XRBaseInteractor interactor) virtual
(Deprecated) Removes the custom reticle from the Interactor.
Parameters
interactor Interactor that is no longer interacting with this Interactable.
RemoveCustomReticle(XRBaseInteractor) has been deprecated. Use RemoveCustomReticle(IXRInteractor) instead.
Reset()
virtual void UnityEngine.XR.Interaction.Toolkit.XRBaseInteractable.Reset () protected virtual
See MonoBehaviour.
Reimplemented in UnityEngine.XR.Interaction.Toolkit.BaseTeleportationInteractable, and UnityEngine.XR.Interaction.Toolkit.TeleportationAnchor.
Property Documentation
activated
ActivateEvent UnityEngine.XR.Interaction.Toolkit.XRBaseInteractable.activated get set
The event that is called when the selecting Interactor activates this Interactable.Not to be confused with activating or deactivating a GameObject with GameObject.SetActive. This is a generic event when an Interactor wants to activate an Interactable, such as from a trigger pull on a controller.
The ActivateEventArgs passed to each listener is only valid while the event is invoked, do not hold a reference to it.
Implements UnityEngine.XR.Interaction.Toolkit.IXRActivateInteractable.
colliders
List<Collider> UnityEngine.XR.Interaction.Toolkit.XRBaseInteractable.colliders get
(Read Only) Colliders to use for interaction with this Interactable (if empty, will use any child Colliders).
Implements UnityEngine.XR.Interaction.Toolkit.IXRInteractable.
Referenced by UnityEngine.XR.Interaction.Toolkit.BaseTeleportationInteractable.GenerateTeleportRequest().
customReticle
GameObject UnityEngine.XR.Interaction.Toolkit.XRBaseInteractable.customReticle get set
The reticle that appears at the end of the line when valid.
deactivated
DeactivateEvent UnityEngine.XR.Interaction.Toolkit.XRBaseInteractable.deactivated get set
The event that is called when an Interactor deactivates this Interactable.Not to be confused with activating or deactivating a GameObject with GameObject.SetActive. This is a generic event when an Interactor wants to deactivate an Interactable, such as from a trigger release on a controller.
The DeactivateEventArgs passed to each listener is only valid while the event is invoked, do not hold a reference to it.
Implements UnityEngine.XR.Interaction.Toolkit.IXRActivateInteractable.
firstHoverEntered
HoverEnterEvent UnityEngine.XR.Interaction.Toolkit.XRBaseInteractable.firstHoverEntered get set
The event that is called only when the first Interactor begins hovering over this Interactable as the sole hovering Interactor. Subsequent Interactors that begin hovering over this Interactable will not cause this event to be invoked as long as any others are still hovering.The HoverEnterEventArgs passed to each listener is only valid while the event is invoked, do not hold a reference to it.
Implements UnityEngine.XR.Interaction.Toolkit.IXRHoverInteractable.
firstInteractorSelecting
IXRSelectInteractor UnityEngine.XR.Interaction.Toolkit.XRBaseInteractable.firstInteractorSelecting get
(Read Only) The first interactor that selected this interactable since not being selected by any interactor. The interactor may not currently be selecting this interactable, which would be the case when it released while multiple interactors were selecting this interactable.
See also
IXRSelectInteractor.firstInteractableSelected
Implements UnityEngine.XR.Interaction.Toolkit.IXRSelectInteractable.
Referenced by UnityEngine.XR.Interaction.Toolkit.XRBaseInteractable.OnSelectEntering(), and UnityEngine.XR.Interaction.Toolkit.XRBaseInteractable.OnSelectExited().
firstSelectEntered
SelectEnterEvent UnityEngine.XR.Interaction.Toolkit.XRBaseInteractable.firstSelectEntered get set
The event that is called only when the first Interactor begins selecting this Interactable as the sole selecting Interactor. Subsequent Interactors that begin selecting this Interactable will not cause this event to be invoked as long as any others are still selecting.The SelectEnterEventArgs passed to each listener is only valid while the event is invoked, do not hold a reference to it.
Implements UnityEngine.XR.Interaction.Toolkit.IXRSelectInteractable.
hoverEntered
HoverEnterEvent UnityEngine.XR.Interaction.Toolkit.XRBaseInteractable.hoverEntered get set
The event that is called when an Interactor begins hovering over this Interactable.The HoverEnterEventArgs passed to each listener is only valid while the event is invoked, do not hold a reference to it.
Implements UnityEngine.XR.Interaction.Toolkit.IXRHoverInteractable.
hoverExited
HoverExitEvent UnityEngine.XR.Interaction.Toolkit.XRBaseInteractable.hoverExited get set
The event that is called when an Interactor ends hovering over this Interactable.The HoverExitEventArgs passed to each listener is only valid while the event is invoked, do not hold a reference to it.
Implements UnityEngine.XR.Interaction.Toolkit.IXRHoverInteractable.
hoveringInteractors
List<XRBaseInteractor> UnityEngine.XR.Interaction.Toolkit.XRBaseInteractable.hoveringInteractors = new List<XRBaseInteractor>() get
(Deprecated) (Read Only) The list of interactors that are hovering on this interactable.
See also
isHovered, XRBaseInteractor.hoverTargets
Referenced by UnityEngine.XR.Interaction.Toolkit.XRBaseInteractable.OnHoverEntered(), UnityEngine.XR.Interaction.Toolkit.XRBaseInteractable.OnHoverEntering(), UnityEngine.XR.Interaction.Toolkit.XRBaseInteractable.OnHoverExited(), and UnityEngine.XR.Interaction.Toolkit.XRBaseInteractable.OnHoverExiting().
interactionLayerMask
LayerMask UnityEngine.XR.Interaction.Toolkit.XRBaseInteractable.interactionLayerMask get set
(Deprecated) Allows interaction with Interactors whose Interaction Layer Mask overlaps with any Layer in this Interaction Layer Mask.
See also
XRBaseInteractor.interactionLayerMask
interactionLayerMask has been deprecated. Use interactionLayers instead.
interactionLayers
InteractionLayerMask UnityEngine.XR.Interaction.Toolkit.XRBaseInteractable.interactionLayers get set
Allows interaction with Interactors whose Interaction Layer Mask overlaps with any Layer in this Interaction Layer Mask.
See also
IXRInteractor.interactionLayers, IsHoverableBy(IXRHoverInteractor), IsSelectableBy(IXRSelectInteractor)
(Read Only) Allows interaction with Interactors whose Interaction Layer Mask overlaps with any Layer in this Interaction Layer Mask.
See also
IXRInteractor.interactionLayers
Implements UnityEngine.XR.Interaction.Toolkit.IXRInteractable.
interactionManager
XRInteractionManager UnityEngine.XR.Interaction.Toolkit.XRBaseInteractable.interactionManager get set
The XRInteractionManager that this Interactable will communicate with (will find one if null).
interactorsHovering
List<IXRHoverInteractor> UnityEngine.XR.Interaction.Toolkit.XRBaseInteractable.interactorsHovering = new List<IXRHoverInteractor>() get
(Read Only) The list of Interactors that are hovering on this Interactable (may by empty).You should treat this as a read only view of the list and should not modify it. Unity exposes this as a List<T> rather than an IReadOnlyList<T> to avoid GC Allocations when enumerating the list.
Implements UnityEngine.XR.Interaction.Toolkit.IXRHoverInteractable.
Referenced by UnityEngine.XR.Interaction.Toolkit.XRBaseInteractable.OnHoverEntered(), UnityEngine.XR.Interaction.Toolkit.XRBaseInteractable.OnHoverEntering(), UnityEngine.XR.Interaction.Toolkit.XRBaseInteractable.OnHoverExited(), and UnityEngine.XR.Interaction.Toolkit.XRBaseInteractable.OnHoverExiting().
interactorsSelecting
List<IXRSelectInteractor> UnityEngine.XR.Interaction.Toolkit.XRBaseInteractable.interactorsSelecting = new List<IXRSelectInteractor>() get
(Read Only) The list of Interactors currently selecting this Interactable (may by empty).You should treat this as a read only view of the list and should not modify it. It is exposed as a List<T> rather than an IReadOnlyList<T> to avoid GC Allocations when enumerating the list.
Implements UnityEngine.XR.Interaction.Toolkit.IXRSelectInteractable.
Referenced by UnityEngine.XR.Interaction.Toolkit.XRGrabInteractable.Grab(), UnityEngine.XR.Interaction.Toolkit.XRBaseInteractable.OnSelectEntered(), UnityEngine.XR.Interaction.Toolkit.XRBaseInteractable.OnSelectEntering(), UnityEngine.XR.Interaction.Toolkit.XRBaseInteractable.OnSelectExited(), UnityEngine.XR.Interaction.Toolkit.XRBaseInteractable.OnSelectExiting(), and UnityEngine.XR.Interaction.Toolkit.XRGrabInteractable.ProcessInteractable().
isHovered
bool UnityEngine.XR.Interaction.Toolkit.XRBaseInteractable.isHovered get
(Read Only) Indicates whether an Interactor currently hovers over this Interactable.In other words, returns whether interactorsHovering contains any interactors.
interactorsHovering.Count > 0
Implements UnityEngine.XR.Interaction.Toolkit.IXRHoverInteractable.
isSelected
bool UnityEngine.XR.Interaction.Toolkit.XRBaseInteractable.isSelected get
(Read Only) Indicates whether this interactable is currently being selected by any interactor.In other words, returns whether interactorsSelecting contains any interactors.
interactorsSelecting.Count > 0
Implements UnityEngine.XR.Interaction.Toolkit.IXRSelectInteractable.
Referenced by UnityEngine.XR.Interaction.Toolkit.XRGrabInteractable.ProcessInteractable(), and UnityEngine.XR.Interaction.Toolkit.XRGrabInteractable.SetupRigidbodyDrop().
lastHoverExited
HoverExitEvent UnityEngine.XR.Interaction.Toolkit.XRBaseInteractable.lastHoverExited get set
The event that is called only when the last remaining hovering Interactor ends hovering over this Interactable.The HoverExitEventArgs passed to each listener is only valid while the event is invoked, do not hold a reference to it.
Implements UnityEngine.XR.Interaction.Toolkit.IXRHoverInteractable.
lastSelectExited
SelectExitEvent UnityEngine.XR.Interaction.Toolkit.XRBaseInteractable.lastSelectExited get set
The event that is called only when the last remaining selecting Interactor ends selecting this Interactable.The SelectExitEventArgs passed to each listener is only valid while the event is invoked, do not hold a reference to it.
Implements UnityEngine.XR.Interaction.Toolkit.IXRSelectInteractable.
onActivate
XRInteractableEvent UnityEngine.XR.Interaction.Toolkit.XRBaseInteractable.onActivate get set
(Deprecated) Gets or sets the event that Unity calls when an Interactor activates this selected Interactable.
onActivate has been deprecated. Use activated instead.
onDeactivate
XRInteractableEvent UnityEngine.XR.Interaction.Toolkit.XRBaseInteractable.onDeactivate get set
(Deprecated) Gets or sets the event that Unity calls when an Interactor deactivates this selected Interactable.
onDeactivate has been deprecated. Use deactivated instead.
onFirstHoverEnter
XRInteractableEvent UnityEngine.XR.Interaction.Toolkit.XRBaseInteractable.onFirstHoverEnter get
(Deprecated) Unity calls this only when the first Interactor begins hovering over this Interactable.
onFirstHoverEnter has been deprecated. Use onFirstHoverEntered instead.
onFirstHoverEntered
XRInteractableEvent UnityEngine.XR.Interaction.Toolkit.XRBaseInteractable.onFirstHoverEntered get set
(Deprecated) Gets or sets the event that Unity calls only when the first Interactor begins hovering over this Interactable as the sole hovering Interactor. Subsequent Interactors that begin hovering over this Interactable will not cause this event to be invoked as long as any others are still hovering.
onFirstHoverEntered has been deprecated. Use firstHoverEntered with updated signature instead.
onHoverEnter
XRInteractableEvent UnityEngine.XR.Interaction.Toolkit.XRBaseInteractable.onHoverEnter get
(Deprecated) Unity calls this every time an Interactor begins hovering over this Interactable.
onHoverEnter has been deprecated. Use onHoverEntered instead.
onHoverEntered
XRInteractableEvent UnityEngine.XR.Interaction.Toolkit.XRBaseInteractable.onHoverEntered get set
(Deprecated) Gets or sets the event that Unity calls when an Interactor begins hovering over this Interactable.
onHoverEntered has been deprecated. Use hoverEntered instead.
onHoverExit
XRInteractableEvent UnityEngine.XR.Interaction.Toolkit.XRBaseInteractable.onHoverExit get
(Deprecated) Unity calls this every time an Interactor ends hovering over this Interactable.
onHoverExit has been deprecated. Use onHoverExited instead.
onHoverExited
XRInteractableEvent UnityEngine.XR.Interaction.Toolkit.XRBaseInteractable.onHoverExited get set
(Deprecated) Gets or sets the event that Unity calls when an Interactor ends hovering over this Interactable.
onHoverExited has been deprecated. Use hoverExited hoverExited with updated signature instead.
onLastHoverExit
XRInteractableEvent UnityEngine.XR.Interaction.Toolkit.XRBaseInteractable.onLastHoverExit get
(Deprecated) Unity calls this only when the last Interactor ends hovering over this Interactable.
onLastHoverExit has been deprecated. Use onLastHoverExited instead.
onLastHoverExited
XRInteractableEvent UnityEngine.XR.Interaction.Toolkit.XRBaseInteractable.onLastHoverExited get set
(Deprecated) Gets or sets the event that Unity calls only when the last remaining hovering Interactor ends hovering over this Interactable.
onLastHoverExited has been deprecated. Use lastHoverExited with updated signature instead.
onSelectCancel
XRInteractableEvent UnityEngine.XR.Interaction.Toolkit.XRBaseInteractable.onSelectCancel get
(Deprecated) Unity calls this when the Interactor selecting this Interactable is disabled or destroyed.
onSelectCancel has been deprecated. Use onSelectCanceled instead.
onSelectCanceled
XRInteractableEvent UnityEngine.XR.Interaction.Toolkit.XRBaseInteractable.onSelectCanceled get set
(Deprecated) Gets or sets the event that Unity calls when this Interactable is selected by an Interactor and either is unregistered (such as from being disabled or destroyed).
onSelectCanceled has been deprecated. Use selectExited with updated signature and check for SelectExitEventArgs.isCanceled instead.
onSelectEnter
XRInteractableEvent UnityEngine.XR.Interaction.Toolkit.XRBaseInteractable.onSelectEnter get
(Deprecated) Unity calls this when an Interactor begins selecting this Interactable.
onSelectEnter has been deprecated. Use onSelectEntered instead.
onSelectEntered
XRInteractableEvent UnityEngine.XR.Interaction.Toolkit.XRBaseInteractable.onSelectEntered get set
(Deprecated) Gets or sets the event that Unity calls when an Interactor begins selecting this Interactable.
onSelectEntered has been deprecated. Use selectEntered with updated signature instead.
onSelectExit
XRInteractableEvent UnityEngine.XR.Interaction.Toolkit.XRBaseInteractable.onSelectExit get
(Deprecated) Unity calls this when an Interactor ends selecting this Interactable.
onSelectExit has been deprecated. Use onSelectExited instead.
onSelectExited
XRInteractableEvent UnityEngine.XR.Interaction.Toolkit.XRBaseInteractable.onSelectExited get set
(Deprecated) Gets or sets the event that Unity calls when an Interactor ends selecting this Interactable.
onSelectExited has been deprecated. Use selectExited with updated signature and check for !SelectExitEventArgs.isCanceled instead.
selectEntered
SelectEnterEvent UnityEngine.XR.Interaction.Toolkit.XRBaseInteractable.selectEntered get set
The event that is called when an Interactor begins selecting this Interactable.The SelectEnterEventArgs passed to each listener is only valid while the event is invoked, do not hold a reference to it.
Implements UnityEngine.XR.Interaction.Toolkit.IXRSelectInteractable.
selectExited
SelectExitEvent UnityEngine.XR.Interaction.Toolkit.XRBaseInteractable.selectExited get set
The event that is called when an Interactor ends selecting this Interactable.The SelectExitEventArgs passed to each listener is only valid while the event is invoked, do not hold a reference to it.
Implements UnityEngine.XR.Interaction.Toolkit.IXRSelectInteractable.
selectingInteractor
XRBaseInteractor UnityEngine.XR.Interaction.Toolkit.XRBaseInteractable.selectingInteractor get protected set
(Deprecated) The Interactor selecting this Interactable (may be null).
Unity automatically sets this value during OnSelectEntering(SelectEnterEventArgs) and OnSelectExiting(SelectExitEventArgs) and should not typically need to be set by a user. The setter is protected to allow for rare scenarios where a derived class needs to control this value. Changing this value does not invoke select events.
selectingInteractor has been deprecated. Use interactorsSelecting or isSelected instead.
See also
isSelected, XRBaseInteractor.selectTarget
selectMode
InteractableSelectMode UnityEngine.XR.Interaction.Toolkit.XRBaseInteractable.selectMode get set
Indicates the selection policy of an Interactable.
See also
InteractableSelectMode
Implements UnityEngine.XR.Interaction.Toolkit.IXRSelectInteractable.
Referenced by UnityEngine.XR.Interaction.Toolkit.BaseTeleportationInteractable.Reset().
Event Documentation
registered
Action<InteractableRegisteredEventArgs> UnityEngine.XR.Interaction.Toolkit.XRBaseInteractable.registered
Referenced by UnityEngine.XR.Interaction.Toolkit.XRBaseInteractable.OnRegistered().
unregistered
Action<InteractableUnregisteredEventArgs> UnityEngine.XR.Interaction.Toolkit.XRBaseInteractable.unregistered
Referenced by UnityEngine.XR.Interaction.Toolkit.XRBaseInteractable.OnUnregistered().
The documentation for this class was generated from the following files:
C:/Users/Lykos/Desktop/Projects/Capstone/VRGames/Library/PackageCache/com.unity.xr.interaction.toolkit@2.0.2/Runtime/Interaction/Interactables/XRBaseInteractable.cs
C:/Users/Lykos/Desktop/Projects/Capstone/VRGames/Library/PackageCache/com.unity.xr.interaction.toolkit@2.0.2/Runtime/Interaction/Interactables/XRBaseInteractable.deprecated.cs