VRGames: Oculus.Platform.Packet Class Reference
Oculus.Platform.Packet Class Reference sealed
Public Member Functions
Packet (IntPtr packetHandle)
ulong ReadBytes (byte[] destination)
void Dispose ()
Properties
UInt64 SenderID [get]
ulong Size [get]
SendPolicy Policy [get]
Constructor & Destructor Documentation
Packet()
Oculus.Platform.Packet.Packet (IntPtr packetHandle)
Member Function Documentation
Dispose()
void Oculus.Platform.Packet.Dispose ()
ReadBytes()
ulong Oculus.Platform.Packet.ReadBytes (byte[] destination)
Copies all the bytes in the payload into byte[] destination. ex: Package package ... byte[] destination = new byte[package.Size]; package.ReadBytes(destination);
Referenced by Oculus.Platform.Samples.VrVoiceChat.P2PManager.GetRemoteHeadTransform(), P2PManager.GetRemotePackets(), and Oculus.Platform.Samples.VrHoops.P2PManager.UpdateNetwork().
Property Documentation
Policy
SendPolicy Oculus.Platform.Packet.Policy get
SenderID
UInt64 Oculus.Platform.Packet.SenderID get
Referenced by Oculus.Platform.Samples.VrHoops.P2PManager.UpdateNetwork().
Size
ulong Oculus.Platform.Packet.Size get
Referenced by Oculus.Platform.Samples.VrVoiceChat.P2PManager.GetRemoteHeadTransform(), P2PManager.GetRemotePackets(), and Oculus.Platform.Samples.VrHoops.P2PManager.UpdateNetwork().
The documentation for this class was generated from the following file:
C:/Users/Lykos/Desktop/Projects/Capstone/VRGames/Assets/ThirdParty/Oculus/Platform/Scripts/Packet.cs