VRGames: UnityEngine.XR.Management.XRManagerSettings Class Reference
UnityEngine.XR.Management.XRManagerSettings Class Reference sealed
Class to handle active loader and subsystem management for XR. This class is to be added as a ScriptableObject asset in your project and should only be referenced by the XRGeneralSettings instance for its use.
Public Member Functions
T ActiveLoaderAs< T > ()
Return the current active loader, cast to the requested type. Useful shortcut when you need to get the active loader as something less generic than XRLoader.
void InitializeLoaderSync ()
Iterate over the configured list of loaders and attempt to initialize each one. The first one that succeeds is set as the active loader and initialization immediately terminates.
IEnumerator InitializeLoader ()
Iterate over the configured list of loaders and attempt to initialize each one. The first one that succeeds is set as the active loader and initialization immediately terminates.
bool TryAddLoader (XRLoader loader, int index=-1)
Attempts to append the given loader to the list of loaders at the given index.
bool TryRemoveLoader (XRLoader loader)
Attempts to remove the first instance of a given loader from the list of loaders.
bool TrySetLoaders (List< XRLoader > reorderedLoaders)
Attempts to set the given loader list as the list of loaders managed by this instance.
void StartSubsystems ()
If there is an active loader, this will request the loader to start all the subsystems that it is managing.
void StopSubsystems ()
If there is an active loader, this will request the loader to stop all the subsystems that it is managing.
void DeinitializeLoader ()
If there is an active loader, this function will deinitialize it and remove the active loader instance from management. We will automatically call StopSubsystems prior to deinitialization to make sure that things are cleaned up appropriately.
Properties
bool automaticLoading [get, set]
Get and set Automatic Loading state for this manager. When this is true, the manager will automatically call InitializeLoader and DeinitializeLoader for you. When false automaticRunning is also set to false and remains that way. This means that disabling automatic loading disables all automatic behavior for the manager.
bool automaticRunning [get, set]
Get and set automatic running state for this manager. When set to true the manager will call StartSubsystems and StopSubsystems APIs at appropriate times. When set to false, or when automaticLoading is false then it is up to the user of the manager to handle that same functionality.
List< XRLoader > loaders [get]
List of loaders currently managed by this XR Manager instance.
IReadOnlyList< XRLoader > activeLoaders [get]
A shallow copy of the list of loaders currently managed by this XR Manager instance.
bool isInitializationComplete [get]
Read only boolean letting us know if initialization is completed. Because initialization is handled as a Coroutine, people taking advantage of the auto-lifecycle management of XRManager will need to wait for init to complete before checking for an ActiveLoader and calling StartSubsystems.
XRLoader activeLoader [get]
Detailed Description
Class to handle active loader and subsystem management for XR. This class is to be added as a ScriptableObject asset in your project and should only be referenced by the XRGeneralSettings instance for its use.
Given a list of loaders, it will attempt to load each loader in the given order. The first loader that is successful wins and all remaining loaders are ignored. The loader that succeeds is accessible through the activeLoader property on the manager.
Depending on configuration the XRManagerSettings instance will automatically manage the active loader at correct points in the application lifecycle. The user can override certain points in the active loader lifecycle and manually manage them by toggling the automaticLoading and automaticRunning properties. Disabling automaticLoading implies the the user is responsible for the full lifecycle of the XR session normally handled by the XRManagerSettings instance. Toggling this to false also toggles automaticRunning false.
Disabling automaticRunning only implies that the user is responsible for starting and stopping the activeLoader through the StartSubsystems and StopSubsystems APIs.
Automatic lifecycle management is executed as follows
Runtime Initialize -> InitializeLoader. The loader list will be iterated over and the first successful loader will be set as the active loader.
Start -> StartSubsystems. Ask the active loader to start all subsystems.
OnDisable -> StopSubsystems. Ask the active loader to stop all subsystems.
OnDestroy -> DeinitializeLoader. Deinitialize and remove the active loader.
Member Function Documentation
ActiveLoaderAs< T >()
T UnityEngine.XR.Management.XRManagerSettings.ActiveLoaderAs< T > ()
Return the current active loader, cast to the requested type. Useful shortcut when you need to get the active loader as something less generic than XRLoader.
Template Parameters
T Requested type of the loader
Returns
The active loader as requested type, or null.
Type Constraints
T : XRLoader
DeinitializeLoader()
void UnityEngine.XR.Management.XRManagerSettings.DeinitializeLoader ()
If there is an active loader, this function will deinitialize it and remove the active loader instance from management. We will automatically call StopSubsystems prior to deinitialization to make sure that things are cleaned up appropriately.
You must wait for isInitializationComplete to be set to tru prior to calling this API.
Upon return isInitializationComplete will be rest to false;
Referenced by UnityEngine.XR.Management.Tests.ManualLifetimeTests.CheckActivatedLoader(), and UnityEditor.XR.Management.Tests.DomainReloadTests.DomainReload().
InitializeLoader()
IEnumerator UnityEngine.XR.Management.XRManagerSettings.InitializeLoader ()
Iterate over the configured list of loaders and attempt to initialize each one. The first one that succeeds is set as the active loader and initialization immediately terminates.
When complete isInitializationComplete will be set to true. This will mark that it is safe to call other parts of the API. This does not guarantee that init successfully created a loader. For that you need to check that ActiveLoader is not null.
Note that there can only be one active loader. Any attempt to initialize a new active loader with one already set will cause a warning to be logged and immediate exit of this function.
Iteration is done asynchronously and this method must be called within the context of a Coroutine.
If manual initialization of XR is being done, this method can not be called before Start completes as it depends on graphics initialization within Unity completing.
Returns
Enumerator marking the next spot to continue execution at.
Referenced by UnityEngine.XR.Management.Tests.ManualLifetimeTests.CheckActivatedLoader(), and UnityEditor.XR.Management.Tests.DomainReloadTests.DomainReload().
InitializeLoaderSync()
void UnityEngine.XR.Management.XRManagerSettings.InitializeLoaderSync ()
Iterate over the configured list of loaders and attempt to initialize each one. The first one that succeeds is set as the active loader and initialization immediately terminates.
When complete isInitializationComplete will be set to true. This will mark that it is safe to call other parts of the API. This does not guarantee that init successfully created a loader. For that you need to check that ActiveLoader is not null.
Note that there can only be one active loader. Any attempt to initialize a new active loader with one already set will cause a warning to be logged and immediate exit of this function.
This method is synchronous and on return all state should be immediately checkable.
If manual initialization of XR is being done, this method can not be called before Start completes as it depends on graphics initialization within Unity completing.
StartSubsystems()
void UnityEngine.XR.Management.XRManagerSettings.StartSubsystems ()
If there is an active loader, this will request the loader to start all the subsystems that it is managing.
You must wait for isInitializationComplete to be set to true prior to calling this API.
StopSubsystems()
void UnityEngine.XR.Management.XRManagerSettings.StopSubsystems ()
If there is an active loader, this will request the loader to stop all the subsystems that it is managing.
You must wait for isInitializationComplete to be set to tru prior to calling this API.
Referenced by UnityEngine.XR.Management.XRManagerSettings.DeinitializeLoader().
TryAddLoader()
bool UnityEngine.XR.Management.XRManagerSettings.TryAddLoader (XRLoader loader, int index = -1)
Attempts to append the given loader to the list of loaders at the given index.
Parameters
loader The XRLoader to be added to this manager's instance of loaders.
index The index at which the given XRLoader should be added. If you set a negative or otherwise invalid index, the loader will be appended to the end of the list.
Returns
true if the loader is not a duplicate and was added to the list successfully, false otherwise.
This method behaves differently in the Editor and during runtime/Play mode. While your app runs in the Editor and not in Play mode, attempting to add an XRLoader will always succeed and register that loader's type internally. Attempting to add a loader during runtime/Play mode will trigger a check to see whether a loader of that type was registered. If the check is successful, the loader is added. If not, the loader is not added and the method returns false.
Referenced by UnityEditor.XR.Management.Metadata.XRPackageMetadataStore.AssignLoader(), UnityEditor.XR.Management.Tests.EditorActiveLoadersManipulationTests.CheckIfAttemptToAddDuplicateLoadersFails(), UnityEngine.XR.Management.Tests.RuntimeActiveLoadersManipulationTests.CheckIfAttemptToAddDuplicateLoadersFails(), UnityEngine.XR.Management.Tests.RuntimeActiveLoadersManipulationTests.CheckIfIllegalAddFails(), UnityEditor.XR.Management.Tests.EditorActiveLoadersManipulationTests.CheckIfLegalAddSucceeds(), UnityEngine.XR.Management.Tests.RuntimeActiveLoadersManipulationTests.CheckIfLegalAddSucceeds(), UnityEditor.XR.Management.Tests.EditorActiveLoadersManipulationTests.CheckIfRemoveAndReAddAtSameIndexWorks(), UnityEngine.XR.Management.Tests.RuntimeActiveLoadersManipulationTests.CheckIfRemoveAndReAddAtSameIndexWorks(), UnityEditor.XR.Management.Tests.EditorActiveLoadersManipulationTests.CheckThatEmptyingListRemovesAllRegisteredLoaders(), and UnityEngine.XR.Management.XRManagerSettings.TrySetLoaders().
TryRemoveLoader()
bool UnityEngine.XR.Management.XRManagerSettings.TryRemoveLoader (XRLoader loader)
Attempts to remove the first instance of a given loader from the list of loaders.
Parameters
loader The XRLoader to be removed from this manager's instance of loaders.
Returns
true if the loader was successfully removed from the list, false otherwise.
This method behaves differently in the Editor and during runtime/Play mode. During runtime/Play mode, the loader will be removed with no additional side effects if it is in the list managed by this instance. While in the Editor and not in Play mode, the loader will be removed if it exists and it will be unregistered from this instance and any attempts to add it during runtime/Play mode will fail. You can re-add the loader in the Editor while not in Play mode.
Referenced by UnityEditor.XR.Management.Tests.EditorActiveLoadersManipulationTests.CheckIfRemoveAndReAddAtSameIndexWorks(), UnityEngine.XR.Management.Tests.RuntimeActiveLoadersManipulationTests.CheckIfRemoveAndReAddAtSameIndexWorks(), UnityEditor.XR.Management.Tests.EditorActiveLoadersManipulationTests.CheckThatEmptyingListRemovesAllRegisteredLoaders(), and UnityEditor.XR.Management.Metadata.XRPackageMetadataStore.RemoveLoader().
TrySetLoaders()
bool UnityEngine.XR.Management.XRManagerSettings.TrySetLoaders (List< XRLoader > reorderedLoaders)
Attempts to set the given loader list as the list of loaders managed by this instance.
Parameters
reorderedLoaders The list of XRLoaders to be managed by this manager instance.
Returns
true if the loader list was set successfully, false otherwise.
This method behaves differently in the Editor and during runtime/Play mode. While in the Editor and not in Play mode, any attempts to set the list of loaders will succeed without any additional checks. During runtime/Play mode, the new loader list will be validated against the registered XRLoader types. If any loaders exist in the list that were not registered at startup, the attempt will fail.
Referenced by UnityEditor.XR.Management.Metadata.XRPackageMetadataStore.AssignLoader(), UnityEngine.XR.Management.Tests.ManualLifetimeTests.CheckActivatedLoader(), UnityEditor.XR.Management.Tests.EditorActiveLoadersManipulationTests.CheckIfAttemptsToSetLoaderListThatContainDuplicatesFails(), UnityEngine.XR.Management.Tests.RuntimeActiveLoadersManipulationTests.CheckIfAttemptsToSetLoaderListThatContainDuplicatesFails(), UnityEditor.XR.Management.Tests.EditorActiveLoadersManipulationTests.CheckIfIllegalSetLoaderListFails(), UnityEngine.XR.Management.Tests.RuntimeActiveLoadersManipulationTests.CheckIfIllegalSetLoaderListFails(), UnityEditor.XR.Management.Tests.EditorActiveLoadersManipulationTests.CheckIfLegalAddSucceeds(), UnityEngine.XR.Management.Tests.RuntimeActiveLoadersManipulationTests.CheckIfLegalAddSucceeds(), UnityEditor.XR.Management.Tests.EditorActiveLoadersManipulationTests.CheckIfSetLegalLoaderListWorks(), UnityEngine.XR.Management.Tests.RuntimeActiveLoadersManipulationTests.CheckIfSetLegalLoaderListWorks(), UnityEditor.XR.Management.Tests.EditorActiveLoadersManipulationTests.CheckThatEmptyingListRemovesAllRegisteredLoaders(), and UnityEngine.XR.Management.XRManagerSettings.TrySetLoaders().
Property Documentation
activeLoader
XRLoader UnityEngine.XR.Management.XRManagerSettings.activeLoader get
Referenced by UnityEngine.XR.Management.XRManagerSettings.ActiveLoaderAs< T >(), UnityEngine.XR.Management.Tests.ManualLifetimeTests.CheckActivatedLoader(), UnityEngine.XR.Management.XRManagerSettings.DeinitializeLoader(), UnityEditor.XR.Management.Tests.DomainReloadTests.DomainReload(), UnityEngine.XR.Management.XRManagerSettings.InitializeLoader(), UnityEngine.XR.Management.XRManagerSettings.InitializeLoaderSync(), UnityEngine.XR.Management.XRManagerSettings.StartSubsystems(), and UnityEngine.XR.Management.XRManagerSettings.StopSubsystems().
activeLoaders
IReadOnlyList<XRLoader> UnityEngine.XR.Management.XRManagerSettings.activeLoaders get
A shallow copy of the list of loaders currently managed by this XR Manager instance.
This property returns a read only list. Any changes made to the list itself will not affect the list used by this XR Manager instance. To mutate the list of loaders currently managed by this instance, use TryAddLoader, TryRemoveLoader, and/or TrySetLoaders.
Referenced by UnityEditor.XR.Management.Metadata.XRPackageMetadataStore.AssignLoader(), UnityEditor.XR.Management.Tests.EditorActiveLoadersManipulationTests.CheckIfAttemptsToSetLoaderListThatContainDuplicatesFails(), UnityEngine.XR.Management.Tests.RuntimeActiveLoadersManipulationTests.CheckIfAttemptsToSetLoaderListThatContainDuplicatesFails(), UnityEditor.XR.Management.Tests.EditorActiveLoadersManipulationTests.CheckIfAttemptToAddDuplicateLoadersFails(), UnityEngine.XR.Management.Tests.RuntimeActiveLoadersManipulationTests.CheckIfAttemptToAddDuplicateLoadersFails(), UnityEditor.XR.Management.Tests.EditorActiveLoadersManipulationTests.CheckIfIllegalSetLoaderListFails(), UnityEngine.XR.Management.Tests.RuntimeActiveLoadersManipulationTests.CheckIfIllegalSetLoaderListFails(), UnityEditor.XR.Management.Tests.EditorActiveLoadersManipulationTests.CheckIfLegalAddSucceeds(), UnityEngine.XR.Management.Tests.RuntimeActiveLoadersManipulationTests.CheckIfLegalAddSucceeds(), UnityEditor.XR.Management.Tests.EditorActiveLoadersManipulationTests.CheckIfRemoveAndReAddAtSameIndexWorks(), UnityEngine.XR.Management.Tests.RuntimeActiveLoadersManipulationTests.CheckIfRemoveAndReAddAtSameIndexWorks(), UnityEditor.XR.Management.Tests.EditorActiveLoadersManipulationTests.CheckIfSetLegalLoaderListWorks(), UnityEngine.XR.Management.Tests.RuntimeActiveLoadersManipulationTests.CheckIfSetLegalLoaderListWorks(), UnityEditor.XR.Management.Tests.EditorActiveLoadersManipulationTests.CheckThatEmptyingListRemovesAllRegisteredLoaders(), UnityEditor.XR.Management.XRGeneralBuildProcessor.OnPreprocessBuild(), UnityEngine.XR.Management.Tests.ManualLifetimeTests.SetupXRManagerTest(), UnityEditor.XR.Management.Tests.PackageManagementTests.TestLoaderAssignment(), and UnityEngine.XR.Management.XRManagerSettings.TrySetLoaders().
automaticLoading
bool UnityEngine.XR.Management.XRManagerSettings.automaticLoading get set
Get and set Automatic Loading state for this manager. When this is true, the manager will automatically call InitializeLoader and DeinitializeLoader for you. When false automaticRunning is also set to false and remains that way. This means that disabling automatic loading disables all automatic behavior for the manager.
automaticRunning
bool UnityEngine.XR.Management.XRManagerSettings.automaticRunning get set
Get and set automatic running state for this manager. When set to true the manager will call StartSubsystems and StopSubsystems APIs at appropriate times. When set to false, or when automaticLoading is false then it is up to the user of the manager to handle that same functionality.
isInitializationComplete
bool UnityEngine.XR.Management.XRManagerSettings.isInitializationComplete get
Read only boolean letting us know if initialization is completed. Because initialization is handled as a Coroutine, people taking advantage of the auto-lifecycle management of XRManager will need to wait for init to complete before checking for an ActiveLoader and calling StartSubsystems.
summary> Return the current singleton active loader instance. /summary>
loaders
List<XRLoader> UnityEngine.XR.Management.XRManagerSettings.loaders get
List of loaders currently managed by this XR Manager instance.
Modifying the list of loaders at runtime is undefined behavior and could result in a crash or memory leak. Use activeLoaders to retrieve the currently ordered list of loaders. If you need to mutate the list at runtime, use TryAddLoader, TryRemoveLoader, and TrySetLoaders.
Referenced by Unity.XR.TestTooling.LoaderTestSetup< L, S >.SetupTest(), and Unity.XR.TestTooling.LoaderTestSetup< L, S >.TearDownTest().
The documentation for this class was generated from the following file:
C:/Users/Lykos/Desktop/Projects/Capstone/VRGames/Library/PackageCache/com.unity.xr.management@4.2.1/Runtime/XRManagerSettings.cs