VRGames: UnityEngine.InputSystem.DefaultInputActions.IUIActions Interface Reference
UnityEngine.InputSystem.DefaultInputActions.IUIActions Interface Reference
Public Member Functions
void OnNavigate (InputAction.CallbackContext context)
void OnSubmit (InputAction.CallbackContext context)
void OnCancel (InputAction.CallbackContext context)
void OnPoint (InputAction.CallbackContext context)
void OnClick (InputAction.CallbackContext context)
void OnScrollWheel (InputAction.CallbackContext context)
void OnMiddleClick (InputAction.CallbackContext context)
void OnRightClick (InputAction.CallbackContext context)
void OnTrackedDevicePosition (InputAction.CallbackContext context)
void OnTrackedDeviceOrientation (InputAction.CallbackContext context)
Member Function Documentation
OnCancel()
void UnityEngine.InputSystem.DefaultInputActions.IUIActions.OnCancel (InputAction.CallbackContext context)
Referenced by UnityEngine.InputSystem.DefaultInputActions.UIActions.SetCallbacks().
OnClick()
void UnityEngine.InputSystem.DefaultInputActions.IUIActions.OnClick (InputAction.CallbackContext context)
Referenced by UnityEngine.InputSystem.DefaultInputActions.UIActions.SetCallbacks().
OnMiddleClick()
void UnityEngine.InputSystem.DefaultInputActions.IUIActions.OnMiddleClick (InputAction.CallbackContext context)
Referenced by UnityEngine.InputSystem.DefaultInputActions.UIActions.SetCallbacks().
OnNavigate()
void UnityEngine.InputSystem.DefaultInputActions.IUIActions.OnNavigate (InputAction.CallbackContext context)
Referenced by UnityEngine.InputSystem.DefaultInputActions.UIActions.SetCallbacks().
OnPoint()
void UnityEngine.InputSystem.DefaultInputActions.IUIActions.OnPoint (InputAction.CallbackContext context)
Referenced by UnityEngine.InputSystem.DefaultInputActions.UIActions.SetCallbacks().
OnRightClick()
void UnityEngine.InputSystem.DefaultInputActions.IUIActions.OnRightClick (InputAction.CallbackContext context)
Referenced by UnityEngine.InputSystem.DefaultInputActions.UIActions.SetCallbacks().
OnScrollWheel()
void UnityEngine.InputSystem.DefaultInputActions.IUIActions.OnScrollWheel (InputAction.CallbackContext context)
Referenced by UnityEngine.InputSystem.DefaultInputActions.UIActions.SetCallbacks().
OnSubmit()
void UnityEngine.InputSystem.DefaultInputActions.IUIActions.OnSubmit (InputAction.CallbackContext context)
Referenced by UnityEngine.InputSystem.DefaultInputActions.UIActions.SetCallbacks().
OnTrackedDeviceOrientation()
void UnityEngine.InputSystem.DefaultInputActions.IUIActions.OnTrackedDeviceOrientation (InputAction.CallbackContext context)
Referenced by UnityEngine.InputSystem.DefaultInputActions.UIActions.SetCallbacks().
OnTrackedDevicePosition()
void UnityEngine.InputSystem.DefaultInputActions.IUIActions.OnTrackedDevicePosition (InputAction.CallbackContext context)
Referenced by UnityEngine.InputSystem.DefaultInputActions.UIActions.SetCallbacks().
The documentation for this interface was generated from the following file:
C:/Users/Lykos/Desktop/Projects/Capstone/VRGames/Library/PackageCache/com.unity.inputsystem@1.3.0/InputSystem/Plugins/PlayerInput/DefaultInputActions.cs