VRGames: Facebook.WitAi.IVoiceService Interface Reference
Facebook.WitAi.IVoiceService Interface Reference
Public Member Functions
void Activate ()
Activate the microphone and send data for NLU processing.
void Activate (WitRequestOptions requestOptions)
Activate the microphone and send data for NLU processing with custom request options.
void ActivateImmediately ()
void ActivateImmediately (WitRequestOptions requestOptions)
void Deactivate ()
Stop listening and submit the collected microphone data for processing.
void DeactivateAndAbortRequest ()
Stop listening and abort any requests that may be active without waiting for a response.
void Activate (string transcription)
Send text data for NLU processing.
void Activate (string text, WitRequestOptions requestOptions)
Send text data for NLU processing with custom request options.
Properties
bool Active [get]
Returns true if this voice service is currently active and listening with the mic.
bool IsRequestActive [get]
bool MicActive [get]
VoiceEvents VoiceEvents [get, set]
ITranscriptionProvider TranscriptionProvider [get, set]
Member Function Documentation
Activate() [1/4]
void Facebook.WitAi.IVoiceService.Activate ()
Activate the microphone and send data for NLU processing.
Implemented in Facebook.WitAi.VoiceService, Facebook.WitAi.Wit, Oculus.Voice.Bindings.Android.VoiceSDKImpl, and Oculus.Voice.AppVoiceExperience.
Referenced by Oculus.Voice.AppVoiceExperience.Activate(), Oculus.Voice.AppVoiceExperience.Activate(), Oculus.Voice.AppVoiceExperience.Activate(), and Oculus.Voice.AppVoiceExperience.Activate().
Activate() [2/4]
void Facebook.WitAi.IVoiceService.Activate (string text, WitRequestOptions requestOptions)
Send text data for NLU processing with custom request options.
Parameters
text
requestOptions
Implemented in Facebook.WitAi.VoiceService, Facebook.WitAi.Wit, Oculus.Voice.Bindings.Android.VoiceSDKImpl, and Oculus.Voice.AppVoiceExperience.
Activate() [3/4]
void Facebook.WitAi.IVoiceService.Activate (string transcription)
Send text data for NLU processing.
Parameters
text
Implemented in Facebook.WitAi.VoiceService, Facebook.WitAi.Wit, Oculus.Voice.Bindings.Android.VoiceSDKImpl, and Oculus.Voice.AppVoiceExperience.
Activate() [4/4]
void Facebook.WitAi.IVoiceService.Activate (WitRequestOptions requestOptions)
Activate the microphone and send data for NLU processing with custom request options.
Parameters
requestOptions
Implemented in Oculus.Voice.AppVoiceExperience, Facebook.WitAi.VoiceService, Facebook.WitAi.Wit, and Oculus.Voice.Bindings.Android.VoiceSDKImpl.
ActivateImmediately() [1/2]
void Facebook.WitAi.IVoiceService.ActivateImmediately ()
Implemented in Facebook.WitAi.VoiceService, Facebook.WitAi.Wit, Oculus.Voice.Bindings.Android.VoiceSDKImpl, and Oculus.Voice.AppVoiceExperience.
Referenced by Oculus.Voice.AppVoiceExperience.ActivateImmediately(), and Oculus.Voice.AppVoiceExperience.ActivateImmediately().
ActivateImmediately() [2/2]
void Facebook.WitAi.IVoiceService.ActivateImmediately (WitRequestOptions requestOptions)
Implemented in Oculus.Voice.AppVoiceExperience, Facebook.WitAi.VoiceService, Facebook.WitAi.Wit, and Oculus.Voice.Bindings.Android.VoiceSDKImpl.
Deactivate()
void Facebook.WitAi.IVoiceService.Deactivate ()
Stop listening and submit the collected microphone data for processing.
Implemented in Facebook.WitAi.VoiceService, Facebook.WitAi.Wit, Oculus.Voice.Bindings.Android.VoiceSDKImpl, and Oculus.Voice.AppVoiceExperience.
Referenced by Oculus.Voice.AppVoiceExperience.Deactivate().
DeactivateAndAbortRequest()
void Facebook.WitAi.IVoiceService.DeactivateAndAbortRequest ()
Stop listening and abort any requests that may be active without waiting for a response.
Implemented in Facebook.WitAi.VoiceService, Facebook.WitAi.Wit, Oculus.Voice.Bindings.Android.VoiceSDKImpl, and Oculus.Voice.AppVoiceExperience.
Referenced by Oculus.Voice.AppVoiceExperience.DeactivateAndAbortRequest().
Property Documentation
Active
bool Facebook.WitAi.IVoiceService.Active get
Returns true if this voice service is currently active and listening with the mic.
Implemented in Facebook.WitAi.VoiceService, Facebook.WitAi.Wit, Oculus.Voice.Bindings.Android.VoiceSDKImpl, and Oculus.Voice.AppVoiceExperience.
IsRequestActive
bool Facebook.WitAi.IVoiceService.IsRequestActive get
Implemented in Facebook.WitAi.VoiceService, Facebook.WitAi.Wit, Oculus.Voice.Bindings.Android.VoiceSDKImpl, and Oculus.Voice.AppVoiceExperience.
MicActive
bool Facebook.WitAi.IVoiceService.MicActive get
Implemented in Facebook.WitAi.VoiceService, Facebook.WitAi.Wit, Oculus.Voice.Bindings.Android.VoiceSDKImpl, and Oculus.Voice.AppVoiceExperience.
TranscriptionProvider
ITranscriptionProvider Facebook.WitAi.IVoiceService.TranscriptionProvider get set
Implemented in Facebook.WitAi.VoiceService, Facebook.WitAi.Wit, Oculus.Voice.Bindings.Android.VoiceSDKImpl, and Oculus.Voice.AppVoiceExperience.
VoiceEvents
VoiceEvents Facebook.WitAi.IVoiceService.VoiceEvents get set
Implemented in Facebook.WitAi.VoiceService, and Oculus.Voice.Bindings.Android.VoiceSDKImpl.
The documentation for this interface was generated from the following file:
C:/Users/Lykos/Desktop/Projects/Capstone/VRGames/Assets/ThirdParty/Oculus/Voice/Lib/Wit.ai/Scripts/Runtime/VoiceService.cs