VRGames: Oculus.Interaction.Input.IHand Interface Reference
Oculus.Interaction.Input.IHand Interface Reference
Public Member Functions
bool GetFingerIsPinching (HandFinger finger)
bool GetIndexFingerIsPinching ()
bool GetPointerPose (out Pose pose)
Attempts to calculate the pose that can be used as a root for raycasting, in world space Returns false if there is no valid tracking data.
bool GetJointPose (HandJointId handJointId, out Pose pose)
Attempts to calculate the pose of the requested hand joint, in world space. Returns false if the skeleton is not yet initialized, or there is no valid tracking data.
bool GetJointPoseLocal (HandJointId handJointId, out Pose pose)
Attempts to calculate the pose of the requested hand joint, in local space. Returns false if the skeleton is not yet initialized, or there is no valid tracking data.
bool GetJointPosesLocal (out ReadOnlyHandJointPoses localJointPoses)
Returns an array containing the local pose of each joint. The poses do not have the root pose applied, nor the hand scale. It is in the same coordinate system as the hand skeleton.
bool GetJointPoseFromWrist (HandJointId handJointId, out Pose pose)
Attempts to calculate the pose of the requested hand joint relative to the wrist. Returns false if the skeleton is not yet initialized, or there is no valid tracking data.
bool GetJointPosesFromWrist (out ReadOnlyHandJointPoses jointPosesFromWrist)
Returns an array containing the pose of each joint relative to the wrist. The poses do not have the root pose applied, nor the hand scale. It is in the same coordinate system as the hand skeleton.
bool GetPalmPoseLocal (out Pose pose)
Obtains palm pose in local space.
bool GetFingerIsHighConfidence (HandFinger finger)
float GetFingerPinchStrength (HandFinger finger)
bool GetRootPose (out Pose pose)
Gets the root pose of the wrist, in world space. Will return true if a pose was available; false otherwise. Confidence level of the pose is exposed via IsHighConfidence.
bool GetCenterEyePose (out Pose pose)
Gets the pose of the center eye (HMD), in world space. Will return true if a pose was available; false otherwise.
bool GetHandAspect< TComponent > (out TComponent foundComponent)
An Aspect provides additional functionality on top of what the HandState provides. The underlying hand is responsible for finding the most appropriate component. It is usually, but not necessarily, located within the same GameObject as the underlying hand. For example, this method can be used to source the SkinnedMeshRenderer representing the hand, if one exists.
Returns
true if an aspect of the requested type was found, false otherwise
Properties
Handedness Handedness [get]
bool IsConnected [get]
bool IsHighConfidence [get]
The hand is connected and tracked, and the root pose's tracking data is marked as high confidence. If this is true, then it implies that IsConnected and IsRootPoseValid are also true, so they don't need to be checked in addition to this.
bool IsDominantHand [get]
float Scale [get]
bool IsPointerPoseValid [get]
Will return true if a pointer pose is available, that can be retrieved via GetPointerPose
bool IsTrackedDataValid [get]
True if the hand is currently tracked, thus tracking poses are available for the hand root and finger joints. This property does not indicate pointing pose validity, which has its own property: IsPointerPoseValid.
bool IsCenterEyePoseValid [get]
Will return true if an HMD Center Eye pose available, that can be retrieved via GetCenterEyePose
Transform TrackingToWorldSpace [get]
The transform that was applied to all tracking space poses to convert them to world space.
int CurrentDataVersion [get]
Incremented every time the source tracking or state data changes.
Events
Action WhenHandUpdated
Member Function Documentation
GetCenterEyePose()
bool Oculus.Interaction.Input.IHand.GetCenterEyePose (out Pose pose)
Gets the pose of the center eye (HMD), in world space. Will return true if a pose was available; false otherwise.
Implemented in Oculus.Interaction.Input.Hand, and Oculus.Interaction.Input.HandRef.
GetFingerIsHighConfidence()
bool Oculus.Interaction.Input.IHand.GetFingerIsHighConfidence (HandFinger finger)
Implemented in Oculus.Interaction.Input.Hand, and Oculus.Interaction.Input.HandRef.
GetFingerIsPinching()
bool Oculus.Interaction.Input.IHand.GetFingerIsPinching (HandFinger finger)
Implemented in Oculus.Interaction.Input.Hand, and Oculus.Interaction.Input.HandRef.
GetFingerPinchStrength()
float Oculus.Interaction.Input.IHand.GetFingerPinchStrength (HandFinger finger)
Implemented in Oculus.Interaction.Input.Hand, and Oculus.Interaction.Input.HandRef.
GetHandAspect< TComponent >()
bool Oculus.Interaction.Input.IHand.GetHandAspect< TComponent > (out TComponent foundComponent)
An Aspect provides additional functionality on top of what the HandState provides. The underlying hand is responsible for finding the most appropriate component. It is usually, but not necessarily, located within the same GameObject as the underlying hand. For example, this method can be used to source the SkinnedMeshRenderer representing the hand, if one exists.
Returns
true if an aspect of the requested type was found, false otherwise
Implemented in Oculus.Interaction.Input.Hand, and Oculus.Interaction.Input.HandRef.
Type Constraints
TComponent : class
GetIndexFingerIsPinching()
bool Oculus.Interaction.Input.IHand.GetIndexFingerIsPinching ()
Implemented in Oculus.Interaction.Input.Hand, and Oculus.Interaction.Input.HandRef.
GetJointPose()
bool Oculus.Interaction.Input.IHand.GetJointPose (HandJointId handJointId, out Pose pose)
Attempts to calculate the pose of the requested hand joint, in world space. Returns false if the skeleton is not yet initialized, or there is no valid tracking data.
Implemented in Oculus.Interaction.Input.Hand, and Oculus.Interaction.Input.HandRef.
GetJointPoseFromWrist()
bool Oculus.Interaction.Input.IHand.GetJointPoseFromWrist (HandJointId handJointId, out Pose pose)
Attempts to calculate the pose of the requested hand joint relative to the wrist. Returns false if the skeleton is not yet initialized, or there is no valid tracking data.
Implemented in Oculus.Interaction.Input.Hand, and Oculus.Interaction.Input.HandRef.
GetJointPoseLocal()
bool Oculus.Interaction.Input.IHand.GetJointPoseLocal (HandJointId handJointId, out Pose pose)
Attempts to calculate the pose of the requested hand joint, in local space. Returns false if the skeleton is not yet initialized, or there is no valid tracking data.
Implemented in Oculus.Interaction.Input.Hand, and Oculus.Interaction.Input.HandRef.
GetJointPosesFromWrist()
bool Oculus.Interaction.Input.IHand.GetJointPosesFromWrist (out ReadOnlyHandJointPoses jointPosesFromWrist)
Returns an array containing the pose of each joint relative to the wrist. The poses do not have the root pose applied, nor the hand scale. It is in the same coordinate system as the hand skeleton.
Parameters
jointPosesFromWrist The array with the joint poses from the wrist. It will be empty if no poses where found
Returns
True if the poses collection was correctly populated. False otherwise.
Implemented in Oculus.Interaction.Input.Hand, and Oculus.Interaction.Input.HandRef.
Referenced by Oculus.Interaction.PoseDetection.FingerShapes.ComputeAngleSum(), Oculus.Interaction.PoseDetection.FingerShapes.GetAbductionValue(), and Oculus.Interaction.PoseDetection.FingerShapes.GetOppositionValue().
GetJointPosesLocal()
bool Oculus.Interaction.Input.IHand.GetJointPosesLocal (out ReadOnlyHandJointPoses localJointPoses)
Returns an array containing the local pose of each joint. The poses do not have the root pose applied, nor the hand scale. It is in the same coordinate system as the hand skeleton.
Parameters
localJointPoses The array with the local joint poses. It will be empty if no poses where found
Returns
True if the poses collection was correctly populated. False otherwise.
Implemented in Oculus.Interaction.Input.HandRef, and Oculus.Interaction.Input.Hand.
GetPalmPoseLocal()
bool Oculus.Interaction.Input.IHand.GetPalmPoseLocal (out Pose pose)
Obtains palm pose in local space.
Parameters
pose The pose to populate
Returns
True if pose was obtained.
Implemented in Oculus.Interaction.Input.Hand, and Oculus.Interaction.Input.HandRef.
GetPointerPose()
bool Oculus.Interaction.Input.IHand.GetPointerPose (out Pose pose)
Attempts to calculate the pose that can be used as a root for raycasting, in world space Returns false if there is no valid tracking data.
Implemented in Oculus.Interaction.Input.Hand, and Oculus.Interaction.Input.HandRef.
GetRootPose()
bool Oculus.Interaction.Input.IHand.GetRootPose (out Pose pose)
Gets the root pose of the wrist, in world space. Will return true if a pose was available; false otherwise. Confidence level of the pose is exposed via IsHighConfidence.
Implemented in Oculus.Interaction.Input.Hand, and Oculus.Interaction.Input.HandRef.
Property Documentation
CurrentDataVersion
int Oculus.Interaction.Input.IHand.CurrentDataVersion get
Incremented every time the source tracking or state data changes.
Implemented in Oculus.Interaction.Input.HandRef.
Handedness
Handedness Oculus.Interaction.Input.IHand.Handedness get
Implemented in Oculus.Interaction.Input.Hand, and Oculus.Interaction.Input.HandRef.
IsCenterEyePoseValid
bool Oculus.Interaction.Input.IHand.IsCenterEyePoseValid get
Will return true if an HMD Center Eye pose available, that can be retrieved via GetCenterEyePose
Implemented in Oculus.Interaction.Input.Hand, and Oculus.Interaction.Input.HandRef.
IsConnected
bool Oculus.Interaction.Input.IHand.IsConnected get
Implemented in Oculus.Interaction.Input.Hand, and Oculus.Interaction.Input.HandRef.
IsDominantHand
bool Oculus.Interaction.Input.IHand.IsDominantHand get
Implemented in Oculus.Interaction.Input.Hand, and Oculus.Interaction.Input.HandRef.
IsHighConfidence
bool Oculus.Interaction.Input.IHand.IsHighConfidence get
The hand is connected and tracked, and the root pose's tracking data is marked as high confidence. If this is true, then it implies that IsConnected and IsRootPoseValid are also true, so they don't need to be checked in addition to this.
Implemented in Oculus.Interaction.Input.Hand, and Oculus.Interaction.Input.HandRef.
IsPointerPoseValid
bool Oculus.Interaction.Input.IHand.IsPointerPoseValid get
Will return true if a pointer pose is available, that can be retrieved via GetPointerPose
Implemented in Oculus.Interaction.Input.Hand, and Oculus.Interaction.Input.HandRef.
IsTrackedDataValid
bool Oculus.Interaction.Input.IHand.IsTrackedDataValid get
True if the hand is currently tracked, thus tracking poses are available for the hand root and finger joints. This property does not indicate pointing pose validity, which has its own property: IsPointerPoseValid.
Implemented in Oculus.Interaction.Input.Hand, and Oculus.Interaction.Input.HandRef.
Referenced by Oculus.Interaction.PoseDetection.Debug.FingerFeatureSkeletalDebugVisual.Update(), and Oculus.Interaction.GrabAPI.FingerPalmGrabAPI.Update().
Scale
float Oculus.Interaction.Input.IHand.Scale get
Implemented in Oculus.Interaction.Input.Hand, and Oculus.Interaction.Input.HandRef.
TrackingToWorldSpace
Transform Oculus.Interaction.Input.IHand.TrackingToWorldSpace get
The transform that was applied to all tracking space poses to convert them to world space.
Implemented in Oculus.Interaction.Input.Hand, and Oculus.Interaction.Input.HandRef.
Event Documentation
WhenHandUpdated
Action Oculus.Interaction.Input.IHand.WhenHandUpdated
Implemented in Oculus.Interaction.Input.HandRef.
The documentation for this interface was generated from the following file:
C:/Users/Lykos/Desktop/Projects/Capstone/VRGames/Assets/ThirdParty/Oculus/Interaction/Runtime/Scripts/Input/Hands/IHand.cs