VRGames: Oculus.Interaction.IInteractorDriver Interface Reference
Oculus.Interaction.IInteractorDriver Interface Reference
IInteractionDriver drives the update loop of an Interaction.
Public Member Functions
void UpdateInteraction ()
void UpdateHover ()
void UpdateSelection (bool selectionCanBeEmpty)
void Enable ()
void Disable ()
Properties
bool IsRootInteractorDriver [get, set]
bool HasCandidate [get]
IInteractor CandidateInteractor [get]
bool ShouldSelect [get]
bool IsHovering [get]
bool IsSelecting [get]
bool IsSelectingInteractable [get]
Detailed Description
IInteractionDriver drives the update loop of an Interaction.
Member Function Documentation
Disable()
void Oculus.Interaction.IInteractorDriver.Disable ()
Implemented in Oculus.Interaction.Interactor< TInteractor, TInteractable >, Oculus.Interaction.InteractorDriver, and Oculus.Interaction.InteractorDriverGroup.
Referenced by Oculus.Interaction.InteractorDriverGroup.Disable().
Enable()
void Oculus.Interaction.IInteractorDriver.Enable ()
Implemented in Oculus.Interaction.Interactor< TInteractor, TInteractable >, Oculus.Interaction.InteractorDriver, and Oculus.Interaction.InteractorDriverGroup.
Referenced by Oculus.Interaction.InteractorDriverGroup.Enable(), and Oculus.Interaction.InteractorDriverGroup.UpdateInteraction().
UpdateHover()
void Oculus.Interaction.IInteractorDriver.UpdateHover ()
Implemented in Oculus.Interaction.Interactor< TInteractor, TInteractable >, Oculus.Interaction.InteractorDriver, and Oculus.Interaction.InteractorDriverGroup.
Referenced by Oculus.Interaction.InteractorDriverGroup.UpdateHover().
UpdateInteraction()
void Oculus.Interaction.IInteractorDriver.UpdateInteraction ()
Implemented in Oculus.Interaction.Interactor< TInteractor, TInteractable >, Oculus.Interaction.InteractorDriver, and Oculus.Interaction.InteractorDriverGroup.
Referenced by Oculus.Interaction.InteractorDriverGroup.UpdateInteraction().
UpdateSelection()
void Oculus.Interaction.IInteractorDriver.UpdateSelection (bool selectionCanBeEmpty)
Implemented in Oculus.Interaction.Interactor< TInteractor, TInteractable >, Oculus.Interaction.InteractorDriver, and Oculus.Interaction.InteractorDriverGroup.
Referenced by Oculus.Interaction.InteractorDriverGroup.UpdateSelection().
Property Documentation
CandidateInteractor
IInteractor Oculus.Interaction.IInteractorDriver.CandidateInteractor get
Implemented in Oculus.Interaction.Interactor< TInteractor, TInteractable >, Oculus.Interaction.InteractorDriver, and Oculus.Interaction.InteractorDriverGroup.
HasCandidate
bool Oculus.Interaction.IInteractorDriver.HasCandidate get
Implemented in Oculus.Interaction.Interactor< TInteractor, TInteractable >, Oculus.Interaction.InteractorDriver, and Oculus.Interaction.InteractorDriverGroup.
Referenced by Oculus.Interaction.InteractorDriverGroup.UpdateHover(), and Oculus.Interaction.InteractorDriverGroup.UpdateInteraction().
IsHovering
bool Oculus.Interaction.IInteractorDriver.IsHovering get
Implemented in Oculus.Interaction.Interactor< TInteractor, TInteractable >, Oculus.Interaction.InteractorDriver, and Oculus.Interaction.InteractorDriverGroup.
IsRootInteractorDriver
bool Oculus.Interaction.IInteractorDriver.IsRootInteractorDriver get set
Implemented in Oculus.Interaction.Interactor< TInteractor, TInteractable >, Oculus.Interaction.InteractorDriver, and Oculus.Interaction.InteractorDriverGroup.
IsSelecting
bool Oculus.Interaction.IInteractorDriver.IsSelecting get
Implemented in Oculus.Interaction.Interactor< TInteractor, TInteractable >, Oculus.Interaction.InteractorDriver, and Oculus.Interaction.InteractorDriverGroup.
Referenced by Oculus.Interaction.InteractorDriverGroup.UpdateSelection().
IsSelectingInteractable
bool Oculus.Interaction.IInteractorDriver.IsSelectingInteractable get
Implemented in Oculus.Interaction.Interactor< TInteractor, TInteractable >, Oculus.Interaction.InteractorDriver, and Oculus.Interaction.InteractorDriverGroup.
ShouldSelect
bool Oculus.Interaction.IInteractorDriver.ShouldSelect get
Implemented in Oculus.Interaction.Interactor< TInteractor, TInteractable >, Oculus.Interaction.InteractorDriver, and Oculus.Interaction.InteractorDriverGroup.
The documentation for this interface was generated from the following file:
C:/Users/Lykos/Desktop/Projects/Capstone/VRGames/Assets/ThirdParty/Oculus/Interaction/Runtime/Scripts/Interaction/Core/IInteractorDriver.cs