VRGames: Unity.Services.Core.Internal.DependencyTreeInitializeOrderSorter Struct Reference
Unity.Services.Core.Internal.DependencyTreeInitializeOrderSorter Struct Reference
Helper object to sort IInitializablePackage stored into a DependencyTree in order they can be initialized successfully. It adapts the Depth-first Search algorithm.
Public Types
enum ExplorationMark { None , Viewed , Sorted }
Public Member Functions
DependencyTreeInitializeOrderSorter (DependencyTree tree, ICollection< int > target)
void SortRegisteredPackagesIntoTarget ()
void RemoveUnprovidedOptionalDependenciesFromTree ()
void RemoveUnprovidedOptionalDependencies (IList< int > dependencyTypeHashes)
void SortTreeThrough (int packageTypeHash)
void SortTreeThrough (IEnumerable< int > dependencyTypeHashes)
void MarkPackage (int packageTypeHash, ExplorationMark mark)
IReadOnlyCollection< int > GetPackageTypeHashes ()
int GetPackageTypeHashFor (int componentTypeHash)
IEnumerable< int > GetDependencyTypeHashesFor (int packageTypeHash)
Public Attributes
readonly DependencyTree Tree
readonly ICollection< int > Target
The collection containing the sorted package type hashes.
Dictionary< int, ExplorationMark > m_PackageTypeHashExplorationHistory
History to track packages' exploration state. Key: Hash code of a IInitializablePackage type. Value: Its exploration state.
Detailed Description
Helper object to sort IInitializablePackage stored into a DependencyTree in order they can be initialized successfully. It adapts the Depth-first Search algorithm.
Algorithm source:
Member Enumeration Documentation
ExplorationMark
enum Unity.Services.Core.Internal.DependencyTreeInitializeOrderSorter.ExplorationMark
Enumerator
None
Viewed
Sorted
Constructor & Destructor Documentation
DependencyTreeInitializeOrderSorter()
Unity.Services.Core.Internal.DependencyTreeInitializeOrderSorter.DependencyTreeInitializeOrderSorter (DependencyTree tree, ICollection< int > target)
Member Function Documentation
GetDependencyTypeHashesFor()
IEnumerable< int > Unity.Services.Core.Internal.DependencyTreeInitializeOrderSorter.GetDependencyTypeHashesFor (int packageTypeHash)
Referenced by Unity.Services.Core.Internal.DependencyTreeInitializeOrderSorter.SortTreeThrough().
GetPackageTypeHashes()
IReadOnlyCollection< int > Unity.Services.Core.Internal.DependencyTreeInitializeOrderSorter.GetPackageTypeHashes ()
Referenced by Unity.Services.Core.Internal.DependencyTreeInitializeOrderSorter.SortRegisteredPackagesIntoTarget().
GetPackageTypeHashFor()
int Unity.Services.Core.Internal.DependencyTreeInitializeOrderSorter.GetPackageTypeHashFor (int componentTypeHash)
Referenced by Unity.Services.Core.Internal.DependencyTreeInitializeOrderSorter.SortTreeThrough().
MarkPackage()
void Unity.Services.Core.Internal.DependencyTreeInitializeOrderSorter.MarkPackage (int packageTypeHash, ExplorationMark mark)
Referenced by Unity.Services.Core.Internal.DependencyTreeInitializeOrderSorter.SortTreeThrough().
RemoveUnprovidedOptionalDependencies()
void Unity.Services.Core.Internal.DependencyTreeInitializeOrderSorter.RemoveUnprovidedOptionalDependencies (IList< int > dependencyTypeHashes)
Referenced by Unity.Services.Core.Internal.DependencyTreeInitializeOrderSorter.RemoveUnprovidedOptionalDependenciesFromTree().
RemoveUnprovidedOptionalDependenciesFromTree()
void Unity.Services.Core.Internal.DependencyTreeInitializeOrderSorter.RemoveUnprovidedOptionalDependenciesFromTree ()
Referenced by Unity.Services.Core.Internal.DependencyTreeInitializeOrderSorter.SortRegisteredPackagesIntoTarget().
SortRegisteredPackagesIntoTarget()
void Unity.Services.Core.Internal.DependencyTreeInitializeOrderSorter.SortRegisteredPackagesIntoTarget ()
SortTreeThrough() [1/2]
void Unity.Services.Core.Internal.DependencyTreeInitializeOrderSorter.SortTreeThrough (IEnumerable< int > dependencyTypeHashes)
SortTreeThrough() [2/2]
void Unity.Services.Core.Internal.DependencyTreeInitializeOrderSorter.SortTreeThrough (int packageTypeHash)
Referenced by Unity.Services.Core.Internal.DependencyTreeInitializeOrderSorter.SortRegisteredPackagesIntoTarget(), Unity.Services.Core.Internal.DependencyTreeInitializeOrderSorter.SortTreeThrough(), and Unity.Services.Core.Internal.DependencyTreeInitializeOrderSorter.SortTreeThrough().
Member Data Documentation
m_PackageTypeHashExplorationHistory
Dictionary<int, ExplorationMark> Unity.Services.Core.Internal.DependencyTreeInitializeOrderSorter.m_PackageTypeHashExplorationHistory
History to track packages' exploration state. Key: Hash code of a IInitializablePackage type. Value: Its exploration state.
Referenced by Unity.Services.Core.Internal.DependencyTreeInitializeOrderSorter.DependencyTreeInitializeOrderSorter(), Unity.Services.Core.Internal.DependencyTreeInitializeOrderSorter.MarkPackage(), Unity.Services.Core.Internal.DependencyTreeInitializeOrderSorter.SortRegisteredPackagesIntoTarget(), and Unity.Services.Core.Internal.DependencyTreeInitializeOrderSorter.SortTreeThrough().
Target
readonly ICollection<int> Unity.Services.Core.Internal.DependencyTreeInitializeOrderSorter.Target
The collection containing the sorted package type hashes.
Referenced by Unity.Services.Core.Internal.DependencyTreeInitializeOrderSorter.DependencyTreeInitializeOrderSorter(), Unity.Services.Core.Internal.DependencyTreeInitializeOrderSorter.SortRegisteredPackagesIntoTarget(), and Unity.Services.Core.Internal.DependencyTreeInitializeOrderSorter.SortTreeThrough().
Tree
readonly DependencyTree Unity.Services.Core.Internal.DependencyTreeInitializeOrderSorter.Tree
The documentation for this struct was generated from the following file:
C:/Users/Lykos/Desktop/Projects/Capstone/VRGames/Library/PackageCache/com.unity.services.core@1.4.0/Runtime/Core.Internal/Registry/DependencyTreeInitializeOrderSorter.cs