VRGames: UnityEngine.InputSystem.Layouts.InputControlLayout.Builder.ControlBuilder Struct Reference
UnityEngine.InputSystem.Layouts.InputControlLayout.Builder.ControlBuilder Struct Reference
Syntax for configuring an individual ControlItem.
Public Member Functions
ControlBuilder WithDisplayName (string displayName)
ControlBuilder WithLayout (string layout)
ControlBuilder WithFormat (FourCC format)
ControlBuilder WithFormat (string format)
ControlBuilder WithByteOffset (uint offset)
ControlBuilder WithBitOffset (uint bit)
ControlBuilder IsSynthetic (bool value)
ControlBuilder IsNoisy (bool value)
ControlBuilder DontReset (bool value)
ControlBuilder WithSizeInBits (uint sizeInBits)
ControlBuilder WithRange (float minValue, float maxValue)
ControlBuilder WithUsages (params InternedString[] usages)
ControlBuilder WithUsages (IEnumerable< string > usages)
ControlBuilder WithUsages (params string[] usages)
ControlBuilder WithParameters (string parameters)
ControlBuilder WithProcessors (string processors)
ControlBuilder WithDefaultState (PrimitiveValue value)
ControlBuilder UsingStateFrom (string path)
ControlBuilder AsArrayOfControlsWithSize (int arraySize)
Detailed Description
Syntax for configuring an individual ControlItem.
Member Function Documentation
AsArrayOfControlsWithSize()
ControlBuilder UnityEngine.InputSystem.Layouts.InputControlLayout.Builder.ControlBuilder.AsArrayOfControlsWithSize (int arraySize)
DontReset()
ControlBuilder UnityEngine.InputSystem.Layouts.InputControlLayout.Builder.ControlBuilder.DontReset (bool value)
IsNoisy()
ControlBuilder UnityEngine.InputSystem.Layouts.InputControlLayout.Builder.ControlBuilder.IsNoisy (bool value)
IsSynthetic()
ControlBuilder UnityEngine.InputSystem.Layouts.InputControlLayout.Builder.ControlBuilder.IsSynthetic (bool value)
UsingStateFrom()
ControlBuilder UnityEngine.InputSystem.Layouts.InputControlLayout.Builder.ControlBuilder.UsingStateFrom (string path)
WithBitOffset()
ControlBuilder UnityEngine.InputSystem.Layouts.InputControlLayout.Builder.ControlBuilder.WithBitOffset (uint bit)
WithByteOffset()
ControlBuilder UnityEngine.InputSystem.Layouts.InputControlLayout.Builder.ControlBuilder.WithByteOffset (uint offset)
WithDefaultState()
ControlBuilder UnityEngine.InputSystem.Layouts.InputControlLayout.Builder.ControlBuilder.WithDefaultState (PrimitiveValue value)
WithDisplayName()
ControlBuilder UnityEngine.InputSystem.Layouts.InputControlLayout.Builder.ControlBuilder.WithDisplayName (string displayName)
WithFormat() [1/2]
ControlBuilder UnityEngine.InputSystem.Layouts.InputControlLayout.Builder.ControlBuilder.WithFormat (FourCC format)
Referenced by UnityEngine.InputSystem.Layouts.InputControlLayout.Builder.ControlBuilder.WithFormat().
WithFormat() [2/2]
ControlBuilder UnityEngine.InputSystem.Layouts.InputControlLayout.Builder.ControlBuilder.WithFormat (string format)
WithLayout()
ControlBuilder UnityEngine.InputSystem.Layouts.InputControlLayout.Builder.ControlBuilder.WithLayout (string layout)
WithParameters()
ControlBuilder UnityEngine.InputSystem.Layouts.InputControlLayout.Builder.ControlBuilder.WithParameters (string parameters)
WithProcessors()
ControlBuilder UnityEngine.InputSystem.Layouts.InputControlLayout.Builder.ControlBuilder.WithProcessors (string processors)
WithRange()
ControlBuilder UnityEngine.InputSystem.Layouts.InputControlLayout.Builder.ControlBuilder.WithRange (float minValue, float maxValue)
WithSizeInBits()
ControlBuilder UnityEngine.InputSystem.Layouts.InputControlLayout.Builder.ControlBuilder.WithSizeInBits (uint sizeInBits)
WithUsages() [1/3]
ControlBuilder UnityEngine.InputSystem.Layouts.InputControlLayout.Builder.ControlBuilder.WithUsages (IEnumerable< string > usages)
WithUsages() [2/3]
ControlBuilder UnityEngine.InputSystem.Layouts.InputControlLayout.Builder.ControlBuilder.WithUsages (params InternedString[] usages)
Referenced by UnityEngine.InputSystem.Layouts.InputControlLayout.Builder.ControlBuilder.WithUsages(), and UnityEngine.InputSystem.Layouts.InputControlLayout.Builder.ControlBuilder.WithUsages().
WithUsages() [3/3]
ControlBuilder UnityEngine.InputSystem.Layouts.InputControlLayout.Builder.ControlBuilder.WithUsages (params string[] usages)
The documentation for this struct was generated from the following file:
C:/Users/Lykos/Desktop/Projects/Capstone/VRGames/Library/PackageCache/com.unity.inputsystem@1.3.0/InputSystem/Controls/InputControlLayout.cs