VRGames: UnityEngine.InputSystem.Utilities.PrimitiveValue Struct Reference
UnityEngine.InputSystem.Utilities.PrimitiveValue Struct Reference
A union holding a primitive value.
Public Member Functions
PrimitiveValue (bool value)
Create a PrimitiveValue holding a bool.
PrimitiveValue (char value)
Create a PrimitiveValue holding a character.
PrimitiveValue (byte value)
Create a PrimitiveValue holding a byte.
PrimitiveValue (sbyte value)
Create a PrimitiveValue holding a signed byte.
PrimitiveValue (short value)
Create a PrimitiveValue holding a short.
PrimitiveValue (ushort value)
Create a PrimitiveValue holding an unsigned short.
PrimitiveValue (int value)
Create a PrimitiveValue holding an int.
PrimitiveValue (uint value)
Create a PrimitiveValue holding an unsigned int.
PrimitiveValue (long value)
Create a PrimitiveValue holding a long.
PrimitiveValue (ulong value)
Create a PrimitiveValue holding a ulong.
PrimitiveValue (float value)
Create a PrimitiveValue holding a float.
PrimitiveValue (double value)
Create a PrimitiveValue holding a double.
PrimitiveValue ConvertTo (TypeCode type)
Convert to another type of value.
unsafe bool Equals (PrimitiveValue other)
Compare this value to other .
override bool Equals (object obj)
Compare this value to the value of obj .
override unsafe int GetHashCode ()
Compute a hash code for the value.
override string ToString ()
Return a string representation of the value.
TypeCode GetTypeCode ()
Equivalent to type.
bool ToBoolean (IFormatProvider provider=null)
Convert the value to a boolean.
byte ToByte (IFormatProvider provider=null)
Convert the value to a byte.
char ToChar (IFormatProvider provider=null)
Convert the value to a char.
DateTime ToDateTime (IFormatProvider provider=null)
Not supported. Throws NotSupportedException.
decimal ToDecimal (IFormatProvider provider=null)
Convert the value to a decimal.
double ToDouble (IFormatProvider provider=null)
Convert the value to a double.
short ToInt16 (IFormatProvider provider=null)
Convert the value to a short.
int ToInt32 (IFormatProvider provider=null)
Convert the value to an int
long ToInt64 (IFormatProvider provider=null)
Convert the value to a long
sbyte ToSByte (IFormatProvider provider=null)
Convert the value to a sbyte.
float ToSingle (IFormatProvider provider=null)
Convert the value to a float.
string ToString (IFormatProvider provider)
Convert the value to a string.
object ToType (Type conversionType, IFormatProvider provider)
Not supported.
ushort ToUInt16 (IFormatProvider provider=null)
Convert the value to a ushort.
uint ToUInt32 (IFormatProvider provider=null)
Convert the value to a uint.
ulong ToUInt64 (IFormatProvider provider=null)
Convert the value to a ulong.
object ToObject ()
Return a boxed version of the value.
Static Public Member Functions
static bool operator== (PrimitiveValue left, PrimitiveValue right)
Compare two PrimitiveValues for equality.
static bool operator!= (PrimitiveValue left, PrimitiveValue right)
Compare two PrimitiveValues for inequality.
static PrimitiveValue FromString (string value)
Parse the given string into a PrimitiveValue.
static PrimitiveValue From< TValue > (TValue value)
Create a PrimitiveValue from the given "blittable"/struct value.
static PrimitiveValue FromObject (object value)
Create a PrimitiveValue from a boxed value.
static implicit operator PrimitiveValue (bool value)
Create a PrimitiveValue holding a bool.
static implicit operator PrimitiveValue (char value)
Create a PrimitiveValue holding a character.
static implicit operator PrimitiveValue (byte value)
Create a PrimitiveValue holding a byte.
static implicit operator PrimitiveValue (sbyte value)
Create a PrimitiveValue holding a signed byte.
static implicit operator PrimitiveValue (short value)
Create a PrimitiveValue holding a short.
static implicit operator PrimitiveValue (ushort value)
Create a PrimitiveValue holding an unsigned short.
static implicit operator PrimitiveValue (int value)
Create a PrimitiveValue holding an int.
static implicit operator PrimitiveValue (uint value)
Create a PrimitiveValue holding an unsigned int.
static implicit operator PrimitiveValue (long value)
Create a PrimitiveValue holding a long.
static implicit operator PrimitiveValue (ulong value)
Create a PrimitiveValue holding a ulong.
static implicit operator PrimitiveValue (float value)
Create a PrimitiveValue holding a float.
static implicit operator PrimitiveValue (double value)
Create a PrimitiveValue holding a double.
static PrimitiveValue FromBoolean (bool value)
static PrimitiveValue FromChar (char value)
static PrimitiveValue FromByte (byte value)
static PrimitiveValue FromSByte (sbyte value)
static PrimitiveValue FromInt16 (short value)
static PrimitiveValue FromUInt16 (ushort value)
static PrimitiveValue FromInt32 (int value)
static PrimitiveValue FromUInt32 (uint value)
static PrimitiveValue FromInt64 (long value)
static PrimitiveValue FromUInt64 (ulong value)
static PrimitiveValue FromSingle (float value)
static PrimitiveValue FromDouble (double value)
Properties
TypeCode type [get]
Type of value stored in the struct. TypeCode.Empty if the struct does not hold a value (i.e. has been default-initialized).
bool isEmpty [get]
If true, the struct does not contain a primitive value (i.e. has type TypeCode.Empty).
Detailed Description
A union holding a primitive value.
This structure is used for storing things such as default states for controls (see Layouts.InputControlLayout.ControlItem.defaultState). It can store one value of any primitive, non-reference C# type (bool, char, int, float, etc).
Constructor & Destructor Documentation
PrimitiveValue() [1/12]
UnityEngine.InputSystem.Utilities.PrimitiveValue.PrimitiveValue (bool value)
Create a PrimitiveValue holding a bool.
Parameters
value A boolean value.
Referenced by UnityEngine.InputSystem.Utilities.PrimitiveValue.ConvertTo(), UnityEngine.InputSystem.Utilities.PrimitiveValue.From< TValue >(), UnityEngine.InputSystem.Utilities.PrimitiveValue.FromBoolean(), UnityEngine.InputSystem.Utilities.PrimitiveValue.FromByte(), UnityEngine.InputSystem.Utilities.PrimitiveValue.FromChar(), UnityEngine.InputSystem.Utilities.PrimitiveValue.FromDouble(), UnityEngine.InputSystem.Utilities.PrimitiveValue.FromInt16(), UnityEngine.InputSystem.Utilities.PrimitiveValue.FromInt32(), UnityEngine.InputSystem.Utilities.PrimitiveValue.FromInt64(), UnityEngine.InputSystem.Utilities.PrimitiveValue.FromObject(), UnityEngine.InputSystem.Utilities.PrimitiveValue.FromSByte(), UnityEngine.InputSystem.Utilities.PrimitiveValue.FromSingle(), UnityEngine.InputSystem.Utilities.PrimitiveValue.FromString(), UnityEngine.InputSystem.Utilities.PrimitiveValue.FromUInt16(), UnityEngine.InputSystem.Utilities.PrimitiveValue.FromUInt32(), UnityEngine.InputSystem.Utilities.PrimitiveValue.FromUInt64(), UnityEngine.InputSystem.Utilities.PrimitiveValue.operator PrimitiveValue(), UnityEngine.InputSystem.Utilities.PrimitiveValue.operator PrimitiveValue(), UnityEngine.InputSystem.Utilities.PrimitiveValue.operator PrimitiveValue(), UnityEngine.InputSystem.Utilities.PrimitiveValue.operator PrimitiveValue(), UnityEngine.InputSystem.Utilities.PrimitiveValue.operator PrimitiveValue(), UnityEngine.InputSystem.Utilities.PrimitiveValue.operator PrimitiveValue(), UnityEngine.InputSystem.Utilities.PrimitiveValue.operator PrimitiveValue(), UnityEngine.InputSystem.Utilities.PrimitiveValue.operator PrimitiveValue(), UnityEngine.InputSystem.Utilities.PrimitiveValue.operator PrimitiveValue(), UnityEngine.InputSystem.Utilities.PrimitiveValue.operator PrimitiveValue(), UnityEngine.InputSystem.Utilities.PrimitiveValue.operator PrimitiveValue(), and UnityEngine.InputSystem.Utilities.PrimitiveValue.operator PrimitiveValue().
PrimitiveValue() [2/12]
UnityEngine.InputSystem.Utilities.PrimitiveValue.PrimitiveValue (char value)
Create a PrimitiveValue holding a character.
Parameters
value A character.
PrimitiveValue() [3/12]
UnityEngine.InputSystem.Utilities.PrimitiveValue.PrimitiveValue (byte value)
Create a PrimitiveValue holding a byte.
Parameters
value A byte value.
PrimitiveValue() [4/12]
UnityEngine.InputSystem.Utilities.PrimitiveValue.PrimitiveValue (sbyte value)
Create a PrimitiveValue holding a signed byte.
Parameters
value A signed byte value.
PrimitiveValue() [5/12]
UnityEngine.InputSystem.Utilities.PrimitiveValue.PrimitiveValue (short value)
Create a PrimitiveValue holding a short.
Parameters
value A short value.
PrimitiveValue() [6/12]
UnityEngine.InputSystem.Utilities.PrimitiveValue.PrimitiveValue (ushort value)
Create a PrimitiveValue holding an unsigned short.
Parameters
value An unsigned short value.
PrimitiveValue() [7/12]
UnityEngine.InputSystem.Utilities.PrimitiveValue.PrimitiveValue (int value)
Create a PrimitiveValue holding an int.
Parameters
value An int value.
PrimitiveValue() [8/12]
UnityEngine.InputSystem.Utilities.PrimitiveValue.PrimitiveValue (uint value)
Create a PrimitiveValue holding an unsigned int.
Parameters
value An unsigned int value.
PrimitiveValue() [9/12]
UnityEngine.InputSystem.Utilities.PrimitiveValue.PrimitiveValue (long value)
Create a PrimitiveValue holding a long.
Parameters
value A long value.
PrimitiveValue() [10/12]
UnityEngine.InputSystem.Utilities.PrimitiveValue.PrimitiveValue (ulong value)
Create a PrimitiveValue holding a ulong.
Parameters
value An unsigned long value.
PrimitiveValue() [11/12]
UnityEngine.InputSystem.Utilities.PrimitiveValue.PrimitiveValue (float value)
Create a PrimitiveValue holding a float.
Parameters
value A float value.
PrimitiveValue() [12/12]
UnityEngine.InputSystem.Utilities.PrimitiveValue.PrimitiveValue (double value)
Create a PrimitiveValue holding a double.
Parameters
value A double value.
Member Function Documentation
ConvertTo()
PrimitiveValue UnityEngine.InputSystem.Utilities.PrimitiveValue.ConvertTo (TypeCode type)
Convert to another type of value.
Parameters
type Type of value to convert to.
Returns
The converted value.
Exceptions
ArgumentException There is no conversion from the PrimitiveValue's current PrimitiveValue.type to type .
This method simply calls the other conversion methods (ToBoolean, ToChar, etc) based on the current type of value. ArgumentException is thrown if there is no conversion from the current to the requested type.
Every value can be converted to TypeCode.Empty.
See also
ToBoolean, ToChar, ToByte, ToSByte, ToInt16, ToInt32, ToInt64, ToUInt16, ToUInt32, ToUInt64, ToSingle, ToDouble
Referenced by UnityEngine.InputSystem.Utilities.NamedValue.ApplyToObject(), and UnityEngine.InputSystem.Utilities.NamedValue.ConvertTo().
Equals() [1/2]
override bool UnityEngine.InputSystem.Utilities.PrimitiveValue.Equals (object obj)
Compare this value to the value of obj .
Parameters
obj Either another PrimitiveValue or a boxed primitive value such as a byte, bool, etc.
Returns
True if the two values are equal.
If obj is a boxed primitive value, it is automatically converted to a PrimitiveValue.
Equals() [2/2]
unsafe bool UnityEngine.InputSystem.Utilities.PrimitiveValue.Equals (PrimitiveValue other)
Compare this value to other .
Parameters
other Another value.
Returns
True if the two values are equal.
Equality is based on type and contents. The types of both values must be identical and the memory contents of each value must be bit-wise identical (i.e. things such as floating-point epsilons are not taken into account).
Referenced by UnityEngine.InputSystem.Utilities.PrimitiveValue.operator!=(), and UnityEngine.InputSystem.Utilities.PrimitiveValue.operator==().
From< TValue >()
static PrimitiveValue UnityEngine.InputSystem.Utilities.PrimitiveValue.From< TValue > (TValue value) static
Create a PrimitiveValue from the given "blittable"/struct value.
Parameters
value A value.
Template Parameters
TValue Type of value to convert. Must be either an enum or one of the C# primitive value types (bool, int, float, etc.).
Returns
The PrimitiveValue converted from value . If it is an enum type, the PrimitiveValue will hold a value of the enum's underlying type (i.e. Type.GetEnumUnderlyingType).
Exceptions
ArgumentException No conversion exists from the given TValue type.
Type Constraints
TValue : struct
FromBoolean()
static PrimitiveValue UnityEngine.InputSystem.Utilities.PrimitiveValue.FromBoolean (bool value) static
FromByte()
static PrimitiveValue UnityEngine.InputSystem.Utilities.PrimitiveValue.FromByte (byte value) static
FromChar()
static PrimitiveValue UnityEngine.InputSystem.Utilities.PrimitiveValue.FromChar (char value) static
FromDouble()
static PrimitiveValue UnityEngine.InputSystem.Utilities.PrimitiveValue.FromDouble (double value) static
FromInt16()
static PrimitiveValue UnityEngine.InputSystem.Utilities.PrimitiveValue.FromInt16 (short value) static
FromInt32()
static PrimitiveValue UnityEngine.InputSystem.Utilities.PrimitiveValue.FromInt32 (int value) static
FromInt64()
static PrimitiveValue UnityEngine.InputSystem.Utilities.PrimitiveValue.FromInt64 (long value) static
FromObject()
static PrimitiveValue UnityEngine.InputSystem.Utilities.PrimitiveValue.FromObject (object value) static
Create a PrimitiveValue from a boxed value.
Parameters
value A value. If null, the result will be default(PrimitiveValue). If it is a string, FromString is used. Otherwise must be either an enum or one of the C# primitive value types (bool, int, float, etc.). If it is an enum type, the PrimitiveValue will hold a value of the enum's underlying type (i.e. Type.GetEnumUnderlyingType).
Exceptions
ArgumentException No conversion exists from the type of value .
Referenced by UnityEngine.InputSystem.Samples.VisualizationHelpers.TimelineVisualizer.AddSample(), and UnityEngine.InputSystem.Utilities.PrimitiveValue.Equals().
FromSByte()
static PrimitiveValue UnityEngine.InputSystem.Utilities.PrimitiveValue.FromSByte (sbyte value) static
FromSingle()
static PrimitiveValue UnityEngine.InputSystem.Utilities.PrimitiveValue.FromSingle (float value) static
FromString()
static PrimitiveValue UnityEngine.InputSystem.Utilities.PrimitiveValue.FromString (string value) static
Parse the given string into a PrimitiveValue.
Parameters
value A string containing a value.
Returns
The PrimitiveValue parsed from the string.
Integers are parsed as longs. Floating-point numbers are parsed as doubles. Hexadecimal notation is supported for integers.
See also
ToString()
Referenced by UnityEngine.InputSystem.Utilities.PrimitiveValue.FromObject().
FromUInt16()
static PrimitiveValue UnityEngine.InputSystem.Utilities.PrimitiveValue.FromUInt16 (ushort value) static
FromUInt32()
static PrimitiveValue UnityEngine.InputSystem.Utilities.PrimitiveValue.FromUInt32 (uint value) static
FromUInt64()
static PrimitiveValue UnityEngine.InputSystem.Utilities.PrimitiveValue.FromUInt64 (ulong value) static
GetHashCode()
override unsafe int UnityEngine.InputSystem.Utilities.PrimitiveValue.GetHashCode ()
Compute a hash code for the value.
Returns
A hash code.
Referenced by UnityEngine.InputSystem.Utilities.NamedValue.GetHashCode().
GetTypeCode()
TypeCode UnityEngine.InputSystem.Utilities.PrimitiveValue.GetTypeCode ()
Equivalent to type.
Returns
Type code for value stored in struct.
operator PrimitiveValue() [1/12]
static implicit UnityEngine.InputSystem.Utilities.PrimitiveValue.operator PrimitiveValue (bool value) static
Create a PrimitiveValue holding a bool.
Parameters
value A boolean value.
operator PrimitiveValue() [2/12]
static implicit UnityEngine.InputSystem.Utilities.PrimitiveValue.operator PrimitiveValue (byte value) static
Create a PrimitiveValue holding a byte.
Parameters
value A byte value.
operator PrimitiveValue() [3/12]
static implicit UnityEngine.InputSystem.Utilities.PrimitiveValue.operator PrimitiveValue (char value) static
Create a PrimitiveValue holding a character.
Parameters
value A character.
operator PrimitiveValue() [4/12]
static implicit UnityEngine.InputSystem.Utilities.PrimitiveValue.operator PrimitiveValue (double value) static
Create a PrimitiveValue holding a double.
Parameters
value A double value.
operator PrimitiveValue() [5/12]
static implicit UnityEngine.InputSystem.Utilities.PrimitiveValue.operator PrimitiveValue (float value) static
Create a PrimitiveValue holding a float.
Parameters
value A float value.
operator PrimitiveValue() [6/12]
static implicit UnityEngine.InputSystem.Utilities.PrimitiveValue.operator PrimitiveValue (int value) static
Create a PrimitiveValue holding an int.
Parameters
value An int value.
operator PrimitiveValue() [7/12]
static implicit UnityEngine.InputSystem.Utilities.PrimitiveValue.operator PrimitiveValue (long value) static
Create a PrimitiveValue holding a long.
Parameters
value A long value.
operator PrimitiveValue() [8/12]
static implicit UnityEngine.InputSystem.Utilities.PrimitiveValue.operator PrimitiveValue (sbyte value) static
Create a PrimitiveValue holding a signed byte.
Parameters
value A signed byte value.
operator PrimitiveValue() [9/12]
static implicit UnityEngine.InputSystem.Utilities.PrimitiveValue.operator PrimitiveValue (short value) static
Create a PrimitiveValue holding a short.
Parameters
value A short value.
operator PrimitiveValue() [10/12]
static implicit UnityEngine.InputSystem.Utilities.PrimitiveValue.operator PrimitiveValue (uint value) static
Create a PrimitiveValue holding an unsigned int.
Parameters
value An unsigned int value.
operator PrimitiveValue() [11/12]
static implicit UnityEngine.InputSystem.Utilities.PrimitiveValue.operator PrimitiveValue (ulong value) static
Create a PrimitiveValue holding a ulong.
Parameters
value An unsigned long value.
operator PrimitiveValue() [12/12]
static implicit UnityEngine.InputSystem.Utilities.PrimitiveValue.operator PrimitiveValue (ushort value) static
Create a PrimitiveValue holding an unsigned short.
Parameters
value An unsigned short value.
operator!=()
static bool UnityEngine.InputSystem.Utilities.PrimitiveValue.operator!= (PrimitiveValue left, PrimitiveValue right) static
Compare two PrimitiveValues for inequality.
Parameters
left First value.
right Second value.
Returns
True if the two values are not equal.
See also
Equals(PrimitiveValue)
operator==()
static bool UnityEngine.InputSystem.Utilities.PrimitiveValue.operator== (PrimitiveValue left, PrimitiveValue right) static
Compare two PrimitiveValues for equality.
Parameters
left First value.
right Second value.
Returns
True if the two values are equal.
See also
Equals(PrimitiveValue)
ToBoolean()
bool UnityEngine.InputSystem.Utilities.PrimitiveValue.ToBoolean (IFormatProvider provider = null)
Convert the value to a boolean.
Parameters
provider Ignored.
Returns
Converted boolean value.
Referenced by UnityEngine.InputSystem.Utilities.PrimitiveValue.ConvertTo(), and UnityEngine.InputSystem.LowLevel.InputStateBlock.Write().
ToByte()
byte UnityEngine.InputSystem.Utilities.PrimitiveValue.ToByte (IFormatProvider provider = null)
Convert the value to a byte.
Parameters
provider Ignored.
Returns
Converted byte value.
Referenced by UnityEngine.InputSystem.Utilities.PrimitiveValue.ConvertTo(), and UnityEngine.InputSystem.LowLevel.InputStateBlock.Write().
ToChar()
char UnityEngine.InputSystem.Utilities.PrimitiveValue.ToChar (IFormatProvider provider = null)
Convert the value to a char.
Parameters
provider Ignored.
Returns
Converted char value.
Referenced by UnityEngine.InputSystem.Utilities.PrimitiveValue.ConvertTo().
ToDateTime()
DateTime UnityEngine.InputSystem.Utilities.PrimitiveValue.ToDateTime (IFormatProvider provider = null)
Not supported. Throws NotSupportedException.
Parameters
provider Ignored.
Returns
Does not return.
Exceptions
NotSupportedException Always thrown.
ToDecimal()
decimal UnityEngine.InputSystem.Utilities.PrimitiveValue.ToDecimal (IFormatProvider provider = null)
Convert the value to a decimal.
Parameters
provider Ignored.
Returns
Value converted to decimal format.
ToDouble()
double UnityEngine.InputSystem.Utilities.PrimitiveValue.ToDouble (IFormatProvider provider = null)
Convert the value to a double.
Parameters
provider Ignored.
Returns
Converted double value.
Referenced by UnityEngine.InputSystem.Utilities.PrimitiveValue.ConvertTo(), UnityEngine.InputSystem.Utilities.PrimitiveValue.ToDecimal(), and UnityEngine.InputSystem.Utilities.PrimitiveValue.ToSingle().
ToInt16()
short UnityEngine.InputSystem.Utilities.PrimitiveValue.ToInt16 (IFormatProvider provider = null)
Convert the value to a short.
Parameters
provider Ignored.
Returns
Converted short value.
Referenced by UnityEngine.InputSystem.Utilities.PrimitiveValue.ConvertTo(), and UnityEngine.InputSystem.LowLevel.InputStateBlock.Write().
ToInt32()
int UnityEngine.InputSystem.Utilities.PrimitiveValue.ToInt32 (IFormatProvider provider = null)
Convert the value to an int
Parameters
provider Ignored.
Returns
Converted int value.
Referenced by UnityEngine.InputSystem.Utilities.PrimitiveValue.ConvertTo(), and UnityEngine.InputSystem.LowLevel.InputStateBlock.Write().
ToInt64()
long UnityEngine.InputSystem.Utilities.PrimitiveValue.ToInt64 (IFormatProvider provider = null)
Convert the value to a long
Parameters
provider Ignored.
Returns
Converted long value.
Referenced by UnityEngine.InputSystem.Utilities.PrimitiveValue.ConvertTo(), UnityEngine.InputSystem.Utilities.PrimitiveValue.ToByte(), UnityEngine.InputSystem.Utilities.PrimitiveValue.ToChar(), UnityEngine.InputSystem.Utilities.PrimitiveValue.ToInt16(), UnityEngine.InputSystem.Utilities.PrimitiveValue.ToInt32(), and UnityEngine.InputSystem.Utilities.PrimitiveValue.ToSByte().
ToObject()
object UnityEngine.InputSystem.Utilities.PrimitiveValue.ToObject ()
Return a boxed version of the value.
Returns
A boxed GC heap object.
This method always allocates GC heap memory.
Referenced by UnityEngine.InputSystem.Utilities.NamedValue.ApplyToObject().
ToSByte()
sbyte UnityEngine.InputSystem.Utilities.PrimitiveValue.ToSByte (IFormatProvider provider = null)
Convert the value to a sbyte.
Parameters
provider Ignored.
Returns
Converted sbyte value.
Referenced by UnityEngine.InputSystem.Utilities.PrimitiveValue.ConvertTo(), and UnityEngine.InputSystem.LowLevel.InputStateBlock.Write().
ToSingle()
float UnityEngine.InputSystem.Utilities.PrimitiveValue.ToSingle (IFormatProvider provider = null)
Convert the value to a float.
Parameters
provider Ignored.
Returns
Converted float value.
Referenced by UnityEngine.InputSystem.Utilities.PrimitiveValue.ConvertTo(), and UnityEngine.InputSystem.LowLevel.InputStateBlock.Write().
ToString() [1/2]
override string UnityEngine.InputSystem.Utilities.PrimitiveValue.ToString ()
Return a string representation of the value.
Returns
A string representation of the value.
String versions of PrimitiveValues are always culture invariant. This means that floating-point values, for example, will not the decimal separator of the current culture.
See also
FromString
Referenced by UnityEngine.InputSystem.Utilities.PrimitiveValue.ToString().
ToString() [2/2]
string UnityEngine.InputSystem.Utilities.PrimitiveValue.ToString (IFormatProvider provider)
Convert the value to a string.
Parameters
provider Ignored.
Returns
Converted string value.
Same as calling ToString().
ToType()
object UnityEngine.InputSystem.Utilities.PrimitiveValue.ToType (Type conversionType, IFormatProvider provider)
Not supported.
Parameters
conversionType Ignored.
provider Ignored.
Returns
Does not return.
Exceptions
NotSupportedException Always thrown.
ToUInt16()
ushort UnityEngine.InputSystem.Utilities.PrimitiveValue.ToUInt16 (IFormatProvider provider = null)
Convert the value to a ushort.
Parameters
provider Ignored.
Returns
Converted ushort value.
Referenced by UnityEngine.InputSystem.LowLevel.InputStateBlock.Write().
ToUInt32()
uint UnityEngine.InputSystem.Utilities.PrimitiveValue.ToUInt32 (IFormatProvider provider = null)
Convert the value to a uint.
Parameters
provider Ignored.
Returns
Converted uint value.
Referenced by UnityEngine.InputSystem.LowLevel.InputStateBlock.Write().
ToUInt64()
ulong UnityEngine.InputSystem.Utilities.PrimitiveValue.ToUInt64 (IFormatProvider provider = null)
Convert the value to a ulong.
Parameters
provider Ignored.
Returns
Converted ulong value.
Referenced by UnityEngine.InputSystem.Utilities.PrimitiveValue.ConvertTo(), UnityEngine.InputSystem.Utilities.PrimitiveValue.ToUInt16(), and UnityEngine.InputSystem.Utilities.PrimitiveValue.ToUInt32().
Property Documentation
isEmpty
bool UnityEngine.InputSystem.Utilities.PrimitiveValue.isEmpty get
If true, the struct does not contain a primitive value (i.e. has type TypeCode.Empty).
Whether the struct is holding a value or not.
Referenced by UnityEngine.InputSystem.Layouts.InputControlLayout.ControlItem.Merge().
type
TypeCode UnityEngine.InputSystem.Utilities.PrimitiveValue.type get
Type of value stored in the struct. TypeCode.Empty if the struct does not hold a value (i.e. has been default-initialized).
Type of value stored in the struct.
Referenced by UnityEngine.InputSystem.Utilities.PrimitiveValue.ConvertTo(), UnityEngine.InputSystem.Utilities.PrimitiveValue.From< TValue >(), UnityEngine.InputSystem.Utilities.PrimitiveValue.GetTypeCode(), UnityEngine.InputSystem.Utilities.PrimitiveValue.ToBoolean(), UnityEngine.InputSystem.Utilities.PrimitiveValue.ToChar(), UnityEngine.InputSystem.Utilities.PrimitiveValue.ToDouble(), UnityEngine.InputSystem.Utilities.PrimitiveValue.ToInt64(), UnityEngine.InputSystem.Utilities.PrimitiveValue.ToString(), and UnityEngine.InputSystem.Utilities.PrimitiveValue.ToUInt64().
The documentation for this struct was generated from the following file:
C:/Users/Lykos/Desktop/Projects/Capstone/VRGames/Library/PackageCache/com.unity.inputsystem@1.3.0/InputSystem/Utilities/PrimitiveValue.cs