VRGames: UnityEngine.XR.InteractionSubsystems.XRGestureSubsystemDescriptor.Cinfo Struct Reference
UnityEngine.XR.InteractionSubsystems.XRGestureSubsystemDescriptor.Cinfo Struct Reference
Used in conjunction with RegisterDescriptor(Cinfo) to register a provider. This should only be used by subsystem implementors.
Public Member Functions
override int GetHashCode ()
override bool Equals (object obj)
bool Equals (Cinfo other)
Static Public Member Functions
static bool operator== (Cinfo lhs, Cinfo rhs)
static bool operator!= (Cinfo lhs, Cinfo rhs)
Properties
string id [get, set]
The string used to identify this subsystem implementation. This will be available when enumerating the available descriptors at runtime.
Type subsystemImplementationType [get, set]
The Type of the implementation.
Detailed Description
Used in conjunction with RegisterDescriptor(Cinfo) to register a provider. This should only be used by subsystem implementors.
Member Function Documentation
Equals() [1/2]
bool UnityEngine.XR.InteractionSubsystems.XRGestureSubsystemDescriptor.Cinfo.Equals (Cinfo other)
Equals() [2/2]
override bool UnityEngine.XR.InteractionSubsystems.XRGestureSubsystemDescriptor.Cinfo.Equals (object obj)
Referenced by UnityEngine.XR.InteractionSubsystems.XRGestureSubsystemDescriptor.Cinfo.Equals(), UnityEngine.XR.InteractionSubsystems.XRGestureSubsystemDescriptor.Cinfo.operator!=(), and UnityEngine.XR.InteractionSubsystems.XRGestureSubsystemDescriptor.Cinfo.operator==().
GetHashCode()
override int UnityEngine.XR.InteractionSubsystems.XRGestureSubsystemDescriptor.Cinfo.GetHashCode ()
Referenced by UnityEngine.XR.InteractionSubsystems.XRGestureSubsystemDescriptor.Cinfo.GetHashCode().
operator!=()
static bool UnityEngine.XR.InteractionSubsystems.XRGestureSubsystemDescriptor.Cinfo.operator!= (Cinfo lhs, Cinfo rhs) static
operator==()
static bool UnityEngine.XR.InteractionSubsystems.XRGestureSubsystemDescriptor.Cinfo.operator== (Cinfo lhs, Cinfo rhs) static
Property Documentation
id
string UnityEngine.XR.InteractionSubsystems.XRGestureSubsystemDescriptor.Cinfo.id get set
The string used to identify this subsystem implementation. This will be available when enumerating the available descriptors at runtime.
Referenced by UnityEngine.XR.InteractionSubsystems.XRGestureSubsystemDescriptor.Cinfo.Equals().
subsystemImplementationType
Type UnityEngine.XR.InteractionSubsystems.XRGestureSubsystemDescriptor.Cinfo.subsystemImplementationType get set
The Type of the implementation.
Referenced by UnityEngine.XR.InteractionSubsystems.XRGestureSubsystemDescriptor.Cinfo.Equals(), and UnityEngine.XR.InteractionSubsystems.XRGestureSubsystemDescriptor.Cinfo.GetHashCode().
The documentation for this struct was generated from the following file:
C:/Users/Lykos/Desktop/Projects/Capstone/VRGames/Library/PackageCache/com.unity.xr.interactionsubsystems@1.0.1/Runtime/GestureSubsystem/XRGestureSubsystemDescriptor.cs