VRGames: UnityEditor.Timeline.TimelineAnimationUtilities.RigidTransform Struct Reference
UnityEditor.Timeline.TimelineAnimationUtilities.RigidTransform Struct Reference
Static Public Member Functions
static RigidTransform Compose (Vector3 pos, Quaternion rot)
static RigidTransform Mul (RigidTransform a, RigidTransform b)
static RigidTransform Inverse (RigidTransform a)
Public Attributes
Vector3 position
Quaternion rotation
Properties
static RigidTransform identity [get]
Member Function Documentation
Compose()
static RigidTransform UnityEditor.Timeline.TimelineAnimationUtilities.RigidTransform.Compose (Vector3 pos, Quaternion rot) static
Referenced by UnityEditor.Timeline.TimelineAnimationUtilities.GetTrackOffsets(), and UnityEditor.Timeline.TimelineAnimationUtilities.UpdateClipOffsets().
Inverse()
static RigidTransform UnityEditor.Timeline.TimelineAnimationUtilities.RigidTransform.Inverse (RigidTransform a) static
Referenced by UnityEditor.Timeline.TimelineAnimationUtilities.RigidTransform.Inverse().
Mul()
static RigidTransform UnityEditor.Timeline.TimelineAnimationUtilities.RigidTransform.Mul (RigidTransform a, RigidTransform b) static
Member Data Documentation
position
Vector3 UnityEditor.Timeline.TimelineAnimationUtilities.RigidTransform.position
Referenced by UnityEditor.Timeline.TimelineAnimationUtilities.RigidTransform.Inverse(), UnityEditor.Timeline.TimelineAnimationUtilities.RigidTransform.Mul(), and UnityEditor.Timeline.TimelineAnimationUtilities.UpdateTrackOffset().
rotation
Quaternion UnityEditor.Timeline.TimelineAnimationUtilities.RigidTransform.rotation
Referenced by UnityEditor.Timeline.TimelineAnimationUtilities.RigidTransform.Inverse(), UnityEditor.Timeline.TimelineAnimationUtilities.RigidTransform.Mul(), and UnityEditor.Timeline.TimelineAnimationUtilities.UpdateTrackOffset().
Property Documentation
identity
RigidTransform UnityEditor.Timeline.TimelineAnimationUtilities.RigidTransform.identity static get
The documentation for this struct was generated from the following file:
C:/Users/Lykos/Desktop/Projects/Capstone/VRGames/Library/PackageCache/com.unity.timeline@1.6.4/Editor/Animation/TimelineAnimationUtilities.cs