VRGames: UnityEngine.InputSystem.InputActionSetupExtensions.ControlSchemeSyntax Struct Reference
UnityEngine.InputSystem.InputActionSetupExtensions.ControlSchemeSyntax Struct Reference
Public Member Functions
ControlSchemeSyntax WithBindingGroup (string bindingGroup)
ControlSchemeSyntax WithRequiredDevice< TDevice > ()
ControlSchemeSyntax WithOptionalDevice< TDevice > ()
ControlSchemeSyntax OrWithRequiredDevice< TDevice > ()
ControlSchemeSyntax OrWithOptionalDevice< TDevice > ()
ControlSchemeSyntax WithRequiredDevice (string controlPath)
ControlSchemeSyntax WithOptionalDevice (string controlPath)
ControlSchemeSyntax OrWithRequiredDevice (string controlPath)
ControlSchemeSyntax OrWithOptionalDevice (string controlPath)
InputControlScheme Done ()
Member Function Documentation
Done()
InputControlScheme UnityEngine.InputSystem.InputActionSetupExtensions.ControlSchemeSyntax.Done ()
OrWithOptionalDevice()
ControlSchemeSyntax UnityEngine.InputSystem.InputActionSetupExtensions.ControlSchemeSyntax.OrWithOptionalDevice (string controlPath)
OrWithOptionalDevice< TDevice >()
ControlSchemeSyntax UnityEngine.InputSystem.InputActionSetupExtensions.ControlSchemeSyntax.OrWithOptionalDevice< TDevice > ()
Type Constraints
TDevice : InputDevice
OrWithRequiredDevice()
ControlSchemeSyntax UnityEngine.InputSystem.InputActionSetupExtensions.ControlSchemeSyntax.OrWithRequiredDevice (string controlPath)
OrWithRequiredDevice< TDevice >()
ControlSchemeSyntax UnityEngine.InputSystem.InputActionSetupExtensions.ControlSchemeSyntax.OrWithRequiredDevice< TDevice > ()
Type Constraints
TDevice : InputDevice
WithBindingGroup()
ControlSchemeSyntax UnityEngine.InputSystem.InputActionSetupExtensions.ControlSchemeSyntax.WithBindingGroup (string bindingGroup)
WithOptionalDevice()
ControlSchemeSyntax UnityEngine.InputSystem.InputActionSetupExtensions.ControlSchemeSyntax.WithOptionalDevice (string controlPath)
Referenced by UnityEngine.InputSystem.InputActionSetupExtensions.ControlSchemeSyntax.OrWithOptionalDevice< TDevice >(), and UnityEngine.InputSystem.InputActionSetupExtensions.ControlSchemeSyntax.WithOptionalDevice< TDevice >().
WithOptionalDevice< TDevice >()
ControlSchemeSyntax UnityEngine.InputSystem.InputActionSetupExtensions.ControlSchemeSyntax.WithOptionalDevice< TDevice > ()
Type Constraints
TDevice : InputDevice
WithRequiredDevice()
ControlSchemeSyntax UnityEngine.InputSystem.InputActionSetupExtensions.ControlSchemeSyntax.WithRequiredDevice (string controlPath)
Referenced by UnityEngine.InputSystem.InputActionSetupExtensions.ControlSchemeSyntax.OrWithRequiredDevice< TDevice >(), and UnityEngine.InputSystem.InputActionSetupExtensions.ControlSchemeSyntax.WithRequiredDevice< TDevice >().
WithRequiredDevice< TDevice >()
ControlSchemeSyntax UnityEngine.InputSystem.InputActionSetupExtensions.ControlSchemeSyntax.WithRequiredDevice< TDevice > ()
Type Constraints
TDevice : InputDevice
The documentation for this struct was generated from the following file:
C:/Users/Lykos/Desktop/Projects/Capstone/VRGames/Library/PackageCache/com.unity.inputsystem@1.3.0/InputSystem/Actions/InputActionSetupExtensions.cs