VRGames: Windows.Kinect.ColorSpacePoint Struct Reference
Windows.Kinect.ColorSpacePoint Struct Reference
Public Member Functions
override int GetHashCode ()
override bool Equals (object obj)
bool Equals (ColorSpacePoint obj)
Static Public Member Functions
static bool operator== (ColorSpacePoint a, ColorSpacePoint b)
static bool operator!= (ColorSpacePoint a, ColorSpacePoint b)
Properties
float X [get, set]
float Y [get, set]
Member Function Documentation
Equals() [1/2]
bool Windows.Kinect.ColorSpacePoint.Equals (ColorSpacePoint obj)
Equals() [2/2]
override bool Windows.Kinect.ColorSpacePoint.Equals (object obj)
Referenced by Windows.Kinect.ColorSpacePoint.Equals(), Windows.Kinect.ColorSpacePoint.operator!=(), and Windows.Kinect.ColorSpacePoint.operator==().
GetHashCode()
override int Windows.Kinect.ColorSpacePoint.GetHashCode ()
operator!=()
static bool Windows.Kinect.ColorSpacePoint.operator!= (ColorSpacePoint a, ColorSpacePoint b) static
operator==()
static bool Windows.Kinect.ColorSpacePoint.operator== (ColorSpacePoint a, ColorSpacePoint b) static
Property Documentation
X
float Windows.Kinect.ColorSpacePoint.X get set
Referenced by Windows.Kinect.PointF.Equals(), Windows.Kinect.ColorSpacePoint.Equals(), and Windows.Kinect.ColorSpacePoint.GetHashCode().
Y
float Windows.Kinect.ColorSpacePoint.Y get set
Referenced by Windows.Kinect.PointF.Equals(), Windows.Kinect.ColorSpacePoint.Equals(), and Windows.Kinect.ColorSpacePoint.GetHashCode().
The documentation for this struct was generated from the following file:
C:/Users/Lykos/Desktop/Projects/Capstone/VRGames/Assets/ThirdParty/Standard Assets/Windows/Kinect/ColorSpacePoint.cs