VRGames: UnityEngine.InputSystem.LowLevel.InputStateBlock Struct Reference
UnityEngine.InputSystem.LowLevel.InputStateBlock Struct Reference
Information about a memory region storing input state.
Public Member Functions
int ReadInt (void *statePtr)
void WriteInt (void *statePtr, int value)
float ReadFloat (void *statePtr)
void WriteFloat (void *statePtr, float value)
double ReadDouble (void *statePtr)
void WriteDouble (void *statePtr, double value)
void Write (void *statePtr, PrimitiveValue value)
void CopyToFrom (void *toStatePtr, void *fromStatePtr)
Static Public Member Functions
static int GetSizeOfPrimitiveFormatInBits (FourCC type)
static FourCC GetPrimitiveFormatFromType (Type type)
Static Public Attributes
const uint InvalidOffset = 0xffffffff
const uint AutomaticOffset = 0xfffffffe
static readonly FourCC FormatBit = new FourCC('B', 'I', 'T')
Format code for a variable-width bitfield representing an unsigned value, i.e. all bits including the highest one represent the magnitude of the value.
static readonly FourCC FormatSBit = new FourCC('S', 'B', 'I', 'T')
Format code for a variable-width bitfield representing a signed value, i.e. the highest bit is used as a sign bit (0=unsigned, 1=signed) and the remaining bits represent the magnitude of the value.
static readonly FourCC FormatInt = new FourCC('I', 'N', 'T')
Format code for a 32-bit signed integer value.
static readonly FourCC FormatUInt = new FourCC('U', 'I', 'N', 'T')
Format code for a 32-bit unsigned integer value.
static readonly FourCC FormatShort = new FourCC('S', 'H', 'R', 'T')
Format code for a 16-bit signed integer value.
static readonly FourCC FormatUShort = new FourCC('U', 'S', 'H', 'T')
Format code for a 16-bit unsigned integer value.
static readonly FourCC FormatByte = new FourCC('B', 'Y', 'T', 'E')
Format code for an 8-bit unsigned integer value.
static readonly FourCC FormatSByte = new FourCC('S', 'B', 'Y', 'T')
Format code for an 8-bit signed integer value.
static readonly FourCC FormatLong = new FourCC('L', 'N', 'G')
Format code for a 64-bit signed integer value.
static readonly FourCC FormatULong = new FourCC('U', 'L', 'N', 'G')
Format code for a 64-bit unsigned integer value.
static readonly FourCC FormatFloat = new FourCC('F', 'L', 'T')
Format code for a 32-bit floating-point value.
static readonly FourCC FormatDouble = new FourCC('D', 'B', 'L')
Format code for a 64-bit floating-point value.
static readonly FourCC FormatVector2 = new FourCC('V', 'E', 'C', '2')
static readonly FourCC FormatVector3 = new FourCC('V', 'E', 'C', '3')
static readonly FourCC FormatQuaternion = new FourCC('Q', 'U', 'A', 'T')
static readonly FourCC FormatVector2Short = new FourCC('V', 'C', '2', 'S')
static readonly FourCC FormatVector3Short = new FourCC('V', 'C', '3', 'S')
static readonly FourCC FormatVector2Byte = new FourCC('V', 'C', '2', 'B')
static readonly FourCC FormatVector3Byte = new FourCC('V', 'C', '3', 'B')
Properties
FourCC format [get, set]
Type identifier for the memory layout used by the state.
uint byteOffset [get, set]
uint bitOffset [get, set]
uint sizeInBits [get, set]
Detailed Description
Information about a memory region storing input state.
Input state is kept in raw memory blocks. All state is centrally managed by the input system; controls cannot keep their own independent state.
Each state block is tagged with a format code indicating the storage format used for the memory block. This can either be one out of a set of primitive formats (such as "INT") or a custom format code indicating a more complex format.
Memory using primitive formats can be converted to and from primitive values directly by this struct.
State memory is bit-addressable, meaning that it can be offset from a byte address in bits (bitOffset) and is sized in bits instead of bytes (sizeInBits). However, in practice, bit-addressing memory reads and writes are only supported on the bitfield primitive format.
Input state memory is restricted to a maximum of 4GB in size. Offsets are recorded in 32 bits.
See also
InputControl.stateBlock
Member Function Documentation
CopyToFrom()
void UnityEngine.InputSystem.LowLevel.InputStateBlock.CopyToFrom (void * toStatePtr, void * fromStatePtr)
GetPrimitiveFormatFromType()
static FourCC UnityEngine.InputSystem.LowLevel.InputStateBlock.GetPrimitiveFormatFromType (Type type) static
GetSizeOfPrimitiveFormatInBits()
static int UnityEngine.InputSystem.LowLevel.InputStateBlock.GetSizeOfPrimitiveFormatInBits (FourCC type) static
ReadDouble()
double UnityEngine.InputSystem.LowLevel.InputStateBlock.ReadDouble (void * statePtr)
Referenced by UnityEngine.InputSystem.Controls.DoubleControl.ReadUnprocessedValueFromState().
ReadFloat()
float UnityEngine.InputSystem.LowLevel.InputStateBlock.ReadFloat (void * statePtr)
Referenced by UnityEngine.InputSystem.Controls.AxisControl.ReadUnprocessedValueFromState().
ReadInt()
int UnityEngine.InputSystem.LowLevel.InputStateBlock.ReadInt (void * statePtr)
Referenced by UnityEngine.InputSystem.Controls.IntegerControl.ReadUnprocessedValueFromState(), and UnityEngine.InputSystem.Controls.TouchPhaseControl.ReadUnprocessedValueFromState().
Write()
void UnityEngine.InputSystem.LowLevel.InputStateBlock.Write (void * statePtr, PrimitiveValue value)
WriteDouble()
void UnityEngine.InputSystem.LowLevel.InputStateBlock.WriteDouble (void * statePtr, double value)
Referenced by UnityEngine.InputSystem.Controls.DoubleControl.WriteValueIntoState().
WriteFloat()
void UnityEngine.InputSystem.LowLevel.InputStateBlock.WriteFloat (void * statePtr, float value)
Referenced by UnityEngine.InputSystem.Controls.AxisControl.WriteValueIntoState().
WriteInt()
void UnityEngine.InputSystem.LowLevel.InputStateBlock.WriteInt (void * statePtr, int value)
Referenced by UnityEngine.InputSystem.Controls.IntegerControl.WriteValueIntoState().
Member Data Documentation
AutomaticOffset
const uint UnityEngine.InputSystem.LowLevel.InputStateBlock.AutomaticOffset = 0xfffffffe static
Referenced by UnityEngine.InputSystem.InputControl< TValue >.InputControl().
FormatBit
readonly FourCC UnityEngine.InputSystem.LowLevel.InputStateBlock.FormatBit = new FourCC('B', 'I', 'T') static
Format code for a variable-width bitfield representing an unsigned value, i.e. all bits including the highest one represent the magnitude of the value.
See also
format
Referenced by UnityEngine.InputSystem.Controls.AnyKeyControl.AnyKeyControl(), UnityEngine.InputSystem.Controls.ButtonControl.ButtonControl(), UnityEngine.InputSystem.Controls.DpadControl.DpadControl(), and UnityEngine.InputSystem.LowLevel.InputStateBlock.GetSizeOfPrimitiveFormatInBits().
FormatByte
readonly FourCC UnityEngine.InputSystem.LowLevel.InputStateBlock.FormatByte = new FourCC('B', 'Y', 'T', 'E') static
Format code for an 8-bit unsigned integer value.
See also
format
Referenced by UnityEngine.InputSystem.LowLevel.InputStateBlock.GetPrimitiveFormatFromType(), and UnityEngine.InputSystem.LowLevel.InputStateBlock.GetSizeOfPrimitiveFormatInBits().
FormatDouble
readonly FourCC UnityEngine.InputSystem.LowLevel.InputStateBlock.FormatDouble = new FourCC('D', 'B', 'L') static
Format code for a 64-bit floating-point value.
See also
format
Referenced by UnityEngine.InputSystem.Controls.DoubleControl.DoubleControl(), UnityEngine.InputSystem.LowLevel.InputStateBlock.GetPrimitiveFormatFromType(), and UnityEngine.InputSystem.LowLevel.InputStateBlock.GetSizeOfPrimitiveFormatInBits().
FormatFloat
readonly FourCC UnityEngine.InputSystem.LowLevel.InputStateBlock.FormatFloat = new FourCC('F', 'L', 'T') static
Format code for a 32-bit floating-point value.
See also
format
Referenced by UnityEngine.InputSystem.Controls.AxisControl.AxisControl(), UnityEngine.InputSystem.LowLevel.InputStateBlock.GetPrimitiveFormatFromType(), and UnityEngine.InputSystem.LowLevel.InputStateBlock.GetSizeOfPrimitiveFormatInBits().
FormatInt
readonly FourCC UnityEngine.InputSystem.LowLevel.InputStateBlock.FormatInt = new FourCC('I', 'N', 'T') static
Format code for a 32-bit signed integer value.
See also
format
Referenced by UnityEngine.InputSystem.LowLevel.InputStateBlock.GetPrimitiveFormatFromType(), UnityEngine.InputSystem.LowLevel.InputStateBlock.GetSizeOfPrimitiveFormatInBits(), UnityEngine.InputSystem.Controls.IntegerControl.IntegerControl(), and UnityEngine.InputSystem.Controls.TouchPhaseControl.TouchPhaseControl().
FormatLong
readonly FourCC UnityEngine.InputSystem.LowLevel.InputStateBlock.FormatLong = new FourCC('L', 'N', 'G') static
Format code for a 64-bit signed integer value.
See also
format
Referenced by UnityEngine.InputSystem.LowLevel.InputStateBlock.GetPrimitiveFormatFromType(), and UnityEngine.InputSystem.LowLevel.InputStateBlock.GetSizeOfPrimitiveFormatInBits().
FormatQuaternion
readonly FourCC UnityEngine.InputSystem.LowLevel.InputStateBlock.FormatQuaternion = new FourCC('Q', 'U', 'A', 'T') static
Referenced by UnityEngine.InputSystem.LowLevel.InputStateBlock.GetPrimitiveFormatFromType(), UnityEngine.InputSystem.LowLevel.InputStateBlock.GetSizeOfPrimitiveFormatInBits(), and UnityEngine.InputSystem.Controls.QuaternionControl.QuaternionControl().
FormatSBit
readonly FourCC UnityEngine.InputSystem.LowLevel.InputStateBlock.FormatSBit = new FourCC('S', 'B', 'I', 'T') static
Format code for a variable-width bitfield representing a signed value, i.e. the highest bit is used as a sign bit (0=unsigned, 1=signed) and the remaining bits represent the magnitude of the value.
See also
format
Referenced by UnityEngine.InputSystem.LowLevel.InputStateBlock.GetSizeOfPrimitiveFormatInBits().
FormatSByte
readonly FourCC UnityEngine.InputSystem.LowLevel.InputStateBlock.FormatSByte = new FourCC('S', 'B', 'Y', 'T') static
Format code for an 8-bit signed integer value.
See also
format
Referenced by UnityEngine.InputSystem.LowLevel.InputStateBlock.GetPrimitiveFormatFromType(), and UnityEngine.InputSystem.LowLevel.InputStateBlock.GetSizeOfPrimitiveFormatInBits().
FormatShort
readonly FourCC UnityEngine.InputSystem.LowLevel.InputStateBlock.FormatShort = new FourCC('S', 'H', 'R', 'T') static
Format code for a 16-bit signed integer value.
See also
format
Referenced by UnityEngine.InputSystem.LowLevel.InputStateBlock.GetPrimitiveFormatFromType(), and UnityEngine.InputSystem.LowLevel.InputStateBlock.GetSizeOfPrimitiveFormatInBits().
FormatUInt
readonly FourCC UnityEngine.InputSystem.LowLevel.InputStateBlock.FormatUInt = new FourCC('U', 'I', 'N', 'T') static
Format code for a 32-bit unsigned integer value.
See also
format
Referenced by UnityEngine.InputSystem.LowLevel.InputStateBlock.GetPrimitiveFormatFromType(), and UnityEngine.InputSystem.LowLevel.InputStateBlock.GetSizeOfPrimitiveFormatInBits().
FormatULong
readonly FourCC UnityEngine.InputSystem.LowLevel.InputStateBlock.FormatULong = new FourCC('U', 'L', 'N', 'G') static
Format code for a 64-bit unsigned integer value.
See also
format
Referenced by UnityEngine.InputSystem.LowLevel.InputStateBlock.GetPrimitiveFormatFromType(), and UnityEngine.InputSystem.LowLevel.InputStateBlock.GetSizeOfPrimitiveFormatInBits().
FormatUShort
readonly FourCC UnityEngine.InputSystem.LowLevel.InputStateBlock.FormatUShort = new FourCC('U', 'S', 'H', 'T') static
Format code for a 16-bit unsigned integer value.
See also
format
Referenced by UnityEngine.InputSystem.LowLevel.InputStateBlock.GetPrimitiveFormatFromType(), and UnityEngine.InputSystem.LowLevel.InputStateBlock.GetSizeOfPrimitiveFormatInBits().
FormatVector2
readonly FourCC UnityEngine.InputSystem.LowLevel.InputStateBlock.FormatVector2 = new FourCC('V', 'E', 'C', '2') static
Referenced by UnityEngine.InputSystem.LowLevel.InputStateBlock.GetPrimitiveFormatFromType(), UnityEngine.InputSystem.LowLevel.InputStateBlock.GetSizeOfPrimitiveFormatInBits(), and UnityEngine.InputSystem.Controls.Vector2Control.Vector2Control().
FormatVector2Byte
readonly FourCC UnityEngine.InputSystem.LowLevel.InputStateBlock.FormatVector2Byte = new FourCC('V', 'C', '2', 'B') static
Referenced by UnityEngine.InputSystem.LowLevel.InputStateBlock.GetSizeOfPrimitiveFormatInBits().
FormatVector2Short
readonly FourCC UnityEngine.InputSystem.LowLevel.InputStateBlock.FormatVector2Short = new FourCC('V', 'C', '2', 'S') static
Referenced by UnityEngine.InputSystem.LowLevel.InputStateBlock.GetSizeOfPrimitiveFormatInBits().
FormatVector3
readonly FourCC UnityEngine.InputSystem.LowLevel.InputStateBlock.FormatVector3 = new FourCC('V', 'E', 'C', '3') static
Referenced by UnityEngine.InputSystem.LowLevel.InputStateBlock.GetPrimitiveFormatFromType(), UnityEngine.InputSystem.LowLevel.InputStateBlock.GetSizeOfPrimitiveFormatInBits(), and UnityEngine.InputSystem.Controls.Vector3Control.Vector3Control().
FormatVector3Byte
readonly FourCC UnityEngine.InputSystem.LowLevel.InputStateBlock.FormatVector3Byte = new FourCC('V', 'C', '3', 'B') static
Referenced by UnityEngine.InputSystem.LowLevel.InputStateBlock.GetSizeOfPrimitiveFormatInBits().
FormatVector3Short
readonly FourCC UnityEngine.InputSystem.LowLevel.InputStateBlock.FormatVector3Short = new FourCC('V', 'C', '3', 'S') static
Referenced by UnityEngine.InputSystem.LowLevel.InputStateBlock.GetSizeOfPrimitiveFormatInBits().
InvalidOffset
const uint UnityEngine.InputSystem.LowLevel.InputStateBlock.InvalidOffset = 0xffffffff static
Referenced by UnityEngine.InputSystem.Layouts.InputControlLayout.Builder.AddControl(), and UnityEngine.InputSystem.Layouts.InputControlLayout.ControlItem.Merge().
Property Documentation
bitOffset
uint UnityEngine.InputSystem.LowLevel.InputStateBlock.bitOffset get set
Referenced by UnityEngine.InputSystem.LowLevel.InputStateBlock.CopyToFrom(), UnityEngine.InputSystem.LowLevel.InputStateBlock.ReadDouble(), UnityEngine.InputSystem.LowLevel.InputStateBlock.ReadFloat(), UnityEngine.InputSystem.LowLevel.InputStateBlock.ReadInt(), UnityEngine.InputSystem.Controls.DiscreteButtonControl.ReadUnprocessedValueFromState(), UnityEngine.InputSystem.Controls.TouchPressControl.ReadUnprocessedValueFromState(), UnityEngine.InputSystem.LowLevel.InputStateBlock.Write(), UnityEngine.InputSystem.LowLevel.InputStateBlock.WriteDouble(), UnityEngine.InputSystem.LowLevel.InputStateBlock.WriteFloat(), UnityEngine.InputSystem.LowLevel.InputStateBlock.WriteInt(), and UnityEngine.InputSystem.Controls.DiscreteButtonControl.WriteValueIntoState().
byteOffset
uint UnityEngine.InputSystem.LowLevel.InputStateBlock.byteOffset get set
Referenced by UnityEngine.InputSystem.InputDevice.CompareValue(), UnityEngine.InputSystem.LowLevel.InputStateBlock.CopyToFrom(), UnityEngine.InputSystem.InputControlExtensions.InputEventControlEnumerator.MoveNext(), UnityEngine.InputSystem.Touchscreen.OnNextUpdate(), UnityEngine.InputSystem.Touchscreen.OnStateEvent(), UnityEngine.InputSystem.LowLevel.InputStateBlock.ReadDouble(), UnityEngine.InputSystem.LowLevel.InputStateBlock.ReadFloat(), UnityEngine.InputSystem.LowLevel.InputStateBlock.ReadInt(), UnityEngine.InputSystem.Controls.DiscreteButtonControl.ReadUnprocessedValueFromState(), UnityEngine.InputSystem.Controls.TouchControl.ReadUnprocessedValueFromState(), UnityEngine.InputSystem.Controls.TouchPressControl.ReadUnprocessedValueFromState(), UnityEngine.InputSystem.InputDevice.ReadValueFromStateAsObject(), UnityEngine.InputSystem.InputDevice.ReadValueFromStateIntoBuffer(), UnityEngine.InputSystem.LowLevel.InputStateHistory< TValue >.RecordStateChange(), UnityEngine.InputSystem.LowLevel.InputStateHistory< TValue >.RecordStateChange(), UnityEngine.InputSystem.LowLevel.InputStateHistory< TValue >.RecordStateChange(), UnityEngine.InputSystem.LowLevel.InputStateBlock.Write(), UnityEngine.InputSystem.LowLevel.InputStateBlock.WriteDouble(), UnityEngine.InputSystem.LowLevel.InputStateBlock.WriteFloat(), UnityEngine.InputSystem.LowLevel.InputStateBlock.WriteInt(), UnityEngine.InputSystem.Controls.DiscreteButtonControl.WriteValueIntoState(), UnityEngine.InputSystem.Controls.TouchPhaseControl.WriteValueIntoState(), and UnityEngine.InputSystem.Controls.TouchControl.WriteValueIntoState().
format
FourCC UnityEngine.InputSystem.LowLevel.InputStateBlock.format get set
Type identifier for the memory layout used by the state.
Used for safety checks to make sure that when the system copies state memory, it copies between compatible layouts. If set to a primitive state format, also used to determine the size of the state block.
Referenced by UnityEngine.InputSystem.Controls.DiscreteButtonControl.FinishSetup(), UnityEngine.InputSystem.Controls.TouchPressControl.FinishSetup(), UnityEngine.InputSystem.LowLevel.InputStateBlock.ReadDouble(), UnityEngine.InputSystem.LowLevel.InputStateBlock.ReadFloat(), UnityEngine.InputSystem.LowLevel.InputStateBlock.ReadInt(), UnityEngine.InputSystem.LowLevel.InputStateBlock.Write(), UnityEngine.InputSystem.LowLevel.InputStateBlock.WriteDouble(), UnityEngine.InputSystem.LowLevel.InputStateBlock.WriteFloat(), and UnityEngine.InputSystem.LowLevel.InputStateBlock.WriteInt().
sizeInBits
uint UnityEngine.InputSystem.LowLevel.InputStateBlock.sizeInBits get set
Referenced by UnityEngine.InputSystem.LowLevel.InputStateBlock.CopyToFrom(), UnityEngine.InputSystem.LowLevel.InputStateBlock.ReadDouble(), UnityEngine.InputSystem.LowLevel.InputStateBlock.ReadFloat(), UnityEngine.InputSystem.LowLevel.InputStateBlock.ReadInt(), UnityEngine.InputSystem.Controls.DiscreteButtonControl.ReadUnprocessedValueFromState(), UnityEngine.InputSystem.Controls.TouchPressControl.ReadUnprocessedValueFromState(), UnityEngine.InputSystem.LowLevel.InputStateBlock.Write(), UnityEngine.InputSystem.LowLevel.InputStateBlock.WriteDouble(), UnityEngine.InputSystem.LowLevel.InputStateBlock.WriteFloat(), UnityEngine.InputSystem.LowLevel.InputStateBlock.WriteInt(), and UnityEngine.InputSystem.Controls.DiscreteButtonControl.WriteValueIntoState().
The documentation for this struct was generated from the following file:
C:/Users/Lykos/Desktop/Projects/Capstone/VRGames/Library/PackageCache/com.unity.inputsystem@1.3.0/InputSystem/State/InputStateBlock.cs